import assert from 'node:assert/strict';import fs from 'node:fs';
import {games} from '../registry.js';import {Session,neutral,random} from '../core.js';
function finite(value,label='value',seen=new Set()){if(typeof value==='number')assert.ok(Number.isFinite(value),label+' finite');else if(value&&typeof value==='object'&&!seen.has(value)){seen.add(value);for(const[k,v]of Object.entries(value))finite(v,label+'.'+k,seen);}}
let calls=0;const gradient={addColorStop(...args){finite(args);}},context=new Proxy({measureText:s=>({width:String(s).length*12}),createLinearGradient:()=>gradient,createRadialGradient:()=>gradient,canvas:{width:900,height:600}},{get(o,k){return k in o?o[k]:(...args)=>{calls++;finite(args,'draw.'+String(k));};},set(o,k,v){finite(v,'ctx.'+String(k));o[k]=v;return true;}});
const rows=[],issues=[];assert.equal(games.length,36);assert.equal(new Set(games.map(g=>g.id)).size,36);
for(const g of games){assert.ok(g.name&&g.description&&g.controls&&g.objective&&g.inspiration&&g.adaptation,g.id+' metadata');assert.ok(new URL(g.sourceUrl).protocol==='https:',g.id+' source');assert.equal(g.medal.length,3);assert.ok(g.medal.every(Number.isFinite)&&g.medal[0]<g.medal[1]&&g.medal[1]<g.medal[2],g.id+' medals');
for(const seed of[17,93,2026])for(const mode of['bot','idle','varied']){try{const s=new Session(g,{seed}),rng=random(seed*3+11);s.step(0,neutral());finite(s.game.snapshot?.());s.game.draw(context);const max=(mode==='bot'?300:120)*60;for(let frame=0;frame<max&&!s.result;frame++){let raw=mode==='bot'?s.game.bot():neutral();if(mode==='varied'){const cycle=frame%90;raw={x:cycle<30?-1:cycle<60?1:0,y:Math.floor(frame/70)%3-1,a:frame%23<8,b:frame%53<6,pointer:{x:80+rng()*740,y:100+rng()*420,down:frame%37<9,valid:frame%180<90}};}s.step(1/60,raw);if(frame%30===0){finite(s.game.snapshot?.());finite(s.hud());s.game.draw(context);}}if(mode==='bot')assert.ok(s.result,g.id+' bot must finish through normal input');finite(s.result);const row={id:g.id,seed,mode,time:+s.time.toFixed(3),completed:!!s.result,result:s.result};rows.push(row);}catch(e){issues.push({id:g.id,seed,mode,error:e.stack});console.error(g.id,seed,mode,e.message);}}
console.log(g.id,'checked');}
const output={games:games.length,cases:rows.length,botCompletions:rows.filter(r=>r.mode==='bot'&&r.completed).length,issues,drawCalls:calls,rows};fs.mkdirSync(new URL('./out/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('./out/simulation.json',import.meta.url),JSON.stringify(output,null,2));console.log(JSON.stringify({games:games.length,cases:rows.length,botCompletions:output.botCompletions,issues:issues.length}));if(issues.length)process.exitCode=1;
