import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,cream='#f6e6bd',colors=['#e996b1','#83b6d4','#e4c071','#91bda1','#b49fce','#deae85'];
const pulse=(t,f=5,o=0)=>(t*f+o)%1<.4,wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const label=(c,id,text,x=0,y=4,z=0,sx=6)=>c.draw(id,'text',{x,y,z,sx,sy:.8,text});
const disc=(c,id,x,z,r,color,y=.02)=>c.draw(id,'cylinder',{x,y,z,sx:r*2,sy:.05,sz:r*2,color});
const live=c=>c.players.filter(p=>p.alive),group=c=>c.players.slice(1).filter(p=>p.alive);
function race(c,arr,reason){if(arr.length){const t=Math.min(...arr.map(o=>o.t));c.complete(arr.filter(o=>Math.abs(o.t-t)<1e-7).flatMap(o=>o.ids),reason);}}
function fight(c,p,q,dt){p.cool=Math.max(0,(p.cool||0)-dt);if(q.bp&&p.cool===0){p.cool=.4;for(const o of live(c))if(o!==p&&dist(p,o)<1.5){const v=toward(p,o.x,o.z);o.x+=v.x*.65;o.z+=v.z*.65;o.slow=.45;}}if(q.cp&&p.y>0){p.pound=true;p.vy=-13;}if(p.pound&&p.y===0){p.pound=false;for(const o of live(c))if(o!==p&&dist(p,o)<1.25)o.stun=.75;}for(const o of live(c))if(o!==p&&p.vy<0&&p.y-o.y>.6&&p.y-o.y<1.1&&dist(p,o)<.55){o.slow=.4;p.vy=4;}}
function grill(c){
 c.limit=30;const red=[];let next=4,id=0;c.players.forEach((p,i)=>{p.x=(i%2-.5)*4;p.z=(i<2?-1:1)*2;p.stun=0;p.slow=0;p.phase=c.rand(0,TAU);});const width=()=>7-c.time*.085,belt=z=>Math.sin(c.time*.7+Math.floor((z+4.5)/2.25)*2)>0?1:-1;
 return{update(dt){next-=dt;if(next<0&&red.length<3){next=c.rand(4,7);red.push({id:id++,x:c.rand(-4,4),z:c.rand(-3,3),warning:.7,life:12});}c.hint('방향 이동 / A 점프 / B 주먹 / 공중 C 내려찍기 · 움직이고 줄어드는 벨트 위 생존');for(const p of live(c)){p.stun=Math.max(0,p.stun-dt);p.slow=Math.max(0,p.slow-dt);const enemies=live(c).filter(o=>o!==p),target=enemies.sort((a,b)=>dist(p,a)-dist(p,b))[0],danger=red.find(o=>dist(p,o)<2),goal=danger?{x:p.x+(p.x-danger.x)*2,z:p.z+(p.z-danger.z)*2}:target?{x:target.x+Math.sin(c.time+p.phase),z:target.z+Math.cos(c.time+p.phase)}:{x:0,z:0};goal.x=clamp(goal.x,-width()+1,width()-1);goal.z=clamp(goal.z,-3.3,3.3);const q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:p.y===0&&!!danger,b:!!target&&dist(p,target)<1.4&&pulse(c.time,2.3,p.phase)}));if(!p.stun)c.move(p,q,p.slow?2.2:4.1,false);if(p.y===0)p.x+=belt(p.z)*(1.05+Math.abs(p.z)*.2)*dt;c.jump(p,{...q,ap:!p.stun&&q.ap},p.slow?4.5:7);fight(c,p,q,dt);if(Math.abs(p.x)>width()||Math.abs(p.z)>4.4)c.eliminate(p);}for(const f of red){f.life-=dt;f.warning-=dt;if(f.warning>0)continue;const target=live(c).sort((a,b)=>dist(a,f)-dist(b,f))[0];if(target){const v=toward(f,target.x,target.z);f.x+=v.x*1.5*dt;f.z+=v.z*1.5*dt;}for(const p of live(c))if(dist(p,f)<.65&&p.y<1)c.eliminate(p);}for(let i=red.length-1;i>=0;i--)if(red[i].life<=0)red.splice(i,1);c.lastStanding();},render(){for(let i=0;i<4;i++){const z=(i-1.5)*2.2;c.draw('belt'+i,'box',{x:0,y:-.2,z,sx:width()*2,sy:.4,sz:2.15,color:i%2?'#a9b5ab':'#c3c4a6'});for(let j=0;j<8;j++)c.draw('stripe'+i+'_'+j,'box',{x:((j*2+c.time*belt(z))%(width()*2))-width(),y:.01,z,sx:.06,sy:.03,sz:2,color:'#81948c'});}for(let j=-4;j<=4;j++)for(const side of [-1,1])c.draw('blue'+j+'_'+side,'cone',{x:side*(width()+.35),y:.4,z:j,sx:.6,sy:.9,sz:.6,color:'#7eafdc',glow:true});red.forEach(f=>c.draw('red'+f.id,'cone',{x:f.x,y:f.warning>0?3*f.warning+.4:.5,z:f.z,sx:.8,sy:1.1,sz:.8,color:'#e69a70',glow:true}));},timeout(){c.complete([],'둘 이상 생존해 무승부');}};
}
function parasol(c){
 c.limit=30;c.view={size:23,eye:[0,7,26],target:[0,4,0]};const loot=[];let id=0,next=0;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.y=3+i*.5;p.z=i*.08;p.open=true;p.stun=0;});
 return{update(dt){next-=dt;if(next<=0){next=.24;const side=c.pick([-1,1]);loot.push({id:id++,x:side*9,y:c.rand(1,8),vx:-side*c.rand(3,5),vy:c.rand(.5,2),value:c.pick([1,1,1,5,-1]),life:0});}c.hint('좌우 이동 / A 우산 열기·닫기 · 열린 우산으로 코인·주머니 수집, 망치는 피하기');for(const o of loot){o.x+=o.vx*dt;o.vy-=1.8*dt;o.y+=o.vy*dt;o.life+=dt;}for(const p of c.players){p.stun=Math.max(0,p.stun-dt);const target=loot.filter(o=>o.value>0&&!o.gone).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y-1)-Math.hypot(b.x-p.x,b.y-p.y-1))[0],desired=!target||target.y>p.y+.7,q=c.input(p,()=>({x:target?Math.sign(target.x-p.x):0,a:p.stun===0&&p.open!==desired}));if(q.ap&&p.stun===0)p.open=!p.open;p.x=clamp(p.x+q.x*(p.open?3.6:0)*dt,-8,8);p.y=clamp(p.y+(p.open?1.6:-3.5)*dt,.1,8);if(p.open&&p.y>=8)p.open=false;else if(!p.open&&p.y<=.1&&p.stun===0)p.open=true;p.pose='float';}for(const o of loot)if(!o.gone){const ps=c.players.filter(p=>p.open&&!p.stun&&Math.abs(p.x-o.x)<.85&&Math.abs(p.y+1.3-o.y)<.6).sort((a,b)=>Math.hypot(a.x-o.x,a.y+1.3-o.y)-Math.hypot(b.x-o.x,b.y+1.3-o.y));if(ps.length){const nearest=Math.hypot(ps[0].x-o.x,ps[0].y+1.3-o.y),p=c.pick(ps.filter(p=>Math.abs(Math.hypot(p.x-o.x,p.y+1.3-o.y)-nearest)<1e-7));o.gone=true;if(o.value>0)c.points(p,o.value);else{p.open=false;p.stun=.75;}}}for(let i=loot.length-1;i>=0;i--)if(loot[i].gone||loot[i].y<-1||loot[i].life>7)loot.splice(i,1);},render(){c.draw('sky','box',{x:0,y:4,z:-2,sx:23,sy:12,sz:.3,color:'#a8cadc'});c.players.forEach(p=>{if(p.open)c.draw('umbrella'+p.i,'cone',{x:p.x,y:p.y+1.35,z:p.z,sx:2,sy:.45,sz:1.3,color:p.color});c.draw('shaft'+p.i,'cylinder',{x:p.x,y:p.y+.9,z:p.z,sx:.05,sy:1,sz:.05,color:cream});});loot.forEach(o=>c.draw('loot'+o.id,o.value===1?'cylinder':'box',{x:o.x,y:o.y,z:0,sx:o.value===5?.65:.45,sy:o.value<0?.25:.45,sz:.45,color:o.value<0?'#728895':'#e9c46e'}));},timeout(){c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'각자 모은 코인을 받습니다');}};
}
function messy(c,m={}){
 const stars=m.titleId==='superstars';c.limit=35;c.view={size:25,eye:[0,31,20],target:[0,0,0]};const correct=c.shuffle(Array.from({length:10},(_,i)=>i)),stay=new Set(c.shuffle(Array.from({length:10},(_,i)=>i)).slice(0,3)),fallen=c.shuffle(correct.filter((_,i)=>!stay.has(i))),initial=Array(20).fill(null);correct.forEach((v,i)=>{if(stay.has(i))initial[i]=v;});fallen.forEach((v,i)=>initial[10+i]=v);const states=c.players.map((p,i)=>{p.visible=false;return{items:[...initial],held:null,cursor:0,cool:0,closed:false,memory:[...correct]};});states.forEach((s,i)=>{if(c.rand()<.65){const a=c.int(0,9),b=c.int(0,9);[s.memory[a],s.memory[b]]=[s.memory[b],s.memory[a]];}});
 const pos=(board,slot)=>({x:(board%2?5.7:-5.7)+(slot%5-2)*1.5,z:(board<2?-4.6:4.6)+(Math.floor(slot/5)-1.5)*1.4});
 return{update(dt){const preview=c.time<5;c.hint(preview?'5초 동안 열 개 물건의 원래 위치를 기억하세요':`방향 커서 / A 집기·놓기 / ${stars?'B':'C'} 커튼 · 남은 30초에 원위치로`);states.forEach((s,i)=>{s.cool=Math.max(0,s.cool-dt);let goal=-1;if(s.held!=null)goal=s.memory.indexOf(s.held);else{const wrong=s.memory.findIndex((id,j)=>s.items[j]!==id);if(wrong>=0)goal=s.items.indexOf(s.memory[wrong]);}const ready=goal<0,q=c.input(c.players[i],()=>({x:!preview&&!ready&&goal%5!==s.cursor%5?Math.sign(goal%5-s.cursor%5):0,z:!preview&&!ready&&goal%5===s.cursor%5?Math.sign(Math.floor(goal/5)-Math.floor(s.cursor/5)):0,a:!preview&&!s.closed&&goal===s.cursor&&pulse(c.time,3.3,i*.1),[stars?'b':'c']:!preview&&ready&&!s.closed}));if(preview)return;if(stars?q.bp:q.cp)s.closed=!s.closed;if(s.closed)return;if(s.cool===0&&(Math.abs(q.x)>.5||Math.abs(q.z)>.5)){const col=clamp(s.cursor%5+Math.sign(q.x),0,4),row=clamp(Math.floor(s.cursor/5)+Math.sign(q.z),0,3);s.cursor=row*5+col;s.cool=.15;}if(q.ap){const item=s.items[s.cursor];s.items[s.cursor]=s.held;s.held=item;}});},render(){c.arena({width:25,depth:22,color:'#beb3c7'});states.forEach((s,i)=>{const center={x:i%2?5.7:-5.7,z:i<2?-4.6:4.6};c.draw('room'+i,'box',{x:center.x,y:-.04,z:center.z,sx:9,sy:.1,sz:6,color:'#e5d5ad'});if(s.closed&&c.time>=5){c.draw('curtain'+i,'box',{x:center.x,y:.4,z:center.z,sx:8.5,sy:.5,sz:5.8,color:c.players[i].color});return;}for(let j=0;j<20;j++){const spot=pos(i,j),v=c.time<5?(j<10?correct[j]:null):s.items[j];c.draw('slot'+i+'_'+j,'box',{x:spot.x,y:.05,z:spot.z,sx:1.3,sy:.07,sz:1.2,color:j<10?'#bea982':'#d5c79e'});if(v!=null){c.draw('item'+i+'_'+j,['cone','sphere','box','cylinder'][v%4],{x:spot.x,y:.4,z:spot.z,sx:.6,sy:.6,sz:.6,color:colors[v%6]});label(c,'itemLabel'+i+'_'+j,String(v+1),spot.x,.9,spot.z,.7);}}const p=pos(i,s.cursor);c.draw('cursor'+i,'ring',{x:p.x,y:.1,z:p.z,sx:1.3,sy:1.3,sz:1,rx:-Math.PI/2,color:c.players[i].color});if(s.held!=null)label(c,'held'+i,'손: '+(s.held+1),center.x,2.6,center.z,3);});},timeout(){states.forEach((s,i)=>c.players[i].score=s.items.slice(0,10).filter((v,j)=>v===correct[j]).length);const best=Math.max(...c.players.map(p=>p.score));c.complete(best>(stars?0:3)?c.players.filter(p=>p.score===best).map(p=>p.i):[],stars?'원위치에 놓은 물건이 가장 많아야 하며 전원 0점은 무승부':'맞힌 위치가 가장 많아야 하며 MP3는 최고점 3 이하 무승부');}};
}
const quizQuestions=[
 ['황금 버섯을 쓰면 주사위 블록은 몇 개일까요?',['2개','3개','4개'],1],
 ['부끄부끄에게 별을 훔치게 하려면 몇 코인일까요?',['20','30','50'],2],
 ['일반 버섯을 쓰면 주사위 블록은 몇 개일까요?',['1개','2개','3개'],1],
 ['와리오의 모자는 무슨 색일까요?',['빨강','노랑','초록'],1],
 ['점프 중 내려찍기에 쓰는 N64 버튼은?',['A','B','Z'],2],
 ['보드에서 별 한 개의 기본 가격은 몇 코인일까요?',['30','50','20'],2],
 ['독버섯 상태의 주사위 최댓값은?',['3','2','1'],0],
 ['동키콩 넥타이에 적힌 글자는?',['DK','TK','PK'],0],
 ['루이지의 모자는 무슨 색일까요?',['노랑','빨강','초록'],2],
 ['이 미니게임의 원작은 마리오 파티 몇 편일까요?',['3','1','2'],0]
];
function quiz(c){
 c.limit=180;const questions=c.shuffle(quizQuestions);let round=0,phase='reveal',age=0,buzzer=null,shown=0,botAnswers=[];c.players.forEach((p,i)=>{p.x=(i-1.5)*3.3;p.z=3;p.skipUntil=-1;p.lag=c.rand(1.1,2.6);});
 function next(){round++;if(round>=10){const best=Math.max(...c.players.map(p=>p.score)),w=c.players.filter(p=>p.score===best);c.complete(w.length===1?[w[0].i]:[],'열 문제 종료 · 최고점 단독 선수가 승리');return;}age=0;phase='reveal';buzzer=null;shown=0;c.players.forEach(p=>p.lag=c.rand(1.1,2.6));}function answer(i){const p=c.players[buzzer];if(i===questions[round][2]){c.points(p);if(p.score===3){c.complete([p.i],'세 문제를 먼저 맞혔습니다');return;}}else p.skipUntil=round+1;phase='result';age=0;}
 return{update(dt){age+=dt;const question=questions[round],inputs=c.players.map(p=>c.input(p,()=>{if(phase==='reveal')return{a:p.skipUntil<round&&age>p.lag};if(phase==='answer'&&p.i===buzzer&&age>.55&&age<.8)return{[['a','b','c'][botAnswers[p.i]]]:true};return{};}));c.hint(phase==='reveal'?'A로 먼저 문제 가로채기 · 문장은 다시 보이지 않습니다':phase==='answer'?`${buzzer+1}P 답변 · A·B·C 중 선택, 5초 · 오답은 다음 문제 쉬기`:'정답 판정');if(phase==='reveal'){shown=Math.min(question[0].length,Math.floor(age*9));const candidates=c.players.filter(p=>p.skipUntil<round&&inputs[p.i].ap);if(candidates.length){buzzer=c.pick(candidates).i;phase='answer';age=0;botAnswers=c.players.map(p=>c.rand()<.15?c.int(0,2):question[2]);}else if(age>question[0].length/9+4)next();}else if(phase==='answer'){const q=inputs[buzzer],choice=q.ap?0:q.bp?1:q.cp?2:-1;if(choice>=0)answer(choice);else if(age>=5)answer(-1);}else if(age>1)next();},render(){c.arena({width:17,depth:11,color:'#b5c4b9'});label(c,'question',questions[Math.min(round,9)][0].slice(0,shown),0,5,-3,15);if(phase!=='reveal')label(c,'answers',questions[Math.min(round,9)][1].map((s,i)=>['A','B','C'][i]+': '+s).join('   '),0,3.6,-2,13);c.players.forEach(p=>{c.draw('block'+p.i,'box',{x:p.x,y:2,z:3,sx:1.2,sy:1,sz:1.2,color:p.skipUntil>=round?'#9ba4aa':p.color});label(c,'qscore'+p.i,p.skipUntil>=round?'한 턴 쉬기':p.score+'/3',p.x,.6,4.5,3);});},timeout(){const best=Math.max(...c.players.map(p=>p.score)),w=c.players.filter(p=>p.score===best);c.complete(w.length===1?[w[0].i]:[],'퀴즈 종료');}};
}
function curtain(c){
 c.limit=50;let round=0,age=0,lineup=[],asked=0,fromRight=false;const icons=['새','거북','유령'];c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=4;p.choice=0;p.confirm=null;p.cool=0;p.error=false;});function next(){round++;age=0;lineup=Array.from({length:round+2},()=>c.int(0,2));asked=c.int(0,lineup.length-1);fromRight=c.rand()<.5;c.players.forEach(p=>{p.confirm=null;p.error=c.rand()<.12;p.answer=p.error?(lineup[asked]+1)%3:lineup[asked];p.lag=c.rand(.25,.8);});}next();
 return{update(dt){age+=dt;const preview=4,answering=age>=preview;c.hint(answering?`${round}/3 · ${fromRight?'오른쪽':'왼쪽'}에서 ${fromRight?lineup.length-asked:asked+1}번째는? · 좌우·A 확인·B 취소`:'무대의 순서를 기억하세요');for(const p of c.players){p.cool=Math.max(0,p.cool-dt);const q=c.input(p,()=>({x:answering&&p.alive&&p.confirm==null&&p.choice!==p.answer?Math.sign(p.answer-p.choice):0,a:answering&&age>preview+p.lag&&p.alive&&p.choice===p.answer&&p.confirm==null}));if(answering&&p.alive){if(q.bp)p.confirm=null;if(p.confirm==null){if(q.x&&p.cool===0){p.choice=clamp(p.choice+Math.sign(q.x),0,2);p.cool=.2;}if(q.ap)p.confirm=p.choice;}}}if(age>=preview+10){for(const p of live(c)){if(p.confirm!==lineup[asked])c.eliminate(p);else c.points(p);}if(!live(c).length)c.complete([],'모두 틀렸습니다');else if(round===3)c.survivors('세 문제를 모두 맞혔습니다');else next();}},render(){c.arena({width:17,depth:13,color:'#b6a5be'});if(age<4){lineup.forEach((kind,i)=>{const x=(i-(lineup.length-1)/2)*2.4;c.draw('dancer'+i,['cone','sphere','sphere'][kind],{x,y:.8+Math.sin(c.time*5+i)*.2,z:-3,sx:1.2,sy:1.5,sz:1.2,color:colors[kind]});label(c,'dancerName'+i,icons[kind],x,2.3,-3,2);});}else c.draw('curtain','box',{x:0,y:1.6,z:-3,sx:14,sy:3.2,sz:.25,color:'#a77e9f'});c.players.forEach(p=>label(c,'choice'+p.i,p.alive?(p.confirm==null?'선택: ':'확인: ')+icons[p.confirm??p.choice]:'춤추기',p.x,2.7,4,3));},timeout(){c.complete([],'세 문제를 마치지 못했습니다');}};
}
function chase(c,m={}){
 const stars=m.titleId==='superstars';c.limit=90;c.view={size:23,eye:[0,20,19],target:[0,0,0]};const length=105,bombs=[16,30,47,63,80,94];let camera=0;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=4;p.d=0;p.speed=0;p.dive=0;p.diveHeld=false;p.stun=0;p.phase=c.rand(0,1);p.hit=new Set();});
 return{update(dt){const fish=c.time*3.7-11,finishes=[];c.hint(`A 반복 수영 / ${stars?'아래 방향':'B 또는 C'} 잠수 · 폭탄 밑으로 들어가 거대 물고기를 피하세요`);for(const p of live(c)){const b=bombs.find(n=>n>p.d-.3&&!p.hit.has(n)),q=c.input(p,()=>({a:pulse(c.time,5.5+p.phase,p.phase),[stars?'z':'b']:b!=null&&b-p.d<2.8&&b>p.d&&p.dive===0?1:0}));const dive=stars?q.z>.5&&!p.diveHeld:q.bp||q.cp;p.diveHeld=q.z>.5;if(dive&&p.dive===0)p.dive=.85;p.dive=Math.max(0,p.dive-dt);p.stun=Math.max(0,p.stun-dt);if(q.ap)p.speed+=1.1;p.speed=clamp(p.speed-dt*3.3,0,5.5);const old=p.d;p.d+=p.speed*(p.stun?.25:1)*dt;for(const b of bombs)if(old<b&&p.d>=b){p.hit.add(b);if(p.dive===0){p.stun=.85;p.speed*=.25;}}if(p.d<fish)c.eliminate(p);p.y=p.dive>0?-.6:0;if(p.d>=length)finishes.push({ids:[p.i],t:(length-old)/(p.d-old)});}camera=Math.max(0,Math.max(...c.players.map(p=>p.d))-8);c.players.forEach(p=>p.z=4-(p.d-camera)*.4);race(c,finishes,'끝에 먼저 도착했습니다');if(!live(c).length)c.complete([],'모두 물고기에게 잡혔습니다');},render(){c.draw('water','box',{x:0,y:-1.3,z:0,sx:17,sy:.4,sz:24,color:'#83bece'});const fish=c.time*3.7-11;c.draw('bigFish','sphere',{x:0,y:0,z:4-(fish-camera)*.4+2,sx:13,sy:3,sz:4,color:'#d896a6'});for(const p of c.players){for(const b of bombs){const z=4-(b-camera)*.4;if(Math.abs(z)<13&&!p.hit.has(b))c.draw('bomb'+p.i+'_'+b,'sphere',{x:p.x,y:.3,z,sx:.9,sy:.9,sz:.9,color:'#69808c'});}if(p.alive&&p.d-fish<3)label(c,'warning'+p.i,'!',p.x,2,p.z,1.5);}label(c,'remaining',Math.max(0,Math.ceil(length-Math.max(...c.players.map(p=>p.d))))+' m',0,4,-8,4);},timeout(){c.complete([],'아무도 탈출하지 못했습니다');}};
}
function aces(c){
 c.limit=60;c.view={size:25,eye:[0,22,23],target:[0,1,0]};const shots=[];let id=0;c.players.forEach((p,i)=>{p.x=(i%2?1:-1)*6;p.z=(i<2?1:-1)*4;p.y=1.4;p.heading=Math.atan2(-p.x,p.z);p.hp=2;p.charge=0;p.cool=0;p.inv=0;p.phase=c.rand(0,1);});
 return{update(dt){c.hint('방향 조향 / A 가속 / B 감속 / C 짧게 보통탄·길게 누르고 놓아 유도탄 · 경계 U턴으로 유도탄 회피');for(const p of live(c)){p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);const target=live(c).filter(o=>o!==p).sort((a,b)=>dist(p,a)-dist(p,b))[0],angle=target?Math.atan2(target.x-p.x,-(target.z-p.z)):p.heading,q=c.input(p,()=>({x:clamp(wrap(angle-p.heading)*2,-1,1),a:shots.some(s=>s.target===p.i),b:false,c:!shots.some(s=>s.owner===p.i)&&(c.time+p.phase)%2.2<(Math.floor((c.time+p.phase)/2.2)%2?.7:.12)}));p.heading+=q.x*dt*1.8;p.z+=q.z*dt*.5;const speed=q.a?7.5:q.b?2.5:4.5;p.x+=Math.sin(p.heading)*speed*dt;p.z-=Math.cos(p.heading)*speed*dt;if(Math.abs(p.x)>9||Math.abs(p.z)>7){p.x=clamp(p.x,-9,9);p.z=clamp(p.z,-7,7);p.heading+=Math.PI;p.inv=.25;shots.forEach(s=>{if(s.homing&&s.target===p.i)s.dead=true;});}if(q.c)p.charge+=dt;if(!q.c&&p.charge>0){if(!p.cool&&!shots.some(s=>s.owner===p.i&&!s.dead)){shots.push({id:id++,owner:p.i,x:p.x,z:p.z,heading:p.heading,homing:p.charge>.45,target:target?.i??p.i,life:0});p.cool=.2;}p.charge=0;}p.rotation=Math.PI/2-p.heading;p.score=p.hp;}const damage=new Set();for(const s of shots){s.life+=dt;if(s.homing){const t=c.players[s.target];if(!t.alive){s.dead=true;continue;}s.heading=Math.atan2(t.x-s.x,-(t.z-s.z));}s.x+=Math.sin(s.heading)*(s.homing?8.5:11)*dt;s.z-=Math.cos(s.heading)*(s.homing?8.5:11)*dt;for(const p of live(c))if(p.i!==s.owner&&!p.inv&&dist(p,s)<.65){damage.add(p.i);s.dead=true;}if(s.life>4||Math.abs(s.x)>11||Math.abs(s.z)>9)s.dead=true;}for(const i of damage){const p=c.players[i];p.hp--;p.score=p.hp;p.inv=.7;if(p.hp===0)c.eliminate(p);}for(let i=shots.length-1;i>=0;i--)if(shots[i].dead)shots.splice(i,1);c.lastStanding();},render(){c.arena({width:22,depth:18,color:'#a2c9da'});for(const p of live(c)){c.draw('plane'+p.i,'box',{x:p.x,y:1.3,z:p.z,sx:2,sy:.25,sz:1.3,ry:-p.heading,color:p.color});label(c,'hp'+p.i,'♥'.repeat(p.hp),p.x,3,p.z,2);}shots.forEach(s=>c.draw('shot'+s.id,s.homing?'cone':'sphere',{x:s.x,y:1.5,z:s.z,sx:s.homing?.5:.25,sy:s.homing?.8:.25,sz:.3,rx:Math.PI/2,rz:s.heading,color:s.homing?'#f0d181':'#eef0dc'}));},timeout(){const max=Math.max(...live(c).map(p=>p.hp)),w=live(c).filter(p=>p.hp===max);c.complete(w.length===1?[w[0].i]:[],'남은 체력 비교 · 최고 체력 동률이면 무승부');}};
}
function bounce(c){
 c.limit=30;const tiles=Array.from({length:9},(_,i)=>({x:(i%3-1)*3.1,z:(Math.floor(i/3)-1)*3.1})),order=c.shuffle([0,1,2,3,5,6,7,8]);c.players.forEach((p,i)=>{p.x=(i%2-.5)*3;p.z=(i<2?-1:1)*1.5;p.vx=p.vz=0;p.jumpY=0;p.cool=0;p.phase=c.rand(0,1);});const gone=i=>i!==4&&c.time>5+order.indexOf(i)*2.6;
 return{update(dt){c.hint('방향 이동 / A 크게 점프 / 공중 C 회전 공격 · 발판이 하나씩 떨어집니다');for(const p of live(c)){p.cool=Math.max(0,p.cool-dt);const o=live(c).filter(o=>o!==p).sort((a,b)=>dist(p,a)-dist(p,b))[0],target=c.time>12?{x:0,z:0}:o||{x:0,z:0},q=c.input(p,()=>({...toward(p,target.x,target.z),a:p.jumpY===0&&pulse(c.time,1.4,p.phase),c:p.jumpY>.4&&!!o&&dist(p,o)<2.4&&p.cool===0}));p.vx=(p.vx+q.x*7*dt)*Math.exp(-dt*2);p.vz=(p.vz+q.z*7*dt)*Math.exp(-dt*2);p.x+=p.vx*dt;p.z+=p.vz*dt;p.y=p.jumpY;c.jump(p,q,7.5);p.jumpY=p.y;if(q.cp&&p.jumpY>.1&&p.cool===0){p.cool=.5;for(const o of live(c))if(o!==p&&dist(p,o)<2.2){const v=toward(p,o.x,o.z);o.vx+=v.x*7;o.vz+=v.z*7;}}if(p.jumpY===0&&!tiles.some((t,i)=>!gone(i)&&Math.abs(p.x-t.x)<1.55&&Math.abs(p.z-t.z)<1.55))c.eliminate(p);p.y=.8+p.jumpY+Math.abs(Math.sin(c.time*7+p.phase))*.18;}c.lastStanding();},render(){tiles.forEach((t,i)=>{if(!gone(i))c.draw('tile'+i,'box',{x:t.x,y:-.2,z:t.z,sx:3,sy:.4,sz:3,color:i!==4&&c.time>4+order.indexOf(i)*2.6?'#dbaa88':'#b8cbb1'});});live(c).forEach(p=>c.draw('ball'+p.i,'sphere',{x:p.x,y:p.y-.5,z:p.z,sx:1.1,sy:1.1,sz:1.1,color:p.color}));},timeout(){c.complete([],'둘 이상 생존해 무승부');}};
}
function eyeSore(c){
 c.limit=60;c.view={size:25,eye:[0,28,20],target:[0,0,0]};const fire=[];let next=2,id=0;c.players.forEach((p,i)=>{p.center={x:i%2?6:-6,z:i<2?-5:5};p.x=p.center.x+3;p.z=p.center.z;p.angle=0;p.turn=0;p.stun=0;p.phase=c.rand(0,TAU);});
 return{update(dt){next-=dt;if(next<0){next=c.rand(.8,1.5);const i=c.int(0,3),p=c.players[i],a=c.rand(0,TAU),r=c.rand(1,3);fire.push({id:id++,i,x:p.center.x+Math.cos(a)*r,z:p.center.z+Math.sin(a)*r,age:0,life:c.rand(2,4)});}fire.forEach(f=>f.age+=dt);c.hint('방향으로 큰 눈 주위를 15바퀴 · 눈과 떨어지는 불에 닿으면 잠시 정지');const finish=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);const radius=2.1-Math.min(15,Math.abs(p.turn)/TAU)*.085,a=Math.atan2(p.z-p.center.z,p.x-p.center.x),goal={x:p.center.x+Math.cos(a+.5)*(radius+.65),z:p.center.z+Math.sin(a+.5)*(radius+.65)},q=c.input(p,()=>toward(p,goal.x,goal.z));if(!p.stun)c.move(p,q,5.3,false);p.x=clamp(p.x,p.center.x-4,p.center.x+4);p.z=clamp(p.z,p.center.z-4,p.center.z+4);let r=dist(p,p.center);if(r<radius){const v=toward(p.center,p.x,p.z);p.x=p.center.x+v.x*(radius+.12);p.z=p.center.z+v.z*(radius+.12);p.stun=.55;}if(fire.some(f=>f.i===p.i&&f.age>.55&&f.age<f.life&&dist(p,f)<.6))p.stun=.6;const angle=Math.atan2(p.z-p.center.z,p.x-p.center.x),old=p.turn;p.turn+=wrap(angle-p.angle);p.angle=angle;p.score=Math.min(15,Math.floor(Math.abs(p.turn)/TAU));if(Math.abs(p.turn)>=15*TAU)finish.push({ids:[p.i],t:(15*TAU-Math.abs(old))/Math.max(.0001,Math.abs(p.turn)-Math.abs(old))});}race(c,finish,'열다섯 바퀴로 큰 눈을 사라지게 했습니다');for(let i=fire.length-1;i>=0;i--)if(fire[i].age>fire[i].life)fire.splice(i,1);},render(){c.arena({width:24,depth:22,color:'#b0bbb4'});c.players.forEach(p=>{const r=2.1-Math.min(15,Math.abs(p.turn)/TAU)*.085;c.draw('eye'+p.i,'sphere',{x:p.center.x,y:r*.7,z:p.center.z,sx:r*2,sy:r*1.5,sz:r*2,color:'#eee4d5'});c.draw('pupil'+p.i,'sphere',{x:p.center.x+Math.cos(p.angle)*r*.8,y:r*.85,z:p.center.z+Math.sin(p.angle)*r*.8,sx:r*.6,sy:r*.6,sz:r*.6,color:p.color});label(c,'laps'+p.i,p.score+'/15',p.center.x,4,p.center.z,3);});fire.forEach(f=>c.draw('fire'+f.id,'cone',{x:f.x,y:f.age<.55?3*(1-f.age/.55)+.3:.4,z:f.z,sx:.65,sy:.8,sz:.65,color:'#e99b70',glow:true}));},timeout(){c.complete([],'15바퀴를 완주하지 못했습니다');}};
}
function beat(c){
 c.limit=180;const interval=.55;let sequence=Array.from({length:4},()=>c.int(0,2)),turn=0,age=0,phase='demo',index=0,played=false,lastDemo=-1,lastTick=-1,extra=null,tone=null;c.players.forEach((p,i)=>{p.x=(i-1.5)*3.2;p.z=1;p.lag=c.rand(.05,.14);p.wrong=-1;});
 const play=k=>{tone={key:k,time:c.time,player:phase==='demo'?-1:turn};c.sound?.([220,330,440][k],.15);};
 function next(){c.lastStanding();if(c.ended)return;do{turn=(turn+1)%4;}while(!c.players[turn].alive);age=0;index=0;played=false;extra=null;lastTick=-1;c.players[turn].wrong=c.rand()<.25?c.int(0,sequence.length-1):-1;}
 return{update(dt){age+=dt;const slot=Math.floor(age/interval),within=age%interval;c.hint(phase==='demo'?'처음 네 박자의 빛·소리와 A·B·C 순서를 기억하세요':`${turn+1}P · 박자 ${Math.min(slot+1,sequence.length+1)}/${sequence.length+1} · A·B·C로 앞 박자를 반복하고 마지막 한 박자 추가`);if(phase==='demo'){if(slot<sequence.length&&slot!==lastDemo){lastDemo=slot;play(sequence[slot]);}c.players.forEach(p=>c.input(p,{}));if(slot>=sequence.length){phase='play';age=0;index=0;played=false;}return;}const p=c.players[turn];if(slot>index){if(!played){c.eliminate(p);next();return;}if(index===sequence.length){sequence.push(extra);if(sequence.length>=16){c.complete([],'16박자까지 둘 이상 남아 무승부');return;}next();return;}index=slot;played=false;}if(slot!==lastTick){lastTick=slot;c.sound?.(100,.025);}for(const player of c.players){const target=slot<sequence.length?sequence[slot]:turn%3,key=slot===player.wrong?(target+1)%3:target,q=c.input(player,()=>({[['a','b','c'][key]]:player.i===turn&&within>player.lag&&within<player.lag+.1}));if(player.i!==turn)continue;const hits=[q.ap,q.bp,q.cp].filter(Boolean).length,k=q.ap?0:q.bp?1:q.cp?2:-1;if(k>=0){if(hits!==1||played||within>.4||(slot<sequence.length&&k!==sequence[slot])){c.eliminate(p);next();return;}played=true;if(slot===sequence.length)extra=k;play(k);}}},render(){c.arena({width:18,depth:10,color:'#a9c6b2'});c.players.forEach(p=>{disc(c,'lily'+p.i,p.x,p.z,1.4,p.color);for(let j=0;j<3;j++){const flash=tone?.player===p.i&&tone.key===j&&c.time-tone.time<.22;c.draw('drum'+p.i+'_'+j,'cylinder',{x:p.x+(j-1)*.75,y:.6,z:p.z-.9,sx:.65,sy:1.2,sz:.65,color:flash?cream:colors[j],glow:flash});}if(p.i===turn&&phase==='play')label(c,'turn','♪',p.x,3.5,p.z,2);});for(let j=0;j<3;j++){const flash=tone?.key===j&&c.time-tone.time<.22;c.draw('guide'+j,'cylinder',{x:(j-1)*1.7,y:.7,z:-3,sx:1.2,sy:1.4,sz:1.2,color:flash?cream:colors[j],glow:flash});label(c,'guideKey'+j,['A','B','C'][j],(j-1)*1.7,2,-3,1);}label(c,'length',sequence.length+' 박자 + 1',0,4.6,-3,6);},timeout(){c.complete([],'리듬 경기 종료 · 무승부');}};
}
function water(c){
 c.limit=180;c.view={size:23,eye:[0,24,19],target:[0,0,0]};c.players.forEach((p,i)=>{p.x=5.2+i*.55;p.z=0;p.heading=Math.PI/2;p.speed=0;p.angle=0;p.turn=0;p.lane=c.rand(5.7,6.5);});
 return{update(dt){c.hint('좌우로 조타 / A 가속 · 다섯 바퀴 선착순 · 벽에 닿으면 감속');const finished=[];for(const p of c.players){const angle=Math.atan2(p.z,p.x),target={x:Math.cos(angle+.4)*p.lane,z:Math.sin(angle+.4)*p.lane},desired=Math.atan2(target.z-p.z,target.x-p.x),error=wrap(desired-p.heading),q=c.input(p,()=>({x:clamp(error*2,-1,1),a:p.speed<5.5||Math.abs(error)<.6}));p.speed=clamp(p.speed+(q.a?3:-2.2)*dt,0,7);p.heading+=q.x*(2.8/(1+p.speed*.25))*dt;p.x+=Math.cos(p.heading)*p.speed*dt;p.z+=Math.sin(p.heading)*p.speed*dt;const r=Math.hypot(p.x,p.z);if(r<4.35||r>7.9){const nr=clamp(r,4.35,7.9);p.x=p.x/r*nr;p.z=p.z/r*nr;p.speed*=Math.exp(-dt*12);}const a=Math.atan2(p.z,p.x),delta=wrap(a-p.angle),old=p.turn;p.turn+=delta;p.angle=a;p.score=Math.max(0,Math.min(5,Math.floor(p.turn/TAU)));p.reverse=delta<-.001;p.rotation=-p.heading;p.y=.35;if(p.turn>=TAU*5)finished.push({ids:[p.i],t:(TAU*5-old)/Math.max(delta,.000001)});}race(c,finished,'다섯 바퀴를 먼저 완주했습니다');},render(){disc(c,'water',0,0,8.4,'#81bed0',-.2);disc(c,'island',0,0,4.2,'#bbcd99',0);c.draw('line','box',{x:6.1,y:.03,z:0,sx:3.5,sy:.04,sz:.12,color:cream});for(const p of c.players){c.draw('boat'+p.i,'cone',{x:p.x,y:.17,z:p.z,sx:.9,sy:1.6,sz:.65,rx:Math.PI/2,rz:-p.heading,color:p.color});if(p.reverse)label(c,'reverse'+p.i,'REVERSE',p.x,2.7,p.z,3);}label(c,'laps','5 LAPS',0,1,0,4);},timeout(){c.complete([],'3분 안에 다섯 바퀴를 완주하지 못했습니다');}};
}
function bridges(c){
 c.limit=180;c.view={size:25,eye:[0,24,21],target:[0,0,0]};const lane=i=>(i-1.5)*5,path=(i,z)=>lane(i)+Math.sin((z+6)*Math.PI/6)*.8,fishPhase=c.players.map(()=>c.rand(0,4));c.players.forEach((p,i)=>{p.x=lane(i);p.z=5.8;p.vx=p.vz=0;p.cargo=true;p.frozen=0;p.hitFish=-1;p.skill=c.rand(2.5,3.2);});
 return{update(dt){c.hint('방향 이동 · 얼음길에서 블록을 세 번 운반 · 떨어지면 출발점으로');const finishes=[];for(const p of c.players){const phase=(c.time+fishPhase[p.i])%5,cycle=Math.floor((c.time+fishPhase[p.i])/5),ahead=p.cargo?Math.max(-5.8,p.z-.7):Math.min(5.8,p.z+.7),goal={x:path(p.i,ahead),z:ahead},q=c.input(p,()=>{const v=toward(p,goal.x,goal.z);return{x:clamp((v.x*p.skill-p.vx)*.55,-1,1),z:clamp((v.z*p.skill-p.vz)*.55,-1,1)};});if(p.frozen>0){p.frozen-=dt;p.y=-.5;if(p.frozen<=0){p.x=lane(p.i);p.z=5.8;p.vx=p.vz=0;p.cargo=true;p.y=0;}continue;}p.vx=(p.vx+q.x*11*dt)*Math.exp(-dt*2.5);p.vz=(p.vz+q.z*11*dt)*Math.exp(-dt*2.5);const oldz=p.z;p.x+=p.vx*dt;p.z+=p.vz*dt;p.pose='run';if(phase>.7&&phase<1.1&&Math.abs(p.z)<.6&&p.hitFish!==cycle){p.hitFish=cycle;p.vx+=c.pick([-1,1])*4;}if(Math.abs(p.x-path(p.i,p.z))>.9||Math.abs(p.z)>6.65){p.frozen=1.6;p.cargo=false;continue;}if(p.cargo&&p.z<-5.6){p.cargo=false;c.points(p);if(p.score>=3)finishes.push({ids:[p.i],t:(oldz+5.6)/Math.max(.000001,oldz-p.z)});}if(!p.cargo&&p.z>5.6)p.cargo=true;}race(c,finishes,'세 블록으로 얼음길을 먼저 완성했습니다');},render(){c.arena({width:25,depth:17,color:'#89becd'});for(let i=0;i<4;i++){for(let j=0;j<=40;j++){const z=-6+j*.3;c.draw('ice'+i+'_'+j,'box',{x:path(i,z),y:-.02,z,sx:1.8,sy:.3,sz:.38,color:j%2?'#d3eced':'#b6dbe3'});}for(let j=0;j<c.players[i].score;j++)c.draw('bridge'+i+'_'+j,'box',{x:lane(i),y:.12,z:-6.3-j*.5,sx:1.5,sy:.35,sz:.48,color:cream});const ph=(c.time+fishPhase[i])%5;if(ph<1.5)c.draw('fish'+i,'sphere',{x:lane(i)+(ph-.75)*3,y:Math.sin(ph/1.5*Math.PI)*1.8,z:0,sx:.9,sy:.6,sz:.5,color:'#e397a6'});label(c,'blocks'+i,c.players[i].score+'/3',lane(i),2.3,-7.1,2);}c.players.forEach(p=>{if(p.cargo)c.draw('block'+p.i,'box',{x:p.x,y:p.y+1.6,z:p.z,sx:.8,sy:.8,sz:.8,color:cream});if(p.frozen>0)c.draw('frozen'+p.i,'box',{x:p.x,y:0,z:p.z,sx:1.4,sy:1.5,sz:1.4,color:'#d4e9f0',opacity:.65});});},timeout(){c.complete([],'안전 시간 안에 세 블록을 완성하지 못했습니다');}};
}
function tower(c){
 c.limit=60;c.view={size:26,eye:[0,13,33],target:[0,5,0]};const h=(k,t)=>1.15*(k+1)+Math.sin(t*1.6+k*.9)*.22,x=(i,k)=>(i-1.5)*5.5+(k%2?.8:-.8),hammers=[];let next=3,id=0;c.players.forEach((p,i)=>{p.x=(i-1.5)*5.5;p.z=0;p.y=0;p.vy=0;p.platform=-1;p.stun=0;p.coins=new Set();p.jumpPause=c.rand(.05,.25);p.rest=0;});
 return{update(dt){c.hint('방향 이동 / A 점프 · 움직이는 블록을 타고 꼭대기까지 · 망치 주의');next-=dt;if(next<=0){next=c.rand(2.5,4);for(const p of c.players)if(p.y>1)hammers.push({id:id++,i:p.i,x:p.x+c.rand(-.3,.3),z:p.z,y:p.y+5,vy:0});}for(const o of hammers){o.vy-=10*dt;o.y+=o.vy*dt;}const finished=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);if(p.platform!=null&&p.platform>=0)p.y=h(p.platform,c.time);const nextk=p.platform==null?p.targetLevel||0:p.platform+1,target={x:x(p.i,Math.min(nextk,8)),z:0};if(p.platform!=null)p.targetLevel=nextk;const goalX=Math.abs(target.x-p.x)>.05?Math.sign(target.x-p.x):0,q=c.input(p,()=>({x:goalX*.75,z:clamp(-p.z*2,-1,1),a:p.platform!=null&&!p.stun&&p.rest>p.jumpPause&&nextk<9}));p.rest+=dt;if(!p.stun)c.move(p,q,3.3,false);p.x=clamp(p.x,(p.i-1.5)*5.5-2.4,(p.i-1.5)*5.5+2.4);p.z=clamp(p.z,-2.5,2.5);if(p.platform!=null&&p.platform>=0&&(Math.abs(p.x-x(p.i,p.platform))>.85||Math.abs(p.z)>1.2))p.platform=null;if(q.ap&&p.platform!=null&&!p.stun){p.vy=8;p.platform=null;p.rest=0;}const old=p.y;if(p.platform==null){p.vy-=18*dt;p.y+=p.vy*dt;if(p.vy<=0)for(let k=8;k>=0;k--){const top=h(k,c.time);if(old>=h(k,c.time-dt)-.001&&p.y<=top&&Math.abs(p.x-x(p.i,k))<.85&&Math.abs(p.z)<1.2){const crossing=(old-h(k,c.time-dt))/Math.max(.0001,old-h(k,c.time-dt)-p.y+top);p.y=top;p.platform=k;p.vy=0;p.rest=0;if(k===8)finished.push({ids:[p.i],t:crossing});break;}}if(p.y<=0){p.y=0;p.vy=0;p.platform=-1;}}for(const k of [2,5,7])if(!p.coins.has(k)&&Math.abs(p.x-x(p.i,k))<.6&&Math.abs(p.y-h(k,c.time)-.55)<.8){p.coins.add(k);c.points(p);}for(const o of hammers)if(!o.gone&&o.i===p.i&&!p.stun&&Math.abs(o.y-p.y-.7)<.6&&dist(o,p)<.6){p.stun=.65;p.vy=-2;p.platform=null;p.x+=c.pick([-1,1])*.6;o.gone=true;}p.pose=p.platform==null?'jump':'idle';}for(let i=hammers.length-1;i>=0;i--)if(hammers[i].gone||hammers[i].y<0)hammers.splice(i,1);race(c,finished,'꼭대기에 먼저 도착했습니다');},render(){c.arena({width:25,depth:7,color:'#accd99'});c.players.forEach(p=>{const base=(p.i-1.5)*5.5;c.draw('tower'+p.i,'box',{x:base,y:5,z:-1.8,sx:3.8,sy:10,sz:1,color:'#b8b5a8'});for(let k=0;k<9;k++){c.draw('platform'+p.i+'_'+k,'box',{x:x(p.i,k),y:h(k,c.time)-.15,z:0,sx:1.7,sy:.3,sz:2.4,color:colors[k%6]});if([2,5,7].includes(k)&&!p.coins.has(k))c.draw('coin'+p.i+'_'+k,'cylinder',{x:x(p.i,k),y:h(k,c.time)+.65,z:0,sx:.45,sy:.1,sz:.45,color:'#e5bf61',rx:Math.PI/2});}c.draw('cloud'+p.i,'sphere',{x:base,y:11,z:0,sx:3,sy:.8,sz:2,color:cream});});hammers.forEach(o=>c.draw('hammer'+o.id,'box',{x:o.x,y:o.y,z:o.z,sx:.65,sy:.3,sz:.5,color:'#768b91',rz:c.time*5}));},timeout(){c.complete([],'누구도 제한 시간 안에 꼭대기에 도착하지 못했습니다');}};
}
function pipes(c){
 c.limit=30;c.view={size:25,eye:[0,27,24],target:[0,0,0]};const cadence=27/26,waves=Array.from({length:26},()=>({pipe:c.int(0,3),brief:c.rand()<.3}));c.players.forEach((p,i)=>{p.x=i%2?6:-6;p.z=i<2?-4.5:4.5;p.hit=-1;p.finalHits=new Set();p.swing=-1;p.swingAge=0;p.lag=c.rand(.16,.35);p.error=c.rand(.06,.18);p.round=-1;});const loc=(p,n)=>({x:p.x+(n%2?2:-2),z:p.z+(n<2?-1.6:1.6)}),shown=(p,n)=>{if(c.time>=27)return!p.finalHits.has(n);const round=Math.min(25,Math.floor(c.time/cadence)),age=c.time%cadence,w=waves[round];return n===w.pipe&&p.hit!==round&&age>=.12&&age<(w.brief?.42:.88);};
 return{update(dt){const final=c.time>=27,round=Math.min(25,Math.floor(c.time/cadence)),age=c.time%cadence,wave=waves[round];c.hint('↑+A 오른쪽 위 / ↓+A 오른쪽 아래 / ↑+B 왼쪽 위 / ↓+B 왼쪽 아래 · 마지막 3초는 네 파이프 모두 등장');for(const p of c.players){if(p.round!==round){p.round=round;p.botPipe=c.rand()<p.error?(wave.pipe+1)%4:wave.pipe;p.botSkip=c.rand()<.06;}const target=final?[0,1,2,3].find(n=>!p.finalHits.has(n)):p.botPipe,active=target!=null&&(final?pulse(c.time,5,p.i*.1):age>.12+p.lag&&age<.26+p.lag&&!p.botSkip),q=c.input(p,()=>({z:target<2?-1:1,a:active&&target%2===1,b:active&&target%2===0}));p.swingAge=Math.max(0,p.swingAge-dt);if((q.ap||q.bp)&&Math.abs(q.z)>.5){const pipe=(q.z<0?0:2)+(q.ap?1:0);p.swing=pipe;p.swingAge=.15;if(shown(p,pipe)){if(final)p.finalHits.add(pipe);else p.hit=round;c.points(p);c.sound?.(380+p.i*40,.06);}}}},render(){c.arena({width:25,depth:20,color:'#b8aa91'});for(const p of c.players){for(let n=0;n<4;n++){const pos=loc(p,n);c.draw('pipe'+p.i+'_'+n,'cylinder',{x:pos.x,y:.45,z:pos.z,sx:1.3,sy:.9,sz:1.3,color:'#91b996'});if(shown(p,n))c.draw('target'+p.i+'_'+n,'sphere',{x:pos.x,y:1.2,z:pos.z,sx:.8,sy:.8,sz:.8,color:'#e1bd78'});label(c,'key'+p.i+'_'+n,(n<2?'↑':'↓')+(n%2?'A':'B'),pos.x,2.2,pos.z,1.2);}if(p.swingAge>0){const pos=loc(p,p.swing);c.draw('mallet'+p.i,'box',{x:pos.x,y:1.4,z:pos.z,sx:1.1,sy:.4,sz:.6,color:p.color});}}},timeout(){c.highest('파이프에서 나온 표적을 가장 많이 맞혔습니다');}};
}
function rocking(c,m={}){
 const classic=!m.titleId||m.titleId==='mp3';c.limit=180;c.view={size:26,eye:[0,26,19],target:[0,0,0]};const length=80,panels=[23,41,59];c.players.forEach((p,i)=>{p.progress=0;p.speed=0;p.stamina=1;p.last=-1;p.spin=0;p.boost=0;p.panel=0;p.cadence=c.rand(4.7,6.3);p.phase=c.rand(0,1);p.x=8-i*.55;p.z=0;});const panelOrange=(index,t)=>Math.floor(t*1.3+index)%2===0;
 return{update(dt){c.hint(`A ↔ B${classic?'(또는 C)':' [원작 L/R]'} 교대로 연타 · 당근 체력이 낮으면 쉬기 · 주황 패널은 가속, 파랑은 감속`);const finished=[];for(const p of c.players){p.spin=Math.max(0,p.spin-dt);p.boost=Math.max(0,p.boost-dt);p.stamina=clamp(p.stamina+dt*.18,0,1);const beat=Math.floor(c.time*p.cadence+p.phase),press=(c.time*p.cadence+p.phase)%1<.35,rest=p.stamina<.25||p.spin>0,q=c.input(p,()=>({a:!rest&&press&&beat%2===0,b:!rest&&press&&beat%2===1}));const left=q.ap,right=q.bp||(classic&&q.cp);if(left!==right&&p.spin===0){const side=left?0:1;if(side!==p.last){p.last=side;p.speed=Math.min(9,p.speed+1.1);p.stamina-=.055;if(p.stamina<=0){p.stamina=0;p.spin=1.6;p.speed=.65;}}}p.speed=Math.max(0,p.speed-dt*2.3);const old=p.progress;p.progress+=p.speed*(p.boost>0?1.5:1)*dt;if(p.panel<panels.length&&p.progress>=panels[p.panel]){if(panelOrange(p.panel,c.time)){p.boost=1.6;p.speed=Math.max(7,p.speed);}else{p.speed*=.25;p.boost=0;}p.panel++;}p.score=Math.floor(p.progress);const a=p.progress/length*TAU,r=8-p.i*.55;p.x=Math.cos(a)*r;p.z=Math.sin(a)*r*.65;p.y=.3+Math.sin(c.time*8)*Math.min(.15,p.speed*.025);p.rotation=-a-Math.PI/2;if(p.spin>0)p.rotation+=c.time*12;if(p.progress>=length)finished.push({ids:[p.i],t:(length-old)/Math.max(.000001,p.progress-old)});}race(c,finished,'목마 경주 결승선에 먼저 도착했습니다');},render(){c.draw('track','cylinder',{x:0,y:-.15,z:0,sx:19,sy:.3,sz:13,color:'#c8b991'});c.draw('infield','cylinder',{x:0,y:.02,z:0,sx:10,sy:.05,sz:5.5,color:'#a0bd98'});c.draw('finish','box',{x:7,y:.05,z:0,sx:4,sy:.05,sz:.12,color:cream});for(let j=0;j<3;j++){const a=panels[j]/length*TAU;c.draw('panel'+j,'box',{x:Math.cos(a)*7.1,y:.07,z:Math.sin(a)*4.6,sx:3.5,sy:.08,sz:1,ry:-a,color:panelOrange(j,c.time)?'#e6a466':'#79afd0'});}c.players.forEach(p=>{c.draw('horse'+p.i,'box',{x:p.x,y:.15,z:p.z,sx:1.25,sy:.6,sz:.6,ry:p.rotation,color:'#b99b77'});label(c,'stamina'+p.i,'🥕 '+Math.round(p.stamina*100)+'%',p.x,2.6,p.z,2.3);});},timeout(){c.complete([],'3분 안에 경주를 완주하지 못했습니다');}};
}
function coconut(c,m={}){
 const stars=m.titleId==='superstars';c.limit=30;c.view={size:23,eye:[0,6,27],target:[0,2,0]};const nuts=[];let id=0;const solo=c.players[0];solo.x=0;solo.z=0;solo.vx=0;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*4;p.z=0;p.y=4;p.jumpY=0;p.pound=false;p.stun=0;p.phase=c.rand(0,1);});
 return{update(dt){c.hint(`1P 좌우로 관성 있는 통 굴리기 / 팀: 좌우 이동 → A 점프 → 공중 ${stars?'A 다시':'C'} 내려찍기로 코코넛`);const threat=nuts.filter(n=>n.y<3&&n.y>.4).sort((a,b)=>Math.abs(a.x-solo.x)-Math.abs(b.x-solo.x))[0],escape=threat?clamp(solo.x+Math.sign(solo.x-threat.x||1)*3,-7,7):Math.sin(c.time*1.3)*5,q0=c.input(solo,()=>({x:clamp((escape-solo.x)*1.4-solo.vx*.6,-1,1)}));solo.vx=(solo.vx+q0.x*14*dt)*Math.exp(-dt*2.1);solo.x=clamp(solo.x+solo.vx*dt,-7.5,7.5);solo.y=.1;solo.rotation=-solo.x*.7;for(const p of c.players.slice(1)){p.stun=Math.max(0,p.stun-dt);const target=clamp(solo.x+solo.vx*.7,-7,7),q=c.input(p,()=>({x:clamp((target-p.x)*1.2,-1,1),a:!p.stun&&((p.jumpY===0&&Math.abs(p.x-target)<1.5&&pulse(c.time,1.1,p.phase))||(stars&&p.jumpY>.9&&p.vy<2)),c:!stars&&p.jumpY>.9&&p.vy<2}));if(!p.stun)p.x=clamp(p.x+q.x*4.2*dt,-7.5,7.5);const old=p.jumpY;p.y=p.jumpY;c.jump(p,{...q,ap:!p.stun&&q.ap},7);if((stars?q.ap&&old>0:q.cp)&&p.y>.1&&!p.stun){p.pound=true;p.vy=-12;}p.jumpY=p.y;if(p.pound&&old>0&&p.jumpY===0){nuts.push({id:id++,x:p.x,y:3.6,vy:0});p.pound=false;c.sound?.(170,.08);}if(p.pound&&p.vy<0)for(const o of c.players.slice(1))if(o!==p&&!o.stun&&Math.abs(o.x-p.x)<.7&&p.jumpY-o.jumpY>.3&&p.jumpY-o.jumpY<1.1){o.stun=.85;o.pose='crouch';}p.y=4+p.jumpY;if(p.stun)p.pose='crouch';}for(const n of nuts){n.vy-=10*dt;n.y+=n.vy*dt;if(n.y<1&&n.y>-.2&&Math.abs(n.x-solo.x)<1)c.complete([1,2,3],'코코넛으로 통을 맞혔습니다');}for(let i=nuts.length-1;i>=0;i--)if(nuts[i].y<-.5)nuts.splice(i,1);},render(){c.arena({width:19,depth:5,color:'#d8c59d'});c.draw('branch','box',{x:0,y:3.82,z:0,sx:17,sy:.3,sz:1.3,color:'#9b9c74'});for(const x of [-7,0,7]){c.draw('trunk'+x,'cylinder',{x,y:1.9,z:-.7,sx:.7,sy:4,sz:.7,color:'#b59573'});c.draw('leaf'+x,'cone',{x,y:5.8,z:-1,sx:4.5,sy:1.2,sz:2,color:'#9cba8a'});}c.draw('barrel','cylinder',{x:solo.x,y:.5,z:0,sx:1.9,sy:1.4,sz:1.9,rx:Math.PI/2,rz:solo.rotation,color:'#b79d77'});nuts.forEach(n=>c.draw('nut'+n.id,'sphere',{x:n.x,y:n.y,z:0,sx:.65,sy:.65,sz:.65,color:'#9d846a'}));},timeout(){c.complete([0],'통이 코코넛을 30초 동안 피했습니다');}};
}
function spotlight(c){
 c.limit=30;c.view={size:23,eye:[0,25,15],target:[0,0,0]};const solo=c.players[0];solo.x=0;solo.z=0;solo.under=false;solo.diveAge=0;solo.breath=0;solo.goal={x:4,z:3};solo.react=0;c.players.slice(1).forEach((p,i)=>{p.x=-9;p.z=(i-1)*4;p.visible=false;p.light={x:(i-1)*5,z:-4};p.goal={x:0,z:0};p.react=c.rand(.1,.25);p.next=0;});
 return{update(dt){c.hint('1P 방향 수영 / A 길게 잠수 · 떠오른 직후 숨 고르기 / 팀 방향으로 세 빛을 동시에 맞추기');solo.breath=Math.max(0,solo.breath-dt);const danger=c.players.slice(1).filter(p=>dist(p.light,solo)<2.4).length;solo.react-=dt;if(solo.react<=0){solo.react=.5;const spots=Array.from({length:8},()=>({x:c.rand(-6.5,6.5),z:c.rand(-4.5,4.5)}));solo.goal=spots.sort((a,b)=>Math.min(...c.players.slice(1).map(p=>dist(p.light,b)))-Math.min(...c.players.slice(1).map(p=>dist(p.light,a))))[0];}const qs=c.input(solo,()=>({...toward(solo,solo.goal.x,solo.goal.z),a:solo.breath===0&&(danger>=2||solo.under)})),wasUnder=solo.under;if(!solo.under&&qs.a&&solo.breath===0){solo.under=true;solo.diveAge=0;}if(solo.under){solo.diveAge+=dt;if(!qs.a||solo.diveAge>=3){solo.under=false;solo.breath=1;}}if(solo.breath===0)c.move(solo,qs,3.5,false);solo.x=clamp(solo.x,-7,7);solo.z=clamp(solo.z,-5,5);solo.visible=!solo.under;solo.y=solo.under?-.7:-.1;for(const p of c.players.slice(1)){if(solo.under&&!wasUnder){p.goal={x:c.rand(-7,7),z:c.rand(-5,5)};p.next=c.time+.7;}if(c.time>=p.next){p.next=c.time+p.react;if(solo.under){if(dist(p.light,p.goal)<1)p.goal={x:c.rand(-7,7),z:c.rand(-5,5)};}else p.goal={x:solo.x+c.rand(-.35,.35),z:solo.z+c.rand(-.35,.35)};}const q=c.input(p,()=>toward(p.light,p.goal.x,p.goal.z));p.light.x=clamp(p.light.x+q.x*4.7*dt,-8,8);p.light.z=clamp(p.light.z+q.z*4.7*dt,-6,6);}if(!solo.under&&c.players.slice(1).every(p=>dist(p.light,solo)<1.35))c.complete([1,2,3],'세 탐조등이 수면 위 수영자를 동시에 비췄습니다');},render(){c.arena({width:18,depth:14,color:'#6a92a7'});c.draw('pool','box',{x:0,y:.03,z:0,sx:16,sy:.07,sz:12,color:'#517d94'});for(const p of c.players.slice(1))disc(c,'light'+p.i,p.light.x,p.light.z,1.35,['','#e19b9c','#92badb','#a0cbab'][p.i],.1+p.i*.003);if(solo.under&&solo.diveAge<.65)for(let i=0;i<3;i++)c.draw('bubble'+i,'sphere',{x:solo.x+Math.sin(i*2)*.35,y:.14,z:solo.z+Math.cos(i*2)*.3,sx:.15,sy:.15,sz:.15,color:cream,opacity:.7});if(solo.breath>0)label(c,'breath','숨 고르기',solo.x,2,solo.z,3);},timeout(){c.complete([0],'세 탐조등을 끝까지 피했습니다');}};
}
function boulder(c){
 c.limit=30;c.view={size:24,eye:[0,18,24],target:[0,2,0]};const balls=[];let id=0,aim=0,cool=0;const solo=c.players[0];solo.x=0;solo.z=-8;solo.y=4.5;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*4;p.z=6.5;p.stun=0;p.phase=c.rand(0,1);p.dodge=c.rand(.65,1);});
 return{update(dt){c.hint('1P 좌우 조준 / A 바위 투하 · 팀 방향 이동, 한 명이라도 언덕 정상에 도착하면 승리');cool=Math.max(0,cool-dt);const target=group(c).sort((a,b)=>a.z-b.z)[0],wanted=target?Math.atan2(target.x,target.z+7):0,q0=c.input(solo,()=>({x:clamp((wanted-aim)*3,-1,1),a:cool===0&&pulse(c.time,2.6,.1)}));aim=clamp(aim+q0.x*1.6*dt,-1.12,1.12);if(q0.ap&&cool===0){cool=.65;balls.push({id:id++,x:0,z:-7,vx:Math.sin(aim)*7,vz:Math.cos(aim)*7,hit:new Set()});}for(const b of balls){b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>6.7){b.x=clamp(b.x,-6.7,6.7);b.vx*=-1;}}const finish=[];for(const p of c.players.slice(1)){p.stun=Math.max(0,p.stun-dt);const danger=balls.filter(b=>!b.hit.has(p.i)&&b.z<p.z&&p.z-b.z<4).sort((a,b)=>a.z-b.z)[0],projected=danger?danger.x+danger.vx*(p.z-danger.z)/Math.max(.1,danger.vz):0,dodge=danger&&Math.abs(projected-p.x)<1.8?Math.sign(p.x-projected||p.i-2||1)*p.dodge:0,q=c.input(p,()=>({x:dodge,z:-1})),old=p.z;if(p.stun){p.z=Math.min(6.5,p.z+3.4*dt);p.pose='crouch';}else c.move(p,q,2.35,false);p.x=clamp(p.x,-6.3,6.3);p.z=Math.min(6.5,p.z);for(const b of balls)if(!b.hit.has(p.i)&&dist(p,b)<1.2){b.hit.add(p.i);p.stun=.9;}p.y=(7-p.z)*.27;p.score=Math.round((6.5-p.z)/13.5*100);if(p.z<=-7)finish.push({ids:[1,2,3],t:(old+7)/Math.max(.0001,old-p.z)});}race(c,finish,'팀원 한 명이 언덕 정상에 도착했습니다');for(let i=balls.length-1;i>=0;i--)if(balls[i].z>9)balls.splice(i,1);},render(){c.draw('slope','box',{x:0,y:1.7,z:0,sx:14,sy:.35,sz:15.5,rx:.264,color:'#cdbc98'});for(const x of [-7,7])c.draw('wall'+x,'box',{x,y:2.2,z:0,sx:.35,sy:1,sz:15.5,rx:.264,color:'#a59b80'});c.draw('machine','box',{x:0,y:4,z:-7.8,sx:2,sy:1,sz:1.3,color:'#92aab3'});c.draw('aim','box',{x:Math.sin(aim),y:4,z:-7+Math.cos(aim),sx:.22,sy:.2,sz:2,ry:aim,color:cream});balls.forEach(b=>c.draw('boulder'+b.id,'sphere',{x:b.x,y:(7-b.z)*.27+.7,z:b.z,sx:1.5,sy:1.5,sz:1.5,color:'#939a96',rx:c.time*4}));},timeout(){c.complete([0],'세 등반자를 제한 시간 동안 막았습니다');}};
}
function cogs(c){
 c.limit=30;c.view={size:24,eye:[0,25,21],target:[0,0,0]};const bullets=[];let turn=0,next=.8,id=0;const solo=c.players[0];solo.x=-9;solo.z=0;c.players.slice(1).forEach((p,i)=>{const a=i*TAU/3;p.x=Math.cos(a)*3;p.z=Math.sin(a)*3;p.lag=c.rand(.12,.3);p.goal={x:p.x,z:p.z};p.react=0;});
 return{update(dt){c.hint('1P 좌우로 톱니 회전 / 팀 방향 이동으로 날아오는 탄환 피하기 · 한 명 생존해도 팀 승리');const q0=c.input(solo,()=>({x:Math.sin(c.time*2)+Math.sin(c.time*.7)>.1?1:-1})),angle=q0.x*1.45*dt;turn+=angle;next-=dt;if(next<=0){next=c.rand(.6,1.05);const a=c.rand(0,TAU),offset=c.rand(-3,3);bullets.push({id:id++,x:Math.cos(a)*11+Math.cos(a+Math.PI/2)*offset,z:Math.sin(a)*11+Math.sin(a+Math.PI/2)*offset,vx:-Math.cos(a)*8,vz:-Math.sin(a)*8,warning:.65,age:0});}for(const b of bullets){b.warning-=dt;b.age+=dt;if(b.warning<=0){b.x+=b.vx*dt;b.z+=b.vz*dt;}}for(const p of group(c)){const x=p.x,z=p.z;p.x=x*Math.cos(angle)-z*Math.sin(angle);p.z=x*Math.sin(angle)+z*Math.cos(angle);p.react-=dt;if(p.react<=0){p.react=p.lag;const danger=bullets.filter(b=>Math.hypot(b.x+b.vx*.25-p.x,b.z+b.vz*.25-p.z)<3).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(danger){const left={x:-danger.vz,z:danger.vx},sign=(p.x-danger.x)*left.x+(p.z-danger.z)*left.z>=0?1:-1;p.goal={x:p.x+left.x/8*sign*2,z:p.z+left.z/8*sign*2};}else if(dist(p,p.goal)<.3)p.goal={x:c.rand(-3,3),z:c.rand(-3,3)};}const q=c.input(p,()=>toward(p,p.goal.x,p.goal.z));c.move(p,q,4.2,false);const r=Math.hypot(p.x,p.z);if(r>5.7){p.x*=5.7/r;p.z*=5.7/r;}for(const b of bullets)if(b.warning<=0&&dist(p,b)<.85)c.eliminate(p);}for(let i=bullets.length-1;i>=0;i--)if(bullets[i].age>4)bullets.splice(i,1);if(!group(c).length)c.complete([0],'회전하는 톱니 위 세 명이 탄환에 맞았습니다');},render(){disc(c,'gear',0,0,6.2,'#b1b3a1');for(let i=0;i<16;i++){const a=turn+i*TAU/16;c.draw('tooth'+i,'box',{x:Math.cos(a)*6.2,y:.02,z:Math.sin(a)*6.2,sx:1,sy:.25,sz:.8,ry:-a,color:'#b1b3a1'});}for(let i=0;i<6;i++){const a=turn+i*TAU/6;c.draw('spoke'+i,'box',{x:Math.cos(a)*3,y:.1,z:Math.sin(a)*3,sx:5,sy:.07,sz:.14,ry:-a,color:'#829b97'});}disc(c,'station',solo.x,solo.z,1.3,'#92acb5');for(const b of bullets){c.draw('bullet'+b.id,'cylinder',{x:b.x,y:.6,z:b.z,sx:.9,sy:1.4,sz:.9,rx:Math.PI/2,rz:Math.atan2(b.vz,b.vx)+Math.PI/2,color:b.warning>0?'#e2b475':'#637982'});if(b.warning>0)label(c,'warning'+b.id,'!',b.x,2,b.z,1);}},timeout(){c.complete(group(c).length?[1,2,3]:[0],'한 명이라도 남은 팀이 승리합니다');}};
}
function tidal(c){
 c.limit=30;const waves=[];let id=0;const solo=c.players[0];solo.x=solo.z=0;solo.y=0;solo.peak=0;solo.poundHeight=0;solo.phase=c.rand(0,1);c.players.slice(1).forEach((p,i)=>{const a=i*TAU/3;p.x=Math.cos(a)*3.5;p.z=Math.sin(a)*3.5;p.vx=p.vz=0;p.stun=0;p.lag=c.rand(.08,.2);p.decided=-1;p.miss=false;});
 return{update(dt){c.hint('1P A 점프 / 공중 C 내려찍기 · 높을수록 큰 물결 / 팀 방향 이동·A 점프로 물결을 넘어 생존');const q0=c.input(solo,()=>({a:solo.y===0&&pulse(c.time,1.25,solo.phase),c:solo.y>1.2&&solo.vy<2})),old=solo.y;c.jump(solo,q0,7.6);solo.peak=Math.max(solo.peak,solo.y);if(q0.cp&&solo.y>.1){solo.poundHeight=solo.y;solo.vy=-14;}if(old>0&&solo.y===0){const height=solo.poundHeight>0?.45+solo.poundHeight*.57:.35;waves.push({id:id++,r:1.4,oldr:1.4,height,hit:new Set()});solo.peak=0;solo.poundHeight=0;c.sound?.(140, .12);}for(const w of waves){w.oldr=w.r;w.r+=4.4*dt;}for(const p of group(c)){p.stun=Math.max(0,p.stun-dt);const r=Math.hypot(p.x,p.z),danger=waves.filter(w=>!w.hit.has(p.i)&&w.r<r+.3).sort((a,b)=>b.r-a.r)[0],jump=!!danger&&(r-danger.r)/4.4<.32+p.lag&&(r-danger.r)>0;if(danger&&p.decided!==danger.id){p.decided=danger.id;p.miss=c.rand()<.12;}const q=c.input(p,()=>({...toward(p,p.x/(r||1)*3,p.z/(r||1)*3),a:jump&&!p.miss&&p.y===0}));if(!p.stun)c.move(p,q,3.2,false);c.jump(p,q,7.8);p.vx*=Math.exp(-dt*2);p.vz*=Math.exp(-dt*2);p.x+=p.vx*dt;p.z+=p.vz*dt;let radius=Math.hypot(p.x,p.z);if(radius<1.5){p.x*=1.5/(radius||1);p.z*=1.5/(radius||1);radius=1.5;}for(const w of waves)if(!w.hit.has(p.i)&&w.oldr<=radius+.35&&w.r>=radius-.35){w.hit.add(p.i);if(p.y<w.height){const force=3+w.height*2.2;p.vx+=p.x/radius*force;p.vz+=p.z/radius*force;p.stun=.35;}}if(radius>6.2)c.eliminate(p);}for(let i=waves.length-1;i>=0;i--)if(waves[i].r>7)waves.splice(i,1);if(!group(c).length)c.complete([0],'세 명을 물결로 가장자리 밖으로 밀어냈습니다');},render(){disc(c,'water',0,0,6.2,'#8cbfcc');c.draw('boat','box',{x:0,y:-.1,z:0,sx:2.7,sy:.55,sz:1.8,color:'#bda47f'});for(const w of waves)c.draw('wave'+w.id,'ring',{x:0,y:w.height*.35,z:0,sx:w.r*2,sy:w.r*2,sz:1,rx:-Math.PI/2,color:'#d3eff0',opacity:.9});for(let i=0;i<20;i++){const a=i*TAU/20;c.draw('rim'+i,'sphere',{x:Math.cos(a)*6.4,y:-.3,z:Math.sin(a)*6.4,sx:1,sy:.7,sz:1,color:'#adb0a2'});}},timeout(){c.complete(group(c).length?[1,2,3]:[0],'팀원 한 명이라도 살아남으면 팀 승리');}};
}
export const games={
 'Treadmill Grill':grill,'Parasol Plummet':parasol,'Messy Memory':messy,'M.P.I.Q.':quiz,'Curtain Call':curtain,'Cheep Cheep Chase':chase,'Aces High':aces,"Bounce 'n' Trounce":bounce,'Eye Sore':eyeSore,'The Beat Goes On':beat,'Water Whirled':water,'Frigid Bridges':bridges,'Awful Tower':tower,'Pipe Cleaners':pipes,"Rockin' Raceway":rocking,'Coconut Conk':coconut,'Spotlight Swim':spotlight,'Boulder Ball':boulder,'Crazy Cogs':cogs,'Tidal Toss':tidal
};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['mp3']]));
for(const name of ['Messy Memory','Cheep Cheep Chase','Coconut Conk','Boulder Ball'])supportedTitles[name].push('superstars');
supportedTitles["Rockin' Raceway"].push('top-100','superstars');
export const aliases={};
export const notes={
 'Treadmill Grill':'MP3: 줄어드는 컨베이어, 외곽 불과 추적 불, 점프·주먹·내려찍기. 둘 이상 생존한 시간 종료는 무승부. 컨베이어 배치와 불의 이동 패턴은 새로 구성했습니다. N64 Z는 C.',
 'Parasol Plummet':'MP3 코인 수집: A 우산 전환, 열린 우산으로 코인 1·주머니 5 수집, 망치에 맞으면 우산이 닫힙니다. 화면 위에서는 자동으로 닫히고 아래에서는 열립니다. 각자 얻은 코인을 유지합니다. 투척 궤적과 비행 속도는 재구성했습니다.',
 'Messy Memory':'MP3: 5초 기억 후 30초 복원, 10개 중 3개는 남고 7개는 바닥으로 떨어집니다. 커서 이동·A 집기/교환·C 커튼. MP3는 최고점 3점 이하 무승부, Superstars는 전원 0점일 때만 무승부이며 B로 커튼을 여닫습니다. 정답 수는 종료 후 공개합니다. 소품은 플라밍고 세계의 기하 도형으로 바꿨습니다.',
 'M.P.I.Q.':'MP3: A로 먼저 응답권, A/B/C로 답 선택, 정답 3개 선승. 오답·시간 초과자는 다음 문제에 참여할 수 없습니다. 10문제 종료 시 단독 최고점만 승리. 출처에 있는 게임 지식 문제를 한국어로 다시 썼습니다.',
 'Curtain Call':'MP3: 세 차례 기억·위치 문제. 좌우로 답 선택, A 확정, B 취소. 잘못 답한 선수는 탈락하고 세 문제를 맞힌 생존자가 함께 승리합니다. 캐릭터 대신 새·거북·유령을 나타내는 도형을 사용합니다.',
 'Cheep Cheep Chase':'MP3: A 연타로 수영, B/C 잠수로 기뢰 회피. 뒤따르는 물고기에 잡히면 탈락. 최초 도착자 승리, 전원 잡히면 무승부. Superstars는 아래 방향으로 잠수합니다. 코스와 잠수 회복 간격은 재구성, 무한 진행 방지 90초 상한.',
 'Aces High':'MP3: 조타, A 가속·B 감속·C 짧게 보통탄·길게 눌렀다 놓으면 유도탄. 경계 U턴으로 유도탄을 떨치며 2회 피격 탈락. 시간 종료는 체력 단독 최고만 승리하고 동률은 무승부. 비행장·미사일 물리와 발사 간격은 재구성했습니다.',
 "Bounce 'n' Trounce":'MP3: 공 위에서 관성 이동, A 점프·공중 C 회전 공격. 바닥이 차례로 떨어지며 떨어진 선수는 탈락. 둘 이상 남은 시간 종료는 무승부. 발판 패턴·공의 물리는 새로 구성했습니다.',
 'Eye Sore':'MP3: 눈 주위를 같은 방향으로 15바퀴 돌아야 합니다. 왕복은 진행을 상쇄하고 눈이 점점 작아집니다. 눈·불 충돌은 정지, 첫 15바퀴 승리. 구역과 불 배치는 재구성, 무한 진행 방지 60초 상한.',
 'The Beat Goes On':'MP3: 네 박자를 들은 뒤 차례대로 반복하고 한 박자를 추가. A/B/C 세 음, 실수하거나 박자를 놓치면 탈락. 마지막 한 명 승리, 16박자를 버티면 무승부. 새로 만든 음과 템포를 사용합니다.',
 'Water Whirled':'MP3: A 가속·좌우 조타, 모터보트 5바퀴 선착순, 180초 내 완주자가 없으면 무승부. 실제 조타·벽 충돌 감속·역주행을 구현했습니다. 원형 수로와 보트 물리는 재구성했습니다.',
 'Frigid Bridges':'MP3: 방향만으로 미끄러운 다리를 오가며 블록 세 개 운반, 물고기 충돌과 추락 후 출발점 복귀. 최초 세 개 승리. 길·얼음 관성·물고기 주기는 재구성, 무한 진행 방지 180초 상한.',
 'Awful Tower':'MP3: 방향+A 점프로 오르내리는 발판을 타고 정상 선착순, 망치 피격은 낙하·일시 정지, 추가 코인은 별도 수집. 60초 내 도착자 없으면 무승부. 아홉 발판의 새 코스로 구성했습니다.',
 'Pipe Cleaners':'MP3: ↑/↓와 A=오른쪽·B=왼쪽 조합으로 네 파이프를 칩니다. 30초 최다 명중 승리, 잠깐 나온 표적도 맞힐 수 있고 마지막 3초에는 네 파이프가 모두 열립니다. 출현 순서·표적 외형은 재구성했습니다.',
 "Rockin' Raceway":'MP3: A와 B 또는 C를 번갈아 눌러 전진. 과속으로 체력이 떨어지면 잠시 느려지고, 주황/파랑 당근 패널은 가속/감속. 180초 내 최초 완주 승리. Top100/Superstars의 L/R은 키보드 A/B로 옮겼습니다. 코스 길이·체력 수치·패널 주기는 재구성했습니다.',
 'Coconut Conk':'MP3 1대3: 관성 있는 통은 좌우 이동, 세 명은 가지 위 이동·A점프→C내려찍기로 코코넛 낙하. 다른 팀원을 찍으면 잠시 납작해집니다. 통에 한 번 맞히면 팀 승리, 30초 생존은 개인 승리. Superstars는 A 점프 후 공중에서 A를 다시 눌러 내려찍습니다. 나무와 낙하 물리는 재구성했습니다.',
 'Spotlight Swim':'MP3 1대3: A를 눌러 잠수, 수면 복귀 뒤 잠시 움직일 수 없습니다. 세 빛을 수면 위 선수에게 동시에 맞히면 팀 승리, 30초 회피는 개인 승리. CPU는 잠수 중 숨은 위치를 추적하지 않고 빛을 흩뜨립니다. 잠수 3초·숨 고르기 1초·빛 반경은 재구성했습니다.',
 'Boulder Ball':'MP3 1대3: 좌우 조준·A 바위 투하, 팀은 방향으로 언덕을 오릅니다. 바위는 벽에 반사되고 피격자는 잠시 납작해져 아래로 밀립니다. 한 명 정상 도착으로 팀 전체 승리, 30초 저지는 개인 승리. 선정된 Superstars판도 같은 목표와 버튼입니다. 경사와 바위 궤적 수치는 재구성했습니다.',
 'Crazy Cogs':'MP3 1대3: 개인이 좌우로 톱니를 돌리고 팀은 실제 회전 이동을 받으며 탄환을 피합니다. 탄환에 맞으면 탈락, 30초에 한 명 남아도 팀 전체 승리. 원작에 없는 추락 탈락은 추가하지 않았습니다. 기어와 탄환 패턴은 재구성했습니다.',
 'Tidal Toss':'MP3 1대3: 개인의 점프 착지·공중 C내려찍기로 물결 생성, 내려찍은 높이가 클수록 높은 물결. 팀은 방향+A점프로 피하며 피격 시 밖으로 밀려납니다. 전원 추락은 개인 승리, 30초 한 명 생존은 팀 전체 승리. 물리·파도 높이는 재구성했습니다.'
};
