import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,colors=['#ee91b0','#7dbbe1','#edc46d','#8fc2a2'];
const pulse=(t,f=5,o=0)=>((t*f+o)%1)<.4;
const label=(c,id,text,x=0,y=4,z=0,sx=6)=>c.draw(id,'text',{x,y,z,sx,sy:.9,text});
const ring=(c,id,x,z,r,color)=>c.draw(id,'cylinder',{x,y:.02,z,sx:r*2,sy:.04,sz:r*2,color});
function solo(c){c.players.slice(1).forEach(p=>{p.visible=false;p.alive=false;});c.players[0].x=0;c.players[0].z=3;}
function collectEnd(c,reason='각자 모은 코인을 받습니다'){c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),reason);}
function teamEnd(c,values,reason){const best=Math.max(...values);c.complete(values.flatMap((n,i)=>n===best?[i*2,i*2+1]:[]),reason);}
function cast(c){
 c.limit=60;c.view={size:23,eye:[0,25,18],target:[0,0,-1]};const loot=[],lines=c.players.map((p,i)=>{p.x=(i-1.5)*4;p.z=5;return{state:'idle',lane:0,z:5,cargo:0,phase:c.rand(0,1)};});let next=0,id=0;
 return {update(dt){next-=dt;if(next<0){next=.62;const lane=c.int(0,2);loot.push({id:id++,x:-10,z:2-lane*3,lane,value:c.pick([1,1,5,10]),speed:1+lane*.35});}for(const o of loot)o.x+=o.speed*dt;c.hint('위·아래로 거리 선택 / A 던지기 / B 반복해 감기 · 세 줄의 보물을 노리세요');for(const p of c.players){const s=lines[p.i],possible=loot.filter(o=>!o.taken&&o.x<p.x+1).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x)),target=possible[0];const q=c.input(p,()=>({z:target?Math.sign(target.lane-s.lane)*(pulse(c.time,4)?1:0):0,a:s.state==='idle'&&!!target&&target.lane===s.lane&&Math.abs(target.x+target.speed*((5-(2-s.lane*3))/13)-p.x)<.55,b:s.state==='reel'&&pulse(c.time,6+s.phase,s.phase)}));if(s.state==='idle'){if(q.z>.5&&(!s.lastZ||s.lastZ<=.5))s.lane=Math.min(2,s.lane+1);if(q.z<-.5&&(!s.lastZ||s.lastZ>=-.5))s.lane=Math.max(0,s.lane-1);if(q.ap){s.state='out';s.cargo=0;s.z=5;}}else if(s.state==='out'){s.z-=13*dt;if(s.z<=2-s.lane*3){s.z=2-s.lane*3;const item=loot.find(o=>!o.taken&&o.lane===s.lane&&Math.abs(o.x-p.x)<.65);if(item){item.taken=true;s.cargo=item.value;}s.state='reel';}}else if(q.bp){s.z+=.65;if(s.z>=5){c.points(p,s.cargo);s.state='idle';s.z=5;}}s.lastZ=q.z;}for(let i=loot.length-1;i>=0;i--)if(loot[i].taken||loot[i].x>11)loot.splice(i,1);},render(){c.arena({width:23,depth:18,color:'#85c7cf'});c.draw('shore','box',{x:0,y:-.05,z:5.5,sx:20,sy:.35,sz:3,color:'#e6ce9d'});loot.forEach(o=>c.draw('loot'+o.id,o.value===1?'cylinder':'box',{x:o.x,y:.2,z:o.z,sx:o.value===10?.7:.5,sy:.45,sz:.5,color:o.value===10?'#b98157':'#eac567'}));lines.forEach((s,i)=>{const x=c.players[i].x;label(c,'lane'+i,`${s.lane+1}`,x,2.7,5,1.4);if(s.state!=='idle'){c.draw('line'+i,'box',{x,y:.15,z:(5+s.z)/2,sx:.035,sy:.035,sz:5-s.z,color:'#f6e6bb'});c.draw('glove'+i,'sphere',{x,y:.3,z:s.z,sx:.65,sy:.3,sz:.65,color:c.players[i].color});}});},timeout(){collectEnd(c);}};
}
function grab(c){
 c.limit=60;c.bounds={x:6.5,z:5};c.players.forEach((p,i)=>{p.x=(i%2-.5)*7;p.z=(i<2?-1:1)*3;p.wallet=30;p.score=0;p.face={x:0,z:-1};p.holding=null;p.heldBy=null;p.escape=0;p.botPhase=c.rand(0,1);});
 function release(p){if(p.holding!=null){c.players[p.holding].heldBy=null;c.players[p.holding].escape=0;}p.holding=null;}
 return {update(dt){c.hint('방향 이동 / A 점프 / B 뒤에서 붙잡기·빼앗기·빠져나오기');for(const p of c.players){const target=c.players.filter(o=>o!==p&&o.wallet>0).sort((a,b)=>dist(p,a)-dist(p,b))[0],goal=target?{x:target.x-target.face.x*1.1,z:target.z-target.face.z*1.1}:{x:0,z:0};const q=c.input(p,()=>({...toward(p,goal.x,goal.z),b:pulse(c.time,5.5,p.botPhase),a:false}));if(p.heldBy!=null){if(q.bp&&++p.escape>=3)release(c.players[p.heldBy]);}else if(p.holding!=null){const o=c.players[p.holding];p.x=o.x-o.face.x*.9;p.z=o.z-o.face.z*.9;if(q.bp&&o.wallet>0){o.wallet--;p.wallet++;}if(o.wallet===0||q.ap)release(p);}else{c.move(p,q,3.7);c.jump(p,q);if(Math.hypot(q.x,q.z)>.1)p.face=toward({x:0,z:0},q.x,q.z);if(q.bp){const victim=c.players.find(o=>o!==p&&o.heldBy==null&&o.holding==null&&o.y<.3&&dist(p,o)<1.5&&((p.x-o.x)*o.face.x+(p.z-o.z)*o.face.z)<-.2);if(victim){p.holding=victim.i;victim.heldBy=p.i;victim.escape=0;}}}p.score=p.wallet-30;}},render(){c.arena({width:15,depth:12,color:'#cfb991'});for(const p of c.players){c.draw('bag'+p.i,'sphere',{x:p.x-p.face.x*.5,y:.75,z:p.z-p.face.z*.5,sx:.65,sy:.8,sz:.55,color:'#c89c63'});label(c,'wallet'+p.i,`${p.wallet}`,p.x,2.8,p.z,2);}},timeout(){for(const p of c.players)p.score=p.wallet-30;c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'처음 30코인에서 각자의 증감분을 반영합니다');}};
}
function hammer(c){
 c.limit=30;c.bounds={x:8,z:8};let next=0,id=0;const things=[];c.players.forEach((p,i)=>{p.x=(i%2-.5)*4;p.z=(i<2?-1:1)*2;p.stun=0;p.vx=p.vz=0;});
 return {update(dt){next-=dt;if(next<0){next=.2;const angle=c.rand(0,TAU),r=c.rand(.3,4.7);things.push({id:id++,x:Math.cos(angle)*r,z:Math.sin(angle)*r,y:6,vy:-2,value:c.pick([1,1,1,5,-1]),life:0});}for(const o of things){o.vy-=12*dt;o.y=Math.max(.15,o.y+o.vy*dt);if(o.y===.15)o.life+=dt;}
 c.hint('방향 이동 / A 점프 / C 내려찍기 · 코인은 줍고 망치는 피하세요');for(const p of c.players){if(!p.alive)continue;p.stun=Math.max(0,p.stun-dt);const target=things.filter(o=>o.value>0&&!o.gone).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...toward(p,target?.x||0,target?.z||0),a:p.y===0&&things.some(o=>o.value<0&&dist(p,o)<1.2&&o.y<2)}));if(!p.stun)c.move(p,q,4.5,false);c.jump(p,q);if(q.cp&&p.y>0)p.vy=-13;p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-5*dt);p.vz*=Math.exp(-5*dt);if(Math.hypot(p.x,p.z)>5.5)c.eliminate(p);}for(const o of things){const ps=c.players.filter(p=>p.alive&&dist(p,o)<.6&&Math.abs(o.y-p.y-.6)<.8).sort((a,b)=>dist(a,o)-dist(b,o));if(ps.length){const close=ps.filter(p=>Math.abs(dist(p,o)-dist(ps[0],o))<1e-7),p=c.pick(close);o.gone=true;if(o.value>0)c.points(p,o.value);else{p.stun=.7;p.vx+=p.x*1.4;p.vz+=p.z*1.4;}}}for(let i=things.length-1;i>=0;i--)if(things[i].gone||things[i].life>2)things.splice(i,1);if(c.players.every(p=>!p.alive))collectEnd(c,'전원 낙하 · 이미 얻은 코인은 유지');},render(){c.arena({width:11,depth:11,shape:'cylinder',height:2,color:'#bdc09c'});c.draw('hostCloud','sphere',{x:0,y:6.8,z:0,sx:3,sy:1,sz:2,color:'#f5f1df'});things.forEach(o=>{ring(c,'shadow'+o.id,o.x,o.z,.2,'#aaac8d');c.draw('drop'+o.id,o.value===1?'cylinder':'box',{x:o.x,y:o.y,z:o.z,sx:o.value===5?.6:.45,sy:o.value<0?.2:.45,sz:o.value<0?.8:.45,color:o.value<0?'#657783':'#f0c459'});});},timeout(){collectEnd(c);}};
}
function coinBlocks(c){
 c.limit=60;c.bounds={x:6,z:5};const blocks=Array.from({length:9},(_,i)=>({x:(i%3-1)*3.4,z:(Math.floor(i/3)-1)*3,hp:c.int(1,12),cool:0}));let paid=false;
 function finish(){if(paid)return;paid=true;for(const p of c.players)p.score=Math.floor(p.score/2);collectEnd(c,'얻은 코인의 절반을 받습니다');}
 return {update(dt){c.hint('방향 이동 / A 점프 · 블록을 아래에서 치세요');blocks.forEach(b=>b.cool=Math.max(0,b.cool-dt));for(const p of c.players){const target=blocks.filter(b=>b.hp>0).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...toward(p,target?.x||0,target?.z||0,target&&dist(p,target)>.1?1:0),a:!!target&&dist(p,target)<.5&&p.y===0}));c.move(p,q,4);c.jump(p,q);for(const b of blocks)if(b.hp>0&&b.cool===0&&dist(p,b)<.65&&p.y>.8&&p.vy>0){b.hp--;b.cool=.18;c.points(p);p.vy=-1;}}if(blocks.every(b=>b.hp===0))finish();},render(){c.arena({width:15,depth:12,color:'#c8c397'});blocks.forEach((b,i)=>{if(b.hp<=0)return;c.draw('block'+i,'box',{x:b.x,y:2.5,z:b.z,sx:1.1,sy:1.1,sz:1.1,color:'#e5bf61'});label(c,'question'+i,'?',b.x,2.7,b.z,1);});},timeout:finish};
}
function mountain(c){
 c.limit=30;c.bounds={x:7,z:5};const boxes=Array.from({length:15},(_,i)=>({x:(i%5-2)*2.1,z:(Math.floor(i/5)-1)*2,stack:c.int(1,3),trap:c.rand()<.17})),coins=[];let id=0;c.players.forEach(p=>{p.cool=0;p.stun=0;});
 return {update(dt){c.hint('방향 이동 / A 점프 / B 공격 / C 내려찍기');for(const p of c.players){p.cool=Math.max(0,p.cool-dt);p.stun=Math.max(0,p.stun-dt);const target=coins.filter(o=>!o.gone).sort((a,b)=>dist(p,a)-dist(p,b))[0]||boxes.filter(b=>b.stack>0&&!b.revealed).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...toward(p,target?.x||0,target?.z||0,target&&dist(p,target)>(coins.includes(target)?.12:.85)?1:0),b:pulse(c.time,4,p.i*.2),a:false}));if(!p.stun)c.move(p,q,4);c.jump(p,q);if(q.cp&&p.y>0){p.pound=true;p.vy=-14;}if((q.bp||p.pound&&p.y===0)&&p.cool===0){p.cool=.35;p.pound=false;const b=boxes.filter(b=>b.stack>0&&dist(p,b)<1.6).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(b){if(b.trap){b.revealed=true;p.stun=.6;const v=toward(b,p.x,p.z);p.x+=v.x;p.z+=v.z;}else{b.stack--;coins.push({id:id++,x:b.x+c.rand(-.5,.5),z:b.z+c.rand(-.5,.5),value:c.rand()<.2?5:1,age:0});}}}for(const coin of coins)if(!coin.gone&&dist(p,coin)<.7){coin.gone=true;c.points(p,coin.value);}}coins.forEach(o=>o.age+=dt);for(let i=coins.length-1;i>=0;i--)if(coins[i].gone||coins[i].age>8)coins.splice(i,1);if(boxes.every(b=>b.stack===0||b.trap)&&coins.length===0)collectEnd(c);},render(){c.arena({width:17,depth:13,color:'#d3b68c'});boxes.forEach((b,i)=>{for(let j=0;j<b.stack;j++)c.draw('crate'+i+'_'+j,'box',{x:b.x,y:.55+j*1.05,z:b.z,sx:1,sy:1,sz:1,color:b.revealed?'#a89985':'#bd8c5c'});});coins.forEach(o=>c.draw('coin'+o.id,'cylinder',{x:o.x,y:.35,z:o.z,sx:.55,sy:.13,sz:.55,color:'#f0c65e'}));},timeout(){collectEnd(c);}};
}
function memory(c){
 solo(c);c.limit=45;c.bounds={x:4,z:4};const faces=c.shuffle([0,0,1,1,2,2,3,3,4]),known=Array(9).fill(null),matched=Array(9).fill(false),shown=[];let hideAt=0,stun=0,pound=false,pairs=0;const spots=Array.from({length:9},(_,i)=>({x:(i%3-1)*2.3,z:(Math.floor(i/3)-1)*2.3}));
 return {update(dt){const p=c.players[0];stun=Math.max(0,stun-dt);if(hideAt&&c.time>=hideAt){shown.length=0;hideAt=0;}let choose=-1;if(shown.length===1)choose=known.findIndex((v,i)=>i!==shown[0]&&!matched[i]&&v===faces[shown[0]]);if(choose<0)choose=known.findIndex((v,i)=>!matched[i]&&!shown.includes(i)&&v==null);if(choose<0)choose=known.findIndex((v,i)=>!matched[i]&&!shown.includes(i)&&v!==4);const goal=spots[Math.max(0,choose)],q=c.input(p,()=>({...toward(p,goal.x,goal.z,dist(p,goal)>.1?1:0),a:!hideAt&&dist(p,goal)<.3&&p.y===0,c:p.y>.8}));c.hint(`A 점프 / C 내려찍기 · ${pairs}/4쌍 · 기억해서 같은 그림 찾기`);if(!stun)c.move(p,q,4);c.jump(p,q);if(q.cp&&p.y>0){pound=true;p.vy=-13;}if(pound&&p.y===0){pound=false;const i=spots.findIndex(s=>dist(p,s)<.85);if(i>=0&&!matched[i]&&!shown.includes(i)&&!hideAt&&!stun){known[i]=faces[i];if(faces[i]===4){stun=.8;shown.push(i);hideAt=c.time+.8;}else{shown.push(i);if(shown.length===2){if(faces[shown[0]]===faces[shown[1]]){shown.forEach(j=>matched[j]=true);shown.length=0;pairs++;p.score=pairs;if(pairs===4)c.complete([0],'네 쌍을 모두 맞췄습니다');}else hideAt=c.time+.85;}}}}},render(){c.arena({width:11,depth:11,color:'#cab991'});spots.forEach((s,i)=>{const reveal=matched[i]||shown.includes(i);c.draw('panel'+i,'box',{x:s.x,y:-.05,z:s.z,sx:2.15,sy:.1,sz:2.15,color:reveal?(faces[i]===4?'#5f6975':colors[faces[i]]):'#e5cb8c'});label(c,'face'+i,reveal?(faces[i]===4?'!':String(faces[i]+1)):'?',s.x,.12,s.z,1.3);});},timeout(){c.complete([],'네 쌍을 모두 찾지 못했습니다');}};
}
function ground(c){
 solo(c);c.limit=33;c.bounds={x:5,z:4};const posts=Array.from({length:12},(_,i)=>({x:(i%4-1.5)*2.1,z:(Math.floor(i/4)-1)*2.2,flat:false,down:false}));c.shuffle(posts).slice(0,6).forEach(p=>p.flat=true);let pound=false,stun=0;
 return {update(dt){const p=c.players[0],ready=c.time>=3;stun=Math.max(0,stun-dt);const target=posts.find(s=>s.flat&&!s.down),q=c.input(p,()=>({...toward(p,target?.x||0,target?.z||0,target&&dist(p,target)>.12?1:0),a:ready&&target&&dist(p,target)<.3&&p.y===0,c:p.y>.8}));c.hint(ready?'방향 이동 / A 점프 / C 내려찍기 · 평평했던 말뚝만 찍으세요':'기억 시간: 평평한 말뚝 위치를 기억하세요');if(ready&&!stun)c.move(p,q,4);if(ready)c.jump(p,q);if(q.cp&&p.y>0){pound=true;p.vy=-13;}if(pound&&p.y===0){pound=false;const s=posts.find(s=>!s.down&&dist(p,s)<.8);if(s){if(s.flat){s.down=true;c.points(p);}else stun=.9;}}if(posts.filter(s=>s.flat).every(s=>s.down))c.complete([0],'평평한 말뚝을 모두 박았습니다');},render(){c.arena({width:12,depth:10,color:'#bac79a'});posts.forEach((s,i)=>{c.draw('post'+i,'cylinder',{x:s.x,y:s.down?-.2:.2,z:s.z,sx:1.1,sy:.5,sz:1.1,color:'#b98e67'});if(!s.down){if(c.time<3&&!s.flat)c.draw('point'+i,'cone',{x:s.x,y:.65,z:s.z,sx:.9,sy:.65,sz:.9,color:'#b98e67'});if(c.time>=3)c.draw('butterfly'+i,'box',{x:s.x,y:.6,z:s.z,sx:1.15,sy:.1,sz:.8,rz:Math.sin(c.time*4+i)*.1,color:'#f2d7aa'});}});},timeout(){c.complete([],'모든 평평한 말뚝을 박지 못했습니다');}};
}
function plants(c){
 solo(c);c.limit=65;c.bounds={x:4,z:4};const spots=Array.from({length:9},(_,i)=>({x:(i%3-1)*2.4,z:(Math.floor(i/3)-1)*2.4}));let wave=0,phase=0,active=[];function next(){wave++;phase=0;active=c.shuffle(spots.map((_,i)=>i)).slice(0,wave);}next();
 return {update(dt){phase+=dt;const p=c.players[0],target=active.map(i=>spots[i]).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...toward(p,target?.x||0,target?.z||0,target&&dist(p,target)>.1?1:0),a:target&&dist(p,target)<1.8&&p.y===0}));c.hint(`A 점프 · ${wave}/8 웨이브 · 식물 위를 밟아 코인 받기`);c.move(p,q,5);c.jump(p,q,7.5);if(p.vy<0&&p.y<.7){const j=active.findIndex(i=>dist(p,spots[i])<.65);if(j>=0){active.splice(j,1);c.points(p);p.vy=6;p.y=.6;}}if(active.length===0||phase>3+wave*.2){if(wave===8)collectEnd(c);else next();}},render(){c.arena({width:12,depth:12,color:'#b7c89d'});spots.forEach((s,i)=>{c.draw('pipe'+i,'cylinder',{x:s.x,y:-.05,z:s.z,sx:1.3,sy:.5,sz:1.3,color:'#6eab8c'});if(active.includes(i)){c.draw('plant'+i,'sphere',{x:s.x,y:.55,z:s.z,sx:.95,sy:1,sz:.9,color:'#e68b9f'});c.draw('mouth'+i,'box',{x:s.x,y:.63,z:s.z+.35,sx:.7,sy:.15,sz:.15,color:'#f6e9c4'});}});},timeout(){collectEnd(c);}};
}
function knock(c){
 solo(c);c.limit=10;c.bounds={x:4,z:3};const p=c.players[0];p.x=-1.65;p.z=0;let crates=5,cool=0;const stone=()=>.8+Math.sin(c.time*3.1)*1.6;
 return {update(dt){cool=Math.max(0,cool-dt);const y=stone(),q=c.input(p,()=>({x:Math.abs(p.x+1.65)>.1?Math.sign(-1.65-p.x):0,b:cool===0&&(y>1.8||y<-.1)&&pulse(c.time,7)}));c.hint('A 점프 / B 상자 치기 · 위아래로 움직이는 돌을 때리면 실패');c.move(p,q,3.5);c.jump(p,q);if(q.bp&&cool===0&&Math.hypot(p.x,p.z)<2.5){cool=.3;if(y>-.1&&y<1.8)c.complete([],'돌을 잘못 때렸습니다');else{crates--;c.points(p);if(crates===0)c.complete([0],'보물상자를 얻었습니다');}}},render(){c.arena({width:10,depth:9,color:'#c7bb95'});for(let j=0;j<crates;j++)c.draw('crate'+j,'box',{x:0,y:.5+j*.85,z:0,sx:1.3,sy:.8,sz:1.3,color:'#c39260'});c.draw('movingStone','box',{x:-.5,y:stone(),z:0,sx:1.4,sy:1,sz:1.4,color:'#809895'});c.draw('chest','box',{x:0,y:crates*.85+.4,z:0,sx:1.3,sy:.7,sz:1,color:'#e5c061'});},timeout(){c.complete([],'보물에 도달하지 못했습니다');}};
}
function musical(c){
 c.limit=30;c.bounds={x:6,z:6};const stop=c.rand(2.5,5.5),pads=Array.from({length:6},(_,i)=>({x:Math.cos(i*TAU/6)*3.7,z:Math.sin(i*TAU/6)*3.7}));c.players.forEach((p,i)=>{p.x=pads[i].x;p.z=pads[i].z;p.lag=c.rand(.15,.6);p.cool=0;});
 return {update(dt){const music=c.time<stop,finishers=[];c.hint(music?'음악이 멈출 때를 기다리세요':'방향 이동 / A 점프 / B 공격 · 중앙 상자로 달려가세요');for(const p of c.players){const q=c.input(p,()=>({...toward(p,0,0,!music&&c.time>stop+p.lag?1:0),a:!music&&dist(p,{x:0,z:0})<1.8&&p.y===0,b:false}));c.move(p,q,4);c.jump(p,q,8.4);p.cool=Math.max(0,p.cool-dt);if(q.bp&&p.cool===0){p.cool=.5;for(const o of c.players)if(o!==p&&dist(p,o)<1.4){const v=toward(p,o.x,o.z);o.x+=v.x*.8;o.z+=v.z*.8;}}if(!music&&Math.hypot(p.x,p.z)<.7&&p.y>1.25)finishers.push(p.i);}if(finishers.length)c.complete(finishers,'상자를 먼저 차지했습니다');},render(){c.arena({width:15,depth:15,color:'#a8c79f'});pads.forEach((s,i)=>c.draw('mushroom'+i,'cylinder',{x:s.x,y:-.1,z:s.z,sx:2.5,sy:.4,sz:2.5,color:'#9fb9d2'}));c.draw('center','cylinder',{x:0,y:.5,z:0,sx:2.4,sy:1,sz:2.4,color:'#dfad6f'});if(c.time>=stop)c.draw('treasure','box',{x:0,y:1.6,z:0,sx:.9,sy:.7,sz:.8,color:'#eed079'});else label(c,'music','♫',0,3,0,3);},timeout(){c.complete([],'상자를 얻지 못했습니다');}};
}
function hot(c,m){
 const one=m.titleId==='mp1';c.limit=one?35:55;c.view={size:18,eye:[0,20,20],target:[0,0,0]};c.players.forEach((p,i)=>{p.x=Math.cos(i*TAU/4)*4;p.z=Math.sin(i*TAU/4)*4;p.stun=0;p.phase=c.rand(0,1);});let carrier=c.int(0,3),fuse=one?30:15,flight=null,round=1;
 return {update(dt){fuse-=dt;c.hint(one?'방향으로 상대 선택 / A 폭탄 넘기기 · 폭발 때 들고 있으면 패배':'방향+A 던지기 / B 받기 · 마지막 생존자가 승리');const inputs=c.players.map(p=>{p.stun=Math.max(0,p.stun-dt);const others=c.players.filter(o=>o.alive&&o!==p),to=others[Math.floor(c.time*.7+p.phase*3)%Math.max(1,others.length)];return c.input(p,()=>({x:to?to.x-p.x:0,z:to?to.z-p.z:0,a:carrier===p.i&&pulse(c.time,2.7,p.phase),b:flight?.to===p.i&&flight.left<.15}));});if(flight){flight.left-=dt;if(flight.left<=0){carrier=flight.to;if(!one&&!inputs[carrier].b)c.players[carrier].stun=.75;flight=null;}}else if(carrier>=0){const p=c.players[carrier],q=inputs[carrier];if(q.ap&&!p.stun){const options=c.players.filter(o=>o.alive&&o!==p);const target=options.sort((a,b)=>{const av=toward(p,a.x,a.z),bv=toward(p,b.x,b.z);return bv.x*q.x+bv.z*q.z-av.x*q.x-av.z*q.z;})[0];if(target){flight={from:carrier,to:target.i,left:.22};carrier=-1;}}}if(fuse<=0){const victim=carrier>=0?carrier:flight?.to;if(victim==null)return;c.eliminate(c.players[victim]);flight=null;if(one)c.complete(c.players.filter(p=>p.alive).map(p=>p.i),'폭탄을 가진 플레이어가 패배했습니다');else{c.lastStanding();if(!c.ended){carrier=c.pick(c.players.filter(p=>p.alive)).i;round++;fuse=15;}}}},render(){c.arena({width:13,depth:13,shape:'cylinder',color:'#bec5a1'});let x=0,z=0;if(flight){const a=c.players[flight.from],b=c.players[flight.to],t=1-flight.left/.22;x=a.x+(b.x-a.x)*t;z=a.z+(b.z-a.z)*t;}else if(carrier>=0){x=c.players[carrier].x;z=c.players[carrier].z;}c.draw('bomb','sphere',{x,y:1.3,z,sx:1+Math.max(0,5-fuse)*.12,sy:1,sz:1,color:fuse<5?'#e57278':'#526d78'});c.draw('fuse','cylinder',{x,y:2,z,sx:.12,sy:.6,sz:.12,color:'#edc374'});},timeout(){c.survivors();}};
}
function cutter(c,m){
 c.limit=30;c.view={size:21,eye:[0,29,17],target:[0,0,0]};const path=Array.from({length:60},(_,i)=>{const a=i/60*TAU,r=1.75+.3*Math.sin(a*3);return{x:Math.cos(a)*r,z:Math.sin(a)*r};}),states=c.players.map((p,i)=>{const x=(i%2-.5)*8,z=(i<2?-1:1)*4;p.x=x+path[0].x;p.z=z+path[0].z;p.scale=.5;return{x,z,next:1,error:0,samples:0,done:false,stopped:false,trace:[],lag:c.rand(.1,.6)};});
 function result(){if(m.titleId==='mp1')c.complete(c.players.filter(p=>p.score>=80).map(p=>p.i),'정확도 80점 이상 성공');else c.highest('가장 정확하게 잘랐습니다');}
 return {update(dt){c.hint('방향으로 굴착기 조종 · 화석 테두리를 따라 한 바퀴 자르세요');for(const p of c.players){const s=states[p.i],goal=path[s.next%path.length],q=c.input(p,()=>toward(p,s.x+goal.x,s.z+goal.z,c.time>s.lag?1:0));if(!s.done&&!s.stopped){c.move(p,q,2.3,false);p.x=clamp(p.x,s.x-2.8,s.x+2.8);p.z=clamp(p.z,s.z-2.8,s.z+2.8);const local={x:p.x-s.x,z:p.z-s.z},distance=Math.min(...path.map(v=>dist(local,v)));s.error+=distance*dt;s.samples+=dt;if(distance>1.2)s.stopped=true;if(dist(local,goal)<.3){s.next++;if(s.next>path.length)s.done=true;}if(!s.trace.length||dist(p,s.trace[s.trace.length-1])>.09)s.trace.push({x:p.x,z:p.z});}p.score=Math.round(clamp((Math.min(s.next,60)/60*100)-(s.error/(s.samples||1))*25,0,100));}if(states.every(s=>s.done||s.stopped))result();},render(){c.arena({width:19,depth:18,color:'#cfbc94'});states.forEach((s,i)=>{path.forEach((v,j)=>c.draw('outline'+i+'_'+j,'sphere',{x:s.x+v.x,y:.025,z:s.z+v.z,sx:.09,sy:.05,sz:.09,color:'#776f63'}));s.trace.forEach((v,j)=>c.draw('cut'+i+'_'+j,'sphere',{x:v.x,y:.05,z:v.z,sx:.08,sy:.08,sz:.08,color:c.players[i].color}));c.draw('hammer'+i,'cylinder',{x:c.players[i].x,y:.3,z:c.players[i].z,sx:.23,sy:.6,sz:.23,color:'#597886'});});},timeout:result};
}
function faces(c){
 c.limit=30;c.view={size:23,eye:[0,30,19],target:[0,0,0]};const defaults=[{x:-.75,z:-.65},{x:.75,z:-.65},{x:0,z:.3},{x:-1,z:.55},{x:1,z:.55}],goal=defaults.map(p=>({x:p.x+c.rand(-.55,.55),z:p.z+c.rand(-.55,.55)})),states=c.players.map((p,i)=>{const x=(i%2-.5)*9,z=(i<2?-1:1)*4.3;p.x=x;p.z=z;p.visible=false;return{x,z,points:defaults.map(v=>({...v})),held:null,bot:0,jitter:defaults.map(()=>({x:c.rand(-.04,.04),z:c.rand(-.04,.04)}))};});
 return {update(dt){c.hint('방향으로 손 이동 / A 잡고 이동 / B 초기화 · 가운데 표본 얼굴과 맞추세요');for(const p of c.players){const s=states[p.i];if(s.held==null&&s.bot<5&&dist(s.points[s.bot],goal[s.bot])<.12)s.bot++;const k=Math.min(4,s.bot),target=s.held==null?s.points[k]:{x:goal[s.held].x+s.jitter[s.held].x,z:goal[s.held].z+s.jitter[s.held].z},q=c.input(p,()=>({...toward(p,s.x+target.x,s.z+target.z,Math.hypot(p.x-s.x-target.x,p.z-s.z-target.z)>.05?1:0),a:s.bot<5&&(s.held==null?Math.hypot(p.x-s.x-target.x,p.z-s.z-target.z)<.2:dist(s.points[s.held],goal[s.held])>.08)}));c.move(p,q,3.2,false);p.x=clamp(p.x,s.x-2.3,s.x+2.3);p.z=clamp(p.z,s.z-2,s.z+2);if(q.bp){s.points=defaults.map(v=>({...v}));s.held=null;}if(q.ap&&s.held==null){const candidates=s.points.map((v,i)=>({i,d:Math.hypot(p.x-s.x-v.x,p.z-s.z-v.z)})).filter(v=>v.d<.4).sort((a,b)=>a.d-b.d);if(candidates.length)s.held=candidates[0].i;}if(!q.a)s.held=null;else if(s.held!=null){s.points[s.held].x=p.x-s.x;s.points[s.held].z=p.z-s.z;}p.score=Math.round(clamp(100-s.points.reduce((sum,v,i)=>sum+dist(v,goal[i]),0)*20,0,100));}},render(){c.arena({width:21,depth:19,color:'#bdc3d8'});const renderFace=(id,x,z,points,scale=1)=>{c.draw('head'+id,'sphere',{x,y:.25,z,sx:4*scale,sy:.5,sz:3.6*scale,color:'#f0abc0'});points.forEach((p,j)=>c.draw('feature'+id+'_'+j,j===2?'cone':'sphere',{x:x+p.x*scale,y:.6,z:z+p.z*scale,sx:(j===2?.7:.45)*scale,sy:.35,sz:(j===2?1:.45)*scale,color:j<2?'#405969':j===2?'#ecc379':'#de789f'}));};states.forEach((s,i)=>{renderFace(i,s.x,s.z,s.points);c.draw('cursor'+i,'ring',{x:c.players[i].x,y:.95,z:c.players[i].z,sx:.7,sy:.7,sz:1,rx:-Math.PI/2,color:'#fff2c9'});label(c,'score'+i,String(c.players[i].score),s.x,2.8,s.z-1.8,2);});renderFace('goal',0,0,goal,.7);label(c,'goalLabel','표본',0,2,0,2);},timeout(){c.highest('표본과 가장 비슷한 얼굴');}};
}
function chip(c,m){
 c.limit=70;c.view={size:22,eye:[0,25,20],target:[0,0,0]};const hole={x:c.rand(-3,3),z:-3.5},tee={x:0,z:5},states=c.players.map((p,i)=>{p.x=-6+i*1.4;p.z=6;p.score=0;return{angle:0,power:.5,distance:Infinity,x:0,z:5,error:c.rand(-.08,.08)};});const first=m.titleId==='mp3'?0:c.int(0,3),order=Array.from({length:4},(_,i)=>(first+i)%4);let position=0,turn=order[0],phase=0,flight=null;
 function finish(){const inns=states.flatMap((s,i)=>s.distance<.3?[i]:[]);if(inns.length)c.complete(inns,'홀인');else{const d=Math.min(...states.map(s=>s.distance)),w=states.flatMap((s,i)=>Math.abs(s.distance-d)<1e-6?[i]:[]);c.complete(w.length===1?w:[],'홀과의 최종 거리 비교');}}
 return {update(dt){phase+=dt;c.hint(`${turn+1}P 차례 · 좌우 조준 / 위아래 세기 / A 샷`);for(const p of c.players){const s=states[p.i],aim=Math.atan2(hole.x-tee.x,tee.z-hole.z)+s.error,pow=Math.hypot(hole.x-tee.x,hole.z-tee.z)/13+s.error*.2,q=c.input(p,()=>({x:turn===p.i&&!flight?Math.sign(aim-s.angle)*(Math.abs(aim-s.angle)>.015?1:0):0,z:turn===p.i&&!flight?Math.sign(pow-s.power)*(Math.abs(pow-s.power)>.009?1:0):0,a:turn===p.i&&!flight&&Math.abs(aim-s.angle)<.025&&Math.abs(pow-s.power)<.018}));if(p.i!==turn||flight)continue;s.angle=clamp(s.angle+q.x*dt*.9,-1,1);s.power=clamp(s.power+q.z*dt*.28,.15,1);if(q.ap||phase>=10){flight={t:0,x:Math.sin(s.angle)*s.power*13,z:5-Math.cos(s.angle)*s.power*13};phase=0;}}
 if(flight){flight.t+=dt;const s=states[turn],t=clamp(flight.t/1.2,0,1);s.x=tee.x+(flight.x-tee.x)*t;s.z=tee.z+(flight.z-tee.z)*t;if(flight.t>=1.6){s.distance=Math.abs(s.x)>6||s.z<-6?Infinity:dist(s,hole);c.players[turn].score=Number.isFinite(s.distance)?+Math.max(0,100-s.distance*10).toFixed(2):0;position++;phase=0;flight=null;if(position===4){finish();}else turn=order[position];}}},render(){c.arena({width:13,depth:13,color:'#a6c290'});ring(c,'hole',hole.x,hole.z,.3,'#527a69');c.draw('flagpole','cylinder',{x:hole.x,y:1.2,z:hole.z,sx:.07,sy:2.4,sz:.07,color:'#faf0d6'});c.draw('flag','box',{x:hole.x+.35,y:2.2,z:hole.z,sx:.7,sy:.5,sz:.05,color:'#e77d92'});states.forEach((s,i)=>{let y=.15;if(i===turn&&flight)y+=Math.sin(clamp(flight.t/1.2,0,1)*Math.PI)*3.5;c.draw('golfball'+i,'sphere',{x:s.x,y,z:s.z,sx:.24,sy:.24,sz:.24,color:colors[i]});});if(!flight&&!c.ended){const s=states[turn];c.draw('aim','box',{x:Math.sin(s.angle)*2,y:.04,z:5-Math.cos(s.angle)*2,sx:.06,sy:.05,sz:4,ry:-s.angle,color:colors[turn]});label(c,'power',`${Math.round(s.power*100)}%`,3,2,4,3);}},timeout:finish};
}
function pizza(c){
 c.limit=30;c.bounds={x:6,z:5};const food=Array.from({length:120},(_,i)=>({x:(i%12-5.5)*.85,z:(Math.floor(i/12)-4.5)*.85,hp:i%7===0?3:1,initial:i%7===0?3:1})).filter(f=>Math.hypot(f.x/1.2,f.z)<4.2);c.players.forEach((p,i)=>{p.x=i<2?-3:3;p.z=i%2?2:-2;p.phase=c.rand(0,1);});const amount=g=>food.filter(f=>(f.x<0?0:1)===g&&f.hp===0).length/food.filter(f=>(f.x<0?0:1)===g).length*100;
 return {update(dt){c.hint('방향 이동 / A 반복해 먹기 · 토핑은 더 여러 번 씹어야 합니다');for(const p of c.players){const g=Math.floor(p.i/2),target=food.filter(f=>f.hp>0&&(f.x<0?0:1)===g).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...toward(p,target?.x||0,target?.z||0,target&&dist(p,target)>.12?1:0),a:pulse(c.time,5+c.players[p.i].phase,p.phase)}));c.move(p,q,3.3);p.x=clamp(p.x,g===0?-5.1:.05,g===0?-.05:5.1);if(q.ap){const bite=food.filter(f=>f.hp>0&&(f.x<0?0:1)===g&&dist(p,f)<.75).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(bite)bite.hp--;}}const a=[amount(0),amount(1)];c.players.forEach(p=>p.score=+a[Math.floor(p.i/2)].toFixed(1));if(a.some(v=>v>=100))teamEnd(c,a,'피자를 다 먹었습니다');},render(){c.arena({width:13,depth:11,shape:'cylinder',color:'#f3e6bc'});food.forEach((f,i)=>{if(f.hp>0)c.draw('food'+i,'box',{x:f.x,y:.1,z:f.z,sx:.83,sy:.2,sz:.83,color:f.initial===3?'#cb7867':'#eed38b'});});c.draw('divider','box',{x:0,y:.02,z:0,sx:.035,sy:.05,sz:9,color:'#d48084'});},timeout(){teamEnd(c,[amount(0),amount(1)],'먹은 면적 비교');}};
}
function logs(c){
 c.limit=30;const states=[0,1].map(()=>({button:c.int(0,2),stage:0,age:0,stun:0,score:0}));c.players.forEach((p,i)=>{p.x=(i<2?-1:1)*4+(i%2?1:-1);p.z=0;p.lag=c.rand(.16,.38);});
 return {update(dt){c.hint('표시된 A·B·C 버튼 · 먼저 놓고 다음 사람이 잘라야 합니다');const keys=['a','b','c'];const input=c.players.map(p=>{const s=states[Math.floor(p.i/2)];return c.input(p,()=>({[keys[s.button]]:p.i%2===s.stage&&s.age>p.lag&&s.stun===0}));});states.forEach((s,g)=>{s.age+=dt;s.stun=Math.max(0,s.stun-dt);if(s.stun)return;const q=input[g*2+s.stage],pressed=keys.findIndex(k=>q[k+'p']);if(pressed>=0){if(pressed===s.button){if(s.stage===0)s.stage=1;else{s.stage=0;s.score++;s.button=c.int(0,2);}s.age=0;}else{s.stun=.55;s.age=0;}}c.players[g*2].score=c.players[g*2+1].score=s.score;});},render(){c.arena({width:16,depth:10,color:'#bfd0aa'});states.forEach((s,g)=>{const x=g?4:-4;c.draw('stump'+g,'cylinder',{x,y:.5,z:-.6,sx:2.6,sy:1,sz:2.6,color:'#9c7855'});if(s.stage===1)c.draw('log'+g,'cylinder',{x,y:1.1,z:-.6,sx:1,sy:1.1,sz:1,color:'#c69967'});label(c,'prompt'+g,['A','B','C'][s.button],x,3.7,-.6,2.5);label(c,'role'+g,s.stage===0?'놓기':'자르기',x,2.7,-.6,3);});},timeout(){teamEnd(c,states.map(s=>s.score),'완성한 장작 수');}};
}
function rockets(c){
 c.limit=22;c.view={size:21,eye:[0,20,20],target:[0,3,0]};let tieAdjusted=false;const air=[0,0],pumps=c.players.map(()=>({h:0,push:false,pause:c.rand(0,.5)}));c.players.forEach((p,i)=>{p.x=(i<2?-1:1)*4+(i%2?1.2:-1.2);p.z=2;});
 return {update(dt){c.hint(c.time<=10?'10초간 A 내리기 / B 올리기 · 팀 로켓에 공기 넣기':'로켓 비행 높이 측정');for(const p of c.players){const s=pumps[p.i],q=c.input(p,()=>{if(s.h>.98&&!s.push){s.push=true;s.pause=c.time+c.rand(0,.07);}if(s.h<.02&&s.push){s.push=false;s.pause=c.time+c.rand(0,.07);}return{a:s.push&&c.time>s.pause,b:!s.push&&c.time>s.pause};});if(c.time>10)continue;const before=s.h;if(q.a&&!q.b)s.h=Math.max(0,s.h-dt*2.6);if(q.b&&!q.a)s.h=Math.min(1,s.h+dt*2.6);air[Math.floor(p.i/2)]+=Math.max(0,before-s.h);}if(c.time>10&&!tieAdjusted){tieAdjusted=true;if(air[0]>0&&Math.abs(air[0]-air[1])<1e-8)air[c.int(0,1)]+=.048;}c.players.forEach(p=>p.score=+(air[Math.floor(p.i/2)]*10).toFixed(2));if(c.time>=17){if(air.every(n=>n===0))c.complete([],'공기를 넣지 않아 무승부');else teamEnd(c,air,'더 높이 올라간 로켓');}},render(){c.arena({width:16,depth:12,color:'#a9c6c9'});for(const p of c.players){c.draw('pump'+p.i,'cylinder',{x:p.x,y:.5,z:1,sx:.7,sy:1,sz:.7,color:p.color});c.draw('handle'+p.i,'box',{x:p.x,y:1+pumps[p.i].h*.7,z:1,sx:1,sy:.13,sz:.2,color:'#e9dcb2'});}air.forEach((a,g)=>{const height=c.time>10?Math.min(a*.3,(c.time-10)*2):0;c.draw('rocket'+g,'cone',{x:g?4:-4,y:1+height,z:-2,sx:1.5,sy:2.4,sz:1.5,color:colors[g*2]});label(c,'height'+g,`${(a*10).toFixed(1)}`,g?4:-4,4+height,-2,3);});},timeout(){teamEnd(c,air,'비행 높이');}};
}
function hydrants(c){
 c.limit=30;c.view={size:20,eye:[0,24,20],target:[0,1,-1]};const teams=[0,1].map(()=>({water:1,score:0,flames:[],next:.1,aim:{x:0,z:0},pump:0,down:false,pause:0}));let id=0;c.players.forEach((p,i)=>{p.x=(i<2?-1:1)*4+(i%2?1:-1);p.z=4;});
 return {update(dt){c.hint('각 팀 앞사람: 방향 조준+A 물 / 뒷사람: A 내리기+B 올리기');teams.forEach((s,g)=>{s.next-=dt;if(s.next<0){s.next=c.rand(.65,1.1);s.flames.push({id:id++,x:c.rand(-2.3,2.3),z:c.rand(-3,1),hp:1});}const shooter=c.players[g*2],pumper=c.players[g*2+1],target=s.flames.find(f=>f.hp>0),q=c.input(shooter,()=>({...toward(s.aim,target?.x||0,target?.z||0,target&&dist(s.aim,target)>.08?1:0),a:!!target&&dist(s.aim,target)<.7})),r=c.input(pumper,()=>{if(s.pump>.98&&!s.down){s.down=true;s.pause=c.time+c.rand(0,.08);}if(s.pump<.02&&s.down){s.down=false;s.pause=c.time+c.rand(0,.08);}return{a:s.down&&c.time>s.pause,b:!s.down&&c.time>s.pause};});s.aim.x=clamp(s.aim.x+q.x*4*dt,-2.5,2.5);s.aim.z=clamp(s.aim.z+q.z*4*dt,-3.3,1.3);const old=s.pump;if(r.b&&!r.a)s.pump=Math.min(1,s.pump+dt*2.5);if(r.a&&!r.b)s.pump=Math.max(0,s.pump-dt*2.5);s.water=Math.min(3,s.water+Math.max(0,old-s.pump)*1.8);s.spraying=q.a&&s.water>0;if(s.spraying){s.water=Math.max(0,s.water-dt*1.1);for(const f of s.flames)if(f.hp>0&&dist(f,s.aim)<.7){f.hp-=dt*2.5;if(f.hp<=0)s.score++;}}s.flames=s.flames.filter(f=>f.hp>0);shooter.score=pumper.score=s.score;});},render(){c.arena({width:17,depth:13,color:'#afbecb'});teams.forEach((s,g)=>{const x=g?4:-4;s.flames.forEach(f=>c.draw('flame'+f.id,'cone',{x:x+f.x,y:.65*f.hp,z:f.z,sx:.8,sy:1.3*f.hp,sz:.8,color:'#ed9b56',glow:true}));ring(c,'target'+g,x+s.aim.x,s.aim.z,.65,'#80cde0');c.draw('tank'+g,'cylinder',{x:x+2,y:s.water*.4,z:3,sx:.8,sy:Math.max(.1,s.water*.8),sz:.8,color:'#77b5d0'});if(s.spraying)for(let j=0;j<8;j++){const t=j/8;c.draw('spray'+g+'_'+j,'sphere',{x:x-1+(s.aim.x+1)*t,y:1.5+Math.sin(t*Math.PI)*.8-t,z:4+(s.aim.z-4)*t,sx:.17,sy:.17,sz:.17,color:'#99dbdf'});}});},timeout(){teamEnd(c,teams.map(s=>s.score),'불을 끈 횟수');}};
}
function etch(c){
 c.limit=30;c.view={size:22,eye:[0,29,18],target:[0,0,0]};const N=25,step=6/(N-1),teams=[0,1].map(()=>({trail:Array(N*N).fill(-100),score:0,t:0,rate:c.rand(1.2,1.45),check:0,target:{x:0,z:0}}));c.players.forEach((p,i)=>{p.x=(i<2?-1:1)*4.5+1.4;p.z=0;p.scale=.55;});
 function cell(x,z){return clamp(Math.round((z+3)/step),0,N-1)*N+clamp(Math.round((x+3)/step),0,N-1);}
 function enclosed(s){const live=s.trail.map(t=>c.time-t<2.8),at=cell(s.target.x,s.target.z);if(live[at])return false;const seen=new Uint8Array(N*N),queue=[];for(let i=0;i<N;i++)for(const j of [i,(N-1)*N+i,i*N,i*N+N-1])if(!live[j]&&!seen[j]){seen[j]=1;queue.push(j);}for(let k=0;k<queue.length;k++){const v=queue[k],x=v%N,z=Math.floor(v/N);for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,nz=z+dz,j=nz*N+nx;if(nx>=0&&nx<N&&nz>=0&&nz<N&&!seen[j]&&!live[j]){seen[j]=1;queue.push(j);}}}return !seen[at];}
 return {update(dt){c.hint('방향으로 크레용 이동 · 두 사람의 선을 연결해 움직이는 그림을 둘러싸세요');const wins=[];teams.forEach((s,g)=>{s.t+=dt;s.check+=dt;s.target.x=Math.sin(c.time*1.2+g)*.25;s.target.z=Math.cos(c.time*.9+g)*.25;for(const p of c.players.slice(g*2,g*2+2)){const center=g?4.5:-4.5,side=p.i%2?1:-1,phase=s.t%3.5,angle=side*Math.min(Math.PI,Math.max(0,phase-.4)*s.rate),goal={x:center+Math.cos(angle)*1.55,z:Math.sin(angle)*1.55},q=c.input(p,()=>toward(p,goal.x,goal.z,dist(p,goal)>.06?1:0)),old={x:p.x,z:p.z};c.move(p,q,4.8,false);p.x=clamp(p.x,center-3,center+3);p.z=clamp(p.z,-3,3);const count=Math.max(1,Math.ceil(dist(old,p)/.09));for(let j=0;j<=count;j++){const x=old.x+(p.x-old.x)*j/count-center,z=old.z+(p.z-old.z)*j/count,i=cell(x,z),cx=i%N,cz=Math.floor(i/N);for(const [dx,dz] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]){const nx=cx+dx,nz=cz+dz;if(nx>=0&&nx<N&&nz>=0&&nz<N)s.trail[nz*N+nx]=c.time;}}}if(s.check>.12){s.check=0;if(enclosed(s)){s.score++;s.trail.fill(-100);s.t=0;if(s.score>=5)wins.push(g*2,g*2+1);}}c.players[g*2].score=c.players[g*2+1].score=s.score;});if(wins.length)c.complete(wins,'다섯 그림을 둘러싸 구했습니다');},render(){c.arena({width:19,depth:10,color:'#d4c3a1'});teams.forEach((s,g)=>{const center=g?4.5:-4.5;c.draw('paper'+g,'box',{x:center,y:-.04,z:0,sx:6.5,sy:.1,sz:6.5,color:'#f8ecca'});s.trail.forEach((t,i)=>{if(c.time-t<2.8)c.draw('stroke'+g+'_'+i,'box',{x:center+i%N*step-3,y:.025,z:Math.floor(i/N)*step-3,sx:step,sy:.035,sz:step,color:colors[g*2],opacity:clamp(1-(c.time-t)/3,.2,1)});});c.draw('picture'+g,'sphere',{x:center+s.target.x,y:.25,z:s.target.z,sx:.65,sy:.45,sz:.65,color:'#dfb666'});label(c,'saved'+g,`${s.score}/5`,center,3.5,-3,3);});},timeout(){teamEnd(c,teams.map(s=>s.score),'구한 그림 수');}};
}
function picking(c){
 c.limit=30;c.view={size:21,eye:[0,16,23],target:[0,3,0]};const teams=[0,1].map(()=>({score:0,next:.2,phase:c.rand(0,.25),fruit:[]}));let id=0;const location=(g,role,t)=>{const phase=t*1.65+teams[g].phase+(role?Math.PI:0),angle=Math.sin(phase)*.83,angular=Math.cos(phase)*.83*1.65,anchor=role?1.2:-3.2;return{x:anchor+Math.sin(angle)*2.6,y:5-Math.cos(angle)*2.6,z:g?3:-3,vx:Math.cos(angle)*angular*2.6,vy:Math.sin(angle)*angular*2.6,anchor};};
 c.players.forEach(p=>p.held=null);
 function canRelease(g,role,p,fruit){const vx=p.swing.vx/(.8+fruit.size*.12),vy=p.swing.vy;for(let t=.12;t<1.5;t+=.04){const x=p.x+vx*t,y=p.y+.65+vy*t-2*t*t;if(role===0){const other=location(g,1,c.time+t);if(Math.hypot(x-other.x,y-other.y-.65)<.7)return true;}else if(y<1.2&&y>.4&&Math.abs(x-5)<.8)return true;}return false;}
 return {update(dt){c.hint('A 누르고 체리 받기 / A 놓아 던지기 · 동료를 거쳐 바구니에 넣으세요');teams.forEach((s,g)=>{const ps=c.players.slice(g*2,g*2+2);ps.forEach((p,role)=>{p.swing=location(g,role,c.time);p.x=p.swing.x;p.y=p.swing.y;p.z=p.swing.z;p.pose='balance';});const input=ps.map((p,role)=>c.input(p,()=>({a:p.held?!canRelease(g,role,p,p.held):true})));s.next-=dt;if(s.next<0&&!ps[0].held&&!s.fruit.some(f=>f.stage===0)){s.next=1.1;s.fruit.push({id:id++,x:ps[0].x,y:6,z:g?3:-3,vx:0,vy:0,size:c.int(1,3),stage:0,held:null});}
 ps.forEach((p,role)=>{if(p.held&&!input[role].a){const f=p.held;f.held=null;f.stage=role+1;f.vx=p.swing.vx/(.8+f.size*.12);f.vy=p.swing.vy;f.x=p.x;f.y=p.y+.65;p.held=null;}});
 for(const f of s.fruit){if(f.held!=null){const p=ps[f.held];f.x=p.x;f.y=p.y+.65;continue;}f.vy-=4*dt;f.x+=f.vx*dt;f.y+=f.vy*dt;const receiver=f.stage===0?0:f.stage===1?1:-1;if(receiver>=0){const p=ps[receiver];if(!p.held&&input[receiver].a&&Math.hypot(f.x-p.x,f.y-p.y-.65)<.85){p.held=f;f.held=receiver;}}if(f.stage===2&&f.y<1.1&&f.y>.2&&Math.abs(f.x-5)<.9){f.dead=true;s.score++;}if(f.y<-.4||Math.abs(f.x)>9)f.dead=true;}s.fruit=s.fruit.filter(f=>!f.dead);ps.forEach(p=>p.score=s.score);});},render(){c.arena({width:17,depth:13,color:'#bbce9c'});teams.forEach((s,g)=>{const z=g?3:-3;c.draw('basket'+g,'cylinder',{x:5,y:.45,z,sx:1.8,sy:.9,sz:1.8,color:'#c99760'});c.draw('branch'+g,'box',{x:-1,y:5.8,z,sx:12,sy:.3,sz:.35,color:'#97754f'});for(const p of c.players.slice(g*2,g*2+2)){const anchor=p.swing?.anchor??(p.i%2?1.2:-3.2),endY=p.y+1.5,dx=p.x-anchor,dy=5.8-endY;c.draw('rope'+p.i,'box',{x:(p.x+anchor)/2,y:(5.8+endY)/2,z,sx:.04,sy:Math.hypot(dx,dy),sz:.04,rz:Math.atan2(dx,dy),color:'#bc9b63'});}s.fruit.forEach(f=>c.draw('cherry'+f.id,'sphere',{x:f.x,y:f.y,z,sx:.35+f.size*.1,sy:.35+f.size*.1,sz:.35+f.size*.1,color:'#dc6c89'}));label(c,'cherryScore'+g,String(s.score),-6,3.5,z,2);});},timeout(){teamEnd(c,teams.map(s=>s.score),'바구니에 넣은 체리 수');}};
}
export const games={
 'Cast Aways':cast,'Grab Bag':grab,'Hammer Drop':hammer,'Coin Block Blitz':coinBlocks,'Box Mountain Mayhem':mountain,'Memory Match':memory,'Ground Pound':ground,'Whack-a-Plant':plants,'Knock Block Tower':knock,'Musical Mushroom':musical,
 'Hot Bob-omb':hot,'Crazy Cutter':cutter,'Face Lift':faces,'Chip Shot Challenge':chip,'Eatsa Pizza':pizza,'Log Jam':logs,'Pump, Pump and Away':rockets,'Hyper Hydrants':hydrants,"Etch 'n' Catch":etch,'Picking Panic':picking
};
export const notes={
'Cast Aways':'원작 스틱 튕기기는 거리 선택+ A, 회전해서 감기는 B 반복으로 바꿨습니다. 세 거리·움직이는 보물·완전히 회수해야 지급되는 코인 규칙입니다.',
'Grab Bag':'방향 이동, A 점프, B 붙잡기·훔치기·탈출입니다. 보드가 없는 독립 경기이므로 모두 30코인으로 시작하고 증감분을 표시합니다.',
'Hammer Drop':'낙하 코인·주머니·망치를 물리적으로 피하거나 받습니다. 떨어져도 받은 코인은 유지합니다. 낙하 배열은 새로 생성합니다.',
'Coin Block Blitz':'블록을 아래에서 점프로 쳐 코인을 얻습니다. 블록별 잔량은 무작위이며 원작처럼 종료 때 획득 코인을 절반으로 환산합니다.',
'Box Mountain Mayhem':'상자 파괴 후 코인을 직접 줍고 숨은 돌 상자는 플레이어를 밀칩니다. 상자 산과 공격 사거리는 새로 제작했습니다.',
'Memory Match':'A 점프, C 내려찍기로 네 그림 쌍을 찾는 1인 게임입니다. 점수 표시는 맞춘 쌍 수입니다.',
'Ground Pound':'3초 미리보기 후 30초 동안 평평한 말뚝만 내려찍습니다. A 점프, C 내려찍기이며 말뚝 배치는 새로 생성합니다.',
'Whack-a-Plant':'1마리부터 8마리까지 늘어나는 식물을 점프로 밟습니다. 한 마리당 코인 한 개, 최대 36개입니다. 출현 시간은 브라우저판에서 조정했습니다.',
'Knock Block Tower':'10초 안에 나무 상자를 때려 보물 높이를 낮춥니다. 움직이는 돌을 때리면 즉시 실패하며 원작과 다른 새 탑 배치를 사용합니다.',
'Musical Mushroom':'음악이 멈춘 뒤 중앙 높은 발판의 상자를 먼저 얻습니다. A 점프, B 공격이며 발판은 새로 배치했습니다.',
'Hot Bob-omb':'1편은 첫 폭발 때 소지자만 패배하고, 2편은 마지막 생존자까지 반복합니다. A 전달, 2편에서는 B 받기가 추가됩니다.',
'Crazy Cutter':'조종 궤적과 테두리 오차를 측정합니다. 1편은 80점 이상 공동 성공, 2편은 최고 정확도입니다. 화석 모양과 채점 수치는 새로 제작했습니다.',
'Face Lift':'방향으로 커서를 움직이고 A를 누른 채 부위를 옮기며 B로 초기화합니다. 얼굴은 플라밍고 조형으로 새로 제작했습니다.',
'Chip Shot Challenge':'좌우는 조준, 상하는 힘, A는 샷입니다. 순서대로 한 번씩 치고 홀과의 거리를 비교하며 구역 밖은 실패입니다. 골프장은 새로 제작했습니다.',
'Eatsa Pizza':'두 팀이 피자 반쪽을 나누어 먹으며 토핑은 여러 번 입력해야 합니다. A 반복으로 먹고 먼저 완료하거나 먹은 면적을 비교합니다.',
'Log Jam':'표시된 버튼으로 통나무 놓기 후 자르기를 순차 수행합니다. 원작 Z는 C로 바꿨습니다.',
'Pump, Pump and Away':'10초 동안 두 명이 펌프를 왕복합니다. A 내리기, B 올리기이며 공기량으로 계산한 비행 높이를 비교합니다.',
'Hyper Hydrants':'각 팀 첫 플레이어가 방향+A로 호스를 조준하고, 두 번째가 A/B로 물을 공급합니다. 사격과 물 공급이 실제로 연결됩니다.',
"Etch 'n' Catch":'지워지는 두 크레용 궤적이 닫힌 영역을 만들었는지 격자 탐색으로 판정합니다. 5개 선취 또는 제한 시간에 구한 수로 승부합니다.',
'Picking Panic':'A를 누르고 받았다가 놓아 던집니다. 그네의 실제 속도와 체리 크기가 비행에 영향을 주며 동료를 거쳐 바구니에 들어가야 득점합니다.'
};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['Chip Shot Challenge','Eatsa Pizza','Log Jam','Pump, Pump and Away','Hyper Hydrants',"Etch 'n' Catch",'Picking Panic'].includes(name)?['mp3']:['Hot Bob-omb','Crazy Cutter','Face Lift'].includes(name)?['mp1','mp2']:['mp1']]));

// Verified reissue rules; the original layout is represented by the same new course.
supportedTitles["Chip Shot Challenge"]=["mp3", "top-100", "superstars"];
supportedTitles["Eatsa Pizza"]=["mp3", "top-100", "superstars"];
