import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2, palette=['#f077a8','#6dbae8','#f4ce62','#77c5a2','#b090d3','#ed9d62','#eee8d9'];
const pulse=(t,h=6,offset=0)=>((t*h+offset)%1)<.42;
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const mp1=m=>m.titleId==='mp1';
const drawLabel=(c,id,text,x=0,y=5,z=-5,sx=9)=>c.draw(id,'text',{x,y,z,sx,sy:1,text});
const drawCircle=(c,id,x,z,r,color,y=.02)=>c.draw(id,'cylinder',{x,y,z,sx:r*2,sy:.05,sz:r*2,color});
const alive=c=>c.players.filter(p=>p.alive);
function separate(c,r=.55,push=0){for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=c.players[i],b=c.players[j];if(!a.alive||!b.alive)continue;const d=dist(a,b);if(d<r*2){const dx=d>.001?(a.x-b.x)/d:1,dz=d>.001?(a.z-b.z)/d:0,k=(r*2-d)/2;a.x+=dx*k;a.z+=dz*k;b.x-=dx*k;b.z-=dz*k;if(push){a.vx=(a.vx||0)+dx*push;a.vz=(a.vz||0)+dz*push;b.vx=(b.vx||0)-dx*push;b.vz=(b.vz||0)-dz*push;}}}}
function fighting(c,p,q,dt){p.cool=Math.max(0,(p.cool||0)-dt);if(q.bp&&p.cool===0){p.cool=.5;p.pose='hit';for(const o of alive(c))if(o!==p&&dist(p,o)<1.65){const d=dist(p,o)||1;o.x+=(o.x-p.x)/d*.9;o.z+=(o.z-p.z)/d*.9;o.stun=.3;}}if(q.cp&&p.y>.1){p.vy=-13;p.pounding=true;}if(p.pounding&&p.y===0){p.pounding=false;for(const o of alive(c))if(o!==p&&dist(p,o)<1.2)o.stun=.7;}p.stun=Math.max(0,(p.stun||0)-dt);}
function mushroom(c){
 c.limit=600;c.bounds={x:7,z:7};c.view={size:19,eye:[0,21,18],target:[0,0,0]};const pads=[{x:0,z:0},...Array.from({length:6},(_,i)=>({x:Math.cos(i*TAU/6)*3.35,z:Math.sin(i*TAU/6)*3.35}))];c.players.forEach((p,i)=>{p.x=pads[i].x;p.z=pads[i].z;});let round=0,phase=0,target=0,checked=false;
 const next=()=>{round++;phase=0;target=c.int(0,6);checked=false;for(const p of c.players)p.botLag=c.rand(.2,1.15);};next();
 return {update(dt){phase+=dt;const wait=Math.max(1.25,4-round*.105),safe=pads[target];c.hint(`깃발 색 ${target+1} · 방향 이동 / A 점프 / C 내려찍기`);
  for(const p of alive(c)){const q=c.input(p,()=>({...toward(p,safe.x+(p.i%2-.5)*.65,safe.z+(Math.floor(p.i/2)-.5)*.65,dist(p,safe)>.4&&phase>p.botLag?1:0),a:phase>wait-.2&&p.y===0&&dist(p,safe)>1.2,c:false}));if(!p.stun)c.move(p,q,4.8,false);c.jump(p,q);fighting(c,p,q,dt);}
  separate(c,.43);for(const p of alive(c)){const hasGround=phase<wait?pads.some(s=>dist(p,s)<1.9):dist(p,safe)<1.9;if(!hasGround&&p.y<=.01)c.eliminate(p);}if(phase>=wait&&!checked){checked=true;for(const p of alive(c))c.points(p);}c.lastStanding();if(phase>wait+1.25&&!c.ended)next();
 },render(){c.arena({width:18,depth:18,color:'#81c7d0'});const wait=Math.max(1.25,4-round*.105);pads.forEach((s,i)=>{const y=i!==target&&phase>wait?-1.3:0;c.draw('pad'+i,'cylinder',{x:s.x,y:y-.27,z:s.z,sx:3.75,sy:.55,sz:3.75,color:palette[i]});drawLabel(c,'padmark'+i,String(i+1),s.x,y+.05,s.z,1);});c.draw('flag','box',{x:0,y:5.8,z:-5,sx:2,sy:1.2,sz:.12,color:palette[target]});drawLabel(c,'flagText',String(target+1),0,6.5,-5,1.5);},timeout(){c.complete([],'장시간 동률');}};
}
function rope(c,m){
 c.limit=600;c.view={size:17,eye:[0,16,17],target:[0,0,0]};c.players.forEach((p,i)=>{p.x=(i-1.5)*2.5;p.z=0;p.botJump=c.rand(.09,.34);});let angle=-Math.PI/2,jumps=0,lastCross=-1;
 return {update(dt){const speed=2.2+Math.min(jumps*.095,3.7),old=angle;angle+=speed*dt;const cross=Math.floor(angle/TAU);c.hint(mp1(m)?`공동 20회 · ${jumps}/20 · A 점프`:`끝까지 살아남으세요 · ${jumps}회 · A 점프`);
 for(const p of alive(c)){const until=(TAU-((angle%TAU+TAU)%TAU))/speed;const q=c.input(p,()=>({a:until<(mp1(m)?.24:p.botJump)||((angle%TAU+TAU)%TAU)/speed<.12}));c.jump(p,q,8);if(!q.a&&p.vy>0)p.vy-=24*dt;}
 if(cross>lastCross&&old<cross*TAU&&angle>=cross*TAU){lastCross=cross;jumps++;for(const p of c.players)p.botJump=c.rand(.005,.32);const misses=alive(c).filter(p=>p.y<.52);if(mp1(m)){if(misses.length)c.complete(c.players.filter(p=>!misses.includes(p)).map(p=>p.i),'줄에 닿아 공동 도전 종료');else if(jumps>=20)c.complete([0,1,2,3],'20회 공동 성공');}else{misses.forEach(p=>c.eliminate(p));c.lastStanding();}for(const p of alive(c))p.score=jumps;}
 },render(){c.arena({width:14,depth:7,color:'#d7b079'});c.draw('postA','cylinder',{x:-6.5,y:1.2,z:0,sx:.3,sy:2.4,sz:.3,color:'#bd8364'});c.draw('postB','cylinder',{x:6.5,y:1.2,z:0,sx:.3,sy:2.4,sz:.3,color:'#bd8364'});for(let i=0;i<27;i++){const x=-6.3+i*.485,curve=Math.sin(i/26*Math.PI);c.draw('fire'+i,'sphere',{x,y:.25+(1-Math.cos(angle))*1.25*curve,z:Math.sin(angle)*2.3*curve,sx:.32,sy:.32,sz:.32,color:jumps<5?'#69cae4':'#ff973b',glow:true});}},timeout(){c.complete([],'동률');}};
}
function bumpers(c,m){
 c.limit=60;c.bounds={x:9,z:9};const radius=m.titleId==='top-100'?5.15:6,course=mp1(m)||m.titleId==='top-100'?0:c.int(0,2),friction=course===1?.75:1.45;const rocks=course===2?[{x:0,z:2,r:.8},{x:-2,z:-2,r:.65}]:[];c.players.forEach((p,i)=>{p.x=Math.cos(i*TAU/4)*3.2;p.z=Math.sin(i*TAU/4)*3.2;p.y=.65;p.vx=p.vz=0;p.botOffset=c.rand(0,TAU);p.botNext=0;p.botTarget=(i+1)%4;});
 return {update(dt){c.hint('방향으로 공 굴리기 · 섬 밖으로 밀어내세요');for(const p of alive(c)){const others=alive(c).filter(o=>o!==p);p.botNext-=dt;if(p.botNext<0||!c.players[p.botTarget]?.alive){p.botNext=c.rand(1,2.5);p.botTarget=c.pick(others)?.i;}const o=c.players[p.botTarget],aim=o?{x:o.x+Math.cos(c.time+p.botOffset)*1.3,z:o.z+Math.sin(c.time+p.botOffset)*1.3}:{x:0,z:0};if(Math.hypot(p.x,p.z)>radius-.65){aim.x=0;aim.z=0;}const q=c.input(p,()=>toward(p,aim.x,aim.z));p.vx=(p.vx+q.x*8*dt)*Math.exp(-friction*dt);p.vz=(p.vz+q.z*8*dt)*Math.exp(-friction*dt);p.x+=p.vx*dt;p.z+=p.vz*dt;p.pose='balance';p.rotation=Math.atan2(-p.vz,p.vx);for(const r of rocks)if(dist(p,r)<r.r+.55){const d=dist(p,r)||1;p.vx+=(p.x-r.x)/d*6*dt;p.vz+=(p.z-r.z)/d*6*dt;}}separate(c,.62,2.1);for(const p of alive(c))if(Math.hypot(p.x,p.z)>radius)c.eliminate(p);c.lastStanding();},render(){c.arena({width:radius*2,depth:radius*2,shape:'cylinder',color:course===1?'#bce5ec':course===2?'#d3c7a3':'#babe8b'});rocks.forEach((r,i)=>c.draw('rock'+i,'sphere',{x:r.x,y:.1,z:r.z,sx:r.r*2,sy:1.1,sz:r.r*2,color:'#7e938f'}));for(const p of c.players)c.draw('ball'+p.i,'sphere',{x:p.x,y:.24,z:p.z,sx:1.4,sy:1.4,sz:1.4,color:p.color});},timeout(){c.complete([],'둘 이상 생존해 무승부');}};
}
function bombs(c,m){
 c.limit=30;c.bounds={x:8,z:8};let tick=.8,serial=0;const shots=[],blasts=[];c.players.forEach((p,i)=>{p.x=(i%2-.5)*4;p.z=(Math.floor(i/2)-.5)*4;p.stun=0;p.vx=p.vz=0;});
 function spawn(big=false){const target=c.pick(alive(c));if(!target)return;shots.push({id:serial++,x:clamp(target.x+c.rand(-1.3,1.3),-5,5),z:clamp(target.z+c.rand(-1.3,1.3),-5,5),left:big?1.8:1.2,big});}
 return {update(dt){tick-=dt;if(tick<0){spawn(false);tick=c.rand(.5,.95);}if(!mp1(m)&&c.time>=23&&!c.bigMissile){c.bigMissile=true;spawn(true);}c.hint('방향 이동 / A 점프 · 착탄 충격을 뛰어넘으세요');for(const p of alive(c)){p.stun=Math.max(0,p.stun-dt);const candidates=Array.from({length:12},(_,i)=>({x:Math.cos(i*TAU/12)*3.6,z:Math.sin(i*TAU/12)*3.6}));const goal=candidates.sort((a,b)=>Math.min(...shots.map(s=>dist(b,s)),9)-Math.min(...shots.map(s=>dist(a,s)),9))[0];const q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:p.y===0&&shots.some(s=>s.left<.23)}));if(!p.stun)c.move(p,q,4.5,false);c.jump(p,q);p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-4*dt);p.vz*=Math.exp(-4*dt);if(Math.hypot(p.x,p.z)>5.9)c.eliminate(p);}
 for(const s of shots){s.left-=dt;if(s.left<=0&&!s.hit){s.hit=true;blasts.push({...s,age:0});for(const p of alive(c)){const d=dist(p,s);if(p.y<.35)p.stun=.45;if(d<(s.big?2.6:.85)){const dx=(p.x-s.x)/(d||1)||1,dz=(p.z-s.z)/(d||1);p.vx+=dx*(s.big?16:12);p.vz+=dz*(s.big?16:12);}}}}for(let i=shots.length-1;i>=0;i--)if(shots[i].hit)shots.splice(i,1);blasts.forEach(b=>b.age+=dt);for(let i=blasts.length-1;i>=0;i--)if(blasts[i].age>.6)blasts.splice(i,1);separate(c,.45);c.lastStanding();},render(){c.arena({width:12,depth:12,shape:'cylinder',color:'#dec593'});c.draw('ship','box',{x:-9,y:1,z:-7,sx:6,sy:2,sz:3,color:'#855f54'});c.draw('sail','box',{x:-9,y:4,z:-7,sx:2.8,sy:3,sz:.2,color:'#fff1cc'});for(const s of shots){drawCircle(c,'shadow'+s.id,s.x,s.z,s.big?2.6:.8,'#ca9b69');c.draw('shell'+s.id,'sphere',{x:s.x,y:.2+s.left*5,z:s.z,sx:s.big?1.7:.65,sy:s.big?1.7:.65,sz:s.big?1.7:.65,color:'#455d62'});}blasts.forEach(b=>drawCircle(c,'blast'+b.id,b.x,b.z,(b.big?2.6:.8)+b.age,'#ffd674',.08));},timeout(){c.survivors('포격을 견뎌냈습니다');}};
}
function flags(c){
 c.limit=600;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=1;p.choice=-1;});let round=0,phase=0,target=0,fake=false,delay=0;function next(){round++;phase=0;target=c.int(0,1);fake=c.rand()<.4;delay=c.rand(1,2);for(const p of c.players){p.choice=-1;p.reaction=c.rand(.17,.39);}}next();
 return {update(dt){phase+=dt;const reveal=delay+(fake?.45:0),window=Math.max(.25,1.05-round*.035);c.hint('A 흰 깃발 / B 빨간 깃발 · 양쪽 깃발 속임수를 주의하세요');for(const p of alive(c)){const q=c.input(p,()=>({a:target===0&&phase>reveal+p.reaction,b:target===1&&phase>reveal+p.reaction}));if(q.ap)p.choice=0;if(q.bp)p.choice=1;}if(phase>reveal+window){for(const p of alive(c)){if(p.choice!==target)c.eliminate(p);else c.points(p);}c.lastStanding();if(!c.ended)next();}},render(){c.arena({width:16,depth:9,color:'#9ed8d1'});c.draw('host','cone',{x:0,y:1.5,z:-4,sx:1.6,sy:3,sz:1.6,color:'#f19a87'});const show=phase>=delay,real=phase>=delay+(fake?.45:0);for(let i=0;i<2;i++)c.draw('hostFlag'+i,'box',{x:i?1.5:-1.5,y:show&&(!real||i===target)?3.8:1.6,z:-4,sx:1.3,sy:1,sz:.1,color:i?'#e9545c':'#fff5df'});for(const p of c.players){drawCircle(c,'barrel'+p.i,p.x,p.z,1,p.color);if(p.choice>=0)c.draw('playerFlag'+p.i,'box',{x:p.x+.6,y:2.4,z:p.z,sx:.65,sy:.65,sz:.08,color:p.choice?'#e9545c':'#fff5df'});}},timeout(){c.complete([],'동률');}};
}
function tipsy(c){
 c.limit=30;c.view={size:19,eye:[0,25,15],target:[0,0,0]};const states=c.players.map((p,i)=>{const x=(i%2-.5)*7,z=(Math.floor(i/2)-.5)*7;p.x=x;p.z=z;return{x,z,bx:0,bz:0,vx:0,vz:0,flipped:Array(25).fill(false),stun:0,lag:c.rand(.1,1.2)};});
 return {update(dt){const finishers=[];c.hint('방향 이동으로 판 기울이기 / A 점프 · 조개가 모든 칸을 지나야 합니다');for(const p of c.players){const s=states[p.i];s.stun=Math.max(0,s.stun-dt);const todo=s.flipped.map((done,j)=>({done,x:(j%5-2),z:(Math.floor(j/5)-2)})).filter(v=>!v.done).sort((a,b)=>Math.hypot(a.x-s.bx,a.z-s.bz)-Math.hypot(b.x-s.bx,b.z-s.bz));const goal=todo[0]||{x:0,z:0},ax=clamp((goal.x-s.bx)*3-s.vx*2,-2.3,2.3),az=clamp((goal.z-s.bz)*3-s.vz*2,-2.3,2.3);const q=c.input(p,()=>({...toward(p,s.x+ax,s.z+az,Math.hypot(p.x-s.x-ax,p.z-s.z-az)>.15&&c.time>s.lag?1:0),a:Math.hypot(p.x-s.x-s.bx,p.z-s.z-s.bz)<.9&&p.y===0}));if(!s.stun)c.move(p,q,4,false);p.x=clamp(p.x,s.x-2.3,s.x+2.3);p.z=clamp(p.z,s.z-2.3,s.z+2.3);c.jump(p,q);s.vx=(s.vx+(p.x-s.x)*3*dt)*Math.exp(-1.2*dt);s.vz=(s.vz+(p.z-s.z)*3*dt)*Math.exp(-1.2*dt);s.bx+=s.vx*dt;s.bz+=s.vz*dt;if(Math.abs(s.bx)>2.4){s.bx=clamp(s.bx,-2.4,2.4);s.vx*=-.5;}if(Math.abs(s.bz)>2.4){s.bz=clamp(s.bz,-2.4,2.4);s.vz*=-.5;}const col=clamp(Math.round(s.bx)+2,0,4),row=clamp(Math.round(s.bz)+2,0,4);s.flipped[row*5+col]=true;p.score=s.flipped.filter(Boolean).length;if(Math.hypot(p.x-s.x-s.bx,p.z-s.z-s.bz)<.6&&p.y<.3)s.stun=.3;if(p.score===25)finishers.push(p.i);}if(finishers.length)c.complete(finishers,'그림의 모든 칸을 뒤집었습니다');},render(){c.arena({width:16,depth:16,color:'#d1b894'});states.forEach((s,i)=>{s.flipped.forEach((v,j)=>c.draw('tile'+i+'_'+j,'box',{x:s.x+j%5-2,y:-.04,z:s.z+Math.floor(j/5)-2,sx:.96,sy:.15,sz:.96,color:v?(j%2?'#f3bdca':'#ea9baf'):'#f6e8b5'}));c.draw('shell'+i,'sphere',{x:s.x+s.bx,y:.25,z:s.z+s.bz,sx:.65,sy:.4,sz:.65,color:'#498d7a'});drawLabel(c,'tipsyScore'+i,`${c.players[i].score}/25`,s.x,2.8,s.z-2.8,2.5);});},timeout(){c.complete([],'시간 안에 완성한 플레이어가 없습니다');}};
}
function buried(c){
 c.limit=60;c.view={size:21,eye:[0,28,17],target:[0,0,0]};const W=17,H=11,soil=Array.from({length:W*H},(_,i)=>({hp:Math.floor(i/W)<2||Math.floor(i/W)>8?3:1,open:false})),idx=(x,z)=>clamp(Math.round(z)+5,0,H-1)*W+clamp(Math.round(x)+8,0,W-1),treasure=c.rand()<.5?idx(c.int(-5,5),0):idx(0,c.int(-3,3));const arrows=c.shuffle(soil.map((_,i)=>i).filter(i=>i!==treasure&&i%W>3&&i%W<13)).slice(0,6);let revealed=null;
 c.players.forEach((p,i)=>{p.x=(i%2?1:-1)*7;p.z=(i<2?-1:1)*4;p.dig=0;p.facing={x:p.x>0?-1:1,z:0};soil[idx(p.x,p.z)].open=true;});
 return {update(dt){const finishers=[];c.hint('방향 이동 / A 굴착 · 드러난 화살표를 따라 보물을 찾으세요');for(const p of c.players){p.dig-=dt;let goal;{const options=soil.map((s,i)=>({s,i,x:i%W-8,z:Math.floor(i/W)-5})).filter(s=>!s.s.open);const rank=o=>dist(p,o)+Math.hypot(o.x,o.z)*.35+(revealed?Math.max(0,-((o.x-revealed.x)*revealed.vx+(o.z-revealed.z)*revealed.vz))*1.5:0);options.sort((a,b)=>rank(a)-rank(b));goal=options[0]||{x:0,z:0};}const q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:true}));if(Math.hypot(q.x,q.z)>.2)p.facing=Math.abs(q.x)>Math.abs(q.z)?{x:Math.sign(q.x),z:0}:{x:0,z:Math.sign(q.z)};const v=toward({x:0,z:0},q.x,q.z);const target=idx(p.x+v.x*.78,p.z+v.z*.78);if(q.a&&p.dig<=0){p.dig=.18;soil[target].hp--;if(soil[target].hp<=0){soil[target].open=true;if(arrows.includes(target)){const x=target%W-8,z=Math.floor(target/W)-5,dx=treasure%W-8-x,dz=Math.floor(treasure/W)-5-z;revealed={x,z,vx:Math.abs(dx)>Math.abs(dz)?Math.sign(dx):0,vz:Math.abs(dx)>Math.abs(dz)?0:Math.sign(dz)};}if(target===treasure)finishers.push(p.i);}}const nx=clamp(p.x+q.x*2.5*dt,-8,8),nz=clamp(p.z+q.z*2.5*dt,-5,5);if(soil[idx(nx,nz)].open){p.x=nx;p.z=nz;p.pose='run';}else p.pose=q.a?'hit':'idle';}if(finishers.length)c.complete(finishers,'보물상자를 먼저 발견했습니다');},render(){c.arena({width:18,depth:12,color:'#c49b6d'});soil.forEach((s,i)=>{const x=i%W-8,z=Math.floor(i/W)-5;if(!s.open)c.draw('dirt'+i,'box',{x,y:.18,z,sx:.96,sy:s.hp>1?.65:.3,sz:.96,color:s.hp>1?'#928b83':'#ceaa7c'});else if(arrows.includes(i)){const tx=treasure%W-8,tz=Math.floor(treasure/W)-5;drawLabel(c,'arrow'+i,Math.abs(tx-x)>Math.abs(tz-z)?(tx>x?'→':'←'):(tz>z?'↓':'↑'),x,.12,z,.85);}});if(c.ended)c.draw('treasure','box',{x:treasure%W-8,y:.35,z:Math.floor(treasure/W)-5,sx:.8,sy:.7,sz:.65,color:'#f3cf68'});},timeout(){c.complete([],'보물을 찾지 못했습니다');}};
}
function balloons(c,m){
 c.limit=30;c.view={size:20,eye:[0,19,20],target:[0,1,0]};const team=m.format==='2v2',groups=team?[[0,1],[2,3]]:[[0],[1],[2],[3]],air=groups.map(()=>0),pumps=c.players.map(()=>({height:0,pause:c.rand(0,1),push:false}));c.players.forEach((p,i)=>{p.x=(i-1.5)*3.6;p.z=2;});
 return {update(dt){const finishers=[];c.hint(team?'A 펌프 내리기 / B 올리기 · 팀 풍선을 터뜨리세요':'A 펌프 내리기 / B 올리기 · 충분히 왕복하세요');for(const p of c.players){const s=pumps[p.i],q=c.input(p,()=>{if(s.height>.95&&!s.push){s.push=true;s.pause=c.time+c.rand(0,.1);}if(s.height<.02&&s.push){s.push=false;s.pause=c.time+c.rand(0,.1);}return {a:s.push&&c.time>s.pause,b:!s.push&&c.time>s.pause};});const before=s.height;if(q.b&&!q.a)s.height=Math.min(1,s.height+dt*2.3);if(q.a&&!q.b)s.height=Math.max(0,s.height-dt*2.3);const g=team?Math.floor(p.i/2):p.i;if(before>s.height)air[g]+=before-s.height;p.score=+(air[g]*100/(team?28:16)).toFixed(1);p.pose='hit';if(air[g]>=(team?28:16))finishers.push(...groups[g]);}if(finishers.length)c.complete(finishers,'풍선을 터뜨렸습니다');},render(){c.arena({width:19,depth:13,color:'#cdb5d2'});for(const p of c.players){c.draw('pump'+p.i,'cylinder',{x:p.x,y:.5,z:1,sx:.7,sy:1,sz:.7,color:p.color});c.draw('handle'+p.i,'box',{x:p.x,y:1+pumps[p.i].height*.65,z:1,sx:1.1,sy:.16,sz:.2,color:'#f4deb0'});}groups.forEach((g,i)=>{const x=team?(i-.5)*7.2:(i-1.5)*3.6,size=1+air[i]/(team?28:16)*2.7;c.draw('balloon'+i,'sphere',{x,y:2+size*.3,z:-2.2,sx:size,sy:size*1.15,sz:size,color:c.players[g[0]].color});c.draw('string'+i,'cylinder',{x,y:1,z:-2.2,sx:.03,sy:2,sz:.03,color:'#6d6777'});});},timeout(){c.complete([],'풍선이 터지지 않아 무승부');}};
}
function slotcars(c,m){
 c.limit=mp1(m)?120:300;c.view={size:19,eye:[0,24,15],target:[0,0,0]};const states=c.players.map(()=>({a:0,v:0,spin:0,started:false,margin:c.rand(.035,.19)}));
 return {update(dt){const arrivals=[];c.hint(c.time<2.5?'출발 신호를 기다리세요':'방향 입력으로 가속 / 놓으면 감속 · 코너에서 과속 주의 · 4바퀴');for(const p of alive(c)){const s=states[p.i],bend=Math.abs(Math.cos(s.a)),safe=bend>.6?.9:1.7;const q=c.input(p,()=>({x:c.time>2.5&&s.v<safe-s.margin?1:0})),throttle=Math.min(1,Math.hypot(q.x,q.z));if(c.time<2.5){if(throttle>.1)s.spin=.7;continue;}s.spin=Math.max(0,s.spin-dt);if(s.spin>0)s.v*=Math.exp(-3*dt);else{s.v=clamp(s.v+(throttle*2.2-.8)*dt,0,1.8);if(bend>.6&&s.v>1.15){s.spin=1;s.v=.2;}}s.a+=s.v*dt;p.score=Math.min(4,Math.floor(s.a/TAU));const radius=5.6+p.i*.5;p.x=Math.cos(s.a)*radius;p.z=Math.sin(s.a)*(3.1+p.i*.4);p.rotation=-s.a-Math.PI/2;p.scale=.55;p.pose='balance';if(s.a>=TAU*4)arrivals.push({i:p.i,t:(TAU*4-(s.a-s.v*dt))/(s.v||1)});}if(arrivals.length){const t=Math.min(...arrivals.map(a=>a.t));c.complete(arrivals.filter(a=>Math.abs(a.t-t)<1e-8).map(a=>a.i),'4바퀴 완주');}const leader=Math.max(...states.map(s=>s.a));for(const p of alive(c))if(leader-states[p.i].a>TAU)c.eliminate(p);},render(){c.arena({width:18,depth:13,color:'#d9c593'});for(let i=0;i<4;i++){c.draw('track'+i,'ring',{x:0,y:.03+i*.005,z:0,sx:(5.6+i*.5)*2,sy:(3.1+i*.4)*2,sz:1,rx:-Math.PI/2,color:i%2?'#8a989a':'#657c82'});const p=c.players[i];c.draw('car'+i,'box',{x:p.x,y:.2,z:p.z,sx:.8,sy:.35,sz:1.1,ry:-p.rotation,color:p.color});}drawLabel(c,'start',c.time<2.5?String(Math.ceil(2.5-c.time)):'4 LAPS',0,1,0,4);},timeout(){c.complete([],'시간 내 완주자가 없어 무승부');}};
}
function tanks(c){
 c.limit=60;c.bounds={x:6.3,z:5};const pipes=[{x:0,z:0,r:1.05}],shots=[];let id=0;c.players.forEach((p,i)=>{p.x=(i%2-.5)*9;p.z=(i<2?-1:1)*3.5;p.hp=2;p.cool=0;p.botOrbit=c.pick([-1,1]);p.botDrive=c.rand(.72,1);p.dir={x:p.x>0?-1:1,z:0};});
 return {update(dt){c.hint('방향 이동 / A 직사포 / B 곡사포 / C 조준 고정 · 두 번 맞으면 탈락');for(const p of alive(c)){p.cool=Math.max(0,p.cool-dt);const target=alive(c).filter(o=>o!==p).sort((a,b)=>dist(p,a)-dist(p,b))[0];const q=c.input(p,()=>{if(!target)return {};const v=toward(p,target.x,target.z),obstruct=pipes.some(r=>Math.abs((target.z-p.z)*r.x-(target.x-p.x)*r.z+target.x*p.z-target.z*p.x)/(dist(p,target)||1)<r.r);const near=dist(p,target);if(obstruct){const r=Math.hypot(p.x,p.z)||1;return {x:(r<2.8?p.x/r:-p.z/r*p.botOrbit)*p.botDrive,z:(r<2.8?p.z/r:p.x/r*p.botOrbit)*p.botDrive,b:pulse(c.time,1.5,p.i*.2)};}return {x:v.x*(near<2.8?-1:1),z:v.z*(near<2.8?-1:1),a:pulse(c.time,2,p.i*.2)};});if(!q.c&&Math.hypot(q.x,q.z)>.1)p.dir=toward({x:0,z:0},q.x,q.z);const before={x:p.x,z:p.z};c.move(p,q,2.7);for(const r of pipes)if(dist(p,r)<r.r+.55){p.x=before.x;p.z=before.z;}p.rotation=Math.atan2(-p.dir.z,p.dir.x);if((q.ap||q.bp)&&p.cool===0){p.cool=.7;shots.push({id:id++,owner:p.i,x:p.x+p.dir.x*.9,z:p.z+p.dir.z*.9,vx:p.dir.x*(q.bp?6:10),vz:p.dir.z*(q.bp?6:10),age:0,lob:q.bp});}}
 separate(c,.6);for(const s of shots){s.age+=dt;s.x+=s.vx*dt;s.z+=s.vz*dt;s.y=s.lob?.3+Math.sin(Math.min(1,s.age/1.2)*Math.PI)*2.6:.35;if(Math.abs(s.x)>7||Math.abs(s.z)>6||s.age>2)s.dead=true;if(!s.lob&&s.y<1.6&&pipes.some(r=>dist(s,r)<r.r))s.dead=true;for(const p of alive(c))if(!s.dead&&p.i!==s.owner&&s.y<1.3&&dist(s,p)<.65){p.hp--;s.dead=true;if(p.hp===0)c.eliminate(p);}}
 for(let i=0;i<shots.length;i++)for(let j=i+1;j<shots.length;j++)if(!shots[i].dead&&!shots[j].dead&&dist(shots[i],shots[j])<.3&&Math.abs(shots[i].y-shots[j].y)<.4)shots[i].dead=shots[j].dead=true;for(let i=shots.length-1;i>=0;i--)if(shots[i].dead)shots.splice(i,1);c.lastStanding();},render(){c.arena({width:14,depth:12,color:'#d9b482'});pipes.forEach((r,i)=>c.draw('pipe'+i,'cylinder',{x:r.x,y:.8,z:r.z,sx:r.r*2,sy:1.6,sz:r.r*2,color:'#579c86'}));for(const p of c.players){c.draw('tank'+p.i,'box',{x:p.x,y:.2,z:p.z,sx:1.4,sy:.45,sz:1.2,color:p.color,ry:-p.rotation});c.draw('gun'+p.i,'box',{x:p.x+p.dir.x*.9,y:.5,z:p.z+p.dir.z*.9,sx:1.15,sy:.2,sz:.2,ry:Math.atan2(-p.dir.z,p.dir.x),color:'#566971'});drawLabel(c,'hp'+p.i,'●'.repeat(p.hp),p.x,2.5,p.z,1.7);}shots.forEach(s=>c.draw('shot'+s.id,'sphere',{x:s.x,y:s.y,z:s.z,sx:.35,sy:.35,sz:.35,color:'#3c5260'}));},timeout(){c.complete([],'둘 이상 남아 무승부');}};
}
function marathon(c,m){
 const winding=m.titleId==='top-100'?7:10,cap=m.titleId==='top-100'?40:m.titleId==='superstars'?70:Infinity;c.limit=50;c.view={size:21,eye:[0,22,22],target:[0,1,-2]};const states=c.players.map((p,i)=>{p.x=(i-1.5)*3.8;p.z=5;return{winds:0,distance:0,flight:0,frequency:c.rand(6.3,9.5),phase:c.rand(0,1)};});let finished=false;
 return {update(dt){c.hint(c.time<winding?`${winding}초 동안 A+B를 동시에 반복하세요`:'태엽 비행 거리 측정 중');for(const p of c.players){const s=states[p.i],q=c.input(p,()=>({a:pulse(c.time,s.frequency,s.phase),b:pulse(c.time,s.frequency,s.phase)}));if(c.time<=winding){if(q.ap&&q.bp)s.winds++;p.pose='hit';}else{s.distance=Math.min(cap,s.winds*.62);s.flight=Math.min(s.distance,(c.time-winding)*7);p.score=+s.flight.toFixed(2);p.pose='idle';}}if(c.time>winding+Math.max(...states.map(s=>s.distance))/7+1&&!finished){finished=true;for(const p of c.players)p.score=+states[p.i].distance.toFixed(2);c.highest('가장 멀리 비행했습니다');}},render(){c.arena({width:18,depth:18,color:'#cad9b4'});states.forEach((s,i)=>{const x=c.players[i].x,z=3-s.flight*.2,y=c.time<winding?1.4:s.flight<s.distance?2.5:.3;c.draw('toy'+i,'sphere',{x,y,z,sx:.9,sy:1,sz:.75,color:c.players[i].color});c.draw('wing'+i,'box',{x,y:y+.15,z,sx:1.8,sy:.1,sz:.35,rz:c.time>winding?Math.sin(c.time*25)*.3:0,color:'#f8ecc4'});drawLabel(c,'distance'+i,c.time<winding?String(s.winds):`${s.flight.toFixed(1)} m`,x,4,z,3);for(let j=0;j<7;j++)c.draw('marker'+i+'_'+j,'box',{x,y:.01,z:3-j*2,sx:2.5,sy:.04,sz:.04,color:'#a3b09b'});});},timeout(){c.highest('비행 거리');}};
}
function count(c,m){
 const species=m.titleId==='superstars'?c.int(0,2):0;c.limit=30;c.view={size:21,eye:[0,26,18],target:[0,0,-1]};const mobs=Array.from({length:c.int(14,19)},(_,i)=>({x:c.rand(-6,6),z:c.rand(-5,2),vx:c.rand(-.6,.6),vz:c.rand(-.6,.6),explode:species===0&&i<3?c.rand(10,23):Infinity,phase:c.rand(0,6)}));const crates=Array.from({length:4},()=>({x:c.rand(-6,6),z:c.rand(-4,2)}));c.players.forEach((p,i)=>{p.x=(i-1.5)*3.8;p.z=5;p.target=0;p.recount=0;p.botDelay=c.rand(.4,1.6);});
 return {update(dt){c.hint(species===0?'A +1 / B −1 · 상자와 폭발한 폭탄을 제외하세요':species===1?'A +1 / B −1 · 잠시 사라진 유령도 세세요':'A +1 / B −1 · 움직이는 새만 세고 버섯 장식은 제외하세요');for(const b of mobs){b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>6)b.vx*=-1;if(b.z>2||b.z<-5)b.vz*=-1;}for(const p of c.players){p.recount-=dt;if(p.recount<0){p.target=mobs.filter(b=>b.explode>c.time).length;p.recount=p.botDelay;}const q=c.input(p,()=>({a:p.score<p.target&&pulse(c.time,5,p.i*.17),b:p.score>p.target&&pulse(c.time,5,p.i*.17)}));if(q.ap)p.score=Math.min(99,p.score+1);if(q.bp)p.score=Math.max(0,p.score-1);}},render(){c.arena({width:17,depth:15,color:'#d1ba97'});mobs.forEach((b,i)=>{if(b.explode<c.time||species===1&&Math.sin(c.time*1.3+b.phase)<-.3)return;c.draw('mob'+i,'sphere',{x:b.x,y:.35,z:b.z,sx:.7,sy:.7,sz:.7,color:species===1?'#eee5d0':species===2?'#db99b0':b.explode-c.time<2?'#e87769':'#547380'});c.draw('fuse'+i,species===2?'sphere':'cylinder',{x:b.x,y:.83,z:b.z,sx:.1,sy:.4,sz:.1,color:'#f0bc65'});});crates.forEach((r,i)=>{c.draw('crate'+i,species===2?'cylinder':'box',{x:r.x,y:.5,z:r.z,sx:1,sy:1,sz:1,color:'#b78561'});c.draw('paint'+i,'sphere',{x:r.x,y:1,z:r.z,sx:.65,sy:.05,sz:.65,color:'#577783'});});for(const p of c.players)drawLabel(c,'answer'+p.i,String(p.score),p.x,3,p.z,2);if(c.ended)drawLabel(c,'answerTrue',`정답 ${mobs.filter(b=>b.explode>c.time).length}`,0,5,-2,6);},timeout(){const n=mobs.filter(b=>b.explode>c.time).length;const closest=Math.min(...c.players.map(p=>Math.abs(p.score-n)));c.complete(c.players.filter(p=>m.titleId==='mp2'?p.score===n:Math.abs(p.score-n)===closest).map(p=>p.i),`정답은 ${n}개`);}};
}
function lavaTiles(c){
 c.limit=30;c.view={size:20,eye:[0,24,18],target:[0,0,0]};const pads=Array.from({length:9},(_,i)=>({x:(i%3-1)*2.8,z:(Math.floor(i/3)-1)*2.8,gx:i%3,gz:Math.floor(i/3)}));let moving=null,phase=0,wait=1.5;c.players.forEach((p,i)=>{p.x=(i%2-.5)*5.6;p.z=(i<2?-1:1)*2.8;});
 function start(){const opts=[];pads.forEach(s=>{for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=s.gx+dx,z=s.gz+dz;if(x>=-1&&x<=3&&z>=-1&&z<=3&&!pads.some(t=>t.gx===x&&t.gz===z))opts.push({s,x,z});}});moving=c.pick(opts);phase=0;if(moving){moving.ox=moving.s.x;moving.oz=moving.s.z;}}
 return {update(dt){wait-=dt;if(!moving&&wait<=0)start();if(moving){phase+=dt;const t=clamp((phase-.6)/.9,0,1),s=moving.s,nx=moving.ox+(moving.x*2.8-2.8-moving.ox)*t,nz=moving.oz+(moving.z*2.8-2.8-moving.oz)*t;for(const p of alive(c))if(p.y===0&&Math.abs(p.x-s.x)<1.4&&Math.abs(p.z-s.z)<1.4){p.x+=nx-s.x;p.z+=nz-s.z;}s.x=nx;s.z=nz;if(t===1){s.gx=moving.x;s.gz=moving.z;moving=null;wait=1.5;}}
 c.hint('방향 이동 / A 점프 / B 공격 / C 내려찍기 · 움직이는 돌 위에서 버티세요');for(const p of alive(c)){const target=pads.reduce((a,b)=>Math.hypot(b.x,b.z)<Math.hypot(a.x,a.z)?b:a),q=c.input(p,()=>({...toward(p,target.x+(p.i%2-.5),target.z+(Math.floor(p.i/2)-.5)),a:p.y===0&&pulse(c.time,1.1,p.i*.2),b:pulse(c.time,2,p.i*.25)}));if(!p.stun)c.move(p,q,3.8,false);c.jump(p,q);fighting(c,p,q,dt);}separate(c,.45);for(const p of alive(c))if(p.y===0&&!pads.some(s=>Math.abs(p.x-s.x)<1.4&&Math.abs(p.z-s.z)<1.4))c.eliminate(p);c.lastStanding();},render(){c.arena({width:23,depth:23,color:'#dd7956'});pads.forEach((s,i)=>{c.draw('stone'+i,'box',{x:s.x,y:-.2,z:s.z,sx:2.78,sy:.4,sz:2.78,color:moving?.s===s&&phase<.6?'#e2bd75':'#8faaa2'});c.draw('eye'+i,'box',{x:s.x-.5,y:.03,z:s.z-.2,sx:.25,sy:.1,sz:.35,color:'#4d6865'});});},timeout(){c.complete([],'둘 이상 남아 무승부');}};
}
function totems(c){
 c.limit=30;c.view={size:19,eye:[0,17,22],target:[0,1,0]};const states=c.players.map((p,i)=>{p.x=(i-1.5)*3.5;p.z=0;return{h:0,vy:0,peak:0,pound:false,depth:0,charge:c.rand(1.25,1.85)};});
 return {update(dt){const finishers=[];c.hint('A 점프 / C 내려찍기 · 높은 곳에서 찍을수록 깊이 들어갑니다');for(const p of c.players){const s=states[p.i],q=c.input(p,()=>({a:s.h===0,c:s.h>s.charge}));if(q.ap&&s.h===0){s.vy=8.5;s.h=.001;s.peak=0;}if(q.cp&&s.h>0){s.pound=true;s.vy=-15;}if(s.h>0){s.vy-=18*dt;s.h=Math.max(0,s.h+s.vy*dt);s.peak=Math.max(s.peak,s.h);if(s.h===0&&s.pound){s.depth+=Math.max(.3,s.peak*1.65);s.pound=false;}}p.y=s.h+Math.max(0,3.8-s.depth*.09);p.pose=s.h>0?'jump':'idle';p.score=+Math.min(42,s.depth).toFixed(1);if(s.depth>=42)finishers.push(p.i);}if(finishers.length)c.complete(finishers,'토템을 모두 박았습니다');},render(){c.arena({width:18,depth:9,color:'#d0b789'});states.forEach((s,i)=>{const h=Math.max(.15,3.8-s.depth*.09);c.draw('totem'+i,'cylinder',{x:c.players[i].x,y:h/2,z:0,sx:1.9,sy:h,sz:1.9,color:c.players[i].color});for(let j=0;j<3;j++)if(h>j)c.draw('totemBand'+i+'_'+j,'cylinder',{x:c.players[i].x,y:j+.15,z:0,sx:1.95,sy:.15,sz:1.95,color:'#f3d995'});});},timeout(){c.complete([],'토템을 완전히 박지 못했습니다');}};
}
function dizzy(c,m){
 const collection=m.titleId!=='mp2';let note={x:0,z:0},cool=0;c.limit=30;c.bounds={x:6,z:6};const rotations=c.players.map(()=>c.pick([Math.PI/2,Math.PI,-Math.PI/2]));c.players.forEach((p,i)=>{p.x=(i%2-.5)*7;p.z=(i<2?-1:1)*3.5;p.botLag=c.rand(.25,1.4);});
 return {update(dt){cool=Math.max(0,cool-dt);const finishers=[];c.hint(collection?'방향이 바뀌었습니다 · A 점프 / B 공격 / C 내려찍기 · 30초 동안 음표 모으기':'어지러워 방향이 바뀌었습니다 · A 점프 / B 공격 · 중앙 음표 하나를 먼저 잡으세요');for(const p of c.players){const a=rotations[p.i],cos=Math.cos(a),sin=Math.sin(a),q=c.input(p,()=>{const v=toward(p,note.x,note.z,dist(p,note)>.18&&c.time>p.botLag?1:0);return{x:v.x*cos+v.z*sin,z:-v.x*sin+v.z*cos,a:dist(p,note)<1.5&&p.y===0,b:dist(p,note)<2&&pulse(c.time,2,p.i*.13)};});const v={...q,x:q.x*cos-q.z*sin,z:q.x*sin+q.z*cos};if(!p.stun)c.move(p,v,3.3);c.jump(p,q);fighting(c,p,q,dt);if(dist(p,note)<.7&&p.y>1.1&&cool===0)finishers.push(p.i);}separate(c,.43);if(finishers.length){if(collection){for(const i of finishers)c.points(c.players[i],1);const angle=c.rand(0,Math.PI*2),r=c.rand(0,4);note={x:Math.cos(angle)*r,z:Math.sin(angle)*r};cool=.35;}else c.complete(finishers,'음표를 먼저 잡았습니다');}},render(){c.arena({width:14,depth:14,shape:'cylinder',color:'#536b76'});for(let r=1;r<=5;r++)c.draw('groove'+r,'ring',{x:0,y:.015,z:0,sx:r*2,sy:r*2,sz:1,rx:-Math.PI/2,color:'#344d59'});drawCircle(c,'recordCenter',0,0,1.3,'#f1a4bd');drawLabel(c,'note','♪',note.x,2.5,note.z,2);},timeout(){if(collection)c.highest('수집한 음표 수');else c.complete([],'음표를 잡지 못해 무승부');}};
}
function tiles(c){
 c.limit=60;c.view={size:22,eye:[0,29,18],target:[0,0,0]};const target=c.int(0,2),states=c.players.map((p,i)=>{const x=(i%2-.5)*8,z=(i<2?-1:1)*4;p.x=x;p.z=z;return{x,z,tiles:Array.from({length:9},()=>c.int(0,2)),pound:false};});
 return {update(dt){const finishers=[];c.hint(`표본 ${target+1}번 그림으로 맞추세요 · A 점프 / C 내려찍기`);for(const p of c.players){const s=states[p.i],wrong=s.tiles.map((v,i)=>({v,i,x:s.x+(i%3-1)*1.5,z:s.z+(Math.floor(i/3)-1)*1.5})).filter(t=>t.v!==target).sort((a,b)=>dist(p,a)-dist(p,b)),goal=wrong[0]||s;const q=c.input(p,()=>({...toward(p,goal.x,goal.z,dist(p,goal)>.08?1:0),a:dist(p,goal)<.3&&p.y===0,c:p.y>.85}));c.move(p,q,4,false);p.x=clamp(p.x,s.x-2.15,s.x+2.15);p.z=clamp(p.z,s.z-2.15,s.z+2.15);c.jump(p,q);if(q.cp&&p.y>0){s.pound=true;p.vy=-13;}if(s.pound&&p.y===0){s.pound=false;const j=clamp(Math.round((p.z-s.z)/1.5)+1,0,2)*3+clamp(Math.round((p.x-s.x)/1.5)+1,0,2);s.tiles[j]=(s.tiles[j]+1)%3;}p.score=s.tiles.filter(v=>v===target).length;if(p.score===9)finishers.push(p.i);}if(finishers.length)c.complete(finishers,'그림을 완성했습니다');},render(){c.arena({width:19,depth:18,color:'#bcbed5'});states.forEach((s,i)=>s.tiles.forEach((v,j)=>{c.draw('panel'+i+'_'+j,'box',{x:s.x+(j%3-1)*1.5,y:-.1,z:s.z+(Math.floor(j/3)-1)*1.5,sx:1.44,sy:.2,sz:1.44,color:palette[v]});drawLabel(c,'symbol'+i+'_'+j,`${v+1}`,s.x+(j%3-1)*1.5,.03,s.z+(Math.floor(j/3)-1)*1.5,.8);}));drawLabel(c,'target',`표본 ${target+1}`,0,5,0,5);},timeout(){c.complete([],'시간 안에 완성하지 못했습니다');}};
}
function snow(c,m){
 c.limit=60;c.view={size:19,eye:[0,22,19],target:[0,0,0]};const balls=[];let id=0;c.players.forEach((p,i)=>{p.x=Math.cos(i*TAU/4)*3.5;p.z=Math.sin(i*TAU/4)*3.5;p.ball=null;p.vx=p.vz=0;p.botCharge=c.rand(.5,.85);p.botPhase=c.rand(0,1);p.face={x:-Math.cos(i*TAU/4),z:-Math.sin(i*TAU/4)};});
 return {update(dt){c.hint('방향 이동·눈덩이 굴리기 / B 반복해 만들기 / A 밀어 발사');for(const p of alive(c)){const target=alive(c).filter(o=>o!==p).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>{const v=target?toward(p,target.x,target.z):{x:0,z:0};return{...v,b:(!p.ball||p.ball.r<p.botCharge)&&pulse(c.time,6,p.botPhase),a:!!p.ball&&p.ball.r>=p.botCharge&&pulse(c.time,2,p.botPhase)};});c.move(p,q,p.ball?2.5:4,false);if(Math.hypot(q.x,q.z)>.1)p.face=toward({x:0,z:0},q.x,q.z);p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-3*dt);p.vz*=Math.exp(-3*dt);if(q.bp){if(!p.ball){p.ball={id:id++,owner:p.i,x:p.x,z:p.z,r:.23,vx:0,vz:0,free:false};balls.push(p.ball);}else p.ball.r=Math.min(1.15,p.ball.r+.055);}if(p.ball){p.ball.r=Math.min(1.15,p.ball.r+Math.hypot(q.x,q.z)*dt*.08);p.ball.x=p.x+p.face.x*(p.ball.r+.65);p.ball.z=p.z+p.face.z*(p.ball.r+.65);if(q.ap){p.ball.free=true;p.ball.vx=p.face.x*9;p.ball.vz=p.face.z*9;p.ball=null;}}if(Math.hypot(p.x,p.z)>6)c.eliminate(p);}
 for(const b of balls){if(b.free){b.x+=b.vx*dt;b.z+=b.vz*dt;b.vx*=Math.exp(-.12*dt);b.vz*=Math.exp(-.12*dt);}if(Math.hypot(b.x,b.z)>8)b.dead=true;for(const p of alive(c))if(p.i!==b.owner&&dist(b,p)<b.r+.5){const d=dist(b,p)||1;p.vx+=(p.x-b.x)/d*(8+b.r*11);p.vz+=(p.z-b.z)/d*(8+b.r*11);b.dead=true;if(p.ball)p.ball.dead=true;p.ball=null;}}
 for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++)if(dist(balls[i],balls[j])<balls[i].r+balls[j].r)balls[i].dead=balls[j].dead=true;for(const p of c.players)if(p.ball?.dead)p.ball=null;for(let i=balls.length-1;i>=0;i--)if(balls[i].dead)balls.splice(i,1);separate(c,.45);c.lastStanding();},render(){c.arena({width:12,depth:12,shape:'cylinder',color:'#ddf0ef'});balls.forEach(b=>c.draw('snow'+b.id,'sphere',{x:b.x,y:b.r,z:b.z,sx:b.r*2,sy:b.r*2,sz:b.r*2,color:'#fff9ed'}));},timeout(){if(m.titleId==='mp3')c.complete([],'둘 이상 남아 무승부');else c.survivors('60초 생존');}};
}
function ice(c){
 c.limit=30;c.bounds={x:6,z:4.8};const shells=[];let next=0;c.players.forEach((p,i)=>{p.x=(i%2-.5)*7;p.z=(i<2?-1:1)*2.6;p.vx=p.vz=0;});
 return {update(dt){if(c.time>=next&&shells.length<3){const a=c.rand(0,TAU);shells.push({x:0,z:0,vx:Math.cos(a)*4,vz:Math.sin(a)*4});next+=10;}c.hint('방향 이동 / A 점프 · 미끄러운 링크에서 가시 껍질 피하기');for(const s of shells){s.x+=s.vx*dt;s.z+=s.vz*dt;if(Math.abs(s.x)>6){s.x=clamp(s.x,-6,6);s.vx*=-1;}if(Math.abs(s.z)>4.8){s.z=clamp(s.z,-4.8,4.8);s.vz*=-1;}}for(const p of alive(c)){let dx=-p.x*.18,dz=-p.z*.18;for(const s of shells){const d=dist(p,s);if(d<3){dx+=(p.x-s.x)/(d*d+.1)*4;dz+=(p.z-s.z)/(d*d+.1)*4;}}const q=c.input(p,()=>({x:clamp(dx,-1,1),z:clamp(dz,-1,1),a:p.y===0&&shells.some(s=>Math.hypot(s.x+s.vx*.2-p.x,s.z+s.vz*.2-p.z)<1.2)}));p.vx=(p.vx+q.x*10*dt)*Math.exp(-2.2*dt);p.vz=(p.vz+q.z*10*dt)*Math.exp(-2.2*dt);p.x=clamp(p.x+p.vx*dt,-6,6);p.z=clamp(p.z+p.vz*dt,-4.8,4.8);c.jump(p,q);if(p.y<.48&&shells.some(s=>dist(p,s)<.7))c.eliminate(p);}separate(c,.4);c.lastStanding();},render(){c.arena({width:13,depth:11,color:'#c2e5ed'});for(const [i,x,z,sx,sz] of [[0,0,-5.2,13,.4],[1,0,5.2,13,.4],[2,-6.5,0,.4,11],[3,6.5,0,.4,11]])c.draw('wall'+i,'box',{x,y:.6,z,sx,sy:1.2,sz,color:'#8cbecb'});shells.forEach((s,i)=>{c.draw('spiny'+i,'sphere',{x:s.x,y:.28,z:s.z,sx:.9,sy:.65,sz:.9,color:'#d88890'});for(let j=0;j<5;j++)c.draw('spike'+i+'_'+j,'cone',{x:s.x+Math.cos(j*TAU/5)*.22,y:.7,z:s.z+Math.sin(j*TAU/5)*.22,sx:.18,sy:.4,sz:.18,color:'#fff0cf'});});},timeout(){c.survivors('30초 생존');}};
}
function storm(c){
 c.limit=30;c.bounds={x:6.5,z:4.7};const cloud={x:0,z:0,vx:2,vz:1},moles=[];let change=2,moleTime=7,id=0;c.players.forEach(p=>p.stun=0);
 return {update(dt){change-=dt;if(change<0){change=c.rand(1.1,2.3);const a=c.rand(0,TAU);cloud.vx=Math.cos(a)*2.5;cloud.vz=Math.sin(a)*2.5;}cloud.x+=cloud.vx*dt;cloud.z+=cloud.vz*dt;if(Math.abs(cloud.x)>5.5){cloud.x=clamp(cloud.x,-5.5,5.5);cloud.vx*=-1;}if(Math.abs(cloud.z)>3.7){cloud.z=clamp(cloud.z,-3.7,3.7);cloud.vz*=-1;}moleTime-=dt;if(moleTime<0){moleTime=2.7;moles.push({id:id++,x:c.rand(-5,5),z:c.rand(-3.5,3.5),age:0});}moles.forEach(m=>m.age+=dt);for(let i=moles.length-1;i>=0;i--)if(moles[i].age>4)moles.splice(i,1);c.hint('방향 이동 · 비구름 아래에서 화분에 물을 받으세요');for(const p of c.players){p.stun=Math.max(0,p.stun-dt);const q=c.input(p,()=>toward(p,cloud.x+cloud.vx*.15,cloud.z+cloud.vz*.15,dist(p,cloud)>.15?1:0));if(!p.stun)c.move(p,q,4.5);if(moles.some(m=>m.age>.5&&dist(p,m)<.65))p.stun=.45;if(dist(p,cloud)<1.4)p.score+=dt;}separate(c,.45);},render(){c.arena({width:15,depth:11,color:'#b8ca8c'});drawCircle(c,'rainArea',cloud.x,cloud.z,1.4,'#84bfc2');for(let i=0;i<5;i++)c.draw('cloud'+i,'sphere',{x:cloud.x+(i-2)*.5,y:4+Math.sin(i)*.15,z:cloud.z,sx:1.4,sy:1,sz:1.4,color:'#f4f4e5'});for(let i=0;i<12;i++)c.draw('rain'+i,'cylinder',{x:cloud.x+Math.sin(i*7)*1.15,y:3.5-((c.time*5+i*.25)%3),z:cloud.z+Math.cos(i*7)*1.15,sx:.045,sy:.3,sz:.045,color:'#70a8c1'});moles.forEach(m=>c.draw('mole'+m.id,'sphere',{x:m.x,y:m.age<.5?-.2:.3,z:m.z,sx:.9,sy:.8,sz:.9,color:'#a88769'}));for(const p of c.players){c.draw('pot'+p.i,'cylinder',{x:p.x+.5,y:.5,z:p.z-.2,sx:.55,sy:.7,sz:.55,color:'#c88664'});c.draw('plant'+p.i,'sphere',{x:p.x+.5,y:1.2+Math.min(1,p.score/10),z:p.z-.2,sx:.55,sy:.7,sz:.55,color:'#77a765'});}},timeout(){const high=Math.max(...c.players.map(p=>p.score));c.complete(c.players.filter(p=>Math.abs(p.score-high)<1e-5).map(p=>p.i),'가장 많은 빗물을 받았습니다');}};
}
function clockHop(c){
 c.limit=600;c.view={size:18,eye:[0,25,16],target:[0,0,0]};c.players.slice(2).forEach(p=>{p.visible=false;p.alive=false;});c.players.slice(0,2).forEach((p,i)=>{p.radius=2.6+i*2;p.y=0;});let hour=0,minute=-Math.PI/2,passes=0,lastSign=-1;
 return {update(dt){const stage=Math.floor(c.time/12),hs=stage%3===2?.5:0,ms=(stage%4===3?-1:1)*(1.2+Math.min(stage*.2,1.2)),old=wrap(minute-hour);hour+=hs*dt;minute+=ms*dt;const relative=wrap(minute-hour);c.hint(`A 점프 · ${passes}/99 · 움직이는 분침을 넘으세요`);for(const p of c.players.slice(0,2)){if(!p.alive)continue;const approaching=wrap(relative+(ms-hs)*.23);const q=c.input(p,()=>({a:p.y===0&&Math.abs(approaching)<.28}));c.jump(p,q,7.3);p.x=Math.cos(hour)*p.radius;p.z=Math.sin(hour)*p.radius;p.rotation=-hour-Math.PI/2;if(Math.abs(relative)<.23/p.radius&&p.y<.45)c.eliminate(p);}if(Math.sign(old)!==Math.sign(relative)&&Math.abs(relative)<1){passes++;for(const p of alive(c))p.score=passes;}if(passes>=99)c.complete([],'99회 생존으로 무승부');c.lastStanding();},render(){c.arena({width:13,depth:13,shape:'cylinder',color:'#e4d5a9'});for(let i=1;i<=12;i++){const a=i*TAU/12-Math.PI/2;drawLabel(c,'number'+i,String(i),Math.cos(a)*5.7,.05,Math.sin(a)*5.7,1.1);}c.draw('hour','box',{x:Math.cos(hour)*2.5,y:.05,z:Math.sin(hour)*2.5,sx:5.5,sy:.14,sz:.85,ry:-hour,color:'#667f84'});c.draw('minute','box',{x:Math.cos(minute)*2.8,y:.22,z:Math.sin(minute)*2.8,sx:6,sy:.25,sz:.35,ry:-minute,color:'#d7916c'});c.draw('pivot','sphere',{x:0,y:.3,z:0,sx:.7,sy:.6,sz:.7,color:'#c0a25d'});},timeout(){c.complete([],'동률');}};
}
export const games={
 'Mushroom Mix-Up':mushroom,'Hot Rope Jump':rope,'Bumper Balls':bumpers,'Bombs Away':bombs,'Shy Guy Says':flags,'Tipsy Tourney':tipsy,'Buried Treasure':buried,'Balloon Burst':balloons,'Slot Car Derby':slotcars,
 'Shell Shocked':tanks,'Mecha-Marathon':marathon,'Roll Call':count,'Lava Tile Isle':lavaTiles,'Totem Pole Pound':totems,'Dizzy Dancing':dizzy,'Tile Driver':tiles,'Snowball Summit':snow,'Ice Rink Risk':ice,'Storm Chasers':storm,'Tick Tock Hop':clockHop
};
export const notes={
 'Mushroom Mix-Up':'깃발·발판·내려찍기·생존 규칙을 유지했습니다. 발판 배치와 라운드 속도는 새로 제작했으며 원작 Z 내려찍기는 C 입력입니다.',
 'Hot Rope Jump':'1편은 전원 20회 성공 또는 첫 실수에서 끝나고, 후속 수록판은 탈락 생존전입니다. 버튼을 놓으면 상승을 일찍 멈춰 점프 높이를 조절할 수 있습니다.',
 'Bumper Balls':'공의 가속·충돌·낙하를 계산합니다. 2편·슈퍼스타즈의 얼음·바위·일반 코스는 새 지형으로 재구성했습니다. 톱100은 더 작은 일반 코스입니다. 제한 시간 다수 생존은 무승부입니다.',
 'Bombs Away':'착탄 위치를 그림자로 예고하며 충격과 직접 피격 밀림을 계산합니다. 2편은 마지막 큰 미사일이 추가됩니다. 섬의 기울기 연출은 생략했습니다.',
 'Shy Guy Says':'A 흰 깃발, B 빨간 깃발입니다. 양쪽 깃발 속임수와 점점 짧아지는 응답 시간을 적용했습니다.',
 'Tipsy Tourney':'플레이어 위치로 판의 기울기를 정하고 조개의 가속도를 계산합니다. 그림은 5×5 새 타일로 제작했습니다.',
 'Buried Treasure':'땅·단단한 돌·숨은 화살표와 보물 찾기를 재현했습니다. A를 누르고 방향을 움직여 굴착합니다. 지형은 새로 생성합니다.',
 'Balloon Burst':'A 내리기, B 올리기로 펌프를 왕복합니다. 원작 수록 형식에 따라 개인전 또는 2인 팀전으로 실행합니다. 필요한 펌프량은 새로 조정했습니다.',
 'Slot Car Derby':'방향 입력의 크기로 가속하고 놓으면 감속합니다. 4바퀴·코너 스핀·한 바퀴 추월 탈락 규칙을 사용하며 코스는 새 타원형입니다.',
 'Shell Shocked':'직사포 A, 곡사포 B, 조준 고정 C입니다. 두 번 맞으면 탈락하며 중앙 파이프가 있는 새 경기장을 사용합니다.',
 'Mecha-Marathon':'2편·슈퍼스타즈 10초/톱100 7초 동안 A+B 동시 반복 후 실제 입력 횟수로 비행 거리를 정합니다. 톱100 40m/슈퍼스타즈 70m 상한을 적용하며 거리 환산과 비행 애니메이션은 새로 조정했습니다.',
 'Roll Call':'2편·톱100은 폭탄, 슈퍼스타즈는 폭탄·유령·새 세기 중 하나를 실행합니다. 2편은 정확한 답만, 재수록판은 가장 가까운 답도 승리합니다.',
 'Lava Tile Isle':'움직이는 블록·격투·낙하와 시간 초과 무승부 규칙입니다. 블록 배치·이동 순서는 새로 제작했습니다.',
 'Totem Pole Pound':'A 점프 뒤 C로 내려찍습니다. 내려찍기 전 도달한 높이가 토템 침하량을 결정합니다.',
 'Dizzy Dancing':'2편은 중앙 음표 하나를 선취하고, 톱100·슈퍼스타즈는 30초 동안 모은 음표 수로 승부합니다. 방향 변환과 음표 배치는 새로 제작했습니다.',
 'Tile Driver':'A 점프, C 내려찍기로 3×3 그림 조각을 순환합니다. 원작 캐릭터 그림 대신 색·번호로 조각을 구분합니다.',
 'Snowball Summit':'B 반복으로 눈덩이를 만들고 방향으로 굴려 키우며 A로 발사합니다. 눈덩이 충돌과 섬 밖 밀림을 계산합니다. MP3는 시간 초과 무승부, 톱100·슈퍼스타즈는 남은 선수 공동승리입니다.',
 'Ice Rink Risk':'10초마다 추가되는 세 가시 껍질·미끄러운 이동·점프 회피를 재현한 새 링크입니다.',
 'Storm Chasers':'움직이는 비구름 아래에 머문 시간으로 점수를 정합니다. 두더지 장애물과 플레이어 간 충돌이 있습니다.',
 'Tick Tock Hop':'두 플레이어가 서로 다른 반지름에서 같은 분침을 넘습니다. 원작처럼 99회는 무승부이며 회전 속도·방향 배열은 새로 제작했습니다.'
};

export const supportedTitles={
'Mushroom Mix-Up':['mp1'],'Hot Rope Jump':['mp1','mp2'],'Bumper Balls':['mp1','mp2','top-100','superstars'],'Bombs Away':['mp1','mp2'],'Shy Guy Says':['mp1','mp2'],'Tipsy Tourney':['mp1','mp2','superstars'],'Buried Treasure':['mp1'],'Balloon Burst':['mp1','mp2'],'Slot Car Derby':['mp1','mp2'],
'Shell Shocked':['mp2'],'Mecha-Marathon':['mp2','top-100','superstars'],'Roll Call':['mp2','top-100','superstars'],'Lava Tile Isle':['mp2'],'Totem Pole Pound':['mp2'],'Dizzy Dancing':['mp2','top-100','superstars'],'Tile Driver':['mp2'],'Snowball Summit':['mp3','top-100','superstars'],'Ice Rink Risk':['mp3'],'Storm Chasers':['mp3'],'Tick Tock Hop':['mp3']
};
