import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,cream='#f6e6bd',colors=['#e993b1','#88b9d5','#e4c274','#97bf9c','#b6a0cd','#bdc8c7'];
const pulse=(t,f=5,o=0)=>(t*f+o)%1<.4,wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const label=(c,id,text,x=0,y=4,z=0,sx=6)=>c.draw(id,'text',{x,y,z,sx,sy:.8,text});
const disc=(c,id,x,z,r,color,y=.01)=>c.draw(id,'cylinder',{x,y,z,sx:r*2,sy:.04,sz:r*2,color});
const live=c=>c.players.filter(p=>p.alive),trio=c=>c.players.slice(1).filter(p=>p.alive);
function finish(c,list,reason){if(list.length){const earliest=Math.min(...list.map(x=>x.t));c.complete(list.filter(x=>Math.abs(x.t-earliest)<1e-7).flatMap(x=>x.ids),reason);}}
function rope(c,id,a,b,color,width=.06){const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,length=Math.hypot(dx,dy,dz);c.draw(id,'cylinder',{x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:(a.z+b.z)/2,sx:width,sy:length,sz:width,rx:Math.atan2(dz,Math.hypot(dx,dy)),rz:-Math.atan2(dx,dy),color});}
function fishing(c){
 c.limit=60;c.view={size:23,eye:[0,25,19],target:[0,0,0]};const solo=c.players[0];solo.x=0;solo.z=-8;let angle=0,range=9,hand=null,serial=0;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*4;p.z=2;p.heading=c.rand(0,TAU);p.goal={x:p.x,z:p.z};p.react=0;p.lag=c.rand(.2,.5);});const target=()=>({x:Math.sin(angle)*range,z:-8+Math.cos(angle)*range});
 return{update(dt){c.hint('1P 좌우 조준·아래/위로 거리 조절·A 던지기 / 물고기: 방향 지정+A 앞으로 수영');const fish=trio(c).sort((a,b)=>dist(a,target())-dist(b,target()))[0],want=fish?Math.atan2(fish.x,fish.z+8):0,wantR=fish?Math.hypot(fish.x,fish.z+8):8,q0=c.input(solo,()=>({x:clamp((want-angle)*3,-1,1),z:clamp((wantR-range)*1.5,-1,1),a:!hand&&!!fish&&dist(fish,target())<1.1}));angle=clamp(angle+q0.x*.95*dt,-.95,.95);range=clamp(range+q0.z*4*dt,3,14);if(q0.ap&&!hand){const p=target();hand={id:serial++,x:0,z:-8,y:1,tx:p.x,tz:p.z,origin:p,age:0,phase:'out',catch:null};}for(const p of trio(c)){p.react-=dt;if(p.react<=0){p.react=p.lag;const danger=hand?.phase==='out'&&dist(p,{x:hand.tx,z:hand.tz})<2.5;if(danger){const v=toward({x:hand.tx,z:hand.tz},p.x,p.z);p.goal={x:clamp(p.x+v.x*3,-7,7),z:clamp(p.z+v.z*3,-4.5,5.2)};}else if(dist(p,p.goal)<.7)p.goal={x:c.rand(-7,7),z:c.rand(-4.5,5.2)};}const q=c.input(p,()=>({...toward(p,p.goal.x,p.goal.z),a:true}));if(Math.hypot(q.x,q.z)>.2)p.heading=Math.atan2(q.x,q.z);if(q.a){p.x+=Math.sin(p.heading)*3.4*dt;p.z+=Math.cos(p.heading)*3.4*dt;}p.x=clamp(p.x,-7.5,7.5);p.z=clamp(p.z,-5,5.5);p.y=-.2;p.rotation=Math.PI/2-p.heading;p.pose='float';}if(hand){hand.age+=dt;if(hand.phase==='out'){hand.tx=clamp(hand.tx+q0.x*1.3*dt,hand.origin.x-1,hand.origin.x+1);hand.tz=clamp(hand.tz+q0.z*1.3*dt,hand.origin.z-1,hand.origin.z+1);const k=Math.min(1,hand.age/.65);hand.x=hand.tx*k;hand.z=-8+(hand.tz+8)*k;hand.y=1+Math.sin(k*Math.PI)*3.5;if(k===1){const hit=trio(c).filter(p=>dist(p,{x:hand.tx,z:hand.tz})<1).sort((a,b)=>dist(a,hand)-dist(b,hand))[0];if(hit){hand.catch=hit.i;c.eliminate(hit);}hand.phase='back';hand.age=0;hand.y=0;}}else{const k=Math.min(1,hand.age/.7);hand.x=hand.tx*(1-k);hand.z=hand.tz+(-8-hand.tz)*k;hand.y=k;if(k===1)hand=null;}}if(!trio(c).length)c.complete([0],'물고기 세 마리를 모두 낚았습니다');},render(){c.arena({width:19,depth:17,color:'#9fbf97'});c.draw('pool','box',{x:0,y:-.1,z:0,sx:17,sy:.15,sz:13,color:'#83bdcf'});const t=target();c.draw('aim','ring',{x:t.x,y:.03,z:t.z,sx:1.8,sy:1.8,sz:1,rx:-Math.PI/2,color:solo.color});if(hand){rope(c,'line',{x:0,y:1.7,z:-8},hand,cream);c.draw('glove','sphere',{x:hand.x,y:hand.y,z:hand.z,sx:1.1,sy:.6,sz:1.1,color:cream});}},timeout(){c.complete(trio(c).length?[1,2,3]:[0],'한 마리라도 남으면 물고기 팀 전체 승리');}};
}
function relay(c){
 c.limit=120;c.view={size:23,eye:[0,16,25],target:[0,0,0]};const length=120,obstacles=Array.from({length:14},(_,i)=>({d:9+i*7.8,z:c.rand(-2.1,2.1),kind:i%2}));let soloD=0,teamD=0,speed=0,stun=0,lastOar=-1,bugStep=0,leg=0;c.players.forEach((p,i)=>{p.x=-7;p.z=i===0?-3:3;p.phase=c.rand(0,1);p.rate=c.rand(4.5,6);});
 return{update(dt){const oldS=soloD,oldT=teamD,next=obstacles.find(o=>o.d>soloD-1),p0=c.players[0],goal=next?next.z>0?-1.9:1.9:0,q0=c.input(p0,()=>({x:1,z:clamp((goal-(p0.z+3))*2,-1,1)}));p0.z=clamp(p0.z+q0.z*3*dt,-5.4,-.6);stun=Math.max(0,stun-dt);soloD+=(stun?1.4:4.1+q0.x*1.3)*dt;for(const o of obstacles)if(!o.hit&&oldS<o.d&&soloD>=o.d&&Math.abs((p0.z+3)-o.z)<.7){o.hit=true;stun=.75;}leg=Math.min(2,Math.floor(teamD/40));c.hint(`1P 위아래로 회피·오른쪽 가속 / 팀 ${leg+1}구간: ${['2P A↔B 노 젓기','3P ↑A→↓A→↑B→↓B','4P A 연타'][leg]}`);for(let i=1;i<4;i++){const p=c.players[i],active=i===leg+1,beat=Math.floor(c.time*p.rate+p.phase),press=pulse(c.time,p.rate,p.phase),button=leg===0?beat%2:leg===1?Math.floor(bugStep/2):0,q=c.input(p,()=>({z:active&&leg===1?(bugStep%2?1:-1):0,a:active&&button===0&&press,b:active&&button===1&&press}));if(!active)continue;if(leg===0){const side=q.ap?0:q.bp?1:-1;if(side>=0&&side!==lastOar){lastOar=side;speed=Math.min(8,speed+1.35);}}else if(leg===1){const key=q.ap?0:q.bp?1:-1;if(key>=0){const expected=Math.floor(bugStep/2),vertical=bugStep%2?1:-1;if(key===expected&&Math.sign(q.z)===vertical){bugStep=(bugStep+1)%4;speed=Math.min(8,speed+1.5);}else speed*=.5;}}else if(q.ap)speed=Math.min(9,speed+1.25);}speed=Math.max(0,speed-2.7*dt);teamD+=speed*dt;if(Math.floor(oldT/40)!==Math.floor(teamD/40)){speed=0;lastOar=-1;bugStep=0;}p0.x=-7+Math.min(1,soloD/length)*14;p0.y=2;c.players.slice(1).forEach((p,i)=>{p.x=-7+clamp((i===leg?teamD:i<leg?(i+1)*40:i*40)/length,0,1)*14;p.z=3;p.y=.3;p.visible=i===leg;});finish(c,[...(soloD>=length?[{ids:[0],t:(length-oldS)/(soloD-oldS)}]:[]),...(teamD>=length?[{ids:[1,2,3],t:(length-oldT)/(teamD-oldT)}]:[])],'경주 결승선에 먼저 도착한 쪽이 승리');},render(){c.arena({width:20,depth:14,color:'#91c2cb'});c.draw('glider','cone',{x:c.players[0].x,y:3,z:c.players[0].z,sx:2.4,sy:.3,sz:1.5,color:c.players[0].color});for(const o of obstacles){const x=c.players[0].x+(o.d-soloD)*.6;if(Math.abs(x)<10)c.draw('enemy'+o.d,o.kind?'cone':'sphere',{x,y:2,z:-3+o.z,sx:1,sy:1,sz:.8,color:'#879b95'});}c.players.slice(1).forEach((p,i)=>{if(i===leg)c.draw('vehicle'+i,i===1?'sphere':'box',{x:p.x,y:.15,z:p.z,sx:1.8,sy:.6,sz:1.2,color:p.color});});for(let i=1;i<3;i++)c.draw('gate'+i,'box',{x:-7+i*14/3,y:.5,z:3,sx:.25,sy:leg>=i?.2:1.5,sz:2.4,color:'#afb5a8'});label(c,'progress',`개인 ${Math.floor(soloD)} / 팀 ${Math.floor(teamD)}`,0,5,0,9);},timeout(){c.complete([],'결승점에 도착한 쪽이 없습니다');}};
}
function pull(c){
 c.limit=60;c.view={size:24,eye:[0,22,20],target:[0,0,0]};const sides=[{d:0,need:0,cool:0,stun:0},{d:0,need:0,cool:0,stun:0}],snow=[];let next=2,id=0;const length=70;c.players.forEach((p,i)=>{p.x=i===0?-5:5;p.z=i===0?4:3+(i-2)*1.1;p.lag=c.rand(.18,.3);p.phase=c.rand(0,1);});sides.forEach(s=>s.need=c.int(0,2));
 return{update(dt){c.hint('1P 표시된 A/B/C 입력 / 팀 2P=C·3P=B·4P=A 담당 · 틀린 버튼은 잠시 정지');next-=dt;if(next<=0){next=c.rand(2,3.3);snow.push({id:id++,side:c.int(0,1),d:c.rand(8,60),age:0});}snow.forEach(b=>b.age+=dt);for(const s of sides){s.cool=Math.max(0,s.cool-dt);s.stun=Math.max(0,s.stun-dt);}const before=sides.map(s=>s.d),inputs=c.players.map(p=>{const side=p.i===0?0:1,s=sides[side],assigned=p.i===0?s.need:3-p.i;return c.input(p,()=>({[['a','b','c'][assigned]]:s.need===assigned&&s.cool===0&&s.stun===0&&pulse(c.time,3.4+p.phase,p.phase)}));});for(let side=0;side<2;side++){const s=sides[side];if(s.cool||s.stun)continue;const relevant=side===0?[inputs[0]]:inputs.slice(1),pressed=relevant.flatMap((q,j)=>['ap','bp','cp'].filter(k=>q[k]).map(k=>({key:['ap','bp','cp'].indexOf(k),player:side===0?0:j+1})));if(pressed.length){const correct=pressed.length===1&&pressed[0].key===s.need&&(side===0||pressed[0].player===3-s.need);if(correct){s.d+=1.5;s.need=c.int(0,2);s.cool=.12;}else{s.stun=.55;}}for(const b of snow)if(b.side===side&&!b.hit&&b.age>.8&&Math.abs(s.d-b.d)<1.6){b.hit=true;s.stun=.8;}c.players.filter(p=>(p.i===0?0:1)===side).forEach(p=>{p.z=5-s.d/length*11+(p.i>0?(p.i-2)*.7:0);p.score=Math.floor(s.d);});}finish(c,sides.flatMap((s,i)=>s.d>=length?[{ids:i===0?[0]:[1,2,3],t:(length-before[i])/(s.d-before[i])}]:[]),'썰매가 결승선에 먼저 도착했습니다');for(let i=snow.length-1;i>=0;i--)if(snow[i].age>4||snow[i].hit)snow.splice(i,1);},render(){c.arena({width:20,depth:16,color:'#cadfe0'});sides.forEach((s,i)=>{const x=i?5:-5;c.draw('sled'+i,'box',{x,y:.05,z:5-s.d/length*11,sx:i?3:2,sy:.3,sz:2.6,color:i?'#94b7bc':'#ceac9a'});for(let j=0;j<3;j++){c.draw('thwomp'+i+'_'+j,'box',{x:x+(j-1)*1.5,y:.6,z:3.1-s.d/length*11,sx:1.15,sy:1.2,sz:1,color:s.need===j?'#e5c77d':'#9fa8a8'});label(c,'button'+i+'_'+j,['A','B','C'][j],x+(j-1)*1.5,2.2,3.1-s.d/length*11,1);}if(s.stun)label(c,'stun'+i,'잠시 정지',x,3,5-s.d/length*11,3);});snow.forEach(b=>c.draw('snow'+b.id,'sphere',{x:b.side?5:-5,y:b.age<.8?3*(1-b.age/.8):.4,z:5-b.d/length*11,sx:1,sy:1,sz:1,color:cream}));},timeout(){c.complete([],'60초 안에 어느 썰매도 완주하지 못했습니다');}};
}
function coaster(c){
 c.limit=180;c.view={size:24,eye:[0,22,22],target:[0,0,0]};const length=140,gates=Array.from({length:14},(_,i)=>({d:12+i*8.5,blocked:c.shuffle([-1,0,1]).slice(0,c.rand()<.45?2:1),coin:c.int(-1,1)})),teams=[{d:0,speed:0,x:0,seen:new Set()},{d:0,speed:0,x:0,seen:new Set()}];c.players.forEach((p,i)=>{p.side=0;p.reaction=c.rand(.18,.4);p.goal=0;p.next=0;p.error=c.rand(.08,.17);p.plan=null;});
 return{update(dt){c.hint('두 사람 함께 좌우 조종 · 한 칸·두 칸 표지판을 피하고 코인을 모으며 결승선까지');const done=[];for(let i=0;i<2;i++){const t=teams[i],next=gates.find(g=>g.d>t.d),inputs=[];for(const p of c.players.slice(i*2,i*2+2)){if(p.plan!==next&&c.time>=p.next){p.plan=next;p.next=c.time+p.reaction;const safe=next?[-1,0,1].filter(l=>!next.blocked.includes(l)):[0];p.goal=c.rand()<p.error?c.int(-1,1):safe.sort((a,b)=>Math.abs(a-t.x)-Math.abs(b-t.x))[0];}inputs.push(c.input(p,()=>({x:clamp((p.goal-t.x)*3,-1,1)})));}t.x=clamp(t.x+(inputs[0].x+inputs[1].x)*1.6*dt,-1,1);t.speed=Math.min(8,t.speed+2.2*dt);const old=t.d;t.d+=t.speed*dt;for(let j=0;j<gates.length;j++){const g=gates[j];if(old<g.d&&t.d>=g.d&&!t.seen.has(j)){t.seen.add(j);if(g.blocked.some(l=>Math.abs(t.x-l)<.5))t.speed=1.8;if(Math.abs(t.x-g.coin)<.4)c.players.slice(i*2,i*2+2).forEach(p=>c.points(p));}}c.players.slice(i*2,i*2+2).forEach((p,j)=>{p.x=(i?5.7:-5.7)+t.x*2;p.z=3+j*1.4;p.y=.4;});if(t.d>=length)done.push({ids:[i*2,i*2+1],t:(length-old)/(t.d-old)});}finish(c,done,'표지판을 피해 코스터 결승선에 먼저 도착했습니다');},render(){c.arena({width:25,depth:22,color:'#8194b0'});teams.forEach((t,i)=>{const base=i?5.7:-5.7;for(let l=-1;l<=1;l++)c.draw('rail'+i+'_'+l,'box',{x:base+l*2,y:0,z:0,sx:.1,sy:.15,sz:22,color:cream});for(let j=0;j<gates.length;j++){const g=gates[j],z=3-(g.d-t.d)*.65;if(Math.abs(z)>11)continue;for(const l of g.blocked)c.draw('sign'+i+'_'+j+'_'+l,'box',{x:base+l*2,y:1,z,sx:1.65,sy:2,sz:.3,color:g.blocked.length===2?'#d0a283':'#b2a1bf'});if(!t.seen.has(j))c.draw('coin'+i+'_'+j,'cylinder',{x:base+g.coin*2,y:.6,z:z-1,sx:.55,sy:.1,sz:.55,rx:Math.PI/2,color:'#e2c16d'});}c.draw('car'+i,'box',{x:base+t.x*2,y:.2,z:3.7,sx:1.6,sy:.5,sz:3.2,color:c.players[i*2].color});label(c,'distance'+i,Math.ceil(length-t.d)+' m',base,4,-7,3);});},timeout(){c.complete([],'결승선에 도착한 팀이 없습니다');}};
}
function locked(c){
 c.limit=36;let room=0,age=0,keys=[],doors=[];const marks=['●','▲','■'];c.players.forEach(p=>{p.key=null;p.stun=0;p.cool=0;p.passed=false;p.phase=c.rand(0,1);});
 function next(){room++;age=0;const ps=live(c),n=ps.length-1,order=c.shuffle([0,1,2]).slice(0,n);doors=order.map((mark,i)=>({mark,x:(i-(n-1)/2)*4,z:-5,used:false}));keys=c.shuffle(order).map((mark,i)=>({mark,x:(i-(n-1)/2)*3,z:c.rand(-1.5,1.5),owner:null,wait:0}));ps.forEach((p,i)=>{p.x=(i-(ps.length-1)/2)*3;p.z=4;p.passed=false;p.visible=true;p.key=null;});}next();
 function drop(p){if(p.key==null)return;const k=keys[p.key];k.owner=null;k.x=p.x;k.z=p.z+.5;k.wait=.35;p.key=null;}
 function endRoom(){for(const p of live(c))if(!p.passed)c.eliminate(p);const ps=live(c);if(ps.length<=1){c.complete(ps.map(p=>p.i),ps.length?'마지막 문까지 통과했습니다':'아무도 문을 통과하지 못했습니다');return;}if(room>=3){c.complete(ps.map(p=>p.i),'마지막 방을 통과했습니다');return;}next();}
 return{update(dt){age+=dt;keys.forEach(k=>k.wait=Math.max(0,k.wait-dt));c.hint(`${room}/3 방 · ${Math.max(0,Math.ceil(10-age))}초 · 방향 이동·A 열쇠 집기/놓기·B 공격 · 같은 무늬의 문으로`);const inputs=c.players.map(p=>{p.stun=Math.max(0,p.stun-dt);p.cool=Math.max(0,p.cool-dt);let goal=p;if(p.key!=null)goal=doors.find(d=>d.mark===keys[p.key].mark&&!d.used)||p;else goal=keys.filter(k=>k.owner==null).sort((a,b)=>dist(p,a)-dist(p,b))[0]||live(c).find(o=>o.key!=null)||p;return c.input(p,()=>({...toward(p,goal.x,goal.z),a:!p.passed&&p.key==null&&keys.some(k=>k.owner==null&&!k.wait&&dist(k,p)<.85)&&pulse(c.time,4,p.phase),b:!p.passed&&live(c).some(o=>o!==p&&o.key!=null&&dist(p,o)<1.3)&&pulse(c.time,2,p.phase)}));});for(const p of live(c))if(!p.passed&&!p.stun)c.move(p,inputs[p.i],4.7,false);for(const p of live(c)){p.x=clamp(p.x,-7.5,7.5);p.z=clamp(p.z,-5.5,5);}const hits=new Set();for(const p of live(c))if(!p.passed&&!p.stun&&inputs[p.i].bp&&p.cool===0){p.cool=.4;for(const o of live(c))if(o!==p&&!o.passed&&dist(p,o)<1.4)hits.add(o.i);}for(const i of hits){const p=c.players[i];drop(p);p.stun=.55;}for(const p of c.shuffle(live(c))){if(p.passed||p.stun)continue;if(inputs[p.i].ap){if(p.key!=null)drop(p);else{const k=keys.filter(k=>k.owner==null&&!k.wait&&dist(k,p)<.9).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(k){p.key=keys.indexOf(k);k.owner=p.i;}}}if(p.key!=null){const k=keys[p.key],d=doors.find(d=>!d.used&&d.mark===k.mark&&dist(d,p)<.9);if(d){d.used=true;k.owner=-1;p.key=null;p.passed=true;p.visible=false;c.points(p);}}}if(age>=10||doors.every(d=>d.used))endRoom();},render(){c.arena({width:18,depth:14,color:'#bbb9a5'});doors.forEach((d,i)=>{c.draw('door'+i,'box',{x:d.x,y:1.6,z:d.z,sx:2.4,sy:3.2,sz:.35,color:d.used?'#859c91':colors[d.mark]});label(c,'mark'+i,marks[d.mark],d.x,2.2,d.z+.25,1.3);});keys.forEach((k,i)=>{if(k.owner===-1)return;const p=k.owner!=null?c.players[k.owner]:k;c.draw('key'+i,'ring',{x:p.x,y:k.owner!=null?1.7:.3,z:p.z,sx:.6,sy:.6,sz:.6,color:colors[k.mark]});label(c,'keyMark'+i,marks[k.mark],p.x,k.owner!=null?2.5:.9,p.z,.8);});},timeout(){endRoom();if(!c.ended)c.complete([],'문을 통과하지 못했습니다');}};
}
function vines(c){
 c.limit=180;c.activePlayers=[0,1];c.view={size:25,eye:[0,8,30],target:[0,4,0]};c.players.slice(2).forEach(p=>{p.visible=false;p.alive=false;});const count=12,spacing=3.2,length=3.3,anchor=k=>({x:k*spacing,y:7.8+(k%3)*.25}),angle=(k,t)=>Math.sin(t*1.3+k*.72)*.75,loc=(k,t)=>{const a=anchor(k),theta=angle(k,t);return{x:a.x+Math.sin(theta)*length,y:a.y-Math.cos(theta)*length};};let camera=0;c.players.slice(0,2).forEach((p,i)=>{p.vine=0;p.previousVine=0;p.air=0;p.stun=0;p.vx=0;p.vy=0;p.worldX=loc(0,0).x;p.y=loc(0,0).y;p.z=(i-.5)*5;p.delay=c.rand(.04,.16);});
 return{update(dt){c.hint('A를 눌러 덩굴 놓기 · 앞으로 휘둘러지는 순간 뛰면 다음 덩굴을 잡습니다 · 1P 대 2P');const done=[];for(const p of c.players.slice(0,2)){p.stun=Math.max(0,p.stun-dt);const hanging=p.vine!=null,a=hanging?angle(p.vine,c.time):0,derivative=hanging?Math.cos(c.time*1.3+p.vine*.72):0,q=c.input(p,()=>({a:hanging&&!p.stun&&a>.15+p.delay&&a<.5&&derivative>0}));if(hanging){const now=loc(p.vine,c.time),before=loc(p.vine,c.time-.01);p.worldX=now.x;p.y=now.y;if(q.ap&&!p.stun){p.vx=(now.x-before.x)/.01+2.2;p.vy=(now.y-before.y)/.01+3.4;p.previousVine=p.vine;p.vine=null;p.air=0;}}else{p.air+=dt;p.vy-=9*dt;const old=p.worldX;p.worldX+=p.vx*dt;p.y+=p.vy*dt;if(p.air>.12){const catches=Array.from({length:count},(_,i)=>i).filter(i=>i>p.previousVine&&Math.hypot(p.worldX-loc(i,c.time).x,p.y-loc(i,c.time).y)<.75);if(catches.length){p.vine=Math.max(...catches);p.previousVine=p.vine;p.score=p.vine;}}const goal=spacing*(count-1)+3;if(p.worldX>=goal&&p.y>2.7)done.push({ids:[p.i],t:(goal-old)/Math.max(.0001,p.worldX-old)});if(p.y<.5){p.vine=p.previousVine;p.stun=.8;p.delay=c.rand(.02,.25);const l=loc(p.vine,c.time);p.worldX=l.x;p.y=l.y;}}}camera=Math.max(0,Math.max(...c.players.slice(0,2).map(p=>p.worldX))-6);c.players.slice(0,2).forEach(p=>p.x=p.worldX-camera);finish(c,done,'덩굴 숲 끝에 먼저 도착했습니다');},render(){c.draw('forest','box',{x:0,y:-.4,z:0,sx:26,sy:.6,sz:13,color:'#9db58c'});for(let i=0;i<count;i++){const a=anchor(i),b=loc(i,c.time);if(a.x-camera<-14||a.x-camera>15)continue;for(const z of [-2.5,2.5]){rope(c,'vine'+i+'_'+z,{x:a.x-camera,y:a.y,z},{x:b.x-camera,y:b.y,z},'#9a9c73',.12);c.draw('anchor'+i+'_'+z,'sphere',{x:a.x-camera,y:a.y,z,sx:.5,sy:.5,sz:.5,color:'#859c72'});}}for(const p of c.players.slice(0,2))if(p.stun)label(c,'miss'+p.i,'다시 잡기',p.x,p.y+2,p.z,3);const goal=spacing*(count-1)+3-camera;if(goal<15)c.draw('goal','box',{x:goal,y:2.7,z:0,sx:3,sy:.6,sz:10,color:cream});},timeout(){c.complete([],'3분 안에 덩굴 숲을 통과하지 못했습니다');}};
}
function poundDown(c){
 c.limit=180;c.view={size:29,eye:[0,0,31],target:[0,-3,0]};const layout=Array.from({length:3},(_,s)=>c.shuffle([[0,1,2],[2,3,4],[5,6,7]][s]).map((count,col)=>{const reserved=s===2?(col===1?[7,8]:[6,7,8]):[],rocks=new Set([...reserved,...c.shuffle(Array.from({length:9},(_,i)=>i).filter(i=>!reserved.includes(i))).slice(0,count-reserved.length)]);return Array.from({length:9},(_,i)=>rocks.has(i)?3:1);}));c.players.forEach((p,i)=>{p.section=0;p.row=0;p.column=1;p.locked=false;p.jumpY=0;p.pound=false;p.power=1;p.grid=layout.map(a=>a.map(b=>[...b]));p.keyWait=0;p.botWait=c.rand(.08,.3);p.phase=c.rand(0,.18);p.bestBias=c.rand()<.15?c.int(0,2):null;p.x=(i-1.5)*6;p.z=0;});
 return{update(dt){c.hint('좌우로 세 통로 중 선택 / A 점프 → 공중 A 내려찍기 · 흙은 한 번, 바위는 세 번 · 꼭대기 타이밍은 흙 여러 칸');const done=[];for(const p of c.players){p.keyWait=Math.max(0,p.keyWait-dt);p.botWait=Math.max(0,p.botWait-dt);const choices=p.section<3?p.grid[p.section].map(a=>a.reduce((n,h)=>n+(h===3?3:1),0)):[],best=p.bestBias??(choices.length?choices.indexOf(Math.min(...choices)):1),q=c.input(p,()=>({x:!p.locked?Math.sign(best-p.column):0,a:(p.jumpY===0&&!p.botWait&&(!p.keyWait||p.locked)&&(p.locked||p.column===best))||(!p.pound&&p.jumpY>1.15+p.phase&&p.vy<2)}));if(!p.locked&&p.jumpY===0&&Math.abs(q.x)>.5&&p.keyWait===0){p.column=clamp(p.column+Math.sign(q.x),0,2);p.keyWait=.18;}const old=p.jumpY,oldVy=p.vy||0;p.y=p.jumpY;c.jump(p,q,7.6);if(q.ap&&old>0&&!p.pound){p.pound=true;p.power=p.y>=1.15?3:1;p.vy=-14;p.locked=true;}p.jumpY=p.y;if(p.pound&&old>0&&p.jumpY===0){p.pound=false;p.botWait=c.rand(.06,.22);let power=p.power;while(power>0&&p.section<3){const blocks=p.grid[p.section][p.column],hp=blocks[p.row];if(layout[p.section][p.column][p.row]===3){blocks[p.row]--;power=0;if(blocks[p.row]<=0)p.row++;}else{blocks[p.row]=0;p.row++;power--;}if(p.row>=9){p.section++;p.row=0;p.locked=false;power=0;}}p.score=p.section*9+p.row;if(p.section===3)done.push({ids:[p.i],t:old/Math.max(.0001,old-(old+(oldVy-18*dt)*dt))});}p.x=(p.i-1.5)*6+(p.column-1)*1.6;p.y=p.jumpY;}finish(c,done,'세 지층을 뚫고 아래 물에 먼저 도착했습니다');},render(){c.draw('back','box',{x:0,y:-4,z:-1.5,sx:26,sy:12,sz:.2,color:'#967d6a'});for(const p of c.players){for(let section=p.section;section<Math.min(3,p.section+2);section++)for(let col=0;col<3;col++)for(let row=0;row<9;row++){const hp=p.grid[section][col][row];if(hp<=0)continue;const depth=section*9+row-p.score;if(depth<0)continue;const rock=layout[section][col][row]===3;c.draw('block'+p.i+'_'+section+'_'+col+'_'+row,'box',{x:(p.i-1.5)*6+(col-1)*1.6,y:-.3-depth*.62,z:0,sx:1.5,sy:.58,sz:1.4,color:rock?['','#d5c7b5','#b3aca1','#96978e'][hp]:['#d6b08b','#bd997b','#a78774'][section]});}label(c,'depth'+p.i,p.score+'/27',(p.i-1.5)*6,3,0,3);}},timeout(){c.complete([],'바닥까지 도착한 선수가 없습니다');}};
}
function chimps(c){
 c.limit=30;c.bounds={x:8,z:5};const nests=[{x:-7,z:-4},{x:7,z:-4},{x:-7,z:4},{x:7,z:4}],babies=[];let id=0,spawn=.6,shout=-1,shoutTime=0,nextShout=4,gold=false;const create=(kind)=>babies.push({id:id++,kind,x:c.rand(-5,5),z:c.rand(-3,3),angle:c.rand(0,TAU),turn:c.rand(.4,1),owner:null,wait:0});for(let i=0;i<12;i++)create(i%4);c.players.forEach((p,i)=>{p.x=(i-1.5)*2;p.z=0;p.carry=null;p.phase=c.rand(0,1);});
 return{update(dt){spawn-=dt;nextShout-=dt;shoutTime=Math.max(0,shoutTime-dt);if(nextShout<=0){nextShout=c.rand(3.5,5);shout=c.int(0,3);shoutTime=1.4;c.sound?.(240+shout*50,.2);}if(!gold&&c.time>=15){gold=true;create(4);}if(spawn<=0&&babies.filter(b=>b.owner==null).length<12){spawn=.7;create(c.int(0,3));}for(const b of babies)if(b.owner==null){b.wait=Math.max(0,b.wait-dt);b.turn-=dt;if(b.turn<=0){b.turn=c.rand(.4,1.2);const near=c.players.filter(p=>p.carry==null).sort((a,d)=>dist(a,b)-dist(d,b))[0];b.angle=near&&dist(near,b)<2.5?Math.atan2(b.z-near.z,b.x-near.x):b.angle+c.rand(-1.1,1.1);}if(!(b.kind===shout&&shoutTime>0)){const v=b.kind===4?3.9:2;b.x+=Math.cos(b.angle)*v*dt;b.z+=Math.sin(b.angle)*v*dt;if(Math.abs(b.x)>7.8||Math.abs(b.z)>4.8){b.x=clamp(b.x,-7.8,7.8);b.z=clamp(b.z,-4.8,4.8);b.angle+=Math.PI;}}}c.hint('방향 이동 / A 잡기·돌려주기 · 같은 색 어른에게 1점, 황금은 어디든 3점 · 외치면 같은 색이 멈춥니다');const inputs=c.players.map(p=>{const target=p.carry!=null?(babies.find(b=>b.id===p.carry)?.kind===4?nests.reduce((a,b)=>dist(p,a)<dist(p,b)?a:b):nests[babies.find(b=>b.id===p.carry).kind]):babies.filter(b=>b.owner==null&&!b.wait).sort((a,b)=>dist(p,a)/(a.kind===4?2:1)-dist(p,b)/(b.kind===4?2:1))[0]||p;return c.input(p,()=>({...toward(p,target.x,target.z),a:dist(p,target)<1&&pulse(c.time,4,p.phase)}));});for(const p of c.players)c.move(p,inputs[p.i],4.7);for(const p of c.shuffle(c.players))if(inputs[p.i].ap){if(p.carry!=null){const b=babies.find(b=>b.id===p.carry),nest=nests.findIndex(n=>dist(p,n)<1.25);if(nest>=0&&(b.kind===4||b.kind===nest)){c.points(p,b.kind===4?3:1);b.gone=true;}else{b.owner=null;b.x=p.x;b.z=p.z;b.wait=.4;}p.carry=null;}else{const b=babies.filter(b=>!b.gone&&b.owner==null&&!b.wait&&dist(p,b)<1).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(b){b.owner=p.i;p.carry=b.id;}}}for(let i=babies.length-1;i>=0;i--)if(babies[i].gone)babies.splice(i,1);},render(){c.arena({width:19,depth:13,color:'#a8be90'});nests.forEach((n,i)=>{disc(c,'nest'+i,n.x,n.z,1.2,colors[i]);c.draw('adult'+i,'sphere',{x:n.x,y:.7,z:n.z,sx:1.3,sy:1.4,sz:1.3,color:colors[i]});if(shout===i&&shoutTime>0)label(c,'shout','!',n.x,2.8,n.z,2);});for(const b of babies){const p=b.owner==null?b:c.players[b.owner];c.draw('baby'+b.id,'sphere',{x:p.x,y:b.owner==null?.35:1.6,z:p.z,sx:.65,sy:.7,sz:.65,color:b.kind===4?'#e6c16e':colors[b.kind]});}},timeout(){const max=Math.max(...c.players.map(p=>p.score));c.complete(c.players.every(p=>p.score===max)?[]:c.players.filter(p=>p.score===max).map(p=>p.i),'같은 색 가족에게 돌려준 점수 비교');}};
}
function chomp(c){
 c.limit=180;c.view={size:29,eye:[0,27,22],target:[0,0,0]};const obs=[{x:-.9,z:2.4,w:2.7},{x:.9,z:-.8,w:2.7},{x:-.9,z:-4,w:2.7}],route=[{x:1.8,z:3.5},{x:1.8,z:1},{x:-1.8,z:1},{x:-1.8,z:-2.3},{x:1.8,z:-2.3},{x:1.8,z:-5.5},{x:0,z:-7.5}],balls=c.players.map((p,i)=>({x:(i-1.5)*6.5,z:5.5,vx:0,vz:0,wait:0,way:0}));c.players.forEach((p,i)=>{p.x=(i-1.5)*6.5+1.8;p.z=4.5;p.stun=0;p.phase=c.rand(0,1);});const blocked=(x,z)=>obs.some(o=>Math.abs(x-o.x)<o.w/2+.22&&Math.abs(z-o.z)<.55);
 return{update(dt){c.hint('방향 이동 / A 호루라기 · 큰 공은 부딪힐 때까지 직진 · 공을 장애물 너머 결승선으로 유도');const done=[];for(const p of c.players){const b=balls[p.i],base=(p.i-1.5)*6.5;while(b.way<route.length-1&&dist({x:b.x-base,z:b.z},route[b.way])<.9)b.way++;const waypoint=route[b.way],goal={x:base+waypoint.x,z:waypoint.z};p.stun=Math.max(0,p.stun-dt);b.wait=Math.max(0,b.wait-dt);const close=dist(p,b)<1.8&&Math.hypot(b.vx,b.vz)>0,moveGoal=close?{x:clamp(p.x+Math.sign(p.x-b.x||1)*2,base-2.4,base+2.4),z:p.z}:goal,q=c.input(p,()=>({...toward(p,moveGoal.x,moveGoal.z),a:!b.wait&&dist(p,goal)<.45&&Math.hypot(b.vx,b.vz)===0&&pulse(c.time,3,p.phase)}));const oldx=p.x,oldz=p.z;if(!p.stun)c.move(p,q,4.3,false);p.x=clamp(p.x,base-2.7,base+2.7);p.z=clamp(p.z,-8,6.5);if(blocked(p.x-base,p.z)){p.x=oldx;p.z=oldz;}if(q.ap&&!p.stun&&!b.wait){const v=toward(b,p.x,p.z);b.vx=v.x*5;b.vz=v.z*5;c.sound?.(720,.12);}const bx=b.x,bz=b.z;b.x+=b.vx*dt;b.z+=b.vz*dt;if(blocked(b.x-base,b.z)||Math.abs(b.x-base)>2.55||b.z>6.4){b.x=bx;b.z=bz;b.vx=b.vz=0;b.wait=.5;}if(dist(p,b)<1.05&&Math.hypot(b.vx,b.vz)>0&&!p.stun){p.stun=.8;p.x=clamp(p.x+Math.sign(p.x-b.x||1)*.7,base-2.7,base+2.7);}if(b.z<=-7)done.push({ids:[p.i],t:(bz+7)/Math.max(.0001,bz-b.z)});p.score=Math.floor((5.5-b.z)*10);}finish(c,done,'큰 공을 결승선 너머로 먼저 유도했습니다');},render(){c.arena({width:28,depth:19,color:'#bfd09d'});for(let i=0;i<4;i++){const base=(i-1.5)*6.5;obs.forEach((o,j)=>{c.draw('obstacle'+i+'_'+j,'box',{x:base+o.x,y:.55,z:o.z,sx:o.w,sy:1.1,sz:.6,color:j===1?'#b8a6bd':'#beae8b'});});c.draw('goal'+i,'box',{x:base,y:.04,z:-7,sx:5.7,sy:.08,sz:.2,color:cream});const b=balls[i];c.draw('chomp'+i,'sphere',{x:b.x,y:.65,z:b.z,sx:1.3,sy:1.3,sz:1.3,color:'#728991'});}},timeout(){c.complete([],'공을 출구까지 데려가지 못했습니다');}};
}
function popstars(c){
 c.limit=25;c.view={size:24,eye:[0,9,28],target:[0,2,0]};let round=0,age=0,reveal=false,odd=0,phase=0;const labels=['A','B','C','D','←','→'];c.players.forEach((p,i)=>{p.x=(i-1.5)*3.5;p.z=4;p.choice=null;p.axis=0;p.lag=c.rand(1.1,2.4);});function next(){round++;age=0;reveal=false;odd=c.int(0,5);phase=c.rand(0,TAU);c.players.forEach(p=>{p.choice=null;p.guess=c.rand()<.14?c.int(0,5):odd;p.lag=c.rand(1.1,2.4);});}next();
 function result(){const max=Math.max(...c.players.map(p=>p.score));c.complete(c.players.every(p=>p.score===max)?[]:c.players.filter(p=>p.score===max).map(p=>p.i),'세 번의 다른 춤 찾기 결과');}
 return{update(dt){age+=dt;c.hint(`${round}/3 · 다른 잎사귀 춤을 찾으세요 · A/B/C/D/←/→로 선택 · 5초`);for(const p of c.players){const bot=()=>{if(p.choice!=null||age<p.lag||reveal)return{};return p.guess<4?{[['a','b','c','d'][p.guess]]:true}:{x:p.guess===4?-1:1};},q=c.input(p,bot);if(!reveal&&p.choice==null){const key=q.ap?0:q.bp?1:q.cp?2:q.dp?3:q.x<-.5&&p.axis>=-.5?4:q.x>.5&&p.axis<=.5?5:-1;if(key>=0)p.choice=key;}p.axis=q.x;}if(!reveal&&(age>=5||c.players.every(p=>p.choice!=null))){reveal=true;age=0;c.players.forEach(p=>{if(p.choice===odd)c.points(p);});c.sound?.(420,.12);}else if(reveal&&age>=1.1){if(round===3)result();else next();}},render(){c.arena({width:23,depth:13,color:'#bba9c3'});for(let i=0;i<6;i++){const x=(i-2.5)*3.4,a=Math.sin(c.time*4+phase+(i===odd?1.2:0));c.draw('pipe'+i,'cylinder',{x,y:.45,z:-2,sx:1.5,sy:.9,sz:1.5,color:'#96b997'});c.draw('stem'+i,'cylinder',{x,y:1.6,z:-2,sx:.22,sy:2.3,sz:.22,color:'#8ca58b'});c.draw('flower'+i,'sphere',{x,y:2.7,z:-2,sx:1.15,sy:.8,sz:1.15,color:'#dfa0b6'});for(const side of [-1,1])c.draw('leaf'+i+'_'+side,'box',{x:x+side*.6,y:1.5,z:-2,sx:1.2,sy:.12,sz:.55,rz:side*a*.65,color:'#87ac85'});label(c,'key'+i,labels[i],x,.5,-.9,1.5);if(reveal&&i===odd)label(c,'correct','✓',x,4,-2,2);}c.players.forEach(p=>{if(reveal)label(c,'guess'+p.i,p.choice==null?'시간 초과':labels[p.choice],p.x,2.5,4,2);});},timeout:result};
}
function maze(c){
 c.limit=45;c.view={size:23,eye:[0,28,18],target:[0,0,0]};const w=7,h=5,unit=2.15,n=w*h,center=17,edges=[];for(let z=0;z<h;z++)for(let x=0;x<w;x++){const a=z*w+x;if(x<w-1)edges.push({a,b:a+1,x:(x-2.5)*unit,z:(z-2)*unit,vertical:true});if(z<h-1)edges.push({a,b:a+w,x:(x-3)*unit,z:(z-1.5)*unit,vertical:false});}let walls=[],epoch=-1;const pos=i=>({x:(i%w-3)*unit,z:(Math.floor(i/w)-2)*unit}),cell=p=>clamp(Math.round(p.z/unit)+2,0,4)*w+clamp(Math.round(p.x/unit)+3,0,6);function build(){const parent=Array.from({length:n},(_,i)=>i),root=i=>{while(parent[i]!==i)i=parent[i];return i;};const open=new Set();for(const e of c.shuffle(edges)){const a=root(e.a),b=root(e.b);if(a!==b){parent[a]=b;open.add(e);}}walls=edges.filter(e=>!open.has(e)&&c.rand()<.82);}function route(start){const queue=[start],prev=new Map([[start,null]]);for(const at of queue){if(at===center)break;for(const e of edges)if(!walls.includes(e)&&(e.a===at||e.b===at)){const b=e.a===at?e.b:e.a;if(!prev.has(b)){prev.set(b,at);queue.push(b);}}}let next=center;while(prev.get(next)!=null&&prev.get(next)!==start)next=prev.get(next);return pos(next);}
 c.players.forEach((p,i)=>{Object.assign(p,pos([0,6,28,34][i]));p.stun=0;p.react=0;p.goal={x:0,z:0};p.lag=c.rand(.12,.3);p.trail=[];});
 return{update(dt){const e=Math.floor(c.time/2);if(e!==epoch){epoch=e;build();c.players.forEach(p=>p.react=0);}c.hint('방향 이동 · 2초마다 전기벽이 바뀝니다 · 가운데 별에 먼저 도착 · 접촉하면 잠시 정지');const done=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.react-=dt;if(p.react<=0){p.react=p.lag;p.goal=route(cell(p));}const q=c.input(p,()=>toward(p,p.goal.x,p.goal.z)),old={x:p.x,z:p.z},distance=Math.hypot(p.x,p.z);if(!p.stun)c.move(p,q,3.9,false);p.x=clamp(p.x,-6.8,6.8);p.z=clamp(p.z,-4.7,4.7);for(const wall of walls){const near=wall.vertical?Math.abs(p.x-wall.x)<.26&&Math.abs(p.z-wall.z)<unit*.49:Math.abs(p.z-wall.z)<.26&&Math.abs(p.x-wall.x)<unit*.49,closer=wall.vertical?Math.abs(p.x-wall.x)<Math.abs(old.x-wall.x):Math.abs(p.z-wall.z)<Math.abs(old.z-wall.z);if(near&&closer){p.x=old.x;p.z=old.z;p.stun=.45;break;}}if(p.trail.length===0||dist(p,p.trail.at(-1))>.3){p.trail.push({x:p.x,z:p.z});if(p.trail.length>70)p.trail.shift();}const d=Math.hypot(p.x,p.z);if(d<.55)done.push({ids:[p.i],t:clamp((distance-.55)/Math.max(.0001,distance-d),0,1)});}finish(c,done,'전기 미로의 가운데 별에 먼저 도착했습니다');},render(){c.arena({width:17,depth:13,color:'#b8bcb5'});walls.forEach((v,i)=>c.draw('wall'+i,'box',{x:v.x,y:.55,z:v.z,sx:v.vertical?.15:unit,sy:1.1,sz:v.vertical?unit:.15,color:'#9da5d6',opacity:.75,glow:true}));for(let z=0;z<=h;z++)for(let x=0;x<=w;x++)c.draw('peg'+z+'_'+x,'cylinder',{x:(x-3.5)*unit,y:.6,z:(z-2.5)*unit,sx:.18,sy:1.2,sz:.18,color:'#859992'});c.players.forEach(p=>p.trail.forEach((v,i)=>disc(c,'trail'+p.i+'_'+i,v.x,v.z,.09,p.color,.02)));c.draw('star','cone',{x:0,y:.5,z:0,sx:.9,sy:1,sz:.9,color:'#e6c576',ry:c.time});},timeout(){c.complete([],'45초 안에 별에 도착한 선수가 없습니다');}};
}
function hydro(c){
 c.limit=300;c.view={size:27,eye:[0,30,22],target:[0,0,0]};const gates=[{x:-8,z:-6},{x:7,z:-7},{x:8,z:6},{x:-7,z:6},{x:-3,z:-1}],goal={x:0,z:-8},crates=[{x:0,z:-6},{x:7,z:0},{x:0,z:6},{x:-7,z:1},{x:1,z:1},{x:-3,z:-5}];c.players.forEach((p,i)=>{p.x=(i-1.5)*1.2;p.z=-8;p.heading=-Math.PI/2;p.speed=0;p.gate=0;p.stun=0;p.inv=0;p.lag=c.rand(.12,.28);p.error=c.rand(-.08,.08);});
 return{update(dt){c.hint('좌우 조타 / A 가속 / B 감속 · 1→5번 링을 순서대로 지난 뒤 결승선으로 · 상자 충돌 주의');const done=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.inv=Math.max(0,p.inv-dt);const target=gates[p.gate]||goal,desired=Math.atan2(target.x-p.x,-(target.z-p.z)),error=wrap(desired-p.heading),q=c.input(p,()=>({x:clamp((error+p.error)*2,-1,1),a:Math.abs(error)<1||p.speed<2.5,b:Math.abs(error)>1.3&&p.speed>3}));p.heading+=q.x*1.85*dt;p.speed=clamp(p.speed+(p.stun?-7:q.b?-6:q.a?3:-1.5)*dt,0,6.5);const before={x:p.x,z:p.z};p.x+=Math.sin(p.heading)*p.speed*dt;p.z-=Math.cos(p.heading)*p.speed*dt;p.x=clamp(p.x,-11.5,11.5);p.z=clamp(p.z,-9.5,9.5);if(!p.inv&&crates.some(b=>dist(p,b)<1)){p.stun=.7;p.inv=1.3;p.speed=.5;p.x=before.x;p.z=before.z;}const d=dist(p,target),oldD=dist(before,target);if(d<1.15){if(p.gate<5){p.gate++;p.score=p.gate;c.sound?.(300+p.gate*60,.08);}else done.push({ids:[p.i],t:clamp((oldD-1.15)/Math.max(.0001,oldD-d),0,1)});}p.y=.2;p.rotation=Math.PI/2-p.heading;}finish(c,done,'다섯 링을 순서대로 지나 결승선을 통과했습니다');},render(){c.arena({width:26,depth:23,color:'#8bbfce'});gates.forEach((g,i)=>{c.draw('ring'+i,'ring',{x:g.x,y:1.2,z:g.z,sx:2.4,sy:2.4,sz:1,color:colors[i],ry:Math.atan2((gates[(i+1)%5].x-g.x),(gates[(i+1)%5].z-g.z))});label(c,'number'+i,String(i+1),g.x,3,g.z,1.5);});crates.forEach((b,i)=>c.draw('crate'+i,'box',{x:b.x,y:.3,z:b.z,sx:1.4,sy:.8,sz:1.4,color:'#b6a184'}));c.draw('finish','box',{x:goal.x,y:.05,z:goal.z,sx:3,sy:.05,sz:.3,color:cream});c.players.forEach(p=>{c.draw('boat'+p.i,'cone',{x:p.x,y:.1,z:p.z,sx:1,sy:1.8,sz:.6,rx:Math.PI/2,rz:-p.heading,color:p.color});const t=gates[p.gate]||goal,a=Math.atan2(t.x-p.x,t.z-p.z);c.draw('arrow'+p.i,'cone',{x:p.x+Math.sin(a)*1.2,y:.4,z:p.z+Math.cos(a)*1.2,sx:.35,sy:.7,sz:.2,rx:Math.PI/2,rz:-a,color:p.color});});},timeout(){c.complete([],'5분 안에 정해진 코스를 완주하지 못했습니다');}};
}
function will(c){
 c.limit=300;const target=100;c.players.forEach((p,i)=>{p.x=(i-1.5)*3.7;p.z=2;p.rate=c.rand(5.8,7.5);p.phase=c.rand(0,1);});return{update(){c.hint('A를 반복해 마음의 힘 보내기 · 시든 꽃을 완전히 살리는 선수가 승리');const done=[];for(const p of c.players){const q=c.input(p,()=>({a:pulse(c.time,p.rate,p.phase)}));if(q.ap){c.points(p);if(p.score>=target)done.push({ids:[p.i],t:0});}}finish(c,done,'꽃이 완전히 되살아났습니다');},render(){c.arena({width:19,depth:12,color:'#c4bd99'});for(const p of c.players){const progress=Math.min(1,p.score/target),height=.8+progress*2.5;c.draw('pot'+p.i,'cylinder',{x:p.x,y:.4,z:0,sx:1.6,sy:.8,sz:1.6,color:'#b99b83'});c.draw('stem'+p.i,'cylinder',{x:p.x,y:.8+height/2,z:0,sx:.17,sy:height,sz:.17,color:'#8dac85'});c.draw('flower'+p.i,'sphere',{x:p.x+(1-progress)*.7,y:.8+height,z:0,sx:1.2,sy:.8,sz:1.2,color:progress>.95?'#e9c972':'#b2aa88'});for(const side of [-1,1])c.draw('leaf'+p.i+'_'+side,'box',{x:p.x+side*.5,y:.9+height*.5,z:0,sx:1,sy:.12,sz:.5,rz:side*(1-progress),color:'#91ad83'});label(c,'growth'+p.i,Math.min(100,p.score)+'%',p.x,4.9,0,2.5);}},timeout(){c.complete([],'5분 안에 꽃을 되살리지 못했습니다');}};
}
function triple(c){
 c.limit=90;c.view={size:26,eye:[0,7,29],target:[0,2,0]};let turn=0,stage=0,age=0,gap=.8,camera=0;const distances=Array(4).fill(null);c.players.forEach((p,i)=>{p.x=-9;p.z=(i-1.5)*1.7;p.y=0;p.worldX=0;p.vx=0;p.vy=0;p.rate=c.rand(5.5,7.4);p.phase=c.rand(0,1);});
 function result(){const max=Math.max(...distances.map(x=>x??0));c.complete(distances.every(x=>x===max)?[]:distances.flatMap((x,i)=>x===max?[i]:[]),'세 번의 점프를 마친 최종 거리 비교');}
 return{update(dt){const p=c.players[Math.min(turn,3)];c.hint(`${Math.min(turn+1,4)}P 차례 · ${Math.min(stage+1,3)}/3 점프 · ${stage===1?'B':'A'} 반복 입력으로 공중 거리 늘리기`);const qs=c.players.map(o=>c.input(o,()=>({a:o===p&&stage!==1&&pulse(c.time,o.rate,o.phase),b:o===p&&stage===1&&pulse(c.time,o.rate,o.phase)})));if(gap>0){gap-=dt;if(gap<=0){age=0;p.vy=7+stage*.6;p.vx=4+stage*1.5;}return;}age+=dt;const q=qs[p.i];if(stage===1?q.bp:q.ap)p.vx=Math.min(13+stage*3,p.vx+.65);p.vy-=10*dt;p.worldX+=p.vx*dt;p.y+=p.vy*dt;if(p.y<=0&&age>.2){p.y=0;stage++;if(stage<3){p.vy=7+stage*.6;p.vx=4+stage*1.5;age=0;c.sound?.(360+stage*90,.1);}else{distances[p.i]=Math.round(p.worldX*100)/100;p.score=distances[p.i];turn++;if(turn===4){result();return;}stage=0;gap=1.1;age=0;}}camera=Math.max(0,c.players[Math.min(turn,3)].worldX-10);for(const o of c.players){o.x=-9+o.worldX-camera;o.visible=o.i===turn||distances[o.i]==null;o.pose='jump';}},render(){c.arena({width:29,depth:12,color:'#c8b58c'});for(let i=0;i<24;i++){const x=-9+i*4-camera;if(x<-14||x>14)continue;c.draw('tick'+i,'box',{x,y:.01,z:0,sx:.05,sy:.02,sz:7,color:cream});label(c,'metre'+i,i*4+' m',x,.7,4,.9);}for(let i=0;i<4;i++)label(c,'record'+i,`${i+1}P ${distances[i]==null?'—':distances[i].toFixed(2)+' m'}`,-9+i*6,5,-3,4);},timeout:result};
}
function flowers(c){
 c.limit=30;const items=[],puddles=[{x:-4,z:1,rx:2,rz:1.1},{x:3.5,z:-2,rx:1.7,rz:1.4}];let next=0,id=0;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=3;p.stun=0;p.phase=c.rand(0,1);});
 return{update(dt){next-=dt;if(next<=0){next=c.rand(.16,.27);items.push({id:id++,x:c.rand(-7.5,7.5),z:c.rand(-4.5,4.5),y:6,age:0,gold:c.rand()<.14});}for(const f of items){f.y=Math.max(.25,f.y-2.9*dt);if(f.y<=.25)f.age+=dt;}c.hint('방향 이동·A 점프 / 분홍 1점·황금 3점 / 물웅덩이는 느려지고 머리를 밟히면 잠시 멈춥니다');const oldY=c.players.map(p=>p.y);for(const p of c.players){p.stun=Math.max(0,p.stun-dt);const target=items.filter(f=>f.age<2.5).sort((a,b)=>(dist(p,a)+Math.max(0,a.y-2))/(a.gold?1.8:1)-(dist(p,b)+Math.max(0,b.y-2))/(b.gold?1.8:1))[0]||p,q=c.input(p,()=>({...toward(p,target.x,target.z),a:!p.stun&&target.y>1&&dist(p,target)<1.3&&pulse(c.time,2,p.phase)})),water=p.y===0&&puddles.some(w=>((p.x-w.x)/w.rx)**2+((p.z-w.z)/w.rz)**2<1);c.move(p,q,p.stun?1.4:water?2:4.5);c.jump(p,p.stun?{}:q,7.5);}const stomps=new Set();for(const p of c.players)for(const o of c.players)if(o!==p&&oldY[p.i]>o.y+1&&p.y<=o.y+1&&p.vy<0&&dist(p,o)<.85)stomps.add(o.i);stomps.forEach(i=>c.players[i].stun=.7);for(const f of items){if(f.taken)continue;const candidates=c.players.filter(p=>dist(p,f)<.7&&Math.abs(p.y+.7-f.y)<1).sort((a,b)=>Math.hypot(a.x-f.x,a.z-f.z,a.y+.7-f.y)-Math.hypot(b.x-f.x,b.z-f.z,b.y+.7-f.y));if(candidates.length){const winner=candidates[0];c.points(winner,f.gold?3:1);f.taken=true;}}for(let i=items.length-1;i>=0;i--)if(items[i].taken||items[i].age>2.5)items.splice(i,1);},render(){c.arena({width:20,depth:14,color:'#b8c795'});puddles.forEach((p,i)=>c.draw('puddle'+i,'cylinder',{x:p.x,y:.02,z:p.z,sx:p.rx*2,sy:.03,sz:p.rz*2,color:'#86bbca'}));for(const f of items){c.draw('flower'+f.id,'sphere',{x:f.x,y:f.y,z:f.z,sx:.5,sy:.2,sz:.5,color:f.gold?'#edc66e':'#dfa3bd'});c.draw('stem'+f.id,'cylinder',{x:f.x,y:f.y-.15,z:f.z,sx:.04,sy:.35,sz:.04,color:'#879c73'});}},timeout(){const max=Math.max(...c.players.map(p=>p.score));c.complete(c.players.every(p=>p.score===max)?[]:c.players.filter(p=>p.score===max).map(p=>p.i),'모은 꽃 점수 비교');}};
}
function fishStar(c){
 c.limit=60;c.bounds={x:10,z:10};const size=1.65,tiles=[],fish=[];let next=.8,id=0;c.players.forEach((p,i)=>{p.x=Math.cos(i*TAU/4)*3;p.z=Math.sin(i*TAU/4)*3;p.stun=0;p.cool=0;p.goal={x:p.x,z:p.z};p.react=0;p.lag=c.rand(.2,.45);p.phase=c.rand(0,1);});for(let x=-4;x<=4;x++)for(let z=-4;z<=4;z++){const a=Math.atan2(z,x),r=Math.hypot(x,z),edge=2.5+1.35*Math.cos(a*5);if(r<edge+.55)tiles.push({x:x*size,z:z*size,fall:null});}const tileAt=p=>tiles.find(t=>t.fall!==-1&&Math.abs(p.x-t.x)<size/2&&Math.abs(p.z-t.z)<size/2);
 return{update(dt){c.hint('방향 이동·A 점프·B 주먹·공중 B 발차기 / 흔들리는 바닥과 낙하 물고기를 피하세요');next-=dt;if(next<=0){next=Math.max(.48,1.65-c.time*.018);const stable=tiles.filter(t=>t.fall==null),edges=stable.filter(t=>tiles.filter(o=>o.fall!==-1&&dist(t,o)<size*1.1).length<5),target=c.pick(edges.length?edges:stable);if(target)fish.push({id:id++,x:target.x,z:target.z,y:7,large:c.rand()<.28,hit:false});}for(const f of fish){f.y-=8*dt;if(f.y<=.5&&!f.hit){f.hit=true;const reach=f.large?size*1.5:size*.7;for(const t of tiles)if(t.fall==null&&dist(t,f)<=reach)t.fall=.65;for(const p of live(c))if(dist(p,f)<(f.large?1.5:.8)){p.stun=.7;const v=toward(f,p.x,p.z);p.vx=v.x*2;p.vz=v.z*2;}}}for(const t of tiles)if(t.fall!=null&&t.fall>=0){t.fall-=dt;if(t.fall<=0)t.fall=-1;}const oldY=c.players.map(p=>p.y),inputs=[];for(const p of live(c)){p.stun=Math.max(0,p.stun-dt);p.cool=Math.max(0,p.cool-dt);p.react-=dt;if(p.react<=0){p.react=p.lag;const safe=tiles.filter(t=>t.fall==null&&!fish.some(f=>!f.hit&&dist(t,f)<(f.large?2.5:1.3))).sort((a,b)=>dist(p,a)+Math.hypot(a.x,a.z)*.15-(dist(p,b)+Math.hypot(b.x,b.z)*.15));p.goal=safe[0]||{x:0,z:0};}const q=inputs[p.i]=c.input(p,()=>({...toward(p,p.goal.x,p.goal.z),a:!tileAt(p)&&p.y===0||!!tileAt(p)?.fall&&pulse(c.time,2,p.phase),b:live(c).some(o=>o!==p&&dist(p,o)<1.4)&&pulse(c.time,2.2,p.phase)}));if(!p.stun)c.move(p,q,4.2,false);if(tileAt(p)||p.y>0)c.jump(p,p.stun?{}:q,7.7);p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-5*dt);p.vz*=Math.exp(-5*dt);}const hits=[];for(const p of live(c))if(!p.stun&&inputs[p.i]?.bp&&p.cool===0){p.cool=.4;for(const o of live(c))if(o!==p&&dist(p,o)<1.5&&Math.abs(p.y-o.y)<1.2)hits.push({target:o,from:p,kick:p.y>.15});}for(const p of live(c))for(const o of live(c))if(o!==p&&oldY[p.i]>o.y+1&&p.y<=o.y+1&&p.vy<0&&dist(p,o)<.8)hits.push({target:o,from:p,stomp:true});for(const h of hits){const v=toward(h.from,h.target.x,h.target.z);h.target.vx+=v.x*(h.stomp?1.5:h.kick?5.5:4);h.target.vz+=v.z*(h.stomp?1.5:h.kick?5.5:4);h.target.stun=h.stomp?.7:.35;}for(const p of live(c))if(!tileAt(p)&&p.y<=.001)c.eliminate(p);if(live(c).length<=1)c.complete(live(c).map(p=>p.i),'마지막까지 별 위에 남은 선수');for(let i=fish.length-1;i>=0;i--)if(fish[i].y<-2)fish.splice(i,1);},render(){c.draw('water','box',{x:0,y:-1,z:0,sx:25,sy:.2,sz:23,color:'#9cc3cd'});tiles.forEach((t,i)=>{if(t.fall===-1)return;c.draw('tile'+i,'box',{x:t.x+(t.fall!=null?Math.sin(c.time*55)*.04:0),y:-.2,z:t.z,sx:size*.97,sy:.4,sz:size*.97,color:t.fall==null?'#dfc88f':'#d49c87'});});fish.forEach(f=>c.draw('fish'+f.id,'cone',{x:f.x,y:f.y,z:f.z,sx:f.large?1.5:.7,sy:f.large?2:1,sz:f.large?1.5:.7,color:f.large?'#ce9188':'#87abc9',rx:Math.PI}));},timeout(){c.complete(live(c).length===1?live(c).map(p=>p.i):[],'시간 종료 · 단독 생존자가 없으면 무승부');}};
}
function frenzy(c){
 c.limit=45;c.bounds={x:8,z:5};const gems=[{x:-6,z:-4},{x:6,z:-4},{x:-6,z:4},{x:6,z:4},{x:0,z:0}].map((p,i)=>({...p,id:i,owner:null,wait:0})),icicles=[];let next=3,id=0;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=2;p.vx=p.vz=0;p.stun=0;p.inv=0;p.cool=0;p.pound=false;p.phase=c.rand(0,1);});
 const held=p=>gems.filter(g=>g.owner===p.i);function release(p,all){const lost=all?held(p):held(p).slice(0,1);lost.forEach((g,i)=>{g.owner=null;g.x=clamp(p.x+Math.cos(i*TAU/Math.max(1,lost.length))*.9,-7.8,7.8);g.z=clamp(p.z+Math.sin(i*TAU/Math.max(1,lost.length))*.9,-4.8,4.8);g.wait=.2;});}
 return{update(dt){c.hint('방향 이동·A 점프→공중 A 내려찍기·B 주먹/공중 발차기 / 수정은 다섯 개 · 고드름을 건드리면 전부 떨어뜨림');next-=dt;if(next<=0){next=c.rand(2,3.4);icicles.push({id:id++,x:c.rand(-7.4,7.4),z:c.rand(-4.4,4.4),y:7,age:0});}for(const ice of icicles){ice.y=Math.max(.9,ice.y-9*dt);ice.age+=dt;}gems.forEach(g=>g.wait=Math.max(0,g.wait-dt));const oldY=c.players.map(p=>p.y),inputs=[],landed=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.inv=Math.max(0,p.inv-dt);p.cool=Math.max(0,p.cool-dt);const loose=gems.filter(g=>g.owner==null&&!g.wait).sort((a,b)=>dist(p,a)-dist(p,b)),victim=c.players.filter(o=>o!==p&&held(o).length).sort((a,b)=>held(b).length-held(a).length||dist(p,a)-dist(p,b)),target=held(p).length>=3?{x:-Math.sign(victim[0]?.x||1)*6,z:-Math.sign(victim[0]?.z||1)*3}:loose[0]||victim[0]||p;let direction=toward(p,target.x,target.z);for(const ice of icicles)if(dist(p,ice)<1.5){const avoid=toward(ice,p.x,p.z);direction={x:direction.x+avoid.x*2,z:direction.z+avoid.z*2};}const q=inputs[p.i]=c.input(p,()=>({...direction,a:icicles.some(i=>dist(p,i)<1.4)&&pulse(c.time,2,p.phase),b:victim.some(o=>dist(p,o)<1.4)&&pulse(c.time,2.1,p.phase)}));p.vx+=(q.x*(p.stun?0:13)-p.vx*3)*dt;p.vz+=(q.z*(p.stun?0:13)-p.vz*3)*dt;p.x=clamp(p.x+p.vx*dt,-8,8);p.z=clamp(p.z+p.vz*dt,-5,5);const old=p.y;c.jump(p,p.stun?{}:q,7.5);if(q.ap&&old>.05&&!p.pound){p.pound=true;p.vy=-15;}if(old>.05&&p.y===0&&p.pound){landed.push(p);p.pound=false;}if(!p.inv&&icicles.some(i=>i.y<2.3&&Math.hypot(p.x-i.x,p.z-i.z)<.62&&p.y<1.7)){release(p,true);p.inv=1;p.stun=.6;}}
 const hits=new Map();for(const p of c.players)if(!p.stun&&inputs[p.i].bp&&p.cool===0){p.cool=.4;for(const o of c.players)if(o!==p&&dist(p,o)<1.5&&Math.abs(p.y-o.y)<1.2)hits.set(o.i,p);}for(const p of landed)for(const o of c.players)if(o!==p&&dist(p,o)<2.1&&o.y<.6)hits.set(o.i,p);for(const p of c.players)for(const o of c.players)if(o!==p&&oldY[p.i]>o.y+1&&p.y<=o.y+1&&p.vy<0&&dist(p,o)<.8)hits.set(o.i,p);for(const [i,from] of hits){const p=c.players[i];if(p.inv)continue;release(p,false);p.inv=.65;p.stun=.4;const v=toward(from,p.x,p.z);p.vx+=v.x*3;p.vz+=v.z*3;}for(const g of gems)if(g.owner==null&&!g.wait){const near=c.shuffle(c.players).filter(p=>!p.stun&&p.y<1.2&&dist(p,g)<.65).sort((a,b)=>dist(a,g)-dist(b,g));if(near[0])g.owner=near[0].i;}c.players.forEach(p=>p.score=held(p).length);},render(){c.arena({width:19,depth:13,color:'#b1cfd0'});icicles.forEach(i=>{c.draw('ice'+i.id,'cone',{x:i.x,y:i.y,z:i.z,sx:.7,sy:1.8,sz:.7,color:'#d4e4de',opacity:.85});if(i.y>1)disc(c,'shadow'+i.id,i.x,i.z,.5,'#87afba');});for(const g of gems){const p=g.owner==null?g:c.players[g.owner],order=g.owner==null?0:held(p).indexOf(g);c.draw('gem'+g.id,'cone',{x:p.x+(g.owner==null?0:(order-(held(p).length-1)/2)*.45),y:g.owner==null?.5:p.y+2.1,z:p.z,sx:.55,sy:.85,sz:.55,color:colors[g.id],ry:c.time*.8});}},timeout(){const max=Math.max(...c.players.map(p=>p.score));c.complete(max===0||c.players.every(p=>p.score===max)?[]:c.players.filter(p=>p.score===max).map(p=>p.i),'종료 순간 보유한 수정 개수 비교');}};
}
function flat(c){
 c.limit=45;c.bounds={x:8,z:5};const ball=c.players[0],moles=[];let next=1.1,id=0;ball.x=0;ball.z=-3;ball.vx=ball.vz=0;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*5;p.z=3;p.stun=0;p.inv=0;p.goal={x:p.x,z:p.z};p.react=0;p.lag=c.rand(.2,.4);});
 return{update(dt){c.hint('방향 이동만 사용 / 1P 관성이 있는 공으로 세 명을 납작하게 / 팀은 두더지를 피해 45초 생존');next-=dt;if(next<=0){next=c.rand(.7,1.2);moles.push({id:id++,x:c.rand(-7.7,7.7),z:c.rand(-4.8,4.8),age:0});}moles.forEach(m=>m.age+=dt);const nearest=trio(c).sort((a,b)=>dist(ball,a)-dist(ball,b))[0]||ball,target={x:nearest.x+nearest.vx*.25,z:nearest.z+nearest.vz*.25},q=c.input(ball,()=>toward(ball,target.x,target.z));ball.vx+=(q.x*8.3-ball.vx*1.35)*dt;ball.vz+=(q.z*8.3-ball.vz*1.35)*dt;ball.x+=ball.vx*dt;ball.z+=ball.vz*dt;if(Math.abs(ball.x)>7.3){ball.x=clamp(ball.x,-7.3,7.3);ball.vx*=-.35;}if(Math.abs(ball.z)>4.5){ball.z=clamp(ball.z,-4.5,4.5);ball.vz*=-.35;}ball.y=2.2;for(const p of trio(c)){p.stun=Math.max(0,p.stun-dt);p.inv=Math.max(0,p.inv-dt);p.react-=dt;if(p.react<=0){p.react=p.lag;const candidates=Array.from({length:12},(_,i)=>({x:Math.cos(i*TAU/12)*6.8,z:Math.sin(i*TAU/12)*4}));p.goal=candidates.sort((a,b)=>(dist(b,ball)-dist(b,p)*.45)-(dist(a,ball)-dist(a,p)*.45))[0];}let direction=toward(p,p.goal.x,p.goal.z);if(dist(p,ball)<3.4){const away=toward(ball,p.x,p.z),side=Math.sign((p.x-ball.x)*ball.vz-(p.z-ball.z)*ball.vx)||1;direction={x:away.x*1.5+away.z*side-.3*p.x/8,z:away.z*1.5-away.x*side-.3*p.z/5};}for(const m of moles)if(m.age>.35&&dist(p,m)<1.5){const v=toward(m,p.x,p.z);direction={x:direction.x+v.x*2,z:direction.z+v.z*2};}const input=c.input(p,()=>direction),old={x:p.x,z:p.z};if(!p.stun)c.move(p,input,4.5);p.vx=dt?(p.x-old.x)/dt:0;p.vz=dt?(p.z-old.z)/dt:0;if(!p.inv&&moles.some(m=>m.age>.35&&dist(p,m)<.7)){p.stun=.65;p.inv=1;}if(dist(p,ball)<1.2)c.eliminate(p);}for(let i=moles.length-1;i>=0;i--)if(moles[i].age>4||dist(moles[i],ball)<1.1)moles.splice(i,1);if(!trio(c).length)c.complete([0],'공으로 세 명을 모두 잡았습니다');},render(){c.arena({width:19,depth:13,color:'#c1ba8d'});c.draw('ball','sphere',{x:ball.x,y:1,z:ball.z,sx:2.2,sy:2.2,sz:2.2,color:'#bbb4d0',ry:c.time,rz:-ball.x});moles.forEach(m=>{disc(c,'hole'+m.id,m.x,m.z,.55,'#988366');if(m.age>.35)c.draw('mole'+m.id,'sphere',{x:m.x,y:.35,z:m.z,sx:.8,sy:.7,sz:.8,color:'#b3977b'});});},timeout(){c.complete(trio(c).length?[1,2,3]:[0],'한 명이라도 살아남으면 팀 전체 승리');}};
}
function mechs(c){
 c.limit=60;c.bounds={x:10,z:7};c.view={size:26,eye:[0,27,23],target:[0,0,0]};const shots=[],waves=[],cover=[{x:-4,z:-2,hp:3},{x:4,z:2,hp:3},{x:0,z:4,hp:3},{x:0,z:-4,hp:3}];let id=0;c.players.forEach((p,i)=>{p.x=i===0?0:(i-2)*6;p.z=i===0?-6.3:6.3;p.heading=i===0?0:Math.PI;p.hp=i===0?12:4;p.chargeA=0;p.chargeB=0;p.wasA=false;p.wasB=false;p.cool=0;p.inv=0;p.dash=0;p.phase=c.rand(0,1);p.rate=c.rand(.7,1.1);});
 function beam(p,charge){shots.push({id:id++,owner:p.i,x:p.x+Math.sin(p.heading),z:p.z+Math.cos(p.heading),vx:Math.sin(p.heading)*14,vz:Math.cos(p.heading)*14,power:p.i===0?charge>.9?4:2:1,radius:charge>.9?.48:.2,age:0});p.cool=p.i===0?.45:.3;c.sound?.(p.i===0?170:310,.06);}
 return{update(dt){c.hint('방향: 좌우 회전·위 전진 / A 빔 / 1P A·B 모았다 놓기, C·D 좌우 이동 / 팀 B 모았다 놓아 돌진');for(const p of live(c)){p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);p.dash=Math.max(0,p.dash-dt);const opponents=p.i===0?trio(c):c.players[0].alive?[c.players[0]]:[],target=opponents.sort((a,b)=>dist(p,a)-dist(p,b))[0]||p,desired=Math.atan2(target.x-p.x,target.z-p.z),error=wrap(desired-p.heading),close=dist(p,target),cycle=(c.time*p.rate+p.phase)%2.2;const q=c.input(p,()=>({x:clamp(error*2,-1,1),z:close>5?-1:close<2.5?1:0,a:Math.abs(error)<.2&&(p.i===0?cycle<1.2:pulse(c.time,2.1,p.phase)),b:p.i===0?close<3.6&&cycle<.6:close<3.5&&cycle<.5,c:p.i===0&&close<4&&Math.sin(c.time)>0,d:p.i===0&&close<4&&Math.sin(c.time)<=0}));p.heading+=q.x*(p.i===0?1.7:2.5)*dt;const speed=p.dash?10:p.i===0?2.8:4,forward=-q.z*speed,strafe=p.i===0?(q.d-q.c)*2.8:0,old={x:p.x,z:p.z};p.x=clamp(p.x+(Math.sin(p.heading)*forward+Math.cos(p.heading)*strafe)*dt,-10,10);p.z=clamp(p.z+(Math.cos(p.heading)*forward-Math.sin(p.heading)*strafe)*dt,-7,7);if(cover.some(b=>b.hp>0&&Math.abs(p.x-b.x)<1.3&&Math.abs(p.z-b.z)<1.1)){p.x=old.x;p.z=old.z;}if(p.i===0){if(q.a)p.chargeA+=dt;if(p.wasA&&!q.a){if(!p.cool)beam(p,p.chargeA);p.chargeA=0;}if(q.b)p.chargeB+=dt;if(p.wasB&&!q.b){if(!p.cool){waves.push({id:id++,x:p.x,z:p.z,r:0,max:2.1+Math.min(1.2,p.chargeB)*1.4,hit:new Set(),age:0});p.cool=.55;}p.chargeB=0;}}else{if(q.ap&&!p.cool)beam(p,0);if(q.b)p.chargeB+=dt;if(p.wasB&&!q.b){if(p.chargeB>.2)p.dash=.25+Math.min(1,p.chargeB)*.2;p.chargeB=0;}}p.wasA=q.a;p.wasB=q.b;p.rotation=Math.PI/2-p.heading;p.y=.25;p.score=p.hp;}
 const damage=new Map(),push=new Map();for(const s of shots){s.age+=dt;s.x+=s.vx*dt;s.z+=s.vz*dt;const b=cover.find(b=>b.hp>0&&Math.abs(s.x-b.x)<1.1+s.radius&&Math.abs(s.z-b.z)<.8+s.radius);if(b){b.hp-=s.power;s.gone=true;continue;}const enemies=s.owner===0?trio(c):c.players[0].alive?[c.players[0]]:[];const p=enemies.filter(p=>dist(p,s)<(p.i===0?1.2:.7)+s.radius).sort((a,b)=>dist(a,s)-dist(b,s))[0];if(p){s.gone=true;if(!p.inv){damage.set(p.i,(damage.get(p.i)||0)+s.power);push.set(p.i,{x:s.vx*.06,z:s.vz*.06});}}}for(const w of waves){w.age+=dt;w.r=Math.min(w.max,w.r+11*dt);for(const p of trio(c))if(!w.hit.has(p.i)&&dist(w,p)<=w.r+.6){w.hit.add(p.i);if(!p.inv){damage.set(p.i,(damage.get(p.i)||0)+1);push.set(p.i,toward(w,p.x,p.z));}}}for(const [i,n] of damage){const p=c.players[i],v=push.get(i)||{x:0,z:0};p.hp=Math.max(0,p.hp-n);p.score=p.hp;p.inv=.28;p.x=clamp(p.x+v.x,-10,10);p.z=clamp(p.z+v.z,-7,7);if(!p.hp)c.eliminate(p);}for(let i=shots.length-1;i>=0;i--)if(shots[i].gone||shots[i].age>2)shots.splice(i,1);for(let i=waves.length-1;i>=0;i--)if(waves[i].age>.6)waves.splice(i,1);if(!c.players[0].alive||!trio(c).length)c.complete(!c.players[0].alive&&!trio(c).length?[]:c.players[0].alive?[0]:[1,2,3],'상대편의 모든 기체를 파괴했습니다');},render(){c.arena({width:24,depth:18,color:'#aba997'});cover.forEach((b,i)=>{if(b.hp>0)c.draw('cover'+i,'box',{x:b.x,y:1,z:b.z,sx:2.2,sy:2,sz:1.6,color:'#929d9b'});});for(const p of live(c)){c.draw('mech'+p.i,'box',{x:p.x,y:.5,z:p.z,sx:p.i===0?2.1:1.1,sy:p.i===0?1:.5,sz:p.i===0?2.3:1.6,color:p.color,ry:p.heading});rope(c,'barrel'+p.i,{x:p.x,y:1.15,z:p.z},{x:p.x+Math.sin(p.heading)*1.5,y:1.15,z:p.z+Math.cos(p.heading)*1.5},'#73868b',.25);label(c,'hp'+p.i,p.hp+' HP',p.x,3,p.z,2);if(p.i>0){const v=toward(p,c.players[0].x,c.players[0].z);c.draw('radar'+p.i,'cone',{x:p.x+v.x*1.3,y:.3,z:p.z+v.z*1.3,sx:.3,sy:.6,sz:.3,rx:Math.PI/2,rz:-Math.atan2(v.x,v.z),color:cream});}}shots.forEach(s=>c.draw('beam'+s.id,'sphere',{x:s.x,y:.8,z:s.z,sx:s.radius*2,sy:s.radius*2,sz:s.radius*2,color:s.owner===0?'#d6adcd':'#f1d488',glow:true}));waves.forEach(w=>c.draw('wave'+w.id,'ring',{x:w.x,y:.3,z:w.z,sx:w.r*2,sy:w.r*2,sz:1,rx:-Math.PI/2,color:'#caabd3',opacity:1-w.age/.6}));},timeout(){c.complete([],'60초 안에 어느 쪽도 상대를 전멸시키지 못했습니다');}};
}
// Two-unit blocks and one-unit compressed blocks retain distinct identities.
function puzzle(c){
 c.limit=300;c.view={size:28,eye:[0,6,33],target:[0,5,0]};const unit=.43,palette=['#e599b4','#8fbacf','#a2bd8d','#e2c672','#d9ddd5','#929aaa'],sequence=[];let serial=0;
 const height=column=>column.reduce((sum,b)=>sum+b.h,0),piece=n=>{while(sequence.length<=n){const i=sequence.length;sequence.push(i%6===5?{stone:true}:{colors:[c.int(0,5),c.int(0,5)]});}return sequence[n];};
 function blocks(board){const out=[];board.columns.forEach((column,x)=>{let y=0;for(const b of column){out.push({...b,x,y});y+=b.h;}});return out;}
 function adjacent(a,b){return a.x===b.x?(Math.abs(a.y+a.h-b.y)<.001||Math.abs(b.y+b.h-a.y)<.001):Math.abs(a.x-b.x)===1&&Math.min(a.y+a.h,b.y+b.h)>Math.max(a.y,b.y);}
 function matches(board){const all=blocks(board),seen=new Set(),removed=new Set(),colored=new Set();for(const first of all){if(first.color<0||seen.has(first.id))continue;const cluster=[],queue=[first];seen.add(first.id);for(const b of queue){cluster.push(b);for(const other of all)if(other.color===b.color&&!seen.has(other.id)&&adjacent(b,other)){seen.add(other.id);queue.push(other);}}if(cluster.length>=2)for(const b of cluster){colored.add(b.id);removed.add(b.id);}}for(const brick of all)if(brick.color<0&&all.some(b=>colored.has(b.id)&&adjacent(brick,b)))removed.add(brick.id);return{removed,colored};}
 function resolve(p){const b=p.puzzle,m=matches(b);if(m.colored.size){b.chain++;b.removed=m.removed;b.clearCount=m.colored.size;b.mode='clear';b.wait=.3;}else{b.mode='wait';b.wait=.25;b.chain=0;}}
 function plan(p){const b=p.puzzle,stone=b.pair.stone,options=[];for(let x=0;x<(stone?3:4);x++)for(let flip=0;flip<(stone?1:2);flip++){const columns=b.columns.map(a=>a.map(v=>({...v})));if(stone){for(let j=x;j<=x+1;j++)columns[j].forEach(block=>block.h=1);}else{const colors=flip?[...b.pair.colors].reverse():b.pair.colors;columns[x].push({id:-2,color:colors[0],h:2},{id:-3,color:colors[1],h:2});}const predicted=matches({columns}),tower=Math.max(...columns.map(height));options.push({x,flip,value:predicted.colored.size*2-tower*.6-height(columns[x])*.15+c.rand(-.2,.2)});}options.sort((a,b)=>b.value-a.value);const chosen=options[c.rand()<.12?Math.min(2,options.length-1):0];b.botX=chosen.x;b.botFlip=chosen.flip;b.botWait=c.rand(.35,.7);}
 function spawn(p){const b=p.puzzle;while(b.garbage>0){const x=c.int(0,3);b.columns[x].push({id:serial++,color:-1,h:2});b.garbage--;}if(b.columns.some(a=>height(a)>20)){c.eliminate(p);return;}b.pair=piece(b.index++);b.pair=b.pair.stone?{stone:true}:{colors:[...b.pair.colors]};b.cursor=Math.min(b.cursor,b.pair.stone?2:3);b.flipped=0;b.bottom=20;b.mode='fall';b.repeat=0;b.axis=0;plan(p);}
 c.players.forEach((p,i)=>{p.x=(i-1.5)*6.2;p.z=2;p.y=-1;p.puzzle={columns:Array.from({length:4},()=>[]),index:0,cursor:1,bottom:20,chain:0,garbage:0,mode:'fall',pair:null,axis:0,repeat:0,flipped:0};spawn(p);});
 return{update(dt){c.hint('좌우로 열 선택 / A·B 색 순서 뒤집기 / C 즉시 낙하 · 같은 색 2개 연결 · 압축과 연쇄로 100점 먼저');const wins=[],incoming=[];for(const p of live(c)){const b=p.puzzle;b.botWait=Math.max(0,b.botWait-dt);const q=c.input(p,()=>({x:b.mode==='fall'?Math.sign(b.botX-b.cursor):0,a:b.mode==='fall'&&!b.pair.stone&&b.flipped!==b.botFlip,c:b.mode==='fall'&&b.cursor===b.botX&&b.flipped===b.botFlip&&!b.botWait}));if(b.mode==='clear'){b.wait-=dt;if(b.wait<=0){const gain=b.clearCount*2**Math.min(8,b.chain-1);c.points(p,gain);b.columns=b.columns.map(a=>a.filter(v=>!b.removed.has(v.id)));if(b.chain>1)for(const o of live(c))if(o!==p)incoming.push({player:o,n:b.chain-1});if(p.score>=100)wins.push(p.i);resolve(p);}continue;}if(b.mode==='wait'){b.wait-=dt;if(b.wait<=0)spawn(p);continue;}b.repeat=Math.max(0,b.repeat-dt);const axis=Math.abs(q.x)>.5?Math.sign(q.x):0;if(axis&&(axis!==b.axis||!b.repeat)){const to=clamp(b.cursor+axis,0,b.pair.stone?2:3),top=b.pair.stone?Math.max(height(b.columns[to]),height(b.columns[to+1])):height(b.columns[to]);if(top<=b.bottom)b.cursor=to;b.repeat=.16;}b.axis=axis;if(!b.pair.stone&&(q.ap||q.bp)){b.pair.colors.reverse();b.flipped=1-b.flipped;}const landing=b.pair.stone?Math.max(height(b.columns[b.cursor]),height(b.columns[b.cursor+1])):height(b.columns[b.cursor]);b.bottom=q.cp?landing:Math.max(landing,b.bottom-5*dt);if(b.bottom<=landing){if(b.pair.stone){for(let j=b.cursor;j<=b.cursor+1;j++)b.columns[j].forEach(block=>block.h=1);c.sound?.(140,.1);}else{b.columns[b.cursor].push(...b.pair.colors.map(color=>({id:serial++,color,h:2})));if(height(b.columns[b.cursor])>20){c.eliminate(p);continue;}}resolve(p);}}
 for(const {player,n} of incoming)if(player.alive)player.puzzle.garbage+=n;if(wins.length)c.complete(wins,'연결과 연쇄로 100점을 먼저 달성했습니다');else if(live(c).length<=1)c.complete(live(c).map(p=>p.i),'더 쌓을 공간이 남은 마지막 선수');},render(){c.draw('back','box',{x:0,y:4.5,z:-1,sx:27,sy:12,sz:.3,color:'#9daaa7'});for(const p of c.players){const b=p.puzzle,base=(p.i-1.5)*6.2;c.draw('well'+p.i,'box',{x:base,y:4.3,z:0,sx:3.8,sy:9.1,sz:.3,color:p.alive?'#6c7a80':'#847e80'});for(let x=0;x<=4;x++)c.draw('grid'+p.i+'_'+x,'box',{x:base+(x-2)*.9,y:4.3,z:.2,sx:.03,sy:8.6,sz:.02,color:'#aebdbc'});for(const block of blocks(b)){const flash=b.mode==='clear'&&b.removed.has(block.id)&&Math.floor(c.time*16)%2===0;c.draw('block'+p.i+'_'+block.id,'box',{x:base+(block.x-1.5)*.9,y:(block.y+block.h/2)*unit,z:.35,sx:.83,sy:block.h*unit-.03,sz:.65,color:flash?cream:block.color<0?'#b19c87':palette[block.color]});}if(p.alive&&b.mode==='fall'){if(b.pair.stone)c.draw('press'+p.i,'box',{x:base+(b.cursor-1)*.9,y:b.bottom*unit+.5,z:.35,sx:1.7,sy:1,sz:.7,color:'#a8afb2'});else b.pair.colors.forEach((color,i)=>c.draw('fall'+p.i+'_'+i,'box',{x:base+(b.cursor-1.5)*.9,y:(b.bottom+i*2+1)*unit,z:.35,sx:.83,sy:unit*2-.03,sz:.65,color:palette[color]}));}const next=piece(b.index);label(c,'nextlabel'+p.i,'다음',base,10.4,0,2);if(next.stone)c.draw('next'+p.i,'box',{x:base,y:9.6,z:.35,sx:1.3,sy:.5,sz:.5,color:'#a8afb2'});else next.colors.forEach((color,i)=>c.draw('next'+p.i+'_'+i,'box',{x:base+(i-.5)*.65,y:9.6,z:.35,sx:.55,sy:.55,sz:.55,color:palette[color]}));if(b.chain>1)label(c,'chain'+p.i,b.chain+'연쇄',base,6.3,.9,3);if(b.garbage)label(c,'garbage'+p.i,'벽돌 '+b.garbage,base,11.3,0,2.5);}},timeout(){c.complete([],'앱의 5분 안전 상한까지 100점 또는 단독 생존을 달성하지 못했습니다');}};
}

export const games={
 "Mario's Puzzle Party":puzzle,
 'Hand, Line and Sinker':fishing,'Ridiculous Relay':relay,'Thwomp Pull':pull,'Cosmic Coaster':coaster,'Locked Out':locked,'Vine With Me':vines,
 'Ground Pound Down':poundDown,'Chimp Chase':chimps,'Chomp Romp':chomp,'Pop-Star Piranhas':popstars,'Mazed & Confused':maze,'Hydrostars':hydro,'Will Flower':will,
 'Triple Jump':triple,'Flower Shower':flowers,'Fish Upon a Star':fishStar,'Frozen Frenzy':frenzy,'Flatiator':flat,'Mario Mechs':mechs,
};
export const supportedTitles=Object.fromEntries(Object.keys(games).map((name,i)=>[name,[i<7?'mp3':'mp5']]));
export const aliases={};
export const notes={
 "Mario's Puzzle Party":'MP3의 4열×10칸, 세로 색 블록 둘의 순서 뒤집기, 같은 색 두 개 연결·낙하 연쇄, 두 열 압축, 방해 벽돌, 100점 또는 최후 생존 규칙을 구현했습니다. Z는 C입니다. 정확한 원작 환산표 미확인으로 브라우저판은 소거 블록 수×2^(연쇄−1), 2연쇄부터 상대마다 연쇄−1개 벽돌, 여섯 번째 낙하마다 압축, 5분 안전 상한을 사용합니다. 원작과 동일한 수치라고 주장하지 않습니다.',

 'Hand, Line and Sinker':'MP3의 낚시 대 물고기 1대3, 60초, 한 마리 생존 시 팀 전체 승리. 방향과 A를 유지하고 낚싯줄 거리는 위/아래 키로 변환했습니다. 연못·투척 궤적은 새로 제작했습니다.',
 'Ridiculous Relay':'MP3의 개인 글라이더 대 3구간 릴레이. 팀은 A/B 노 젓기, ↑A·↓A·↑B·↓B, A 추진을 각각 담당합니다. 구간·장애물·가속은 재제작했으며 원작 타이머가 확인되지 않아 앱 안전 상한 120초를 둡니다.',
 'Thwomp Pull':'MP3의 60초 1대3 썰매 경주. 개인은 A/B/Z 모두, 팀은 각자 하나를 담당하며 Z를 C로 옮겼습니다. 잘못된 입력·눈덩이 정지와 결승선 판정을 구현했습니다. 코스와 속도 수치는 재제작했습니다.',
 'Cosmic Coaster':'MP3의 2대2 공동 좌우 조종 경주. 한 칸·두 칸 장애물과 코인을 재제작했습니다. 코스·관성은 새로 조정했으며 원작 타이머가 확인되지 않아 앱 안전 상한 180초를 둡니다.',
 'Locked Out':'MP3의 방별 10초 열쇠 쟁탈. A 집기/놓기·B 공격, 열쇠와 문 무늬 일치, 3→2→1개의 문과 탈락, 3개 방을 구현했습니다. 방 배치는 재제작했습니다.',
 'Vine With Me':'MP3의 2인 듀얼입니다. A로 덩굴을 놓고 자동으로 다음 덩굴을 잡으며 떨어지면 직전 덩굴로 복귀합니다. 덩굴 배치·운동은 재제작했고 원작 타이머 미확인으로 앱 안전 상한 180초를 둡니다.',
 'Ground Pound Down':'MP5의 3구간·구간마다 3통로 선택, A 점프→공중 A 내려찍기, 바위 3회·흙 1회 파괴와 높은 점프의 흙 연속 파괴를 구현했습니다. 지층 배치·높이 판정·속도는 재제작했고 앱 안전 상한 180초입니다.',
 'Chimp Chase':'MP5의 30초 색깔별 원숭이 돌려주기. A 잡기/돌려주기, 일반 1점·황금 3점, 어른의 외침에 같은 색이 멈추는 규칙을 구현했습니다. 출현·이동 패턴은 재제작했습니다.',
 'Chomp Romp':'MP5의 A 호루라기로 큰 공을 유도하는 4인 경주입니다. 각자의 장애물 코스, 충돌 정지·기절·공의 결승 통과를 구현했습니다. 코스는 재제작했으며 앱 안전 상한 180초입니다.',
 'Pop-Star Piranhas':'MP5의 서로 다른 잎사귀 춤 찾기 3라운드·각 5초. 게임큐브 A/B/X/Y/L/R은 A/B/C/D/←/→에 대응합니다. 춤·음색은 직접 제작했고 정답은 선택 종료 후 공개합니다.',
 'Mazed & Confused':'MP5의 45초 전기 미로. 벽 접촉 정지, 2초마다 벽 변경, 중앙 선착순을 구현했습니다. 매번 연결 가능한 미로와 이동 수치는 새로 제작했습니다.',
 'Hydrostars':'MP5의 5개 링을 순서대로 지나 결승에 들어오는 수상 경주입니다. A 가속·B 감속·좌우 조타와 충돌 정지, 5분 제한을 적용했습니다. 링·상자 배치와 배의 물리는 재제작했습니다.',
 'Will Flower':'MP5의 A 반복 입력으로 꽃을 살리는 선착순 경기와 5분 상한을 구현했습니다. 입력량과 꽃 성장 곡선은 웹 키보드용으로 새로 조정했습니다.',
 'Triple Jump':'MP5의 네 명이 차례로 하는 세 번 도약입니다. 각 공중 구간 A→B→A 연타가 거리를 늘리고 최장 거리 승리, 전원 동률은 무승부입니다. 거리·궤적은 새로 조정했습니다.',
 'Flower Shower':'MP5의 30초 꽃 모으기입니다. 분홍 1점·황금 3점, A 점프, 웅덩이 감속, 밟히면 이동·점프 지연, 전원 동점 무승부를 구현했습니다. 낙하 패턴·지형은 재제작했습니다.',
 'Fish Upon a Star':'MP5의 별 발판 생존전입니다. A 점프·B 주먹·공중 B 발차기, 밟기, 작은 물고기 한 칸·큰 물고기 여러 칸 파괴와 흔들림 예고를 구현했습니다. 지형·밀기·낙하 패턴은 재제작했습니다.',
 'Frozen Frenzy':'MP5의 45초 수정 다섯 개 쟁탈입니다. A 점프→공중 A 내려찍기·B 주먹/공중 발차기, 공격 시 수정 하나 떨어뜨리기, 고드름 접촉 시 전부 떨어뜨리기, 소유 수 최다 승리를 구현했습니다. 얼음 물리·고드름 배치는 재제작했습니다.',
 'Flatiator':'MP5의 45초 1대3 공 굴리기입니다. 방향만 사용하며 관성이 있는 공, 두더미에 걸린 팀의 기절, 공으로 두더미 제거, 한 명 생존 시 팀 전체 승리를 구현했습니다. 물리·출현 패턴은 재제작했습니다.',
 'Mario Mechs':'MP5의 60초 1대3 기체 전투입니다. 개인 A 빔·B 충격파의 누르기/충전/놓기, L/R 횡이동은 C/D, 팀 A 빔·B 충전 돌진을 구현했습니다. 전멸 판정, 미결 시 무승부이며 경기장·체력·무기 수치는 새로 조정했습니다.',
};
