import {clamp,toward} from '../core.js';
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const label=(c,id,text,x,y,z,w=3)=>c.draw(id,'text',{x,y,z,text,sx:w,sy:w/4,color:'#294a51'});
function dungeon(c,m){
 c.limit=m.titleId==='superstars'?180:300;c.view={size:25,eye:[0,23,21],target:[0,0,0]};
 const teams=[0,1].map(i=>({i,base:i?6:-6,stage:0,gate:0,work:[0,0,0,0],angle:0,previous:0,pipes:[],correct:0,known:false,fill:0,actors:[0,1].map(j=>({player:c.players[i*2+j],j,x:j?1.2:-1.2,z:4.7,y:0,vy:0,ride:null,far:false,fall:0,wait:0,done:false,try:0,last:null,beat:0}))}));
 const setStage=(t,stage)=>{t.stage=stage;t.angle=t.previous=0;t.known=false;t.actors.forEach(a=>{Object.assign(a,{x:a.j?1.2:-1.2,z:4.7,y:0,vy:0,ride:null,far:false,fall:0,wait:0,done:false,try:0,last:null,beat:0});});if(stage===3||stage===4){const n=stage===3?5:9;t.pipes=Array.from({length:n},(_,i)=>({i,x:stage===3?(i-2)*1.4:(i%3-1)*2,z:stage===3?0:(Math.floor(i/3)-1)*2}));t.correct=c.int(0,n-1);for(const a of t.actors)a.order=c.shuffle(t.pipes.map(p=>p.i));}};
 const platforms=t=>Array.from({length:t.stage===1?2:1},(_,i)=>({i,x:Math.sin(t.angle+i*Math.PI)*3,z:Math.cos(t.angle+i*Math.PI)*3}));
 function bot(t,a){const other=t.actors[1-a.j];if(t.stage===0){const g=Math.min(3,t.gate),operator=g%2,open=t.work[g]>=6;if(t.gate>=4)return toward(a,a.j?1.2:-1.2,-5);const target={x:a.j?1.2:-1.2,z:a.j===operator&&!open?3-g*2:1.3-g*2};return{...toward(a,target.x,target.z,Math.hypot(a.x-target.x,a.z-target.z)>.12?1:0),b:a.j===operator&&Math.hypot(a.x-target.x,a.z-target.z)<.65&&Math.sin(c.time*12)>0};}
 if(t.stage===1||t.stage===2){const controller=t.actors.find(p=>p.far)||t.actors[0],rider=t.actors[1-controller.j],pads=platforms(t);if(a===controller){const lever={x:a.far?2:-2,z:a.far?-4.8:4.8};let selected=rider.ride===null?pads.reduce((a,b)=>Math.hypot(a.x,a.z-3)<Math.hypot(b.x,b.z-3)?a:b).i:rider.ride;const target=(rider.ride===null?0:Math.PI)-selected*Math.PI,error=wrap(target-t.angle);const turning=Math.hypot(a.x-lever.x,a.z-lever.z)<.7&&rider.y===0&&Math.abs(error)>.045;return{...toward(a,lever.x,lever.z,Math.hypot(a.x-lever.x,a.z-lever.z)>.15?1:0),c:turning&&error<0,d:turning&&error>0};}
 if(a.far)return{};if(a.ride!==null){const pad=pads[a.ride];if(pad.z< -2.9&&Math.abs(pad.x)<.25)return{...toward(a,0,-4.8),a:a.y===0};return{};}
 if(a.y>0)return toward(a,a.departing?0:0,a.departing?-4.8:3);const pad=pads.find(p=>p.z>2.9&&Math.abs(p.x)<.25);if(pad&&a.z>3.7&&Math.abs(a.x)<.3)return{z:-1,a:true};return toward(a,0,4.3,Math.hypot(a.x,a.z-4.3)>.1?1:0);}
 if(t.stage===3||t.stage===4){if(a.done)return{};const i=t.known?t.correct:a.order[a.try%t.pipes.length],pipe=t.pipes[i],near=Math.hypot(a.x-pipe.x,a.z-pipe.z)<.4;return{...toward(a,pipe.x,pipe.z,near?0:1),a:near&&a.wait===0};}
 const left=Math.floor(c.time/.24+a.j*.5)%2===0;return{c:left,d:!left};}
 return{update(dt){const winners=[];for(const t of teams){const inputs=t.actors.map(a=>c.input(a.player,()=>bot(t,a)));if(t.stage===0){for(const a of t.actors){const q=inputs[a.j];a.x=clamp(a.x+q.x*3*dt,-3.4,3.4);a.z=clamp(a.z+q.z*3*dt,-5.5,5.5);for(let g=0;g<4;g++){const z=2-g*2;if(t.work[g]<6&&a.z<z+.6)a.z=z+.6;}const g=t.gate;if(g<4&&a.j===g%2&&Math.hypot(a.x-(a.j?1.2:-1.2),a.z-(3-g*2))<.7&&q.bp)t.work[g]++;}if(t.gate<4&&t.work[t.gate]>=6&&t.actors[1-t.gate%2].z<1.55-t.gate*2)t.gate++;if(t.gate===4&&t.actors.every(a=>a.z< -4.7))setStage(t,1);}
 else if(t.stage===1||t.stage===2){const old=platforms(t);let turn=0;for(const a of t.actors){const q=inputs[a.j];const leverNear=Math.hypot(a.x+2,a.z-4.8)<.8||Math.hypot(a.x-2,a.z+4.8)<.8;if(leverNear)turn+=(q.d?1:0)-(q.c?1:0);}t.angle+=turn*dt*1.15;const pads=platforms(t);for(const a of t.actors){const q=inputs[a.j];if(a.fall){a.fall=Math.max(0,a.fall-dt);if(!a.fall){a.x=0;a.z=a.far?-4.8:4.8;a.y=0;a.vy=0;}continue;}if(a.ride!==null&&a.y===0){a.x+=pads[a.ride].x-old[a.ride].x;a.z+=pads[a.ride].z-old[a.ride].z;}a.x+=q.x*3.4*dt;a.z+=q.z*3.4*dt;if(q.ap&&a.y===0){a.y=.001;a.vy=5.3;a.departing=a.ride!==null;a.ride=null;}const pad=pads.find(p=>Math.abs(p.x-a.x)<.85&&Math.abs(p.z-a.z)<.85),ground=Math.abs(a.x)<3.5&&(a.z>=4||a.z<=-4);if(a.y>0||!ground&&!pad){a.vy-=18*dt;a.y+=a.vy*dt;if(a.y<=0&&(ground||pad)){a.y=0;a.vy=0;a.ride=pad?pad.i:null;}if(a.y< -2){a.fall=1;a.y=-2;a.ride=null;}}else {a.y=0;a.ride=pad?pad.i:null;}if(a.z<=-4&&ground&&a.y===0)a.far=true;}
 if(t.actors.every(a=>a.far))setStage(t,t.stage+1);}
 else if(t.stage===3||t.stage===4){for(const a of t.actors){const q=inputs[a.j];a.wait=Math.max(0,a.wait-dt);if(a.done)continue;a.x=clamp(a.x+q.x*3.2*dt,-3.4,3.4);a.z=clamp(a.z+q.z*3.2*dt,-5,5);if(q.ap&&a.wait===0){const pipe=t.pipes.find(p=>Math.hypot(p.x-a.x,p.z-a.z)<.55);if(pipe){a.wait=.6;if(pipe.i===t.correct){a.done=true;t.known=true;a.x=a.j?1:-1;a.z=-4.5;}else{a.try++;const exit=t.pipes[(pipe.i+1)%t.pipes.length];a.x=exit.x;a.z=exit.z+.8;}}}}if(t.actors.every(a=>a.done))setStage(t,t.stage+1);}
 else {for(const a of t.actors){const q=inputs[a.j];a.x=a.j?1:-1;a.z=2;const hit=q.cp?'c':q.dp?'d':null;if(hit&&hit!==a.last&&c.time-a.beat>=.12){t.fill=Math.min(100,t.fill+2);a.last=hit;a.beat=c.time;}}if(t.fill>=100)winners.push(t.i);}
 for(const a of t.actors){const p=a.player;p.x=t.base+a.x;p.z=a.z;p.y=a.y;p.scale=.62;p.score=t.stage*100+(t.stage===0?t.gate*25:t.stage===5?t.fill:0);p.pose=a.y>0?'jump':Math.abs(inputs[a.j].x)+Math.abs(inputs[a.j].z)>.1?'run':'idle';}}
 if(winners.length)c.complete(winners.flatMap(i=>[i*2,i*2+1]),'두 동료가 풍선을 타고 탈출했습니다');
 c.hint('방향 이동 · A 점프/굴 들어가기 · B 레버 반복 · C/D 회전 / 마지막 풍선 번갈아 누르기');},
 render(){for(const t of teams){const base=t.base;label(c,'stage'+t.i,`${t.i+1}팀 · ${['서로 벽 열기','두 발판 다리','한 발판 다리','다섯 굴 찾기','아홉 굴 찾기','풍선 탈출'][t.stage]}`,base,1,7,5);if(t.stage===1||t.stage===2){for(const z of [-5,5])c.draw('bank'+t.i+z,'box',{x:base,y:-.3,z,sx:7,sy:.6,sz:2,color:'#c5b49b'});c.draw('hub'+t.i,'cylinder',{x:base,y:-.5,z:0,sx:.5,sy:1,sz:.5,color:'#718e8a'});for(const p of platforms(t)){c.draw('arm'+t.i+'_'+p.i,'box',{x:base+p.x/2,y:-.2,z:p.z/2,sx:.18,sy:.3,sz:3,ry:t.angle+p.i*Math.PI,color:'#96a39a'});c.draw('pad'+t.i+'_'+p.i,'box',{x:base+p.x,y:-.15,z:p.z,sx:1.7,sy:.3,sz:1.7,color:'#d9c69d'});}for(const side of [-1,1])c.draw('lever'+t.i+side,'box',{x:base+side*2,y:.6,z:-side*4.8,sx:.3,sy:1.2,sz:.3,rz:Math.sin(c.time*4)*.2,color:'#c69775'});}else{c.draw('floor'+t.i,'box',{x:base,y:-.25,z:0,sx:8,sy:.5,sz:12,color:'#bcb9a3'});if(t.stage===0){for(let g=0;g<4;g++){c.draw('wall'+t.i+'_'+g,'box',{x:base,y:t.work[g]>=6?-.4:1.4,z:2-g*2,sx:7,sy:2.8,sz:.45,color:'#91998c'});c.draw('switch'+t.i+'_'+g,'box',{x:base+(g%2?1.2:-1.2),y:.6,z:3-g*2,sx:.3,sy:1.2,sz:.3,color:t.work[g]>=6?'#a5c8a0':'#d9b578'});label(c,'work'+t.i+'_'+g,`${Math.min(6,t.work[g])}/6`,base+(g%2?1.2:-1.2),1.5,3-g*2,1.5);}}else if(t.stage===3||t.stage===4){for(const p of t.pipes){c.draw('pipe'+t.i+'_'+p.i,'cylinder',{x:base+p.x,y:.3,z:p.z,sx:1.1,sy:.6,sz:1.1,color:t.known&&p.i===t.correct?'#e8c068':'#80a69a'});c.draw('hole'+t.i+'_'+p.i,'cylinder',{x:base+p.x,y:.61,z:p.z,sx:.8,sy:.025,sz:.8,color:'#3b5a5a'});}}else{const r=1+t.fill*.025;c.draw('balloon'+t.i,'sphere',{x:base,y:3,z:-1,sx:r*1.6,sy:r*2,sz:r*1.6,color:t.i?'#8ab7be':'#dfa4b4'});c.draw('basket'+t.i,'box',{x:base,y:.5,z:-1,sx:2.2,sy:1,sz:1.5,color:'#cba16e'});label(c,'fill'+t.i,`${t.fill}%`,base,1,4);}}}},timeout(){c.complete([],'제한시간 안에 탈출하지 못했습니다');}};
}
export const games={'Dungeon Duos':dungeon};
export const supportedTitles={'Dungeon Duos':['mp4','superstars']};
export const notes={'Dungeon Duos':'네 개의 교대 레버 벽 → 두 발판/한 발판 회전 다리 → 5개/9개 굴 → 풍선의 협동 순서를 구현했습니다. A 점프·굴 입장, B 레버 반복, C/D 회전·교대 펌프입니다. 코스·점프·펌프 횟수는 새로 제작했으며 MP4 5분, 슈퍼스타즈 3분 종료를 구분합니다.'};
