import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,cream='#f2e5c9',ink='#35555e';
const label=(c,id,text,x,y,z,w=4)=>c.draw(id,'text',{x,y,z,sx:w,sy:w/4,text,color:ink});
const pair=t=>[t*2,t*2+1];const teamScore=(c,s,reason)=>c.complete(s[0]===s[1]?[]:pair(s[0]>s[1]?0:1),reason);
const pulse=(t,h,phase=0)=>(t*h+phase)%1<.4;
function waves(c){
 c.limit=30;c.view={size:21,eye:[0,24,17],target:[0,0,0]};const tilt={x:0,z:0,vx:0,vz:0};let waves=[],id=0;c.players.forEach(p=>{p.x=0;p.z=0;p.angle=p.i*TAU/3;p.hop=0;p.pound=false;p.wait=c.rand(.2,1.4);});
 return{update(dt){for(const p of c.players.slice(1)){p.wait=Math.max(0,p.wait-dt);const q=c.input(p,()=>({x:Math.sin(c.time*.5+p.i)*.5,a:p.hop===0&&p.wait===0||p.hop>.6&&p.vy<1&&!p.pound}));p.angle+=q.x*dt*.7;p.x=Math.cos(p.angle)*7;p.z=Math.sin(p.angle)*7;if(q.ap){if(!p.hop){p.hop=.001;p.vy=6;}else{p.pound=true;p.vy=-12;}}if(p.hop){p.vy-=18*dt;p.hop=Math.max(0,p.hop+p.vy*dt);if(!p.hop&&p.pound){waves.push({id:id++,x:p.x,z:p.z,r:0,hit:false});p.pound=false;p.wait=c.rand(.4,1.2);}}p.y=.2+p.hop;p.pose=p.hop?'jump':'idle';}for(const w of waves){w.r+=dt*5;if(!w.hit&&w.r>=5){w.hit=true;tilt.vx-=w.x/7*.75;tilt.vz-=w.z/7*.75;}}waves=waves.filter(w=>w.r<13);const p=c.players[0],q=c.input(p,()=>({x:clamp((-p.x*.5-tilt.x*3)*2,-1,1),z:clamp((-p.z*.5-tilt.z*3)*2,-1,1)}));tilt.vx+=(-tilt.x*4-tilt.vx*1.5+p.x*.015)*dt;tilt.vz+=(-tilt.z*4-tilt.vz*1.5+p.z*.015)*dt;tilt.x+=tilt.vx*dt;tilt.z+=tilt.vz*dt;p.x+=(q.x*3.7+tilt.x*7)*dt;p.z+=(q.z*3.7+tilt.z*7)*dt;p.y=.35+tilt.x*p.x+tilt.z*p.z;if(Math.abs(p.x)>3.1||Math.abs(p.z)>2.5)c.complete([1,2,3],'파도로 균형을 무너뜨렸습니다');c.hint('1P 방향으로 기울기 균형 잡기 · 팀 좌우로 뗏목 이동/A 점프/공중 A 내려찍기로 파도 만들기');},render(){c.arena({width:19,depth:19,color:'#89c1c9'});c.draw('raft','box',{x:0,y:.1,z:0,sx:6.6,sy:.4,sz:5.4,rz:tilt.x,rx:-tilt.z,color:'#d2b68b'});for(const p of c.players.slice(1))c.draw('outer'+p.i,'cylinder',{x:p.x,y:.05,z:p.z,sx:2,sy:.3,sz:2,color:p.color});for(const w of waves)c.draw('wave'+w.id,'ring',{x:w.x,y:.05,z:w.z,sx:w.r*2,sy:w.r*2,sz:1,rx:-Math.PI/2,color:cream,opacity:Math.max(.1,1-w.r/13)});},timeout(){c.complete([0],'30초 동안 균형을 지켰습니다');}};
}
function drips(c){
 c.limit=60;c.view={size:22,eye:[0,15,22],target:[0,2,0]};const keys=['a','b','c','d','left','right'],symbols=['A','B','C','D','←','→'],water=[0,0];let soloSeq=c.shuffle(keys),soloAt=0,teamAt=1,teamNeed=c.int(0,5);c.players.forEach(p=>{p.x=p.i===0?-6:(p.i-2)*2+5;p.z=4;p.wait=c.rand(.3,.7);p.cool=0;p.side=0;});
 return{update(dt){const additions=[0,0];for(const p of c.players){p.wait=Math.max(0,p.wait-dt);p.cool=Math.max(0,p.cool-dt);const active=p.i===0||p.i===teamAt,need=p.i===0?keys.indexOf(soloSeq[soloAt]):teamNeed;const q=c.input(p,()=>{if(!active||p.wait||p.cool)return{};const k=keys[need];p.wait=c.rand(p.i?.4:.22,p.i?.7:.42);return k==='left'?{x:-1}:k==='right'?{x:1}:{[k]:true};});const side=q.x<-.5?-1:q.x>.5?1:0,pressed=q.ap?0:q.bp?1:q.cp?2:q.dp?3:side&&side!==p.side?side<0?4:5:-1;p.side=side;if(!active||p.cool||pressed<0)continue;if(pressed===need){if(p.i===0){soloAt++;if(soloAt===6){additions[0]++;soloAt=0;soloSeq=c.shuffle(keys);}}else{teamAt++;if(teamAt===4){teamAt=1;additions[1]++;}teamNeed=c.int(0,5);c.players[teamAt].wait=c.rand(.45,.7);}}else{p.cool=.65;if(p.i===0)soloAt=0;}}for(let t=0;t<2;t++)water[t]+=additions[t];c.players[0].score=water[0];c.players.slice(1).forEach(p=>p.score=water[1]);const done=water.flatMap((n,t)=>n>=8?t?[1,2,3]:[0]:[]);if(done.length)c.complete(done,'수조를 먼저 채웠습니다');c.hint('표시된 버튼을 순서대로 · 1P는 6개/팀은 각자 한 번 · 원작 L/R은 ←/→ · 틀리면 지연');},render(){c.arena({width:22,depth:12,color:'#becbc4'});for(let t=0;t<2;t++){const x=t?5:-6;c.draw('tank'+t,'box',{x,y:2,z:-1,sx:6,sy:4,sz:3,color:'#bcced0',opacity:.3});c.draw('water'+t,'box',{x,y:water[t]/8*1.9,z:-1,sx:5.8,sy:Math.max(.03,water[t]/8*3.8),sz:2.8,color:'#7fb8c9'});label(c,'fill'+t,`${water[t]}/8`,x,5,-1,4);}soloSeq.forEach((k,i)=>label(c,'sequence'+i,(i===soloAt?'▸':'')+symbols[keys.indexOf(k)],-9+i*1.3,6,1,3));for(const p of c.players.slice(1))label(c,'need'+p.i,p.i===teamAt?symbols[teamNeed]:'·',p.x,2.5,4,3);},timeout(){c.complete([],'시간 안에 수조를 채우지 못했습니다');}};
}
function belts(c){
 c.limit=30;c.view={size:21,eye:[0,22,17],target:[0,0,0]};let objects=[],next=.5,id=0;const score=[0,0];c.players.forEach(p=>{p.x=(p.i-1.5)*3;p.z=p.i===0?-3:3;p.fall=0;});return{update(dt){if(c.time>next){next+=.55;const kind=c.rand()<.55?'coin':c.rand()<.25?'bag':'snack';for(let row=0;row<2;row++)objects.push({id:id++,row,x:8.5,z:(row?3:-3)+c.rand(row?-1.8:-.8,row?1.8:.8),kind,value:kind==='bag'?5:1});}for(const o of objects)o.x-=dt*2.4;for(const p of c.players){const row=p.i===0?0:1,center=row?3:-3;p.fall=Math.max(0,p.fall-dt);if(p.fall){p.visible=false;if(p.fall<=dt){p.x=7;p.z=center;p.visible=true;}continue;}p.visible=true;const choices=objects.filter(o=>o.row===row&&o.kind!=='snack'&&!o.gone);const target=choices.sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,target?toward(p,target.x,target.z):toward(p,4,center));p.x+=q.x*4*dt-1.25*dt;p.z=clamp(p.z+q.z*4*dt,center-(row?2.2:1.1),center+(row?2.2:1.1));p.x=Math.min(p.x,8);for(const o of objects)if(!o.gone&&o.row===row&&dist(p,o)<(o.kind==='snack'?1:.65)){if(o.kind==='snack'){const d=dist(p,o)||1;p.x=o.x+(p.x-o.x)/d*1.05;p.z=clamp(o.z+(p.z-o.z)/d*1.05,center-(row?2.2:1.1),center+(row?2.2:1.1));}else{o.gone=true;score[row]+=o.value;}}if(p.x< -8){p.fall=1.4;p.x=7;p.z=center;}}objects=objects.filter(o=>!o.gone&&o.x> -10);c.players[0].score=score[0];c.players.slice(1).forEach(p=>p.score=score[1]);c.hint('방향으로 벨트 이동 · 과자는 길을 막습니다 · 떨어져도 상자로 복귀 · 코인 1/주머니 5');},render(){for(let row=0;row<2;row++){const z=row?3:-3;c.draw('belt'+row,'box',{x:0,y:-.15,z,sx:17,sy:.3,sz:row?5:3,color:'#8eaaa7'});for(let j=0;j<20;j++)c.draw('stripe'+row+j,'box',{x:(j*.85-c.time*1.25% .85)-8,y:.02,z,sx:.04,sy:.02,sz:row?5:3,color:'#c9d2b9'});}for(const o of objects)c.draw('item'+o.id,o.kind==='snack'?'box':o.kind==='bag'?'sphere':'cylinder',{x:o.x,y:o.kind==='snack'?.6:.4,z:o.z,sx:o.kind==='snack'?1.6:.65,sy:o.kind==='snack'?1.2:.35,sz:o.kind==='snack'?1.3:.65,color:o.kind==='snack'?'#d5a787':'#e6c267'});},timeout(){c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'각 팀이 모은 코인을 보관합니다');}};
}
function goal(c){
 c.limit=30;c.view={size:20,eye:[0,17,22],target:[0,1,0]};let balls=[],id=0,goals=0;c.players.forEach(p=>{p.x=p.i===0?0:(p.i-2)*4.5;p.z=p.i===0?-5:4;p.aim=p.x;p.charge=0;p.last=false;p.wait=c.rand(.3,1.1);p.cool=0;p.botAim=c.rand(-5,5);});return{update(dt){const keeper=c.players[0],threat=balls.filter(b=>!b.gone).sort((a,b)=>a.z-b.z)[0];const q=c.input(keeper,()=>({x:threat?clamp((threat.goalX-keeper.x)*2,-1,1):0,a:!!threat&&threat.z< -1.5&&threat.height>1.5}));keeper.x=clamp(keeper.x+q.x*7*dt,-5.7,5.7);c.jump(keeper,q,7.5);for(const p of c.players.slice(1)){p.wait=Math.max(0,p.wait-dt);p.cool=Math.max(0,p.cool-dt);const r=c.input(p,()=>({x:clamp((p.botAim-p.aim)*2,-1,1),a:p.wait===0&&p.charge<.7&&p.cool===0}));p.aim=clamp(p.aim+r.x*6*dt,-5.8,5.8);if(r.a&&!p.cool)p.charge=Math.min(1.3,p.charge+dt);if(!r.a&&p.last&&p.charge>0&&!p.cool){const flight=.7-p.charge*.2;balls.push({id:id++,x:p.x,z:p.z,y:.4,startX:p.x,goalX:p.aim,t:0,flight,height:1+p.charge*1.2,charge:p.charge});p.charge=0;p.cool=.7;p.wait=c.rand(.8,1.4);p.botAim=c.rand(-5.2,5.2);}p.last=r.a;}for(const b of balls){b.t+=dt;const t=b.t/b.flight;b.x=b.startX+(b.goalX-b.startX)*t;b.z=4-10*t;b.y=.4+Math.sin(Math.min(1,t)*Math.PI*.65)*b.height;if(b.z< -4.5&&!b.checked){b.checked=true;if(Math.abs(b.x-keeper.x)<.95&&Math.abs(b.y-(keeper.y+.65))<.9)b.gone=true;}if(b.z<=-6&&!b.gone){goals++;b.gone=true;}}for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(!a.gone&&!b.gone&&Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z)<.5)a.gone=b.gone=true;}balls=balls.filter(b=>!b.gone);c.players.slice(1).forEach(p=>p.score=goals);keeper.score=Math.max(0,10-goals);if(goals>=10)c.complete([1,2,3],'10골을 넣었습니다');c.hint('1P 좌우 이동/A 점프로 골키퍼 · 팀 좌우 조준/A 눌렀다 떼서 슛 · 길게 눌러 강하게');},render(){c.arena({width:16,depth:14,color:'#99b990'});for(const x of [-6,6])c.draw('post'+x,'cylinder',{x,y:1.7,z:-6.1,sx:.2,sy:3.4,sz:.2,color:cream});c.draw('crossbar','box',{x:0,y:3.4,z:-6.1,sx:12,sy:.18,sz:.18,color:cream});c.draw('net','box',{x:0,y:1.7,z:-6.4,sx:12,sy:3.4,sz:.05,color:cream,opacity:.25});for(const p of c.players.slice(1)){c.draw('aim'+p.i,'ring',{x:p.aim,y:.03,z:-5.6,sx:1,sy:1,sz:1,rx:-Math.PI/2,color:p.color});c.draw('readyball'+p.i,'sphere',{x:p.x,y:.3,z:3.1,sx:.6,sy:.6,sz:.6,color:p.cool?'#bec8ba':cream});}for(const b of balls)c.draw('ball'+b.id,'sphere',{x:b.x,y:b.y,z:b.z,sx:.55,sy:.55,sz:.55,color:cream});label(c,'goals',`${goals} / 10`,0,5,-6,4);},timeout(){c.complete([0],'30초 동안 10골 미만으로 막았습니다');}};
}
function crane(c){
 c.limit=60;c.view={size:21,eye:[0,25,18],target:[0,0,0]};let arm=8,phase='idle',age=0,last=false,clawY=6;
 const decoys=Array.from({length:6},(_,i)=>({i,x:Math.cos(i*TAU/6)*4,z:Math.sin(i*TAU/6)*4,gone:false}));c.players.forEach(p=>{p.x=p.i===0?9:Math.cos(p.i*TAU/3)*3;p.z=p.i===0?0:Math.sin(p.i*TAU/3)*3;p.react=c.rand(.27,.4);});
 return{update(dt){age+=dt;for(const d of decoys)if(!d.gone){const a=.36*dt,x=d.x;d.x=x*Math.cos(a)-d.z*Math.sin(a);d.z=x*Math.sin(a)+d.z*Math.cos(a);}for(const p of c.players.slice(1)){if(!p.alive)continue;const escape=phase==='drop'&&age>p.react&&Math.abs(p.x-arm)<2?{x:p.x,z:p.z>=0?5:-5}:{x:p.x*.8,z:p.z*.8};const q=c.input(p,toward(p,escape.x,escape.z,phase==='drop'&&age>p.react?1:.15));const x=p.x,a=.36*dt;p.x=x*Math.cos(a)-p.z*Math.sin(a);p.z=x*Math.sin(a)+p.z*Math.cos(a);c.move(p,q,2.4,false);const r=Math.hypot(p.x,p.z);if(r>5.7){p.x*=5.7/r;p.z*=5.7/r;}}const targets=c.players.slice(1).filter(p=>p.alive),target=targets.sort((a,b)=>Math.abs(a.z)-Math.abs(b.z))[0];const q=c.input(c.players[0],()=>({a:phase==='idle'||phase==='move'&&!!target&&arm>target.x+.25}));if(phase==='idle'&&q.ap){phase='move';age=0;arm=8;}if(phase==='move'){arm-=dt*4;if((last&&!q.a)||arm<=-6.5){phase='drop';age=0;}}else if(phase==='drop'){clawY=Math.max(.7,6-age*9);if(age>.6){const options=[...c.players.slice(1).filter(p=>p.alive).map(p=>({p,x:p.x,z:p.z})),...decoys.filter(d=>!d.gone).map(d=>({d,x:d.x,z:d.z}))].filter(o=>Math.hypot(o.x-arm,o.z)<1.1).sort((a,b)=>Math.hypot(a.x-arm,a.z)-Math.hypot(b.x-arm,b.z));const hit=options[0];if(hit?.p){c.eliminate(hit.p);c.points(c.players[0]);}if(hit?.d)hit.d.gone=true;phase='return';age=0;}}else if(phase==='return'){clawY=Math.min(6,.7+age*7);arm+=(8-arm)*dt*3;if(age>1.2){phase='idle';arm=8;age=0;}}last=q.a;if(!c.players.slice(1).some(p=>p.alive))c.complete([0],'세 캡슐을 모두 잡았습니다');c.hint('1P A 유지로 크레인 전진/놓으면 하강 · 팀 방향으로 회전판 위 굴리기 · 회색 공은 미끼');},render(){c.arena({width:13,depth:13,shape:'cylinder',color:'#baaecd'});for(let i=0;i<8;i++){const a=i*TAU/8+c.time*.36;c.draw('line'+i,'box',{x:Math.cos(a)*3,y:.03,z:Math.sin(a)*3,sx:6,sy:.03,sz:.07,ry:-a,color:cream});}for(const p of c.players.slice(1))if(p.alive)c.draw('capsule'+p.i,'sphere',{x:p.x,y:.6,z:p.z,sx:1.7,sy:1.7,sz:1.7,color:p.color,opacity:.3});for(const d of decoys)if(!d.gone)c.draw('decoy'+d.i,'sphere',{x:d.x,y:.6,z:d.z,sx:1.5,sy:1.5,sz:1.5,color:'#91a7a6'});c.draw('rail','box',{x:1,y:6.5,z:0,sx:16,sy:.3,sz:.3,color:'#c1b89b'});c.draw('cable','cylinder',{x:arm,y:(6.5+clawY)/2,z:0,sx:.1,sy:6.5-clawY,sz:.1,color:ink});c.draw('claw','ring',{x:arm,y:clawY,z:0,sx:2,sy:2,sz:1,rx:-Math.PI/2,color:'#e4c26c'});c.draw('shadow','cylinder',{x:arm,y:.03,z:0,sx:2,sy:.03,sz:2,color:ink,opacity:.2});},timeout(){c.complete([1,2,3],'회전판에서 한 명 이상 버텼습니다');}};
}
function oars(c){
 c.limit=300;c.view={size:22,eye:[0,23,20],target:[0,0,0]};const teams=[0,1].map(t=>({base:t?5.5:-5.5,x:0,distance:0,heading:0,v:0,stun:0})),hazards=Array.from({length:24},(_,i)=>({i,x:c.rand(-3,3),at:12+i*6,type:i%4===0?'fire':'rock'}));c.players.forEach(p=>{p.phase=c.rand();p.rate=c.rand(3.8,5);});
 return{update(dt){const arrivals=[];for(let t=0;t<2;t++){const s=teams[t];s.stun=Math.max(0,s.stun-dt);const hazard=hazards.find(h=>h.at>s.distance&&h.at<s.distance+13);const desired=hazard&&Math.abs(hazard.x-s.x)<1.5?clamp(hazard.x+(s.x>=hazard.x?2:-2),-3.5,3.5):s.x;const heading=clamp((desired-s.x)*.55,-.7,.7);let left=0,right=0;for(const i of pair(t)){const p=c.players[i],q=c.input(p,()=>({a:pulse(c.time,p.rate,p.phase)&&s.heading<heading+.12,b:pulse(c.time,p.rate,p.phase)&&s.heading>heading-.12}));if(q.ap)right++;if(q.bp)left++;}if(!s.stun){s.v=Math.min(7,s.v+(left+right)*.24);s.heading=clamp(s.heading+(right-left)*.075,-1,1);s.v=Math.max(0,s.v-dt*1.1);s.x+=Math.sin(s.heading)*s.v*dt;const old=s.distance;s.distance+=Math.cos(s.heading)*s.v*dt;if(Math.abs(s.x)>4){s.x=clamp(s.x,-4,4);s.heading*=-.3;s.v*=.5;}for(const h of hazards)if(Math.abs(h.at-s.distance)<1&&Math.abs(h.x-s.x)<1.05&&(h.type!=='fire'||Math.sin(c.time*2+h.i)>0)){s.stun=.8;s.v=1;s.distance=Math.max(0,s.distance-.8);}if(s.distance>=165)arrivals.push({t,at:(165-old)/(s.v*Math.cos(s.heading)||1)});}pair(t).forEach((i,j)=>{const p=c.players[i];p.x=s.base+s.x+(j?-.45:.45);p.z=4+(j?1:-1)*.5;p.y=.2;p.score=Math.floor(s.distance);p.pose='sit';});}if(arrivals.length){const n=Math.min(...arrivals.map(s=>s.at));c.complete(arrivals.filter(s=>Math.abs(s.at-n)<1e-7).flatMap(s=>pair(s.t)),'동굴 끝에 먼저 도착');}c.hint('A 오른쪽 노/B 왼쪽 노를 반복 · 동시에 누르면 직진 · 두 사람이 함께 조향 · 기둥과 불꽃 피하기');},render(){for(let t=0;t<2;t++){const s=teams[t];c.draw('river'+t,'box',{x:s.base,y:-.2,z:0,sx:9,sy:.4,sz:21,color:'#91b3bb'});for(const h of hazards){const z=4-(h.at-s.distance)*.45;if(z< -11||z>10)continue;c.draw('hazard'+t+'_'+h.i,h.type==='fire'?'cone':'cylinder',{x:s.base+h.x,y:.8,z,sx:1.5,sy:h.type==='fire'&&Math.sin(c.time*2+h.i)>0?3:1.6,sz:1.5,color:h.type==='fire'?'#e3a564':'#a0aaa6'});}c.draw('boat'+t,'sphere',{x:s.base+s.x,y:.05,z:4,sx:1.9,sy:.6,sz:3,ry:-s.heading,color:t?'#90c4b0':'#d69fa9'});label(c,'distance'+t,`${Math.min(165,Math.floor(s.distance))}/165`,s.base,3,7,5);}},timeout(){c.complete([],'5분 안에 동굴을 통과하지 못했습니다');}};
}
function cliffs(c){
 c.limit=Infinity;c.view={size:21,eye:[0,12,27],target:[0,5,0]};let gust=false,warning=false,next=c.rand(3,5),end=0;const ropes=[0,0];c.players.forEach(p=>{p.base=(p.i<2?-5:5)+(p.i%2?1.3:-1.3);p.x=p.base;p.height=0;p.z=0;p.lag=c.rand(.1,.35);p.pace=c.rand(.8,.98);p.warningAt=0;});
 return{update(dt){if(!warning&&!gust&&c.time>=next){warning=true;c.players.forEach(p=>p.warningAt=c.time);end=c.time+1;}if(warning&&c.time>=end){warning=false;gust=true;end=c.time+c.rand(1.3,2);}if(gust&&c.time>=end){gust=false;next=c.time+c.rand(2.5,4.2);}const q=c.players.map(p=>c.input(p,()=>({z:-p.pace,a:(warning||gust)&&c.time>p.warningAt+p.lag})));for(const p of c.players){p.x=clamp(p.x+q[p.i].x*dt*1.5,p.base-1,p.base+1);if(!q[p.i].a)p.height=Math.max(0,p.height+(gust?-5.5:-q[p.i].z*2.2)*dt);}const done=[];for(let t=0;t<2;t++){const a=c.players[t*2],b=c.players[t*2+1];if(a.height-b.height>2.5)a.height=b.height+2.5;if(b.height-a.height>2.5)b.height=a.height+2.5;ropes[t]=Math.max(0,Math.min(a.height,b.height)-4);for(const p of [a,b]){p.y=p.height-ropes[t];p.pose=q[p.i].a?'idle':'climb';p.score=Math.min(40,Math.floor(p.height));}if(Math.min(a.height,b.height)>=40)done.push(...pair(t));}if(done.length)c.complete(done,'두 사람이 함께 산 정상 도착');c.hint(warning?'!! 바람 예고 · A를 눌러 바위에 붙으세요':gust?'강풍! A 유지 · 한 사람이 미끄러지면 밧줄로 연결된 동료도 내려갑니다':'위 방향으로 등반 · A로 붙잡기 · 두 사람 모두 정상까지');},render(){for(let t=0;t<2;t++){const x=t?5:-5;c.draw('cliff'+t,'box',{x,y:4,z:-1,sx:8,sy:15,sz:1.5,color:'#c1c5ba'});for(let j=0;j<20;j++)c.draw('grip'+t+j,'sphere',{x:x+Math.sin(j*5.2)*3,y:(j*.85-ropes[t]% .85),z:0,sx:.5,sy:.3,sz:.3,color:'#93a8a1'});const a=c.players[t*2],b=c.players[t*2+1],dx=b.x-a.x,dy=b.y-a.y;c.draw('rope'+t,'box',{x:(a.x+b.x)/2,y:(a.y+b.y)/2+.7,z:.2,sx:Math.hypot(dx,dy),sy:.07,sz:.07,rz:Math.atan2(dy,dx),color:'#dec48d'});}if(warning||gust)label(c,'wind',gust?'≋ ≋ ≋':'!!',0,10,1,8);}};
}
function sailing(c){
 c.limit=45;c.view={size:24,eye:[0,17,25],target:[0,2,0]};const teams=[0,1].map(t=>({base:t?6:-6,x:0,height:2,speed:6,distance:0,stun:0,score:0})),coins=Array.from({length:100},(_,i)=>({i,x:c.rand(-3,3),height:c.rand(.8,6),at:12+i*3,taken:[false,false]})),crates=Array.from({length:18},(_,i)=>({i,x:c.rand(-3,3),at:24+i*14}));
 return{update(dt){for(let t=0;t<2;t++){const s=teams[t],driver=c.players[t*2],flyer=c.players[t*2+1];s.stun=Math.max(0,s.stun-dt);const nextCoin=coins.find(o=>!o.taken[t]&&o.at>s.distance&&o.at<s.distance+20),crate=crates.find(o=>o.at>s.distance&&o.at<s.distance+12),targetX=crate&&Math.abs(s.x-crate.x)<1.2?clamp(crate.x+(s.x>=crate.x?2:-2),-3.5,3.5):nextCoin?.x||0;const q=c.input(driver,()=>({x:clamp((targetX-s.x)*2,-1,1),a:!!nextCoin&&s.height<nextCoin.height-.2,b:!!nextCoin&&s.height>nextCoin.height+.2})),r=c.input(flyer,()=>({x:nextCoin?clamp((s.base+nextCoin.x-flyer.x)*2,-1,1):0}));if(!s.stun){s.x=clamp(s.x+q.x*3*dt,-3.6,3.6);s.speed=clamp(s.speed+((q.a?1:0)-(q.b?1:0))*dt*4,3,10);s.height+=(Math.max(.5,s.speed-3)-s.height)*dt*2;}else{s.speed=3;s.height=Math.max(.5,s.height-dt*6);}s.distance+=s.speed*dt;driver.x=s.base+s.x;driver.y=0;driver.z=0;flyer.x=clamp((Number.isFinite(flyer.sailX)?flyer.sailX:s.base)+r.x*4*dt,s.base-4,s.base+4);flyer.sailX=flyer.x;flyer.y=s.height;flyer.z=3+clamp(r.z,-1,1);for(const o of crates)if(Math.abs(o.at-s.distance)<.6&&Math.abs(o.x-s.x)<1){s.stun=1.3;s.distance+=.8;}for(const o of coins)if(!o.taken[t]&&Math.abs(o.at-s.distance+3)<1&&Math.hypot(o.x+s.base-flyer.x,o.height-flyer.y)<.9){o.taken[t]=true;s.score++;}driver.score=flyer.score=s.score;driver.pose='sit';flyer.pose='glide';}c.hint('조종사 방향 이동/A 가속/B 감속 · 속도가 높을수록 낙하산 상승 · 낙하산 선수 방향으로 코인 조준');},render(){for(let t=0;t<2;t++){const s=teams[t],driver=c.players[t*2],flyer=c.players[t*2+1];c.draw('water'+t,'box',{x:s.base,y:-.25,z:0,sx:10,sy:.5,sz:22,color:'#85bfc8'});c.draw('boat'+t,'sphere',{x:driver.x,y:0,z:0,sx:1.8,sy:.6,sz:3,color:driver.color});c.draw('sail'+t,'sphere',{x:flyer.x,y:flyer.y+2,z:flyer.z,sx:3,sy:.6,sz:2,color:flyer.color});for(const o of coins){const z=-(o.at-s.distance);if(o.taken[t]||z< -12||z>12)continue;c.draw('coin'+t+'_'+o.i,'cylinder',{x:s.base+o.x,y:o.height,z,sx:.6,sy:.15,sz:.6,color:'#e9c86d'});}for(const o of crates){const z=-(o.at-s.distance);if(z< -12||z>12)continue;c.draw('crate'+t+'_'+o.i,'box',{x:s.base+o.x,y:.5,z,sx:1.5,sy:1,sz:1.5,color:'#c8aa82'});}}},timeout(){c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'낙하산으로 모은 코인 보관');}};
}
function fishing(c){
 c.limit=Infinity;const bite=c.rand(3,8);c.players.forEach(p=>{p.x=(p.i-1.5)*3.5;p.z=2;p.response=null;p.lag=c.rand(.17,.43);p.false=false;});return{update(){for(const p of c.players){const q=c.input(p,{a:c.time>=bite+p.lag});if(q.ap&&p.response===null){p.response=c.time-bite;p.false=p.response<0;p.score=p.false?0:Math.max(0,Math.round((1.5-p.response)*100));}}if(c.players.every(p=>p.response!==null)||c.time>=bite+1.5){const valid=c.players.filter(p=>p.response!==null&&!p.false&&p.response<=1.5);if(!valid.length)c.complete([],'입질 전에 당겼거나 너무 늦었습니다');else{const best=Math.min(...valid.map(p=>p.response));c.complete(valid.filter(p=>Math.abs(p.response-best)<1e-7).map(p=>p.i),'입질 뒤 가장 빠르게 낚아챘습니다');}}c.hint(c.time<bite?'기다리세요 · 입질 표시 !! 뒤에 A 한 번':'!! 지금 A로 낚싯대를 당기세요');},render(){c.arena({width:18,depth:13,color:'#92c0c5'});for(const p of c.players){c.draw('dock'+p.i,'box',{x:p.x,y:-.2,z:3,sx:3,sy:.4,sz:6,color:'#c9b18b'});c.draw('rod'+p.i,'cylinder',{x:p.x,y:1.3,z:.7,sx:.07,sy:3,sz:.07,rx:-.7,color:'#836c55'});c.draw('float'+p.i,'sphere',{x:p.x,y:c.time>=bite?.08:.25,z:-2,sx:.3,sy:.4,sz:.3,color:p.color});if(p.false)label(c,'early'+p.i,'실격',p.x,3,0,3);else if(c.time>=bite&&p.response===null)label(c,'bite'+p.i,'!!',p.x,3,0,3);else if(p.response!==null&&!p.false)c.draw('catch'+p.i,'sphere',{x:p.x,y:1,z:-1,sx:.5+p.score*.013,sy:.5,sz:.7,color:p.color});}}};
}
function bop(c){
 c.limit=60;c.activePlayers=[0,1];c.view={size:20,eye:[0,22,16],target:[0,0,0]};const holes=Array.from({length:12},(_,i)=>({i,x:(i%4-1.5)*3,z:(Math.floor(i/4)-1)*3,show:0,value:1}));let next=.5;c.players.forEach(p=>{p.visible=p.i<2;p.x=p.i?-5:5;p.z=4;p.cool=0;});return{update(dt){if(c.time>=next){next=c.time+c.rand(.3,.6);const h=c.pick(holes.filter(h=>!h.show));if(h){h.show=c.rand(.8,1.6);h.value=c.rand()<.3?2:1;}}for(const h of holes)h.show=Math.max(0,h.show-dt);const hits=[];for(const p of c.players.slice(0,2)){p.cool=Math.max(0,p.cool-dt);const target=holes.filter(h=>h.show).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...target?toward(p,target.x,target.z):{},a:!!target&&dist(p,target)<1.3&&p.cool===0}));c.move(p,q,5.8);if(q.ap&&!p.cool){p.cool=.3;p.pose='hit';const h=holes.filter(h=>h.show&&dist(p,h)<1.35).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(h)hits.push({p,h,d:dist(p,h)});}}for(const h of holes){const possible=hits.filter(v=>v.h===h);if(possible.length){const min=Math.min(...possible.map(v=>v.d));possible.filter(v=>Math.abs(v.d-min)<1e-7).forEach(v=>c.points(v.p,h.value));h.show=0;}}c.hint('방향으로 이동/A 망치 · 작은 새 1점/큰 새 2점 · 1P 대 2P');},render(){c.arena({width:16,depth:12,color:'#bea792'});for(const h of holes){c.draw('hole'+h.i,'cylinder',{x:h.x,y:.03,z:h.z,sx:1.6,sy:.05,sz:1.6,color:'#726b65'});if(h.show){c.draw('head'+h.i,'sphere',{x:h.x,y:.4,z:h.z,sx:h.value===2?1.4:1,sy:h.value===2?1.3:.8,sz:1,color:h.value===2?'#b78cad':'#d3b682'});label(c,'value'+h.i,String(h.value),h.x,1.8,h.z,2.6);}}},timeout(){const a=c.players[0],b=c.players[1];c.complete(a.score===b.score?[]:[a.score>b.score?0:1],'60초 망치 점수');}};
}
export const games={"Makin' Waves":waves,"Fish n' Drips":drips,'Money Belts':belts,'GOOOOOOOAL!!':goal,'Blame It on the Crane':crane,'Right Oar Left?':oars,'Cliffhangers':cliffs,'Pair-a-sailing':sailing,'Rumble Fishing':fishing,'Bowser Bop':bop};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(n=>[n,['mp4']]));
const own='새 플라밍고 모델·코스·물리값으로 재구성했습니다. ';
export const notes={
"Makin' Waves":own+'팀의 A 점프→공중 A 내려찍기가 파도를 만듭니다. 1P는 이동해 흔들리는 뗏목의 균형을 잡고 30초 버텨야 합니다.',
"Fish n' Drips":own+'1P는 6개 순서 입력, 팀은 한 사람씩 넘겨 물을 채웁니다. 원작 L/R은 좌우 방향으로 배치했습니다. 8통 용량은 브라우저판 값이며 60초 안에 완성이 목표입니다.',
'Money Belts':own+'위 벨트 1P와 아래 벨트 팀이 코인을 모읍니다. 과자는 길을 막고 떨어지면 상자로 돌아옵니다. 30초 후 각 팀이 모은 코인을 유지합니다.',
'GOOOOOOOAL!!':own+'골키퍼는 방향/A 점프, 팀은 조준/A 누르기 후 놓기로 슛합니다. 공끼리 충돌하고 30초 안에 10골이면 팀 승리입니다.',
'Blame It on the Crane':own+'MP4 조작 A 유지 전진/놓기 하강입니다. 팀은 반시계 회전판 위에서 굴러 피하고 6개 미끼 공이 함께 있습니다. 60초 내 세 선수 포획이 목표입니다.',
'Right Oar Left?':own+'A 오른쪽 노/B 왼쪽 노를 반복합니다. 두 사람이 같은 배의 방향과 추진력을 결정합니다. 새 동굴의 기둥·불꽃을 피해 300초 안에 결승점을 통과하세요.',
'Cliffhangers':own+'방향 등반/A 고정이며 진동 예고를 !! 표시로 대체했습니다. 바람에 놓치면 밀리고 밧줄 길이로 동료의 높이도 제한됩니다. 두 사람 모두 정상에 도착해야 합니다.',
'Pair-a-sailing':own+'조종사의 A 가속/B 감속으로 낙하산 높이가 바뀝니다. 다른 선수는 공중에서 방향으로 코인을 모읍니다. 상자 충돌은 정지·추락이며 45초 획득 코인은 팀이 공유합니다.',
'Rumble Fishing':own+'진동을 !! 표시로 바꿨습니다. A를 일찍 누르면 실격, 입질 후 빨리 누를수록 큰 물고기입니다. 원작 응답창 길이가 확인되지 않아 브라우저판은 1.5초로 정했습니다.',
'Bowser Bop':own+'두 선수만 60초 동안 점수를 겨룹니다. 방향으로 이동/A 망치이며 작은 새 머리는 1점, 큰 머리는 2점입니다.'};
