import{clamp,dist,toward}from'../core.js';
const TAU=Math.PI*2,ink='#375763',cream='#f1e8ce',teams=[[0,1],[2,3]],team=p=>Math.floor(p.i/2);
const text=(c,id,s,x,y,z,w=4)=>c.draw(id,'text',{x,y,z,sx:w,sy:w/4,text:s,color:ink});
const teamScore=(c,t,n=1)=>teams[t].forEach(i=>c.points(c.players[i],n));
const oneThree=(c)=>{if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'세 선수를 모두 잡았습니다');};
function power(c){
 c.limit=30;c.view={size:22,eye:[0,24,20],target:[0,0,0]};const holes=[[-6,-4],[-6,4],[6,-4],[6,4]];c.players.forEach(p=>{p.x=p.i?(p.i-2)*3:0;p.z=p.i?4:0;});let angle=0;
 return{update(dt){const p=c.players[0],target=c.players.slice(1).filter(p=>p.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0],a=target?Math.atan2(target.z-p.z,target.x-p.x):angle,d=Math.atan2(Math.sin(a-angle),Math.cos(a-angle)),q=c.input(p,{x:clamp(d*1.7,-1,1)});angle+=q.x*2*dt;p.x=clamp(p.x+Math.cos(angle)*4.5*dt,-8,8);p.z=clamp(p.z+Math.sin(angle)*4.5*dt,-6,6);p.y=.35;p.rotation=-angle;p.pose='sit';for(const o of c.players.slice(1)){if(!o.alive)continue;const goals=Array.from({length:12},(_,i)=>({x:clamp(o.x+Math.cos(i*TAU/12)*2,-7,7),z:clamp(o.z+Math.sin(i*TAU/12)*2,-5,5)})).filter(v=>holes.every(([x,z])=>Math.abs(v.x-x)>1.3||Math.abs(v.z-z)>1.3)),goal=goals.sort((a,b)=>dist(b,p)-dist(a,p))[0]||{x:0,z:0},v=c.input(o,()=>({...toward(o,goal.x,goal.z),a:o.y===0&&(dist(o,p)<3.4||holes.some(([x,z])=>Math.abs(o.x-x)<1.5&&Math.abs(o.z-z)<1.5))}));c.move(o,v,4.7,false);c.jump(o,v,8);if(Math.abs(o.x)>8.5||Math.abs(o.z)>6.5||!o.y&&holes.some(([x,z])=>Math.abs(o.x-x)<1&&Math.abs(o.z-z)<1)||dist(o,p)<1.4&&o.y<.8)c.eliminate(o);}oneThree(c);c.hint('1P 좌우로 UFO 회전: 자동 전진 · 2–4P 방향 이동/A 점프 · 전기 UFO와 발판의 구멍을 피하세요');},render(){c.arena({width:18,depth:14,color:'#b9c4ad'});for(const[x,z]of holes)c.draw('hole'+x+z,'box',{x,y:.02,z,sx:2,sy:.03,sz:2,color:'#4b5961'});const p=c.players[0];c.draw('ufo','sphere',{x:p.x,y:.45,z:p.z,sx:2.5,sy:.6,sz:2.5,color:'#daae78'});c.draw('electric','ring',{x:p.x,y:.55,z:p.z,sx:2.9,sy:2.9,sz:1,rx:-Math.PI/2,color:'#e2e78c',glow:true});},timeout(){c.complete([1,2,3],'30초 동안 팀이 생존했습니다');}};
}
function bombs(c){
 c.limit=30;c.view={size:22,eye:[0,10,28],target:[0,6,0]};const pegs=Array.from({length:35},(_,i)=>({x:(i%7-3)*2+(Math.floor(i/7)%2?.8:0),y:3+Math.floor(i/7)*1.8})),balls=[];let id=0;c.players.forEach(p=>{p.x=p.i?(p.i-2)*4:0;p.y=p.i?13:0;p.z=0;p.cool=c.rand(.3,1.2);});
 return{update(dt){const solo=c.players[0],threat=balls.filter(b=>!b.dead&&b.y<4).sort((a,b)=>a.y-b.y)[0],safe=Array.from({length:17},(_,i)=>i-8).sort((a,b)=>Math.min(...balls.filter(v=>!v.dead&&v.y<4).map(v=>Math.abs(b-v.x)),9)-Math.min(...balls.filter(v=>!v.dead&&v.y<4).map(v=>Math.abs(a-v.x)),9))[0],q=c.input(solo,{x:threat?clamp((safe-solo.x)*2,-1,1):0});solo.x=clamp(solo.x+q.x*6*dt,-8,8);for(const p of c.players.slice(1)){p.cool-=dt;const v=c.input(p,{x:clamp((solo.x+(p.i-2)*1.5-p.x)*.8,-1,1),a:p.cool<=0&&Math.floor(c.time*5+p.i)%2===0});p.x=clamp(p.x+v.x*4*dt,-8,8);if(v.ap&&p.cool<=0){p.cool=1.1;balls.push({id:id++,x:p.x,y:12.5,vx:0,vy:0,age:0,peg:new Set()});}}for(const b of balls){if(b.dead)continue;b.age+=dt;b.vy-=7*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(Math.abs(b.x)>8){b.x=clamp(b.x,-8,8);b.vx*=-.7;}for(let i=0;i<pegs.length;i++){const v=pegs[i];if(!b.peg.has(i)&&Math.hypot(v.x-b.x,v.y-b.y)<.55){b.peg.add(i);b.vx=(b.x>v.x?1:b.x<v.x?-1:c.pick([-1,1]))*c.rand(1.5,3);b.vy=-Math.max(1,Math.abs(b.vy)*.4);b.y=v.y-.6;}}if(b.y<.6||b.age>6){b.dead=true;b.explode=c.time;if(Math.abs(b.x-solo.x)<1.25)c.complete([1,2,3],'핀 사이로 떨어진 폭탄 명중');}}c.hint('1P 좌우 회피 · 2–4P 좌우 이동/A 폭탄 투하 · 핀에 튕기는 경로를 읽으세요');},render(){c.draw('wall','box',{x:0,y:6,z:-1,sx:18,sy:14,sz:.4,color:'#b0c6c0'});for(let i=0;i<pegs.length;i++){const v=pegs[i];c.draw('peg'+i,'sphere',{x:v.x,y:v.y,z:.1,sx:.45,sy:.45,sz:.6,color:cream});}for(const b of balls)if(!b.dead||c.time-b.explode<.3)c.draw('bomb'+b.id,'sphere',{x:b.x,y:Math.max(.4,b.y),z:.2,sx:b.dead?2:.7,sy:b.dead?2:.7,sz:.7,color:b.dead?'#efb365':'#747b91'});},timeout(){c.complete([0],'30초 동안 폭탄을 피했습니다');}};
}
function skies(c){
 c.limit=30;c.view={size:24,eye:[0,10,30],target:[0,6,0]};const bullets=[];let id=0;c.players.forEach(p=>{p.x=(p.i-1.5)*3;p.y=p.i?6:2;p.z=p.i?0:7;p.targets=[true,true];p.cool=0;});
 return{update(dt){const shooter=c.players[0],target=c.players.slice(1).find(p=>p.alive),side=target?.targets[0]?-1:1,q=c.input(shooter,{x:target?clamp((target.x+side*1.2-shooter.x)*1.5,-1,1):0,z:target?clamp((shooter.y-target.y)*1.5,-1,1):0,a:!!target});shooter.x=clamp(shooter.x+q.x*5*dt,-9,9);shooter.y=clamp(shooter.y-q.z*5*dt,1,11);shooter.cool-=dt;if((q.a||q.b)&&shooter.cool<=0){shooter.cool=.3;bullets.push({id:id++,x:shooter.x,y:shooter.y,age:0});}for(const p of c.players.slice(1)){if(!p.alive)continue;const t=c.time+p.i*2,v=c.input(p,{x:Math.cos(t*.8),z:Math.sin(t*.63)});p.x=clamp(p.x+v.x*3.8*dt,-8,8);p.y=clamp(p.y-v.z*3.8*dt,1.5,10);}for(const b of bullets){if(b.dead)continue;b.age+=dt;if(b.age>=.45){b.dead=true;for(const p of c.players.slice(1)){if(!p.alive)continue;for(let i=0;i<2;i++)if(p.targets[i]&&Math.hypot(b.x-p.x-(i?1.2:-1.2),b.y-p.y)<.7)p.targets[i]=false;if(p.targets.every(v=>!v))c.eliminate(p);}}}oneThree(c);c.hint('모두 방향으로 비행 · 1P A/B 발사 · 세 비행기의 양쪽 날개 표적을 모두 맞히세요');},render(){c.draw('sky','box',{x:0,y:6,z:-2,sx:22,sy:14,sz:.3,color:'#a8d1d4'});for(const p of c.players)if(p.alive){c.draw('wing'+p.i,'box',{x:p.x,y:p.y-.1,z:p.z,sx:3.3,sy:.15,sz:1,color:p.color});if(p.i)for(let i=0;i<2;i++)if(p.targets[i])c.draw('target'+p.i+'_'+i,'sphere',{x:p.x+(i?1.2:-1.2),y:p.y,z:.2,sx:.7,sy:.7,sz:.7,color:'#eed489'});}for(const b of bullets)if(!b.dead)c.draw('bullet'+b.id,'sphere',{x:b.x,y:b.y,z:7*(1-b.age/.45),sx:.25,sy:.25,sz:.4,color:cream});},timeout(){c.complete([1,2,3],'팀 비행기가 30초 생존했습니다');}};
}
function picture(c){
 c.limit=Infinity;c.view={size:28,eye:[0,32,13],target:[0,0,0]};let round=0,deadline=0,wait=0,shape=0;const scores=[0,0],panels=[[],[]],sizes=[2,3],origin=[-7,7];const fresh=()=>{round++;if(round>5){c.complete([],'5라운드 동안 3장 완성한 편이 없습니다');return;}shape=c.int(0,5);deadline=c.time+20;for(let t=0;t<2;t++)panels[t]=Array.from({length:sizes[t]**2},(_,i)=>({i,turn:c.int(0,3),moving:true,clock:c.rand(0,.65),valid:validTurns(t,i)}));};const pigment=(x,z)=>{if(shape===0)return Math.hypot(x+.15,z+.1)<.5||Math.abs(x-.25)<.12&&z<.55||Math.hypot(x-.3,z+.6)<.22;if(shape===1)return Math.hypot(x,z)<.55||Math.abs(x)<.08&&z>.4;if(shape===2)return Math.hypot(x/.8,z/.5)<1&&x+z>.1;if(shape===3)return Math.hypot(x,z)<.5||Math.abs(x)<.12||Math.abs(z)<.12;if(shape===4)return Math.hypot(x/.6,z/.35)<1||x<-.4&&Math.abs(z)<(-x-.3);return (x*x/.3+(z+.05)**2/.65)<1;};const validTurns=(t,index)=>{const n=sizes[t],col=index%n,row=Math.floor(index/n),mask=(x,z)=>pigment((col+(x+.5)/7)/n*2-1,(row+(z+.5)/7)/n*2-1);return[0,1,2,3].filter(turn=>{for(let z=0;z<7;z++)for(let x=0;x<7;x++){let xx=x,zz=z;for(let j=0;j<turn;j++){const old=xx;xx=6-zz;zz=old;}if(mask(x,z)!==mask(xx,zz))return false;}return true;});};c.players.forEach(p=>{p.board=p.i?1:0;p.cursor=0;p.cx=origin[p.board]-2;p.cz=-2;p.x=origin[p.board]+(p.i>0?(p.i-2)*2:0);p.z=5;p.scale=.7;p.repeat=0;});fresh();
 return{update(dt){if(wait){if(c.time>=wait){wait=0;fresh();}return;}for(let t=0;t<2;t++)for(const a of panels[t])if(a.moving){a.clock+=dt;if(a.clock>.65){a.clock-=.65;a.turn=(a.turn+1)%4;}}for(const p of c.players){const t=p.board,n=sizes[t],targets=panels[t].filter(a=>a.moving||!a.valid.includes(a.turn)),target=targets[(p.i? p.i-1:0)%Math.max(1,targets.length)],tx=target?origin[t]+(target.i%n-(n-1)/2)*2.4:origin[t],tz=target?(Math.floor(target.i/n)-(n-1)/2)*2.4:0,q=c.input(p,()=>({x:clamp((tx-p.cx)*3,-1,1),z:clamp((tz-p.cz)*3,-1,1),a:!!target&&Math.hypot(tx-p.cx,tz-p.cz)<.6&&(target.moving?target.valid.includes(target.turn)&&target.clock<.45:true)}));if(p.i===0&&q.pointer.worldValid){p.cx=clamp(q.pointer.worldX,origin[t]-n*1.2,origin[t]+n*1.2);p.cz=clamp(q.pointer.worldZ,-n*1.2,n*1.2);}else{p.cx=clamp(p.cx+q.x*7*dt,origin[t]-n*1.2,origin[t]+n*1.2);p.cz=clamp(p.cz+q.z*7*dt,-n*1.2,n*1.2);}const x=clamp(Math.floor((p.cx-origin[t])/2.4+n/2),0,n-1),z=clamp(Math.floor(p.cz/2.4+n/2),0,n-1);p.cursor=z*n+x;if(q.ap||q.bp||q.pointer.pressed)panels[t][p.cursor].moving=!panels[t][p.cursor].moving;}const won=[0,1].filter(t=>panels[t].every(a=>!a.moving&&a.valid.includes(a.turn)));if(won.length||c.time>=deadline){won.forEach(t=>scores[t]++);c.players[0].score=scores[0];c.players.slice(1).forEach(p=>p.score=scores[1]);const winners=[...(scores[0]>=3?[0]:[]),...(scores[1]>=3?[1,2,3]:[])];if(winners.length)c.complete(winners,'그림 세 장을 먼저 맞췄습니다');else wait=c.time+1.2;}c.hint(`방향 또는 1P 포인터 조준/A·B 회전 정지·재시작 · 1P 4조각, 팀 9조각 · ${round}/5라운드 ${Math.max(0,Math.ceil(deadline-c.time))}초`);},render(){for(let t=0;t<2;t++){const n=sizes[t];for(const a of panels[t]){const col=a.i%n,row=Math.floor(a.i/n),x=origin[t]+(col-(n-1)/2)*2.4,z=(row-(n-1)/2)*2.4,angle=a.turn*Math.PI/2;c.draw('tile'+t+'_'+a.i,'box',{x,y:-.12,z,sx:2.34,sy:.2,sz:2.34,color:cream});for(let j=0;j<7;j++)for(let i=0;i<7;i++){const xx=(i-3)*.31,zz=(j-3)*.31,px=x+xx*Math.cos(angle)-zz*Math.sin(angle),pz=z+xx*Math.sin(angle)+zz*Math.cos(angle),gx=(col+(i+.5)/7)/n*2-1,gz=(row+(j+.5)/7)/n*2-1;if(pigment(gx,gz))c.draw('pixel'+t+'_'+a.i+'_'+j+'_'+i,'box',{x:px,y:.03,z:pz,sx:.31,sy:.05,sz:.31,color:['#ef9eab','#e2bb65','#9eaece','#d6ac74','#86bfc0','#aa9bbb'][shape]});}if(a.moving)c.draw('turn'+t+'_'+a.i,'sphere',{x:x+1,y:.2,z:z+1,sx:.18,sy:.18,sz:.18,color:'#a3bb98'});}}for(let j=0;j<10;j++)for(let i=0;i<10;i++)if(pigment((i+.5)/5-1,(j+.5)/5-1))c.draw('sample'+j+'_'+i,'box',{x:(i-4.5)*.24,y:.03,z:(j-4.5)*.24,sx:.24,sy:.08,sz:.24,color:'#cb8b98'});for(const p of c.players)c.draw('cursor'+p.i,'ring',{x:p.cx,y:.2,z:p.cz,sx:.6,sy:.6,sz:1,rx:-Math.PI/2,color:p.color});text(c,'round',`${round}/5`,0,.5,4,3);}};
}
function snow(c){
 c.limit=30;c.view={size:22,eye:[0,24,20],target:[0,0,0]};const patches=[],shots=[];let id=0;const solo=c.players[0];solo.x=0;solo.z=9;solo.aim={x:0,z:0};solo.cool=0;c.players.slice(1).forEach(p=>{p.x=(p.i-2)*3;p.z=0;p.vx=0;p.vz=0;p.frozen=0;});
 return{update(dt){solo.cool-=dt;const target=c.players.slice(1).filter(p=>p.alive).sort((a,b)=>Math.abs(b.x)-Math.abs(a.x))[0],v=c.input(solo,{x:target?clamp((target.x+target.vx*.25-solo.aim.x)*2,-1,1):0,z:target?clamp((target.z+target.vz*.25-solo.aim.z)*2,-1,1):0,a:solo.cool<=0});if(v.pointer.worldValid){solo.aim.x=clamp(v.pointer.worldX,-8,8);solo.aim.z=clamp(v.pointer.worldZ,-5,5);}else{solo.aim.x=clamp(solo.aim.x+v.x*9*dt,-8,8);solo.aim.z=clamp(solo.aim.z+v.z*9*dt,-5,5);}if((v.ap||v.bp||v.pointer.pressed)&&solo.cool<=0){solo.cool=.65;shots.push({id:id++,x:solo.aim.x,z:solo.aim.z,age:0});}for(const s of shots){if(s.dead)continue;s.age+=dt;if(s.age>=.4){s.dead=true;patches.push({id:s.id,x:s.x,z:s.z});for(const p of c.players.slice(1))if(p.alive&&dist(p,s)<1.15&&p.y<1.3){p.frozen=1.4;p.vx=(p.x>=0?1:-1)*5;p.vz=p.z*.3;}}}for(const p of c.players.slice(1)){if(!p.alive)continue;p.frozen=Math.max(0,p.frozen-dt);const threat=shots.filter(s=>!s.dead).sort((a,b)=>dist(p,a)-dist(p,b))[0],goal=threat&&dist(p,threat)<2?{x:clamp(p.x+(p.x>=threat.x?2:-2),-5.5,5.5),z:clamp(p.z+(p.z>=threat.z?2:-2),-3,3)}:{x:p.x*.4,z:p.z*.4},q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:!!threat&&dist(p,threat)<1.6&&p.y===0})),ice=patches.some(a=>dist(p,a)<1.4);if(!p.frozen){p.vx+=q.x*14*dt;p.vz+=q.z*14*dt;}p.vx*=Math.exp(-dt*(ice?1:5));p.vz*=Math.exp(-dt*(ice?1:5));p.x+=p.vx*dt;p.z+=p.vz*dt;if(!p.frozen)c.jump(p,q,8);for(const o of c.players.slice(1))if(o!==p&&o.alive&&p.vy<0&&p.y-o.y>.6&&p.y-o.y<1.1&&dist(p,o)<.55)o.frozen=.5;if(Math.abs(p.x)>7.8||Math.abs(p.z)>4.8)c.eliminate(p);}oneThree(c);c.hint('1P 방향·포인터 조준/A·B 눈덩이 · 2–4P 이동/A 점프 · 얼음에 미끄러져 지붕에서 떨어지면 탈락');},render(){c.arena({width:16,depth:10,color:'#b8c4c7'});for(const a of patches)c.draw('ice'+a.id,'cylinder',{x:a.x,y:.025,z:a.z,sx:2.8,sy:.05,sz:2.8,color:'#dbeaf0'});c.draw('aim','ring',{x:solo.aim.x,y:.09,z:solo.aim.z,sx:1,sy:1,sz:1,rx:-Math.PI/2,color:solo.color});for(const s of shots)if(!s.dead)c.draw('snow'+s.id,'sphere',{x:s.x,y:5*(1-s.age/.4),z:s.z,sx:.7,sy:.7,sz:.7,color:cream});for(const p of c.players.slice(1))if(p.frozen)c.draw('frozen'+p.i,'box',{x:p.x,y:.7,z:p.z,sx:1.1,sy:1.5,sz:1.1,color:'#b7dfe9',opacity:.5});},timeout(){c.complete([1,2,3],'팀이 30초 동안 지붕 위에서 생존');}};
}
function thrash(c){
 c.limit=30;c.view={size:24,eye:[0,25,22],target:[0,0,0]};const traps=Array.from({length:22},(_,i)=>({id:i,at:9+i*5,x:c.pick([-6,-3,0,3,6]),kind:i%5,active:i%5===0||i%5===4,age:0,used:false}));const solo=c.players[0];solo.x=0;solo.z=10;solo.aim={x:0,z:0};c.players.slice(1).forEach(p=>{p.x=(p.i-2)*4;p.z=3;p.pose='balance';});
 return{update(dt){const progress=c.time*4;for(const t of traps){t.z=5-(t.at-progress);if(t.active)t.age+=dt;if(t.active&&(t.kind===2||t.kind===3)){if(!t.started){t.startX=t.x<0?-8:8;t.x=t.startX;t.started=true;}t.x+=(t.startX<0?1:-1)*(t.kind===3?9:5)*dt;}}const available=traps.filter(t=>!t.active&&t.z>-5&&t.z<5),target=available.sort((a,b)=>Math.min(...c.players.slice(1).filter(p=>p.alive).map(p=>dist(p,a)))-Math.min(...c.players.slice(1).filter(p=>p.alive).map(p=>dist(p,b))))[0],q=c.input(solo,{x:target?clamp((target.x-solo.aim.x)*2,-1,1):0,z:target?clamp((target.z-solo.aim.z)*2,-1,1):0,a:!!target&&dist(solo.aim,target)<.8});if(q.pointer.worldValid){solo.aim.x=q.pointer.worldX;solo.aim.z=q.pointer.worldZ;}else{solo.aim.x=clamp(solo.aim.x+q.x*10*dt,-9,9);solo.aim.z=clamp(solo.aim.z+q.z*10*dt,-10,10);}if(q.ap||q.bp||q.pointer.pressed){const t=traps.find(t=>!t.active&&dist(t,solo.aim)<1.2);if(t)t.active=true;}for(const p of c.players.slice(1)){if(!p.alive)continue;const near=traps.filter(t=>t.active&&!t.used&&Math.abs(t.z-p.z)<4),goals=Array.from({length:9},(_,i)=>({x:i*1.7-6.8,z:clamp(p.z,-2,6)})),goal=goals.sort((a,b)=>Math.min(...near.map(t=>dist(b,t)),20)-Math.min(...near.map(t=>dist(a,t)),20))[0],v=c.input(p,toward(p,goal.x,goal.z));p.x=clamp(p.x+v.x*5*dt,-7.5,7.5);p.z=clamp(p.z+v.z*4*dt,-3,7);for(const t of traps)if(t.active&&!t.used&&(t.kind!==1||t.age>.3)&&Math.abs(t.z-p.z)<.85&&Math.abs(t.x-p.x)<(t.kind===0||t.kind===1?1.6:1)){c.eliminate(p);if(t.kind===2)t.used=true;}}oneThree(c);c.hint('1P 방향·포인터로 장치 조준/A·B 작동 · 팀은 방향 이동 · 통·발사관·바퀴와 고정 벽을 피하세요');},render(){c.arena({width:17,depth:26,color:'#ccbda2'});for(const t of traps){if(!Number.isFinite(t.z)||Math.abs(t.z)>14||t.used)continue;const color=t.active?'#bd8c86':'#9baeba';c.draw('trap'+t.id,t.kind===2?'sphere':t.kind===3?'cylinder':'box',{x:t.x,y:.6,z:t.z,sx:t.kind===0||t.kind===1?3:1.6,sy:1.3,sz:1.4,color});if(!t.active)c.draw('activate'+t.id,'ring',{x:t.x,y:1.5,z:t.z,sx:1.5,sy:1.5,sz:1,rx:-Math.PI/2,color:'#e5c65d'});}for(const p of c.players.slice(1))if(p.alive)c.draw('board'+p.i,'box',{x:p.x,y:.05,z:p.z,sx:.65,sy:.15,sz:1.8,color:p.color});c.draw('aim','ring',{x:solo.aim.x,y:.2,z:solo.aim.z,sx:1,sy:1,sz:1,rx:-Math.PI/2,color:solo.color});},timeout(){c.complete([1,2,3],'팀이 30초 코스를 생존');}};
}
function rope(c){
 c.limit=15;c.view={size:20,eye:[0,16,24],target:[0,2,0]};let angle=0,speed=3,oldAxis=null;c.players.forEach(p=>{p.x=p.i?(p.i-2)*3:-7;p.z=0;});
 return{update(dt){const solo=c.players[0],q=c.input(solo,{x:Math.sin(c.time*2.5),z:Math.cos(c.time*2.5),a:Math.floor(c.time*3)%2===0});let rotation=0;if(Math.hypot(q.x,q.z)>.4){const a=Math.atan2(q.z,q.x);if(oldAxis!==null)rotation=Math.abs(Math.atan2(Math.sin(a-oldAxis),Math.cos(a-oldAxis)));oldAxis=a;}else oldAxis=null;speed=clamp(speed+rotation*1.2+(q.ap?1:0)-dt*.8,1.4,8);const old=angle;angle+=speed*dt;for(const p of c.players.slice(1)){if(!p.alive)continue;const remaining=((Math.PI-angle%TAU)+TAU)%TAU/speed,v=c.input(p,()=>({a:remaining<.28&&p.y===0}));c.jump(p,v,8);if(Math.floor((old+Math.PI)/TAU)!==Math.floor((angle+Math.PI)/TAU)&&p.y<.6)c.eliminate(p);}oneThree(c);c.hint('1P 방향을 원으로 돌리거나 A를 눌러 줄 가속 · 팀은 A 점프 · 15초 동안 줄을 피하세요');},render(){c.arena({width:18,depth:9,color:'#bfd0ad'});for(let i=0;i<36;i++){const x=-7+i*.4,t=Math.sin(i/35*Math.PI);c.draw('rope'+i,'sphere',{x,y:1.8+Math.cos(angle)*t*1.8,z:Math.sin(angle)*t*2.3,sx:.18,sy:.18,sz:.18,color:'#cda579'});}text(c,'speed',`${speed.toFixed(1)} RAD/S`,0,.5,-4,5);},timeout(){c.complete([1,2,3],'15초 줄넘기 생존');}};
}
function gridiron(c){
 c.limit=300;c.view={size:22,eye:[0,25,20],target:[0,0,0]};c.bounds={x:8,z:6};const balls=[];let id=0;const spawn=()=>balls.push({id:id++,x:c.rand(-6,6),z:0,vx:c.rand(-3,3),vz:c.pick([-1,1])*3,owner:null,lock:0});spawn();spawn();c.players.forEach(p=>{p.x=p.i%2?4:-4;p.z=team(p)?3:-3;p.stun=0;p.cool=0;});const drop=p=>{const b=balls.find(b=>!b.dead&&b.owner===p.i);if(b){b.owner=null;b.x=p.x;b.z=p.z;b.vx=c.rand(-3,3);b.vz=c.rand(-3,3);b.lock=.4;}};
 return{update(dt){for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.cool-=dt;const carry=balls.find(b=>!b.dead&&b.owner===p.i),free=balls.filter(b=>b.owner===null).sort((a,b)=>dist(p,a)-dist(p,b))[0],opponent=c.players.filter(o=>team(o)!==team(p)).sort((a,b)=>dist(p,a)-dist(p,b))[0],goal=carry?{x:0,z:team(p)?6:-6}:free||opponent,q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:!carry&&dist(p,opponent)<1.5&&p.y===0,b:dist(p,opponent)<1.5&&p.cool<=0}));if(!p.stun)c.move(p,q,carry?4.4:5);c.jump(p,q,8);if(q.ap&&carry){const buddy=c.players[teams[team(p)].find(i=>i!==p.i)];carry.owner=null;carry.x=p.x;carry.z=p.z;const v=toward(p,buddy.x,buddy.z);carry.vx=v.x*8;carry.vz=v.z*8;carry.lock=.2;}if(q.bp&&p.cool<=0&&!p.stun){p.cool=.6;for(const o of c.players)if(team(o)!==team(p)&&dist(p,o)<1.6){o.stun=.8;drop(o);const v=toward(p,o.x,o.z);o.x=clamp(o.x+v.x,-8,8);o.z=clamp(o.z+v.z,-6,6);}}for(const o of c.players)if(team(o)!==team(p)&&p.vy<0&&p.y-o.y>.6&&p.y-o.y<1.1&&dist(p,o)<.55){o.stun=.8;drop(o);}}for(const b of balls){if(b.dead)continue;b.lock=Math.max(0,b.lock-dt);if(b.owner!==null){const p=c.players[b.owner];b.x=p.x;b.z=p.z;if(Math.abs(p.x)<2&&Math.abs(p.z-(team(p)?6:-6))<.7){b.dead=true;teamScore(c,team(p));spawn();}}else{b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>8){b.x=clamp(b.x,-8,8);b.vx*=-1;}if(Math.abs(b.z)>6){b.z=clamp(b.z,-6,6);b.vz*=-1;}if(!b.lock){const p=c.players.find(p=>!p.stun&&p.y<1&&dist(p,b)<.7&&!balls.some(v=>v.owner===p.i&&!v.dead));if(p)b.owner=p.i;}}}const winner=[0,1].filter(t=>c.players[t*2].score>=5);if(winner.length)c.complete(winner.flatMap(t=>teams[t]),'공 다섯 개를 자기 팀 골에 넣었습니다');c.hint('이동/A 점프·공 패스/B 펀치/공중 B 발차기 · 상대를 때리면 공을 놓칩니다 · 자기 색 골에 5개 선취');},render(){c.arena({width:18,depth:14,color:'#b2cba7'});for(let t=0;t<2;t++)c.draw('goal'+t,'box',{x:0,y:.1,z:t?6:-6,sx:4,sy:.2,sz:1,color:c.players[t*2].color});for(const b of balls)if(!b.dead)c.draw('ball'+b.id,'sphere',{x:b.x,y:b.owner!==null?1.3:.5,z:b.z,sx:.55,sy:.55,sz:.8,color:'#c5936d'});},timeout(){c.complete([],'브라우저판 5분 제한 동안 5점에 도달하지 못했습니다');}};
}
function balloons(c){
 c.limit=300;c.view={size:23,eye:[0,25,20],target:[0,0,0]};const targets=Array.from({length:24},(_,i)=>({id:i,t:i%2,x:c.rand(-7,7),z:c.rand(-5,5),dead:false}));c.players.forEach(p=>{p.x=p.i%2?5:-5;p.z=team(p)?5:-5;p.heading=team(p)?-Math.PI/2:Math.PI/2;p.speed=0;});
 return{update(dt){for(const p of c.players){const target=targets.filter(v=>!v.dead&&v.t===team(p)).sort((a,b)=>dist(p,a)-dist(p,b))[0],a=target?Math.atan2(target.z-p.z,target.x-p.x):p.heading,d=Math.atan2(Math.sin(a-p.heading),Math.cos(a-p.heading)),q=c.input(p,{x:clamp(d*2,-1,1),a:Math.abs(d)<1.4,b:Math.abs(d)>2});p.heading+=q.x*2.3*dt*(p.speed<-.2?-1:1);p.speed=clamp(p.speed+((q.a?5:0)-(q.b?7:0)-p.speed*.8)*dt,-2.7,6);p.x=clamp(p.x+Math.cos(p.heading)*p.speed*dt,-8,8);p.z=clamp(p.z+Math.sin(p.heading)*p.speed*dt,-6,6);p.rotation=-p.heading;p.pose='sit';for(const b of targets)if(!b.dead&&dist(p,b)<.85){b.dead=true;teamScore(c,b.t);}}for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=c.players[i],b=c.players[j],d=dist(a,b);if(d<1.2&&d>.001){const v=toward(b,a.x,a.z),push=(1.2-d)/2;a.x+=v.x*push;a.z+=v.z*push;b.x-=v.x*push;b.z-=v.z*push;a.speed*=.96;b.speed*=.96;}}const winners=[0,1].filter(t=>targets.filter(v=>v.t===t).every(v=>v.dead));if(winners.length)c.complete(winners.flatMap(t=>teams[t]),'자기 팀 풍선을 모두 터뜨렸습니다');c.hint('좌우 핸들/A 가속/B 감속·후진 · 자기 팀 색 풍선을 모두 터뜨리세요 · 상대 풍선을 터뜨리면 상대를 돕습니다');},render(){c.arena({width:19,depth:15,color:'#a7b9b6'});for(const b of targets)if(!b.dead){c.draw('balloon'+b.id,'sphere',{x:b.x,y:.8,z:b.z,sx:.8,sy:1,sz:.8,color:c.players[b.t*2].color});c.draw('string'+b.id,'box',{x:b.x,y:.25,z:b.z,sx:.03,sy:.5,sz:.03,color:ink});}for(const p of c.players)c.draw('car'+p.i,'box',{x:p.x,y:.2,z:p.z,sx:1.5,sy:.4,sz:1,ry:-p.heading,color:c.players[team(p)*2].color});},timeout(){c.complete([],'브라우저판 5분 동안 모두 터뜨리지 못했습니다');}};
}
function row(c){
 c.limit=300;c.view={size:25,eye:[0,27,23],target:[0,0,0]};const boats=[{x:-8,z:8,a:-Math.PI/2,v:0,target:0},{x:8,z:8,a:-Math.PI/2,v:0,target:0}],logs=[{x:-4,z:3},{x:4,z:3},{x:-4,z:-3},{x:4,z:-3}];c.players.forEach(p=>p.cadence=c.rand(3,4));
 return{update(dt){const arrived=[];for(let t=0;t<2;t++){const boat=boats[t],sign=t?1:-1,path=[{x:sign*8,z:-4},{x:0,z:-6},{x:0,z:0}],goal=path[boat.target],angle=Math.atan2(goal.z-boat.z,goal.x-boat.x),d=Math.atan2(Math.sin(angle-boat.a),Math.cos(angle-boat.a));if(dist(boat,goal)<2&&boat.target<2)boat.target++;for(let k=0;k<2;k++){const p=c.players[t*2+k],q=c.input(p,{a:(Math.abs(d)<.2||k===(d>0?0:1))&&Math.floor(c.time*p.cadence)%2===0});if(q.ap){boat.v+=.85;boat.a+=(k?-.4:.4);p.stroke=c.time;}}boat.v=clamp(boat.v*Math.exp(-dt*.8),0,5);boat.x+=Math.cos(boat.a)*boat.v*dt;boat.z+=Math.sin(boat.a)*boat.v*dt;for(const log of logs)if(Math.abs(boat.x-log.x)<1.8&&Math.abs(boat.z-log.z)<.8){boat.x-=Math.cos(boat.a)*boat.v*dt;boat.z-=Math.sin(boat.a)*boat.v*dt;boat.v*=.3;}boat.x=clamp(boat.x,-11,11);boat.z=clamp(boat.z,-9,10);for(let k=0;k<2;k++){const p=c.players[t*2+k];p.x=boat.x+Math.cos(boat.a+Math.PI/2)*(k?.55:-.55);p.z=boat.z+Math.sin(boat.a+Math.PI/2)*(k?.55:-.55);p.rotation=-boat.a;p.pose='sit';p.score=Math.max(0,30-Math.floor(Math.hypot(boat.x,boat.z)));}if(Math.hypot(boat.x,boat.z)<2.4)arrived.push(t);}if(arrived.length)c.complete(arrived.flatMap(t=>teams[t]),'섬에 먼저 도착했습니다');c.hint('각자 A를 눌러 자기 쪽 노 젓기 · 한쪽만 저으면 회전 · 나뭇가지에 걸리면 방향을 바꾸세요');},render(){c.arena({width:25,depth:22,color:'#99c3c6'});c.draw('island','cylinder',{x:0,y:.15,z:0,sx:4.5,sy:.3,sz:4.5,color:'#d7cf9c'});text(c,'flag','FINISH',0,1,0,4);logs.forEach((v,i)=>c.draw('log'+i,'box',{x:v.x,y:.1,z:v.z,sx:3.4,sy:.6,sz:.8,color:'#b29679'}));boats.forEach((v,t)=>{c.draw('boat'+t,'sphere',{x:v.x,y:.05,z:v.z,sx:2.8,sy:.4,sz:1.7,ry:-v.a,color:c.players[t*2].color});for(let k=0;k<2;k++)c.draw('oar'+t+k,'box',{x:v.x+Math.cos(v.a+Math.PI/2)*(k?1.2:-1.2),y:.15,z:v.z+Math.sin(v.a+Math.PI/2)*(k?1.2:-1.2),sx:1.8,sy:.12,sz:.15,ry:-v.a+((c.time-(c.players[t*2+k].stroke??-1))<.2?.6:0),color:cream});});},timeout(){c.complete([],'브라우저판 5분 안에 섬에 도착하지 못했습니다');}};
}
function dinner(c){
 c.limit=30;c.view={size:21,eye:[0,23,20],target:[0,0,0]};const items=[],plants=Array.from({length:4},(_,i)=>({x:Math.cos(i*TAU/4)*6,z:Math.sin(i*TAU/4)*6}));let next=.5,id=0;c.players.forEach(p=>{p.x=(p.i%2?1:-1)*2;p.z=p.i<2?-2:2;p.stun=0;p.out=false;});
 return{update(dt){if(c.time>=next){next+=2;for(const p of c.players)if(p.out){p.out=false;p.visible=true;p.x=c.rand(-.5,.5);p.z=c.rand(-.5,.5);p.y=2;p.vy=0;}for(let i=0;i<6;i++){const a=c.rand(0,TAU),r=c.rand(2,5.7);items.push({id:id++,x:Math.cos(a)*r,z:Math.sin(a)*r,age:0,spike:i===0});}}for(const b of items)b.age+=dt;for(const p of c.players){if(p.out)continue;p.stun=Math.max(0,p.stun-dt);const target=items.filter(b=>!b.dead&&!b.spike&&b.age>.4).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...toward(p,target?.x??0,target?.z??0),a:items.some(b=>!b.dead&&b.spike&&dist(p,b)<1.1)&&p.y===0}));if(!p.stun)c.move(p,q,5,false);c.jump(p,q,8);for(const b of items)if(!b.dead&&b.age>.65&&dist(p,b)<.7&&p.y<1.1){b.dead=true;if(b.spike)p.stun=1;else teamScore(c,team(p));}if(plants.some(v=>dist(p,v)<1.1)){p.out=true;p.visible=false;p.x=0;p.z=0;}const r=Math.hypot(p.x,p.z);if(r>6.6){p.x*=6.6/r;p.z*=6.6/r;}}c.hint('이동/A 점프 · 중앙에서 튀어나오는 코인을 팀 합산 · 가시 열매는 기절, 가장자리 새 식물에 잡히면 다음 분출 때 복귀');},render(){c.arena({width:14,depth:14,shape:'cylinder',color:'#c7d3a0'});c.draw('pipe','cylinder',{x:0,y:.35,z:0,sx:1.4,sy:.7,sz:1.4,color:'#87af96'});plants.forEach((p,i)=>{c.draw('stem'+i,'cylinder',{x:p.x,y:.5,z:p.z,sx:.25,sy:1,sz:.25,color:'#6f9f8a'});c.draw('plant'+i,'sphere',{x:p.x,y:1.2,z:p.z,sx:1.6,sy:1.2,sz:1.6,color:'#d294a2'});});for(const b of items)if(!b.dead){const t=Math.min(1,b.age/.8);c.draw('item'+b.id,b.spike?'cone':'cylinder',{x:b.x*t,y:.3+Math.sin(t*Math.PI)*3,z:b.z*t,sx:.55,sy:b.spike?.6:.13,sz:.55,color:b.spike?'#879498':'#eac261'});}},timeout(){c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'수집한 팀 코인을 가져갑니다');}};
}
function paint(c){
 c.limit=30;c.view={size:22,eye:[0,24,20],target:[0,0,0]};const chicks=Array.from({length:11},(_,i)=>({id:i,x:c.rand(-5,5),z:c.rand(-4,4),vx:c.rand(-1,1),vz:c.rand(-1,1),t:null})),shots=[];let id=0;c.players.forEach(p=>{p.x=team(p)?8:-8;p.z=p.i%2?3:-3;p.cool=0;p.stun=0;});
 return{update(dt){for(const b of chicks){b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>5){b.x=clamp(b.x,-5,5);b.vx*=-1;}if(Math.abs(b.z)>4.5){b.z=clamp(b.z,-4.5,4.5);b.vz*=-1;}}for(const p of c.players){p.cool-=dt;p.stun=Math.max(0,p.stun-dt);const target=chicks.filter(b=>b.t!==team(p)&&((p.i%2)?b.z>=-.5:b.z<=.5)).sort((a,b)=>Math.abs(a.z-p.z)-Math.abs(b.z-p.z))[0],goal=target?target.z+target.vz*Math.abs(target.x-p.x)/12:p.z,q=c.input(p,{z:clamp((goal-p.z)*2,-1,1),a:!!target&&Math.abs(goal-p.z)<.4});if(!p.stun){p.z=clamp(p.z+q.z*5*dt,-5,5);if((q.a||q.b)&&p.cool<=0){p.cool=.28;shots.push({id:id++,t:team(p),x:p.x,z:p.z,vx:team(p)?-12:12});}}}for(const t of teams){const a=c.players[t[0]],b=c.players[t[1]];if(b.z-a.z<1){const middle=(a.z+b.z)/2;a.z=clamp(middle-.5,-5,4);b.z=clamp(middle+.5,-4,5);}}for(const b of shots){if(b.dead)continue;b.x+=b.vx*dt;const chick=chicks.find(v=>dist(v,b)<.65);if(chick){chick.t=b.t;b.dead=true;}else{const p=c.players.find(p=>team(p)!==b.t&&!p.stun&&dist(p,b)<.7);if(p){p.stun=.7;b.dead=true;}}if(Math.abs(b.x)>9)b.dead=true;}for(const p of c.players)p.score=chicks.filter(b=>b.t===team(p)).length;c.hint('위아래로 레일 이동/A 발사 · 아기 새 11마리를 자기 팀 색으로 칠하세요 · 덧칠 가능, 상대 피격은 기절, 동료와 자리 교환 불가');},render(){c.arena({width:19,depth:12,color:'#d4c5ae'});for(const b of chicks){c.draw('chick'+b.id,'sphere',{x:b.x,y:.45,z:b.z,sx:1,sy:.85,sz:.8,color:b.t===null?'#baa69a':c.players[b.t*2].color});c.draw('beak'+b.id,'cone',{x:b.x,y:.55,z:b.z+.45,sx:.25,sy:.5,sz:.25,rx:Math.PI/2,color:ink});}for(const b of shots)if(!b.dead)c.draw('paint'+b.id,'sphere',{x:b.x,y:.4,z:b.z,sx:.35,sy:.35,sz:.35,color:c.players[b.t*2].color});for(const p of c.players)c.draw('cart'+p.i,'box',{x:p.x,y:.2,z:p.z,sx:1.2,sy:.4,sz:1.2,color:c.players[team(p)*2].color});},timeout(){const a=c.players[0].score,b=c.players[2].score;c.complete(a===b?[]:teams[a>b?0:1],'30초 뒤 자기 색 아기 새 수');}};
}
function king(c){
 c.limit=300;c.view={size:24,eye:[0,24,20],target:[0,0,0]};let phase=0,started=0,radius=3.2;const bases=[-5,5];c.players.forEach(p=>{p.arena=p.i%2;p.x=bases[p.arena]+(team(p)?1.2:-1.2);p.z=0;p.vx=0;p.vz=0;p.stun=0;p.cool=0;});
 return{update(dt){radius=Math.max(1,phase?4-Math.max(0,c.time-started-8)*.12:3.2-Math.max(0,c.time-8)*.1);for(const p of c.players){if(!p.alive)continue;const peers=c.players.filter(o=>o.alive&&o!==p&&(phase||o.arena===p.arena)),opponent=peers[0];if(!opponent)continue;const base=phase?0:bases[p.arena];p.cool-=dt;p.stun=Math.max(0,p.stun-dt);const towardCenter=Math.hypot(p.x-base,p.z)>radius-.7,goal=towardCenter?{x:base,z:0}:opponent,q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:dist(p,opponent)<1.5&&p.y===0&&Math.floor(c.time*2+p.i)%2===0,b:dist(p,opponent)<1.7&&p.cool<=0}));if(!p.stun)c.move(p,q,3.6,false);p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-dt*3);p.vz*=Math.exp(-dt*3);c.jump(p,q,8);if(q.bp&&p.cool<=0&&!p.stun&&dist(p,opponent)<1.8){p.cool=.55;const v=toward(p,opponent.x,opponent.z);opponent.vx=v.x*(p.y>0?8:6);opponent.vz=v.z*(p.y>0?8:6);opponent.stun=.35;}if(Math.hypot(p.x-base,p.z)>radius)c.eliminate(p);}if(!phase){const groups=[0,1].map(a=>c.players.filter(p=>p.arena===a&&p.alive));if(groups.every(g=>g.length<=1)){const winners=groups.flat();if(!winners.length)c.complete([],'첫 대결에서 모두 떨어졌습니다');else if(winners.length===1||team(winners[0])===team(winners[1]))c.complete(teams[team(winners[0])],'두 플랫폼의 대결에서 팀이 승리');else{phase=1;started=c.time;winners.forEach((p,i)=>{p.x=i?1.3:-1.3;p.z=0;p.y=0;p.vx=p.vz=0;p.score=1;});}}}else{const alive=c.players.filter(p=>p.alive);if(alive.length===1)c.complete(teams[team(alive[0])],'정상 대결에서 승리');else if(!alive.length)c.complete([],'정상에서 두 선수 모두 떨어졌습니다');}c.hint('이동/A 점프/B 펀치/공중 B 발차기 · 작은 플랫폼에서 각각 대결 · 다른 팀 승자 둘이면 정상에서 결승');},render(){for(const base of phase?[0]:bases)c.draw('platform'+base,'cylinder',{x:base,y:-.3,z:0,sx:radius*2,sy:.6,sz:radius*2,color:'#bbc1a5'});text(c,'round',phase?'FINAL':'TEAM DUELS',0,1,-6,7);},timeout(){c.complete([],'5분 안에 대결이 끝나지 않았습니다');}};
}
function ravine(c){
 c.limit=300;c.view={size:26,eye:[0,27,23],target:[0,0,0]};const boats=[{x:0,distance:0,boost:0,stun:0,seen:new Set()},{x:0,distance:0,boost:0,stun:0,seen:new Set()}],features=Array.from({length:34},(_,i)=>({id:i,at:10+i*6,x:c.rand(-3.4,3.4),ramp:i%4===0}));c.players.forEach(p=>p.skill=c.rand(.55,1));
 return{update(dt){const done=[];for(let t=0;t<2;t++){const b=boats[t];b.boost=Math.max(0,b.boost-dt);b.stun=Math.max(0,b.stun-dt);const next=features.find(f=>f.at>b.distance&&f.at<b.distance+8&&(f.ramp||Math.abs(f.x-b.x)<1.4)),goal=next?next.ramp?next.x:clamp(next.x+(b.x>next.x?2:-2),-3.8,3.8):b.x;let steer=0;for(const i of teams[t]){const p=c.players[i],q=c.input(p,{x:clamp((goal-b.x)*2,-1,1)*p.skill});steer+=q.x;}b.x=clamp(b.x+steer*2.8*dt,-4.2,4.2);const speed=b.stun?1.4:b.boost?8:4.5;b.distance+=speed*dt;for(const f of features)if(!b.seen.has(f.id)&&Math.abs(f.at-b.distance)<.6){b.seen.add(f.id);if(Math.abs(f.x-b.x)<1){if(f.ramp)b.boost=2;else b.stun=1.1;}}for(let k=0;k<2;k++){const p=c.players[t*2+k];p.x=(t?6:-6)+b.x+(k?.45:-.45);p.z=5;p.y=b.boost>1.6?Math.sin((2-b.boost)*Math.PI/.4)*1.2:0;p.pose='sit';p.score=Math.floor(b.distance);}if(b.distance>=220)done.push(t);}if(done.length)c.complete(done.flatMap(t=>teams[t]),'협동 호버카로 결승점에 도착');c.hint('두 팀원이 좌우로 기울여 조향 · 같은 쪽을 누르면 더 급하게 회전 · 경사로는 가속, 물기둥은 감속');},render(){for(let t=0;t<2;t++){const b=boats[t],base=t?6:-6;c.draw('river'+t,'box',{x:base,y:-.2,z:0,sx:10,sy:.3,sz:26,color:'#99c6c8'});for(const f of features){const z=5-(f.at-b.distance)*.55;if(z< -14||z>13)continue;c.draw('feature'+t+'_'+f.id,f.ramp?'box':'cylinder',{x:base+f.x,y:f.ramp?.3:1,z,sx:f.ramp?2:1,sy:f.ramp?.6:2,sz:f.ramp?2:1,rx:f.ramp?-.25:0,color:f.ramp?'#cab796':'#b9e0e0'});}c.draw('craft'+t,'sphere',{x:base+b.x,y:c.players[t*2].y+.05,z:5,sx:2.5,sy:.5,sz:2,color:c.players[t*2].color});}},timeout(){c.complete([],'브라우저판 5분 안에 완주하지 못했습니다');}};
}
function gallery(c){
 c.limit=300;c.view={size:26,eye:[0,11,32],target:[0,5,0]};const state=[{stage:0,ghosts:[],wait:0},{stage:0,ghosts:[],wait:0}],bases=[-6.5,6.5];let serial=0;const spawn=t=>{const s=state[t];s.ghosts=Array.from({length:s.stage===2?1:s.stage===1?12:8},(_,i)=>({id:serial++,x:c.rand(-3.6,3.6),y:c.rand(2,8),phase:c.rand(0,TAU),hp:s.stage===2?20:1,max:s.stage===2?20:1}));};spawn(0);spawn(1);c.players.forEach(p=>{p.x=bases[team(p)]+(p.i%2?1.5:-1.5);p.y=0;p.z=3;p.aim={x:bases[team(p)],y:5};p.cool=0;});
 return{update(dt){for(let t=0;t<2;t++){const s=state[t];if(s.wait&&c.time>=s.wait){s.wait=0;spawn(t);}if(!s.wait)for(const g of s.ghosts){g.drawX=bases[t]+g.x+Math.sin(c.time*1.4+g.phase)*.6;g.drawY=g.y+Math.cos(c.time+g.phase)*.4;}}for(const p of c.players){p.cool-=dt;const t=team(p),s=state[t],available=s.ghosts.filter(g=>g.hp>0),g=available[(p.i%2)%Math.max(1,available.length)],q=c.input(p,{x:g?clamp((g.drawX-p.aim.x)*2,-1,1):0,z:g?clamp((p.aim.y-g.drawY)*2,-1,1):0,a:!!g&&Math.hypot(g.drawX-p.aim.x,g.drawY-p.aim.y)<.5});if(p.i===0&&q.pointer.frontValid){p.aim.x=clamp(q.pointer.frontX,bases[t]-5,bases[t]+5);p.aim.y=clamp(q.pointer.frontY,0,10);}else{p.aim.x=clamp(p.aim.x+q.x*8*dt,bases[t]-5,bases[t]+5);p.aim.y=clamp(p.aim.y-q.z*8*dt,0,10);}if((q.a||q.b||q.pointer.down)&&p.cool<=0&&!s.wait){p.cool=.28;const hit=available.find(g=>Math.hypot(g.drawX-p.aim.x,g.drawY-p.aim.y)<(s.stage===2?1.6:.7));if(hit){hit.hp--;c.points(p);p.flash=c.time;}}}for(let t=0;t<2;t++){const s=state[t];if(!s.wait&&s.ghosts.every(g=>g.hp<=0)){s.stage++;if(s.stage===3)c.complete(teams[t],'저택 지하의 거대한 유령 새 퇴치');else s.wait=c.time+.8;}}c.hint('방향 또는 1P 포인터 조준/A·B 발사 · 바깥뜰 → 현관 → 지하 · 동료와 서로 다른 유령 새를 맡으세요');},render(){for(let t=0;t<2;t++){const s=state[t];c.draw('room'+t,'box',{x:bases[t],y:5,z:-1,sx:11,sy:11,sz:.3,color:['#a3bdb5','#bbb1c6','#939caf'][Math.min(s.stage,2)]});text(c,'stage'+t,`${Math.min(s.stage+1,3)} / 3`,bases[t],10,0,4);if(!s.wait)for(const g of s.ghosts)if(g.hp>0){const r=s.stage===2?2.8:1.2;c.draw('ghost'+g.id,'sphere',{x:g.drawX??bases[t]+g.x,y:g.drawY??g.y,z:0,sx:r,sy:r,sz:r,color:'#e4a3b6',opacity:.85});c.draw('beak'+g.id,'cone',{x:g.drawX??bases[t]+g.x,y:(g.drawY??g.y)-.1,z:r*.5,sx:.35,sy:.6,sz:.35,rx:Math.PI/2,color:ink});if(s.stage===2)text(c,'hp'+t,`${g.hp}`,g.drawX??bases[t]+g.x,(g.drawY??g.y)+2,1,3);}}for(const p of c.players)c.draw('aim'+p.i,'ring',{x:p.aim.x,y:p.aim.y,z:2,sx:.6,sy:.6,sz:1,color:p.color});},timeout(){c.complete([],'브라우저판 5분 동안 유령 새를 모두 퇴치하지 못했습니다');}};
}
function crops(c){
 c.limit=300;c.view={size:27,eye:[0,30,22],target:[0,0,0]};const path=[];for(let row=0;row<5;row++){for(let col=0;col<9;col++)path.push({x:row%2?8-col:col,z:row*2});if(row<4)path.push({x:row%2?0:8,z:row*2+1});}const key=v=>v.z*9+v.x,walk=new Set(path.map(key)),blocks=[new Map(),new Map()];for(let t=0;t<2;t++)for(let j=3;j<path.length;j+=4)blocks[t].set(key(path[j]),{kind:Math.floor(j/4)%2,at:j});c.players.forEach(p=>{p.cell=key(path[p.i%2]);p.repeat=0;p.cool=0;p.pace=c.rand(.13,.2);p.x=0;p.z=0;p.scale=.65;});const neighbors=k=>[k%9>0?k-1:-1,k%9<8?k+1:-1,k-9,k+9].filter(v=>walk.has(v));const pos=k=>({x:k%9,z:Math.floor(k/9)});
 return{update(dt){for(const p of c.players){p.cool-=dt;p.repeat-=dt;const t=team(p),role=p.i%2,near=neighbors(p.cell).find(k=>blocks[t].get(k)?.kind===role),queue=[p.cell],previous=new Map([[p.cell,null]]);let goal=null;for(let i=0;i<queue.length&&!goal;i++){const k=queue[i];if(neighbors(k).some(n=>blocks[t].get(n)?.kind===role)){goal=k;break;}for(const n of neighbors(k))if(!blocks[t].has(n)&&!previous.has(n)){previous.set(n,k);queue.push(n);}}let step=goal;if(step!==null)while(previous.get(step)!==null&&previous.get(step)!==p.cell)step=previous.get(step);const here=pos(p.cell),to=step!==null?pos(step):here,q=c.input(p,{x:to.x-here.x,z:to.z-here.z,a:near!==undefined&&(role===1||Math.floor(c.time*6)%2===0),b:near!==undefined&&role===1&&Math.floor(c.time*5)%2===0});if(p.repeat<=0&&(Math.abs(q.x)>.4||Math.abs(q.z)>.4)){let next=p.cell;if(Math.abs(q.x)>Math.abs(q.z)){if(q.x>0&&p.cell%9<8)next++;if(q.x<0&&p.cell%9>0)next--;}else next+=q.z>0?9:-9;if(walk.has(next)&&!blocks[t].has(next))p.cell=next;p.repeat=p.pace;}const target=neighbors(p.cell).find(k=>blocks[t].get(k)?.kind===role);if(target!==undefined&&p.cool<=0&&(role===0?q.ap:q.a&&q.bp)){blocks[t].delete(target);teamScore(c,t);p.cool=.3;p.work=c.time;}const xy=pos(p.cell);p.x=(t?6.5:-6.5)+(xy.x-4)*.95;p.z=(xy.z-4)*.95;p.pose=c.time-(p.work??-2)<.2?'jump':'run';}const won=[0,1].filter(t=>blocks[t].size===0);if(won.length)c.complete(won.flatMap(t=>teams[t]),'밭의 당근과 두더지를 모두 정리');c.hint('방향으로 밭 이동 · 1P·3P A 망치 · 2P·4P A로 당근 잡고 B로 뽑기 · 서로 막힌 길을 열어 주세요');},render(){for(let t=0;t<2;t++){const base=t?6.5:-6.5;for(let z=0;z<9;z++)for(let x=0;x<9;x++){const k=z*9+x,px=base+(x-4)*.95,pz=(z-4)*.95;c.draw('ground'+t+'_'+k,'box',{x:px,y:walk.has(k)?-.12:.2,z:pz,sx:.92,sy:walk.has(k)?.2:.7,sz:.92,color:walk.has(k)?'#d4c19d':'#9bb792'});const b=blocks[t].get(k);if(b){c.draw('crop'+t+'_'+k,b.kind?'cone':'sphere',{x:px,y:.4,z:pz,sx:.65,sy:.8,sz:.65,color:b.kind?'#ddaa64':'#a9968d'});if(b.kind)c.draw('leaf'+t+'_'+k,'cone',{x:px,y:.9,z:pz,sx:.5,sy:.35,sz:.5,color:'#789e7f'});}}text(c,'remaining'+t,`${blocks[t].size} LEFT`,base,.5,5.5,5);}},timeout(){c.complete([],'5분 안에 밭 정리를 마치지 못했습니다');}};
}
export const games={'Power Trip':power,'Bob-ombs Away':bombs,"Swervin' Skies":skies,'Picture Perfect':picture,'Snow Way Out':snow,"Thrash 'n' Crash":thrash,'Chump Rope':rope,'Grabby Gridiron':gridiron,'Bumper Balloons':balloons,'Rowed to Victory':row,'Winner or Dinner':dinner,"Paint Misbehavin'":paint,'King of the Thrill':king,'Lean, Mean Ravine':ravine,'Boo-ting Gallery':gallery,"Crops 'n' Robbers":crops};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['mp8']]));
const own='원작 중심 규칙을 새 플라밍고 3D 장면으로 만들었습니다. Wii 기울이기·흔들기 동작은 방향키와 버튼으로 바꾸었으며, 물리 속도·충돌 범위·새 코스와 적 배치는 브라우저판 조정값입니다. ';
export const notes={
'Power Trip':own+'1P는 자동 전진하는 전기 UFO를 좌우로 회전시킵니다. 팀은 이동/A 점프로 기체와 구멍을 피합니다. 30초 안에 세 명을 모두 잡으면 1P, 하나라도 남으면 팀 승리입니다.',
'Bob-ombs Away':own+'팀이 위에서 A로 떨어뜨린 폭탄은 핀과 벽에 튕겨 내려옵니다. 1P는 좌우 이동만 가능하며 한 번 폭발에 맞으면 팀 승리, 30초 생존하면 1P 승리입니다.',
"Swervin' Skies":own+'방향으로 비행하며 1P가 A/B로 발사합니다. 세 기체마다 날개 양쪽에 독립된 표적이 있으며 모두 맞혀야 격추됩니다. 30초 안에 모두 격추하면 1P 승리입니다.',
'Picture Perfect':own+'1P는 4조각, 팀은 9조각의 돌아가는 그림을 각각 선택해 A/B로 멈추거나 다시 돌립니다. 플라밍고·과일·조개·햇살·물고기·알 그림을 맞춥니다. 라운드당 20초, 3장 선취, 5라운드 안에 승자가 없으면 무승부입니다. 브라우저판은 90도씩 단계 회전합니다.',
'Snow Way Out':own+'1P 조준/A·B 눈덩이가 지붕을 얼리고 직접 맞은 선수를 얼려 미끄러뜨립니다. 팀은 이동/A 점프와 서로 밟기가 가능합니다. 세 명 모두 추락해야 1P 승리, 30초 생존자는 팀 승리입니다.',
"Thrash 'n' Crash":own+'1P 조준/A·B로 통·발사관·바퀴를 활성화합니다. 고정 벽과 세로 장애물도 있습니다. 팀은 스케이트보드로 전후좌우 이동하며 30초 동안 한 명이라도 생존하면 승리합니다. 발사체는 한 명, 바퀴는 여러 명을 맞힐 수 있습니다.',
'Chump Rope':own+'1P는 방향을 원으로 돌리거나 A로 줄을 가속하고, 팀은 A로 점프합니다. 속도를 바꾸며 세 명을 모두 넘어뜨리면 1P 승리, 15초 생존자는 팀 승리입니다.',
'Grabby Gridiron':own+'튀는 공 두 개를 잡아 자기 팀 골에 넣고 5점 선취합니다. A 점프·공 패스/B 펀치/공중 B 발차기로 공을 빼앗을 수 있습니다. 원작 숨은 시간 제한이 미확인이라 브라우저판 5분 상한을 사용합니다.',
'Bumper Balloons':own+'좌우 핸들/A 가속/B 감속·후진으로 자기 팀 풍선을 모두 터뜨립니다. 상대 색 풍선을 터뜨리면 상대 실적으로 셉니다. 풍선 수는 새 배치 12개씩이며 원작 숨은 제한이 미확인이라 브라우저판 5분 상한입니다.',
'Rowed to Victory':own+'각자가 A로 자기 쪽 노를 젓습니다. 불균형한 젓기는 배를 회전시키고 가지에 닿으면 막힙니다. 섬에 먼저 도착한 팀이 승리합니다. 원작 숨은 제한이 미확인이라 브라우저판 5분 상한입니다.',
'Winner or Dinner':own+'30초 동안 중앙에서 튀는 코인을 모아 팀 합산합니다. 가시 열매에 닿으면 기절하고 가장자리 식물에 잡히면 다음 분출 때 중앙으로 복귀합니다. 코인은 얻은 만큼 가져갑니다.',
"Paint Misbehavin'":own+'옆면 레일에서 위아래 이동/A 발사로 아기 새 11마리를 칠합니다. 상대 색을 덧칠할 수 있고 상대 선수 피격은 기절을 일으킵니다. 동료를 지나칠 수 없으며 30초 뒤 더 많은 색을 가진 팀 승리입니다.',
'King of the Thrill':own+'줄어드는 작은 플랫폼 두 곳에서 상대와 이동·점프·펀치·공중 발차기로 대결합니다. 양쪽 승자가 같은 팀이면 승리, 다른 팀이면 큰 플랫폼에서 결승을 치릅니다. 5분 제한이며 결승 둘 다 추락하면 무승부입니다.',
'Lean, Mean Ravine':own+'두 팀원이 같은 쪽을 누르면 호버카가 더 급히 회전합니다. 경사로는 가속, 물기둥은 감속시키며 결승에 먼저 도착한 팀 승리입니다. 코스는 새로 구성했고 숨은 제한 미확인으로 브라우저판 5분 상한입니다.',
'Boo-ting Gallery':own+'팀이 조준/A·B로 바깥뜰·현관·지하의 유령 새를 차례로 퇴치합니다. 지하 보스를 먼저 쓰러뜨리면 승리합니다. 원작 정확한 개체 수·체력이 미확인이라 브라우저판은 8마리/12마리/보스 20회 명중과 5분 상한을 사용합니다.',
"Crops 'n' Robbers":own+'두더지 담당은 A 망치, 당근 담당은 A로 잡고 B로 뽑습니다. 상대 역할의 작물을 통과할 수 없어 동료가 길을 열어야 합니다. 밭을 모두 정리하면 승리하며 5분 제한입니다. 9×9 밭 배치는 새로 구성했습니다.'};
