import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,cream='#f1e6cd',ink='#355a62',colors=['#df859f','#e5bc63','#83b9ba','#a795c6'];
const label=(c,id,text,x,y,z,w=3)=>c.draw(id,'text',{x,y,z,sx:w,sy:w*.23,text,color:ink});
const unequal=(c,reason)=>new Set(c.players.map(p=>p.score)).size===1?c.complete([],'모두 같은 기록으로 무승부'):c.highest(reason);
const first=(c,list,reason)=>{if(list.length){const min=Math.min(...list.map(v=>v.t));c.complete(list.filter(v=>Math.abs(v.t-min)<1e-7).map(v=>v.i),reason);}};
const pulse=(t,s,phase=0)=>((t*s+phase)%1)<.4;
function escape(p,foes,x=6,z=4){const choices=Array.from({length:12},(_,i)=>({x:clamp(p.x+Math.cos(i*TAU/12)*2,-x,x),z:clamp(p.z+Math.sin(i*TAU/12)*2,-z,z)}));const value=t=>Math.min(...foes.map(o=>dist(t,o)))-.1*Math.hypot(t.x,t.z);return choices.sort((a,b)=>value(b)-value(a))[0];}
function manta(c){
 c.limit=Infinity;c.view={size:21,eye:[0,13,23],target:[0,0,-1]};let travel=0;
 const objects=Array.from({length:90},(_,i)=>({i,x:c.rand(-7,7),z:10+i*1.45,y:c.rand(.5,4.5),type:i%9===0?'gold':i%5===0?'eel':i%7===0?'shark':i%4===0?'squid':'ring',taken:false}));
 c.players.forEach(p=>{p.x=(p.i-1.5)*2;p.z=3;p.y=2;p.stroke=0;p.cool=0;});
 return{update(dt){travel+=dt*3.3;for(const p of c.players){const list=objects.filter(o=>!o.taken&&['gold','ring'].includes(o.type)&&o.z-travel>p.z-1&&o.z-travel<p.z+13).sort((a,b)=>(a.z-travel-p.z)*.25+Math.abs(a.x-p.x)-(b.z-travel-p.z)*.25-Math.abs(b.x-p.x)),o=list[0];const q=c.input(p,()=>({x:o?clamp((o.x-p.x)*2,-1,1):0,z:o?clamp((p.y-o.y)*2,-1,1):0,a:pulse(c.time,4+p.i*.2,p.i*.1)}));p.x=clamp(p.x+q.x*4*dt,-7.5,7.5);p.y=clamp(p.y-q.z*3*dt,.35,5);p.stroke=Math.max(0,p.stroke-dt*1.3);if(q.ap)p.stroke=Math.min(2,p.stroke+.3);p.z=clamp(p.z+(p.stroke-.65)*dt,-1,5);p.cool=Math.max(0,p.cool-dt);p.pose='swim';for(const o of objects){if(o.taken)continue;const d=Math.hypot(o.x-p.x,o.y-p.y,(o.z-travel)-p.z);if(d<.85){if(['ring','gold'].includes(o.type)){o.taken=true;c.points(p,o.type==='gold'?3:1);}else if(!p.cool){c.points(p,-Math.min(p.score,{squid:1,shark:2,eel:3}[o.type]));p.cool=1.2;p.z=Math.max(-1,p.z-.7);}}}}if(travel>objects.at(-1).z+8)unequal(c,'수중 고리 득점');c.hint('방향으로 좌우·수심 이동 · A 반복으로 앞으로 · 금 고리 3점 / 일반 1점 · 해파리 −1, 물고기 −2, 장어 −3');},render(){c.arena({width:20,depth:25,color:'#83bdc7'});for(const o of objects){const z=o.z-travel;if(o.taken||z< -5||z>18)continue;const good=['ring','gold'].includes(o.type);c.draw('o'+o.i,good?'ring':o.type==='eel'?'cylinder':'sphere',{x:o.x,y:o.y,z,sx:good?1.7:o.type==='eel'?.35:1,sy:good?1.7:o.type==='eel'?2:1,sz:.35,rx:good?0:Math.PI/2,color:o.type==='gold'?'#f3cb62':good?cream:o.type==='squid'?'#dfcbd4':o.type==='shark'?'#849eaa':'#df9a6e'});}label(c,'route',`${Math.min(100,Math.floor(travel/(objects.at(-1).z+8)*100))}%`,0,6,-3);}};
}
function slime(c){
 c.limit=30;c.view={size:19,eye:[0,20,18],target:[0,0,0]};c.players.forEach(p=>{p.distance=0;p.rate=c.rand(5,7);p.phase=c.rand();p.score=0;});
 return{update(dt){const arrivals=[];for(const p of c.players){const q=c.input(p,{a:pulse(c.time,p.rate,p.phase)}),old=p.distance;p.distance=Math.max(0,p.distance-dt*(.85+p.distance*.13));if(q.ap)p.distance+=.3;if(p.distance>=6.2)arrivals.push({i:p.i,t:q.ap?0:(6.2-old)/(p.distance-old||1)});const a=p.i*TAU/4+Math.PI/4;p.x=Math.cos(a)*(8-p.distance);p.z=Math.sin(a)*(8-p.distance);p.rotation=-a+Math.PI;p.score=Math.round(p.distance*10);p.pose=q.a?'run':'idle';}first(c,arrivals,'끈적한 젤을 벗어나 중앙에 먼저 도착');c.hint('A 빠르게 반복 · 쉬면 젤이 다시 잡아당깁니다');},render(){c.arena({width:19,depth:19,color:'#b8c9b8'});c.draw('center','cylinder',{x:0,y:.05,z:0,sx:4,sy:.1,sz:4,color:'#ddbd84'});for(const p of c.players){const a=p.i*TAU/4+Math.PI/4,x=Math.cos(a)*8,z=Math.sin(a)*8;c.draw('slime'+p.i,'sphere',{x,y:.5,z,sx:2.7,sy:1.5,sz:2.7,color:colors[p.i],opacity:.65});c.draw('string'+p.i,'box',{x:(x+p.x)/2,y:.7,z:(z+p.z)/2,sx:.24,sy:.24,sz:Math.max(.1,dist(p,{x,z})),ry:Math.atan2(x-p.x,z-p.z),color:colors[p.i],opacity:.65});}},timeout(){c.complete([],'30초 안에 탈출한 선수가 없습니다');}};
}
function medley(c){
 c.limit=300;c.view={size:24,eye:[0,24,17],target:[0,0,0]};c.players.forEach(p=>{p.distance=0;p.energy=100;p.speed=0;p.next=0;p.seq=0;p.lap=0;p.interval=c.rand(.15,.2);p.x=(p.i-1.5)*4;p.z=7;});
 return{update(dt){const arrivals=[];for(const p of c.players){const lap=Math.min(2,Math.floor(p.distance/60)),sequence=lap===1?['c','d']:['b','a'];if(p.lap!==lap){p.lap=lap;p.seq=0;p.energy=Math.min(100,p.energy+12);}const q=c.input(p,()=>{if(c.time<p.next||p.energy<20&&p.speed>1.8)return{};p.next=c.time+p.interval;return lap===0?{a:true,b:true}:{[sequence[p.seq%2]]:true};});let stroke=false;if(lap===0)stroke=q.a&&q.b&&(q.ap||q.bp);else if(q[sequence[p.seq%2]+'p']){p.seq++;stroke=true;}if(stroke){p.speed=Math.min(p.energy>4?6:1.1,p.speed+(p.energy>4?1.25:.1));p.energy=Math.max(0,p.energy-6);}p.energy=Math.min(100,p.energy+dt*11);p.speed=Math.max(.05,p.speed-dt*1.7);const old=p.distance;p.distance+=p.speed*dt;if(p.distance>=180)arrivals.push({i:p.i,t:(180-old)/(p.speed||1)});const f=p.distance%60/60;p.z=7-(lap%2?1-f:f)*14;p.y=.15;p.pose='swim';p.score=+(p.distance/180*100).toFixed(1);}first(c,arrivals,'세 가지 영법으로 먼저 3바퀴 완주');c.hint('1구간 A+B 동시 반복 · 2구간 C/D 번갈아 · 3구간 B/A 번갈아 · 지치기 전에 잠깐 쉬세요');},render(){c.arena({width:20,depth:18,color:'#88c1cc'});for(const p of c.players){c.draw('lane'+p.i,'box',{x:p.x+1.8,y:0,z:0,sx:.12,sy:.15,sz:17,color:cream});label(c,'lap'+p.i,`${p.lap+1}/3`,p.x,2,8);c.draw('energy'+p.i,'box',{x:p.x,y:.2,z:9,sx:3.4*p.energy/100,sy:.15,sz:.4,color:p.energy<20?'#e38d91':'#9dc28a'});}},timeout(){c.complete([],'5분 안에 완주한 선수가 없습니다');}};
}
function avalanche(c){
 c.limit=Infinity;c.view={size:23,eye:[0,23,20],target:[0,0,0]};const obstacles=Array.from({length:34},(_,i)=>({i,x:c.rand(-6.5,6.5),at:14+i*5,type:i%3===0?'ramp':'rock'}));let snow=-14,lead=0;
 c.players.forEach(p=>{p.distance=0;p.x=(p.i-1.5)*3;p.z=5;p.speed=4;p.boost=0;p.stun=0;p.air=0;p.phase=c.rand();p.rate=c.rand(2.8,4);p.hit=new Set();});
 return{update(dt){snow+=dt*(4.1+c.time*.025);const arrivals=[];for(const p of c.players){if(!p.alive)continue;const front=obstacles.filter(o=>!p.hit.has(o.i)&&o.at>p.distance-1&&o.at<p.distance+12).sort((a,b)=>a.at-b.at)[0];const target=front?front.type==='ramp'?front.x:Math.abs(p.x-front.x)<1.8?clamp(front.x+(p.x>=front.x?2:-2),-6.5,6.5):p.x:p.x;const q=c.input(p,{x:clamp((target-p.x)*2,-1,1),a:pulse(c.time,p.rate,p.phase)});p.x=clamp(p.x+q.x*4*dt,-7,7);p.boost=Math.max(0,p.boost-dt);p.stun=Math.max(0,p.stun-dt);p.air=Math.max(0,p.air-dt);if(q.ap)p.speed=Math.min(6.8,p.speed+.38);p.speed=Math.max(3.7,p.speed-dt*.65);const v=p.stun?1.5:p.speed+(p.boost?2:0),old=p.distance;p.distance+=v*dt;for(const o of obstacles)if(!p.hit.has(o.i)&&Math.abs(o.at-p.distance)<.7&&Math.abs(o.x-p.x)<1.15){p.hit.add(o.i);if(o.type==='rock'&&!p.air){p.stun=1.1;p.speed=3.7;}else if(o.type==='ramp'){p.boost=1.7;p.air=1;}}p.y=p.air?Math.sin(p.air*Math.PI)*2:0;p.pose=p.air?'jump':'balance';if(p.distance<snow)c.eliminate(p);if(p.distance>=185)arrivals.push({i:p.i,t:(185-old)/v});p.score=Math.floor(p.distance);}first(c,arrivals,'눈사태를 피해 결승점 선착');if(!c.players.some(p=>p.alive))c.complete([],'모두 눈사태에 휩쓸렸습니다');lead=Math.max(...c.players.filter(p=>p.alive).map(p=>p.distance),snow);for(const p of c.players)p.z=5-(p.distance-lead)*.5;c.hint('좌우로 바위 피하기 · A 반복으로 폴 밀기 · 경사로를 타면 점프 가속');},render(){c.arena({width:18,depth:30,color:'#e6ebdf'});for(const o of obstacles){const z=5-(o.at-lead)*.5;if(z< -15||z>15)continue;c.draw('obstacle'+o.i,o.type==='rock'?'sphere':'box',{x:o.x,y:o.type==='rock'?.6:.15,z,sx:1.8,sy:o.type==='rock'?1.3:.5,sz:2,rx:o.type==='ramp'?-.25:0,color:o.type==='rock'?'#a2adb0':'#a6d0d4'});}const z=5-(snow-lead)*.5;for(let i=0;i<9;i++)c.draw('avalanche'+i,'sphere',{x:(i-4)*2,y:.5,z,sx:3,sy:3,sz:3,color:'#f6f0df'});for(const p of c.players)c.draw('ski'+p.i,'box',{x:p.x,y:p.y,z:p.z,sx:1.1,sy:.1,sz:2,color:p.color});}};
}
function domination(c){
 c.limit=10;c.players.forEach(p=>{p.x=(p.i-1.5)*4;p.z=5;p.rate=c.rand(5.5,8);p.phase=c.rand();});return{update(){for(const p of c.players){const q=c.input(p,{a:pulse(c.time,p.rate,p.phase)});if(q.ap&&c.time<=10&&p.score<300)c.points(p);p.pose=q.a?'hit':'idle';}c.hint('10초 동안 A 빠르게 반복 · 한 번 누를 때마다 도미노 하나');},render(){c.arena({width:20,depth:20,color:'#b5c4a0'});for(const p of c.players){c.draw('button'+p.i,'cylinder',{x:p.x,y:.35,z:4,sx:1.4,sy:.7,sz:1.4,color:p.color});for(let j=0;j<Math.min(p.score,100);j++){const row=j%25,col=Math.floor(j/25);c.draw('domino'+p.i+'_'+j,'box',{x:p.x+(col-1.5)*.7,y:.55,z:3-row*.5,sx:.5,sy:1.1,sz:.2,color:j%2?p.color:cream});}label(c,'count'+p.i,String(p.score),p.x,2,6);}},timeout(){unequal(c,'세운 도미노 수');}};
}
function plunge(c){
 c.limit=Infinity;c.view={size:22,eye:[0,20,16],target:[0,0,0]};let distance=0;const items=Array.from({length:100},(_,i)=>({i,x:c.rand(-8,8),z:c.rand(-5,5),at:10+i*1.5,type:i%6===0?'bag':i%3===0?'enemy':'coin',taken:false}));c.players.forEach(p=>{p.x=(p.i-1.5)*3;p.z=0;p.hits=0;p.cool=0;});return{update(dt){distance+=dt*4;for(const p of c.players){if(!p.alive)continue;const near=items.filter(o=>!o.taken&&o.type!=='enemy'&&o.at>distance&&o.at<distance+10).sort((a,b)=>Math.hypot(p.x-a.x,p.z-a.z)+(a.at-distance)*.15-Math.hypot(p.x-b.x,p.z-b.z)-(b.at-distance)*.15)[0],q=c.input(p,near?toward(p,near.x,near.z):{});c.move(p,q,4);p.cool=Math.max(0,p.cool-dt);p.pose='glide';for(const o of items)if(!o.taken&&Math.abs(o.at-distance)<.8&&dist(o,p)<.9){if(o.type==='enemy'){if(!p.cool){p.hits++;p.cool=1;if(p.hits>=4)c.eliminate(p);}}else{o.taken=true;c.points(p,o.type==='bag'?5:1);}}}if(distance>items.at(-1).at+5||!c.players.some(p=>p.alive))c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'획득한 코인은 탈락해도 유지합니다');c.hint('방향으로 활공 · 코인 1 / 주머니 5 · 적과 네 번 부딪히면 낙하 종료');},render(){c.arena({width:21,depth:15,color:'#a3d3d0'});for(const o of items){const dy=(o.at-distance)*.3;if(o.taken||dy< -2||dy>6)continue;c.draw('drop'+o.i,o.type==='enemy'?'cone':o.type==='bag'?'sphere':'cylinder',{x:o.x,y:-dy,z:o.z,sx:o.type==='coin'?.5:1,sy:o.type==='coin'?.16:.8,sz:o.type==='coin'?.5:1,color:o.type==='enemy'?'#8a9cba':'#e8bf62'});}for(const p of c.players)if(p.alive){const size=1.8-p.hits*.27;c.draw('parachute'+p.i,'sphere',{x:p.x,y:3,z:p.z,sx:size,sy:size,sz:size,color:p.color});label(c,'hp'+p.i,`${4-p.hits}♥`,p.x,4.4,p.z,2);}}};
}
function quickDraw(c){
 c.limit=Infinity;c.view={size:18,eye:[0,12,23],target:[0,3,0]};let balloons=[],target=0,round=0,age=0,reveal=0;
 c.players.forEach(p=>{p.x=(p.i-1.5)*4;p.z=5;p.cursor={x:0,y:3};p.lag=c.rand(.25,.65);p.cool=0;});function next(){round++;age=0;reveal=c.rand(1.3,2.8);target=c.int(0,3);balloons=Array.from({length:c.int(6,8)},(_,i)=>({i,x:(i-3)*2.2,y:c.rand(2,5.5),color:i===0?target:c.int(0,3)}));}next();
 return{update(dt){age+=dt;const shots=[];for(const p of c.players){p.cool=Math.max(0,p.cool-dt);const b=balloons.find(b=>b.color===target),q=c.input(p,()=>({x:age>reveal+p.lag?clamp((b.x-p.cursor.x)*3,-1,1):0,z:age>reveal+p.lag?clamp((p.cursor.y-b.y)*3,-1,1):0,a:age>reveal+p.lag&&Math.hypot(b.x-p.cursor.x,b.y-p.cursor.y)<.4&&p.cool===0}));if(p.i===0&&q.pointer.frontValid){p.cursor.x=clamp(q.pointer.frontX,-10,10);p.cursor.y=clamp(q.pointer.frontY,1,7);}else{p.cursor.x=clamp(p.cursor.x+q.x*9*dt,-10,10);p.cursor.y=clamp(p.cursor.y-q.z*7*dt,1,7);}if((q.ap||p.i===0&&q.pointer.pressed)&&!p.cool){p.cool=.16;const hit=balloons.filter(b=>Math.hypot(b.x-p.cursor.x,b.y-p.cursor.y)<.7).sort((a,b)=>Math.hypot(a.x-p.cursor.x,a.y-p.cursor.y)-Math.hypot(b.x-p.cursor.x,b.y-p.cursor.y))[0];if(age>reveal&&hit?.color===target)shots.push(p);}}if(shots.length){for(const p of shots)c.points(p);const winners=shots.filter(p=>p.score>=3);if(winners.length)c.complete(winners.map(p=>p.i),'올바른 풍선을 세 번 선취');else next();}c.hint(age<reveal?'깃발이 나올 때까지 기다리세요':'방향으로 조준 / A 발사 · 깃발과 같은 풍선을 먼저 맞히세요 · 1P 마우스도 가능');},render(){c.arena({width:23,depth:12,color:'#c3c9a5'});c.draw('train','box',{x:0,y:.7,z:-3,sx:21,sy:1.4,sz:2,color:'#9fbaba'});for(const b of balloons){c.draw('balloon'+b.i,'sphere',{x:b.x,y:b.y,z:0,sx:1.2,sy:1.4,sz:1,color:colors[b.color]});label(c,'symbol'+b.i,String(b.color+1),b.x,b.y,.7,3);}c.draw('flag','box',{x:0,y:7,z:-3,sx:2,sy:1.2,sz:.15,color:age>reveal?colors[target]:cream});if(age>reveal)label(c,'flagmark',String(target+1),0,7,-2.5,3);for(const p of c.players)c.draw('aim'+p.i,'ring',{x:p.cursor.x,y:p.cursor.y,z:.8,sx:1,sy:1,sz:1,color:p.color});}};
}
function claw(c){
 c.limit=60;c.view={size:19,eye:[0,15,26],target:[0,3,0]};const target=c.int(0,3);c.players.forEach(p=>{p.base=(p.i-1.5)*6;p.x=p.base;p.z=4;p.column=0;p.row=0;p.cool=c.rand(.7,1.1);p.next=0;p.doors=Array.from({length:12},(_,i)=>({i,type:c.int(0,3),phase:c.rand(0,4),closed:0}));p.doors[0].type=target;});
 const open=d=>(c.time+d.phase)%4<2.7&&d.closed<=0;
 return{update(dt){const done=[];for(const p of c.players){p.cool=Math.max(0,p.cool-dt);p.next=Math.max(0,p.next-dt);p.doors.forEach(d=>d.closed=Math.max(0,d.closed-dt));const goal=p.doors.find(d=>open(d)&&d.type===target),row=goal?Math.floor(goal.i/4):p.row,col=goal?goal.i%4:p.column;const q=c.input(p,()=>({b:col!==p.column&&pulse(c.time,4,p.i*.1),z:Math.sign(row-p.row),a:!!goal&&col===p.column&&row===p.row&&p.cool===0}));if(q.bp)p.column=(p.column+1)%4;if(q.cp)p.column=(p.column+3)%4;if(Math.abs(q.z)>.5&&p.next===0){p.row=clamp(p.row+Math.sign(q.z),0,2);p.next=.18;}if(q.ap&&!p.cool){p.cool=.85;const d=p.doors[p.row*4+p.column];if(open(d)){d.closed=1;if(d.type===target){c.points(p);d.type=c.int(0,3);}if(p.score>=3)done.push(p.i);}}}if(done.length)c.complete(done,'지명 수배 대상을 세 번 포획');c.hint('B/C로 좌우 칸 회전 · 위아래 높이 · A 집기 · 수배 번호 '+(target+1));},render(){for(const p of c.players){c.draw('tower'+p.i,'box',{x:p.base,y:3,z:0,sx:5.7,sy:6,sz:1,color:'#b4b8a3'});for(const d of p.doors){const x=p.base+(d.i%4-1.5)*1.3,y=5-Math.floor(d.i/4)*1.7;c.draw('door'+p.i+'_'+d.i,'box',{x,y,z:.6,sx:1.05,sy:1.4,sz:.15,color:open(d)?colors[d.type]:'#7f9693'});if(open(d))label(c,'type'+p.i+'_'+d.i,String(d.type+1),x,y,.85,2.7);}c.draw('claw'+p.i,'ring',{x:p.base+(p.column-1.5)*1.3,y:5-p.row*1.7,z:1,sx:1.2,sy:1.5,sz:1,color:p.color});label(c,'wanted'+p.i,`수배 ${target+1} · ${p.score}/3`,p.base,7,0,4);}},timeout(){c.complete([],'시간 안에 세 마리를 잡지 못했습니다');}};
}
function breather(c){
 c.limit=Infinity;c.players.forEach(p=>{p.x=(p.i-1.5)*3.5;p.z=0;p.next=0;p.seq=0;p.interval=c.rand(.09,.16);p.air=0;p.done=false;});
 return{update(){for(const p of c.players){const key=p.seq%2?'b':'a',q=c.input(p,()=>{if(c.time>=5||c.time<p.next)return{};p.next=c.time+p.interval;return{[key]:true};});if(c.time<5&&q[key+'p']){p.seq++;p.air+=.16;}if(c.time>=5){p.score=+(Math.min(c.time-5,p.air)).toFixed(2);p.done=c.time-5>=p.air;p.y=p.done?0:-1;p.pose=p.done?'idle':'swim';}}if(c.time>=5&&c.players.every(p=>p.done))unequal(c,'가장 오래 숨 참기');c.hint(c.time<5?`${Math.ceil(5-c.time)}초 · A/B를 번갈아 반복해서 공기를 모으세요`:'물속에서 기다리세요 · 모은 공기에 따라 숨 참는 기록이 결정됩니다');},render(){c.arena({width:18,depth:12,color:'#92c6ce'});for(const p of c.players){c.draw('dock'+p.i,'box',{x:p.x,y:-.3,z:3,sx:2.7,sy:.4,sz:5,color:'#c9b28b'});if(c.time<5)label(c,'air'+p.i,'●'.repeat(Math.min(8,Math.ceil(p.air))),p.x,2,0,3);else label(c,'time'+p.i,p.score.toFixed(2)+' s',p.x,2,0,3);}}};
}
function candle(c){
 c.limit=30;c.bounds={x:7,z:5};let flame=5,shots=[],serial=0;c.players.forEach(p=>{p.x=p.i===0?0:(p.i-2)*5;p.z=p.i===0?0:-3;p.cool=c.rand(.3,1);p.aim={x:0,z:1};p.seen={x:0,z:0};p.wander={x:c.rand(-5,5),z:c.rand(-3,3)};p.wanderAt=0;});
 return{update(dt){const solo=c.players[0];for(const p of c.players){p.cool=Math.max(0,p.cool-dt);let goal;if(!p.i)goal=escape(p,c.players.slice(1));else{if(dist(p,solo)<2+flame*.5)p.seen={x:solo.x,z:solo.z};if(c.time>=p.wanderAt){p.wanderAt=c.time+1.2;p.wander={x:c.rand(-5,5),z:c.rand(-3,3)};}goal=dist(p,solo)<2+flame*.5?p.seen:p.wander;}const q=c.input(p,()=>({...toward(p,goal.x,goal.z,!p.i||dist(p,solo)>3?1:0),a:p.i>0&&dist(p,solo)<2+flame*.5&&p.cool===0}));if(p.cool<.35)c.move(p,q,p.i?3.5:4.5);if(Math.hypot(q.x,q.z)>.1){const d=Math.hypot(q.x,q.z);p.aim={x:q.x/d,z:q.z/d};}if(p.i&&q.ap&&p.cool===0){const a=p.i>=c.humans?toward(p,p.seen.x+c.rand(-.65,.65),p.seen.z+c.rand(-.65,.65)):p.aim;shots.push({id:serial++,x:p.x,z:p.z,vx:a.x*10,vz:a.z*10,life:.7});p.cool=.9;p.pose='hit';}}for(const b of shots){b.x+=b.vx*dt;b.z+=b.vz*dt;b.life-=dt;if(b.life>0&&dist(b,solo)<.55){b.life=0;flame--;c.players.slice(1).forEach(p=>p.score=5-flame);}}shots=shots.filter(b=>b.life>0);if(flame<=0)c.complete([1,2,3],'다섯 번 물을 맞혀 촛불을 껐습니다');c.hint('1P: 방향으로 촛불 지키기 · 팀: 방향으로 이동·조준 / A 물총 · 쏘는 동안 잠깐 멈춤');},render(){c.arena({width:17,depth:13,color:'#425c64'});const p=c.players[0];c.draw('candle','cylinder',{x:p.x+.5,y:1.1,z:p.z,sx:.18,sy:.7,sz:.18,color:cream});c.draw('flame','sphere',{x:p.x+.5,y:1.6,z:p.z,sx:.2+flame*.07,sy:.3+flame*.08,sz:.2,color:'#efc35e',glow:true});c.draw('glow','cylinder',{x:p.x,y:.025,z:p.z,sx:3+flame,sy:.04,sz:3+flame,color:'#a8a781',opacity:.2});for(const b of shots)c.draw('water'+b.id,'sphere',{x:b.x,y:1.4,z:b.z,sx:.3,sy:.3,sz:.3,color:'#aedce2',glow:true});for(const o of c.players.slice(1)){const visible=dist(o,p)<2+flame*.5;o.visible=visible;const d=o.aim;c.draw('watergun'+o.i,'box',{x:o.x+d.x*.5,y:1,z:o.z+d.z*.5,sx:.5,sy:.3,sz:.7,color:'#91c1cc',opacity:visible?1:.2});}label(c,'flamecount',`촛불 ${Math.max(0,flame)} / 5`,0,4,-5,5);},timeout(){c.complete([0],'30초 동안 촛불을 지켰습니다');}};
}
function trees(c){
 c.limit=45;c.bounds={x:7,z:5};let peels=[],serial=0,next=2;c.players.forEach(p=>{p.x=p.i===0?0:(p.i-2)*5;p.z=p.i===0?3:-3;p.heading=0;p.stun=0;p.boost=0;p.cool=0;});
 return{update(dt){const solo=c.players[0];if(c.time>next){next+=2;peels.push({id:serial++,x:c.rand(-6,6),z:c.rand(-4,4),gold:c.rand()<.3,life:10});}for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.boost=Math.max(0,p.boost-dt);p.cool=Math.max(0,p.cool-dt);const angle=Math.atan2(solo.x-p.x,-(solo.z-p.z)),wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));const escapeGoal=escape(p,c.players.slice(1));const q=c.input(p,()=>p.i?{x:clamp(wrap(angle-p.heading)*2,-1,1),a:Math.abs(wrap(angle-p.heading))<1.1,b:false}:toward(p,escapeGoal.x,escapeGoal.z));if(!p.stun){if(!p.i)c.move(p,q,4.5*(p.boost?1.6:1));else{p.heading+=q.x*dt*2;const v=((q.a?1:0)-(q.b?1:0))*3.3*(p.boost?1.6:1);p.x=clamp(p.x+Math.sin(p.heading)*v*dt,-7,7);p.z=clamp(p.z-Math.cos(p.heading)*v*dt,-5,5);p.rotation=Math.PI/2-p.heading;}}for(const b of peels)if(b.life>0&&dist(p,b)<.7){b.life=0;if(b.gold)p.boost=3;else p.stun=1.1;}}for(let i=1;i<4;i++)for(let j=i+1;j<4;j++){const a=c.players[i],b=c.players[j],d=dist(a,b);if(d<1.5){const dx=(a.x-b.x)/(d||1),dz=(a.z-b.z)/(d||1);a.x+=dx*.08;a.z+=dz*.08;b.x-=dx*.08;b.z-=dz*.08;if(!a.cool&&!b.cool){a.stun=b.stun=2;a.cool=b.cool=2.5;}}}if(c.players.slice(1).some(p=>dist(p,solo)<1.05))c.complete([1,2,3],'나무 로봇으로 도망자를 잡았습니다');for(const b of peels)b.life-=dt;peels=peels.filter(b=>b.life>0);c.hint('1P 방향으로 도망 · 팀 좌우 회전/A 전진/B 후진 · 로봇끼리 부딪히면 2초 정지 · 금 바나나는 가속');},render(){c.arena({width:17,depth:13,color:'#aabf91'});for(const p of c.players.slice(1)){c.draw('stump'+p.i,'cylinder',{x:p.x,y:.4,z:p.z,sx:1.8,sy:.8,sz:1.8,color:p.stun?'#abaaa0':'#bd986c'});c.draw('front'+p.i,'box',{x:p.x+Math.sin(p.heading)*.9,y:.3,z:p.z-Math.cos(p.heading)*.9,sx:.5,sy:.4,sz:.5,color:p.color});if(p.stun)label(c,'broken'+p.i,'✶',p.x,2.5,p.z,1.5);}for(const b of peels)c.draw('peel'+b.id,'cone',{x:b.x,y:.18,z:b.z,sx:.8,sy:.35,sz:.8,color:b.gold?'#e7be57':'#e7d68c'});},timeout(){c.complete([0],'45초 도망 성공');}};
}
function hopPop(c){
 c.limit=45;c.bounds={x:6,z:5};c.players.forEach(p=>{p.x=p.i===0?0:(p.i-2)*4;p.z=p.i===0?-3:2;p.hop=0;p.wait=0;p.jumpX=0;p.jumpZ=0;p.landed=-5;p.gait=0;});
 return{update(dt){const solo=c.players[0],alive=c.players.slice(1).filter(p=>p.alive);for(const p of c.players){if(!p.alive)continue;const target=!p.i?alive.sort((a,b)=>dist(p,a)-dist(p,b))[0]:escape(p,[solo],5.5,4.5);const q=c.input(p,()=>({...toward(p,target?.x??0,target?.z??0),a:p.i>0&&p.hop===0}));if(!p.i){c.move(p,q,3.9);p.pose='run';}else{if(p.hop===0&&q.ap){const perfect=c.time-p.landed<.15;p.hop=.001;p.vy=perfect?7:5.7;p.jumpX=q.x*(perfect?5.6:4.2);p.jumpZ=q.z*(perfect?5.6:4.2);}if(p.hop>0){p.vy-=17*dt;p.hop=Math.max(0,p.hop+p.vy*dt);p.x=clamp(p.x+p.jumpX*dt,-6,6);p.z=clamp(p.z+p.jumpZ*dt,-5,5);if(!p.hop)p.landed=c.time;}p.y=p.hop;p.pose='jump';}}for(const p of c.players.slice(1))if(p.alive&&dist(p,solo)<1.1&&p.hop<.65)c.eliminate(p);if(!c.players.slice(1).some(p=>p.alive))c.complete([0],'세 풍선을 모두 터뜨렸습니다');c.hint('1P 방향으로 가시공 이동 · 팀 방향+A 점프 · 착지 직후 다시 A를 누르면 멀리 뛰어요');},render(){c.arena({width:15,depth:13,color:'#d0c49f'});for(const p of c.players)if(p.alive){c.draw('orb'+p.i,'sphere',{x:p.x,y:.65+p.y,z:p.z,sx:1.6,sy:1.6,sz:1.6,color:p.i?p.color:'#858d91',opacity:p.i?.35:1});if(!p.i)for(let i=0;i<10;i++){const a=i*TAU/10;c.draw('spike'+i,'cone',{x:p.x+Math.cos(a)*.8,y:.6,z:p.z+Math.sin(a)*.8,sx:.4,sy:.7,sz:.4,rz:Math.PI/2,ry:-a,color:cream});}}},timeout(){c.complete([1,2,3],'풍선이 하나 이상 남았습니다');}};
}
export const games={'Manta Rings':manta,'Slime Time':slime,'Mario Medley':medley,'Avalanche!':avalanche,'Domination':domination,'Paratrooper Plunge':plunge,"Toad's Quick Draw":quickDraw,'Long Claw of the Law':claw,'Take a Breather':breather,'Candlelight Flight':candle,'Tree Stomp':trees,'Hop or Pop':hopPop};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(n=>[n,['mp4']]));
const own='캐릭터·경기장·물리 수치는 새로 제작했습니다. ';
export const notes={
'Manta Rings':own+'고리 1점/금 고리 3점, 적별 1·2·3점 감점입니다. 좌우·수심 이동과 A 반복 전진을 사용하며 새 수중 코스 끝에서 집계합니다.',
'Slime Time':own+'A 반복으로 늘어나는 젤의 저항을 이기고 중앙까지 갑니다. 30초 안에 먼저 탈출해야 합니다.',
'Mario Medley':own+'평영 A+B 동시, 배영 C/D 번갈아(원작 L/R), 자유형 B/A 번갈아입니다. 지치면 느려지고 쉬면 회복합니다. 3구간 선착순, 300초 제한입니다.',
'Avalanche!':own+'뒤에서 오는 눈사태, 바위 충돌, 경사로 점프 가속을 반영한 새 스키 코스입니다. A는 폴 밀기이고 좌우로 방향을 바꿉니다.',
'Domination':own+'10초 동안 A 입력 횟수로 도미노 수를 정합니다. 연타를 실제 누름으로 세며 시스템상 300개 상한을 둡니다.',
'Paratrooper Plunge':own+'코인 1점/주머니 5점, 적과 네 번 접촉하면 탈락하되 얻은 코인은 유지합니다. 새 낙하 경로를 끝까지 이동하면 집계합니다.',
"Toad's Quick Draw":own+'같은 색 깃발과 풍선을 매칭해 먼저 맞히면 1점, 3점 선취입니다. 틀린 풍선 감점은 없습니다. 방향/A 또는 1P 포인터로 조준·발사합니다.',
'Long Claw of the Law':own+'수배한 동일 대상을 열리는 문에서 세 번 잡습니다. 원작 L/R 회전은 B/C 칸 회전, 방향 위아래 높이/A 집기로 바꿨습니다.',
'Take a Breather':own+'5초간 A/B 교대 입력(원작 L/R)으로 모은 공기에 비례해 잠수합니다. 버튼당 호흡량은 브라우저판 수치입니다.',
'Candlelight Flight':own+'팀이 A 물총을 쏘면 잠시 이동을 멈춥니다. 다섯 번 맞히면 팀 승리, 30초를 버티면 촛불을 든 1P 승리입니다. 불이 작아질수록 보이는 영역도 줄어듭니다.',
'Tree Stomp':own+'로봇의 전후진·회전, 로봇끼리 충돌 시 2초 정지, 바나나 미끄러짐과 금 바나나 가속을 구현했습니다. 45초 추격전입니다.',
'Hop or Pop':own+'1P 가시공과 세 풍선의 추격전입니다. 풍선은 A로만 이동 점프하며 착지 직후 누르면 멀리 뜁니다. 45초 한 명 이상 생존하면 팀 승리입니다.'};
