import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,colors=['#e490ab','#91bec9','#e6be69','#a3bca0'],cream='#f3e7cb',ink='#35565e';
const label=(c,id,text,x,y,z,w=4)=>c.draw(id,'text',{x,y,z,sx:w,sy:w/4,text,color:ink});
const pair=t=>[t*2,t*2+1];const teamScore=(c,s,reason)=>c.complete(s[0]===s[1]?[]:pair(s[0]>s[1]?0:1),reason);
function breakers(c){
 c.limit=Infinity;c.view={size:17,eye:[0,8,25],target:[0,3,0]};const W=12,H=9,grid=Array.from({length:H},()=>Array(W).fill(null)),vectors=[[0,-1],[1,0],[0,1],[-1,0]];let serial=0;
 const cells=s=>[{x:s.x,y:s.y,type:s.types[0]},{x:s.x+vectors[s.rot][0],y:s.y+vectors[s.rot][1],type:s.types[1]}];
 const valid=s=>cells(s).every(b=>b.x>=0&&b.x<W&&b.y<H&&(b.y<0||grid[b.y][b.x]===null));
 const spawn=p=>{const types=[c.rand()<.1?-1:c.int(0,3),c.int(0,3)];p.block={x:p.i*3+1,y:0,rot:0,types,fall:0,cool:.25,move:0};p.plan=0;let best=-Infinity;for(let x=0;x<W;x++){let y=0;while(y<H&&grid[y][x]===null)y++;const value=(y-1)*.5+(y<H&&grid[y][x]?.type===types[0]?5:0)+(types[0]===types[1]?1:0);if(value>best){best=value;p.plan=x;}}};
 function settle(p){let chain=1;for(let guard=0;guard<20;guard++){for(let x=0;x<W;x++){const col=[];for(let y=H-1;y>=0;y--)if(grid[y][x])col.push(grid[y][x]);for(let y=H-1;y>=0;y--)grid[y][x]=col[H-1-y]||null;}const seen=new Set(),remove=new Set();for(let y=0;y<H;y++)for(let x=0;x<W;x++){const cell=grid[y][x];if(!cell||seen.has(y*W+x)||cell.type<0)continue;const group=[],todo=[[x,y]];while(todo.length){const [a,b]=todo.pop(),key=b*W+a;if(seen.has(key)||grid[b][a]?.type!==cell.type)continue;seen.add(key);group.push(key);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])if(a+dx>=0&&a+dx<W&&b+dy>=0&&b+dy<H)todo.push([a+dx,b+dy]);}if(group.length>=3)group.forEach(i=>remove.add(i));}for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(grid[y][x]?.type===-1&&[[1,0],[-1,0],[0,1],[0,-1]].every(([dx,dy])=>x+dx<0||x+dx>=W||y+dy<0||y+dy>=H||grid[y+dy][x+dx]))for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(x+dx>=0&&x+dx<W&&y+dy>=0&&y+dy<H&&grid[y+dy][x+dx])remove.add((y+dy)*W+x+dx);if(!remove.size)break;c.points(p,remove.size*chain);for(const key of remove)grid[Math.floor(key/W)][key%W]=null;chain++;}}
 c.players.forEach(p=>{p.x=(p.i-1.5)*3.6;p.z=3;p.y=0;p.scale=.65;p.block=null;spawn(p);});
 return{update(dt){const winners=[];for(const p of c.players){const blocked=[0,1,2].every(i=>grid[0][p.i*3+i]!==null);p.alive=!blocked;if(blocked){p.block=null;c.input(p,{});continue;}if(!p.block)spawn(p);const s=p.block;s.cool=Math.max(0,s.cool-dt);s.move=Math.max(0,s.move-dt);const q=c.input(p,()=>({x:s.x===p.plan?0:Math.sign(p.plan-s.x),z:s.x===p.plan?1:0}));if(!s.cool){if(q.ap||q.bp||q.cp||q.dp){const rot=(s.rot+(q.cp||q.dp?2:q.ap?1:3))%4;if(valid({...s,rot}))s.rot=rot;}if(Math.abs(q.x)>.5&&!s.move){const x=s.x+Math.sign(q.x);if(valid({...s,x}))s.x=x;s.move=.13;}s.fall+=dt*(q.z>.5?11:1.6);if(s.fall>=1){s.fall=0;if(valid({...s,y:s.y+1}))s.y++;else{for(const b of cells(s))if(b.y>=0&&b.y<H&&grid[b.y][b.x]===null)grid[b.y][b.x]={type:b.type,id:serial++};p.block=null;settle(p);if(p.score>=100)winners.push(p.i);}}}}if(winners.length)c.complete(winners,'먼저 100점 달성');else{const active=c.players.filter(p=>![0,1,2].every(i=>grid[0][p.i*3+i]!==null));if(active.length<2&&c.time>2)c.complete(active.map(p=>p.i),'블록을 놓을 공간이 남은 선수');}c.hint('좌우 이동/아래 빠르게 내리기 · A/B 회전/C 뒤집기 · 3개 같은 모양 연결 · 상대 칸에도 놓을 수 있어요');},render(){c.draw('board','box',{x:0,y:3.5,z:-.5,sx:14.7,sy:10.7,sz:.5,color:'#c5c7b3'});const draw=(id,b,color)=>{const x=(b.x-5.5)*1.15,y=(8-b.y)*1.05-.7;c.draw(id,b.type<0?'sphere':'box',{x,y,z:0,sx:1.03,sy:.94,sz:.5,color:b.type<0?ink:colors[b.type]});if(color)c.draw(id+'outline','ring',{x,y,z:.35,sx:.7,sy:.7,sz:1,color});};for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(grid[y][x])draw('block'+grid[y][x].id,{...grid[y][x],x,y});for(const p of c.players){if(p.block)cells(p.block).filter(b=>b.y>=0).forEach((b,i)=>draw('fall'+p.i+'_'+i,b,p.color));label(c,'score'+p.i,String(p.score),p.x,1,3,3);}for(let i=0;i<5;i++)c.draw('division'+i,'box',{x:(i*3-6)*1.15,y:3.5,z:.4,sx:.035,sy:10,sz:.04,color:cream});}};
}
function treasure(c){
 c.limit=60;c.view={size:22,eye:[0,28,15],target:[0,0,0]};const W=17,H=13,map=Array.from({length:H},()=>Array(W).fill(1));map[1][1]=0;const stack=[[1,1]];while(stack.length){const [x,y]=stack.at(-1),options=c.shuffle([[2,0],[-2,0],[0,2],[0,-2]]).filter(([dx,dy])=>x+dx>0&&x+dx<W-1&&y+dy>0&&y+dy<H-1&&map[y+dy][x+dx]);if(!options.length){stack.pop();continue;}const [dx,dy]=options[0];map[y+dy/2][x+dx/2]=0;map[y+dy][x+dx]=0;stack.push([x+dx,y+dy]);}
 const spaces=[];for(let y=1;y<H;y+=2)for(let x=1;x<W;x+=2)spaces.push({x,y});const places=c.shuffle(spaces).slice(0,4),items=places.map((v,i)=>({...v,i,taken:false}));
 const starts=[[1,1],[15,11],[15,1],[1,11]];c.players.forEach(p=>{p.gx=starts[p.i][0];p.gy=starts[p.i][1];p.baseX=p.i%2?6:-6;p.baseZ=p.i<2?-4:4;p.map=false;p.cool=0;p.has=false;p.pace=c.rand(.18,.26);p.scale=.45;});
 function path(s,goal){const queue=[[s.gx,s.gy]],from=new Map([[s.gy*W+s.gx,null]]);for(let i=0;i<queue.length;i++){const [x,y]=queue[i];if(x===goal.x&&y===goal.y){let key=y*W+x,prev=from.get(key);while(prev!==null&&prev!==s.gy*W+s.gx){key=prev;prev=from.get(key);}return{x:key%W,y:Math.floor(key/W)};}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=ny*W+nx;if(nx>=0&&nx<W&&ny>=0&&ny<H&&!map[ny][nx]&&!from.has(k)){from.set(k,y*W+x);queue.push([nx,ny]);}}}return{x:s.gx,y:s.gy};}
 return{update(dt){for(const p of c.players){p.cool=Math.max(0,p.cool-dt);const buddy=c.players[p.i^1],goal=p.has?buddy.has?{x:buddy.gx,y:buddy.gy}:items[buddy.i]:items[p.i],next=path(p,goal),q=c.input(p,()=>({x:c.time>3?Math.sign(next.x-p.gx):0,z:c.time>3?Math.sign(next.y-p.gy):0}));if(q.cp||q.dp)p.map=!p.map;if(c.time>3&&!p.map&&!p.cool&&(Math.abs(q.x)>.5||Math.abs(q.z)>.5)){const dx=Math.abs(q.x)>Math.abs(q.z)?Math.sign(q.x):0,dy=dx?0:Math.sign(q.z),x=p.gx+dx,y=p.gy+dy;if(x>=0&&x<W&&y>=0&&y<H&&!map[y][x]){p.gx=x;p.gy=y;}p.cool=p.i<c.humans?.12:p.pace;}if(!p.has&&p.gx===items[p.i].x&&p.gy===items[p.i].y){p.has=true;items[p.i].taken=true;p.score=1;}p.x=p.baseX+(p.gx-8)*.5;p.z=p.baseZ+(p.gy-6)*.5;}const done=[];for(let t=0;t<2;t++){const a=c.players[t*2],b=c.players[t*2+1];if(a.has&&b.has&&Math.abs(a.gx-b.gx)+Math.abs(a.gy-b.gy)<=1)done.push(...pair(t));}if(done.length)c.complete(done,'열쇠와 보물상자를 찾아 동료와 만났습니다');c.hint(c.time<3?'미로와 물건의 위치를 기억하세요':'방향으로 미로 이동/C 또는 D 지도 · 지도에는 벽이 안 보이고 움직일 수 없습니다');},render(){for(const p of c.players){c.draw('floor'+p.i,'box',{x:p.baseX,y:-.2,z:p.baseZ,sx:9,sy:.3,sz:7,color:p.i<2?'#d9bcc0':'#b5cdd1'});for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(map[y][x]&&!p.map&&(c.time<3||Math.abs(x-p.gx)+Math.abs(y-p.gy)<5))c.draw('wall'+p.i+'_'+y+'_'+x,'box',{x:p.baseX+(x-8)*.5,y:.25,z:p.baseZ+(y-6)*.5,sx:.48,sy:.55,sz:.48,color:'#b4b39f'});for(const item of items)if(!item.taken&&(p.map||c.time<3||Math.abs(item.x-p.gx)+Math.abs(item.y-p.gy)<4)){const x=p.baseX+(item.x-8)*.5,z=p.baseZ+(item.y-6)*.5;c.draw('item'+p.i+'_'+item.i,item.i%2?'ring':'box',{x,y:.7,z,sx:.45,sy:.45,sz:.45,color:item.i<2?'#db8da5':'#8baeca'});}if(p.has)label(c,'held'+p.i,p.i%2?'열쇠':'상자',p.x,1.8,p.z,2.8);label(c,'who'+p.i,`${p.i+1}P`+(p.map?' 지도':''),p.baseX,1.4,p.baseZ+3.5,3);}},timeout(){c.complete([],'60초 안에 보물을 열지 못했습니다');}};
}
function orders(c){
 c.limit=Infinity;c.view={size:23,eye:[0,24,18],target:[0,0,0]};let age=0,round=0,request=[],foods=[],rotation=0;const teams=[0,1].map(()=>({score:0,chosen:[],removed:new Set()}));const names=['빵','꼬치','감자','음료','아이스'];c.players.forEach(p=>{p.base=p.i<2?-5:5;p.x=p.base+(p.i%2?3:-3);p.z=3;p.wait=c.rand(.4,.8);});
 const pos=i=>({x:Math.cos(i*TAU/10+rotation)*3,z:Math.sin(i*TAU/10+rotation)*3});function next(){round++;age=0;request=[c.int(0,4),c.int(0,4)];foods=c.shuffle([0,0,1,1,2,2,3,3,4,4]);rotation=0;teams.forEach(t=>{t.chosen=[];t.removed.clear();});}next();
 return{update(dt){age+=dt;if(age>2&&age<4)rotation+=dt*3;const claim=[];for(const p of c.players){const team=teams[Math.floor(p.i/2)],wanted=[...request];for(const n of team.chosen){const i=wanted.indexOf(n);if(i>=0)wanted.splice(i,1);}const index=foods.findIndex((f,i)=>!team.removed.has(i)&&wanted.includes(f)),target=pos(Math.max(0,index));const q=c.input(p,()=>({...toward(p,p.base+target.x,target.z,age>4+p.wait?1:0),a:age>4+p.wait&&dist({x:p.x-p.base,z:p.z},target)<.8}));if(age>4){c.move(p,q,4,false);p.x=clamp(p.x,p.base-4,p.base+4);p.z=clamp(p.z,-4.5,4.5);if(q.ap){const near=foods.map((_,i)=>({i,...pos(i)})).filter(v=>!team.removed.has(v.i)&&dist(v,{x:p.x-p.base,z:p.z})<1).sort((a,b)=>dist(a,{x:p.x-p.base,z:p.z})-dist(b,{x:p.x-p.base,z:p.z}))[0];if(near){team.removed.add(near.i);if(wanted.includes(foods[near.i]))team.chosen.push(foods[near.i]);}}}}for(let t=0;t<2;t++)if(teams[t].chosen.length>=2)claim.push(t);if(claim.length){claim.forEach(t=>{teams[t].score++;pair(t).forEach(i=>c.players[i].score=teams[t].score);});const win=claim.filter(t=>teams[t].score>=3);if(win.length)c.complete(win.flatMap(pair),'주문을 세 번 먼저 완성');else next();}else if(age>=19){if(round>=10)c.complete([],'장기 대결 종료');else next();}c.hint(age<2?'10개 음식의 위치를 기억하세요':age<4?'상자를 덮고 테이블이 회전합니다':`주문: ${request.map(i=>names[i]).join(' + ')} · 방향 이동/A 열기 · 남은 ${Math.ceil(19-age)}초`);},render(){for(let t=0;t<2;t++){const x=t?5:-5;c.draw('table'+t,'cylinder',{x,y:-.05,z:0,sx:8,sy:.3,sz:8,color:'#d4c6a5'});for(let i=0;i<10;i++){if(teams[t].removed.has(i))continue;const p=pos(i);c.draw('food'+t+'_'+i,age<2?'sphere':'box',{x:x+p.x,y:.4,z:p.z,sx:1,sy:.8,sz:1,color:age<2?colors[foods[i]%4]:cream});if(age<2)label(c,'foodname'+t+'_'+i,names[foods[i]],x+p.x,1.2,p.z,2.5);}label(c,'team'+t,`${teams[t].score}/3`,x,3.5,-4,4);}}};
}
function sweep(c){
 c.limit=60;const fish=Array.from({length:32},(_,i)=>({i,x:c.rand(-6,6),z:c.rand(-4,3),value:i<6?2:1,held:false,angle:c.rand(0,TAU)})),score=[0,0];c.players.forEach(p=>{p.x=(p.i-1.5)*3;p.z=3;p.net=[];p.cool=0;});
 return{update(dt){const motion=[];for(const p of c.players){const base={x:p.i<2?-7:7,z:4},target=p.net.length>=3||p.net.length&&!fish.some(f=>!f.held)?base:fish.filter(f=>!f.held).sort((a,b)=>dist(p,a)-dist(p,b))[0]||base;const q=c.input(p,()=>({...toward(p,target.x,target.z,dist(p,target)<3?.32:.9),a:target!==base&&dist(p,target)<1,c:false,b:dist(p,base)<1&&p.net.length>0}));const slow=q.c?.32:1;c.move(p,{x:q.x*slow,z:q.z*slow},4);motion.push({p,speed:Math.hypot(q.x,q.z)*slow});p.cool=Math.max(0,p.cool-dt);if(q.ap&&!p.cool&&p.net.length<3){p.cool=.35;const caught=fish.filter(f=>!f.held&&dist(p,f)<1.15).sort((a,b)=>dist(p,a)-dist(p,b)).slice(0,3-p.net.length);caught.forEach(f=>{f.held=true;p.net.push(f);});}if(q.bp&&dist(p,base)<1.4&&p.net.length){score[Math.floor(p.i/2)]+=p.net.reduce((a,f)=>a+f.value,0);p.net=[];}}for(const f of fish)if(!f.held){const threat=motion.filter(v=>v.speed>.6&&dist(v.p,f)<2.3).sort((a,b)=>dist(a.p,f)-dist(b.p,f))[0];if(threat){const d=toward(threat.p,f.x,f.z);f.x+=d.x*3*dt;f.z+=d.z*3*dt;}else{f.x+=Math.cos(f.angle+c.time*.2)*.4*dt;f.z+=Math.sin(f.angle+c.time*.2)*.4*dt;}f.x=clamp(f.x,-6.8,6.8);f.z=clamp(f.z,-4.6,3.5);}c.players.forEach(p=>p.score=score[Math.floor(p.i/2)]);if(fish.every(f=>f.held)&&c.players.every(p=>!p.net.length))teamScore(c,score,'모든 물고기를 운반했습니다');c.hint('방향 이동/C 유지로 살금살금 · A 뜰채(최대 3마리)/우리 앞 B 비우기 · 분홍 1점/금 2점');},render(){c.arena({width:18,depth:12,color:'#97c4c6'});for(const f of fish)if(!f.held)c.draw('fish'+f.i,'sphere',{x:f.x,y:.15,z:f.z,sx:.7,sy:.25,sz:.4,color:f.value===2?'#e7be5b':'#e098ac'});for(let t=0;t<2;t++)c.draw('cage'+t,'box',{x:t?7:-7,y:.4,z:4,sx:2,sy:.8,sz:2,color:t?'#96bcbf':'#d59baa',opacity:.6});for(const p of c.players){c.draw('net'+p.i,'ring',{x:p.x+.7,y:.6,z:p.z,sx:1.2,sy:1.2,sz:1,rx:-Math.PI/2,color:p.color});label(c,'load'+p.i,`${p.net.length}/3`,p.x,2,p.z,2.7);}},timeout(){teamScore(c,score,'우리 안에 담은 물고기 점수');}};
}
function fever(c){
 c.limit=60;c.bounds={x:9,z:8};const boss={x:0,z:0,phase:'aim',age:0,dx:1,dz:0},walls=Array(16).fill(true);let fires=[];c.players.forEach(p=>{p.x=(p.i%2?1:-1)*4;p.z=p.i<2?-3:3;p.goal={x:p.x,z:p.z};p.next=0;});
 return{update(dt){boss.age+=dt;if(boss.phase==='aim'){if(boss.age>=1.1){const a=c.players.filter(p=>p.alive);if(a.length){const target=c.pick(a),d=toward(boss,target.x,target.z);boss.dx=d.x;boss.dz=d.z;}boss.phase='rush';boss.age=0;}}else if(boss.phase==='rush'){boss.x+=boss.dx*9*dt;boss.z+=boss.dz*9*dt;if(Math.hypot(boss.x,boss.z)>6.3){const a=Math.atan2(boss.z,boss.x),i=Math.round((a+TAU)%TAU/TAU*16)%16;walls[i]=false;boss.x=Math.cos(a)*6.3;boss.z=Math.sin(a)*6.3;boss.phase='stun';boss.age=0;fires.push({x:c.rand(-4,4),z:c.rand(-4,4),age:0});}}else if(boss.age>=1.4){boss.phase='aim';boss.age=0;}for(const f of fires)f.age+=dt;fires=fires.filter(f=>f.age<4);for(const p of c.players){if(!p.alive)continue;if(c.time>p.next){p.next=c.time+.3;const candidates=Array.from({length:12},(_,i)=>({x:p.x+Math.cos(i*TAU/12)*2,z:p.z+Math.sin(i*TAU/12)*2})).filter(t=>Math.hypot(t.x,t.z)<5.5);p.goal=candidates.sort((a,b)=>(dist(b,boss)-Math.abs(boss.dx*(b.z-boss.z)-boss.dz*(b.x-boss.x))*.01)-(dist(a,boss)-Math.abs(boss.dx*(a.z-boss.z)-boss.dz*(a.x-boss.x))*.01))[0]||{x:0,z:0};}const q=c.input(p,toward(p,p.goal.x,p.goal.z));c.move(p,q,4.7,false);const radius=Math.hypot(p.x,p.z),a=(Math.atan2(p.z,p.x)+TAU)%TAU,i=Math.round(a/TAU*16)%16;if(radius>6.6){if(walls[i]){p.x*=6.6/radius;p.z*=6.6/radius;}else c.eliminate(p);}if(dist(p,boss)<1.5&&boss.phase==='rush'||fires.some(f=>f.age>1&&Math.hypot(p.x-f.x,p.z-f.z)<.75))c.eliminate(p);}c.lastStanding();c.hint('방향으로 돌진 피하기 · 부서진 담장 틈은 낭떠러지 · 붉은 균열 뒤 불꽃이 솟습니다');},render(){c.arena({width:14,depth:14,shape:'cylinder',color:'#b9b19b'});walls.forEach((on,i)=>{if(on){const a=i*TAU/16;c.draw('wall'+i,'box',{x:Math.cos(a)*7,y:.6,z:Math.sin(a)*7,sx:.35,sy:1.2,sz:2.6,ry:-a,color:'#a8aaa1'});}});c.draw('boss','sphere',{x:boss.x,y:1.2,z:boss.z,sx:3,sy:3,sz:3,color:boss.phase==='stun'?'#889696':'#546b72'});if(boss.phase==='aim')label(c,'warning','!',boss.x,3.6,boss.z,4);for(let i=0;i<fires.length;i++){const f=fires[i];c.draw('fire'+i,f.age<1?'cylinder':'cone',{x:f.x,y:f.age<1?.04:.9,z:f.z,sx:1.4,sy:f.age<1?.05:1.8,sz:1.4,color:'#dc9567'});}},timeout(){c.survivors('60초 생존 성공');}};
}
function butterflies(c){
 c.limit=60;const bugs=Array.from({length:45},(_,i)=>({i,x:c.rand(-7,7),z:c.rand(-4,4),y:c.rand(.6,3.2),value:i%3+1,phase:c.rand(0,TAU),caught:false}));c.players.forEach(p=>{p.x=(p.i-1.5)*3;p.z=3;p.cool=0;p.heading=0;});
 return{update(dt){for(const b of bugs){if(b.caught&&c.time>=b.returnAt){b.caught=false;b.x=c.rand(-7,7);b.z=c.rand(-4,4);}if(!b.caught){b.x=clamp(b.x+Math.sin(c.time*.5+b.phase)*dt*.6,-7.5,7.5);b.z=clamp(b.z+Math.cos(c.time*.6+b.phase)*dt*.6,-5,5);b.y=1.6+Math.sin(c.time*.8+b.phase)*1.15;}}const attacks=[];for(const p of c.players){p.cool=Math.max(0,p.cool-dt);const target=bugs.filter(b=>!b.caught).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...target?toward(p,target.x,target.z,dist(p,target)>.5?1:0):{},a:!!target&&target.y>1.5&&dist(p,target)<1.2&&p.cool===0,b:!!target&&target.y<=1.5&&dist(p,target)<1.8&&p.cool===0}));c.move(p,q,4.5);if(Math.hypot(q.x,q.z)>.1)p.heading=Math.atan2(q.z,q.x);if((q.ap||q.bp)&&!p.cool){p.cool=.5;p.swipe=q.ap?'up':'side';p.pose='hit';attacks.push({p,up:q.ap});}}for(const b of bugs)if(!b.caught){const hits=attacks.filter(a=>{const d=dist(a.p,b),angle=Math.atan2(b.z-a.p.z,b.x-a.p.x)-a.p.heading,front=Math.cos(angle)>-.1;return a.up?d<1.2&&b.y>=1:front&&d<2&&b.y<1.8;}).sort((a,d)=>dist(a.p,b)-dist(d.p,b));if(hits.length){b.caught=true;b.returnAt=c.time+c.rand(3,6);c.points(hits[0].p,b.value);}}c.hint('방향 이동 · A 위로 좁게 휘두르기/B 옆으로 넓게 · 노랑 1/분홍 2/파랑 3');},render(){c.arena({width:18,depth:13,color:'#b7c59e'});for(const b of bugs)if(!b.caught)for(const s of [-1,1])c.draw('wing'+b.i+s,'sphere',{x:b.x+s*.24,y:b.y,z:b.z,sx:.55,sy:.09,sz:.5,rz:s*Math.sin(c.time*16+b.phase)*.5,color:['','#e5c466','#df94ab','#91bacc'][b.value]});for(const p of c.players)c.draw('net'+p.i,'ring',{x:p.x+Math.cos(p.heading)*.8,y:p.cool&&p.swipe==='up'?2.5:1,z:p.z+Math.sin(p.heading)*.8,sx:1.2,sy:1.2,sz:1,rx:p.swipe==='side'?Math.PI/2:0,color:p.color});},timeout(){if(new Set(c.players.map(p=>p.score)).size===1)c.complete([],'모두 같은 점수');else c.highest('잡은 나비 점수');}};
}
function volley(c){
 c.limit=Infinity;c.view={size:22,eye:[0,23,19],target:[0,0,0]};const score=[0,0];let ball={x:-2,y:1,z:5},flight=null,serving=0,pause=1,touches=0,last=-1;
 c.players.forEach(p=>{p.x=p.i%2?2.5:-2.5;p.z=p.i<2?4:-4;p.cool=0;p.reaction=c.rand(.1,.3);p.noticeAt=0;p.miss=false;});
 function launch(from,target,duration,arc){c.players.forEach(p=>{p.noticeAt=c.time+c.rand(.1,.35);p.miss=c.rand()<.13;});flight={from:{...from},to:target,t:0,duration,arc};}
 function point(t){score[t]++;c.players.forEach(p=>p.score=score[Math.floor(p.i/2)]);if(score[t]>=5){c.complete(pair(t),'먼저 5점으로 배구 승리');return;}serving=t*2;pause=1;flight=null;touches=0;last=-1;c.players.forEach(p=>{p.x=p.i%2?2.5:-2.5;p.z=p.i<2?4:-4;});ball={x:c.players[serving].x,y:1,z:c.players[serving].z};}
 return{update(dt){pause=Math.max(0,pause-dt);const beforeZ=ball.z;if(flight&&!pause){flight.t+=dt;const k=Math.min(1,flight.t/flight.duration);ball.x=flight.from.x+(flight.to.x-flight.from.x)*k;ball.z=flight.from.z+(flight.to.z-flight.from.z)*k;ball.y=flight.from.y+(flight.to.y-flight.from.y)*k+Math.sin(k*Math.PI)*flight.arc;}
 const side=ball.z>=0?0:1,goal=flight?flight.to:ball,candidates=c.players.filter(p=>Math.floor(p.i/2)===side&&p.i!==last).sort((a,b)=>dist(a,goal)-dist(b,goal)),receiver=candidates[0];const actions=[];
 for(const p of c.players){p.cool=Math.max(0,p.cool-dt);const team=Math.floor(p.i/2),home={x:p.i%2?2.5:-2.5,z:team?-4:4},target=p===receiver?goal:home;const q=c.input(p,()=>{if(pause)return{};if(serving>=0)return{a:p.i===serving};if(c.time<p.noticeAt||p.miss)return{};const near=dist(p,ball)<1.15;return{...toward(p,target.x,target.z,c.time>p.noticeAt?1:0),b:near&&ball.y>2&&p.y===0,a:near&&(ball.y<2||p.y>.5)&&p.cool===0};});if(!pause)c.move(p,q,4.8,false);p.x=clamp(p.x,-5.7,5.7);p.z=team?clamp(p.z,-6.7,-.3):clamp(p.z,.3,6.7);c.jump(p,{ap:q.bp},7.2);if(q.ap&&!pause&&!p.cool){p.cool=.2;if(serving===p.i){serving=-1;last=p.i;touches=0;launch({x:p.x,y:1.4,z:p.z},{x:c.rand(-4.5,4.5),y:0,z:team?4.5:-4.5},1.4,3.4);}else if(serving<0&&p.i!==last&&dist(p,ball)<(ball.y<1?1.9:1.25)&&Math.abs(ball.y-(p.y+1.2))<1.5)actions.push({p,q,d:dist(p,ball)});}}
 if(actions.length&&flight){const {p,q}=actions.sort((a,b)=>a.d-b.d)[0],team=Math.floor(p.i/2),prevTeam=last>=0?Math.floor(last/2):-1;if(prevTeam!==team)touches=0;touches++;last=p.i;if(p.y>.4||touches>=3){const x=clamp(p.x+q.x*4+c.rand(-2.8,2.8),-5.2,5.2),z=team?c.rand(2.8,6):c.rand(-6,-2.8);launch(ball,{x,y:0,z},p.y>.4?.65:1.1,p.y>.4?.8:3);touches=0;}else{const buddy=c.players[p.i^1];launch(ball,{x:clamp(buddy.x,-4.7,4.7),y:0,z:team?-1.4:1.4},1.1,3.3);}}
 if(flight&&beforeZ*ball.z<0&&!pause){const blocker=c.players.find(p=>Math.floor(p.i/2)!==Math.floor(last/2)&&p.y>.4&&dist(p,ball)<1.3&&Math.abs(ball.y-(p.y+1.4))<1.2);if(blocker){last=blocker.i;touches=0;launch(ball,{x:clamp(ball.x+c.rand(-2,2),-5,5),y:0,z:blocker.i<2?-3:3},.7,1.2);}else if(ball.y<2.6){point(Math.floor(last/2)===0?1:0);}}if(flight&&flight.t>=flight.duration&&!pause)point(ball.z>=0?1:0);c.hint(serving>=0?'서브 선수 A로 시작 · 방향 이동/A 받기/B 점프/공중 A 스파이크':'방향 이동/A 받기·다이빙/B 점프/공중 A 스파이크 · 팀당 세 번까지 터치 · 5점 선취');},render(){c.arena({width:15,depth:17,color:'#dbc699'});for(const x of [-6,6])c.draw('sideline'+x,'box',{x,y:.02,z:0,sx:.06,sy:.03,sz:14,color:cream});for(const z of [-7,7])c.draw('endline'+z,'box',{x:0,y:.02,z,sx:12,sy:.03,sz:.06,color:cream});c.draw('net','box',{x:0,y:1.3,z:0,sx:13,sy:2.6,sz:.07,color:cream,opacity:.4});c.draw('tape','box',{x:0,y:2.6,z:0,sx:13,sy:.08,sz:.1,color:cream});for(const x of [-6.5,6.5])c.draw('post'+x,'cylinder',{x,y:1.5,z:0,sx:.2,sy:3,sz:.2,color:ink});c.draw('ball','sphere',{x:ball.x,y:ball.y+.25,z:ball.z,sx:.65,sy:.65,sz:.65,color:'#efd577'});if(flight)c.draw('landing','ring',{x:flight.to.x,y:.04,z:flight.to.z,sx:1.2,sy:1.2,sz:1,rx:-Math.PI/2,color:ink});label(c,'score',score.join(' : '),0,4,0,5);}};
}
export const games={'Bob-omb Breakers':breakers,'Team Treasure Trek':treasure,'Order Up':orders,'Cheep Cheep Sweep':sweep,'Chain Chomp Fever':fever,'Butterfly Blitz':butterflies,'Beach Volley Folly':volley};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(n=>[n,['mp4']]));
const own='새 플라밍고 모델·색과 기호·경기장으로 재구성했습니다. ';
export const notes={
'Bob-omb Breakers':own+'공유 12×9 판에서 각자 기본 3열, 두 블록 회전·뒤집기, 같은 모양 3개 연결·연쇄, 둘러싸인 폭탄의 주변 소거, 남의 칸에서 얻는 득점을 구현했습니다. 100점 선취 또는 혼자 공간이 남으면 승리합니다. 정확한 MP4 연쇄 점수표가 확인되지 않아 브라우저판 점수는 지운 블록 수×연쇄 단계입니다.',
'Team Treasure Trek':own+'처음에 미로를 보여주고 이후 각자의 주변만 봅니다. C/D 지도에는 위치만 나오고 이동은 멈춥니다. 각자 열쇠나 상자를 확보한 후 동료와 만나야 합니다. 60초 제한입니다.',
'Order Up':own+'두 개씩 있는 5종 음식을 기억하고 회전 뒤 주문한 두 개를 찾습니다. 방향 이동/A 열기, 15초 라운드와 3점 선취입니다. 원작 최대 라운드는 확인되지 않아 브라우저판은 10라운드로 제한했습니다.',
'Cheep Cheep Sweep':own+'빠른 움직임에 물고기가 도망갑니다. C로 천천히 움직이며 A로 최대 3마리를 잡고 우리 앞에서 B로 비웁니다. 일반 1점/금 2점, 60초 팀 합산입니다.',
'Chain Chomp Fever':own+'커다란 새 공의 돌진과 담장 파괴, 균열 뒤 불꽃, 담장 틈 낙하를 구현했습니다. 60초 생존자는 모두 승리합니다.',
'Butterfly Blitz':own+'A로 높은 곳을 좁게, B로 낮은 곳을 넓게 잡습니다. 노랑 1점/분홍 2점/파랑 3점, 60초 합계를 겨룹니다. 나비 출현과 비행 경로는 새로 생성합니다.',
'Beach Volley Folly':own+'2인 팀 배구의 받기·토스·점프·블로킹·스파이크와 5점 선취를 구현했습니다. A 받기/B 점프/공중 A 스파이크이며 3회 터치·네트 미달 실점 규칙과 새 공 궤적을 사용합니다.'};
