import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,cream='#f2e6ce',ink='#355760';
const label=(c,id,text,x,y,z,w=3)=>c.draw(id,'text',{x,y,z,sx:w,sy:w/4,text,color:ink});
const unequal=(c,reason)=>new Set(c.players.map(p=>p.score)).size===1?c.complete([],'모두 같은 기록으로 무승부'):c.highest(reason);
const first=(c,list,reason,allDraw=false)=>{if(!list.length)return;const min=Math.min(...list.map(v=>v.t)),win=list.filter(v=>Math.abs(v.t-min)<1e-7).map(v=>v.i);c.complete(allDraw&&win.length===4?[]:win,reason);};
function graffiti(c){
 c.limit=30;c.view={size:22,eye:[0,20,20],target:[0,0,0]};const fresh=p=>{p.shape=c.int(0,2);p.covered=new Set();p.ink=new Set();p.path=Array.from({length:72},(_,i)=>{const t=i/72,a=t*TAU;if(p.shape===0)return{x:Math.cos(a)*1.4,z:Math.sin(a)*1.4};const corners=p.shape===1?[[-1.4,-1.4],[1.4,-1.4],[1.4,1.4],[-1.4,1.4]]:[[0,-1.5],[1.5,1.3],[-1.5,1.3]],at=t*corners.length,j=Math.floor(at),u=at-j,v=corners[j],w=corners[(j+1)%corners.length];return{x:v[0]+(w[0]-v[0])*u,z:v[1]+(w[1]-v[1])*u};});p.target=0;p.wait=.25;};c.players.forEach(p=>{p.baseX=p.i%2?5:-5;p.baseZ=p.i<2?-3.6:3.6;p.x=p.baseX;p.z=p.baseZ+2.5;p.cursor={x:0,z:0};p.scale=.6;fresh(p);});
 return{update(dt){for(const p of c.players){p.wait=Math.max(0,p.wait-dt);const target=p.path[p.target%72],q=c.input(p,()=>({...toward(p.cursor,target.x,target.z),a:p.wait===0}));if(p.i===0&&q.pointer.worldValid){p.cursor.x=clamp(q.pointer.worldX-p.baseX,-1.8,1.8);p.cursor.z=clamp(q.pointer.worldZ-p.baseZ,-1.8,1.8);}else{p.cursor.x=clamp(p.cursor.x+q.x*4*dt,-1.8,1.8);p.cursor.z=clamp(p.cursor.z+q.z*4*dt,-1.8,1.8);}if(dist(p.cursor,target)<.12)p.target++;if((q.a||q.b||p.i===0&&q.pointer.down)&&!p.wait){p.path.forEach((v,i)=>{if(dist(v,p.cursor)<.27)p.covered.add(i);});for(let z=0;z<24;z++)for(let x=0;x<24;x++)if(Math.hypot((x+.5)/24*3.6-1.8-p.cursor.x,(z+.5)/24*3.6-1.8-p.cursor.z)<.27)p.ink.add(z*24+x);if(p.covered.size>=68||p.ink.size>=540){c.points(p);fresh(p);}}}c.hint('방향 또는 1P 포인터로 페인트 조준 · A/B 유지로 분사 · 원·네모·세모 테두리를 채우세요');},render(){for(const p of c.players){c.draw('slab'+p.i,'box',{x:p.baseX,y:-.2,z:p.baseZ,sx:4.1,sy:.4,sz:4.1,color:'#bac2b4'});for(let i=0;i<72;i++){const v=p.path[i];c.draw('guide'+p.i+'_'+i,'sphere',{x:p.baseX+v.x,y:.04,z:p.baseZ+v.z,sx:.08,sy:.04,sz:.08,color:ink});}for(const i of p.ink)c.draw('paint'+p.i+'_'+i,'box',{x:p.baseX+(i%24+.5)/24*3.6-1.8,y:.05,z:p.baseZ+(Math.floor(i/24)+.5)/24*3.6-1.8,sx:.16,sy:.03,sz:.16,color:p.color});c.draw('cursor'+p.i,'ring',{x:p.baseX+p.cursor.x,y:.07,z:p.baseZ+p.cursor.z,sx:.55,sy:.55,sz:1,rx:-Math.PI/2,color:cream});}},timeout(){if(c.players.every(p=>!p.score))c.complete([],'표식을 완성하지 못했습니다');else c.highest('완성한 표식 수');}};
}
function waterSki(c){
 c.limit=Infinity;c.view={size:24,eye:[0,22,20],target:[0,0,0]};const ramps=Array.from({length:17},(_,i)=>({i,at:12+i*11,side:c.pick([-1,1]),both:c.rand()<.5,spike:c.pick([-1,1])}));let progress=0;c.players.forEach(p=>{p.base=(p.i-1.5)*5;p.local=0;p.x=p.base;p.z=5;p.stun=0;p.air=0;p.got=new Set();p.hit=new Set();p.botLag=c.rand(.15,.35);});
 return{update(dt){progress+=dt*6;for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.air=Math.max(0,p.air-dt);const next=ramps.find(r=>r.at>progress-.5),q=c.input(p,()=>({x:next?clamp((next.side*1.3-p.local)*3,-1,1):0}));if(!p.stun)p.local=clamp(p.local+q.x*4*dt,-1.8,1.8);p.x=p.base+p.local;p.pose='balance';for(const r of ramps){if(!p.got.has(r.i)&&Math.abs(r.at-progress)<.4){p.got.add(r.i);if(Math.abs(p.local-r.side*1.3)<.7){c.points(p);p.air=.7;}else if(r.both&&Math.abs(p.local+r.side*1.3)<.7)p.air=.7;}if(!p.hit.has(r.i)&&Math.abs(r.at+4-progress)<.4&&Math.abs(p.local-r.spike*1.3)<.6&&!p.air){p.hit.add(r.i);p.stun=1.1;}}p.y=p.air?Math.sin(p.air/.7*Math.PI)*1.8:0;}if(progress>ramps.at(-1).at+9)c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'최대 17개의 코인 획득');c.hint('좌우로 수상스키 조향 · 코인이 있는 경사로 선택 · 가시공에 맞으면 조향 정지 · 최대 17개');},render(){for(const p of c.players){c.draw('water'+p.i,'box',{x:p.base,y:-.2,z:0,sx:4.6,sy:.3,sz:22,color:'#92c7ce'});c.draw('ski'+p.i,'box',{x:p.x,y:p.y+.04,z:p.z,sx:1,sy:.12,sz:2,color:p.color});for(const r of ramps){const z=5-(r.at-progress)*.65;if(z< -12||z>10)continue;for(const side of r.both?[-1,1]:[r.side]){c.draw('ramp'+p.i+'_'+r.i+'_'+side,'box',{x:p.base+side*1.3,y:.25,z,sx:1.3,sy:.5,sz:1.7,rx:-.2,color:'#d4bb8e'});if(side===r.side&&!p.got.has(r.i))c.draw('coin'+p.i+'_'+r.i,'cylinder',{x:p.base+side*1.3,y:1,z,sx:.65,sy:.18,sz:.65,color:'#e8c063'});}c.draw('spike'+p.i+'_'+r.i,'cone',{x:p.base+r.spike*1.3,y:.3,z:z-2.6,sx:.8,sy:.8,sz:.8,color:'#7d959c'});}}}};
}
function mosh(c){
 c.limit=300;c.bounds={x:7,z:5};const balls=Array.from({length:200},(_,i)=>({i,owner:Math.floor(i/50),x:c.rand(-7,7),z:c.rand(-5,5),y:c.rand(.2,5),vy:0,vx:c.rand(-1,1),vz:c.rand(-1,1),taken:false}));c.players.forEach(p=>{p.x=(p.i%2?1:-1)*5;p.z=p.i<2?-4:4;p.stun=0;});
 return{update(dt){for(const b of balls)if(!b.taken){b.vy-=10*dt;b.y=Math.max(.18,b.y+b.vy*dt);if(b.y===.18&&b.vy<0)b.vy=-b.vy*.72;b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>7){b.x=clamp(b.x,-7,7);b.vx*=-1;}if(Math.abs(b.z)>5){b.z=clamp(b.z,-5,5);b.vz*=-1;}}const done=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);const target=balls.filter(b=>!b.taken&&b.owner===p.i).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,target?toward(p,target.x,target.z):{});if(!p.stun)c.move(p,q,4.5);c.jump(p,q);for(const o of c.players)if(o!==p&&p.vy<0&&p.y-o.y>.7&&p.y-o.y<1.4&&dist(p,o)<.55)o.stun=.5;for(const b of balls)if(!b.taken&&b.owner===p.i&&Math.hypot(b.x-p.x,b.z-p.z,b.y-(p.y+.5))<.7){b.taken=true;c.points(p);}if(p.score===50)done.push(p.i);}if(done.length)c.complete(done,'자기 색 공 50개를 모두 모았습니다');c.hint('방향으로 자기 색 공 모으기 · A 점프로 상대를 잠시 멈추게 할 수 있어요 · 50개 선취');},render(){c.arena({width:16,depth:12,color:'#d3c3a3'});for(const b of balls)if(!b.taken)c.draw('ball'+b.i,'sphere',{x:b.x,y:b.y,z:b.z,sx:.42,sy:.42,sz:.42,color:c.players[b.owner].color});},timeout(){c.complete([],'5분 안에 50개를 모으지 못했습니다');}};
}
function lava(c){
 c.limit=30;c.view={size:19,eye:[0,20,18],target:[0,0,0]};let flames=[{id:0,x:0,z:0,vx:2.4,vz:1.7,r:1}],next=8,serial=1;c.players.forEach(p=>{p.x=(p.i%2?1:-1)*3.5;p.z=p.i<2?-2.5:2.5;p.stun=0;});
 return{update(dt){if(c.time>=next){next+=8;flames=flames.flatMap(f=>[-1,1].map(side=>({id:serial++,x:f.x+side*.25,z:f.z,vx:f.vz*side*1.1,vz:-f.vx*side*1.1,r:Math.max(.28,f.r*.65)})));}for(const f of flames){f.x+=f.vx*dt;f.z+=f.vz*dt;if(Math.hypot(f.x,f.z)>5.7-f.r){const a=Math.atan2(f.z,f.x),dot=f.vx*Math.cos(a)+f.vz*Math.sin(a);f.vx-=2*dot*Math.cos(a);f.vz-=2*dot*Math.sin(a);}}for(const p of c.players){if(!p.alive)continue;p.stun=Math.max(0,p.stun-dt);const near=flames.slice().sort((a,b)=>dist(p,a)-dist(p,b))[0],candidates=Array.from({length:8},(_,i)=>({x:clamp(p.x+Math.cos(i*TAU/8)*1.5,-4.4,4.4),z:clamp(p.z+Math.sin(i*TAU/8)*1.5,-4.4,4.4)})).filter(v=>Math.hypot(v.x,v.z)<4.8),goal=candidates.sort((a,b)=>Math.min(...flames.map(f=>dist(b,f)))-Math.min(...flames.map(f=>dist(a,f))))[0]||{x:0,z:0};const q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:dist(p,near)<2&&p.y===0}));if(!p.stun)c.move(p,q,4.4,false);c.jump(p,q,7.5);for(const o of c.players)if(o!==p&&o.alive&&p.vy<0&&p.y-o.y>.65&&p.y-o.y<1.2&&dist(p,o)<.55)o.stun=.6;if(Math.hypot(p.x,p.z)>6||flames.some(f=>dist(p,f)<f.r+.4&&p.y<f.r*1.4))c.eliminate(p);}c.lastStanding();c.hint('방향 이동/A 점프 · 불덩이가 둘씩 분열합니다 · 상대를 밟아 잠깐 멈추게 할 수 있어요');},render(){c.arena({width:12.5,depth:12.5,shape:'cylinder',color:'#b4ad9b'});for(const f of flames)c.draw('flame'+f.id,'sphere',{x:f.x,y:f.r,z:f.z,sx:f.r*2,sy:f.r*2,sz:f.r*2,color:'#df975e',glow:true});},timeout(){c.survivors('30초 동안 불덩이를 피했습니다');}};
}
function kart(c){
 c.limit=300;c.view={size:23,eye:[0,24,20],target:[0,0,0]};const points=Array.from({length:16},(_,i)=>({x:Math.cos(i*TAU/16)*8,z:Math.sin(i*TAU/16)*5}));c.players.forEach(p=>{p.x=8+(p.i-1.5)*.7;p.z=-(p.i%2)*1.5;p.heading=Math.PI/2;p.speed=0;p.check=1;p.stun=0;p.margin=c.rand(.1,.35);});
 return{update(dt){const done=[];for(const p of c.players){const target=points[p.check%16],angle=Math.atan2(target.z-p.z,target.x-p.x),delta=Math.atan2(Math.sin(angle-p.heading),Math.cos(angle-p.heading)),q=c.input(p,()=>({x:clamp(delta*2,-1,1),a:true,b:Math.abs(delta)>1+p.margin&&p.speed>3.5}));p.heading+=q.x*dt*(1.2+Math.min(1,p.speed/4));p.speed=clamp(p.speed+((q.a?3:0)-(q.b?6:0)-.5)*dt,0,7);const radial=Math.hypot(p.x/8,p.z/5);if(radial<.75||radial>1.25)p.speed=Math.max(1,p.speed-dt*7);p.x=clamp(p.x+Math.cos(p.heading)*p.speed*dt,-11,11);p.z=clamp(p.z+Math.sin(p.heading)*p.speed*dt,-8,8);p.rotation=-p.heading;p.pose='sit';if(dist(p,target)<1.8){p.check++;if(p.check>=33)done.push({i:p.i,t:0});}p.score=Math.floor((p.check-1)/16);}first(c,done,'두 바퀴 먼저 완주');c.hint('좌우 핸들/A 가속/B 브레이크 · 두 바퀴 경주 · 급한 커브에서는 감속');},render(){c.arena({width:23,depth:18,color:'#a9c09d'});c.draw('track','cylinder',{x:0,y:.01,z:0,sx:20,sy:.03,sz:12.5,color:'#8c9fa1'});c.draw('infield','cylinder',{x:0,y:.03,z:0,sx:12,sy:.04,sz:7.5,color:'#a9c09d'});for(let i=0;i<8;i++)c.draw('line'+i,'box',{x:6.25+i*.5,y:.08,z:0,sx:.5,sy:.03,sz:.4,color:i%2?cream:ink});for(const p of c.players)c.draw('kart'+p.i,'box',{x:p.x,y:.2,z:p.z,sx:1.4,sy:.4,sz:1,ry:-p.heading,color:p.color});label(c,'lap','2 LAPS',0,1,0,5);},timeout(){c.complete([],'5분 안에 완주한 선수가 없습니다');}};
}
function rudder(c){
 c.limit=300;c.view={size:21,eye:[0,23,20],target:[0,0,0]};const obstacles=Array.from({length:40},(_,i)=>({i,x:c.rand(-6,6),at:10+i*5,r:i%3?.6:1.2}));let lead=0;c.players.forEach(p=>{p.x=(p.i-1.5)*2.2;p.distance=0;p.vx=0;p.slow=0;p.hit=new Set();p.lag=c.rand(.1,.35);});
 return{update(dt){const done=[];for(const p of c.players){p.slow=Math.max(0,p.slow-dt);const front=obstacles.find(o=>o.at>p.distance&&o.at<p.distance+7&&Math.abs(o.x-p.x)<o.r+1.1),target=front?clamp(front.x+(p.x>=front.x?1:-1)*(front.r+1.5),-6.5,6.5):p.x,q=c.input(p,{x:clamp((target-p.x)*2,-1,1)});p.vx+=(q.x*4-p.vx)*dt*2;p.x=clamp(p.x+p.vx*dt,-7,7);const v=(p.slow?1:3.6)-Math.abs(q.x)*.2,old=p.distance;p.distance+=v*dt;for(const o of obstacles)if(!p.hit.has(o.i)&&Math.abs(o.at-p.distance)<o.r+.6&&Math.abs(o.x-p.x)<o.r+.6){p.hit.add(o.i);p.slow=1.1;p.vx=(p.x>=o.x?1:-1)*2;}if(p.distance>=215)done.push({i:p.i,t:(215-old)/v});p.score=Math.floor(p.distance);p.pose='balance';}for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=c.players[i],b=c.players[j],d=Math.hypot(a.x-b.x,a.distance-b.distance);if(d<1.4&&d>.001){const k=(1.4-d)/2,dx=(a.x-b.x)/d,dz=(a.distance-b.distance)/d;a.x+=dx*k;b.x-=dx*k;a.distance+=dz*k;b.distance-=dz*k;}}first(c,done,'강 하류의 결승점 도착',true);lead=Math.max(...c.players.map(p=>p.distance));for(const p of c.players)p.z=4-(p.distance-lead)*.6;c.hint('좌우로 노를 기울여 수련잎 조향 · 바위·기둥·다른 선수와 부딪히면 지연');},render(){c.arena({width:18,depth:25,color:'#8fb9b6'});for(const o of obstacles){const z=4-(o.at-lead)*.6;if(z< -14||z>13)continue;c.draw('rock'+o.i,o.r>1?'sphere':'cylinder',{x:o.x,y:.5,z,sx:o.r*2,sy:1.4,sz:o.r*2,color:'#abb29f'});}for(const p of c.players)c.draw('pad'+p.i,'cylinder',{x:p.x,y:.03,z:p.z,sx:1.9,sy:.12,sz:1.9,color:p.color});},timeout(){c.complete([],'5분 안에 완주하지 못했습니다');}};
}
function sick(c){
 c.limit=Infinity;c.view={size:24,eye:[0,25,21],target:[0,0,0]};const platforms=Array.from({length:13},(_,i)=>({x:i===0||i===12?0:Math.sin(i*1.6)*2,z:-i*4.8,r:i===0||i===12?4:2.4+(i%3)*.15,spin:i===0||i===12?0:(i%2?1:-1)*(.3+i*.025)})),shots=[];let next=3,serial=0,lead=0;c.players.forEach(p=>{p.x=(p.i-1.5)*1.3;p.worldZ=0;p.jumpY=0;p.vy=0;p.stage=0;p.finished=false;p.stun=0;});
 return{update(dt){lead=Math.max(...c.players.filter(p=>p.alive).map(p=>-p.worldZ),0);if(c.time>next){const target=c.players.filter(p=>p.alive&&!p.finished).sort((a,b)=>a.worldZ-b.worldZ)[0];if(target){shots.push({id:serial++,x:target.x+(serial%2?10:-10),z:target.worldZ-2,vx:serial%2?-5:5,vz:1});}next=c.time+2.4;}for(const b of shots){b.x+=b.vx*dt;b.z+=b.vz*dt;}for(const p of c.players){if(!p.alive||p.finished)continue;p.stun=Math.max(0,p.stun-dt);let ground=platforms.find(v=>Math.hypot(p.x-v.x,p.worldZ-v.z)<v.r-.12);const target=platforms[Math.min(12,p.stage+1)],v=toward({x:p.x,z:p.worldZ},target.x,target.z),q=c.input(p,()=>({...v,a:p.jumpY===0&&Math.hypot(p.x-target.x,p.worldZ-target.z)<4.7&&(!ground||Math.hypot(p.x-ground.x,p.worldZ-ground.z)>ground.r-.9)}));if(ground&&p.jumpY===0){const x=p.x-ground.x,z=p.worldZ-ground.z,angle=ground.spin*dt;p.x=ground.x+x*Math.cos(angle)-z*Math.sin(angle);p.worldZ=ground.z+x*Math.sin(angle)+z*Math.cos(angle);}if(!p.stun){p.x+=q.x*4.8*dt;p.worldZ+=q.z*4.8*dt;}if(q.ap&&p.jumpY===0&&ground){p.vy=9;p.jumpY=.001;}if(p.jumpY>0){p.vy-=18*dt;p.jumpY=Math.max(0,p.jumpY+p.vy*dt);}ground=platforms.find(v=>Math.hypot(p.x-v.x,p.worldZ-v.z)<v.r-.12);if(!p.jumpY&&!ground||lead+p.worldZ>25||shots.some(b=>Math.hypot(p.x-b.x,p.worldZ-b.z)<.7&&p.jumpY<1.1))c.eliminate(p);if(ground&&p.jumpY===0){p.stage=Math.max(p.stage,platforms.indexOf(ground));p.score=p.stage;if(p.stage===12){p.finished=true;p.score=13;}}for(const o of c.players)if(o!==p&&o.alive&&p.vy<0&&p.jumpY-o.jumpY>.6&&p.jumpY-o.jumpY<1.1&&Math.hypot(p.x-o.x,p.worldZ-o.worldZ)<.6)o.stun=.55;p.z=p.worldZ+lead-3;p.y=p.jumpY;p.pose=p.y?'jump':'run';}if(c.players.every(p=>!p.alive||p.finished))c.complete(c.players.filter(p=>p.finished).map(p=>p.i),'결승 발판에 도착한 선수 모두 승리');c.hint('방향 이동/A 점프 · 회전 발판과 날아오는 새알을 피하세요 · 끝까지 도착한 선수 모두 승리');},render(){platforms.forEach((v,i)=>{const z=v.z+lead-3;if(Math.abs(z)>17)return;c.draw('platform'+i,i===0||i===12?'box':'cylinder',{x:v.x,y:-.2,z,sx:v.r*2,sy:.4,sz:v.r*2,color:i===12?'#f1c45d':'#acd1bb'});c.draw('spin'+i,'box',{x:v.x,y:.02,z,sx:v.r*1.8,sy:.04,sz:.16,ry:c.time*v.spin,color:'#628f86'});});shots.forEach(b=>{const z=b.z+lead-3;if(Math.abs(z)<17)c.draw('shot'+b.id,'sphere',{x:b.x,y:.6,z,sx:1.4,sy:.8,sz:.8,color:'#756976'});});}};
}
function nick(c){
 c.limit=Infinity;c.view={size:28,eye:[0,32,10],target:[0,0,0]};let round=0,target=0,phase='new',until=0,deadline=0;const loc=[[-7,-5],[7,-5],[-7,5],[7,5]],delta=(a,b)=>((a-b+1080)%720)-360;const fresh=()=>{round++;if(round>10){c.complete([],'10라운드 안에 3점을 얻지 못했습니다');return;}target=c.int(0,143)*5;deadline=c.time+20;phase='play';c.players.forEach(p=>{p.minute=0;p.reaction=c.time+c.rand(.35,.85);p.rate=c.rand(.8,1);});};c.players.forEach(p=>{p.x=loc[p.i][0];p.z=loc[p.i][1]+3;p.scale=.7;p.minute=0;});
 const clock=(id,x,z,r,min,color)=>{c.draw(id+'dial','cylinder',{x,y:0,z,sx:r*2,sy:.18,sz:r*2,color:cream});for(let i=0;i<12;i++){const a=i*TAU/12;c.draw(id+'tick'+i,'sphere',{x:x+Math.sin(a)*r*.83,y:.13,z:z-Math.cos(a)*r*.83,sx:.13,sy:.06,sz:.13,color:ink});}for(const [key,a,len,w]of[['minute',min%60*TAU/60,r*.77,.12],['hour',min/720*TAU,r*.5,.2]])c.draw(id+key,'box',{x:x+Math.sin(a)*len/2,y:.2,z:z-Math.cos(a)*len/2,sx:w,sy:.08,sz:len,ry:-a,color});};
 return{update(dt){if(phase==='new'||phase==='wait'&&c.time>=until)fresh();if(phase==='play'){const matching=[];for(const p of c.players){const d=delta(target,p.minute),q=c.input(p,()=>({x:c.time>p.reaction?clamp(d/14,-1,1)*p.rate:0}));p.minute=(p.minute+q.x*120*dt+720)%720;if(Math.abs(delta(target,p.minute))<1.2)matching.push(p);}if(matching.length){matching.forEach(p=>c.points(p));const done=c.players.filter(p=>p.score>=3);if(done.length)c.complete(done.map(p=>p.i),'시계를 세 번 먼저 맞췄습니다');else{phase='wait';until=c.time+1.3;}}else if(c.time>=deadline){phase='wait';until=c.time+1.3;}}c.hint(`좌우로 분침 돌리기 · 시침은 12배 느리게 함께 회전 · 중앙 시각에 먼저 맞춰 3점 · ${round}/10라운드 (${Math.max(0,Math.ceil(deadline-c.time))}초)`);},render(){clock('target',0,0,2.5,target,'#d58e8d');for(const p of c.players)clock('dial'+p.i,loc[p.i][0],loc[p.i][1],2.5,p.minute,p.color);label(c,'round',`${round}/10`,0,.5,3.5,4);}};
}
function scooter(c){
 c.limit=30;c.view={size:21,eye:[0,24,19],target:[0,0,0]};const balls=[];let serial=0;c.players.forEach(p=>{p.x=p.i%2?6:-6;p.z=p.i<2?-5:5;p.heading=Math.atan2(-p.z,-p.x);p.stun=0;p.cool=c.rand(.1,.5);p.reaction=c.rand(.3,.6);});
 return{update(dt){for(const p of c.players){p.cool-=dt;p.stun=Math.max(0,p.stun-dt);const target=c.players.filter(o=>o!==p).sort((a,b)=>dist(p,a)-dist(p,b))[0],angle=Math.atan2(target.z-p.z,target.x-p.x),d=Math.atan2(Math.sin(angle-p.heading),Math.cos(angle-p.heading)),q=c.input(p,()=>({x:clamp(d*2,-1,1),z:dist(p,target)>4?-1:Math.abs(d)<.4?.4:0,a:Math.abs(d)<.24}));if(p.stun)continue;p.heading+=q.x*2.5*dt;p.x=clamp(p.x-Math.cos(p.heading)*q.z*4*dt,-8,8);p.z=clamp(p.z-Math.sin(p.heading)*q.z*4*dt,-6,6);const r=Math.hypot(p.x,p.z);if(r<2.5){p.x*=2.5/(r||1);p.z*=2.5/(r||1);}if((q.a||q.b)&&p.cool<=0){p.cool=p.reaction;balls.push({id:serial++,owner:p.i,x:p.x+Math.cos(p.heading)*.8,z:p.z+Math.sin(p.heading)*.8,vx:Math.cos(p.heading)*10,vz:Math.sin(p.heading)*10,age:0});}p.rotation=-p.heading;p.pose='sit';}for(const b of balls){if(b.dead)continue;b.x+=b.vx*dt;b.z+=b.vz*dt;b.age+=dt;if(b.age>2||Math.hypot(b.x,b.z)<2.1){b.dead=true;continue;}const hit=c.players.find(p=>p.i!==b.owner&&!p.stun&&dist(p,b)<.7);if(hit){hit.stun=.85;c.points(c.players[b.owner]);b.dead=true;}}c.hint('위아래 전진·후진/좌우 차체 회전/A 발사 · 명중 1점 · 피격하면 잠깐 정지');},render(){c.arena({width:18,depth:14,color:'#acccc6'});c.draw('middle','cylinder',{x:0,y:.3,z:0,sx:4.2,sy:.6,sz:4.2,color:'#d5c6a2'});for(const p of c.players){c.draw('scooter'+p.i,'cylinder',{x:p.x,y:.15,z:p.z,sx:1.4,sy:.3,sz:1.4,color:p.color});c.draw('gun'+p.i,'box',{x:p.x+Math.cos(p.heading)*.55,y:.6,z:p.z+Math.sin(p.heading)*.55,sx:1.2,sy:.2,sz:.2,ry:-p.heading,color:ink});}for(const b of balls)if(!b.dead)c.draw('ball'+b.id,'sphere',{x:b.x,y:.55,z:b.z,sx:.35,sy:.35,sz:.35,color:c.players[b.owner].color});},timeout(){if(c.players.every(p=>p.score===0))c.complete([],'명중 기록 없음');else c.highest('가장 많이 명중');}};
}
function flip(c){
 c.limit=300;c.view={size:23,eye:[0,13,27],target:[0,9,0]};let next=.5,serial=0;const nuts=[];c.players.forEach(p=>{p.base=(p.i-1.5)*5;p.side=-1;p.height=0;p.wait=0;p.hit=0;});
 return{update(dt){if(c.time>next){for(const p of c.players)nuts.push({id:serial++,lane:p.i,side:c.pick([-1,1]),y:Math.max(18,p.height+7)});next=c.time+c.rand(1.1,1.8);}for(const n of nuts)n.y-=7*dt;const done=[];for(const p of c.players){p.wait=Math.max(0,p.wait-dt);p.hit=Math.max(0,p.hit-dt);const threat=nuts.find(n=>!n.dead&&n.lane===p.i&&n.side===p.side&&n.y>p.height&&n.y<p.height+3),q=c.input(p,{a:!!threat&&p.wait===0});if(q.ap&&!p.hit){p.side*=-1;p.wait=.28;}const old=p.height,v=!p.wait&&!p.hit?1.1:0;p.height+=v*dt;for(const n of nuts)if(!n.dead&&n.lane===p.i&&n.side===p.side&&Math.abs(n.y-p.height)<.6){n.dead=true;p.height=Math.max(0,p.height-1.5);p.hit=.65;}if(p.height>=18)done.push({i:p.i,t:v?(18-old)/v:0});p.x=p.base+p.side*.65;p.y=p.height;p.z=0;p.score=Math.floor(p.height);p.pose='jump';}first(c,done,'야자나무 꼭대기에 먼저 도착');c.hint('A를 눌러 나무 반대편으로 뒤집기 · 자동으로 올라갑니다 · 뒤집을 때 잠깐 멈추고 열매에 맞으면 미끄러집니다');},render(){for(const p of c.players){c.draw('tree'+p.i,'cylinder',{x:p.base,y:9,z:0,sx:.6,sy:19,sz:.6,color:'#bd9d75'});c.draw('leaf'+p.i,'cone',{x:p.base,y:19,z:0,sx:3.3,sy:2,sz:3.3,color:'#8fbe92'});}for(const n of nuts)if(!n.dead&&n.y>-.5&&n.y<23)c.draw('nut'+n.id,'sphere',{x:c.players[n.lane].base+n.side*.65,y:n.y,z:0,sx:.65,sy:.65,sz:.65,color:'#a57c63'});},timeout(){c.complete([],'5분 동안 꼭대기에 도착하지 못했습니다');}};
}
function alpine(c){
 c.limit=300;c.view={size:24,eye:[0,25,20],target:[0,0,0]};const obstacles=Array.from({length:45},(_,i)=>({id:i,at:14+i*5,x:c.rand(-7,7),ramp:i%4===0}));let lead=0;c.players.forEach(p=>{p.x=(p.i-1.5)*2.3;p.distance=0;p.speed=5.5;p.air=0;p.spins=0;p.boost=0;p.stun=0;p.seen=new Set();p.pace=c.rand(.82,1);});
 return{update(dt){const done=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.boost=Math.max(0,p.boost-dt);const next=obstacles.find(o=>o.at>p.distance&&o.at<p.distance+9&&(o.ramp||Math.abs(o.x-p.x)<1.5)),target=next?next.ramp?next.x:clamp(next.x+(p.x>next.x?2:-2),-7,7):p.x,q=c.input(p,()=>({x:clamp((target-p.x)*2,-1,1)*p.pace,a:p.air>0&&Math.floor(c.time*(6+p.pace*2))%2===0}));if(!p.stun)p.x=clamp(p.x+q.x*4*dt,-8,8);if(p.air>0){p.air-=dt;if(q.ap||q.bp)p.spins++;if(p.air<=0){p.air=0;if(p.spins)p.boost=Math.min(2.5,.6+p.spins*.5);}}p.speed=p.stun?1.5:p.boost?9:5.5;const old=p.distance;p.distance+=p.speed*dt;for(const o of obstacles)if(!p.seen.has(o.id)&&Math.abs(o.at-p.distance)<.6){p.seen.add(o.id);if(Math.abs(o.x-p.x)<1){if(o.ramp){p.air=1;p.spins=0;}else if(!p.air)p.stun=1.2;}}if(p.distance>=250)done.push({i:p.i,t:(250-old)/p.speed});p.score=Math.floor(p.distance);p.y=p.air?Math.sin(p.air*Math.PI)*2:0;p.pose='balance';p.rotation=p.air?p.spins*Math.PI/2:0;}first(c,done,'보드 경주 결승점 도착',true);lead=Math.max(...c.players.map(p=>p.distance));for(const p of c.players)p.z=5+(lead-p.distance)*.45;c.hint('좌우로 보드 조향 · 경사로에서 뛰는 동안 A/B로 회전하면 착지 가속 · 눈사람을 피하세요');},render(){c.arena({width:19,depth:26,color:'#dce8e5'});for(const o of obstacles){const z=5-(o.at-lead)*.45;if(z< -14||z>15)continue;if(o.ramp)c.draw('ramp'+o.id,'box',{x:o.x,y:.3,z,sx:2,sy:.6,sz:2,rx:-.25,color:'#9bbbc3'});else{c.draw('snow'+o.id,'sphere',{x:o.x,y:.5,z,sx:1.1,sy:1.1,sz:1.1,color:cream});c.draw('head'+o.id,'sphere',{x:o.x,y:1.3,z,sx:.7,sy:.7,sz:.7,color:cream});}}for(const p of c.players)c.draw('board'+p.i,'box',{x:p.x,y:p.y+.05,z:p.z,sx:.6,sy:.1,sz:1.9,ry:p.rotation,color:p.color});},timeout(){c.complete([],'5분 안에 완주하지 못했습니다');}};
}
function tightrope(c){
 c.limit=300;c.view={size:24,eye:[0,24,20],target:[0,0,0]};let wind=0,lead=0;c.players.forEach(p=>{p.base=(p.i-1.5)*5;p.distance=0;p.lean=0;p.sway=0;p.skill=c.rand(.94,1.04);});
 return{update(dt){wind=Math.sin(c.time*.7)*(.3+.5*Math.max(0,Math.sin(c.time*.29)));const done=[];for(const p of c.players){if(!p.alive)continue;const q=c.input(p,()=>({x:clamp((-wind-p.lean*1.7-p.sway*.7)*p.skill,-1,1),z:Math.abs(p.lean)<.45&&Math.abs(wind)<.62?-p.skill*.9:0})),forward=Math.max(0,-q.z),v=forward*4;p.sway+=(q.x+wind+p.lean*.45)*dt*2;p.sway*=Math.exp(-dt*(forward?1.4:3));p.lean+=p.sway*dt;const old=p.distance;p.distance+=v*dt;p.x=p.base+p.lean*.7;p.y=.05;p.pose='balance';if(Math.abs(p.lean)>1.15)c.eliminate(p);if(p.distance>=60&&p.alive)done.push({i:p.i,t:v?(60-old)/v:0});p.score=Math.floor(p.distance);}first(c,done,'외줄 결승점에 먼저 도착');if(c.players.every(p=>!p.alive))c.complete([],'모두 외줄에서 떨어졌습니다');lead=Math.max(...c.players.map(p=>p.distance));for(const p of c.players)p.z=4+(lead-p.distance)*.4;c.hint(`위쪽으로 전진/좌우로 균형 · 바람 ${wind>0?'→':'←'} ${Math.round(Math.abs(wind)*100)} · 멈추면 흔들림이 줄어듭니다`);},render(){for(const p of c.players){c.draw('rope'+p.i,'box',{x:p.base,y:-.04,z:0,sx:.12,sy:.12,sz:28,color:'#d7c29c'});c.draw('finish'+p.i,'box',{x:p.base,y:-.2,z:4-(60-lead)*.4,sx:3.6,sy:.4,sz:2,color:'#96b5a5'});c.draw('balance'+p.i,'box',{x:p.x,y:1.1,z:p.z,sx:2,sy:.12,sz:.12,rz:-p.lean*.5,color:p.color});}label(c,'wind',wind>0?'WIND →':'← WIND',0,1,-10,6);},timeout(){c.complete([],'5분 안에 건너지 못했습니다');}};
}
function saucer(c){
 c.limit=30;c.view={size:27,eye:[0,28,18],target:[0,0,0]};const origins=[[-6,-5],[6,-5],[-6,5],[6,5]],ships=[],shots=[];let next=.4,id=0;c.players.forEach(p=>{p.baseX=origins[p.i][0];p.baseZ=origins[p.i][1];p.x=p.baseX;p.z=p.baseZ+3;p.angle=0;p.cool=0;p.stun=0;});
 return{update(dt){if(c.time>next){for(const p of c.players)ships.push({id:id++,lane:p.i,x:c.rand(-3.5,3.5),z:-4,y:.5,gold:c.rand()<.16,speed:c.rand(.8,1.5)});next=c.time+c.rand(.6,1);}for(const p of c.players){p.cool-=dt;p.stun=Math.max(0,p.stun-dt);const target=ships.filter(s=>!s.dead&&s.lane===p.i).sort((a,b)=>b.z-a.z)[0],a=target?Math.atan2(target.x,3-target.z):0,q=c.input(p,{x:clamp((a-p.angle)*3,-1,1),a:!!target&&Math.abs(p.angle-a)<.15});if(!p.stun){p.angle=clamp(p.angle+q.x*1.5*dt,-1.05,1.05);if((q.a||q.b)&&p.cool<=0){p.cool=.22;shots.push({id:id++,lane:p.i,x:0,z:3,vx:Math.sin(p.angle)*11,vz:-Math.cos(p.angle)*11});}}p.rotation=p.angle;}for(const s of ships){if(s.dead)continue;s.z+=s.speed*dt;s.x+=Math.sin(c.time*2+s.id)*dt*.2;if(s.z>2.7){c.players[s.lane].stun=.9;s.dead=true;}}for(const b of shots){if(b.dead)continue;b.x+=b.vx*dt;b.z+=b.vz*dt;if(b.z< -5||Math.abs(b.x)>4.8){b.dead=true;continue;}const s=ships.find(s=>!s.dead&&s.lane===b.lane&&dist(s,b)<.55);if(s){s.dead=b.dead=true;c.points(c.players[b.lane],s.gold?2:1);}}c.hint('좌우로 포탑 회전/A 연사 · 원반 1점/금빛 원반 2점 · 원반이 다가와 부딪히면 잠깐 정지');},render(){for(const p of c.players){c.draw('sky'+p.i,'box',{x:p.baseX,y:-.2,z:p.baseZ,sx:9,sy:.3,sz:8.5,color:'#92b8b6'});c.draw('turret'+p.i,'box',{x:p.x+Math.sin(p.angle)*.5,y:.4,z:p.z-Math.cos(p.angle)*.5,sx:.25,sy:.3,sz:1.4,ry:-p.angle,color:ink});}for(const s of ships)if(!s.dead){const p=c.players[s.lane];c.draw('ship'+s.id,'sphere',{x:p.baseX+s.x,y:.5,z:p.baseZ+s.z,sx:1.2,sy:.35,sz:.8,color:s.gold?'#e7b759':'#d3abcb'});}for(const b of shots)if(!b.dead){const p=c.players[b.lane];c.draw('shot'+b.id,'sphere',{x:p.baseX+b.x,y:.5,z:p.baseZ+b.z,sx:.2,sy:.2,sz:.2,color:p.color});}},timeout(){if(c.players.every(p=>!p.score))c.complete([],'격추 기록 없음');else c.highest('격추 점수');}};
}
function glacial(c){
 c.limit=300;c.view={size:19,eye:[0,22,18],target:[0,0,0]};let next=1,id=0;const beetles=[];c.players.forEach(p=>{p.x=(p.i%2?1:-1)*2.5;p.z=p.i<2?-2.5:2.5;p.cool=0;p.vx=0;p.vz=0;p.stun=0;});
 return{update(dt){if(c.time>next){beetles.push({id:id++,x:c.rand(-4,4),z:c.rand(-4,4),y:7,vy:0,vx:c.rand(-.6,.6),vz:c.rand(-.6,.6),kicked:false});next=c.time+c.rand(1.3,2.2);}for(const b of beetles){if(b.dead)continue;b.vy-=18*dt;b.y=Math.max(0,b.y+b.vy*dt);b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.hypot(b.x,b.z)>7)b.dead=true;}for(const p of c.players){if(!p.alive)continue;p.cool-=dt;p.stun=Math.max(0,p.stun-dt);const target=c.players.filter(o=>o!==p&&o.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0],near=target&&dist(p,target)<1.6,q=c.input(p,()=>({...toward(p,Math.hypot(p.x,p.z)>4?0:target?.x??0,Math.hypot(p.x,p.z)>4?0:target?.z??0),a:beetles.some(b=>!b.dead&&b.y<2&&dist(p,b)<1.6)&&p.y===0,b:near&&p.cool<=0}));if(!p.stun){p.vx+=q.x*8*dt;p.vz+=q.z*8*dt;if(Math.hypot(q.x,q.z)>.1)p.rotation=Math.atan2(-q.z,q.x);}p.vx*=Math.exp(-dt*1.7);p.vz*=Math.exp(-dt*1.7);p.x+=p.vx*dt;p.z+=p.vz*dt;c.jump(p,q,8);if(q.bp&&p.cool<=0&&!p.stun){p.cool=.5;for(const o of [...c.players.filter(o=>o!==p&&o.alive),...beetles.filter(b=>!b.dead&&b.y<1)])if(dist(p,o)<1.8){const v=toward(p,o.x,o.z);o.vx=v.x*(p.y>0?9:7);o.vz=v.z*(p.y>0?9:7);o.stun=.5;o.kicked=true;}}for(const b of beetles)if(!b.dead&&b.y<1&&dist(p,b)<.7&&p.y<.7&&!p.stun){const v=toward(b,p.x,p.z);p.vx=v.x*5;p.vz=v.z*5;p.stun=.6;}if(Math.hypot(p.x,p.z)>6.1)c.eliminate(p);}const alive=c.players.filter(p=>p.alive);if(alive.length===1)c.complete(alive.map(p=>p.i),'빙판의 마지막 생존자');else if(!alive.length){const last=Math.max(...c.players.map(p=>p.outAt));c.complete(c.players.filter(p=>p.outAt===last).map(p=>p.i),'마지막에 떨어진 선수');}c.hint('방향 이동/A 점프/B 펀치/공중 B 발차기 · 미끄러운 빙판에서 상대와 떨어지는 딱정벌레를 밀어내세요');},render(){c.arena({width:12.2,depth:12.2,shape:'cylinder',color:'#c6e0de'});for(const b of beetles)if(!b.dead)c.draw('beetle'+b.id,'sphere',{x:b.x,y:b.y+.3,z:b.z,sx:1.1,sy:.7,sz:.85,color:b.kicked?'#c7aaba':'#637e92'});},timeout(){c.survivors('5분 동안 빙판에서 생존');}};
}
function runner(c){
 c.limit=30;c.view={size:26,eye:[0,13,33],target:[0,9,0]};const platforms=Array.from({length:11},(_,i)=>({i,x:i?i%2?2:-2:0,y:i*1.7,old:i*1.7,lift:i===4||i===8})),shots=[];let serial=0;const solo=c.players[0];solo.x=0;solo.y=0;solo.z=0;solo.vy=0;solo.ground=0;solo.stun=0;c.players.slice(1).forEach(p=>{p.x=(p.i-2)*5;p.y=0;p.z=7;p.aim={x:0,y:3};p.cool=c.rand(.6,1.2);p.think=0;});
 return{update(dt){for(const v of platforms){v.old=v.y;v.y=v.i*1.7+(v.lift?Math.sin(c.time*1.2)*.55:0);}solo.stun=Math.max(0,solo.stun-dt);const target=platforms[Math.min(10,solo.ground+1)],q=c.input(solo,()=>({x:clamp((target.x-solo.x)*2,-1,1),a:solo.ground<10&&solo.vy===0&&Math.abs(target.x-solo.x)<3.1}));if(!solo.stun){solo.x=clamp(solo.x+q.x*5*dt,-5,5);if(q.ap&&solo.vy===0){solo.vy=10.8;solo.y+=.001;}}const old=solo.y;if(solo.vy!==0){solo.vy-=18*dt;solo.y+=solo.vy*dt;const landing=platforms.filter(v=>Math.abs(solo.x-v.x)<1.8&&old>=v.old&&solo.y<=v.y&&solo.vy<0).sort((a,b)=>b.y-a.y)[0];if(landing){solo.y=landing.y;solo.vy=0;solo.ground=landing.i;}}else{const stand=platforms[solo.ground];if(Math.abs(solo.x-stand.x)<1.8)solo.y=stand.y;else solo.vy=-.01;}if(solo.y<0){solo.y=0;solo.vy=0;solo.ground=0;}solo.score=solo.ground;solo.pose=solo.vy?'jump':'run';for(const p of c.players.slice(1)){p.cool-=dt;p.think-=dt;if(p.think<=0){p.botAim={x:solo.x+c.rand(-3.4,3.4),y:solo.y+.8+c.rand(-2,2)};p.think=c.rand(.35,.65);}const aim=p.botAim,v=c.input(p,()=>({x:clamp((aim.x-p.aim.x)*2,-1,1),z:clamp((p.aim.y-aim.y)*2,-1,1),a:p.cool<=0&&Math.floor(c.time*5+p.i)%3===0}));if(v.pointer.frontValid){p.aim.x=clamp(v.pointer.frontX,-6,6);p.aim.y=clamp(v.pointer.frontY,0,20);}else{p.aim.x=clamp(p.aim.x+v.x*7*dt,-6,6);p.aim.y=clamp(p.aim.y-v.z*7*dt,0,20);}if((v.ap||v.bp||v.pointer.pressed)&&p.cool<=0){p.cool=1;shots.push({id:serial++,owner:p.i,x:p.aim.x,y:p.aim.y,age:0});}}for(const b of shots){if(b.dead)continue;b.age+=dt;if(b.age>=.35){b.dead=true;if(Math.hypot(b.x-solo.x,b.y-(solo.y+.8))<.8&&!solo.stun)solo.stun=3;}}if(solo.ground===10)c.complete([0],'30초 안에 탑 탈출');c.hint('1P: 좌우/A 점프로 탑 등반 · 2–4P: 방향 조준/A·B 발사 · 재장전 1초, 명중 시 등반자 3초 정지');},render(){c.draw('tower','box',{x:0,y:8,z:-1.8,sx:11,sy:19,sz:1,color:'#bdd0c8'});for(const v of platforms)c.draw('ledge'+v.i,'box',{x:v.x,y:v.y-.15,z:0,sx:3.6,sy:.3,sz:2,color:v.lift?'#e8bd69':'#95b4ad'});for(const p of c.players.slice(1))c.draw('aim'+p.i,'ring',{x:p.aim.x,y:p.aim.y,z:.8,sx:.85,sy:.85,sz:1,color:p.color});for(const b of shots)if(!b.dead)c.draw('ball'+b.id,'sphere',{x:b.x,y:b.y,z:7*(1-b.age/.35),sx:.35,sy:.35,sz:.35,color:c.players[b.owner].color});},timeout(){c.complete([1,2,3],'등반자의 탈출을 막았습니다');}};
}
function gold(c){
 c.limit=20;c.view={size:23,eye:[0,9,28],target:[0,6,0]};const drops=[];let steady=.3,erratic=.2,id=0;c.players.forEach(p=>{p.x=p.i===0?-5:3+(p.i-1)*1.5;p.y=0;p.z=0;p.stun=0;p.caught=0;});const spawn=team=>drops.push({id:id++,team,x:team?c.rand(1,9):c.rand(-9,-1),y:13,spike:c.rand()<.2,speed:c.rand(3,4)});
 return{update(dt){if(c.time>=steady){spawn(0);steady+=.45;}if(c.time>=erratic){for(let i=0;i<c.int(1,3);i++)spawn(1);erratic=c.time+c.rand(.3,1.2);}for(const p of c.players){p.stun=Math.max(0,p.stun-dt);const team=p.i>0,target=drops.filter(d=>!d.dead&&!!d.team===team&&!d.spike).sort((a,b)=>a.y-b.y)[p.i>0?(p.i-1)%Math.max(1,drops.filter(d=>!d.dead&&d.team&&!d.spike).length):0],hazard=drops.find(d=>!d.dead&&!!d.team===team&&d.spike&&d.y<2&&Math.abs(d.x-p.x)<(team?.7:1.6)),goal=hazard?hazard.x+(p.x>hazard.x?2:-2):target?.x??p.x,q=c.input(p,{x:clamp((goal-p.x)*2,-1,1)});p.x=clamp(p.x+q.x*5*dt,team?1:-9,team?9:-1);p.pose=p.stun?'sad':'balance';}for(const d of drops){if(d.dead)continue;d.y-=d.speed*dt;if(d.y<=.8){const p=c.players.filter(p=>!!d.team===(p.i>0)&&Math.abs(p.x-d.x)<(p.i? .8:1.8)).sort((a,b)=>Math.abs(a.x-d.x)-Math.abs(b.x-d.x))[0];if(p&&!p.stun){if(d.spike)p.stun=1.5;else{p.caught++;if(p.i)c.players.slice(1).forEach(o=>c.points(o));else c.points(p);}d.dead=true;}else if(d.y<0)d.dead=true;}}c.hint('좌우로 바구니 이동 · 1P는 넓은 바구니, 2–4P는 작은 바구니와 공유 코인 · 가시 열매를 받으면 잠깐 수집 불가');},render(){for(const [x,color]of[[-5,'#a3c4bb'],[5,'#c8bfce']])c.draw('machine'+x,'box',{x,y:6,z:-1,sx:9,sy:14,sz:.5,color});for(const p of c.players)c.draw('basket'+p.i,'box',{x:p.x,y:.4,z:.5,sx:p.i?1.6:3.6,sy:.5,sz:1,color:p.stun?'#a39a94':p.color});for(const d of drops)if(!d.dead)c.draw('drop'+d.id,d.spike?'cone':'cylinder',{x:d.x,y:d.y,z:.4,sx:.55,sy:d.spike?.65:.16,sz:.55,rx:d.spike?0:Math.PI/2,color:d.spike?'#827f99':'#ebc466'});},timeout(){c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'획득한 코인을 가져갑니다');}};
}
export const games={'Speedy Graffiti':graffiti,'Water Ski Spree':waterSki,'Mosh-Pit Playroom':mosh,'Lava or Leave ’Em':lava,'Kartastrophe':kart,'Rudder Madness':rudder,'Sick and Twisted':sick,'In the Nick of Time':nick,'Scooter Pursuit':scooter,'Flip the Chimp':flip,'Alpine Assault':alpine,'Treacherous Tightrope':tightrope,'Saucer Swarm':saucer,'Glacial Meltdown':glacial,'Gun the Runner':runner,"Grabbin' Gold":gold};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['mp8']]));
const own='원작 중심 규칙을 플라밍고 3D로 재구성했습니다. 리모컨 기울이기는 방향키, 흔들기는 버튼으로 바꾸었습니다. 코스 배치·이동 속도·충돌 범위는 새 브라우저판 수치이며 원작 수치와 동일하다고 주장하지 않습니다. ';
export const notes={
'Speedy Graffiti':own+'30초 동안 원·네모·세모 테두리를 칠하거나 판 전체를 칠하면 다음 판으로 바뀝니다. 방향 또는 포인터 조준/A·B 분사입니다. 72개 테두리 표본 중 68개 또는 24×24 면적 중 540칸을 칠하면 완성으로 판정합니다.',
'Water Ski Spree':own+'좌우로 조향해 코인이 있는 경사로를 고릅니다. 최대 17코인, 가시공 피격 시 잠깐 조향이 멈춥니다. 얻은 코인을 모두 가져가는 보너스 경기입니다.',
'Mosh-Pit Playroom':own+'200개 공 중 자기 색 50개를 모두 모으면 승리합니다. 이동/A 점프, 밟힌 상대는 잠깐 정지합니다. 5분 제한입니다.',
'Lava or Leave ’Em':own+'30초 동안 분열하는 불덩이를 피합니다. 이동/A 점프와 상대 밟기가 가능하며, 제한 시간 생존자는 모두 승리합니다.',
'Kartastrophe':own+'좌우 핸들/A 가속/B 브레이크로 두 바퀴를 달립니다. 16개 순차 체크포인트를 두 차례 지나야 하며 오프로드에서 느려집니다. 5분 제한입니다.',
'Rudder Madness':own+'수련잎을 좌우로 조향해 바위·기둥·선수를 피하는 경주입니다. 첫 도착자가 승리하며 4명 동시 도착이나 5분 미도착은 무승부입니다.',
'Sick and Twisted':own+'서로 반대로 회전하는 원형 발판 사이를 뛰고 날아오는 장애물을 피합니다. 낙하·피격·뒤처짐으로 탈락하며 끝에 도착한 선수 모두 승리합니다. 브라우저 코스는 13개 발판입니다.',
'In the Nick of Time':own+'분침을 움직이면 시침도 1/12 비율로 돌아갑니다. 중앙 시계에 먼저 맞추면 1점, 3점 선취입니다. 라운드당 20초, 10라운드 안에 승자가 없으면 무승부입니다. 맞춤 오차는 브라우저판 1.2분입니다.',
'Scooter Pursuit':own+'전후 이동/좌우 회전/A 발사로 30초 동안 명중 점수를 겨룹니다. 중앙 구조물은 탄을 막고 피격 시 잠깐 기절합니다. 각 명중 1점, 모두 0점이면 무승부입니다.',
'Flip the Chimp':own+'자동으로 나무를 오르며 A로 반대편으로 뒤집어 열매를 피합니다. 뒤집을 때 잠깐 멈추고 맞으면 미끄러집니다. 5분 제한이며 동시 도착은 공동 승리합니다.',
'Alpine Assault':own+'자동으로 내려가는 보드를 좌우로 조향하고 경사로에서 뜬 동안 A/B로 회전하면 착지 가속을 얻습니다. 눈사람 피격은 감속, 5분 제한이며 4명 동시 도착은 무승부입니다.',
'Treacherous Tightrope':own+'전진과 좌우 균형 조절로 바람 속 외줄을 건넙니다. 멈추면 흔들림이 줄어듭니다. 첫 도착자가 승리하며 모두 낙하하거나 5분이 지나면 무승부입니다.',
'Saucer Swarm':own+'좌우 포탑 회전/A 발사로 접근하는 원반을 격추합니다. 일반 1점/금색 2점, 원반 접촉 시 기절합니다. 30초 합계를 겨룹니다.',
'Glacial Meltdown':own+'미끄러운 얼음판에서 이동/A 점프/B 펀치/공중 B 발차기로 상대와 떨어지는 딱정벌레를 밀어냅니다. 마지막 생존자 또는 5분 생존자가 승리하며 전원 낙하 시 마지막에 떨어진 선수를 판정합니다.',
'Gun the Runner':own+'1P는 고정 발판과 승강기를 뛰어올라 30초 안에 탈출합니다. 2–4P는 방향키로 조준하고 A/B로 발사합니다. 재장전 1초, 명중 시 등반자 3초 정지 규칙을 적용했습니다.',
"Grabbin' Gold":own+'20초 코인 수집: 1P 넓은 바구니와 일정한 출현, 팀은 세 바구니와 불규칙 출현입니다. 가시 열매에 맞으면 수집이 잠깐 중단됩니다. 팀 코인은 합산합니다.'};
