import{clamp,dist,toward}from'../core.js';
const TAU=Math.PI*2,ink='#345961',cream='#f0e7ce';
const text=(c,id,s,x,y,z,w=4)=>c.draw(id,'text',{x,y,z,sx:w,sy:w/4,text:s,color:ink});
const hearts=c=>{c.players.forEach(p=>{p.hearts=3;p.score=3;p.inv=0;});};
const damage=(c,p,grace=.8)=>{if(p.inv||!p.alive)return false;p.hearts--;p.score=p.hearts;p.inv=grace;if(!p.hearts)c.eliminate(p);return true;};
const highHearts=c=>{const alive=c.players.filter(p=>p.alive);if(!alive.length)c.complete([],'모두 탈락');else{const h=Math.max(...alive.map(p=>p.hearts));c.complete(alive.filter(p=>p.hearts===h).map(p=>p.i),'남은 하트 수');}};
function snake(c){
 c.limit=Infinity;c.view={size:23,eye:[0,26,22],target:[0,0,0]};hearts(c);let head=12,lead=0;const point=s=>({x:Math.sin(s*.16)*3,z:-s});c.players.forEach(p=>{p.x=(p.i-1.5)*.7;p.worldZ=0;p.jumpY=0;p.vy=0;p.wait=0;});
 return{update(dt){head=Math.min(82,12+c.time*2.4);const blocks=Array.from({length:12},(_,i)=>point(Math.max(0,head-i*1.3)));for(const p of c.players){if(!p.alive)continue;p.inv=Math.max(0,p.inv-dt);p.wait=Math.max(0,p.wait-dt);if(p.wait){p.y=0;continue;}const goal=point(Math.min(74,head-2,Math.max(1,-p.worldZ+2))),q=c.input(p,()=>({...toward({x:p.x,z:p.worldZ},goal.x,goal.z),a:false}));p.x+=q.x*4.8*dt;p.worldZ+=q.z*4.8*dt;const supported=p.worldZ>-2&&p.worldZ<2&&Math.abs(p.x)<4||p.worldZ< -71&&p.worldZ> -77&&Math.abs(p.x-point(74).x)<4||blocks.some(b=>Math.abs(b.x-p.x)<1.1&&Math.abs(b.z-p.worldZ)<1.1);if(q.ap&&!p.jumpY&&supported){p.jumpY=.001;p.vy=8;}if(p.jumpY>0){p.vy-=18*dt;p.jumpY=Math.max(0,p.jumpY+p.vy*dt);}if(!supported&&!p.jumpY&&damage(c,p)){p.wait=.8;const at=point(Math.min(74,head-4));p.x=at.x;p.worldZ=at.z;}p.y=p.jumpY;p.pose=p.y?'jump':'run';if(p.worldZ<=-74&&p.alive)c.complete([p.i],'뱀 블록 길의 결승점 도착');}lead=Math.max(...c.players.filter(p=>p.alive).map(p=>-p.worldZ),0);for(const p of c.players)p.z=p.worldZ+lead-3;c.lastStanding();c.hint('이동/A 점프 · 굽이치며 움직이는 블록 길을 따라가세요 · 낙하마다 하트 감소, 3번 떨어지면 탈락');},render(){for(let i=0;i<12;i++){const b=point(Math.max(0,head-i*1.3)),z=b.z+lead-3;if(Math.abs(z)<16)c.draw('snake'+i,'box',{x:b.x,y:-.2,z,sx:2.2,sy:.4,sz:2.2,color:i%2?'#a8c991':'#b7d6a0'});}for(const s of[0,74]){const b=point(s),z=b.z+lead-3;if(Math.abs(z)<18)c.draw('island'+s,'box',{x:b.x,y:-.25,z,sx:8,sy:.5,sz:6,color:'#d1c89e'});}}};
}
function cheep(c){
 c.limit=30;c.view={size:21,eye:[0,17,25],target:[0,2,0]};const fish=[];let next=.4,id=0;c.bounds={x:8,z:2.5};c.players.forEach(p=>{p.x=(p.i-1.5)*3;p.z=0;});
 return{update(dt){if(c.time>next){for(let i=0;i<8;i++){const r=c.rand(),value=r<.1?3:r<.3?2:1;fish.push({id:id++,x:c.rand(-8,8),z:-7-c.rand(0,3),y:0,speed:c.rand(5,7),height:c.rand(2,3.8),value});}next=c.time+1.5;}for(const b of fish){b.z+=b.speed*dt;b.y=Math.max(0,Math.sin((b.z+7)/14*Math.PI))*b.height;if(b.z>7)b.dead=true;}for(const p of c.players){const goal=fish.filter(b=>!b.dead&&b.z>-5&&b.z<3).sort((a,b)=>Math.abs(a.x-p.x)+Math.abs(a.z-p.z)*.3-(Math.abs(b.x-p.x)+Math.abs(b.z-p.z)*.3))[0],q=c.input(p,()=>({...toward(p,goal?.x??p.x,goal?clamp(goal.z,-2,2):p.z),a:!!goal&&Math.abs(goal.x-p.x)<1.3&&goal.z>p.z-2.8&&p.y===0}));c.move(p,q,5);c.jump(p,q,9);for(const b of fish)if(!b.dead&&dist(p,b)<.8&&Math.abs(p.y+1-b.y)<.8){b.dead=true;c.points(p,b.value);}p.pose=p.y?'jump':'run';}c.hint('이동/A 점프 · 반짝이는 무적 상태로 물고기 잡기 · 일반 1점/큰 물고기 2점/금 물고기 3점');},render(){c.arena({width:18,depth:6,color:'#c5b394'});for(const b of fish)if(!b.dead)c.draw('fish'+b.id,'sphere',{x:b.x,y:b.y,z:b.z,sx:b.value===2?1.25:.7,sy:b.value===2?1:.6,sz:.5,color:b.value===3?'#e5c257':'#dd969e'});for(const p of c.players)c.draw('star'+p.i,'ring',{x:p.x,y:p.y+.08,z:p.z,sx:1.4,sy:1.4,sz:1,rx:-Math.PI/2,color:'#f5d477',glow:true});},timeout(){c.highest('30초 동안 잡은 물고기 점수');}};
}
function peepa(c){
 c.limit=Infinity;c.view={size:22,eye:[0,23,20],target:[0,0,0]};hearts(c);const ghosts=Array.from({length:26},(_,i)=>({id:i,x:c.rand(-6,6),at:6+i*2.5,phase:c.rand(0,TAU)}));let lead=0;c.players.forEach(p=>{p.x=(p.i-1.5)*2;p.distance=0;p.caught=0;p.escape=0;});
 return{update(dt){for(const g of ghosts)g.drawX=clamp(g.x+Math.sin(c.time*1.5+g.phase)*1.6,-6.5,6.5);const done=[];for(const p of c.players){if(!p.alive)continue;p.inv=Math.max(0,p.inv-dt);const obstacle=ghosts.find(g=>g.at>p.distance&&g.at<p.distance+5&&Math.abs(g.drawX-p.x)<1.7),goal=obstacle?clamp(obstacle.drawX+(p.x>=obstacle.drawX?2.3:-2.3),-6.5,6.5):p.x,q=c.input(p,{x:clamp((goal-p.x)*2,-1,1),z:-1,a:p.caught>0&&Math.floor(c.time*12)%2===0});if(p.caught){p.caught+=dt;if(q.ap)p.escape++;p.y=p.caught*1.8;if(p.escape>=6){p.caught=0;p.y=0;p.inv=1.2;}else if(p.caught>=2.2)c.eliminate(p);}else{p.x=clamp(p.x+q.x*4.5*dt,-7,7);p.distance=Math.max(0,p.distance-q.z*4.5*dt);if(!p.inv&&ghosts.some(g=>Math.abs(g.at-p.distance)<.7&&Math.abs(g.drawX-p.x)<.8)){damage(c,p,0);p.caught=.001;p.escape=0;}}if(p.distance>=76&&p.alive)done.push(p);}if(done.length){if(done.length===2&&c.players.filter(p=>p.alive).length===2){const hp=Math.max(...done.map(p=>p.hearts)),best=done.filter(p=>p.hearts===hp);c.complete(best.length===2?[]:best.map(p=>p.i),'두 생존자 동시 도착: 남은 하트 비교');}else c.complete(done.map(p=>p.i),'저택의 출구에 도착');}lead=Math.max(...c.players.map(p=>p.distance));for(const p of c.players)p.z=4+(lead-p.distance)*.6;c.lastStanding();c.hint('방향으로 저택 통과 · 잡히면 A 연타로 탈출 · 잡힐 때 하트 감소, 하트가 남아도 끌려가면 탈락');},render(){c.arena({width:16,depth:25,color:'#aeb9b5'});for(const g of ghosts){const z=4-(g.at-lead)*.6;if(Math.abs(z)<14){c.draw('ghost'+g.id,'sphere',{x:g.drawX??g.x,y:1,z,sx:1.5,sy:1.8,sz:1.5,color:'#cabbd6',opacity:.7});c.draw('eye'+g.id,'sphere',{x:(g.drawX??g.x)-.2,y:1.2,z:z+.65,sx:.15,sy:.2,sz:.15,color:ink});}}}};
}
function balance(c){
 c.limit=120;c.view={size:26,eye:[0,28,22],target:[0,0,0]};const bases=[[-6,-4.5],[6,-4.5],[-6,4.5],[6,4.5]],targets=Array.from({length:9},(_,i)=>({x:(i%3-1)*2.4,z:(Math.floor(i/3)-1)*2.1}));c.players.forEach(p=>{p.local={x:0,z:0};p.vx=0;p.vz=0;p.seen=new Set();p.y=.8;p.scale=.65;});
 return{update(dt){const done=[];for(const p of c.players){const target=targets.filter((v,i)=>!p.seen.has(i)).sort((a,b)=>dist(p.local,a)-dist(p.local,b))[0],q=c.input(p,target?toward(p.local,target.x-p.vx*.3,target.z-p.vz*.3):{});p.vx=(p.vx+q.x*7*dt)*Math.exp(-dt*2.2);p.vz=(p.vz+q.z*7*dt)*Math.exp(-dt*2.2);p.local.x=clamp(p.local.x+p.vx*dt,-3.6,3.6);p.local.z=clamp(p.local.z+p.vz*dt,-3.4,3.4);targets.forEach((v,i)=>{if(!p.seen.has(i)&&dist(p.local,v)<.62){p.seen.add(i);c.points(p);}});if(p.seen.size===targets.length)done.push(p.i);p.x=bases[p.i][0]+p.local.x;p.z=bases[p.i][1]+p.local.z;p.pose='balance';}if(done.length)c.complete(done,'모든 스위치를 눌렀습니다');c.hint('방향으로 균형공 기울이기 · 관성에 주의하며 자기 구역의 스위치를 모두 누르세요');},render(){for(const p of c.players){const[x,z]=bases[p.i];c.draw('board'+p.i,'box',{x,y:-.2,z,sx:8,sy:.4,sz:7.5,color:'#bbcec1'});targets.forEach((v,i)=>c.draw('switch'+p.i+'_'+i,'cylinder',{x:x+v.x,y:.03,z:z+v.z,sx:1,sy:.08,sz:1,color:p.seen.has(i)?p.color:'#e9dfc1'}));c.draw('ball'+p.i,'sphere',{x:p.x,y:.4,z:p.z,sx:.9,sy:.9,sz:.9,color:p.color});}},timeout(){c.complete([],'2분 안에 모든 스위치를 누르지 못했습니다');}};
}
function bogey(c){
 c.limit=Infinity;c.view={size:23,eye:[0,15,25],target:[0,1,0]};let balls=0,bomb=false,phase='wait',at=.8,deadline=0,rank=0;const points=[50,30,20,10];c.players.forEach(p=>{p.x=(p.i-1.5)*5;p.z=0;p.hit=false;p.cool=0;});const fresh=()=>{bomb=c.rand()<.3;phase='hit';deadline=c.time+1.2;rank=0;c.players.forEach(p=>{p.hit=false;p.react=c.time+c.rand(.18,.65);p.tempt=bomb&&c.rand()<.07;});};
 return{update(dt){if(phase==='wait'&&c.time>=at)fresh();for(const p of c.players){p.cool-=dt;const q=c.input(p,{a:phase==='hit'&&!p.hit&&c.time>=p.react&&(!bomb||p.tempt)});if(q.ap&&p.cool<=0){p.cool=.3;p.swing=c.time;if(phase==='hit'&&!p.hit){p.hit=true;if(bomb)c.points(p,-50);else c.points(p,points[Math.min(rank++,3)]);}}}if(phase==='hit'&&(c.time>=deadline||c.players.every(p=>p.hit))){if(!bomb)balls++;if(balls===10)c.highest('공 열 개의 반응 속도 합계');else{phase='wait';at=c.time+c.rand(.5,1.2);}}c.hint(`A로 빠르게 스윙 · 1·2·3·4번째 50·30·20·10점 · 폭탄은 -50점 · ${balls}/10개`);},render(){c.arena({width:23,depth:9,color:'#b4cca6'});for(const p of c.players){if(phase==='hit'&&!p.hit)c.draw('ball'+p.i,'sphere',{x:p.x+1.1,y:.25,z:-1,sx:bomb?.65:.4,sy:bomb?.65:.4,sz:bomb?.65:.4,color:bomb?'#657381':cream});const swinging=c.time-(p.swing??-1)<.2;c.draw('club'+p.i,'box',{x:p.x+.5,y:.5,z:swinging?-1:.3,sx:.08,sy:1.3,sz:.08,rx:swinging?1.3:.1,color:ink});}text(c,'count',`${balls}/10`,0,1,-4,5);}};
}
function spiked(c){
 c.limit=Infinity;c.view={size:24,eye:[0,25,22],target:[0,0,0]};const hazards=Array.from({length:6},(_,i)=>({at:i*12+6,side:c.pick([-1,1]),phase:c.rand(0,TAU),large:i>3}));let lead=0;c.players.forEach(p=>{p.x=(p.i-1.5)*1.3;p.distance=0;p.finished=false;p.branch=c.pick([-1,1]);});
 return{update(dt){for(const h of hazards){h.x=h.side*3+Math.sin(c.time*1.7+h.phase)*(h.large?3.5:1.5);h.r=h.large?.9:.65;}for(const p of c.players){if(!p.alive||p.finished)continue;const phase=p.distance%12,near=hazards.find(h=>h.at>p.distance-1&&h.at<p.distance+4),targetX=phase>1&&phase<10?p.branch*3:phase>=10?p.branch*3:p.x;let avoid=targetX;if(near&&near.at-p.distance<2.5&&Math.abs(near.x-targetX)<2)avoid=clamp(targetX+(targetX>near.x?.8:-.8),p.branch*3-1,p.branch*3+1);const q=c.input(p,{x:clamp((avoid-p.x)*2,-1,1),z:near&&near.at-p.distance<2&&Math.abs(near.x-p.x)<1.5?0:-1});p.x+=q.x*4.8*dt;p.distance=Math.max(0,p.distance-q.z*4.8*dt);const d=p.distance%12,onFloor=d<3||d>9?Math.abs(p.x)<5.5:Math.abs(Math.abs(p.x)-3)<1.5;if(!onFloor||hazards.some(h=>Math.abs(h.at-p.distance)<h.r+.35&&Math.abs(h.x-p.x)<h.r+.35))c.eliminate(p);if(p.distance>=74&&p.alive){p.finished=true;p.score=1;}p.pose='run';}const live=c.players.filter(p=>p.alive);if(live.length<=1)c.complete(live.map(p=>p.i),'마지막 생존자');else if(c.players.every(p=>!p.alive||p.finished))c.complete(c.players.filter(p=>p.finished).map(p=>p.i),'출구에 도착한 선수');lead=Math.max(...c.players.filter(p=>p.alive).map(p=>p.distance),0);for(const p of c.players)p.z=4+(lead-p.distance)*.6;c.hint('방향 이동 · 좁은 두 갈래 길과 흔들리는 가시추 · 문 뒤 위험은 가까이 가야 보입니다');},render(){for(let i=0;i<6;i++){const d=i*12,z=4-(d-lead)*.6;if(Math.abs(z)<21){for(const x of[-3,3])c.draw('path'+i+'_'+x,'box',{x,y:-.2,z:z-3.6,sx:3,sy:.4,sz:7.2,color:'#a6c593'});c.draw('cross'+i,'box',{x:0,y:-.2,z,sx:11,sy:.4,sz:3.6,color:'#bfd1a6'});if(lead<d+1)c.draw('door'+i,'box',{x:0,y:1.8,z:z-1,sx:11,sy:3.6,sz:.2,color:'#a7b7b1'});}const h=hazards[i],hz=4-(h.at-lead)*.6;if(Math.abs(hz)<14&&lead>d+.5){c.draw('spike'+i,'sphere',{x:h.x??h.side*3,y:.6,z:hz,sx:h.large?1.8:1.3,sy:h.large?1.8:1.3,sz:h.large?1.8:1.3,color:'#879096'});for(let k=0;k<8;k++)c.draw('thorn'+i+'_'+k,'cone',{x:(h.x??0)+Math.cos(k*TAU/8)*(h.r??.65),y:.6,z:hz+Math.sin(k*TAU/8)*(h.r??.65),sx:.4,sy:.55,sz:.4,rz:Math.PI/2,color:'#65777e'});}}}};
}
function bouncy(c){
 c.limit=30;c.view={size:19,eye:[0,20,20],target:[0,0,0]};c.players.forEach(p=>{p.x=(p.i%2?1:-1)*2.5;p.z=p.i<2?-2.5:2.5;p.spin=0;p.botLimit=c.rand(5.4,6.5);p.botRate=c.rand(6,9);p.dizzy=0;p.vx=p.vz=0;});
 return{update(dt){for(const p of c.players){if(!p.alive)continue;p.dizzy=Math.max(0,p.dizzy-dt);p.spin=Math.max(0,p.spin-dt*1.4);const target=c.players.filter(o=>o!==p&&o.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0],goal=Math.hypot(p.x,p.z)>4?{x:0,z:0}:target||{x:0,z:0},q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:p.spin<p.botLimit&&Math.floor(c.time*p.botRate+p.i)%2===0}));if(!p.dizzy){if(q.ap)p.spin+=1.05;c.move(p,q,3.2,false);}if(p.spin>7){p.spin=0;p.dizzy=4;}p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-dt*3);p.vz*=Math.exp(-dt*3);p.y=Math.abs(Math.sin(c.time*6+p.i))*1.2;p.rotation+=p.spin*dt;p.pose='jump';p.score=Math.round(p.spin*10)/10;if(Math.hypot(p.x,p.z)>6)c.eliminate(p);}for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=c.players[i],b=c.players[j];if(!a.alive||!b.alive||dist(a,b)>1.2)continue;const v=toward(a,b.x,b.z),d=dist(a,b)||1;a.x-=v.x*(1.21-d)/2;b.x+=v.x*(1.21-d)/2;a.z-=v.z*(1.21-d)/2;b.z+=v.z*(1.21-d)/2;const force=2+Math.abs(a.spin-b.spin)*1.2;if(a.spin>=b.spin){b.vx=v.x*force;b.vz=v.z*force;}if(b.spin>=a.spin){a.vx=-v.x*force;a.vz=-v.z*force;}}c.lastStanding();c.hint('이동/A 연타로 회전 강화 · 너무 빠르게 돌면 4초 어지럼 · 회전이 약한 상대를 더 멀리 밀어냅니다');},render(){c.arena({width:12,depth:12,shape:'cylinder',color:'#a6bdc4'});for(const p of c.players)if(p.alive)c.draw('spin'+p.i,'ring',{x:p.x,y:p.y+.2,z:p.z,sx:1+p.spin*.12,sy:1+p.spin*.12,sz:1,rx:-Math.PI/2,color:p.dizzy?'#aaa3a6':p.color});},timeout(){c.survivors('30초 동안 트램펄린에 생존');}};
}
function cliff(c){
 c.limit=30;c.view={size:22,eye:[0,22,23],target:[0,0,0]};let wave=-1,upper=[],lower=[];const state=Array.from({length:5},()=>({front:-3,edge:3}));c.players.forEach(p=>{p.x=(p.i-1.5)*2.3;p.z=0;});
 return{update(dt){const n=Math.floor(c.time/2.5),phase=c.time%2.5;if(n!==wave){wave=n;upper=c.shuffle([0,1,2,3,4]).slice(0,2);lower=c.shuffle([0,1,2,3,4]).slice(0,2);}const amount=phase<.65?0:phase<1.15?(phase-.65)/.5:phase<1.8?1:Math.max(0,1-(phase-1.8)/.7);state.forEach((s,i)=>{s.front=-3+(upper.includes(i)?amount*4:0);s.edge=3-(lower.includes(i)?amount*4:0);});for(const p of c.players){if(!p.alive)continue;const safe=[0,1,2,3,4].filter(i=>!upper.includes(i)&&!lower.includes(i)),lane=(safe.length?safe:[0,1,2,3,4]).sort((a,b)=>Math.abs((a-2)*2.8-p.x)-Math.abs((b-2)*2.8-p.x))[0],goal={x:(lane-2)*2.8,z:0},q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:phase>.5&&phase<1.2&&p.y===0&&Math.abs(p.x-goal.x)>1}));c.move(p,q,5,false);c.jump(p,q,8);const at=clamp(Math.floor((p.x+7)/2.8),0,4),s=state[at];if(p.y<2&&p.z<s.front+.35)p.z=s.front+.35;if(Math.abs(p.x)>7||p.y===0&&(p.z>s.edge||p.z< -3))c.eliminate(p);}const live=c.players.filter(p=>p.alive);if(live.length<=1){if(live.length)c.complete(live.map(p=>p.i),'마지막 생존자');else{const last=Math.max(...c.players.map(p=>p.outAt));c.complete(c.players.filter(p=>p.outAt===last).map(p=>p.i),'가장 오래 버틴 선수');}}c.hint('이동/A 점프 · 주황색 경고 확인 · 위 벽은 밀고 아래 발판은 뒤로 들어갑니다');},render(){for(let i=0;i<5;i++){const s=state[i],x=(i-2)*2.8;c.draw('floor'+i,'box',{x,y:-.3,z:(s.edge-3)/2,sx:2.75,sy:.6,sz:s.edge+3,color:lower.includes(i)&&c.time%2.5<.65?'#deb781':'#b9c9b8'});c.draw('wall'+i,'box',{x,y:1.3,z:s.front-1.1,sx:2.7,sy:2.6,sz:2.2,color:upper.includes(i)&&c.time%2.5<.65?'#deb781':'#a5b6b2'});}},timeout(){c.survivors('30초 동안 절벽 발판에 생존');}};
}
function fruit(c){
 c.limit=30;c.view={size:21,eye:[0,23,20],target:[0,0,0]};const objects=[];let next=.2,id=0;c.players.forEach(p=>{p.x=(p.i-1.5)*3;p.z=0;p.stun=0;p.inv=0;});
 return{update(dt){if(c.time>next){objects.push({id:id++,x:c.rand(-7.5,7.5),z:-8,spike:c.rand()<.22,v:c.rand(2,3)});next=c.time+.16;}for(const b of objects){b.z+=b.v*dt;if(b.z>8)b.dead=true;}for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.inv=Math.max(0,p.inv-dt);const target=objects.filter(b=>!b.dead&&!b.spike&&b.z> -6&&b.z<5).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...toward(p,target?.x??0,target?.z??-2),a:objects.some(b=>!b.dead&&b.spike&&dist(p,b)<1.4)&&p.y===0}));if(!p.stun)c.move(p,q,5,false);p.z+=dt*1.1;p.x=clamp(p.x,-8.4,8.4);p.z=Math.max(-6.5,p.z);c.jump(p,q,8);for(const b of objects)if(!b.dead&&dist(p,b)<.65&&p.y<1.1){if(b.spike){if(!p.inv){p.score=Math.max(0,p.score-3);p.stun=.6;p.inv=1;}}else{b.dead=true;c.points(p);}}if(p.z>6.5){p.score=Math.max(0,p.score-3);p.x=c.rand(-5,5);p.z=-5;p.stun=1;p.inv=1;}p.pose=p.y?'jump':'run';}c.hint('이동/A 점프 · 흐르는 물에서 과일 수집 · 성게 접촉과 폭포 추락은 3점 손실');},render(){c.arena({width:18,depth:15,color:'#a3cdcc'});c.draw('waterfall','box',{x:0,y:-2,z:7.5,sx:18,sy:4,sz:.5,color:'#c2e2dc'});for(const b of objects)if(!b.dead)c.draw('item'+b.id,b.spike?'cone':'sphere',{x:b.x,y:.4,z:b.z,sx:b.spike?.9:.55,sy:b.spike?.9:.55,sz:b.spike?.9:.55,color:b.spike?'#7e92a6':'#e5b773'});},timeout(){c.highest('모은 과일 수');}};
}
function beeline(c){
 c.limit=30;c.view={size:21,eye:[0,23,20],target:[0,0,0]};hearts(c);const bees=[];let next=.5,id=0,wave=0;c.bounds={x:8,z:5};c.players.forEach(p=>{p.x=(p.i%2?1:-1)*5;p.z=p.i<2?-3:3;});
 return{update(dt){if(c.time>next){const kind=wave++%3,offset=c.rand(-3,3);for(let i=0;i<12;i++){const a=i*TAU/12;bees.push({id:id++,x:kind===0?offset+Math.cos(a)*3:kind===1?(i%6-2.5)*2:offset+(i%3-1)*2,z:-10+(kind===0?Math.sin(a)*3:kind===1?Math.floor(i/6)*2:Math.floor(i/3)*1.6)});}next=c.time+3;}for(const b of bees)b.z+=3*dt;for(const p of c.players){if(!p.alive)continue;p.inv=Math.max(0,p.inv-dt);const nearby=bees.filter(b=>b.z>-7&&b.z<7),goals=Array.from({length:12},(_,i)=>({x:clamp(p.x+Math.cos(i*TAU/12)*1.6,-7.5,7.5),z:clamp(p.z+Math.sin(i*TAU/12)*1.6,-4.5,4.5)})),goal=goals.sort((a,b)=>Math.min(...nearby.map(v=>dist(b,v)),20)-Math.min(...nearby.map(v=>dist(a,v)),20))[0],q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:nearby.some(b=>dist(p,b)<1.4)&&p.y===0}));c.move(p,q,4.6);c.jump(p,q,8);if(p.y<.9&&nearby.some(b=>dist(p,b)<.65))damage(c,p,1);}c.lastStanding();c.hint('이동/A 점프 · 원·줄·격자 대형의 벌 떼를 피하세요 · 하트 3개, 30초 뒤 남은 하트 비교');},render(){c.arena({width:18,depth:13,color:'#b9c79c'});for(const b of bees)if(b.z> -13&&b.z<10){c.draw('bee'+b.id,'sphere',{x:b.x,y:.65,z:b.z,sx:.7,sy:.5,sz:.5,color:'#d8b363'});c.draw('wing'+b.id,'box',{x:b.x,y:.9,z:b.z,sx:1,sy:.05,sz:.3,color:cream});}},timeout(){highHearts(c);}};
}
function blastoff(c){
 c.limit=120;let cameraY=5;const torpedoes=Array.from({length:10},(_,i)=>({id:i,y:8+i*5,x:c.rand(-9,9),direction:i%2?1:-1})),jets=Array.from({length:8},(_,i)=>({id:i,y:10+i*6,side:i%2?1:-1}));c.players.forEach(p=>{p.x=(p.i-1.5)*3;p.y=0;p.z=0;p.angle=0;p.vx=0;p.vy=0;p.stun=0;p.inv=0;});
 return{update(dt){for(const t of torpedoes){t.x+=t.direction*3.3*dt;if(Math.abs(t.x)>10)t.x=-t.direction*10;}const done=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.inv=Math.max(0,p.inv-dt);const threat=torpedoes.find(t=>t.y>p.y&&t.y<p.y+5&&Math.abs(t.x-p.x)<2),goal=threat?clamp(threat.x+(p.x>threat.x?3:-3),-7,7):p.x*.5,desired=clamp((goal-p.x)*.35,-1.1,1.1),q=c.input(p,{x:clamp((desired-p.angle)*2,-1,1),a:Math.floor(c.time*9+p.i)%2===0});if(!p.stun){p.angle=clamp(p.angle+q.x*2*dt,-1.3,1.3);if(q.ap){p.vx+=Math.sin(p.angle)*2.2;p.vy+=Math.cos(p.angle)*2.2;}}p.vx*=Math.exp(-dt*1.6);p.vy*=Math.exp(-dt*1.4);for(const j of jets)if(Math.abs(p.y-j.y)<1&&Math.abs(p.x-j.side*7)<5)p.vx-=j.side*dt*9;p.x=clamp(p.x+p.vx*dt,-8,8);p.y=Math.max(0,p.y+p.vy*dt);if(!p.inv&&torpedoes.some(t=>Math.hypot(t.x-p.x,t.y-p.y)<.85)){p.stun=1;p.inv=1.2;p.vx=p.vy=0;}p.rotation=p.angle;p.pose='sit';p.score=Math.floor(p.y);if(p.y>60)done.push(p.i);}if(done.length)c.complete(done,'수면의 점선을 먼저 통과');cameraY=Math.max(5,Math.max(...c.players.map(p=>p.y))-3);c.view={size:23,eye:[0,cameraY+4,28],target:[0,cameraY,0]};c.hint('좌우로 잠수정 각도 조절/A 반복 추진 · 어뢰에 맞으면 1초 정지 · 파이프 물살을 피해서 수면으로');},render(){c.draw('water','box',{x:0,y:cameraY,z:-2,sx:21,sy:26,sz:.3,color:'#9ac6d0'});for(const t of torpedoes)if(Math.abs(t.y-cameraY)<15)c.draw('torpedo'+t.id,'sphere',{x:t.x,y:t.y,z:0,sx:1.5,sy:.65,sz:.65,color:'#7d96a5'});for(const j of jets)if(Math.abs(j.y-cameraY)<15){c.draw('pipe'+j.id,'box',{x:j.side*8,y:j.y,z:0,sx:2,sy:.9,sz:1,color:'#c3b99e'});c.draw('current'+j.id,'box',{x:j.side*5.5,y:j.y,z:0,sx:4,sy:.25,sz:.4,color:'#dcebdc',opacity:.6});}for(const p of c.players)c.draw('sub'+p.i,'sphere',{x:p.x,y:p.y-.2,z:0,sx:1.1,sy:1.6,sz:1.1,rz:-p.angle,color:p.color});if(cameraY>45)for(let i=0;i<12;i++)c.draw('finish'+i,'box',{x:i*1.5-8,y:60,z:.2,sx:.8,sy:.15,sz:.2,color:cream});},timeout(){c.complete([],'2분 안에 수면에 도착하지 못했습니다');}};
}
function paintball(c){
 c.limit=30;c.view={size:22,eye:[0,25,20],target:[0,0,0]};hearts(c);c.bounds={x:8,z:6};const tiles=Array.from({length:63},()=>c.rand()<.22?.65:0),shots=[];let id=0;const height=(x,z)=>tiles[clamp(Math.floor((z+7)/2),0,6)*9+clamp(Math.floor((x+9)/2),0,8)];c.players.forEach(p=>{p.x=(p.i%2?1:-1)*6;p.z=p.i<2?-4:4;p.angle=0;p.cool=c.rand(0,.7);p.cadence=c.rand(.35,.65);});
 return{update(dt){for(const p of c.players){if(!p.alive)continue;p.inv=Math.max(0,p.inv-dt);p.cool-=dt;const target=c.players.filter(o=>o!==p&&o.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0],q=c.input(p,()=>({...toward(p,target?.x??0,target?.z??0),a:!!target&&p.cool<=0}));c.move(p,q,4);if(Math.hypot(q.x,q.z)>.1)p.angle=Math.atan2(q.z,q.x);p.y=height(p.x,p.z);if((q.a||q.b)&&p.cool<=0){p.cool=p.cadence;shots.push({id:id++,owner:p.i,x:p.x+Math.cos(p.angle)*.7,z:p.z+Math.sin(p.angle)*.7,y:p.y+.7,vx:Math.cos(p.angle)*10,vz:Math.sin(p.angle)*10});}}for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=c.players[i],b=c.players[j],d=dist(a,b);if(a.alive&&b.alive&&d<1.2&&d>.001){const v=toward(a,b.x,b.z),push=(1.2-d)/2;a.x-=v.x*push;a.z-=v.z*push;b.x+=v.x*push;b.z+=v.z*push;}}for(const b of shots){if(b.dead)continue;b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>9||Math.abs(b.z)>7)b.dead=true;}for(let i=0;i<shots.length;i++)for(let j=i+1;j<shots.length;j++){const a=shots[i],b=shots[j];if(!a.dead&&!b.dead&&a.owner!==b.owner&&dist(a,b)<.45&&Math.abs(a.y-b.y)<.4)a.dead=b.dead=true;}for(const b of shots)if(!b.dead){const p=c.players.find(p=>p.alive&&p.i!==b.owner&&dist(p,b)<.7&&Math.abs(p.y+.7-b.y)<.5);if(p){b.dead=true;damage(c,p,.6);}}const live=c.players.filter(p=>p.alive);if(live.length===1)c.complete(live.map(p=>p.i),'마지막 생존자');else if(!live.length){const last=Math.max(...c.players.map(p=>p.outAt)),lastGroup=c.players.filter(p=>p.outAt===last);c.complete(lastGroup.length===4?[]:lastGroup.map(p=>p.i),'마지막 피격의 동시 판정');}c.hint('방향 이동으로 조준/A 발사 · 페인트탄끼리 만나면 상쇄 · 하트 3개, 높은 발판은 탄의 높이도 바꿉니다');},render(){for(let z=0;z<7;z++)for(let x=0;x<9;x++){const h=tiles[z*9+x];c.draw('tile'+x+'_'+z,'box',{x:(x-4)*2,y:(h-.3)/2,z:(z-3)*2,sx:1.97,sy:h+.3,sz:1.97,color:h?'#b1bdaa':'#c5d0b9'});}for(const b of shots)if(!b.dead)c.draw('shot'+b.id,'sphere',{x:b.x,y:b.y,z:b.z,sx:.3,sy:.3,sz:.3,color:c.players[b.owner].color});},timeout(){highHearts(c);}};
}
function ice(c){
 c.limit=Infinity;c.view={size:25,eye:[0,24,22],target:[0,0,0]};const obstacles=Array.from({length:12},(_,i)=>({at:12+i*11,duck:i%2===0}));let lead=0;c.players.forEach(p=>{p.x=(p.i-1.5)*5;p.distance=0;p.stun=0;p.seen=new Set();p.burst=0;p.skill=c.rand(.85,1);});
 return{update(dt){const done=[];for(const p of c.players){p.stun=Math.max(0,p.stun-dt);const next=obstacles.find(o=>o.at>p.distance&&o.at<p.distance+4),q=c.input(p,()=>({a:p.distance>150?Math.floor(c.time*10*p.skill)%2===0:!!next&&!next.duck&&next.at-p.distance<2.5&&p.y===0,b:!!next&&next.duck}));p.duck=!!q.b;if(p.distance<150)c.jump(p,q,8);else{p.y=0;if(q.ap)p.burst=clamp(p.burst+.22,0,3);p.burst=Math.max(0,p.burst-dt*.2);}const speed=p.stun?1.3:5+p.burst;p.distance+=speed*dt;for(const o of obstacles)if(!p.seen.has(o.at)&&Math.abs(o.at-p.distance)<.35){p.seen.add(o.at);if(o.duck?!p.duck||p.y>.1:p.y<.6)p.stun=1;}if(p.distance>=195)done.push(p.i);p.score=Math.floor(p.distance);p.pose=p.duck?'sit':p.y?'jump':'run';}if(done.length)c.complete(done,'얼음길 결승선 도착');lead=Math.max(...c.players.map(p=>p.distance));for(const p of c.players)p.z=4+(lead-p.distance)*.45;c.hint('A 점프/B 숙이기 · 눈덩이는 넘고 높은 장애물 밑은 숙이세요 · 마지막 직선은 A 연타로 가속');},render(){for(const p of c.players){c.draw('ice'+p.i,'box',{x:p.x,y:-.2,z:0,sx:4.5,sy:.3,sz:26,color:'#d6e6e4'});for(const o of obstacles){const z=4-(o.at-lead)*.45;if(z< -14||z>14)continue;c.draw('obstacle'+p.i+'_'+o.at,o.duck?'box':'sphere',{x:p.x,y:o.duck?1.8:.4,z,sx:o.duck?4:1.2,sy:o.duck?.65:.8,sz:1,color:o.duck?'#aebec5':cream});}}}};
}
function gallop(c){
 c.limit=Infinity;c.view={size:23,eye:[0,24,21],target:[0,0,0]};let round=0,phase='watch',until=0,rank=0,correct=0,flock=[],serial=0;const colors=['#d98fa9','#d3b065','#91b6c7'];const fresh=()=>{round++;const counts=[c.int(7,12),c.int(7,12),c.int(7,12)];correct=c.int(0,2);counts[correct]=Math.max(...counts)+2;flock=[];for(let type=0;type<3;type++)for(let i=0;i<counts[type];i++)flock.push({id:serial++,type,x:c.rand(-7,7),start:-8-c.rand(0,7),delay:c.rand(0,.5)});phase='watch';until=c.time+9;rank=0;c.players.forEach(p=>{p.choice=0;p.answered=false;p.repeat=0;p.guess=c.rand()<.88?correct:c.int(0,2);p.reaction=c.rand(.35,1.3);p.start=c.time;});};c.players.forEach(p=>{p.x=(p.i-1.5)*4;p.z=6;p.scale=.6;});fresh();
 return{update(dt){if(phase==='watch'&&c.time>=until){phase='answer';until=c.time+10;c.players.forEach(p=>p.answerAt=c.time+p.reaction);}for(const p of c.players){p.repeat-=dt;const q=c.input(p,{x:phase==='answer'?Math.sign(p.guess-p.choice):0,a:phase==='answer'&&c.time>=p.answerAt&&p.choice===p.guess});if(phase!=='answer'||p.answered)continue;if(p.i===0&&q.pointer.worldValid)p.choice=clamp(Math.round(q.pointer.worldX/5)+1,0,2);else if(p.repeat<=0&&Math.abs(q.x)>.4){p.choice=clamp(p.choice+Math.sign(q.x),0,2);p.repeat=.18;}if(q.ap||q.pointer.pressed){p.answered=true;if(p.choice===correct)c.points(p,[5,3,2,1][Math.min(rank++,3)]);}}if(phase==='answer'&&(c.players.every(p=>p.answered)||c.time>=until)){if(round===2)c.highest('두 차례 무리 세기 합계');else fresh();}c.hint(phase==='watch'?`${round}/2라운드 · 세 종류의 새 중 가장 많은 무리를 기억하세요`:'좌우 또는 포인터로 종류 선택/A 확정 · 정답 순서대로 5·3·2·1점 · 10초');},render(){c.arena({width:19,depth:15,color:'#bfd0a2'});if(phase==='watch'){const elapsed=c.time-c.players[0].start;for(const b of flock){const z=b.start+(elapsed-b.delay)*3;if(z< -10||z>9)continue;const x=b.x+(b.type===1?Math.sin(elapsed*2+b.id)*.7:b.type===2?Math.sin(elapsed*.7+b.id)*1.3:0);c.draw('bird'+b.id,b.type===0?'sphere':b.type===1?'box':'cone',{x,y:.4,z,sx:.65,sy:.8,sz:.65,color:colors[b.type]});}if(round===2&&elapsed>4&&elapsed<4.5)c.draw('glider','box',{x:0,y:5,z:0,sx:14,sy:.2,sz:4,color:'#a0ad94'});}else{for(let i=0;i<3;i++){c.draw('answer'+i,'box',{x:(i-1)*5,y:.1,z:0,sx:3.5,sy:.2,sz:3.5,color:colors[i]});text(c,'name'+i,['ROUND','SQUARE','CREST'][i],(i-1)*5,.6,0,3);}for(const p of c.players)c.draw('cursor'+p.i,'ring',{x:(p.choice-1)*5+(p.i-1.5)*.5,y:.3,z:1.5,sx:.45,sy:.45,sz:1,rx:-Math.PI/2,color:p.color});}}};
}
function platform(c){
 c.limit=30;c.view={size:21,eye:[0,24,20],target:[0,0,0]};let edge=6;c.players.forEach(p=>{p.x=(p.i%2?1:-1)*3;p.z=p.i<2?-3:3;p.vx=p.vz=0;p.cool=0;p.stun=0;});
 return{update(dt){edge=c.time<5?6:c.time<18?4.5:3;for(const p of c.players){if(!p.alive)continue;p.cool-=dt;p.stun=Math.max(0,p.stun-dt);const other=c.players.filter(o=>o!==p&&o.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0],goal=Math.max(Math.abs(p.x),Math.abs(p.z))>edge-1.2?{x:0,z:0}:other||{x:0,z:0},q=c.input(p,()=>({...toward(p,goal.x,goal.z),a:!!other&&dist(p,other)<1.8&&Math.floor(c.time*3+p.i)%2===0&&p.y===0,b:!!other&&dist(p,other)<1.8&&p.cool<=0}));if(!p.stun)c.move(p,q,3.8,false);p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-dt*3);p.vz*=Math.exp(-dt*3);c.jump(p,q,8);if(q.bp&&p.cool<=0&&!p.stun){p.cool=.6;for(const o of c.players)if(o!==p&&o.alive&&dist(p,o)<1.8){const v=toward(p,o.x,o.z);o.vx=v.x*(p.y>0?8:6);o.vz=v.z*(p.y>0?8:6);o.stun=.3;}}if(Math.abs(p.x)>edge||Math.abs(p.z)>edge)c.eliminate(p);}c.lastStanding();c.hint('이동/A 점프/B 펀치/공중 B 발차기 · 가장자리 타일이 두 번 가라앉습니다');},render(){const n=Math.round(edge*2/1.5);for(let z=0;z<n;z++)for(let x=0;x<n;x++)c.draw('tile'+x+'_'+z,'box',{x:(x-(n-1)/2)*1.5,y:-.2,z:(z-(n-1)/2)*1.5,sx:1.46,sy:.4,sz:1.46,color:(x+z)%2?'#b0c5ac':'#c7d2b9'});},timeout(){c.survivors('30초 동안 발판에서 생존');}};
}
export const games={'Snake Block Party':snake,'Cheep Cheep Leap':cheep,'Peepa Panic':peepa,'Balance Ball Brawl':balance,'Bob-omb Bogey':bogey,'Spiked Ball Scramble':spiked,'Bouncy Brawl':bouncy,'Cliffside Crisis':cliff,'Fruit of the Doom':fruit,'Beeline Shrine':beeline,'Blooper Blastoff':blastoff,'Paintball Battle':paintball,'Ice Slide, You Slide':ice,'Goomba Gallop':gallop,'Platform Push':platform};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['mp10']]));
const own='원작 중심 규칙을 새 플라밍고 3D로 재구성했습니다. 리모컨 동작은 방향키·버튼으로 바꾸고, 배치·속도·충돌 수치는 브라우저판에 맞춰 새로 설정했습니다. ';
export const notes={
'Snake Block Party':own+'움직이며 굽이치는 블록을 이동/A 점프로 건넙니다. 낙하마다 하트가 하나 줄고 3번이면 탈락합니다. 첫 결승 도착자 또는 마지막 생존자가 승리합니다.',
'Cheep Cheep Leap':own+'무적 상태에서 이동/A 점프로 물고기를 잡습니다. 일반 1점/큰 물고기 2점/금 물고기 3점, 30초 합계입니다. 선수끼리는 해를 끼치지 않습니다.',
'Peepa Panic':own+'이동으로 유령을 피해 출구로 갑니다. 잡히면 하트가 줄고 A 연타로 탈출해야 하며, 하트가 남아도 끌려가면 탈락합니다. 브라우저 탈출 입력은 2.2초 안에 6회입니다.',
'Balance Ball Brawl':own+'방향으로 관성 있는 공을 기울여 자기 구역의 스위치를 모두 누릅니다. 새 배치는 9개이며 2분 제한입니다.',
'Bob-omb Bogey':own+'A로 빠르게 골프 스윙합니다. 공마다 반응 순서 50·30·20·10점, 폭탄은 50점 감점입니다. 폭탄은 공 10개에 포함하지 않습니다.',
'Spiked Ball Scramble':own+'방향 이동만으로 좁은 길과 문 뒤의 두 갈래를 고르고 흔들리는 가시추를 피합니다. 낙하나 접촉은 탈락, 마지막 생존자 또는 출구 도달자가 승리합니다. 새 코스는 여섯 갈림길입니다.',
'Bouncy Brawl':own+'이동/A 연타로 회전하며 상대를 밀어냅니다. 회전 속도가 높을수록 강하지만 과열하면 4초 어지럽습니다. 30초 생존자는 승리합니다.',
'Cliffside Crisis':own+'위쪽 다섯 벽은 선수를 밀고 아래 다섯 발판은 뒤로 빠집니다. 이동/A 점프로 안전한 칸을 찾고 30초 또는 마지막까지 버팁니다. 동시 최후 낙하는 함께 가장 오래 생존한 것으로 셉니다.',
'Fruit of the Doom':own+'흐르는 폭포에서 이동/A 점프로 과일을 모읍니다. 성게 접촉과 추락은 과일 3개 손실과 지연을 줍니다. 30초 합계입니다.',
'Beeline Shrine':own+'원·줄·격자로 오는 벌 떼를 이동/A 점프로 피합니다. 하트 3개를 잃으면 탈락하며 마지막 생존자 또는 30초 후 하트 최다가 승리합니다.',
'Blooper Blastoff':own+'좌우 각도/A 반복 추진으로 잠수정을 수면까지 올립니다. 어뢰 피격 시 1초 정지하며 파이프 물살이 옆으로 밉니다. 2분 제한입니다.',
'Paintball Battle':own+'이동/A 사격으로 세 하트를 겨룹니다. 무작위 높이의 발판, 다른 높이의 탄, 탄끼리의 상쇄를 구현했습니다. 마지막 생존자 또는 30초 하트 최다 승리입니다.',
'Ice Slide, You Slide':own+'자동으로 미끄러지며 A로 눈덩이를 넘고 B로 높은 장애물 아래를 지납니다. 마지막 직선에서 A 연타로 가속합니다. 장애물 12개의 새 코스입니다.',
'Goomba Gallop':own+'직선·지그재그·곡선으로 지나가는 세 새 무리 중 가장 많은 종류를 고릅니다. 2라운드, 답변 10초, 정답 순서 5·3·2·1점입니다. 무리 수·출현 경로는 새로 생성합니다.',
'Platform Push':own+'이동/A 점프/B 펀치/공중 B 발차기로 상대를 밀어냅니다. 두 번 외곽 타일이 사라지고 30초 생존자는 승리합니다. 첫 축소 5초는 원작, 미확인 두 번째 시점은 브라우저판 18초입니다.'};
