import{clamp,dist,toward}from'../core.js';
const PINK='#ed91aa',BLUE='#76b9da',GOLD='#ebc362',GREEN='#8abf97';
const box=(c,id,x,y,z,sx,sy,sz,color,more={})=>c.draw(id,'box',{x,y,z,sx,sy,sz,color,...more});
const ball=(c,id,x,y,z,s,color,more={})=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color,...more});
const text=(c,id,label,x=0,y=1,z=0,size=3,color='#294652')=>{const value=String(label),short=[...value.trim()].length<=3;return c.draw(id,'text',{text:value,x,y,z,sx:size,sy:short?Math.max(size/4,Math.min(size*.75,1.2)):size/4,color});};
const diff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function four(c,limit=Infinity){c.limit=limit;c.activePlayers=[0,1,2,3];return c.players;}
function solo(c){c.limit=60;c.activePlayers=[0];c.players.forEach((p,i)=>{p.alive=i===0;p.visible=i===0;});return c.players[0];}
function record(c,p){c.complete([0],`60초 기록 ${p.score}동전`);c.result.outcome='record';}
function high(c,reason){const top=Math.max(...c.players.map(p=>p.score)),w=c.players.filter(p=>p.score===top);c.complete(w.length===4?[]:w.map(p=>p.i),reason);}
function line(c,id,a,b,color,width=.1,y=.1){const d=dist(a,b);box(c,id,(a.x+b.x)/2,y,(a.z+b.z)/2,d,.08,width,color,{ry:-Math.atan2(b.z-a.z,b.x-a.x)});}

function kingBoo(c){
 const players=four(c,300),platforms=Array.from({length:6},(_,j)=>({x:j%2?1.35:-1.35,z:7-j*3.3,r:1.85,angle:0,dir:j%2?-1:1})),state=players.map(()=>({carry:0,index:0,on:null,inv:0,returning:false}));let hp=30;players.forEach((p,i)=>{p.x=(i-1.5)*1.7;p.z=11;p.y=0;});c.view={size:35,eye:[0,30,30],target:[0,0,-1]};
 const ghost=(j)=>({x:Math.sin(c.time*(hp<=15?1.6:1)+j)*2.8,z:platforms[j===0?2:4].z});
 function reset(p,s,penalty){if(penalty)c.points(p,-1);s.carry=0;s.index=0;s.on=null;s.returning=false;s.inv=1;p.x=(p.i-1.5)*1.7;p.z=11;p.y=0;p.vy=0;}
 return{update(dt){c.hint(`유령왕 체력 ${hp}/30 · 방향 이동 · A 점프/빛 상자 잡기. 회전 발판 여섯 개를 건너 배달 후 초록 파이프로 돌아오세요.`);platforms.forEach(q=>q.angle+=q.dir*dt*(hp<=15?1.45:.65));players.forEach((p,i)=>{const s=state[i];s.inv=Math.max(0,s.inv-dt);if(s.on!==null&&p.y===0){const q=platforms[s.on],a=q.dir*dt*(hp<=15?1.45:.65),x=p.x-q.x,z=p.z-q.z;p.x=q.x+x*Math.cos(a)-z*Math.sin(a);p.z=q.z+x*Math.sin(a)+z*Math.cos(a);}let target;if(s.returning)target={x:3,z:-12};else if(!s.carry)target={x:hp<=15&&i%2===0?-2:2,z:11};else target=s.index<6?platforms[s.index]:{x:0,z:-13};const input=c.input(p,()=>{if(s.carry&&s.index<6&&dist(p,platforms[s.index])<.8&&p.y===0)s.index++;const q=s.carry&&s.index<6?platforms[s.index]:target,on=platforms.find(q=>dist(p,q)<q.r),edge=s.carry&&p.y===0&&(!on||dist(p,on)>1.1),danger=[ghost(0),ghost(1)].some(g=>dist(p,g)<2);return{...toward(p,q.x,q.z),a:!s.carry&&!s.returning&&dist(p,target)<.8||edge||danger&&p.y===0};});if(input.ap&&!s.carry&&!s.returning&&p.z>9.6&&Math.abs(p.x-(hp<=15&&p.x<0?-2:2))<1.3)s.carry=hp<=15&&p.x<0?3:1;c.move(p,input,s.carry===3?3.4:4.8,false);c.jump(p,input,8);const on=platforms.findIndex(q=>dist(p,q)<q.r);s.on=p.y===0&&on>=0?on:null;const ground=p.z>=9.3&&p.z<=13&&Math.abs(p.x)<5||p.z<=-11&&p.z>=-15&&Math.abs(p.x)<5||on>=0;if(p.y===0&&!ground)reset(p,s,false);if(!s.inv&&p.y<1.3&&[ghost(0),ghost(1)].some(g=>dist(p,g)<.9))reset(p,s,true);if(s.carry&&p.z<-11.5&&Math.abs(p.x)<2){const damage=s.carry;hp=Math.max(0,hp-damage);c.points(p,damage);s.carry=0;s.returning=true;if(hp===0){c.points(p,3);high(c,'유령왕 격파 · 마지막 공격 보너스 3점');}}if(s.returning&&dist(p,{x:3,z:-12})<.9)reset(p,s,false);});
 },render(){box(c,'boo-start',0,-.2,11,10,.4,4,'#8db49c');box(c,'boo-goal',0,-.2,-13,10,.4,4,'#8db49c');platforms.forEach((q,j)=>{c.draw(`boo-platform-${j}`,'cylinder',{x:q.x,y:-.2,z:q.z,sx:q.r*2,sy:.4,sz:q.r*2,color:j%2?PINK:BLUE});box(c,`platform-spoke-${j}`,q.x,.03,q.z,q.r*2,.06,.2,GOLD,{ry:-q.angle});});for(let j=0;j<2;j++){const g=ghost(j);ball(c,`boo-peepa-${j}`,g.x,.7,g.z,1.2,'#e8e9da');}box(c,'regular-light',2,.5,11,1,1,1,'#ece7c4');if(hp<=15)box(c,'gold-light',-2,.7,11,1.3,1.4,1.3,GOLD);ball(c,'king-ghost',0,2,-15,4,'#e1e7db');text(c,'king-hp',`HP ${hp}`,0,4.5,-14,5);c.draw('return-pipe','cylinder',{x:3,y:.4,z:-12,sx:1.5,sy:.8,sz:1.5,color:GREEN});players.forEach((p,i)=>{if(state[i].carry)box(c,`light-box-${i}`,p.x,p.y+1.3,p.z,.75,.8,.75,state[i].carry===3?GOLD:'#efe8b9');});},timeout(){c.complete([],'5분 안에 유령왕을 쓰러뜨리지 못함');}};
}
function blooper(c){
 const players=four(c,300),state=players.map(()=>({done:false,offset:c.rand(-.12,.12),jump:0}));let progress=0,start=0,order=[],times=[],demoDuration=0,playStart=0,heard=new Set(),pattern=0;
 function begin(){order=c.shuffle([0,1,2,3]);const unit=progress>=10?.56:.85;times=[unit,unit*2,unit*3.5,unit*4.5];start=c.time;demoDuration=times.at(-1)+.65;playStart=start+demoDuration+.45;heard.clear();state.forEach(s=>s.done=false);pattern++;}begin();
 function score(p,points){c.points(p,points);if(points>0){progress+=points;if(progress>=20){c.points(p,3);high(c,'리듬 누적 20점 · 마지막 성공 보너스 3점');}}}
 return{update(dt){const demo=c.time<playStart;c.hint(`${progress}/20 리듬 · ${demo?'먼저 문어의 시범 박자를 보세요.':'내 색 공이 내려올 때 A로 받아치세요! 정확 2점·근접 1점·실수 -1점.'}${progress>=10?' 빠른 박자':''}`);times.forEach((t,j)=>{if(c.time>=start+t&&!heard.has(j)){heard.add(j);c.sound?.([330,392,440,523][j],.13);}});players.forEach((p,i)=>{const s=state[i],slot=order.indexOf(i),when=playStart+times[slot],input=c.input(p,()=>!demo&&!s.done&&Math.abs(c.time-when-s.offset)<.035?{a:true}:{});s.jump=Math.max(0,s.jump-dt);p.x=(slot-1.5)*4;p.z=3;p.y=Math.sin(s.jump/.45*Math.PI)*1.3;if(!demo&&!s.done){if(input.ap){s.done=true;s.jump=.45;const error=Math.abs(c.time-when);score(p,error<.10?2:error<.23?1:-1);c.sound?.(error<.23?620:130,.05);}else if(c.time>when+.23){s.done=true;score(p,-1);}}});if(!c.ended&&c.time>playStart+times.at(-1)+.7)begin();
 },render(){box(c,'bayside',0,-.3,0,23,.4,14,BLUE);ball(c,'conductor-blooper',0,1.8,-6,4,'#ebe8d9');for(let j=0;j<4;j++){const when=c.time<playStart?start+times[j]:playStart+times[j],before=when-c.time,h=before>0&&before<1.4?before*2:.2,x=(j-1.5)*4;ball(c,`rhythm-ball-${j}`,x,.6+h,3,.65,players[order[j]].color);box(c,`rhythm-card-${j}`,x,.05,-1,3.3,.15,1.7,'#e8dfc7');text(c,`rhythm-note-${j}`,'♪',x,1,-1,2,players[order[j]].color);}text(c,'rhythm-phase',c.time<playStart?'시범':'따라 하기',0,5,-4,6);},timeout(){c.complete([],'5분 안에 리듬 누적 목표를 채우지 못함');}};
}

function tiles(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),N=6,grid=[],icons=['●','▲','☾','✿','✹','♦','⬟'],colors=[PINK,GREEN,BLUE,'#e69564','#56616f',PINK,'#7f72a4'];let cx=2,cz=2,repeat=0,busy=0,plan=null;
 const randomTile=()=>{const r=c.rng();return level>=2&&r< (level===3?.18:.09)?5:r>.93?4:c.int(0,level===3?4:3)===4?6:c.int(0,3);};
 for(let z=0;z<N;z++)for(let x=0;x<N;x++){let v=randomTile();while(x>1&&grid[z*N+x-1]===v&&grid[z*N+x-2]===v||z>1&&grid[(z-1)*N+x]===v&&grid[(z-2)*N+x]===v)v=randomTile();grid.push(v);}
 function matches(a){const out=new Set();for(let z=0;z<N;z++)for(let x=0;x<N;x++){const v=a[z*N+x];if(x<4&&a[z*N+x+1]===v&&a[z*N+x+2]===v){let k=x;while(k<N&&a[z*N+k]===v)out.add(z*N+k++);}if(z<4&&a[(z+1)*N+x]===v&&a[(z+2)*N+x]===v){let k=z;while(k<N&&a[k*N+x]===v)out.add(k++*N+x);}}return out;}
 function rotate(a,x,z,dir){const ids=[z*N+x,z*N+x+1,(z+1)*N+x+1,(z+1)*N+x],values=ids.map(j=>a[j]);ids.forEach((j,k)=>a[j]=values[(k+(dir>0?3:1))%4]);}
 function clear(){const m=matches(grid);if(!m.size)return false;for(const j of [...m])if(grid[j]===4){const x=j%N,z=Math.floor(j/N);for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++)if(x+dx>=0&&x+dx<N&&z+dz>=0&&z+dz<N)m.add((z+dz)*N+x+dx);}m.forEach(j=>c.points(p,grid[j]===5?3:1));for(let x=0;x<N;x++){const kept=[];for(let z=N-1;z>=0;z--)if(!m.has(z*N+x))kept.push(grid[z*N+x]);for(let z=N-1;z>=0;z--)grid[z*N+x]=kept[N-1-z]??randomTile();}c.sound?.(620,.05);return true;}
 p.x=-6;p.z=5;c.view={size:23,eye:[0,25,20],target:[0,0,0]};
 return{update(dt){c.hint(`레벨 ${level} · 방향키로 2×2 묶음 선택 · A 오른쪽 회전 · B 왼쪽 회전. 셋 이상 이어 지우고 폭탄의 주변 폭발도 이용하세요.`);const input=c.input(p,()=>{if(busy>0)return{};if(!plan){let best=-1;const options=[];for(let z=0;z<5;z++)for(let x=0;x<5;x++)for(const dir of[-1,1]){const a=[...grid];rotate(a,x,z,dir);const n=matches(a).size;if(n>best){best=n;options.length=0;}if(n===best)options.push({x,z,dir});}plan=c.pick(options);}if(cx!==plan.x)return{x:Math.sign(plan.x-cx)};if(cz!==plan.z)return{z:Math.sign(plan.z-cz)};return plan.dir>0?{a:true}:{b:true};});repeat-=dt;busy=Math.max(0,busy-dt);if(busy===0){if((input.x||input.z)&&repeat<=0){cx=clamp(cx+Math.sign(input.x),0,4);cz=clamp(cz+Math.sign(input.z),0,4);repeat=.12;}if(input.ap||input.bp){rotate(grid,cx,cz,input.ap?1:-1);clear();busy=.28;plan=null;}else if(clear())busy=.25;}
 },render(){for(let z=0;z<N;z++)for(let x=0;x<N;x++){const value=grid[z*N+x],wx=(x-2.5)*1.45,wz=(z-2.5)*1.4;box(c,`coin-tile-${x}-${z}`,wx,.1,wz,1.32,.22,1.28,colors[value]);text(c,`tile-icon-${x}-${z}`,icons[value],wx,.5,wz,1.05,'#f1ead8');}const x=(cx-2)*1.45,z=(cz-2)*1.4;box(c,'selector-top',x,.3,z-1.4,2.9,.1,.09,GOLD);box(c,'selector-bottom',x,.3,z+1.4,2.9,.1,.09,GOLD);box(c,'selector-left',x-1.45,.3,z,.09,.1,2.8,GOLD);box(c,'selector-right',x+1.45,.3,z,.09,.1,2.8,GOLD);},timeout(){record(c,p);}};
}
function rolling(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),foes=[];let id=0,next=0,charge=0,held=false,dash=0,respawn=0,lastDir={x:1,z:0};p.x=0;p.z=0;p.y=.8;
 function spawn(){const a=c.rand(0,Math.PI*2),big=c.rng()<.22,red=level>1&&c.rng()<(level===3?.3:.15);foes.push({id:id++,x:Math.cos(a)*6,z:Math.sin(a)*6,vx:0,vz:0,r:big?1.1:.65,mass:big?2.4:1,value:red?3:big?5:1,red,live:true});}for(let j=0;j<6;j++)spawn();
 return{update(dt){c.hint(`레벨 ${level} · 방향 이동 · A를 눌러 모았다 놓으면 돌진. 작은 공 1·큰 공 5·빨간 동전 공 3동전. 떨어지면 다시 올라옵니다.`);if(c.time>=next&&foes.filter(f=>f.live).length<12){spawn();next=c.time+1.7;}const q=foes.filter(f=>f.live).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>q?{...toward(p,q.x,q.z),a:charge<.7&&dash===0}:{});if(Math.hypot(input.x,input.z)>.1)lastDir=toward({x:0,z:0},input.x,input.z);if(input.a)charge=Math.min(1.5,charge+dt);if(held&&!input.a&&charge>0){p.vx+=lastDir.x*(5+charge*7);p.vz+=lastDir.z*(5+charge*7);dash=.4;charge=0;}held=input.a;dash=Math.max(0,dash-dt);respawn=Math.max(0,respawn-dt);if(!respawn){p.visible=true;p.vx=(p.vx+input.x*dt*5)*Math.pow(.985,dt*60);p.vz=(p.vz+input.z*dt*5)*Math.pow(.985,dt*60);p.x+=p.vx*dt;p.z+=p.vz*dt;if(Math.hypot(p.x,p.z)>8){respawn=1;p.visible=false;p.x=p.z=p.vx=p.vz=0;}}foes.filter(f=>f.live).forEach(f=>{const v=toward(f,p.x,p.z);f.vx=(f.vx+v.x*dt*.6)*Math.pow(.99,dt*60);f.vz=(f.vz+v.z*dt*.6)*Math.pow(.99,dt*60);f.x+=f.vx*dt;f.z+=f.vz*dt;const d=dist(p,f),r=.8+f.r;if(!respawn&&d<r&&d>.01){const n=toward(p,f.x,f.z),relative=(p.vx-f.vx)*n.x+(p.vz-f.vz)*n.z,impulse=Math.max(0,relative)*1.3+(dash?8:1);f.vx+=n.x*impulse/f.mass;f.vz+=n.z*impulse/f.mass;p.vx-=n.x*impulse*.5;p.vz-=n.z*impulse*.5;f.x+=n.x*(r-d)*.65;f.z+=n.z*(r-d)*.65;}if(Math.hypot(f.x,f.z)>8){f.live=false;c.points(p,f.value);}});
 },render(){c.draw('rumble-ring','cylinder',{x:0,y:-.25,z:0,sx:16,sy:.5,sz:16,color:'#9bc5a8'});if(!respawn)ball(c,'rider-ball',p.x,.4,p.z,1.6,p.color);foes.filter(f=>f.live).forEach(f=>{ball(c,`enemy-ball-${f.id}`,f.x,f.r,f.z,f.r*2,f.red?PINK:BLUE);ball(c,`enemy-rider-${f.id}`,f.x,f.r*2+.3,f.z,.6,'#e0c292');});text(c,'charge-label',`힘 ${Math.round(charge/1.5*100)}%`,0,1,8,4);},timeout(){record(c,p);}};
}
function goldRush(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),trains=[],shots=[];let id=0,bid=0,cool=0,next=0;p.x=0;p.z=6;
 function spawn(){const row=c.int(0,2),bomb=c.rng()<.5,chain={id:id++,phase:c.rand(0,6),z:-4+row*2,members:Array.from({length:8},(_,j)=>({j,live:true,type:j===0&&bomb?'bomb':level>1&&c.rng()<(level===3?.3:.13)?'red':'goomba'}))};trains.push(chain);}for(let j=0;j<3;j++)spawn();
 const pos=(t,m)=>({x:((c.time*(level===3?3:2)+t.phase-m.j*.8)%26+26)%26-13,z:t.z});
 return{update(dt){c.hint(`레벨 ${level} · ← → 대포 이동 · A 발사. 폭탄 선두를 맞히면 뒤 행렬과 근처 적도 연쇄 폭발합니다. 빨간 동전은 3개 가치.`);if(c.time>=next&&trains.filter(t=>t.members.some(m=>m.live)).length<5){spawn();next=c.time+2;}const targets=trains.flatMap(t=>t.members.filter(m=>m.live).map(m=>({t,m,...pos(t,m)}))).filter(q=>Math.abs(q.x)<8),q=targets.sort((a,b)=>(a.m.type==='bomb'?-5:0)+Math.abs(a.x-p.x)-((b.m.type==='bomb'?-5:0)+Math.abs(b.x-p.x)))[0],input=c.input(p,()=>q?{x:clamp((q.x+(6-q.z)/16*(level===3?3:2)-p.x)*4,-1,1),a:cool<=0&&Math.abs(q.x+(6-q.z)/16*(level===3?3:2)-p.x)<.5}:{});p.x=clamp(p.x+input.x*dt*6,-8,8);cool-=dt;if(input.ap&&cool<=0){cool=.18;shots.push({id:bid++,x:p.x,z:5,live:true});}shots.forEach(b=>{if(!b.live)return;b.z-=16*dt;const hit=targets.find(q=>q.m.live&&dist(b,q)<.55);if(hit){b.live=false;const victims=hit.m.type==='bomb'?targets.filter(q=>q.t===hit.t&&q.m.j>=hit.m.j||dist(q,hit)<2):[hit];victims.forEach(q=>{if(q.m.live){q.m.live=false;c.points(p,q.m.type==='red'?3:1);}});if(hit.m.type==='bomb')c.sound?.(110,.08);}if(b.z<-7)b.live=false;});
 },render(){c.arena({width:19,depth:15,color:'#c8bd9d'});box(c,'gold-cannon',p.x,.4,6,1.5,.8,1.3,p.color);trains.forEach(t=>t.members.filter(m=>m.live).forEach(m=>{const q=pos(t,m);if(Math.abs(q.x)<10)ball(c,`gold-target-${t.id}-${m.j}`,q.x,.45,q.z,.85,m.type==='bomb'?'#4b5260':m.type==='red'?PINK:'#b39570');}));shots.filter(b=>b.live).forEach(b=>ball(c,`gold-shot-${b.id}`,b.x,.5,b.z,.3,GOLD));},timeout(){record(c,p);}};
}

function leafboard(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),coins=[],obstacles=[],barrels=[];let d=0,next=0,id=0,stun=0,inv=0,flight=null,barrelNext=80;p.x=0;p.z=4;p.y=.25;
 return{update(dt){c.hint(`레벨 ${level} · 방향 이동 · A 점프. 꽃과 애벌레를 피하며 노랑 1·빨강 3동전을 모으세요. 세 통 중 하나를 타면 공중 동전 길로 날아갑니다.`);if(c.time>=next){const x=c.pick([-4,0,4]);for(let j=0;j<5;j++)coins.push({id:id++,x,z:d+20+j*1.3,y:.5,red:level>1&&c.rng()<(level===3?.4:.2),live:true});obstacles.push({id:id++,x:c.pick([-4,0,4]),z:d+26,w:c.rng()<.5,phase:c.rand(0,6)});next=c.time+2;}if(d+20>barrelNext){for(let k=0;k<3;k++)barrels.push({id:id++,x:(k-1)*4,z:barrelNext,route:k,used:false});barrelNext+=120;}const target=coins.filter(q=>q.live&&q.z>d&&q.z<d+12&&q.y<2).sort((a,b)=>a.z-b.z)[0],near=obstacles.find(q=>q.z>d&&q.z-d<5&&Math.abs(q.x-p.x)<1.4),input=c.input(p,()=>({x:target?clamp((target.x-p.x)*2,-1,1):0,a:!!near&&near.z-d<2.6&&p.y<.3}));stun=Math.max(0,stun-dt);inv=Math.max(0,inv-dt);if(flight){flight.t+=dt;d=flight.start+flight.t*12;p.x=flight.x;p.y=.25+Math.sin(Math.min(1,flight.t/2)*Math.PI)*7;if(flight.t>=2){flight=null;p.y=.25;p.vy=0;}}else{if(!stun){p.x=clamp(p.x+input.x*dt*5,-6,6);d+=dt*8;if(input.ap&&p.y<=.25){p.vy=8;p.y=.251;}}if(p.y>.25){p.vy=(p.vy||0)-18*dt;p.y=Math.max(.25,p.y+p.vy*dt);}const barrel=barrels.find(b=>!b.used&&Math.abs(b.z-d)<1&&Math.abs(b.x-p.x)<1.2);if(barrel){barrels.filter(b=>b.z===barrel.z).forEach(b=>b.used=true);flight={t:0,start:d,x:barrel.x};const count=[5,9,7][barrel.route];for(let j=0;j<count;j++){const t=.2+j*1.6/(count-1);coins.push({id:id++,x:barrel.x,z:d+t*12,y:.25+Math.sin(t/2*Math.PI)*7,red:level>1&&j%3===0,live:true});}}}coins.forEach(q=>{if(q.live&&Math.abs(q.z-d)<.7&&Math.abs(q.x-p.x)<.8&&Math.abs(q.y-p.y)<1){q.live=false;c.points(p,q.red?3:1);}});obstacles.forEach(q=>{const x=q.x+(q.w?Math.sin(c.time*(level>1?2:1)+q.phase)*1.4:0);if(!inv&&!flight&&Math.abs(q.z-d)<.8&&Math.abs(x-p.x)<1.1&&p.y<1.3){stun=.8;inv=1.6;}});
 },render(){box(c,'leaf-track',0,-.3,-3,15,.5,32,'#b09c71');box(c,'leaf-board',p.x,p.y-.15,4,1.8,.15,1.1,GREEN);coins.forEach(q=>{const z=4+d-q.z;if(q.live&&z>-21&&z<10)ball(c,`leaf-coin-${q.id}`,q.x,q.y,z,.4,q.red?PINK:GOLD);});obstacles.forEach(q=>{const z=4+d-q.z;if(z>-21&&z<10){const x=q.x+(q.w?Math.sin(c.time*(level>1?2:1)+q.phase)*1.4:0);if(q.w)for(let j=-1;j<=1;j++)ball(c,`leaf-wiggler-${q.id}-${j}`,x+j*.4,.45,z,.7,GOLD);else c.draw(`thorn-${q.id}`,'cone',{x,y:.6,z,sx:1.3,sy:1.3,sz:1.3,color:PINK});}});barrels.forEach(b=>{const z=4+d-b.z;if(!b.used&&z>-21&&z<10)c.draw(`barrel-${b.id}`,'cylinder',{x:b.x,y:.5,z,sx:1.7,sy:1,sz:1.7,color:'#8d7055'});});},timeout(){record(c,p);}};
}
function toadShop(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),items=['🍄','🌿','🌰','✿','❄'],supplies=items.map((name,j)=>({x:(j-2)*3,z:-4,name,j})),customers=[],tray=[];let cool=0;
 function order(i){const double=c.time>10&&c.rng()<(level===3?.75:level===2?.45:.12);return{x:(i-1)*5,z:4,needs:Array.from({length:double?2:1},()=>c.int(0,4)),red:level>1&&c.rng()<(level===3?.4:.2),born:c.time,base:double?5:3};}for(let i=0;i<3;i++)customers.push(order(i));p.x=0;p.z=0;c.bounds={x:8,z:5.5};
 return{update(dt){c.hint(`레벨 ${level} · 방향 이동 · A 물건 집기/배달 · B 쟁반 비우기. 최대 세 개를 들고 요청한 물건을 가져가세요. 오래 기다리면 대금이 줄어듭니다.`);const targetCustomer=customers.slice().sort((a,b)=>a.born-b.born)[0],have=tray.some(t=>targetCustomer.needs.includes(t)),need=targetCustomer.needs.find(t=>!tray.includes(t))??targetCustomer.needs[0],target=have||tray.length===3?targetCustomer:supplies[need],input=c.input(p,()=>({...toward(p,target.x,target.z),a:dist(p,target)<1.1&&cool<=0,b:tray.length===3&&!have}));cool-=dt;c.move(p,input,5.2);if(input.bp)tray.length=0;if(input.ap&&cool<=0){cool=.2;const supply=supplies.find(q=>dist(p,q)<1.2);if(supply&&tray.length<3)tray.push(supply.j);else{const index=customers.findIndex(q=>dist(p,q)<1.3);if(index>=0){const q=customers[index];for(let j=tray.length-1;j>=0;j--){const k=q.needs.indexOf(tray[j]);if(k>=0){q.needs.splice(k,1);tray.splice(j,1);}}if(!q.needs.length){const pay=Math.max(1,q.base-Math.floor((c.time-q.born)/5));c.points(p,pay*(q.red?3:1));customers[index]=order(index);}}}}
 },render(){c.arena({width:18,depth:14,color:'#c9c5a5'});supplies.forEach(q=>{box(c,`supply-${q.j}`,q.x,.5,q.z,2.3,1,1.5,[PINK,GREEN,GOLD,PINK,BLUE][q.j]);text(c,`supply-icon-${q.j}`,q.name,q.x,1.5,q.z,1.8);});customers.forEach((q,j)=>{ball(c,`customer-${j}`,q.x,.5,q.z,1,BLUE);text(c,`order-${j}`,q.needs.map(t=>items[t]).join(' '),q.x,2,q.z,3);text(c,`payment-${j}`,`${Math.max(1,q.base-Math.floor((c.time-q.born)/5))}${q.red?' 빨강':' 동전'}`,q.x,3,q.z,3,q.red?PINK:GOLD);});box(c,'tray',p.x,1.1,p.z-.6,1.5,.12,1,p.color);tray.forEach((t,j)=>text(c,`tray-item-${j}`,items[t],p.x+(j-1)*.5,1.7,p.z-.6,.75));},timeout(){record(c,p);}};
}
function cheepReach(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),fish=[];let id=0,next=0,cx=0,cz=0,charge=0,held=false,shot=null,stun=0,cool=0;p.x=0;p.z=7;
 function spawn(){const r=c.rng(),kind=r<.13?'urchin':r<.24?'gold':level>1&&r<(level===3?.6:.42)?'red':'fish',dir=c.rng()<.5?1:-1;fish.push({id:id++,x:dir>0?-10:10,z:c.rand(-4,4),vx:dir*(kind==='gold'?3:1.3),kind,live:true});}for(let j=0;j<14;j++){spawn();fish.at(-1).x=c.rand(-8,8);}
 return{update(dt){c.hint(`레벨 ${level} · 방향키 조준 · A를 눌러 손을 키우고 놓아 던지세요. 너무 오래 누르면 작아집니다. 일반 1·금 10·빨강 3, 성게는 피하세요.`);if(c.time>=next){spawn();next=c.time+.6;}fish.filter(f=>f.live).forEach(f=>{f.x+=f.vx*dt;if(Math.abs(f.x)>11)f.live=false;});const target=fish.filter(f=>f.live&&f.kind!=='urchin').sort((a,b)=>(b.kind==='gold'?10:1)-(a.kind==='gold'?10:1)||dist({x:cx,z:cz},a)-dist({x:cx,z:cz},b))[0],input=c.input(p,()=>target?{x:clamp((target.x+target.vx*.5-cx)*2,-1,1),z:clamp((target.z-cz)*2,-1,1),a:!shot&&!stun&&cool<=0&&charge<1.25}:{});stun=Math.max(0,stun-dt);cool=Math.max(0,cool-dt);if(!stun){cx=clamp(cx+input.x*dt*6,-8,8);cz=clamp(cz+input.z*dt*6,-4.7,4.7);if(input.a&&!shot&&cool===0)charge+=dt;if(held&&!input.a&&charge>0&&!shot){shot={x:cx,z:cz,r:.45+(charge%1.7)/1.7*2.1,t:0};charge=0;}}held=input.a;if(shot){shot.t+=dt;if(shot.t>=.5){const caught=fish.filter(f=>f.live&&dist(f,shot)<shot.r);if(caught.some(f=>f.kind==='urchin'))stun=1.2;else caught.forEach(f=>{f.live=false;c.points(p,f.kind==='gold'?10:f.kind==='red'?3:1);});shot=null;cool=.2;}}
 },render(){c.arena({width:21,depth:13,color:'#75b5c9'});fish.filter(f=>f.live).forEach(f=>{ball(c,`fish-${f.id}`,f.x,.35,f.z,f.kind==='gold'?1:.65,f.kind==='urchin'?'#72638c':f.kind==='gold'?GOLD:f.kind==='red'?PINK:'#ea9a8d');if(f.kind==='urchin')c.draw(`urchin-spike-${f.id}`,'cone',{x:f.x,y:.9,z:f.z,sx:.4,sy:.7,sz:.4,color:'#cecbd3'});});const r=.45+(charge%1.7)/1.7*2.1;c.draw('glove-max','ring',{x:cx,y:.06,z:cz,sx:5.1,sy:5.1,rx:-Math.PI/2,color:PINK});c.draw('glove-size','ring',{x:cx,y:.1,z:cz,sx:r*2,sy:r*2,rx:-Math.PI/2,color:'#f1ebda'});if(shot)ball(c,'thrown-glove',shot.x,3*(1-shot.t/.5)+.2,shot.z,shot.r*2,'#f1ebda',{sy:.3});},timeout(){record(c,p);}};
}

function samurai(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),enemies=[];let id=0,next=0,stun=0,cool=0,attack=0,high=false,facing=1;p.x=0;p.z=0;
 function spawn(){const kind=level>1&&c.rng()<(level===3?.5:.25)?'bill':c.rng()<.5?'swoop':'goombrat',left=c.rng()<.15;enemies.push({id:id++,x:p.x+(left?-9:10),high:kind==='swoop'||kind==='bill'&&c.rng()<.5,kind,vx:left?1.3:-1.5,live:true});}
 return{update(dt){c.hint(`레벨 ${level} · ← → 이동 · A 위쪽 공격 · B 아래쪽 공격. 박쥐 1·걸어오는 적 2·탄환 3동전. 오른쪽으로 전진하세요.`);stun=Math.max(0,stun-dt);cool-=dt;attack=Math.max(0,attack-dt);if(!stun&&c.time>=next){spawn();next=c.time+.85;}enemies.filter(e=>e.live).forEach(e=>e.x+=e.vx*dt);const target=enemies.filter(e=>e.live).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0],input=c.input(p,()=>target?{x:Math.abs(target.x-p.x)>1.55?Math.sign(target.x-p.x):0,a:target.high&&Math.abs(target.x-p.x)<2.1&&cool<=0,b:!target.high&&Math.abs(target.x-p.x)<2.1&&cool<=0}:{x:1});if(!stun){p.x+=input.x*dt*4.8;if(input.x)facing=Math.sign(input.x);if((input.ap||input.bp)&&cool<=0){cool=.24;attack=.17;high=input.ap;enemies.forEach(e=>{if(e.live&&e.high===high&&(e.x-p.x)*facing>-.25&&(e.x-p.x)*facing<2.3){e.live=false;c.points(p,e.kind==='bill'?3:e.kind==='goombrat'?2:1);}});}if(enemies.some(e=>e.live&&Math.abs(e.x-p.x)<.6)){stun=.8;enemies.forEach(e=>e.live=false);next=c.time+.9;}}c.view={size:24,eye:[p.x,8,26],target:[p.x,3,0]};p.rotation=facing>0?0:Math.PI;
 },render(){box(c,'samurai-ground',p.x,-.3,0,30,.5,4,'#bdac8a');enemies.filter(e=>e.live&&Math.abs(e.x-p.x)<15).forEach(e=>{ball(c,`samurai-enemy-${e.id}`,e.x,e.high?2.2:.55,0,e.kind==='bill'?.9:.75,e.kind==='swoop'?'#8371a2':e.kind==='bill'?'#53616e':'#b3936b');if(e.high)box(c,`enemy-wings-${e.id}`,e.x,2.2,0,1.6,.1,.4,PINK);});if(attack){box(c,'samurai-handle',p.x+facing*.8,high?2: .6,0,1.5,.13,.13,'#88725d');box(c,'samurai-hammer',p.x+facing*1.5,high?2:.6,0,.7,.7,.7,GOLD);}text(c,'go-right','→',p.x+8,3,0,4);},timeout(){record(c,p);}};
}
function pinball(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),shells=[],coins=[],foes=[],bumpers=[{x:-2.5,z:-3,r:1,cool:0},{x:2.5,z:-3,r:1,cool:0},{x:0,z:-6.5,r:.7,cool:0}],pipes=[false,false];let id=0,slots=[0,1,2],helper=null,helperNext=0,spawnNext=0,empty=0,left=0,right=0;p.visible=false;c.view={size:23,eye:[0,25,20],target:[0,0,-1]};
 function shell(x=4.5,z=5,vx=-2,vz=-9){shells.push({id:id++,x,z,vx,vz,live:true});}function coin(x,z,red=false){coins.push({id:id++,x,z,vx:c.rand(-2,2),vz:c.rand(-2,2),red,live:true});}function foe(kind,x,z){foes.push({id:id++,kind,x,z,phase:c.rand(0,6),live:true});}shell();for(let j=0;j<3;j++)foe('goomba',(j-1)*2,-.5);for(let j=0;j<(level===1?1:level===2?2:3);j++)foe('koopa',(j-1)*2,-4.7);if(level===3)foe('spiny',0,-2);
 function flipper(b,side,on){const pivot={x:side*3.4,z:5},end={x:side*.25,z:on?4:5.6},dx=end.x-pivot.x,dz=end.z-pivot.z,t=clamp(((b.x-pivot.x)*dx+(b.z-pivot.z)*dz)/(dx*dx+dz*dz),0,1),x=pivot.x+dx*t,z=pivot.z+dz*t;if(Math.hypot(b.x-x,b.z-z)<.46&&b.vz>0){b.z=z-.5;b.vz=-(on?9:4);b.vx=side<0?3.5:-3.5;}}
 return{update(dt){c.hint(`레벨 ${level} · A 왼쪽 플리퍼 · B 오른쪽 플리퍼. 등껍질로 범퍼를 쳐 동전을 꺼낸 뒤 실제로 주우세요. ? 범퍼의 슬롯이 맞으면 도우미 등장!`);const input=c.input(p,()=>({a:shells.some(b=>b.live&&b.z>3.7&&b.x<.6),b:shells.some(b=>b.live&&b.z>3.7&&b.x>-.6)}));left=input.a?1:0;right=input.b?1:0;bumpers.forEach(q=>q.cool=Math.max(0,q.cool-dt));if(c.time>=spawnNext){foe(c.rng()<.3?'koopa':'goomba',c.rand(-4,4),c.rand(-5,0));spawnNext=c.time+9;}if(helper&&c.time>helper.until)helper=null;if(helper&&c.time>=helperNext){helperNext=c.time+.8;if(helper.kind===0){const q=c.pick(bumpers.slice(0,2));for(let j=0;j<3;j++)coin(q.x,q.z,level>1&&c.rng()<.2);}else if(helper.kind===1)for(let j=0;j<4;j++)coin(c.rand(-4,4),c.rand(-6,1),level>1&&c.rng()<.2);}foes.filter(f=>f.live).forEach(f=>{if(f.kind!=='shy')f.x=clamp(f.x+Math.sin(c.time+f.phase)*dt*.35,-4.5,4.5);});coins.filter(q=>q.live).forEach(q=>{q.x=clamp(q.x+q.vx*dt,-5.6,5.6);q.z=clamp(q.z+q.vz*dt,-7,4.5);q.vx*=Math.pow(.96,dt*60);q.vz*=Math.pow(.96,dt*60);});const add=[];shells.filter(b=>b.live).forEach(b=>{b.vz+=dt*3.4;b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>5.7){b.x=clamp(b.x,-5.7,5.7);b.vx*=-.9;}if(b.z<-7.6){b.z=-7.6;b.vz=Math.abs(b.vz);}bumpers.forEach((q,j)=>{const d=dist(b,q);if(d<q.r+.25){const n=toward(q,b.x,b.z),dot=b.vx*n.x+b.vz*n.z;b.x=q.x+n.x*(q.r+.27);b.z=q.z+n.z*(q.r+.27);if(dot<0){b.vx-=2*dot*n.x;b.vz-=2*dot*n.z;}if(!q.cool){q.cool=.2;if(j===2){slots=[c.int(0,2),c.int(0,2),c.int(0,2)];if(slots.every(v=>v===slots[0])){helper={kind:slots[0],until:c.time+7};helperNext=c.time;if(helper.kind===2)foe('shy',0,-2);}}else for(let k=0;k<3;k++)coin(q.x+n.x*1.35,q.z+n.z*1.35,level>1&&c.rng()<(level===3?.3:.15));}}});flipper(b,-1,left);flipper(b,1,right);coins.filter(q=>q.live).forEach(q=>{if(dist(b,q)<.55){q.live=false;c.points(p,q.red?3:1);}});foes.filter(f=>f.live).forEach(f=>{if(dist(b,f)<.65){f.live=false;if(f.kind==='koopa')add.push({x:f.x,z:f.z,vx:c.rand(-4,4),vz:-6});else if(f.kind==='goomba')c.points(p);else for(let j=0;j<(f.kind==='shy'?2:3);j++)coin(f.x,f.z,true);b.vz*=-1;}});if(b.z>4.5&&Math.abs(b.x)>4.7){if(level===3){pipes[b.x>0?1:0]=true;b.vz=Math.max(b.vz,4);}else{b.x=Math.sign(b.x)*4.7;b.vx=-Math.sign(b.x)*Math.abs(b.vx);}}if(b.z>6.8){if(level===1){b.z=6.8;b.vz=-8;}else b.live=false;}const speed=Math.hypot(b.vx,b.vz);if(speed>12){b.vx*=12/speed;b.vz*=12/speed;}});add.forEach(q=>shell(q.x,q.z,q.vx,q.vz));if(!shells.some(b=>b.live)){empty+=dt;if(empty>.8){shell();empty=0;}}else empty=0;
 },render(){box(c,'pinball-board',0,-.3,-.5,13,.5,16,'#8fbab2');bumpers.forEach((q,j)=>{c.draw(`coin-bumper-${j}`,'cylinder',{x:q.x,y:.3,z:q.z,sx:q.r*2,sy:.6,sz:q.r*2,color:j===2?PINK:GOLD});if(j===2)text(c,'question-bumper','?',q.x,1,q.z,1.2);});for(const side of[-1,1]){const on=side<0?left:right;line(c,`flipper-${side}`,{x:side*3.4,z:5},{x:side*.25,z:on?4:5.6},'#eadcca',.55,.2);c.draw(`side-pipe-${side}`,'cylinder',{x:side*5.8,y:pipes[side>0?1:0]?-.2:.3,z:5.2,sx:1.4,sy:.6,sz:1.4,color:level===3?PINK:BLUE});}if(level===1)c.draw('gutter-pipe','cylinder',{x:0,y:.3,z:7,sx:2,sy:.6,sz:2,color:GREEN});slots.forEach((v,j)=>text(c,`slot-${j}`,['⚒','☁','●'][v],(j-1)*1.2,.5,2.4,1));shells.filter(b=>b.live).forEach(b=>ball(c,`pin-shell-${b.id}`,b.x,.35,b.z,.55,GREEN));coins.filter(q=>q.live).forEach(q=>ball(c,`pin-coin-${q.id}`,q.x,.2,q.z,.35,q.red?PINK:GOLD));foes.filter(f=>f.live).forEach(f=>ball(c,`pin-foe-${f.id}`,f.x,.55,f.z,.8,f.kind==='koopa'?GREEN:f.kind==='spiny'?PINK:f.kind==='shy'?BLUE:'#b89c78'));if(helper)text(c,'pin-helper',['망치 도우미','구름 도우미','빨간 동전 도우미'][helper.kind],0,1,-8,5);},timeout(){record(c,p);}};
}

function silverLining(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),clouds=[],coins=[];let id=0,vy=0,lastJump=false,treasure=null,nextChest=6,ground=true;
 for(let row=0;row<4;row++)for(let j=0;j<3;j++)clouds.push({x:(j-1)*5+(row%2?.7:-.7),y:row*2.7,w:3.6});
 const bases=clouds.flatMap((q,j)=>[-1,0,1].map((dx,k)=>({x:q.x+dx,y:q.y+.8,red:level>1&&(j*3+k)% (level===3?3:7)===0})));
 function refill(){bases.forEach(q=>coins.push({...q,id:id++,live:true,scattered:false}));}refill();p.x=-5.7;p.y=0;p.z=0;c.view={size:29,eye:[0,12,34],target:[0,5,0]};
 return{update(dt){c.hint(`레벨 ${level} · ← → 이동 · A 점프. 구름을 밟으면 튀어 오릅니다. 날아가는 상자를 아래서 치고 모든 동전을 모으면 같은 자리에 다시 생깁니다.`);const options=coins.filter(q=>q.live&&!q.scattered),target=options.slice().sort((a,b)=>Math.abs(a.y-p.y)*1.6+Math.abs(a.x-p.x)-(Math.abs(b.y-p.y)*1.6+Math.abs(b.x-p.x)))[0],input=c.input(p,()=>({x:target?clamp((target.x-p.x)*2,-1,1):0,a:ground&&!lastJump}));lastJump=input.a;p.x=clamp(p.x+input.x*dt*5.5,-8.6,8.6);const before=p.y;if(input.ap&&ground){vy=12;ground=false;}if(!ground){vy-=18*dt;p.y+=vy*dt;if(vy<0){const land=clouds.filter(q=>Math.abs(p.x-q.x)<q.w/2&&before>=q.y&&p.y<=q.y).sort((a,b)=>b.y-a.y)[0];if(land){p.y=land.y;vy=input.a?12:10.5;ground=false;}else if(p.y<=0){p.y=0;vy=0;ground=true;}}}else if(!clouds.some(q=>q.y===0&&Math.abs(p.x-q.x)<q.w/2)&&p.y>0)ground=false;
 if(!treasure&&c.time>=nextChest){treasure={x:-10,y:11.9,hit:false};nextChest=c.time+12;}if(treasure){treasure.x+=dt*2.2;if(!treasure.hit&&vy>0&&Math.abs(p.x-treasure.x)<1.1&&before+1.5<=treasure.y&&p.y+1.5>=treasure.y){treasure.hit=true;vy=-1;for(let j=0;j<12;j++)coins.push({id:id++,x:treasure.x,y:treasure.y,vx:c.rand(-4,4),vy:c.rand(1,4),red:level>1&&j%3===0,live:true,scattered:true});c.sound?.(750,.08);}if(treasure.x>11)treasure=null;}
 coins.forEach(q=>{if(!q.live)return;if(q.scattered){q.vy-=9*dt;q.x+=q.vx*dt;q.y+=q.vy*dt;if(Math.abs(q.x)>8.7){q.x=clamp(q.x,-8.7,8.7);q.vx*=-.7;}if(q.y<.3){q.y=.3;q.vy=Math.abs(q.vy)*.4;q.vx*=.8;}}if(Math.hypot(q.x-p.x,q.y-(p.y+.8))<.7){q.live=false;c.points(p,q.red?3:1);}});if(!coins.some(q=>q.live&&!q.scattered))refill();
 },render(){clouds.forEach((q,j)=>{box(c,`bounce-cloud-${j}`,q.x,q.y-.15,0,q.w,.3,2,'#e7e9df');for(let k=-1;k<=1;k++)ball(c,`cloud-puff-${j}-${k}`,q.x+k*.9,q.y-.2,.1,1.2,'#e7e9df',{sy:.5});});coins.filter(q=>q.live).forEach(q=>ball(c,`sky-coin-${q.id}`,q.x,q.y,0,.4,q.red?PINK:GOLD));if(treasure&&!treasure.hit){box(c,'flying-chest',treasure.x,treasure.y,0,1.7,1,1.2,'#ad845a');box(c,'chest-wing',treasure.x,treasure.y,0,3,.15,.4,'#e6e9dc');}},timeout(){record(c,p);}};
}
function conveyor(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),items=[];let id=0,next=0,direction=1,jam=0,flash=null;p.visible=false;c.view={size:27,eye:[0,27,25],target:[0,0,0]};
 const belt=(row,j)=>({x:(j-row/2)*6,z:-5+row*4});
 function spawn(){const red=level>1&&c.rng()<(level===3?.3:.12);items.push({id:id++,row:0,j:0,x:0,z:-5,kind:red?'red':c.rng()<.5?'gold':'mushroom',fall:null,live:true});}
 function drop(q,dir){const n=q.j+(dir>0?1:0),from={x:q.x,z:q.z},to=q.row<2?belt(q.row+1,n):{x:(n-1.5)*6,z:8};q.fall={t:0,from,to,index:n};}
 return{update(dt){c.hint(`레벨 ${level} · ← →로 모든 벨트 방향 변경 · A 가속. 분홍 버섯은 분홍 통 1동전, 금 버섯은 금 통 3동전. 잘못 넣으면 잠시 멈춥니다.`);const lowest=items.filter(q=>q.live&&!q.fall).sort((a,b)=>b.row-a.row||Math.abs(b.x-belt(b.row,b.j).x)-Math.abs(a.x-belt(a.row,a.j).x))[0],input=c.input(p,()=>{if(!lowest)return{a:true};const desired=lowest.kind==='gold'?1:0,dir=lowest.kind==='red'?direction:((lowest.j%2)===desired?-1:1);return{x:lowest.row===2?dir:direction,a:true};});if(input.x)direction=Math.sign(input.x);jam=Math.max(0,jam-dt);if(!jam&&c.time>=next){spawn();next=c.time+1.5;}if(flash&&c.time>flash.until)flash=null;if(!jam)items.filter(q=>q.live).forEach(q=>{if(q.fall){q.fall.t+=dt;const t=Math.min(1,q.fall.t/.45);q.x=q.fall.from.x+(q.fall.to.x-q.fall.from.x)*t;q.z=q.fall.from.z+(q.fall.to.z-q.fall.from.z)*t;if(t===1){if(q.row===2){const correct=q.kind==='red'||(q.kind==='gold'?1:0)===q.fall.index%2;if(correct)c.points(p,q.kind==='mushroom'?1:3);else jam=.9;flash={x:q.x,good:correct,until:c.time+.7};q.live=false;}else{q.row++;q.j=q.fall.index;}q.fall=null;}}else{q.x+=direction*dt*(input.a?7:3);const b=belt(q.row,q.j);if(Math.abs(q.x-b.x)>=2.45){q.x=b.x+direction*2.45;drop(q,direction);}}});
 },render(){for(let row=0;row<3;row++)for(let j=0;j<=row;j++){const q=belt(row,j);box(c,`sort-belt-${row}-${j}`,q.x,.1,q.z,5,.25,1.7,jam?'#786f77':'#8fa9b1');for(let k=-2;k<=2;k++)text(c,`belt-arrow-${row}-${j}-${k}`,direction>0?'›':'‹',q.x+k,.65,q.z,1.4,'#294652');}for(let j=0;j<4;j++){const x=(j-1.5)*6;box(c,`sorting-bin-${j}`,x,.3,8,4.8,.6,2.6,j%2?GOLD:PINK);text(c,`bin-value-${j}`,j%2?'황금 3':'일반 1',x,1.4,8,3.5);}items.filter(q=>q.live).forEach(q=>{const y=.8+(q.fall?Math.sin(q.fall.t/.45*Math.PI)*.7:0);ball(c,`sort-object-${q.id}`,q.x,y,q.z,.75,q.kind==='gold'?GOLD:PINK);if(q.kind!=='red')box(c,`mushroom-stem-${q.id}`,q.x,y-.4,q.z,.3,.5,.3,'#e6dccb');else text(c,`red-value-${q.id}`,'3',q.x,y+.7,q.z,.7);});if(flash)text(c,'sort-flash',flash.good?'✓':'멈춤',flash.x,2.6,7,3,flash.good?GREEN:PINK);},timeout(){record(c,p);}};
}
function stealDiver(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),objects=[];let id=0,next=0,angle=0,stun=0,inv=0;p.x=0;p.y=3;p.z=0;c.view={size:27,eye:[0,10,32],target:[0,4,0]};
 function toss(){const j=c.int(0,2),r=c.rng(),kind=r<.22?'spiny':level>1&&r<(level===3?.65:.4)?'red':'coin';objects.push({id:id++,x:(j-1)*5,y:9,vx:c.rand(-1.2,1.2),vy:-.9,kind,live:true,rest:0});}
 return{update(dt){c.hint(`레벨 ${level} · 방향키로 잠수정 방향을 정하고 A로 전진. 세 구름이 던지는 노랑 1·빨강 3동전을 받으세요. 가시는 기절시키고 바닥의 동전은 사라집니다.`);if(c.time>=next){toss();next=c.time+.35;}const danger=objects.filter(q=>q.live&&q.kind==='spiny'&&Math.hypot(q.x-p.x,q.y-p.y)<2).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],target=objects.filter(q=>q.live&&q.kind!=='spiny'&&q.y>.5&&Math.abs(q.x)<8).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)/(a.kind==='red'?1.8:1)-Math.hypot(b.x-p.x,b.y-p.y)/(b.kind==='red'?1.8:1))[0],input=c.input(p,()=>{const q=danger?{x:p.x+(p.x-danger.x)*2,y:p.y+(p.y-danger.y)*2}:target;if(!q)return{};const d=Math.hypot(q.x-p.x,q.y-p.y)||1;return{x:(q.x-p.x)/d,z:-(q.y-p.y)/d,a:true};});stun=Math.max(0,stun-dt);inv=Math.max(0,inv-dt);if(Math.hypot(input.x,input.z)>.1)angle=Math.atan2(-input.z,input.x);if(input.a&&!stun){p.x=clamp(p.x+Math.cos(angle)*dt*5,-8.5,8.5);p.y=clamp(p.y+Math.sin(angle)*dt*5,.65,8);}p.rotation=-angle;objects.forEach(q=>{if(!q.live)return;q.vy-=dt*.12;q.x+=q.vx*dt;q.y+=q.vy*dt;if(Math.abs(q.x)>9){q.x=clamp(q.x,-9,9);q.vx*=-.5;}const floor=Math.abs(q.x)<1.7?-3:.25;if(q.y<floor){q.y=floor;q.vy=0;q.vx*=Math.pow(.95,dt*60);q.rest+=dt;if(q.rest>2)q.live=false;}if(q.live&&Math.hypot(q.x-p.x,q.y-p.y)<.8){if(q.kind==='spiny'){if(!inv){stun=.8;inv=1.5;q.live=false;}}else{q.live=false;c.points(p,q.kind==='red'?3:1);}}});
 },render(){box(c,'diver-water',0,3,-1,20,16,.3,'#82b9c4');for(const side of[-1,1])box(c,`sea-floor-${side}`,side*5.8,-.6,0,8,1.2,3,'#c0b192');for(let j=0;j<3;j++){ball(c,`cloud-pilot-${j}`,(j-1)*5,10,0,1.5,'#e7e7d6');box(c,`cloud-platform-${j}`,(j-1)*5,9.3,0,2.8,.4,1.5,'#e7e7d6');}box(c,'submarine',p.x,p.y,0,1.8,.7,1.2,GOLD,{rz:angle});ball(c,'sub-window',p.x,p.y,.65,.55,BLUE);objects.filter(q=>q.live).forEach(q=>{ball(c,`diver-object-${q.id}`,q.x,q.y,0,q.kind==='spiny'?.7:.4,q.kind==='spiny'?'#835f76':q.kind==='red'?PINK:GOLD);if(q.kind==='spiny')c.draw(`diver-spike-${q.id}`,'cone',{x:q.x,y:q.y+.5,z:0,sx:.35,sy:.5,sz:.35,color:'#dfd5cc'});});},timeout(){record(c,p);}};
}
function houseBoos(c){
 const p=solo(c),level=clamp(Math.floor(c.meta.coinLevel||1),1,3),map=['#############','#.....#.....#','#.###.#.###.#','#.#.......#.#','#.#.##.##.#.#','#...#...#...#','###.......###','#...#...#...#','#.#.##.##.#.#','#.#.......#.#','#.###.#.###.#','#.....#.....#','#############'],step=1.4,cells=[],coins=[],ghosts=[],peepas=[];let facing={x:0,z:-1},inv=0,waypoint=null;
 const world=(x,z)=>({x:(x-6)*step,z:(z-6)*step}),at=(x,z)=>map[z]?.[x]&&map[z][x]!=='#';
 for(let z=0;z<13;z++)for(let x=0;x<13;x++)if(at(x,z)){const q={...world(x,z),col:x,row:z,id:cells.length};cells.push(q);if(x!==6||z!==6)coins.push({...q,red:level>1&&c.rng()<(level===3?.45:.18),live:true});}
 for(let j=0;j<level+1;j++)ghosts.push({...world(j%2?10:2,j<2?3:9),hidden:false});
 const paths=[[[1,1],[5,1],[5,3],[3,3],[3,5],[1,5]],[[7,11],[11,11],[11,7],[9,7],[9,9],[7,9]],[[7,1],[11,1],[11,5],[9,5],[9,3],[7,3]]];for(let j=0;j<level;j++)peepas.push({...world(...paths[j][0]),index:1,path:paths[j].map(q=>world(...q))});p.x=p.z=0;c.view={size:26,eye:[0,29,20],target:[0,0,0]};
 function valid(x,z){for(const dx of[-.28,.28])for(const dz of[-.28,.28])if(!at(Math.round((x+dx)/step+6),Math.round((z+dz)/step+6)))return false;return true;}
 function route(){const sx=Math.round(p.x/step+6),sz=Math.round(p.z/step+6),queue=[{x:sx,z:sz,path:[]}],seen=new Set([`${sx},${sz}`]);while(queue.length){const q=queue.shift(),coin=coins.find(v=>v.live&&v.col===q.x&&v.row===q.z);if(coin&&q.path.length)return q.path.map(v=>world(v.x,v.z));const ns=[[q.x-1,q.z],[q.x+1,q.z],[q.x,q.z-1],[q.x,q.z+1]].filter(([x,z])=>at(x,z)&&!seen.has(`${x},${z}`));ns.sort((a,b)=>{const wa=world(...a),wb=world(...b);return Math.min(...ghosts.map(g=>dist(g,wb)))-Math.min(...ghosts.map(g=>dist(g,wa)));});for(const [x,z]of ns){seen.add(`${x},${z}`);queue.push({x,z,path:[...q.path,{x,z}]});}}return[];}
 return{update(dt){c.hint(`레벨 ${level} · 방향 이동 · A 빠르게 달리기. 유령을 바라보면 멈춥니다. 등지면 벽을 뚫고 추격하며, 유령 접촉은 중앙 복귀입니다.`);const input=c.input(p,()=>{if(!waypoint||dist(p,waypoint)<.1)waypoint=route()[0];return waypoint?{...toward(p,waypoint.x,waypoint.z),a:true}:{};});inv=Math.max(0,inv-dt);if(Math.hypot(input.x,input.z)>.1)facing=toward({x:0,z:0},input.x,input.z);const speed=input.a?6.8:4.5,d=Math.max(1,Math.hypot(input.x,input.z)),nx=p.x+input.x/d*dt*speed,nz=p.z+input.z/d*dt*speed;if(valid(nx,p.z))p.x=nx;if(valid(p.x,nz))p.z=nz;p.rotation=Math.atan2(-facing.z,facing.x);coins.forEach(q=>{if(q.live&&dist(p,q)<.48){q.live=false;c.points(p,q.red?3:1);}});ghosts.forEach(g=>{const to=toward(p,g.x,g.z);g.hidden=to.x*facing.x+to.z*facing.z>.28;if(!g.hidden){const v=toward(g,p.x,p.z);g.x+=v.x*dt*(1.2+level*.25);g.z+=v.z*dt*(1.2+level*.25);}});peepas.forEach(g=>{const q=g.path[g.index],v=toward(g,q.x,q.z);g.x+=v.x*dt*1.7;g.z+=v.z*dt*1.7;if(dist(g,q)<.1)g.index=(g.index+1)%g.path.length;});if(!inv&&[...ghosts,...peepas].some(g=>dist(p,g)<.6)){p.x=p.z=0;inv=1.5;waypoint=null;c.sound?.(140,.08);}
 },render(){box(c,'haunted-floor',0,-.2,0,18,.4,18,'#6d8498');for(let z=0;z<13;z++)for(let x=0;x<13;x++)if(!at(x,z)){const q=world(x,z);box(c,`boo-wall-${x}-${z}`,q.x,.4,q.z,step,.8,step,'#526474');}coins.filter(q=>q.live).forEach(q=>ball(c,`maze-coin-${q.id}`,q.x,.35,q.z,.32,q.red?PINK:GOLD));ghosts.forEach((g,j)=>{ball(c,`maze-boo-${j}`,g.x,.7,g.z,1.1,g.hidden?'#aaa7bd':'#e7e4d6');text(c,`boo-face-${j}`,g.hidden?'× ×':'• •',g.x,1.5,g.z,.8);});peepas.forEach((g,j)=>ball(c,`maze-peepa-${j}`,g.x,.55,g.z,.9,PINK));line(c,'facing-ray',p,{x:p.x+facing.x,z:p.z+facing.z},GOLD,.12,.2);},timeout(){record(c,p);}};
}

export const games={
 "King Boo's Light Smite":kingBoo,"Mega Blooper's Bayside Bop":blooper,'Tiles and Tribulations':tiles,'Rolling Rumble':rolling,'Goomba Gold Rush':goldRush,'Leafboard Hoard':leafboard,'One-Stop Toad Shop':toadShop,'Cheep Cheep Reach':cheepReach,'Samurai Smackdown':samurai,'Pinball Brawl':pinball,'Silver Lining':silverLining,'Conveyor Meltdown':conveyor,'Steal Diver':stealDiver,'House of Boos':houseBoos
};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(n=>[n,['star-rush']]));
const coinNote=' 코인애슬론의 1인 60초 기록 경기입니다. 3분 독립 미니게임 모드는 사용하지 않습니다. meta.coinLevel 1~3(기본 1)으로 레벨을 고르며 다른 보드 참가자에게 쓰는 아이템 상자는 생략했습니다.';
export const notes={
 "King Boo's Light Smite":'방향 이동·A 점프/시작 지점의 빛 상자 집기. 회전 발판을 건너 보스에게 배달하고 파이프로 출발점 복귀. 큰 금 상자는 느리지만 3점, 일반 1점, 유령 접촉 -1점, 마지막 공격 +3점입니다. 절반 진행 후 회전이 빨라집니다. 실제 회전에 서 있는 사람도 함께 움직입니다. 보스 체력 30·여섯 발판의 지형·점프/이동·회전 수치는 재구성했습니다. 5분 미격파는 무승부.',
 "Mega Blooper's Bayside Bop":'시범 공의 박자를 기억한 뒤 내 색 공이 내려올 때 A. 정확 2점·근접 1점·잘못 누르거나 놓치면 -1점, 마지막 성공 +3점입니다. 10점부터 박자가 빨라지고 20점 공동 목표를 채우면 종료됩니다. 자체 생성 네 음 리듬·0.10/0.23초 판정 폭·양의 점수만 채우는 공동 게이지 처리는 재구성이며 원작 음원을 쓰지 않습니다. 5분 목표 미달은 무승부.',
 'Tiles and Tribulations':'방향키로 6×6 판의 2×2 묶음 선택, A 시계 방향·B 반시계 방향 회전. 가로/세로 3개 이상을 지우고 빈 칸으로 위쪽 타일이 떨어져 연쇄됩니다. 폭탄은 주변 여덟 칸도 제거합니다. 레벨 2부터 빨간 동전, 3에는 딱정벌레 타일이 추가됩니다. 일반 타일 1·빨강 3 환산과 출현 확률·0.28초 회전 간격은 재구성입니다.'+coinNote,
 'Rolling Rumble':'방향 이동·A 누른 채 힘 모으기·놓으면 돌진. 실제 공끼리 충돌해 작은 적 공을 밀어내면 1동전, 큰 공 5동전, 빨간 동전 공 3동전입니다. 플레이어가 떨어지면 복귀합니다. 구형 물리의 질량·충격량·링 반경·적 수·재등장 시간은 재구성했습니다.'+coinNote,
 'Goomba Gold Rush':'← → 대포 이동·A 발사. 행렬의 적에 실제 탄환을 맞히면 동전을 얻고 폭탄 선두를 맞히면 뒤 행렬과 주변 적이 함께 폭발합니다. 빨간 동전은 3개 가치입니다. 세 줄 행렬·8마리 묶음·출현 및 이동/탄속·폭발 반경은 재구성했습니다.'+coinNote,
 'Leafboard Hoard':'자동으로 나뭇잎 보드를 타고 전진합니다. ← → 이동·A 점프로 꽃과 애벌레를 피하고 동전을 모읍니다. 세 통 중 하나를 타면 서로 다른 공중 동전 길로 발사됩니다. 노랑 1·빨강 3. 직접 구성한 길·세 공중 경로 5/9/7개·장애물 배치·속도/기절/비행 수치는 재구성입니다.'+coinNote,
 'One-Stop Toad Shop':'방향 이동·A 물품 집기/손님에게 전달·B 쟁반 비우기. 최대 세 물건을 들고 손님이 요구한 한두 가지를 배달합니다. 오래 기다리면 지불액이 줄며 높은 레벨에서 빨간 동전 손님이 등장합니다. 진열 물품·가게 배치·기본 대금 3/5·5초마다 1 감소·최소 1·출현 확률은 원작 수치가 확인되지 않아 이 버전에서 정했습니다.'+coinNote,
 'Cheep Cheep Reach':'방향키 조준·A를 눌러 손을 키우고 놓아 던집니다. 오래 누르면 손이 다시 작아집니다. 실제 손 범위에 든 물고기를 잡으며 일반 1·금색 10·빨강 3, 성게를 잡으면 기절합니다. 금색 물고기는 더 크고 빠릅니다. 손 크기 주기 1.7초·투사 0.5초·성게와 함께 잡힌 물고기를 무효로 하는 처리·출현 확률은 재구성입니다.'+coinNote,
 'Samurai Smackdown':'← → 이동·A 위쪽 공격·B 아래쪽 공격. 다가오는 박쥐는 1동전, 걸어오는 적은 2, 높은 레벨의 탄환은 3동전입니다. 적의 높이와 바라보는 방향을 맞춰 실제 사거리 안에서 공격하며 접촉하면 잠시 기절합니다. 적 간격·공격 범위·기절 후 화면의 적을 비우는 처리·속도는 재구성했습니다.'+coinNote,
 'Pinball Brawl':'A 왼쪽·B 오른쪽 플리퍼(원작 L/왼쪽, R/B/A를 변환). 실제 등껍질이 범퍼를 쳐 동전을 꺼내고 다시 접촉해야 획득합니다. 거북을 치면 공 추가, 버섯 적은 동전. ? 범퍼 슬롯 일치 시 망치·구름·가면 도우미, 가면 2빨강·가시 적 3빨강. 레벨 1 배수구 차단, 2부터 배수구를 열고 3은 접촉 시 옆 파이프가 낮아집니다. 판 배치·탄성·범퍼당 3동전·슬롯 확률·7초 도우미·빈 판 공 복귀는 재구성입니다.'+coinNote,
 'Silver Lining':'← → 이동·A 점프. 구름에 실제로 착지하면 튀어 오릅니다. 노랑 1·빨강 3동전, 날아가는 상자를 아래에서 머리로 치면 동전이 흩어집니다. 기본 동전을 모두 주우면 정확히 같은 위치에 다시 생성됩니다. 구름 12개·36개 기본 동전·상자 주기와 산개 12개·중력/반발은 재구성했습니다.'+coinNote,
 'Conveyor Meltdown':'← →로 여섯 벨트 전체의 방향을 바꾸고 A로 가속. 1→2→3개 벨트를 타고 떨어진 버섯을 네 통에 분류합니다. 일반 버섯 1·금 버섯 3동전, 잘못 넣으면 일시 정지. 레벨 2/3의 빨간 동전은 어느 통이나 3동전입니다. 속도·1.5초 출현 간격·낙하 시간·0.9초 정지는 재구성했습니다.'+coinNote,
 'Steal Diver':'방향키로 잠수정의 진행 방향을 정하고 A를 눌러 추진합니다. 세 구름이 실제로 던지는 노랑 1·빨강 3동전을 받고 가시 알을 피합니다. 가시 접촉 시 기절하고 바닥이나 접근 못 하는 구덩이의 동전은 사라집니다. 수조/구덩이 배치·이동 및 침강 속도·출현 확률·바닥 잔류 2초·기절 시간은 재구성했습니다.'+coinNote,
 'House of Boos':'방향 이동·A 달리기. 미로의 동전 줄을 모으며 노랑 1·빨강 3동전입니다. 유령을 바라보면 멈추고 등지면 벽을 통과해 추격합니다. 별도의 분홍 유령은 고정 경로로 움직입니다. 유령과 닿으면 중앙으로 돌아가며 높은 레벨은 적과 빨간 동전이 늘어납니다. 새로운 13×13 미로·유령 수·시선 각도·속도·복귀 유예는 재구성했습니다.'+coinNote
};
