import { clamp, dist, toward } from '../core.js';
const PINK='#ed91aa',BLUE='#76b9da',GOLD='#ebc362',GREEN='#8abf97';
const box=(c,id,x,y,z,sx,sy,sz,color,more={})=>c.draw(id,'box',{x,y,z,sx,sy,sz,color,...more});
const ball=(c,id,x,y,z,s,color,more={})=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color,...more});
const text=(c,id,label,x=0,y=1,z=0,size=3,color='#294652')=>c.draw(id,'text',{text:label,x,y,z,sx:size,sy:size/4,color});
function active(c,n,limit=Infinity){c.limit=limit;c.activePlayers=Array.from({length:n},(_,i)=>i);c.players.forEach((p,i)=>{p.visible=p.alive=i<n;p.x=n===1?0:i===0?-5:5;p.z=0;});return c.players.slice(0,n);}
const win=(c,reason)=>c.complete([0],reason),lose=(c,reason)=>c.complete([],reason);
function side(c,x=0,y=5,size=25){c.view={size,eye:[x,y+4,28],target:[x,y,0]};}
const angleDifference=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function duelEnd(c,players,reason){const live=players.filter(p=>p.alive);if(live.length<2)c.complete(live.map(p=>p.i),reason);}

function koopaKrunch(c){
 const [p]=active(c,1);side(c,0,5,24);p.x=7;p.scale=.6;const W=6,H=10,grid=Array.from({length:H},()=>Array(W).fill(-1));let piece=null,count=0,nextMove=0,fall=0;
 const cells=q=>q.rot?[[q.x,q.y,q.a],[q.x+1,q.y,q.b]]:[[q.x,q.y,q.a],[q.x,q.y-1,q.b]];
 const fits=q=>cells(q).every(([x,y])=>x>=0&&x<W&&y<H&&(y<0||grid[y][x]<0));
 const spawn=()=>{count++;piece={x:2,y:0,rot:0,a:count%7===0?3:c.int(0,1),b:count%4===0?2:c.int(0,1)};if(!fits(piece))lose(c,'블록이 천장에 닿았습니다');};
 const settle=()=>{let changed=true;while(changed){changed=false;for(let y=H-2;y>=0;y--)for(let x=0;x<W;x++)if(grid[y][x]>=0&&grid[y+1][x]<0){grid[y+1][x]=grid[y][x];grid[y][x]=-1;changed=true;}}};
 const clear=()=>{let again=true;while(again){again=false;const remove=new Set();for(let y=0;y<H;y++)for(let x=0;x<W;x++){const v=grid[y][x];if(v<0)continue;if(v<2){for(const [dx,dy]of [[1,0],[0,1]]){const run=[];for(let n=0;x+n*dx<W&&y+n*dy<H&&grid[y+n*dy][x+n*dx]===v;n++)run.push(`${x+n*dx},${y+n*dy}`);if(run.length>=3)run.forEach(a=>remove.add(a));}}else if(v===3){remove.add(`${x},${y}`);const queue=[[x,y]],seen=new Set();while(queue.length){const [a,b]=queue.pop(),key=`${a},${b}`;if(seen.has(key))continue;seen.add(key);for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const xx=a+dx,yy=b+dy;if(xx>=0&&xx<W&&yy>=0&&yy<H&&grid[yy][xx]===2){remove.add(`${xx},${yy}`);queue.push([xx,yy]);}}}}}if(remove.size){again=true;remove.forEach(key=>{const[x,y]=key.split(',').map(Number);grid[y][x]=-1;});c.points(p,remove.size*10);settle();}}};
 spawn();
 const bot=()=>{let best=null;for(let rot=0;rot<2;rot++)for(let x=0;x<W;x++){const q={...piece,x,rot,y:0};if(!fits(q))continue;while(fits({...q,y:q.y+1}))q.y++;let score=q.y*.3;for(const[a,b,v]of cells(q)){if(b<0)continue;for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]])if(grid[b+dy]?.[a+dx]===v)score+=4;}if(!best||score>best.score)best={x,rot,score};}if(!best)return{};return piece.rot!==best.rot?{a:Math.sin(c.time*15)>.2}:piece.x!==best.x?{x:Math.sign(best.x-piece.x)}:{z:1};};
 return{update(dt){c.hint('좌우 이동 · ↓ 빠르게 · A/B 회전. 같은 색 3개 연결, 초록 껍질은 빨강으로 제거 · 목표 300점');const input=c.input(p,bot);if(c.time>nextMove&&Math.abs(input.x)>.3){const q={...piece,x:piece.x+Math.sign(input.x)};if(fits(q))piece=q;nextMove=c.time+.13;}if(input.ap||input.bp){const q={...piece,rot:1-piece.rot};if(fits(q))piece=q;}fall+=dt;if(fall>(input.z>.3?.045:.65)){fall=0;if(fits({...piece,y:piece.y+1}))piece.y++;else{for(const[x,y,v]of cells(piece)){if(y<0){lose(c,'블록이 천장에 닿았습니다');return;}grid[y][x]=v;}clear();if(p.score>=300)win(c,'Shroom City 퍼즐 300점');else spawn();}}},render(){box(c,'puzzle-back',0,5,-.4,8.4,12,.3,'#637d87');const draw=(x,y,v,id)=>{const xx=(x-2.5)*1.3,yy=11-y*1.15;if(v<2)box(c,id,xx,yy,0,1.14,1,.7,[PINK,GOLD][v]);else ball(c,id,xx,yy,0,1.1,v===2?GREEN:'#dc6579',{sy:.7});};grid.forEach((row,y)=>row.forEach((v,x)=>{if(v>=0)draw(x,y,v,`cell-${x}-${y}`);}));cells(piece).forEach(([x,y,v],i)=>{if(y>=0)draw(x,y,v,`falling-${i}`);});text(c,'krunch-score',`${p.score} / 300`,0,13,0,7);}};
}

function floorIt(c){
 const[p]=active(c,1,60);side(c,0,6,28);const colors=['#ece9de','#b59a78',GREEN,PINK],queues=Array.from({length:4},()=>[[],[]]);let floor=3,pos=3,doors=[false,false],cargo=[],spawn=.2,id=0,nextAction=0;
 const serve=()=>{if(Math.abs(pos-floor)>.02)return;for(let side=0;side<2;side++){if(!doors[side])continue;const leaving=cargo.filter(q=>q.home===floor);if(leaving.length){cargo=cargo.filter(q=>q.home!==floor);c.points(p,leaving.length*(leaving.length+1)*5);if(leaving.length>=2)c.limit+=leaving.length;leaving.forEach(q=>{if(q.clock)c.limit+=4;});}while(cargo.length<4&&queues[floor][side].length)cargo.push(queues[floor][side].shift());}};
 return{update(dt){c.hint('↑/↓ 승강기 · A 오른문, B 왼문. 최대 4명, 같은 승객 함께 배달하면 보너스 · 200점');const input=c.input(p,()=>{let goal=cargo[0]?.home;if(goal===undefined){let oldest=null;queues.forEach((q,f)=>q.forEach((list,s)=>{if(list.length&&(!oldest||list[0].at<oldest.at))oldest={f,s,at:list[0].at};}));goal=oldest?.f??floor;}return floor!==goal?{z:Math.sign(goal-floor)}:Math.abs(pos-floor)>.025?{}:{a:Math.sin(c.time*10)>.1,b:Math.sin(c.time*10)>.1};});
  if(Math.abs(input.z)>.3&&c.time>nextAction){floor=clamp(floor+Math.sign(input.z),0,3);doors=[false,false];nextAction=c.time+.24;}pos+=(floor-pos)*Math.min(1,dt*10);if(Math.abs(pos-floor)<.025)pos=floor;if(input.ap)doors[1]=!doors[1];if(input.bp)doors[0]=!doors[0];serve();
  if(c.time>spawn){spawn=c.time+c.rand(.85,1.4);const f=c.int(0,3),s=c.int(0,1),home=(f+c.int(1,3))%4;queues[f][s].push({id:id++,home,at:c.time,clock:c.rng()<.1});}queues.forEach(q=>q.forEach((list,s)=>{while(list.length&&c.time-list[0].at>10)list.shift();}));p.y=11-pos*3;p.x=0;p.score>=200&&win(c,'승강기 배달 200점');
 },render(){for(let f=0;f<4;f++){const y=11-f*3;box(c,`floor-${f}`,0,y-.5,0,23,.3,3,'#b69b76');text(c,`home-${f}`,['유령','버섯','거북','가면'][f],-10,y+.7,0,2.5,colors[f]);queues[f].forEach((list,s)=>list.slice(0,5).forEach((q,j)=>{const x=(s?1:-1)*(3+j*1.2);ball(c,`passenger-${q.id}`,x,y+.5,0,.85,colors[q.home]);if(q.clock)text(c,`clock-${q.id}`,'+시간',x,y+1.5,0,1.5); }));}box(c,'elevator',0,11-pos*3+.7,-.3,4,2.5,2.5,'#849ca9',{opacity:.6});doors.forEach((open,s)=>{if(!open)box(c,`door-${s}`,s?1.7:-1.7,11-pos*3+.6,.9,.2,2.3,.3,GOLD);});cargo.forEach((q,i)=>ball(c,`cargo-${i}`,(i-1.5)*.7,11-pos*3+.3,.8,.6,colors[q.home]));text(c,'lift-score',`${p.score} / 200`,0,15,0,7);},timeout(){p.score>=200?win(c,'목표 점수 달성'):lose(c,'배달 점수가 부족합니다');}};
}

function dreadmill(c){
 const[p]=active(c,1,60);p.z=4;let stun=0;const spikes=Array.from({length:13},(_,i)=>({x:(i%3-1)*3,z:-3-i*5,kind:i%3}));
 const where=s=>({x:s.x+(s.kind===1?Math.sin(c.time*1.5+s.z)*2:0),z:s.z+(s.kind===2?Math.sin(c.time*1.2)*1.3:0)});
 return{update(dt){c.hint('방향키로 움직이는 벨트에 맞서 전진하세요. 노랑 가시는 좌우, 빨강 가시는 앞뒤로 이동합니다. 60초 안에 결승점!');const q=spikes.map(where).filter(q=>q.z<p.z&&p.z-q.z<7).sort((a,b)=>b.z-a.z)[0];const input=c.input(p,()=>({x:q&&Math.abs(q.x-p.x)<1.8?p.x<=q.x?-1:1:Math.abs(p.x)>3.8?-Math.sign(p.x):0,z:-1}));const belt=Math.sin(c.time*.65+Math.floor(-p.z/10))*2.7;
  if(c.time>stun){p.x=clamp(p.x+input.x*dt*5,-5.5,5.5);p.z+=input.z*dt*6;}p.z+=belt*dt;
  if(c.time>stun&&spikes.some(s=>dist(p,where(s))<1.1)){stun=c.time+.8;p.z+=1.5;}p.score=Math.max(p.score,-p.z);if(p.z<-70)win(c,'컨베이어 코스 완주');c.view={size:24,eye:[0,20,p.z+16],target:[0,0,p.z-5]};
 },render(){box(c,'conveyor-road',0,-.25,-30,13,.5,85,'#5c7d8d');for(let i=0;i<17;i++){const z=7-i*5;box(c,`belt-line-${i}`,0,.03,z,12,.06,.2,'#a9c2bd');text(c,`belt-arrow-${i}`,Math.sin(c.time*.65+Math.floor(-z/10))>0?'↓':'↑',0,.2,z,2.5);}spikes.forEach((s,i)=>{const q=where(s);c.draw(`spike-${i}`,'cone',{x:q.x,y:.7,z:q.z,sx:1.6,sy:1.5,sz:1.6,color:s.kind===1?GOLD:s.kind===2?PINK:'#d4daca'});});box(c,'dread-goal',0,.1,-70,13,.15,.6,PINK);},timeout(){lose(c,'60초 안에 벨트 코스를 통과하지 못했습니다');}};
}

function stompbot(c){
 const[p]=active(c,1);p.z=0;p.y=1.4;let health=3,speed=0,lava=7,hurt=0;const obstacles=Array.from({length:20},(_,i)=>({x:(i%3-1)*3,z:-5-i*4.3,type:i%7===6?'kit':i%3===1?'lava':'rock',gone:false}));
 return{update(dt){c.hint('좌우 조향 · A 전진, B 제동. 용암을 피하고 구급상자로 하트 회복! Shroom City 한 구간 탈출');const near=obstacles.find(q=>!q.gone&&q.type!=='kit'&&q.z<p.z&&p.z-q.z<7);const input=c.input(p,()=>({x:near&&Math.abs(near.x-p.x)<1.7?p.x<near.x?-1:1:Math.abs(p.x)>3.8?-Math.sign(p.x):0,a:true}));speed=clamp(speed+(input.a?5:-2)*dt,0,health===3?7:health===2?5.8:4.5);if(input.b)speed=Math.max(0,speed-dt*8);p.x=clamp(p.x+input.x*dt*4.6,-5.5,5.5);p.z-=speed*dt;lava-=dt*4.3;
  obstacles.forEach(q=>{if(q.gone||dist(p,q)>1.3)return;q.gone=true;if(q.type==='kit')health=3;else if(c.time>hurt){hurt=c.time+.8;if(q.type==='lava')health--;else speed=Math.max(0,speed-4);}});p.score=Math.round(Math.max(0,-p.z));if(health<=0)lose(c,'로봇의 하트가 모두 줄었습니다');else if(p.z>=lava-1.2)lose(c,'용암 파도가 따라잡았습니다');else if(p.z<-90)win(c,'Shroom City 한 체크포인트 완주');c.view={size:23,eye:[0,18,p.z+17],target:[0,0,p.z-4]};
 },render(){box(c,'robot-track',0,-.3,-43,14,.6,104,'#8f9184');box(c,'lava-wave',0,.25,lava+10,16,.5,20,'#e68b50',{glow:true});obstacles.forEach((q,i)=>{if(!q.gone){if(q.type==='rock')ball(c,`rock-${i}`,q.x,.6,q.z,1.9,'#8e9b9e');else if(q.type==='lava')box(c,`lava-${i}`,q.x,.05,q.z,2.5,.1,2.4,'#f49458',{glow:true});else{box(c,`kit-${i}`,q.x,.6,q.z,1.4,1.2,1.3,'#f0ebdb');text(c,`cross-${i}`,'+',q.x,1.4,q.z,2,PINK);}}});box(c,'robot-body',p.x,.8,p.z,1.7,1.1,1.8,PINK);[-.65,.65].forEach((x,i)=>box(c,`robot-leg-${i}`,p.x+x,.2,p.z+Math.sin(c.time*speed+i*Math.PI)*.35,.5,.8,.8,'#657e92'));text(c,'robot-hearts','♥'.repeat(health),p.x,4,p.z,4,PINK);}};
}

function goGoPogo(c){
 const[p]=active(c,1,60);p.x=0;p.y=1;p.vy=8;const pipes=Array.from({length:11},(_,i)=>({x:i*4,y:0,green:i>0&&i%3===0,phase:c.rand(0,4)}));let lastPipe=0;
 const plant=q=>q.green&&(c.time+q.phase)%4.5>2.3&&(c.time+q.phase)%4.5<3.6;
 return{update(dt){c.hint('좌우 이동 · A를 누르면 높게 바운스. 초록 관의 식물 예고를 보고, 불덩이를 피해 끝으로!');const next=pipes[Math.min(lastPipe+1,10)];const input=c.input(p,()=>({x:plant(next)&&Math.abs(p.x-next.x)<4?0:Math.abs(next.x-p.x)>.2?Math.sign(next.x-p.x):0,a:true}));p.x+=input.x*dt*5.5;const old=p.y;p.vy-=18*dt;p.y+=p.vy*dt;
  for(let i=0;i<pipes.length;i++){const q=pipes[i];if(Math.abs(p.x-q.x)<1.25&&p.vy<=0&&old>=q.y+.5&&p.y<=q.y+.5){p.y=q.y+.5;p.vy=input.a?11:8;lastPipe=i;}if(plant(q)&&Math.abs(p.x-q.x)<.7&&p.y<2.2)lose(c,'관에서 나온 식물에 닿았습니다');}
  [10,26].forEach((x,i)=>{const y=Math.max(-1,Math.sin(c.time*1.6+i)*3.5);if(Math.hypot(p.x-x,p.y-y)<.8)lose(c,'용암 불덩이에 닿았습니다');});if(p.y<-.6)lose(c,'용암에 떨어졌습니다');if(lastPipe===10)win(c,'포고 코스의 마지막 관 도착');p.score=Math.round(Math.max(0,p.x));side(c,p.x+4,4,26);
 },render(){box(c,'pogo-lava',p.x,-1,0,45,.8,7,'#e48b59',{glow:true});pipes.forEach((q,i)=>{c.draw(`pipe-${i}`,'cylinder',{x:q.x,y:-.1,z:0,sx:2.5,sy:1.2,sz:2.5,color:q.green?GREEN:BLUE});if(q.green){const t=(c.time+q.phase)%4.5;ball(c,`plant-${i}`,q.x,plant(q)?1.5:.3,0,plant(q)?1.3:.5,PINK);if(t>1.6&&t<2.3)text(c,`warning-${i}`,'!',q.x,2.4,0,2.3,PINK);}});[10,26].forEach((x,i)=>ball(c,`fire-${i}`,x,Math.max(-1,Math.sin(c.time*1.6+i)*3.5),0,1,GOLD,{glow:true}));box(c,'pogo-stick',p.x,p.y-.5,0,.18,1,.18,'#75899d');},timeout(){lose(c,'60초 안에 포고 코스를 마치지 못했습니다');}};
}

function sledSlide(c){
 const[p]=active(c,1,30);p.x=9;p.z=0;let heading=Math.PI/2,speed=0,progress=0,lastAngle=0,spin=0;
 return{update(dt){c.hint('좌우 조향 · A 가속 · B 제동. 빠른 속도에서 급회전하면 회전합니다. 30초 안에 한 바퀴!');const theta=Math.atan2(p.z/6,p.x/9),target={x:Math.cos(theta+.45)*9,z:Math.sin(theta+.45)*6};const delta=angleDifference(Math.atan2(target.z-p.z,target.x-p.x),heading);
  const input=c.input(p,()=>({x:clamp(delta*2,-1,1),a:Math.abs(delta)<.65,b:Math.abs(delta)>.8}));
  if(c.time<spin){speed*=Math.pow(.96,dt*60);heading+=dt*7;}else{speed=clamp(speed+dt*(input.a?4:-1.6),0,9);if(input.b)speed=Math.max(0,speed-dt*7);if(Math.abs(input.x)>.85&&speed>7.4){spin=c.time+.65;speed=3;}else heading+=input.x*dt*(1.25+speed*.06);}
  p.x+=Math.cos(heading)*speed*dt;p.z+=Math.sin(heading)*speed*dt;p.rotation=-heading;const r=Math.hypot(p.x/9,p.z/6);if(r<.73||r>1.28){const rr=clamp(r,.74,1.27);p.x*=rr/r;p.z*=rr/r;speed*=.92;}
  const now=Math.atan2(p.z/6,p.x/9),d=angleDifference(now,lastAngle);progress+=d;lastAngle=now;p.score=Math.max(0,Math.round(progress/Math.PI/2*100));if(progress>=Math.PI*2-.1)win(c,'얼음 트랙 한 바퀴 완주');
 },render(){c.arena({width:25,depth:18,color:'#bdd8dd',shape:'cylinder'});c.draw('track-outer','ring',{y:.03,sx:22,sy:15,sz:1,rx:-Math.PI/2,color:'#e7f0dc'});c.draw('track-inner','cylinder',{x:0,y:.06,z:0,sx:12,sy:.15,sz:8,color:'#8eaeb8'});for(let i=0;i<8;i++){const a=i*Math.PI/4;text(c,`track-arrow-${i}`,'➜',Math.cos(a)*9,.2,Math.sin(a)*6,1.5,'#73949e');}box(c,'sled',p.x,.18,p.z,1.3,.35,1.8,PINK,{ry:p.rotation});text(c,'sled-progress',`${Math.min(100,p.score)}%`,0,1,0,4);},timeout(){lose(c,'30초 안에 한 바퀴를 완주하지 못했습니다');}};
}

function flippinOut(c){
 const[p]=active(c,1,30);side(c,5,6,26);const pegs=Array.from({length:10},(_,i)=>({x:i*4,y:[5,5,9,9,9,5,5,9,9,5][i],type:i===9?'goal':i===3||i===6?'blue':i===4?'red':'green'}));let attached=0,vx=0,vy=0,cooldown=0;
 const point=(q,i)=>({x:q.x+(q.type==='blue'?Math.sin(c.time*1.3+i)*.45:0),y:q.y+(q.type==='blue'?Math.cos(c.time+i)*.35:0),on:q.type!=='red'||(c.time%4.5)<3.5});
 return{update(dt){c.hint('방향키로 방향 선택 · A로 다음 고리 향해 뛰기 · B 놓기. 빨간 고리는 사라지고 파란 고리는 움직입니다.');const input=c.input(p,()=>{if(attached===null)return{};const next=pegs[attached+1];if(!next)return{};const a=point(pegs[attached],attached),b=point(next,attached+1);if(!b.on||(next.type==='red'&&c.time%4.5>2.85))return{};return{x:1,z:b.y-a.y>2?-1:b.y-a.y<-2?1:0,a:Math.sin(c.time*8)>.1};});
  if(attached!==null){const a=point(pegs[attached],attached);p.x=a.x;p.y=a.y-1.25;if(!a.on||input.bp){attached=null;vx=0;vy=0;cooldown=c.time+.15;}else if(input.ap){vx=input.x*9;vy=-input.z*9+2;attached=null;cooldown=c.time+.18;}}
  else{const oldX=p.x;p.x+=vx*dt;vy-=9*dt;p.y+=vy*dt;if(!input.b&&c.time>cooldown)for(let i=0;i<pegs.length;i++){const q=point(pegs[i],i);if(q.on&&Math.hypot(p.x-q.x,p.y+1.25-q.y)<.9){attached=i;p.x=q.x;p.y=q.y-1.25;vx=vy=0;p.score=Math.max(p.score,i);if(i===9)win(c,'목표 고리에 도착');break;}}if(p.y<.1)lose(c,'용암에 떨어졌습니다');}
  side(c,p.x+5,7,27);
 },render(){box(c,'peg-lava',p.x,-.7,0,48,1,7,'#db8859',{glow:true});pegs.forEach((q,i)=>{const a=point(q,i);if(a.on){ball(c,`peg-${i}`,a.x,a.y,0,.7,q.type==='goal'?GOLD:q.type==='red'?PINK:q.type==='blue'?BLUE:GREEN);box(c,`peg-post-${i}`,a.x,a.y,-.5,.25,.25,1.4,'#677e8c');}if(q.type==='blue')box(c,`peg-rail-${i}`,q.x,q.y,-.8,2,.14,.1,'#8996a0');});text(c,'peg-goal','GOAL',pegs[9].x,pegs[9].y+2,0,4,GOLD);},timeout(){lose(c,'30초 안에 목표 고리에 닿지 못했습니다');}};
}

function seeMonkey(c){
 const[p]=active(c,1,50);p.z=6;let heading=-Math.PI/2,speed=0,stun=0;const swimmers=Array.from({length:10},(_,i)=>({x:Math.cos(i*Math.PI/5)*7,z:Math.sin(i*Math.PI/5)*4.5,saved:false}));const rocks=[{x:-3,z:-1},{x:2,z:2},{x:3,z:-2},{x:-4,z:3}].map(q=>({...q,broken:false}));
 return{update(dt){c.hint('좌우로 배 방향을 돌리고 A로 가속하세요. 바위 충돌은 잠시 기절 · 50초 안에 물에 빠진 친구 10명');const q=swimmers.filter(q=>!q.saved).sort((a,b)=>dist(p,a)-dist(p,b))[0];const delta=q?angleDifference(Math.atan2(q.z-p.z,q.x-p.x),heading):0;const input=c.input(p,()=>({x:clamp(delta*2,-1,1),a:Math.abs(delta)<.8}));heading+=input.x*dt*2.8;speed=clamp(speed+(input.a?4:-4)*dt,0,6);if(c.time<stun)speed=0;p.x=clamp(p.x+Math.cos(heading)*speed*dt,-9,9);p.z=clamp(p.z+Math.sin(heading)*speed*dt,-6.5,6.5);p.rotation=-heading;
  swimmers.forEach(q=>{if(!q.saved&&dist(p,q)<1.15){q.saved=true;c.points(p);}});rocks.forEach(q=>{if(!q.broken&&dist(p,q)<1.25){q.broken=true;stun=c.time+.8;speed=0;}});if(p.score===10)win(c,'친구 열 명 구조');
 },render(){c.arena({width:21,depth:16,color:'#69afc3'});swimmers.forEach((q,i)=>{if(!q.saved){ball(c,`swimmer-${i}`,q.x,.25+Math.sin(c.time*3+i)*.1,q.z,.8,'#b38869');c.draw(`float-${i}`,'ring',{x:q.x,y:.2,z:q.z,sx:1.2,sy:1.2,sz:1,rx:-Math.PI/2,color:GOLD});}});rocks.forEach((q,i)=>{if(!q.broken)ball(c,`lake-rock-${i}`,q.x,.45,q.z,2,'#81959b');});box(c,'rescue-boat',p.x,.2,p.z,2,.4,1.2,PINK,{ry:p.rotation});text(c,'rescue-count',`${p.score} / 10`,0,1,-8,6);},timeout(){lose(c,'50초 안에 열 명을 구조하지 못했습니다');}};
}

function outtaMyWay(c){
 const[p]=active(c,1,60);p.x=0;p.vy=0;side(c,7,4,27);let stun=0;const obstacles=Array.from({length:9},(_,i)=>({x:6+i*5.5,type:i%3,hp:i%3===0?4:1,push:0,last:'b',fall:0,dead:false,nextPunch:0}));
 return{update(dt){c.hint('좌우 이동 · A 점프 · B 펀치. 무거운 돌 앞에서는 A/B 교대 밀기, 쓰러진 돌은 위에서 밟으세요!');const q=obstacles.find(q=>!q.dead&&q.x>p.x-1.3),near=q&&q.x-p.x<2.3;
  const input=c.input(p,()=>{if(!near)return{x:1};if(q.type===0)return{x:1,b:Math.sin(c.time*12)>.2};if(q.type===1)return{[q.last==='a'?'b':'a']:Math.sin(c.time*15)>.1,x:1};return{x:q.fall&&c.time-q.fall>.6?1:-.1,a:!!q.fall&&c.time-q.fall>.8};});
  if(c.time>stun){p.x+=input.x*dt*4.2;if(!(near&&q.type===1)&&input.ap&&p.y===0)p.vy=8;}
  const old=p.y;p.vy-=18*dt;p.y=Math.max(0,p.y+p.vy*dt);if(p.y===0)p.vy=0;
  for(const o of obstacles){if(o.dead)continue;const d=o.x-p.x;if(o.type===0){if(Math.abs(d)<2&&input.bp&&c.time>o.nextPunch){o.nextPunch=c.time+.2;o.hp-=p.y>2?4:1;if(o.hp<=0)o.dead=true;}if(!o.dead&&Math.abs(d)<.9&&p.y<3.5&&c.time>stun){p.x=o.x-1.3;stun=c.time+.35;}}
   else if(o.type===1){if(Math.abs(d)<2.2){const k=input.ap?'a':input.bp?'b':null;if(k&&k!==o.last){o.last=k;o.push++;if(o.push>=12)o.dead=true;}if(!o.dead&&p.x>o.x-1.3)p.x=o.x-1.3;}}
   else{if(!o.fall&&Math.abs(d)<2.3)o.fall=c.time;if(o.fall){const t=c.time-o.fall;if(t>.65&&t<2.5){if(Math.abs(d)<1.8&&p.vy<0&&old>.55&&p.y<=.55){o.dead=true;p.vy=6;}else if(t<.9&&Math.abs(d)<1.5&&p.y<1&&c.time>stun){p.x-=2;stun=c.time+.7;}}if(t>2.5)o.fall=0;}if(!o.dead&&(!o.fall||c.time-o.fall<.65)&&p.x>o.x-1.1)p.x=o.x-1.1;}}
  p.x=Math.max(0,p.x);p.score=Math.floor(p.x);if(p.x>57)win(c,'장애물을 치우고 결승점 도착');side(c,p.x+6,4,27);
 },render(){box(c,'obstacle-floor',p.x+8,-.3,0,45,.6,5,'#c2ae86');obstacles.forEach((q,i)=>{if(q.dead)return;if(q.type===0){for(let n=0;n<q.hp;n++)ball(c,`cactus-${i}-${n}`,q.x,.45+n*.85,0,.9,GREEN);}else if(q.type===1){box(c,`heavy-${i}`,q.x,1.6,0,2,3.2,2,'#8c99a4');text(c,`push-${i}`,`${q.push}/12`,q.x,3.8,0,2.5);}else{const down=q.fall&&c.time-q.fall>.65;box(c,`falling-stone-${i}`,q.x,down?.25:1.7,0,down?3.2:1.7,down?.5:3.4,1.6,'#a38e8b');text(c,`stone-warning-${i}`,q.fall&&!down?'!':'● ●',q.x,down?1:3.8,0,2);}});box(c,'outta-finish',57,2,-.5,.3,4,1,PINK);},timeout(){lose(c,'60초 안에 장애물 코스를 마치지 못했습니다');}};
}

function broomZoom(c){
 const[p]=active(c,1);p.z=3;p.y=4;let travel=0,combo=0,stun=0;const rings=Array.from({length:32},(_,i)=>({x:Math.sin(i*1.4)*5,y:4+Math.sin(i*.8)*2,z:-10-i*6,done:false}));const hazards=Array.from({length:12},(_,i)=>({x:(i%2?1:-1)*5.8,y:3+i%3,z:-15-i*15,type:i%2,hit:false}));
 return{update(dt){c.hint('방향키로 빗자루의 좌우·높이 조절. 고리를 연속 통과하면 1·2·4·8…점! 장애물은 연속 점수 초기화 · 목표 5,000');const q=rings.find(q=>!q.done);const input=c.input(p,()=>q?{x:clamp((q.x-p.x)*2,-1,1),z:clamp((p.y-q.y)*2,-1,1)}:{});if(c.time>stun){p.x=clamp(p.x+input.x*dt*6,-8,8);p.y=clamp(p.y-input.z*dt*5,1,8);}travel+=dt*6;p.pose='jump';
  rings.forEach(q=>{if(!q.done&&q.z+travel>=p.z){q.done=true;if(Math.hypot(p.x-q.x,p.y-q.y)<1.5){c.points(p,2**Math.min(combo,18));combo++;}else combo=0;}});hazards.forEach(h=>{if(!h.hit&&Math.abs(h.z+travel-p.z)<1&&Math.hypot(p.x-h.x,p.y-h.y)<1.2){h.hit=true;combo=0;stun=c.time+.7;}});if(p.score>=5000)win(c,'연속 고리 통과 5,000점 달성');else if(rings.every(q=>q.done))lose(c,'코스를 끝냈지만 5,000점에 못 미쳤습니다');c.view={size:23,eye:[0,12,23],target:[0,4,-3]};
 },render(){rings.forEach((q,i)=>{const z=q.z+travel;if(!q.done&&z>-40)c.draw(`air-ring-${i}`,'ring',{x:q.x,y:q.y,z,sx:3.3,sy:3.3,sz:1,color:GOLD});});hazards.forEach((h,i)=>{const z=h.z+travel;if(!h.hit&&z>-40&&z<10){if(h.type)ball(c,`flight-amp-${i}`,h.x,h.y,z,1.6,'#5d7184');else box(c,`flight-block-${i}`,h.x,h.y,z,1.6,1.6,1.6,'#ad896a');}});box(c,'broom',p.x,p.y-.2,p.z,2.7,.14,.2,'#ac835b');text(c,'broom-score',`${p.score} / 5000 · 연속 ${combo}`,0,10,-1,12);}};
}

function tankDown(c){
 const players=active(c,2,60);c.bounds={x:8,z:5.5};const states=players.map((p,i)=>{p.z=i?-3:3;p.score=5;return{charge:0,holding:false,angle:i?Math.PI:0,ready:0,hurt:0,known:{x:-p.x,z:-p.z},wander:0,phase:c.rand(0,1.5),period:c.rand(2.1,2.8)};});const shots=[];let id=0;
 return{update(dt){c.hint('방향키로 전차 이동 · A를 눌렀다 놓아 로켓 주먹 발사. 오래 누르면 최대 3하트 피해, 충전 중 감속.');players.forEach((p,i)=>{const s=states[i],enemy=players[1-i],seen=dist(p,enemy)<6;if(seen)s.known={x:enemy.x,z:enemy.z};
  const input=c.input(p,()=>{if(!seen&&dist(p,s.known)<1&&c.time>s.wander){s.known={x:c.rand(-7,7),z:c.rand(-4,4)};s.wander=c.time+2;}const v=toward(p,s.known.x,s.known.z);return{...v,a:seen&&((c.time+s.phase)%s.period)<1.45};});if(!p.alive)return;if(Math.hypot(input.x,input.z)>.1)s.angle=Math.atan2(input.z,input.x);c.move(p,input,input.a?2:4.2);
  if(input.a)s.charge=Math.min(1.5,s.charge+dt);if(s.holding&&!input.a&&c.time>s.ready){shots.push({id:id++,owner:i,x:p.x,z:p.z,vx:Math.cos(s.angle)*10,vz:Math.sin(s.angle)*10,damage:Math.min(3,1+Math.floor(s.charge/.5)),time:c.time});s.ready=c.time+.3;s.charge=0;}s.holding=input.a;
  p.visible=c.humans===1&&i===1?seen:true;
 });shots.forEach(q=>{q.x+=q.vx*dt;q.z+=q.vz*dt;const enemy=players[1-q.owner];if(!q.hit&&c.time-q.time<1&&dist(q,enemy)<1&&c.time>states[enemy.i].hurt){q.hit=true;enemy.score=Math.max(0,enemy.score-q.damage);states[enemy.i].hurt=c.time+.5;enemy.x=clamp(enemy.x+q.vx*.13,-8,8);enemy.z=clamp(enemy.z+q.vz*.13,-5.5,5.5);if(enemy.score===0)c.eliminate(enemy);}});duelEnd(c,players,'로켓 주먹 결투 종료');
 },render(){c.arena({width:18,depth:13,color:'#273445'});players.forEach((p,i)=>{if(p.visible){c.draw(`lamp-${i}`,'cylinder',{x:p.x,y:.01,z:p.z,sx:9,sy:.03,sz:9,color:'#b1b79a',opacity:.2});box(c,`tank-${i}`,p.x,.25,p.z,1.8,.6,1.4,p.color,{ry:-states[i].angle});text(c,`tank-life-${i}`,'♥'.repeat(p.score),p.x,3,p.z,3.5,p.color);if(states[i].charge>0)ball(c,`tank-charge-${i}`,p.x+Math.cos(states[i].angle),1,p.z+Math.sin(states[i].angle),.5+states[i].charge*.4,GOLD);}});shots.forEach(q=>{if(!q.hit&&c.time-q.time<1&&(c.humans!==1||dist(q,players[0])<6))box(c,`punch-${q.id}`,q.x,.8,q.z,.5+q.damage*.3,.7,.7,GOLD,{ry:-Math.atan2(q.vz,q.vx)});});},timeout(){c.complete([],'60초 안에 상대를 쓰러뜨리지 못해 무승부');}};
}

function hammergeddon(c){
 const players=active(c,2);c.bounds={x:8,z:5.5};players.forEach(p=>p.score=3);const state=players.map(()=>({angle:0,next:0,hurt:0})),hammers=[];let id=0;
 return{update(dt){c.hint('방향 이동 · A 점프 · B 망치 던지기. 방향을 놓고 던지면 바로 위로! 자기 망치도 위험 · 하트 3개');players.forEach((p,i)=>{const s=state[i],other=players[1-i];const input=c.input(p,()=>{let v=dist(p,other)>4?toward(p,other.x,other.z):{x:Math.cos(c.time*1.8+i)*.8,z:Math.sin(c.time*1.8+i)*.8};const threat=hammers.find(q=>!q.hit&&q.y<3&&dist(p,q)<2);if(threat)v=toward(threat,p.x,p.z);return{...v,a:!!threat,b:c.time>s.next&&Math.sin(c.time*9+i)>.2};});if(!p.alive)return;c.move(p,input,5);c.jump(p,input,7.5);if(Math.hypot(input.x,input.z)>.1)s.angle=Math.atan2(input.z,input.x);
   if(input.bp&&c.time>s.next){const moving=Math.hypot(input.x,input.z)>.1;hammers.push({id:id++,x:p.x,z:p.z,y:p.y+1.3,vx:moving?Math.cos(s.angle)*7:0,vz:moving?Math.sin(s.angle)*7:0,vy:7,born:c.time,hit:false});s.next=c.time+.45;}}
 );hammers.forEach(q=>{if(q.hit)return;q.x+=q.vx*dt;q.z+=q.vz*dt;q.vy-=14*dt;q.y+=q.vy*dt;players.forEach(p=>{if(p.alive&&c.time-q.born>.3&&c.time>state[p.i].hurt&&dist(p,q)<.9&&q.y>p.y-.2&&q.y<p.y+1.7){q.hit=true;p.score--;state[p.i].hurt=c.time+.65;if(p.score===0)c.eliminate(p);}});if(q.y<0)q.hit=true;});duelEnd(c,players,'망치 결투 종료');
 },render(){c.arena({width:18,depth:13,color:'#a9b899'});players.forEach(p=>text(c,`hammer-life-${p.i}`,'♥'.repeat(p.score),p.x,p.y+3,p.z,3,p.color));hammers.forEach(q=>{if(!q.hit){box(c,`hammer-head-${q.id}`,q.x,q.y,q.z,.8,.45,.5,'#6c7685',{rz:c.time*8});box(c,`hammer-stick-${q.id}`,q.x,q.y-.45,q.z,.18,.9,.18,'#b58e69',{rz:c.time*8});}});}};
}

function stairScare(c){
 const players=active(c,2);side(c,0,6,27);const rates=players.map(()=>c.rand(5.8,7.5));players.forEach((p,i)=>{p.x=i?3:-3;p.z=0;});
 return{update(){c.hint('A를 반복해서 눌러 무너지는 계단을 오르세요. 열기구에 먼저 닿거나 상대를 크게 따돌리면 승리!');players.forEach((p,i)=>{const input=c.input(p,()=>({a:Math.floor(c.time*rates[i]*2)%2===0}));if(p.alive&&input.ap){p.score++;p.y=p.score*.2;}if(p.alive&&p.score<Math.max(0,(c.time-3)*3.2))c.eliminate(p);});const live=players.filter(p=>p.alive);if(live.length<2)c.complete(live.map(p=>p.i),'계단 붕괴');else if(players.some(p=>p.score>=100)){const best=Math.max(...players.map(p=>p.score));c.complete(players.filter(p=>p.score===best).map(p=>p.i),'열기구 도착');}else if(Math.abs(players[0].score-players[1].score)>=20)c.complete([players[0].score>players[1].score?0:1],'상대를 충분히 따돌렸습니다');side(c,0,Math.max(6,Math.max(...players.map(p=>p.y))),27);
 },render(){for(let i=Math.max(0,Math.floor((c.time-3)*3.2));i<101;i++)box(c,`stair-${i}`,0,i*.2-.15,-i*.03,11,.25,1.7,i%2?'#a6ada6':'#bcc0ab');players.forEach(p=>text(c,`stair-count-${p.i}`,p.score,p.x,p.y+2,0,2.5,p.color));ball(c,'escape-balloon',0,24,-1,5,PINK);box(c,'escape-basket',0,20.7,-1,2,1,1.5,'#b48f67');}};
}

function chicken(c){
 const players=active(c,2);const impact=c.rand(5,8),threshold=players.map(()=>c.rand(.93,.985)),escaped=[null,null],fake=[0,0];
 return{update(){const fraction=clamp(c.time/impact,0,1);c.hint('그림자가 커질수록 돌이 가깝습니다. A 진짜 도망 · B 가짜 도망. 더 늦게 안전하게 빠져나오면 승리!');players.forEach((p,i)=>{const input=c.input(p,()=>({a:fraction>threshold[i],b:!escaped[i]&&fraction>.6&&fraction<.65}));if(escaped[i]===null&&input.ap){escaped[i]=c.time;p.x=i?7:-7;}else if(escaped[i]===null&&input.bp)fake[i]=c.time+.55;if(escaped[i]===null)p.x=(i?1:-1)*(fake[i]>c.time?4:1.8);});
  if(c.time>=impact){const safe=escaped.map((at,i)=>({at,i})).filter(q=>q.at!==null&&q.at<impact);if(!safe.length)c.complete([],'두 플레이어 모두 돌에 눌렸습니다');else{const last=Math.max(...safe.map(q=>q.at));c.complete(safe.filter(q=>q.at===last).map(q=>q.i),'가장 늦게 안전하게 탈출');}}
 },render(){const f=clamp(c.time/impact,0,1);c.arena({width:19,depth:12,color:'#b2ae9a'});c.draw('danger-shadow','cylinder',{x:0,y:.02,z:0,sx:1+f*f*9,sy:.04,sz:1+f*f*7,color:'#475263',opacity:.2+.65*f});if(f>.8)box(c,'falling-block',0,16*(1-f*f)+2,0,6,4,5,'#8693a0');players.forEach(p=>{if(fake[p.i]>c.time)text(c,`fake-${p.i}`,'?',p.x,3,0,2.5,p.color);});}};
}

function chainSaw(c){
 const players=active(c,2);players.forEach(p=>p.z=1);const state=players.map(()=>({expected:'a',heat:0,last:-1,rest:0,next:.3,pace:c.rand(.18,.26)}));
 return{update(dt){c.hint('A/B를 번갈아 당기고 밀어 사슬을 끊으세요. 너무 빠르면 땀이 나고 쉬어야 합니다!');players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>{if(c.time<s.next||c.time<s.rest)return{};s.next=c.time+s.pace;return{[s.expected]:true};});s.heat=Math.max(0,s.heat-dt*.55);if(c.time<s.rest)return;const key=input.ap?'a':input.bp?'b':null;if(key===s.expected){const interval=c.time-s.last;s.last=c.time;s.heat+=interval<.14?.45:.11;s.expected=key==='a'?'b':'a';if(s.heat>1.3){s.rest=c.time+1.3;s.heat=.7;}else c.points(p);}});const best=Math.max(...players.map(p=>p.score));if(best>=40)c.complete(players.filter(p=>p.score===best).map(p=>p.i),'사슬을 먼저 절단');
 },render(){c.arena({width:19,depth:12,color:'#a3b596'});players.forEach((p,i)=>{const other=players[1-i],s=state[i];box(c,`saw-${i}`,p.x,1.2,-1,3,.2,.5,'#a8afb4',{rz:s.expected==='a'?.1:-.1});for(let n=0;n<8;n++)ball(c,`chain-${i}-${n}`,other.x,2+n*.6,0,.3,'#617b8b');box(c,`hanging-${i}`,other.x,7.5,0,2.8,2.5,2.6,'#8b9097');text(c,`saw-progress-${i}`,`${p.score}/40 ${c.time<s.rest?'휴식':s.heat>.7?'땀!':''}`,p.x,3.8,2,5,p.color);});}};
}

function volleybomb(c){
 const players=active(c,2);side(c,0,5,27);players.forEach(p=>p.score=3);let bomb=null,serveAt=.5,serve=0,lastHit=-1,hitAt=0;const next=players.map(()=>0);
 const spawn=()=>{const side=serve++%2;bomb={x:side?4:-4,y:5,vx:side?-3:3,vy:3,fuse:c.rand(6,9)};lastHit=-1;};
 const point=()=>{const loser=bomb.x<0?0:1;players[loser].score--;if(players[loser].score===0){c.eliminate(players[loser]);c.complete([1-loser],'상대의 세 하트를 모두 줄였습니다');}bomb=null;serveAt=c.time+1;};
 return{update(dt){c.hint('좌우 이동 · A 점프 · B 망치. 바닥에서 높게, 공중에서 강하게 보내세요. 떨어지거나 도화선이 끝난 쪽이 하트를 잃습니다.');if(!bomb&&c.time>=serveAt)spawn();players.forEach((p,i)=>{const input=c.input(p,()=>{if(!bomb)return{};const own=i===0?bomb.x<0:bomb.x>=0,target=clamp(bomb.x+(bomb.vx||0)*.2,i===0?-8:.8,i===0?-.8:8);return{x:own?clamp((target-p.x)*2,-1,1):0,a:own&&bomb.y>3.3&&Math.abs(bomb.x-p.x)<2,b:own&&Math.hypot(bomb.x-p.x,bomb.y-p.y-1)<2.1&&c.time>next[i]};});p.x=clamp(p.x+input.x*dt*5,i===0?-8:.8,i===0?-.8:8);c.jump(p,input,7.5);if(bomb&&input.bp&&c.time>next[i]&&Math.hypot(bomb.x-p.x,bomb.y-p.y-1)<2.2&&c.time-hitAt>.15){lastHit=i;hitAt=c.time;next[i]=c.time+.35;bomb.vx=i===0?6:-6;bomb.vy=p.y>1?-1.5:8;bomb.y=Math.max(bomb.y,p.y+1.2);}});
  if(bomb){const old=bomb.x;bomb.x+=bomb.vx*dt;bomb.vy-=10*dt;bomb.y+=bomb.vy*dt;bomb.fuse-=dt;if(old*bomb.x<0&&bomb.y<2){bomb.x=old;bomb.vx*=-.8;}if(bomb.x<-9||bomb.x>9)bomb.vx*=-.9;if(bomb.y<=0||bomb.fuse<=0)point();}
 },render(){box(c,'volley-floor',0,-.3,0,20,.6,6,'#d1be95');box(c,'volley-net',0,1,0,.15,2,5,'#e9dfc8');players.forEach(p=>text(c,`volley-life-${p.i}`,'♥'.repeat(p.score),p.x,p.y+3.5,0,3,p.color));if(bomb){ball(c,'volley-bomb',bomb.x,bomb.y,0,1.1,bomb.fuse<1.5?PINK:'#506076');text(c,'volley-fuse',bomb.fuse.toFixed(1),bomb.x,bomb.y+1.2,0,2);}}};
}

function koopaKurl(c){
 const players=active(c,2);players.forEach((p,i)=>{p.x=-10;p.z=i?5:-5;});c.view={size:27,eye:[0,24,18],target:[0,0,0]};const shells=[];let turn=0,round=1,shot=0,aim=0,rolling=false,shotAt=0,ready=.4,id=0;
 const zone=q=>{const d=Math.hypot(q.x-7,q.z);if(d<.55)return 100;if(d<1.2)return 50;if(d<1.9)return 30;if(d<2.7)return 20;for(const a of [{x:0,z:-3,r:1.15,v:20},{x:0,z:0,r:.8,v:15},{x:0,z:3,r:.8,v:25}])if(Math.hypot(q.x-a.x,q.z-a.z)<a.r)return a.v;return 0;};
 const tally=i=>{const own=shells.filter(q=>q.owner===i),points=own.reduce((s,q)=>s+zone(q),0),double=own.some(q=>Math.abs(q.x-3)<.35&&(Math.abs(q.z-1.65)<1.1||Math.abs(q.z+1.65)<1.1));return points*(double?2:1);};
 return{update(dt){c.hint(`방향 좌우로 조준 · A로 왕복하는 힘 게이지 정지 · B 코트 확인. ${round}/2 라운드, ${turn+1}P 차례 · 각 3개`);const power=.5+.5*Math.sin(c.time*3);players.forEach((p,i)=>{const input=c.input(p,()=>i===turn&&!rolling&&c.time>ready?{x:Math.abs(aim)>.005?-Math.sign(aim):0,a:Math.abs(power-.66)<.035}:{});if(i!==turn||rolling)return;aim=clamp(aim+input.x*dt*.4,-.42,.42);if(input.ap&&c.time>ready){const speed=3+power*9;shells.push({id:id++,owner:i,x:-9,z:0,vx:Math.cos(aim)*speed,vz:Math.sin(aim)*speed});rolling=true;shotAt=c.time;c.sound?.(300+power*300,.08);}});
  if(rolling){shells.forEach(q=>{q.x+=q.vx*dt;q.z+=q.vz*dt;const speed=Math.hypot(q.vx,q.vz),k=speed?Math.max(0,speed-2.5*dt)/speed:0;q.vx*=k;q.vz*=k;});for(let i=0;i<shells.length;i++)for(let j=i+1;j<shells.length;j++){const a=shells[i],b=shells[j],d=dist(a,b);if(d<.8&&d>.001){const nx=(b.x-a.x)/d,nz=(b.z-a.z)/d,v=(a.vx-b.vx)*nx+(a.vz-b.vz)*nz,over=(.8-d)/2;a.x-=nx*over;a.z-=nz*over;b.x+=nx*over;b.z+=nz*over;if(v>0){a.vx-=nx*v*.92;a.vz-=nz*v*.92;b.vx+=nx*v*.92;b.vz+=nz*v*.92;}}}
   if(c.time-shotAt>.25&&shells.every(q=>Math.hypot(q.vx,q.vz)<.04)){rolling=false;shot++;ready=c.time+.5;if(shot===6){players.forEach((p,i)=>c.points(p,tally(i)));if(round===2){const best=Math.max(...players.map(p=>p.score));c.complete(players.filter(p=>p.score===best).map(p=>p.i),'두 라운드 합계 점수');}else{round++;shot=0;shells.length=0;turn=0;}}else turn=shot%2;aim=0;}}
 },render(){box(c,'curl-court',0,-.15,0,23,.3,11,'#d9e7da');[[2.7,BLUE],[1.9,PINK],[1.2,GOLD],[.55,GREEN]].forEach(([r,col],i)=>{c.draw(`curl-target-${i}`,'cylinder',{x:7,y:.02+i*.015,z:0,sx:r*2,sy:.02,sz:r*2,color:col});});text(c,'target-100','100',7,.2,0,1.4);[{z:-3,r:1.15,v:20,col:BLUE},{z:0,r:.8,v:15,col:PINK},{z:3,r:.8,v:25,col:BLUE}].forEach((q,i)=>{c.draw(`curl-side-${i}`,'cylinder',{x:0,y:.05,z:q.z,sx:q.r*2,sy:.02,sz:q.r*2,color:q.col});text(c,`curl-number-${i}`,q.v,0,.2,q.z,1.5);});[-1.65,1.65].forEach((z,i)=>{box(c,`double-${i}`,3,.06,z,.7,.03,2.2,GOLD);text(c,`double-label-${i}`,'×2',3,.2,z,1.3);});shells.forEach(q=>ball(c,`curl-shell-${q.id}`,q.x,.35,q.z,.8,players[q.owner].color,{sy:.5}));if(!rolling){const power=.5+.5*Math.sin(c.time*3);box(c,'curl-aim',-7,.08,Math.sin(aim)*2,4,.04,.1,players[turn].color,{ry:-aim});box(c,'curl-power-bg',-7,.1,6,5,.1,.5,'#a1adab');box(c,'curl-power',-9.5+2.5*power,.2,6,5*power,.15,.45,GOLD);}players.forEach((p,i)=>text(c,`curl-score-${i}`,`${i+1}P: ${p.score} + ${tally(i)}`,-5+i*10,1,-7,6,p.color));}};
}

function slammer(c){
 const players=active(c,2);players.forEach(p=>{p.x*=.6;p.score=5;});let attacker=0,cueAt=0,resetAt=0,resolved=false,sounded=false,hit=-1;const reaction=[0,0];
 const newRound=()=>{attacker=c.int(0,1);cueAt=c.time+c.rand(1.3,3.5);resolved=sounded=false;reaction.forEach((_,i)=>reaction[i]=c.rand(.16,.38));};newRound();
 const strike=i=>{players[i].score--;hit=i;resolved=true;resetAt=c.time+.85;c.sound?.(130,.12,'square');if(players[i].score<=0){c.eliminate(players[i]);c.complete([1-i],'상대에게 다섯 번 적중');}};
 return{update(){c.hint('선택 신호를 기다리세요. 내 차례 A 망치 · 상대 차례 B 방어. 신호 전에 누르면 자신이 맞습니다!');if(resolved&&c.time>=resetAt)newRound();const inputs=players.map((p,i)=>c.input(p,()=>!resolved&&c.time>cueAt+reaction[i]?{[i===attacker?'a':'b']:true}:{}));if(resolved)return;if(c.time<cueAt){const early=inputs.findIndex(q=>q.ap||q.bp);if(early>=0)strike(early);return;}if(!sounded){sounded=true;c.sound?.(720,.12);}const defender=1-attacker;if(inputs[defender].bp)strike(attacker);else if(inputs[attacker].ap)strike(defender);
 },render(){c.arena({width:17,depth:11,color:'#c1ae92'});players.forEach((p,i)=>{text(c,`slam-life-${i}`,'♥'.repeat(Math.max(0,p.score)),p.x,4,0,4,p.color);box(c,`slam-stand-${i}`,p.x,.3,0,2,.5,2,p.color);if(!resolved&&c.time>=cueAt&&attacker===i)text(c,`slam-cue-${i}`,'A !',p.x,6,0,4,GOLD);if(resolved&&hit===i){box(c,`slam-hammer-${i}`,p.x,1.7,0,2.5,.8,1.6,GOLD);box(c,`slam-handle-${i}`,p.x,3.3,0,.25,2.5,.25,'#a78264');}});if(c.time<cueAt&&!resolved)text(c,'slam-wait','대기…',0,6,0,4);}};
}

function mushRush(c){
 const[p]=active(c,1);p.z=3;let supply=3,spawnAt=.4,count=0,kills=0,power=false,ready=0,swing=0,swingSide=0;const raiders=[],total=20;
 return{update(dt){c.hint('A 오른쪽 · B 왼쪽 망치. 파랑은 두 번, 빨강은 돌진! ! 표시 다음 타격은 같은 줄 전체를 밀어냅니다.');if(count<total&&c.time>=spawnAt){const n=count++;raiders.push({id:n,lane:n%2,type:n%3,x:n%2?3:-3,z:-10,hp:n%3===1?2:1,invuln:0,dead:false,switched:false,fake:0});spawnAt=c.time+c.rand(1.2,1.8);}
  const input=c.input(p,()=>{if(c.time<ready)return{};const q=raiders.filter(q=>!q.dead&&q.z>-.7&&q.z<2.1&&c.time>q.invuln).sort((a,b)=>b.z-a.z)[0];return q?{[q.lane?'a':'b']:Math.sin(c.time*18)>.1}:{};});const lane=input.ap?1:input.bp?0:null;
  if(lane!==null&&c.time>=ready){ready=c.time+.3;swing=c.time+.16;swingSide=lane;const q=raiders.filter(q=>!q.dead&&q.lane===lane&&q.z>-.8&&q.z<2.2&&c.time>q.invuln).sort((a,b)=>b.z-a.z)[0];if(q){if(power){raiders.filter(r=>!r.dead&&r.lane===lane).forEach(r=>{r.dead=true;kills++;});power=false;}else{q.hp--;q.invuln=c.time+.32;q.z-=.7;if(q.hp<=0){q.dead=true;kills++;if(kills%4===0)power=true;}}c.sound?.(q.type===1?300:460,.06);}}
  raiders.forEach(q=>{if(q.dead)return;let speed=q.type===1?.95:q.type===2&&q.z>-4?3:1.35;q.z+=speed*dt;if(supply<3&&!q.switched&&q.z>-5){q.switched=true;if(q.id%2===0)q.lane=1-q.lane;else q.fake=c.time+.55;}const target=q.lane?3:-3;q.x+=(target+(c.time<q.fake?(q.lane?-1.4:1.4):0)-q.x)*Math.min(1,dt*8);if(q.z>=2.2){q.dead=true;supply--;c.sound?.(110,.14);if(supply<=0)lose(c,'버섯 세 개를 모두 빼앗겼습니다');}});p.score=kills;if(count===total&&raiders.every(q=>q.dead)&&supply>0)win(c,'버섯을 지키며 모든 침입자를 막았습니다');
 },render(){c.arena({width:12,depth:19,color:'#b9bd95'});[-3,3].forEach((x,i)=>box(c,`mush-lane-${i}`,x,.02,-4,3,.06,15,'#d6ccad'));raiders.forEach(q=>{if(!q.dead){ball(c,`raider-${q.id}`,q.x,.7,q.z,1.2,[GREEN,BLUE,PINK][q.type]);text(c,`raider-health-${q.id}`,q.hp===2?'●●':'●',q.x,2,q.z,1.6);}});for(let i=0;i<supply;i++){ball(c,`mushroom-${i}`,(i-1)*1.7,1.1,5,1.3,PINK);box(c,`mushroom-stem-${i}`,(i-1)*1.7,.4,5,.5,.8,.5,'#e9e4d8');}if(power)text(c,'power-hammer','!',p.x,4,p.z,4,GOLD);if(c.time<swing){box(c,'mush-hammer',swingSide?3:-3,1,1,2,.7,1,GOLD);box(c,'mush-handle',swingSide?1.5:-1.5,1,2,3,.2,.2,'#9e775f');}text(c,'mush-count',`${kills}명 격퇴 · 버섯 ${supply}`,0,2,-12,8);}};
}

function crushedIce(c){
 const[p]=active(c,1,99);p.z=4;const enemies=Array.from({length:12},(_,i)=>({id:i,type:i%3,x:c.rand(-7,7),z:c.rand(-4,3),angle:c.rand(-Math.PI,Math.PI),hp:i%3===2?2:1,invuln:0,dash:0,next:c.rand(2,5),dead:false}));let bump=0;
 return{update(dt){c.hint('방향키로 미끄러지는 쇄빙차 조종. 벽과 기둥은 튕깁니다. 빨강 돌진 중 무적 · 파랑 두 번 · 99초');const q=enemies.filter(q=>!q.dead&&c.time>q.invuln&&c.time>q.dash).sort((a,b)=>dist(p,a)-dist(p,b))[0];const input=c.input(p,()=>q?{x:clamp((q.x-p.x)*1.4-p.vx*.5,-1,1),z:clamp((q.z-p.z)*1.4-p.vz*.5,-1,1)}:{});p.vx=(p.vx+input.x*dt*12)*Math.pow(.96,dt*60);p.vz=(p.vz+input.z*dt*12)*Math.pow(.96,dt*60);p.x+=p.vx*dt;p.z+=p.vz*dt;
  if(Math.abs(p.x)>8){p.x=clamp(p.x,-8,8);p.vx*=-.8;}if(Math.abs(p.z)>5){p.z=clamp(p.z,-5,5);p.vz*=-.8;}[{x:0,z:-3},{x:0,z:3}].forEach(a=>{const d=dist(p,a);if(d<1.3){const nx=(p.x-a.x)/(d||1),nz=(p.z-a.z)/(d||1),v=p.vx*nx+p.vz*nz;p.x=a.x+nx*1.3;p.z=a.z+nz*1.3;if(v<0){p.vx-=1.8*v*nx;p.vz-=1.8*v*nz;}}});
  enemies.forEach(q=>{if(q.dead)return;if(q.type===1&&c.time>q.next){q.angle=Math.atan2(q.z-p.z,q.x-p.x);q.dash=c.time+2;q.next=c.time+c.rand(3.5,5.5);}const speed=c.time<q.dash?6:c.time<q.invuln?2.5:1.1;q.x+=Math.cos(q.angle)*dt*speed;q.z+=Math.sin(q.angle)*dt*speed;if(Math.abs(q.x)>7.8||Math.abs(q.z)>4.8){q.x=clamp(q.x,-7.8,7.8);q.z=clamp(q.z,-4.8,4.8);q.angle+=Math.PI+c.rand(-.7,.7);q.dash=0;}if(c.time>q.invuln&&c.time>q.dash&&c.time>bump&&dist(p,q)<1.2){q.hp--;q.invuln=c.time+1.6;q.angle=Math.atan2(q.z-p.z,q.x-p.x);bump=c.time+.16;c.sound?.(q.hp?300:620,.06);if(q.hp===0){q.dead=true;c.points(p);}}});if(enemies.every(q=>q.dead))win(c,'얼음 위 침입자를 모두 밀어냈습니다');
 },render(){c.arena({width:18,depth:12,color:'#b8dce0'});[{x:0,z:-3},{x:0,z:3}].forEach((q,i)=>c.draw(`ice-pole-${i}`,'cylinder',{x:q.x,y:1.5,z:q.z,sx:1.3,sy:3,sz:1.3,color:'#92b4c8'}));enemies.forEach(q=>{if(!q.dead){ball(c,`skater-${q.id}`,q.x,.65,q.z,1.2,[GREEN,PINK,BLUE][q.type],{opacity:c.time<q.invuln?.45:1});if(c.time<q.dash)text(c,`dash-${q.id}`,'➜',q.x,2,q.z,2,PINK);}});box(c,'ice-crusher',p.x,.4,p.z,1.7,.65,1.7,GOLD);for(let i=0;i<8;i++){const a=i*Math.PI/4;c.draw(`crusher-spike-${i}`,'cone',{x:p.x+Math.cos(a),y:.4,z:p.z+Math.sin(a),sx:.3,sy:.7,sz:.3,rz:Math.PI/2,ry:-a,color:'#6f8598'});}text(c,'ice-score',`${p.score} / 12`,0,2,-7,6);},timeout(){lose(c,'99초 안에 침입자를 모두 밀어내지 못했습니다');}};
}

export const games={
 'Koopa Krunch':koopaKrunch,'Floor It!':floorIt,'Dreadmill':dreadmill,'Stompbot XL':stompbot,'Go-go Pogo':goGoPogo,'Sled Slide':sledSlide,"Flippin' Out":flippinOut,'See Monkey?':seeMonkey,'Outta My Way':outtaMyWay,'Broom Zoom':broomZoom,'Tank-Down':tankDown,'Hammergeddon':hammergeddon,'Stair Scare':stairScare,'Chicken!':chicken,'Chain Saw':chainSaw,'Volleybomb':volleybomb,'Koopa Kurl':koopaKurl,'Slammer':slammer,'Mush Rush':mushRush,'Crushed Ice':crushedIce
};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['advance']]));
export const notes={
 'Koopa Krunch':'1P 솔로 · ←→ 낙하 쌍 이동, ↓ 빠른 낙하, A/B 회전. Shroom City 300점 목표. 같은 색 3개 연결과 빨간 껍질로 초록 껍질 제거를 재현. 6×10 보드·2색 블록 및 제거 한 칸당 10점은 이 재현판의 규격이며 원작 점수 계수는 미확인입니다.',
 'Floor It!':'1P 솔로 · ↑↓ 층 이동, A 오른쪽 문, B 왼쪽 문. 60초부터 시작해 Shroom City 200점 목표. 승객을 같은 종의 층에 운송하며 1/2/3/4명 일괄 하차 10/30/60/100점은 플레이 가이드 기준. 2명 이상 일괄 하차와 시계 승객에 시간 보너스가 있습니다. 일괄 하차 인원당 1초·시계 승객당 4초·운행 간격·대기 이탈 시간은 재현판 조정값입니다.',
 'Dreadmill':'1P 솔로 · 방향키 이동. Shroom City 컨베이어 코스 1회, 60초 안에 도착. 노란 가시의 가로 이동·빨간 가시의 세로 이동과 벨트 속도 변화를 재현합니다. 코스 길이·가시 배치는 새 3D 코스입니다.',
 'Stompbot XL':'1P 솔로 · ←→ 조향, A 가속, B 제동. Shroom City 1개 구간 목표. 바위는 감속, 용암 장애물은 체력 감소, 수리 상자는 회복. 체력이 줄면 최고 속도가 낮아지며 뒤에서 따라오는 용암을 피해야 합니다. 90단위 코스·체력 3·속도 계수는 재현판 조정값입니다.',
 'Go-go Pogo':'1P 솔로 · ←→ 이동, A를 누른 채 착지하면 높은 바운스. 60초 안에 Shroom City 코스 1회. 관 위에서 자동으로 튀며 초록 관의 식물·용암 불덩이·추락을 피합니다. 관 11개와 배치·식물 주기는 새 3D 코스입니다.',
 'Sled Slide':'1P 솔로 · ←→ 조향, A 가속, B 제동. 30초 안에 트랙 한 바퀴. 고속 급회전 시 스핀. 원작 목표를 유지한 타원형 얼음 코스이며 속도·조향·스핀 임계값은 재현판 조정값입니다.',
 "Flippin' Out":'1P 솔로 · 방향키로 도약 방향 선택, A 도약, B 고리 놓기. Shroom City 30초 목표. 파란 고리는 이동, 빨간 고리는 사라집니다. 원작의 그네 회전을 방향 지정 도약으로 바꿨으며 10개 고리 배치는 새 3D 코스입니다.',
 'See Monkey?':'1P 솔로 · ←→ 배 회전, A 가속. Shroom City 목표 50초 안에 친구 10명 구조. 바위 충돌은 잠시 기절합니다. 호수와 바위 배치는 재현판용입니다.',
 'Outta My Way':'1P 솔로 · ←→ 이동, A 점프, B 펀치. Shroom City 60초 코스 1회. 선인장은 펀치·높은 머리 공격, 무거운 돌은 A/B 교대 밀기, 쓰러진 돌은 위에서 밟기로 제거합니다. 장애물 수·밀기 12회는 새 3D 코스 조정값입니다.',
 'Broom Zoom':'1P 솔로 · ←→ 좌우, ↑↓ 높이. Shroom City 5,000점 목표. 고리 연속 통과가 1·2·4·8…로 증가하고 놓치거나 장애물에 닿으면 연속이 끊깁니다. 32개 고리와 장애물 배치는 재현판용 코스입니다.',
 'Tank-Down':'1P 대 2P 결투 · 방향키 이동, A를 눌렀다 놓아 발사. 충전하면 느려지고 최대 3하트 피해. 어둠 속 근거리만 보입니다. 60초 안에 상대를 쓰러뜨리지 못하면 무승부. 최초 5하트·충전 시간·시야 반경은 재현판 조정값으로 원작 초기 하트 수는 미확인입니다.',
 'Hammergeddon':'1P 대 2P 결투 · 방향키 이동, A 점프, B 망치. 이동하며 던지면 전방, 방향을 놓으면 수직으로 던집니다. 자기 망치도 맞으며 하트 3개를 모두 잃으면 패배. 투사체 속도·쿨다운은 재현판 조정값입니다.',
 'Stair Scare':'1P 대 2P 결투 · A 연타로 계단을 오릅니다. 열기구 도착 또는 큰 격차로 승리, 뒤쪽 계단은 붕괴합니다. 목표 100계단·20계단 격차·붕괴 속도는 재현판 조정값입니다.',
 'Chicken!':'1P 대 2P 결투 · A 실제 탈출, B 가짜 탈출. 떨어지는 돌의 그림자를 보고 더 늦게 안전하게 빠져나온 쪽이 승리합니다. 그림자와 낙하 시간은 매 경기 생성됩니다.',
 'Chain Saw':'1P 대 2P 결투 · A/B를 번갈아 누르세요. 너무 빠르면 땀이 나고 잠시 멈춥니다. 상대 위의 돌을 연결한 사슬을 먼저 끊으면 승리. 유효 동작 40회·피로 임계값·휴식 시간은 원작 계수 미확인으로 정한 재현판 조정값입니다.',
 'Volleybomb':'1P 대 2P 결투 · ←→ 이동, A 점프, B 망치로 폭탄 타격. 지상에서는 높게, 공중에서는 강하게 보냅니다. 폭탄을 자기 쪽에 떨어뜨리거나 자기 쪽에서 도화선이 끝나면 하트 감소. 하트 3개·도화선 6–9초·공 궤적은 재현판 조정값입니다.',
 'Koopa Kurl':'1P 대 2P 결투 · ←→ 조준, A 힘 게이지 정지, B 코트 확인(3D판은 항상 코트 전체 표시). 각자 3개씩 2라운드, 껍질끼리 밀기 가능. 과녁 20/30/50/100, 중간 원 20/15/25, 노랑 막대는 해당 라운드 점수 ×2. 득점 구역의 정확한 위치·물리 계수는 재현판 배치입니다.',
 'Slammer':'1P 대 2P 결투 · 자신이 선택되면 A 공격, 상대가 선택되면 B 방어. 신호 전 입력은 자기 피해, 방어는 상대 망치를 반사합니다. 먼저 5회 맞으면 패배. 같은 프레임의 공격·방어는 방어 우선 판정입니다.',
 'Mush Rush':'1P 솔로 · A 오른쪽, B 왼쪽 망치. 버섯 3개를 지키며 모든 침입자 퇴치. 파랑은 2회, 빨강은 돌진하며 버섯이 줄면 차선 변경·속임수가 생깁니다. ! 강화 타격은 같은 줄을 밀어냅니다. 20명·4명 격퇴마다 강화·공격 간격은 재현판 조정값입니다.',
 'Crushed Ice':'1P 솔로 · 방향키로 관성 이동. 99초 안에 모두 퇴치. 벽·기둥 충돌은 반동, 빨강은 돌진 중 무적, 파랑은 2회 적중과 잠깐의 무적. 12명·관성·무적 시간·기둥 배치는 재현판 조정값입니다.'
};
