import {clamp,dist,toward} from '../core.js';
const PINK='#ed91aa',BLUE='#76b9da',GOLD='#ebc362',GREEN='#8abf97';
const box=(c,id,x,y,z,sx,sy,sz,color,more={})=>c.draw(id,'box',{x,y,z,sx,sy,sz,color,...more});
const ball=(c,id,x,y,z,s,color,more={})=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color,...more});
const text=(c,id,label,x=0,y=1,z=0,size=3,color='#294652')=>c.draw(id,'text',{text:String(label),x,y,z,sx:size,sy:size/4,color});
const keys=['a','b','c','d'];
function setup(c,limit=Infinity){c.limit=limit;c.activePlayers=[0,1,2,3];return c.players;}
function high(c,reason){const best=Math.max(...c.players.map(p=>p.score)),w=c.players.filter(p=>p.score===best);c.complete(w.length===4?[]:w.map(p=>p.i),reason);}
function teamHigh(c,reason){const a=c.players[0].score+c.players[1].score,b=c.players[2].score+c.players[3].score;c.complete(a===b?[]:a>b?[0,1]:[2,3],reason);}
function side(c,x=0,y=5,size=25){c.view={size,eye:[x,y+4,28],target:[x,y,0]};}
function angleDiff(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b));}
function circle(c,id,x,z,r,color,y=.05){c.draw(id,'cylinder',{x,y,z,sx:r*2,sy:.06,sz:r*2,color});}
function moveAround(c,p,input,speed,blocks,phase=false){const ox=p.x,oz=p.z;c.move(p,input,speed);if(phase)return;for(const q of blocks){if(Math.abs(p.x-q.x)<q.w/2+.35&&Math.abs(p.z-q.z)<q.d/2+.35){p.x=ox;p.z=oz;if(Math.abs(ox-q.x)>=q.w/2+.35)p.z=clamp(oz+input.z*speed*c.dt,-c.bounds.z,c.bounds.z);else if(Math.abs(oz-q.z)>=q.d/2+.35)p.x=clamp(ox+input.x*speed*c.dt,-c.bounds.x,c.bounds.x);}}}
function makeMaze(c){
 const size=9,step=2.3,walls=new Set();for(let z=1;z<8;z+=2)for(let x=1;x<8;x+=2){walls.add(`${x},${z}`);const options=[[x+1,z],[x,z+1],[x-1,z],[x,z-1]].filter(([a,b])=>a>0&&a<8&&b>0&&b<8);if(options.length){const[a,b]=c.pick(options);walls.add(`${a},${b}`);}}
 const blocks=[...walls].map(key=>{const[x,z]=key.split(',').map(Number);return{x:(x-4)*step,z:(z-4)*step,w:step,d:step};});c.bounds={x:9.9,z:9.9};c.view={size:29,eye:[0,28,21],target:[0,0,0]};
 const cell=p=>[clamp(Math.round(p.x/step)+4,0,8),clamp(Math.round(p.z/step)+4,0,8)];
 const path=(p,target)=>{const start=cell(p),end=cell(target),queue=[start],prev=new Map([[start.join(','),null]]);let found=null;while(queue.length){const a=queue.shift();if(a[0]===end[0]&&a[1]===end[1]){found=a;break;}for(const[dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const b=[a[0]+dx,a[1]+dz],key=b.join(',');if(b[0]<0||b[0]>=size||b[1]<0||b[1]>=size||walls.has(key)||prev.has(key))continue;prev.set(key,a);queue.push(b);}}
  if(!found)return{};let a=found,parent=prev.get(a.join(','));while(parent&&parent.join(',')!==start.join(',')){a=parent;parent=prev.get(a.join(','));}if(a.join(',')===start.join(','))return toward(p,target.x,target.z);const center={x:(start[0]-4)*step,z:(start[1]-4)*step};if(Math.abs(a[0]-start[0])&&Math.abs(p.z-center.z)>.16)return toward(p,center.x,center.z);if(Math.abs(a[1]-start[1])&&Math.abs(p.x-center.x)>.16)return toward(p,center.x,center.z);return toward(p,(a[0]-4)*step,(a[1]-4)*step);
 };
 const clear=(a,b)=>{const n=Math.ceil(dist(a,b)/.25);for(let i=1;i<n;i++){const x=a.x+(b.x-a.x)*i/n,z=a.z+(b.z-a.z)*i/n;if(blocks.some(q=>Math.abs(x-q.x)<q.w/2&&Math.abs(z-q.z)<q.d/2))return false;}return true;};
 const render=(color='#8cb17c')=>{c.arena({width:22,depth:22,color:'#d2c89f'});blocks.forEach((q,i)=>box(c,`maze-${i}`,q.x,.85,q.z,q.w,1.7,q.d,color));};return{blocks,path,clear,render,cell,step,walls};
}

function dress(c){
 const players=setup(c);c.view={size:27,eye:[0,30,23],target:[0,0,0]};players.forEach((p,i)=>{p.x=-8+i%2*16;p.z=i<2?-4:6;p.scale=.6;});let round=0,start=0,nextSwap=0,swap=null;const state=players.map(()=>({cards:[],memory:0,cursor:0,next:0,picked:false,target:0,accuracy:c.rand(.94,.995)}));
 const begin=()=>{round++;start=c.time;nextSwap=start+2;swap=null;state.forEach(s=>{s.cards=[0,1,2,3];s.target=c.int(0,3);s.memory=s.target;s.cursor=0;s.picked=false;});};begin();
 return{update(){const elapsed=c.time-start;c.hint(`머리와 맞는 옷 카드를 기억하고 섞이는 자리를 추적하세요. ←→ 선택 · A 확정 또는 카드 클릭 · ${round}/4 라운드`);
  if(elapsed>=2&&elapsed<5&&c.time>=nextSwap&&!swap){const a=c.int(0,3),b=(a+c.int(1,3))%4;swap={a,b,at:c.time};nextSwap=c.time+.6;}
  if(swap&&c.time-swap.at>=.45){state.forEach((s,i)=>{[s.cards[swap.a],s.cards[swap.b]]=[s.cards[swap.b],s.cards[swap.a]];if(s.memory===swap.a)s.memory=swap.b;else if(s.memory===swap.b)s.memory=swap.a;if(i>=c.humans&&c.rng()>s.accuracy)s.memory=c.int(0,3);});swap=null;}
  players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>elapsed>5.25&&!s.picked?{x:Math.sign(s.memory-s.cursor),a:s.cursor===s.memory}:{});if(elapsed<5||s.picked)return;if(Math.abs(input.x)>.3&&c.time>s.next){s.cursor=clamp(s.cursor+Math.sign(input.x),0,3);s.next=c.time+.15;}const ptr=input.pointer;if(ptr.pressed&&ptr.worldValid&&Math.abs(ptr.worldZ-(i<2?-4:6))<1.2){const j=Math.round((ptr.worldX-(-8+i%2*16-3.6))/2.4);if(j>=0&&j<4){s.cursor=j;s.picked=true;}}if(input.ap)s.picked=true;if(s.picked&&s.cards[s.cursor]===s.target)c.points(p);});
  if(elapsed>=10||elapsed>5&&state.every(s=>s.picked)){if(players.some(p=>p.score>=3)||round===4)high(c,'옷 카드 정답 수');else begin();}
 },render(){const elapsed=c.time-start;players.forEach((p,i)=>{const s=state[i],cx=-8+i%2*16,z=i<2?-4:6;box(c,`dress-board-${i}`,cx,-.2,z,11,.3,7,'#e5ebd4');text(c,`dress-head-${i}`,`참고: ${['● ●','●●●','● ● / ● ●','●'][s.target]}`,cx,1,z-3,7,p.color);s.cards.forEach((v,j)=>{let x=cx-3.6+j*2.4,zz=z;if(swap&&(j===swap.a||j===swap.b)){const f=clamp((c.time-swap.at)/.45,0,1),other=j===swap.a?swap.b:swap.a;x+=((other-j)*2.4)*f;zz+=Math.sin(f*Math.PI)*(j===swap.a?.7:-.7);}const face=elapsed<2||s.picked;box(c,`dress-card-${i}-${j}`,x,.1,zz,2.1,.15,2.3,elapsed>=5&&s.cursor===j?GOLD:face?p.color:'#879ca7');text(c,`dress-pattern-${i}-${j}`,face?['● ●','●●●','● ● / ● ●','●'][v]:'?',x,.3,zz,1.8);});text(c,`dress-points-${i}`,`${p.score}점 ${s.picked?'선택 완료':''}`,cx,1,z+3,5,p.color);});}};
}

function cameraShy(c){
 const players=setup(c,300),maze=makeMaze(c),starts=[[-9,-9],[9,-9],[-9,9],[9,9]];const state=players.map((p,i)=>{[p.x,p.z]=starts[i];return{angle:0,ready:0,stun:0,flash:0,caught:new Set(),wander:{x:0,z:0}};});
 const inFocus=(p,q,s)=>{const d=dist(p,q);return d<4.7&&d>.25&&Math.cos(angleDiff(Math.atan2(q.z-p.z,q.x-p.x),s.angle))>.72&&maze.clear(p,q);};
 return{update(dt){c.hint('방향키 이동 · A 사진. 초록 조준 안에 상대가 들어오면 촬영! 재충전 중에는 기다리고 상대 세 명을 모두 촬영하세요.');const photos=[];players.forEach((p,i)=>{const s=state[i],target=players.filter(q=>q.i!==i&&!s.caught.has(q.i)).sort((a,b)=>dist(p,a)-dist(p,b))[0];const input=c.input(p,()=>{if(!target)return{};const v=maze.path(p,target);return{...v,a:inFocus(p,target,s)&&c.time>s.ready};});if(c.time<s.stun)return;if(Math.hypot(input.x,input.z)>.1)s.angle=Math.atan2(input.z,input.x);moveAround(c,p,input,4.3,maze.blocks);if(input.ap&&c.time>s.ready){s.ready=c.time+2;s.flash=c.time+.45;photos.push(i);c.sound?.(650,.05);}});photos.forEach(i=>{const p=players[i],s=state[i];players.forEach(q=>{if(q.i!==i&&inFocus(p,q,s)){s.caught.add(q.i);state[q.i].stun=c.time+.8;}});p.score=s.caught.size;});const winners=players.filter(p=>state[p.i].caught.size===3);if(winners.length)c.complete(winners.map(p=>p.i),'모든 상대를 촬영');
 },render(){maze.render();players.forEach((p,i)=>{const s=state[i],green=players.some(q=>q.i!==i&&!s.caught.has(q.i)&&inFocus(p,q,s));box(c,`camera-${i}`,p.x+Math.cos(s.angle)*.6,1,p.z+Math.sin(s.angle)*.6,.5,.35,.5,'#596a78');text(c,`camera-score-${i}`,`${p.score}/3`,p.x,3,p.z,2.4,p.color);if(green)circle(c,`focus-${i}`,p.x+Math.cos(s.angle)*2.6,p.z+Math.sin(s.angle)*2.6,1,GREEN);if(c.time<s.flash)ball(c,`flash-${i}`,p.x,1,p.z,2.8,'#ffffd3',{opacity:.5});});},timeout(){c.complete([],'5분 안에 모든 상대를 촬영하지 못했습니다');}};
}

function soccer(c){
 const players=setup(c,30);c.bounds={x:7.5,z:4.5};players.forEach(p=>p.z=2);const balls=[];let next=.4,id=0;const stun=players.map(()=>0);
 return{update(dt){c.hint('방향키 이동 · A 점프. 날아오는 축구공을 피하세요. 상대를 밟으면 잠깐 점프를 막고 마지막 10초에는 공이 휘어집니다.');if(c.time>next){const target=c.pick(players.filter(p=>p.alive));if(target){balls.push({id:id++,startX:c.rand(-7,7),x:0,z:-9,vx:0,target:target.x,kind:c.time>20?c.int(0,3):0,age:0});next=c.time+c.rand(.55,.9);}}
  balls.forEach(q=>{q.age+=dt;q.z+=dt*8;q.x=q.startX+(q.target-q.startX)*Math.min(1,q.age/1.3)+(q.kind===1?Math.sin(q.age*3)*2:q.kind===2?Math.sin(q.age*8)*1.7:0);q.y=q.kind===3?2+Math.sin(q.age*3)*1.3:.45;});
  players.forEach((p,i)=>{const q=balls.filter(q=>q.z<p.z&&p.z-q.z<5).sort((a,b)=>b.z-a.z)[0];const input=c.input(p,()=>({x:q&&Math.abs(q.x-p.x)<1.7?(p.x>q.x?1:-1):Math.abs(p.x)>5?-Math.sign(p.x):0,z:0,a:!!q&&q.kind!==3&&p.z-q.z<2.5&&Math.abs(q.x-p.x)<2}));if(!p.alive)return;c.move(p,input,c.time<stun[i]?1.4:5.3);const old=p.y;if(c.time>stun[i])c.jump(p,input,7.5);else c.jump(p,{},7.5);players.forEach(o=>{if(o!==p&&o.alive&&p.vy<0&&old>o.y+1.4&&p.y<=o.y+1.4&&dist(p,o)<.6){stun[o.i]=c.time+.9;p.vy=6;}});if(balls.some(q=>dist(p,q)<.9&&Math.abs(p.y+.6-q.y)<1))c.eliminate(p);});c.lastStanding();
 },render(){c.arena({width:18,depth:13,color:'#93b889'});box(c,'soccer-goal',0,1.7,6,16,3.4,.2,'#d9e6d0',{opacity:.4});ball(c,'soccer-kicker',0,.8,-10,2,'#b49670');balls.forEach(q=>{if(q.z<9)ball(c,`soccer-ball-${q.id}`,q.x,q.y,q.z,1.1,'#e3e9dd');});},timeout(){c.survivors('30초 동안 축구공 회피');}};
}

function pedal(c){
 const players=setup(c,300),state=players.map(()=>({expected:'a',last:-1,speed:0,spin:0,next:.1,pace:c.rand(.1,.17)}));
 return{update(dt){c.hint('A 왼쪽 페달 · B 오른쪽 페달을 교대로 누르세요. 파란 빙판 코너에서는 천천히 밟아야 회전하지 않습니다.');players.forEach((p,i)=>{const s=state[i],ice=p.score>20&&p.score<35||p.score>65&&p.score<80,input=c.input(p,()=>{if(c.time<s.next)return{};s.next=c.time+(ice?.3:s.pace);return{[s.expected]:true};});const key=input.ap?'a':input.bp?'b':null;if(key===s.expected&&c.time>s.spin){if(ice&&c.time-s.last<.23){s.spin=c.time+1;s.speed=0;}else s.speed=Math.min(9,s.speed+1.3);s.last=c.time;s.expected=key==='a'?'b':'a';}s.speed=Math.max(0,s.speed-dt*1.8);if(c.time>s.spin)p.score+=s.speed*dt;const a=p.score/100*Math.PI*2;p.x=Math.cos(a)*(10+i*.5);p.z=Math.sin(a)*(6+i*.5);p.rotation=-a-Math.PI/2;});const best=Math.max(...players.map(p=>p.score));if(best>=100)c.complete(players.filter(p=>p.score===best).map(p=>p.i),'페달 경주 한 바퀴 완주');
 },render(){c.arena({width:29,depth:22,color:'#c5b691'});circle(c,'toy-infield',0,0,5,'#8bab91');for(let j=0;j<40;j++){const a=j/40*Math.PI*2;box(c,`pedal-track-${j}`,Math.cos(a)*10.7,.05,Math.sin(a)*6.7,2.5,.1,2.5,j>=8&&j<14||j>=26&&j<32?'#99d4e2':'#e3dbc2');}players.forEach((p,i)=>{box(c,`pedal-car-${i}`,p.x,.25,p.z,1.3,.4,1.5,p.color,{ry:p.rotation});text(c,`pedal-meter-${i}`,`${Math.floor(p.score)}%`,p.x,2.4,p.z,2,p.color);});},timeout(){c.complete([],'5분 안에 완주하지 못했습니다');}};
}

function lead(c){
 const players=setup(c,10),counts=[0,0,0,0],rates=players.map(()=>c.rand(5.8,8.2));players.forEach((p,i)=>{p.x=-7+i*4.5;p.z=5;});
 return{update(){c.hint('A를 10초 동안 연타하세요. 한 번 누를 때마다 샤프심 길이가 정확히 0.3 늘어납니다.');players.forEach((p,i)=>{const input=c.input(p,()=>({a:Math.floor(c.time*rates[i]*2)%2===0}));if(input.ap){counts[i]++;p.score=counts[i]*.3;}});},render(){c.arena({width:23,depth:23,color:'#e4e9d5'});players.forEach((p,i)=>{box(c,`pencil-${i}`,p.x,.35,3,.65,.65,4,p.color);const len=p.score*.32;box(c,`lead-${i}`,p.x,.35,1-len/2,.18,.18,Math.max(.01,len),'#535b67');text(c,`lead-length-${i}`,p.score.toFixed(1),p.x,1,6,3,p.color);});},timeout(){high(c,'가장 긴 샤프심');}};
}

function trash(c){
 const players=setup(c,25),objects=Array.from({length:5},()=>({x:c.rand(3.2,7),width:c.rand(.8,2.6)}));const state=players.map((p,i)=>{p.x=-9;p.z=(i-1.5)*3;p.y=5;return{cursor:i,rope:null,next:0,released:false,done:false,landed:false,vx:4.5,vy:0,target:i};});
 const select=(s)=>{if(!state.some(o=>o!==s&&o.rope===s.cursor))s.rope=s.cursor;};
 return{update(dt){c.hint(c.time<5?'5초 안에 빈 밧줄 선택: ←→ · A 확정. 발판 크기는 출발 후 공개됩니다.':'A를 눌러 밧줄을 놓으세요. 앞으로 움직이는 관성을 읽고 쓰레기 발판 위에 착지!');players.forEach((p,i)=>{const s=state[i],q=objects[s.rope??s.cursor];const input=c.input(p,()=>{if(c.time<5){if(s.rope!==null)return{};if(state.some(o=>o!==s&&o.rope===s.cursor)){s.target=(s.cursor+1)%5;return{x:1};}return{a:c.time>.3+i*.1};}const landingX=p.x+s.vx*Math.sqrt(Math.max(0,2*(p.y-.75)/18));return{a:!s.released&&landingX>=q.x-.08};});if(c.time<5){if(s.rope===null&&Math.abs(input.x)>.3&&c.time>s.next){s.cursor=(s.cursor+5+Math.sign(input.x))%5;s.next=c.time+.15;}if(input.ap&&s.rope===null)select(s);p.z=((s.rope??s.cursor)-2)*3;return;}
  if(s.rope===null){s.cursor=Array.from({length:5},(_,n)=>n).find(n=>!state.some(o=>o.rope===n));select(s);}p.z=(s.rope-2)*3;if(s.done)return;if(input.ap)s.released=true;p.x+=s.vx*dt;if(s.released){const old=p.y;s.vy-=18*dt;p.y+=s.vy*dt;if(old>=.75&&p.y<=.75){s.done=true;s.landed=Math.abs(p.x-q.x)<q.width/2;p.y=s.landed?.75:0;p.score=s.landed?1:0;if(!s.landed)c.eliminate(p);}}if(p.x>12){s.done=true;c.eliminate(p);}});if(state.every(s=>s.done))c.complete(players.filter(p=>state[p.i].landed).map(p=>p.i),'안전 착지 성공');
 },render(){c.arena({width:27,depth:20,color:'#aaa591'});for(let i=0;i<5;i++){box(c,`rope-${i}`,0,6,(i-2)*3,24,.08,.08,'#ab8660');if(c.time>=5){const q=objects[i];box(c,`landing-object-${i}`,q.x,.35,(i-2)*3,q.width,.75,2,[PINK,BLUE,GOLD,GREEN,'#9b8aba'][i]);}else text(c,`rope-label-${i}`,`밧줄 ${i+1}`,0,6,(i-2)*3,3);}players.forEach((p,i)=>{if(!state[i].released&&c.time>=5)box(c,`rope-grip-${i}`,p.x,5.6,p.z,.08,1.2,.08,'#b89b73');});},timeout(){c.complete(players.filter(p=>state[p.i].landed).map(p=>p.i),'착지 종료');}};
}

function whomp(c){
 const players=setup(c,30),holes=[];let next=.7,cycle=null,id=0;
 const rect=(edge,along)=>edge<2?{x:along,z:edge===0?-2.7:2.7,w:3.5,d:8.5}:{x:edge===2?-3.8:3.8,z:along,w:9.5,d:3.2};
 const inside=(p,q)=>Math.abs(p.x-q.x)<q.w/2+.25&&Math.abs(p.z-q.z)<q.d/2+.25;
 return{update(dt){c.hint('방향키 이동. 돌이 흔들리면 쓰러질 자리에서 벗어나세요. 여러 돌이 흔들릴 때는 먼저 흔들린 돌이 공격합니다.');if(c.time>=next){const edge=c.int(0,3),along=edge<2?c.rand(-4,4):c.rand(-2,2);cycle={edge,along,at:c.time,rect:rect(edge,along),fake:c.time>10?(edge+2)%4:null,hit:false,id:id++};next=c.time+c.rand(2,2.6);}
  players.forEach(p=>{const input=c.input(p,()=>{if(!cycle||cycle.hit)return{};const r=cycle.rect;if(inside(p,r)){const options=[{x:-7,z:-4},{x:7,z:-4},{x:-7,z:4},{x:7,z:4}].filter(q=>!inside(q,r)).sort((a,b)=>dist(p,a)-dist(p,b));return options[0]?toward(p,options[0].x,options[0].z):{};}return{};});const old={x:p.x,z:p.z};c.move(p,input,5.5);if(holes.some(q=>dist(p,q)<.85)){p.x=old.x;p.z=old.z;}});
  if(cycle&&!cycle.hit&&c.time-cycle.at>.8){cycle.hit=true;players.forEach(p=>{if(p.alive&&inside(p,cycle.rect)){holes.push({x:p.x,z:p.z});c.eliminate(p);}});c.sound?.(100,.12);c.lastStanding();}
 },render(){c.arena({width:19,depth:13,color:'#d9c49a'});holes.forEach((q,i)=>circle(c,`sand-hole-${i}`,q.x,q.z,.8,'#695f57'));for(let edge=0;edge<4;edge++){const selected=cycle&&cycle.edge===edge,warning=selected&&c.time-cycle.at<.8,fake=cycle?.fake===edge&&c.time-cycle.at>.2&&c.time-cycle.at<.8,along=selected?cycle.along:Math.sin(c.time+edge)*2;const x=edge<2?along:edge===2?-9:9,z=edge<2?edge===0?-6:6:along;if(selected&&cycle.hit&&c.time-cycle.at<1.4){const q=cycle.rect;box(c,`whomp-${edge}`,q.x,.2,q.z,q.w,.4,q.d,'#8797a0');}else{box(c,`whomp-${edge}`,x+(warning||fake?Math.sin(c.time*50)*.15:0),2,z,edge<2?3.5:1.2,4,edge<2?1.2:3.2,'#8797a0');if(warning||fake)text(c,`whomp-warning-${edge}`,'!',x,5,z,3,PINK);}}},timeout(){c.survivors('돌 낙하에서 30초 생존');}};
}

function twist(c){
 const players=setup(c,300),state=players.map(()=>({fuel:0,wound:0,lastAngle:null,progress:0,stun:0,pace:c.rand(7,9)}));const obstacles=Array.from({length:21},(_,i)=>({x:(i%3-1)*4,z:-8-i*4.1,type:i%3}));players.forEach(p=>p.z=2);
 return{update(dt){c.hint('태엽 표시가 나오면 원을 시계 방향으로 돌리세요: 1P 원 안에서 드래그, 키보드는 방향키 원형 회전. 주행 중 ←→ 조향.');players.forEach((p,i)=>{const s=state[i],winding=s.fuel<=0,q=obstacles.find(q=>q.z<p.z&&p.z-q.z<5);const input=c.input(p,()=>winding?{x:Math.cos(c.time*s.pace),z:Math.sin(c.time*s.pace)}:{x:q&&Math.abs(q.x-p.x)<1.8?p.x<q.x?-1:1:Math.abs(p.x)>6?-Math.sign(p.x):0});if(winding){let a=null;const ptr=input.pointer;if(ptr.down&&ptr.worldValid&&Math.hypot(ptr.worldX-p.x,ptr.worldZ-(p.z-2))<2)a=Math.atan2(ptr.worldZ-(p.z-2),ptr.worldX-p.x);else if(Math.hypot(input.x,input.z)>.4)a=Math.atan2(input.z,input.x);if(a!==null&&s.lastAngle!==null){const delta=angleDiff(a,s.lastAngle);if(delta>0&&delta<2)s.wound+=delta;}s.lastAngle=a;if(s.wound>=Math.PI*4){s.fuel=1;s.wound=0;s.lastAngle=null;}}else{p.x=clamp(p.x+input.x*dt*5,-7.2,7.2);const speed=c.time<s.stun?1.2:7;p.z-=speed*dt;s.fuel=Math.max(0,s.fuel-dt*.05);if(c.time>s.stun&&obstacles.some(q=>dist(p,q)<1.3)){s.stun=c.time+.75;s.fuel=Math.max(0,s.fuel-.25);}}p.score=Math.max(0,-p.z);});const arrived=players.filter(p=>p.z<-100);if(arrived.length)c.complete(arrived.map(p=>p.i),'태엽 자동차 결승점');const z=players.reduce((s,p)=>s+p.z,0)/4;c.view={size:25,eye:[0,23,z+18],target:[0,0,z-7]};
 },render(){box(c,'windup-road',0,-.3,-49,18,.6,108,'#b1a588');obstacles.forEach((q,i)=>q.type===0?c.draw(`tool-${i}`,'cylinder',{x:q.x,y:.3,z:q.z,sx:2.1,sy:.6,sz:2.1,color:'#8d9ba0'}):box(c,`tool-${i}`,q.x,.2,q.z,2.6,.5,1.2,'#a48d75'));players.forEach((p,i)=>{const s=state[i];box(c,`windup-car-${i}`,p.x,.3,p.z,1.4,.5,2,p.color);if(s.fuel<=0){c.draw(`crank-${i}`,'ring',{x:p.x,y:.08,z:p.z-2,sx:3,sy:3,sz:1,rx:-Math.PI/2,color:p.color});text(c,`windup-hint-${i}`,`↻ ${Math.floor(s.wound/Math.PI/4*100)}%`,p.x,1,p.z-2,3);}else text(c,`windup-fuel-${i}`,`${Math.ceil(s.fuel*100)}%`,p.x,2.5,p.z,2,p.color);});},timeout(){c.complete([],'제한 시간 안에 완주하지 못했습니다');}};
}

function crater(c){
 const players=setup(c,30);side(c,0,5,26);players.forEach((p,i)=>{p.x=-5+i*3.3;p.y=3+i*.15;p.z=0;});let next=.5,id=0;const eruptions=[];
 return{update(dt){c.hint('방향키로 화산 벽을 이동하고 A를 연타해 상대를 넘어가세요. 끓어오르는 자리가 곧 용암 기둥이 됩니다!');if(c.time>next){eruptions.push({id:id++,x:c.rand(-7,7),at:c.time,delay:Math.max(.38,.9-c.time*.012),hit:false});next=c.time+Math.max(.5,1.2-c.time*.025);}
  players.forEach(p=>{const danger=eruptions.find(q=>!q.hit&&Math.abs(q.x-p.x)<1.7),input=c.input(p,()=>({x:danger?p.x<danger.x?-1:1:0,z:Math.abs(p.y-5)>1?Math.sign(p.y-5):0,a:Math.sin(c.time*13+p.i)>.3}));if(!p.alive)return;const old=p.x;p.x=clamp(p.x+input.x*dt*5.5,-7.5,7.5);p.y=clamp(p.y-input.z*dt*2,2,7);const other=players.find(q=>q!==p&&q.alive&&Math.abs(q.x-p.x)<.8&&Math.abs(q.y-p.y)<1.2);if(other){if(input.ap)p.y=clamp(p.y+.4,2,8.2);else p.x=old;}p.score=c.time;});eruptions.forEach(q=>{if(!q.hit&&c.time-q.at>q.delay){q.hit=true;players.forEach(p=>{if(p.alive&&Math.abs(p.x-q.x)<1.05)c.eliminate(p);});}});c.lastStanding();
 },render(){box(c,'volcano-wall',0,5,-1,20,15,1.4,'#92766e');box(c,'crater-lava',0,-.5,1,20,1,4,'#e68b5e',{glow:true});eruptions.forEach(q=>{const age=c.time-q.at;if(age<q.delay)ball(c,`bubble-${q.id}`,q.x,.3,0,.4+age*1.1,GOLD);else if(age<q.delay+.5)box(c,`eruption-${q.id}`,q.x,5,0,1.8,10,1.3,'#f1ad59',{glow:true});});},timeout(){c.survivors('화산에서 30초 동안 생존');}};
}

function booTag(c){
 const players=setup(c,30),blocks=[{x:-3,z:0,w:2,d:5},{x:3,z:0,w:2,d:5},{x:0,z:3.5,w:2,d:1.5},{x:0,z:-3.5,w:2,d:1.5}];let possessed=new Set([c.int(0,3)]),added=false;const cool=[0,0,0,0];
 return{update(dt){c.hint('방향키 이동. 유령이 붙었으면 다른 선수에게 닿아 넘기세요. 유령이 붙은 선수는 보물을 통과하며 붙어 있던 총 시간이 짧으면 승리!');if(c.time>=20&&!added){added=true;possessed.add(c.pick(players.filter(p=>!possessed.has(p.i))).i);}
  players.forEach(p=>{const tagged=possessed.has(p.i),targets=players.filter(q=>q!==p&&possessed.has(q.i)!==tagged),target=targets.sort((a,b)=>dist(p,a)-dist(p,b))[0];const input=c.input(p,()=>{if(!target)return{};let v=tagged?toward(p,target.x,target.z):toward(target,p.x,p.z);if(!tagged){for(const b of blocks){if(Math.abs(p.x-b.x)<b.w/2+1.4&&Math.abs(p.z-b.z)<b.d/2+1.4){v.x+=(p.x-b.x)*.5;v.z+=(p.z-b.z)*.4;}}if(Math.abs(p.x)>7)v.x-=Math.sign(p.x);if(Math.abs(p.z)>4)v.z-=Math.sign(p.z);}return v;});moveAround(c,p,input,tagged?5.1:5.3,blocks,tagged);if(tagged)p.score+=dt;});
  for(const i of [...possessed]){const q=players.find(p=>!possessed.has(p.i)&&dist(players[i],p)<.85&&c.time>cool[p.i]&&c.time>cool[i]);if(q){possessed.delete(i);possessed.add(q.i);cool[i]=cool[q.i]=c.time+.8;}}
 },render(){c.arena({width:19,depth:13,color:'#998d7c'});blocks.forEach((q,i)=>box(c,`treasure-${i}`,q.x,.7,q.z,q.w,1.4,q.d,i%2?GOLD:'#90b69f'));players.forEach(p=>{text(c,`boo-time-${p.i}`,p.score.toFixed(1)+'초',p.x,3,p.z,2.6,p.color);if(possessed.has(p.i))ball(c,`tag-ghost-${p.i}`,p.x,2,p.z+.6,1.3,'#e7eee7',{opacity:.8});});},timeout(){const best=Math.min(...players.map(p=>p.score));c.complete(players.filter(p=>Math.abs(p.score-best)<.001).map(p=>p.i),'유령이 붙었던 시간 최소');}};
}

function dust(c){
 const players=setup(c,300);players.forEach(p=>p.z=0);let vacuum=8;const obstacles=Array.from({length:35},(_,i)=>({id:i,x:c.rand(-6.5,6.5),z:-6-i*2.2,type:i%4}));obstacles.push({id:35,x:0,z:-86,type:4});const stun=[0,0,0,0];
 return{update(dt){c.hint('방향키 이동 · A 점프. 먼지는 느려지고 점프 불가, 단추·공은 기절, 리본·필름은 청소기 쪽으로 끌려갑니다.');vacuum-=dt*5;players.forEach(p=>{const near=obstacles.filter(q=>q.z<p.z&&p.z-q.z<5&&Math.abs(q.x-p.x)<2).sort((a,b)=>b.z-a.z)[0];const input=c.input(p,()=>({x:near&&near.type!==4?p.x<near.x?-1:1:Math.abs(p.x)>5.7?-Math.sign(p.x):0,z:-1,a:!!near&&(near.type===1||near.type===2)&&p.z-near.z<2.4}));if(!p.alive)return;const contacts=obstacles.filter(q=>Math.abs(p.x-q.x)<(q.type===4?8:1.1)&&Math.abs(p.z-q.z)<1.1&&p.y<.6),fluff=contacts.some(q=>q.type===0),pull=contacts.some(q=>q.type>=3);c.move(p,input,c.time<stun[p.i]?0:fluff?2:6,false);p.x=clamp(p.x,-7.2,7.2);c.jump(p,fluff?{}:input,7.5);if(pull)p.z+=dt*5;if(c.time>stun[p.i]&&contacts.some(q=>q.type===1||q.type===2)){stun[p.i]=c.time+.8;p.z+=1.1;}if(p.z>vacuum)c.eliminate(p);p.score=-p.z;});const arrived=players.filter(p=>p.alive&&p.z<-95);if(arrived.length)c.complete(arrived.map(p=>p.i),'청소기를 피해 결승점 도착');else c.lastStanding();const live=players.filter(p=>p.alive),z=live.length?live.reduce((s,p)=>s+p.z,0)/live.length:vacuum;c.view={size:25,eye:[0,24,z+17],target:[0,0,z-6]};
 },render(){box(c,'dust-hall',0,-.3,-45,18,.6,110,'#b4a48a');box(c,'vacuum-mouth',0,1.2,vacuum+1,18,2.5,3,'#6d8290');obstacles.forEach(q=>{if(q.type===0)ball(c,`dust-${q.id}`,q.x,.25,q.z,2,'#bcb8a8');else if(q.type===1)circle(c,`button-${q.id}`,q.x,q.z,1,PINK,.2);else if(q.type===2)ball(c,`ball-${q.id}`,q.x,.7,q.z,1.6,BLUE);else box(c,`pulling-${q.id}`,q.x,.02,q.z,q.type===4?16:2.1,.07,2.1,q.type===4?'#e1d6b8':'#86948e');});box(c,'dust-finish',0,.1,-95,18,.1,.5,GOLD);},timeout(){c.complete([],'결승점에 도착하지 못했습니다');}};
}

function cyber(c){
 const players=setup(c,300),rows=26,cols=5,tiles=[];let route=2;for(let r=0;r<rows;r++){if(r>6)route=clamp(route+c.int(-1,1),0,4);for(let x=0;x<cols;x++){const safe=r<7||r===rows-1||x===route||c.rng()<(r<14?.72:.5);tiles.push({r,x,safe,color:r===0||r===7||r===14||r===25?3:c.int(0,r<14?1:2),wx:(x-2)*2.1,z:-r*2.1});}}const memory=players.map(()=>new Set()),state=players.map(()=>({row:1,target:null,wait:0}));players.forEach((p,i)=>{p.x=(i-1.5)*2;p.z=0;});const visible=q=>q.color===3||Math.floor(c.time*1.6)%4===q.color;
 return{update(dt){c.hint('방향키 이동 · A 점프. 색이 켜질 때 발판을 기억하세요. 검은 시간에는 구멍과 길이 구분되지 않습니다.');players.forEach((p,i)=>{const s=state[i],current=Math.max(0,Math.round(-p.z/2.1));tiles.forEach(q=>{if(q.safe&&visible(q)&&Math.abs(q.r-current)<6)memory[i].add(`${q.r},${q.x}`);});const input=c.input(p,()=>{if(s.target&&dist(p,s.target)<.15){s.row++;s.target=null;}if(!s.target){const candidates=tiles.filter(q=>q.r===s.row&&q.safe&&memory[i].has(`${q.r},${q.x}`)&&Math.abs(q.wx-p.x)<3).sort((a,b)=>Math.abs(a.wx-p.x)-Math.abs(b.wx-p.x));if(candidates.length)s.target={x:candidates[0].wx,z:candidates[0].z};}if(!s.target)return{};return{...toward(p,s.target.x,s.target.z),a:Math.abs(s.target.x-p.x)>.5&&p.y===0&&Math.sin(c.time*9+i)>.4};});if(!p.alive)return;c.move(p,input,4.7,false);c.jump(p,input,7.5);const r=Math.round(-p.z/2.1),x=Math.round(p.x/2.1)+2,q=tiles.find(q=>q.r===r&&q.x===x);if(p.y===0&&(!q?.safe||Math.abs(p.x)>5.2))c.eliminate(p);p.score=Math.max(0,-p.z);});const arrived=players.filter(p=>p.alive&&p.z<=-52.2);if(arrived.length)c.complete(arrived.map(p=>p.i),'마지막 파란 발판 도착');else c.lastStanding();const alive=players.filter(p=>p.alive),z=alive.length?Math.min(...alive.map(p=>p.z)):0;c.view={size:24,eye:[0,22,z+18],target:[0,0,z-7]};
 },render(){tiles.forEach((q,i)=>{const on=visible(q);if(!on||q.safe)box(c,`cyber-tile-${i}`,q.wx,-.1,q.z,2.03,.2,2.03,on?[GREEN,PINK,GOLD,BLUE][q.color]:'#202b3c');});},timeout(){c.complete([],'제한 시간 안에 완주하지 못했습니다');}};
}

function raft(c){
 const players=setup(c,300),state=players.map((p,i)=>{p.x=11+i*.45;p.z=-i*.9;return{angle:Math.PI/2,speed:0,progress:0,last:Math.atan2(p.z/7,p.x/11),boost:0,hurt:0};});const buoys=Array.from({length:8},(_,i)=>({x:Math.cos(i*Math.PI/4+.2)*11,z:Math.sin(i*Math.PI/4+.2)*7}));
 return{update(dt){c.hint('←→ 조향 · A 가속 · B 제동. 부표와 다른 뗏목은 튕김, 노란 경사로는 잠깐 가속합니다.');players.forEach((p,i)=>{const s=state[i],theta=Math.atan2(p.z/7,p.x/11),target={x:Math.cos(theta+.5)*11,z:Math.sin(theta+.5)*7};let delta=angleDiff(Math.atan2(target.z-p.z,target.x-p.x),s.angle);const input=c.input(p,()=>({x:clamp(delta*2,-1,1),a:true,b:Math.abs(delta)>1.1}));s.speed=clamp(s.speed+dt*(input.a?3:-2)-(input.b?dt*7:0),0,c.time<s.boost?12:7.5);s.angle+=input.x*dt*2.1;p.x+=Math.cos(s.angle)*s.speed*dt;p.z+=Math.sin(s.angle)*s.speed*dt;p.rotation=-s.angle;
  const radius=Math.hypot(p.x/11,p.z/7);if(radius<.67||radius>1.3){p.x*=clamp(radius,.68,1.29)/radius;p.z*=clamp(radius,.68,1.29)/radius;s.speed*=.85;s.angle+=.15;}
  if(c.time>s.hurt){const q=buoys.find(q=>dist(p,q)<1);if(q){const v=toward(q,p.x,p.z);p.x+=v.x*.8;p.z+=v.z*.8;s.speed*=.4;s.hurt=c.time+.8;}for(const o of players){if(o.i>i&&dist(p,o)<1.1){const v=toward(o,p.x,p.z);p.x+=v.x*.5;p.z+=v.z*.5;o.x-=v.x*.5;o.z-=v.z*.5;s.speed*=.75;state[o.i].speed*=.75;s.hurt=state[o.i].hurt=c.time+.5;}}}
  if(Math.abs(p.x)<2&&(Math.abs(p.z-7)<1.2||Math.abs(p.z+7)<1.2))s.boost=c.time+1.4;const a=Math.atan2(p.z/7,p.x/11);s.progress+=angleDiff(a,s.last);s.last=a;p.score=Math.max(0,s.progress/Math.PI/2*100);});const top=Math.max(...players.map(p=>p.score));if(top>=100){const winners=players.filter(p=>p.score===top);c.complete(winners.length===4?[]:winners.map(p=>p.i),'뗏목 경주 한 바퀴 완주');}
 },render(){c.arena({width:32,depth:23,color:'#72b8c6'});circle(c,'raft-island',0,0,4.5,'#c4bb8b');buoys.forEach((q,i)=>ball(c,`buoy-${i}`,q.x,.65,q.z,1.2,PINK));[-7,7].forEach((z,i)=>box(c,`ramp-${i}`,0,.1,z,3,.3,2,GOLD,{rz:i?.1:-.1}));players.forEach((p,i)=>{box(c,`raft-${i}`,p.x,.15,p.z,1.4,.3,1.9,p.color,{ry:-state[i].angle});text(c,`raft-progress-${i}`,`${Math.floor(p.score)}%`,p.x,2.5,p.z,2,p.color);});},timeout(){c.complete([],'5분 안에 완주하지 못했습니다');}};
}

function geared(c){
 const players=setup(c,300);side(c,0,6,24);const platforms=[{id:0,x:0,y:0,w:17,type:0,level:0}];for(let n=1;n<=15;n++)for(let j=0;j<2;j++)platforms.push({id:platforms.length,x:j?3:-3,y:n*1.4,w:3.8,type:n%4,level:n});const state=players.map(()=>({ground:0,level:0,delay:c.rand(0,.25)}));players.forEach((p,i)=>{p.x=i%2?3:-3;p.z=(i<2?-.2:.2);p.vy=0;});
 const where=q=>({x:q.x+(q.type===1?Math.sin(c.time*1.7+q.id)*.7:q.type===2?Math.cos(c.time*1.3+q.id)*.5:0),y:q.y+(q.type===2?Math.sin(c.time*1.3+q.id)*.2:0),on:q.type!==3||(c.time+q.id*.2)%4<3});
 return{update(dt){c.hint('←→ 이동 · A 점프. 움직이고 회전하고 들어가는 시계 발판을 밟아 정상에 도착하세요. 상대를 밟아 방해할 수 있습니다.');players.forEach((p,i)=>{const s=state[i],next=platforms.filter(q=>q.level===Math.min(15,s.level+1)).sort((a,b)=>Math.abs(where(a).x-p.x)-Math.abs(where(b).x-p.x))[0];const target=next?where(next):null;const input=c.input(p,()=>target?{x:clamp((target.x-p.x)*2,-1,1),a:s.ground!==null&&target.on&&Math.abs(target.x-p.x)<2&&Math.sin(c.time*7+s.delay)>.1}:{});p.x=clamp(p.x+input.x*dt*5.2,-8,8);if(s.ground!==null){const q=platforms[s.ground],a=where(q);if(!a.on||Math.abs(p.x-a.x)>q.w/2){s.ground=null;p.vy=0;}else{p.y=a.y;if(input.ap){p.vy=8.2;s.ground=null;p.y+=.01;}}}if(s.ground===null){const old=p.y;p.vy-=18*dt;p.y+=p.vy*dt;if(p.vy<0)for(const q of platforms){const a=where(q);if(a.on&&old>=a.y&&p.y<=a.y&&Math.abs(p.x-a.x)<q.w/2){p.y=a.y;p.vy=0;s.ground=q.id;s.level=q.level;break;}}if(p.y<0){p.y=0;p.vy=0;s.ground=0;s.level=0;}}p.score=Math.max(p.score,p.y);});players.forEach(p=>players.forEach(q=>{if(p.i<q.i&&Math.abs(p.x-q.x)<.65&&p.vy<0&&p.y>q.y+1&&p.y<q.y+1.5){q.vy=-3;state[q.i].ground=null;p.vy=6;}}));const arrived=players.filter(p=>state[p.i].level===15);if(arrived.length)c.complete(arrived.map(p=>p.i),'시계 꼭대기 도착');side(c,0,Math.max(5,Math.max(...players.map(p=>p.y))),25);
 },render(){box(c,'clock-back',0,12,-1.5,21,28,1,'#ab997d');platforms.forEach(q=>{const a=where(q);if(a.on){box(c,`gear-platform-${q.id}`,a.x,a.y-.15,0,q.w,.3,1.4,q.type===3?PINK:q.type===2?GOLD:'#9faeb1');if(q.type===2)c.draw(`gear-${q.id}`,'cylinder',{x:a.x,y:a.y-.8,z:-.3,sx:2.2,sy:.4,sz:2.2,rx:Math.PI/2,color:'#738b96'});}});text(c,'clock-goal','GOAL',0,24,0,6,GOLD);},timeout(){c.complete([],'5분 안에 정상에 도착하지 못했습니다');}};
}

function washer(c){
 const players=setup(c,30);c.bounds={x:8,z:8};players[0].x=9;players[0].z=6;players.slice(1).forEach((p,i)=>{p.x=Math.cos(i*Math.PI*2/3)*3;p.z=Math.sin(i*Math.PI*2/3)*3;});let angle=0;
 return{update(dt){c.hint('1P: ←→ 분사기 회전 또는 원 안에서 드래그. 2–4P: 이동·A 점프. 후반에는 두 번째 물줄기가 켜집니다.');const team=players.slice(1),target=team.filter(p=>p.alive).sort((a,b)=>Math.hypot(b.x,b.z)-Math.hypot(a.x,a.z))[0];const input=c.input(players[0],()=>target?{x:clamp(angleDiff(Math.atan2(target.z,target.x),angle)*2,-1,1)}:{});if(input.pointer.down&&input.pointer.worldValid)angle=Math.atan2(input.pointer.worldZ,input.pointer.worldX);else angle+=input.x*dt*2.8;const jets=[angle,...(c.time>=20?[angle+Math.PI/2]:[])];team.forEach(p=>{const input=c.input(p,()=>{let x=-p.x*.1,z=-p.z*.1,near=false;jets.forEach(a=>{const side=-p.x*Math.sin(a)+p.z*Math.cos(a);if(Math.abs(side)<1.6){const s=side>=0?1:-1;x-=Math.sin(a)*s;z+=Math.cos(a)*s;near=true;}});return{x,z,a:near&&p.y===0};});if(!p.alive)return;c.move(p,input,4.5,false);c.jump(p,input,7.5);jets.forEach(a=>{if(Math.abs(-p.x*Math.sin(a)+p.z*Math.cos(a))<.7&&p.y<1.3){p.x+=Math.cos(a)*dt*10;p.z+=Math.sin(a)*dt*10;}});if(Math.hypot(p.x,p.z)>6)c.eliminate(p);});if(team.every(p=>!p.alive))c.complete([0],'물줄기로 세 상대를 모두 밀어냈습니다');
 },render(){circle(c,'plate-stack',0,0,6.2,'#e0e6d5');c.draw('plate-rim','ring',{x:0,y:.06,z:0,sx:12.3,sy:12.3,sz:1,rx:-Math.PI/2,color:BLUE});[angle,...(c.time>=20?[angle+Math.PI/2]:[])].forEach((a,i)=>{box(c,`water-${i}`,0,.9,0,15,.35,.6,'#81c7e6',{ry:-a,opacity:.6});ball(c,`nozzle-${i}`,-Math.cos(a)*7,.9,-Math.sin(a)*7,1,'#8298a4');});},timeout(){c.complete([1,2,3],'팀이 30초 동안 버텼습니다');}};
}

function trackStar(c){
 const players=setup(c);let round=0,start=0,phase='choose',pair=['b','c'];const state=players.map(()=>({choice:0,progress:0,pace:0,picked:false}));
 const begin=()=>{round++;start=c.time;phase='choose';pair=c.shuffle(keys).slice(0,2);state.forEach(s=>{s.choice=c.int(0,1);s.progress=0;s.pace=c.rand(5,7.6);s.picked=false;});};begin();
 return{update(dt){const elapsed=c.time-start;c.hint(phase==='choose'?`${round}/3 갈림길 · ← 또는 →로 비밀 선택, 3초 뒤 공개`:`1P A 연타 · 같은 길의 주자 ${pair.map(k=>k.toUpperCase()).join('+')} 동시 연타 · 5초 추격`);players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>phase==='choose'?{x:s.choice?1:-1}:i===0?{a:Math.floor(c.time*s.pace*2)%2===0}:Object.fromEntries(pair.map(k=>[k,Math.floor(c.time*s.pace*2)%2===0])));if(!p.alive)return;if(phase==='choose'){if(Math.abs(input.x)>.3){s.choice=input.x>0?1:0;s.picked=true;}p.x=(i-1.5)*3;p.z=i===0?4:0;}else{const matched=i===0||s.choice===state[0].choice;if(matched){s.progress+=dt*(i===0?1.8:1.6);const stroke=i===0?input.ap:input[pair[0]]&&input[pair[1]]&&(input[pair[0]+'p']||input[pair[1]+'p']);if(stroke)s.progress+=i===0?.35:.32;}p.x=(s.choice?4:-4)+(i===0?0:(i-2)*.65);p.z=-s.progress+(i===0?3:0);p.score=round-1;}});
  if(phase==='choose'&&elapsed>=3){phase='chase';start=c.time;}else if(phase==='chase'){players.slice(1).forEach(p=>{if(p.alive&&state[p.i].choice===state[0].choice&&state[0].progress>=state[p.i].progress+3)c.eliminate(p);});if(players.slice(1).every(p=>!p.alive))c.complete([0],'열차로 세 주자를 모두 잡았습니다');else if(elapsed>=5){if(round===3)c.complete([1,2,3],'세 갈림길에서 팀 생존');else begin();}}
 },render(){c.arena({width:19,depth:28,color:'#abbb9c'});[-4,4].forEach((x,i)=>{box(c,`rail-${i}`,x,.03,-4,2,.1,22,'#887765');for(let n=0;n<10;n++)box(c,`tie-${i}-${n}`,x,.08,5-n*2,2.8,.1,.2,'#c1ac87');});box(c,'toy-train',players[0].x,.5,players[0].z,2,1,3,PINK);if(phase==='choose')text(c,'secret-fork','←  갈림길  →',0,4,-6,8);else players.slice(1).forEach(p=>{if(p.alive&&state[p.i].choice!==state[0].choice)box(c,`safe-cart-${p.i}`,p.x,.25,p.z,1.3,.4,1.8,p.color);});}};
}

function flashDash(c){
 const players=setup(c,30),maze=makeMaze(c);const starts=[[-9,0],[9,-9],[9,0],[9,9]],angles=[0,0,0,0];players.forEach((p,i)=>{[p.x,p.z]=starts[i];if(maze.blocks.some(b=>Math.abs(p.x-b.x)<b.w/2&&Math.abs(p.z-b.z)<b.d/2))p.x=-9;});let escape={x:9,z:9},nextEscape=0;
 return{update(){c.hint('방향키 이동. 1P는 도망, 2–4P는 손전등을 비추며 추격합니다. 머리 위 경고등이 많을수록 상대가 가깝습니다.');if(c.time>nextEscape){const corners=[{x:-9,z:-9},{x:9,z:-9},{x:-9,z:9},{x:9,z:9}];escape=corners.sort((a,b)=>Math.min(...players.slice(1).map(p=>dist(p,b)))-Math.min(...players.slice(1).map(p=>dist(p,a))))[0];nextEscape=c.time+2;}
  players.forEach((p,i)=>{const input=c.input(p,()=>maze.path(p,i===0?escape:players[0]));if(Math.hypot(input.x,input.z)>.1)angles[i]=Math.atan2(input.z,input.x);moveAround(c,p,input,i===0?4.5:3.9,maze.blocks);});players.slice(1).forEach(p=>{const a=angles[p.i],d=dist(p,players[0]);if(d<3&&Math.cos(angleDiff(Math.atan2(players[0].z-p.z,players[0].x-p.x),a))>.8&&maze.clear(p,players[0]))c.complete([1,2,3],'도망자를 손전등으로 포착');});
 },render(){maze.render('#7b91a4');players.forEach((p,i)=>{const d=i===0?Math.min(...players.slice(1).map(q=>dist(p,q))):dist(p,players[0]),n=clamp(5-Math.floor(d/3),1,5);text(c,`alarm-${i}`,'●'.repeat(n),p.x,3,p.z,3,i===0?PINK:GOLD);if(i>0)box(c,`torch-${i}`,p.x+Math.cos(angles[i])*1.3,.4,p.z+Math.sin(angles[i])*1.3,2.8,.25,.9,GOLD,{ry:-angles[i],opacity:.35});});},timeout(){c.complete([0],'손전등을 피해 30초 생존');}};
}

function cubes(c){
 const players=setup(c,300),teams=[{stage:0,blocks:[],press:[-10,-10]},{stage:0,blocks:[],press:[-10,-10]}],state=players.map(()=>({power:false,frozen:0,next:0,opened:false,face:-Math.PI/2}));c.view={size:28,eye:[0,24,20],target:[0,0,-3]};
 const center=t=>t?6:-6,world=(t,col,row)=>({x:center(t)+(col-2)*1.5,z:4-row*1.5});
 const begin=t=>{const team=teams[t];team.blocks=[];for(let col=0;col<5;col++)team.blocks.push({col,row:2,hp:2,kind:'white',id:`${t}-${team.stage}-white-${col}`});for(const col of[0,2,4])team.blocks.push({col,row:4,hp:1,kind:'ice',id:`${t}-${team.stage}-ice-${col}`});[1,3].forEach((col,j)=>team.blocks.push({col,row:1,hp:1,kind:'?',prize:(j+team.stage)%2?'freeze':'star',id:`${t}-${team.stage}-question-${col}`}));for(let j=0;j<2;j++){const p=players[t*2+j],q=world(t,j?3:1,0);p.x=q.x;p.z=q.z;Object.assign(state[p.i],{power:false,frozen:0,opened:false});}team.press=[-10,-10];};begin(0);begin(1);
 return{update(dt){c.hint('방향키 이동 · A 펀치. ? 상자에는 별 또는 얼음 함정. 별로 흰 얼음을 두 번 치고 동료를 구한 뒤 출구 버튼 두 개를 함께 누르세요.');players.forEach((p,i)=>{const t=Math.floor(i/2),j=i%2,team=teams[t],s=state[i],partner=players[t*2+1-j],ps=state[partner.i],ownCol=j?3:1;const input=c.input(p,()=>{if(s.frozen)return{a:Math.sin(c.time*18+i)>.1};let target;if(!s.opened)target=world(t,ownCol,1);else{const powered=s.power?j:ps.power?1-j:j,corridor=powered?3:1;if(p.z>1.2&&Math.abs(p.x-world(t,corridor,0).x)>.3)target={x:world(t,corridor,0).x,z:p.z};else if(p.z>-.5)target=world(t,corridor,3);else target=world(t,ownCol,6);}return{...toward(p,target.x,target.z),a:Math.sin(c.time*14+i*.1)>.1};});if(s.frozen){if(input.ap&&--s.frozen<=0)s.frozen=0;return;}if(Math.hypot(input.x,input.z)>.1)s.face=Math.atan2(input.z,input.x);const ox=p.x,oz=p.z;c.move(p,input,4,false);p.x=clamp(p.x,center(t)-3.6,center(t)+3.6);p.z=clamp(p.z,-5.5,4.5);if(team.blocks.some(b=>b.hp>0&&dist(p,world(t,b.col,b.row))<1.05)){p.x=ox;p.z=oz;}
  if(input.ap&&c.time>s.next){s.next=c.time+.2;if(ps.frozen&&dist(p,partner)<1.8)ps.frozen=0;const b=team.blocks.filter(b=>b.hp>0&&dist(p,world(t,b.col,b.row))<1.9).sort((a,b)=>dist(p,world(t,a.col,a.row))-dist(p,world(t,b.col,b.row)))[0];if(b){if(b.kind==='?'){b.hp=0;s.opened=true;if(b.prize==='star')s.power=true;else s.frozen=8;}else if(b.kind!=='white'||s.power)b.hp--;}
   const button=world(t,ownCol,6);if(dist(p,button)<.9)team.press[j]=c.time;}
  if(s.opened===false&&!team.blocks.some(b=>b.kind==='?'&&b.col===ownCol&&b.hp>0))s.opened=true;
 });teams.forEach((team,t)=>{if(team.press.every(at=>c.time-at<.55)){team.stage++;players.slice(t*2,t*2+2).forEach(p=>p.score=team.stage);if(team.stage<3)begin(t);}});const finished=teams.map((t,i)=>t.stage===3?i:null).filter(i=>i!==null);if(finished.length)c.complete(finished.length===2?[]:finished.flatMap(t=>[t*2,t*2+1]),'세 얼음 방 탈출');
 },render(){teams.forEach((team,t)=>{box(c,`ice-room-${t}`,center(t),-.2,-.5,8.5,.4,12,'#bfdee0');team.blocks.forEach(b=>{if(b.hp>0){const q=world(t,b.col,b.row);box(c,b.id,q.x,.7,q.z,1.3,1.4,1.3,b.kind==='?'?GOLD:b.kind==='white'?'#e5eeec':BLUE);if(b.kind==='?')text(c,b.id+'-q','?',q.x,1.7,q.z,2);}});[1,3].forEach((col,j)=>{const q=world(t,col,6);circle(c,`exit-button-${t}-${j}`,q.x,q.z,.6,PINK);});text(c,`cube-stage-${t}`,`${team.stage+1} / 3`,center(t),1,-7,5);});players.forEach((p,i)=>{if(state[i].frozen)box(c,`frozen-${i}`,p.x,.8,p.z,1.5,2,1.5,BLUE,{opacity:.55});if(state[i].power)text(c,`star-${i}`,'★',p.x,3,p.z,2.5,GOLD);});},timeout(){c.complete([],'얼음 미로에서 제한 시간 초과');}};
}

function mole(c){
 const players=setup(c),teams=[{x:0,y:3,caught:false},{x:0,y:3,caught:false}],taps=players.map(()=>[]),rates=players.map(()=>c.rand(5,6.6)),rocks=Array.from({length:12},(_,i)=>({x:9+i*5,y:1.5+(i%3)*2}));side(c,12,5,30);
 return{update(dt){c.hint('각자 A 연타. 위쪽 선수가 빠르면 위로, 아래쪽 선수가 빠르면 아래로 파고 갑니다. 바위를 피하며 뒤쫓는 두더지보다 앞서세요.');players.forEach((p,i)=>{const t=Math.floor(i/2),team=teams[t],rock=rocks.find(q=>q.x>team.x&&q.x-team.x<6),desired=rock?(rock.y<3?5:1):3,upper=i%2===0,rate=Math.abs(desired-team.y)<.5?rates[i]:(desired>team.y===upper?8:2.8);const input=c.input(p,()=>({a:Math.floor(c.time*rate*2)%2===0}));if(input.ap)taps[i].push(c.time);taps[i]=taps[i].filter(at=>c.time-at<.75);});teams.forEach((team,t)=>{if(team.caught)return;const upper=taps[t*2].length/.75,lower=taps[t*2+1].length/.75,blocked=rocks.some(q=>Math.hypot(team.x-q.x,team.y-q.y)<1.3);team.y=clamp(team.y+(upper-lower)*dt*.55,.6,6.3);team.x+=dt*(.7+(upper+lower)*.4)*(blocked?.2:1);if(team.x<-5+c.time*3.5)team.caught=true;players.slice(t*2,t*2+2).forEach((p,j)=>{p.x=team.x;p.y=team.y+t*8+(j===0?.55:-.55);p.z=0;p.score=team.x;});});if(teams.some(t=>t.x>=72)){const best=Math.max(...teams.map(t=>t.x));const w=teams.map((q,i)=>q.x===best?i:null).filter(i=>i!==null);c.complete(w.length===2?[]:[w[0]*2,w[0]*2+1],'땅굴 출구에 먼저 도착');}else if(teams.some(t=>t.caught)){const live=teams.map((q,i)=>q.caught?null:i).filter(i=>i!==null);c.complete(live.length?[live[0]*2,live[0]*2+1]:[],'두더지 추격 종료');}side(c,Math.max(...teams.map(t=>t.x))+8,8,31);
 },render(){teams.forEach((team,t)=>{box(c,`tunnel-${t}`,team.x+7,3+t*8,-.8,42,7.4,.3,'#baa080');rocks.forEach((q,i)=>ball(c,`dig-rock-${t}-${i}`,q.x,q.y+t*8,0,2,'#8b9392'));ball(c,`chasing-mole-${t}`,-5+c.time*3.5,team.y+t*8,0,2.4,'#987451');});}};
}

function bookIt(c){
 const players=setup(c),teams=[{lifts:0,step:0,actor:0,next:0},{lifts:0,step:0,actor:0,next:0}],pace=players.map(()=>c.rand(.13,.2));side(c,0,6,26);
 return{update(){c.hint('불이 켜진 선수가 A→B→C→D 순서 두 바퀴를 입력하면 파트너 차례! 서로 번갈아 들어 올려 책 더미 정상으로 가세요.');players.forEach((p,i)=>{const t=Math.floor(i/2),team=teams[t],actor=t*2+team.actor,k=keys[team.step%4],input=c.input(p,()=>{if(i!==actor||c.time<team.next)return{};team.next=c.time+pace[i];return{[k]:true};});if(i===actor){const pressed=keys.find(k=>input[k+'p']);if(pressed===k){team.step++;if(team.step===8){team.step=0;team.actor=1-team.actor;team.lifts++;}}}p.x=t?5:-5;p.y=team.lifts*.85+(i===actor?0:1.5);p.z=i%2*.5;p.score=team.lifts;});players.forEach(p=>p.score=teams[Math.floor(p.i/2)].lifts);const done=teams.map((t,i)=>t.lifts>=12?i:null).filter(i=>i!==null);if(done.length)c.complete(done.length===2?[]:done.flatMap(t=>[t*2,t*2+1]),'서로 들어 올려 책 더미 정상 도착');side(c,0,Math.max(5,Math.max(...teams.map(t=>t.lifts*.85))),26);
 },render(){teams.forEach((t,i)=>{for(let n=0;n<12;n++)box(c,`book-stack-${i}-${n}`,i?5:-5,n*.85-.25,-1,6,.65,2,[PINK,BLUE,GOLD,GREEN][n%4]);text(c,`book-prompt-${i}`,`${i*2+t.actor+1}P: ${keys[t.step%4].toUpperCase()} (${Math.floor(t.step/4)+1}/2)`,i?5:-5,t.lifts*.85+4,1,8,c.players[i*2+t.actor].color);});}};
}

export const games={
 'Dress for Success':dress,'Camera Shy':cameraShy,'Soccer Survival':soccer,'Pedal Pushers':pedal,'Get the Lead Out':lead,'Trash Landing':trash,'Whomp-a-thon':whomp,'Twist and Route':twist,'Crater Crawl':crater,'Boo Tag':booTag,'Dust Buddies':dust,'Cyber Scamper':cyber,'Raft Riot':raft,'All Geared Up':geared,'Power Washer':washer,'Track Star':trackStar,'Flash and Dash':flashDash,'Cube Crushers':cubes,'Mole Thrill':mole,'Book It!':bookIt
};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['ds']]));
export const notes={
 'Dress for Success':'4인 · 옷 카드의 단추 무늬를 기억하고 뒷면 섞기를 추적. ←→ 선택·A 확정, 1P는 카드 클릭 가능. 라운드별 답변 5초, 3점 선취 또는 4라운드 점수 비교. 원작 인물의 비슷한 가짜 옷을 플라밍고 단추 무늬로 바꿨습니다.',
 'Camera Shy':'4인 버전 · 방향키 이동·A 촬영. 초록 조준 표시가 있을 때 촬영하면 상대가 잠깐 기절. 상대 3명 전원 촬영 선착순, 5분 무승부. 미로·재충전 2초·촬영 거리·각도는 재현판 수치. 개인 DS 화면은 공유 3D 화면으로 표시합니다.',
 'Soccer Survival':'4인 버전 · 방향키 이동·A 점프. 상대 머리를 밟으면 기절시켜 점프를 잠깐 방해. 마지막 10초에 곡선·지그재그·높은 공이 추가됩니다. 최후 생존 또는 30초 생존, 전원 동시 탈락은 무승부.',
 'Pedal Pushers':'4인 버전 · A 왼쪽 페달, B 오른쪽 페달 교대. 원작 왼쪽 방향키/오른쪽 얼굴 버튼을 A/B로 분리했습니다. 빙판에서 너무 빨리 밟으면 스핀. 한 바퀴 선착순·5분 무승부, 코스와 가속·스핀 계수는 재현판 조정값입니다.',
 'Get the Lead Out':'4인 버전 · A 연타, 10초. 원작대로 입력 1회당 샤프심 길이 0.3 증가. 최고 길이 승리, 전원 같은 길이는 무승부. 원작 표시 단위는 지역별 표기가 달라도 숫자가 같습니다.',
 'Trash Landing':'4인 버전 · 최초 5초 ←→로 밧줄 선택·A 확정, 다른 선수 밧줄 선택 불가. 출발 뒤 A로 놓기. 물체는 출발 후 공개되며 안전하게 착지한 모두 승리. 밧줄 속도·낙하·물체 폭은 재현판 조정값입니다.',
 'Whomp-a-thon':'4인 버전 · 방향키 이동. 먼저 흔들린 돌이 쓰러집니다. 후반에는 가짜 경고도 추가되며 눌린 자리는 이동을 막는 구멍이 됩니다. 최후 생존 또는 30초 생존. 낙하 간격·범위는 재현판 조정값입니다.',
 'Twist and Route':'4인 버전 · 정지해 태엽 표시가 나올 때 방향키를 시계 방향으로 원형 회전. 1P는 원형 태엽 안에서 실제 원 드래그 가능. 주행 중 ←→ 조향. 원작처럼 멈췄을 때만 감으며 장애물은 동력을 줄입니다. 두 바퀴 감기·연료·100단위 코스는 재현판 조정값입니다.',
 'Crater Crawl':'4인 버전 · 방향키 이동, A 연타로 앞을 막는 선수를 넘어감. 끓는 위치에서 용암 기둥이 솟습니다. 최후 생존 또는 30초 생존. 벽 높이·전조·분출 배치는 재현판용입니다.',
 'Boo Tag':'4인 · 방향키 이동. 유령이 붙으면 장애물을 통과하며 접촉으로 상대에게 넘깁니다. 20초에 두 번째 유령 등장. 30초 동안 붙었던 누적 시간이 가장 짧으면 승리. 유령 전달 보호시간·장애물 배치는 재현판 조정값입니다.',
 'Dust Buddies':'4인 버전 · 방향키 이동·A 점프. 먼지 감속·점프 차단, 단추/공 기절, 필름/리본/마지막 봉투의 뒤쪽 끌림을 구현. 결승점 도착 또는 최후 생존. 무작위 장애물과 95단위 복도는 재현판 코스입니다.',
 'Cyber Scamper':'4인 버전 · 방향키 이동·A 점프. 불빛이 켜질 때 안전 타일을 기억. 초반 구멍 없음→중간 구멍→후반 3색 순환. 마지막 파란 타일 또는 최후 생존. 5×26 경로·점등 주기는 재현판 규격입니다.',
 'Raft Riot':'4인 버전 · ←→ 조향·A 가속·B 제동. 경사로 가속, 부표/뗏목 충돌 반동. 한 바퀴 선착순·5분 무승부. 트랙 모양·속도·충돌 계수는 재현판 조정값입니다.',
 'All Geared Up':'4인 버전 · ←→ 이동·A 점프. 이동·회전·출입 발판과 상대 밟기를 구현. 정상 선착순·5분 무승부. 원작 시계 내부를 15층 두 경로의 새 3D 코스로 구성했습니다.',
 'Power Washer':'1 대 3 · 1P ←→ 분사기 회전 또는 포인터 드래그, 2–4P 방향 이동·A 점프. 20초에 두 번째 물줄기. 30초 안에 모두 떨어뜨리면 1P, 한 명이라도 남으면 팀 승리. 분사 힘·접촉 폭·접시 크기는 재현판 조정값입니다.',
 'Track Star':'1 대 3 · 갈림길 3초 동안 ←/→로 비밀 선택. 공개 후 같은 길에서 5초 추격: 1P A 연타, 주자 표시된 두 버튼 동시 연타. 세 라운드 동안 모두 잡으면 1P, 생존자가 있으면 팀 승리. 추격 속도 계수는 재현판 조정값입니다.',
 'Flash and Dash':'1 대 3 · 전원 방향키 이동. 1P는 도망, 2–4P는 이동 방향 손전등으로 추격. 경고등은 거리 표시. 30초 생존하면 1P, 빛 포착은 팀 승리. 미로·속도·빛 범위는 재현판 조정값이며 개인 화면은 공유 화면으로 바꿨습니다.',
 'Cube Crushers':'2 대 2, 팀 1·2P / 3·4P · 방향키 이동·A 펀치. 별로 흰 얼음 2회 파괴, ? 함정에 얼면 동료 펀치 또는 A 연타 8회 탈출. 두 출구 버튼을 0.55초 안에 함께 누르면 다음 방. 3개 방 선착순. 함정 배치·연타 횟수·동시 판정 폭은 재현판 조정값입니다.',
 'Mole Thrill':'2 대 2, 팀 1·2P / 3·4P · 각자 A 연타. 앞 번호는 위쪽, 뒤 번호는 아래쪽 땅파기. 연타 속도 차이로 상하 조향, 바위는 감속, 두더지에 잡히면 팀 패배. 먼저 출구에 닿으면 승리. 경로·속도·72단위 길이는 재현판 수치입니다.',
 'Book It!':'2 대 2, 팀 1·2P / 3·4P · 현재 차례 선수만 A→B→C→D 두 바퀴, 이어 파트너 차례. 원작의 네 버튼 순서를 앱의 A/B/C/D로 치환했습니다. 정상을 먼저 오르면 승리. 12회 교대와 책 높이는 재현판 수치입니다.'
};
