import{clamp,dist,toward}from'../core.js';
const PINK='#ed91aa',BLUE='#76b9da',GOLD='#ebc362',GREEN='#8abf97';
const box=(c,id,x,y,z,sx,sy,sz,color,more={})=>c.draw(id,'box',{x,y,z,sx,sy,sz,color,...more});
const ball=(c,id,x,y,z,s,color,more={})=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color,...more});
const text=(c,id,label,x=0,y=1,z=0,size=3,color='#294652')=>c.draw(id,'text',{text:String(label),x,y,z,sx:size,sy:size/4,color});
const layouts=[{x:-6,z:-5},{x:6,z:-5},{x:-6,z:5},{x:6,z:5}],keys=['a','b','c','d'];
function setup(c,limit=Infinity){c.limit=limit;c.activePlayers=[0,1,2,3];return c.players;}
function high(c,reason){const top=Math.max(...c.players.map(p=>p.score)),w=c.players.filter(p=>p.score===top);c.complete(w.length===4?[]:w.map(p=>p.i),reason);}
function boards(c){c.view={size:28,eye:[0,30,24],target:[0,0,0]};c.players.forEach((p,i)=>{p.x=layouts[i].x;p.z=layouts[i].z+3.8;p.scale=.6;});}
function board(c,i,label){const a=layouts[i];box(c,`board-${i}`,a.x,-.2,a.z,11,.3,8.5,'#e7edd8');text(c,`board-title-${i}`,label,a.x,.5,a.z-3.6,7,c.players[i].color);}
function cursor(c,p,g){c.draw(`cursor-${p.i}`,'ring',{x:g.x,y:.1,z:g.z,sx:.6,sy:.6,sz:1,rx:-Math.PI/2,color:p.color});}
function gesture(c,p,s,input,center={x:0,z:0},rx=8,rz=5){const ptr=input.pointer;let down;if(ptr.worldValid){s.cx=ptr.worldX;s.cz=ptr.worldZ;down=ptr.down;}else{s.cx=clamp((s.cx??center.x)+input.x*c.dt*7,center.x-rx,center.x+rx);s.cz=clamp((s.cz??center.z)+input.z*c.dt*7,center.z-rz,center.z+rz);down=input.a;}const g={x:s.cx,z:s.cz,down,pressed:down&&!s.gDown,released:!down&&!!s.gDown,dx:down&&s.gDown?s.cx-s.gX:0,dz:down&&s.gDown?s.cz-s.gZ:0};s.gDown=down;s.gX=s.cx;s.gZ=s.cz;return g;}
const angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function rotateInput(s,input,center){let a=null;const q=input.pointer;if(q.down&&q.worldValid&&Math.hypot(q.worldX-center.x,q.worldZ-center.z)>.3)a=Math.atan2(q.worldZ-center.z,q.worldX-center.x);else if(Math.hypot(input.x,input.z)>.4)a=Math.atan2(input.z,input.x);let delta=0;if(a!==null&&s.lastAngle!==undefined&&s.lastAngle!==null){const d=angleDiff(a,s.lastAngle);if(Math.abs(d)<2)delta=d;}s.lastAngle=a;return delta;}
function side(c,x=0,y=5,size=25){c.view={size,eye:[x,y+4,28],target:[x,y,0]};}

function claimingCube(c){
 const players=setup(c,30),faces=[{n:[0,1,0],u:[1,0,0],v:[0,0,1]},{n:[1,0,0],u:[0,0,-1],v:[0,1,0]},{n:[0,-1,0],u:[1,0,0],v:[0,0,-1]},{n:[-1,0,0],u:[0,0,1],v:[0,1,0]},{n:[0,0,1],u:[1,0,0],v:[0,1,0]},{n:[0,0,-1],u:[-1,0,0],v:[0,1,0]}],panels=Array.from({length:24},(_,i)=>({white:i%2===0,owner:null})),state=players.map((p,i)=>({face:i===2?4:i,u:-2,v:-2,h:0,vy:0,pound:false}));let next=.5;
 const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),sum=(...terms)=>[0,1,2].map(i=>terms.reduce((s,[a,k])=>s+a[i]*k,0));
 return{update(dt){c.hint('방향키로 정육면체의 여섯 면 이동 · A 점프 후 A/B로 찍기. 흰 패널만 득점! 아래 여섯 면 지도에서 위치를 확인하세요.');if(c.time>next){for(let n=0;n<3;n++)panels[c.int(0,23)].white=true;next=c.time+c.rand(.55,.9);}players.forEach((p,i)=>{const s=state[i],face=faces[s.face],input=c.input(p,()=>{const options=panels.map((q,j)=>({...q,j})).filter(q=>q.white&&Math.floor(q.j/4)===s.face),target=options.sort((a,b)=>Math.hypot((a.j%2?2:-2)-s.u,((Math.floor(a.j/2)%2)?2:-2)-s.v)-Math.hypot((b.j%2?2:-2)-s.u,((Math.floor(b.j/2)%2)?2:-2)-s.v))[0];if(!target)return{x:1,z:0};const u=target.j%2?2:-2,v=Math.floor(target.j/2)%2?2:-2;return{x:clamp((u-s.u)*2,-1,1),z:clamp((v-s.v)*2,-1,1),a:s.h===0&&Math.hypot(u-s.u,v-s.v)<.5,b:s.h>.7};});s.u+=input.x*dt*3.7;s.v+=input.z*dt*3.7;for(let n=0;n<2;n++){const f=faces[s.face],axis=Math.abs(s.u)>4?'u':Math.abs(s.v)>4?'v':null;if(!axis)break;const value=s[axis],sign=Math.sign(value),normal=f[axis].map(x=>x*sign),other=axis==='u'?'v':'u',world=sum([f.n,4-(Math.abs(value)-4)],[normal,4],[f[other],s[other]]);s.face=faces.findIndex(q=>dot(q.n,normal)>.99);s.u=dot(world,faces[s.face].u);s.v=dot(world,faces[s.face].v);}if(input.ap&&s.h===0){s.vy=7.5;s.h=.001;s.pound=false;}if((input.ap||input.bp)&&s.h>.3){s.vy=-18;s.pound=true;}if(s.h>0){s.vy-=18*dt;s.h+=s.vy*dt;if(s.h<=0){s.h=0;if(s.pound){const index=s.face*4+(s.u>=0?1:0)+(s.v>=0?2:0),q=panels[index];if(q.white){q.white=false;q.owner=i;c.points(p);}}}}const f=faces[s.face],q=sum([f.n,4+s.h],[f.u,s.u],[f.v,s.v]);p.x=q[0];p.y=q[1]+6;p.z=q[2];p.normal=f.n;p.scale=.6;});c.view={size:30,eye:[19,22,25],target:[0,4,3]};
 },render(){box(c,'space-cube',0,6,0,8,8,8,'#8292a0');faces.forEach((f,fi)=>{for(let j=0;j<4;j++){const q=panels[fi*4+j],u=j%2?2:-2,v=j>=2?2:-2,w=sum([f.n,4.025],[f.u,u],[f.v,v]),color=q.white?'#f5f3dc':q.owner===null?'#71959f':players[q.owner].color;box(c,`cube-panel-${fi}-${j}`,w[0],w[1]+6,w[2],f.n[0]!==0?.05:3.92,f.n[1]!==0?.05:3.92,f.n[2]!==0?.05:3.92,color,{glow:q.white});const mx=(fi%3-1)*5,mz=fi<3?8:12;box(c,`cube-map-${fi}-${j}`,mx+(j%2?.9:-.9),.01,mz+(j>=2?.9:-.9),1.7,.1,1.7,color);}});players.forEach((p,i)=>{const s=state[i],x=(s.face%3-1)*5+s.u*.4,z=(s.face<3?8:12)+s.v*.4;ball(c,`cube-marker-${i}`,x,.5,z,.55,p.color);text(c,`cube-marker-id-${i}`,i+1,x,1,z,1.3);});},timeout(){high(c,'30초 흰 패널 득점');}};
}

function ropeSlope(c){
 const players=setup(c),state=players.map(()=>({progress:0,jump:0,stun:0,hit:new Set(),pace:c.rand(.05,.2)})),bushes=Array.from({length:16},(_,i)=>7+i*4.2);players.forEach((p,i)=>{p.x=(i-1.5)*4;p.z=0;p.y=15;});
 return{update(dt){c.hint('A로 벽에서 뛰어 나와 관목을 넘으세요. 줄을 타고 자동으로 내려가며 부딪히면 잠시 지체됩니다.');players.forEach((p,i)=>{const s=state[i],next=bushes.find(y=>y>s.progress),input=c.input(p,()=>({a:!!next&&next-s.progress<1.8+s.pace&&s.jump===0}));if(input.ap&&s.jump===0)s.jump=.001;if(s.jump>0){s.jump+=dt;if(s.jump>.85)s.jump=0;}const away=s.jump?Math.sin(s.jump/.85*Math.PI)*2.5:0;s.progress+=dt*(c.time<s.stun?.4:4.2);bushes.forEach((y,j)=>{if(!s.hit.has(j)&&Math.abs(y-s.progress)<.6&&away<1.4){s.hit.add(j);s.stun=c.time+1;}});p.y=15-s.progress;p.z=away;p.score=s.progress;});const best=Math.max(...players.map(p=>p.score));if(best>=75)c.complete(players.filter(p=>p.score===best).map(p=>p.i),'줄을 타고 절벽 바닥에 먼저 도착');side(c,0,15-Math.max(...players.map(p=>p.score))-3,29);
 },render(){const y=players.reduce((sum,p)=>sum+p.y,0)/4;box(c,'rappel-wall',0,y,-1.3,21,100,1.5,'#a48d75');players.forEach((p,i)=>{box(c,`rappel-rope-${i}`,p.x,y,0,.08,90,.08,'#cfb88d');bushes.forEach((b,j)=>ball(c,`rappel-bush-${i}-${j}`,p.x,15-b,.4,2,GREEN,{sy:1,sz:1.3}));});}};
}

function carpet(c){
 const players=setup(c,60),W=9,H=7,safe=new Set(Array.from({length:W*H},(_,i)=>i)),mouths=[],stun=[0,0,0,0];let next=.7,id=0;const cell=(x,z)=>{const xx=Math.floor((x+9)/2),zz=Math.floor((z+7)/2);return xx<0||xx>=W||zz<0||zz>=H?-1:zz*W+xx;};players.forEach(p=>p.z=0);c.bounds={x:8.5,z:6.5};
 return{update(dt){c.hint('방향키 이동 · A 점프. 입이 카펫을 먹으며 구멍을 만듭니다. 닿으면 튕기고 잠시 기절하니 안전한 발판을 남겨 두세요.');if(c.time>next){const horizontal=id%2===0,side=id%4<2?1:-1;mouths.push({id:id++,x:horizontal?-10*side:c.int(-4,4)*2,z:horizontal?c.int(-3,3)*2:-8*side,vx:horizontal?side*2.3:0,vz:horizontal?0:side*2.3,eaten:new Set()});next=c.time+Math.max(2.5,5.5-c.time*.05);}mouths.forEach(q=>{q.x+=q.vx*dt;q.z+=q.vz*dt;const n=cell(q.x,q.z);if(n>=0&&!q.eaten.has(n)){q.eaten.add(n);safe.delete(n);}});
  players.forEach((p,i)=>{const input=c.input(p,()=>{const candidates=[...safe].map(n=>({x:(n%W-4)*2,z:(Math.floor(n/W)-3)*2})).filter(q=>dist(p,q)<5).sort((a,b)=>{const score=q=>Math.min(8,...mouths.map(m=>dist(q,m)))-dist(p,q)*.35;return score(b)-score(a);});const q=candidates[0];if(!q)return{a:true};const v=toward(p,q.x,q.z),future=cell(p.x+v.x,p.z+v.z);return{...v,a:(!safe.has(future)||mouths.some(q=>dist(p,q)<2))&&p.y===0};});if(!p.alive)return;c.move(p,input,c.time<stun[i]?1.3:5.5);c.jump(p,input,7.7);const m=mouths.find(q=>dist(p,q)<1&&p.y<1);if(m&&c.time>stun[i]){p.x+=m.vx*.5;p.z+=m.vz*.5;stun[i]=c.time+.6;}if(p.y===0&&!safe.has(cell(p.x,p.z)))c.eliminate(p);});c.lastStanding();
 },render(){for(const n of safe)box(c,`carpet-${n}`,(n%W-4)*2,-.1,(Math.floor(n/W)-3)*2,1.97,.2,1.97,n%2?PINK:'#d8a2ab');mouths.forEach(q=>{if(Math.abs(q.x)<12&&Math.abs(q.z)<10){ball(c,`mouth-${q.id}`,q.x,.3,q.z,1.4,'#55516d');box(c,`mouth-teeth-${q.id}`,q.x,.5,q.z+.35,1,.3,.6,'#e7e7cf');}});},timeout(){c.survivors('카펫 위에서 60초 생존');}};
}

function colorFast(c){
 const players=setup(c,60);boards(c);const W=18,H=14,size=.38,state=players.map((p,i)=>({page:0,painted:new Set(),cx:layouts[i].x,cz:layouts[i].z,botX:layouts[i].x,botZ:layouts[i].z,last:null,pace:c.rand(5.8,8)}));
 const mask=(page,x,z)=>{if(page%3===0)return Math.hypot((x-8.5)/1.1,z-7)<4.7||(Math.hypot(x-6.5,z-4)<2.2)||(Math.hypot(x-10.5,z-4)<2.2);if(page%3===1)return Math.hypot(x-8,z-6)<5.8&&Math.hypot(x-5.5,z-3.8)>5;return[[6,4],[9,3],[12,4],[7.5,7],[10.5,7],[9,10]].some(([a,b])=>Math.hypot(x-a,z-b)<2);};
 const world=(i,x,z)=>({x:layouts[i].x+(x-8.5)*size,z:layouts[i].z+(z-6.5)*size});
 return{update(dt){c.hint('과일 안을 모두 색칠하세요! 1P 드래그 / A를 누른 채 방향키로 붓 이동. 일반 경기 세 페이지 선착순.');players.forEach((p,i)=>{const s=state[i],cells=[];for(let z=0;z<H;z++)for(let x=0;x<W;x++)if(mask(s.page,x,z))cells.push({x,z,key:z*W+x});const input=c.input(p,()=>{const q=cells.filter(q=>!s.painted.has(q.key)).sort((a,b)=>dist({x:s.botX,z:s.botZ},world(i,a.x,a.z))-dist({x:s.botX,z:s.botZ},world(i,b.x,b.z)))[0];if(!q)return{};const target=world(i,q.x,q.z),v=toward({x:s.botX,z:s.botZ},target.x,target.z);s.botX+=v.x*Math.min(dist({x:s.botX,z:s.botZ},target),dt*s.pace);s.botZ+=v.z*Math.min(dist({x:s.botX,z:s.botZ},target),dt*s.pace);return{pointer:{valid:true,worldValid:true,down:true,worldX:s.botX,worldZ:s.botZ}};});const g=gesture(c,p,s,input,layouts[i],4.5,2.8);if(g.down){const old=s.last??g,n=Math.max(1,Math.ceil(dist(old,g)/.15));for(let j=0;j<=n;j++){const q={x:old.x+(g.x-old.x)*j/n,z:old.z+(g.z-old.z)*j/n};cells.forEach(cell=>{if(dist(q,world(i,cell.x,cell.z))<.48)s.painted.add(cell.key);});}s.last={x:g.x,z:g.z};}else s.last=null;if(s.painted.size>=cells.length){s.page++;p.score=s.page;s.painted.clear();s.last=null;}});const done=players.filter(p=>p.score===3);if(done.length)c.complete(done.map(p=>p.i),'세 과일 그림 완성');
 },render(){players.forEach((p,i)=>{const s=state[i];board(c,i,`${Math.min(3,s.page+1)} / 3 페이지`);for(let z=0;z<H;z++)for(let x=0;x<W;x++)if(mask(s.page,x,z)){const q=world(i,x,z);box(c,`paint-pixel-${i}-${x}-${z}`,q.x,.02,q.z,size,.08,size,s.painted.has(z*W+x)?[PINK,GOLD,BLUE][s.page%3]:'#b7bfab');}cursor(c,p,{x:s.cx,z:s.cz});});},timeout(){high(c,'색칠 시간 종료');}};
}

function musical(c){
 const players=setup(c,30),notes=[];let next=.1,id=0;players.forEach((p,i)=>{p.x=(i-1.5)*2.8;p.z=0;p.y=.7;});
 return{update(dt){c.hint('방향키로 드럼 위 공을 조종해 음표를 모으세요. 보통 1점·금색 2점. 모을수록 공이 커집니다.');if(c.time>next){const a=c.rand(0,Math.PI*2),r=c.rand(0,6);notes.push({id:id++,x:Math.cos(a)*r,z:Math.sin(a)*r,gold:c.rng()<.2,taken:false});next=c.time+.35;}players.forEach(p=>{const q=notes.filter(q=>!q.taken).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>q?toward(p,q.x,q.z):{});p.vx=(p.vx+input.x*dt*12)*Math.pow(.93,dt*60);p.vz=(p.vz+input.z*dt*12)*Math.pow(.93,dt*60);p.x+=p.vx*dt;p.z+=p.vz*dt;const r=Math.hypot(p.x,p.z);if(r>7){p.x*=7/r;p.z*=7/r;p.vx*=-.5;p.vz*=-.5;}p.y=.7+p.score*.025;notes.forEach(q=>{if(!q.taken&&dist(p,q)<.75+p.score*.025){q.taken=true;c.points(p,q.gold?2:1);c.sound?.(q.gold?780:520,.04);}});});for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=players[i],b=players[j],d=dist(a,b),r=1.3+(a.score+b.score)*.025;if(d<r&&d>.01){const v=toward(a,b.x,b.z);a.x-=v.x*(r-d)*.5;a.z-=v.z*(r-d)*.5;b.x+=v.x*(r-d)*.5;b.z+=v.z*(r-d)*.5;}}
 },render(){c.draw('snare','cylinder',{x:0,y:-.5,z:0,sx:15,sy:1,sz:15,color:'#bcad88'});c.draw('drum-rim','ring',{x:0,y:.03,z:0,sx:15,sy:15,sz:1,rx:-Math.PI/2,color:'#7e98a6'});players.forEach(p=>ball(c,`music-ball-${p.i}`,p.x,p.y/2,p.z,p.y,p.color));notes.forEach(q=>{if(!q.taken)text(c,`music-note-${q.id}`,'♪',q.x,.9,q.z,1.7,q.gold?GOLD:'#e8ebdf');});},timeout(){high(c,'30초 음표 점수');}};
}

function buzz(c){
 const players=setup(c,Infinity);boards(c);let round=0,start=0,targets=[];const state=players.map((p,i)=>({cx:layouts[i].x,cz:layouts[i].z,shot:null,held:false,pace:c.rand(.7,1.3)}));
 function begin(){start=c.time;targets=Array.from({length:12},(_,j)=>({j,depth:1+j%3,speed:c.rand(.45,1.1),phase:c.rand(0,Math.PI*2)}));state.forEach(s=>{s.shot=null;s.held=false;});}begin();
 const pos=t=>({x:Math.sin((c.time-start)*t.speed+t.phase)*3.8,z:(t.j%4-1.5)*1.2+Math.cos((c.time-start)*t.speed*.8+t.phase)*.5});
 return{update(dt){c.hint(`한 발로 여러 솜털을 관통시키세요. ${round+1}/3회 · 방향/포인터 조준 · A를 당겼다 놓아 발사`);players.forEach((p,i)=>{const s=state[i],a=layouts[i],input=c.input(p,()=>{const opts=targets.map(t=>pos(t)),q=opts.map(q=>({...q,n:opts.filter(r=>dist(q,r)<.8).length})).sort((a,b)=>b.n-a.n)[0],age=c.time-start;return{x:clamp((a.x+q.x-s.cx)*4,-1,1),z:clamp((a.z+q.z-s.cz)*4,-1,1),a:age<2+s.pace};});if(!s.shot){const ptr=input.pointer;if(ptr.worldValid){s.cx=clamp(ptr.worldX,a.x-4.2,a.x+4.2);s.cz=clamp(ptr.worldZ,a.z-2.8,a.z+2.8);}else{s.cx=clamp(s.cx+input.x*dt*5,a.x-4.2,a.x+4.2);s.cz=clamp(s.cz+input.z*dt*5,a.z-2.8,a.z+2.8);}if(s.held&&!input.a){s.shot={x:s.cx-a.x,z:s.cz-a.z,depth:0,caught:new Set()};c.sound?.(540,.05);}s.held=input.a;}else{s.shot.depth+=dt*5;targets.forEach(t=>{if(!s.shot.caught.has(t.j)&&Math.abs(t.depth-s.shot.depth)<.18&&dist(s.shot,pos(t))<.8){s.shot.caught.add(t.j);c.points(p);}});}});if(c.time-start>=20||state.every(s=>s.shot?.depth>4)){round++;if(round===3)high(c,'세 화살에 잡힌 솜털 총수');else begin();}
 },render(){players.forEach((p,i)=>{const a=layouts[i],s=state[i];board(c,i,`${round+1}회 · 잡은 수 ${p.score}`);for(let j=0;j<4;j++)box(c,`fuzzy-rail-${i}-${j}`,a.x,.05,a.z+(j-1.5)*1.2,8,.07,.07,'#899d99');targets.forEach(t=>{const q=pos(t),caught=s.shot?.caught.has(t.j);ball(c,`fuzzy-${i}-${t.j}`,a.x+q.x,.3+t.depth*.2,a.z+q.z,.6,caught?p.color:'#4e485c');});cursor(c,p,{x:s.cx,z:s.cz});if(s.shot)box(c,`arrow-${i}`,a.x+s.shot.x,.2+s.shot.depth*.2,a.z+s.shot.z,.09,.08,1.2,GOLD);});}};
}
function cannon(c){
 const players=setup(c,Infinity),state=players.map((p,i)=>({lastAngle:null,turns:0,pace:c.rand(7,12),distance:0}));let launched=false;players.forEach((p,i)=>{p.x=(i-1.5)*4;p.z=2;p.visible=false;});
 return{update(dt){c.hint(c.time<4?'4초 동안 방향키를 원으로 돌리거나 대포 손잡이를 드래그 회전하세요.':'회전시킨 힘으로 날아갑니다! 가장 멀리 착지하면 승리.');players.forEach((p,i)=>{const s=state[i],center={x:(i-1.5)*4,z:2},input=c.input(p,()=>({x:Math.cos(c.time*s.pace),z:Math.sin(c.time*s.pace)}));if(c.time<=4)s.turns+=Math.abs(rotateInput(s,input,center))/(Math.PI*2);});if(!launched&&c.time>=4){launched=true;players.forEach((p,i)=>{state[i].distance=Math.round((70+state[i].turns*55)*10)/10;p.score=state[i].distance;});}if(launched){const t=Math.min(1,(c.time-4)/4);players.forEach((p,i)=>{p.visible=true;p.x=(i-1.5)*4;p.z=2-t*state[i].distance*.06;p.y=Math.sin(t*Math.PI)*10;});const leader=Math.max(...state.map(s=>s.distance));c.view={size:32,eye:[18,22,20-leader*.03*t],target:[0,2,2-leader*.03*t]};}if(c.time>=8)high(c,'대포 비행 거리');
 },render(){players.forEach((p,i)=>{const x=(i-1.5)*4,s=state[i];c.draw(`cannon-${i}`,'cylinder',{x,y:.6,z:2,sx:1.8,sy:3,sz:1.8,rx:-.8,color:p.color});c.draw(`crank-${i}`,'ring',{x,y:.1,z:2,sx:2.5,sy:2.5,rx:-Math.PI/2,color:GOLD});ball(c,`handle-${i}`,x+Math.cos((s.lastAngle??0))*1.2,.3,2+Math.sin(s.lastAngle??0)*1.2,.5,GOLD);text(c,`cannon-score-${i}`,launched?`${p.score.toFixed(1)} m`:`${s.turns.toFixed(1)} 회전`,x,2,4,4,p.color);});}};
}
function goombaManeuver(c){
 const players=setup(c,Infinity),flowers=Array.from({length:20},(_,j)=>({x:c.rand(-2.9,2.9),z:10+j*3.3,r:j>11?.8:.55})),state=players.map(p=>({progress:0,localX:0,stun:0,history:[{x:0,z:0}],followers:Array.from({length:10},(_,j)=>({id:j,x:0,z:-j*.65-1})),done:false,pace:3.4,reaction:c.rand(1.8,4.7)}));c.view={size:33,eye:[0,31,26],target:[0,0,0]};
 const sample=(s,z)=>{const h=s.history;for(let k=h.length-1;k>0;k--)if(h[k-1].z<=z){const a=h[k-1],b=h[k],t=clamp((z-a.z)/(b.z-a.z||1),0,1);return a.x+(b.x-a.x)*t;}return 0;};
 return{update(dt){c.hint('자동으로 걷습니다. ← →로 꽃을 피하며 뒤따르는 열 마리를 지키세요. 모두 완주한 뒤 남은 수 비교!');players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>{const danger=flowers.filter(f=>f.z>s.progress-.3&&f.z<s.progress+s.reaction).sort((a,b)=>a.z-b.z)[0];let x=s.localX;if(danger&&Math.abs(danger.x-x)<danger.r+1)x=clamp(danger.x+(danger.x>0?-1:1)*(danger.r+1.35),-3,3);return{x:clamp((x-s.localX)*3,-1,1)};});if(!s.done){s.localX=clamp(s.localX+input.x*dt*4,-3.25,3.25);s.stun=Math.max(0,s.stun-dt);if(!s.stun){s.progress+=dt*s.pace;const hit=flowers.find(f=>Math.abs(f.z-s.progress)<.45&&Math.abs(f.x-s.localX)<f.r+.3);if(hit){s.stun=.7;s.progress=Math.max(0,s.progress-.8);}}const last=s.history.at(-1);if(s.progress>last.z+.02)s.history.push({x:s.localX,z:s.progress});s.followers.forEach((f,j)=>{const targetZ=s.progress-(j+1)*.7;f.z=Math.min(targetZ,f.z+dt*5);f.x=sample(s,f.z);});s.followers=s.followers.filter(f=>!flowers.some(q=>dist(f,q)<q.r+.24));p.score=s.followers.length;if(!s.followers.length||s.progress>=80)s.done=true;}p.x=(i-1.5)*8+s.localX;p.z=3;p.y=s.stun?Math.sin(s.stun*20)*.15:0;});if(state.every(s=>s.done)){const top=Math.max(...players.map(p=>p.score));c.complete(top===0?[]:players.filter(p=>p.score===top).map(p=>p.i),'전원 완주 · 남은 행렬 비교');}
 },render(){players.forEach((p,i)=>{const s=state[i],cx=(i-1.5)*8;box(c,`flower-track-${i}`,cx,-.2,0,7.3,.3,23,'#a8c993');flowers.forEach((f,j)=>{const z=3+s.progress-f.z;if(z>-12&&z<12){ball(c,`thorn-flower-${i}-${j}`,cx+f.x,.25,z,f.r*2,PINK);c.draw(`thorn-${i}-${j}`,'cone',{x:cx+f.x,y:.8,z,sx:.5,sy:1,sz:.5,color:'#5b6154'});}});s.followers.forEach(f=>ball(c,`follower-${i}-${f.id}`,cx+f.x,.25,3+s.progress-f.z,.5,p.color));text(c,`guide-count-${i}`,s.done?`완주 ${p.score}마리`:`${p.score}마리`,cx,1,-11,5,p.color);});}};
}
function kabob(c){
 const players=setup(c,60);c.bounds={x:7.2,z:5.3};const skewers=Array.from({length:5},(_,j)=>({id:j,x:(j-2)*3,born:-10,next:.7+j*.6,height:.55}));
 return{update(dt){c.hint('뒤쪽의 다섯 꼬치를 피하세요. 경고 후 앞쪽으로 찌릅니다. 방향 이동 · A 점프 · 60초 생존.');skewers.forEach(s=>{if(c.time>=s.next){s.born=c.time;s.height=c.rng()<.75?.55:1.8;s.next=c.time+c.rand(2.6,5.4)*Math.max(.6,1-c.time*.007);}});players.filter(p=>p.alive).forEach(p=>{const danger=skewers.filter(s=>c.time-s.born<2),input=c.input(p,()=>{const options=[-7,-4.5,-1.5,1.5,4.5,7].map(x=>({x,z:3})),q=options.sort((a,b)=>{const score=q=>Math.min(10,...danger.map(s=>Math.abs(q.x-s.x)))-dist(p,q)*.13;return score(b)-score(a);})[0];return{...toward(p,q.x,q.z),a:danger.some(s=>Math.abs(p.x-s.x)<1.2&&s.height<1&&c.time-s.born>.7)};});c.move(p,input,5.8);c.jump(p,input,8);skewers.forEach(s=>{const age=c.time-s.born;if(age<.9||age>1.95)return;const tip=-7+(age-.9)*19;if(p.z<tip&&p.z>tip-15&&Math.abs(p.x-s.x)<.85&&Math.abs(p.y+.4-s.height)<.7)c.eliminate(p);});});c.lastStanding();
 },render(){c.arena({width:17,depth:13,color:'#bfae85'});skewers.forEach(s=>{const age=c.time-s.born;box(c,`skewer-port-${s.id}`,s.x,1.5,-7,2,3,.7,'#768891');if(age>=0&&age<.9)box(c,`skewer-warn-${s.id}`,s.x,.03,0,.4,.03,13,GOLD,{opacity:.7});if(age>=.9&&age<1.95){const tip=-7+(age-.9)*19;box(c,`skewer-${s.id}`,s.x,s.height,tip-7.5,.8,.7,15,'#81929b');c.draw(`skewer-tip-${s.id}`,'cone',{x:s.x,y:s.height,z:tip,sx:1.2,sy:1.5,sz:1.2,rx:Math.PI/2,color:'#cad7d6'});}});},timeout(){c.survivors('다섯 꼬치 생존');}};
}
function tanks(c){
 const players=setup(c,Infinity),bricks=Array.from({length:12},(_,j)=>({x:(j%4-1.5)*3,z:(Math.floor(j/4)-1)*3,hp:1})),bullets=[],state=players.map((p,i)=>({aim:i*Math.PI/2,cool:0,respawn:0}));let id=0;c.bounds={x:9,z:7};players.forEach((p,i)=>{p.x=(i%2?1:-1)*8;p.z=(i<2?-1:1)*6;});
 return{update(dt){c.hint('방향으로 전차 이동·포신 조준 · A 발사. 갈색 벽은 파괴됩니다. 상대를 세 번 맞히면 승리!');players.forEach((p,i)=>{const s=state[i],target=players.filter(q=>q!==p).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>({...toward(p,target.x,target.z),a:s.cool<=0&&c.rng()<.15}));s.cool-=dt;s.respawn=Math.max(0,s.respawn-dt);if(Math.hypot(input.x,input.z)>.1)s.aim=Math.atan2(input.z,input.x);const old={x:p.x,z:p.z};c.move(p,input,3.2);if(bricks.some(b=>b.hp&&Math.abs(p.x-b.x)<1.25&&Math.abs(p.z-b.z)<1.25)){p.x=old.x;p.z=old.z;}if(input.ap&&s.cool<=0){s.cool=.48;bullets.push({id:id++,owner:i,x:p.x+Math.cos(s.aim),z:p.z+Math.sin(s.aim),vx:Math.cos(s.aim)*11,vz:Math.sin(s.aim)*11,live:true});}p.rotation=-s.aim;});bullets.forEach(b=>{if(!b.live)return;b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>10||Math.abs(b.z)>8)b.live=false;const wall=bricks.find(q=>q.hp&&Math.abs(b.x-q.x)<.8&&Math.abs(b.z-q.z)<.8);if(wall){wall.hp=0;b.live=false;}if(b.live){const hit=players.find(p=>p.i!==b.owner&&state[p.i].respawn===0&&dist(p,b)<.9);if(hit){c.points(players[b.owner]);b.live=false;state[hit.i].respawn=1.2;hit.x=(hit.i%2?1:-1)*8;hit.z=(hit.i<2?-1:1)*6;c.sound?.(140,.1);}}});const won=players.filter(p=>p.score>=3);if(won.length)c.complete(won.map(p=>p.i),'전차 명중 세 번');
 },render(){c.arena({width:21,depth:17,color:'#c9ba97'});bricks.forEach((b,j)=>{if(b.hp)box(c,`tank-brick-${j}`,b.x,.6,b.z,1.6,1.2,1.6,'#956747');});players.forEach((p,i)=>{box(c,`tank-${i}`,p.x,.3,p.z,1.5,.5,1.2,p.color);const a=state[i].aim;box(c,`tank-barrel-${i}`,p.x+Math.cos(a)*.5,.7,p.z+Math.sin(a)*.5,1.7,.25,.25,p.color,{ry:-a});});bullets.forEach(b=>{if(b.live)ball(c,`tank-ball-${b.id}`,b.x,.7,b.z,.3,GOLD);});}};
}

function xylophone(c){
 const players=setup(c,Infinity);boards(c);const melody=[0,2,1,3,2,0,1,2,3,1,0,3,1,2,0,2,3,0,1,3,2,1,3,0],chart=melody.map((lane,j)=>({lane,time:2+j*.62,heard:false})),state=players.map(()=>({hit:new Set(),accuracy:c.rand(-.08,.08)}));
 return{update(dt){c.hint('내려오는 음표가 건반 선에 닿을 때 A / B / C / D 또는 해당 건반 클릭. 정확하면 2점, 근접하면 1점.');chart.forEach(n=>{if(!n.heard&&c.time>=n.time){n.heard=true;c.sound?.([392,440,523,587][n.lane],.16);}});players.forEach((p,i)=>{const s=state[i],a=layouts[i],input=c.input(p,()=>{const n=chart.find((n,j)=>!s.hit.has(j)&&Math.abs(c.time-n.time-s.accuracy)<.04);return n?{[keys[n.lane]]:true}:{};}),pressed=keys.map(k=>input[k+'p']);if(input.pointer.pressed&&input.pointer.worldValid&&Math.abs(input.pointer.worldZ-(a.z+1.6))<1.1){const lane=Math.floor((input.pointer.worldX-a.x+4)/2);if(lane>=0&&lane<4)pressed[lane]=true;}pressed.forEach((yes,lane)=>{if(!yes)return;const matches=chart.map((n,j)=>({...n,j})).filter(n=>n.lane===lane&&!s.hit.has(n.j)&&Math.abs(c.time-n.time)<.23).sort((a,b)=>Math.abs(c.time-a.time)-Math.abs(c.time-b.time));if(matches.length){const n=matches[0];s.hit.add(n.j);c.points(p,Math.abs(c.time-n.time)<.1?2:1);}});});if(c.time>chart.at(-1).time+.7)high(c,'멜로디의 정확한 타이밍');
 },render(){players.forEach((p,i)=>{const a=layouts[i],s=state[i];board(c,i,`리듬 ${p.score}점`);for(let lane=0;lane<4;lane++){box(c,`xylo-key-${i}-${lane}`,a.x+(lane-1.5)*2,.2,a.z+1.6,1.8,.35,1.5,[PINK,BLUE,GOLD,GREEN][lane]);text(c,`xylo-letter-${i}-${lane}`,keys[lane].toUpperCase(),a.x+(lane-1.5)*2,.6,a.z+1.7,1.8);}chart.forEach((n,j)=>{const until=n.time-c.time;if(!s.hit.has(j)&&until>-.25&&until<2)text(c,`xylo-note-${i}-${j}`,'♪',a.x+(n.lane-1.5)*2,.7,a.z+1.6-until*2.4,1.5,p.color);});});}};
}
function spinBubble(c){
 const players=setup(c,Infinity);boards(c);let round=0,start=0,target=[0,0,0],rank=0;const state=players.map(()=>({rot:[0,0,0],done:false,hold:0,pace:2.2,gain:c.rand(1.8,4)}));
 const vertices=[[0,0,0],[.95,0,0],[-.3,1,0],[.15,-.7,.6],[-.5,0,-.5]];
 function rotate(v,r){let[x,y,z]=v,[a,b,d]=r;[y,z]=[y*Math.cos(a)-z*Math.sin(a),y*Math.sin(a)+z*Math.cos(a)];[x,z]=[x*Math.cos(b)+z*Math.sin(b),-x*Math.sin(b)+z*Math.cos(b)];[x,y]=[x*Math.cos(d)-y*Math.sin(d),x*Math.sin(d)+y*Math.cos(d)];return[x,y,z];}
 function begin(){start=c.time;rank=0;target=[c.rand(-1.3,1.3),c.rand(-1.5,1.5),c.rand(-1,1)];state.forEach(s=>{s.rot=[c.rand(-2,2),c.rand(-2,2),c.rand(-2,2)];s.done=false;s.hold=0;});}begin();
 return{update(dt){c.hint(`캡슐 안 입체를 검은 윤곽과 맞추세요. ${round+1}/3회 · 방향키 두 축 회전 · A/B 세 번째 축 회전. 순서대로 9·6·3·0점.`);players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>({x:clamp(angleDiff(target[1],s.rot[1])*s.gain,-1,1),z:clamp(angleDiff(target[0],s.rot[0])*s.gain,-1,1),a:angleDiff(target[2],s.rot[2])>.05,b:angleDiff(target[2],s.rot[2])<-.05}));if(s.done)return;s.rot[0]+=input.z*dt*s.pace;s.rot[1]+=input.x*dt*s.pace;s.rot[2]+=((input.a?1:0)-(input.b?1:0))*dt*s.pace;const error=vertices.reduce((sum,v)=>{const a=rotate(v,s.rot),b=rotate(v,target);return sum+Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);},0)/vertices.length;s.hold=error<.18?s.hold+dt:0;if(s.hold>.3){s.done=true;c.points(p,[9,6,3,0][Math.min(3,rank++)]);c.sound?.(660,.06);}});if(c.time-start>=20||state.every(s=>s.done)){round++;if(round>=3)high(c,'세 캡슐 순위 합계');else begin();}
 },render(){players.forEach((p,i)=>{const a=layouts[i],s=state[i];board(c,i,s.done?'포장 완료':`캡슐 ${round+1} · ${p.score}점`);ball(c,`capsule-${i}`,a.x-1.7,1.6,a.z,3.8,'#8ecbd8',{opacity:.15});vertices.forEach((v,j)=>{const q=rotate(v,s.rot),t=rotate(v,target),size=j===0?1.3:.65;ball(c,`figure-${i}-${j}`,a.x-1.7+q[0],1.6+q[1],a.z+q[2],size,s.done?GREEN:p.color);ball(c,`silhouette-${i}-${j}`,a.x+2.6+t[0],1.6+t[1],a.z+t[2]*.04,size,'#263d47');});text(c,`target-label-${i}`,'맞출 윤곽',a.x+2.6,.3,a.z+2.3,3);});}};
}
function ratFlat(c){
 const players=setup(c,30),rats=[],state=players.map(()=>({pound:false})),holes=[[-6,-3],[-2,-4],[3,-4],[6,-2],[-5,3],[0,3],[5,3]];let next=.1,id=0;c.bounds={x:8,z:5};
 return{update(dt){c.hint('방향 이동 · A 점프 후 A/B로 엉덩이 찍기! 돌아다니는 생쥐는 1점, 금색은 3점.');if(c.time>=next){const start=c.pick(holes),end=c.pick(holes);rats.push({id:id++,x:start[0],z:start[1],tx:end[0],tz:end[1],gold:c.rng()<.2,live:true});next=c.time+.7;}rats.forEach(r=>{if(!r.live)return;const v=toward(r,r.tx,r.tz);r.x+=v.x*dt*2;r.z+=v.z*dt*2;if(dist(r,{x:r.tx,z:r.tz})<.2)r.live=false;});players.forEach((p,i)=>{const s=state[i],target=rats.filter(r=>r.live).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>target?{...toward(p,target.x,target.z),a:p.y===0&&dist(p,target)<1.3,b:p.y>.7}:{});c.move(p,input,5.5);if(input.ap&&p.y===0){p.y=.001;p.vy=8;s.pound=false;}if((input.ap||input.bp)&&p.y>.3){p.vy=-18;s.pound=true;}if(p.y>0){p.vy-=18*dt;p.y+=p.vy*dt;if(p.y<=0){p.y=0;if(s.pound){rats.forEach(r=>{if(r.live&&dist(p,r)<1.15){r.live=false;c.points(p,r.gold?3:1);}});s.pound=false;}}}});
 },render(){c.arena({color:'#bfa283'});holes.forEach(([x,z],j)=>c.draw(`rat-hole-${j}`,'cylinder',{x,y:.02,z,sx:1.2,sy:.04,sz:1.2,color:'#3f4146'}));rats.forEach(r=>{if(r.live){ball(c,`rat-${r.id}`,r.x,.25,r.z,.7,r.gold?GOLD:'#b4a2ba');ball(c,`rat-ear-${r.id}`,r.x+.25,.5,r.z,.27,r.gold?GOLD:PINK);}});},timeout(){high(c,'생쥐 찍기 점수');}};
}
function hideSplat(c){
 const players=setup(c,60),boxes=[];let id=0; c.bounds={x:7.3,z:5.3};
 function add(){const x=c.int(-2,2)*3,z=c.int(-1,1)*3;boxes.push({id:id++,x,z,tx:x,tz:z,start:c.time,next:c.time+.8,moving:false});}add();add();
 return{update(dt){c.hint('방향키로 굴러오는 상자를 피하세요. 밝은 사각형이 다음 착지 지점입니다. 점점 더 많고 빨라집니다.');if(boxes.length<Math.min(6,2+Math.floor(c.time/12)))add();boxes.forEach(b=>{const speed=Math.max(.48,1.25-c.time*.01);if(!b.moving&&c.time>=b.next){const axis=c.int(0,1),sign=c.rng()<.5?-1:1;b.tx=clamp(b.x+(axis?3*sign:0),-6,6);b.tz=clamp(b.z+(axis?0:3*sign),-3,3);b.start=c.time;b.moving=true;}if(b.moving&&c.time-b.start>=speed){b.x=b.tx;b.z=b.tz;b.moving=false;b.next=c.time+.18;players.forEach(p=>{if(p.alive&&Math.abs(p.x-b.x)<1.65&&Math.abs(p.z-b.z)<1.65)c.eliminate(p);});}});players.filter(p=>p.alive).forEach(p=>{const opts=Array.from({length:25},(_,j)=>({x:(j%5-2)*3,z:(Math.floor(j/5)-2)*2.4})),input=c.input(p,()=>{const q=opts.sort((a,b)=>{const score=q=>Math.min(20,...boxes.map(t=>Math.hypot(q.x-t.tx,q.z-t.tz)))-dist(p,q)*.18;return score(b)-score(a);})[0];return toward(p,q.x,q.z);});c.move(p,input,5.4);});c.lastStanding();
 },render(){c.arena({width:17,depth:13,color:'#9bac9f'});boxes.forEach(b=>{const speed=Math.max(.48,1.25-c.time*.01),t=b.moving?clamp((c.time-b.start)/speed,0,1):0,x=b.x+(b.tx-b.x)*t,z=b.z+(b.tz-b.z)*t;box(c,`tox-warning-${b.id}`,b.tx,.02,b.tz,3.2,.05,3.2,GOLD,{opacity:b.moving?.55:0});box(c,`tox-box-${b.id}`,x,1.5+Math.sin(t*Math.PI)*1.4,z,3,3,3,'#756582',{rx:b.tz!==b.z?t*Math.PI/2:0,rz:b.tx!==b.x?t*Math.PI/2:0});text(c,`tox-face-${b.id}`,'><',x,3.3+Math.sin(t*Math.PI)*1.4,z,2,PINK);});},timeout(){c.survivors('상자 생존');}};
}
function slowGlide(c){
 const players=setup(c,Infinity),balloons=Array.from({length:80},(_,j)=>({id:j,depth:10+j*1.7,x:c.rand(-7,7),height:c.rand(1,7),owner:j%10===0?-1:j%4,taken:false,phase:c.rand(0,6)}));const progress=()=>c.time*4;players.forEach((p,i)=>{p.x=(i-1.5)*3;p.y=4;p.z=3;});c.view={size:26,eye:[0,11,24],target:[0,4,-2]};
 const by=b=>b.height+(b.owner===-1?Math.sin(c.time*1.7+b.phase)*1.4:0);
 return{update(dt){c.hint('자동 활공 · 방향키로 좌우/높이 조절. 자기 색 풍선 1점, 움직이는 금 풍선 3점. 다른 색은 통과합니다.');players.forEach(p=>{const opts=balloons.filter(b=>!b.taken&&(b.owner===p.i||b.owner===-1)&&b.depth>progress()-1).sort((a,b)=>a.depth-b.depth),q=opts[0],input=c.input(p,()=>q?{x:clamp((q.x-p.x)*2,-1,1),z:clamp((p.y-by(q))*2,-1,1)}:{});p.x=clamp(p.x+input.x*dt*4,-8,8);p.y=clamp(p.y-input.z*dt*4,1,8);balloons.forEach(b=>{if(!b.taken&&(b.owner===p.i||b.owner===-1)&&Math.abs(b.depth-progress())<.65&&Math.hypot(p.x-b.x,p.y-by(b))<1){b.taken=true;c.points(p,b.owner===-1?3:1);}});});if(progress()>155)high(c,'활공 코스 풍선 점수');
 },render(){box(c,'cloud-floor',0,-1,-10,23,.2,50,'#b8dbdf');players.forEach(p=>box(c,`glider-${p.i}`,p.x,p.y-.1,3,3,.12,1.8,p.color,{rz:-.08*p.x}));balloons.forEach(b=>{const z=3+progress()-b.depth;if(!b.taken&&z>-28&&z<8){ball(c,`balloon-${b.id}`,b.x,by(b),z,1.3,b.owner===-1?GOLD:players[b.owner].color);box(c,`string-${b.id}`,b.x,by(b)-.9,z,.025,1.1,.025,'#e5eadf');}});}};
}

function subTrouble(c){
 const players=setup(c,Infinity),rocks=Array.from({length:22},(_,j)=>({x:10+j*5,center:c.rand(2,6),gap:c.rand(2.4,3.1)})),state=players.map(()=>({progress:0,height:4,stun:0,hit:new Set(),pace:4.7,gain:c.rand(.8,2.8)}));c.view={size:30,eye:[0,23,27],target:[0,0,0]};
 return{update(dt){c.hint('잠수함은 자동 전진합니다. ↑ ↓로 높이를 조절해 바위 사이를 통과하세요. 먼저 출구에 닿으면 승리!');players.forEach((p,i)=>{const s=state[i],q=rocks.find(r=>r.x>s.progress-1),input=c.input(p,()=>({z:q?clamp((s.height-q.center)*s.gain,-1,1):0}));s.height=clamp(s.height-input.z*dt*3.3,.7,7.3);s.stun=Math.max(0,s.stun-dt);s.progress+=dt*s.pace*(s.stun?.12:1);rocks.forEach((r,j)=>{if(!s.hit.has(j)&&Math.abs(r.x-s.progress)<.7&&Math.abs(s.height-r.center)>r.gap/2-.35){s.hit.add(j);s.stun=1.5;c.sound?.(100,.05);}});p.x=-8;p.z=(i-1.5)*5;p.y=.6;p.score=s.progress;});const done=players.filter((p,i)=>state[i].progress>=125);if(done.length)c.complete(done.map(p=>p.i),'먼저 잠수함 출구 도착');
 },render(){players.forEach((p,i)=>{const s=state[i],lane=(i-1.5)*5;box(c,`water-${i}`,0,-.3,lane,23,.2,4.7,'#69a8b8');p.visible=false;const localY=(s.height-4)*.45;ball(c,`submarine-${i}`,-8,.7,lane-localY,1.3,p.color,{sx:2,sy:.7,sz:1});box(c,`periscope-${i}`,-8,.9,lane-localY,.3,.6,.3,p.color);rocks.forEach((r,j)=>{const x=-8+r.x-s.progress;if(x>-11&&x<12){const top=(8-(r.center+r.gap/2))*.45,bottom=(r.center-r.gap/2)*.45;box(c,`subrock-top-${i}-${j}`,x,.35,lane-1.8+top/2,1.2,.9,Math.max(.05,top),'#597b86');box(c,`subrock-bottom-${i}-${j}`,x,.35,lane+1.8-bottom/2,1.2,.9,Math.max(.05,bottom),'#597b86');}});text(c,`sub-distance-${i}`,`${Math.min(100,Math.floor(s.progress/125*100))}%`,-11,1,lane,3,p.color);});}};
}
function peep(c){
 const players=setup(c,30);boards(c);const state=players.map((p,i)=>({cx:layouts[i].x,cz:layouts[i].z,ghosts:[],next:0,tick:0,pace:5.5,gain:c.rand(.75,1)}));let id=0;
 return{update(dt){c.hint('방향키 또는 포인터로 손전등을 계속 비추세요. 유령 하나를 다섯 번 비추면 사라집니다. 버튼은 필요 없습니다.');players.forEach((p,i)=>{const s=state[i],a=layouts[i];if(c.time>=s.next){s.ghosts.push({id:id++,x:c.rand(-3.5,3.5),z:c.rand(-2,2),phase:c.rand(0,6),hits:0});s.next=c.time+1.1;}const pos=g=>({x:a.x+g.x+Math.sin(c.time+g.phase)*.45,z:a.z+g.z+Math.cos(c.time*.8+g.phase)*.4}),q=s.ghosts.filter(g=>g.hits<5).sort((u,v)=>dist({x:s.cx,z:s.cz},pos(u))-dist({x:s.cx,z:s.cz},pos(v)))[0],input=c.input(p,()=>q?toward({x:s.cx,z:s.cz},pos(q).x,pos(q).z,s.gain):{});if(input.pointer.worldValid){s.cx=clamp(input.pointer.worldX,a.x-4.5,a.x+4.5);s.cz=clamp(input.pointer.worldZ,a.z-2.8,a.z+2.8);}else{s.cx=clamp(s.cx+input.x*dt*s.pace,a.x-4.5,a.x+4.5);s.cz=clamp(s.cz+input.z*dt*s.pace,a.z-2.8,a.z+2.8);}s.tick-=dt;if(s.tick<=0){s.tick=.25;s.ghosts.filter(g=>g.hits<5&&dist({x:s.cx,z:s.cz},pos(g))<.65).forEach(g=>{g.hits++;c.points(p);});}});
 },render(){players.forEach((p,i)=>{const a=layouts[i],s=state[i];board(c,i,`빛 ${p.score}점`);box(c,`dark-room-${i}`,a.x,-.01,a.z,10,.08,6,'#263647');s.ghosts.filter(g=>g.hits<5).forEach(g=>{const x=a.x+g.x+Math.sin(c.time+g.phase)*.45,z=a.z+g.z+Math.cos(c.time*.8+g.phase)*.4;ball(c,`peepa-${g.id}`,x,.4,z,.8,'#e3e7da',{opacity:1-g.hits*.1});text(c,`peepa-eyes-${g.id}`,'··',x,.9,z,.8,'#2c3643');});c.draw(`light-${i}`,'cylinder',{x:s.cx,y:.05,z:s.cz,sx:1.4,sy:.05,sz:1.4,color:GOLD,opacity:.5});cursor(c,p,{x:s.cx,z:s.cz});});},timeout(){high(c,'30초 손전등 점수');}};
}
function puzzleShape(c,id,type,x,z,size,color){
 if(type%6===0){ball(c,id,x,.2,z,size,color,{sy:.2});box(c,id+'stem',x,.1,z+size*.4,size*.25,.12,size*.5,color);}
 else if(type%6===1)box(c,id,x,.15,z,size,.2,size,color,{ry:Math.PI/4});
 else if(type%6===2){box(c,id,x,.1,z,size,.2,size*.3,color);box(c,id+'v',x,.1,z,size*.3,.2,size,color);}
 else if(type%6===3){box(c,id,x-size*.3,.1,z,size*.3,.2,size,color);box(c,id+'l',x,.1,z+size*.35,size,.2,size*.3,color);}
 else if(type%6===4)c.draw(id,'cone',{x,y:.18,z,sx:size,sy:.25,sz:size,color});
 else{ball(c,id,x-size*.23,.15,z-size*.1,size*.65,color,{sy:.2});ball(c,id+'r',x+size*.23,.15,z-size*.1,size*.65,color,{sy:.2});box(c,id+'tip',x,.15,z+size*.2,size*.65,.2,size*.65,color,{ry:Math.PI/4});}
}
function puzzlePronto(c){
 const players=setup(c,Infinity);boards(c);const variant=c.int(0,3),templates=Array.from({length:3},(_,stage)=>({order:c.shuffle(Array.from({length:[4,6,9][stage]},(_,j)=>j)),types:c.shuffle([0,1,2,3,4,5]),angles:[c.pick([Math.PI/2,Math.PI,Math.PI*1.5]),c.pick([Math.PI/2,Math.PI,Math.PI*1.5])]})),state=players.map((p,i)=>({stage:0,cx:layouts[i].x,cz:layouts[i].z,marked:new Set(),drag:null,selected:0,lastAngle:null,rot:[...templates[0].angles],botPhase:0,botT:0}));
 const loc=(i,x,z)=>({x:layouts[i].x+x,z:layouts[i].z+z}),mushroom=(stage,j)=>({x:Math.sin(j*2.7+c.time*(.55+stage*.1))*3.4,z:Math.cos(j*3.7+c.time*.6)*2.1});
 const item=(stage,j)=>({x:(j%3-1)*2.6,z:1.3+Math.floor(j/3)*1.1}),slot=(stage,j)=>({x:(j-([2,3,4][stage]-1)/2)*2.1,z:-1.7}),number=(stage,j)=>({x:(j%3-1)*2.6,z:(Math.floor(j/3)-1)*1.8});
 function advance(s,p){s.stage++;p.score=s.stage;s.marked.clear();s.drag=null;s.selected=0;s.lastAngle=null;s.botPhase=0;if(s.stage<3)s.rot=[...templates[s.stage].angles];}
 return{update(dt){c.hint(['버섯 퍼즐: 움직이는 버섯을 모두 클릭! A는 가상 커서 클릭.','그림자 퍼즐: 맞는 물건을 그림자로 드래그! A를 누른 채 방향 이동.','파이프 퍼즐: 안·밖 고리를 드래그 회전. 키보드는 B로 고리 선택 후 방향키 원운동.','숫자 퍼즐: 작은 수부터 차례대로 클릭! A는 가상 커서 클릭.'][variant]+' 세 단계 선착순.');players.forEach((p,i)=>{const s=state[i],a=layouts[i];if(s.stage>=3)return;const stage=s.stage,t=templates[stage];let target=null,botDown=false,botExtra={};if(variant===0){const n=[5,6,8][stage],j=Array.from({length:n},(_,j)=>j).find(j=>!s.marked.has(j));target=loc(i,mushroom(stage,j).x,mushroom(stage,j).z);botDown=Math.floor(c.time*6)%2===0;}else if(variant===1){const j=Array.from({length:[2,3,4][stage]},(_,j)=>j).find(j=>!s.marked.has(j));if(s.drag===null){const q=item(stage,j);target=loc(i,q.x,q.z);botDown=Math.hypot(s.cx-target.x,s.cz-target.z)<.12;}else{const q=slot(stage,s.drag);target=loc(i,q.x,q.z);botDown=Math.hypot(s.cx-target.x,s.cz-target.z)>.1;}}else if(variant===2){const active=Math.abs(angleDiff(0,s.rot[0]))>.035?0:1;if(s.selected!==active)botExtra.b=Math.floor(c.time*8)%2===0;const sign=Math.sign(angleDiff(0,s.rot[active]));s.botT+=dt*3*sign;botExtra.x=Math.cos(s.botT);botExtra.z=Math.sin(s.botT);}else{const expected=s.marked.size,j=t.order.indexOf(expected),q=number(stage,j);target=loc(i,q.x,q.z);botDown=Math.floor(c.time*7)%2===0;}
 const input=c.input(p,()=>{if(variant===2)return botExtra;const v=toward({x:s.cx,z:s.cz},target.x,target.z),d=Math.min(dist({x:s.cx,z:s.cz},target),dt*8);return{pointer:{valid:true,worldValid:true,worldX:s.cx+v.x*d,worldZ:s.cz+v.z*d,down:botDown}};});
 if(variant===2){if(input.bp){s.selected=1-s.selected;s.lastAngle=null;}const ptr=input.pointer;if(ptr.pressed&&ptr.worldValid){s.selected=Math.hypot(ptr.worldX-a.x,ptr.worldZ-a.z)>2.1?1:0;s.lastAngle=null;}const delta=rotateInput(s,input,a);s.rot[s.selected]+=delta;const period=stage===0?Math.PI:Math.PI*2,ok=s.rot.every(v=>Math.abs(Math.atan2(Math.sin(v*Math.PI*2/period),Math.cos(v*Math.PI*2/period)))<.11);if(ok)advance(s,p);return;}
 const g=gesture(c,p,s,input,a,4.5,2.9);if(variant===0&&g.pressed){for(let j=0;j<[5,6,8][stage];j++){const q=mushroom(stage,j);if(!s.marked.has(j)&&dist(g,loc(i,q.x,q.z))<.65)s.marked.add(j);}if(s.marked.size===[5,6,8][stage])advance(s,p);}else if(variant===1){if(g.pressed&&s.drag===null){for(let j=0;j<[3,4,6][stage];j++){const q=item(stage,j);if(!s.marked.has(j)&&dist(g,loc(i,q.x,q.z))<.7){s.drag=j;break;}}}if(g.released&&s.drag!==null){const j=s.drag;if(j<[2,3,4][stage]){const q=slot(stage,j);if(dist(g,loc(i,q.x,q.z))<.8)s.marked.add(j);}s.drag=null;if(s.marked.size===[2,3,4][stage])advance(s,p);}}else if(variant===3&&g.pressed){const expected=s.marked.size,j=t.order.indexOf(expected),q=number(stage,j);if(dist(g,loc(i,q.x,q.z))<.7)s.marked.add(expected);if(s.marked.size===[4,6,9][stage])advance(s,p);}});const done=players.filter(p=>p.score>=3);if(done.length)c.complete(done.map(p=>p.i),'세 터치 퍼즐 완성');
 },render(){players.forEach((p,i)=>{const s=state[i],a=layouts[i],stage=Math.min(2,s.stage),t=templates[stage];board(c,i,`${['버섯','그림자','파이프','숫자'][variant]} ${Math.min(3,s.stage+1)}/3`);if(variant===0){for(let j=0;j<[5,6,8][stage];j++)if(!s.marked.has(j)){const q=mushroom(stage,j);puzzleShape(c,`mushroom-${i}-${j}`,0,a.x+q.x,a.z+q.z,.9,PINK);}}else if(variant===1){for(let j=0;j<[2,3,4][stage];j++){const q=slot(stage,j);puzzleShape(c,`sil-slot-${i}-${j}`,t.types[j],a.x+q.x,a.z+q.z,1.2,s.marked.has(j)?GREEN:'#344450');}for(let j=0;j<[3,4,6][stage];j++)if(!s.marked.has(j)){const q=item(stage,j);puzzleShape(c,`sil-item-${i}-${j}`,t.types[j],s.drag===j?s.cx:a.x+q.x,s.drag===j?s.cz:a.z+q.z,1.05,p.color);}}else if(variant===2){const endpoints=stage===0?[0,Math.PI]:stage===1?[Math.PI,-Math.PI/2]:[0,Math.PI,-Math.PI/2];for(let k=0;k<2;k++){const r=k?2.7:1.5;c.draw(`pipe-ring-${i}-${k}`,'ring',{x:a.x,y:.04,z:a.z,sx:r*2,sy:r*2,rx:-Math.PI/2,color:s.selected===k?GOLD:'#aabcb5'});endpoints.forEach((theta,j)=>{const v=theta+s.rot[k];box(c,`pipe-part-${i}-${k}-${j}`,a.x+Math.cos(v)*(k?2.65:1.3),.2,a.z+Math.sin(v)*(k?2.65:1.3),k?1.4:1.3,.35,.55,GREEN,{ry:-v});});}endpoints.forEach((v,j)=>box(c,`pipe-port-${i}-${j}`,a.x+Math.cos(v)*3.7,.2,a.z+Math.sin(v)*3.7,1,.4,.7,'#567a62',{ry:-v}));}else{for(let j=0;j<[4,6,9][stage];j++){const n=t.order[j],q=number(stage,j);if(!s.marked.has(n)){ball(c,`number-circle-${i}-${j}`,a.x+q.x,.15,a.z+q.z,1.2,p.color,{sy:.2});text(c,`number-${i}-${j}`,n+1,a.x+q.x,.55,a.z+q.z,.9);}}}if(variant!==2)cursor(c,p,{x:s.cx,z:s.cz});});}};
}

function truckCluck(c){
 const players=setup(c,30),birds=[],state=players.map(()=>({cool:0,dash:0,dx:0,dz:0,stun:0}));let next=0,id=0;c.bounds={x:8,z:5};
 function spawn(gold=false){birds.push({id:id++,x:gold?-8:c.rand(-6,6),z:c.rand(-4,4),gold,held:null,eggs:gold?5:7,next:c.time+.9,phase:c.rand(0,6),live:true});}spawn();
 return{update(dt){c.hint('방향 이동 · A 닭 잡기/몸통박치기. 붙잡고 있는 동안 알 1점, 금색 닭은 2점. 상대를 들이받아 빼앗으세요!');if(c.time>=next){spawn(c.time>3&&c.rng()<.4);next=c.time+4;}players.forEach((p,i)=>{const s=state[i],held=birds.find(b=>b.live&&b.held===i),target=held?players.filter(q=>q!==p).sort((a,b)=>dist(p,a)-dist(p,b))[0]:birds.filter(b=>b.live).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>{if(!target)return{};const v=toward(p,target.x,target.z);return held?{x:-v.x,z:-v.z}:{...v,a:dist(p,target)<1.8&&s.cool<=0};});s.cool=Math.max(0,s.cool-dt);s.stun=Math.max(0,s.stun-dt);if(s.stun)return;if(input.ap&&s.cool<=0&&!held){s.cool=.75;const d=Math.hypot(input.x,input.z)||1;s.dx=input.x/d;s.dz=input.z/d;if(!input.x&&!input.z){s.dx=Math.cos(-p.rotation);s.dz=Math.sin(-p.rotation);}s.dash=.22;const free=birds.find(b=>b.live&&b.held===null&&dist(p,b)<1.5);if(free){free.held=i;free.next=c.time+.7;s.dash=0;}}if(s.dash>0){s.dash-=dt;c.move(p,{x:s.dx,z:s.dz},11);const holder=players.find(q=>q!==p&&dist(p,q)<1.15&&birds.some(b=>b.live&&b.held===q.i));if(holder){const bird=birds.find(b=>b.live&&b.held===holder.i);bird.held=i;state[holder.i].stun=.65;s.dash=0;}}else c.move(p,input,held?4.3:5.5);});birds.forEach(b=>{if(!b.live)return;if(b.held!==null){const p=players[b.held];b.x=p.x;b.z=p.z;if(c.time>=b.next){c.points(p,b.gold?2:1);b.eggs--;b.next=c.time+.8;if(b.eggs<=0)b.live=false;}}else{b.x=clamp(b.x+Math.cos(c.time*.7+b.phase)*dt*(b.gold?2:1),-8,8);b.z=clamp(b.z+Math.sin(c.time+b.phase)*dt,-4.5,4.5);}});
 },render(){c.arena({color:'#aeca8b'});birds.filter(b=>b.live).forEach(b=>{const y=b.held!==null?1.7:b.gold?1.1:.4;ball(c,`chicken-${b.id}`,b.x,y,b.z,.7,b.gold?GOLD:'#f4efda');ball(c,`comb-${b.id}`,b.x+.18,y+.4,b.z,.25,PINK);if(b.held!==null)text(c,`eggs-${b.id}`,`🥚 ${b.eggs}`,b.x,2.8,b.z,2,b.gold?GOLD:'#354b50');});},timeout(){high(c,'닭이 낳은 알 점수');}};
}
function getReel(c){
 const players=setup(c,Infinity);boards(c);let round=0,start=0,target=0,rank=0;const state=players.map(()=>({frame:0,lastAngle:null,stun:0,done:false,pace:c.rand(1.4,2)}));
 function begin(){target=c.int(5,25);start=c.time;rank=0;state.forEach(s=>{s.frame=c.int(0,30);s.lastAngle=null;s.done=false;s.stun=0;});}begin();
 function scene(id,a,frame,small){const q=frame/30,sc=small?.65:1,xx=x=>a.x+x*sc,zz=z=>a.z+z*sc,B=(n,x,y,z,sx,sy,sz,color,more={})=>box(c,id+n,xx(x),y*sc,zz(z),sx*sc,sy*sc,sz*sc,color,more),S=(n,x,y,z,size,color)=>ball(c,id+n,xx(x),y*sc,zz(z),size*sc,color);B('bg',0,-.02,0,4.6,.08,2.8,'#c6d6bd');if(round===0){S('ghost',-1.7,.5,0,.6,'#f6f1e2');B('feet',(q-.5)*3.5,.25,Math.sin(q*4*Math.PI)*.4,.7,.25,.35,PINK);S('runner',(q-.5)*3.5,.6,0,.55,PINK);}else if(round===1){for(let j=0;j<3;j++)S('balloon'+j,(j-1)*1.4,.8,-.8,.5,[BLUE,GOLD,GREEN][j]);B('plane',(q-.5)*3.5,.7+Math.sin(q*Math.PI)*.7,0,1.1,.1,.7,PINK,{rz:(q-.5)*.5});}else{for(let j=-1;j<=1;j++)c.draw(id+'pipe'+j,'cylinder',{x:xx(j*1.4),y:.2*sc,z:zz(0),sx:.65*sc,sy:.5*sc,sz:.65*sc,color:j===0?GOLD:GREEN});S('jumper',0,.6+Math.sin(q*Math.PI)*1.6,(q-.5)*1.1,.5,PINK);B('ray',(q-.5)*3,1.8,-1,1,.1,.6,BLUE);}}
 return{update(dt){c.hint(`아래 기준 장면과 필름을 맞추세요. ${round+1}/3회 · 방향키 원운동/손잡이 드래그로 되감기 · A 확인 · B/C 한 프레임 뒤/앞.`);players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>{const diff=target-Math.round(s.frame);return{b:diff<0&&Math.floor(c.time*14*s.pace)%2===0,c:diff>0&&Math.floor(c.time*14*s.pace)%2===0,a:diff===0&&s.stun===0};});s.stun=Math.max(0,s.stun-dt);if(s.done||s.stun)return;const delta=rotateInput(s,input,{x:layouts[i].x+4,z:layouts[i].z+1.5});s.frame=clamp(s.frame+delta*5+(input.cp?1:0)-(input.bp?1:0),0,30);if(input.ap){if(Math.round(s.frame)===target){s.done=true;c.points(p,[9,6,3,0][Math.min(3,rank++)]);c.sound?.(740,.05);}else{s.stun=.7;c.sound?.(130,.06);}}});if(c.time-start>=20||state.every(s=>s.done)){round++;if(round===3)high(c,'세 필름 순위 합계');else begin();}
 },render(){players.forEach((p,i)=>{const a=layouts[i],s=state[i];board(c,i,s.done?'일치!':s.stun?'다른 장면':'기준 그림을 찾으세요');scene(`film-${i}`,{x:a.x-1.3,z:a.z-1},Math.round(s.frame),false);scene(`reference-${i}`,{x:a.x-1.3,z:a.z+2},target,true);c.draw(`reel-${i}`,'ring',{x:a.x+3.6,y:.1,z:a.z+1.5,sx:2,sy:2,rx:-Math.PI/2,color:p.color});box(c,`reel-spoke-${i}`,a.x+3.6,.12,a.z+1.5,2,.1,.1,GOLD,{ry:-s.frame/5});});}};
}

export const games={
 'Claiming the Cube':claimingCube,'Rope a Slope':ropeSlope,'Tragic Carpet Ride':carpet,'Color Me Fast':colorFast,'Musical Snares':musical,
 'Buzz a Fuzzy':buzz,'Cannonball!':cannon,'Goomba to Maneuver':goombaManeuver,'Kabob and Weave':kabob,'Tanks a Lot':tanks,
 'Xylophone Home':xylophone,'Spin the Bubble':spinBubble,'Rat-a-tat Flat':ratFlat,"Hide 'n' Splat":hideSplat,'Slow Glide':slowGlide,
 'Sub Trouble':subTrouble,'Peep a Peepa':peep,'Puzzle Pronto':puzzlePronto,"Truckin' and Cluckin'":truckCluck,'Get Reel':getReel
};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['island-tour']]));
export const notes={
 'Claiming the Cube':'원작 30초·정육면체 여섯 면·면마다 네 패널·흰 칸 엉덩이 찍기 득점. 방향 이동, A 점프 후 공중 A/B 찍기. 여섯 면의 경계에서 실제 이동 방향을 접고 몸도 면 법선으로 회전합니다. 아래 펼친 지도는 화면에 가려진 면 확인용입니다. 흰 패널 출현 간격·속도는 재구성했습니다.',
 'Rope a Slope':'자동 하강 중 A로 벽 바깥쪽에 뛰어 덤불을 피합니다. 먼저 밑에 닿으면 승리. 코스 75단위·덤불 16개·피격 지연 1초는 재구성 수치이며 원작 수치로 확인되지 않았습니다. 제한시간은 두지 않았습니다.',
 'Tragic Carpet Ride':'원작 60초. 방향 이동·A 점프. 카펫을 먹는 적이 실제 통과한 바닥을 없애며 몸에 부딪히면 밀리고 잠시 멈춥니다. 떨어지면 탈락, 마지막 생존자 또는 시간 종료 생존자 승리. 바닥 격자·적 출현은 새 구성입니다.',
 'Color Me Fast':'원작 일반 경기의 과일 세 장을 60초 안에 먼저 칠합니다. 1P는 드래그, 다른 입력은 A를 누른 채 방향키로 실제 붓 이동. 18×14 과일 마스크의 모든 칸이 칠해져야 다음 장으로 넘어갑니다. 붓 반경·과일 도안은 재구성. 시간 종료 시 완성한 장수가 가장 많은 참가자를 비교합니다.',
 'Musical Snares':'원작 30초·일반 음표 1점·금 음표 2점·수집할수록 공이 커집니다. 방향키로 관성 있는 공을 굴립니다. 공끼리 밀어내기, 가장자리 반사, 음표 출현과 성장 계수는 재구성했습니다.',
 'Buzz a Fuzzy':'원작 세 라운드·라운드당 20초·화살 한 발로 잡은 솜털 합계 비교. 기울이기 대신 방향/포인터 조준, A를 누른 후 놓으면 화살 발사. 세 깊이의 레일을 한 화살이 관통합니다. 레일 배치·12개 표적·화살 속도는 재구성 수치입니다.',
 'Cannonball!':'원작 준비시간 4초 동안 손잡이 회전 후 비행 거리를 비교합니다. 방향키 원운동 또는 대포 중심을 돌아가는 포인터 드래그가 실제 누적 회전으로 판정됩니다. 회전 방향은 모두 허용. 거리 70+55×회전수 및 비행 연출 4초는 재구성 계수입니다.',
 'Goomba to Maneuver':'원작 열 마리 행렬·좌우 이동·자동 전진·꽃에 닿은 추종자 탈락·뒤쪽 빈틈 메우기·본체 충돌 시 밀림과 정지. 전원이 완주하거나 행렬을 잃으면 남은 수로 판정하고 전원 0마리면 무승부. 추종자는 실제 지나온 경로를 따릅니다. 꽃 배치·80단위 코스는 재구성했습니다.',
 'Kabob and Weave':'방향 이동·A 점프. 원작 다섯 꼬치를 피하는 60초 생존 경기. 꼬치가 몸에 닿으면 탈락하며 마지막 생존자 또는 종료 시 생존자 승리. 경고 표시, 꼬치 배치·속도·높이는 재구성했습니다.',
 'Tanks a Lot':'방향키 전차 이동 및 포신 방향, A 발사. 파괴 가능한 갈색 벽과 상대 전차 명중을 판정하며 맞은 전차는 재출발합니다. 먼저 상대 세 번 명중 승리. 재생성 무적 1.2초·발사 간격·벽 배치는 새 수치이며 제한시간은 확인되지 않아 두지 않았습니다.',
 'Xylophone Home':'터치 건반을 A/B/C/D 네 키와 1P 클릭으로 옮겼습니다. 실제 음표가 판정선에 닿는 시간과 입력을 비교하여 정확 2점·근접 1점. 판정 폭 0.10/0.23초·24음 차트는 재구성이며 원작 멜로디 대신 새로 만든 생성 단음을 사용합니다.',
 'Spin the Bubble':'원작 실루엣에 입체 캡슐 방향을 맞추기, 세 라운드 순위별 9·6·3·0점. 기울이기 입력은 방향키의 두 축 회전과 A/B의 세 번째 축 회전으로 대체했습니다. 각 라운드 20초, 모형 한 개, 방향 오차 0.18 및 0.3초 유지 판정으로 재구성했으며 이 세부 수치는 원작 확인값이 아닙니다.',
 'Rat-a-tat Flat':'원작 30초, 생쥐 1점·금 생쥐 3점. 방향 이동·A 점프 후 공중 A/B 엉덩이 찍기. 구멍 사이를 실제 이동하는 생쥐에게 착지해야 득점합니다. 구멍 배치·출현 간격은 재구성했습니다.',
 "Hide 'n' Splat":'원작 60초 이동 전용 회피. 굴러 착지하는 상자에 깔리면 탈락하고 마지막 생존자 또는 시간 종료 생존자 승리. 시간이 지나면서 상자 수와 굴림 속도가 증가합니다. 상자 경로·최대 여섯 개·예고 표시·충돌 범위는 재구성했습니다.',
 'Slow Glide':'자동 활공 중 기울이기는 방향키 좌우·상하 조종으로 대체했습니다. 자기 색 풍선 1점, 상하로 움직이는 금 풍선 3점. 다른 색 풍선은 득점되지 않습니다. 80개 풍선과 155단위 코스는 재구성이며 원작 제한시간을 뜻하지 않습니다.',
 'Sub Trouble':'원작 자동 전진 잠수함의 높이만 ↑/↓로 조절하고 먼저 출구에 도착하면 승리합니다. 바위 충돌은 지연을 발생시킵니다. 코스 125단위·장애물 22개·충돌 감속 1.5초는 재구성. 고정 제한시간 없이 결승까지 경주합니다.',
 'Peep a Peepa':'원작 30초·계속 비추면 반복 득점·유령당 다섯 번 비추면 사라짐. 기울이기 조준은 방향키/포인터로 대체. 버튼 없이 자동 조명이며 0.25초 간격 판정·유령 경로·출현 간격은 재구성했습니다.',
 'Puzzle Pronto':'네 유형 중 모두에게 같은 유형을 무작위로 선택. 버섯 5/6/8개 클릭, 그림자 2/3·3/4·4/6개 실제 드래그, 두 파이프 고리의 직선/굽은/분기 연결 회전, 숫자 4/6/9개 오름차순. 1P 포인터, 방향+A 가상 커서. 고리는 B 선택 후 방향 원운동 또는 드래그. 먼저 세 단계 완성 승리. 도안·경로·각도 허용 오차는 새 구성입니다.',
 "Truckin' and Cluckin'":'원작 30초·잡은 닭이 알을 낳으면 1점·금색 닭은 2점·알이 소진되면 떠남. 방향 이동, A 근처 닭 잡기/전방 몸통박치기로 보유자에게서 빼앗기. 닭별 알 7/5개, 0.8초 산란·0.75초 돌진 간격은 재구성 수치입니다.',
 'Get Reel':'원작 세 필름 라운드·20초·맞는 장면 A 확인·오답 정지·순위 9/6/3/0점. 방향 원운동/손잡이 드래그로 되감기하며 B/C 한 프레임 보조 조작. 세 장면은 자체 3D 연출로 재제작, 31단계의 같은 그림을 정확히 찾게 했습니다. 오답 정지 0.7초·프레임 수는 재구성 수치입니다.'
};
