import{clamp,dist,toward}from'../core.js';
const PINK='#ed91aa',BLUE='#76b9da',GOLD='#ebc362',GREEN='#8abf97',keys=['a','b','c','d'];
const box=(c,id,x,y,z,sx,sy,sz,color,more={})=>c.draw(id,'box',{x,y,z,sx,sy,sz,color,...more});
const ball=(c,id,x,y,z,s,color,more={})=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color,...more});
const text=(c,id,label,x=0,y=1,z=0,size=3,color='#294652')=>c.draw(id,'text',{text:String(label),x,y,z,sx:size,sy:size/4,color});
const diff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function setup(c,limit=Infinity){c.limit=limit;c.activePlayers=[0,1,2,3];return c.players;}
function high(c,reason){const top=Math.max(...c.players.map(p=>p.score)),w=c.players.filter(p=>p.score===top);c.complete(w.length===4?[]:w.map(p=>p.i),reason);}
const layouts=[{x:-6,z:-5},{x:6,z:-5},{x:-6,z:5},{x:6,z:5}];
function boards(c){c.view={size:28,eye:[0,30,24],target:[0,0,0]};c.players.forEach((p,i)=>{p.x=layouts[i].x;p.z=layouts[i].z+3.8;p.scale=.6;});}
function board(c,i,label){const a=layouts[i];box(c,`board-${i}`,a.x,-.2,a.z,11,.3,8.5,'#e7edd8');text(c,`board-title-${i}`,label,a.x,.5,a.z-3.6,7,c.players[i].color);}
function gesture(c,s,input,a,rx=4.7,rz=3){const ptr=input.pointer;let down;if(ptr.worldValid){s.cx=ptr.worldX;s.cz=ptr.worldZ;down=ptr.down;}else{s.cx=clamp(s.cx+input.x*c.dt*7,a.x-rx,a.x+rx);s.cz=clamp(s.cz+input.z*c.dt*7,a.z-rz,a.z+rz);down=input.a;}const g={x:s.cx,z:s.cz,down,pressed:down&&!s.down,released:!down&&!!s.down,dx:down&&s.down?s.cx-s.px:0,dz:down&&s.down?s.cz-s.pz:0};s.down=down;s.px=s.cx;s.pz=s.cz;return g;}
function line(c,id,a,b,color,width=.1,y=.1){const d=dist(a,b);box(c,id,(a.x+b.x)/2,y,(a.z+b.z)/2,d,.08,width,color,{ry:-Math.atan2(b.z-a.z,b.x-a.x)});}
function rotateInput(s,input,a){let angle=null;const p=input.pointer;if(p.down&&p.worldValid&&Math.hypot(p.worldX-a.x,p.worldZ-a.z)>.3)angle=Math.atan2(p.worldZ-a.z,p.worldX-a.x);else if(Math.hypot(input.x,input.z)>.4)angle=Math.atan2(input.z,input.x);let d=0;if(angle!==null&&s.lastAngle!==null&&s.lastAngle!==undefined){const q=diff(angle,s.lastAngle);if(Math.abs(q)<2)d=q;}s.lastAngle=angle;return d;}

function acorn(c){
 const players=setup(c,Infinity),enemies=Array.from({length:18},(_,j)=>({x:j%2?-9:9,z:15-j*2,dir:j%2?1:-1,phase:c.rand(0,5)})),state=players.map(()=>({inv:0,done:false,lead:c.rand(1.2,2.5)}));players.forEach((p,i)=>{p.x=(i-1.5)*2;p.z=20;p.score=5;});c.view={size:59,eye:[0,48,41],target:[0,0,0]};
 return{update(dt){c.hint('방향키로 길을 건너며 도토리 다섯 개를 지키세요. 돌진에 맞으면 하나 잃습니다. 전원 종료 후 남은 도토리 수 비교!');enemies.forEach((e,j)=>{e.x=-e.dir*9+e.dir*((c.time*3+e.phase*3)%18);});players.filter(p=>p.alive).forEach(p=>{const s=state[p.i],input=c.input(p,()=>{const nearby=enemies.filter(e=>Math.abs(e.z-p.z)<s.lead),danger=nearby.sort((a,b)=>dist(p,a)-dist(p,b))[0];let x=0;if(danger&&Math.abs(danger.x-p.x)<2.5)x=clamp((p.x-danger.x)*1.5,-1,1)||-danger.dir;return{x,z:-1};});s.inv=Math.max(0,s.inv-dt);if(!s.done){c.move(p,input,3.3,false);p.x=clamp(p.x,-5.5,5.5);p.z=clamp(p.z,-20,21);if(!s.inv&&enemies.some(e=>dist(p,e)<1)){p.score--;s.inv=1.2;p.z+=.65;if(p.score===0){c.eliminate(p);s.done=true;}}if(p.z<=-20)s.done=true;}});for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=players[i],b=players[j],d=dist(a,b);if(a.alive&&b.alive&&!state[i].done&&!state[j].done&&d<1.1&&d>.01){const v=toward(a,b.x,b.z);a.x-=v.x*(1.1-d)*.5;a.z-=v.z*(1.1-d)*.5;b.x+=v.x*(1.1-d)*.5;b.z+=v.z*(1.1-d)*.5;}}if(state.every(s=>s.done)){const best=Math.max(...players.map(p=>p.score));c.complete(best?players.filter(p=>p.score===best).map(p=>p.i):[],'끝까지 지킨 도토리 수');}
 },render(){box(c,'acorn-road',0,-.3,0,13,.5,44,'#c9bc92');box(c,'acorn-finish',0,.02,-20,13,.06,.4,GOLD);enemies.forEach((e,j)=>{ball(c,`goombrat-${j}`,e.x,.6,e.z,1.2,'#b8956d');box(c,`goombrat-brow-${j}`,e.x,1.1,e.z,.9,.15,.35,'#5f524c');});players.forEach(p=>{box(c,`acorn-plate-${p.i}`,p.x,1.4,p.z-.5,1.6,.12,1,p.color);for(let j=0;j<p.score;j++)ball(c,`acorn-${p.i}-${j}`,p.x+(j-2)*.25,1.6,p.z-.5,.25,GOLD);});}};
}
function corkscrew(c){
 const players=setup(c,Infinity),order=c.shuffle([0,1,2,3]),amps=Array.from({length:16},(_,j)=>9+j*6.4),state=players.map((p,i)=>({d:order.indexOf(i)*-.7,h:0,vy:0,stun:0,hit:new Set(),reaction:c.rand(.9,1.8)}));
 const pos=d=>({x:Math.cos(d/5)*6,z:Math.sin(d/5)*6,y:d*.13});
 return{update(dt){c.hint('자동으로 나선 길을 달립니다. A로 앞의 전기 구슬을 뛰어넘으세요. 먼저 꼭대기에 도착하면 승리!');players.forEach((p,i)=>{const s=state[i],next=amps.find(a=>a>s.d-.3),input=c.input(p,()=>({a:next!==undefined&&next-s.d<s.reaction&&s.h===0}));s.stun=Math.max(0,s.stun-dt);if(!s.stun)s.d+=dt*4.6;if(input.ap&&s.h===0){s.h=.001;s.vy=7;}if(s.h>0){s.vy-=18*dt;s.h=Math.max(0,s.h+s.vy*dt);}amps.forEach((a,j)=>{if(!s.hit.has(j)&&Math.abs(s.d-a)<.45&&s.h<.9){s.hit.add(j);s.stun=.85;}});const q=pos(s.d);p.x=q.x;p.z=q.z;p.y=q.y+s.h;p.score=s.d;p.rotation=-s.d/5-Math.PI/2;});c.view={size:30,eye:[20,25,27],target:[0,6,0]};const done=players.filter(p=>p.score>=115);if(done.length)c.complete(done.map(p=>p.i),'나선 경주 정상 도착');
 },render(){for(let j=0;j<60;j++){const q=pos(j*2);box(c,`spiral-ramp-${j}`,q.x,q.y-.18,q.z,2,.35,2,'#b0cbab',{ry:-j*2/5});}amps.forEach((a,j)=>{const q=pos(a);ball(c,`spiral-amp-${j}`,q.x,q.y+.45,q.z,.8,BLUE);});}};
}
function cake(c){
 const players=setup(c,Infinity);boards(c);let round=0,start=0,fruits=[],wanted=0;const state=players.map((p,i)=>({cx:layouts[i].x,cz:layouts[i].z-1.5,stroke:null,cut:null,memory:0,delay:c.rand(.4,1.1),phase:0}));
 const colors=[PINK,GOLD,GREEN],labels=['딸기','레몬','키위'];
 function begin(){start=c.time;fruits=c.shuffle([[0],[1],[2],[0,1],[0,2],[1,2]]);wanted=c.int(0,5);state.forEach(s=>{s.cut=null;s.stroke=null;s.phase=0;s.memory=c.rng()<.85?wanted:c.int(0,5);s.down=false;});}begin();
 return{update(dt){const age=c.time-start;c.hint(age<10?`${round+1}/3회 · ${Math.ceil(10-age)}초 동안 과일 위치를 기억하세요.`:`기준 조각과 같은 위치를 세로로 잘라 주세요. 드래그 또는 A를 누른 채 ↓ · ${Math.max(0,Math.ceil(20-age))}초`);players.forEach((p,i)=>{const s=state[i],a=layouts[i],input=c.input(p,()=>{if(age<10+s.delay||s.cut!==null)return{};const x=a.x+(s.memory-2.5)*1.35,z=a.z+(s.phase===0?-1.4:1.4),v=toward({x:s.cx,z:s.cz},x,z),d=Math.min(dist({x:s.cx,z:s.cz},{x,z}),dt*10);let down=s.phase===1;if(s.phase===0&&Math.hypot(s.cx-x,s.cz-z)<.04){s.phase=1;down=true;}else if(s.phase===1&&Math.hypot(s.cx-x,s.cz-z)<.04){down=false;s.phase=2;}return{pointer:{valid:true,worldValid:true,worldX:s.cx+v.x*d,worldZ:s.cz+v.z*d,down}};});const g=gesture(c,s,input,a);if(age>=10&&s.cut===null){if(g.pressed&&g.z<a.z-.8)s.stroke={x:g.x,z:g.z,endX:g.x,endZ:g.z};if(s.stroke&&g.down){s.stroke.endX=g.x;s.stroke.endZ=g.z;}if(g.released&&s.stroke){const t=s.stroke;if(t.endZ>a.z+.8&&Math.abs(t.endX-t.x)<.5){const index=Math.round(((t.x+t.endX)/2-a.x)/1.35+2.5);if(index>=0&&index<6){s.cut=index;if(index===wanted)c.points(p);}}s.stroke=null;}}});if(age>=20||age>=10&&state.every(s=>s.cut!==null)){round++;if(round===3)high(c,'세 번의 과일 기억');else begin();}
 },render(){const age=c.time-start;players.forEach((p,i)=>{const a=layouts[i],s=state[i];board(c,i,age<10?'기억하기':'과일 위치 잘라내기');box(c,`cake-base-${i}`,a.x,.2,a.z,8.5,.5,2.4,'#e7c28e');box(c,`cake-cream-${i}`,a.x,.51,a.z,8.5,.15,2.4,'#f2ebd5');for(let j=0;j<6;j++){const x=a.x+(j-2.5)*1.35;if(age<10)fruits[j].forEach((f,k)=>ball(c,`cake-fruit-${i}-${j}-${k}`,x+(k-(fruits[j].length-1)/2)*.4,.85,a.z,.45,colors[f]));if(s.cut===j)box(c,`cake-cut-${i}`,x,.65,a.z,.05,.08,2.6,p.color);}if(age>=10){text(c,`cake-target-${i}`,fruits[wanted].map(f=>labels[f]).join(' + '),a.x,1,a.z-2.4,5);fruits[wanted].forEach((f,k)=>ball(c,`target-fruit-${i}-${k}`,a.x+(k-.5)*.6,.3,a.z+2.5,.45,colors[f]));}if(s.stroke&&s.down)line(c,`knife-${i}`,s.stroke,{x:s.cx,z:s.cz},p.color,.08,.8);});}};
}
function mazeMap(rows,scale){const nodes=[],index=new Map();rows.forEach((r,z)=>[...r].forEach((v,x)=>{if(v!== '#'){index.set(`${x},${z}`,nodes.length);nodes.push({x:(x-(r.length-1)/2)*scale,z:(z-(rows.length-1)/2)*scale,cx:x,cz:z,neighbors:[]});}}));nodes.forEach(n=>{for(const[dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const j=index.get(`${n.cx+dx},${n.cz+dz}`);if(j!==undefined)n.neighbors.push(j);}});const closest=p=>nodes.reduce((best,n,i)=>dist(p,n)<dist(p,nodes[best])?i:best,0),path=(from,to)=>{const q=[from],prev=new Map([[from,null]]);for(let h=0;h<q.length;h++){const k=q[h];if(k===to)break;nodes[k].neighbors.forEach(n=>{if(!prev.has(n)){prev.set(n,k);q.push(n);}});}if(!prev.has(to))return from;let k=to;while(prev.get(k)!==from&&prev.get(k)!==null)k=prev.get(k);return k;},walkable=p=>{const x=Math.round(p.x/scale+(rows[0].length-1)/2),z=Math.round(p.z/scale+(rows.length-1)/2);return rows[z]?.[x]!==undefined&&rows[z][x]!=='#';};return{nodes,index,closest,path,walkable};}
function lavaMaze(c){
 const players=setup(c,Infinity),rows=['###########','#...#.....#','#.#.#.###.#','#.#...#...#','#.###.#.#.#','#...#...#.#','###.#####.#','#.........#','###########'],map=mazeMap(rows,2),ends=[[1,1],[9,1],[1,5],[9,7]].map(([x,z])=>map.index.get(`${x},${z}`)),values=c.shuffle([3,2,1,0]),chests=ends.map((node,i)=>({node,value:values[i],taken:false})),state=players.map(()=>({stun:0,done:false,waypoint:null,pace:c.rand(.75,1)})),danger=[7,14,21,29].map(j=>({node:j%map.nodes.length,phase:c.rand(0,5)}));players.forEach((p,i)=>{const q=map.nodes[map.index.get('5,7')];p.x=q.x+(i-1.5)*.2;p.z=q.z;p.scale=.65;});c.view={size:29,eye:[0,30,22],target:[0,0,0]};
 return{update(dt){c.hint('고정 미로에서 가장 큰 금 상자를 먼저 찾으세요. 상자 위치는 매 경기 바뀌며 용암 괴물은 잠시 멈추게 합니다.');players.forEach((p,i)=>{const s=state[i],gold=chests.find(t=>t.value===3),from=map.closest(p),input=c.input(p,()=>{if(s.waypoint===null)s.waypoint=from;if(dist(p,map.nodes[s.waypoint])<.2)s.waypoint=map.path(s.waypoint,gold.node);const q=map.nodes[s.waypoint];return toward(p,q.x,q.z,s.pace);});s.stun=Math.max(0,s.stun-dt);if(s.stun||s.done)return;const old={x:p.x,z:p.z};c.move(p,input,4,false);if(!map.walkable(p)){p.x=old.x;p.z=old.z;}danger.forEach(d=>{if((c.time+d.phase)%4<1&&dist(p,map.nodes[d.node])<.75)s.stun=.7;});const chest=chests.find(t=>!t.taken&&dist(p,map.nodes[t.node])<.75);if(chest){chest.taken=true;s.done=true;p.score=chest.value;if(chest.value===3)c.complete([p.i],'가장 큰 금 상자 발견');}});
 },render(){box(c,'lava',0,-.4,0,24,.2,20,'#df784e');map.nodes.forEach((n,j)=>box(c,`maze-path-${j}`,n.x,-.12,n.z,1.9,.25,1.9,'#788b8c'));chests.forEach((t,j)=>{if(!t.taken){const q=map.nodes[t.node];box(c,`treasure-${j}`,q.x,.45,q.z,.7+t.value*.2,.8,.7+t.value*.2,[BLUE,'#ac865e','#c5d0cd',GOLD][t.value]);}});danger.forEach((d,j)=>{if((c.time+d.phase)%4<1){const q=map.nodes[d.node];ball(c,`magma-${j}`,q.x,.8,q.z,1.3,'#e67e47');}});}};
}

function piranha(c){
 const players=setup(c,30),plants=[],bullets=[],state=players.map(()=>({u:0,stun:0,cool:0})),sides=[{x:0,z:8,dx:0,dz:-1,tx:1,tz:0},{x:0,z:-8,dx:0,dz:1,tx:1,tz:0},{x:-8,z:0,dx:1,dz:0,tx:0,tz:1},{x:8,z:0,dx:-1,dz:0,tx:0,tz:1}];let next=.2,id=0,bid=0,big=false;
 return{update(dt){c.hint('← →로 레일 이동 · A 발사. 일반 1점·금 3점·거대 금색의 마지막 명중 10점. 상대 탄환에 맞으면 잠시 멈춥니다.');if(c.time>=next){const gold=c.rng()<.25;plants.push({id:id++,x:c.rand(-5.2,5.2),z:c.rand(-5.2,5.2),hp:1,value:gold?3:1,big:false});next=c.time+.65;}if(!big&&c.time>=13){big=true;plants.push({id:id++,x:0,z:0,hp:6,value:10,big:true});}players.forEach((p,i)=>{const s=state[i],a=sides[i],target=plants.filter(q=>q.hp>0).sort((u,v)=>v.value-u.value||Math.abs(u.x*a.tx+u.z*a.tz-s.u)-Math.abs(v.x*a.tx+v.z*a.tz-s.u))[0],input=c.input(p,()=>target?{x:clamp(((target.x-a.x)*a.tx+(target.z-a.z)*a.tz-s.u)*3,-1,1),a:Math.abs((target.x-a.x)*a.tx+(target.z-a.z)*a.tz-s.u)<.5&&s.cool<=0}:{});s.cool-=dt;s.stun=Math.max(0,s.stun-dt);if(!s.stun){s.u=clamp(s.u+input.x*dt*5.5,-6.7,6.7);if(input.ap&&s.cool<=0){s.cool=.3;bullets.push({id:bid++,owner:i,x:a.x+a.tx*s.u+a.dx,z:a.z+a.tz*s.u+a.dz,vx:a.dx*14,vz:a.dz*14,live:true});}}p.x=a.x+a.tx*s.u;p.z=a.z+a.tz*s.u;p.rotation=Math.atan2(-a.dz,a.dx);});bullets.forEach(b=>{if(!b.live)return;b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>10||Math.abs(b.z)>10)b.live=false;const plant=plants.find(q=>q.hp>0&&dist(b,q)<(q.big?1.15:.65));if(plant){plant.hp--;b.live=false;if(plant.hp===0)c.points(players[b.owner],plant.value);}if(b.live){const hit=players.find(p=>p.i!==b.owner&&dist(p,b)<.75);if(hit){state[hit.i].stun=2;b.live=false;}}});
 },render(){c.arena({width:19,depth:19,color:'#aac89b'});plants.filter(q=>q.hp>0).forEach(q=>{c.draw(`plant-pipe-${q.id}`,'cylinder',{x:q.x,y:.2,z:q.z,sx:q.big?1.5:.8,sy:.5,sz:q.big?1.5:.8,color:GREEN});ball(c,`plant-head-${q.id}`,q.x,q.big?1.5:1,q.z,q.big?2:1,q.value>1?GOLD:PINK);if(q.big)text(c,'giant-plant-hp',`HP ${q.hp}`,q.x,3,q.z,3);});players.forEach((p,i)=>box(c,`plant-cannon-${i}`,p.x,.6,p.z,1.5,.6,.7,p.color,{ry:p.rotation}));bullets.filter(b=>b.live).forEach(b=>ball(c,`plant-bullet-${b.id}`,b.x,.8,b.z,.3,players[b.owner].color));},timeout(){high(c,'30초 꽃 사격 점수');}};
}
function jumpConclusion(c){
 const players=setup(c,Infinity),danger=new Set([4,8,13,17,22,26,31,35,40,43]),state=players.map(()=>({step:0,from:0,to:0,t:0,duration:0,stun:0,delay:c.rand(.04,.18),next:0}));
 return{update(dt){c.hint('A 한 칸 점프 · B 두 칸 점프. 덩굴 꽃이 있는 계단에 착지하면 지연됩니다. 45계단 먼저 완주!');players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>s.duration||s.stun||c.time<s.next?{}:danger.has(s.step+2)?{a:true}:{b:true});s.stun=Math.max(0,s.stun-dt);if(!s.duration&&!s.stun&&(input.ap||input.bp)){s.from=s.step;s.to=Math.min(45,s.step+(input.bp?2:1));s.duration=input.bp?.75:.5;s.t=0;}let loc=s.step,h=0;if(s.duration){s.t+=dt;const t=Math.min(1,s.t/s.duration);loc=s.from+(s.to-s.from)*t;h=Math.sin(t*Math.PI)*(s.to-s.from===2?1.3:.9);if(t>=1){s.step=s.to;s.duration=0;s.next=c.time+s.delay;if(danger.has(s.step))s.stun=1.1;}}p.x=(i-1.5)*4;p.z=-loc*.65;p.y=loc*.28+h;p.score=s.step;});const lead=Math.max(...state.map(s=>s.step));c.view={size:28,eye:[19,lead*.28+21,-lead*.65+22],target:[0,lead*.28,-lead*.65-1]};const done=players.filter(p=>p.score>=45);if(done.length)c.complete(done.map(p=>p.i),'45계단 정상 도착');
 },render(){players.forEach((p,i)=>{const x=(i-1.5)*4;for(let j=0;j<=45;j++){box(c,`stair-${i}-${j}`,x,j*.28-.18,-j*.65,3.5,.35,.7,j===45?GOLD:'#b9caae');if(danger.has(j)){ball(c,`creeper-${i}-${j}`,x,j*.28+.35,-j*.65,.8,PINK);box(c,`creeper-stem-${i}-${j}`,x,j*.28+.05,-j*.65,.2,.4,.2,GREEN);}}});}};
}
function wigglin(c){
 const players=setup(c,30),state=players.map((p,i)=>({a:i*Math.PI/2,count:5,history:[],body:[],cool:0,dash:0,hit:new Set()}));players.forEach((p,i)=>{p.x=Math.cos(i*Math.PI/2)*5;p.z=Math.sin(i*Math.PI/2)*5;p.score=5;});
 return{update(dt){c.hint('방향키로 차의 방향을 바꾸고 A로 돌진. 돌진 재사용은 2초 후. 상대 몸통을 줄이고 내 몸통을 지키세요!');players.filter(p=>p.alive).forEach(p=>{const s=state[p.i],target=players.filter(q=>q!==p&&q.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>target?{...toward(p,target.x,target.z),a:s.cool<=0&&dist(p,target)<4&&c.rng()<.1}:{});s.cool=Math.max(0,s.cool-dt);s.dash=Math.max(0,s.dash-dt);if(Math.hypot(input.x,input.z)>.1){const a=Math.atan2(input.z,input.x);s.a+=clamp(diff(a,s.a),-dt*4,dt*4);}if(input.ap&&s.cool<=0){s.cool=2;s.dash=.35;s.hit.clear();}const speed=s.dash?11:3;p.x+=Math.cos(s.a)*speed*dt;p.z+=Math.sin(s.a)*speed*dt;const r=Math.hypot(p.x,p.z);if(r>8){p.x*=8/r;p.z*=8/r;s.a=Math.atan2(-p.z,-p.x);}const last=s.history.at(-1);if(!last||dist(last,p)>.08)s.history.push({x:p.x,z:p.z});let length=0;s.body=[];for(let k=s.history.length-1;k>0&&s.body.length<s.count;k--){length+=dist(s.history[k],s.history[k-1]);if(length>=(s.body.length+1)*.75)s.body.push(s.history[k-1]);}if(s.history.length>300)s.history.splice(0,s.history.length-300);p.rotation=-s.a;p.score=s.count;});const hits=[];players.filter(p=>p.alive&&state[p.i].dash>0).forEach(p=>{const s=state[p.i];players.forEach(q=>{if(q!==p&&q.alive&&!s.hit.has(q.i)&&[q,...state[q.i].body].some(t=>dist(p,t)<.85)){s.hit.add(q.i);hits.push(q.i);}});});hits.forEach(i=>{const s=state[i];s.count=Math.max(0,s.count-1);players[i].score=s.count;if(!s.count)c.eliminate(players[i]);});c.lastStanding();
 },render(){c.draw('wiggler-arena','cylinder',{x:0,y:-.3,z:0,sx:18,sy:.5,sz:18,color:'#b4c89e'});players.filter(p=>p.alive).forEach(p=>{const s=state[p.i];ball(c,`wiggler-head-${p.i}`,p.x,.35,p.z,1,p.color);s.body.slice(0,s.count).forEach((q,j)=>ball(c,`wiggler-body-${p.i}-${j}`,q.x,.3,q.z,.85,p.color));if(s.dash>0)text(c,`boost-${p.i}`,'➤',p.x,2,p.z,2,GOLD);});},timeout(){high(c,'남아 있는 차량 몸통 수');}};
}

function blowboat(c){
 const players=setup(c,Infinity),floaties=Array.from({length:10},(_,j)=>({x:c.rand(-6,6),z:14-j*3.6})),fish=Array.from({length:6},(_,j)=>({x:0,z:12-j*6,phase:c.rand(0,6)})),state=players.map(()=>({inv:0}));players.forEach((p,i)=>{p.x=(i-1.5)*2.7;p.z=21;});c.view={size:56,eye:[0,45,39],target:[0,0,0]};
 return{update(dt){c.hint('A를 누르고 방향키로 바람을 불어 보트를 미세요. 원작 마이크 불기를 키로 바꿨습니다. 장난감 물고기와 튜브에 부딪히면 튕깁니다.');fish.forEach(f=>f.x=Math.sin(c.time*1.1+f.phase)*6.5);players.forEach((p,i)=>{const s=state[i],obstacles=[...floaties,...fish],input=c.input(p,()=>{const q=obstacles.filter(q=>q.z<p.z&&q.z>p.z-5).sort((a,b)=>dist(p,a)-dist(p,b))[0];return{x:q&&Math.abs(p.x-q.x)<2?clamp((p.x-q.x)*2,-1,1)||1:clamp(-p.x*.25,-1,1),z:-1,a:true};});s.inv=Math.max(0,s.inv-dt);if(input.a){const v=Math.hypot(input.x,input.z)||1;p.vx+=input.x/v*dt*7;p.vz+=input.z/v*dt*7;}p.vx*=Math.pow(.97,dt*60);p.vz*=Math.pow(.97,dt*60);const speed=Math.hypot(p.vx,p.vz);if(speed>6){p.vx*=6/speed;p.vz*=6/speed;}p.x=clamp(p.x+p.vx*dt,-7,7);p.z=clamp(p.z+p.vz*dt,-22,23);if(!s.inv&&obstacles.some(q=>dist(p,q)<1.25)){const angle=c.rand(0,Math.PI*2);p.vx=Math.cos(angle)*5;p.vz=Math.sin(angle)*5;s.inv=.6;}p.score=21-p.z;p.rotation=Math.atan2(-p.vz,p.vx);});const done=players.filter(p=>p.z<=-22);if(done.length)c.complete(done.map(p=>p.i),'바람 보트 결승 도착');
 },render(){box(c,'bathtub',0,-.3,0,17,.5,49,'#79b7c9');box(c,'boat-finish',0,.02,-22,17,.05,.4,GOLD);floaties.forEach((q,j)=>c.draw(`floatie-${j}`,'ring',{x:q.x,y:.2,z:q.z,sx:2,sy:2,rx:-Math.PI/2,color:[PINK,GOLD,GREEN][j%3]}));fish.forEach((f,j)=>ball(c,`toy-fish-${j}`,f.x,.3,f.z,1.4,PINK,{sx:1.8,sy:.65}));players.forEach(p=>{box(c,`blowboat-${p.i}`,p.x,.15,p.z,1.3,.3,1.8,p.color);box(c,`boat-sail-${p.i}`,p.x,1,p.z,.1,1.6,.8,'#efeada');});}};
}
function bumperBugs(c){
 const players=setup(c,Infinity),flags=Array.from({length:8},(_,j)=>({x:Math.cos(j*Math.PI/4)*6,z:Math.sin(j*Math.PI/4)*4})),urchins=Array.from({length:5},(_,j)=>({x:Math.cos(j*1.9)*3.5,z:Math.sin(j*1.9)*2.4,phase:c.rand(0,6)})),state=players.map(()=>({flags:new Set(),cx:0,cz:0,start:null,stun:0,inv:0,phase:0,cool:0,pace:c.rand(.8,1.2)}));players.forEach((p,i)=>{p.x=(i-1.5)*1.2;p.z=0;});
 return{update(dt){c.hint('기계 벌레를 탭한 뒤 원하는 방향으로 밀어 떼세요. 키보드는 방향+A 가상 드래그. 여덟 깃발을 모두 통과하면 승리!');players.forEach((p,i)=>{const s=state[i],available=flags.map((q,j)=>({...q,j})).filter(q=>!s.flags.has(q.j)),target=available.sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>{if(!target||s.stun||s.cool>0)return{};const v=toward(p,target.x,target.z),end={x:p.x+v.x*2,z:p.z+v.z*2};if(s.phase===0){s.phase=1;return{pointer:{valid:true,worldValid:true,worldX:p.x,worldZ:p.z,down:true}};}if(s.phase===1){s.phase=2;return{pointer:{valid:true,worldValid:true,worldX:end.x,worldZ:end.z,down:true}};}s.phase=0;s.cool=.35*s.pace;return{pointer:{valid:true,worldValid:true,worldX:end.x,worldZ:end.z,down:false}};});s.stun=Math.max(0,s.stun-dt);s.inv=Math.max(0,s.inv-dt);s.cool=Math.max(0,s.cool-dt);const g=gesture(c,s,input,{x:0,z:0},9,6);if(g.pressed&&dist(g,p)<1.5)s.start={x:g.x,z:g.z};if(g.released&&s.start){const dx=g.x-s.start.x,dz=g.z-s.start.z,len=Math.hypot(dx,dz);if(len>.25&&!s.stun){const impulse=Math.min(8,len*3);p.vx=dx/len*impulse;p.vz=dz/len*impulse;}s.start=null;}if(!s.stun){p.x=clamp(p.x+p.vx*dt,-8,8);p.z=clamp(p.z+p.vz*dt,-5.5,5.5);}p.vx*=Math.pow(.977,dt*60);p.vz*=Math.pow(.977,dt*60);flags.forEach((q,j)=>{if(dist(p,q)<.8)s.flags.add(j);});urchins.forEach(q=>{const pos={x:q.x+Math.sin(c.time+q.phase)*.6,z:q.z};if(!s.inv&&dist(p,pos)<1){s.stun=.8;s.inv=1.6;p.vx=p.vz=0;}});p.score=s.flags.size;});const done=players.filter(p=>p.score===8);if(done.length)c.complete(done.map(p=>p.i),'여덟 깃발 모두 통과');
 },render(){c.arena({width:19,depth:14,color:'#81bdce'});flags.forEach((q,j)=>{box(c,`buoy-${j}`,q.x,.15,q.z,.7,.3,.7,'#e9e6cc');box(c,`flag-pole-${j}`,q.x,1,q.z,.07,1.8,.07,'#52717b');for(let i=0;i<4;i++)box(c,`flag-check-${j}-${i}`,q.x+.15+i*.16,1.7,q.z,.13,.35,.08,state[i].flags.has(j)?players[i].color:'#738d93');});urchins.forEach((q,j)=>{ball(c,`bug-urchin-${j}`,q.x+Math.sin(c.time+q.phase)*.6,.5,q.z,1.3,'#6b608f');});players.forEach(p=>{ball(c,`skeeter-${p.i}`,p.x,.25,p.z,1.1,p.color,{sy:.4});for(let j=-1;j<=1;j+=2)box(c,`skeeter-leg-${p.i}-${j}`,p.x+j*.6,.12,p.z,.8,.1,1.6,p.color);});}};
}
function splat(c){
 const players=setup(c,30),kind=c.int(0,2),W=25,H=19,size=.5,cells=[],shots=[],corners=[{x:-8,z:7},{x:8,z:7},{x:-8,z:-7},{x:8,z:-7}],state=players.map((p,i)=>({cx:corners[i].x,cz:corners[i].z,start:null,aim:null,phase:0,cool:0,pace:c.rand(.4,.7)}));let id=0;
 function mask(x,z){if(kind===0)return Math.abs(x)<5&&Math.abs(z)<2.6||Math.hypot(x+4,z)<2.6;if(kind===1)return Math.hypot(x,z)<4.3||Math.abs(x)<1.1&&z< -3&&z> -4.8;return Math.abs(x)<3.4&&z>-3.2&&z<3.5||Math.hypot(x,z+2.5)<3.4;}
 for(let z=0;z<H;z++)for(let x=0;x<W;x++){const wx=(x-(W-1)/2)*size,wz=(z-(H-1)/2)*size;if(mask(wx,wz))cells.push({x:wx,z:wz,owner:null});}
 const landing=(s,a,g)=>({x:clamp(a.x+(a.x-g.x)*2,-6,6),z:clamp(a.z+(a.z-g.z)*2,-4.8,4.8)});
 return{update(dt){c.hint('내 색 공을 잡아 아래/바깥쪽으로 당겼다 놓으세요. 당김 반대 방향으로 잉크가 날아갑니다. 다른 색을 덮어 가장 넓게 칠하면 승리!');players.forEach((p,i)=>{const s=state[i],a=corners[i],input=c.input(p,()=>{if(s.cool>0)return{};if(s.phase===0){const targets=cells.filter(q=>q.owner!==i);s.aim=c.pick(targets.length?targets:cells);s.phase=1;return{pointer:{valid:true,worldValid:true,worldX:a.x,worldZ:a.z,down:true}};}const q={x:a.x+(a.x-s.aim.x)/2,z:a.z+(a.z-s.aim.z)/2};if(s.phase===1){s.phase=2;return{pointer:{valid:true,worldValid:true,worldX:q.x,worldZ:q.z,down:true}};}s.phase=0;s.cool=s.pace;return{pointer:{valid:true,worldValid:true,worldX:q.x,worldZ:q.z,down:false}};});s.cool=Math.max(0,s.cool-dt);const g=gesture(c,s,input,a,7,7);if(g.pressed&&dist(g,a)<1)s.start={x:g.x,z:g.z};if(g.released&&s.start){if(dist(g,s.start)>.4){const q=landing(s,a,g);shots.push({id:id++,owner:i,start:{...a},target:q,age:0});}s.start=null;}p.x=a.x;p.z=a.z;p.y=0;});shots.forEach(b=>{b.age+=dt;if(!b.done&&b.age>.5){b.done=true;cells.forEach(q=>{if(dist(q,b.target)<1.4)q.owner=b.owner;});}});players.forEach(p=>p.score=Math.round(cells.filter(q=>q.owner===p.i).length/cells.length*1000)/10);c.view={size:34,eye:[0,31,26],target:[0,0,0]};
 },render(){cells.forEach((q,j)=>box(c,`stamp-${j}`,q.x,-.04,q.z,size,.12,size,q.owner===null?'#eee9d3':players[q.owner].color));players.forEach((p,i)=>{const a=corners[i],s=state[i];box(c,`slingshot-${i}`,a.x,.5,a.z,1.2,1,.4,'#a88a65');ball(c,`paintball-${i}`,s.start&&s.down?s.cx:a.x,.7,s.start&&s.down?s.cz:a.z,.55,p.color);if(s.start&&s.down){line(c,`elastic-${i}`,a,{x:s.cx,z:s.cz},p.color,.07,.5);const q=landing(s,a,{x:s.cx,z:s.cz});c.draw(`paint-aim-${i}`,'ring',{x:q.x,y:.12,z:q.z,sx:2.8,sy:2.8,rx:-Math.PI/2,color:p.color});}});shots.filter(b=>!b.done).forEach(b=>{const t=clamp(b.age/.5,0,1);ball(c,`ink-flight-${b.id}`,b.start.x+(b.target.x-b.start.x)*t,Math.sin(t*Math.PI)*5,b.start.z+(b.target.z-b.start.z)*t,.65,players[b.owner].color);});},timeout(){high(c,'도장에 남은 잉크 면적');}};
}

function parkour(c){
 const players=setup(c,Infinity),mushrooms=[{x:-4,z:0,y:0},{x:0,z:2,y:4},{x:3,z:-1,y:8}],top={x:0,z:0,y:12},state=players.map(()=>({carry:false,delivered:0,stun:0,nextTarget:0}));players.forEach((p,i)=>{p.x=-5+(i-1.5)*.3;p.z=3;p.y=0;p.vy=0;});c.view={size:27,eye:[21,23,26],target:[0,6,0]};
 return{update(dt){c.hint('방향 이동 · A 점프. 지상의 보석을 들고 버섯 트램펄린을 타세요. 꼭대기 내 자리에 세 개 배달하면 승리!');players.forEach((p,i)=>{const s=state[i],slot={x:(i-1.5)*2.4,z:0};if(!s.carry&&p.y===0&&dist(p,{x:-5,z:3})<1.25)s.carry=true;let target;if(!s.carry)target=p.y>0?{x:-7,z:5}:{x:-5,z:3};else target=s.nextTarget>=3?slot:mushrooms[s.nextTarget];const input=c.input(p,()=>({...toward(p,target.x,target.z),a:p.y===0&&dist(p,mushrooms[0])<1.2}));c.move(p,input,s.carry?4.3:5.2,false);p.x=clamp(p.x,-8,8);p.z=clamp(p.z,-6,6);const onTop=p.y===12&&Math.abs(p.x)<6&&Math.abs(p.z)<2.2;if(input.ap&&(p.y===0||onTop)){p.vy=8;p.y+=.001;}const oldY=p.y;if(!onTop||p.vy>0){p.vy-=18*dt;p.y+=p.vy*dt;if(p.vy<0){const m=mushrooms.filter(q=>oldY>=q.y&&p.y<=q.y&&dist(p,q)<1.45).sort((a,b)=>b.y-a.y)[0];if(m){s.nextTarget=Math.min(3,mushrooms.indexOf(m)+1);p.y=m.y+.001;p.vy=14;c.sound?.(500+m.y*20,.06);}else if(oldY>=12&&p.y<=12&&Math.abs(p.x)<6&&Math.abs(p.z)<2.2){p.y=12;p.vy=0;}else if(p.y<=0){p.y=0;p.vy=0;s.nextTarget=0;}}}if(s.carry&&p.y===12&&dist(p,slot)<.8){s.carry=false;s.delivered++;p.score=s.delivered;c.sound?.(790,.08);}});const done=players.filter(p=>p.score===3);if(done.length)c.complete(done.map(p=>p.i),'보석 세 개 정상 배달');
 },render(){c.arena({width:18,depth:14,color:'#9dbc90'});box(c,'jewel-source',-5,.2,3,2,.4,2,GREEN);mushrooms.forEach((m,j)=>{c.draw(`mushroom-stem-${j}`,'cylinder',{x:m.x,y:m.y/2-.15,z:m.z,sx:1,sy:Math.max(.2,m.y),sz:1,color:'#ded6b9'});ball(c,`mushroom-cap-${j}`,m.x,m.y-.2,m.z,3.1,PINK,{sy:.6});});box(c,'parkour-top',0,11.7,0,12,.5,4.4,'#e5ce9a');players.forEach((p,i)=>{const s=state[i];for(let j=0;j<3;j++){const x=(i-1.5)*2.4,z=(j-1)*.9;c.draw(`gem-slot-${i}-${j}`,'ring',{x,y:12.03,z,sx:.7,sy:.7,rx:-Math.PI/2,color:p.color});if(j<s.delivered)c.draw(`gem-delivered-${i}-${j}`,'cone',{x,y:12.4,z,sx:.7,sy:.8,sz:.7,color:p.color});}if(s.carry)c.draw(`carried-jewel-${i}`,'cone',{x:p.x,y:p.y+1.5,z:p.z,sx:.65,sy:.8,sz:.65,color:p.color});});}};
}
function fruitParade(c){
 const players=setup(c,Infinity),carriers=Array.from({length:12},(_,j)=>({type:c.int(0,2),count:c.int(1,3),start:j*.7})),totals=[0,0,0],names=['사과','레몬','오렌지'],colors=[PINK,GOLD,'#e99d52'],asked=c.int(0,2),state=players.map(()=>({answer:0,locked:false,next:0,memory:0,notes:[],last:null}));carriers.forEach(q=>totals[q.type]+=q.count);state.forEach(s=>s.memory=Math.max(0,totals[asked]+(c.rng()<.82?0:c.pick([-1,1]))));const showTime=15;
 return{update(dt){const viewing=c.time<showTime;c.hint(viewing?'행렬의 사과·레몬·오렌지 수를 기억하세요. 1P는 아래 메모 칸에 자유롭게 필기할 수 있습니다.':`${names[asked]}는 몇 개였나요? ← → 수 선택 · A 확정 · ${Math.max(0,Math.ceil(showTime+10-c.time))}초`);players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>viewing?{}:{x:Math.sign(s.memory-s.answer),a:s.memory===s.answer}),a={x:(i-1.5)*6,z:4.8};if(viewing){const q=input.pointer;if(q.down&&q.worldValid&&Math.abs(q.worldX-a.x)<2.5&&Math.abs(q.worldZ-a.z)<1.5){const now={x:q.worldX,z:q.worldZ};if(s.last&&dist(s.last,now)>.04)s.notes.push([s.last,now]);s.last=now;}else s.last=null;}else if(!s.locked){if(input.x&&c.time>=s.next){s.answer=clamp(s.answer+Math.sign(input.x),0,36);s.next=c.time+.13;}if(input.ap)s.locked=true;}});if(c.time>=showTime+10||!viewing&&state.every(s=>s.locked)){const error=Math.min(...state.map(s=>Math.abs(s.answer-totals[asked])));players.forEach((p,i)=>p.score=-Math.abs(state[i].answer-totals[asked]));c.complete(players.filter((p,i)=>Math.abs(state[i].answer-totals[asked])===error).map(p=>p.i),`${names[asked]} ${totals[asked]}개 · 가장 가까운 답`);}c.view={size:31,eye:[0,22,26],target:[0,1,0]};
 },render(){const viewing=c.time<showTime;box(c,'parade-path',0,-.2,-2,26,.3,6,'#c6d1b0');if(viewing)carriers.forEach((q,j)=>{const x=-13+(c.time-q.start)*3.5;if(x>-12&&x<12){ball(c,`fruit-carrier-${j}`,x,.6,-2,1,BLUE);box(c,`fruit-tray-${j}`,x,1.35,-2,1.8,.13,1.1,'#e7e2c3');for(let k=0;k<q.count;k++)ball(c,`parade-fruit-${j}-${k}`,x+(k-(q.count-1)/2)*.5,1.7,-2,.45,colors[q.type]);}});players.forEach((p,i)=>{const x=(i-1.5)*6;p.x=x;p.z=7;p.scale=.7;box(c,`notes-board-${i}`,x,-.05,4.8,5,.15,3,'#eee9d4');state[i].notes.forEach(([a,b],j)=>line(c,`fruit-note-${i}-${j}`,a,b,p.color,.06));if(!viewing)text(c,`fruit-answer-${i}`,`${state[i].answer}${state[i].locked?' ✓':''}`,x,1,4.8,4,p.color);});}};
}
function randomRooms(c,n=5){const rows=Array.from({length:n*2+1},()=>Array(n*2+1).fill('#')),seen=new Set([0]),stack=[0];rows[1][1]='.';while(stack.length){const cell=stack.at(-1),x=cell%n,z=Math.floor(cell/n),options=[[1,0],[-1,0],[0,1],[0,-1]].filter(([dx,dz])=>x+dx>=0&&x+dx<n&&z+dz>=0&&z+dz<n&&!seen.has((z+dz)*n+x+dx));if(!options.length){stack.pop();continue;}const[dx,dz]=c.pick(options),next=(z+dz)*n+x+dx;rows[z*2+1+dz][x*2+1+dx]='.';rows[(z+dz)*2+1][(x+dx)*2+1]='.';seen.add(next);stack.push(next);}return rows.map(r=>r.join(''));}
function haunted(c){
 const players=setup(c,Infinity),rows=randomRooms(c),map=mazeMap(rows,1.65),start=map.index.get('1,1'),goal=map.index.get('9,9'),state=players.map(()=>({visited:new Set([start]),waypoint:start,pace:c.rand(.75,1),face:{x:1,z:0},inv:0})),ghosts=Array.from({length:4},(_,j)=>{const room=map.nodes[map.index.get(`${3+(j%2)*4},${3+Math.floor(j/2)*4}`)];return{x:room.x+.62,z:room.z+.62,startX:room.x+.62,startZ:room.z+.62};});players.forEach((p,i)=>{p.x=map.nodes[start].x;p.z=map.nodes[start].z;p.scale=.55;});c.view={size:29,eye:[0,30,22],target:[0,0,0]};
 return{update(dt){c.hint('방향키로 저택의 마지막 노란 방을 찾으세요. 유령을 보면 멈추고 등을 돌리면 쫓아옵니다. 닿으면 출발 방으로 돌아갑니다.');players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>{if(dist(p,map.nodes[s.waypoint])<.17||dist(p,map.nodes[s.waypoint])<.7&&ghosts.some(g=>dist(g,map.nodes[s.waypoint])<.7))s.waypoint=map.path(s.waypoint,goal);const q=map.nodes[s.waypoint],near=ghosts.filter(g=>dist(p,g)<1.8);if(!near.length)return toward(p,q.x,q.z,s.pace);const options=Array.from({length:24},(_,j)=>({x:p.x+Math.cos(j*Math.PI/12)*.5,z:p.z+Math.sin(j*Math.PI/12)*.5})).filter(map.walkable),target=options.sort((a,b)=>{const score=v=>-dist(v,q)+Math.min(1.2,...near.map(g=>dist(v,g)))*1.4;return score(b)-score(a);})[0]||q;return toward(p,target.x,target.z,s.pace);});s.inv=Math.max(0,s.inv-dt);if(Math.hypot(input.x,input.z)>.1){const len=Math.hypot(input.x,input.z);s.face={x:input.x/len,z:input.z/len};}const old={x:p.x,z:p.z};c.move(p,input,3.7,false);if(!map.walkable(p)){p.x=old.x;p.z=old.z;}const node=map.closest(p);s.visited.add(node);p.score=s.visited.size;ghosts.forEach(g=>{if(!s.inv&&dist(p,g)<.42){p.x=map.nodes[start].x;p.z=map.nodes[start].z;s.waypoint=start;s.inv=1.2;}});if(dist(p,map.nodes[goal])<.5)c.complete([i],'저택의 마지막 방 도착');});ghosts.forEach(g=>{const seen=players.some((p,i)=>{const v=toward(p,g.x,g.z);return dist(p,g)<5&&v.x*state[i].face.x+v.z*state[i].face.z>.5;});if(!seen){const p=players.slice().sort((a,b)=>dist(g,a)-dist(g,b))[0];if(dist(g,p)<4.5){const v=toward(g,p.x,p.z);g.x+=v.x*dt*1.1;g.z+=v.z*dt*1.1;}}});
 },render(){map.nodes.forEach((n,j)=>{const seen=state.some(s=>s.visited.has(j));box(c,`haunt-room-${j}`,n.x,-.12,n.z,1.55,.25,1.55,j===goal?GOLD:j===start?PINK:seen?'#94b3a2':'#334957');});ghosts.forEach((g,j)=>ball(c,`hallway-boo-${j}`,g.x,.6,g.z,.85,'#e4e4da'));players.forEach((p,i)=>{const a={x:(i-1.5)*6,z:11};for(let z=0;z<5;z++)for(let x=0;x<5;x++){const node=map.index.get(`${x*2+1},${z*2+1}`);box(c,`room-map-${i}-${x}-${z}`,a.x+(x-2)*.7,.02,a.z+(z-2)*.5,.6,.08,.4,node===goal?GOLD:node===start?PINK:state[i].visited.has(node)?GREEN:'#263d49');}const n=map.nodes[map.closest(p)];ball(c,`map-player-${i}`,a.x+(n.cx/2-2.5)*.7,.3,a.z+(n.cz/2-2.5)*.5,.3,p.color);});}};
}

function roller(c){
 const players=setup(c,60),rollers=[],state=players.map(()=>({lives:3,bubble:0,inv:0,attack:0}));let next=.5,id=0;
 function hurt(p){const s=state[p.i];if(s.inv||s.bubble||!p.alive)return;s.lives--;p.score=s.lives;if(!s.lives)c.eliminate(p);else{s.bubble=1.6;s.inv=2.5;p.x=c.rand(-3,3);p.z=c.rand(-2,2);p.y=3;p.vx=p.vz=0;}}players.forEach(p=>p.score=3);
 return{update(dt){c.hint('세 번의 기회! 방향 이동 · A 점프 · B 밀치기. 가시 롤러나 낙하로 목숨을 잃으면 거품으로 돌아옵니다.');if(c.time>=next){const side=c.int(0,3),axis=side<2,sign=side%2?1:-1;rollers.push({id:id++,x:axis?sign*11:c.rand(-6,6),z:axis?c.rand(-4,4):sign*9,vx:axis?-sign*5.5:0,vz:axis?0:-sign*5.5,axis});next=c.time+Math.max(.65,1.8-c.time*.017);}rollers.forEach(r=>{r.x+=r.vx*dt;r.z+=r.vz*dt;});players.filter(p=>p.alive).forEach(p=>{const s=state[p.i],close=rollers.filter(r=>Math.abs(r.x)<10&&Math.abs(r.z)<8),input=c.input(p,()=>{const target=players.filter(q=>q!==p&&q.alive&&dist(p,q)<2)[0],danger=close.find(r=>Math.abs((r.axis?p.x-r.x:p.z-r.z))<2.2&&Math.abs(r.axis?p.z-r.z:p.x-r.x)<3);return{x:clamp(-p.x*.4,-1,1),z:clamp(-p.z*.4,-1,1),a:!!danger&&p.y===0,b:!!target&&s.attack<=0&&c.rng()<.07};});s.inv=Math.max(0,s.inv-dt);s.attack-=dt;if(s.bubble){s.bubble=Math.max(0,s.bubble-dt);p.y=s.bubble/1.6*3;if(!s.bubble)p.y=0;return;}c.move(p,input,5.1,false);p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.pow(.9,dt*60);p.vz*=Math.pow(.9,dt*60);c.jump(p,input,8);if(input.bp&&s.attack<=0){s.attack=.6;players.forEach(q=>{if(q!==p&&q.alive&&!state[q.i].bubble&&dist(p,q)<1.7){const v=toward(p,q.x,q.z);q.vx=v.x*7;q.vz=v.z*7;}});}if(Math.abs(p.x)>8||Math.abs(p.z)>6)hurt(p);close.forEach(r=>{if(p.y<1.1&&Math.abs(r.axis?p.x-r.x:p.z-r.z)<.75&&Math.abs(r.axis?p.z-r.z:p.x-r.x)<2.8)hurt(p);});});c.lastStanding();
 },render(){c.arena({width:16,depth:12,color:'#aabb9b'});rollers.filter(r=>Math.abs(r.x)<12&&Math.abs(r.z)<10).forEach(r=>{c.draw(`spike-roller-${r.id}`,'cylinder',{x:r.x,y:.6,z:r.z,sx:1.3,sy:5,sz:1.3,rx:r.axis?Math.PI/2:0,rz:r.axis?0:Math.PI/2,color:'#8e859d'});for(let j=-2;j<=2;j++)c.draw(`roller-spike-${r.id}-${j}`,'cone',{x:r.x+(r.axis?0:j),y:1.2,z:r.z+(r.axis?j:0),sx:.4,sy:.7,sz:.4,color:'#dce5d9'});});players.forEach(p=>{const s=state[p.i];if(s.bubble)ball(c,`revive-bubble-${p.i}`,p.x,p.y+.8,p.z,2.2,BLUE,{opacity:.3});text(c,`roller-lives-${p.i}`,'♥'.repeat(s.lives),p.x,p.y+2.3,p.z,2,p.color);});},timeout(){high(c,'남은 목숨 비교');}};
}
function jewels(c){
 const players=setup(c,30),corners=[{x:-7,z:-5},{x:7,z:-5},{x:-7,z:5},{x:7,z:5}],gems=[],state=players.map(()=>({power:1,stun:0}));let id=0,added=false;
 function spawn(count){for(let j=0;j<count;j++)gems.push({id:id++,x:c.rand(-5,5),z:c.rand(-3,3),vx:0,vz:0,big:c.rng()<.15,live:true});}spawn(30);players.forEach((p,i)=>{p.x=corners[i].x;p.z=corners[i].z;});c.bounds={x:8,z:6};
 return{update(dt){c.hint('방향 이동 · A 흡입. 보석을 실제로 끌어 내 색 모서리에 넣으세요. 일반 1점·큰 보석 5점. 오래 흡입하면 약해집니다.');if(!added&&c.time>=15){added=true;spawn(25);}const amp={x:Math.sin(c.time*1.3)*4,z:Math.cos(c.time*.8)*3};players.forEach((p,i)=>{const s=state[i],near=gems.filter(g=>g.live&&dist(p,g)<1.1),target=near.length?corners[i]:gems.filter(g=>g.live).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>target?{...toward(p,target.x,target.z),a:s.power>.12}:{});s.stun=Math.max(0,s.stun-dt);if(added&&!s.stun&&dist(p,amp)<1)s.stun=1.5;if(!s.stun)c.move(p,input,4.3);const vacuum=input.a&&!s.stun;s.power=clamp(s.power+dt*(vacuum?-.3:.8),.05,1);if(vacuum)gems.filter(g=>g.live&&dist(p,g)<4.2).forEach(g=>{const v=toward(g,p.x,p.z),d=dist(g,p);g.vx+=v.x*dt*(12*s.power)/(1+d*.2);g.vz+=v.z*dt*(12*s.power)/(1+d*.2);});});gems.filter(g=>g.live).forEach(g=>{g.x=clamp(g.x+g.vx*dt,-8,8);g.z=clamp(g.z+g.vz*dt,-6,6);g.vx*=Math.pow(.95,dt*60);g.vz*=Math.pow(.95,dt*60);corners.forEach((a,i)=>{if(g.live&&dist(g,a)<1.25){g.live=false;c.points(players[i],g.big?5:1);}});});
 },render(){c.arena({width:18,depth:14,color:'#c7c6ae'});corners.forEach((a,i)=>{box(c,`gem-zone-${i}`,a.x,.02,a.z,2.5,.06,2.5,players[i].color);text(c,`vacuum-power-${i}`,`${Math.round(state[i].power*100)}%`,players[i].x,2.4,players[i].z,2,players[i].color);});gems.filter(g=>g.live).forEach(g=>c.draw(`jewel-${g.id}`,'cone',{x:g.x,y:.3,z:g.z,sx:g.big?1:.5,sy:g.big?1:.6,sz:g.big?1:.5,color:g.big?GOLD:BLUE}));if(added)ball(c,'jewel-amp',Math.sin(c.time*1.3)*4,.65,Math.cos(c.time*.8)*3,1.2,'#675b84');},timeout(){high(c,'모서리에 넣은 보석 점수');}};
}
function dizzy(c){
 const players=setup(c,Infinity),fuzzies=Array.from({length:8},(_,j)=>({h:5+j*5,phase:c.rand(0,6)})),state=players.map(()=>({height:0,speed:0,lastAngle:null,stun:0,inv:0,pace:c.rand(7,10)}));c.view={size:63,eye:[16,52,60],target:[0,21,0]};
 return{update(dt){c.hint('시계 방향으로 나사를 돌려 상승! 1P 원형 드래그 또는 방향키 원운동. 터치를 멈추거나 A로 제동해 솜털을 피하세요.');players.forEach((p,i)=>{const s=state[i],center={x:(i-1.5)*8,z:6},near=fuzzies.find(q=>q.h>s.height&&q.h-s.height<2),stop=near&&Math.abs(Math.sin(c.time*1.7+near.phase)*3)<1.5,input=c.input(p,()=>stop?{a:true}:{x:Math.cos(c.time*s.pace),z:Math.sin(c.time*s.pace)}),turn=rotateInput(s,input,center);s.stun=Math.max(0,s.stun-dt);s.inv=Math.max(0,s.inv-dt);if(input.a||input.pointer.down&&Math.abs(turn)<.002)s.speed=0;else if(!s.stun)s.speed=Math.min(7,s.speed+Math.max(0,turn)*3);s.speed*=Math.pow(.994,dt*60);if(!s.stun)s.height+=s.speed*dt;fuzzies.forEach(q=>{if(!s.inv&&Math.abs(q.h-s.height)<.65&&Math.abs(Math.sin(c.time*1.7+q.phase)*3)<1){s.stun=.9;s.inv=1.8;s.speed=0;}});p.x=center.x;p.z=0;p.y=s.height;p.score=s.height;});const done=players.filter(p=>p.score>=45);if(done.length)c.complete(done.map(p=>p.i),'나사 리프트 정상 도착');
 },render(){players.forEach((p,i)=>{const x=(i-1.5)*8,s=state[i];c.draw(`screw-pole-${i}`,'cylinder',{x,y:22,z:0,sx:.5,sy:44,sz:.5,color:'#9eb6bc'});for(let j=0;j<22;j++)c.draw(`screw-thread-${i}-${j}`,'ring',{x,y:j*2,z:0,sx:1.6,sy:1.6,rx:-Math.PI/2,color:'#798f99'});c.draw(`screw-lift-${i}`,'cylinder',{x,y:s.height-.2,z:0,sx:3,sy:.4,sz:3,color:p.color});fuzzies.forEach((q,j)=>ball(c,`lift-fuzzy-${i}-${j}`,x+Math.sin(c.time*1.7+q.phase)*3,q.h,0,1.2,'#5b5367'));c.draw(`screw-crank-${i}`,'ring',{x,y:.1,z:6,sx:3.5,sy:3.5,rx:-Math.PI/2,color:p.color});box(c,`crank-spoke-${i}`,x,.15,6,3.5,.1,.12,GOLD,{ry:-(s.lastAngle??0)});});}};
}

function popQuiz(c){
 const players=setup(c,Infinity);let round=0,start=0,order=[],answer=0,rank=0;const state=players.map(()=>({done:false,choice:0,delay:0}));
 function begin(){start=c.time;order=c.shuffle([0,1,2,3]);answer=round===0?order.indexOf(2):round===1?order[3]:c.int(0,3);rank=0;state.forEach(s=>{s.done=false;s.choice=c.rng()<.9?answer:c.int(0,3);s.delay=c.rand(.35,2.5);});}begin();
 return{update(dt){const age=c.time-start,questions=['누가 두 번 뛰었나요?','누가 마지막으로 파이프에 숨었나요?','누가 보석을 떨어뜨렸나요?'];c.hint(age<6?`${round+1}/3회 · 적들의 행동을 주의 깊게 보세요.`:`${questions[round]} A/B/C/D 선택 · ${Math.max(0,Math.ceil(16-age))}초 · 정답 순서 4·3·2·1점`);players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>age>=6+s.delay&&!s.done?{[keys[s.choice]]:true}:{});if(age>=6&&!s.done){const choice=keys.findIndex(k=>input[k+'p']);if(choice>=0){s.done=true;if(choice===answer)c.points(p,[4,3,2,1][Math.min(3,rank++)]);}}p.x=(i-1.5)*4;p.z=5;});if(age>=16||age>=6&&state.every(s=>s.done)){round++;if(round===3)high(c,'세 관찰 퀴즈 총점');else begin();}
 },render(){const age=c.time-start;c.arena({width:22,depth:14,color:'#bdc9ab'});for(let i=0;i<4;i++){const x=(i-1.5)*4.5;let y=.7,visible=age<6;if(round===0){for(let j=0;j<order[i];j++){const t=age-(.8+j*1.3);if(t>=0&&t<.7)y+=Math.sin(t/.7*Math.PI)*1.8;}}else if(round===1){const hide=.7+order.indexOf(i)*1.15;if(age>hide)visible=false;c.draw(`quiz-pipe-${i}`,'cylinder',{x,y:.25,z:-2,sx:1.7,sy:.5,sz:1.7,color:GREEN});}else if(round===2){const dropped=i===answer&&age>2.3;ball(c,`quiz-gem-${i}`,x,dropped?.2:1.8,-1.5,.45,GOLD);}if(visible)ball(c,`quiz-actor-${i}`,x,y,-2,1.3,[PINK,BLUE,GOLD,GREEN][i],{sy:i%2?1.7:1.1});text(c,`quiz-key-${i}`,keys[i].toUpperCase(),x,.3,0,3,[PINK,BLUE,GOLD,GREEN][i]);}players.forEach((p,i)=>text(c,`quiz-status-${i}`,state[i].done?'선택 완료':'',p.x,2,p.z,2,p.color));}};
}
function shootingStars(c){
 const players=setup(c,30),corners=[{x:-8,z:7},{x:8,z:7},{x:-8,z:-7},{x:8,z:-7}],holes=Array.from({length:12},(_,j)=>({angle:j*Math.PI/6,r:j%2?4.7:2.8,value:[1,3,1,5,1,3,0,5,1,3,1,5][j]})),balls=[],state=players.map((p,i)=>({left:5,cx:corners[i].x,cz:corners[i].z,start:null,phase:0,target:null,cool:c.rand(.2,1.2)}));let id=0;
 const position=h=>({x:Math.cos(h.angle+c.time*.42)*h.r,z:Math.sin(h.angle+c.time*.42)*h.r});
 function launch(owner,origin,dx,dz,bonus=false){const d=Math.hypot(dx,dz)||1;balls.push({id:id++,owner,x:origin.x,z:origin.z,vx:dx/d*(bonus?7:Math.min(17,8+d)),vz:dz/d*(bonus?7:Math.min(17,8+d)),age:0,flight:bonus?0:.45,live:true});}
 return{update(dt){c.hint('다섯 공을 탭해 중심으로 튕기세요. 방향+A로 가상 손을 끌고 놓을 수도 있습니다. 회전 구멍은 1·3·5점, 별 구멍은 보너스 공 네 개!');players.forEach((p,i)=>{const s=state[i],a=corners[i],input=c.input(p,()=>{if(s.left<=0||s.cool>0)return{};if(s.phase===0){s.target=position(c.pick(holes.filter(h=>h.value===5||h.value===0)));s.phase=1;return{pointer:{valid:true,worldValid:true,worldX:a.x,worldZ:a.z,down:true}};}if(s.phase===1){s.phase=2;return{pointer:{valid:true,worldValid:true,worldX:s.target.x,worldZ:s.target.z,down:true}};}s.phase=0;s.cool=c.rand(1,2);return{pointer:{valid:true,worldValid:true,worldX:s.target.x,worldZ:s.target.z,down:false}};});s.cool=Math.max(0,s.cool-dt);const g=gesture(c,s,input,a,16,15);if(s.left>0&&g.pressed&&dist(g,a)<1.1)s.start={x:g.x,z:g.z};if(g.released&&s.start){const dx=g.x-s.start.x,dz=g.z-s.start.z;if(Math.hypot(dx,dz)>.4){launch(i,a,dx,dz);s.left--;}s.start=null;}p.x=a.x;p.z=a.z;});const spawned=[];balls.forEach(b=>{if(!b.live)return;b.age+=dt;b.x+=b.vx*dt;b.z+=b.vz*dt;if(b.age>=b.flight){if(b.flight&&b.age-dt<b.flight){if(Math.hypot(b.x,b.z)>6.5){b.live=false;return;}b.vx*=.62;b.vz*=.62;}b.vx+=(-b.z*.4-b.x*.035)*dt;b.vz+=(b.x*.4-b.z*.035)*dt;b.vx*=Math.pow(.997,dt*60);b.vz*=Math.pow(.997,dt*60);const radius=Math.hypot(b.x,b.z);if(radius>6.1){const nx=b.x/radius,nz=b.z/radius,dot=b.vx*nx+b.vz*nz;b.x=nx*6.1;b.z=nz*6.1;b.vx-=1.8*dot*nx;b.vz-=1.8*dot*nz;}const h=holes.find(h=>dist(b,position(h))<.55);if(h){b.live=false;if(h.value)c.points(players[b.owner],h.value);else for(let k=0;k<4;k++){const a=k*Math.PI/2+.3,origin={x:Math.cos(a)*5.8,z:Math.sin(a)*5.8};spawned.push({owner:b.owner,origin,dx:-origin.x+c.rand(-1,1),dz:-origin.z+c.rand(-1,1)});}}}if(b.age>8)b.live=false;});spawned.forEach(b=>launch(b.owner,b.origin,b.dx,b.dz,true));c.view={size:33,eye:[0,32,26],target:[0,0,0]};
 },render(){c.draw('star-wheel','cylinder',{x:0,y:-.3,z:0,sx:13,sy:.5,sz:13,color:'#b7c3a0'});holes.forEach((h,j)=>{const q=position(h);c.draw(`score-hole-${j}`,'cylinder',{x:q.x,y:.02,z:q.z,sx:1,sy:.06,sz:1,color:h.value? '#435a61':GOLD});text(c,`hole-value-${j}`,h.value||'★',q.x,.5,q.z,.9,'#e9e8cf');});players.forEach((p,i)=>{text(c,`balls-left-${i}`,`공 ${state[i].left}`,p.x,2,p.z,3,p.color);ball(c,`ammo-${i}`,state[i].start&&state[i].down?state[i].cx:p.x,.5,state[i].start&&state[i].down?state[i].cz:p.z,.6,p.color);});balls.filter(b=>b.live).forEach(b=>ball(c,`star-ball-${b.id}`,b.x,b.age<b.flight?Math.sin(b.age/b.flight*Math.PI)*4+.3:.3,b.z,.5,players[b.owner].color));},timeout(){high(c,'회전판 공 점수');}};
}
function blockBusters(c){
 const players=setup(c,Infinity),owners=c.shuffle(Array.from({length:80},(_,j)=>j%4)),blocks=owners.map((owner,j)=>({id:j,col:j%8,x:(j%8-3.5)*1.15,y:.6+Math.floor(j/8)*1.05,vy:0,owner,live:true})),bullets=[],state=players.map(()=>({cx:0,cy:3,cool:0,pace:c.rand(4,6)}));let id=0;c.view={size:25,eye:[0,13,28],target:[0,5,0]};
 return{update(dt){c.hint('방향키로 조준점 이동 · A 발사. 내 무늬 블록 스무 개를 모두 제거하세요. 남의 블록을 부수면 그 사람의 진행이 올라갑니다.');for(let col=0;col<8;col++){const stack=blocks.filter(b=>b.live&&b.col===col).sort((a,b)=>a.y-b.y);stack.forEach((b,j)=>{const y=.6+j*1.05;if(b.y>y){b.vy-=18*dt;b.y=Math.max(y,b.y+b.vy*dt);if(b.y===y)b.vy=0;}});}players.forEach((p,i)=>{const s=state[i],target=blocks.filter(b=>b.live&&b.owner===i).sort((a,b)=>Math.hypot(a.x-s.cx,a.y-s.cy)-Math.hypot(b.x-s.cx,b.y-s.cy))[0],input=c.input(p,()=>target?{x:clamp((target.x-s.cx)*s.pace,-1,1),z:clamp((s.cy-target.y)*s.pace,-1,1),a:Math.hypot(target.x-s.cx,target.y-s.cy)<.2&&s.cool<=0}:{});s.cool-=dt;s.cx=clamp(s.cx+input.x*dt*8,-5.5,5.5);s.cy=clamp(s.cy-input.z*dt*8,.4,11);p.x=(i-1.5)*4;p.z=8;p.scale=.7;if(input.ap&&s.cool<=0){s.cool=.25;const t=.32;bullets.push({id:id++,owner:i,x:p.x,y:.8,z:7.5,vx:(s.cx-p.x)/t,vy:(s.cy-.8)/t,vz:-7.5/t,live:true});}});bullets.forEach(b=>{if(!b.live)return;b.x+=b.vx*dt;b.y+=b.vy*dt;b.z+=b.vz*dt;if(b.z<=0){const hit=blocks.find(q=>q.live&&Math.abs(q.x-b.x)<.54&&Math.abs(q.y-b.y)<.5);if(hit){hit.live=false;c.points(players[hit.owner]);}b.live=false;}});const done=players.filter(p=>p.score>=20);if(done.length)c.complete(done.map(p=>p.i),'내 블록 스무 개 제거');
 },render(){box(c,'block-base',0,-.2,0,11,.4,3,'#80969b');blocks.filter(b=>b.live).forEach(b=>{box(c,`symbol-block-${b.id}`,b.x,b.y,0,1.05,1,1,players[b.owner].color);text(c,`block-symbol-${b.id}`,['♥','♠','♣','◆'][b.owner],b.x,b.y,.55,.8,'#f4eedc');});players.forEach((p,i)=>{const s=state[i];c.draw(`block-cursor-${i}`,'ring',{x:s.cx,y:s.cy,z:.7,sx:.8,sy:.8,color:p.color});});bullets.filter(b=>b.live).forEach(b=>ball(c,`block-bullet-${b.id}`,b.x,b.y,b.z,.25,players[b.owner].color));}};
}
function megaGoomba(c){
 const players=setup(c,300),state=players.map(()=>({carry:0,inv:0,stun:0,cool:0})),patrols=Array.from({length:3},(_,j)=>({x:0,z:(j-1)*3})),chaser={x:4,z:0},extra=[];let total=0,awake=false,lunge=null,next=0;players.forEach((p,i)=>{p.x=(i-1.5)*2.4;p.z=6;});c.bounds={x:8,z:7};
 return{update(dt){c.hint(`큰 상자 ${total}/50개 · 방향 이동 · A 사과 집기/상자에 넣기. 최대 세 개, 많이 들수록 느립니다.${awake?' 거인이 깨어났습니다!':''}`);if(!awake&&total>=25){awake=true;for(let j=0;j<3;j++)extra.push({x:c.rand(-5,5),z:c.rand(-4,4),phase:c.rand(0,6)});}patrols.forEach((g,j)=>g.x=Math.sin(c.time*(awake?1.2:.8)+j*2)*6.5);const target=players.slice().sort((a,b)=>dist(chaser,a)-dist(chaser,b))[0],v=toward(chaser,target.x,target.z);chaser.x+=v.x*dt*(awake?1.8:1.3);chaser.z+=v.z*dt*(awake?1.8:1.3);extra.forEach(g=>{g.x=Math.sin(c.time+g.phase)*6;g.z=Math.cos(c.time*.6+g.phase)*4;});if(awake&&c.time>=next){const target=players.filter(p=>p.z<-3).sort((a,b)=>a.z-b.z)[0];if(target){lunge={start:c.time,x:target.x};next=c.time+3;}}const boss={x:lunge?lunge.x:0,z:lunge&&c.time-lunge.start<1.5?-8+Math.sin((c.time-lunge.start)/1.5*Math.PI)*5:-8};players.forEach((p,i)=>{const s=state[i],destination=s.carry>=3?{x:0,z:6.5}:s.carry&&p.z>0?{x:0,z:6.5}:{x:(i-1.5)*1.7,z:-6},obstacles=[...patrols,chaser,...extra],input=c.input(p,()=>{let q=destination;const danger=obstacles.filter(g=>dist(p,g)<1.6).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(danger)q={x:clamp(p.x+(p.x>danger.x?2:-2),-7,7),z:p.z+(destination.z>p.z?1:-1)};return{...toward(p,q.x,q.z),a:s.cool<=0&&(p.z<-5.6&&s.carry<3||dist(p,{x:0,z:6.5})<1.8&&s.carry>0)};});s.inv=Math.max(0,s.inv-dt);s.stun=Math.max(0,s.stun-dt);s.cool-=dt;if(!s.stun){c.move(p,input,5/(1+s.carry*.28));if(input.ap&&s.cool<=0){s.cool=.18;if(p.z<-5.6&&s.carry<3)s.carry++;else if(dist(p,{x:0,z:6.5})<1.8&&s.carry){total+=s.carry;c.points(p,s.carry);s.carry=0;}}}if(!s.inv&&(obstacles.some(g=>dist(p,g)<.85)||awake&&dist(p,boss)<2)){c.points(p,-1);s.inv=1.3;s.stun=.45;}});if(total>=50)high(c,'사과 50개 운반 · 개인 점수 비교');c.view={size:25,eye:[0,25,23],target:[0,0,0]};
 },render(){c.arena({width:18,depth:17,color:'#adc48a'});box(c,'apple-box',0,.55,7,4,1.1,1.5,'#ad845a');text(c,'apple-total',`${total} / 50`,0,2.2,7,4);patrols.forEach((g,j)=>{box(c,`patrol-track-${j}`,0,.015,g.z,14,.025,.12,'#cfbd94');ball(c,`patrol-goomba-${j}`,g.x,.5,g.z,1,'#a58a65');});ball(c,'chasing-goomba',chaser.x,.5,chaser.z,1,PINK);extra.forEach((g,j)=>ball(c,`extra-goomba-${j}`,g.x,.5,g.z,1,'#a58a65'));const boss={x:lunge?lunge.x:0,z:lunge&&c.time-lunge.start<1.5?-8+Math.sin((c.time-lunge.start)/1.5*Math.PI)*5:-8};ball(c,'sleepy-giant',boss.x,1.8,boss.z,4.5,'#ad9372');text(c,'giant-face',awake?'> <':'Zzz',boss.x,4,boss.z,3);players.forEach((p,i)=>{box(c,`apple-basket-${i}`,p.x,1.1,p.z-.5,1.3,.4,1,p.color);for(let j=0;j<state[i].carry;j++)ball(c,`carried-apple-${i}-${j}`,p.x+(j-1)*.35,1.5,p.z-.5,.35,PINK);});},timeout(){c.complete([],'5분 안에 사과 운반 목표를 채우지 못함');}};
}

export const games={
 'Acornucopia':acorn,'Corkscrew Climb':corkscrew,'Piece of Cake':cake,'Lava Labyrinth':lavaMaze,'Piranha Plantemonium':piranha,'Jump to Conclusion':jumpConclusion,"Wheelin' and Wigglin'":wigglin,'Blowboat Battle':blowboat,'Bumper Bugs':bumperBugs,'Splat-a-Stamp':splat,
 'Parkour War':parkour,'Fruit Parade':fruitParade,'Haunted Hallways':haunted,'Roller Revenge':roller,'Jewel Janitors':jewels,'Dodge Fuzzy, Get Dizzy':dizzy,'Pop Quiz':popQuiz,'Shooting Stars':shootingStars,'Block Busters':blockBusters,"Mega Goomba's Bad Dream":megaGoomba
};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(n=>[n,['star-rush']]));
export const notes={
 'Acornucopia':'방향 이동으로 도토리 다섯 개를 운반합니다. 돌진하는 적에 맞을 때 하나를 잃고, 모두 잃으면 탈락. 모든 참가자가 결승 도착/탈락한 뒤 남은 수가 많은 사람이 승리합니다. 참가자끼리 실제로 밀 수 있습니다. 코스 40단위·적 18마리·피격 유예 1.2초는 재구성 수치입니다.',
 'Corkscrew Climb':'원작 무작위 선두·나선 경로 자동 달리기·A로 전기 구슬 점프·먼저 결승 도착. 실제 3D 나선 램프를 따라 오릅니다. 115단위 코스·16구슬·피격 지연 0.85초·선두 간격은 재구성했습니다.',
 'Piece of Cake':'원작 세 라운드, 10초 기억 후 10초 자르기, 맞으면 1점. 실제 과일 위치를 숨긴 뒤 제시 조각에 해당하는 위치를 세로로 드래그합니다. 키보드는 A를 누른 채 방향키로 칼 이동. 여섯 과일 조합의 직사각형 케이크·세로 스트로크 허용 폭은 재구성이며 원작 도안과 같지는 않습니다.',
 'Lava Labyrinth':'방향 이동, 가장 큰 금 상자를 먼저 찾으면 승리. 은/동/물고기 결과도 각각 2/1/0으로 기록합니다. 고정 통로에 상자 위치만 무작위로 바뀌고 용암 괴물에 닿으면 지연됩니다. 이 버전은 새로 구성한 고정 11×9 미로를 전체 카메라로 보이며 원작 카메라 버튼은 사용하지 않습니다.',
 'Piranha Plantemonium':'원작 30초·좌우 이동·A 발사·일반 1점·금색 3점·거대 금색 마지막 명중 10점·상대 탄환 피격 시 정지. 네 변의 레일에서 실제 탄환을 쏩니다. 거대 꽃 체력 6·등장 시각 13초·정지 2초·레일/꽃 배치는 재구성했습니다.',
 'Jump to Conclusion':'원작 A 한 칸, B 두 칸 점프와 45계단 경주를 구현했습니다. 실제 착지 계단의 덩굴 꽃을 확인하며 먼저 정상에 도달하면 승리. 계단별 장애물 배치·0.5/0.75초 점프·피격 지연 1.1초는 재구성 수치입니다.',
 "Wheelin' and Wigglin'":'원작 30초, 방향으로 차체 조향, A 돌진은 2초 재사용 대기. 실제 이동 경로를 따라 몸통이 이어지고 돌진으로 상대 몸통을 하나씩 줄입니다. 몸통이 모두 사라지면 탈락, 마지막 생존자 또는 남은 몸통이 많은 사람 승리. 초기 5칸·돌진 0.35초·조향/속도 계수는 새 수치입니다.',
 'Blowboat Battle':'원작 마이크 불기는 A를 누르는 입력으로 바꾸고 방향키로 바람 방향을 정합니다. 바람의 힘·관성·장난감 물고기·튜브 충돌에 의한 무작위 튕김을 실제로 계산합니다. 먼저 결승 도착 승리. 43단위 욕조 경로·추진력·마찰·장애물 배치는 재구성했습니다.',
 'Bumper Bugs':'원작 터치 끌기/밀기로 기계 벌레를 움직여 깃발 부표 여덟 개를 통과합니다. 1P는 벌레 가까이에서 드래그, 키보드는 방향+A 가상 손. 실제 스트로크 방향과 길이로 추진하며 성게 접촉 시 잠시 멈춥니다. 부표 배치·마찰·기절 및 회복 유예는 재구성했습니다.',
 'Splat-a-Stamp':'원작 30초, 공을 잡아 당겼다 놓아 공동 도장에 잉크를 덮고 마지막 면적 비율을 비교합니다. 실제 드래그 반대 방향으로 포물선 발사하며 다른 색 위를 다시 칠할 수 있습니다. 1P 포인터 또는 방향+A. 25×19 도장 마스크·세 자체 도안·잉크 반경은 재구성했습니다.',
 'Parkour War':'방향 이동·A 점프. 지상 보석을 자동으로 들고 실제 버섯 트램펄린으로 상승해 내 자리로 운반합니다. 내려와 다시 가져가는 과정을 반복하여 세 개 먼저 배달하면 승리. 버섯 세 개의 위치·4/8/12 높이·탄성 계수·자동 접촉 배달은 이 버전의 구성입니다.',
 'Fruit Parade':'행렬의 세 종류 과일을 기억한 뒤 무작위로 질문한 종류의 개수를 10초 동안 답합니다. ←/→ 수 선택·A 확정, 가장 가까운 답 승리. 1P 포인터 자유 필기 칸이 있습니다. 12명의 행렬·15초 관찰·각 1~3개 과일은 새 구성이고 메모가 정답을 자동 계산하지 않습니다.',
 'Haunted Hallways':'방향 이동, 무작위 저택에서 마지막 노란 방에 먼저 도착하면 승리. 개인 지도에 방문 방을 표시합니다. 유령을 바라보면 멈추고 등지면 추격하며 접촉 시 시작 방 복귀. 새로 생성하는 5×5 방 미로·가까운 유령 활성 범위·충돌 반경은 재구성했습니다. 승리 후 나머지 참가자의 길 안내 연출은 생략했습니다.',
 'Roller Revenge':'원작 60초·세 목숨·롤러/낙하 피격 시 한 목숨 손실·거품 복귀. 방향 이동·A 점프·B 밀치기. 모두 잃으면 탈락하고 마지막 생존자 또는 종료 시 목숨이 많은 사람 승리. 롤러 배치·속도·복귀/무적 시간·공격 충격량은 재구성했습니다.',
 'Jewel Janitors':'원작 30초, 방향 이동·A 흡입. 실제 보석에 힘을 가해 내 색 모서리로 넣으며 일반 1점·큰 보석 5점입니다. 계속 흡입하면 약해지고 놓으면 회복됩니다. 중간에 보석과 전기 구슬이 추가됩니다. 원형 흡입 범위·보석 수·힘/회복 계수·기절 1.5초는 재구성했습니다.',
 'Dodge Fuzzy, Get Dizzy':'원작 시계 방향으로 나사를 돌려 상승하고 터치로 멈춰 솜털을 피하는 경주. 1P 원형 드래그 또는 방향키 원운동, A도 제동. 양의 실제 회전량으로 가속하며 거꾸로 돌리면 상승력을 얻지 못합니다. 45단위 높이·장애물 위치·속도/기절 계수는 재구성했습니다.',
 'Pop Quiz':'원작 세 라운드 관찰 퀴즈, 답변 10초, A/B/C/D 선택, 정답 순서대로 4/3/2/1점·오답 0점. 실제 점프 횟수, 숨는 순서, 보석 놓기를 보고 답합니다. 자체 적 동작·문제·관찰 6초는 새 구성이며 원작의 모든 질문을 복제하지 않았습니다.',
 'Shooting Stars':'원작 30초·플레이어당 다섯 공·회전 구멍 1/3/5점·별 구멍에서 같은 색 보너스 공 네 개, 보너스도 별 구멍 재작동 가능. 실제 포인터 튕기기 또는 방향+A 드래그로 던집니다. 공의 굴림·반사·구멍 충돌을 계산합니다. 구멍 12개 배치·투사/마찰·공 체류 8초는 재구성했습니다.',
 'Block Busters':'방향키로 조준점 이동·A 발사. 80개 중 내 색/무늬 블록 20개를 모두 제거하면 승리합니다. 실제 탄환 명중과 위쪽 블록의 낙하를 계산합니다. 다른 사람 색 블록을 부수면 해당 색 주인의 진행을 올리는 처리, 8열×10단 배치·발사 간격은 이 버전의 구성입니다.',
 "Mega Goomba's Bad Dream":'Toad Scramble 기준: A로 최대 세 사과 집기/상자 넣기, 많이 들수록 느림. 합계 25개 후 보스가 깨어나 돌진하고 추가 적이 생기며, 접촉하면 개인 점수 -1. 합계 50개 운반 후 최고점 승리, 5분 미달이면 무승부. 25개로 끝나는 Balloon Bash 규칙은 선택하지 않았습니다. 코스·감속률·추격/돌진 수치는 재구성했습니다.'
};
