import{clamp,dist,toward}from'../core.js';
const PINK='#ed91aa',BLUE='#76b9da',GOLD='#ebc362',GREEN='#8abf97';
const box=(c,id,x,y,z,sx,sy,sz,color,more={})=>c.draw(id,'box',{x,y,z,sx,sy,sz,color,...more});
const ball=(c,id,x,y,z,s,color,more={})=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color,...more});
const text=(c,id,label,x=0,y=1,z=0,size=3,color='#294652')=>c.draw(id,'text',{text:String(label),x,y,z,sx:size,sy:size/4,color});
const diff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function setup(c,limit=Infinity){c.limit=limit;c.activePlayers=[0,1,2,3];return c.players;}
function high(c,reason){const top=Math.max(...c.players.map(p=>p.score)),w=c.players.filter(p=>p.score===top);c.complete(w.length===4?[]:w.map(p=>p.i),reason);}
const layouts=[{x:-6,z:-5},{x:6,z:-5},{x:-6,z:5},{x:6,z:5}];
function boards(c){c.view={size:28,eye:[0,30,24],target:[0,0,0]};c.players.forEach((p,i)=>{p.x=layouts[i].x;p.z=layouts[i].z+3.8;p.scale=.6;});}
function board(c,i,label){const a=layouts[i];box(c,`board-${i}`,a.x,-.2,a.z,11,.3,8.5,'#e7edd8');text(c,`board-title-${i}`,label,a.x,.5,a.z-3.6,7,c.players[i].color);}
function gesture(c,s,input,a,rx=4.7,rz=3){const ptr=input.pointer;let down;if(ptr.worldValid){s.cx=ptr.worldX;s.cz=ptr.worldZ;down=ptr.down;}else{s.cx=clamp(s.cx+input.x*c.dt*7,a.x-rx,a.x+rx);s.cz=clamp(s.cz+input.z*c.dt*7,a.z-rz,a.z+rz);down=input.a;}const g={x:s.cx,z:s.cz,down,pressed:down&&!s.down,released:!down&&!!s.down,dx:down&&s.down?s.cx-s.px:0,dz:down&&s.down?s.cz-s.pz:0};s.down=down;s.px=s.cx;s.pz=s.cz;return g;}
function line(c,id,a,b,color,width=.1,y=.1){const d=dist(a,b);box(c,id,(a.x+b.x)/2,y,(a.z+b.z)/2,d,.08,width,color,{ry:-Math.atan2(b.z-a.z,b.x-a.x)});}
function segmentDistance(p,a,b){const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((p.x-a.x)*dx+(p.z-a.z)*dz)/(dx*dx+dz*dz||1),0,1);return Math.hypot(p.x-a.x-dx*t,p.z-a.z-dz*t);}

function slip(c){
 const players=setup(c,45),penguins=[],state=players.map(()=>({h:0,vy:0}));let next=.5,id=0,tiltX=0,tiltZ=0;
 return{update(dt){c.hint('미끄러운 얼음 위에서 방향으로 버티고 A로 펭귄을 뛰어넘으세요. 얼음은 펭귄의 무게로 기울어집니다.');if(c.time>=next){const a=c.rand(0,Math.PI*2),x=Math.cos(a)*8,z=Math.sin(a)*6,v=toward({x,z},-x*.8,-z*.8);penguins.push({id:id++,x,z,vx:v.x*c.rand(3,5),vz:v.z*c.rand(3,5)});next=c.time+c.rand(1,1.9);}penguins.forEach(q=>{q.x+=q.vx*dt;q.z+=q.vz*dt;});const on=penguins.filter(q=>Math.hypot(q.x/7,q.z/5)<1.1),tx=clamp(on.reduce((s,q)=>s+q.x*.025,0),-.24,.24),tz=clamp(on.reduce((s,q)=>s+q.z*.035,0),-.24,.24);tiltX+=(tx-tiltX)*Math.min(1,dt*2);tiltZ+=(tz-tiltZ)*Math.min(1,dt*2);players.filter(p=>p.alive).forEach(p=>{const s=state[p.i],input=c.input(p,()=>({x:clamp(-p.x*.6-p.vx*.5-tiltX*3,-1,1),z:clamp(-p.z*.6-p.vz*.5-tiltZ*3,-1,1),a:on.some(q=>dist(p,q)<2)&&s.h===0}));p.vx=(p.vx+input.x*dt*8+tiltX*dt*20)*Math.pow(.987,dt*60);p.vz=(p.vz+input.z*dt*8+tiltZ*dt*20)*Math.pow(.987,dt*60);p.x+=p.vx*dt;p.z+=p.vz*dt;if(input.ap&&s.h===0){s.h=.001;s.vy=7;}if(s.h>0){s.vy-=18*dt;s.h=Math.max(0,s.h+s.vy*dt);}on.forEach(q=>{if(s.h<1&&dist(p,q)<1){const v=toward(q,p.x,p.z);p.vx=v.x*8;p.vz=v.z*8;}});p.y=s.h-tiltX*p.x-tiltZ*p.z;if(Math.hypot(p.x/7,p.z/5)>1.04){c.eliminate(p);p.y=-1.3;}});c.lastStanding();
 },render(){c.draw('sea','cylinder',{x:0,y:-2,z:0,sx:30,sy:.3,sz:30,color:'#65a7be'});c.draw('ice-floe','cylinder',{x:0,y:-.4,z:0,sx:14,sy:.8,sz:10,color:'#d2edf0',rx:tiltZ,rz:-tiltX});penguins.filter(q=>Math.abs(q.x)<12&&Math.abs(q.z)<10).forEach(q=>{ball(c,`penguin-${q.id}`,q.x,.5-tiltX*q.x-tiltZ*q.z,q.z,1,BLUE,{sy:1.3});ball(c,`penguin-front-${q.id}`,q.x,.5-tiltX*q.x-tiltZ*q.z,q.z+.35,.65,'#eee8d6');});players.filter(p=>!p.alive).forEach(p=>box(c,`frozen-${p.i}`,p.x,-1,p.z,1.4,2,1.4,BLUE,{opacity:.6}));},timeout(){c.survivors('45초 얼음 생존');}};
}
function noTraction(c){
 const players=setup(c,Infinity),state=players.map((p,i)=>({heading:Math.PI/2,angle:0,progress:0,gain:c.rand(1.5,2.2)}));c.view={size:31,eye:[0,27,25],target:[0,0,0]};players.forEach((p,i)=>{p.x=9+(i-1.5)*.45;p.z=0;});
 return{update(dt){c.hint('← →로 조향 · A 가속 · B 브레이크. 관성으로 미끄러지는 타원 트랙을 세 바퀴 먼저 완주하세요.');players.forEach((p,i)=>{const s=state[i],theta=Math.atan2(p.z/5.5,p.x/9),input=c.input(p,()=>{const a=theta+.3,q={x:9*Math.cos(a),z:5.5*Math.sin(a)},target=Math.atan2(q.z-p.z,q.x-p.x),turn=diff(target,s.heading);return{x:clamp(turn*s.gain,-1,1),a:Math.abs(turn)<1.2,b:Math.abs(turn)>1.25};});const speed=Math.hypot(p.vx,p.vz);s.heading+=input.x*dt*(1.6+speed*.035);const accel=input.a?5:0;p.vx+=Math.cos(s.heading)*accel*dt;p.vz+=Math.sin(s.heading)*accel*dt;const forward=p.vx*Math.cos(s.heading)+p.vz*Math.sin(s.heading),lateral=-p.vx*Math.sin(s.heading)+p.vz*Math.cos(s.heading),f=forward*Math.pow(input.b?.92:.993,dt*60),l=lateral*Math.pow(.96,dt*60);p.vx=Math.cos(s.heading)*f-Math.sin(s.heading)*l;p.vz=Math.sin(s.heading)*f+Math.cos(s.heading)*l;const v=Math.hypot(p.vx,p.vz);if(v>8){p.vx*=8/v;p.vz*=8/v;}p.x+=p.vx*dt;p.z+=p.vz*dt;let r=Math.hypot(p.x/9,p.z/5.5);if(r<.67||r>1.28){const bound=r<.67?.67:1.28;p.x*=bound/(r||1);p.z*=bound/(r||1);p.vx*=.3;p.vz*=.3;}const a=Math.atan2(p.z/5.5,p.x/9),delta=diff(a,s.angle);s.progress=Math.max(0,s.progress+delta);s.angle=a;p.score=s.progress/(Math.PI*2);p.rotation=-s.heading;});const done=players.filter(p=>p.score>=3);if(done.length)c.complete(done.map(p=>p.i),'세 바퀴 완주');
 },render(){c.draw('oval-road','cylinder',{x:0,y:-.3,z:0,sx:23.5,sy:.5,sz:14.7,color:'#aad0d6'});c.draw('oval-island','cylinder',{x:0,y:.02,z:0,sx:12,sy:.3,sz:7.2,color:'#89b38c'});box(c,'start-line',9,.03,0,5,.06,.25,'#f1f0d9');players.forEach(p=>{box(c,`slippy-kart-${p.i}`,p.x,.3,p.z,1.5,.5,.9,p.color,{ry:p.rotation});text(c,`lap-${p.i}`,`${Math.min(3,Math.floor(p.score)+1)} / 3`,p.x,2,p.z,1.9,p.color);});}};
}
function blownHover(c){
 const players=setup(c,Infinity),panels=Array.from({length:26},(_,j)=>({d:10+j*6.3,x:[-2.4,0,2.4][j%3],phase:c.rand(0,6),high:j%3===0})),state=players.map(()=>({d:0,x:0,h:0,vy:0,meter:4,hit:new Set(),reaction:c.rand(2.2,4.8)}));c.view={size:34,eye:[0,32,27],target:[0,0,0]};
 const height=q=>q.high?1.7+.35*Math.sin(c.time*2+q.phase):.35;
 return{update(dt){c.hint('자동 전진 · ← → 회피 · A 점프. 낮은 패널은 넘고 높은 패널 밑은 지나가세요. 충돌하면 속도 게이지가 줄어듭니다.');players.forEach((p,i)=>{const s=state[i],q=panels.find(q=>q.d>s.d-.5),input=c.input(p,()=>{const near=q&&q.d-s.d<s.reaction,x=near&&Math.abs(s.x-q.x)<1.3?(q.x>0?-2.3:2.3):s.x;return{x:clamp((x-s.x)*3,-1,1),a:!!near&&!q.high&&Math.abs(s.x-q.x)<1.4&&q.d-s.d<1.7};});s.x=clamp(s.x+input.x*dt*5,-3.3,3.3);if(input.ap&&s.h===0){s.h=.001;s.vy=7;}if(s.h>0){s.vy-=18*dt;s.h=Math.max(0,s.h+s.vy*dt);}s.meter=Math.min(12,s.meter+dt*.8);s.d+=s.meter*dt;panels.forEach((q,j)=>{if(!s.hit.has(j)&&Math.abs(q.d-s.d)<.6&&Math.abs(s.x-q.x)<1.1&&Math.abs(s.h+.3-height(q))<.65){s.hit.add(j);s.meter=Math.max(3,s.meter*(q.high?.55:.4));}});p.x=(i-1.5)*8+s.x;p.z=4;p.y=s.h+.4;p.score=s.d;});const done=players.filter((p,i)=>state[i].d>=185);if(done.length)c.complete(done.map(p=>p.i),'호버보드 결승 도착');
 },render(){players.forEach((p,i)=>{const s=state[i],x=(i-1.5)*8;box(c,`hover-road-${i}`,x,-.2,0,7.3,.2,25,'#c4d8b0');box(c,`hoverboard-${i}`,p.x,p.y-.2,p.z,1.5,.2,.8,p.color);panels.forEach((q,j)=>{const z=4+s.d-q.d;if(z>-14&&z<10)box(c,`flip-panel-${i}-${j}`,x+q.x,height(q),z,2,.25,1.2,q.high?BLUE:GOLD,{rx:q.high?.3*Math.sin(c.time*2+q.phase):0});});box(c,`boost-bg-${i}`,x,-.05,11,6,.1,.4,'#758a91');box(c,`boost-${i}`,x-3+s.meter/4,-.01,11,s.meter/2,.15,.35,p.color);});}};
}
function slowG(c){
 const players=setup(c,Infinity),platforms=Array.from({length:13},(_,j)=>({x:j===0?0:Math.sin(j*1.7)*2.4,y:j*2.8,z:j===0?0:Math.cos(j*1.2)*1.5})),state=players.map(()=>({x:0,z:0,y:0,vy:0,ground:0,boost:0,checkpoint:0,pace:c.rand(7,10)}));c.view={size:31,eye:[0,18,29],target:[0,12,0]};
 return{update(dt){c.hint('방향 이동 · A 점프. 공중에서 A를 다시 누를 때마다 약한 추진력으로 체공을 늘릴 수 있습니다. 위쪽 목표에 먼저 도착하세요.');players.forEach((p,i)=>{const s=state[i],goal=platforms[Math.min(12,s.checkpoint+1)],input=c.input(p,()=>{const dx=goal.x-s.x,dz=goal.z-s.z;return{x:clamp(dx*2,-1,1),z:clamp(dz*2,-1,1),a:(s.ground!==null||s.y<goal.y+1.3)&&Math.floor(c.time*s.pace)%2===0};});s.x=clamp(s.x+input.x*dt*3.3,-4,4);s.z=clamp(s.z+input.z*dt*3.3,-3,3);if(input.ap){if(s.ground!==null){s.vy=5.8;s.ground=null;s.boost=0;}else if(s.boost<5&&s.vy>-1.5){s.vy=Math.min(6.5,s.vy+1.4);s.boost++;}}if(s.ground!==null){const q=platforms[s.ground];if(Math.hypot(s.x-q.x,s.z-q.z)>1.3)s.ground=null;}if(s.ground===null){const oldY=s.y;s.vy-=4.3*dt;s.y+=s.vy*dt;if(s.vy<0){const landed=platforms.map((q,j)=>({...q,j})).filter(q=>oldY>=q.y&&s.y<=q.y&&Math.hypot(s.x-q.x,s.z-q.z)<1.4).sort((a,b)=>b.y-a.y)[0];if(landed){s.y=landed.y;s.ground=landed.j;s.checkpoint=Math.max(s.checkpoint,landed.j);s.vy=0;}}if(s.y<-4){s.x=0;s.z=0;s.y=0;s.ground=0;s.vy=0;s.checkpoint=0;}}p.x=(i-1.5)*8+s.x;p.z=s.z;p.y=s.y;p.score=s.checkpoint;});const lead=Math.max(...state.map(s=>s.y));c.view={size:35,eye:[0,lead+11,30],target:[0,lead+1,0]};const done=players.filter(p=>p.score>=12);if(done.length)c.complete(done.map(p=>p.i),'저중력 정상 도착');
 },render(){players.forEach((p,i)=>{const x=(i-1.5)*8;platforms.forEach((q,j)=>c.draw(`moon-platform-${i}-${j}`,'cylinder',{x:x+q.x,y:q.y-.2,z:q.z,sx:2.8,sy:.4,sz:2.8,color:j===12?GOLD:'#a8c2c4'}));text(c,`moon-goal-${i}`,'GOAL',x+platforms[12].x,35,platforms[12].z,3,p.color);});}};
}

function fisticlouds(c){
 const players=setup(c,60),tiles=Array.from({length:5},(_,i)=>({x:i?Math.cos((i-1)*Math.PI/2)*4:0,z:i?Math.sin((i-1)*Math.PI/2)*4:0,a:0,px:0,pz:0,pa:0})),state=players.map(()=>({tile:null,cool:0,stun:0}));players.forEach((p,i)=>{p.x=Math.cos(i*Math.PI/2)*4;p.z=Math.sin(i*Math.PI/2)*4;state[i].tile=i+1;});
 const inside=(p,t)=>{const dx=p.x-t.x,dz=p.z-t.z,x=dx*Math.cos(t.a)+dz*Math.sin(t.a),z=-dx*Math.sin(t.a)+dz*Math.cos(t.a);return Math.abs(x)<1.75&&Math.abs(z)<1.75;};
 return{update(dt){c.hint('방향 이동 · A 점프 · B 펀치 · 공중 B 발차기. 가운데는 고정, 분홍 발판은 움직이고 회전합니다.');tiles.forEach((t,j)=>{t.px=t.x;t.pz=t.z;t.pa=t.a;if(j){const a=(j-1)*Math.PI/2+.28*Math.sin(c.time*.45),r=3.9+Math.sin(c.time*.8+j)*.7;t.x=Math.cos(a)*r;t.z=Math.sin(a)*r;t.a=.55*Math.sin(c.time*.5+j);}});players.filter(p=>p.alive).forEach(p=>{const s=state[p.i];if(s.tile!==null&&p.y===0){const t=tiles[s.tile],r=diff(t.a,t.pa),dx=p.x-t.px,dz=p.z-t.pz;p.x=t.x+dx*Math.cos(r)-dz*Math.sin(r);p.z=t.z+dx*Math.sin(r)+dz*Math.cos(r);}const target=players.filter(q=>q!==p&&q.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>{const targetTile=tiles.find(t=>inside(p,t)),q=target&&dist(p,target)<3.8?target:targetTile||tiles[0];return{...toward(p,q.x,q.z),a:!tiles.some(t=>inside({x:p.x+(q.x-p.x)*.25,z:p.z+(q.z-p.z)*.25},t))||c.rng()<.012,b:!!target&&dist(p,target)<1.9&&s.cool<=0};});s.cool-=dt;s.stun=Math.max(0,s.stun-dt);if(!s.stun)c.move(p,input,4.6,false);p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.pow(.92,dt*60);p.vz*=Math.pow(.92,dt*60);c.jump(p,input,7.5);if(input.bp&&s.cool<=0){s.cool=.48;players.forEach(q=>{if(q!==p&&q.alive&&dist(p,q)<(p.y>.2?2.1:1.8)&&Math.abs(p.y-q.y)<1.7){const v=toward(p,q.x,q.z);q.vx=v.x*(p.y>.2?12:8);q.vz=v.z*(p.y>.2?12:8);state[q.i].stun=.25;}});}const j=tiles.findIndex(t=>inside(p,t));s.tile=p.y===0&&j>=0?j:null;if(p.y===0&&j<0)c.eliminate(p);});c.lastStanding();
 },render(){tiles.forEach((t,j)=>box(c,`cloud-tile-${j}`,t.x,-.25,t.z,3.5,.5,3.5,j?PINK:GOLD,{ry:-t.a}));for(let j=0;j<7;j++)ball(c,`cloud-${j}`,Math.sin(j*7)*10,-4,Math.cos(j*7)*6,5,'#d5e5e2',{sy:1.5});},timeout(){c.survivors('하늘 발판 생존');}};
}
function starring(c){
 const players=setup(c,Infinity);boards(c);const constellations=[{points:[[-1,-1],[0,-1.7],[1,-1],[1.4,.1],[.6,.9],[-.6,.9],[-1.4,.1]],edges:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,0],[0,2]]},{points:[[-1.3,.5],[-.5,-1],[.4,-1.3],[1.2,-.5],[.9,.8],[0,1.1]],edges:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[1,4]]},{points:[[-1.2,-1.1],[0,-.4],[1.2,-1.1],[.8,1],[0,.55],[-.8,1]],edges:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[1,4]]}],state=players.map((p,i)=>({drawing:0,lines:new Set(),anchor:null,cx:layouts[i].x,cz:layouts[i].z,botEdge:0,botPhase:0,pace:c.rand(6,8)}));let round=0,start=0,rank=0;
 const model=s=>constellations[(round+s.drawing)%3],point=(i,j,s)=>{const q=model(s).points[j];return{x:layouts[i].x+1.6+q[0]*1.3,z:layouts[i].z+q[1]*1.3};};const edgeKey=(a,b)=>[a,b].sort((a,b)=>a-b).join('-');
 function begin(){start=c.time;rank=0;state.forEach(s=>{s.drawing=0;s.lines.clear();s.anchor=null;s.botEdge=0;s.botPhase=0;s.down=false;});}
 return{update(dt){c.hint(`별자리 두 그림을 보고 선을 그대로 연결하세요. ${Math.min(3,round+1)}/3회 · ${Math.max(0,Math.ceil(20-(c.time-start)))}초 · 드래그 또는 방향+A.`);players.forEach((p,i)=>{const s=state[i];if(s.drawing>=2)return;const m=model(s),e=m.edges.find(([a,b])=>!s.lines.has(edgeKey(a,b))),input=c.input(p,()=>{if(!e)return{};const a=point(i,e[0],s),b=point(i,e[1],s),dest=s.botPhase===0?a:b,v=toward({x:s.cx,z:s.cz},dest.x,dest.z),d=Math.min(dist({x:s.cx,z:s.cz},dest),dt*s.pace);let down=s.botPhase===1;if(s.botPhase===0&&dist({x:s.cx,z:s.cz},a)<.06){down=true;s.botPhase=1;}else if(s.botPhase===1&&dist({x:s.cx,z:s.cz},b)<.06){down=false;s.botPhase=0;}return{pointer:{valid:true,worldValid:true,worldX:s.cx+v.x*d,worldZ:s.cz+v.z*d,down}};});const g=gesture(c,s,input,layouts[i]);if(g.pressed)s.anchor=null;if(g.down){const near=m.points.findIndex((q,j)=>dist(g,point(i,j,s))<.3);if(near>=0&&s.anchor===null)s.anchor=near;else if(near>=0&&near!==s.anchor){const k=edgeKey(near,s.anchor);if(m.edges.some(([a,b])=>edgeKey(a,b)===k)){s.lines.add(k);c.sound?.(620,.03);}else{s.lines.clear();c.sound?.(140,.04);}s.anchor=near;}}if(g.released)s.anchor=null;if(s.lines.size===m.edges.length){s.drawing++;s.lines.clear();s.anchor=null;s.botPhase=0;if(s.drawing===2)c.points(p,[9,6,3,0][Math.min(3,rank++)]);}});if(c.time-start>=20||state.every(s=>s.drawing===2)){round++;if(round===3)high(c,'별자리 세 라운드 순위 합계');else begin();}
 },render(){players.forEach((p,i)=>{const s=state[i],a=layouts[i];board(c,i,s.drawing>=2?'두 별자리 완성':`별자리 ${s.drawing+1}/2`);if(s.drawing>=2)return;const m=model(s);box(c,`night-${i}`,a.x,.01,a.z,10,.06,6,'#243c55');m.points.forEach((q,j)=>{const dest=point(i,j,s);ball(c,`star-${i}-${j}`,dest.x,.2,dest.z,.2,GOLD);ball(c,`reference-star-${i}-${j}`,a.x-3+q[0]*.6,.2,a.z+q[1]*.6,.12,'#e9e9da');});m.edges.forEach(([u,v],j)=>{line(c,`reference-edge-${i}-${j}`,{x:a.x-3+m.points[u][0]*.6,z:a.z+m.points[u][1]*.6},{x:a.x-3+m.points[v][0]*.6,z:a.z+m.points[v][1]*.6},'#e8e4c1',.045);if(s.lines.has(edgeKey(u,v)))line(c,`constellation-edge-${i}-${j}`,point(i,u,s),point(i,v,s),p.color,.1);});if(s.anchor!==null&&s.down)line(c,`pencil-${i}`,point(i,s.anchor,s),{x:s.cx,z:s.cz},p.color,.04);c.draw(`star-cursor-${i}`,'ring',{x:s.cx,y:.1,z:s.cz,sx:.35,sy:.35,rx:-Math.PI/2,color:p.color});});}};
}
function pokey(c){
 const players=setup(c,60),pokeys=[];let next=.5,id=0;const radius=6.6;
 return{update(dt){c.hint('방향키만으로 움직이는 모래에 버티세요. 솟는 선인장을 피하고 상대를 몸으로 밀 수 있습니다. 떨어지면 탈락!');if(c.time>=next){const a=c.rand(0,Math.PI*2),r=c.rand(1,5.5);pokeys.push({id:id++,x:Math.cos(a)*r,z:Math.sin(a)*r,born:c.time});next=c.time+c.rand(.8,1.4);}players.filter(p=>p.alive).forEach(p=>{const near=pokeys.filter(q=>c.time-q.born<5),input=c.input(p,()=>{const opts=Array.from({length:12},(_,j)=>({x:Math.cos(j*Math.PI/6)*3,z:Math.sin(j*Math.PI/6)*3})),q=opts.sort((a,b)=>{const score=q=>Math.min(8,...near.map(t=>dist(q,t)))-dist(p,q)*.15;return score(b)-score(a);})[0];return toward(p,q.x,q.z);});c.move(p,input,4.7,false);const spin=.65+.25*Math.sin(c.time*.4),oldX=p.x;p.x+=(-p.z*spin+p.x*.12+p.vx)*dt;p.z+=(oldX*spin+p.z*.12+p.vz)*dt;p.vx*=Math.pow(.91,dt*60);p.vz*=Math.pow(.91,dt*60);near.forEach(q=>{const age=c.time-q.born;if(age>.65&&age<4.7&&dist(p,q)<1.15){const v=toward(q,p.x,p.z);p.vx=v.x*7;p.vz=v.z*7;}});});for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=players[i],b=players[j],d=dist(a,b);if(a.alive&&b.alive&&d<1&&d>.01){const v=toward(a,b.x,b.z);a.x-=v.x*(1-d)*.5;a.z-=v.z*(1-d)*.5;b.x+=v.x*(1-d)*.5;b.z+=v.z*(1-d)*.5;}}players.forEach(p=>{if(p.alive&&Math.hypot(p.x,p.z)>radius)c.eliminate(p);});c.lastStanding();
 },render(){c.draw('sand-pillar','cylinder',{x:0,y:-2,z:0,sx:radius*2,sy:4,sz:radius*2,color:'#d5ba78'});for(let j=0;j<5;j++)c.draw(`sand-flow-${j}`,'ring',{x:0,y:.02,z:0,sx:2+j*2.4,sy:2+j*2.4,rx:-Math.PI/2,rz:c.time*.2,color:'#c69d66'});pokeys.forEach(q=>{const age=c.time-q.born;if(age>5)return;if(age<.65)c.draw(`pokey-warn-${q.id}`,'ring',{x:q.x,y:.03,z:q.z,sx:2,sy:2,rx:-Math.PI/2,color:GOLD});else for(let n=0;n<4;n++)ball(c,`pokey-${q.id}-${n}`,q.x,n*.7+.4,q.z,.9,n===3?GOLD:GREEN);});},timeout(){c.survivors('움직이는 모래 생존');}};
}
function hare(c){
 const players=setup(c,30),rabbits=[],held=Array(4).fill(null);let next=0,id=0;c.bounds={x:8,z:5};
 return{update(dt){c.hint('방향 이동 · A로 토끼 잡기/놓기. 가운데 우리에 놓으면 1점, 금색 토끼는 3점입니다.');if(c.time>=next){const a=c.rand(0,Math.PI*2);rabbits.push({id:id++,x:Math.cos(a)*7.5,z:Math.sin(a)*4.5,gold:c.rng()<.18,owner:null,live:true,phase:c.rand(0,6)});next=c.time+.7;}rabbits.filter(r=>r.live&&r.owner===null).forEach(r=>{const threat=players.filter(p=>held[p.i]===null).sort((a,b)=>dist(r,a)-dist(r,b))[0],v=threat&&dist(r,threat)<2?toward(threat,r.x,r.z):{x:Math.cos(c.time+r.phase),z:Math.sin(c.time*.7+r.phase)};r.x=clamp(r.x+v.x*dt*2,-7.5,7.5);r.z=clamp(r.z+v.z*dt*2,-4.6,4.6);if(Math.abs(r.x)<1.7&&Math.abs(r.z)<1.5)r.x=Math.sign(r.x||1)*1.7;});players.forEach(p=>{const h=held[p.i],target=h?{x:0,z:2}:rabbits.filter(r=>r.live&&r.owner===null).sort((a,b)=>dist(p,a)-dist(p,b))[0],input=c.input(p,()=>target?{...toward(p,target.x,target.z),a:dist(p,target)<1.2&&Math.floor(c.time*10)%2===0}:{});c.move(p,input,h?4.8:5.7);if(input.ap){if(h){if(Math.hypot(p.x,p.z)<2.6){c.points(p,h.gold?3:1);h.live=false;}else{h.owner=null;h.x=p.x;h.z=p.z;}held[p.i]=null;}else{const r=rabbits.find(r=>r.live&&r.owner===null&&dist(p,r)<1.25);if(r){r.owner=p.i;held[p.i]=r;}}}if(held[p.i]){held[p.i].x=p.x;held[p.i].z=p.z;}});
 },render(){c.arena({color:'#ccb58e'});box(c,'rabbit-pen',0,.2,0,3.3,.4,2.7,'#84b493');for(let j=0;j<8;j++){const a=j*Math.PI/4;box(c,`pen-post-${j}`,Math.cos(a)*1.8,.6,Math.sin(a)*1.5,.2,1.2,.2,'#a17f56');}rabbits.filter(r=>r.live).forEach(r=>{const y=r.owner!==null?1.5:.3;ball(c,`rabbit-${r.id}`,r.x,y,r.z,.65,r.gold?GOLD:'#efe9d5');box(c,`rabbit-ears-${r.id}`,r.x,y+.5,r.z,.4,.65,.17,r.gold?GOLD:PINK);});},timeout(){high(c,'우리로 데려온 토끼 점수');}};
}

function deck(c){
 const players=setup(c,Infinity),coins=Array.from({length:100},(_,j)=>({id:j,x:c.rand(-7.5,7.5),d:8+j*1.55,speed:j%5===0?1.8:0,live:true,born:-1})),eggs=Array.from({length:22},(_,j)=>({x:c.rand(-7.3,7.3),d:12+j*6.5,hit:new Set()}));let id=100;players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=3;});
 return{update(dt){const progress=c.time*5;c.hint('방향키로 스케이트보드를 조종하며 동전을 모으세요. 가시 알에 닿으면 세 개를 떨어뜨리고 누구나 다시 주울 수 있습니다.');coins.forEach(q=>{if(q.live)q.d+=q.speed*dt;});players.forEach(p=>{const options=coins.filter(q=>q.live&&q.d>progress-5&&q.d<progress+14),input=c.input(p,()=>{const q=options.sort((a,b)=>dist(p,{x:a.x,z:4+progress-a.d})-dist(p,{x:b.x,z:4+progress-b.d}))[0];if(!q)return{};const threat=eggs.find(e=>dist(p,{x:e.x,z:4+progress-e.d})<2),target=threat?{x:p.x+(p.x>threat.x?3:-3),z:p.z}:{x:q.x,z:4+progress-q.d};return toward(p,target.x,target.z);});c.move(p,input,5);coins.forEach(q=>{if(q.live&&!(q.owner===p.i&&c.time-q.born<.5)&&dist(p,{x:q.x,z:4+progress-q.d})<.7){q.live=false;c.points(p);}});eggs.forEach(e=>{if(!e.hit.has(p.i)&&dist(p,{x:e.x,z:4+progress-e.d})<.9){e.hit.add(p.i);const n=Math.min(3,p.score);c.points(p,-n);for(let k=0;k<n;k++)coins.push({id:id++,x:clamp(p.x+c.rand(-1.6,1.6),-8,8),d:progress+4-p.z+c.rand(-1,1),speed:c.rand(1,3),live:true,born:c.time,owner:p.i});}});});if(progress>=180)high(c,'내리막 동전 수');
 },render(){const progress=c.time*5;box(c,'skate-road',0,-.4,-4,18,.5,34,'#adc4b7');players.forEach(p=>box(c,`skateboard-${p.i}`,p.x,.1,p.z,1.2,.2,.65,p.color));coins.forEach(q=>{const z=4+progress-q.d;if(q.live&&z>-22&&z<9)c.draw(`deck-coin-${q.id}`,'cylinder',{x:q.x,y:.5,z,sx:.5,sy:.13,sz:.5,rx:Math.PI/2,color:GOLD});});eggs.forEach((e,j)=>{const z=4+progress-e.d;if(z>-22&&z<9){ball(c,`spiny-egg-${j}`,e.x,.45,z,1,PINK);c.draw(`egg-spike-${j}`,'cone',{x:e.x,y:1,z,sx:.4,sy:.6,sz:.4,color:'#f3eedb'});}});}};
}
function paddle(c){
 const players=setup(c,Infinity),state=players.map(()=>({x:0,d:0,speed:0,heading:0,stroke:null,lastStroke:0,cadence:c.rand(5.5,7.5)}));c.view={size:35,eye:[0,32,28],target:[0,0,0]};
 const center=d=>Math.sin(d*.08)*2+Math.sin(d*.035)*1.2;
 return{update(dt){c.hint('카누의 왼쪽/오른쪽 물을 뒤로 드래그해 노를 저으세요. 키보드 A 왼쪽 노 · B 오른쪽 노. 번갈아 추진하고 방향을 맞추세요.');players.forEach((p,i)=>{const s=state[i],lane=(i-1.5)*8,pulse=Math.floor(c.time*s.cadence)%2===0,input=c.input(p,()=>{const desired=Math.atan2(center(s.d+5)-s.x,5),turn=diff(desired,s.heading);return turn>0?{a:pulse}:{b:pulse};});let stroke=0;if(input.ap)stroke=1;if(input.bp)stroke=-1;const ptr=input.pointer;if(ptr.pressed&&ptr.worldValid)s.stroke={x:ptr.worldX,z:ptr.worldZ,endZ:ptr.worldZ};if(s.stroke&&ptr.down&&ptr.worldValid)s.stroke.endZ=ptr.worldZ;if(s.stroke&&ptr.released){const travel=s.stroke.endZ-s.stroke.z;if(travel>.6&&Math.abs(s.stroke.x-(lane+s.x))<2.5)stroke=s.stroke.x<lane+s.x?1:-1;s.stroke=null;}if(stroke&&c.time-s.lastStroke>.12){s.speed=Math.min(8,s.speed+1.2);s.heading=clamp(s.heading+stroke*.13,-1.2,1.2);s.lastStroke=c.time;c.sound?.(220,.04);}s.speed*=Math.pow(.985,dt*60);s.x+=Math.sin(s.heading)*s.speed*dt;s.d+=Math.cos(s.heading)*s.speed*dt;const bank=center(s.d);if(Math.abs(s.x-bank)>2.25){s.x=bank+Math.sign(s.x-bank)*2.25;s.speed*=.45;s.heading=clamp(s.heading-Math.sign(s.x-bank)*dt*2,-1.2,1.2);}p.x=lane+s.x;p.z=4;p.y=.2;p.rotation=Math.PI/2-s.heading;p.score=s.d;});const done=players.filter((p,i)=>state[i].d>=140);if(done.length)c.complete(done.map(p=>p.i),'굽이치는 강 결승 도착');
 },render(){players.forEach((p,i)=>{const s=state[i],lane=(i-1.5)*8,theme=Math.min(3,Math.floor(s.d/35)),shore=['#8fa99e','#d8bb7b','#97bb81','#decf9c'][theme];box(c,`river-shore-${i}`,lane,-.3,0,8,.3,28,shore);for(let j=0;j<15;j++){const z=12-j*2,d=s.d+4-z,x=lane+center(d);box(c,`river-${i}-${j}`,x,-.08,z,4.6,.15,2.2,BLUE);}box(c,`canoe-${i}`,p.x,.1,4,1.1,.4,2.8,p.color,{ry:s.heading});const strokeSide=Math.floor(c.time*5)%2?1:-1;box(c,`paddle-${i}`,p.x+strokeSide*.9,.4,4,.15,.2,2,GOLD,{ry:strokeSide*.6});const z=4+s.d-140;if(z>-12&&z<13)box(c,`finish-bridge-${i}`,lane+center(140),.6,z,5,.4,1.8,'#b08c60');text(c,`canoe-progress-${i}`,`${Math.min(100,Math.floor(s.d/140*100))}%`,lane,1,12,4,p.color);});}};
}
function golf(c){
 const players=setup(c,30);boards(c);const targets=[{x:-3.4,z:-1.9,v:5,r:.75},{x:-1.25,z:-2.4,v:20,r:.48},{x:1.1,z:-2.1,v:-5,r:.75},{x:3.3,z:-1.6,v:10,r:.65}],state=players.map((p,i)=>({cx:layouts[i].x,cz:layouts[i].z+2.4,start:null,shot:null,cool:0,phase:0,pace:c.rand(8,11)}));
 return{update(dt){c.hint('공 위에서 목표 쪽으로 실제 선을 그어 스윙하세요. 1P 드래그 / 방향+A. 목표는 -5·5·10·20점, 30초 합계 비교.');players.forEach((p,i)=>{const s=state[i],a=layouts[i],origin={x:a.x,z:a.z+2.4},target={x:a.x+targets[1].x,z:a.z+targets[1].z},input=c.input(p,()=>{const q=s.phase===0?origin:target,v=toward({x:s.cx,z:s.cz},q.x,q.z),d=Math.min(dist({x:s.cx,z:s.cz},q),dt*s.pace);let down=s.phase===1;if(!s.shot&&s.cool<=0&&s.phase===0&&dist({x:s.cx,z:s.cz},origin)<.05){s.phase=1;down=true;}else if(s.phase===1&&dist({x:s.cx,z:s.cz},target)<.05){s.phase=0;down=false;}return{pointer:{valid:true,worldValid:true,worldX:s.cx+v.x*d,worldZ:s.cz+v.z*d,down}};});s.cool=Math.max(0,s.cool-dt);const g=gesture(c,s,input,a);if(!s.shot&&s.cool===0&&g.pressed&&dist(g,origin)<.85)s.start={x:g.x,z:g.z};if(g.released&&s.start&&!s.shot){const dx=g.x-s.start.x,dz=g.z-s.start.z,len=Math.hypot(dx,dz);if(len>.4){const scale=Math.min(1,7/len);s.shot={x:origin.x,z:origin.z,vx:dx*scale/.8,vz:dz*scale/.8,age:0};}s.start=null;}if(s.shot){const b=s.shot;b.age+=dt;b.x+=b.vx*dt;b.z+=b.vz*dt;if(b.age>=.8){const q=targets.find(q=>dist(b,{x:a.x+q.x,z:a.z+q.z})<q.r);if(q)c.points(p,q.v);s.shot=null;s.cool=.15;}}});
 },render(){players.forEach((p,i)=>{const a=layouts[i],s=state[i];board(c,i,`골프 ${p.score}점`);targets.forEach((q,j)=>{c.draw(`golf-target-${i}-${j}`,'cylinder',{x:a.x+q.x,y:.03,z:a.z+q.z,sx:q.r*2,sy:.06,sz:q.r*2,color:q.v<0?PINK:q.v===20?GOLD:GREEN});text(c,`golf-value-${i}-${j}`,q.v,a.x+q.x,.6,a.z+q.z,1.3);});const b=s.shot;ball(c,`golf-ball-${i}`,b?.x??a.x,b?.age?Math.sin(Math.min(1,b.age/.8)*Math.PI)*1.5+.15:.15,b?.z??a.z+2.4,.3,'#f7f3db');if(s.start&&s.down)line(c,`swing-${i}`,s.start,{x:s.cx,z:s.cz},p.color,.08);c.draw(`golf-cursor-${i}`,'ring',{x:s.cx,y:.1,z:s.cz,sx:.35,sy:.35,rx:-Math.PI/2,color:p.color});});},timeout(){high(c,'30초 골프 표적 점수');}};
}
function amp(c){
 const players=setup(c,60),vertices=Array.from({length:8},(_,j)=>({x:Math.cos(j*Math.PI/4)*7,z:Math.sin(j*Math.PI/4)*5}));let from=vertices.map(v=>({...v})),target=vertices.map(v=>({...v})),start=0,next=2;
 const inside=p=>{let yes=false;for(let i=0,j=7;i<8;j=i++){const a=vertices[i],b=vertices[j];if((a.z>p.z)!==(b.z>p.z)&&p.x<(b.x-a.x)*(p.z-a.z)/(b.z-a.z)+a.x)yes=!yes;}return yes;};
 const safety=p=>Math.min(...vertices.map((v,j)=>segmentDistance(p,v,vertices[(j+1)%8])));
 return{update(dt){c.hint('방향키로 움직이는 여덟 전기 구슬과 연결선을 피하세요. 경계가 다른 모양으로 바뀝니다. 닿으면 탈락!');if(c.time>=next){from=vertices.map(v=>({...v}));const ox=c.rand(-1.8,1.8),oz=c.rand(-1.3,1.3),phase=c.rand(-.35,.35);target=vertices.map((v,j)=>{const a=j*Math.PI/4+phase,r=c.rand(3.1,6.7);return{x:ox+Math.cos(a)*r,z:oz+Math.sin(a)*r*.75};});start=c.time;next=c.time+3.8;}const t=clamp((c.time-start)/2.5,0,1);vertices.forEach((v,j)=>{v.x=from[j].x+(target[j].x-from[j].x)*t;v.z=from[j].z+(target[j].z-from[j].z)*t;});players.filter(p=>p.alive).forEach(p=>{const input=c.input(p,()=>{const candidates=Array.from({length:81},(_,j)=>({x:(j%9-4)*.8,z:(Math.floor(j/9)-4)*.6})).filter(inside),q=candidates.sort((a,b)=>(safety(b)-dist(p,b)*.06)-(safety(a)-dist(p,a)*.06))[0]||{x:0,z:0};return toward(p,q.x,q.z);});c.move(p,input,4.8,false);if(safety(p)<.43||!inside(p))c.eliminate(p);});c.lastStanding();
 },render(){c.arena({width:19,depth:15,color:'#445661'});vertices.forEach((v,j)=>{ball(c,`amp-${j}`,v.x,.65,v.z,1,BLUE);text(c,`amp-eyes-${j}`,'··',v.x,1.35,v.z,1,GOLD);line(c,`electric-line-${j}`,v,vertices[(j+1)%8],c.time% .12<.06?GOLD:'#e9f7dc',.12,.6);});},timeout(){c.survivors('전기 우리 생존');}};
}

export const games={"Slip 'n' Slip":slip,'No-Traction Action':noTraction,'Blown Hover':blownHover,'Slow G':slowG,'Fisticlouds':fisticlouds,'Starring Artist':starring,'Pokey Corral':pokey,'Hare Today':hare,'Deck Hunt':deck,'Paddle Skedaddle':paddle,'Drive for Show':golf,'Amp My Style':amp};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(n=>[n,['island-tour']]));
export const notes={
 "Slip 'n' Slip":'원작 45초·방향 이동·A 점프·바다로 떨어지면 탈락. 펭귄이 얼음 위를 이동하며 무게 중심으로 기울기를 만들고, 관성과 경사 가속을 받습니다. 마지막 생존자 또는 시간 종료 생존자 승리. 타원 얼음 크기·틸트/마찰/충돌 계수는 재구성했습니다.',
 'No-Traction Action':'원작 일반 경기 세 바퀴. ←/→ 조향, A 가속, B 브레이크. 실제 속도 벡터와 차체 방향이 별도로 움직여 미끄러집니다. 타원 안·밖 벽에 부딪히면 감속. 코스를 한 방향으로 완주한 회전량으로 바퀴를 셉니다. 트랙 치수·물리 계수는 재구성이며 제한시간은 두지 않았습니다.',
 'Blown Hover':'원작 자동 전진·좌우 조종·A 점프, 위/아래로 피하는 패널과 충돌 시 감소하는 속도 게이지. 먼저 결승 도착 승리. 185단위 코스·26패널·최고속도 12·피격 감속률은 재구성 수치입니다. 높은 패널은 밑으로, 낮은 패널은 점프로 피할 수 있습니다.',
 'Slow G':'방향 이동·A 점프, 공중에서 A를 다시 누르면 체공 시간이 늘어납니다. 저중력으로 실제 상승/낙하하며 발판 위에 착지하고 먼저 꼭대기 도착 승리. 13발판·한 점프당 추가 추진 최대 5회·중력/추진 계수는 재구성했습니다. 바닥 아래로 떨어지면 출발점 복귀.',
 'Fisticlouds':'원작 60초. 방향 이동·A 점프·B 펀치·공중 B 발차기. 가운데 주황 발판은 고정이고 바깥 분홍 발판 네 개가 이동/회전하며 탑승자도 함께 이동합니다. 발판에서 밀려 떨어지면 탈락. 충격량·이동 경로·타격 범위는 재구성 수치입니다.',
 'Starring Artist':'원작 라운드당 20초, 별자리 두 그림, 세 라운드 순위별 9/6/3/0점. 1P 실제 드래그 또는 방향+A 가상 연필로 별 사이를 잇습니다. 표시된 간선만 연결하며 잘못된 별 연결은 현재 그림을 지웁니다. 자체 별자리 도안·잘못된 선의 초기화 처리는 재구성입니다.',
 'Pokey Corral':'원작 60초·이동만 사용. 회전하며 밀어내는 모래 위에서 솟아나는 선인장과 몸 충돌을 피합니다. 가장자리로 떨어지면 탈락, 마지막 또는 종료 시 생존자 승리. 선인장 접촉은 밀림으로 구현했으며 모래 흐름·발생 간격·충격 계수는 새 구성입니다.',
 'Hare Today':'원작 30초. 방향 이동·A 토끼 잡기/놓기. 벽에서 나온 토끼를 가운데 우리에 놓으면 1점, 금색 3점. 밖에 놓으면 다시 도망가며 점수를 주지 않습니다. 토끼 도주·출현 간격·우리 반경은 재구성했습니다.',
 'Deck Hunt':'원작 이동 전용 내리막 스케이트보드. 동전을 모으고 가시 알에 닿으면 최대 세 개를 실제로 떨어뜨립니다. 떨어진 동전은 다시 누구나 주울 수 있습니다. 일부 동전도 아래로 흘러갑니다. 180단위 코스·100개 초기 동전·22알은 재구성이며 원작 제한시간으로 주장하지 않습니다.',
 'Paddle Skedaddle':'원작 터치 노젓기는 카누 양옆에서 뒤쪽으로 드래그하는 스트로크로 옮겼습니다. A는 왼쪽 노, B는 오른쪽 노 한 번. 양쪽 입력이 추진력과 반대 방향 회전을 만들며 굽이치는 강을 먼저 통과하면 승리. 산/사막/초원/해변 네 구간을 표현했습니다. 140단위 길이·스트로크/저항 계수는 재구성했습니다.',
 'Drive for Show':'원작 30초·터치 스윙·-5/5/10/20점 표적. 공 가까이에서 출발해 실제 드래그 방향과 길이로 착지점을 정합니다. 키보드는 방향+A 가상 커서, A를 놓으면 타구. 공 궤적·네 표적 배치/반경·0.8초 비행은 재구성 수치입니다.',
 'Amp My Style':'원작 60초·이동 전용·여덟 전기 구슬과 그 연결선의 모양이 계속 변합니다. 몸과 이동 선분의 거리로 접촉을 판정하고 닿으면 탈락. 마지막 생존자 또는 종료 시 생존자 승리. 경계 꼭짓점·변형 주기·충돌 반경은 재구성했습니다.'
};
