import{clamp,dist,toward}from'../core.js';
const PINK='#ef90aa',BLUE='#72b7d9',GOLD='#eac563',GREEN='#86be96';
const box=(c,id,x,y,z,sx,sy,sz,color,more={})=>c.draw(id,'box',{x,y,z,sx,sy,sz,color,...more});
const ball=(c,id,x,y,z,s,color,more={})=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color,...more});
const text=(c,id,label,x=0,y=1,z=0,size=3,color='#294652')=>c.draw(id,'text',{text:String(label),x,y,z,sx:size,sy:size/4,color});
const layouts=[{x:-6,z:-5},{x:6,z:-5},{x:-6,z:5},{x:6,z:5}];
const angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function setup(c,limit=Infinity){c.limit=limit;c.activePlayers=[0,1,2,3];return c.players;}
function boards(c){c.view={size:28,eye:[0,30,24],target:[0,0,0]};c.players.forEach((p,i)=>{p.x=layouts[i].x;p.z=layouts[i].z+3.8;p.scale=.6;});}
function board(c,i,label){const a=layouts[i];box(c,`board-${i}`,a.x,-.2,a.z,11,.3,8.5,'#e7edd8');text(c,`board-label-${i}`,label,a.x,.5,a.z-3.5,7,c.players[i].color);}
function line(c,id,a,b,color,width=.07,y=.08){const dx=b.x-a.x,dz=b.z-a.z;box(c,id,(a.x+b.x)/2,y,(a.z+b.z)/2,Math.hypot(dx,dz),.07,width,color,{ry:-Math.atan2(dz,dx)});}
function high(c,reason){const best=Math.max(...c.players.map(p=>p.score)),w=c.players.filter(p=>p.score===best);c.complete(w.length===4?[]:w.map(p=>p.i),reason);}
function gesture(c,p,s,input,center={x:0,z:0},rx=8,rz=5){const ptr=input.pointer;let down;if(ptr.worldValid&&(ptr.down||ptr.released)){s.cx=ptr.worldX;s.cz=ptr.worldZ;down=ptr.down;}else{s.cx=clamp((s.cx??center.x)+input.x*c.dt*7,center.x-rx,center.x+rx);s.cz=clamp((s.cz??center.z)+input.z*c.dt*7,center.z-rz,center.z+rz);down=input.a;}const g={x:s.cx,z:s.cz,down,pressed:down&&!s.gDown,released:!down&&!!s.gDown,dx:down&&s.gDown?s.cx-s.gX:0,dz:down&&s.gDown?s.cz-s.gZ:0};s.gDown=down;s.gX=s.cx;s.gZ=s.cz;return g;}
function rotateInput(s,input,center){let angle=null;const ptr=input.pointer;if(ptr.down&&ptr.worldValid&&Math.hypot(ptr.worldX-center.x,ptr.worldZ-center.z)>.25)angle=Math.atan2(ptr.worldZ-center.z,ptr.worldX-center.x);else if(Math.hypot(input.x,input.z)>.4)angle=Math.atan2(input.z,input.x);let delta=0;if(angle!==null&&s.lastAngle!==null&&s.lastAngle!==undefined){const d=angleDiff(angle,s.lastAngle);if(Math.abs(d)<2)delta=d;}s.lastAngle=angle;return delta;}
function inside(point,polygon){let yes=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a.z>point.z)!==(b.z>point.z)&&point.x<(b.x-a.x)*(point.z-a.z)/(b.z-a.z)+a.x)yes=!yes;}return yes;}
function cursor(c,p,g,id='cursor'){c.draw(`${id}-${p.i}`,'ring',{x:g.x,y:.12,z:g.z,sx:.5,sy:.5,sz:1,rx:-Math.PI/2,color:p.color});}

function wrangler(c){
 const players=setup(c,20),npcs=[],state=players.map(()=>({path:[],length:0,locked:false,cx:0,cz:0,bot:null}));players.forEach((p,i)=>{p.x=(i-1.5)*4;p.z=7;});c.view={size:25,eye:[0,27,19],target:[0,0,0]};let id=0,next=0;
 const spawn=()=>{const n=id++;npcs.push({id:n,x:c.rand(-7,7),z:c.rand(-4,4),vx:c.rand(-.7,.7),vz:c.rand(-.7,.7),kind:n%6===0?'bomb':c.time>=15&&n%2===0?'gold':'bird',alive:true});};for(let i=0;i<20;i++)spawn();
 return{update(dt){c.hint('궤적을 닫아 대상을 둘러싸세요. 1P 마우스 드래그, 키보드는 A를 누른 채 방향키로 커서 그리기. 보통 1점·금색 3점·폭탄은 절반 감점!');if(c.time>next&&npcs.filter(q=>q.alive).length<22){spawn();next=c.time+.25;}npcs.forEach(q=>{if(!q.alive)return;q.x+=q.vx*dt;q.z+=q.vz*dt;if(Math.abs(q.x)>7.7)q.vx*=-1;if(Math.abs(q.z)>4.7)q.vz*=-1;});players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>{if(!s.bot){const available=npcs.filter(q=>q.alive&&q.kind!=='bomb'&&!npcs.some(b=>b.alive&&b.kind==='bomb'&&dist(b,q)<1.6));if(!available.length)return{};const q=c.pick(available);s.bot={x:q.x+q.vx*.35,z:q.z+q.vz*.35,at:c.time,duration:c.rand(.65,.95)};}const elapsed=c.time-s.bot.at;if(elapsed>s.bot.duration){s.bot=null;return{};}const angle=elapsed/s.bot.duration*Math.PI*2;return{pointer:{valid:true,worldValid:true,down:true,worldX:s.bot.x+Math.cos(angle)*1.05,worldZ:s.bot.z+Math.sin(angle)*1.05}};});const g=gesture(c,p,s,input);if(g.pressed){s.path=[{x:g.x,z:g.z}];s.length=0;s.locked=false;}if(g.down&&!s.locked){const last=s.path[s.path.length-1];if(last&&dist(last,g)>.035){s.length+=dist(last,g);s.path.push({x:g.x,z:g.z});}if(s.path.length>12&&s.length>3&&dist(s.path[0],g)<.35){const caught=npcs.filter(q=>q.alive&&inside(q,s.path));let score=0,bomb=false;caught.forEach(q=>{q.alive=false;if(q.kind==='bomb')bomb=true;else score+=q.kind==='gold'?3:1;});p.score+=score;if(bomb)p.score=Math.floor(p.score/2);s.locked=true;if(caught.length)c.sound?.(bomb?100:620,.08);}if(s.path.length>250){s.path=[];s.locked=true;}}if(g.released){s.path=[];s.locked=false;}});
 },render(){c.arena({width:18,depth:12,color:'#a9bf95'});npcs.forEach(q=>{if(q.alive){ball(c,`wrangle-${q.id}`,q.x,.35,q.z,.65,q.kind==='bomb'?'#596775':q.kind==='gold'?GOLD:'#b7946f');if(q.kind==='bomb')text(c,`fuse-${q.id}`,'!',q.x,1.15,q.z,1.2,PINK);}});players.forEach((p,i)=>{const s=state[i];for(let j=1;j<s.path.length;j++)line(c,`lasso-${i}-${j}`,s.path[j-1],s.path[j],p.color,.08);cursor(c,p,{x:s.cx,z:s.cz});});},timeout(){high(c,'20초 포획 점수');}};
}

function rails(c){
 const players=setup(c),state=players.map(()=>({progress:0,boost:0,lastY:null,virtualY:.9,air:false,x:0,y:0,vx:0,vy:0,done:false,rate:c.rand(2.6,4)}));c.view={size:38,eye:[0,18,29],target:[0,2,0]};players.forEach((p,i)=>{p.x=-12;p.z=(i-1.5)*3;p.y=6;});
 return{update(dt){c.hint('위로 길게 반복해서 그어 가속하세요. 마우스 드래그 또는 A+↑, A를 놓으면 가상 펜이 아래로 돌아옵니다. 레일 끝의 속도로 점프 거리 결정!');players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>{const phase=(c.time*s.rate)%1;return{pointer:{valid:true,x:.5,y:.9-phase*.95,down:phase<.85}};});if(s.done)return;if(!s.air){let y=null;if(input.pointer.valid&&input.pointer.down)y=input.pointer.y;else if(input.a){s.virtualY=clamp(s.virtualY+input.z*dt*2.5,.05,.95);y=s.virtualY;}else s.virtualY=.9;if(y!==null&&s.lastY!==null&&y<s.lastY)s.boost=Math.min(35,s.boost+(s.lastY-y)*7);s.lastY=y;s.progress+=dt*(4+s.boost);p.x=-12+s.progress*.6;p.y=6-s.progress*.1;if(s.progress>=40){s.air=true;s.x=0;s.y=2;s.vx=6+s.boost*.55;s.vy=4+s.boost*.1;}}else{s.x+=s.vx*dt;s.vy-=12*dt;s.y+=s.vy*dt;p.x=12+s.x*.35;p.y=Math.max(0,s.y);if(s.y<=0){s.done=true;p.score=Math.round(s.x*10)/10;}}});if(state.every(s=>s.done))high(c,'레일 끝에서 날아간 거리');const far=Math.max(...players.map(p=>p.x));c.view={size:Math.max(38,far+16),eye:[4,18,30],target:[4,2,0]};
 },render(){players.forEach((p,i)=>{const z=(i-1.5)*3;box(c,`handrail-${i}`,0,4,z,25,.2,.3,'#95a5a9',{rz:-.166});box(c,`rail-floor-${i}`,18,-.2,z,30,.4,2,'#d6c49c');text(c,`rail-distance-${i}`,state[i].done?p.score.toFixed(1):'↥',p.x,p.y+2.5,z,3,p.color);});}};
}

function hedge(c){
 const players=setup(c,300);boards(c);const state=players.map((p,i)=>({leaf:0,hedge:0,cx:layouts[i].x,cz:layouts[i].z,offset:0,rub:0,stun:0,entered:0,pace:c.rand(.85,1.2),kinds:Array.from({length:20},(_,j)=>j%6===3?'bee':j%5===2?'lady':'leaf')}));
 return{update(){c.hint('맨 앞 잎을 잡아 옆으로 밀어 주세요. 무당벌레는 문지르고 벌은 떠날 때까지 기다리세요. 1P 드래그 / 방향 커서+A');players.forEach((p,i)=>{const s=state[i],a=layouts[i],kind=s.kinds[s.leaf],input=c.input(p,()=>{if(kind==='bee'||c.time<s.stun)return{};const elapsed=((c.time-s.entered)*s.pace)%1;if(kind==='lady')return{pointer:{valid:true,worldValid:true,down:elapsed<.95,worldX:a.x+Math.sin(c.time*25*s.pace)*.6,worldZ:a.z}};return{pointer:{valid:true,worldValid:true,down:elapsed<.8,worldX:a.x+elapsed*4,worldZ:a.z}};});const g=gesture(c,p,s,input,a,4,2.5);if(c.time<s.stun)return;const near=Math.hypot(g.x-a.x,g.z-a.z)<2.5;if(kind==='bee'){if(g.down&&near){s.stun=c.time+.8;s.entered=c.time-.5;}if(c.time-s.entered>1.3){s.leaf++;s.entered=c.time;s.rub=s.offset=0;}}else if(kind==='lady'){if(g.down&&Math.hypot(g.x-a.x,g.z-a.z)<1.2)s.rub+=Math.hypot(g.dx,g.dz);if(s.rub>5){s.kinds[s.leaf]='leaf';s.rub=0;s.entered=c.time;}}else{if(g.pressed&&near)s.grab=true;if(g.down&&s.grab)s.offset+=Math.hypot(g.dx,g.dz);if(g.released){s.grab=false;s.offset=0;}if(s.offset>2.2){s.leaf++;s.offset=0;s.grab=false;s.entered=c.time;}}s.hedge=Math.floor(s.leaf/4);p.score=s.hedge;});const winners=players.filter(p=>state[p.i].leaf>=20);if(winners.length)c.complete(winners.map(p=>p.i),'다섯 덤불을 지나 연못 도착');
 },render(){players.forEach((p,i)=>{const s=state[i],a=layouts[i],kind=s.kinds[s.leaf];board(c,i,`덤불 ${Math.min(5,s.hedge+1)} / 5`);for(let n=3;n>=0;n--)ball(c,`leaf-${i}-${n}`,a.x+(n===0?s.offset:Math.sin(n)*.3),.1+(3-n)*.08,a.z,4,GREEN,{sy:.12,sz:2.4});if(kind==='lady'){ball(c,`lady-${i}`,a.x,.6,a.z,1.1,PINK);text(c,`lady-spots-${i}`,'● ●',a.x,1,a.z,1.1);}if(kind==='bee'){ball(c,`bee-${i}`,a.x,.9+Math.sin(c.time*10)*.1,a.z,1,GOLD);text(c,`bee-stripe-${i}`,'=',a.x,1.2,a.z,1.2);}if(c.time<s.stun)text(c,`hedge-stun-${i}`,'앗!',a.x,1.5,a.z,3,PINK);cursor(c,p,{x:s.cx,z:s.cz});});},timeout(){c.complete([],'5분 안에 연못에 도착하지 못했습니다');}};
}

function cherry(c){
 const players=setup(c),state=players.map(()=>({lastAngle:null,turns:0,rate:c.rand(7,11)}));boards(c);
 return{update(){c.hint('5초 동안 체리를 원형으로 돌리세요. 어느 방향이든 가능! 1P는 원 안 드래그, 키보드는 방향키를 원형으로 회전.');players.forEach((p,i)=>{const s=state[i],a=layouts[i],input=c.input(p,()=>({x:Math.cos(c.time*s.rate),z:Math.sin(c.time*s.rate)}));if(c.time<=5){s.turns+=Math.abs(rotateInput(s,input,a));p.score=Math.min(200,Math.round(s.turns*3.5*10)/10);}});if(c.time>=7.5)high(c,'체리 던지기 거리');
 },render(){players.forEach((p,i)=>{const s=state[i],a=layouts[i],flight=clamp((c.time-5)/2.5,0,1),angle=s.lastAngle||0;board(c,i,c.time<5?'체리 돌리기':p.score.toFixed(1));c.draw(`cherry-guide-${i}`,'ring',{x:a.x,y:.05,z:a.z,sx:4,sy:4,sz:1,rx:-Math.PI/2,color:p.color});const x=a.x+(c.time<5?Math.cos(angle)*1.8:flight*p.score/60),z=a.z+(c.time<5?Math.sin(angle)*1.8:0),y=c.time<5?.5:Math.sin(flight*Math.PI)*3+.5;ball(c,`cherry-one-${i}`,x,y,z,.65,PINK);ball(c,`cherry-two-${i}`,x+.6,y,z,.65,PINK);box(c,`cherry-stem-${i}`,x+.3,y+.5,z,.08,1,.08,GREEN);});}};
}

function outline(cells){const edges=new Map(),add=(a,b)=>{const key=a.join(',')+'>'+b.join(','),reverse=b.join(',')+'>'+a.join(',');if(edges.has(reverse))edges.delete(reverse);else edges.set(key,[a,b]);};cells.forEach(([x,z])=>{add([x,z],[x+1,z]);add([x+1,z],[x+1,z+1]);add([x+1,z+1],[x,z+1]);add([x,z+1],[x,z]);});const segments=[...edges.values()],points=[segments.shift()[0]];let current=points[0];while(points.length<edges.size+1){const entry=[...edges.values()].find(([a])=>a[0]===current[0]&&a[1]===current[1]);if(!entry)break;current=entry[1];points.push(current);if(current[0]===points[0][0]&&current[1]===points[0][1])break;}return points;}
function segmentDistance(p,a,b){const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((p.x-a.x)*dx+(p.z-a.z)*dz)/(dx*dx+dz*dz||1),0,1);return{d:Math.hypot(p.x-a.x-t*dx,p.z-a.z-t*dz),t};}
function traceCadets(c){
 const players=setup(c,300);boards(c);const pieces=[[[0,0],[1,0],[0,1],[1,1]],[[2,0],[3,0],[2,1],[3,1]],[[4,0],[5,0],[4,1],[5,1]],[[0,2],[0,3],[1,3],[2,3]],[[1,2],[2,2],[3,2],[3,3]],[[4,2],[5,2],[4,3],[5,3]]];const state=players.map(()=>({cx:0,cz:0,claimed:new Set(),piece:null,path:[],coverage:new Set(),invalid:false,locked:false,bot:null,pace:c.rand(5.2,7.4)}));
 const polygon=(i,n)=>outline(pieces[n]).map(([x,z])=>({x:layouts[i].x-3.9+x*1.3,z:layouts[i].z-2.6+z*1.3}));
 const eligible=(s,n)=>!s.claimed.has(n)&&(s.claimed.size===0?n===0:pieces[n].some(([x,z])=>[...s.claimed].some(k=>pieces[k].some(([a,b])=>Math.abs(x-a)+Math.abs(z-b)===1))));
 return{update(){c.hint('자기 색 테두리의 조각을 펜을 떼지 않고 한 바퀴 따라 그리세요. 채운 조각에 닿은 이웃으로 확장합니다. 1P 드래그 / 방향 커서+A');players.forEach((p,i)=>{const s=state[i],input=c.input(p,()=>{if(s.bot&&s.claimed.has(s.bot.n)){s.bot=null;return{};}if(!s.bot){const n=pieces.findIndex((_,n)=>eligible(s,n));if(n<0)return{};s.bot={n,at:c.time};}const poly=polygon(i,s.bot.n),distance=(c.time-s.bot.at)*s.pace;let remaining=distance;for(let n=1;n<poly.length;n++){const len=dist(poly[n-1],poly[n]);if(remaining<=len)return{pointer:{valid:true,worldValid:true,down:true,worldX:poly[n-1].x+(poly[n].x-poly[n-1].x)*remaining/len,worldZ:poly[n-1].z+(poly[n].z-poly[n-1].z)*remaining/len}};remaining-=len;}s.bot=null;return{};});const g=gesture(c,p,s,input,layouts[i],4.7,3);if(g.pressed){s.path=[{x:g.x,z:g.z}];s.coverage.clear();s.invalid=false;s.locked=false;s.piece=pieces.findIndex((_,n)=>eligible(s,n)&&polygon(i,n).slice(1).some((b,j)=>segmentDistance(g,polygon(i,n)[j],b).d<.3));}
  if(g.down&&!s.locked&&s.piece!==null&&s.piece>=0){const poly=polygon(i,s.piece),last=s.path[s.path.length-1]||g,length=dist(last,g),steps=Math.max(1,Math.ceil(length/.08));for(let n=1;n<=steps;n++){const q={x:last.x+(g.x-last.x)*n/steps,z:last.z+(g.z-last.z)*n/steps},near=poly.slice(1).map((b,j)=>({...segmentDistance(q,poly[j],b),j,len:dist(poly[j],b)})).sort((a,b)=>a.d-b.d)[0];if(near.d>.25)s.invalid=true;else s.coverage.add(`${near.j}-${Math.min(Math.ceil(near.len/.2)-1,Math.floor(near.t*Math.ceil(near.len/.2)))}`);}if(length>.035)s.path.push({x:g.x,z:g.z});const total=poly.slice(1).reduce((sum,b,j)=>sum+Math.ceil(dist(poly[j],b)/.2),0);if(s.path.length>12&&dist(g,s.path[0])<.25&&s.coverage.size>=total*.92&&!s.invalid){s.claimed.add(s.piece);p.score=s.claimed.size;s.locked=true;s.path=[];}if(s.path.length>400){s.invalid=true;s.path=s.path.slice(-100);}}if(g.released){s.piece=null;s.path=[];s.locked=false;}});const winners=players.filter(p=>p.score===pieces.length);if(winners.length)c.complete(winners.map(p=>p.i),'도형 윤곽을 따라 격자 완성');
 },render(){players.forEach((p,i)=>{const s=state[i],a=layouts[i];board(c,i,`${s.claimed.size} / ${pieces.length} 조각`);pieces.forEach((cells,n)=>{cells.forEach(([x,z],j)=>box(c,`trace-cell-${i}-${n}-${j}`,a.x-3.25+x*1.3,0,a.z-1.95+z*1.3,1.26,.12,1.26,s.claimed.has(n)?p.color:'#d0d9c9'));const poly=polygon(i,n);for(let j=1;j<poly.length;j++)line(c,`trace-edge-${i}-${n}-${j}`,poly[j-1],poly[j],eligible(s,n)?p.color:'#738887',.09,.12);});for(let j=1;j<s.path.length;j++)line(c,`trace-path-${i}-${j}`,s.path[j-1],s.path[j],s.invalid?'#ce414f':GOLD,.11,.2);cursor(c,p,{x:s.cx,z:s.cz});});},timeout(){c.complete([],'5분 안에 격자를 채우지 못했습니다');}};
}

function hotShots(c){
 const players=setup(c,30);boards(c);const state=players.map((p,i)=>({cx:layouts[i].x,cz:layouts[i].z+2.7,pulling:false,streak:0,ready:0,bot:null,phase:c.rand(0,.3)})),targets=players.map(()=>Array.from({length:8},(_,i)=>({col:i%4,row:Math.floor(i/4),kind:i===1?'boss':i%4===0?'friend':'mage',gone:0}))),arrows=[];let id=0;
 const position=(i,q)=>({x:layouts[i].x-3.6+q.col*2.4,z:layouts[i].z-1.9+q.row*1.7});
 return{update(dt){c.hint('활 아래를 잡아 뒤로 당긴 뒤 놓아 발사하세요. 1P 드래그 / 방향 커서+A. 금색 100·파랑 20·분홍 친구 −30, 연속 적중 보너스.');players.forEach((p,i)=>{const s=state[i],a=layouts[i],base={x:a.x,z:a.z+2.7};const input=c.input(p,()=>{const phase=(c.time+s.phase)%1.15;if(!s.bot){const q=targets[i].filter(q=>c.time>=q.gone&&q.kind!=='friend').sort((a,b)=>(b.kind==='boss')-(a.kind==='boss'))[0];if(!q)return{};s.bot=position(i,q);}if(phase>.9){s.bot=null;return{};}const v=toward(s.bot,base.x,base.z),pull=phase<.08?0:Math.min(1.5,(phase-.08)*5);return{pointer:{valid:true,worldValid:true,down:true,worldX:base.x+v.x*pull,worldZ:base.z+v.z*pull}};});const g=gesture(c,p,s,input,a,5.2,4.7);if(g.pressed&&dist(g,base)<.8&&c.time>s.ready)s.pulling=true;if(g.released&&s.pulling){const d=dist(g,base);s.pulling=false;if(d>.35){arrows.push({id:id++,owner:i,x:base.x,z:base.z,vx:(base.x-g.x)/d*13,vz:(base.z-g.z)/d*13,born:c.time,done:false});s.ready=c.time+.18;}}});arrows.forEach(q=>{if(q.done)return;q.x+=q.vx*dt;q.z+=q.vz*dt;const s=state[q.owner],p=players[q.owner],target=targets[q.owner].find(t=>c.time>=t.gone&&dist(q,position(q.owner,t))<.6);if(target){q.done=true;if(target.kind==='friend'){p.score-=30;s.streak=0;}else{s.streak++;p.score+=(target.kind==='boss'?100:20)+(s.streak-1)*10;}target.gone=c.time+.65;target.kind=c.pick(['mage','mage','boss','friend']);}else if(c.time-q.born>1){q.done=true;s.streak=0;}});
 },render(){players.forEach((p,i)=>{const s=state[i],a=layouts[i];board(c,i,`${p.score}점 · 연속 ${s.streak}`);targets[i].forEach((q,j)=>{if(c.time<q.gone)return;const b=position(i,q);ball(c,`archery-target-${i}-${j}`,b.x,.3,b.z,1,q.kind==='boss'?GOLD:q.kind==='friend'?PINK:BLUE);text(c,`archery-points-${i}-${j}`,q.kind==='boss'?'100':q.kind==='friend'?'−30':'20',b.x,.85,b.z,1.4);});const base={x:a.x,z:a.z+2.7};box(c,`bow-${i}`,base.x,.2,base.z,2,.2,.15,'#a17f59');if(s.pulling){line(c,`bow-string-a-${i}`,{x:base.x-1,z:base.z},{x:s.cx,z:s.cz},p.color,.05,.2);line(c,`bow-string-b-${i}`,{x:base.x+1,z:base.z},{x:s.cx,z:s.cz},p.color,.05,.2);}cursor(c,p,{x:s.cx,z:s.cz});});arrows.forEach(q=>{if(!q.done)box(c,`match-arrow-${q.id}`,q.x,.3,q.z,.12,.12,.7,GOLD,{ry:Math.atan2(q.vx,q.vz)});});},timeout(){high(c,'30초 표적 점수');}};
}

function callGoomba(c){
 const players=setup(c,34),target=c.pick([Math.PI*2,Math.PI*3,Math.PI*4]),state=players.map(()=>({lastAngle:null,speed:0,quality:0,phase:0,error:c.rand(.92,1.08)}));players.forEach((p,i)=>{p.x=i%2?7:-7;p.z=i<2?-4.5:4.5;});const crowd=Array.from({length:50},(_,i)=>({id:i,x:c.rand(-3.5,3.5),z:c.rand(-2.5,2.5),owner:null}));let beat=-1;
 return{update(dt){c.hint(c.time<4?'시범 박자를 듣고 손잡이 속도를 기억하세요.':'반시계 방향으로 같은 속도의 원을 그리세요. 1P 손잡이 드래그 / 방향키 원형 회전. 알맞은 속도는 컬러 음표!');if(c.time<4){const n=Math.floor(c.time*target/Math.PI/2);if(n!==beat){beat=n;c.sound?.(440,.09);}}
  players.forEach((p,i)=>{const s=state[i];s.phase-=dt*target*s.error;const input=c.input(p,()=>c.time>4?{x:Math.cos(s.phase),z:Math.sin(s.phase)}:{});const delta=rotateInput(s,input,p);if(c.time>=4&&dt>0){s.speed+=(Math.max(0,-delta)/dt-s.speed)*Math.min(1,dt*6);s.quality=clamp(1-Math.abs(s.speed-target)/target*2,0,1);}});
  if(c.time>=4)crowd.forEach(q=>{if(q.owner!==null)return;const options=players.map((p,i)=>({p,i,value:state[i].quality/(dist(q,p)+2)})).filter(a=>state[a.i].quality>.35).sort((a,b)=>b.value-a.value);if(!options.length)return;const a=options[0],v=toward(q,a.p.x,a.p.z);q.x+=v.x*dt*state[a.i].quality*2.1;q.z+=v.z*dt*state[a.i].quality*2.1;if(dist(q,a.p)<1.2){q.owner=a.i;c.points(a.p);}});if(crowd.every(q=>q.owner!==null))high(c,'청중 50명의 선택');
 },render(){c.arena({width:20,depth:15,color:'#abc59a'});players.forEach((p,i)=>{const s=state[i],angle=c.time<4?-c.time*target:s.lastAngle||0;c.draw(`organ-ring-${i}`,'ring',{x:p.x,y:.08,z:p.z,sx:2.7,sy:2.7,sz:1,rx:-Math.PI/2,color:p.color});line(c,`organ-crank-${i}`,p,{x:p.x+Math.cos(angle)*1.2,z:p.z+Math.sin(angle)*1.2},GOLD,.13,.2);text(c,`organ-note-${i}`,'♪',p.x,3,p.z,3,s.quality>.7?p.color:'#f0f0df');});crowd.forEach(q=>{if(q.owner===null)ball(c,`audience-${q.id}`,q.x,.3,q.z,.55,'#ad8b6d');});if(c.time<4)text(c,'tempo-intro','박자를 기억하세요',0,2,0,9);},timeout(){high(c,'30초 동안 모은 청중');}};
}

function rollers(c){
 const players=setup(c,300),state=players.map(()=>({cx:0,cz:0,hurt:0,lastPointer:null})),obstacles=Array.from({length:20},(_,i)=>({id:i,type:i%3,x:(i%3-1)*4,z:-8-i*3.4}));players.forEach(p=>{p.z=2;p.y=1;});
 const position=q=>({x:q.x+(q.type===2?Math.sin(c.time*1.5+q.id)*2.5:0),z:q.z});
 return{update(dt){c.hint('볼을 밀어 모래성까지 경주하세요. 1P 드래그, 키보드는 A를 누른 채 방향키. 양동이·블록집·장난감 트럭과 충돌하면 튕깁니다.');players.forEach((p,i)=>{const s=state[i],near=obstacles.map(q=>({...position(q),type:q.type})).filter(q=>q.z<p.z&&p.z-q.z<5).sort((a,b)=>b.z-a.z)[0];const input=c.input(p,()=>({x:near&&Math.abs(near.x-p.x)<1.8?p.x<near.x?-1:1:Math.abs(p.x)>5.7?-Math.sign(p.x):0,z:-1,a:true}));let dx=0,dz=0;if(input.pointer.down&&input.pointer.worldValid){if(s.lastPointer){dx=input.pointer.worldX-s.lastPointer.x;dz=input.pointer.worldZ-s.lastPointer.z;}s.lastPointer={x:input.pointer.worldX,z:input.pointer.worldZ};}else{s.lastPointer=null;if(input.a){dx=input.x*dt*3.2;dz=input.z*dt*3.2;}}const n=Math.hypot(dx,dz);if(n>1){dx/=n;dz/=n;}p.vx=(p.vx+dx*6)*Math.pow(.94,dt*60);p.vz=(p.vz+dz*6)*Math.pow(.94,dt*60);const speed=Math.hypot(p.vx,p.vz);if(speed>8.5){p.vx*=8.5/speed;p.vz*=8.5/speed;}p.x+=p.vx*dt;p.z+=p.vz*dt;if(Math.abs(p.x)>7.3){p.x=clamp(p.x,-7.3,7.3);p.vx*=-.6;}if(c.time>s.hurt){const q=obstacles.map(position).find(q=>dist(p,q)<1.5);if(q){const v=toward(q,p.x,p.z);p.x=q.x+v.x*1.55;p.z=q.z+v.z*1.55;p.vx=v.x*4;p.vz=v.z*4;s.hurt=c.time+.3;}}p.score=Math.max(0,-p.z);});const arrived=players.filter(p=>p.z<-85);if(arrived.length)c.complete(arrived.map(p=>p.i),'공을 굴려 모래성 도착');const z=Math.min(...players.map(p=>p.z));c.view={size:25,eye:[0,24,z+18],target:[0,0,z-7]};
 },render(){box(c,'sandbox',0,-.2,-40,18,.4,100,'#d8c299');obstacles.forEach(q=>{const a=position(q);if(q.type===0)c.draw(`bucket-${q.id}`,'cylinder',{x:a.x,y:.7,z:a.z,sx:2,sy:1.5,sz:2,color:BLUE});else if(q.type===1){box(c,`house-${q.id}`,a.x,.6,a.z,2,1.2,2,GREEN);c.draw(`roof-${q.id}`,'cone',{x:a.x,y:1.7,z:a.z,sx:2.5,sy:1.2,sz:2.5,color:PINK});}else box(c,`truck-${q.id}`,a.x,.5,a.z,2.8,1,1.5,GOLD);});players.forEach(p=>ball(c,`rubber-ball-${p.i}`,p.x,.6,p.z,1.3,p.color));for(let i=-2;i<=2;i++)box(c,`castle-${i}`,i*2.8,1.5,-87,2.5,3,3,'#bea67c');},timeout(){c.complete([],'5분 안에 모래성에 도착하지 못했습니다');}};
}

function blowout(c){
 const players=setup(c,300),total=18,state=players.map(()=>({blowing:false,breath:0,jumpUntil:0,from:0,to:0,botStart:.2,hold:c.rand(.65,.85)}));players.forEach((p,i)=>{p.x=(i-1.5)*4;p.z=3;p.y=1.8;});
 return{update(){c.hint('마이크 대신 A를 길게 누른 뒤 놓아 바람을 붑니다. 한 번에 최대 세 촛불! 자동으로 건너뛰는 동안에는 불 수 없습니다.');players.forEach((p,i)=>{const s=state[i],jumping=c.time<s.jumpUntil,input=c.input(p,()=>{if(jumping)return{};if(c.time<s.botStart)return{};if(!s.blowing)return{a:true};return{a:s.breath<s.hold};});if(jumping){const f=1-(s.jumpUntil-c.time)/(.25*(s.to-s.from)+.25);p.z=3-(s.from+(s.to-s.from)*clamp(f,0,1))*1.25;p.y=1.8+Math.sin(clamp(f,0,1)*Math.PI)*1.5;return;}p.y=1.8;p.z=3-p.score*1.25;if(input.ap){s.blowing=true;s.breath=0;}if(s.blowing&&input.a)s.breath+=c.dt;if(s.blowing&&!input.a){const n=Math.min(3,Math.max(1,Math.floor(s.breath/.25)));s.blowing=false;s.from=p.score;p.score=Math.min(total,p.score+n);s.to=p.score;s.jumpUntil=c.time+.25*n+.25;s.botStart=s.jumpUntil+.1;}});const arrived=players.filter(p=>p.score===total&&c.time>=state[p.i].jumpUntil);if(arrived.length)c.complete(arrived.map(p=>p.i),'모든 촛불을 끄고 결승점 도착');const z=Math.min(...players.map(p=>p.z));c.view={size:26,eye:[0,20,z+19],target:[0,1,z-7]};
 },render(){players.forEach((p,i)=>{for(let n=0;n<=total;n++){const z=3-n*1.25;c.draw(`candle-${i}-${n}`,'cylinder',{x:p.x,y:.8,z,sx:1,sy:1.6,sz:1,color:'#e5dec2'});if(n>p.score)c.draw(`flame-${i}-${n}`,'cone',{x:p.x,y:2.3,z,sx:.5,sy:.9,sz:.5,color:GOLD,glow:true});}if(state[i].blowing)text(c,`breath-${i}`,`후~ ${Math.min(3,Math.max(1,Math.floor(state[i].breath/.25)))}`,p.x,p.y+2,p.z,3,BLUE);});},timeout(){c.complete([],'5분 안에 촛불 길을 끝내지 못했습니다');}};
}

function sweets(c){
 const players=setup(c,31.2);boards(c);let id=0;const state=players.map((p,i)=>({cx:layouts[i].x,cz:layouts[i].z,items:[],target:null,held:null,bot:null,expanded:0}));
 const add=(s,n)=>{for(let j=0;j<n;j++){const k=s.items.length;s.items.push({id:id++,kind:c.int(0,3),stripe:c.int(0,2),x:-3+(k%4)*1.25,z:-1.5+Math.floor(k/4)*1.4});}if(s.target===null&&s.items.length)s.target={kind:s.items[0].kind,stripe:s.items[0].stripe};};state.forEach(s=>add(s,8));
 const match=(q,s)=>q.kind===s.target.kind&&q.stripe===s.target.stripe;
 return{update(){c.hint('요청한 모양과 무늬의 사탕을 잡아 오른쪽 요청자에게 끌어 놓으세요. 1P 드래그 / 방향 커서+A를 눌러 잡고 놓아 배달.');players.forEach((p,i)=>{const s=state[i],a=layouts[i],receiver={x:a.x+3.6,z:a.z};if(c.time>10&&s.expanded===0){add(s,4);s.expanded++;}if(c.time>20&&s.expanded===1){add(s,4);s.expanded++;}const input=c.input(p,()=>{if(!s.bot){if(c.time>=30)return{};const q=s.items.find(q=>match(q,s));if(!q)return{};s.bot={q,at:c.time};}const f=(c.time-s.bot.at)/.6;if(f>1){s.bot=null;return{};}const start={x:a.x+s.bot.q.x,z:a.z+s.bot.q.z};return{pointer:{valid:true,worldValid:true,down:true,worldX:start.x+(receiver.x-start.x)*clamp(f,0,1),worldZ:start.z+(receiver.z-start.z)*clamp(f,0,1)}};});const g=gesture(c,p,s,input,a,5,3);if(g.pressed&&c.time<30)s.held=s.items.find(q=>dist(g,{x:a.x+q.x,z:a.z+q.z})<.55)??null;if(g.released&&s.held){if(dist(g,receiver)<1&&match(s.held,s)){s.items=s.items.filter(q=>q!==s.held);c.points(p);if(!s.items.length)add(s,8);const q=c.pick(s.items);s.target={kind:q.kind,stripe:q.stripe};}s.held=null;}});if(c.time>=30&&state.every(s=>!s.held))high(c,'30초 정확한 사탕 배달');
 },render(){const candy=(id,q,x,z,y=.3)=>{if(q.kind===0)ball(c,id,x,y,z,.8,PINK);else if(q.kind===1)box(c,id,x,y,z,.9,.35,.6,BLUE);else if(q.kind===2)c.draw(id,'cone',{x,y,z,sx:.8,sy:.5,sz:.8,color:GOLD});else box(c,id,x,y,z,.7,.4,.7,GREEN,{ry:Math.PI/4});text(c,id+'-stripe',['|||','===','///'][q.stripe],x,y+.45,z,.8,'#4f6170');};players.forEach((p,i)=>{const s=state[i],a=layouts[i];board(c,i,`${p.score}개 · 같은 모양과 무늬`);s.items.forEach(q=>{if(q!==s.held)candy(`candy-${q.id}`,q,a.x+q.x,a.z+q.z);});if(s.held)candy(`held-candy-${i}`,s.held,s.cx,s.cz,.5);ball(c,`customer-${i}`,a.x+3.6,.7,a.z,1.5,p.color);candy(`request-${i}`,s.target,a.x+3.6,a.z-2.3,.6);cursor(c,p,{x:s.cx,z:s.cz});});},timeout(){high(c,'사탕 배달 종료');}};
}

function foodFrenzy(c){
 const players=setup(c,30),foods=[],names=['버거','셰이크','핫도그','팬케이크','아이스크림','감자튀김'];let id=0;const control={cx:0,cz:-4,type:0,dragging:false,ready:0},status=players.map(()=>({stun:0,sticky:0,frozen:0,supported:false}));players[0].x=9;players[0].z=6;players.slice(1).forEach((p,i)=>{p.x=(i-1)*3;p.z=1;});c.view={size:28,eye:[0,27,21],target:[1,0,0]};
 return{update(dt){c.hint('1P: 오른쪽 음식을 끌어 벨트에 놓기 / B 음식 변경·A를 잡고 방향키, 놓아 투하. 팀: 이동·A 점프, 벨트 끝으로 밀리지 않기!');const target=players.slice(1).filter(p=>p.alive).sort((a,b)=>b.z-a.z)[0];const input=c.input(players[0],()=>{const phase=c.time%1.5;return{...toward({x:control.cx,z:control.cz},target?.x??0,(target?.z??0)-2),a:phase<.8,b:phase<.03};});const g=gesture(c,players[0],control,input,{x:0,z:0},6,5);if(input.bp)control.type=(control.type+1)%6;if(g.pressed){if(input.pointer.worldValid){const k=Math.round((g.z+5)/2);if(Math.abs(g.x-9)<1.1&&k>=0&&k<6){control.type=k;control.dragging=true;}}else control.dragging=true;}if(g.released&&control.dragging){if(c.time>=control.ready&&Math.abs(g.x)<6.8&&g.z<4.5&&g.z>-6){foods.push({id:id++,type:control.type,x:clamp(g.x,-6,6),z:clamp(g.z,-5,3),born:c.time,affected:new Set()});control.ready=c.time+.5;}control.dragging=false;}
  const belt=2+c.time*.07;foods.forEach(q=>q.z+=belt*dt);players.slice(1).forEach(p=>{const s=status[p.i],near=foods.filter(q=>c.time-q.born>.2&&q.z<p.z+1&&p.z-q.z<4&&Math.abs(q.x-p.x)<2).sort((a,b)=>b.z-a.z)[0],inp=c.input(p,()=>({x:near?p.x<near.x?-1:1:Math.abs(p.x)>4.7?-Math.sign(p.x):0,z:p.z>-.5?-1:0,a:!!near&&near.type===5&&Math.abs(near.z-p.z)<2.4}));if(!p.alive)return;const ox=p.x,oz=p.z,old=p.y;if(c.time>s.frozen&&c.time>s.stun)c.move(p,inp,c.time<s.sticky?2.3:5.6,false);if(inp.ap&&c.time<s.sticky)s.sticky-=.6;if(s.supported&&inp.ap){p.vy=7.6;p.y+=.01;}c.jump(p,c.time>s.frozen&&c.time>s.stun?inp:{},7.6);s.supported=false;p.z+=dt*belt;p.x=clamp(p.x,-6.5,6.5);p.z=Math.max(-5,p.z);
   foods.forEach(q=>{if(c.time-q.born<.45||Math.abs(p.x-q.x)>1.05||Math.abs(p.z-q.z)>1.05)return;if(q.type<2&&p.y<2.6){const v=toward(q,p.x,p.z);p.x=q.x+v.x*1.12;p.z=q.z+v.z*1.12;}else if(q.type===5){if(old>.65&&p.y<=.65&&p.vy<0){p.y=.65;p.vy=0;s.supported=true;}else if(p.y<.5){const v=toward(q,p.x,p.z);p.x+=v.x*.4;p.z+=v.z*.5;}}else if(p.y<.8&&!q.affected.has(p.i)){q.affected.add(p.i);if(q.type===2)s.stun=c.time+.9;if(q.type===3)s.sticky=c.time+3;if(q.type===4)s.frozen=c.time+1.5;}});if(p.z>6)c.eliminate(p);});if(players.slice(1).every(p=>!p.alive))c.complete([0],'음식 장애물로 팀 전원을 벨트에서 밀어냈습니다');
 },render(){box(c,'food-belt',0,-.2,0,14,.4,13,'#798f91');for(let i=0;i<13;i++)box(c,`belt-line-${i}`,0,.02,-6+i+(c.time*3)%1,14,.05,.08,'#b2c3b5');const drawFood=(q,id,y=.4)=>{const col=[GOLD,BLUE,'#bd826a','#d5b27c',PINK,GOLD][q.type];if(q.type===0){ball(c,id+'-bun',q.x,y+.6,q.z,2,col,{sy:.6});box(c,id+'-filling',q.x,y,q.z,1.8,.6,1.7,'#926c55');}else if(q.type===1)c.draw(id,'cone',{x:q.x,y:y+.8,z:q.z,sx:1.5,sy:2.4,sz:1.5,color:col});else if(q.type===4){c.draw(id+'-cone','cone',{x:q.x,y:y+.3,z:q.z,sx:1.3,sy:1.2,sz:1.3,color:GOLD});ball(c,id+'-ice',q.x,y+1,q.z,1.5,col);}else box(c,id,q.x,y,q.z,q.type===2?2.3:1.8,q.type===5?1:.5,1.4,col);};foods.forEach(q=>{if(q.z<9)drawFood(q,`food-${q.id}`,.4+Math.max(0,1-(c.time-q.born)/.45)*3);});names.forEach((name,i)=>{drawFood({x:9,z:-5+i*2,type:i},`tray-food-${i}`,0);text(c,`tray-label-${i}`,name,11.2,1,-5+i*2,2.5,control.type===i?PINK:'#314a54');});if(control.dragging)drawFood({x:control.cx,z:control.cz,type:control.type},'held-food',3);players.slice(1).forEach(p=>{if(c.time<status[p.i].frozen)box(c,`food-ice-${p.i}`,p.x,p.y+.8,p.z,1.4,2,1.4,BLUE,{opacity:.6});});},timeout(){c.complete([1,2,3],'팀이 30초 동안 벨트에서 생존');}};
}

function plush(c){
 const players=setup(c,30),toys=[],control=players.map((p,i)=>({cx:(i-2)*3,cz:-2,dragging:false,ready:0,pace:c.rand(1.6,2.3),radius:c.rand(.9,1.5)}));players[0].x=0;players[0].z=2;players.slice(1).forEach((p,i)=>{p.x=(i-1)*6;p.z=-8;});let id=0;const old={x:0,z:2};
 return{update(dt){c.hint('1P는 방향키로 그림자를 피하세요. 2–4P는 A를 잡고 방향키로 인형 이동, 놓아 투하. 인형에 직접 깔리면 팀 승리!');const live=toys.filter(q=>!q.landed),solid=toys.filter(q=>q.landed);const input=c.input(players[0],()=>{const p=players[0],options=[{x:p.x,z:p.z},...Array.from({length:12},(_,i)=>({x:clamp(p.x+Math.cos(i*Math.PI/6)*2.5,-7,7),z:clamp(p.z+Math.sin(i*Math.PI/6)*2.5,-4.5,4.5)}))].filter(q=>!solid.some(t=>dist(q,t)<t.r+.5));options.sort((a,b)=>{const score=q=>Math.min(8,...live.map(t=>dist(q,t)-t.r))-dist(q,p)*.12;return score(b)-score(a);});return options[0]?toward(p,options[0].x,options[0].z):{};});const runner=players[0],ox=runner.x,oz=runner.z;c.move(runner,input,5.4);if(solid.some(q=>dist(runner,q)<q.r+.4)){runner.x=ox;runner.z=oz;}const velocity={x:dt>0?(runner.x-old.x)/dt:0,z:dt>0?(runner.z-old.z)/dt:0};old.x=runner.x;old.z=runner.z;
  players.slice(1).forEach((p,j)=>{const i=p.i,s=control[i],phase=c.time%s.pace,inp=c.input(p,()=>{const tx=runner.x+velocity.x*.5+Math.sin(i*2+c.time)*1.2,tz=runner.z+velocity.z*.5+Math.cos(i*2+c.time);return{...toward({x:s.cx,z:s.cz},tx,tz),a:phase<s.pace*.6};});const g=gesture(c,p,s,inp,{x:0,z:0},7.3,4.7);if(g.pressed&&c.time>s.ready)s.dragging=true;if(g.released&&s.dragging){toys.push({id:id++,x:clamp(g.x,-7.5,7.5),z:clamp(g.z,-4.8,4.8),at:c.time,r:s.radius,color:p.color,kind:id%3,landed:false});s.dragging=false;s.ready=c.time+.5;s.radius=c.rand(.9,1.5);}});
  toys.forEach(q=>{if(!q.landed&&c.time-q.at>=.7){q.landed=true;if(dist(runner,q)<q.r+.45)c.complete([1,2,3],'인형이 도망자를 눌렀습니다');}});
 },render(){c.arena({width:18,depth:13,color:'#d6c49f'});toys.forEach(q=>{const f=clamp((c.time-q.at)/.7,0,1),y=q.landed?q.r*.5:7*(1-f*f)+q.r*.5;c.draw(`plush-shadow-${q.id}`,'cylinder',{x:q.x,y:.03,z:q.z,sx:q.r*2,sy:.04,sz:q.r*2,color:'#646b77',opacity:.4});if(q.kind===0)box(c,`plush-${q.id}`,q.x,y,q.z,q.r*2,q.r,q.r*2,q.color);else ball(c,`plush-${q.id}`,q.x,y,q.z,q.r*2,q.color,{sy:q.kind===1?q.r:2*q.r});text(c,`plush-face-${q.id}`,'● ●',q.x,y+q.r*.6,q.z,q.r,'#4e6370');});players.slice(1).forEach(p=>{const s=control[p.i];cursor(c,p,{x:s.cx,z:s.cz});if(s.dragging)ball(c,`held-plush-${p.i}`,s.cx,7,s.cz,s.radius*2,p.color);});},timeout(){c.complete([0],'떨어지는 인형을 30초 회피');}};
}

function soil(c){
 const players=setup(c),cars=[{x:-3,z:3,heading:0},{x:3,z:3,heading:0}],state=players.map(()=>({lastAngle:null,speed:0,phase:0})),patches=Array.from({length:15},(_,i)=>({x:(i%3-1)*4,z:-6-i*4.2}));players.forEach((p,i)=>{p.x=cars[Math.floor(i/2)].x+(i%2?1:-1);p.z=3;});
 return{update(dt){c.hint('팀 1·2P / 3·4P. 각자 맡은 앞바퀴를 시계 방향으로 돌리세요. 느린 바퀴 쪽으로 회전합니다. 1P 드래그 / 방향키 원형 회전.');players.forEach((p,i)=>{const car=cars[Math.floor(i/2)],s=state[i],patch=patches.find(q=>q.z<car.z&&car.z-q.z<10),desiredX=patch&&Math.abs(patch.x-car.x)<2?(car.x<patch.x?-5:5):Math.floor(i/2)?3:-3,desired=Math.atan2(desiredX-car.x,9),error=angleDiff(desired,car.heading),rate=clamp(8+(i%2?-1:1)*error*4,2,13);s.phase+=rate*dt;const input=c.input(p,()=>({x:Math.cos(s.phase),z:Math.sin(s.phase)}));const d=rotateInput(s,input,p);if(dt>0)s.speed+=(Math.max(0,d)/dt-s.speed)*Math.min(1,dt*5);});cars.forEach((car,t)=>{const left=state[t*2].speed,right=state[t*2+1].speed;car.heading=clamp(car.heading+(left-right)*dt*.3,-1.1,1.1);const dark=patches.some(q=>Math.abs(q.x-car.x)<2&&Math.abs(q.z-car.z)<1.8),speed=(left+right)*.35*(dark?.4:1);car.x=clamp(car.x+Math.sin(car.heading)*speed*dt,-7,7);car.z-=Math.cos(car.heading)*speed*dt;players.slice(t*2,t*2+2).forEach((p,j)=>{p.x=car.x+(j?1:-1);p.z=car.z;p.score=Math.max(0,-car.z);});});const done=cars.map((q,i)=>q.z<-75?i:null).filter(i=>i!==null);if(done.length)c.complete(done.length===2?[]:done.flatMap(t=>[t*2,t*2+1]),'텃밭 경주 결승점 도착');const z=Math.min(...cars.map(q=>q.z));c.view={size:25,eye:[0,22,z+18],target:[0,0,z-6]};
 },render(){box(c,'garden-road',0,-.2,-37,18,.4,87,'#b1a079');patches.forEach((q,i)=>box(c,`dark-soil-${i}`,q.x,.03,q.z,4,.07,3.6,'#786951'));cars.forEach((q,t)=>{box(c,`garden-car-${t}`,q.x,.3,q.z,3.4,.6,2.2,players[t*2].color,{ry:-q.heading});players.slice(t*2,t*2+2).forEach(p=>{c.draw(`wheel-guide-${p.i}`,'ring',{x:p.x,y:.08,z:p.z,sx:1.7,sy:1.7,sz:1,rx:-Math.PI/2,color:p.color});const a=state[p.i].lastAngle||0;line(c,`wheel-spoke-${p.i}`,p,{x:p.x+Math.cos(a)*.8,z:p.z+Math.sin(a)*.8},GOLD,.12,.12);});});box(c,'garden-goal',0,.05,-75,18,.1,.5,PINK);}};
}

function crosshairs(c){
 const players=setup(c,30),teams=[{x:-3,z:0,lock:null,next:0,target:null,flash:0,score:0},{x:3,z:0,lock:null,next:0,target:null,flash:0,score:0}],targets=Array.from({length:15},(_,i)=>({id:i,x:(i%5-2)*3,z:(Math.floor(i/5)-1)*3,gold:i%5===2,gone:0}));players.forEach((p,i)=>{p.x=(Math.floor(i/2)?5:-5)+(i%2?1:-1);p.z=7;});c.view={size:26,eye:[0,26,21],target:[0,0,0]};
 const position=q=>({x:q.x+Math.sin(c.time*1.4+q.id)*.6,z:q.z+Math.cos(c.time*1.1+q.id)*.4});
 return{update(dt){c.hint('팀 1·2P / 3·4P. 앞 번호 ←→ 가로 조준, 뒤 번호 ↑↓ 세로 조준. 먼저 A를 누르면 그 축 고정, 파트너의 A가 발사!');teams.forEach((s,t)=>{if(!s.target||c.time<s.target.gone)s.target=targets.filter(q=>c.time>=q.gone).sort((a,b)=>dist(s,position(a))-dist(s,position(b)))[0]??null;const q=s.target?position(s.target):null,inputs=players.slice(t*2,t*2+2).map((p,j)=>c.input(p,()=>q?{x:j===0?clamp((q.x-s.x)*3,-1,1):0,z:j===1?clamp((q.z-s.z)*3,-1,1):0,a:c.time>s.next&&s.lock!==j&&Math.abs(j===0?q.x-s.x:q.z-s.z)<.13}:{}));if(s.lock!==0){if(inputs[0].pointer.down&&inputs[0].pointer.worldValid)s.x=clamp(inputs[0].pointer.worldX,-7.5,7.5);else s.x=clamp(s.x+inputs[0].x*dt*6,-7.5,7.5);}if(s.lock!==1)s.z=clamp(s.z+inputs[1].z*dt*6,-4.5,4.5);
  inputs.forEach((input,j)=>{if((input.ap||input.pointer.pressed)&&c.time>s.next){if(s.lock===null)s.lock=j;else if(s.lock!==j){const hit=targets.find(q=>c.time>=q.gone&&dist(s,position(q))<.65);if(hit){s.score+=hit.gold?3:1;hit.gone=c.time+.8;}s.lock=null;s.next=c.time+.25;s.flash=c.time+.12;s.target=null;c.sound?.(hit?550:180,.05);}}});players.slice(t*2,t*2+2).forEach(p=>p.score=s.score);});
 },render(){c.arena({width:18,depth:12,color:'#a7bf9b'});for(let i=-4;i<=4;i++)line(c,`web-${i}`,{x:-8,z:i},{x:8,z:-i},'#dae7cd',.04);targets.forEach(q=>{if(c.time>=q.gone){const a=position(q);ball(c,`web-bug-${q.id}`,a.x,.4,a.z,.8,q.gold?GOLD:'#8f7695');}});teams.forEach((s,t)=>{const color=players[t*2].color;box(c,`cross-h-${t}`,s.x,.15,s.z,1.4,.06,.07,color);box(c,`cross-v-${t}`,s.x,.15,s.z,.07,.06,1.4,color);text(c,`axis-lock-${t}`,s.lock===null?'조준':s.lock===0?'가로 고정':'세로 고정',s.x,1.4,s.z,3,color);if(c.time<s.flash)line(c,`cross-shot-${t}`,{x:t?5:-5,z:6},s,color,.16,.3);});},timeout(){c.complete(teams[0].score===teams[1].score?[]:teams[0].score>teams[1].score?[0,1]:[2,3],'30초 팀 표적 점수');}};
}

export const games={'Goomba Wrangler':wrangler,'Rail Riders':rails,'Hedge Honcho':hedge,'Cherry-Go-Round':cherry,'Trace Cadets':traceCadets,'Hot Shots':hotShots,'Call of the Goomba':callGoomba,'Roller Coasters':rollers,'Big Blowout':blowout,'Sweet Sleuth':sweets,'Fast Food Frenzy':foodFrenzy,'Plush Crush':plush,'Soil Toil':soil,'Crazy Crosshairs':crosshairs};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['ds']]));
export const notes={
 'Goomba Wrangler':'4인 버전 · 1P 마우스/터치로 닫힌 원 그리기. 키보드는 A를 누른 채 방향키로 같은 커서 궤적을 그립니다. 실제 다각형 안의 대상만 포획: 보통 1점, 마지막 5초 금색 3점, 폭탄은 보유 점수 절반. 20초. 대상 수·속도·닫힘 허용오차는 재현판 수치입니다.',
 'Rail Riders':'4인 버전 · 1P 화면을 아래에서 위로 반복 드래그. 키보드는 A+↑로 위로 긋고 A를 놓아 가상 펜을 아래로 복귀. 위로 그은 거리만 가속에 반영하며 레일 끝 속도로 비행 거리를 결정합니다. 레일 길이·가속·거리 표시 단위는 재현판 수치입니다.',
 'Hedge Honcho':'4인 버전 · 1P 잎 드래그, 키보드 방향 커서+A를 눌러 잡고 이동. 앞 잎만 밀기, 무당벌레는 실제 이동 궤적으로 문지르기, 벌은 기다리기. 덤불 5개 선착순·5분 무승부. 덤불당 잎 4개·문지르기 거리·기절 시간은 재현판 수치입니다.',
 'Cherry-Go-Round':'4인 버전 · 1P 원 안에서 드래그, 키보드 방향키를 원형으로 회전. 시계/반시계 모두 유효. 5초 동안 누적 회전으로 체리를 던지고 원작 최고 200 제한을 적용합니다. 회전량→거리 변환 3.5 계수는 재현판 수치이며 비행 표시 2.5초를 덧붙였습니다.',
 'Trace Cadets':'4인 버전 · 1P 펜을 떼지 않고 자기 색 도형 윤곽을 한 바퀴 따라 그리기. 키보드는 방향 커서+A 유지. 실제 선분과 외곽선의 거리·전체 둘레 방문·닫힘을 검사합니다. 채운 조각과 닿은 이웃만 활성화, 5분 무승부. 6×4 격자의 조각 6개와 판정 오차는 재현판 규격입니다.',
 'Hot Shots':'4인 버전 · 활 아래를 잡고 목표 반대 방향으로 당겼다 놓아 쏩니다. 1P 드래그 또는 방향 커서+A. 금색 보스 100, 파란 마법사 20, 분홍 친구 −30. 30초 최다 점수. 연속 적중 보너스는 원작 존재만 확인되어 이 재현판에서는 2연속부터 10점씩 증가하며 실수 시 초기화합니다.',
 'Call of the Goomba':'4인 버전 · 시범 뒤 반시계 원형 조작으로 박자 맞추기. 1P 손잡이 드래그 또는 방향키 원형 회전. 맞는 속도는 색 음표, 틀리면 흰 음표. 청중 50명 모두 선택 또는 실제 경기 30초 뒤 최다 승리. 4초 시범과 자체 생성 단음·속도 오차 판정은 재현판 규격이며 원작 음원은 사용하지 않습니다.',
 'Roller Coasters':'4인 버전 · 1P 드래그 이동량으로 공을 밀기. 키보드는 A를 누른 채 방향키로 같은 추진 동작. 양동이·블록집·움직이는 트럭은 반동을 일으킵니다. 모래성 선착순·5분 무승부. 85단위 코스와 물리 계수는 재현판 규격입니다.',
 'Big Blowout':'4인 버전 · 원작 마이크를 A 길게 누르기→놓기로 치환했습니다. 길게 불수록 최대 3개 촛불을 끄며 자동 점프 중에는 바람 입력 불가. 모두 끄고 결승점 선착순·5분 무승부. 촛불 18개·0.25초당 1개는 재현판 조정값입니다.',
 'Sweet Sleuth':'4인 버전 · 요청한 모양·무늬 사탕을 실제로 끌어 오른쪽 요청자에게 놓으세요. 1P 드래그 또는 방향 커서+A 유지 후 놓기. 30초 최다 정답, 사탕은 시간이 지나며 추가됩니다. 종료 직전에 잡은 사탕은 최대 1.2초 더 배달 가능하며 이 유예 길이·재고 수는 재현판 조정값입니다.',
 'Fast Food Frenzy':'1 대 3 · 1P 음식 트레이에서 실제 드래그·드롭, 키보드는 B 종류 변경·A 잡기·방향 이동·A 놓기. 2–4P 이동·A 점프. 버거/셰이크 통과 불가, 핫도그 기절, 팬케이크 끈적임, 아이스크림 얼음, 감자튀김 반동/안전 점프. 30초 생존은 팀 승리. 낙하·벨트·상태 지속 시간은 재현판 수치입니다.',
 'Plush Crush':'1 대 3 · 1P 방향 이동. 2–4P A 유지로 인형을 잡고 방향키로 조준, 놓아 떨어뜨리기(포인터가 해당 선수에 연결되면 실제 드래그도 가능). 그림자 예고 후 직접 깔리면 팀 승리, 30초 생존은 1P. 인형 모양·크기·낙하 0.7초는 재현판 규격입니다.',
 'Soil Toil':'2 대 2, 팀 1·2P / 3·4P · 각자 맡은 바퀴를 시계 방향 원형 조작. 1P 포인터 드래그 또는 방향키 원형 회전. 왼쪽/오른쪽 바퀴 속도 차이가 조향, 검은 흙은 감속. 결승 선착순. 75단위 텃밭 코스·바퀴 계수는 재현판 수치이며 확인되지 않은 제한 시간은 추가하지 않았습니다.',
 'Crazy Crosshairs':'2 대 2, 팀 1·2P / 3·4P · 앞 번호 ←→ 가로, 뒤 번호 ↑↓ 세로 조준. 먼저 A를 누른 선수의 축이 잠기고 파트너 A로 발사. 1P 포인터도 가로 조준 가능. 보통 1점·금색 3점, 30초 팀 점수. 표적 배치·속도·재등장 시간은 재현판 조정값입니다.'
};
