import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,KEYS=['a','b','c','d'],TEAM=[[0,1],[2,3]],SIDE=[[0],[1,2,3]],PAL=['#ef91aa','#72abc9','#e6bd5f','#71b798'];
const text=(c,id,t,x=0,z=-5,y=2,sx=8,color='#264650')=>c.draw(id,'text',{text:String(t),x,y,z,sx,sy:.65,color});
const box=(c,id,x,z,color,sx=1,sz=1,y=.1,sy=.2)=>c.draw(id,'box',{x,y,z,sx,sy,sz,color});
const ball=(c,id,x,z,color,s=.5,y=.4)=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color});
const ring=(c,id,x,z,color,s=1,y=.1)=>c.draw(id,'ring',{x,y,z,sx:s,sy:s,sz:s,rx:Math.PI/2,color});
const near=(p,items)=>items.reduce((a,b)=>!a||dist(p,b)<dist(p,a)?b:a,null);
const tap=(c,p,rate=.3)=>((c.time+(p.phase||0))%rate)<rate*.42;
function init(c,limit=60){c.limit=limit;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=3;p.phase=c.rand(0,1);p.cadence=c.rand(.24,.4);});}
function scores(c,v,teams=TEAM){teams.forEach((ids,t)=>ids.forEach(i=>c.players[i].score=v[t]));}
function finish(c,v,reason,teams=TEAM,tie=[]){v=v.map(n=>Math.round(n*100)/100);scores(c,v,teams);c.complete(v[0]===v[1]?tie:teams[v[0]>v[1]?0:1],reason);}
const won=c=>c.players.filter(p=>p.score>0).map(p=>p.i);
const coinFinish=(c,reason)=>c.complete(won(c),reason);
function segment(c,id,a,b,color='#f9edd0',width=.08,y=.3){c.draw(id,'box',{x:(a.x+b.x)/2,y,z:(a.z+b.z)/2,sx:dist(a,b),sy:width,sz:width,ry:-Math.atan2(b.z-a.z,b.x-a.x),color});}
function fruit(c,id,type,x,z,s=.7,y=.4){if(type===1){for(let i=0;i<3;i++)ball(c,id+'b'+i,x+(i-1)*s*.24,z+Math.abs(i-1)*s*.1,'#ebc957',s*.42,y);}else{ball(c,id,x,z,type===0?'#d87c80':type===2?'#72a66c':'#c79bbb',s,y);box(c,id+'leaf',x,z,'#537f65',s*.12,s*.15,y+s*.52,s*.2);}}
function rank(c,answer){const ordered=c.players.filter(p=>p.answer===answer).sort((a,b)=>a.answerAt-b.answerAt);ordered.forEach((p,i)=>{const r=ordered.findIndex(q=>Math.abs(q.answerAt-p.answerAt)<1e-8);c.points(p,[5,3,2,1][r]);});}
export const games={};

games['Lumber Tumble']=(c)=>{
 init(c,Infinity);c.view={size:24,eye:[0,20,20],target:[0,0,-2]};const tiles=[],logs=[],route=[];let camera=0,next=1.1,serial=0;const lanes=[0,0,1,1,2,2,1,1,0,0,-1,-1,0,0,1,1,0,0,-1,-1,0,0];
 for(let row=0;row<22;row++){const x=lanes[row]*2;if(row&&lanes[row]!==lanes[row-1])route.push({x:lanes[row-1]*2,z:-row*2});route.push({x,z:-row*2});tiles.push({x,z:-row*2,row,broken:false});if(row&&lanes[row]!==lanes[row-1])tiles.push({x:lanes[row-1]*2,z:-row*2,row,broken:false});}c.players.forEach((p,i)=>{p.x=(i-1.5)*.36;p.z=.35;p.route=0;p.speed=c.rand(2.4,3);p.finished=false;});
 return {update(dt){if(c.time>=next){const spike=c.time>17&&serial%3===0;logs.push({id:serial++,x:-7,z:Math.max(-42,-camera-c.rand(1,8)),vx:spike?4.5:3.6,spike});next=c.time+c.rand(1.25,2);}for(const l of logs){l.x+=l.vx*dt;if(l.spike)for(const t of tiles)if(!t.broken&&Math.abs(t.z-l.z)<.5&&Math.abs(t.x-l.x)<.7)t.broken=true;}for(const p of c.players){if(p.finished){c.input(p,{});continue;}let target=route[Math.min(p.route,route.length-1)];if(dist(p,target)<.15&&p.route<route.length-1){p.route++;target=route[p.route];}const threat=logs.find(l=>Math.abs(l.z-p.z)<.8&&Math.abs(l.x-p.x)<2.5);const u=c.input(p,threat?{x:0,z:Math.abs(target.x-p.x)<.3?-1:1}:toward(p,target.x,target.z));c.move(p,u,p.speed,false);if(logs.some(l=>Math.abs(l.z-p.z)<.65&&Math.abs(l.x-p.x)<1)){p.x+=dt*4;p.pose='hit';}const support=tiles.some(t=>!t.broken&&Math.abs(t.x-p.x)<.98&&Math.abs(t.z-p.z)<1.02);if(p.alive&&!support)c.eliminate(p);if(p.alive&&p.z< -41.4){p.finished=true;p.score=1;}p.pose='run';}const living=c.players.filter(p=>p.alive);if(living.length<=1)c.complete(living.map(p=>p.i),'다리 위에 마지막으로 남았습니다.');else if(living.every(p=>p.finished))c.complete(living.map(p=>p.i),'미로 다리의 끝에 도착했습니다.');camera=Math.max(0,-Math.max(...living.map(p=>p.z),-42)-4);c.hint('방향키 이동. 점프할 수 없습니다! 굽은 다리를 따라가며 통나무를 피하세요. 뾰족한 통나무는 다리도 부숩니다.');},render(){tiles.forEach((t,i)=>{const z=t.z+camera;if(!t.broken&&z>-15&&z<10)box(c,'bridge'+i,t.x,t.z,'#bc9a6c',1.95,1.95,-.2,.4);});logs.forEach(l=>{const z=l.z+camera;if(Math.abs(l.x)<9&&z>-15&&z<10){c.draw('log'+l.id,'cylinder',{x:l.x,y:.55,z:l.z,sx:1.1,sy:2,sz:1.1,rx:Math.PI/2,color:'#98754f'});if(l.spike)c.draw('spike'+l.id,'cone',{x:l.x+.6,y:.55,z:l.z,sx:.7,sy:.8,sz:.7,rz:-Math.PI/2,color:'#88999d'});}});c.players.forEach(p=>{p.displayZ=p.z+camera;});c.view.target=[0,0,-camera-2];c.view.eye=[0,20,20-camera];},timeout(){c.survivors();}};
};

games['Big-Top Quiz']=(c)=>{
 init(c,60);let round=0,phase='watch',start=0,until=0,images=[],question='',answer=0,options=[],wave=0;const names=['새우','조개','물고기','별'];
 function next(){round++;phase='watch';start=c.time;until=c.time+6;images=round===1?c.shuffle([0,0,1]):c.shuffle([0,1,2]);wave=c.int(0,2);options=c.shuffle([0,1,2,3]).slice(0,3);if(round===1){const more=c.rand()<.5;question=more?'어느 그림이 더 많았나요?':'어느 그림이 더 적었나요?';answer=more?0:1;options=c.shuffle([0,1,2]);}else if(round===2){question='손 흔들던 새가 타던 공 그림은?';answer=images[wave];if(!options.includes(answer))options[0]=answer;}else{question='한 번도 나오지 않은 그림은?';answer=3;options=c.shuffle([1,2,3]);}c.players.forEach(p=>{p.answer=null;p.answerAt=Infinity;p.choice=0;p.nav=0;p.reaction=c.rand(.4,1.5);p.guess=c.rand()<.86?options.indexOf(answer):c.int(0,2);});}next();
 return {update(){if(phase==='watch'&&c.time>=until){phase='answer';start=c.time;until=c.time+10;}for(const p of c.players){const u=c.input(p,{x:phase==='answer'?Math.sign(p.guess-p.choice):0,a:phase==='answer'&&p.answer===null&&p.choice===p.guess&&c.time-start>p.reaction});if(phase==='answer'&&p.answer===null){if(Math.abs(u.x)>.4&&c.time>p.nav){p.choice=clamp(p.choice+Math.sign(u.x),0,2);p.nav=c.time+.16;}if(u.ap){p.answer=options[p.choice];p.answerAt=c.time;}}}if(phase==='answer'&&(c.players.every(p=>p.answer!==null)||c.time>=until)){rank(c,answer);phase='result';until=c.time+1;}if(phase==='result'&&c.time>=until){if(round===3)c.highest('세 문제의 순서별 점수 합계');else next();}c.hint(`${round}/3 · 공의 그림과 손 흔드는 새를 관찰! 문제 뒤 ←/→ 선택, A 확정. 정답 순서 5·3·2·1점.`);},render(){c.arena({color:'#c3b4c4'});if(phase==='watch')images.forEach((v,i)=>{const t=c.time-start,a=t*(round===1?1.1:round===2?1.5:1.8)+i*TAU/3,x=round===1?(i-1)*4*Math.cos(t*.8):Math.cos(a)*(round===2?4:3+Math.sin(t+i)),z=round===1?Math.sin(a):Math.sin(a)*2;ball(c,'circus'+i,x,z,PAL[i],2,1);const visible=Math.cos(t*2.1+i)>0;if(visible)text(c,'image'+i,names[v],x,z+.6,1.1,1.8);ball(c,'rider'+i,x,z,'#efd2a0',.7,2.5);if(i===wave&&round>1)text(c,'wave'+i,'손 흔들기',x,z,3.4,2.5);});else{options.forEach((v,i)=>{box(c,'answer'+i,(i-1)*4,0,'#e6d7b1',3,2,.1,.2);text(c,'option'+i,names[v],(i-1)*4,0,.4,2.6);});text(c,'question',question,0,-3,2.5,12);c.players.forEach(p=>text(c,'pick'+p.i,p.answer===null?`${p.i+1}P`:'✓',(p.choice-1)*4,1+p.i*.4,.25,1.5,p.color));}},timeout(){c.highest();}};
};

games['Camera-Ready']=(c)=>{
 init(c,101);let round=0,start=0,until=0,phase='play',goal={},actors=[];const cameras=c.players.map(()=>({x:0,z:0,zoom:1,shot:false}));
 function next(){round++;start=c.time;until=c.time+30;phase='play';goal={x:c.rand(-2,2),z:c.rand(-1.4,1.4),zoom:c.rand(.9,1.5),time:c.rand(1,5)};actors=Array.from({length:5},(_,i)=>({x:(i-2)*1.5,z:Math.sin(i*2)*1.4,moving:i<2,phase:i*1.4}));cameras.forEach((a,i)=>{Object.assign(a,{x:0,z:0,zoom:1,shot:false});c.players[i].error=c.rand(-.14,.14);});}next();
 function pose(a,t){return {x:a.x+(a.moving?Math.sin(t*1.3+a.phase):0),z:a.z+(a.moving?Math.cos(t*1.1+a.phase)*.5:0)};}
 function shoot(p){const a=cameras[p.i];a.shot=true;a.shotTime=c.time-start;const target=actors.map(q=>pose(q,goal.time)),actual=actors.map(q=>pose(q,c.time-start));let err=Math.hypot(a.x-goal.x,a.z-goal.z)*.5+Math.abs(a.zoom-goal.zoom)*2;err+=actual.reduce((s,q,i)=>s+dist(q,target[i]),0)/actors.length;const value=Math.max(0,Math.round(100-err*35));c.points(p,value);a.result=value;}
 return {update(dt){for(const p of c.players){const a=cameras[p.i],targetTime=goal.time+TAU/1.3;const u=c.input(p,{x:clamp((goal.x+p.error-a.x)*3,-1,1),z:clamp((goal.z+p.error-a.z)*3,-1,1),b:a.zoom<goal.zoom-.02,c:a.zoom>goal.zoom+.02,a:!a.shot&&c.time-start>goal.time&&Math.abs(Math.sin((c.time-start-goal.time)*1.3))<.12});if(!a.shot&&phase==='play'){a.x=clamp(a.x+u.x*dt*3,-4,4);a.z=clamp(a.z+u.z*dt*3,-3,3);a.zoom=clamp(a.zoom+((u.b?1:0)-(u.c?1:0))*dt,.65,1.9);if(u.ap)shoot(p);}}if(phase==='play'&&(cameras.every(a=>a.shot)||c.time>=until)){phase='result';until=c.time+1;}else if(phase==='result'&&c.time>=until){if(round===3){if(c.players.every(p=>p.score===0))c.complete([],'사진 점수가 없습니다.');else c.highest('세 장의 사진이 샘플과 닮은 정도');}else next();}c.hint(`${round}/3 · 방향키로 사진틀 이동 · B 확대 / C 축소 · A 촬영. 샘플의 위치·크기·움직이는 피사체 순간을 맞추세요!`);},render(){c.arena({width:23,depth:16,color:'#c5c7ae'});const panels=[{x:-5.5,z:-2.8},{x:5.5,z:-2.8},{x:-5.5,z:3.3},{x:5.5,z:3.3}];const drawScene=(id,center,a,t,scale)=>{box(c,id+'bg',center.x,center.z,'#e7ddbb',8.5*scale,4.8*scale,.06,.12);actors.forEach((q,j)=>{const p=pose(q,t),x=(p.x-a.x)*a.zoom,z=(p.z-a.z)*a.zoom;if(Math.abs(x)<3.8&&Math.abs(z)<2.1)fruit(c,id+j,j%3,center.x+x*scale,center.z+z*scale,.55*a.zoom*scale,.35);});};drawScene('sample',{x:0,z:-7},goal,goal.time,.57);text(c,'sampleTitle','샘플',0,-8.5,1,3);panels.forEach((center,i)=>{const a=cameras[i];drawScene('scene'+i,center,a,a.shot?a.shotTime:c.time-start,.8);text(c,'camera'+i,a.shot?`${i+1}P ${a.result}점`:`${i+1}P ×${a.zoom.toFixed(1)}`,center.x,center.z+2.2,1,4,PAL[i]);c.players[i].x=center.x;c.players[i].z=center.z+3;c.players[i].scale=.45;});},timeout(){if(c.players.every(p=>p.score===0))c.complete([],'사진 점수가 없습니다.');else c.highest();}};
};

games['Hot Cross Blocks']=(c)=>{
 init(c,300);c.view={size:24,eye:[0,24,18],target:[0,0,0]};let until=10,phase='choose',round=0,patterns=[];c.players.forEach(p=>{p.path=new Set(['0,1']);p.front=0;p.choice=-1;p.x=-7;p.z=(p.i-1.5)*3;});
 function next(){round++;phase='choose';until=c.time+10;patterns=Array.from({length:4},()=>{const start=c.int(0,2),end=c.int(0,2),length=c.int(1,3),cells=[];for(let x=0;x<length;x++)cells.push([x,start]);for(let z=Math.min(start,end);z<=Math.max(start,end);z++)if(z!==start)cells.push([length-1,z]);return {cells,length};});c.players.forEach(p=>{p.choice=-1;p.bot=c.int(0,3);p.planRand=c.rand();p.react=c.rand(.6,3);});}next();
 return {update(){for(const p of c.players){const options=patterns.map((q,i)=>({i,valid:q.cells.some(([x,z])=>x===0&&p.path.has(`${p.front},${z}`)),length:q.length})).filter(q=>q.valid);if(options.length&&p.choice<0)p.bot=options[Math.floor(p.planRand*options.length)%options.length].i;const u=c.input(p,{[KEYS[p.bot]]:phase==='choose'&&c.time>until-10+p.react});if(phase==='choose')for(let i=0;i<4;i++)if(u[KEYS[i]+'p'])p.choice=i;}if(phase==='choose'&&c.time>=until){for(const p of c.players){if(p.choice<0||c.players.filter(q=>q.choice===p.choice).length>1)continue;const pat=patterns[p.choice],anchor=p.front+1,cells=pat.cells.map(([x,z])=>[x+anchor,z]),connected=cells.some(([x,z])=>p.path.has(`${x-1},${z}`)||p.path.has(`${x},${z-1}`)||p.path.has(`${x},${z+1}`));if(connected){cells.forEach(([x,z])=>p.path.add(`${x},${z}`));p.front=Math.max(...[...p.path].map(v=>+v.split(',')[0]));p.score=p.front;}}const done=c.players.filter(p=>p.front>=10);if(done.length)c.complete(done.map(p=>p.i),'용암 건너편 문까지 길을 연결했습니다.');phase='reveal';until=c.time+1;}if(phase==='reveal'&&c.time>=until)next();c.hint(`라운드 ${round} · A/B/C/D 블록 선택. 같은 모양 선택자는 모두 실패! 내 길 끝에 연결되지 않는 블록도 가라앉습니다.`);},render(){c.arena({width:24,depth:15,color:'#d18465'});c.players.forEach(p=>{const z=(p.i-1.5)*3;box(c,'start'+p.i,-8,z,'#8c887d',2,2.8,.1,.3);box(c,'goal'+p.i,5,z,'#8c887d',2,2.8,.1,.3);for(let gx=1;gx<=10;gx++)for(let gy=0;gy<3;gy++)if(!p.path.has(`${gx},${gy}`)){const xx=-7+gx*1.1,zz=z+(gy-1)*.8;box(c,`grid${p.i}-${gx}-${gy}`,xx,zz,'#dfaa7d',1.02,.72,-.18,.035);}for(const v of p.path){const [x,row]=v.split(',').map(Number);box(c,`block${p.i}-${v}`,-7+x*1.1,z+(row-1)*.8,p.color,1.05,.75,.05,.2);}p.x=-7+p.front*1.1;const end=[...p.path].find(v=>+v.split(',')[0]===p.front);p.z=z+((end?+end.split(',')[1]:1)-1)*.8;});patterns.forEach((q,i)=>{const x=8.1,z=(i-1.5)*3.1;q.cells.forEach(([dx,dz],j)=>box(c,`pattern${i}-${j}`,x+dx*.6,z+(dz-1)*.6,'#f0d393',.55,.55,.1,.2));text(c,'button'+i,KEYS[i].toUpperCase(),7.2,z,.6,1);});},timeout(){c.complete([],'5분 안에 출구에 도달하지 못했습니다.');}};
};

games['Thwomp the Difference']=(c)=>{
 init(c,108);let round=0,start=0,until=0,phase='play',count=3,odd=0,type=0,variant=0;const shutters=[];
 function next(){round++;start=c.time;until=c.time+20;phase='play';count=round<3?3:4;odd=c.int(0,count-1);type=c.int(0,2);variant=round<3?0:1;shutters.length=0;for(let i=0;i<count;i++)shutters.push({phase:c.rand(0,TAU),speed:c.rand(1.4,2.5),half:c.rand()<.4});c.players.forEach(p=>{p.answer=null;p.answerAt=Infinity;p.reaction=c.rand(.5,1.4);p.guess=c.rand()<.89?odd:c.int(0,count-1);});}next();
 return {update(){const open=shutters[odd],height=Math.max(0,Math.sin((c.time-start)*open.speed+open.phase))*(open.half?.9:2.4);for(const p of c.players){const u=c.input(p,{[KEYS[p.guess]]:phase==='play'&&p.answer===null&&c.time-start>p.reaction&&height>.8});if(phase==='play'&&p.answer===null)for(let i=0;i<count;i++)if(u[KEYS[i]+'p']){p.answer=i;p.answerAt=c.time;}}if(phase==='play'&&(c.players.every(p=>p.answer!==null)||c.time>=until)){rank(c,odd);phase='reveal';until=c.time+1.1;}if(phase==='reveal'&&c.time>=until){if(round===5)c.highest('다섯 문제 정답의 순서별 점수');else next();}c.hint(`${round}/5 · 들어올리는 돌 뒤에서 다른 그림 찾기! 왼쪽부터 A/B/C${count===4?'/D':''}. 정답 속도순 5·3·2·1점.`);},render(){c.arena({color:'#bcb8a8'});shutters.forEach((s,i)=>{const x=(i-(count-1)/2)*3.6,h=phase==='reveal'?3:Math.max(0,Math.sin((c.time-start)*s.speed+s.phase))*(s.half?.9:2.4);box(c,'panel'+i,x,0,'#ecddba',3,1,.8,2);fruit(c,'fruit'+i,i===odd&&variant===0?(type+1)%3:type,x,.62,i===odd&&variant===1?.7:1.1,1);box(c,'shutter'+i,x,1,'#889a9d',3.1,.45,1+h,2.1);text(c,'key'+i,KEYS[i].toUpperCase(),x,2.1,.5,2);});},timeout(){c.highest();}};
};

games['Tiny Triathlon']=(c)=>{
 init(c,Infinity);c.view={size:22,eye:[0,16,21],target:[0,0,0]};c.players.forEach(p=>{p.stage=0;p.progress=0;p.velocity=0;p.lastTilt=0;p.lastAngle=null;p.power=0;p.nextHurdle=4;});
 return {update(dt){for(const p of c.players){let raw;if(p.stage===0)raw={x:Math.floor((c.time+p.phase)/p.cadence)%2?1:-1};else if(p.stage===1)raw={x:Math.cos(c.time*(6+p.phase)),z:Math.sin(c.time*(6+p.phase))};else raw={a:p.nextHurdle-p.progress<1.6&&p.nextHurdle-p.progress>.2&&tap(c,p,.3)};const u=c.input(p,raw);if(p.stage===0){const tilt=Math.sign(u.x);if(tilt&&tilt!==p.lastTilt)p.velocity+=1.8;p.lastTilt=tilt;p.velocity*=Math.exp(-dt*1.6);p.progress+=Math.min(8,p.velocity)*dt;}else if(p.stage===1){if(Math.hypot(u.x,u.z)>.4){const a=Math.atan2(u.z,u.x);if(p.lastAngle!==null){const d=Math.abs(Math.atan2(Math.sin(a-p.lastAngle),Math.cos(a-p.lastAngle)));if(d<2)p.velocity+=d*.55;}p.lastAngle=a;}else p.lastAngle=null;p.velocity*=Math.exp(-dt*.9);p.progress+=Math.min(8,p.velocity)*dt;}else{if(c.time>(p.stun||0))p.progress+=dt*5.5;c.jump(p,u,7.2);if(p.progress>=p.nextHurdle&&p.nextHurdle<23){if(p.y<.7)p.stun=c.time+.9;p.nextHurdle+=4;}}if(p.progress>=24&&p.stage<2){p.stage++;p.progress=0;p.velocity=0;p.y=0;}p.score=p.stage*24+p.progress;p.x=(p.i-1.5)*3.6;p.z=3-p.progress*.3;p.pose=p.stage===2?'run':'attack';}const done=c.players.filter(p=>p.stage===2&&p.progress>=24);if(done.length)c.complete(done.map(p=>p.i),'수영·세발자전거·허들 세 구간을 완주했습니다.');c.hint('수영: ←/→ 번갈아 젓기 → 자전거: 방향 입력 원운동 → 허들: A 점프. 종목마다 동작이 달라집니다!');},render(){c.arena({color:'#b9c7a6'});c.players.forEach(p=>{const x=p.x;box(c,'lane'+p.i,x,-.5,p.stage===0?'#90bdcf':p.stage===1?'#b99c85':'#c5aa8e',3.2,11,-.04,.1);if(p.stage===0)box(c,'float'+p.i,x,p.z,p.color,1.1,1.6,.15,.2);if(p.stage===1){ring(c,'bike'+p.i,x,p.z,p.color,1,.25);}if(p.stage===2)for(let k=4;k<24;k+=4)box(c,`hurdle${p.i}-${k}`,x,3-k*.3,'#eed6a4',2.4,.15,.45,.9);text(c,'stage'+p.i,['수영','자전거','허들'][p.stage],x,-6,2,3);});},timeout(){c.complete([],'미완주');}};
};

games['Rinks to Riches']=(c)=>{
 init(c,30);c.bounds={x:7,z:4.5};const coins=[],snow=[{id:0,x:0,z:0,hp:3,big:true,last:-1}],grace=[];let next=.3,serial=1;c.players.forEach(p=>{p.vx=0;p.vz=0;});
 return {update(dt){if(c.time<30&&c.time>=next){const x=c.rand(-6.5,6.5),z=c.rand(-4,4);if(c.rand()<.27)snow.push({id:serial++,x,z,hp:c.rand()<.35?3:1,big:false,last:-1});else coins.push({id:serial++,x,z,value:1,y:3});next=c.time+.38;}for(const q of snow)if(q.hp===3)q.big=true;for(const coin of coins)coin.y=Math.max(.15,coin.y-dt*5);for(const p of c.players){const target=near(p,coins.filter(q=>!q.gone)),u=c.input(p,c.time<30?(target?toward(p,target.x,target.z):toward(p,0,0)):{});p.vx=(p.vx+(c.time<30?u.x:0)*dt*5)*Math.exp(-dt*.8);p.vz=(p.vz+(c.time<30?u.z:0)*dt*5)*Math.exp(-dt*.8);p.x+=p.vx*dt;p.z+=p.vz*dt;if(Math.abs(p.x)>7){p.x=clamp(p.x,-7,7);p.vx*=-.6;}if(Math.abs(p.z)>4.5){p.z=clamp(p.z,-4.5,4.5);p.vz*=-.6;}for(const s of snow)if(s.hp>0&&dist(p,s)<(s.big?1:.5)&&c.time-s.last>.28){s.last=c.time;s.hp--;p.vx*=-.3;p.vz*=-.3;if(s.hp===0&&s.big)coins.push({id:serial++,x:s.x,z:s.z,value:3,y:.15});}for(const q of coins)if(!q.gone&&q.y<.5&&dist(p,q)<.65){q.gone=true;c.points(p,q.value);}}c.hint('방향키로 얼음 스케이트 조종. 작은 눈덩이는 감속, 큰 눈덩이를 3번 부딪쳐 깨면 3코인!');},render(){c.arena({color:'#c5e2e1'});snow.forEach(s=>{if(s.hp>0){ball(c,'snow'+s.id,s.x,s.z,'#f1f0de',s.big?1.65:.8,s.big?.8:.4);if(s.big)text(c,'hp'+s.id,s.hp,s.x,s.z,1.9,1);}});coins.forEach(q=>{if(!q.gone)ball(c,'coin'+q.id,q.x,q.z,q.value===3?'#dc777e':'#eac459',.35,q.y);});c.players.forEach(p=>box(c,'skate'+p.i,p.x,p.z,'#748b96',.18,1.2,.05,.15));},timeout(){if(c.limit===30){c.limit=30.4;}else coinFinish(c,'각자가 모은 코인을 받습니다.');}};
};

games['Treetop Treasure']=(c)=>{
 init(c,30);c.view={size:21,eye:[0,10,20],target:[0,1,0]};const seesaws=[{x:-4.2,tilt:0},{x:4.2,tilt:0}],coins=[];let next=0,serial=0;c.players.forEach((p,i)=>{p.x=i<2?-6+i*3:3+(i-2)*3;p.z=0;p.y=0;p.vy=0;});
 function surface(x){const s=seesaws.find(s=>Math.abs(x-s.x)<=3.4);return s?{s,y:.9+(x-s.x)*s.tilt}:null;}
 return {update(dt){if(c.time>=next){coins.push({id:serial++,x:c.rand(-7.3,7.3),z:0,y:c.rand(1.6,4.2),value:c.rand()<.23?3:1,gone:false});next=c.time+.32;}for(const s of seesaws){const riders=c.players.filter(p=>!p.respawn&&Math.abs(p.x-s.x)<3.4&&p.y<surface(p.x).y+.15),torque=riders.reduce((a,p)=>a+(p.x-s.x),0);s.tilt+=(-clamp(torque*.07,-.4,.4)-s.tilt)*dt*3;}for(const p of c.players){const target=near(p,coins.filter(q=>!q.gone)),u=c.input(p,target?{x:Math.sign(target.x-p.x),a:Math.abs(target.x-p.x)<1.5&&tap(c,p,.6)}:{});if(p.respawn){if(c.time>=p.respawn){p.respawn=0;p.x=p.i<2?-4.2:4.2;p.y=2;p.vy=0;}continue;}p.x=clamp(p.x+u.x*dt*3.8,-9,9);const ground=surface(p.x),old=p.y;if(ground&&p.y<=ground.y+.1&&u.ap)p.vy=7.4;p.vy-=dt*16;p.y+=p.vy*dt;if(ground&&p.y<ground.y&&p.vy<0){p.y=ground.y;p.vy=0;}for(const q of c.players)if(q!==p&&!q.respawn&&p.vy<0&&old>q.y+.8&&p.y<q.y+.9&&Math.abs(p.x-q.x)<.65){p.vy=10;p.y=q.y+.9;}if(p.y< -2){p.respawn=c.time+2;p.y=-1.5;}for(const q of coins)if(!q.gone&&Math.abs(p.x-q.x)<.6&&Math.abs(p.y+.7-q.y)<.65){q.gone=true;c.points(p,q.value);}p.pose='jump';}c.hint('←/→ 이동 · A 점프. 시소의 기울기와 다른 선수 위 튀어오르기를 이용하세요. 추락하면 2초 뒤 구조됩니다.');},render(){seesaws.forEach((s,i)=>{c.draw('seesaw'+i,'box',{x:s.x,y:.9,z:0,sx:6.8,sy:.22,sz:2,rz:Math.atan(s.tilt),color:'#b9986e'});c.draw('pivot'+i,'cone',{x:s.x,y:.3,z:0,sx:1.2,sy:1.1,sz:1.2,color:'#719d85'});});coins.forEach(q=>{if(!q.gone)ball(c,'coin'+q.id,q.x,0,q.value===3?'#d67c80':'#e6c45c',.35,q.y);});},timeout(){coinFinish(c,'각자가 받은 나무 위 코인을 받습니다.');}};
};

games['Sunset Standoff']=(c)=>{
 init(c,35);c.bounds={x:6.8,z:1.3};let round=0,start=0,phase='flight',until=0;const missile={x:0,z:-12};c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*4;p.z=0;});
 function next(){round++;start=c.time;phase='flight';missile.x=c.rand(-3,3);missile.z=-12;}next();
 return {update(dt){const target=near(missile,c.players.slice(1).filter(p=>p.alive)),u=c.input(c.players[0],target?{x:Math.sign(target.x-missile.x)}:{});if(phase==='flight'){missile.x=clamp(missile.x+u.x*dt*3.2,-6.7,6.7);missile.z+=dt*4.1;}for(const p of c.players.slice(1)){const evade=missile.z>-5?Math.sign(p.x-missile.x)||1:Math.sin(c.time+p.phase),v=c.input(p,{x:evade,z:Math.sin(c.time+p.i)*.4});c.move(p,v,4.3);if(p.alive&&phase==='flight'&&dist(p,missile)<1.25)c.eliminate(p);}const solo=c.players[0];solo.x=missile.x;solo.z=missile.z;solo.y=.7;if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'다섯 번의 돌진 안에 세 명을 모두 잡았습니다.');if(phase==='flight'&&missile.z>4){phase='pause';until=c.time+.8;}if(phase==='pause'&&c.time>=until){if(round===5)c.complete([1,2,3],'다섯 번의 돌진에서 살아남았습니다.');else next();}c.hint(`${round}/5 돌진 · 1P ←/→ 비행체 조종 · 2~4P 좁은 활주로에서 이동 회피. 한 명 생존이면 팀 승리!`);},render(){c.arena({width:16,depth:5,color:'#caaa8d'});box(c,'runway',0,-5,'#bc947a',16,19,-.4,.3);c.draw('missile','cylinder',{x:missile.x,y:.6,z:missile.z,sx:1.9,sy:3,sz:1.9,rx:Math.PI/2,color:'#567483'});},timeout(){c.complete([1,2,3],'팀원이 살아남았습니다.');}};
};

games['Cookie Cutters']=(c)=>{
 init(c,30);const states=[0,1].map(()=>({cells:Array.from({length:9},()=>c.int(0,2)),cursor:0,done:[],next:0})),sum=[0,0],names=['버섯','별','네모'];c.players.forEach(p=>p.react=c.rand(.25,.5));
 function cut(t,shape){const s=states[t];if(c.time<s.next)return;const good=shape===s.cells[s.cursor];if(good)sum[t]++;s.done.push(good);s.cursor++;s.next=c.time+.1;if(s.cursor===9){s.cursor=0;s.done=[];s.cells=Array.from({length:9},()=>c.int(0,2));s.next=c.time+.35;}}
 return {update(){const actions=[];for(const p of c.players){const t=p.i===0?0:1,s=states[t],target=s.cells[s.cursor];let raw={};if(c.time>s.next+p.react&&tap(c,p,p.cadence)){if(p.i===0)raw[KEYS[target]]=true;else if(p.i-1===target)raw.a=true;}const u=c.input(p,raw);if(p.i===0){for(let i=0;i<3;i++)if(u[KEYS[i]+'p'])actions.push({t:0,shape:i});}else if(u.ap)actions.push({t:1,shape:p.i-1});}for(const action of c.shuffle(actions))cut(action.t,action.shape);scores(c,sum,SIDE);c.hint('표시된 반죽 칸의 모양을 누르세요. 1P A=버섯 B=별 C=네모 / 2·3·4P는 각 버섯·별·네모 담당, A로 누르기!');},render(){c.arena({color:'#cdb495'});states.forEach((s,t)=>{const x=t?4.6:-4.6;box(c,'board'+t,x,0,t?'#8ac4c0':'#d398ac',7.8,7.4,.08,.2);s.cells.forEach((type,i)=>{const px=x+(i%3-1)*2,pz=(Math.floor(i/3)-1)*1.8;box(c,`dough${t}-${i}`,px,pz,'#efdaab',1.85,1.65,.25,.2);if(i>=s.cursor){if(type===0)ring(c,`shape${t}-${i}`,px,pz,'#a78364',.85,.43);else if(type===1){for(let k=0;k<5;k++){const a=k*TAU/5;c.draw(`star${t}-${i}-${k}`,'box',{x:px+Math.cos(a)*.2,y:.43,z:pz+Math.sin(a)*.2,sx:.55,sy:.08,sz:.14,ry:-a,color:'#a78364'});}}else for(let k=0;k<4;k++)box(c,`square${t}-${i}-${k}`,px+(k<2?(k?.4:-.4):0),pz+(k>1?(k===2?-.4:.4):0),'#a78364',k<2?.08:.8,k<2?.8:.08,.43,.08);}else text(c,`cut${t}-${i}`,s.done[i]?'✓':'½',px,pz,.45,1.3);if(i===s.cursor)ring(c,'current'+t,px,pz,'#dd7498',1.7,.5);});text(c,'total'+t,sum[t],x,-4.3,1.4,3);});c.players[0].x=-4.6;c.players[0].z=4.8;c.players.slice(1).forEach((p,j)=>{p.x=4.6+(j-1)*2;p.z=4.8;});},timeout(){finish(c,sum,'30초 동안 정확하게 찍은 쿠키 수',SIDE);}};
};

games['Unfriendly Flying Object']=(c)=>{
 init(c,30);c.view={size:21,eye:[0,7,23],target:[0,3,0]};const plates=[];let ready=0,serial=0,width=3,up=false;const solo=c.players[0];solo.x=0;solo.z=0;solo.y=7;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*5;p.z=0;p.vy=0;});
 return {update(dt){const target=c.players.slice(1).filter(p=>p.alive).sort((a,b)=>Math.abs(a.x-solo.x)-Math.abs(b.x-solo.x))[0],u=c.input(solo,{x:target?Math.sign(target.x-solo.x):0,a:target&&Math.abs(target.x-solo.x)<width*.4&&c.time>ready});solo.x=clamp(solo.x+u.x*dt*4.6,-7,7);if(u.ap&&c.time>=ready){plates.push({id:serial++,x:solo.x,y:6,vy:0,w:width,up,landed:false});ready=c.time+.85;width=c.pick([1.8,2.7,3.6]);up=!up;}for(const plate of plates)if(!plate.landed){const old=plate.y;plate.vy-=dt*10;plate.y+=plate.vy*dt;const support=Math.max(.2,...plates.filter(q=>q!==plate&&q.landed&&Math.abs(q.x-plate.x)<(q.w+plate.w)/2).map(q=>q.y+.42));if(plate.y<=support){plate.y=support;plate.landed=true;}for(const p of c.players.slice(1))if(p.alive&&Math.abs(p.x-plate.x)<plate.w/2+.25&&old>p.y+.6&&plate.y<p.y+1.2)c.eliminate(p);}for(const p of c.players.slice(1)){const danger=plates.filter(q=>!q.landed&&Math.abs(q.x-p.x)<q.w/2+1).sort((a,b)=>a.y-b.y)[0];const goal=danger?clamp(danger.x+(p.x>=danger.x?1:-1)*(danger.w/2+1.2),-7,7):p.x;const obstacle=plates.find(q=>q.landed&&Math.abs(q.x-p.x)<q.w/2+1&&q.y>p.y-.1);const v=c.input(p,{x:Math.sign(goal-p.x),a:!!obstacle&&tap(c,p,.45)});if(!p.alive)continue;p.x=clamp(p.x+v.x*dt*4.5,-7.3,7.3);const supports=plates.filter(q=>q.landed&&!q.up&&Math.abs(p.x-q.x)<q.w/2),ground=Math.max(0,...supports.map(q=>q.y+.24));if(p.y<=ground+.1&&v.ap)p.vy=7.5;p.vy-=dt*18;const old=p.y;p.y+=p.vy*dt;if(p.y<ground&&p.vy<0&&old>=ground-.12){p.y=ground;p.vy=0;}if(p.y<0){p.y=0;p.vy=0;}for(const q of plates)if(q.landed&&Math.abs(p.x-q.x)<q.w/2+.15){if(q.up&&Math.abs(p.y-q.y)<.65)c.eliminate(p);else if(p.y<q.y-.1){p.x=q.x+Math.sign(p.x-q.x||1)*(q.w/2+.25);if(Math.abs(p.x)>7.3)c.eliminate(p);}}p.pose=p.y>.1?'jump':'run';}if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'가시판으로 세 명을 모두 잡았습니다.');c.hint('1P ←/→ 이동 · A 가시판 낙하. 2~4P ←/→ 회피 · A 점프. 가시·낙하 압착·벽 끼임을 피하세요!');},render(){c.arena({width:16,depth:3,color:'#a0bc8c'});for(const side of [-1,1])box(c,'wall'+side,side*8,0,'#bea383',.6,3,4,8);c.draw('ufo','sphere',{x:solo.x,y:7,z:0,sx:2.8,sy:.5,sz:2.8,color:'#ad9ec0'});box(c,'preview',solo.x,0,'#758ba5',width,1.4,6.3,.35);plates.forEach(q=>{box(c,'plate'+q.id,q.x,0,'#729bb1',q.w,1.3,q.y,.3);for(let j=0;j<Math.floor(q.w/.5);j++)c.draw(`spike${q.id}-${j}`,'cone',{x:q.x+(j-(Math.floor(q.w/.5)-1)/2)*.5,y:q.y+(q.up?.38:-.38),z:0,sx:.45,sy:.5,sz:.45,rz:q.up?0:Math.PI,color:'#b3bfc5'});});},timeout(){c.complete([1,2,3],'팀원 한 명 이상이 가시판을 피했습니다.');}};
};

games['Lost and Pound']=(c)=>{
 init(c,75);let round=0,phase='hide',until=0,secret=0,hp=3,revealAt=0;const holes=[{x:-3,z:-1.5},{x:3,z:-1.5},{x:-3,z:2},{x:3,z:2}];
 function next(){round++;phase='hide';until=c.time+10;secret=c.int(0,3);c.players.forEach(p=>{p.choice=-1;p.guess=c.int(0,3);p.reaction=c.rand(.8,3);});}next();
 return {update(){for(const p of c.players){const active=p.i===0?phase==='hide':phase==='strike',u=c.input(p,{[KEYS[p.guess]]:active&&c.time>until-10+p.reaction});if(active)for(let i=0;i<4;i++)if(u[KEYS[i]+'p']){p.choice=i;if(p.i===0)secret=i;}}if(phase==='hide'&&(c.players[0].choice>=0||c.time>=until)){phase='strike';until=c.time+10;}if(phase==='strike'&&(c.players.slice(1).every(p=>p.choice>=0)||c.time>=until)){phase='reveal';revealAt=c.time;until=c.time+2;const hits=c.players.slice(1).filter(p=>p.choice===secret).length;hp=Math.max(0,hp-hits);c.players[0].score=3-hp;if(hp===0)c.complete([1,2,3],'숨은 구멍을 세 번 맞혔습니다.');}if(phase==='reveal'&&c.time>=until){if(round===3)c.complete([0],'세 라운드에서 목숨을 남겼습니다.');else next();}c.hint(`${round}/3 · 남은 목숨 ${hp} · ${phase==='hide'?'1P A/B/C/D로 비밀 구멍 선택':phase==='strike'?'2~4P A/B/C/D로 망치 칠 구멍 선택':'구멍 공개!'}`);},render(){c.arena({color:'#a8b3bd'});holes.forEach((h,i)=>{c.draw('hole'+i,'cylinder',{x:h.x,y:.04,z:h.z,sx:2.2,sy:.1,sz:2.2,color:'#4b606c'});text(c,'key'+i,KEYS[i].toUpperCase(),h.x,h.z+1.4,.3,1.5);if(phase==='reveal'){if(i===secret)ball(c,'head',h.x,h.z,'#ef9bae',1,.8);c.players.slice(1).forEach(p=>{if(p.choice===i)box(c,'hammer'+p.i,h.x+(p.i-2)*.45,h.z,p.color,.8,.8,1.6,.7);});}});c.players[0].visible=phase==='hide';c.players.slice(1).forEach((p,j)=>{p.x=(j-1)*3;p.z=5;});},timeout(){c.complete(hp>0?[0]:[1,2,3],'숨바꼭질 종료');}};
};

games['Arch Rivals']=(c)=>{
 init(c,30);c.view={size:22,eye:[0,11,21],target:[0,1,0]};const targets=c.players.slice(1).map((p,i)=>({x:(i-1)*4,z:-2,tilt:0})),arrows=[];let next=0,serial=0;const solo=c.players[0];solo.z=5;
 return {update(dt){solo.x=Math.sin(c.time*1.15)*6.5;const lined=targets.find(t=>Math.abs(t.x+Math.sin(t.tilt)*1.1-solo.x)<.5),u=c.input(solo,{a:!!lined&&c.time>next});if(u.ap&&c.time>=next){arrows.push({id:serial++,x:solo.x,z:4.5,done:false});next=c.time+.48;}for(const p of c.players.slice(1)){const t=targets[p.i-1],danger=arrows.some(a=>!a.done&&Math.abs(a.x-t.x)<2),v=c.input(p,{x:danger?Math.sign(t.x-solo.x)||1:Math.sin(c.time+p.phase)});t.tilt=clamp(v.x,-1,1)*.95;p.x=t.x;p.z=-3;p.rotation=t.tilt;}for(const a of arrows)if(!a.done){a.z-=dt*15;if(a.z< -2){a.done=true;for(const t of targets){const center=t.x+Math.sin(t.tilt)*1.1,w=1.5*Math.max(.4,Math.cos(t.tilt)),d=Math.abs(a.x-center);if(d<w){c.points(solo,d<w/3?30:d<w*2/3?20:10);break;}}}}if(solo.score>=100)c.complete([0],'과녁 중앙과 가장자리를 맞혀 100점을 얻었습니다.');c.hint('1P는 자동 왕복 이동 · A 화살. 2~4P ←/→ 과녁 기울이기. 중앙 30, 중간 20, 가장자리 10점. 100점이면 공격수 승리!');},render(){c.arena({color:'#c6bea4'});targets.forEach((t,i)=>{for(let j=0;j<3;j++)c.draw(`target${i}-${j}`,'cylinder',{x:t.x+Math.sin(t.tilt)*1.1,y:1.5,z:t.z+j*.04,sx:(3-j)*Math.max(.4,Math.cos(t.tilt)),sy:.1,sz:3-j,rx:Math.PI/2,rz:t.tilt,color:['#e7c668','#c789a2','#7ba6b5'][j]});});arrows.forEach(a=>{if(!a.done)box(c,'arrow'+a.id,a.x,a.z,'#78674e',.07,1.1,1.5,.07);});box(c,'moving',solo.x,5,'#9baaa9',2,1.5,.05,.2);},timeout(){c.complete([1,2,3],'공격수가 100점에 도달하지 못했습니다.');}};
};

games['On-Again, Off-Again']=(c)=>{
 init(c,30);c.view={size:21,eye:[0,10,23],target:[0,2,0]};let on=true,next=.6,serial=0;const rocks=[];c.players[0].x=-8;c.players[0].z=0;c.players.slice(1).forEach((p,j)=>{p.x=(j-1)*4;p.z=0;p.vy=0;});
 return {update(dt){if(c.time>=next){rocks.push({id:serial++,x:c.pick([-1,1])*6.5,y:5.6,vx:c.pick([-1,1])*2,vy:0,level:2});next=c.time+.7;}const threat=rocks.some(r=>r.level>0&&c.players.slice(1).some(p=>p.alive&&Math.abs(p.x-r.x)<1)),u=c.input(c.players[0],{a:threat&&tap(c,c.players[0],.9)});if(u.ap)on=!on;for(const r of rocks){r.x+=r.vx*dt;if(Math.abs(r.x)>6.7){r.x=clamp(r.x,-6.7,6.7);r.vx*=-1;}const floor=r.level===2?5:r.level===1?2.8:0,support=r.level===0||(r.level===2?on:!on);if(!support||r.y>floor+.1){r.vy-=dt*10;r.y+=r.vy*dt;if(support&&r.y<floor+.4){r.y=floor+.4;r.vy=0;}if(r.level===2&&r.y<3.3)r.level=1;if(r.level===1&&r.y<.6)r.level=0;}else r.y=floor+.4;}for(const p of c.players.slice(1)){const nearRock=rocks.find(r=>r.y<2&&Math.abs(r.x-p.x)<2),v=c.input(p,{x:nearRock?Math.sign(p.x-nearRock.x)||1:Math.sin(c.time+p.phase)*.4,a:nearRock&&nearRock.y<1&&tap(c,p,.45)});if(p.alive){p.x=clamp(p.x+v.x*dt*4,-6.8,6.8);c.jump(p,v,7);for(const r of rocks)if(Math.abs(p.x-r.x)<.7&&Math.abs(p.y+.5-r.y)<.7)c.eliminate(p);}}if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'스위치로 세 명 모두에게 바위를 떨어뜨렸습니다.');c.hint('1P A: ON/OFF 발판 전환 · 2~4P ←/→ 이동, A 점프. 위에 모인 바위가 어느 발판으로 떨어지는지 보세요!');},render(){c.arena({width:16,depth:3,color:'#b4c49a'});for(let level=1;level<=2;level++)for(let i=0;i<7;i++)box(c,`platform${level}-${i}`,(i-3)*2,0,(level===2?on:!on)?'#d18996':'#9bbbc3',1.9,1.2,level===2?4.8:2.6,(level===2?on:!on)?.2:.035);rocks.forEach(r=>ball(c,'rock'+r.id,r.x,0,'#82918f',1.1,r.y));box(c,'switch',-8,0,on?'#e2949f':'#73a6c1',1,1,1.8,1);text(c,'onoff',on?'ON':'OFF',-8,0,3,2);},timeout(){c.complete([1,2,3],'바위에서 살아남았습니다.');}};
};

games['Broozer Bash']=(c)=>{
 init(c,30);c.bounds={x:7,z:4.5};const robot={x:0,z:0,angle:0};c.players.slice(1).forEach((p,j)=>{p.x=(j-1)*5;p.z=3;});
 return {update(dt){const solo=c.players[0],target=near(robot,c.players.slice(1).filter(p=>p.alive));let delta=0;if(target){const a=Math.atan2(target.z-robot.z,target.x-robot.x);delta=Math.atan2(Math.sin(a-robot.angle),Math.cos(a-robot.angle));}const u=c.input(solo,{b:delta<-.1,c:delta>.1,a:Math.abs(delta)<.8});robot.angle+=((u.c?1:0)-(u.b?1:0))*dt*1.4;if(u.a){robot.x=clamp(robot.x+Math.cos(robot.angle)*dt*3.6,-6.7,6.7);robot.z=clamp(robot.z+Math.sin(robot.angle)*dt*3.6,-4.2,4.2);}for(const p of c.players.slice(1)){const angle=Math.atan2(p.z-robot.z,p.x-robot.x)+(p.i%2?1:-1)*(.65+p.phase*.45);let dx=Math.cos(angle),dz=Math.sin(angle);if(p.x>5.8&&dx>0)dx=-.6;if(p.x< -5.8&&dx<0)dx=.6;if(p.z>3.5&&dz>0)dz=-.6;if(p.z< -3.5&&dz<0)dz=.6;if(p.escape&&dist(p,p.escape)<.35)p.escape=null;if(!p.escape&&Math.abs(p.x)>5.4&&Math.abs(p.z)>3.1)p.escape={x:Math.sign(p.x)*3,z:-Math.sign(p.z)*2.7};if(p.escape){const move=toward(p,p.escape.x,p.escape.z);dx=move.x;dz=move.z;}const v=c.input(p,{x:dx,z:dz});c.move(p,v,4.5);const front={x:robot.x+Math.cos(robot.angle)*1.1,z:robot.z+Math.sin(robot.angle)*1.1};if(u.a&&p.alive&&dist(p,front)<1.15)c.eliminate(p);}solo.x=robot.x;solo.z=robot.z;solo.y=1;solo.rotation=-robot.angle;if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'로봇의 주먹으로 세 명을 모두 잡았습니다.');c.hint('1P A 누르기: 전진·펀치, B/C: 좌·우 회전. 2~4P 방향키 회피. 옆걸음할 수 없는 로봇의 방향을 읽으세요!');},render(){c.arena({color:'#b2aaa2'});c.draw('robot','box',{x:robot.x,y:.7,z:robot.z,sx:1.6,sy:1.4,sz:1.6,ry:-robot.angle,color:'#9194a3'});for(const side of [-1,1]){const a=robot.angle+side*.7;ball(c,'glove'+side,robot.x+Math.cos(a)*1.1,robot.z+Math.sin(a)*1.1,'#d184a0',.85,.9);}},timeout(){c.complete([1,2,3],'팀원 한 명 이상이 30초 동안 남았습니다.');}};
};

games['Cage Catch']=(c)=>{
 init(c,30);c.bounds={x:6.8,z:4.2};const cage={x:0,z:0,state:'ready',at:0},fish=Array.from({length:3},(_,i)=>({x:(i-1)*4,z:0,phase:c.rand(0,TAU)})),solo=c.players[0];solo.x=0;solo.z=2;
 return {update(dt){fish.forEach((f,i)=>{f.x=Math.sin(c.time*(.7+i*.2)+f.phase)*6;f.z=Math.cos(c.time*(.9+i*.2)+f.phase)*3.5;});const safe=Array.from({length:24},(_,i)=>({x:(i%6-2.5)*2,z:(Math.floor(i/6)-1.5)*2})).map(q=>({...q,s:dist(q,cage)-dist(q,solo)*.3+Math.min(...fish.map(f=>dist(f,q)))*.4})).sort((a,b)=>b.s-a.s)[0];const u=c.input(solo,{...toward(solo,safe.x,safe.z),a:tap(c,solo,.22)});if(c.time>(solo.stun||0))c.move(solo,u,u.ap?8:3.5);if(fish.some(f=>dist(f,solo)<.75)&&c.time>(solo.inv||0)){solo.stun=c.time+.6;solo.inv=c.time+1.2;}const uy=c.input(c.players[1],{z:clamp((solo.z-cage.z)*3,-1,1)}),ux=c.input(c.players[2],{x:clamp((solo.x-cage.x)*3,-1,1)}),ud=c.input(c.players[3],{a:cage.state==='ready'&&dist(cage,solo)<.9});if(cage.state==='ready'){cage.x=clamp(cage.x+ux.x*dt*4.3,-6.5,6.5);cage.z=clamp(cage.z+uy.z*dt*4.3,-4,4);if(ud.ap){cage.state='drop';cage.at=c.time;}}else if(cage.state==='drop'&&c.time-cage.at>.45){if(dist(cage,solo)<1.05)c.complete([1,2,3],'세 역할을 맞춰 수영 선수를 가뒀습니다.');cage.state='reset';cage.at=c.time;}else if(cage.state==='reset'&&c.time-cage.at>1.3)cage.state='ready';c.players.slice(1).forEach((p,j)=>{p.x=(j-1)*3;p.z=5.7;});c.hint('1P 이동+A 연타 빠른 수영 · 2P ↑/↓ 우리 세로 · 3P ←/→ 우리 가로 · 4P A 낙하. 물고기와 닿으면 잠깐 기절!');},render(){c.arena({width:16,depth:10,color:'#85bdcb'});fish.forEach((f,i)=>fruit(c,'fish'+i,1,f.x,f.z,.7,.35));const y=cage.state==='ready'?3:cage.state==='drop'?Math.max(.5,3-(c.time-cage.at)*6):.5;for(let i=0;i<4;i++)box(c,'bar'+i,cage.x+(i<2?(i?1:-1):0),cage.z+(i>=2?(i===2?-1:1):0),'#c5b06d',i<2?.1:2.1,i<2?2.1:.1,y,.9);ring(c,'shadow',cage.x,cage.z,'#e7d58c',2.3,.1);['세로','가로','내리기'].forEach((v,j)=>text(c,'role'+j,v,(j-1)*3,5.6,2,2.5,PAL[j+1]));},timeout(){c.complete([0],'30초 동안 우리를 피했습니다.');}};
};

games['Income Stream']=(c)=>{
 init(c,Infinity);c.view={size:22,eye:[0,17,20],target:[0,0,-2]};const coins=Array.from({length:33},(_,i)=>({x:c.rand(-3.5,3.5),at:4+i*2,value:1,gone:false}));let travel=0;const finishAt=74;c.players.forEach(p=>{p.x=(p.i-1.5)*1.4;p.z=p.i===0?2:0;p.depth=p.z;});const center=t=>Math.sin(t*.065)*2.1;
 return {update(dt){travel+=dt*2.6;for(const p of c.players){const nearby=coins.filter(q=>!q.gone&&q.at>travel-3&&q.at<travel+10),target=near({x:p.x,z:0},nearby.map(q=>({x:q.x+center(q.at),z:0}))),u=c.input(p,target?{x:clamp((target.x-p.x)*2,-1,1),z:-.2}:{});if(p.respawn){if(c.time>=p.respawn){p.respawn=0;p.x=center(travel);p.depth=4;}else continue;}p.x+=u.x*dt*(p.i===0?3.4:4.5);p.depth=clamp(p.depth+u.z*dt*2,-1,4);p.z=p.depth;if(Math.abs(p.x-center(travel-p.depth))>4.4){p.respawn=c.time+2;p.y=-1;continue;}p.y=.15;for(const q of coins)if(!q.gone&&Math.abs(q.at-(travel-p.depth))<.6&&Math.abs(q.x+center(q.at)-p.x)<(p.i===0?1:.55)){q.gone=true;c.points(p);}if(p.i>0&&dist(p,c.players[0])<1.35){p.x+=Math.sign(p.x-c.players[0].x||1)*dt*6;p.depth=Math.min(4,p.depth+dt*3);}}if(travel>=finishAt)coinFinish(c,'수로의 33개 코인 중 각자가 모은 코인을 받습니다.');c.hint('방향키: 물 위 조종. 1P 큰 탈것은 강하게 밀어내고, 2~4P는 흩어져 코인 수집! 수로 밖으로 빠지면 2초 손해.');},render(){for(let i=-3;i<12;i++){const at=travel+i*2;box(c,'water'+i,center(at),-i*2,'#8dbec9',9,2.1,-.15,.3);}coins.forEach((q,i)=>{const z=travel-q.at;if(!q.gone&&z>-18&&z<8)ball(c,'coin'+i,q.x+center(q.at),z,'#e3bf55',.35,.6);});c.players.forEach(p=>{if(!p.respawn)c.draw('boat'+p.i,'sphere',{x:p.x,y:.1,z:p.z,sx:p.i===0?2.3:.7,sy:.45,sz:p.i===0?2.7:1.6,color:p.color});});},timeout(){coinFinish(c,'획득 코인을 받습니다.');}};
};

games['Squeaky Shakedown']=(c)=>{
 init(c,30);c.bounds={x:7,z:4.5};c.players[0].x=0;c.players[0].z=0;c.players.slice(1).forEach((p,j)=>{p.x=(j-1)*5;p.z=3;p.score=7;});let ready=0;
 return {update(){const solo=c.players[0],target=near(solo,c.players.slice(1).filter(p=>p.score>0)),u=c.input(solo,target?{...toward(solo,target.x,target.z),a:dist(solo,target)<1.5&&tap(c,solo,.35)}:{});c.move(solo,u,5.1);if(u.ap&&c.time>=ready){ready=c.time+.42;solo.pose='attack';const hit=near(solo,c.players.slice(1).filter(p=>p.score>0&&c.time>(p.inv||0)));if(hit&&dist(solo,hit)<1.5){hit.score--;c.points(solo);hit.inv=c.time+.55;const v=toward(solo,hit.x,hit.z);hit.x=clamp(hit.x+v.x*.8,-7,7);hit.z=clamp(hit.z+v.z*.8,-4.5,4.5);}}for(const p of c.players.slice(1)){const a=Math.atan2(p.z-solo.z,p.x-solo.x)+(p.i%2?1:-1)*.8;let dx=Math.cos(a),dz=Math.sin(a);if(p.x>5.8&&dx>0)dx=-.6;if(p.x< -5.8&&dx<0)dx=.6;if(p.z>3.5&&dz>0)dz=-.6;if(p.z< -3.5&&dz<0)dz=.6;if(p.escape&&dist(p,p.escape)<.35)p.escape=null;if(!p.escape&&Math.abs(p.x)>5.4&&Math.abs(p.z)>3.1)p.escape={x:Math.sign(p.x)*3,z:-Math.sign(p.z)*2.7};if(p.escape){const move=toward(p,p.escape.x,p.escape.z);dx=move.x;dz=move.z;}const v=c.input(p,p.score>0?{x:dx,z:dz}:{});if(p.score>0)c.move(p,v,4.7);else p.pose='sleep';}if(solo.score===21)coinFinish(c,'상대의 코인 21개를 모두 가져왔습니다.');c.hint('1P 이동 · A 망치로 1코인씩 빼앗기. 2~4P는 각자 가진 7코인을 지키세요. 0코인이면 더 움직일 수 없습니다.');},render(){c.arena({color:'#c6b68f'});const p=c.players[0];box(c,'hammer',p.x+.8,p.z-.3,'#dbb35c',1,.7,1.3,.7);c.players.slice(1).forEach(q=>text(c,'coins'+q.i,q.score,q.x,q.z,2.4,1.6));},timeout(){coinFinish(c,'공격수의 획득량과 팀원의 남은 코인을 각각 받습니다.');}};
};

games['Rocky Rope Race']=(c)=>{
 init(c,180);c.view={size:24,eye:[0,16,22],target:[0,1,0]};const teams=[0,1].map(t=>({t,bar:[0,1],held:[true,true],swing:[null,null],reset:0,furthest:1}));let camera=0;
 return {update(dt){for(const t of teams){const raw=TEAM[t.t].map((i,j)=>{if(t.reset)return {};if(t.swing[j])return {a:t.swing[j].phase>.84};const other=1-j,front=t.bar[j]>=t.bar[other];return {a:front||!t.held[other]};}),inputs=TEAM[t.t].map((i,j)=>c.input(c.players[i],raw[j]));if(t.reset){if(c.time>=t.reset){t.reset=0;const n=Math.max(0,t.furthest-1);t.bar=[n,n+1];t.held=[true,true];t.swing=[null,null];}continue;}for(let j=0;j<2;j++){const other=1-j;if(t.held[j]&&!inputs[j].a){t.held[j]=false;if(t.held[other])t.swing[j]={pivot:t.bar[other],phase:0,duration:1.05+c.players[TEAM[t.t][j]].phase*.18};}if(t.swing[j]){const swing=t.swing[j];swing.phase+=dt/swing.duration;const angle=Math.PI+clamp(swing.phase,0,1)*Math.PI,p=c.players[TEAM[t.t][j]],x=swing.pivot*1.4+Math.cos(angle)*1.4;if(inputs[j].a&&swing.phase>.86){t.bar[j]=swing.pivot+1;t.held[j]=true;t.swing[j]=null;t.furthest=Math.max(t.furthest,t.bar[j]);}else if(swing.phase>1.35){t.held[j]=false;t.swing[j]=null;}}}if(!t.held.some(Boolean)||(!t.swing.some(Boolean)&&!t.held.every(Boolean)))t.reset=c.time+2;TEAM[t.t].forEach(i=>c.players[i].score=Math.max(0,Math.min(...t.bar)));}const done=teams.filter(t=>Math.min(...t.bar)>=12);if(done.length)c.complete(done.length===2?[0,1,2,3]:TEAM[done[0].t],'로프를 번갈아 잡고 동굴의 끝에 도착했습니다.');camera=Math.max(0,Math.min(...teams.map(t=>Math.min(...t.bar)))*1.4-4);for(const t of teams)TEAM[t.t].forEach((i,j)=>{const p=c.players[i],s=t.swing[j],angle=s?Math.PI+clamp(s.phase,0,1)*Math.PI:0;p.x=(s?s.pivot*1.4+Math.cos(angle)*1.4:t.bar[j]*1.4)-camera-5;p.z=t.t?3:-3;p.y=t.reset?-1:s?2.5+Math.sin(angle)*1.4:2.5;p.pose='jump';});c.hint('A를 누르면 봉 잡기, 놓으면 동료를 축으로 스윙. 앞사람이 잡은 동안 뒷사람이 놓고 다음 봉에서 다시 A! 둘 다 놓으면 추락합니다.');},render(){box(c,'cave-back',0,-5,'#b4ab96',23,.6,2,6);for(let t=0;t<2;t++){for(let i=0;i<15;i++){const x=i*1.4-camera-5;if(x>-10&&x<11)box(c,`bar${t}-${i}`,x,t?2.7:-3.3,'#d3c696',.5,.8,3.5,.15);}const a=c.players[t*2],b=c.players[t*2+1];const dx=b.x-a.x,dz=b.z-a.z,dy=b.y-a.y;c.draw('rope'+t,'box',{x:(a.x+b.x)/2,y:(a.y+b.y)/2+.35,z:(a.z+b.z)/2,sx:Math.hypot(dx,dy,dz),sy:.08,sz:.08,ry:-Math.atan2(dz,dx),rz:Math.atan2(dy,Math.hypot(dx,dz)),color:'#ede3bd'});}c.players.forEach(p=>text(c,'grip'+p.i,teams[p.i<2?0:1].held[p.i%2]?'잡음':'스윙',p.x,p.z,p.y+1.6,1.8,p.color));},timeout(){c.complete([],'3분 안에 동굴을 통과하지 못했습니다.');}};
};

games["Pickin' Produce"]=(c)=>{
 init(c,30);const centers=[-4.8,4.8],fruitList=[],sum=[0,0],beltX=(t,l)=>centers[t]+(l-1)*2.2;let next=.15,serial=0;c.players.forEach((p,i)=>{p.x=centers[i<2?0:1]+(i%2?1.1:-1.1);p.z=0;p.held=null;p.lock=0;});
 return {update(dt){if(c.time>=next){const type=c.int(0,2),lane=c.int(0,2);for(let t=0;t<2;t++)fruitList.push({id:serial++,t,type,lane,x:beltX(t,lane),z:lane===1?3.8:-3.8,holder:null,done:false});next=c.time+.5;}for(const f of fruitList)if(!f.done&&f.holder===null){f.z+=dt*(f.lane===1?-1.65:1.65);if(Math.abs(f.z)>4.25){f.done=true;if(f.lane===f.type)sum[f.t]++;}}for(const p of c.shuffle(c.players)){const t=p.i<2?0:1,j=p.i%2,allowed=j?[1,2]:[0,1],targetLane=p.held?(allowed.includes(p.held.type)?p.held.type:1):null;let target=p.held?{x:beltX(t,targetLane),z:p.z}:near(p,fruitList.filter(f=>!f.done&&f.holder===null&&f.t===t&&allowed.includes(f.lane)&&f.lane!==f.type));if(target){target={...target,x:clamp(target.x,centers[t]+(j?.45:-1.75),centers[t]+(j?1.75:-.45))};}const u=c.input(p,target?{...toward(p,target.x,target.z),a:dist(p,target)<.4&&tap(c,p,.3)&&c.time>p.lock}:{});p.x=clamp(p.x+u.x*dt*4,centers[t]+(j?.45:-1.75),centers[t]+(j?1.75:-.45));p.z=clamp(p.z+u.z*dt*4,-3.5,3.5);if(u.ap&&c.time>p.lock){if(p.held){const f=p.held,lane=allowed.sort((a,b)=>Math.abs(p.x-beltX(t,a))-Math.abs(p.x-beltX(t,b)))[0];f.holder=null;f.lane=lane;f.x=beltX(t,lane);f.z=p.z;p.held=null;p.lock=c.time+.4;}else{const f=near(p,fruitList.filter(f=>!f.done&&f.holder===null&&f.t===t&&allowed.includes(f.lane)));if(f&&dist(p,f)<1.3){p.held=f;f.holder=p.i;p.lock=c.time+.18;}}}if(p.held){p.held.x=p.x;p.held.z=p.z;}}scores(c,sum);c.hint('방향키 이동 · A 과일 집기/놓기. 왼쪽 바나나·가운데 사과·오른쪽 수박! 반대 끝 과일은 가운데 벨트로 동료에게 전달하세요.');},render(){c.arena({width:21,depth:13,color:'#c5b69a'});centers.forEach((x,t)=>{for(let lane=0;lane<3;lane++){box(c,`belt${t}-${lane}`,beltX(t,lane),0,'#758e90',.8,8.5,.1,.2);text(c,`arrow${t}-${lane}`,lane===1?'↑':'↓',beltX(t,lane),0,.35,1);fruit(c,`basket${t}-${lane}`,lane===0?1:lane===1?0:2,beltX(t,lane),lane===1?-4.8:4.8,.75,.4);}});fruitList.forEach(f=>{if(!f.done)fruit(c,'fruit'+f.id,f.type===0?1:f.type===1?0:2,f.x,f.z,.5,f.holder===null?.4:1.4);});},timeout(){finish(c,sum,'정확한 바구니에 넣은 과일 수');}};
};

const polygonArea=poly=>Math.abs(poly.reduce((s,p,i)=>{const q=poly[(i+1)%poly.length];return s+p.x*q.z-q.x*p.z;},0)/2);
function halfPolygon(poly,top,bottom){const side=p=>p.x-(top+(bottom-top)*(p.z+2.5)/5),out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],sa=side(a),sb=side(b);if(sa<=0)out.push(a);if((sa<0)!==(sb<0)){const t=sa/(sa-sb);out.push({x:a.x+(b.x-a.x)*t,z:a.z+(b.z-a.z)*t});}}return out;}
function inPoly(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.z>p.z)!==(b.z>p.z)&&p.x<(b.x-a.x)*(p.z-a.z)/(b.z-a.z)+a.x)inside=!inside;}return inside;}
games['Prime Cut']=(c)=>{
 init(c,35);let round=0,until=0,phase='cut',poly=[],median=0,result=[50,50];const blades=[[0,0],[0,0]],sum=[0,0];
 function next(){round++;phase='cut';until=c.time+10;poly=Array.from({length:12},(_,i)=>{const a=i*TAU/12,r=c.rand(.7,1.2);return {x:Math.cos(a)*2.5*r,z:Math.sin(a)*1.8*r};});let lo=-3,hi=3;for(let i=0;i<30;i++){const x=(lo+hi)/2;if(polygonArea(halfPolygon(poly,x,x))/polygonArea(poly)<.5)lo=x;else hi=x;}median=(lo+hi)/2;c.players.forEach(p=>p.cutError=c.rand(-.2,.2));blades.forEach(b=>{b[0]=c.rand(-2,2);b[1]=c.rand(-2,2);});}next();
 return {update(dt){for(const p of c.players){const t=p.i<2?0:1,j=p.i%2,u=c.input(p,{x:phase==='cut'?clamp((median+p.cutError-blades[t][j])*4,-1,1):0});if(phase==='cut')blades[t][j]=clamp(blades[t][j]+u.x*dt*2.2,-3.2,3.2);p.x=(t?4.7:-4.7)+blades[t][j];p.z=j?3.2:-3.2;}if(c.time>=until){if(phase==='cut'){result=blades.map(b=>polygonArea(halfPolygon(poly,b[0],b[1]))/polygonArea(poly)*100);const err=result.map(v=>Math.abs(50-v));if(Math.abs(err[0]-err[1])<.001){sum[0]++;sum[1]++;}else sum[err[0]<err[1]?0:1]++;scores(c,sum);phase='result';until=c.time+1.2;}else if(round===3)finish(c,sum,'세 번의 고기를 더 정확하게 반으로 잘랐습니다.',TEAM,[0,1,2,3]);else next();}c.hint(`${round}/3 · 두 팀원이 칼의 위·아래 끝을 ←/→로 움직이세요. 10초 뒤 자동으로 자릅니다. 면적이 50:50에 가까운 팀이 1점!`);},render(){c.arena({width:22,depth:12,color:'#b9af9c'});for(let t=0;t<2;t++){const cx=t?4.7:-4.7;box(c,'board'+t,cx,0,'#d6bd96',7.3,6,.1,.2);for(let ix=-13;ix<=13;ix++)for(let iz=-10;iz<=10;iz++){const p={x:ix*.23,z:iz*.23};if(inPoly(p,poly))box(c,`meat${t}-${ix}-${iz}`,cx+p.x,p.z,'#cc8e95',.24,.24,.3,.25);}segment(c,'knife'+t,{x:cx+blades[t][0],z:-2.5},{x:cx+blades[t][1],z:2.5},'#c8d2cf',.17,.7);if(phase==='result')text(c,'ratio'+t,`${result[t].toFixed(1)} : ${(100-result[t]).toFixed(1)}`,cx,0,2,5);}},timeout(){finish(c,sum,'세 번의 면적 반분 점수',TEAM,[0,1,2,3]);}};
};

games['Dorrie Pedal-Paddle']=(c)=>{
 init(c,180);c.view={size:22,eye:[0,18,21],target:[0,0,-2]};const boats=[{x:-3,z:0,angle:0,speed:0},{x:3,z:0,angle:0,speed:0}],buoys=Array.from({length:15},(_,i)=>({x:c.rand(-6,6),at:8+i*6}));let camera=0;c.players.forEach(p=>{p.angle=null;p.power=0;p.botAngle=p.phase;});const fish={x:0,at:48};
 return {update(dt){fish.x=Math.sin(c.time*1.7)*6;const raw=c.players.map(p=>{const t=p.i<2?0:1,j=p.i%2,b=boats[t],obstacle=buoys.find(q=>q.at>b.z&&q.at-b.z<9&&Math.abs(q.x-b.x)<2),target=obstacle?clamp(obstacle.x+(b.x>=obstacle.x?1:-1)*2.3,-6,6):Math.sin(b.z*.06)*2,desired=Math.atan2((target-b.x)*.15,1),delta=Math.atan2(Math.sin(desired-b.angle),Math.cos(desired-b.angle)),rate=clamp(6+(j?-1:1)*delta*10,1,10);p.botAngle+=rate*dt;const a=p.botAngle;return c.input(p,{x:Math.cos(a),z:Math.sin(a)});});c.players.forEach((p,i)=>{const u=raw[i];let rate=0;if(Math.hypot(u.x,u.z)>.4){const a=Math.atan2(u.z,u.x);if(p.angle!==null){const d=Math.abs(Math.atan2(Math.sin(a-p.angle),Math.cos(a-p.angle)));if(d<2)rate=d/dt;}p.angle=a;}else p.angle=null;p.power+=(Math.min(10,rate)-p.power)*Math.min(1,dt*3);});boats.forEach((b,t)=>{const left=c.players[t*2].power,right=c.players[t*2+1].power;b.angle=clamp(b.angle+(left-right)*dt*.09,-1.25,1.25);b.speed=(left+right)*.32;if(c.time<(b.stun||0))b.speed*=.2;b.x=clamp(b.x+Math.sin(b.angle)*b.speed*dt,-7,7);b.z+=Math.cos(b.angle)*b.speed*dt;for(const q of [...buoys,fish])if(Math.abs(q.at-b.z)<1&&Math.abs(q.x-b.x)<1.4&&c.time>(b.inv||0)){b.stun=c.time+.7;b.inv=c.time+1;b.x=clamp(b.x+Math.sign(b.x-q.x||1)*.6,-7,7);}TEAM[t].forEach((i,j)=>{c.players[i].score=b.z;c.players[i].x=b.x+(j?.6:-.6);c.players[i].z=3-(b.z-camera);c.players[i].rotation=-b.angle;});});camera=Math.max(0,Math.min(...boats.map(b=>b.z))-4);const done=boats.map((b,t)=>b.z>=105?t:-1).filter(t=>t>=0);if(done.length)c.complete(done.flatMap(t=>TEAM[t]),'두 페달을 맞춰 보트 경주를 완주했습니다.');c.hint('각자 방향 입력 원운동으로 페달. 왼쪽 선수가 빠르면 우회전, 오른쪽이 빠르면 좌회전! 부표와 움직이는 물고기를 피하세요.');},render(){c.arena({width:18,depth:28,color:'#8cbec8'});buoys.forEach((q,i)=>{const z=3-(q.at-camera);if(z>-16&&z<9)c.draw('buoy'+i,'cone',{x:q.x,y:.6,z,sx:1,sy:1.2,sz:1,color:'#e6bb66'});});const fz=3-(fish.at-camera);if(fz>-16&&fz<9)ball(c,'fish',fish.x,fz,'#d9949b',1.7,.9);boats.forEach((b,t)=>c.draw('boat'+t,'sphere',{x:b.x,y:.1,z:3-(b.z-camera),sx:2.2,sy:.65,sz:3,ry:-b.angle,color:PAL[t*2]}));},timeout(){c.complete([],'3분 안에 결승에 도달하지 못했습니다.');}};
};

const SHAPES=[
 [[0,0],[0,1],[0,2],[1,2]],[[0,0],[1,0],[2,0],[1,1]],[[0,0],[1,0],[1,1],[2,1]],[[0,0],[0,1],[1,1],[1,2]],
 [[0,0],[1,0],[2,0],[0,1],[2,1]],[[0,0],[1,0],[1,1],[0,2]],[[1,0],[0,1],[1,1],[2,1]],[[0,0],[0,1],[1,1],[2,1],[2,2]]
];
function shadowMask(role,index){return SHAPES[index].map(([x,z])=>`${role?4-x:x},${role?4-z:z}`);}
const joined=(a,b)=>[...new Set([...a,...b])].sort().join('|');
function shapeDraw(c,id,mask,x,z,size=.35,color='#40546b'){mask.forEach((v,i)=>{const [a,b]=v.split(',').map(Number);box(c,id+i,x+(a-2)*size,z+(b-2)*size,color,size*.95,size*.95,.22,.13);});}
games['Shadow Play']=(c)=>{
 init(c,83);let round=0,until=0,pause=0,goal='',answer=[0,0];const sum=[0,0];
 function next(){round++;until=c.time+15;pause=0;answer=[c.int(0,7),c.int(0,7)];goal=joined(shadowMask(0,answer[0]),shadowMask(1,answer[1]));c.players.forEach(p=>{p.shape=c.int(0,7);p.overlap=false;p.nav=0;p.errorUntil=0;});}next();
 return {update(){for(const p of c.players){const j=p.i%2,want=answer[j],dir=((want-p.shape+8)%8)<=4?1:-1,u=c.input(p,{x:!pause&&!p.overlap&&p.shape!==want?dir:0,a:!pause&&p.shape===want&&!p.overlap&&c.time>p.errorUntil+ p.phase});if(!pause){if(u.bp)p.overlap=false;if(!p.overlap&&Math.abs(u.x)>.5&&c.time>p.nav){p.shape=(p.shape+Math.sign(u.x)+8)%8;p.nav=c.time+.22;}if(u.ap&&!p.overlap){p.overlap=true;p.at=c.time;}}}if(!pause){const winners=[];for(let t=0;t<2;t++){const [a,b]=TEAM[t].map(i=>c.players[i]);if(a.overlap&&b.overlap&&c.time-Math.max(a.at,b.at)>.35){const actual=joined(shadowMask(0,a.shape),shadowMask(1,b.shape));if(actual===goal)winners.push(t);else{a.overlap=b.overlap=false;a.errorUntil=b.errorUntil=c.time+.5;}}}if(winners.length){if(winners.length===1)sum[winners[0]]++;scores(c,sum);pause=c.time+.8;}else if(c.time>=until)pause=c.time+.8;}else if(c.time>=pause){if(Math.max(...sum)>=3||round===5)finish(c,sum,'두 그림을 겹쳐 만든 그림자 점수');else next();}c.hint(`${round}/5 · ←/→ 8개 모양 회전 · A 겹치기 · B 빼기. 두 사람의 그림자를 합쳐 중앙 샘플과 같게 만드세요. 3점 선취!`);},render(){c.arena({width:23,depth:12,color:'#8991aa'});shapeDraw(c,'goal',goal.split('|'),0,-4.2,.6,'#384b61');text(c,'target','샘플',0,-6.2,1.5,3);for(let t=0;t<2;t++){const cx=t?5.5:-5.5;box(c,'screen'+t,cx,0,'#eee3bd',8.5,6,.1,.2);TEAM[t].forEach((i,j)=>{const p=c.players[i],x=cx+(p.overlap?0:j?2:-2);shapeDraw(c,'shape'+i,shadowMask(j,p.shape),x,0,.55,p.overlap?'#40546b':PAL[i]);text(c,'choice'+i,`${p.shape+1}/8 ${p.overlap?'겹침':''}`,cx+(j?2.2:-2.2),3.1,1.2,3,p.color);p.x=cx+(j?2.2:-2.2);p.z=4;});text(c,'score'+t,sum[t],cx,-4,2,3);}},timeout(){finish(c,sum,'그림자 맞추기 점수');}};
};

games['Match Makers']=(c)=>{
 init(c,180);const teams=[0,1].map(t=>({t,room:0,cards:[],memory:{},pause:0,done:false}));
 function setup(t){const count=5+t.room,pair=c.int(0,3),values=c.shuffle([pair,pair,...Array.from({length:count-2},(_,i)=>4+i)]);t.cards=values.map((value,i)=>({id:i,value,x:(t.t?4.7:-4.7)+(i%4-1.5)*1.5,z:Math.floor(i/4)*2-1,holder:null}));t.memory={};TEAM[t.t].forEach((i,j)=>{const p=c.players[i];p.held=null;p.x=(t.t?4.7:-4.7)+(j?1.5:-1.5);p.z=3;});}teams.forEach(setup);
 return {update(dt){for(const t of teams){if(t.done)continue;if(t.pause){TEAM[t.t].forEach(i=>c.input(c.players[i],{}));if(c.time>=t.pause){t.pause=0;setup(t);}continue;}for(const i of c.shuffle(TEAM[t.t])){const p=c.players[i],mate=c.players[TEAM[t.t].find(j=>j!==i)];const knownPair=t.cards.filter(q=>t.memory[q.id]!==undefined&&t.cards.some(o=>o!==q&&t.memory[o.id]===t.memory[q.id]));const assigned=knownPair.length?knownPair[p.i%2]:null;let target;if(!p.held){const known=mate.held?t.cards.find(q=>q.holder===null&&t.memory[q.id]===mate.held.value):null;target=(assigned?.holder===null?assigned:null)||known||near(p,t.cards.filter(q=>q.holder===null&&t.memory[q.id]===undefined))||near(p,t.cards.filter(q=>q.holder===null));}const drop=p.held&&c.time>p.picked+.8&&(assigned?p.held!==assigned:mate.held&&mate.held.value!==p.held.value),u=c.input(p,p.held?{a:drop&&tap(c,p,.35)}:target?{...toward(p,target.x,target.z),a:dist(p,target)<.5&&tap(c,p,.35)}:{});if(!p.held)c.move(p,u,4,false);p.x=clamp(p.x,(t.t?4.7:-4.7)-3.5,(t.t?4.7:-4.7)+3.5);p.z=clamp(p.z,-2.5,3.5);if(u.ap){if(p.held){p.held.holder=null;p.held=null;}else{const q=near(p,t.cards.filter(q=>q.holder===null));if(q&&dist(p,q)<.65){q.holder=p.i;p.held=q;p.picked=c.time;t.memory[q.id]=q.value;}}}}const [a,b]=TEAM[t.t].map(i=>c.players[i]);if(a.held&&b.held&&a.held!==b.held&&a.held.value===b.held.value){t.room++;TEAM[t.t].forEach(i=>c.players[i].score=t.room);if(t.room===4)t.done=true;else t.pause=c.time+.75;}}const done=teams.filter(t=>t.done);if(done.length)c.complete(done.flatMap(t=>TEAM[t.t]),'네 개의 방에서 같은 그림 카드 두 장을 찾았습니다.');c.hint('이동 · A 카드 들기/놓기. 들고 있을 때는 움직일 수 없습니다! 팀원과 같은 그림을 동시에 들면 다음 방으로 갑니다. 4개 방 탈출!');},render(){c.arena({width:22,depth:12,color:'#a9aaa1'});teams.forEach(t=>{const cx=t.t?4.7:-4.7;box(c,'wall'+t.t,cx,-3.2,'#869697',8,.6,1.5,3);text(c,'room'+t.t,`${Math.min(t.room+1,4)}/4층`,cx,-3,3.5,4);t.cards.forEach(q=>{box(c,`card${t.t}-${q.id}`,q.x,q.z,q.holder===null?'#c5ad87':'#f1deac',1.15,1.4,q.holder===null?.12:1.4,.1);if(q.holder!==null)text(c,`face${t.t}-${q.id}`,['새우','조개','별','물고기','잎','꽃','달','구름','돌','열매'][q.value],q.x,q.z,1.6,1.05);});});},timeout(){c.complete([],'3분 안에 네 방을 탈출하지 못했습니다.');}};
};

games['Tricky Turntable']=(c)=>{
 init(c,80);let round=0,until=0,phase='choose',items=[],rotation=0;const sum=[0,0];
 function payout(turn,t){const side=t===0?3:1;return items[(side-turn%4+4)%4];}
 function next(){round++;until=c.time+10;phase='choose';rotation=0;items=c.shuffle(round<=3?[1,2,3,-1]:[1,3,5,-1]);c.players.forEach(p=>{p.pressed=false;p.decide=c.time+c.rand(2,7);p.changed=false;});}next();
 return {update(){const count=c.players.filter(p=>p.pressed).length;for(const p of c.players){const t=p.i<2?0:1,current=count,changed=count+(p.pressed?-1:1),better=payout(changed,t)-payout(changed,1-t)*.3>payout(current,t)-payout(current,1-t)*.3;const u=c.input(p,{a:phase==='choose'&&!p.changed&&c.time>p.decide&&better});if(u.ap&&phase==='choose'){p.pressed=!p.pressed;p.changed=true;}}if(c.time>=until){if(phase==='choose'){rotation=c.players.filter(p=>p.pressed).length;for(let t=0;t<2;t++)sum[t]=Math.max(0,sum[t]+payout(rotation,t));scores(c,sum);phase='result';until=c.time+1;}else if(round===7){c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'각 팀이 회전판에서 얻은 코인을 받습니다.');}else next();}c.hint(`${round}/7 · A로 버튼 올라가기/내려가기. 눌린 버튼 하나당 시계방향 90° 회전! 내 팀 앞의 코인을 받고 폭탄이면 1코인 잃습니다.`);},render(){c.arena({color:'#bdb095'});c.draw('cog','cylinder',{x:0,y:.1,z:0,sx:8,sy:.3,sz:8,color:'#92a6a8'});items.forEach((n,i)=>{const a=(i+rotation)*Math.PI/2-Math.PI/2,x=Math.cos(a)*3,z=Math.sin(a)*3;box(c,'pedestal'+i,x,z,'#ccb886',1.6,1.6,.35,.45);if(n<0)ball(c,'bomb'+i,x,z,'#435566',.7,.9);else{ball(c,'coin'+i,x,z,'#e5c359',.5,.8);text(c,'value'+i,n,x,z,1.5,1.3);}});c.players.forEach(p=>{p.x=p.i<2?-6.3:6.3;p.z=p.i%2?1.7:-1.7;box(c,'button'+p.i,p.x,p.z,p.pressed?p.color:'#8f9891',1.3,1.3,p.pressed?.02:.15,.2);p.y=p.pressed?.2:.45;});},timeout(){coinFinish(c,'팀별 획득 코인을 받습니다.');}};
};

export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['jamboree']]));
export const notes={
 'Lumber Tumble':'점프 없는 미로 다리 이동, 통나무 밀림, 후반 가시 통나무의 다리 파괴와 생존·완주를 구현했습니다. 다리와 통나무 배치는 새로 제작했습니다.',
 'Big-Top Quiz':'3라운드의 서로 다른 공 이동과 질문을 사용합니다. 첫 문제는 그림 수 비교이며 이후 손 흔든 새·나오지 않은 그림을 묻고 정답 순서에 따라 5·3·2·1점입니다.',
 'Camera-Ready':'사진틀 이동·확대·축소·한 번 촬영과 피사체 타이밍을 구현했습니다. 30초씩 세 라운드이며 새로 만든 피사체와 샘플의 구도 차이를 점수로 계산합니다.',
 'Hot Cross Blocks':'10초 선택, 중복 선택 무효, 기존 경로에 연결되지 않은 블록 침몰과 5분 무승부를 적용했습니다. 블록 모양과 통로 배치는 새로 제작했습니다.',
 'Thwomp the Difference':'5라운드, 3라운드부터 4개 그림, 가림막의 완전·부분 개방과 정답 순서 5·3·2·1점을 적용했습니다.',
 'Tiny Triathlon':'수영은 좌우 교대, 자전거는 방향 원운동, 허들은 A 점프로 모션 동작을 대체했습니다. 세 구간을 연속으로 완주하며 허들 충돌은 일시 정지입니다.',
 'Rinks to Riches':'얼음 관성, 작은 눈덩이 감속, 큰 눈덩이 3회 충돌과 안의 빨간 3코인을 적용했습니다. 각자 획득 코인을 받는 코인 경기입니다.',
 'Treetop Treasure':'무게로 기울어지는 두 시소, 점프·선수 밟기 추가 도약, 낙사 후 구조 지연과 일반 1·빨강 3코인을 구현했습니다.',
 'Sunset Standoff':'다섯 번의 비행 돌진 동안 1P는 좌우 조종하고 세 명은 좁은 활주로에서 회피합니다. 한 명이라도 끝까지 남으면 팀 승리입니다.',
 'Cookie Cutters':'3×3 반죽의 표시된 칸을 순서대로 찍습니다. 1P는 A/B/C로 세 모양을 맡고 2~4P는 각자 정해진 모양을 A로 찍습니다. 잘못된 모양은 득점 없이 다음 칸으로 갑니다.',
 'Unfriendly Flying Object':'횡스크롤 공간의 낙하·쌓이는 가시판과 점프 회피를 구현했습니다. 가시 접촉뿐 아니라 낙하 압착·벽 끼임도 탈락입니다. 판 크기와 낙하 물리는 새로 제작했습니다.',
 'Lost and Pound':'숨기기와 공격 선택을 각각 10초 동안 비밀로 진행합니다. 4개 구멍, 목숨 3개와 최대 3라운드 규칙입니다.',
 'Arch Rivals':'공격자는 자동 왕복 발판 위에서 A로만 발사합니다. 팀의 과녁 기울이기는 좌우 입력으로 바꿨으며 가장자리 10·중간 20·중앙 30점, 30초 내 100점을 적용했습니다.',
 'On-Again, Off-Again':'한 명의 스위치가 상하 발판을 전환해 쌓인 바위를 떨어뜨립니다. 세 명은 이동과 점프로 30초를 버팁니다.',
 'Broozer Bash':'A 전진·펀치, B/C 좌우 회전으로 로봇을 조종합니다. 일반 이동형 공격과 달리 방향을 먼저 돌려야 전진하는 규칙입니다.',
 'Cage Catch':'1P 이동·A 연타 빠른 수영, 2P 세로, 3P 가로, 4P 낙하로 역할을 나눴습니다. 물고기 기절과 우리 재상승 지연을 적용했습니다.',
 'Income Stream':'큰 탈것의 강한 밀치기, 세 작은 탈것의 분산 이동, 수로 이탈 후 2초 복귀와 총 33코인 경주입니다. 기울이기는 방향 입력으로 바꿨습니다.',
 'Squeaky Shakedown':'팀원 각각 7코인에서 시작하고 망치 적중마다 1코인을 공격수에게 옮깁니다. 0코인이면 멈추며 종료 때 각자 남은 코인을 받습니다.',
 'Rocky Rope Race':'A 유지로 봉 잡기, 놓아서 동료를 축으로 스윙, 다음 봉에서 다시 잡기를 구현했습니다. 둘 다 놓으면 구조 대기, 3분 미완주면 무승부입니다.',
 "Pickin' Produce":'가운데 벨트는 위로, 양끝 벨트는 아래로 움직입니다. 각 선수는 인접한 두 벨트만 접근하며 가운데 벨트로 상대편 과일을 전달해야 합니다.',
 'Prime Cut':'두 선수가 칼의 양 끝을 좌우로 조절합니다. 실제 불규칙 다각형을 칼의 직선으로 분할해 면적을 계산하며 10초씩 3라운드를 비교합니다.',
 'Dorrie Pedal-Paddle':'두 사람의 방향 원운동을 각 페달에 연결했습니다. 좌우 속도 차로 회전하고 부표·움직이는 장애물에 부딪히면 느려집니다. 3분 제한입니다.',
 'Shadow Play':'각자 8개 도형 중 하나를 골라 A로 겹치고 B로 뺍니다. 실제 두 도형의 합집합을 샘플과 비교하며 오답은 원위치, 15초씩 최대 5라운드·3점 선취입니다.',
 'Match Makers':'카드를 들었을 때만 그림을 공개하며 들고 있으면 이동이 금지됩니다. CPU도 공개된 카드만 기억합니다. 5·6·7·8장 방을 순서대로 통과하며 3분 제한입니다.',
 'Tricky Turntable':'눌린 버튼마다 시계방향 90° 회전하고 양 팀 앞의 보상을 받습니다. 10초씩 7라운드, 폭탄은 1코인 감소입니다. 코인 배치는 최대 획득량 29에 맞춰 새로 구성했습니다.'
};
