import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,cream='#f2dfb8',col=['#d88dad','#81add0'],pulse=(t,f=4,o=0)=>(t*f+o)%1<.4;
const team=p=>Math.floor(p.i/2),members=t=>[t*2,t*2+1],score=(c,t)=>c.players[t*2].score+c.players[t*2+1].score;
const text=(c,id,s,x=0,y=5,z=0,sx=9)=>c.draw(id,'text',{x,y,z,sx,sy:.7,text:s});
const won=(c,reason,both=false)=>{const a=score(c,0),b=score(c,1);c.complete(a===b?(both?[0,1,2,3]:[]):members(a>b?0:1),reason);};
const add=(c,t,n=1)=>c.points(c.players[t*2],n);
const held=q=>q.a||q.pointer.down,press=q=>q.ap||q.pointer.pressed;
function init(c,limit=60){c.limit=limit;c.bounds={x:15,z:9};c.view={size:35,eye:[0,30,22],target:[0,0,0]};c.players.forEach(p=>{p.x=(team(p)?8:-8)+(p.i%2?2:-2);p.z=6;p.phase=c.rand(0,1);p.lag=c.rand(.16,.38);p.cool=0;p.cursorSkill=c.rand(.55,.85);});}
function cursor(c,p,bot,dt,bounds={x:15,z:9}){const q=c.input(p,bot);if(q.pointer.valid){const at=c.pointerProject?.(q.pointer,p)??(q.pointer.worldValid?{x:q.pointer.worldX,z:q.pointer.worldZ}:{x:(q.pointer.x-.5)*32,z:(q.pointer.y-.5)*20});const pointerSpeed=c.pointerSpeed??c.cursorSpeed;if(pointerSpeed){p.x+=clamp(at.x-p.x,-pointerSpeed*dt,pointerSpeed*dt);p.z+=clamp(at.z-p.z,-pointerSpeed*dt,pointerSpeed*dt);}else{p.x=at.x;p.z=at.z;}}else {const move=p.i>=c.humans?{...q,x:q.x*p.cursorSkill,z:q.z*p.cursorSkill}:q;c.move(p,move,c.cursorSpeed||12,false);}p.x=clamp(p.x,-bounds.x,bounds.x);p.z=clamp(p.z,-bounds.z,bounds.z);return q;}
function aiming(p,o,button=false){return{...toward(p,o.x,o.z,Math.min(1,dist(p,o)*2)),a:button};}
function arena(c){c.arena({width:33,depth:21,color:'#b8c5b8'});c.draw('divider','box',{x:0,y:.02,z:0,sx:.12,sy:.04,sz:20,color:cream});}
function shell(c){init(c,60);c.bounds={x:13,z:7};const pucks=[{x:0,z:0,vx:8,vz:3}],goals=[0,0];let extra=false;c.players.forEach(p=>{p.x=team(p)?7:-7;p.z=p.i%2?3:-3;});function puck(o,dt){if(!o.waiting){o.x+=o.vx*dt;o.z+=o.vz*dt;}if(Math.abs(o.z)>7.6){o.z=clamp(o.z,-7.6,7.6);o.vz*=-1;}for(const p of c.players){const d=dist(o,p);if(d<1.35){o.waiting=false;const nx=(o.x-p.x)/(d||1),nz=(o.z-p.z)/(d||1);o.x=p.x+nx*1.36;o.z=p.z+nz*1.36;const v=Math.max(8,Math.min(16,Math.hypot(o.vx,o.vz)+1));o.vx=nx*v;o.vz=nz*v;}}if(Math.abs(o.x)>14){if(Math.abs(o.z)<3.7){add(c,o.x>0?0:1);o.x=o.z=0;o.vx=c.pick([-1,1])*8;o.vz=c.rand(-5,5);}else{o.x=clamp(o.x,-14,14);o.vx*=-1;}}}
 return{update(dt){c.hint('방향키 또는 포인터로 패들 이동 / 상대 골에 등껍질 넣기 / 마지막20초에 등껍질4개 추가');if(!extra&&c.time>=40){extra=true;for(let i=0;i<4;i++)pucks.push({x:(i%2?1:-1)*3,z:i<2?-5:5,vx:0,vz:0,waiting:true});}for(const p of c.players){const t=team(p),nearest=pucks.filter(o=>(t?o.x> -2:o.x<2)).sort((a,b)=>dist(a,p)-dist(b,p))[0]||pucks[0],target={x:nearest.x+(t?1:-1),z:nearest.z};cursor(c,p,()=>aiming(p,target),dt,{x:13,z:7});p.x=t?clamp(p.x,.7,13):clamp(p.x,-13,-.7);}pucks.forEach(o=>puck(o,dt));},render(){c.arena({width:30,depth:17,color:'#9ec2ca'});for(let t=0;t<2;t++)c.draw('goal'+t,'box',{x:t?14.5:-14.5,y:.2,z:0,sx:.6,sy:.4,sz:7.5,color:col[t]});pucks.forEach((o,i)=>c.draw('puck'+i,'sphere',{x:o.x,y:.3,z:o.z,sx:1,sy:o.waiting?1.1:.6,sz:1,color:o.waiting?'#9fb99a':'#b0a6c7'}));},timeout(){won(c,'60초 동안 넣은 골 합계');}};}
function filter(c){init(c,180);const data=[0,1].map(t=>({items:Array.from({length:30},(_,i)=>({id:i,kind:i<20?c.int(0,1):2,x:(t?8:-8)+c.rand(-5,5),z:c.rand(-5,2),holder:null,done:false})),count:0}));const bin=(t,k)=>({x:(t?8:-8)+(k-1)*4,z:7});c.players.forEach(p=>p.grab=null);
 return{update(dt){c.hint('A/포인터 누른 채 편지 끌기, 놓아 분류 / 일반:노랑 · 악당:보라 쓰레기 · 하트:분홍');const finished=[];for(const p of c.players){const t=team(p),d=data[t],obj=p.grab??d.items.filter(o=>!o.done&&o.holder==null&&(o.kind!==2||d.count>=12)).sort((a,b)=>dist(a,p)-dist(b,p))[0],dest=p.grab?bin(t,obj.kind):obj||p;const q=cursor(c,p,()=>aiming(p,dest,!!obj&&(p.grab?dist(p,dest)>.35:dist(p,obj)<.65)),dt);if(!p.grab&&press(q)&&obj&&dist(p,obj)<.9){p.grab=obj;obj.holder=p.i;}if(p.grab){const o=p.grab;o.x=p.x;o.z=p.z;if(!held(q)){const k=[0,1,2].find(k=>dist(p,bin(t,k))<1.5);if(k===o.kind){o.done=true;d.count++;c.points(p);}else{o.x=(t?8:-8)+c.rand(-4,4);o.z=c.rand(-4,1);}o.holder=null;p.grab=null;}}}for(let t=0;t<2;t++)if(data[t].count===30)finished.push(...members(t));if(finished.length)c.complete(finished,'편지를 모두 올바르게 분류했습니다');},render(){arena(c);data.forEach((d,t)=>{for(let k=0;k<3;k++){const b=bin(t,k);c.draw('bin'+t+k,'box',{...b,y:.2,sx:3,sy:.4,sz:2.5,color:['#d8c58b','#9890af','#d497b0'][k]});text(c,'bintext'+t+k,['일반','악당','하트'][k],b.x,1,b.z,2.5);}d.items.filter(o=>!o.done&&(o.kind!==2||d.count>=12)).forEach(o=>c.draw('mail'+t+'-'+o.id,'box',{x:o.x,y:.35,z:o.z,sx:.8,sy:.16,sz:.55,color:['#d8c58b','#9890af','#d497b0'][o.kind]}));});},timeout(){won(c,'분류한 편지 수 비교');}};}
function stack(c){init(c,45);c.pointerProject=(q,p)=>q.frontValid&&(p.grab||q.worldZ<2.5)?{x:q.frontX,z:-(q.frontY-(p.grab?1:0))*.7}:q.worldValid?{x:q.worldX,z:q.worldZ+.6*35/12}:null;c.view={size:38,eye:[0,17,35],target:[0,5,0]};let serial=0;const data=[0,1].map(t=>({pieces:[],batch:0}));function batch(t){const d=data[t];for(let i=0;i<5;i++){const kind=c.int(0,4);d.pieces.push({id:serial++,x:(t?8:-8)+(i-2)*2,z:5,y:.6,w:[1.2,1.8,2.4,1.6,3][kind],h:[1.1,1,1.6,1.3,2.1][kind],kind,used:false,holder:null,vy:0,vx:0});}d.batch++;}batch(0);batch(1);c.players.forEach(p=>p.grab=null);
 return{update(dt){c.hint('A/포인터로 인형 잡아 이동, 놓아 쌓기 / 방향 위아래로 높이 조절 · B 회전 / 5개를 모두 써야 새 묶음');for(const p of c.players){const t=team(p),d=data[t],obj=p.grab||d.pieces.find(o=>!o.used&&o.holder==null),top=Math.max(0,...d.pieces.filter(o=>o.used&&o.holder==null&&Math.abs(o.x-(t?8:-8))<3).map(o=>o.y+o.h/2));const dest=p.grab?{x:(t?8:-8)+Math.sin(p.phase*9)*.2,z:-Math.min(8,top*.7+1)}:obj||p;const q=cursor(c,p,()=>aiming(p,dest,!!obj&&(p.grab?dist(p,dest)>.35:dist(p,obj)<.7)),dt);if(!p.grab&&press(q)){const hit=d.pieces.filter(o=>o.holder==null&&Math.abs(o.x-p.x)<1&&Math.abs((o.used?-o.y*.7:o.z)-p.z)<1.6).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];if(hit){p.grab=hit;hit.holder=p.i;hit.used=true;}}if(p.grab){const o=p.grab;o.x=p.x;o.z=0;o.y=clamp(-p.z/ .7+1,1,18);if(q.bp)[o.w,o.h]=[o.h,o.w];if(!held(q)){o.holder=null;o.vy=0;p.grab=null;}}}for(let t=0;t<2;t++){const d=data[t];const sorted=d.pieces.filter(o=>o.used&&o.holder==null).sort((a,b)=>a.y-b.y);for(const o of sorted){const old=o.y;o.vy-=12*dt;o.y+=o.vy*dt;o.x+=o.vx*dt;let floor=o.h/2,support=null;for(const b of sorted){if(b===o||b.y>=old||Math.abs(o.x-b.x)> (o.w+b.w)/2-.12)continue;const top=b.y+b.h/2+o.h/2;if(old>=top-.05&&o.y<=top){floor=Math.max(floor,top);support=b;}}if(o.y<floor){o.y=floor;o.vy=0;if(support&&Math.abs(o.x-support.x)>support.w*.43)o.vx+=Math.sign(o.x-support.x)*3*dt;else o.vx*=.8;}}if(d.pieces.every(o=>o.used))batch(t);const height=Math.max(0,...sorted.filter(o=>Math.abs(o.x-(t?8:-8))<5&&o.vy===0).map(o=>o.y+o.h/2));c.players[t*2].score=Math.round(height*100)/100;}},render(){arena(c);data.forEach((d,t)=>d.pieces.forEach(o=>c.draw('stuff'+o.id,o.kind===1?'sphere':o.kind===3?'cone':'box',{x:o.x,y:o.y,z:o.used?0:o.z,sx:o.w,sy:o.h,sz:1.6,color:['#c6a3bd','#a4bda3','#e3c786','#9dbbd0','#aca5c7'][o.kind]})));},timeout(){won(c,'종료 시 서 있는 인형 탑의 높이');}};}
function pullback(c){init(c,60);c.bounds={x:14,z:7};c.players.forEach(p=>{p.x=team(p)?12:-12;p.z=(p.i%2?1:-1)*3;p.vx=p.vz=0;p.power=0;p.flip=0;p.dir=team(p)?Math.PI:0;p.drivePower=c.rand(1.2,1.58);});const stompers=[{x:-4,z:-2},{x:4,z:2}];function reset(p){p.x=team(p)?12:-12;p.z=(p.i%2?1:-1)*3;p.vx=p.vz=0;p.power=0;}
 return{update(dt){c.hint('방향으로 조준 · A 누른 채 당겨 충전, 놓아 출발 · 전복 시 B 반복 / 압착기와 물 조심');for(const p of c.players){const t=team(p),moving=Math.hypot(p.vx,p.vz)>.15,q=c.input(p,()=>({x:t?-1:1,z:-Math.sign(p.z)*.25,a:!moving&&!p.flip&&p.power<p.drivePower,b:p.flip>0&&pulse(c.time,4,p.phase)}));if(p.flip){if(q.bp)p.flip--;if(!p.flip)p.power=0;continue;}if(!moving){if(q.pointer.valid){p.dir=Math.atan2((q.pointer.worldValid?q.pointer.worldZ:(q.pointer.y-.5)*16)-p.z,(q.pointer.worldValid?q.pointer.worldX:(q.pointer.x-.5)*30)-p.x);}else if(q.x||q.z)p.dir=Math.atan2(q.z,q.x);if(held(q))p.power=Math.min(1.6,p.power+dt);else if(p.power){const v=6+p.power*13;p.vx=Math.cos(p.dir)*v;p.vz=Math.sin(p.dir)*v;p.power=0;}}p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-1.05*dt);p.vz*=Math.exp(-1.05*dt);if(Math.abs(p.z)>8)reset(p);else if(t?p.x<-14:p.x>14){c.points(p);reset(p);}else if(stompers.some((o,i)=>dist(p,o)<1.7&&((c.time+i*1.2)%3)<.55))reset(p);}for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=c.players[i],b=c.players[j],d=dist(a,b);if(d<1.1){const relative=Math.hypot(a.vx-b.vx,a.vz-b.vz);[a.vx,b.vx]=[b.vx,a.vx];[a.vz,b.vz]=[b.vz,a.vz];const nx=(a.x-b.x)/(d||1),nz=(a.z-b.z)/(d||1);a.x+=nx*.12;b.x-=nx*.12;a.z+=nz*.12;b.z-=nz*.12;if(relative>18){a.flip=b.flip=3;a.vx=a.vz=b.vx=b.vz=0;}}}},render(){c.arena({width:30,depth:16,color:'#b5c1a7'});for(let i=0;i<2;i++){const o=stompers[i],down=(c.time+i*1.2)%3<.55;c.draw('stomp'+i,'box',{x:o.x,y:down?.7:4,z:o.z,sx:2.8,sy:1.4,sz:2.8,color:'#9fabc0'});}c.players.forEach(p=>c.draw('car'+p.i,'box',{x:p.x,y:.2,z:p.z,sx:1.6,sy:.4,sz:1,color:p.color,ry:-p.dir,rz:p.flip?Math.PI:0}));},timeout(){won(c,'상대 골에 도달한 횟수');}};}
function domino(c){init(c,180);const data=[0,1].map(t=>({pieces:Array.from({length:22},(_,i)=>({id:i,x:(t?8:-8)+4+(i%2)*.5,z:6-Math.floor(i/2)*.25,placed:false,holder:null})),chain:null}));c.players.forEach(p=>p.grab=null);const start=t=>({x:t?8:-8,z:6}),end=t=>({x:t?8:-8,z:-6}),danger=t=>({x:(t?8:-8)+Math.sin(c.time*.8+t)*2.7,z:0});
 function chainPath(t){const d=data[t],seen=new Set(),path=[];let pos=start(t);for(let n=0;n<22;n++){const o=d.pieces.filter(o=>o.placed&&o.holder==null&&!seen.has(o.id)&&dist(o,pos)<1.45).sort((a,b)=>dist(a,end(t))-dist(b,end(t)))[0];if(!o)break;seen.add(o.id);path.push(o);pos=o;if(dist(pos,end(t))<1.5)return{path,success:true};}return{path,success:false};}
 return{update(dt){c.hint('A/포인터로 도미노 끌어 배치 / 시작 인물을 눌러 연쇄 / 움직이는 장애물에 닿은 첫 도미노는 제거');const finished=[];for(const p of c.players){const t=team(p),d=data[t];if(d.chain){c.input(p,{});continue;}const positions=Array.from({length:10},(_,i)=>({x:t?8:-8,z:4.9-i*1.1})),target=positions.find(o=>!d.pieces.some(b=>b.placed&&dist(o,b)<.6)),obj=p.grab||d.pieces.find(o=>!o.placed&&o.holder==null),dest=p.grab?(target||end(t)):target?(obj||p):start(t);const q=cursor(c,p,()=>aiming(p,dest,target?!!obj&&(p.grab?dist(p,dest)>.3:dist(p,obj)<.6):dist(p,dest)<.4&&pulse(c.time,2,p.phase)),dt);if(!p.grab&&press(q)){if(dist(p,start(t))<.75){const chain=chainPath(t);d.chain={...chain,age:0};}else{const o=d.pieces.filter(o=>o.holder==null&&dist(o,p)<.8).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(o){p.grab=o;o.holder=p.i;}}}if(p.grab){p.grab.x=p.x;p.grab.z=p.z;if(!held(q)){p.grab.placed=true;p.grab.holder=null;p.grab=null;}}}for(let t=0;t<2;t++){const d=data[t];if(d.chain){d.chain.age+=dt;if(d.chain.age>=d.chain.path.length*.13+.2){if(d.chain.success)finished.push(...members(t));else if(d.chain.path.length)d.pieces=d.pieces.filter(o=>o!==d.chain.path[0]);d.chain=null;}}else{const hit=d.pieces.find(o=>o.placed&&o.holder==null&&dist(o,danger(t))<.55);if(hit)d.pieces=d.pieces.filter(o=>o!==hit);}c.players[t*2].score=d.pieces.filter(o=>o.placed).length;}if(finished.length)c.complete(finished,'도미노 연쇄가 화분까지 도달했습니다');},render(){arena(c);data.forEach((d,t)=>{for(const [name,o]of[['start',start(t)],['pot',end(t)]]){c.draw(name+t,'cylinder',{...o,y:.5,sx:1,sy:1,sz:1,color:name==='pot'?'#a9bf8f':col[t]});}d.pieces.forEach(o=>{const index=d.chain?.path.indexOf(o)??-1,fallen=index>=0&&d.chain.age>index*.13;c.draw('domino'+t+'-'+o.id,'box',{x:o.x,y:fallen?.2:.65,z:o.z,sx:.65,sy:fallen?.2:1.3,sz:fallen?1.3:.3,color:col[t]});});c.draw('danger'+t,'sphere',{...danger(t),y:.6,sx:1,sy:1.2,sz:1,color:'#ac9a82'});});},timeout(){c.complete([],'어느 팀도 화분까지 연결하지 못했습니다');}};}
function makeover(c){init(c,18);let round=0,age=0,pause=.4,bombs=[];function setup(){const n=[5,7,3][round];bombs=Array.from({length:n},(_,i)=>({x:(i-(n-1)/2)*3,z:0,r:round===2&&i===1?2:1.05,value:round===2&&i===1?3:1,paint:[0,0],incoming:[0,0]}));c.players.forEach(p=>p.ink=1);}setup();
 return{update(dt){c.hint(`라운드 ${round+1}/3 · A/포인터 누르고 분사, B 반복으로 잉크 채우기 / 마지막 큰 폭탄 3점`);if(pause){pause=Math.max(0,pause-dt);c.players.forEach(p=>c.input(p,{}));return;}age+=dt;for(const b of bombs)b.incoming=[0,0];for(const p of c.players){const t=team(p),b=bombs.map((b,i)=>({b,i})).sort((a,b)=>(a.b.paint[t]-a.b.paint[1-t])/a.b.value-(b.b.paint[t]-b.b.paint[1-t])/b.b.value)[p.i%2%(bombs.length)]?.b||bombs[0];const q=cursor(c,p,()=>({...aiming(p,b,p.ink>.1),b:p.ink<.45&&pulse(c.time,5,p.phase)}),dt);if(q.bp)p.ink=Math.min(1,p.ink+.34);if(held(q)&&p.ink>0){const hit=bombs.find(o=>dist(p,o)<o.r);p.ink=Math.max(0,p.ink-dt*.4);if(hit){hit.incoming[t]+=dt;}}}for(const b of bombs){b.paint=b.paint.map((v,t)=>Math.max(0,v+b.incoming[t]-b.incoming[1-t]*.6));}if(age>=5){for(const b of bombs)if(Math.abs(b.paint[0]-b.paint[1])>.00001)add(c,b.paint[0]>b.paint[1]?0:1,b.value);round++;if(round===3)won(c,'각 폭탄의 다수 색 점수 합계');else{age=0;pause=.6;setup();}}},render(){arena(c);bombs.forEach((b,i)=>{const t=b.paint[0]===b.paint[1]?-1:b.paint[0]>b.paint[1]?0:1;c.draw('bomb'+i,'sphere',{x:b.x,y:b.r,z:b.z,sx:b.r*2,sy:b.r*2,sz:b.r*2,color:t<0?'#9d99ac':col[t]});text(c,'paint'+i,`${b.value}점`,b.x,b.r*2+.8,b.z,2);});c.players.forEach(p=>text(c,'ink'+p.i,Math.round(p.ink*100)+'%',p.x,3,p.z,2));},timeout(){won(c,'도색한 폭탄 점수 합계');}};}
const segDistance=(p,a,b)=>{const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((p.x-a.x)*dx+(p.z-a.z)*dz)/(dx*dx+dz*dz||1),0,1);return Math.hypot(p.x-a.x-dx*t,p.z-a.z-dz*t);};
function electric(c){init(c,180);c.cursorSpeed=4;const paths=[0,1].map(t=>{const x=t?8:-8;return[{x:x-3,z:7},{x:x-3,z:2},{x:x+3,z:2},{x:x+3,z:-2},{x:x-3,z:-2},{x:x-3,z:-7}];});c.players.forEach(p=>{const path=paths[team(p)];p.x=path[0].x;p.z=path[0].z+(p.i%2? .6:0);p.step=1;p.checkpoint=0;p.done=false;p.retry=0;});
 return{update(dt){c.hint('A/포인터를 누른 채 새를 운반 / 전기 벽에 닿으면 체크포인트로 / 둘 다 출구에 먼저 보내기');for(const p of c.players){const path=paths[team(p)];p.retry=Math.max(0,p.retry-dt);const goal=path[Math.min(p.step,5)],old={x:p.x,z:p.z},q=cursor(c,p,()=>({...aiming(p,goal,true)}),dt);if(!held(q)||p.done||p.retry){p.x=old.x;p.z=old.z;}const d=Math.min(...path.slice(1).map((b,i)=>segDistance(p,path[i],b)));if(d>.88){p.x=path[p.checkpoint].x;p.z=path[p.checkpoint].z;p.step=p.checkpoint+1;p.retry=.5;}else if(dist(p,goal)<.45){p.step=Math.min(6,p.step+1);if(p.step===4)p.checkpoint=3;if(p.step===6)p.done=true;}p.score=p.done?6:p.step-1;}for(let t=0;t<2;t++){const a=c.players[t*2],b=c.players[t*2+1];if(!a.done&&!b.done&&dist(a,b)<.45){const dx=(a.x-b.x)||.05,dz=(a.z-b.z)||.05;a.x+=dx*.2;b.x-=dx*.2;a.z+=dz*.2;b.z-=dz*.2;}}const finish=[0,1].filter(t=>members(t).every(i=>c.players[i].done));if(finish.length)c.complete(finish.flatMap(members),'두 선수가 전기 미로 출구에 도착했습니다');},render(){c.arena({width:33,depth:21,color:'#868ba8'});paths.forEach((path,t)=>path.slice(1).forEach((b,i)=>{const a=path[i];c.draw('corridor'+t+i,'box',{x:(a.x+b.x)/2,y:.04,z:(a.z+b.z)/2,sx:Math.abs(a.x-b.x)+1.8,sy:.08,sz:Math.abs(a.z-b.z)+1.8,color:'#c6d2c7'});if(i===2||i===4)c.draw('checkpoint'+t+i,'cylinder',{x:b.x,y:.11,z:b.z,sx:1.6,sy:.15,sz:1.6,color:i===4?'#e2c777':'#a0bd9c'});}));},timeout(){c.complete([],'두 선수를 모두 구출한 팀이 없습니다');}};}
function ice(c){init(c,48);let round=0,age=0,pause=.5,balloons=[];function setup(){balloons=Array.from({length:25},(_,i)=>({x:c.rand(-11,11),z:c.rand(-6,5),gold:round===2&&i===0,alive:true}));c.players.forEach(p=>{p.x=(p.i-1.5)*7;p.z=8;p.vx=p.vz=0;p.power=0;p.angle=-Math.PI/2;});}setup();
 return{update(dt){c.hint(`얼음 라운드 ${round+1}/3 · 방향 조준, A/포인터 누른 뒤 놓아 튜브 밀기 / 황금 풍선 3점`);if(pause){pause=Math.max(0,pause-dt);c.players.forEach(p=>c.input(p,{}));return;}age+=dt;for(const p of c.players){const target=balloons.filter(b=>b.alive).sort((a,b)=>dist(p,a)-dist(p,b))[0]||{x:0,z:0},speed=Math.hypot(p.vx,p.vz),q=c.input(p,()=>({...toward(p,target),a:speed<.5&&p.power<.8}));if(speed<.5){if(q.pointer.valid)p.angle=Math.atan2((q.pointer.worldValid?q.pointer.worldZ:(q.pointer.y-.5)*20)-p.z,(q.pointer.worldValid?q.pointer.worldX:(q.pointer.x-.5)*32)-p.x);else if(q.x||q.z)p.angle=Math.atan2(q.z,q.x);if(held(q))p.power=Math.min(1.5,p.power+dt);else if(p.power){p.vx=Math.cos(p.angle)*(5+p.power*10);p.vz=Math.sin(p.angle)*(5+p.power*10);p.power=0;}}p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-.8*dt);p.vz*=Math.exp(-.8*dt);if(Math.abs(p.x)>14){p.x=clamp(p.x,-14,14);p.vx*=-.65;}if(Math.abs(p.z)>8){p.z=clamp(p.z,-8,8);p.vz*=-.65;}for(const b of balloons)if(b.alive&&dist(p,b)<1){b.alive=false;c.points(p,b.gold?3:1);}}if(age>=15){round++;if(round===3)won(c,'세 라운드의 풍선 점수');else{age=0;pause=.5;setup();}}},render(){c.arena({width:30,depth:18,color:'#aac9d3'});balloons.forEach((b,i)=>{if(b.alive)c.draw('balloon'+i,'sphere',{x:b.x,y:.9,z:b.z,sx:1,sy:1.4,sz:1,color:b.gold?'#e1c365':'#ca9ebc'});});c.players.forEach(p=>c.draw('tube'+p.i,'ring',{x:p.x,y:.25,z:p.z,sx:2,sy:2,sz:5,rx:-Math.PI/2,color:p.color}));},timeout(){won(c,'세 라운드의 풍선 점수');}};}
function toss(c){init(c,30);const bombs=Array.from({length:21},(_,i)=>({id:i,owner:i%2,x:(i%2?8:-8)+c.rand(-4,4),z:c.rand(-5,4),holder:null}));c.players.forEach(p=>p.grab=null);
 return{update(dt){c.hint('A/포인터를 누른 채 폭탄을 상대 풍선으로 옮기고 놓기 / 종료 시 내 풍선 폭탄이 적으면 승리');for(const p of c.players){const t=team(p),o=p.grab||bombs.filter(b=>b.owner===t&&b.holder==null).sort((a,b)=>dist(p,a)-dist(p,b))[0],dest=p.grab?{x:t?-7:7,z:(p.i%2?2:-2)}:o||{x:t?8:-8,z:0};const q=cursor(c,p,()=>aiming(p,dest,!!o&&(p.grab?dist(p,dest)>.4:dist(p,o)<.6)),dt);if(!p.grab&&press(q)&&o&&dist(p,o)<.9&&o.owner===t){p.grab=o;o.holder=p.i;}if(p.grab){p.grab.x=p.x;p.grab.z=p.z;if(!held(q)){if(Math.abs(p.x)>2)p.grab.owner=p.x>0?1:0;else p.grab.x=p.grab.owner?4:-4;p.grab.holder=null;p.grab=null;}}}for(let t=0;t<2;t++)c.players[t*2].score=bombs.filter(b=>b.owner===1-t).length;},render(){for(let t=0;t<2;t++)c.draw('basket'+t,'cylinder',{x:t?8:-8,y:-.2,z:0,sx:13,sy:.4,sz:16,color:col[t]});bombs.forEach(b=>c.draw('bomb'+b.id,'sphere',{x:b.x,y:b.holder==null?.45:1,z:b.z,sx:.9,sy:.9,sz:.9,color:'#9896ac'}));},timeout(){won(c,'풍선에 남은 폭탄이 더 적은 팀');}};}
function net(c){init(c,64);let round=0,age=0,fish=[];const pos=(t,x,z)=>({x:(t?8:-8)+(x-2.5)*1.5,z:(z-2.5)*1.5});function setup(){const pattern=Array.from({length:36},(_,i)=>({x:i%6,z:Math.floor(i/6),kind:c.rand()<.22?'urchin':c.rand()<.16?'gold':'fish'}));fish=[0,1].map(t=>pattern.map(o=>({...o,alive:true})));c.players.forEach(p=>{p.netStart=null;p.used=false;p.plan=null;});}setup();
 function plan(p){const t=team(p);let choices=[];for(let axis=0;axis<2;axis++)for(let n=0;n<6;n++)for(let lo=0;lo<6;lo++)for(let hi=lo;hi<6;hi++){const cells=fish[t].filter(o=>o.alive&&(axis?o.x:o.z)===n&&(axis?o.z:o.x)>=lo&&(axis?o.z:o.x)<=hi);if(cells.some(o=>o.kind==='urchin'))continue;const value=cells.reduce((s,o)=>s+(o.kind==='gold'?3:1),0);choices.push({value,a:pos(t,axis?n:lo,axis?lo:n),b:pos(t,axis?n:hi,axis?hi:n)});}return choices.sort((a,b)=>b.value-a.value)[p.i%2]||{a:p,b:p};}
 return{update(dt){age+=dt;c.hint(`그물 ${round+1}/15 · A/포인터를 누르고 가로 또는 세로로 끌어 놓기 / 성게가 닿으면 그물 찢김 · 금색3점`);for(const p of c.players){if(!p.plan)p.plan=plan(p);const dest=p.netStart?p.plan.b:p.plan.a,q=cursor(c,p,()=>aiming(p,dest,!p.used&&(p.netStart?dist(p,dest)>.25:dist(p,dest)<.5)),dt);if(!p.used&&press(q))p.netStart={x:p.x,z:p.z};if(p.netStart&&!held(q)){const a=p.netStart,b={x:p.x,z:p.z},t=team(p),horizontal=Math.abs(a.x-b.x)>=Math.abs(a.z-b.z),cells=fish[t].filter(o=>{const at=pos(t,o.x,o.z);return o.alive&&(horizontal?Math.abs(at.z-a.z)<.65&&at.x>=Math.min(a.x,b.x)-.6&&at.x<=Math.max(a.x,b.x)+.6:Math.abs(at.x-a.x)<.65&&at.z>=Math.min(a.z,b.z)-.6&&at.z<=Math.max(a.z,b.z)+.6);});if(!cells.some(o=>o.kind==='urchin'))for(const o of cells){o.alive=false;c.points(p,o.kind==='gold'?3:1);}p.netStart=null;p.used=true;}}if(age>=4){round++;if(round===15)won(c,'15번 그물질의 물고기 점수');else{age=0;setup();}}},render(){arena(c);fish.forEach((list,t)=>list.forEach((f,i)=>{if(f.alive)c.draw('fish'+t+'-'+i,f.kind==='urchin'?'cone':'sphere',{...pos(t,f.x,f.z),y:.4,sx:.7,sy:.7,sz:.7,color:f.kind==='urchin'?'#9085b4':f.kind==='gold'?'#debf67':'#d899ad'});}));c.players.forEach(p=>{if(p.netStart)c.draw('net'+p.i,'box',{x:(p.x+p.netStart.x)/2,y:.8,z:(p.z+p.netStart.z)/2,sx:Math.max(.2,Math.abs(p.x-p.netStart.x)),sy:.1,sz:Math.max(.2,Math.abs(p.z-p.netStart.z)),color:p.color,opacity:.5});});},timeout(){won(c,'그물로 잡은 물고기 점수');}};}
function grip(c){init(c,180);c.pointerProject=q=>q.frontValid?{x:q.frontX,z:8-q.frontY}:null;c.cursorSpeed=5;c.view={size:34,eye:[0,14,38],target:[0,8,0]};const checkpoint=[0,0];c.players.forEach(p=>{p.rock=0;p.gripping=true;p.visible=false;p.x=team(p)?8:-8;p.z=6;p.target=0;});function rock(t,i){return{x:(t?8:-8)+(i===0||i===5||i===10?0:(i%2?1.15:-1.15))+(i>5&&i<10?Math.sin(c.time*.7+i)*.7:0),z:6-i*1.2};}
 return{update(dt){c.hint('방향/포인터로 손 이동 · A를 누르면 바위 잡기 / 한 손을 잡은 채 다른 손 이동 / 중간·끝은 두 손 모두');for(const p of c.players){const other=c.players[p.i^1],t=team(p);let target=p.rock;if(p.gripping){const atGate=(Math.max(p.rock,other.rock)===5&&checkpoint[t]===0);if(atGate)target=5;else if(p.rock<other.rock||p.rock===other.rock&&p.i%2===0)target=Math.min(10,other.rock+1);}else target=p.target;target=Math.min(target,checkpoint[t]===0?5:10);p.target=target;const pos=rock(t,target);const q=cursor(c,p,()=>aiming(p,pos,target===p.rock&&p.gripping||dist(p,pos)<.45),dt);if(p.gripping&&held(q)){const r=rock(t,p.rock);p.x=r.x;p.z=r.z;}else{p.gripping=false;if(other.gripping){const r=rock(t,other.rock),d=dist(p,r);if(d>3.2){p.x=r.x+(p.x-r.x)*3.2/d;p.z=r.z+(p.z-r.z)*3.2/d;}}if(held(q)){const candidates=Array.from({length:11},(_,i)=>i).filter(i=>i<=(checkpoint[t]===0?5:10)&&dist(p,rock(t,i))<.65);if(candidates.length){p.rock=candidates.sort((a,b)=>dist(p,rock(t,a))-dist(p,rock(t,b)))[0];p.gripping=true;}}}p.score=p.rock;}for(let t=0;t<2;t++){const a=c.players[t*2],b=c.players[t*2+1];if(a.gripping&&b.gripping&&a.rock===5&&b.rock===5)checkpoint[t]=5;if(!a.gripping&&!b.gripping){for(const p of[a,b]){p.rock=p.target=checkpoint[t];Object.assign(p,rock(t,p.rock));p.gripping=true;}}}const winners=[0,1].filter(t=>members(t).every(i=>c.players[i].gripping&&c.players[i].rock===10));if(winners.length)c.complete(winners.flatMap(members),'두 손이 정상 바위를 붙잡았습니다');},render(){for(let t=0;t<2;t++){c.draw('wall'+t,'box',{x:t?8:-8,y:8,z:-1,sx:12,sy:16,sz:.3,color:'#bac3c5'});for(let i=0;i<=10;i++){const r=rock(t,i);c.draw('rock'+t+i,'sphere',{x:r.x,y:8-r.z,z:0,sx:i%5===0?2:1.1,sy:.6,sz:.8,color:i%5===0?'#dcc88a':'#9cb7a8'});}}c.players.forEach(p=>{c.draw('hand'+p.i,'sphere',{x:p.x,y:8-p.z,z:.5,sx:.7,sy:.7,sz:.7,color:p.color});});},timeout(){c.complete([],'두 손이 정상에 도달한 팀이 없습니다');}};}
function scoop(c){init(c,45);const flavors=['#d896b0','#ddc99e','#927660'],data=[0,1].map(()=>({order:c.shuffle([0,1,2]),done:0}));const tub=(t,k)=>({x:(t?8:-8)+(k-1)*3.5,z:-3}),cone=t=>({x:t?8:-8,z:5});c.players.forEach(p=>{p.flavor=null;p.rub=0;p.last={x:p.x,z:p.z};p.kind=0;});
 return{update(dt){c.hint('A/포인터를 누른 채 통에서 문질러 아이스크림 만들기 → 콘으로 옮겨 놓기 / 주문 순서가 틀리면 콘 초기화');for(const p of c.players){const t=team(p),d=data[t],other=c.players[p.i^1];if(p.flavor==null&&p.rub===0)p.kind=d.order[Math.min(d.order.length-1,d.done+(other.flavor!=null?1:0))];const dest=p.flavor!=null?cone(t):{...tub(t,p.kind),x:tub(t,p.kind).x+Math.sin(c.time*12+p.phase)*.45};const q=cursor(c,p,()=>aiming(p,dest,p.flavor!=null?dist(p,dest)>.35:true),dt);const previous=p.last,moved=Math.hypot(p.x-previous.x,p.z-previous.z);p.last={x:p.x,z:p.z};if(held(q)&&p.flavor==null){const k=[0,1,2].find(k=>dist(p,tub(t,k))<1.4);if(k!=null){if(p.kind!==k)p.rub=0;p.kind=k;if(dist(previous,tub(t,k))<1.4)p.rub+=moved;if(p.rub>=1.5){p.flavor=k;p.rub=0;}}}if(!held(q)&&p.flavor!=null){if(dist(p,cone(t))<1.5){if(p.flavor===d.order[d.done]){d.done++;if(d.done===d.order.length){c.points(p);d.order=Array.from({length:c.int(2,3)},()=>c.int(0,2));d.done=0;}}else d.done=0;}p.flavor=null;p.rub=0;}}},render(){arena(c);for(let t=0;t<2;t++){for(let k=0;k<3;k++)c.draw('tub'+t+k,'cylinder',{...tub(t,k),y:.3,sx:2.6,sy:.6,sz:2.6,color:flavors[k]});const at=cone(t);c.draw('cone'+t,'cone',{...at,y:.6,sx:1.3,sy:1.7,sz:1.3,rz:Math.PI,color:'#d3b784'});for(let j=0;j<data[t].done;j++)c.draw('scoop'+t+j,'sphere',{...at,y:1.4+j*.7,sx:1.25,sy:1,sz:1.25,color:flavors[data[t].order[j]]});data[t].order.forEach((k,i)=>c.draw('order'+t+i,'sphere',{x:(t?8:-8)+(i-1)*1.4,y:2,z:-7,sx:1,sy:1,sz:1,color:flavors[k]}));}c.players.forEach(p=>{if(p.flavor!=null)c.draw('held'+p.i,'sphere',{x:p.x,y:2,z:p.z,sx:1,sy:1,sz:1,color:flavors[p.flavor]});});},timeout(){won(c,'완성한 아이스크림 주문 수');}};}
function knock(c){init(c,180);const pattern=c.shuffle([...Array(6).keys(),...Array(6).keys()]),data=[0,1].map(()=>({open:[],matched:new Set(),memory:new Map(),wait:0,firstPlayer:null}));const door=(t,i)=>({x:(t?8:-8)+(i%4-1.5)*2.5,z:(Math.floor(i/4)-1)*3});c.players.forEach(p=>p.target=-1);
 return{update(dt){c.hint('방향/포인터로 문 선택 후 A / 팀원이 연 두 문의 그림이 같으면 한 쌍 / 다른 그림이면 잠시 대기');for(let t=0;t<2;t++){const d=data[t];d.wait=Math.max(0,d.wait-dt);if(d.wait===0&&d.open.length===2){d.open=[];d.firstPlayer=null;}}for(const p of c.players){const t=team(p),d=data[t];if(p.target<0||d.matched.has(p.target)||d.open.includes(p.target)){const available=pattern.map((_,i)=>i).filter(i=>!d.matched.has(i)&&!d.open.includes(i));const first=d.open[0];const known=first!=null?available.find(i=>d.memory.get(i)===pattern[first]):undefined;p.target=known??available.filter(i=>!d.memory.has(i))[0]??available[0]??0;}const dest=door(t,p.target),q=cursor(c,p,()=>aiming(p,dest,!d.wait&&dist(p,dest)<.5&&pulse(c.time,2+p.phase,p.phase)),dt);if(press(q)&&!d.wait&&d.open.length<2&&(d.open.length===0||d.firstPlayer!==p.i)){const i=pattern.map((_,i)=>i).find(i=>!d.matched.has(i)&&!d.open.includes(i)&&dist(p,door(t,i))<.8);if(i!=null){if(d.open.length===0)d.firstPlayer=p.i;d.open.push(i);d.memory.set(i,pattern[i]);p.target=-1;if(d.open.length===2){const[a,b]=d.open;if(pattern[a]===pattern[b]){d.matched.add(a);d.matched.add(b);c.points(p);d.open=[];d.firstPlayer=null;}else d.wait=1.1;}}}}const winners=[0,1].filter(t=>data[t].matched.size===12);if(winners.length)c.complete(winners.flatMap(members),'여섯 쌍을 모두 찾았습니다');},render(){arena(c);data.forEach((d,t)=>pattern.forEach((kind,i)=>{const at=door(t,i),show=d.open.includes(i)||d.matched.has(i);c.draw('door'+t+i,'box',{...at,y:.5,sx:2,sy:1,sz:2.4,color:show?['#d899ae','#9fbbd1','#dccc82','#9bbea6','#b4a2cf','#bb9277'][kind]:'#bbc4bd'});if(show)text(c,'icon'+t+i,String(kind+1),at.x,1.4,at.z,1);}));},timeout(){c.complete([],'여섯 쌍을 모두 찾은 팀이 없습니다');}};}
function scoopas(c){init(c,30);c.pointerSpeed=18;const units=Array.from({length:150},(_,i)=>({id:i,x:c.rand(-11,11),z:c.rand(-6,6),vx:0,vz:0,alive:true}));c.players.forEach(p=>{p.x=team(p)?5:-5;p.z=(p.i%2?1:-1)*4;});
 return{update(dt){c.hint('방향키/포인터로 불도저 이동 / 작은 새150마리를 내 팀 좌우 출구로 밀기 / 동점이면 양 팀 승리');for(const p of c.players){const t=team(p),o=units.filter(o=>o.alive).sort((a,b)=>dist(a,p)-dist(b,p))[0],target=o?{x:o.x+(t?-1.1:1.1),z:o.z}:p,old={x:p.x,z:p.z};cursor(c,p,()=>aiming(p,dist(p,target)<.4?{x:t?16:-16,z:o?.z||0}:target),dt);const vx=dt?(p.x-old.x)/dt:0,vz=dt?(p.z-old.z)/dt:0;for(const o of units){if(!o.alive)continue;const d=dist(o,p);if(d<1.15){const nx=(o.x-p.x)/(d||1),nz=(o.z-p.z)/(d||1);o.x=p.x+nx*1.16;o.z=p.z+nz*1.16;o.vx=vx*.7+nx*3;o.vz=vz*.7+nz*3;}}}for(const o of units){if(!o.alive)continue;o.x+=o.vx*dt;o.z+=o.vz*dt;o.vx*=Math.exp(-4*dt);o.vz*=Math.exp(-4*dt);if(Math.abs(o.z)>8){o.z=clamp(o.z,-8,8);o.vz*=-.5;}if(Math.abs(o.x)>14){o.alive=false;add(c,o.x<0?0:1);}}},render(){c.arena({width:31,depth:18,color:'#b7c6af'});for(let t=0;t<2;t++)c.draw('gate'+t,'box',{x:t?15:-15,y:.2,z:0,sx:2,sy:.4,sz:16,color:col[t]});units.forEach(o=>{if(o.alive)c.draw('small'+o.id,'sphere',{x:o.x,y:.28,z:o.z,sx:.55,sy:.55,sz:.55,color:'#b99d7e'});});c.players.forEach(p=>c.draw('scoop'+p.i,'box',{x:p.x,y:.35,z:p.z,sx:1.6,sy:.7,sz:1.8,color:p.color}));},timeout(){won(c,'출구에 모은 작은 새 수',true);}};}
function flower(c){init(c,18);let round=0,age=0,pause=.4,hat=0,crouch=false,negative=false;function setup(){hat=c.int(0,1);crouch=c.rand()<.5;negative=c.rand()<.5;c.players.forEach(p=>{p.respondAt=c.rand(.45,1.5);p.error=c.rand()<.1;p.responded=false;});}setup();c.players.forEach(p=>{p.crouch=false;p.x=(p.i-1.5)*6;p.z=0;});
 return{update(dt){c.hint('A 서기 / B 앉기 · 모자 색을 보고 꽃의 지시 따르기 / 부정문 주의');if(pause){pause=Math.max(0,pause-dt);c.players.forEach(p=>c.input(p,{}));return;}age+=dt;for(const p of c.players){const action=p.error?!crouch:crouch,q=c.input(p,()=>age>=p.respondAt&&!p.responded&&p.i%2===hat?{a:!action,b:action}:{});if(q.ap){p.crouch=false;p.responded=true;}if(q.bp){p.crouch=true;p.responded=true;}p.pose=p.crouch?'crouch':'idle';p.y=p.crouch?-.35:0;}if(age>=3){for(let t=0;t<2;t++)if(members(t).some(i=>i%2===hat&&c.players[i].crouch===crouch))add(c,t);round++;if(round===5)won(c,'다섯 지시를 올바르게 따른 라운드 수');else{age=0;pause=.4;setup();}}},render(){c.arena({width:28,depth:12,color:'#b7c4ae'});const verb=negative?(crouch?'서지 마세요':'앉지 마세요'):(crouch?'앉으세요':'서세요');text(c,'instruction',`${hat?'초록':'빨강'} 모자: ${verb}`,0,6,-3,18);text(c,'round',`${Math.min(5,round+1)} / 5`,0,4,-3,5);c.players.forEach(p=>c.draw('hat'+p.i,'cone',{x:p.x,y:p.crouch?1.55:1.9,z:p.z,sx:1,sy:.7,sz:1,color:p.i%2?'#80b293':'#d68fa4'}));},timeout(){won(c,'올바르게 따른 지시 수');}};}
function rich(c){init(c,15);c.players.forEach(p=>{p.x=(p.i-1.5)*6;p.z=0;p.flash=0;p.rate=c.rand(3.8,6.8);});return{update(dt){c.hint('A 반복으로 머리 위 블록 치기 / 카메라의 위로 치는 동작을 버튼으로 변환');for(const p of c.players){p.cool=Math.max(0,p.cool-dt);p.flash=Math.max(0,p.flash-dt);const q=c.input(p,()=>({a:pulse(c.time,p.rate,p.phase)}));if(q.ap&&!p.cool){c.points(p);p.cool=.1;p.flash=.15;}p.pose=p.flash?'punch':'idle';}},render(){c.arena({width:28,depth:11,color:'#b1c4b8'});c.players.forEach(p=>{c.draw('block'+p.i,'box',{x:p.x,y:3.5+(p.flash?.15:0),z:0,sx:2,sy:2,sz:2,color:'#d9c27e'});if(p.flash)c.draw('coin'+p.i,'cylinder',{x:p.x,y:5.5-p.flash*3,z:0,sx:.8,sy:.13,sz:.8,color:'#ead088'});});},timeout(){won(c,'15초 동안 블록에서 꺼낸 동전 합계');}};}
function balancing(c){init(c,15);c.view={size:33,eye:[0,9,32],target:[0,4,0]};c.players.forEach(p=>{p.x=(p.i-1.5)*7;p.z=0;p.angle=0;p.items=[];p.drops=Array.from({length:10},(_,i)=>({at:.4+i*1.25,x:c.rand(-1.2,1.2),y:9,vx:c.rand(-.8,.8),wind:c.rand(-.55,.55),landed:false,alive:true}));});
 return{update(dt){c.hint('좌우 방향키로 머리 받침대 기울이기 / 너무 기울이면 새가 미끄러짐 / 한 사람 최대10마리');for(const p of c.players){const resting=p.drops.filter(o=>o.landed&&o.alive),mean=resting.reduce((s,o)=>s+o.x,0)/(resting.length||1),q=c.input(p,()=>({x:clamp(-mean*1.2+Math.sin(c.time*1.7+p.phase*9)*.08,-.65,.65)}));p.angle+=((q.x||0)*.6-p.angle)*Math.min(1,dt*8);p.rotation=-p.angle;for(const o of p.drops){if(!o.alive||c.time<o.at)continue;if(!o.landed){o.y-=5*dt;if(o.y<=2.5+resting.length*.35){if(Math.abs(o.x)<1.65){o.landed=true;o.y=2.5+resting.length*.35;resting.push(o);}else o.alive=false;}}else{o.vx+=(Math.sin(p.angle)*4+o.wind-o.vx*.8)*dt;o.x+=o.vx*dt;if(Math.abs(o.x)>1.6)o.alive=false;}}const kept=p.drops.filter(o=>o.alive&&o.landed);kept.forEach((o,i)=>o.y=2.5+i*.35);p.score=kept.length;}},render(){c.arena({width:31,depth:10,color:'#afc3b5'});c.players.forEach(p=>{c.draw('platform'+p.i,'box',{x:p.x,y:2.25,z:0,sx:3.5,sy:.2,sz:2,rz:p.angle,color:p.color});p.drops.forEach((o,i)=>{if(o.alive&&c.time>=o.at)c.draw('bird'+p.i+'-'+i,'sphere',{x:p.x+o.x,y:o.y,z:0,sx:.6,sy:.45,sz:.6,color:'#b99d7e'});});});},timeout(){won(c,'받침대에 남은 새의 합계');}};}
function chicken(c){init(c,22);let round=0,age=0,pause=.5;const cars=[0,1].map(t=>({x:-12,z:t?3:-3,d:0,crushed:false}));c.players.forEach(p=>{p.goal=c.rand(23.4,24.7);p.visible=false;});
 return{update(dt){c.hint(`라운드 ${round+1}/2 · A를 누르면 목소리 입력, 놓으면 정지 / 팀원과 함께 거인 직전까지 이동`);if(pause){pause=Math.max(0,pause-dt);c.players.forEach(p=>c.input(p,{}));return;}age+=dt;const qs=c.players.map(p=>c.input(p,()=>({a:cars[team(p)].d<p.goal})));for(let t=0;t<2;t++){const o=cars[t];if(o.crushed)continue;const power=members(t).reduce((s,i)=>s+(qs[i].a?1:0),0)/2;o.d+=power*4*dt;o.x=-12+o.d;if(o.d>=25)o.crushed=true;}if(age>=10){for(let t=0;t<2;t++)if(!cars[t].crushed)add(c,t,Math.floor(cars[t].d/25*100));round++;if(round===2)won(c,'충돌하지 않고 접근한 두 라운드 거리 점수');else{age=0;pause=.5;cars.forEach(o=>{o.d=0;o.x=-12;o.crushed=false;});}}},render(){c.arena({width:31,depth:13,color:'#b8c5b0'});c.draw('giant','cone',{x:14,y:3,z:0,sx:3.5,sy:6,sz:9,color:'#ad97b4'});cars.forEach((o,t)=>{c.draw('car'+t,'box',{x:o.x,y:o.crushed?.12:.6,z:o.z,sx:2,sy:o.crushed?.2:1.2,sz:2,color:col[t]});text(c,'distance'+t,`${o.crushed?'충돌':Math.floor(o.d/25*100)+'점'}`,0,3,o.z,5);});},timeout(){won(c,'접근 거리 점수');}};}
function junior(c){init(c,32);let round=0,age=0,pause=.5;const cars=[0,1].map(t=>({y:4,medals:[]}));const pattern=Array.from({length:25},(_,i)=>({at:1+i*.54,y:2+Math.sin(i*.85)*2+c.rand(0,3)}));function setup(){cars.forEach(o=>{o.y=4;o.medals=pattern.map((m,i)=>({...m,id:i,x:13+i*2.7,got:false}));});}setup();c.players.forEach(p=>p.visible=false);
 return{update(dt){c.hint(`라운드 ${round+1}/2 · A를 누르면 음성 입력으로 상승, 놓으면 하강 / 팀원이 함께 비행 높이 조절`);if(pause){pause=Math.max(0,pause-dt);c.players.forEach(p=>c.input(p,{}));return;}age+=dt;const qs=c.players.map(p=>c.input(p,()=>{const o=cars[team(p)],m=o.medals.find(m=>!m.got&&m.x>=-8)||{y:4};return{a:o.y<m.y+Math.sin(c.time*.9+p.phase*7)*(.18+p.lag)};}));for(let t=0;t<2;t++){const o=cars[t],power=members(t).reduce((s,i)=>s+(qs[i].a?1:0),0)/2;o.y=clamp(o.y+(power*7-3)*dt,.6,8);for(const m of o.medals){const old=m.x;m.x-=5*dt;if(!m.got&&old>=-8&&m.x<-8&&Math.abs(o.y-m.y)<1){m.got=true;add(c,t);}}}if(age>=15){round++;if(round===2)won(c,'두 번의 비행에서 모은 메달 합계');else{age=0;pause=.5;setup();}}},render(){c.view={size:33,eye:[0,12,36],target:[0,5,0]};for(let t=0;t<2;t++){const o=cars[t],z=t?3:-3;c.draw('car'+t,'sphere',{x:-8,y:o.y,z,sx:2,sy:1.5,sz:2,color:col[t]});o.medals.forEach(m=>{if(!m.got&&m.x<15&&m.x>-11)c.draw('medal'+t+'-'+m.id,'cylinder',{x:m.x,y:m.y,z,sx:.8,sy:.15,sz:.8,rx:Math.PI/2,color:'#dfc679'});});}},timeout(){won(c,'비행 중 모은 메달 합계');}};}
function beats(c){init(c,22);const notes=Array.from({length:64},(_,i)=>({at:2+i*.28,player:i%4,done:false,tone:[261.63,329.63,392,523.25][i%4],sounded:false,error:c.rand(-.13,.13)}));c.players.forEach(p=>{p.x=(p.i-1.5)*6;p.z=4;p.flash=0;});
 return{update(dt){c.hint('자기 색 음표가 판정선에 올 때 A로 박수 / 정확2점·조금 빠르거나 늦으면1점 / 직접 만든 리듬');for(const n of notes)if(!n.sounded&&c.time>=n.at){n.sounded=true;c.sound?.(n.tone,.09,'sine');}for(const p of c.players){p.flash=Math.max(0,p.flash-dt);const upcoming=notes.find(n=>n.player===p.i&&!n.done&&n.at>=c.time-.24),q=c.input(p,()=>({a:!!upcoming&&Math.abs(c.time-upcoming.at-upcoming.error)<.03}));if(q.ap&&upcoming&&Math.abs(c.time-upcoming.at)<=.24){const delta=Math.abs(c.time-upcoming.at);c.points(p,delta<=.075?2:1);upcoming.done=true;p.flash=.15;}}for(const n of notes)if(c.time>n.at+.24)n.done=true;if(c.time>=notes.at(-1).at+.6)won(c,'자기 음표에 맞춰 친 박수 점수');},render(){arena(c);c.draw('judge','box',{x:0,y:.1,z:3,sx:28,sy:.2,sz:.18,color:cream});notes.forEach((n,i)=>{const z=3-(n.at-c.time)*5;if(!n.done&&z>-9&&z<5)c.draw('note'+i,'sphere',{x:(n.player-1.5)*6,y:.7,z,sx:1,sy:1,sz:1,color:c.players[n.player].color});});c.players.forEach(p=>{if(p.flash)text(c,'hit'+p.i,'짝!',p.x,3,3,2);});},timeout(){won(c,'박수 리듬 점수');}};}
export const games={'Shell Hockey':shell,'Bowser Filter':filter,'Stuffie Stacker':stack,'Pull-Back Attack':pullback,'Domino Effect':domino,'Bob-omb Makeover':makeover,'Toad-ally Electric Escape':electric,'Ice and Easy':ice,'Bob-omb Toss':toss,'Net Gains':net,'Get a Grip':grip,"What's the Scoop?":scoop,'Knock-Knock Match':knock,'Goomba Scoopas':scoopas,'Talking Flower Says':flower,'Hitting It Rich':rich,'Goombalancing Act':balancing,'Bowser Chicken':chicken,'Speak Up, Junior!':junior,'Bowser Beats':beats};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(n=>[n,['jamboree-tv']]));
export const aliases={};
const mouse='2대2 원작의 마우스 조작을 포인터 또는 방향키+A로 옮겼습니다. 맵·소품·물리·반응 수치는 브라우저판에서 새로 만들었습니다. ';
const camera='2대2 원작의 카메라/마이크 입력을 키보드로 옮겨 장치 권한 없이 플레이합니다. 원작 영상·음원은 사용하지 않고 장면·수치는 브라우저판에서 새로 만들었습니다. ';
export const notes={
 'Shell Hockey':mouse+'60초 골 득점 경기이며 마지막20초에 새4마리를 추가하고 처음 부딪히면 움직이는 공이 됩니다. 새와 공은 직접 만든 소품입니다.',
 'Bowser Filter':mouse+'일반·악당·하트 편지를 분류하고 오분류는 돌아옵니다. 모두 분류한 팀이 우승하며180초가 끝나면 분류 수 비교, 동점은 무승부. 편지30개와 하트 등장 시점은 새로 정했습니다.',
 'Stuffie Stacker':mouse+'45초 뒤 서 있는 탑 높이를 비교합니다. 제공된5개를 모두 써야 다음 묶음을 받습니다. B 회전, 위아래 이동은 들고 있는 높이 조절입니다. 인형 모양과 낙하·지지·기울어짐 물리는 새로 만들었습니다.',
 'Pull-Back Attack':mouse+'A를 눌러 충전하고 놓아 발사하며 B 반복이 뒤집힌 차를 바로 세우는 흔들기입니다. 두 압착기·물 추락은 출발점으로 복귀합니다.60초 골 합계를 비교합니다. 끌기 거리 대신 누르는 시간이 힘입니다.',
 'Domino Effect':mouse+'각 팀22개로 시작에서 화분까지 연쇄를 연결하고 시작 인물을 눌러 실행합니다. 장애물로 쓰러진 첫 블록은 제거되며 나머지는 복구됩니다.180초 내 아무도 도착하지 못하면 무승부. 장애물과 도미노 연결 반경은 자체 구성입니다.',
 'Bob-omb Makeover':mouse+'5초씩3라운드, 폭탄은5개→7개→보통2개+3점 대형1개입니다. 각 폭탄에서 더 많이 칠한 팀이 점수를 받습니다. A 분사, B가 흔들어 재충전입니다. 표면을 색 점유량으로 근사하고 동률 폭탄은 무득점 처리합니다.',
 'Toad-ally Electric Escape':mouse+'두 선수를 A로 잡아 전기 미로 출구에 먼저 보내는 팀이 승리합니다. 벽 접촉은 체크포인트 복귀, 동료 접촉은 밀침입니다.180초 미완주 시 무승부. 새 미로를 만들었습니다.',
 'Ice and Easy':mouse+'15초씩3라운드 튜브로 풍선 접촉, 마지막 황금 풍선3점입니다. 방향으로 조준하고 A 충전 후 놓아 밀어내는 방식이 원작의 마우스 밀기 세기·방향을 대신합니다. 풍선 배치와 미끄럼 수치는 새로 정했습니다.',
 'Bob-omb Toss':mouse+'폭탄을 내 풍선에서 상대 풍선으로 옮기며 종료 시 적은 쪽이 이깁니다. 홀수21개와30초는 브라우저판에서 정한 수치입니다. 들고 있는 폭탄은 놓기 전 소유 팀에 남아 홀수 총량을 보존합니다.',
 'Net Gains':mouse+'15번에 걸쳐 가로·세로 그물을 끌어 물고기1점·금색3점을 얻고 성게가 걸리면 그물이 찢어집니다.6×6 배치, 한 선수당 라운드1회 그물, 회당4초는 브라우저판 값입니다.',
 'Get a Grip':mouse+'팀원이 각각 한 손을 조작해 바위를 잡습니다. 중간과 정상 바위는 두 손 모두 필요하고 후반 바위는 움직입니다. A 누르기=잡기, 놓기=이동. 두 손을 놓으면 체크포인트로 복귀합니다. 바위 수·간격·180초 안전 제한은 새로 정했습니다.',
 "What's the Scoop?":mouse+'45초 동안 주문된 맛 순서로 콘을 완성합니다. 통에서 A를 누른 채 문지르고 콘에 놓으며 틀린 맛은 콘을 초기화합니다. 맛3종, 주문2~3단, 문지르기 임계값은 브라우저판 설정입니다.',
 'Knock-Knock Match':mouse+'팀원이 문을 하나씩 열어 같은 그림6쌍을 먼저 찾습니다. 오답은 잠깐 기다립니다. 그림·문 배치·오답 대기1.1초·180초 안전 제한은 새로 정했습니다.',
 'Goomba Scoopas':mouse+'총150마리를 팀 출구로 밀어30초 후 수를 비교하며 동점은 양 팀 승리합니다. 과반을 먼저 얻어도 경기는 계속됩니다. 새 캐릭터와 좌우 출구·접촉 물리를 만들었습니다.',
 'Talking Flower Says':camera+'A=서기·B=앉기. 모자 색과 부정 지시를 확인해5라운드를 진행하고 해당 팀원이 지시를 따르면 팀1점입니다. 지시 문장·라운드3초는 자체 구성입니다.',
 'Hitting It Rich':camera+'A 반복이 카메라의 위로 치는 동작입니다.15초 동안 팀 동전 합계를 비교합니다. 치기당1점과0.1초 최소 간격은 브라우저판 수치입니다.',
 'Goombalancing Act':camera+'좌우 방향키가 머리 기울이기입니다. 한 사람당 최대10마리가 떨어지며 기울어지면 미끄러져 떨어집니다.15초 후 남은 수로 승부합니다. 낙하 배치·받침대 크기·각 물체의 미끄러짐과 기울기 물리는 새로 만들었습니다.',
 'Bowser Chicken':camera+'A를 누르면 소리 내기, 놓으면 멈추기입니다. 팀원 입력으로 한 차를 움직여10초씩2라운드 진행하며 거인에 닿으면0점입니다. 거리0~100 환산·이동 속도는 브라우저판 값입니다.',
 'Speak Up, Junior!':camera+'A를 누르면 목소리로 상승, 놓으면 하강합니다.15초씩2라운드 팀 비행체로 메달을 모읍니다. 비행 경로·메달 배치·상승과 하강 물리는 새로 만들었습니다.',
 'Bowser Beats':camera+'자기 색 음표가 판정선에 올 때 A가 박수입니다. 정확2점·조금 빠르거나 늦으면1점 규칙을 유지했습니다. 직접 만든64박 리듬과0.075/0.24초 판정 창을 사용합니다.'
};
