import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,KEYS=['a','b','c','d'],TEAM=[[0,1],[2,3]],SIDE=[[0],[1,2,3]];
const text=(c,id,t,x=0,z=-5,y=2,sx=7,color='#294550')=>c.draw(id,'text',{text:String(t),x,y,z,sx,sy:.7,color});
const box=(c,id,x,z,color,sx=1,sz=1,y=.1,sy=.2)=>c.draw(id,'box',{x,y,z,sx,sy,sz,color});
const ball=(c,id,x,z,color,s=.6,y=.5)=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color});
const ring=(c,id,x,z,color,s=1,y=.1)=>c.draw(id,'ring',{x,y,z,sx:s,sy:s,sz:s,rx:Math.PI/2,color});
const near=(p,items)=>items.reduce((a,b)=>!a||dist(p,b)<dist(p,a)?b:a,null);
const tap=(c,p,rate=p.cadence)=>((c.time+p.phase)%rate)<rate*.4;
function init(c,limit){c.limit=limit;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=3;p.phase=c.rand(0,1);p.cadence=c.rand(.23,.38);p.stun=0;});}
function scoreTeams(c,values,teams=TEAM){teams.forEach((ids,t)=>ids.forEach(i=>c.players[i].score=values[t]));}
function line(c,id,a,b,color,width=.1,y=.3){c.draw(id,'box',{x:(a.x+b.x)/2,y,z:(a.z+b.z)/2,sx:dist(a,b),sy:width,sz:width,ry:-Math.atan2(b.z-a.z,b.x-a.x),color});}
function segDistance(p,a,b){const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((p.x-a.x)*dx+(p.z-a.z)*dz)/(dx*dx+dz*dz||1),0,1);return Math.hypot(p.x-a.x-dx*t,p.z-a.z-dz*t);}
function separation(a,b,r){const d=dist(a,b);if(d<r){const x=(a.x-b.x)/(d||1),z=(a.z-b.z)/(d||1);a.x+=x*(r-d)/2;b.x-=x*(r-d)/2;a.z+=z*(r-d)/2;b.z-=z*(r-d)/2;}}
function avoid(p,threats,x=7,z=4){let best={x:p.x,z:p.z},bestScore=-Infinity;for(let i=0;i<16;i++){const a=i*TAU/16,q={x:clamp(p.x+Math.cos(a)*2,-x,x),z:clamp(p.z+Math.sin(a)*2,-z,z)},s=Math.min(...threats.map(t=>dist(q,t)),20)-Math.hypot(q.x,q.z)*.03;if(s>bestScore){bestScore=s;best=q;}}return toward(p,best.x,best.z);}
function obstacle(p,o,r=.35){const co=Math.cos(o.a||0),si=Math.sin(o.a||0),dx=p.x-o.x,dz=p.z-o.z,lx=dx*co+dz*si,lz=-dx*si+dz*co,hx=o.w/2+r,hz=o.h/2+r;if(Math.abs(lx)<hx&&Math.abs(lz)<hz){let x=lx,z=lz;if(hx-Math.abs(lx)<hz-Math.abs(lz)){x=Math.sign(lx||1)*hx;if(p.vx!==undefined){const v=p.vx*co+p.vz*si;p.vx-=v*co*1.6;p.vz-=v*si*1.6;}}else{z=Math.sign(lz||1)*hz;if(p.vx!==undefined){const v=-p.vx*si+p.vz*co;p.vx+=v*si*1.6;p.vz-=v*co*1.6;}}p.x=o.x+x*co-z*si;p.z=o.z+x*si+z*co;}}
export const games={};

games['Treasure Trawlers']=(c)=>{
 init(c,45);const treasures=Array.from({length:30},(_,id)=>({id,x:c.rand(-7,7),z:c.rand(-4,4),value:c.pick([1,1,1,3,-1]),taken:false}));c.players.forEach(p=>{p.target={x:c.rand(-7,7),z:c.rand(-4,4)};p.haul=null;p.cue=false;});
 return {update(){for(const p of c.shuffle(c.players)){const found=near(p,treasures.filter(q=>!q.taken)),cue=!!found&&dist(p,found)<.75;p.cue=cue;if(dist(p,p.target)<.6)p.target={x:c.rand(-7,7),z:c.rand(-4,4)};const u=c.input(p,{...toward(p,p.target.x,p.target.z),a:cue&&!p.haul&&c.time>=p.stun});if(p.haul){if(c.time>=p.haul.until){if(p.haul.value<0)p.stun=c.time+1.5;else c.points(p,p.haul.value);p.haul=null;}}else if(c.time<45&&c.time>=p.stun){c.move(p,u,3.7);if(u.ap){const q=near(p,treasures.filter(q=>!q.taken));p.haul={value:q&&dist(p,q)<.9?q.value:0,until:c.time+1.1};if(q&&dist(p,q)<.9)q.taken=true;}}}if(c.time>=45&&c.players.every(p=>!p.haul)){const max=Math.max(...c.players.map(p=>p.score));max?c.highest('인양 중이던 보물까지 합산했습니다.'):c.complete([],'보물을 건지지 못했습니다.');}c.hint('이동 · ! 신호가 뜨면 A로 인양. 보물 1점, 금 보물 3점, 폭탄은 기절! 45초 전에 내린 집게는 끝까지 끌어올립니다.');},render(){c.arena({color:'#8dbac3'});c.players.forEach(p=>{c.draw('boat'+p.i,'sphere',{x:p.x,y:.05,z:p.z,sx:1.7,sy:.5,sz:2.1,color:p.color});box(c,'crane'+p.i,p.x+.65,p.z,'#a59072',.12,.15,1.2,2.4);if(p.cue&&!p.haul)text(c,'cue'+p.i,'!',p.x,p.z,3,1.5,'#ffe8a4');if(p.haul){const height=.1+Math.abs(Math.sin((p.haul.until-c.time)/1.1*Math.PI))*1.3;box(c,'hook'+p.i,p.x,p.z-.8,p.haul.value===3?'#e7c255':p.haul.value<0?'#405565':'#a27c58',.55,.55,height,.45);}if(c.time<p.stun)text(c,'stun'+p.i,'★',p.x,p.z,2.3,1.5);});},timeout(){c.limit=46.2;}};
};

games['Memory Lane']=(c)=>{
 init(c,308);c.view={size:26,eye:[0,21,24],target:[0,0,-2]};const path=[{col:2,row:0}],size=1.6;let col=2;for(let row=1;row<10;row++){path.push({col,row});if(row<9){const next=clamp(col+c.pick([-1,1]),0,4);if(next!==col){col=next;path.push({col,row});}}}const tile=q=>({x:(q.col-2)*size,z:6-q.row*size}),demo=path.length*.36+1; c.limit=demo+300;c.players.forEach((p,i)=>{p.x=(i-1.5)*.25;p.z=6;p.index=0;p.rescue=0;p.botPace=c.rand(.86,1);p.memory=[];});
 return {update(){const shown=Math.min(path.length-1,Math.floor(c.time/.36));for(const p of c.players){if(c.time<demo)p.memory[shown]={...path[shown]};const next=p.memory[Math.min(p.index+1,path.length-1)]||path[0],goal=tile(next),u=c.input(p,c.time>=demo?toward(p,goal.x,goal.z,p.botPace):{});if(c.time<demo||c.time<p.rescue)continue;c.move(p,u,3.5,false);const q={col:Math.round(p.x/size)+2,row:Math.round((6-p.z)/size)},index=path.findIndex(t=>t.col===q.col&&t.row===q.row);if(index<0||index>p.index+1){p.rescue=c.time+1.1;Object.assign(p,tile(path[p.index]));p.pose='hit';}else if(index===p.index+1&&dist(p,tile(path[index]))<.48){p.index=index;p.score=index;}p.x=clamp(p.x,-4.2,4.2);p.z=clamp(p.z,-9,6.6);}const done=c.players.filter(p=>p.index===path.length-1);if(done.length)c.complete(done.map(p=>p.i),'기억한 길을 따라 성에 먼저 도착했습니다.');c.hint(c.time<demo?'안내 새가 걷는 길을 한 번만 보여줍니다. 꺾이는 방향도 기억하세요!':'방향키로 정확히 같은 길을 걸으세요. 틀린 칸은 무너져 마지막 안전 칸으로 구조됩니다.');},render(){for(let row=0;row<10;row++)for(let x=0;x<5;x++)box(c,`tile${x}-${row}`,(x-2)*size,6-row*size,'#a3b7c6',size-.07,size-.07,-.15,.25);box(c,'goal',tile(path.at(-1)).x,-9.3,'#d1b987',2,1.3,.25,.5);if(c.time<demo){const k=Math.min(path.length-1,Math.floor(c.time/.36)),v=tile(path[k]);ball(c,'guide',v.x,v.z,'#e4ca6e',.6,.8);ring(c,'foot',v.x,v.z,'#fff4cb',1,.06);}c.players.forEach(p=>{if(c.time<p.rescue)text(c,'rescue'+p.i,'구조 중',p.x,p.z,2.5,2);});},timeout(){c.complete([],'5분 동안 성에 도착하지 못했습니다.');}};
};

games['Hyper Sniper']=(c)=>{
 init(c,30);c.view={size:20,eye:[0,23,20],target:[0,0,0]};let targets=[],serial=0,next=0;const aims=c.players.map((p,i)=>({x:(i-1.5)*2,z:0}));c.players.forEach(p=>{p.x=(p.i-1.5)*3.5;p.z=6;p.cool=0;});
 return {update(dt){if(c.time>=next){const value=c.pick([10,10,30,30,50,100,0]);targets.push({id:serial++,x:c.rand(-6.5,6.5),z:-5,value,r:value===100?.36:value===50?.55:value===30?.75:1,hit:false});next=c.time+c.rand(.22,.38);}targets.forEach(t=>t.z+=dt*1.65);const shots=[];for(const p of c.players){const aim=aims[p.i],target=near(aim,targets.filter(t=>!t.hit&&t.value>0&&t.z<4)),u=c.input(p,target?{...toward(aim,target.x,target.z),a:dist(aim,target)<target.r*.7&&tap(c,p)}:{});aim.x=clamp(aim.x+u.x*dt*7,-7.5,7.5);aim.z=clamp(aim.z+u.z*dt*7,-4.6,4.3);if(u.ap&&c.time>=p.cool){p.cool=c.time+.15;const hit=targets.filter(t=>!t.hit&&dist(aim,t)<t.r).sort((a,b)=>dist(aim,a)/a.r-dist(aim,b)/b.r)[0];if(hit)shots.push({p,target:hit});}}for(const t of targets){const competing=shots.filter(s=>s.target===t);if(competing.length){const chosen=c.pick(competing);t.hit=true;if(t.value===0)chosen.p.score=0;else c.points(chosen.p,t.value);}}targets=targets.filter(t=>t.z<5.3);c.hint('네 명이 같은 과녁판을 겨룹니다. 방향키 조준 · A 발사. 10·30·50·100점 과녁을 먼저 맞히세요. 검은 과녁은 누적 점수 0!');},render(){box(c,'panel',0,-.5,'#617c8b',16,10,-.18,.3);targets.forEach(t=>{if(!t.hit){c.draw('target'+t.id,'cylinder',{x:t.x,y:.16,z:t.z,sx:t.r*2,sy:.15,sz:t.r*2,color:t.value===100?'#efcf78':t.value===50?'#8cb9cd':t.value===30?'#aac584':t.value===10?'#dfa9a2':'#41384e'});text(c,'value'+t.id,t.value||'×',t.x,t.z,.85,t.value===100?3.4:t.r*5,t.value?'#294550':'#f2e7d6');}});aims.forEach((a,i)=>{ring(c,'scope'+i,a.x,a.z,c.players[i].color,1,.5);text(c,'points'+i,`${i+1}P · ${c.players[i].score}`,(i-1.5)*4,-6.4,1.4,3.6,c.players[i].color);});},timeout(){Math.max(...c.players.map(p=>p.score))?c.highest('공용 과녁판의 최종 점수'):c.complete([],'점수가 없습니다.');}};
};

games['Strawberry Shortfuse']=(c)=>{
 init(c,Infinity);let round=0,phase='show',until=0,turn=0,cakes=0,trays=[],mix=0,swap=null;const slots=Array.from({length:10},(_,i)=>({x:(i%5-2)*2.7,z:i<5?-2.2:1.1}));const order=c.shuffle([0,1,2,3]);let reveal=null;
 function setup(){round++;phase='show';until=c.time+2;cakes=0;mix=0;trays=c.shuffle([1,1,1,1,1,0,0,0,0,0]).map((value,i)=>({id:i,value,slot:i,x:slots[i].x,z:slots[i].z,taken:false}));c.players.forEach(p=>{p.remember=trays.filter(q=>q.value).map(q=>q.id);p.choice=0;p.nav=0;});}setup();
 function active(){while(!c.players[order[turn%4]].alive)turn++;return c.players[order[turn%4]];}
 function pick(p){let t=trays.find(q=>q.slot===p.choice&&!q.taken)||trays.find(q=>!q.taken);t.taken=true;reveal=t;phase='result';until=c.time+1;if(t.value){cakes++;c.points(p);}else c.eliminate(p);}
 return {update(){if(phase==='show'&&c.time>=until){phase='mix';until=c.time+4.8;mix=0;}if(phase==='mix'){if(!swap){const pair=c.shuffle(trays).slice(0,2);swap={a:pair[0],b:pair[1],fromA:{x:pair[0].x,z:pair[0].z},fromB:{x:pair[1].x,z:pair[1].z},at:c.time};}const t=clamp((c.time-swap.at)/.55,0,1);swap.a.x=swap.fromA.x+(swap.fromB.x-swap.fromA.x)*t;swap.a.z=swap.fromA.z+(swap.fromB.z-swap.fromA.z)*t+Math.sin(t*Math.PI)*.5;swap.b.x=swap.fromB.x+(swap.fromA.x-swap.fromB.x)*t;swap.b.z=swap.fromB.z+(swap.fromA.z-swap.fromB.z)*t-Math.sin(t*Math.PI)*.5;if(t===1){[swap.a.slot,swap.b.slot]=[swap.b.slot,swap.a.slot];swap=null;mix++;}if(mix>=8&&!swap){phase='pick';until=c.time+10;}}const p=phase==='pick'?active():null;for(const q of c.players){let target=q.choice;if(q===p){const remembered=trays.filter(t=>!t.taken&&q.remember.includes(t.id));target=(remembered[0]||trays.find(t=>!t.taken))?.slot??0;}const u=c.input(q,{x:q===p?Math.sign(target%5-q.choice%5):0,z:q===p?Math.sign(Math.floor(target/5)-Math.floor(q.choice/5)):0,a:q===p&&q.choice===target&&tap(c,q,.8)});if(q===p){if(c.time>=q.nav&&(Math.abs(u.x)>.5||Math.abs(u.z)>.5)){q.choice=clamp(q.choice+Math.sign(u.x)+Math.sign(u.z)*5,0,9);q.nav=c.time+.18;}if(u.ap||c.time>=until)pick(q);}}if(phase==='result'&&c.time>=until){const living=c.players.filter(p=>p.alive);if(living.length<=1)c.complete(living.map(p=>p.i),'케이크를 기억해 마지막까지 남았습니다.');else{turn++;if(cakes===5){if(round===3)c.complete(living.map(p=>p.i),'세 차례의 케이크를 모두 골랐습니다.');else setup();}else{phase='pick';until=c.time+10;}}}c.hint(`${round}/3 · ${phase==='show'?'케이크 5개와 폭탄 5개를 기억하세요':phase==='mix'?'쟁반을 든 새가 섞입니다!':phase==='pick'?`${active().i+1}P 차례 · 방향키 선택, A 확정 · 10초`:'쟁반 공개!'}`);},render(){c.arena({color:'#c4a5a9'});trays.forEach(t=>{if(t.taken)return;ball(c,'waiter'+t.id,t.x,t.z,'#b98c75',.7,.65);box(c,'tray'+t.id,t.x,t.z-.2,'#e6d9b5',1.4,1.1,1.1,.15);if(phase==='show'){if(t.value)box(c,'cake'+t.id,t.x,t.z-.2,'#f5c4ca',.6,.6,1.5,.65);else ball(c,'bomb'+t.id,t.x,t.z-.2,'#374b5c',.55,1.5);}else box(c,'cover'+t.id,t.x,t.z-.2,'#abb8b9',.9,.8,1.35,.3);});c.players.forEach((p,i)=>{p.x=(i-1.5)*2.5;p.z=5;});if(phase==='pick'){const p=active(),s=slots[p.choice];ring(c,'cursor',s.x,s.z,p.color,2.1,.05);}if(phase==='result'){if(reveal)text(c,'reveal',reveal.value?'케이크!':'폭탄!',0,-5,2.5,5);}},timeout(){c.survivors();}};
};

games['Pit Boss']=(c,meta)=>{
 init(c,Infinity);c.bounds={x:7,z:4.2};const spheres=[{x:-6,z:-3,vx:c.rand(7.5,9.5),vz:c.rand(3.5,5.5),r:.85}];let phase=1;const stars=meta.titleId==='superstars';
 return {update(dt){for(const p of c.players){const threats=spheres.map(b=>({x:b.x+b.vx*.3,z:b.z+b.vz*.3})),u=c.input(p,avoid(p,threats,6.6,3.8));c.move(p,u,4.6);}for(const b of spheres){b.x+=b.vx*dt;b.z+=b.vz*dt;b.vx*=Math.exp(-.32*dt);b.vz*=Math.exp(-.32*dt);if(Math.abs(b.x)>7-b.r){b.x=clamp(b.x,-7+b.r,7-b.r);b.vx*=-1;}if(Math.abs(b.z)>4.2-b.r){b.z=clamp(b.z,-4.2+b.r,4.2-b.r);b.vz*=-1;}for(const p of c.players)if(p.alive&&dist(p,b)<b.r+.35)c.eliminate(p);}for(let i=0;i<spheres.length;i++)for(let j=i+1;j<spheres.length;j++){const a=spheres[i],b=spheres[j],d=dist(a,b),r=a.r+b.r;if(d<r){const nx=(b.x-a.x)/(d||1),nz=(b.z-a.z)/(d||1),v=(a.vx-b.vx)*nx+(a.vz-b.vz)*nz;if(v>0){a.vx-=v*nx;a.vz-=v*nz;b.vx+=v*nx;b.vz+=v*nz;}separation(a,b,r);}}if(spheres.every(b=>Math.hypot(b.vx,b.vz)<.12)){if(phase===1){phase=2;const b=spheres[0];for(const z of [-3.1,3.1]){const t=toward({x:6,z},b.x,b.z);spheres.push({x:6,z,vx:t.x*10,vz:t.z*10,r:.85});}}else c.survivors('세 가시공이 모두 멈출 때까지 살아남았습니다.');}if(stars)c.lastStanding();else if(c.players.every(p=>!p.alive))c.complete([],'모두 가시공에 닿았습니다.');c.hint('방향키로 굴러오는 가시공을 피하세요. 첫 공이 멈추면 두 공이 더 떨어져 서로 부딪힙니다!');},render(){c.arena({width:14,depth:8.4,color:'#a6928f'});for(const [i,b]of spheres.entries()){ball(c,'ball'+i,b.x,b.z,'#6f8090',b.r*2,b.r);for(let k=0;k<6;k++){const a=k*TAU/6+c.time;c.draw(`spike${i}-${k}`,'cone',{x:b.x+Math.cos(a)*b.r,y:b.r,z:b.z+Math.sin(a)*b.r,sx:.45,sy:.65,sz:.45,rz:Math.PI/2,ry:-a,color:'#c6cbd0'});}}},timeout(){c.survivors();}};
};

games["Dark 'n Crispy"]=(c,meta)=>{
 init(c,30);c.bounds={x:7,z:4.5};const boss={x:0,z:-2,a:0,mode:'walk',until:2},flames=[];let serial=0;const stars=meta.titleId==='superstars';
 return {update(dt){const living=c.players.filter(p=>p.alive),target=near(boss,living);if(c.time>=boss.until){boss.mode=c.pick(['walk','charge','fire']);boss.until=c.time+(boss.mode==='walk'?2.4:boss.mode==='charge'?1.2:1.5);if(target)boss.a=Math.atan2(target.z-boss.z,target.x-boss.x);}if(boss.mode==='walk'&&target){const v=toward(boss,target.x,target.z);boss.x+=v.x*dt*1.65;boss.z+=v.z*dt*1.65;boss.a=Math.atan2(v.z,v.x);}if(boss.mode==='charge'){boss.x+=Math.cos(boss.a)*dt*5.6;boss.z+=Math.sin(boss.a)*dt*5.6;}boss.x=clamp(boss.x,-6.1,6.1);boss.z=clamp(boss.z,-3.6,3.6);if(boss.mode==='fire'&&Math.floor(c.time*9)!==Math.floor((c.time-dt)*9))flames.push({id:serial++,x:boss.x+Math.cos(boss.a),z:boss.z+Math.sin(boss.a),vx:Math.cos(boss.a)*7,vz:Math.sin(boss.a)*7,until:c.time+.9});for(const f of flames){f.x+=f.vx*dt;f.z+=f.vz*dt;}for(const p of c.players){const u=c.input(p,avoid(p,[boss,...flames.filter(f=>f.until>c.time)],6.4,3.9));c.move(p,u,4.8,false);if(p.alive&&(Math.abs(p.x)>7||Math.abs(p.z)>4.5||dist(p,boss)<1.1||flames.some(f=>f.until>c.time&&dist(p,f)<.7)))c.eliminate(p);}if(stars)c.lastStanding();else if(living.length===0)c.complete([],'모두 어둠 속 위험에 닿았습니다.');c.hint('방향키 이동. 어둠 속 발소리·눈빛을 보고 돌진과 불길을 피하세요. 경기장 밖으로 떨어져도 탈락합니다.');},render(){c.arena({width:14,depth:9,color:'#303e4c'});ball(c,'boss',boss.x,boss.z,'#354353',2,1);for(const side of [-1,1])ball(c,'eye'+side,boss.x+Math.cos(boss.a)*.7+Math.sin(boss.a)*side*.25,boss.z+Math.sin(boss.a)*.7-Math.cos(boss.a)*side*.25,'#eabd66',.16,1.65);flames.forEach(f=>{if(f.until>c.time)ball(c,'flame'+f.id,f.x,f.z,'#e9a76a',.85,.6);});},timeout(){c.survivors('30초 동안 어둠과 불길을 피했습니다.');}};
};

games['Sink or Swim']=(c)=>{
 init(c,30);c.view={size:21,eye:[0,6,22],target:[0,-2,0],noSea:true};const mines=[];let next=0,serial=0;const solo=c.players[0];solo.x=0;solo.y=.7;solo.z=0;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*4;p.y=-2;p.z=0;p.breath=1;p.forced=false;});
 return {update(dt){const living=c.players.slice(1).filter(p=>p.alive),target=living.length?living.reduce((a,b)=>a.y>b.y?a:b):null,u=c.input(solo,{x:target?Math.sign(target.x-solo.x):0,a:!!target&&Math.abs(target.x-solo.x)<.7&&tap(c,solo,.8)});solo.x=clamp(solo.x+u.x*dt*4,-7,7);if(u.ap&&c.time>=next){mines.push({id:serial++,x:solo.x,y:.2});next=c.time+.65;}for(const p of c.players.slice(1)){const danger=mines.filter(m=>m.y>p.y-1&&m.y<p.y+3&&Math.abs(m.x-p.x)<2),v=c.input(p,{x:danger.length?Math.sign(p.x-danger[0].x||p.i-2||1):Math.sin(c.time*.65+p.phase),z:p.breath<.3?-1:p.y> -2.8?1:Math.sin(c.time+p.phase)*.3,a:true});if(!p.alive)continue;if(p.y<-.3)p.breath=Math.max(0,p.breath-dt/5.5);else{p.breath=Math.min(1,p.breath+dt*1.7);if(p.breath>.9)p.forced=false;}if(p.breath===0)p.forced=true;if(p.forced){p.y+=dt*2.4;p.pose='hit';}else if(v.a){p.x+=v.x*dt*3.6;p.y-=v.z*dt*2.8;p.pose='run';}else p.y+=dt*.22;p.x=clamp(p.x,-7.2,7.2);p.y=clamp(p.y,-5.5,0);}for(const m of mines){m.y-=dt*1.9;for(const p of living)if(p.alive&&Math.hypot(m.x-p.x,m.y-(p.y+.4))<.65)c.eliminate(p);}if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'기뢰로 세 잠수 선수를 모두 잡았습니다.');c.hint('1P ←/→ 이동 · A 기뢰. 2~4P 방향키+A 유지로 수영(↑ 수면, ↓ 잠수). 숨이 떨어지면 강제로 떠오릅니다!');},render(){box(c,'pool',0,-1.1,'#739eac',16,1,-3,6);box(c,'waterline',0,0,'#b8d5d9',16,.3,.1,.14);c.draw('boat','sphere',{x:solo.x,y:.3,z:0,sx:2.4,sy:.6,sz:1.5,color:'#c9a172'});mines.forEach(m=>{if(m.y> -6.5)ball(c,'mine'+m.id,m.x,0,'#485869',.75,m.y);});c.players.slice(1).forEach(p=>{if(p.alive){box(c,'airbg'+p.i,p.x,-.2,'#405867',1.3,.13,p.y+2,.14);box(c,'air'+p.i,p.x-(1-p.breath)*.65,-.3,'#ead693',Math.max(.02,p.breath*1.3),.14,p.y+2,.15);}});},timeout(){c.complete([1,2,3],'잠수 팀이 한 명 이상 살아남았습니다.');}};
};

games['Snow Brawl']=(c,meta)=>{
 init(c,60);const helpers=Array.from({length:4},(_,i)=>({i:i+4,x:-6+(i%2)*2,z:(Math.floor(i/2)?2:-2),y:0,vx:0,vz:0,alive:true,held:false,making:0,face:{x:1,z:0},cadence:c.rand(.8,1.5),phase:c.rand(0,1),next:0})),shots=[];let serial=0;c.players.forEach((p,i)=>{p.x=i?4:-6.5;p.z=i?(i-2)*2:0;p.held=false;p.making=0;p.face={x:i?-1:1,z:0};p.next=0;});
 function step(p,u,team,dt){if(!p.alive)return;const dx=u.x||0,dz=u.z||0,n=Math.hypot(dx,dz);if(n>.05){p.face={x:dx/n,z:dz/n};if(!p.making){p.x+=dx/Math.max(1,n)*dt*3.8;p.z+=dz/Math.max(1,n)*dt*3.8;}}p.x=clamp(p.x,team?.55:-7.5,team?7.5:-.55);p.z=clamp(p.z,-4.5,4.5);if(u.bp&&!p.held&&!p.making)p.making=c.time+.42;if(p.making&&c.time>=p.making){p.held=true;p.making=0;}if(u.ap&&p.held&&c.time>=p.next){shots.push({id:serial++,x:p.x+p.face.x*.6,z:p.z+p.face.z*.6,vx:p.face.x*10,vz:p.face.z*10,team,active:true});p.held=false;p.next=c.time+.2;}p.rotation=Math.atan2(-p.face.z,p.face.x);p.pose=p.making?'attack':n>.1?'run':'idle';}
 return {update(dt){const all=[...c.players,...helpers];for(const p of all){const team=p.i>0&&p.i<4,targets=team?[c.players[0]].filter(p=>p.alive):c.players.slice(1).filter(p=>p.alive),target=near(p,targets),incoming=near(p,shots.filter(s=>s.active&&s.team!==team&&Math.abs(s.x-p.x)<3));const ready=p.held&&tap(c,p,p.i>=4?p.cadence:.55),home=team?4:-4-(p.i>=4?p.i%2:1),goal={x:home,z:incoming?clamp(p.z+Math.sign(p.z-incoming.z||p.phase-.5)*1.8,-4,4):target?.z||0};let raw=target?{...(ready?toward(p,target.x,target.z):toward(p,goal.x,goal.z)),a:ready,b:!p.held&&!p.making&&tap(c,p,p.i>=4?p.cadence:.65)}:{};if(p.i<4)step(p,c.input(p,raw),team,dt);else{const old=p.raw||{};step(p,{...raw,ap:raw.a&&!old.a,bp:raw.b&&!old.b},team,dt);p.raw=raw;}}for(const s of shots)if(s.active){s.x+=s.vx*dt;s.z+=s.vz*dt;if(Math.abs(s.x)>9||Math.abs(s.z)>6)s.active=false;}for(let i=0;i<shots.length;i++)for(let j=i+1;j<shots.length;j++){const a=shots[i],b=shots[j];if(a.active&&b.active&&a.team!==b.team&&dist(a,b)<.48)a.active=b.active=false;}for(const s of shots)if(s.active){const targets=s.team?[c.players[0],...helpers]:c.players.slice(1),hit=targets.find(p=>p.alive&&dist(p,s)<.58);if(hit){hit.alive=false;hit.outAt=c.time;s.active=false;}}const solo=!c.players[0].alive,team=c.players.slice(1).every(p=>!p.alive);if(solo||team)c.complete(solo&&team?[]:solo?[1,2,3]:[0],solo&&team?'양쪽이 동시에 얼었습니다.':'상대 주전 선수를 모두 눈뭉치로 맞혔습니다.');c.hint('방향키로 이동·던질 방향 · B 눈뭉치 만들기 · A 던지기. 1P는 조수 4명과 한 편, 팀은 조수가 아닌 1P를 맞혀야 승리!');},render(){c.arena({width:17,depth:11,color:'#d7e4df'});box(c,'center',0,0,'#9bbbc2',.12,10,.02,.04);helpers.forEach((p,i)=>{ball(c,'helper'+i,p.x,p.z,p.alive?'#b79976':'#9ccad8',.9,.5);if(p.held)ball(c,'heldh'+i,p.x+p.face.x*.5,p.z+p.face.z*.5,'#fff3db',.35,.9);});c.players.forEach(p=>{if(p.held)ball(c,'held'+p.i,p.x+p.face.x*.5,p.z+p.face.z*.5,'#fff7e5',.4,1);if(!p.alive)ball(c,'ice'+p.i,p.x,p.z,'#9ccddd',1.5,.7);});shots.forEach(s=>{if(s.active)ball(c,'snow'+s.id,s.x,s.z,'#fff8e8',.4,.8);});},timeout(){c.complete(meta.titleId==='jamboree'?[0,1,2,3]:[],'60초 동안 어느 편도 상대 주전을 모두 얼리지 못했습니다.');}};
};

games['Ball Dozers']=(c)=>{
 init(c,300);c.view={size:24,eye:[0,22,19],target:[0,0,0]};const boards=[-5,5].map((x,t)=>({x,ball:{x,z:-5,vx:0,vz:0,r:t?1.05:.38},pegs:Array.from({length:30},(_,i)=>({x:x+(i%5-2)*1.35,z:-3.7+Math.floor(i/5)*1.6,alive:true,id:i})),done:false}));c.players.forEach(p=>{const t=p.i?1:0;p.x=boards[t].x+(p.i>0?p.i-2:0)*1.3;p.z=-4;p.cool=0;});
 return {update(dt){for(const p of c.players){const t=p.i?1:0,b=boards[t],alive=b.pegs.filter(q=>q.alive&&q.z>b.ball.z-.4),blocking=alive.filter(q=>Math.abs(q.x-b.ball.x)<b.ball.r+.55&&q.z<b.ball.z+2),pool=blocking.length?blocking:alive,sorted=[...pool].sort((a,d)=>dist(a,p)-dist(d,p)),target=sorted[Math.min(p.i>0?p.i-1:0,sorted.length-1)],u=c.input(p,target?{...toward(p,target.x,target.z),a:dist(p,target)<1&&tap(c,p)}:{});c.move(p,u,4.2,false);p.x=clamp(p.x,b.x-3.5,b.x+3.5);p.z=clamp(p.z,-5.4,5.5);if(u.ap&&c.time>=p.cool){const q=near(p,b.pegs.filter(q=>q.alive));if(q&&dist(p,q)<1.05)q.alive=false;p.cool=c.time+.18;p.pose='attack';}}for(const b of boards){const q=b.ball;q.vz+=dt*2.3;q.vx*=Math.exp(-dt);q.vz=clamp(q.vz,-2,3);q.x+=q.vx*dt;q.z+=q.vz*dt;if(Math.abs(q.x-b.x)>3.65-q.r){q.x=clamp(q.x,b.x-3.65+q.r,b.x+3.65-q.r);q.vx*=-.5;}for(const peg of b.pegs)if(peg.alive){const d=dist(q,peg),r=q.r+.28;if(d<r){const nx=(q.x-peg.x)/(d||1),nz=(q.z-peg.z)/(d||1),v=q.vx*nx+q.vz*nz;q.x=peg.x+nx*r;q.z=peg.z+nz*r;if(v<0){q.vx-=v*nx;q.vz-=v*nz;}}}if(q.z>3.4){const half=Math.max(1.25,3.65-(q.z-3.4)*1.05)-q.r;if(Math.abs(q.x-b.x)>half){q.x=b.x+Math.sign(q.x-b.x)*half;q.vx=-Math.sign(q.x-b.x)*Math.abs(q.vz)*.7;}}b.done=q.z>5.6&&Math.abs(q.x-b.x)<1.3-q.r;}const done=boards.map((b,t)=>b.done?t:-1).filter(t=>t>=0);if(done.length)c.complete(done.length>1?[]:SIDE[done[0]],'장애물을 치워 공을 아래 출구로 보냈습니다.');c.hint('이동 · A 망치. 혼자는 작은 공, 세 명 팀은 큰 공이 지나갈 폭을 만들어야 합니다. 공은 실제 경사와 핀 충돌로 굴러갑니다.');},render(){boards.forEach((b,t)=>{box(c,'board'+t,b.x,0,t?'#a8c0cd':'#c6b392',7.5,12,-.2,.4);b.pegs.forEach(q=>{if(q.alive)c.draw(`peg${t}-${q.id}`,'cylinder',{x:q.x,y:.35,z:q.z,sx:.56,sy:.7,sz:.56,color:'#a17d57'});});ball(c,'pinball'+t,b.ball.x,b.ball.z,t?'#679dbd':'#e5ad5b',b.ball.r*2,b.ball.r);ring(c,'exit'+t,b.x,5.7,'#405c6d',2.5,.03);for(const side of [-1,1])line(c,'funnel'+t+'-'+side,{x:b.x+side*3.7,z:3.4},{x:b.x+side*1.25,z:5.7},'#8d9b94',.2,.15);});c.players.forEach(p=>box(c,'hammer'+p.i,p.x+.6,p.z,'#946d50',.7,.4,1.4,.4));},timeout(){c.complete([],'5분 동안 공이 출구에 도달하지 못했습니다.');}};
};

games['Surge and Destroy']=(c)=>{
 init(c,30);const orb={x:0,z:0};c.players[0].x=-9;c.players[0].z=0;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*4;p.z=2;p.lineUntil=0;});
 return {update(){const target=near(orb,c.players.slice(1).filter(p=>p.alive)),u=c.input(c.players[0],target?toward(orb,target.x,target.z):{});orb.x=clamp(orb.x+u.x*c.dt*4,-7,7);orb.z=clamp(orb.z+u.z*c.dt*4,-4.2,4.2);for(const p of c.players.slice(1)){const threat=Math.abs(p.x-orb.x)<1||Math.abs(p.z-orb.z)<1,v=c.input(p,{...avoid(p,[orb],6.8,3.9),a:threat&&tap(c,p,.5)});if(c.time>=p.stun)c.move(p,v,4.7);c.jump(p,c.time>=p.stun?v:{...v,ap:false});if(p.alive){if(dist(p,orb)<.82&&p.y<1.1)c.eliminate(p);else if(p.y<.45&&c.time>=p.lineUntil&&(Math.abs(p.x-orb.x)<.18||Math.abs(p.z-orb.z)<.18)){p.stun=c.time+1;p.lineUntil=c.time+1.3;}}}if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'교차 전기구로 세 명을 모두 잡았습니다.');c.hint('1P ←/→ 가로 전류, ↑/↓ 세로 전류. 2~4P 이동 · A 점프. 전선은 1초 기절, 교차 전기구는 탈락!');},render(){c.arena({width:16,depth:10,color:'#7fa1b0'});box(c,'vertical',orb.x,0,'#f4da76',.13,9,.35,.14);box(c,'horizontal',0,orb.z,'#f4da76',15,.13,.35,.14);ball(c,'orb',orb.x,orb.z,'#efcf71',1.4,.6);box(c,'console',-9,0,'#8595ab',1.5,2,.8,1.6);},timeout(){c.complete([1,2,3],'전기구를 피한 팀원이 남았습니다.');}};
};

games['Stage Fright']=(c)=>{
 init(c,30);c.view={size:25,eye:[0,22,23],target:[0,0,1]};const shots=[];let serial=0;c.players[0].x=0;c.players[0].z=-2;c.players.slice(1).forEach(p=>{p.z=2.5+(p.i-1)*2.5;p.next=0;});
 return {update(dt){const solo=c.players[0],threats=shots.filter(s=>s.active).map(s=>({x:s.x,z:s.z-1})),u=c.input(solo,avoid(solo,threats,6.6,4));c.move(solo,u,4.7,false);solo.x=clamp(solo.x,-6.8,6.8);solo.z=clamp(solo.z,-5,1);for(const p of c.players.slice(1)){p.x=Math.sin(c.time*(.65+p.i*.38)+p.phase)*6.4;const v=c.input(p,{a:Math.abs(solo.x-p.x)<.9&&c.time>p.stun&&tap(c,p,.45)});if(v.ap&&c.time>=p.next&&c.time>=p.stun){shots.push({id:serial++,x:p.x,z:p.z-.6,owner:p.i,active:true,color:p.color});p.next=c.time+.45;}}for(const s of shots)if(s.active){const old=s.z;s.z-=dt*9;for(const p of c.players.slice(1))if(p.i!==s.owner&&p.z<old&&p.z>=s.z&&Math.abs(p.x-s.x)<.85){p.stun=c.time+1.2;s.active=false;}if(s.active&&Math.abs(s.x-solo.x)<.48&&s.z<solo.z+.4&&old>solo.z-.4){s.active=false;c.complete([1,2,3],'무대의 선수를 공으로 맞혔습니다.');}if(s.z< -6)s.active=false;}c.hint('1P 이동해 공 피하기. 2~4P 대포는 각기 다른 속도로 자동 이동 · A 발사. 앞줄 아군을 맞히면 잠깐 기절시킵니다.');},render(){box(c,'stage',0,-2,'#b293a4',15,7,-.25,.5);c.players.slice(1).forEach(p=>{box(c,'rail'+p.i,0,p.z,'#849eab',15,.2,-.1,.2);box(c,'platform'+p.i,p.x,p.z,p.color,2,1.5,0,.3);c.draw('cannon'+p.i,'cylinder',{x:p.x,y:1.1,z:p.z-.55,sx:.85,sy:1.3,sz:.85,rx:Math.PI/2,color:c.time<p.stun?'#ce978c':'#526a7b'});});shots.forEach(s=>{if(s.active)ball(c,'shot'+s.id,s.x,s.z,s.color,.55,.7);});},timeout(){c.complete([0],'30초 동안 대포의 공을 피했습니다.');}};
};

games['Conveyor Bolt']=(c,meta)=>{
 init(c,30);const night=meta.variant==='night'||meta.variant!=='day'&&c.rand()<.5,attack=night?[1,2,3]:[0],defend=night?[0]:[1,2,3],bolts=[],spikes=[];let serial=0,nextSpike=1.3;c.players.forEach(p=>{p.x=(p.i-1.5)*2.5;p.z=0;p.y=attack.includes(p.i)?4:0;p.next=0;});
 return {update(dt){if(!night&&c.time>nextSpike){spikes.push({id:serial++,x:7,z:c.pick([-3,0,3]),at:c.time+.8,until:c.time+9});nextSpike=c.time+2.7;}for(const s of spikes)s.x-=dt*1.6;for(const p of c.players){const airborne=attack.includes(p.i),targets=defend.map(i=>c.players[i]).filter(p=>p.alive),target=near(p,targets),dangers=[...bolts.filter(b=>b.until>c.time),...spikes.filter(s=>s.at<c.time)],raw=airborne?target?{...toward(p,target.x+(!night?-.4:0),target.z),a:dist(p,target)<1.3&&tap(c,p,.75)}:{}:avoid(p,dangers,6.4,3.9),u=c.input(p,raw);c.move(p,u,airborne?4.1:4.7,false);if(!airborne&&!night)p.x-=dt*1.6;p.x=clamp(p.x,-7,7);p.z=clamp(p.z,-4.3,4.3);if(airborne&&u.ap&&c.time>=p.next){bolts.push({id:serial++,x:p.x,z:p.z,y:3.7,land:false,until:c.time+3});p.next=c.time+(night?.8:.6);}}for(const b of bolts){if(!b.land){b.y-=dt*10;if(b.y<=.2){b.y=.2;b.land=true;b.until=c.time+2.2;if(spikes.some(s=>s.at<c.time&&Math.abs(s.x-b.x)<.8&&Math.abs(s.z-b.z)<1.2))b.until=0;}}else if(!night)b.x-=dt*1.6;if(b.until>c.time&&b.y<1.3)for(const i of defend){const p=c.players[i];if(p.alive&&dist(p,b)<(night?.52:.85))c.eliminate(p);}}if(!night)for(const i of defend){const p=c.players[i];if(p.alive&&spikes.some(s=>s.at<c.time&&s.until>c.time&&Math.abs(s.x-p.x)<.65&&Math.abs(s.z-p.z)<1.05))c.eliminate(p);}if(defend.every(i=>!c.players[i].alive))c.complete(attack,'번개와 가시로 회피 선수를 모두 잡았습니다.');c.hint(`${night?'밤: 2~4P가 작은 번개 공격, 1P는 정지 바닥 회피':'낮: 1P가 큰 번개 공격, 2~4P는 가시 컨베이어 회피'} · 구름은 이동+A · 바닥은 이동`);},render(){c.arena({width:15,depth:10,color:night?'#697e91':'#abb39b'});if(!night)for(let i=0;i<12;i++)box(c,'belt'+i,((i*1.4-c.time*1.6+100)%16.8)-8.4,0,'#819990',.08,9,.02,.04);spikes.forEach(s=>{if(s.until>c.time&&s.x> -8)for(let j=0;j<3;j++)c.draw(`spike${s.id}-${j}`,'cone',{x:s.x,y:s.at<c.time?.45:.06,z:s.z+(j-1)*.65,sx:.6,sy:s.at<c.time?.9:.12,sz:.6,color:'#c5c8b9'});});attack.forEach(i=>{const p=c.players[i];c.draw('cloud'+i,'sphere',{x:p.x,y:3.7,z:p.z,sx:2,sy:.5,sz:1.6,color:'#e5ded8'});});bolts.forEach(b=>{if(b.until>c.time)box(c,'bolt'+b.id,b.x,b.z,'#f5d875',night?.35:.65,night?.35:.65,b.y+.45,1);});text(c,'variant',night?'밤 · 역할 반전':'낮 · 움직이는 벨트',0,-6,3,8);},timeout(){c.complete(defend,'회피 선수가 30초 동안 살아남았습니다.');}};
};

games['Crate and Peril']=(c)=>{
 init(c,30);const shells=[{x:-5,z:-2,vx:0,vz:0},{x:5,z:2,vx:0,vz:0}],layout=c.int(0,3),walls=[[-3,-1.6],[3,-1.6],[-3,1.6],[3,1.6]].map(([x,z],i)=>({x:x*(layout===1?.65:1),z:z*(layout===2?1.5:1),w:2.3,h:.35,a:layout===3?(i%2?-.6:.6):i%2?Math.PI/2:0}));let tilt={x:0,z:0};c.players[0].x=-9;c.players[0].z=0;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*1.6;p.z=0;});
 return {update(dt){const target=near(shells[0],c.players.slice(1).filter(p=>p.alive));tilt=c.input(c.players[0],target?toward(shells[0],target.x,target.z):{});for(const b of shells){b.vx=(b.vx+tilt.x*dt*12)*Math.exp(-dt*.9);b.vz=(b.vz+tilt.z*dt*12)*Math.exp(-dt*.9);const speed=Math.hypot(b.vx,b.vz);if(speed>8){b.vx*=8/speed;b.vz*=8/speed;}b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>6.8){b.x=clamp(b.x,-6.8,6.8);b.vx*=-.7;}if(Math.abs(b.z)>4){b.z=clamp(b.z,-4,4);b.vz*=-.7;}walls.forEach(w=>obstacle(b,w,.55));}for(const p of c.players.slice(1)){const u=c.input(p,avoid(p,shells.map(b=>({x:b.x+b.vx*.25,z:b.z+b.vz*.25})),6.6,3.8));c.move(p,u,4.7,false);p.x=clamp(p.x,-7,7);p.z=clamp(p.z,-4.2,4.2);walls.forEach(w=>obstacle(p,w));}const alive=c.players.slice(1).filter(p=>p.alive);for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++)separation(alive[i],alive[j],.65);for(const p of alive)if(shells.some(b=>dist(p,b)<.84))c.eliminate(p);if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'상자를 기울여 가시껍질을 모두에게 굴렸습니다.');c.hint('1P 방향키로 상자를 기울여 두 가시껍질 굴리기. 2~4P는 이동으로 회피! 칸막이와 동료에게도 길이 막힙니다.');},render(){c.arena({width:15,depth:10,color:'#c4ad89'});walls.forEach((w,i)=>c.draw('divider'+i,'box',{x:w.x,y:.4,z:w.z,sx:w.w,sy:.8,sz:w.h,ry:-w.a,color:'#d6c599'}));shells.forEach((b,i)=>{ball(c,'shell'+i,b.x,b.z,'#839a70',1.1,.6);for(let k=0;k<4;k++){const a=k*TAU/4;c.draw(`sp${i}-${k}`,'cone',{x:b.x+Math.cos(a)*.35,y:1,z:b.z+Math.sin(a)*.35,sx:.3,sy:.5,sz:.3,color:'#e7dfc5'});}});text(c,'tilt','↔ ↕',-9,0,2.7,2);},timeout(){c.complete([1,2,3],'상자 속 팀원이 살아남았습니다.');}};
};

games['Ray of Fright']=(c)=>{
 init(c,30);const rays=[];let angle=0,next=0,serial=0;c.players[0].x=0;c.players[0].z=0;c.players[0].y=.7;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*5;p.z=3;});
 return {update(dt){const target=near({x:0,z:0},c.players.slice(1).filter(p=>p.alive)),desired=target?Math.atan2(target.z,target.x):angle,delta=Math.atan2(Math.sin(desired-angle),Math.cos(desired-angle)),u=c.input(c.players[0],{b:delta<-.07,c:delta>.07,a:Math.abs(delta)<.16&&tap(c,c.players[0],.48)});angle+=((u.c?1:0)-(u.b?1:0))*dt*2.2;const tip={x:Math.cos(angle)*1.8,z:Math.sin(angle)*1.8};if(u.ap&&c.time>=next){rays.push({id:serial++,x:tip.x,z:tip.z,vx:Math.cos(angle)*18,vz:Math.sin(angle)*18,until:c.time+1.2,old:{...tip}});next=c.time+.4;}for(const p of c.players.slice(1)){const v=c.input(p,avoid(p,[tip,...rays.filter(r=>r.until>c.time)],6.7,3.9));c.move(p,v,4.8,false);p.x=clamp(p.x,-7,7);p.z=clamp(p.z,-4.2,4.2);if(dist(p,{x:0,z:0})<1.15){const d=Math.hypot(p.x,p.z)||1;p.x=p.x/d*1.15;p.z=p.z/d*1.15;}if(p.alive&&dist(p,tip)<.65)c.eliminate(p);}for(const r of rays)if(c.time<r.until){r.old={x:r.x,z:r.z};r.x+=r.vx*dt;r.z+=r.vz*dt;if(Math.abs(r.x)>7.5){r.x=clamp(r.x,-7.5,7.5);r.vx*=-1;}if(Math.abs(r.z)>4.7){r.z=clamp(r.z,-4.7,4.7);r.vz*=-1;}for(const p of c.players.slice(1))if(p.alive&&segDistance(p,r.old,r)<.38)c.eliminate(p);}if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'반사 레이저로 세 명 모두 잡았습니다.');c.hint('1P B 반시계 / C 시계 회전 · A 레이저. 2~4P 이동. 벽에 튕기는 짧은 광선과 포탑의 빛나는 끝을 피하세요!');},render(){c.arena({width:16,depth:10,color:'#8597b4'});c.draw('turret','cylinder',{x:0,y:.35,z:0,sx:2.2,sy:.7,sz:2.2,color:'#4d6178'});line(c,'barrel',{x:0,z:0},{x:Math.cos(angle)*1.8,z:Math.sin(angle)*1.8},'#82989d',.45,.8);ball(c,'tip',Math.cos(angle)*1.8,Math.sin(angle)*1.8,'#ead487',.6,.8);rays.forEach(r=>{if(r.until>c.time)line(c,'ray'+r.id,r.old,r,'#f4cae0',.14,.65);});},timeout(){c.complete([1,2,3],'레이저를 피한 팀원이 남았습니다.');}};
};

games['Garden Grab']=(c)=>{
 init(c,Infinity);const labels=['A','B','C','D','↑','↓'],teams=[0,1].map(t=>({t,stage:0,turn:0,prompt:c.int(0,5),pull:0,done:false}));c.players.forEach(p=>p.oldDir=0);
 return {update(){const inputs=c.players.map(p=>{const t=teams[p.i<2?0:1],myTurn=t.stage>=8||t.turn===p.i%2;let raw={};if(myTurn&&tap(c,p)){if(t.prompt<4)raw[KEYS[t.prompt]]=true;else raw.z=t.prompt===4?-1:1;}const u=c.input(p,raw),d=u.z<-.5?-1:u.z>.5?1:0,a=KEYS.findIndex(k=>u[k+'p']),result=a>=0?a:d&&d!==p.oldDir?(d<0?4:5):-1;p.oldDir=d;return result;});for(const t of teams){if(t.stage<8){const i=TEAM[t.t][t.turn];if(inputs[i]===t.prompt){t.stage++;t.turn=1-t.turn;t.prompt=c.int(0,5);}}else{for(const i of TEAM[t.t])if(inputs[i]===t.prompt)t.pull++;if(t.pull>=24)t.done=true;}TEAM[t.t].forEach((i,j)=>{const p=c.players[i];p.x=(t.t?4.5:-4.5)+(j?.75:-.75);p.z=2.5;p.pose=inputs[i]===t.prompt?'attack':'idle';p.score=t.stage+Math.min(24,t.pull);});}const done=teams.filter(t=>t.done);if(done.length)c.complete(done.length===2?[]:TEAM[done[0].t],'짝과 번갈아 당기고 마지막 연타로 뿌리를 뽑았습니다.');c.hint('표시 A/B/C/D/↑/↓를 두 사람이 교대로 입력하세요. 마지막에는 둘 다 같은 버튼 연타! 틀린 버튼은 진도가 늘지 않습니다.');},render(){c.arena({color:'#a4b78c'});teams.forEach(t=>{const x=t.t?4.5:-4.5,rise=t.stage*.07+t.pull*.07;c.draw('carrot'+t.t,'cone',{x,y:.2+rise,z:0,sx:2.4,sy:4,sz:2.4,rz:Math.PI,color:'#deaa70'});for(let k=0;k<3;k++)box(c,`leaf${t.t}-${k}`,x+(k-1)*.4,0,'#679366',.4,.5,2.5+rise,1.2);text(c,'prompt'+t.t,`${t.stage<8?`${TEAM[t.t][t.turn]+1}P 차례`:'둘 다 연타'} · ${labels[t.prompt]}`,x,-2.5,4.5,5);box(c,'basket'+t.t,x,4.4,'#a18057',3,1.2,.45,.9);});},timeout(){c.complete([],'아직 뿌리가 남았습니다.');}};
};

games['Pixel Perfect']=(c)=>{
 init(c,108);c.view={size:25,eye:[0,23,20],target:[0,0,-1]};const patterns=['0010001110111110101000100','0111011111111110101001110','0010001010011101010110001'].map(s=>[...s].map(Number)),boards=[Array(25).fill(0),Array(25).fill(0)],sum=[0,0];let target=[],round=0,until=0,pause=0;
 const position=(t,i)=>({x:(t?5.2:-5.2)+(i%5-2)*1.25,z:(Math.floor(i/5)-2)*1.25});
 function next(){round++;until=c.time+20;pause=0;target=[...c.pick(patterns)];boards.forEach(b=>b.fill(0));c.players.forEach(p=>{const t=p.i<2?0:1;p.x=(t?5.2:-5.2)+(p.i%2?.8:-.8);p.z=3;p.y=0;p.vy=0;p.slam=false;p.stun=0;});}next();
 return {update(dt){const toggle=[];for(const p of c.players){const t=p.i<2?0:1,j=p.i%2,b=boards[t],needed=b.map((v,i)=>v!==target[i]?i:-1).filter(i=>i>=0),mine=needed.filter(i=>i%5<3?j===0:j===1),ids=mine.length?mine:needed,goal=near(p,ids.map(i=>({...position(t,i),i})));const u=c.input(p,!pause&&goal?{...toward(p,goal.x,goal.z),a:dist(p,goal)<.28&&tap(c,p,.26)}:{});if(pause||c.time<p.stun)continue;if(!p.slam)c.move(p,u,4.5,false);p.x=clamp(p.x,(t?5.2:-5.2)-3,(t?5.2:-5.2)+3);p.z=clamp(p.z,-3,3);if(u.ap){if(p.y<=0){p.vy=7;p.y=.001;}else{p.slam=true;p.vy=-13;}}if(p.y>0){p.vy-=18*dt;p.y+=p.vy*dt;if(p.y<=0){p.y=0;p.vy=0;if(p.slam){const col=clamp(Math.round((p.x-(t?5.2:-5.2))/1.25)+2,0,4),row=clamp(Math.round(p.z/1.25)+2,0,4);toggle.push({t,i:row*5+col});const mate=c.players[TEAM[t].find(i=>i!==p.i)];if(dist(p,mate)<.7&&mate.y<.5)mate.stun=c.time+1;}p.slam=false;}}p.pose=p.slam?'attack':p.y>0?'jump':'run';}for(const {t,i}of toggle)boards[t][i]=1-boards[t][i];if(!pause){const winners=boards.map((b,t)=>b.every((v,i)=>v===target[i])?t:-1).filter(t=>t>=0);if(winners.length){winners.forEach(t=>sum[t]++);scoreTeams(c,sum);pause=c.time+1;}else if(c.time>=until)pause=c.time+1;}else if(c.time>=pause){if(Math.max(...sum)>=2)c.complete(sum[0]===sum[1]?[]:TEAM[sum[0]>sum[1]?0:1],'샘플 그림 두 개를 먼저 완성했습니다.');else if(round===5)c.complete([],'다섯 라운드 안에 두 그림을 완성하지 못했습니다.');else next();}c.hint(`${round}/5 · 이동, A 점프→공중 A 찍기. 발판 색을 샘플과 똑같이 맞추세요. 동료를 찍으면 기절! 그림당 20초, 2점 선취.`);},render(){for(let t=0;t<2;t++){boards[t].forEach((v,i)=>{const q=position(t,i);box(c,`tile${t}-${i}`,q.x,q.z,v?'#45596a':'#e5decb',1.19,1.19,.02,.12);});text(c,'score'+t,sum[t],t?5.2:-5.2,4.2,1,3);}target.forEach((v,i)=>box(c,'sample'+i,(i%5-2)*.55,-5.6+(Math.floor(i/5)-2)*.55,v?'#45596a':'#eee3c9',.52,.52,.3,.15));text(c,'sampletitle','샘플',0,-8,1.2,3);},timeout(){c.complete([],'두 그림을 완성하지 못했습니다.');}};
};

games['Jump the Gun']=(c,meta)=>{
 init(c,meta.titleId==='jamboree'?180:300);c.view={size:28,eye:[8,24,30],target:[8,1,0]};const boards=[0,1].map(t=>({t,z:t?4:-4,aim:{x:-5,y:1},flight:null,platforms:[{x:-8,y:0}],next:0,targets:Array.from({length:13},(_,i)=>({x:-6+i*2,y:[0,1,2,1,3,2,1,0,1,2,3,1,0][i]*.5})),done:false}));c.players.forEach((p,i)=>{const t=i<2?0:1;p.x=-8;p.z=boards[t].z+(i%2?0:2);p.y=i%2?0:1.2;p.vy=0;p.safe={x:-8,y:0};p.rescue=0;});
 return {update(dt){for(const b of boards){const gun=c.players[b.t*2],runner=c.players[b.t*2+1],ahead=b.targets.find(q=>q.x>runner.safe.x+.5&&!b.platforms.some(p=>p.x===q.x)),target=ahead||b.targets.at(-1),u=c.input(gun,{x:clamp((target.x-b.aim.x)*3,-1,1),z:clamp((b.aim.y-target.y)*4,-1,1),a:Math.abs(b.aim.x-target.x)<.3&&Math.abs(b.aim.y-target.y)<.3&&!b.flight&&tap(c,gun,.4)});b.aim.x=clamp(b.aim.x+u.x*dt*9,-6,18);b.aim.y=clamp(b.aim.y-u.z*dt*3,0,1.5);if(u.ap&&!b.flight&&c.time>=b.next){const q=b.targets.reduce((a,d)=>Math.hypot(d.x-b.aim.x,d.y-b.aim.y)<Math.hypot(a.x-b.aim.x,a.y-b.aim.y)?d:a);if(Math.hypot(q.x-b.aim.x,q.y-b.aim.y)<.8&&!b.platforms.some(p=>p.x===q.x)){b.flight={target:q,at:c.time,until:c.time+.38};b.next=c.time+.4;}}if(b.flight&&c.time>=b.flight.until){b.platforms.push({...b.flight.target});b.flight=null;}const next=b.platforms.filter(q=>q.x>runner.safe.x+.3&&q.x-runner.safe.x<=3.8).sort((a,d)=>a.x-d.x)[0],ground=b.platforms.find(q=>Math.abs(runner.x-q.x)<.65&&Math.abs(runner.z-b.z)<.75&&Math.abs(runner.y-q.y)<.1),goal=next||{x:runner.safe.x,y:runner.safe.y},v=c.input(runner,{x:next?Math.sign(goal.x-runner.x):Math.sign(runner.safe.x-runner.x),z:Math.sign(b.z-runner.z),a:!!next&&!!ground&&tap(c,runner,.3)});if(c.time<runner.rescue)continue;if(ground&&v.ap){runner.vy=7.2;runner.y+=.01;}const old=runner.y;runner.x+=v.x*dt*3.5;runner.z=clamp(runner.z+v.z*dt*3.5,b.z-2,b.z+2);runner.vy-=dt*16;runner.y+=runner.vy*dt;for(const q of b.platforms)if(runner.vy<=0&&old>=q.y-.08&&runner.y<=q.y&&Math.abs(runner.x-q.x)<.65&&Math.abs(runner.z-b.z)<.75){runner.y=q.y;runner.vy=0;runner.safe={x:q.x,y:q.y};}if(runner.y< -4){runner.x=runner.safe.x;runner.y=runner.safe.y;runner.z=b.z;runner.vy=0;runner.rescue=c.time+1.2;}runner.pose=runner.vy?'jump':'run';if(runner.safe.x>=18)b.done=true;}const done=boards.filter(b=>b.done);if(done.length)c.complete(done.flatMap(b=>TEAM[b.t]),'만든 발판을 밟아 목적지에 도착했습니다.');c.hint('1P·3P 방향키 조준, A로 과녁에 발판 탄환. 2P·4P 이동, A 점프. 높이와 간격을 고려해 발판을 만들고 건너세요!');},render(){boards.forEach(b=>{if(b.t===0)box(c,'wall',6,-5.2,'#9facb4',29,.25,1.5,5);b.targets.forEach((q,i)=>ring(c,`target${b.t}-${i}`,q.x,b.z,'#d5ac69',.75,q.y+.07));b.platforms.forEach((q,i)=>{box(c,`platform${b.t}-${i}`,q.x,b.z,i?'#708b9b':'#a9b788',1.25,1.45,q.y-.25,.5);});ring(c,'scope'+b.t,b.aim.x,b.z,'#ef9bad',1.15,b.aim.y+.25);if(b.flight){const a=clamp((c.time-b.flight.at)/.38,0,1);ball(c,'bill'+b.t,-8+(b.flight.target.x+8)*a,b.z,'#526e82',.7,b.flight.target.y+.4);}box(c,'goal'+b.t,19.2,b.z,'#c6ba88',2,2,0,.4);box(c,'cannon'+b.t,-8,b.z+2,'#5d788a',1.2,1.3,.6,1.2);});},timeout(){c.complete([],`${meta.titleId==='jamboree'?'3':'5'}분 안에 발판 코스를 완주하지 못했습니다.`);}};
};

games['Rocky Road']=(c,meta)=>{
 init(c,300);const sizes=[[1,1],[1],[1,1,1],[1.65,1.65],[2.8]],teams=[0,1].map(t=>({t,stage:0,rocks:[],pause:0,done:false}));
 function setup(t){const sizesNow=sizes[t.stage];t.rocks=sizesNow.map((size,i)=>({x:(t.t?4.7:-4.7)+(i-(sizesNow.length-1)/2)*1.8,z:-1,size,hp:size<1.5?3:size<2?8:18,max:size<1.5?3:size<2?8:18}));TEAM[t.t].forEach((i,j)=>{const p=c.players[i];p.x=(t.t?4.7:-4.7)+(j?1:-1);p.z=2;p.y=0;p.vy=0;p.cool=0;p.face={x:0,z:-1};});}teams.forEach(setup);
 return {update(dt){const strikes=[];for(const t of teams){if(t.done)continue;for(const i of TEAM[t.t]){const p=c.players[i],alive=t.rocks.filter(r=>r.hp>0),target=alive[Math.min(i%2,alive.length-1)],goal=target?{x:target.x+(i%2?.25:-.25),z:target.z+target.size*.5+.85}:null,d=goal?dist(p,goal):0,u=c.input(p,!t.pause&&goal?{...toward(p,goal.x,goal.z),a:target.size>1.5&&d<.35&&p.y===0&&tap(c,p,.8),b:d<.45&&tap(c,p,p.y>.2?.32:.24)}:{});if(t.pause||c.time<p.stun)continue;if(d<.45&&p.i>=c.humans){u.x=0;u.z=-.01;}c.move(p,u,4.3,false);if(Math.hypot(u.x,u.z)>.005)p.face=toward({x:0,z:0},u.x,u.z);p.x=clamp(p.x,(t.t?4.7:-4.7)-3.8,(t.t?4.7:-4.7)+3.8);p.z=clamp(p.z,-3.5,4);c.jump(p,u,6.6);for(const r of alive){const radius=r.size*.5+.3,d=dist(p,r);if(d<radius){p.x=r.x+(p.x-r.x)/(d||1)*radius;p.z=r.z+(p.z-r.z)/(d||1)*radius;}}if(u.bp&&c.time>=p.cool){strikes.push({p,t,kick:p.y>.2});p.cool=c.time+(p.y>.2?.45:.22);p.pose='attack';}}}for(const {p,t,kick}of strikes){for(const r of t.rocks)if(r.hp>0){const d=dist(p,r),dx=(r.x-p.x)/(d||1),dz=(r.z-p.z)/(d||1);if(d<r.size*.5+1.05&&dx*p.face.x+dz*p.face.z>.1)r.hp=Math.max(0,r.hp-(kick?2:1));}{const mate=c.players[TEAM[t.t].find(i=>i!==p.i)],d=dist(p,mate);if(d<1.3&&((mate.x-p.x)*p.face.x+(mate.z-p.z)*p.face.z)/(d||1)>.35){if(meta.titleId==='top-100'){mate.x+=p.face.x*.3;mate.z+=p.face.z*.3;mate.cool=Math.max(mate.cool,c.time+.18);mate.hitUntil=c.time+.18;}else mate.stun=c.time+(meta.titleId==='superstars'?.6:1.2);mate.pose='hit';}}}for(const t of teams){if(t.done)continue;if(t.pause){if(c.time>=t.pause){t.pause=0;setup(t);}}else if(t.rocks.every(r=>r.hp<=0)&&TEAM[t.t].every(i=>c.time>=c.players[i].stun)){t.stage++;if(t.stage===5)t.done=true;else t.pause=c.time+1.1;}}const done=teams.filter(t=>t.done);if(done.length)c.complete(done.length===2?[]:TEAM[done[0].t],'다섯 구간의 바위를 모두 치워 출발했습니다.');c.hint(`이동 · A 점프 · B 펀치 / 공중 B 더 강한 발차기. 작은 바위 2→1→3개, 중간 2개, 거대 1개! ${meta.titleId==='top-100'?'동료를 때리면 밀려 공격 흐름이 끊깁니다.':'동료를 때리면 기절해 출발이 늦어집니다.'}`);},render(){c.arena({width:20,depth:11,color:'#b7bea0'});teams.forEach(t=>{const x=t.t?4.7:-4.7;box(c,'road'+t.t,x,0,'#c7bba8',8,10,.01,.02);box(c,'car'+t.t,x,4,'#ba949e',3.3,1.5,.45,.9);t.rocks.forEach((r,i)=>{if(r.hp>0)ball(c,`rock${t.t}-${i}`,r.x,r.z,'#929da0',r.size,r.size*.5);});text(c,'stage'+t.t,`${Math.min(t.stage+1,5)}/5 구간`,x,-4,2.5,4);});},timeout(){c.complete([],'5분 안에 모든 바위를 치우지 못했습니다.');}};
};

games['Clean Team']=(c)=>{
 init(c,300);c.view={size:24,eye:[0,12,27],target:[0,3,0]};const xs=[-2.8,-1.8,0,1.8,2.8],teams=[0,1].map(t=>({t,windows:Array.from({length:12},(_,i)=>({node:Math.floor(i/3)*5+i%3+1,state:0})),done:false,plan:null})),blocks=[[0,2],[1,1],[3,2]];
 const coords=(t,n)=>({x:(t?4.8:-4.8)+xs[n%5],y:Math.floor(n/5)*2,z:0});
 function neighbors(n){const x=n%5,y=Math.floor(n/5),result=[];if(x>0&&!blocks.some(([r,col])=>r===y&&col===x-1))result.push(n-1);if(x<4&&!blocks.some(([r,col])=>r===y&&col===x))result.push(n+1);if(x===0||x===4){if(y>0)result.push(n-5);if(y<3)result.push(n+5);}return result;}
 function route(start,target,occupied){const q=[[start]],seen=new Set([start]);while(q.length){const path=q.shift(),n=path.at(-1);if(n===target)return path;for(const next of neighbors(n))if(!seen.has(next)&&next!==occupied){seen.add(next);q.push([...path,next]);}}return [];}
 // Joint path planning makes one CPU step aside when its partner needs the same narrow corridor.
 function plan(t){const ids=TEAM[t.t],[a,b]=ids.map(i=>c.players[i]),start=[a.node,b.node],key=pair=>pair.join(','),queue=[{pair:start,first:null}],seen=new Set([key(start)]);while(queue.length){const state=queue.shift();for(let role=0;role<2;role++){if(t.windows.some(w=>w.state===role&&w.node===state.pair[role]))return state.first||{role,to:state.pair[role],act:true};}for(let role=0;role<2;role++)for(const to of neighbors(state.pair[role])){if(to===state.pair[1-role])continue;const pair=[...state.pair];pair[role]=to;const k=key(pair);if(!seen.has(k)){seen.add(k);queue.push({pair,first:state.first||{role,to,act:false}});}}}return null;}
 c.players.forEach((p,i)=>{p.node=i%2?0:1;p.transit=null;p.next=0;Object.assign(p,coords(i<2?0:1,p.node));});
 return {update(){for(const t of teams){const members=TEAM[t.t].map(i=>c.players[i]),bothCpu=members.every(p=>p.i>=c.humans);if(bothCpu&&!members.some(p=>p.transit))t.plan=plan(t);for(const i of TEAM[t.t]){const p=c.players[i],mate=members.find(q=>q!==p),role=i%2,current=coords(t.t,p.node);let raw={};if(!p.transit){if(bothCpu){if(t.plan?.role===role){if(t.plan.act)raw.a=tap(c,p,.3);else{const q=coords(t.t,t.plan.to);raw={x:Math.sign(q.x-current.x),z:-Math.sign(q.y-current.y)};}}}else{const goals=t.windows.filter(w=>w.state===role).map(w=>({w,path:route(p.node,w.node,mate.transit?.node??mate.node)})).filter(q=>q.path.length).sort((a,b)=>a.path.length-b.path.length),goal=goals[0];if(goal?.path.length===1)raw.a=tap(c,p,.3);else{const path=goal?.path||route(p.node,role?3:0,mate.node),q=path[1]!==undefined?coords(t.t,path[1]):null;if(q)raw={x:Math.sign(q.x-current.x),z:-Math.sign(q.y-current.y)};}}}const u=c.input(p,raw);if(p.transit){const q=coords(t.t,p.transit.node),a=clamp((c.time-p.transit.at)/.32,0,1);p.x=p.transit.from.x+(q.x-p.transit.from.x)*a;p.y=p.transit.from.y+(q.y-p.transit.from.y)*a;if(a===1){p.node=p.transit.node;p.transit=null;}continue;}let requested=null;if(Math.abs(u.x)>.5)requested=p.node+Math.sign(u.x);else if(Math.abs(u.z)>.5)requested=p.node-Math.sign(u.z)*5;if(requested!==null&&neighbors(p.node).includes(requested)&&requested!==mate.node&&requested!==mate.transit?.node&&c.time>=p.next){p.transit={node:requested,from:{...current},at:c.time};p.next=c.time+.32;}if(u.ap){const w=t.windows.find(w=>w.node===p.node);if(w&&w.state===role){w.state++;p.pose='attack';}}}t.done=t.windows.every(w=>w.state===2);TEAM[t.t].forEach(i=>c.players[i].score=t.windows.filter(w=>w.state===2).length);}const done=teams.filter(t=>t.done);if(done.length)c.complete(done.length===2?[]:TEAM[done[0].t],'모든 창문에 거품을 뿌리고 닦았습니다.');c.hint('1P·3P A 거품, 2P·4P A 닦기. ←/→ 복도, 양끝 사다리에서 ↑/↓ 층 이동. 4층의 창문 12개를 청소하고 양동이·동료는 돌아가세요!');},render(){teams.forEach(t=>{const cx=t.t?4.8:-4.8;box(c,'building'+t.t,cx,-.65,'#a7b4b7',6.7,.5,3.4,8);for(let row=0;row<4;row++)box(c,`ledge${t.t}-${row}`,cx,.15,'#bfaa8c',6.6,.9,row*2-.15,.2);for(const x of [cx-2.8,cx+2.8])for(let k=0;k<19;k++)box(c,`ladder${x}-${k}`,x,.1,'#c9bb9e',.55,.1,k*.35,.07);t.windows.forEach((w,i)=>{const q=coords(t.t,w.node);box(c,`window${t.t}-${i}`,q.x,-.25,w.state===0?'#89735d':w.state===1?'#ebe9d9':'#78acc2',1.35,.2,q.y+.8,1.25);if(w.state===2)ball(c,`guest${t.t}-${i}`,q.x,-.03,'#e9c980',.28,q.y+.55);});blocks.forEach(([r,col],i)=>c.draw(`bucket${t.t}-${i}`,'cylinder',{x:cx+(xs[col]+xs[col+1])/2,y:r*2+.4,z:0,sx:.6,sy:.8,sz:.6,color:'#8d9eac'}));});c.players.forEach(p=>box(c,'tool'+p.i,p.x+.4,.3,p.i%2?'#e7d3ac':'#efb4c6',.25,.3,p.y+1,.5));},timeout(){c.complete([],'5분 동안 모든 창문을 청소하지 못했습니다.');}};
};

games['Burnstile']=(c)=>{
 init(c,Infinity);let angle=.8;c.players.forEach((p,i)=>{p.x=(i<2?-4.5:4.5)+(i%2?.3:-.3);p.z=i%2?1:-1;p.delay=c.rand(.03,.12);});
 return {update(dt){const speed=.65+c.time*.085;angle+=dt*speed;const a={x:Math.cos(angle)*7.1,z:Math.sin(angle)*7.1},b={x:-a.x,z:-a.z},soonA={x:Math.cos(angle+speed*.2)*7.1,z:Math.sin(angle+speed*.2)*7.1},soonB={x:-soonA.x,z:-soonA.z};for(const p of c.players){const cx=p.i<2?-4.5:4.5,hitSoon=segDistance(p,soonA,soonB)<.8,u=c.input(p,{x:(cx-p.x)*.5,z:((p.i%2?.7:-.7)-p.z)*.5,a:hitSoon&&tap(c,p,.18)});c.move(p,u,4,false);c.jump(p,u,6.8);if(p.alive&&(Math.abs(p.x-cx)>2||Math.abs(p.z)>2||segDistance(p,a,b)<.45&&p.y<.65))c.eliminate(p);}const alive=TEAM.map(ids=>ids.some(i=>c.players[i].alive));if(!alive[0]||!alive[1])c.complete(alive[0]===alive[1]?[]:TEAM[alive[0]?0:1],'회전 가시막대에서 마지막 팀이 남았습니다.');c.hint('이동 · A 점프. 회전 가시막대는 점점 빨라집니다. 막대에 닿거나 작은 발판에서 떨어지면 탈락!');},render(){for(let t=0;t<2;t++)box(c,'platform'+t,t?4.5:-4.5,0,t?'#a0b7cb':'#c49ca5',4,4,-.2,.4);const a={x:Math.cos(angle)*7.1,z:Math.sin(angle)*7.1},b={x:-a.x,z:-a.z};line(c,'bar',a,b,'#788992',.25,.38);ball(c,'pivot',0,0,'#bca66c',.7,.4);for(let i=-7;i<=7;i++)c.draw('spike'+i,'cone',{x:Math.cos(angle)*i,y:.65,z:Math.sin(angle)*i,sx:.3,sy:.5,sz:.3,color:'#d1c4b0'});box(c,'lava',0,0,'#c47c72',20,12,-.9,.25);},timeout(){c.complete([],'경기 종료');}};
};

export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['mp6']]));
// Reissues with rule differences have explicit per-title branches above.
supportedTitles['Pit Boss'].push('superstars');
supportedTitles["Dark 'n Crispy"].push('superstars');
supportedTitles['Snow Brawl'].push('jamboree');
supportedTitles['Jump the Gun'].push('jamboree');
supportedTitles['Burnstile'].push('superstars');
supportedTitles['Strawberry Shortfuse'].push('top-100');
supportedTitles['Rocky Road'].push('top-100','superstars');
export const notes={
 'Treasure Trawlers':'신호가 뜨는 숨은 물체를 지연 인양하며 일반 1·금 3점, 폭탄 기절입니다. 45초 전에 시작한 인양은 시간이 끝나도 점수를 받습니다. 보물 배치는 새로 제작했습니다.',
 'Memory Lane':'안내자가 한 번 보여준 꺾이는 경로를 기억해 그대로 걷습니다. 틀린 칸은 구조 지연이며 시범 뒤 5분 제한입니다. 유리 바닥 경로는 새로 제작했습니다.',
 'Hyper Sniper':'네 명이 같은 과녁을 먼저 맞히며 아래로 이동하는 10·30·50·100점 과녁, 조준·발사, 폭군 과녁에 맞히면 점수 0을 적용했습니다. 30초 경기입니다.',
 'Strawberry Shortfuse':'케이크 5·폭탄 5 쟁반을 보여준 뒤 실제 위치를 교환합니다. 각자 10초씩 선택하며 케이크를 다 고르면 다시 섞고 최대 3회 진행합니다. Top100도 같은 선택·생존 규칙과 원형 패드+A 입력을 대응했습니다.',
 'Pit Boss':'첫 공이 멈춘 뒤 두 공을 추가하며 공끼리 충돌해 다시 구릅니다. MP6는 세 공이 모두 멈출 때 생존자를 결정하고 Superstars 자유 모드는 1명만 남으면 즉시 끝납니다. 공 물리는 새로 제작했습니다.',
 "Dark 'n Crispy":'어두운 경기장에서 추적·직선 돌진·불길과 낭떠러지를 피합니다. MP6는 30초 생존, Superstars 자유 모드는 마지막 1명일 때 먼저 종료합니다.',
 'Sink or Swim':'공격자는 수면 위 이동·기뢰 투하, 세 명은 방향+A 수영입니다. 잠수하면 숨이 줄고 바닥나면 수면으로 강제 상승합니다. 물속 이동과 숨 게이지 수치는 새로 조정했습니다.',
 'Snow Brawl':'1P와 조수 4명이 세 명 팀과 싸웁니다. B로 눈 만들기 후 A 던지기, 눈뭉치 상쇄, 조수 대신 주전 1P 명중 승리를 적용했습니다. MP6 60초 무승부, Jamboree 시간 종료 양팀 승리를 분기했습니다.',
 'Ball Dozers':'핀을 실제로 제거해 경사 아래로 공을 굴립니다. 혼자 작은 공·세 명 큰 공이며 큰 공이 지나갈 폭을 확보해야 합니다. 새로 만든 핀 배치와 충돌 물리, 5분 제한입니다.',
 'Surge and Destroy':'원작 두 스틱을 가로·세로 방향 입력에 대응했습니다. 전류선 1초 기절, 교차 구체 탈락, 팀의 점프 회피와 30초 제한입니다.',
 'Stage Fright':'세 대포가 앞줄부터 각기 다른 속도로 자동 왕복합니다. A로 쏜 공은 앞줄 아군을 기절시킬 수 있으며, 30초 안에 솔로 선수를 맞혀야 합니다.',
 'Conveyor Bolt':'시드별 낮·밤 규칙을 모두 구현했습니다. 낮은 1P 공격·가시·이동 벨트·큰 잔류 번개, 밤은 세 명 공격·정지 바닥·작은 번개입니다. meta.variant로 낮/밤을 고정할 수도 있습니다.',
 'Crate and Peril':'기울기 가속·관성·벽 반사로 가시껍질 두 개를 굴립니다. 칸막이와 팀원 충돌, 네 종류의 자체 제작 배치, 30초 생존을 적용했습니다.',
 'Ray of Fright':'L/R을 B/C 회전으로 바꿨습니다. 짧은 레이저의 벽 반사와 빛나는 포신 끝 탈락, 팀 이동 회피와 30초 제한입니다.',
 'Garden Grab':'여섯 버튼을 A/B/C/D/위/아래로 대응했습니다. 팀원 교대 입력 뒤 동일 버튼 연타이며 오답 기절은 없습니다. 뿌리 크기와 교대·연타 횟수는 새로 정했습니다.',
 'Pixel Perfect':'실제 흑백 격자의 색을 공중 A 찍기로 뒤집습니다. 동료 찍기 기절, 그림당 20초, 2점 선취·최대 5라운드 규칙이며 그림은 새로 제작했습니다.',
 'Jump the Gun':'사수가 과녁에 쏜 탄환이 발판이 되고 주자는 실제 높이·중력·점프로 건넙니다. 낙사 후 마지막 발판 구조, 한 발씩 발사, MP6 5분/Jamboree 3분 제한입니다. 코스는 새로 제작했습니다.',
 'Rocky Road':'작은 바위 2→1→3개, 중간 2개, 거대 1개 순서와 더 강한 공중 발차기, MP6의 아군 기절·회복 전 출발 대기, Top100의 긴 기절 없는 간섭, Superstars 공식 영상에서 확인한 짧은 피격 반응을 분기했습니다. 내구도·밀림·피격 시간은 새로 조정했고 5분 제한입니다.',
 'Clean Team':'거품 분사자와 닦는 선수가 동일 창문을 순서대로 처리합니다. 층별 복도·양끝 사다리·통과 불가 양동이·동료 점유를 적용했습니다. 4층·층당 3창문 구조와 5분 제한이며 양동이 배치는 화면 자료를 참고했습니다.',
 'Burnstile':'실제 회전 막대를 점프로 넘으며 회전 속도가 계속 증가합니다. 막대 접촉·발판 이탈은 탈락, 한 명이라도 남은 마지막 팀 승리입니다. 자체 회전 물리와 발판 배치를 사용합니다.'
};
