import{clamp,dist,toward}from'../core.js';
const TAU=Math.PI*2;
const txt=(c,id,text,x=0,z=-5,y=2,sx=5,color='#294550')=>c.draw(id,'text',{text:String(text),x,y,z,sx,sy:.7,color});
const box=(c,id,x,z,color,sx=1,sz=1,y=.1,sy=.2)=>c.draw(id,'box',{x,y,z,sx,sy,sz,color});
const ball=(c,id,x,z,color,s=.6,y=.5)=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color});
const ring=(c,id,x,z,color,s=1,y=.1)=>c.draw(id,'ring',{x,y,z,sx:s,sy:s,sz:s,rx:Math.PI/2,color});
const tap=(c,p,r=p.cadence)=>((c.time+p.phase)%r)<r*.4;
const near=(p,a)=>a.reduce((a,b)=>!a||dist(p,b)<dist(p,a)?b:a,null);
function init(c,limit){c.limit=limit;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=3;p.vy=0;p.phase=c.rand();p.cadence=c.rand(.24,.43);p.cool=0;p.stun=0;});}
function line(c,id,a,b,color,w=.08,y=.08,h=w){c.draw(id,'box',{x:(a.x+b.x)/2,z:(a.z+b.z)/2,y,sx:dist(a,b),sy:h,sz:w,ry:-Math.atan2(b.z-a.z,b.x-a.x),color});}
function avoid(p,threats,x=7,z=4){let best=p,score=-Infinity;for(let k=0;k<20;k++){const a=k*TAU/20,q={x:clamp(p.x+Math.cos(a)*2,-x,x),z:clamp(p.z+Math.sin(a)*2,-z,z)},s=Math.min(...threats.map(t=>dist(q,t)),20)-Math.hypot(q.x,q.z)*.04;if(s>score){score=s;best=q;}}return toward(p,best.x,best.z);}
function pushOut(p,o,r=.4){const dx=p.x-o.x,dz=p.z-o.z,hx=o.w/2+r,hz=o.h/2+r;if(Math.abs(dx)<hx&&Math.abs(dz)<hz){if(hx-Math.abs(dx)<hz-Math.abs(dz))p.x=o.x+Math.sign(dx||1)*hx;else p.z=o.z+Math.sign(dz||1)*hz;}}
function segment(p,a,b){const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((p.x-a.x)*dx+(p.z-a.z)*dz)/(dx*dx+dz*dz||1),0,1);return Math.hypot(p.x-a.x-dx*t,p.z-a.z-dz*t);}
function inside(p,poly){let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.z>p.z)!==(b.z>p.z)&&p.x<(b.x-a.x)*(p.z-a.z)/(b.z-a.z)+a.x)hit=!hit;}return hit;}
function cross(a,b,c,d){const x=b.x-a.x,z=b.z-a.z,u=d.x-c.x,v=d.z-c.z,den=x*v-z*u;if(Math.abs(den)<1e-8)return null;const t=((c.x-a.x)*v-(c.z-a.z)*u)/den,s=((c.x-a.x)*z-(c.z-a.z)*x)/den;return t>=0&&t<=1&&s>=0&&s<=1?{x:a.x+t*x,z:a.z+t*z}:null;}
export const games={};

games["King Boo's Puzzle Attack"]=c=>{
 init(c,Infinity);c.view={size:23,eye:[0,21,24],target:[0,1,0]};const W=12,H=5,board=Array(W*H),colors=['#91b795','#d29dad','#8eb4c9','#d7b48a','#e0cc7d'];let hp=180,serial=0,nextGhost=0,ghosts=[],flashes=[];c.players.forEach((p,i)=>{p.cursor={col:2+i*2,row:3};p.selected=null;p.repeat=0;p.trap=0;p.escape=0;p.plan=null;});
 function matches(){const hit=new Set();for(let r=0;r<H;r++)for(let col=0;col<W;col++){const i=r*W+col,kind=board[i];if(col<W-2&&board[i+1]===kind&&board[i+2]===kind){let j=col;while(j<W&&board[r*W+j]===kind)hit.add(r*W+j++);}if(r<H-2&&board[i+W]===kind&&board[i+2*W]===kind){let j=r;while(j<H&&board[j*W+col]===kind)hit.add(j++*W+col);}}return[...hit];}
 function fill(){for(let i=0;i<board.length;i++){let kind;do{kind=c.int(0,4);}while(i%W>=2&&board[i-1]===kind&&board[i-2]===kind||i>=W*2&&board[i-W]===kind&&board[i-W*2]===kind);board[i]=kind;}}
 function plan(){let best=null,score=-1;for(let a=0;a<board.length;a++)for(const b of[a%W<W-1?a+1:-1,a+W<board.length?a+W:-1]){if(b<0)continue;[board[a],board[b]]=[board[b],board[a]];const hits=matches(),v=hits.length+(hits.some(i=>board[i]===4)?10:0);[board[a],board[b]]=[board[b],board[a]];if(v>score){score=v;best={a,b};}}return score>0?best:null;}
 function refill(hit){const removed=new Set(hit);for(let col=0;col<W;col++){const keep=[];for(let r=H-1;r>=0;r--)if(!removed.has(r*W+col))keep.push(board[r*W+col]);for(let r=H-1;r>=0;r--)board[r*W+col]=keep[H-1-r]??c.int(0,4);}}
 fill();if(!plan())fill();
 return{update(){const commands=[];for(const p of c.players){if(!p.plan||p.selected===null&&c.time>=p.repeat)p.plan=plan();const target=p.selected===null?(p.plan?.a??0):(p.plan?.b??p.selected),tc=target%W,tr=Math.floor(target/W),at=p.cursor.col===tc&&p.cursor.row===tr,raw=p.trap?{a:tap(c,p,.13)}:{x:tc===p.cursor.col?0:Math.sign(tc-p.cursor.col),z:tc===p.cursor.col?Math.sign(tr-p.cursor.row):0,a:p.selected===null&&at&&tap(c,p,.2)},u=c.input(p,raw);if(p.trap){if(u.ap)p.escape++;if(p.escape>=6){p.trap=0;p.escape=0;p.repeat=c.time+.15;p.protectUntil=c.time+.7;}continue;}if(c.time<p.repeat)continue;if(u.ap){p.selected=p.selected===null?p.cursor.row*W+p.cursor.col:null;p.repeat=c.time+.12;}else if(Math.abs(u.x)>.45||Math.abs(u.z)>.45){const dc=Math.abs(u.x)>=Math.abs(u.z)?Math.sign(u.x):0,dr=dc?0:Math.sign(u.z),col=clamp(p.cursor.col+dc,0,W-1),row=clamp(p.cursor.row+dr,0,H-1),to=row*W+col;if(p.selected!==null){if(to!==p.selected)commands.push({p,a:p.selected,b:to});p.selected=null;p.plan=null;}p.cursor={col,row};p.repeat=c.time+.14;}p.x=(p.i-1.5)*4;p.z=6;p.y=0;}
 for(const {p,a,b}of c.shuffle(commands)){if(hp<=0)break;[board[a],board[b]]=[board[b],board[a]];let hit=matches(),cascade=0;while(hit.length&&cascade<8){const lightning=hit.some(i=>board[i]===4),points=lightning?10:hit.length;c.points(p,points);if(lightning){c.players.filter(q=>q!==p).forEach(q=>q.score=Math.max(0,q.score-3));ghosts=[];c.players.forEach(q=>{q.trap=0;q.escape=0;q.protectUntil=c.time+.5;});}hp=Math.max(0,hp-points);flashes.push(...hit.map(i=>({id:serial++,x:(i%W-5.5)*1.1,z:(Math.floor(i/W)-2)*1.2,until:c.time+.35,color:lightning?'#e2cf87':p.color})));refill(hit);if(!hp){c.points(p,10);break;}hit=matches();cascade++;}if(!plan())fill();}
 if(hp<=90&&c.time>=nextGhost){ghosts.push({id:serial++,col:c.rand(1,10),row:c.rand(0,4),phase:c.rand(0,TAU)});nextGhost=c.time+4;}for(const g of ghosts){g.x=clamp(g.col+Math.sin(c.time+g.phase)*1.3,0,W-1);g.z=clamp(g.row+Math.cos(c.time*.7+g.phase)*.6,0,H-1);for(const p of c.players)if(!p.trap&&c.time>=(p.protectUntil||0)&&Math.hypot(p.cursor.col-g.x,p.cursor.row-g.z)<.45){p.trap=1;p.escape=0;p.selected=null;}}flashes=flashes.filter(f=>f.until>c.time);if(hp<=0)c.highest('퍼즐 공격 점수와 마지막 공격 +10점');c.hint('공동 퍼즐판에서 방향키 커서 · A 선택 후 방향키로 이웃과 교환. 같은 모양 3개 이상! 일반 조각 1점씩, 번개 조합 10점·상대 -3. 유령에 잡히면 A 연타로 풀려나세요.');},render(){c.arena({color:'#96a4a7'});board.forEach((kind,i)=>{const x=(i%W-5.5)*1.1,z=(Math.floor(i/W)-2)*1.2;box(c,'cell'+i,x,z,'#bdc8ba',1.03,1.1,.02,.04);if(kind===4){c.draw('item'+i,'cone',{x,y:.38,z,sx:.65,sy:.75,sz:.4,rz:-.4,color:colors[kind]});}else if(kind<2){c.draw('item'+i,'sphere',{x,y:.32,z,sx:.7,sy:.5,sz:.7,color:colors[kind]});line(c,'shellstripe'+i,{x:x-.28,z},{x:x+.28,z},'#e2dcc4',.05,.59);}else{for(let k=0;k<5;k++)ball(c,`petal${i}-${k}`,x+Math.cos(k*TAU/5)*.23,z+Math.sin(k*TAU/5)*.23,colors[kind],.28,.35);ball(c,'item'+i,x,z,'#ded9be',.22,.5);}});c.players.forEach(p=>{const x=(p.cursor.col-5.5)*1.1,z=(p.cursor.row-2)*1.2;ring(c,'cursor'+p.i,x,z,p.color,p.selected!==null?1.2:1,.85);if(p.trap)ball(c,'trap'+p.i,x,z,'#e3e5dd',1.3,1);});ghosts.forEach(g=>{ball(c,'ghost'+g.id,(g.x-5.5)*1.1,(g.z-2)*1.2,'#e4e7df',.8,1);});flashes.forEach(f=>ring(c,'flash'+f.id,f.x,f.z,f.color,1.2,.8));ball(c,'boss',0,-5.5,'#e0e5dc',3.5,2.5);for(const side of[-1,1])ball(c,'eye'+side,side*.6,-4,'#526c7c',.3,2.9);c.draw('crown','cone',{x:0,y:4.6,z:-5.5,sx:1.4,sy:.8,sz:1.4,color:'#dac888'});txt(c,'health',`유령 보스 ${Math.max(0,hp)}/180`,0,-7,5,8);},timeout(){c.complete([]);}};
};

games['Ruins Rumble']=c=>{
 init(c,30);const solo=c.players[0],npcs=Array.from({length:3},(_,i)=>({id:i,x:(i-1)*5,z:-3,alive:true})),blocks=[{x:-3,z:0,w:1.3,h:1.3},{x:3,z:0,w:1.3,h:1.3}];solo.x=0;solo.z=0;solo.y=.4;solo.vx=solo.vz=0;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*5;p.z=3;});
 return{update(dt){const targets=[...c.players.slice(1),...npcs].filter(p=>p.alive),target=near(solo,targets),u=c.input(solo,target?toward(solo,target.x,target.z):{}),n=Math.max(1,Math.hypot(u.x,u.z));solo.vx+=(u.x/n*5.9-solo.vx)*Math.min(1,dt*5);solo.vz+=(u.z/n*5.9-solo.vz)*Math.min(1,dt*5);solo.x=clamp(solo.x+solo.vx*dt,-7,7);solo.z=clamp(solo.z+solo.vz*dt,-4.7,4.7);blocks.forEach(o=>pushOut(solo,o,.7));if(Math.hypot(solo.vx,solo.vz)>.1)solo.rotation=Math.atan2(-solo.vz,solo.vx);for(const p of c.players.slice(1)){const v=c.input(p,avoid(p,[solo],7,4.7));c.move(p,v,3.8,false);p.x=clamp(p.x,-7,7);p.z=clamp(p.z,-4.7,4.7);blocks.forEach(o=>pushOut(p,o));}for(const p of npcs){if(!p.alive)continue;const v=avoid(p,[solo],7,4.7);p.x=clamp(p.x+v.x*dt*3.8,-7,7);p.z=clamp(p.z+v.z*dt*3.8,-4.7,4.7);blocks.forEach(o=>pushOut(p,o));}for(const p of targets)if(dist(solo,p)<1){if(p.i!==undefined)c.eliminate(p);else p.alive=false;}solo.score=6-[...c.players.slice(1),...npcs].filter(p=>p.alive).length;if(solo.score===6)c.complete([0],'선수와 해골 친구 여섯을 모두 잡았습니다.');c.hint('1P 방향키 기울기 조향: 더 빠른 차량으로 여섯 목표 모두 잡기. 2~4P 이동으로 피하기. 해골 친구 하나라도 남으면 30초 뒤 도망 팀 승리!');},render(){c.arena({color:'#b6b3a0'});blocks.forEach((o,i)=>box(c,'pillar'+i,o.x,o.z,'#8e9fa6',o.w,o.h,.8,1.6));box(c,'car',solo.x,solo.z,'#c7a1b1',1.8,1.8,.3,.6);npcs.forEach(p=>{if(p.alive){ball(c,'skull'+p.id,p.x,p.z,'#dedccc',.7,.9);box(c,'bone'+p.id,p.x,p.z,'#c8c5b5',.22,.2,.4,.7);for(const side of[-1,1])ball(c,'socket'+p.id+side,p.x+side*.14,p.z+.25,'#6c8692',.14,1);}});txt(c,'caught',solo.score+'/6',0,-6.5,2,5);},timeout(){c.complete([1,2,3],'선수 또는 해골 친구가 30초 동안 살아남았습니다.');}};
};

games['Hazard Hold']=c=>{
 init(c,30);let facing=0,ringStart=-100,fireStart=-100,windStart=-100;const ready=[0,0,0],solo=c.players[0];solo.x=0;solo.z=-8;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*3;p.z=2;});
 return{update(dt){const options=ready.map((v,i)=>({v,i})).filter(v=>c.time>=v.v),choice=options.length?options[Math.floor(c.time*1.1)%options.length].i:facing,u=c.input(solo,{x:choice===0?-1:choice===2?1:0,z:choice===1?-1:0,a:options.length>0&&tap(c,solo,.35)});if(u.x<-.5)facing=0;else if(u.x>.5)facing=2;else if(u.z<-.5)facing=1;if(u.ap&&c.time>=ready[facing]){ready[facing]=c.time+(facing===2?2.5:4);if(facing===0)ringStart=c.time;else if(facing===1)fireStart=c.time;else windStart=c.time;}const radius=(c.time-ringStart)*4,fireTime=c.time-fireStart,windTime=c.time-windStart;for(const p of c.players.slice(1)){const windActive=windTime>=0&&windTime<1.3,raw=windActive?toward(p,p.x>0?6:-6,p.z):avoid(p,[{x:0,z:0}],6,4.4),v=c.input(p,{...raw,a:Math.abs(Math.hypot(p.x,p.z)-radius)<1.4&&tap(c,p,.25)});c.move(p,v,4.4,false);p.x=clamp(p.x,-6.8,6.8);p.z=clamp(p.z,-4.5,4.5);c.jump(p,v,7);let hit=radius<9&&Math.abs(Math.hypot(p.x,p.z)-radius)<.45&&p.y<.6;if(fireTime>=0&&fireTime<2)for(let k=0;k<4;k++){const a=k*TAU/4,torch={x:Math.cos(a)*5.5,z:Math.sin(a)*4.3},f=a+Math.PI-Math.PI/4+fireTime/2*Math.PI/2,end={x:torch.x+Math.cos(f)*7,z:torch.z+Math.sin(f)*7};if(segment(p,torch,end)<.35&&p.y<1.2)hit=true;}if(windActive){const front=-6+windTime*12;if(p.z<front&&p.z>front-2&&Math.abs(p.x)<2.3+p.z*.08)hit=true;}if(hit)c.eliminate(p);}if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'전기·불·바람으로 상대 팀을 모두 잡았습니다.');c.hint('1P ← 전기 / ↑ 불 / → 바람 선택 · A 작동. 충전 4초/4초/2.5초. 2~4P 이동 · A 점프. 전기 파문, 90도 회전 불길, 정면 바람을 피하세요.');},render(){c.arena({width:16,depth:12,color:'#a9b6ac'});box(c,'console',0,-8,'#b8bba8',10,3,-.2,.4);for(let k=0;k<3;k++){box(c,'switch'+k,(k-1)*3,-8,k===facing?'#e1ce92':'#a4b7b9',1.5,1.5,.4,.8);txt(c,'label'+k,['전기','불','바람'][k],(k-1)*3,-8,2.3,3);}const r=(c.time-ringStart)*4;if(r>=0&&r<9)for(let k=0;k<64;k++)line(c,'electric'+k,{x:Math.cos(k*TAU/64)*r,z:Math.sin(k*TAU/64)*r},{x:Math.cos((k+1)*TAU/64)*r,z:Math.sin((k+1)*TAU/64)*r},'#e1d38d',.12,.2);for(let k=0;k<4;k++){const a=k*TAU/4,torch={x:Math.cos(a)*5.5,z:Math.sin(a)*4.3};box(c,'torch'+k,torch.x,torch.z,'#8ea0a6',.5,.5,.6,1.2);const t=c.time-fireStart;if(t>=0&&t<2){const f=a+Math.PI-Math.PI/4+t/2*Math.PI/2;line(c,'fire'+k,torch,{x:torch.x+Math.cos(f)*7,z:torch.z+Math.sin(f)*7},'#d4a17e',.45,1);}}const w=c.time-windStart;if(w>=0&&w<1.3)for(let i=-4;i<=4;i++)line(c,'wind'+i,{x:i*.45,z:-6+w*12-2},{x:i*.45,z:-6+w*12},'#dde1d1',.035,1);box(c,'fan',0,-6,'#869ca7',4,.6,1,2);},timeout(){c.complete([1,2,3],'팀원이 30초 동안 재난을 피했습니다.');}};
};

games['Line in the Sand']=c=>{
 init(c,30);const cursor={x:0,z:0};let trail=[],drawing=false,closed=[],flashUntil=0,botCenter=null,botAngle=0,botReset=0;const solo=c.players[0];solo.x=0;solo.z=-7;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*4;p.z=1;});
 return{update(dt){const target=near(cursor,c.players.slice(1).filter(p=>p.alive));if(!botCenter&&target){botCenter={x:clamp(target.x,-4.8,4.8),z:clamp(target.z,-2.3,2.3)};botAngle=0;}const goal=botCenter?{x:botCenter.x+Math.cos(botAngle)*2.4,z:botCenter.z+Math.sin(botAngle)*2.4}:cursor;if(dist(cursor,goal)<.35)botAngle+=dt*5;if(botAngle>TAU+.3){botCenter=null;botReset=c.time+.1;}const raw={...toward(cursor,goal.x,goal.z),a:!!botCenter&&c.time>=botReset},u=c.input(solo,raw),held=u.pointer.valid?u.pointer.down:u.a;if(u.pointer.valid&&Number.isFinite(u.pointer.worldX)){cursor.x=clamp(u.pointer.worldX,-7,7);cursor.z=clamp(u.pointer.worldZ,-4.5,4.5);}else{cursor.x=clamp(cursor.x+u.x*dt*10,-7,7);cursor.z=clamp(cursor.z+u.z*dt*10,-4.5,4.5);}if(held){if(!drawing){trail=[{...cursor}];drawing=true;}else if(dist(cursor,trail.at(-1))>.12){const last=trail.at(-1);let polygon=null;for(let i=0;i<trail.length-3;i++){const at=cross(last,cursor,trail[i],trail[i+1]);if(at){polygon=[at,...trail.slice(i+1),{...at}];break;}}trail.push({...cursor});if(polygon&&polygon.length>=4){closed=polygon;flashUntil=c.time+.7;for(const p of c.players.slice(1))if(p.alive&&inside(p,polygon))c.eliminate(p);trail=[{...cursor}];}let length=0;for(let i=1;i<trail.length;i++)length+=dist(trail[i-1],trail[i]);while(length>36&&trail.length>2){length-=dist(trail[0],trail[1]);trail.shift();}}}else{drawing=false;trail=[];}for(const p of c.players.slice(1)){const v=c.input(p,avoid(p,[cursor],6.7,4.3));c.move(p,v,3.7,false);p.x=clamp(p.x,-6.8,6.8);p.z=clamp(p.z,-4.3,4.3);}if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'끊기지 않는 폐곡선으로 세 선수를 모두 가뒀습니다.');c.hint('1P 포인터로 A/마우스를 누른 채 선을 그려 닫힌 모양 만들기. 방향키+A 커서도 가능. 너무 긴 열린 선은 앞부분부터 지워집니다. 2~4P는 이동해 원 밖으로 피하세요.');},render(){c.arena({color:'#d0c09c'});for(let i=1;i<trail.length;i++)line(c,'ink'+i,trail[i-1],trail[i],'#867b70',.07,.035);if(c.time<flashUntil){for(let i=1;i<closed.length;i++)line(c,'closed'+i,closed[i-1],closed[i],'#9a796e',.12,.04);for(let x=-7;x<7;x+=.55)for(let z=-4.5;z<4.5;z+=.55)if(inside({x,z},closed))box(c,'fill'+x+'-'+z,x,z,'#b2a084',.54,.54,.015,.02);}ring(c,'cursor',cursor.x,cursor.z,'#d5a0af',.7,.08);box(c,'stick',cursor.x,cursor.z,'#af9373',.08,.08,.6,1.2);},timeout(){c.complete([1,2,3],'30초 동안 모래 선 밖으로 빠져나갔습니다.');}};
};

games['Block and Roll']=c=>{
 init(c,60);const solo=c.players[0];solo.x=7;solo.z=1;solo.held=true;solo.delivered=0;let serial=0;const boulders=[];c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*5;p.z=-5.5;});
 return{update(dt){const future=boulders.filter(b=>b.active&&b.z<solo.z+.5).map(b=>({x:b.x,z:b.z+1.5})),danger=near(solo,future),goal={x:solo.held?-7:7,z:danger&&dist(solo,danger)<2.3?(solo.z<1?3:-1.5):1},u=c.input(solo,toward(solo,goal.x,goal.z));if(c.time>=solo.stun)c.move(solo,u,solo.held?3.2:5.4,false);solo.x=clamp(solo.x,-7.4,7.4);solo.z=clamp(solo.z,-2,4);if(!solo.held&&solo.x>6.7)solo.held=true;if(solo.held&&solo.x< -6.7){solo.held=false;solo.delivered++;c.points(solo,1);}for(const p of c.players.slice(1)){const prediction=solo.x+(solo.held?-1:1)*(1.2+(p.i-2)*.85),v=c.input(p,{x:clamp((prediction-p.x)*2,-1,1),z:clamp((-6+(p.i-1)*.5-p.z)*2,-1,1),a:Math.abs(prediction-p.x)<1&&c.time>=p.cool&&tap(c,p,.5)});p.x=clamp(p.x+v.x*dt*3.5,-7,7);p.z=clamp(p.z+v.z*dt*3.5,-6.2,-4.8);if(v.ap&&c.time>=p.cool){boulders.push({id:serial++,x:p.x,z:p.z+.65,active:true});p.cool=c.time+3;}}for(const b of boulders){if(!b.active)continue;b.z+=dt*5.3;if(dist(b,solo)<.85&&c.time>=solo.stun){solo.held=false;solo.stun=c.time+.6;b.active=false;}if(b.z>6)b.active=false;}if(solo.delivered===3)c.complete([0],'세 블록을 왼쪽 도착점까지 운반했습니다.');c.hint('1P 이동: 오른쪽에서 자동으로 블록을 들고 왼쪽으로 배달하세요. 빈손은 더 빠릅니다. 2~4P 방향키 이동 · A 바위 투하(3초 간격). 맞으면 운반 중인 블록을 잃습니다.');},render(){box(c,'path',0,1,'#b7b397',16,7,-.2,.4);box(c,'ledge',0,-5.5,'#a9aaa0',16,2,.1,.6);box(c,'source',7,1,'#d4b6bc',1.2,1.2,.6,1.2);for(let i=0;i<solo.delivered;i++)box(c,'delivered'+i,-7,(i-1)*1.2,'#c5b888',1,1,.5,1);if(solo.held)box(c,'carried',solo.x,solo.z-.5,'#d6b9c2',.85,.85,1.15,.85);boulders.forEach(b=>{if(b.active)c.draw('rock'+b.id,'sphere',{x:b.x,y:.6,z:b.z,sx:1.2,sy:1.2,sz:1.2,rx:c.time*5,color:'#899da6'});});txt(c,'count',solo.delivered+'/3',-7,-4,2.5,3);},timeout(){c.complete([1,2,3],'60초 안에 세 블록을 운반하지 못했습니다.');}};
};

games['Tackle Takedown']=(c,meta)=>{
 init(c,30);c.view={size:26,eye:[0,25,24],target:[0,0,0]};const solo=c.players[0];solo.x=0;solo.z=8;solo.boosts=3;solo.boostUntil=0;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*4;p.z=-1-i*4;p.face={x:0,z:1};p.lunge=0;});
 function contact(a0,a1,b0,b1,r){const x=a0.x-b0.x,z=a0.z-b0.z,dx=(a1.x-a0.x)-(b1.x-b0.x),dz=(a1.z-a0.z)-(b1.z-b0.z),A=dx*dx+dz*dz,B=2*(x*dx+z*dz),C=x*x+z*z-r*r;if(C<=0)return 0;if(A<1e-10)return Infinity;const d=B*B-4*A*C;if(d<0)return Infinity;const t=(-B-Math.sqrt(d))/(2*A);return t>=0&&t<=1?t:Infinity;}
 return{update(dt){const old=c.players.map(p=>({x:p.x,z:p.z})),defender=near(solo,c.players.slice(1).filter(p=>c.time>=p.stun)),goal=defender&&dist(solo,defender)<6?{x:solo.x<=defender.x?-5:5,z:solo.z-3}:{x:0,z:-16},u=c.input(solo,{...toward(solo,goal.x,goal.z),a:defender&&dist(solo,defender)<4.8&&solo.boosts>0&&c.time>=solo.boostUntil&&tap(c,solo,.5)});if(u.ap&&solo.boosts>0&&c.time>=solo.boostUntil){solo.boosts--;solo.boostUntil=c.time+.7;}c.move(solo,u,c.time<solo.boostUntil?8:4.2,false);solo.x=clamp(solo.x,-6,6);solo.z=clamp(solo.z,-16,9);for(const p of c.players.slice(1)){const target={x:solo.x,z:solo.z-.8},v=c.input(p,{...toward(p,target.x,target.z),a:dist(p,solo)<2.6&&tap(c,p,.5)});if(c.time<p.lunge){p.x+=p.face.x*dt*8;p.z+=p.face.z*dt*8;}else if(c.time>=p.stun){if(Math.hypot(v.x,v.z)>.05)p.face=toward({x:0,z:0},v.x,v.z);c.move(p,v,3.8,false);if(v.ap){p.lunge=c.time+.45;p.stun=p.lunge+1.1;}}p.x=clamp(p.x,-6,6);p.z=clamp(p.z,-16,9);p.pose=c.time<p.lunge?'attack':c.time<p.stun?'stun':'run';}let hit=Infinity;for(const p of c.players.slice(1))if(c.time<p.lunge)hit=Math.min(hit,contact(old[0],solo,old[p.i],p,.85));const finish=solo.z<=-15?(old[0].z+15)/(old[0].z-solo.z||1):Infinity;if(hit<finish)c.complete([1,2,3],'수비수가 공을 든 선수를 태클했습니다.');else if(finish<=1)c.complete([0],'세 번의 가속을 활용해 터치다운했습니다.');solo.score=3-solo.boosts;c.hint('1P 이동 · A 가속(3회). 아래에서 위 결승으로 공을 운반하세요. 2~4P 이동 · A 태클! 몸으로 닿는 것만으로는 안 되며, 빗나가면 잠시 일어나지 못합니다.');},render(){box(c,'field',0,-3,'#a1b99d',14,28,-.2,.4);for(let k=0;k<8;k++)box(c,'stripe'+k,0,8-k*3,'#d5dac5',13,.06,.025,.04);for(let k=0;k<12;k++)box(c,'goal'+k,(k-5.5),-15,meta.titleId==='top-100'?(k%2?'#d898aa':'#c68091'):meta.titleId==='superstars'?(k%2?'#9ebaa8':'#e0e0cf'):'#dccf9e',1,1,.03,.06);txt(c,'goalText','GOAL',0,-17,1.5,6);ball(c,'football',solo.x,solo.z-.45,'#bca183',.6,.95);for(let i=0;i<solo.boosts;i++)ring(c,'boost'+i,solo.x+(i-1)*.45,solo.z+.6,'#e4ce8d',.3,.06);},timeout(){c.complete([1,2,3],'30초 동안 터치다운을 막았습니다.');}};
};

games['Mob Sleds']=c=>{
 init(c,30);const nodes=Array.from({length:9},(_,i)=>({id:i,x:(i%3-1)*6,z:(Math.floor(i/3)-1)*4})),obstacles=[{x:-3,z:-2,w:4.4,h:2.4},{x:3,z:-2,w:4.4,h:2.4},{x:-3,z:2,w:4.4,h:2.4},{x:3,z:2,w:4.4,h:2.4}],solo=c.players[0];solo.x=0;solo.z=1;c.players.slice(1).forEach((p,i)=>{p.from=[0,2,8][i];p.to=[1,5,7][i];p.f=0;p.collide=0;p.x=nodes[p.from].x;p.z=nodes[p.from].z;});
 function adjacent(id){const out=[];if(id%3)out.push(id-1);if(id%3<2)out.push(id+1);if(id>=3)out.push(id-3);if(id<6)out.push(id+3);return out;}
 return{update(dt){const danger=c.players.slice(1).map(p=>({x:p.x,z:p.z})),u=c.input(solo,avoid(solo,danger,6.4,4.4));c.move(solo,u,4.6,false);solo.x=clamp(solo.x,-6.4,6.4);solo.z=clamp(solo.z,-4.4,4.4);obstacles.forEach(o=>pushOut(solo,o));for(const p of c.players.slice(1)){const targetNode=adjacent(p.to).sort((a,b)=>dist(nodes[a],solo)-dist(nodes[b],solo))[0],goal=nodes[targetNode],v=c.input(p,toward(nodes[p.to],goal.x,goal.z)),a=nodes[p.from],b=nodes[p.to];p.f+=dt*4.6/dist(a,b);if(p.f>=1){const choices=adjacent(p.to).map(id=>{const dir=toward(b,nodes[id].x,nodes[id].z);return{id,dot:dir.x*v.x+dir.z*v.z};}).sort((a,b)=>b.dot-a.dot),forward={x:b.x-a.x,z:b.z-a.z};let to;if(Math.hypot(v.x,v.z)>.3&&choices[0].dot>.4)to=choices[0].id;else to=adjacent(p.to).sort((x,y)=>{const vx={x:nodes[x].x-b.x,z:nodes[x].z-b.z},vy={x:nodes[y].x-b.x,z:nodes[y].z-b.z};return(vy.x*forward.x+vy.z*forward.z)-(vx.x*forward.x+vx.z*forward.z);})[0];const leftover=(p.f-1)*dist(a,b);p.from=p.to;p.to=to;p.f=leftover/dist(nodes[p.from],nodes[p.to]);}const start=nodes[p.from],end=nodes[p.to];p.x=start.x+(end.x-start.x)*p.f;p.z=start.z+(end.z-start.z)*p.f;p.rotation=Math.atan2(start.z-end.z,end.x-start.x);}
 for(let i=1;i<4;i++)for(let j=i+1;j<4;j++){const p=c.players[i],q=c.players[j];if(c.time>=p.collide&&c.time>=q.collide&&p.from===q.to&&p.to===q.from&&dist(p,q)<1.1){for(const a of[p,q]){[a.from,a.to]=[a.to,a.from];a.f=1-a.f;a.collide=c.time+.45;}}}if(c.players.slice(1).some(p=>dist(p,solo)<.85))c.complete([1,2,3],'레일 위 썰매가 도망가는 선수를 잡았습니다.');c.hint('1P는 방향키로 자유 이동. 2~4P 썰매는 자동 이동하며 방향키로 교차로에서만 방향을 선택합니다. 정면 충돌한 썰매는 둘 다 반대로 돌아갑니다. 속도는 모두 같습니다.');},render(){c.arena({color:'#a5c8cd'});nodes.forEach(n=>{for(const id of adjacent(n.id))if(id>n.id)line(c,'rail'+n.id+'-'+id,n,nodes[id],'#d5e2db',1.8,.015,.03);});obstacles.forEach((o,i)=>box(c,'island'+i,o.x,o.z,'#dce5d9',o.w,o.h,.2,.4));c.players.slice(1).forEach(p=>{c.draw('sled'+p.i,'sphere',{x:p.x,y:.25,z:p.z,sx:1.2,sy:.6,sz:1.5,ry:p.rotation,color:'#789eaf'});for(const side of[-1,1])box(c,'ski'+p.i+side,p.x+side*.6,p.z,'#dfdfcf',.08,1.8,.08,.08);});},timeout(){c.complete([0],'30초 동안 세 썰매를 피했습니다.');}};
};

export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['mp9']]));supportedTitles['Tackle Takedown'].push('top-100','superstars');
export const notes={
 "King Boo's Puzzle Attack":'원본 화면처럼 네 커서가 한 퍼즐판을 공유합니다. A 선택 후 이웃 교환·3개 이상 연결·일반 조각 1점씩·번개 조합 10점 및 상대 -3·반체력부터 커서를 잡는 유령·연타 탈출·번개 유령 제거·마지막 공격 +10점입니다. 판 크기·체력180·유령 간격은 원작 숫자 미확인으로 브라우저판 조정값입니다.',
 'Ruins Rumble':'솔로는 더 빠른 관성 차량, 팀은 방향키 이동입니다. 세 선수 외 해골 목표 3명까지 총 여섯을 실제 충돌로 잡아야 승리하며 NPC 하나만 남아도 30초 팀 승리입니다. 지도·차량 물리는 새로 제작했습니다.',
 'Hazard Hold':'방향으로 스위치를 향하고 A로 발동합니다. 전기 원 4초·90도 회전 불길 4초·바람 2.5초 재충전, 팀의 이동/점프와 접촉 즉시 탈락, 30초 생존입니다. 불길 길이·전파 속도·배치는 새로 제작했습니다.',
 'Line in the Sand':'포인터+A 또는 방향키+A로 연속 선을 그립니다. 자기 교차로 생긴 실제 폐곡선의 내부 판정으로만 포획하며 너무 긴 열린 선은 앞에서 삭제합니다. 30초 1대3, 선 길이36은 원작 미확인 수치를 구분한 브라우저판 조정입니다.',
 'Block and Roll':'솔로의 자동 블록 들기/놓기·빈손이 더 빠른 이동·피격 시 운반 중 블록 손실·3개 배달을 구현했습니다. 팀은 위치를 바꿔 바위를 굴리며 각자 3초 재사용, 60초 제한입니다. 지형과 바위 물리는 자체 제작했습니다.',
 'Tackle Takedown':'30초·솔로 가속 3회·팀원의 실제 방향 태클·빗나간 뒤 회복 지연입니다. 접촉과 결승 통과를 같은 프레임 안의 시간으로 비교합니다. MP9/Top100/Superstars 일반 1대3 규칙을 확인했으며 결승판 색도 버전별로 분기했습니다. 운동 수치는 새로 조정했습니다.',
 'Mob Sleds':'팀은 고정 레일에서 자동으로 움직이며 교차로에서만 선택합니다. 솔로와 같은 속도, 정면 충돌 시 두 썰매 방향 반전, 솔로 자유 이동과 30초 생존입니다. 원본 1대3의 네 고리 구조를 참고해 레일을 새로 제작했습니다.'
};
