import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,K=['a','b','c','d'],C=['#ef8ca7','#68aed9','#e8bf5a','#69b496','#b599cc'];
const text=(c,id,v,x=0,z=-4,y=2,sx=5,color='#243e49')=>c.draw(id,'text',{x,y,z,sx,sy:.85,text:v,color});
const box=(c,id,x,z,color,sx=1,sz=1,y=.1,sy=.2)=>c.draw(id,'box',{x,z,y,sx,sy,sz,color});
const ball=(c,id,x,z,color,s=.6,y=.5)=>c.draw(id,'sphere',{x,z,y,sx:s,sy:s,sz:s,color});
function init(c,limit=60){c.limit=limit;c.players.forEach((p,i)=>{p.x=(i-1.5)*4;p.z=3.5;p.cadence=c.rand(.16,.28);p.phase=c.rand(0,.3);});}
const tap=(c,p,rate=p.cadence)=>((c.time+p.phase)%rate)<rate*.4;
function direction(u){return u.x<-.5?0:u.x>.5?1:u.z<-.5?2:u.z>.5?3:-1;}
function directionPress(p,u){const d=direction(u),result=d!==p.oldDir?d:-1;p.oldDir=d;return result;}
const rawDirection=d=>({x:d===0?-1:d===1?1:0,z:d===2?-1:d===3?1:0});
const glyph=['←','→','↑','↓','A'];
const action=u=>K.findIndex(k=>u[k+'p']);
export const games={};

games['Pokey Pummel']=(c,meta)=>{
 init(c,300);const hits=/top.?100/i.test(meta.titleName||meta.titleId||'')?3:5,total=hits*5;
 return {update(){for(const p of c.players){const u=c.input(p,{a:tap(c,p)});if(u.ap&&p.score<total){c.points(p);p.pose='attack';}}const done=c.players.filter(p=>p.score>=total);if(done.length)c.complete(done.map(p=>p.i),'선인장의 모든 마디를 쳐냈습니다.');c.hint(`A 연타: 망치. 마디마다 ${hits}번씩, 머리까지 먼저 치세요!`);},render(){c.arena({color:'#dec894'});c.players.forEach(p=>{const n=Math.max(0,5-Math.floor(p.score/hits));for(let i=0;i<n;i++){ball(c,`pokey${p.i}-${i}`,p.x,0,i===n-1?'#ecc75d':'#d3b64e',.9,.5+i*.8);}box(c,'hammer'+p.i,p.x+.7,p.z-.5,'#7f6149',.8,.45,1.2,.45);text(c,'hits'+p.i,`${p.score}/${total}`,p.x,-2,2,3);});},timeout(){c.complete([],'완전히 제거한 플레이어가 없습니다.');}};
};

games['Sunday Drivers']=(c)=>{
 init(c,300);const signs=['A','B','C','D','↑','↓'];c.players.forEach(p=>{p.target=c.int(0,5);p.lock=0;});
 return {update(){for(const p of c.players){let raw={};if(c.time>p.lock&&tap(c,p)){if(p.target<4)raw[K[p.target]]=true;else raw.z=p.target===4?-1:1;}const u=c.input(p,raw),d=directionPress(p,u),a=action(u),choice=a>=0?a:d===2?4:d===3?5:-1;if(choice>=0&&c.time>=p.lock){if(choice===p.target){c.points(p);p.target=c.int(0,5);p.lock=c.time+.12;}else p.lock=c.time+.7;p.pose='attack';}}const done=c.players.filter(p=>p.score>=10);if(done.length)c.complete([c.pick(done).i],'표시 버튼으로 공 10개를 먼저 쳤습니다.');c.hint('표시된 A/B/C/D/↑/↓를 누르세요. 틀리면 스윙이 빗나가 잠시 늦어집니다.');},render(){c.arena({color:'#93b482'});c.players.forEach(p=>{box(c,'sign'+p.i,p.x,0,'#fff0cf',2,1.7,.5,1.3);text(c,'prompt'+p.i,signs[p.target],p.x,.8,1.3,2,c.time<p.lock?'#ac8b82':'#234554');ball(c,'golf'+p.i,p.x,p.z-1,'#fffbe1',.25,.18);});},timeout(){c.complete([],'10번 성공한 플레이어가 없습니다.');}};
};

games['Tuber Tug']=(c)=>{
 init(c,10);c.players.forEach(p=>{p.pull=0;p.grab=false;p.dir=0;});
 return {update(){for(const p of c.players){const cycle=(c.time+p.phase)%1.7,holding=cycle<1.45;const u=c.input(p,{a:holding,b:holding,z:holding?(Math.floor(c.time/p.cadence)%2?1:-1):0});const grab=u.a&&u.b,d=u.z>.5?1:u.z<-.5?-1:0;if(grab&&d&&d!==p.dir){p.pull++;p.pose='attack';}if(!grab&&p.grab){c.points(p,p.pull);p.pull=0;}p.dir=d;p.grab=grab;}c.hint('A+B를 누른 채 ↑/↓를 번갈아 당기세요. A/B를 놓으면 뽑은 고구마를 바구니에 넣습니다!');},render(){c.arena({color:'#a7b993'});c.players.forEach(p=>{box(c,'vine'+p.i,p.x,.5,'#5d8b54',.12,.15,1,.15+p.pull*.1);for(let i=0;i<Math.min(8,p.pull);i++)ball(c,`tuber${p.i}-${i}`,p.x+Math.sin(i)*.2,.5,'#af7b70',.38,.3+i*.25);box(c,'basket'+p.i,p.x+1.1,2.6,'#b99766',.9,.8,.35,.65);});},timeout(){c.highest('10초 동안 수확한 고구마 수');}};
};

games['Crank to Rank']=(c)=>{
 init(c,300);c.players.forEach(p=>{p.lastAngle=null;p.crank=0;p.rate=c.rand(3.4,5.1);});
 return {update(){for(const p of c.players){const u=c.input(p,{x:Math.cos(c.time*p.rate),z:Math.sin(c.time*p.rate)});if(Math.hypot(u.x,u.z)>.4){const a=Math.atan2(u.z,u.x);if(p.lastAngle!==null){const d=Math.atan2(Math.sin(a-p.lastAngle),Math.cos(a-p.lastAngle));if(d>0&&d<2)p.crank+=d;}p.lastAngle=a;}else p.lastAngle=null;p.score=Math.min(8,p.crank/TAU);p.pose='attack';}const done=c.players.filter(p=>p.score>=8);if(done.length)c.complete(done.map(p=>p.i),'깃발을 꼭대기까지 올렸습니다.');c.hint('방향 입력을 시계 방향으로 원처럼 이어 주세요: → ↓ ← ↑. 반대 방향은 올라가지 않습니다.');},render(){c.arena({color:'#d1cba3'});c.players.forEach(p=>{box(c,'pole'+p.i,p.x,0,'#d6ded4',.1,.1,3.2,6.4);box(c,'flag'+p.i,p.x+.65,0,p.color,1.3,.07,.3+p.score*.7,.75);c.draw('crank'+p.i,'ring',{x:p.x,y:1.2,z:1.4,sx:1,sy:1,sz:1,color:'#876b51'});text(c,'height'+p.i,`${Math.round(p.score/8*100)}%`,p.x,-1.5,6.8,2.5);});},timeout(){c.complete([],'깃발이 정상에 도달하지 못했습니다.');}};
};

games['At the Chomp Wash']=(c)=>{
 init(c,300);const states=c.players.map(p=>({cursor:{x:0,z:0},stain:{x:c.rand(-.9,.9),z:c.rand(-.8,.8)},dirt:1,last:{x:0,z:0}}));
 return {update(dt){for(const p of c.players){const s=states[p.i],target={x:s.stain.x+Math.sin(c.time*15+p.i)*.28,z:s.stain.z+Math.cos(c.time*13+p.i)*.28},u=c.input(p,toward(s.cursor,target.x,target.z));s.cursor.x=clamp(s.cursor.x+u.x*dt*4,-1.4,1.4);s.cursor.z=clamp(s.cursor.z+u.z*dt*4,-1.2,1.2);const travel=dist(s.cursor,s.last);if(dist(s.cursor,s.stain)<.5)s.dirt-=travel/3;s.last={...s.cursor};if(s.dirt<=0){c.points(p);s.dirt=1;s.stain={x:c.rand(-.9,.9),z:c.rand(-.8,.8)};}p.rotation+=dt*.15;}const done=c.players.filter(p=>p.score>=5);if(done.length)c.complete(done.map(p=>p.i),'물감 얼룩 다섯 군데를 모두 닦았습니다.');c.hint('방향키로 스펀지를 움직여 색 얼룩 위를 왕복 문지르세요. 얼룩 5개를 먼저 지우기!');},render(){c.arena({color:'#c4d8c2'});states.forEach((s,i)=>{const x=c.players[i].x;ball(c,'pet'+i,x,0,'#43596a',2.8,1.3);ball(c,'paint'+i,x+s.stain.x,s.stain.z,'#ed9b82',Math.max(.1,s.dirt)*.75,2.45);box(c,'sponge'+i,x+s.cursor.x,s.cursor.z,'#f2d36d',.5,.4,2.8,.2);text(c,'washed'+i,`${c.players[i].score}/5`,x,-2,2.5,2.5);});},timeout(){c.complete([],'아직 물감이 남았습니다.');}};
};

games['Swing Kings']=(c)=>{
 init(c,60);let pitch=0,start=0,flight=1.5,gap=2.2,height=1.3;c.players.forEach(p=>{p.swing=false;p.hit=false;p.aim=0;});
 function next(){pitch++;start=c.time;flight=c.rand(1,1.5);gap=flight+.55;height=c.pick([.9,1.3,1.7]);c.players.forEach(p=>{p.swing=false;p.hit=false;p.aim=flight+c.rand(-.14,.14);});}next();
 return {update(){const t=c.time-start;for(const p of c.players){const u=c.input(p,{a:!p.swing&&t>=p.aim});if(u.ap&&!p.swing){p.swing=true;p.pose='attack';if(Math.abs(t-flight)<.125){p.hit=true;c.points(p);}}}if(t>=gap){if(pitch>=20)Math.max(...c.players.map(p=>p.score))>0?c.highest('20번 던진 공 중 가장 많이 맞혔습니다.'):c.complete([],'무득점 무승부');else next();}c.hint(`${pitch}/20구 · 공이 타석에 오는 순간 A: 스윙. 빠르거나 늦으면 헛스윙입니다.`);},render(){c.arena({color:'#9db880'});const t=c.time-start;c.players.forEach(p=>{box(c,'base'+p.i,p.x,p.z,'#ffefd3',1,1,.02,.07);const z=-4+Math.min(t/flight,1.4)*7.5;ball(c,'ball'+p.i,p.x,p.hit?z-5*(t-flight):z,'#fff6da',.3,p.hit?height+Math.max(0,t-flight)*6:height);box(c,'bat'+p.i,p.x+.6,p.z-.3,'#b98c64',.12,.15,1.4,1.7);});},timeout(){Math.max(...c.players.map(p=>p.score))>0?c.highest():c.complete([],'무득점 무승부');}};
};

games['Punch-a-Bunch']=(c)=>{
 init(c,90);c.players.forEach(p=>{p.last=0;p.power=0;p.aim=c.rand(.82,.99);});
 return {update(){for(const p of c.players){const phase=(c.time-p.last)/1.5;p.power=phase<=1?phase:Math.max(0,2-phase);const u=c.input(p,{a:p.power>p.aim&&c.time-p.last>.2});if(u.ap){const damage=1+Math.floor(p.power*5);c.points(p,damage);p.last=c.time;p.pose='attack';}}const done=c.players.filter(p=>p.score>=30);if(done.length)c.complete(done.map(p=>p.i),'큰 장갑으로 석상을 부쉈습니다.');c.hint('장갑이 가장 커졌을 때 A: 펀치. 급하게 치는 것보다 힘을 모으는 편이 강합니다.');},render(){c.arena({color:'#b7c4a3'});c.players.forEach(p=>{box(c,'statue'+p.i,p.x,0,'#879d98',1.6,1.6,1.5,Math.max(.15,3-p.score/10));ball(c,'glove'+p.i,p.x,2,p.color,.6+p.power*1.1,1.2);text(c,'damage'+p.i,`${Math.min(30,p.score)}/30`,p.x,-2,2.5,3);});},timeout(){c.complete([],'석상을 완전히 부수지 못했습니다.');}};
};

games['Launch Break']=(c)=>{
 init(c,10);c.players.forEach(p=>{p.energy=[0,0,0];p.oldDir=-1;});
 return {update(){const phase=Math.min(2,Math.floor(c.time/3));for(const p of c.players){let raw={};if(phase<2)raw[K[phase]]=tap(c,p);else raw.z=Math.floor(c.time/p.cadence)%2?1:-1;const u=c.input(p,raw),d=directionPress(p,u);if(phase===0&&u.ap||phase===1&&u.bp||phase===2&&d>=0){p.energy[phase]++;p.score=p.energy.reduce((a,b)=>a+b,0);}p.pose='attack';}if(c.time>=9)c.highest('3단 로켓에 모은 총 추진력');c.hint(`3단계 추진력: ${phase===0?'A 연타':phase===1?'B 연타':'↑/↓를 빠르게 번갈아 입력'} · 세 구간 모두 힘을 채우세요!`);},render(){c.arena({color:'#b0c0c4'});c.players.forEach(p=>{c.draw('rocket'+p.i,'cylinder',{x:p.x,y:1.5,z:0,sx:1.3,sy:3,sz:1.3,color:p.color});c.draw('nose'+p.i,'cone',{x:p.x,y:3.5,z:0,sx:1.3,sy:1,sz:1.3,color:'#edf1d6'});p.energy.forEach((e,j)=>box(c,`energy${p.i}-${j}`,p.x+(j-1)*.5,2.3,C[j],.35,.35,e*.05,Math.max(.04,e*.1)));});},timeout(){c.highest();}};
};

games['Growing Up']=(c)=>{
 init(c,28);let round=0,start=0,target=0,limit=2,phase='wait';
 function next(){round++;start=c.time;phase='wait';target=c.int(0,4);limit=Math.max(.65,1.9-round*.13);c.players.forEach(p=>{p.answered=false;p.react=c.rand(.23,Math.min(.85,limit));});}next();
 return {update(){if(phase==='wait'&&c.time-start>.5){phase='answer';start=c.time;}for(const p of c.players){let raw={};if(phase==='answer'&&!p.answered&&c.time-start>p.react){if(target<4)raw[K[target]]=true;else raw.z=-1;}const u=c.input(p,raw),d=directionPress(p,u),a=action(u),choice=a>=0?a:d>=0?4:-1;if(phase==='answer'&&!p.answered&&choice>=0){p.answered=true;if(choice===target)c.points(p,Math.max(1,Math.round((limit-(c.time-start))*100)));}}if(phase==='answer'&&(c.time-start>limit||c.players.every(p=>p.answered))){if(round>=8)c.highest('8번의 반응으로 키운 넝쿨 높이');else next();}c.hint(`${round}/8 · 표시된 버튼을 빨리 누르세요. 빠를수록 넝쿨이 더 자랍니다!`);},render(){c.arena({color:'#bdd4a2'});text(c,'button',phase==='answer'?(target<4?K[target].toUpperCase():'↑'):'?',0,-3,4,4);c.players.forEach(p=>{const h=p.score/130;box(c,'vine'+p.i,p.x,p.z,'#6e9e67',.2,.2,h/2,Math.max(.1,h));p.y=h;});},timeout(){c.highest();}};
};

games['Skipping Class']=(c)=>{
 init(c,55);let round=0,seq=[],start=0,phase='play';
 function next(){round++;seq=Array.from({length:Math.min(5,2+Math.floor(round/2))},()=>c.int(0,4));start=c.time;phase='play';c.players.forEach(p=>{p.seq=0;p.failed=false;p.done=false;p.next=c.time+c.rand(.3,.6);});}next();
 return {update(){for(const p of c.players){const target=seq[p.seq];let raw={};if(phase==='play'&&!p.done&&!p.failed&&c.time>p.next){raw=target===4?{a:true}:rawDirection(target);p.next=c.time+p.cadence+.12;}const u=c.input(p,raw),d=directionPress(p,u),choice=u.ap?4:d;if(phase==='play'&&!p.done&&!p.failed&&choice>=0){if(choice===target){p.seq++;p.y=.3;if(p.seq===seq.length){p.done=true;c.points(p,Math.max(1,Math.round((5-(c.time-start))*10)));}}else p.failed=true;}p.y=Math.max(0,p.y-c.dt*2);}if(phase==='play'&&(c.time-start>=5||c.players.every(p=>p.done||p.failed))){phase='pause';start=c.time;}else if(phase==='pause'&&c.time-start>.6){if(round>=8)c.highest('8라운드 줄넘기 기술 점수');else next();}c.hint(`${round}/8 · 왼쪽부터 ${seq.map(i=>glyph[i]).join(' ')} 입력. 오답은 이 라운드 0점!`);},render(){c.arena({color:'#c3d8b0'});seq.forEach((v,i)=>text(c,'seq'+i,glyph[v],(i-(seq.length-1)/2)*2,-2,3,1.7));c.players.forEach(p=>{c.draw('rope'+p.i,'ring',{x:p.x,y:1,z:p.z,sx:2,sy:2,sz:2,ry:c.time*4,color:p.color});text(c,'progress'+p.i,p.failed?'실수':`${p.seq}/${seq.length}`,p.x,p.z,2.8,2);});},timeout(){c.highest();}};
};

games["Don't Look"]=(c)=>{
 init(c,28);let round=0,start=0,phase='wait',arrows=[],limit=1.5;
 function next(){round++;start=c.time;phase='wait';const n=round<=2?1:round<=6?2:3;arrows=c.shuffle([0,1,2,3]).slice(0,n);limit=Math.max(.65,1.7-round*.08);c.players.forEach(p=>{p.answer=null;p.reaction=c.rand(.25,.6);p.target=c.rand()<.87?c.pick([0,1,2,3].filter(i=>!arrows.includes(i))):c.int(0,3);});}next();
 return {update(){if(phase==='wait'&&c.time-start>.45){phase='play';start=c.time;}for(const p of c.players){const u=c.input(p,phase==='play'&&c.time-start>p.reaction&&p.answer===null?rawDirection(p.target):{});const d=directionPress(p,u);if(phase==='play'&&p.answer===null&&d>=0){p.answer=d;p.rotation=[Math.PI,0,Math.PI/2,-Math.PI/2][d];if(!arrows.includes(d))c.points(p);}}if(phase==='play'&&(c.time-start>=limit||c.players.every(p=>p.answer!==null))){if(round>=10)c.highest('화살표가 가리키지 않은 방향을 본 횟수');else next();}c.hint(`${round}/10 · 화살표가 가리키지 않는 방향을 입력하세요!`);},render(){c.arena({color:'#c2d5b3'});box(c,'screen',0,-2,'#f6e9c7',10,2.4,1.5,1);text(c,'arrows',phase==='play'?arrows.map(i=>glyph[i]).join('   '):'준비',0,-.7,2,8);},timeout(){c.highest();}};
};

games['Goomba Village']=(c)=>{
 init(c,35);const houses=c.shuffle([5,8,11,14,17]).map((n,i)=>({x:(i-2)*3,z:-2,n,arrived:0}));const visitors=[];let phase='watch',chooseAt=0;const assignments=c.shuffle(houses.flatMap((h,i)=>Array(h.n).fill(i)));c.players.forEach(p=>{p.house=2;p.nav=0;p.choice=null;p.memory=[0,0,0,0,0];});let spawned=0;
 return {update(dt){if(phase==='watch'){if(spawned<assignments.length&&c.time>spawned*.19){const h=assignments[spawned];visitors.push({id:spawned,x:c.rand(-7,7),z:4,h,inside:false});spawned++;}for(const v of visitors)if(!v.inside){const h=houses[v.h],d=dist(v,h),step=3.8*dt;if(d<step+.2){v.inside=true;h.arrived++;c.players.forEach(p=>{if(c.rand()>.02)p.memory[v.h]++;});}else{const a=toward(v,h.x,h.z);v.x+=a.x*step;v.z+=a.z*step;}}if(spawned===assignments.length&&visitors.every(v=>v.inside)){phase='choose';chooseAt=c.time;}}for(const p of c.shuffle(c.players)){const available=houses.map((h,i)=>i).filter(i=>!c.players.some(q=>q.choice===i));const want=available.sort((a,b)=>p.memory[b]-p.memory[a])[0]??p.house;const u=c.input(p,{x:phase==='choose'?Math.sign(want-p.house):0,a:phase==='choose'&&p.house===want&&c.time-chooseAt>1+p.phase});if(phase==='choose'&&p.choice===null){if(Math.abs(u.x)>.5&&c.time>p.nav){p.house=clamp(p.house+Math.sign(u.x),0,4);p.nav=c.time+.2;}if(u.ap&&!c.players.some(q=>q.choice===p.house)){p.choice=p.house;p.score=houses[p.choice].n;}}}if(phase==='choose'&&(c.players.every(p=>p.choice!==null)||c.time-chooseAt>=10))c.highest('고른 집에 들어간 새우의 수');c.hint(phase==='watch'?'새우들이 어느 집으로 들어가는지 기억하세요.':'←/→ 집 선택 · A 확정. 선택된 집은 다시 고를 수 없습니다!');},render(){c.arena({color:'#acd0ae'});houses.forEach((h,i)=>{box(c,'house'+i,h.x,h.z,C[i],2.1,2,1,2);c.draw('roof'+i,'cone',{x:h.x,y:2.4,z:h.z,sx:2.8,sy:1.3,sz:2.8,color:'#da9a7a'});box(c,'door'+i,h.x,h.z+1.05,'#41525b',.7,.06,.65,1.3);if(c.ended)text(c,'housecount'+i,h.n,h.x,h.z,3.8,2);});visitors.forEach(v=>{if(!v.inside)ball(c,'visitor'+v.id,v.x,v.z,'#e894a7',.35,.22);});if(phase==='choose')c.players.forEach(p=>text(c,'cursor'+p.i,p.choice===null?`${p.i+1}P`:'✓',houses[p.house].x,0+p.i*.35,.2,1.2,p.color));},timeout(){c.highest();}};
};

games['Card Smarts']=(c)=>{
 init(c,55);let round=1,until=5,phase='choose',revealed=[];c.players.forEach(p=>{p.hand=[1,2,2,3,3,4,4,5];p.cursor=0;p.choice=null;p.bot=c.int(0,7);p.nav=0;});
 return {update(){for(const p of c.players){const u=c.input(p,{x:phase==='choose'?Math.sign(p.bot-p.cursor):0,a:phase==='choose'&&p.cursor===p.bot&&c.time>until-2});if(phase==='choose'){if(Math.abs(u.x)>.5&&c.time>=p.nav){p.cursor=clamp(p.cursor+Math.sign(u.x),0,p.hand.length-1);p.nav=c.time+.16;}if(u.ap)p.choice=p.cursor;}}if(c.time>=until){if(phase==='choose'){revealed=c.players.map(p=>p.hand[p.choice??p.cursor]);const high=Math.max(...revealed);if(!revealed.every(v=>v===revealed[0]))c.players.forEach(p=>{if(revealed[p.i]===high)c.points(p);});c.players.forEach(p=>p.hand.splice(p.choice??p.cursor,1));const done=c.players.filter(p=>p.score>=3);if(done.length)c.complete(done.map(p=>p.i),'큰 숫자 카드로 3점 선취했습니다.');phase='reveal';until=c.time+1.4;}else{if(!c.players[0].hand.length)c.complete([],'모든 손패를 사용했지만 3점 달성자가 없습니다.');round++;phase='choose';until=c.time+5;c.players.forEach(p=>{p.cursor=0;p.choice=null;p.bot=c.int(0,Math.max(0,p.hand.length-1));});}}c.hint(`${round}라운드 · ←/→ 카드 선택, A 제출. 가장 큰 숫자가 1점; 사용한 카드는 사라집니다. 전원 같은 숫자는 0점.`);},render(){c.arena({color:'#537c75'});c.players.forEach(p=>{p.hand.forEach((v,i)=>{const x=p.x+(i-(p.hand.length-1)/2)*.39;box(c,`card${p.i}-${i}`,x,.5,p.cursor===i?'#ffd277':'#fff0cf',.33,.75,.2,.09);text(c,`num${p.i}-${i}`,v,x,.5,.4,.33);});text(c,'chosen'+p.i,phase==='reveal'?revealed[p.i]:p.choice===null?'?':'✓',p.x,-1.5,1.5,2);});},timeout(){c.complete([],'3점 선취자가 없습니다.');}};
};

games['10 to Win']=(c)=>{
 init(c,150);const definitions=[['self',1],['self',2],['self',3],['first',1],['first',2],['last',2],['last',3],['rivals',1],['rivals',2],['rivals',3],['all',1],['all',2]];const cards=c.shuffle(definitions).map((d,i)=>({type:d[0],value:d[1],x:(i%4-1.5)*2.7,z:(Math.floor(i/4)-1)*2,used:false}));const order=c.shuffle([0,1,2,3]);let turn=0,phase='reveal',until=4,cursor={x:0,z:0},last=-1;
 return {update(dt){if(phase==='reveal'&&c.time>=until){phase='choose';until=c.time+10;}const current=order[turn%4];for(const p of c.players){const target=cards.find(q=>!q.used&&q.type==='self'&&q.value===3)||cards.find(q=>!q.used);const u=c.input(p,p.i===current&&phase==='choose'&&target?{...toward(cursor,target.x,target.z),a:dist(cursor,target)<.3&&c.time>until-8.5}:{});if(p.i===current&&phase==='choose'){cursor.x=clamp(cursor.x+u.x*dt*5,-5.5,5.5);cursor.z=clamp(cursor.z+u.z*dt*5,-3,3);if(u.ap||c.time>=until){const list=cards.filter(q=>!q.used),card=list.reduce((a,b)=>dist(cursor,a)<dist(cursor,b)?a:b);if(card&&dist(cursor,card)<1.4){const top=Math.max(...c.players.map(p=>p.score)),low=Math.min(...c.players.map(p=>p.score));card.used=true;last=cards.indexOf(card);const eligible=c.players.filter(q=>card.type==='self'?q.i===current:card.type==='rivals'?q.i!==current:card.type==='first'?q.score===top:card.type==='last'?top!==low&&q.score===low:true);eligible.forEach(q=>c.points(q,card.value));const done=c.players.filter(q=>q.score>=10);if(done.length)c.complete(done.map(q=>q.i),'10점을 먼저 넘었습니다.');phase='result';until=c.time+1.2;}else if(c.time>=until){cursor.x=list[0].x;cursor.z=list[0].z;}}}}if(phase==='result'&&c.time>=until){turn++;phase='choose';until=c.time+10;}c.hint(`${current+1}P 차례 · 방향키 커서, A 패널 뒤집기. 나/상대/선두/꼴찌/모두의 점수가 바뀝니다.`);},render(){c.arena({color:'#baabb4'});const names={self:'나',first:'선두',last:'꼴찌',rivals:'상대',all:'모두'};cards.forEach((q,i)=>{box(c,'panel'+i,q.x,q.z,q.used?'#857d89':'#f8df9d',2.4,1.7,.1,.15);text(c,'effect'+i,phase==='reveal'||i===last?`${names[q.type]} +${q.value}`:'?',q.x,q.z,.45,2);});if(phase==='choose')c.draw('cursor','ring',{x:cursor.x,y:.6,z:cursor.z,rx:Math.PI/2,sx:1,sy:1,sz:1,color:c.players[order[turn%4]].color});},timeout(){c.highest();}};
};

games["Dice 'n' Dash"]=(c)=>{
 init(c,120);c.players.forEach(p=>{p.icons=new Set();p.face=c.int(0,3);p.next=c.rand(.2,.4);p.cool=0;});const symbols=['버섯','꽃','껍질','X'];
 return {update(){for(const p of c.players){if(c.time>=p.next){p.face=(p.face+1)%4;p.next=c.time+.38/(1+p.icons.size*.38);}const u=c.input(p,{a:p.face<3&&!p.icons.has(p.face)&&c.time>=p.cool&&tap(c,p,.1)});if(u.ap&&c.time>=p.cool){p.cool=c.time+.45;p.pose='jump';if(p.face===3)p.icons.clear();else p.icons.add(p.face);p.score=p.icons.size;}}const done=c.players.filter(p=>p.icons.size===3);if(done.length)c.complete(done.map(p=>p.i),'서로 다른 세 암호를 맞혀 문을 열었습니다.');c.hint('A: 주사위 치기. 버섯·꽃·껍질을 하나씩 모으세요. X가 나오면 지금까지 모은 암호가 사라집니다.');},render(){c.arena({color:'#bea982'});c.players.forEach(p=>{box(c,'door'+p.i,p.x,-1,'#8b8572',2.8,.5,1.5,3);box(c,'dice'+p.i,p.x,1,'#edc973',1.6,1.4,1.8,1.3);text(c,'face'+p.i,symbols[p.face],p.x,1.8,1.9,1.7);text(c,'icons'+p.i,[...p.icons].map(i=>symbols[i]).join(' '),p.x,-1,3.7,3);});},timeout(){c.complete([],'문을 열지 못했습니다.');}};
};

games['Foo Me Once']=(c)=>{
 init(c,38);const seq=Array.from({length:7},()=>c.int(0,2));let step=0,phase='reveal',until=3;c.players.forEach(p=>{p.choice=null;p.reaction=c.rand(.4,1.1);p.memory=seq.map(v=>c.rand()<.92?v:c.int(0,2));});
 return {update(){if(phase==='reveal'&&c.time>=until){phase='choose';until=c.time+3;}for(const p of c.players){const raw=phase==='choose'&&p.alive&&p.choice===null&&c.time>until-3+p.reaction?{[K[p.memory[step]]]:true}:{};const u=c.input(p,raw),a=action(u);if(phase==='choose'&&p.alive&&p.choice===null&&a>=0&&a<3)p.choice=a;}if(phase==='choose'&&(c.time>=until||c.players.filter(p=>p.alive).every(p=>p.choice!==null))){for(const p of c.players)if(p.alive){if(p.choice!==seq[step])c.eliminate(p);else{c.points(p);p.z=3.5-step*.8;}}phase='walk';until=c.time+.7;if(c.players.filter(p=>p.alive).length<=1)c.survivors();}if(phase==='walk'&&c.time>=until){step++;if(step>=7)c.survivors('7개 버튼 길을 모두 기억했습니다.');else{phase='choose';until=c.time+3;c.players.forEach(p=>p.choice=null);}}c.hint(phase==='reveal'?`곧 안개가 가립니다: ${seq.map(v=>K[v].toUpperCase()).join(' → ')}`:`${step+1}/7 · 기억한 A/B/C 버튼을 선택하세요. 오답·시간 초과는 탈락!`);},render(){c.arena({color:'#c7dce2'});seq.forEach((v,i)=>{box(c,'step'+i,(i-3)*2.1,-2,'#f5e4ae',1.8,1.8,.1,.2);text(c,'button'+i,phase==='reveal'||i<step?K[v].toUpperCase():'☁',(i-3)*2.1,-2,.5,1.6);});text(c,'progress',`${step+1} / 7`,0,0,2,4);},timeout(){c.survivors();}};
};

games['Meanie Match']=(c)=>{
 init(c,300);const colors=['#ed94a6','#eeba64','#73bdaa','#6eaadd','#9e8ec5','#d7a676','#72a388','#d8839c','#8dbad0','#d1ce76','#9fb79b','#bda4c7'];const icons=['✦','●','▲','◆','★','☾','♠','♣','♥','♦','☀','✿','⊕','◉','▣'];const spaces=colors.map((color,i)=>({x:Math.cos(i/12*TAU)*5.3,z:Math.sin(i/12*TAU)*3.5,color}));const pieces=c.shuffle(icons).map((icon,i)=>({icon,color:i%12}));let phase='reveal',until=5,index=0,turn=0,held=false,cursor={x:0,z:0};c.players.forEach(p=>p.memory=pieces.map(q=>c.rand()<.92?q.color:c.int(0,11)));
 function advance(){const alive=c.players.filter(p=>p.alive);if(alive.length<=1||index>=pieces.length){c.survivors('색 위치 기억하기 종료');return;}do{turn=(turn+1)%4;}while(!c.players[turn].alive);held=false;cursor={x:0,z:0};until=c.time+15;}
 return {update(dt){if(phase==='reveal'&&c.time>=until){phase='place';until=c.time+15;}for(const p of c.players){let target={x:0,z:0};if(held)target=spaces[p.memory[index]??0];const u=c.input(p,p.i===turn&&phase==='place'?{...toward(cursor,target.x,target.z),a:dist(cursor,target)<.25&&tap(c,p,.4)}:{});if(p.i!==turn||phase!=='place')continue;cursor.x=clamp(cursor.x+u.x*dt*5,-6,6);cursor.z=clamp(cursor.z+u.z*dt*5,-4.2,4.2);if(u.ap){if(!held&&Math.hypot(cursor.x,cursor.z)<.7)held=true;else if(held){const slot=spaces.map((s,i)=>({...s,i})).sort((a,b)=>dist(cursor,a)-dist(cursor,b))[0];if(dist(cursor,slot)<.75){if(slot.i===pieces[index].color){c.points(p);index++;}else c.eliminate(p);advance();}}}}if(phase==='place'&&c.time>=until){c.eliminate(c.players[turn]);advance();}c.hint(phase==='reveal'?'각 무늬가 놓인 색을 기억하세요!':`${turn+1}P · 방향키 커서, A로 중앙 무늬를 집어 원래 색 칸에 놓으세요.`);},render(){c.arena({color:'#cab990'});spaces.forEach((s,i)=>box(c,'space'+i,s.x,s.z,s.color,1.35,1.35,.1,.2));if(phase==='reveal')pieces.forEach((q,i)=>{const s=spaces[q.color];text(c,'icon'+i,q.icon,s.x+(i>=12?.35:0),s.z,.5+(i>=12?.6:0),.8);});else if(index<pieces.length){text(c,'current',pieces[index].icon,held?cursor.x:0,held?cursor.z:0,held?1.2:.6,1.3);c.draw('cursor','ring',{x:cursor.x,y:.55,z:cursor.z,rx:Math.PI/2,sx:.9,sy:.9,sz:.9,color:c.players[turn].color});}text(c,'placed',`${index}/15`,0,-5,2,3);},timeout(){c.survivors();}};
};

games['Goomba Gotcha']=(c)=>{
 init(c,30);const wanted=c.int(0,2),names=['동그란 새우','삼각 새우','네모 새우'];const mobs=Array.from({length:25},(_,i)=>({x:c.rand(-7,7),z:c.rand(-3.6,3.3),type:c.int(0,2),vx:c.rand(-.6,.6),vz:c.rand(-.4,.4)}));const curs=c.players.map(p=>({x:p.x,z:0,cool:0}));let replenish=0;
 return {update(dt){if(c.time>replenish){const need=Math.max(0,7-mobs.filter(q=>q.type===wanted).length);c.shuffle(mobs.filter(q=>q.type!==wanted)).slice(0,need).forEach(q=>q.type=wanted);replenish=c.time+1.2;}mobs.forEach(q=>{q.x+=q.vx*dt;q.z+=q.vz*dt;if(Math.abs(q.x)>7)q.vx*=-1;if(Math.abs(q.z)>3.6)q.vz*=-1;});for(const p of c.players){const r=curs[p.i],target=mobs.filter(q=>q.type===wanted).sort((a,b)=>dist(r,a)-dist(r,b))[0];const u=c.input(p,target?{...toward(r,target.x,target.z),a:dist(r,target)<.4&&tap(c,p)}:{});r.x=clamp(r.x+u.x*dt*6,-7.5,7.5);r.z=clamp(r.z+u.z*dt*6,-4,4);if(u.ap&&c.time>r.cool){r.cool=c.time+.12;const q=mobs.reduce((a,b)=>dist(r,a)<dist(r,b)?a:b);if(dist(r,q)<.6){c.points(p,q.type===wanted?1:-1);Object.assign(q,{x:c.rand(-7,7),z:c.rand(-3.6,3.3),type:c.int(0,2)});}}}c.hint(`${names[wanted]}만 선택! 방향키 커서 · A 선택. 정답 +1, 다른 모양 -1.`);},render(){c.arena({color:'#bcd0ae'});mobs.forEach((q,i)=>c.draw('mob'+i,['sphere','cone','box'][q.type],{x:q.x,y:.4,z:q.z,sx:.65,sy:.65,sz:.65,color:'#e995a8'}));curs.forEach((r,i)=>c.draw('cursor'+i,'ring',{x:r.x,y:.8,z:r.z,rx:Math.PI/2,sx:.9,sy:.9,sz:.9,color:c.players[i].color}));text(c,'target',names[wanted],0,-5,2,7);},timeout(){c.highest('지정된 생물을 가장 많이 골랐습니다.');}};
};

const tileIcon=(c,id,type,x,z,scale=1)=>{const kinds=['sphere','cone','box','ring'];c.draw(id,kinds[type],{x,y:.25,z,sx:.65*scale,sy:.35*scale,sz:.65*scale,rx:type===3?Math.PI/2:0,color:C[type]});};
games['Found it? Pound it!']=(c)=>{
 init(c,48);c.bounds={x:5.7,z:3.7};let round=0,target=0,remaining=3,start=0,tiles=[];
 function next(){round++;target=c.int(0,3);remaining=3;start=c.time;const correct=c.shuffle(Array.from({length:24},(_,i)=>i)).slice(0,3);tiles=Array.from({length:24},(_,i)=>({x:(i%6-2.5)*2,z:(Math.floor(i/6)-1.5)*2,type:correct.includes(i)?target:c.pick([0,1,2,3].filter(v=>v!==target)),used:false}));}next();
 return {update(){const landings=[];for(const p of c.players){const goal=tiles.filter(t=>!t.used&&t.type===target).sort((a,b)=>dist(p,a)-dist(p,b))[0];const u=c.input(p,goal?{...toward(p,goal.x,goal.z),a:p.y>.2?!p.lastA:dist(p,goal)<.65&&!p.lastA}:{});p.lastA=u.a;if(c.time<(p.stun||0))continue;c.move(p,u,5);if(u.ap&&p.y>.15){p.pound=true;p.vy=-12;}const y=p.y;c.jump(p,u);if(y>0&&p.y===0&&p.pound){p.pound=false;const t=tiles.reduce((a,b)=>dist(p,a)<dist(p,b)?a:b);if(dist(p,t)<.8)landings.push({p,t});}}for(const {p,t} of c.shuffle(landings)){if(t.type===target&&!t.used){t.used=true;c.points(p,remaining);remaining--;}else if(t.type!==target)p.stun=c.time+1;}if(remaining===0||c.time-start>=12){if(round>=3)c.highest('3라운드 정답 발판의 순서 점수');else next();}c.hint(`${round}/3 · 위의 무늬와 같은 바닥을 찍으세요. A 점프→공중 A. 정답 순서대로 3·2·1점, 오답은 기절.`);},render(){c.arena({color:'#adbab6'});tiles.forEach((t,i)=>{box(c,'tile'+i,t.x,t.z,t.used?'#78988e':'#eee2c4',1.88,1.88,.03,.12);if(!t.used)tileIcon(c,'icon'+i,t.type,t.x,t.z);});box(c,'sample',0,-5.5,'#f8eac9',3.5,1.6,.2,.3);tileIcon(c,'target',target,0,-5.5,2);},timeout(){c.highest();}};
};

games['Fruit Scoot Scurry']=(c)=>{
 init(c,30);const cells=Array.from({length:16},(_,i)=>({x:(i%4-1.5)*2.3,z:(Math.floor(i/4)-1.5)*2.3,fruit:0}));[0,3,12,15].forEach((n,i)=>{Object.assign(c.players[i],{cell:n,x:cells[n].x,z:cells[n].z,hop:null,next:0});});let spawn=0;
 return {update(dt){if(c.time>spawn){const options=cells.filter(s=>!s.fruit);if(options.length)c.pick(options).fruit=c.rand()<.18?3:1;spawn=c.time+c.rand(.3,.6);}const attempts=[];for(const p of c.players){const here=cells[p.cell],targets=cells.map((s,i)=>({...s,i})).filter(s=>s.fruit).sort((a,b)=>dist(here,a)-dist(here,b)),goal=targets[0];let d=-1;if(goal){const col=p.cell%4,row=Math.floor(p.cell/4);const neighbors=[col>0?{i:p.cell-1,d:0}:null,col<3?{i:p.cell+1,d:1}:null,row>0?{i:p.cell-4,d:2}:null,row<3?{i:p.cell+4,d:3}:null].filter(Boolean).filter(n=>!c.players.some(q=>q!==p&&(q.hop?.to??q.cell)===n.i)).sort((a,b)=>dist(cells[a.i],goal)-dist(cells[b.i],goal));if(neighbors.length)d=neighbors[0].d;}const u=c.input(p,rawDirection(d)),dir=direction(u);if(!p.hop&&cells[p.cell].fruit){c.points(p,cells[p.cell].fruit);cells[p.cell].fruit=0;}if(p.hop){p.hop.t+=dt;const t=Math.min(1,p.hop.t/.22),a=cells[p.hop.from],b=cells[p.hop.to];p.x=a.x+(b.x-a.x)*t;p.z=a.z+(b.z-a.z)*t;p.y=Math.sin(t*Math.PI)*.7;if(t===1){p.cell=p.hop.to;p.hop=null;p.y=0;if(cells[p.cell].fruit){c.points(p,cells[p.cell].fruit);cells[p.cell].fruit=0;}}}else if(dir>=0&&c.time>=p.next){const col=p.cell%4,row=Math.floor(p.cell/4);let to=p.cell;if(dir===0&&col>0)to--;if(dir===1&&col<3)to++;if(dir===2&&row>0)to-=4;if(dir===3&&row<3)to+=4;if(to!==p.cell)attempts.push({p,to});p.next=c.time+.3;}}
 let allowed=attempts.filter(a=>!attempts.some(b=>b!==a&&b.to===a.to)&&!c.players.some(q=>q!==a.p&&q.hop?.to===a.to));for(let pass=0;pass<4;pass++)allowed=allowed.filter(a=>!c.players.some(q=>q!==a.p&&!q.hop&&q.cell===a.to&&!allowed.some(b=>b.p===q)));for(const a of attempts){if(allowed.includes(a))a.p.hop={from:a.p.cell,to:a.to,t:0};else a.p.next=c.time+.35;}c.hint('방향 입력: 인접 돌기둥으로 점프. 같은 칸을 향해 동시에 뛰면 서로 튕깁니다. 과일 1점·묶음 3점!');},render(){cells.forEach((s,i)=>{c.draw('stone'+i,'cylinder',{x:s.x,y:-.65,z:s.z,sx:1.65,sy:1.3,sz:1.65,color:'#91aba6'});for(let n=0;n<s.fruit;n++)ball(c,`fruit${i}-${n}`,s.x+(n-1)*.3,s.z,'#f2b669',.4,.35);});},timeout(){c.highest('30초 동안 모은 과일');}};
};

export const notes={
 'Pokey Pummel':'원작별 마디당 타수를 구분합니다: MP7·Superstars 5타, The Top 100 3타. 망치는 A 연타로 조작합니다.',
 'Sunday Drivers':'원작 여섯 버튼을 A/B/C/D/위/아래에 재배치했습니다. 표시 버튼으로 공 10개를 먼저 치는 규칙입니다.',
 'Tuber Tug':'Wii를 잡고 흔들고 놓는 동작을 A+B 유지·상하 교대·버튼 놓기로 바꾸었습니다. 놓아야 바구니에 수확합니다.',
 'Crank to Rank':'리모컨 원운동/스타일러스 회전을 원형 방향 입력으로 바꾸었습니다. 반대 회전은 깃발을 올리지 않습니다. 깃대 길이는 새로 조정했습니다.',
 'At the Chomp Wash':'Wii 또는 스타일러스 문지르기를 스펀지 커서 이동으로 바꾸었습니다. 다섯 얼룩 제거 규칙은 유지했습니다.',
 'Swing Kings':'스윙은 A 버튼으로 입력합니다. 20구의 높이와 도착 시간이 달라지며 타이밍이 맞을 때만 점수를 얻습니다.',
 'Punch-a-Bunch':'리모컨 펀치를 A로 바꾸었습니다. 장갑이 커질 때 강해지는 규칙을 유지하고 석상 내구도는 브라우저판에 맞게 조정했습니다.',
 'Launch Break':'세 구간의 조작을 A 연타, B 연타, 상하 교대로 옮겼습니다. 구간 길이는 각 3초로 조정했습니다.',
 'Growing Up':'8라운드 반응 속도에 따라 넝쿨 높이가 달라집니다. 원작의 입력 종류를 네 동작 버튼과 방향 입력으로 재배치했습니다.',
 'Skipping Class':'8라운드의 순서 입력과 빠른 완성 점수를 유지했습니다. 줄넘기 기술·순서·시간 배분은 새로 제작했습니다.',
 "Don't Look":'10라운드에서 화살표가 가리키지 않은 방향을 선택합니다. 후반에는 동시에 세 방향을 피해야 합니다.',
 'Goomba Village':'실제로 집에 들어가는 새우를 세고 가장 많은 집을 고릅니다. 마을 배치와 등장 순서는 새로 제작했습니다.',
 'Card Smarts':'1~5의 원작 손패 구성, 사용 카드 소모, 최고 카드 1점·3점 선취를 유지했습니다.',
 '10 to Win':'원작 12패널의 나/상대/선두/꼴찌/전체 점수 효과를 각각 적용했습니다. 처음 내용을 본 뒤 차례로 뒤집습니다.',
 "Dice 'n' Dash":'세 그림 암호 수집, 중복 무효, X로 초기화, 성공할수록 빨라지는 주사위를 구현했습니다.',
 'Foo Me Once':'일곱 버튼 기억 경로를 A/B/C로 재배치했습니다. 각 단계 3초 안에 골라야 합니다.',
 'Meanie Match':'원작 적 캐릭터 15종을 서로 다른 문양으로 바꾸었습니다. 12색 위치를 기억해 차례로 옮기고 오답이면 탈락합니다.',
 'Goomba Gotcha':'세 종류 생물을 동그라미·삼각형·네모 새우로 표현했습니다. 지정 종류 +1·오답 -1 규칙을 유지했습니다.',
 'Found it? Pound it!':'정답 세 칸의 순서 점수 3·2·1점과 3라운드를 유지했습니다. 무늬·발판 배치는 새로 제작했습니다.',
 'Fruit Scoot Scurry':'4×4 칸 이동, 동시 목적지 충돌, 과일 묶음 3점을 구현했습니다. 돌기둥과 과일은 새로 제작했습니다.'
};

export const supportedTitles={
 'Pokey Pummel':['mp7','top-100','superstars'],'Sunday Drivers':['mp6'],'Tuber Tug':['mp9'],
 'Crank to Rank':['mp8','top-100'],'At the Chomp Wash':['mp8','top-100'],'Swing Kings':['mp8'],
 'Punch-a-Bunch':['mp8'],'Launch Break':['mp9'],'Growing Up':['mp9'],'Skipping Class':['mp9'],
 "Don't Look":['mp9','top-100'],'Goomba Village':['mp9'],'Card Smarts':['mp9'],'10 to Win':['mp9'],
 "Dice 'n' Dash":['mp10'],'Foo Me Once':['mp10'],'Meanie Match':['mp10'],'Goomba Gotcha':['mp10'],
 'Found it? Pound it!':['mp10'],'Fruit Scoot Scurry':['mp10']
};
