import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2;
const txt=(c,id,text,x=0,z=-5,y=2,sx=5,color='#294550')=>c.draw(id,'text',{text:String(text),x,y,z,sx,sy:.7,color});
const box=(c,id,x,z,color,sx=1,sz=1,y=.1,sy=.2)=>c.draw(id,'box',{x,y,z,sx,sy,sz,color});
const ball=(c,id,x,z,color,s=.6,y=.5)=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color});
const ring=(c,id,x,z,color,s=1,y=.1)=>c.draw(id,'ring',{x,y,z,sx:s,sy:s,sz:s,rx:Math.PI/2,color});
const near=(p,a)=>a.reduce((a,b)=>!a||dist(p,b)<dist(p,a)?b:a,null);
const tap=(c,p,r=p.cadence)=>((c.time+p.phase)%r)<r*.4;
function init(c,limit){c.limit=limit;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=3;p.vy=0;p.phase=c.rand();p.cadence=c.rand(.25,.43);p.stun=0;p.cool=0;p.face={x:0,z:-1};});}
function line(c,id,a,b,color,w=.1,y=.1,h=w){c.draw(id,'box',{x:(a.x+b.x)/2,z:(a.z+b.z)/2,y,sx:dist(a,b),sy:h,sz:w,ry:-Math.atan2(b.z-a.z,b.x-a.x),color});}
function finish(c,arr,reason){if(arr.length)c.complete(arr.length===1?[arr[0]]:[],reason);}
function race(c,arr,reason){if(!arr.length)return;const min=Math.min(...arr.map(q=>q.time));c.complete(arr.filter(q=>Math.abs(q.time-min)<1e-6).map(q=>q.id),reason);}
function highest(c,reason){const max=Math.max(...c.players.map(p=>p.score));c.complete(c.players.filter(p=>p.score===max).map(p=>p.i),reason);}
function avoid(p,threats,x=7,z=4){let best=p,score=-Infinity;for(let i=0;i<16;i++){const a=i*TAU/16,q={x:clamp(p.x+Math.cos(a)*2,-x,x),z:clamp(p.z+Math.sin(a)*2,-z,z)},v=Math.min(...threats.map(t=>dist(q,t)),10)-Math.hypot(q.x,q.z)*.05;if(v>score){score=v;best=q;}}return toward(p,best.x,best.z);}
function combat(c,dt,bot){const attacks=[];for(const p of c.players){const u=c.input(p,bot(p));if(!p.alive)continue;if(c.time>=p.stun){c.move(p,u,4.6,false);if(Math.hypot(u.x,u.z)>.05)p.face=toward({x:0,z:0},u.x,u.z);}c.jump(p,c.time>=p.stun?u:{},7);if(u.bp&&c.time>=p.cool&&c.time>=p.stun){attacks.push({p,force:p.y>.3?5.5:4});p.cool=c.time+.42;p.pose='attack';}p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-4*dt);p.vz*=Math.exp(-4*dt);}const hits=[];for(const {p,force}of attacks)for(const q of c.players)if(q!==p&&q.alive&&dist(p,q)<1.35&&((q.x-p.x)*p.face.x+(q.z-p.z)*p.face.z)>.05&&Math.abs(q.y-p.y)<1.2)hits.push({q,vx:p.face.x*force,vz:p.face.z*force});for(const h of hits){h.q.vx+=h.vx;h.q.vz+=h.vz;h.q.stun=c.time+.35;}}
export const games={};

games['Buddy Bounce']=c=>{
 init(c,30);c.view={size:24,eye:[0,10,26],target:[0,4,0]};const balloons=Array.from({length:24},(_,i)=>({id:i,x:(i%8-3.5)*1.6,z:Math.floor(i/8)%2?-.8:.8,y:[1.8,3.2,6.5][Math.floor(i/8)],value:[1,3,10][Math.floor(i/8)],ready:0}));c.players.forEach(p=>{p.z=c.rand(-1,1);p.vy=11.5;p.y=c.rand(0,.2);});
 return{update(dt){const before=c.players.map(p=>p.y);for(const p of c.players){const available=balloons.filter(b=>c.time>=b.ready&&b.y<Math.max(3.3,p.y+1)),target=near(p,available),u=c.input(p,target?toward(p,target.x,target.z):{});c.move(p,u,4.2,false);p.x=clamp(p.x,-7,7);p.z=clamp(p.z,-2,2);p.vy-=18*dt;p.y+=p.vy*dt;if(p.y<0){p.y=0;p.vy=11.5;}}const stomp=[];for(const p of c.players)for(const q of c.players)if(p!==q&&p.vy<0&&dist(p,q)<.65&&before[p.i]>before[q.i]+1&&p.y<=q.y+1)stomp.push({p,q});for(const {p,q}of stomp){p.y=q.y+1.05;p.vy=12.5;q.vy=Math.min(q.vy,0);}for(const b of balloons){if(c.time<b.ready)continue;const candidates=c.players.filter(p=>Math.hypot(p.x-b.x,p.z-b.z,p.y+.9-b.y)<.7);if(candidates.length){const p=c.pick(candidates);c.points(p,b.value);b.ready=c.time+c.rand(5,7);}}c.hint('방향키로 자동 점프 구름 위를 이동하세요. 풍선은 1·3·10점. 가장 높은 10점 풍선은 내려올 때 다른 선수 머리를 밟아 높이 튀어야 닿습니다.');},render(){box(c,'sky',0,0,'#bbced0',17,7,-.4,.4);for(let i=-4;i<=4;i++)c.draw('cloud'+i,'sphere',{x:i*1.8,y:-.3,z:0,sx:2.5,sy:.8,sz:5,color:'#e2e7d9'});balloons.forEach(b=>{if(c.time>=b.ready){ball(c,'balloon'+b.id,b.x,b.z,b.value===10?'#dccc84':b.value===3?'#d8a2b7':'#91b7c8',.6,b.y);txt(c,'value'+b.id,b.value,b.x,b.z,b.y+.6,2.4);}});},timeout(){highest(c,'30초 동안 모은 풍선 점수');}};
};

games['Pinball Fall']=c=>{
 init(c,310);c.view={size:27,eye:[0,24,27],target:[0,0,0]};let phase='choose',start=0;const balls=Array.from({length:5},(_,i)=>({id:i,x:(i-2)*2.5,s:0,vx:0,vs:0,owner:null,trap:null,shake:0})),pegs=Array.from({length:20},(_,i)=>({x:(i%4-1.5)*3+(Math.floor(i/4)%2?1:-1),s:8+Math.floor(i/4)*11,r:i%4===0?1.1:.7,rotating:i%3===0})),holes=[{x:-3,s:16},{x:3,s:29},{x:0,s:46}];c.players.forEach((p,i)=>{p.choice=i;p.pickAt=c.rand(.6,2);});
 function launch(){const free=balls.filter(b=>b.owner===null);c.players.filter(p=>p.ball===undefined).forEach(p=>{const b=free.shift();p.ball=b.id;b.owner=p.i;});phase='roll';start=c.time;c.limit=start+300;}
 return{update(dt){if(phase==='choose'){const requests=[];for(const p of c.players){const free=balls.filter(b=>b.owner===null),target=free[(p.i+Math.floor(p.phase*3))%free.length],u=c.input(p,{x:target?Math.sign(target.id-p.choice):0,a:c.time>p.pickAt});if(p.ball!==undefined)continue;if(Math.abs(u.x)>.5&&c.time>=p.cool){p.choice=clamp(p.choice+Math.sign(u.x),0,4);p.cool=c.time+.2;}if(u.pointer.valid&&u.pointer.worldX!==undefined){p.choice=clamp(Math.round(u.pointer.worldX/2.5+2),0,4);}if(u.ap||u.pointer.pressed)requests.push(p);}for(const p of c.shuffle(requests)){const b=balls[p.choice];if(b.owner===null){b.owner=p.i;p.ball=b.id;}}if(c.time>=10||c.players.every(p=>p.ball!==undefined))launch();c.hint('10초 안에 다섯 구슬 중 하나 선택: ←/→ 또는 포인터 · A 확정. 출발 뒤 조향은 불가능하며 구멍에 걸리면 A 연타로 탈출합니다.');}else{const done=[];for(const p of c.players){const b=balls[p.ball],u=c.input(p,{a:b.trap!==null&&tap(c,p,.17)}),before=b.s;if(b.trap!==null){if(u.ap)b.shake++;if(b.shake>=6){const h=holes[b.trap];b.x=h.x+1.4*(p.phase>.5?1:-1);b.s=h.s+.4;b.vs=4;b.trap=null;b.shake=0;}}else{b.vs=Math.min(11,b.vs+dt*2.4);b.vx*=Math.exp(-.2*dt);b.x+=b.vx*dt;b.s+=b.vs*dt;if(Math.abs(b.x)>6.7){b.x=clamp(b.x,-6.7,6.7);b.vx*=-.8;}for(const [i,o]of pegs.entries()){const ox=o.x+(o.rotating?Math.sin(c.time*1.4+i)*1.1:0),dx=b.x-ox,ds=b.s-o.s,d=Math.hypot(dx,ds);if(d<o.r+.55&&c.time>=(b.hitAt||0)){const nx=dx/(d||1),ns=ds/(d||1),dot=b.vx*nx+b.vs*ns;b.vx-=2*dot*nx;b.vs-=2*dot*ns;b.x=ox+nx*(o.r+.6);b.s=o.s+ns*(o.r+.6);b.hitAt=c.time+.12;}}for(let i=0;i<holes.length;i++)if(Math.hypot(b.x-holes[i].x,b.s-holes[i].s)<.8){b.trap=i;b.vx=0;b.vs=0;break;}}p.x=b.x;p.z=7-b.s*.23;p.y=.55;p.score=Math.max(0,b.s);if(before<65&&b.s>=65)done.push({id:p.i,time:c.time-dt+(65-before)/(b.s-before)*dt});}race(c,done,'핀볼 언덕의 아래 결승에 먼저 도착했습니다.');c.hint('내리막 구슬은 범퍼와 회전 블록에 반사됩니다. 구멍에 잡혔다면 A를 반복해서 눌러 탈출하세요.');}},render(){box(c,'hill',0,0,'#b6bbad',15,19,-.2,.4);pegs.forEach((o,i)=>{const x=o.x+(o.rotating?Math.sin(c.time*1.4+i)*1.1:0),z=7-o.s*.23;if(o.rotating)c.draw('block'+i,'box',{x,y:.5,z,sx:2.1,sy:1,sz:.45,ry:c.time*1.4,color:'#9aadb4'});else ball(c,'mushroom'+i,x,z,'#d5a6b2',o.r*2,.5);});holes.forEach((h,i)=>ring(c,'hole'+i,h.x,7-h.s*.23,'#5b7483',1.8,.06));balls.forEach(b=>{if(phase==='choose'||b.owner!==null){c.draw('ball'+b.id,'sphere',{x:b.x,y:.55,z:7-b.s*.23,sx:1.25,sy:1.25,sz:1.25,color:b.owner===null?'#bac6bd':c.players[b.owner].color,opacity:.6});if(phase==='choose')txt(c,'number'+b.id,b.id+1,b.x,5.5,2.5,2);}});if(phase==='choose')c.players.forEach(p=>{p.x=(p.choice-2)*2.5;p.z=9;p.y=0;});},timeout(){c.complete([],'5분 동안 결승에 도착한 구슬이 없습니다.');}};
};

games['Speeding Bullets']=(c,meta)=>{
 init(c,Infinity);c.view={size:26,eye:[0,22,26],target:[0,0,0]};const pads=Array.from({length:16},(_,i)=>({s:8+i*7,x:Math.sin(i*2.2)*2})),obstacles=Array.from({length:15},(_,i)=>({s:12+i*7,x:Math.cos(i*1.7)*2,ground:i%3===0})).filter(o=>meta.titleId!=='top-100'||!o.ground);c.players.forEach(p=>{p.lx=0;p.s=0;p.speed=1;p.used=new Set();p.hit=new Set();});
 return{update(dt){const done=[];for(const p of c.players){const next=pads.find(o=>o.s>p.s-.3),haz=obstacles.find(o=>o.s>p.s&&o.s-p.s<4),goal=haz&&Math.abs((next?.x||0)-haz.x)<1.3?-Math.sign(haz.x||1)*2:next?.x||0,u=c.input(p,{x:clamp((goal-p.lx)*2,-1,1)}),before=p.s;p.lx=clamp(p.lx+u.x*dt*(1.8+p.speed*.7),-2.9,2.9);p.s+=dt*(3+p.speed*1.6);pads.forEach((o,i)=>{if(!p.used.has(i)&&before<=o.s&&p.s>=o.s&&Math.abs(p.lx-o.x)<.85){p.used.add(i);p.speed=Math.min(5,p.speed+1);}});obstacles.forEach((o,i)=>{if(!p.hit.has(i)&&Math.abs(p.s-o.s)<.9&&Math.abs(p.lx-o.x)<.9){p.hit.add(i);p.speed=1;p.stun=c.time+.4;}});p.x=(p.i-1.5)*6.3+p.lx;p.z=4;p.y=.7;p.score=p.s;if(before<125&&p.s>=125)done.push({id:p.i,time:c.time-dt+(125-before)/(p.s-before)*dt});}race(c,done,'대시 패드를 타며 탄환 코스를 먼저 완주했습니다.');c.hint('←/→ 기울기 조향. 대시 패드는 속도를 한 단계 높이고 식물·파이프 충돌은 1단계로 낮춥니다. 빠를수록 조향 폭도 커집니다.');},render(){c.players.forEach(p=>{const x=(p.i-1.5)*6.3;box(c,'course'+p.i,x,0,'#a8b7ac',6,22,-.2,.4);pads.forEach((o,i)=>{const z=4-(o.s-p.s)*.75;if(Math.abs(z)<11){box(c,`pad${p.i}-${i}`,x+o.x,z,'#dec98b',1.6,1,.03,.06);txt(c,`arrow${p.i}-${i}`,'↑',x+o.x,z,.2,1.5);}});obstacles.forEach((o,i)=>{const z=4-(o.s-p.s)*.75;if(Math.abs(z)<11){c.draw(`pipe${p.i}-${i}`,'cylinder',{x:x+o.x,y:.7,z,sx:1.1,sy:1.4,sz:1.1,color:'#819e91'});if(!o.ground)ball(c,`plant${p.i}-${i}`,x+o.x,z,'#d1a0b0',1,1.6);}});c.draw('bullet'+p.i,'sphere',{x:p.x,y:.5,z:4,sx:1.2,sy:1,sz:2,color:'#718998'});txt(c,'speed'+p.i,`단계 ${p.speed}`,x,-8,2,4);});},timeout(){c.complete([]);}};
};

games['Pianta Pool']=c=>{
 init(c,60);const rings=[];let serial=0,next=0;c.players.forEach(p=>{p.vx=0;p.vz=0;});function toss(){rings.push(...[3,3,5].map(value=>({id:serial++,x:c.rand(-6,6),z:c.rand(-3.5,3.5),value,owner:null,at:0})));}toss();
 return{update(dt){for(const p of c.players){const target=near(p,rings.filter(r=>r.owner===null)),u=c.input(p,target?toward(p,target.x,target.z):{});if(c.time>=(p.busy||0)){p.vx=(p.vx+u.x*dt*10)*Math.exp(-2*dt);p.vz=(p.vz+u.z*dt*10)*Math.exp(-2*dt);p.x=clamp(p.x+p.vx*dt,-7,7);p.z=clamp(p.z+p.vz*dt,-4,4);}p.y=-.2;}for(const r of rings)if(r.owner===null){const nearPlayers=c.players.filter(p=>c.time>=(p.busy||0)&&dist(p,r)<.7);if(nearPlayers.length){const p=c.pick(nearPlayers);r.owner=p.i;r.at=c.time;p.busy=c.time+.75;c.points(p,r.value);}}if(rings.every(r=>r.owner!==null)&&!next)next=c.time+.75;if(next&&c.time>=next){rings.length=0;toss();next=0;}c.hint('방향키 기울기로 헤엄쳐 링을 잡으세요. 분홍 3점·금색 5점, 세 링을 모두 잡으면 다음 묶음! 시간 직전에 잡은 링도 점수에 포함됩니다.');},render(){c.arena({color:'#8fbdc6'});rings.forEach(r=>{const p=r.owner===null?null:c.players[r.owner],f=(c.time-r.at)/.75;if(!p||f<1){ring(c,'ring'+r.id,p?p.x:r.x,p?p.z:r.z,r.value===5?'#e1ca83':'#dca5b8',1.4,p?1.4:.04);if(p)for(let k=0;k<r.value;k++)ball(c,`fish${r.id}-${k}`,p.x+(k-(r.value-1)/2)*.3,p.z+Math.sin(f*Math.PI)*.7,'#c7a191',.3,.3+Math.sin(f*Math.PI)*2);}});ball(c,'thrower',0,-6,'#a8b692',2,1.5);},timeout(){highest(c,'60초 동안 받은 링 점수');}};
};

games['Chain Event']=c=>{
 init(c,Infinity);c.view={size:23,eye:[0,3,25],target:[0,1,0],noSea:true};const obstacles=Array.from({length:24},(_,i)=>({s:6+i*4.4,side:c.pick([-1,1])}));c.players.forEach(p=>{p.s=0;p.side=p.i%2?1:-1;p.speed=3.5;p.hit=new Set();});
 return{update(dt){const done=[];for(const p of c.players){const next=obstacles.find(o=>o.s>p.s-.3),u=c.input(p,{x:next?-next.side:0}),before=p.s;if(u.x<-.3)p.side=-1;if(u.x>.3)p.side=1;if(c.time>=p.stun){p.speed=Math.min(9,p.speed+dt*.6);p.s+=p.speed*dt;}obstacles.forEach((o,i)=>{if(!p.hit.has(i)&&Math.abs(p.s-o.s)<.55&&p.side===o.side){p.hit.add(i);p.stun=c.time+.7;p.speed=3.5;}});p.x=(p.i-1.5)*5.2+p.side*.8;p.y=1;p.z=0;p.score=p.s;if(before<115&&p.s>=115)done.push({id:p.i,time:c.time-dt+(115-before)/(p.s-before)*dt});}race(c,done,'가시공을 피해 사슬 아래에 먼저 도착했습니다.');c.hint('←/→ 사슬의 왼쪽·오른쪽으로 전환. 계속 피하면 점점 빨라지고 가시공에 닿으면 기절·감속합니다. 일반 경주 규칙입니다.');},render(){c.players.forEach(p=>{const x=(p.i-1.5)*5.2;for(let k=-6;k<=6;k++)c.draw(`chain${p.i}-${k}`,'ring',{x,y:k*1.1+(p.s%1.1),z:0,sx:.4,sy:.7,sz:.4,color:'#9dacae'});obstacles.forEach((o,i)=>{const y=1-(o.s-p.s)*.5;if(Math.abs(y)<7){ball(c,`spike${p.i}-${i}`,x+o.side*.8,0,'#697f8f',1.1,y);for(let k=0;k<6;k++)c.draw(`tip${p.i}-${i}-${k}`,'cone',{x:x+o.side*.8+Math.cos(k*TAU/6)*.55,y:y+Math.sin(k*TAU/6)*.55,z:0,sx:.3,sy:.6,sz:.3,rz:k*TAU/6-Math.PI/2,color:'#b9b6a5'});}});txt(c,'distance'+p.i,`${Math.floor(p.s)}/115`,x,0,7,4);});},timeout(){c.complete([]);}};
};

games['Skyjinks']=c=>{
 init(c,Infinity);c.view={size:24,eye:[0,20,23],target:[0,0,0]};const platforms=Array.from({length:26},(_,i)=>({id:i,s:i*3.1,x:i<2?0:Math.sin(i*1.8)*2.7,w:i===0?9:i<9?3.5:i<18?4:3.6,h:i===0?4:2.5,type:i<9?'disc':i<18?(i%3?'cross':'tee'):i%2?'cloud':'disc',rot:i%2?1:-1}));c.players.forEach((p,i)=>{p.s=0;p.lx=(i-1.5)*1.3;p.h=0;p.on=0;p.hearts=3;p.rescue=0;});let camera=0;
 function surface(p,q){const dz=p.s-q.s,dx=p.lx-q.x;if(q.type==='disc'||q.type==='cloud')return Math.hypot(dx/(q.w/2),dz/(q.h/2))<=1;const a=c.time*.5*q.rot,xx=dx*Math.cos(a)+dz*Math.sin(a),zz=-dx*Math.sin(a)+dz*Math.cos(a);return Math.abs(xx)<q.w/2&&Math.abs(zz-(q.type==='tee'?-q.h/3:0))<.5||Math.abs(xx)<.5&&Math.abs(zz)<q.h/2;}
 return{update(dt){camera=Math.max(0,c.time*1.9-3);const done=[];for(const p of c.players){const next=platforms[Math.min(platforms.length-1,(p.on??p.checkpoint??0)+1)],u=c.input(p,{x:clamp((next.x-p.lx)*2,-1,1),z:clamp((p.s-next.s)*2,-1,1),a:p.on!==null&&tap(c,p,.25)});if(!p.alive)continue;if(c.time<p.rescue){p.y=1;continue;}const n=Math.max(1,Math.hypot(u.x,u.z));p.lx=clamp(p.lx+u.x/n*dt*4.6,-6,6);p.s+=-u.z/n*dt*4.6;if(p.on!==null&&u.ap){p.vy=8;p.h=.01;p.on=null;}if(p.on!==null){const q=platforms[p.on];if(q.type!=='cloud'){const a=dt*.5*q.rot,dx=p.lx-q.x,ds=p.s-q.s;p.lx=q.x+dx*Math.cos(a)-ds*Math.sin(a);p.s=q.s+dx*Math.sin(a)+ds*Math.cos(a);}if(!surface(p,platforms[p.on]))p.on=null;else if(platforms[p.on].type==='cloud'){p.vy=10;p.h=.01;p.on=null;}}if(p.on===null){const old=p.h;p.vy-=18*dt;p.h+=p.vy*dt;if(old>=0&&p.h<=0&&p.vy<0){const q=platforms.find(q=>surface(p,q));if(q){p.on=q.id;p.checkpoint=q.id;p.h=0;p.vy=0;}}}if(p.h< -2||p.s<camera-9){if(p.hearts>0){p.hearts--;const choices=platforms.filter(q=>q.s>=camera&&q.s<=camera+6),q=c.pick(choices.length?choices:[platforms.at(-1)]);p.s=q.s;p.lx=q.x;p.on=q.id;p.checkpoint=q.id;p.h=0;p.vy=0;p.rescue=c.time+.8;}else c.eliminate(p);}p.x=p.lx;p.z=5-(p.s-camera)*.65;p.y=p.h;p.score=p.hearts;if(p.on===platforms.length-1)done.push(p.i);}if(done.length)finish(c,done,'하늘 코스의 마지막 발판에 먼저 도착했습니다.');else{const alive=c.players.filter(p=>p.alive);if(alive.length<=1)c.complete(alive.map(p=>p.i),'하늘 코스에서 가장 오래 살아남았습니다.');}c.hint('이동 · A 점프. 회전 원판→십자 블록→탄성 구름을 건너세요. 하트 3개는 추락 복귀 기회이며 모두 쓰고 다시 떨어지면 탈락합니다. 뒤쪽 발판은 화면 밖으로 사라집니다.');},render(){platforms.forEach(q=>{const z=5-(q.s-camera)*.65;if(Math.abs(z)>12)return;if(q.type==='cross'||q.type==='tee'){for(const k of[0,1]){const offset=q.type==='tee'&&!k?-q.h/3:0,a=c.time*.5*q.rot;c.draw(`platform${q.id}-${k}`,'box',{x:q.x-offset*Math.sin(a),y:-.2,z:z+offset*Math.cos(a)*.65,sx:k?1:q.w,sy:.4,sz:k?q.h*.65:.7,ry:-c.time*.5*q.rot,color:'#abb9ac'});}}else c.draw('platform'+q.id,q.type==='cloud'?'sphere':'cylinder',{x:q.x,y:-.2,z,sx:q.w,sy:.4,sz:q.h*.65,ry:c.time*.5*q.rot,color:q.type==='cloud'?'#e1e5d7':'#b8b39e'});if(q.type==='disc')c.draw('stripe'+q.id,'box',{x:q.x,y:.025,z,sx:q.w*.8,sy:.035,sz:.12,ry:-c.time*.5*q.rot,color:'#d8d7be'});});c.players.forEach(p=>{if(c.time<p.rescue)ball(c,'bubble'+p.i,p.x,p.z,'#b2d0d5',2,p.y+.6);});},timeout(){c.complete([]);}};
};

games['Mecha Choice']=c=>{
 init(c,Infinity);let round=0,until=0,pause=0,bad=0;function setup(){round++;until=c.time+3;bad=c.int(0,2);c.players.forEach(p=>{p.choice=-1;p.botChoice=c.int(0,2);p.chooseAt=c.time+c.rand(.4,2.1);});}setup();
 return{update(){for(const p of c.players){const raw=c.time>=p.chooseAt?{[['a','b','c'][p.botChoice]]:true}:{},u=c.input(p,raw);if(!p.alive||pause)continue;if(u.ap)p.choice=0;if(u.bp)p.choice=1;if(u.cp)p.choice=2;}if(pause){if(c.time>=pause){pause=0;setup();}}else if(c.time>=until){const alive=c.players.filter(p=>p.alive),deadEnd=alive.filter(p=>p.choice===bad);for(const p of alive)if(p.choice===bad||p.choice<0)c.eliminate(p);const survivors=c.players.filter(p=>p.alive);if(!survivors.length)c.complete(deadEnd.map(p=>p.i),'막다른 길 선택은 미선택보다 높은 순위입니다.');else if(survivors.length===1||round===5)c.complete(survivors.map(p=>p.i),'기계 군단의 다섯 갈림길을 탈출했습니다.');else pause=c.time+1;}c.hint(`${round}/5 갈림길 · ${Math.max(0,Math.ceil(until-c.time))}초. A/B/C로 세 문 중 선택, 시간 안에는 변경할 수 있습니다. 막다른 길 1개 또는 미선택은 탈락합니다.`);},render(){c.arena({color:'#9ba9a9'});for(let i=0;i<3;i++){box(c,'door'+i,(i-1)*5,-3,'#849ba6',3,1,2,4);txt(c,'button'+i,['A','B','C'][i],(i-1)*5,-2,3,2);if(pause&&i===bad)txt(c,'danger','막다른 길',(i-1)*5,-3,5,5);}c.players.forEach(p=>{p.x=p.choice<0?(p.i-1.5)*3:(p.choice-1)*5+(p.i-1.5)*.6;p.z=2;p.y=0;if(!p.alive)box(c,'robot'+p.i,p.x,3,'#8a967d',1,1,.5,1);});},timeout(){c.complete([]);}};
};

games['Jigsaw Jumble']=c=>{
 init(c,300);c.view={size:29,eye:[0,29,22],target:[0,0,0]};const board=p=>({x:p.i%2?6:-6,z:p.i<2?-5:5}),colors=['#d2a1b5','#9fbdb6','#d7c28e','#879fae'];c.players.forEach(p=>{p.stage=0;p.cursor={x:board(p).x,z:board(p).z+3};p.held=null;setup(p);});
 function setup(p){p.pattern=Array.from({length:16},()=>c.int(0,3));p.correct=c.int(0,p.stage+3);p.pieces=Array.from({length:p.stage+4},(_,i)=>({id:i,pattern:i===p.correct?[...p.pattern]:p.pattern.map((v,j)=>j%3===i%3?(v+1+i%3)%4:v),placed:false}));p.held=null;p.wait=0;}
 function pos(p,id){const o=board(p);return{x:o.x+(id%4-1.5)*2,z:o.z+2+Math.floor(id/4)*1.7};}
 return{update(dt){const done=[];for(const p of c.players){const o=board(p),goal=p.held===null?pos(p,p.correct):{x:o.x,z:o.z-1.5},delta=toward(p.cursor,goal.x,goal.z),arrived=dist(p.cursor,goal)<.2,u=c.input(p,{...delta,a:p.held===null?arrived:!arrived});const oldHeld=p.holding||false,pressed=u.pointer.valid?u.pointer.pressed:u.a&&!oldHeld,released=u.pointer.valid?u.pointer.released:!u.a&&oldHeld;p.holding=!!u.a;if(u.pointer.valid&&Number.isFinite(u.pointer.worldX)){p.cursor.x=clamp(u.pointer.worldX,o.x-4.5,o.x+4.5);p.cursor.z=clamp(u.pointer.worldZ,o.z-3.3,o.z+4.1);}else{p.cursor.x=clamp(p.cursor.x+u.x*dt*6,o.x-4.5,o.x+4.5);p.cursor.z=clamp(p.cursor.z+u.z*dt*6,o.z-3.3,o.z+4.1);}if(c.time<p.wait)continue;if(pressed&&p.held===null){const piece=near(p.cursor,p.pieces.map(q=>({...pos(p,q.id),id:q.id})));if(piece&&dist(p.cursor,piece)<.8)p.held=piece.id;}if(released&&p.held!==null){if(dist(p.cursor,{x:o.x,z:o.z-1.5})<.9&&p.held===p.correct){p.stage++;p.score=p.stage;if(p.stage===5)done.push(p.i);else setup(p);}else{p.held=null;p.wait=c.time+.3;}}p.x=o.x-4;p.z=o.z;p.y=0;}finish(c,done,'다섯 그림의 빠진 조각을 먼저 끼웠습니다.');c.hint('포인터 또는 방향키로 커서 이동. A를 누른 채 조각을 집어 빈칸으로 끌고, 놓아서 끼우세요. 그림 무늬가 같은 조각을 고릅니다. 후보는 4→8개, 총 5퍼즐!');},render(){c.players.forEach(p=>{const o=board(p);box(c,'board'+p.i,o.x,o.z,'#b8bcad',10,9,-.2,.4);box(c,'picture'+p.i,o.x,o.z-1.5,'#eee4ce',5,3,.05,.1);for(let j=0;j<16;j++){const x=o.x+(j%4-1.5)*.38,z=o.z-1.5+(Math.floor(j/4)-1.5)*.38;box(c,`target${p.i}-${j}`,x,z,colors[p.pattern[j]],.34,.34,.07,.12);}ring(c,'slot'+p.i,o.x,o.z-1.5,'#7e959e',2.25,.18);p.pieces.forEach(q=>{const at=p.held===q.id?p.cursor:pos(p,q.id);for(let j=0;j<16;j++)box(c,`piece${p.i}-${q.id}-${j}`,at.x+(j%4-1.5)*.28,at.z+(Math.floor(j/4)-1.5)*.28,colors[q.pattern[j]],.25,.25,p.held===q.id?.65:.2,.13);});ring(c,'cursor'+p.i,p.cursor.x,p.cursor.z,p.color,.65,.85);txt(c,'stage'+p.i,p.stage+'/5',o.x+4,o.z-3.8,1.8,2);});},timeout(){c.complete([],'5분 동안 다섯 퍼즐을 끝내지 못했습니다.');}};
};

games['Upward Mobility']=c=>{
 init(c,Infinity);c.view={size:27,eye:[0,5,28],target:[0,5,0],noSea:true};const platforms=[{x:0,y:0,w:5,spring:false}];for(let i=1;i<=16;i++){const pair=i<12;for(const side of pair?[-1,1]:[i%2?1:-1])platforms.push({x:side*(i%3===0?.6:1.65),y:i*1.5,w:pair?1.6:2,spring:i%4!==0});}c.players.forEach(p=>{p.lx=0;p.h=0;p.on=0;p.best=0;p.botTarget=1;});
 return{update(dt){const done=[];for(const p of c.players){if(p.on!==null){const candidates=platforms.map((q,id)=>({...q,id})).filter(q=>q.y>p.h+.2&&q.y<p.h+3.2);p.botTarget=(candidates.sort((a,b)=>a.y-b.y||Math.abs(a.x-p.lx)-Math.abs(b.x-p.lx))[0]||{id:platforms.length-1}).id;}const next=platforms[p.botTarget],u=c.input(p,{x:clamp((next.x-p.lx)*2,-1,1),a:p.on!==null&&tap(c,p,.25)});p.lx=clamp(p.lx+u.x*dt*4.2,-3.4,3.4);if(p.on!==null){const q=platforms[p.on];if(Math.abs(p.lx-q.x)>q.w/2+.2)p.on=null;else if(q.spring||u.ap){p.vy=q.spring?11:8.3;p.h+=.01;p.on=null;}}if(p.on===null){const old=p.h;p.vy-=18*dt;p.h+=p.vy*dt;if(p.vy<0){let landing=-1;for(let i=0;i<platforms.length;i++){const q=platforms[i];if(old>=q.y&&p.h<=q.y&&Math.abs(p.lx-q.x)<q.w/2+.2&&(landing<0||q.y>platforms[landing].y))landing=i;}if(landing>=0){p.h=platforms[landing].y;p.on=landing;p.vy=0;}}}if(p.h< -3){p.lx=0;p.h=0;p.on=0;p.vy=0;}p.best=Math.max(p.best,p.h);p.x=(p.i-1.5)*6.4+p.lx;p.y=4+(p.h-p.best);p.z=0;p.score=Math.min(24,p.best);if(p.on!==null&&platforms[p.on].y>=24)done.push(p.i);}finish(c,done,'점프 블록을 타고 꼭대기 구름에 먼저 도착했습니다.');c.hint('←/→ 이동 · A 점프. 체크무늬 점프 블록은 착지하면 더 높이 튀며, 일반 블록에서는 직접 점프합니다. 꼭대기 무지개 구름에 착지하세요.');},render(){c.players.forEach(p=>{const x=(p.i-1.5)*6.4;platforms.forEach((q,i)=>{const y=4+q.y-p.best;if(y> -4&&y<14){box(c,`block${p.i}-${i}`,x+q.x,0,q.spring?'#d8c48c':'#a5b4b0',q.w,1,y-.2,.4);if(q.spring)for(let k=0;k<4;k++)box(c,`checker${p.i}-${i}-${k}`,x+q.x+(k%2?.25:-.25),.52,'#a68f8a',.35,.04,y+(k<2?-.1:.1),.18);if(q.y===24)ring(c,'rainbow'+p.i,x+q.x,0,'#dbaabc',2,y+1);}});txt(c,'height'+p.i,Math.floor(p.best)+' m',x,1,13,4);});},timeout(){c.complete([]);}};
};

games['Ring Leader']=c=>{
 init(c,Infinity);c.view={size:25,eye:[0,18,23],target:[0,1,0]};const rings=[];for(let i=0;i<10;i++){rings.push({s:8+i*10,y:1.2,value:1});rings.push({s:13+i*10,y:3.4,value:3});}c.players.forEach(p=>{p.h=0;p.vy=0;p.s=0;p.dive=0;p.scored=new Set();});
 return{update(dt){for(const p of c.players){const next=rings.find((r,i)=>!p.scored.has(i)&&r.s>p.s-.2),until=next?(next.s-p.s)/4:99,high=next?.value===3,u=c.input(p,{b:high&&until<1.8&&p.h<=0,a:until<(high?.63:.43)&&p.h<=0});p.s+=dt*4;if(p.h<=0){if(u.b)p.dive=Math.min(1,p.dive+dt*2);else p.dive=Math.max(0,p.dive-dt*2);if(u.ap){p.vy=p.dive>.3?11:7;p.h=.01;p.dive=0;}}else{p.vy-=18*dt;p.h+=p.vy*dt;if(p.h<0){p.h=0;p.vy=0;}}rings.forEach((r,i)=>{if(!p.scored.has(i)&&p.s>=r.s){p.scored.add(i);if(Math.abs(p.h+.4-r.y)<.7)c.points(p,r.value);}});p.x=(p.i-1.5)*5.8;p.y=p.h-p.dive*.5;p.z=0;}if(c.players[0].s>=108)highest(c,'돌고래 코스에서 통과한 링 점수');c.hint('A 점프 · B를 유지해 잠수한 다음 A로 높이 점프. 낮은 빨강 링 1점·높은 금 링 3점. 링을 지나는 순간 높이를 맞추세요. 총 40점 코스입니다.');},render(){c.players.forEach(p=>{const x=(p.i-1.5)*5.8;box(c,'sea'+p.i,x,0,'#93bec7',5.5,21,-.6,.25);c.draw('dolphin'+p.i,'sphere',{x,y:p.y-.1,z:0,sx:1.1,sy:.65,sz:2,color:'#91b3c3'});rings.forEach((r,i)=>{const z=-(r.s-p.s)*.75;if(Math.abs(z)<10)c.draw(`ring${p.i}-${i}`,'ring',{x,y:r.y,z,sx:1.7,sy:1.7,sz:1.7,color:r.value===3?'#e3cc87':'#d89aac'});});txt(c,'score'+p.i,p.score+'/40',x,-3,7,4);});},timeout(){c.complete([]);}};
};

games['Smash Compactor']=c=>{
 init(c,Infinity);let round=0,until=0,pause=0,holes=[];function setup(){round++;const count=c.players.filter(p=>p.alive).length-1;holes=c.shuffle(Array.from({length:9},(_,i)=>({x:(i%3-1)*4,z:(Math.floor(i/3)-1)*2.7}))).slice(0,count);until=c.time+5;for(const p of c.players){p.vx=0;p.vz=0;p.y=0;}}setup();
 return{update(dt){if(pause){c.players.forEach(p=>c.input(p,{}));if(c.time>=pause){pause=0;setup();}}else{combat(c,dt,p=>{const goal=near(p,holes),enemy=near(p,c.players.filter(q=>q!==p&&q.alive)),v=goal?toward(p,goal.x,goal.z):{};return{...v,b:enemy&&dist(p,enemy)<1.1&&tap(c,p,.35),a:enemy&&dist(p,enemy)<1.5&&tap(c,p,.55)};});c.players.forEach(p=>{p.x=clamp(p.x,-7,7);p.z=clamp(p.z,-4.5,4.5);});if(c.time>=until){const safe=new Set();for(const h of holes){const candidates=c.players.filter(p=>p.alive&&p.y<.5&&dist(p,h)<.85&&!safe.has(p.i));if(candidates.length){candidates.sort((a,b)=>dist(a,h)-dist(b,h));const ties=candidates.filter(p=>Math.abs(dist(p,h)-dist(candidates[0],h))<1e-7);safe.add(c.pick(ties).i);}}for(const p of c.players)if(p.alive&&!safe.has(p.i))c.eliminate(p);const alive=c.players.filter(p=>p.alive);if(alive.length<=1)c.complete(alive.map(p=>p.i),'마지막 안전구멍을 차지했습니다.');else pause=c.time+1.2;}}c.hint(`${round}라운드 · 안전구멍 ${holes.length}개. 이동 · A 점프 · B 펀치/공중 발차기. 뚜껑이 열리는 순간 구멍 위에 있어야 압착기를 피합니다.`);},render(){c.arena({color:'#a7b1aa'});holes.forEach((h,i)=>{ring(c,'hole'+i,h.x,h.z,'#e1ce90',1.7,.03);ball(c,'glow'+i,h.x,h.z,'#d4d9b4',.4,.08);});if(pause)box(c,'press',0,0,'#879da7',15,10,.5,1);else{const warning=c.time>until-1;for(let i=0;i<4;i++)box(c,'post'+i,i%2?8:-8,i<2?-5:5,'#8498a3',.6,.6,3.5,7);if(warning)box(c,'ceiling',0,0,'#9aa8aa',15,10,7-(c.time-until+1)*2,.7);}},timeout(){c.complete([]);}};
};

games['Toad and Go Seek']=c=>{
 init(c,124);c.view={size:25,eye:[0,23,23],target:[0,0,0]};const houses=Array.from({length:12},(_,i)=>({id:i,x:(i%4-1.5)*4,z:(Math.floor(i/4)-1)*4,color:['#cb9fac','#b9bc96','#94b5c2'][i%3],mark:['○','△','□','☆'][Math.floor(i/3)]})),target=c.int(0,11),preview=4;c.players.forEach(p=>{p.x=(p.i-1.5)*1.4;p.z=7;p.reveal=-1;});
 return{update(dt){const done=[];for(const p of c.players){const h=houses[target],goal={x:h.x,z:h.z+1.4},u=c.input(p,c.time>=preview?{...toward(p,goal.x,goal.z),a:dist(p,goal)<.6&&tap(c,p)}:{});if(c.time<preview||c.time<p.stun)continue;c.move(p,u,4.6,false);p.x=clamp(p.x,-8.5,8.5);p.z=clamp(p.z,-6,7.5);for(const q of houses){const dx=p.x-q.x,dz=p.z-q.z;if(Math.abs(dx)<1.2&&Math.abs(dz)<.8){if(1.2-Math.abs(dx)<.8-Math.abs(dz))p.x=q.x+Math.sign(dx||1)*1.2;else p.z=q.z+Math.sign(dz||1)*.8;}}if(u.ap){const q=near(p,houses.map(q=>({...q,z:q.z+1.4})));if(q&&dist(p,q)<.8){p.reveal=q.id;p.showUntil=c.time+.6;if(q.id===target)done.push(p.i);else p.stun=c.time+.6;}}}finish(c,done,'숨은 친구가 들어간 집을 먼저 찾았습니다.');c.hint(c.time<preview?'먼저 파란 친구가 어느 집에 들어가는지 지켜보세요. 집 색깔과 표식을 기억하세요.':`이동 · A 문 두드리기. ${c.time>=64?'1분 경과: 정답 집 위치가 지도에 표시됩니다.':'소개 장면에서 본 집을 찾아가세요.'}`);},render(){c.arena({width:20,depth:17,color:'#b9c0a1'});houses.forEach(h=>{box(c,'house'+h.id,h.x,h.z,h.color,2.2,1.5,.6,1.2);c.draw('roof'+h.id,'cone',{x:h.x,y:1.6,z:h.z,sx:2.8,sy:1.1,sz:2,color:'#cbb78e'});box(c,'door'+h.id,h.x,h.z+.8,'#718d97',.7,.06,.5,1);txt(c,'mark'+h.id,h.mark,h.x,h.z+.9,1.2,1.1);});const h=houses[target];if(c.time<preview){const t=clamp(c.time/3,0,1);ball(c,'friend',h.x,h.z+3-t*2.1,'#83aec6',.65,.55);}if(c.time>=64)ring(c,'map',h.x,h.z,'#ead390',3.4,.06);c.players.forEach(p=>{if(p.reveal>=0&&c.time<p.showUntil){const h=houses[p.reveal];ball(c,'guest'+p.i,h.x,h.z+1,p.reveal===target?'#83aec6':'#ac9277',.7,.6);}});},timeout(){c.complete([],'2분 동안 숨은 친구를 찾지 못했습니다.');}};
};

games['Polar Extreme']=c=>{
 init(c,Infinity);c.view={size:25,eye:[0,21,25],target:[0,0,0]};const chunks=Array.from({length:24},(_,i)=>({id:i,s:i*3,x:i<2?0:Math.sin(i*1.8)*2,w:i===0?9:3.8,h:2.7,drift:c.rand(0,TAU),broken:false})),penguins=chunks.filter(q=>q.id>2&&q.id%4===0).map(q=>({id:q.id,down:0}));c.players.forEach((p,i)=>{p.lx=(i-1.5)*1.3;p.s=0;p.h=0;p.on=0;p.wet=0;p.splash=0;p.recover=0;});let camera=0;
 const position=q=>({x:q.x+(q.id?Math.sin(c.time*.6+q.drift)*.35:0)+(q.shift||0),s:q.s});
 function over(p,q){const a=position(q),dx=Math.abs(p.lx-a.x),ds=Math.abs(p.s-q.s);return dx<q.w/2&&ds<q.h/2&&(!q.broken||dx>.2||ds>.2);}
 return{update(dt){camera=Math.max(0,c.time*1.65-3);for(const q of chunks){const prev=position(q).x,weight=c.players.filter(p=>p.alive&&p.on===q.id).reduce((v,p)=>v+p.lx-prev,0);q.shift=clamp((q.shift||0)+weight*dt*.16,-.5,.5);q.shiftDelta=position(q).x-prev;}const done=[];for(const p of c.players){const next=chunks[Math.min(23,(p.on??p.checkpoint??0)+1)],at=position(next),u=c.input(p,{x:clamp((at.x+(next.broken?.8:0)-p.lx)*2,-1,1),z:clamp((p.s-next.s)*2,-1,1),a:tap(c,p,p.wet?.12:.28)});if(!p.alive)continue;if(p.wet){if(u.ap){p.recover++;p.vy=6;p.h=.01;p.wet=0;}else{p.h=-.6;if(c.time-p.wet>1.8||p.splash>=4)c.eliminate(p);}}else{if(c.time>=p.stun){const n=Math.max(1,Math.hypot(u.x,u.z));p.lx=clamp(p.lx+u.x/n*dt*4.5,-6,6);p.s-=u.z/n*dt*4.5;}if(p.on!==null&&u.ap){p.vy=8;p.h=.01;p.on=null;}if(p.on!==null){const q=chunks[p.on];if(!over(p,q))p.on=null;else p.lx+=Math.cos(c.time*.6+q.drift)*dt*.21+(q.shiftDelta||0);}if(p.on===null){const old=p.h;p.vy-=18*dt;p.h+=p.vy*dt;if(old>=0&&p.h<=0&&p.vy<0){const q=chunks.find(q=>over(p,q));if(q){p.h=0;p.on=q.id;p.checkpoint=q.id;p.vy=0;p.splash=0;if(q.id>0&&q.id%5===0)q.broken=true;}}if(p.h<-.8){p.wet=c.time;p.h=-.6;p.vy=0;p.splash++;if(p.splash>=4)c.eliminate(p);}}}for(const e of penguins){const q=chunks[e.id],at=position(q);if(Math.hypot(p.lx-at.x,p.s-at.s)<.65&&c.time>=e.down){if(p.h>.5&&p.vy<0){e.down=c.time+1;p.vy=5;}else if(p.h<.6&&c.time>=p.stun)p.stun=c.time+.65;}}if(p.s<camera-9)c.eliminate(p);p.x=p.lx;p.z=5-(p.s-camera)*.7;p.y=p.h;p.score=Math.max(0,p.s);if(p.on===23)done.push(p.i);}if(done.length)finish(c,done,'끝의 구조선에 먼저 올라탔습니다.');else{const alive=c.players.filter(p=>p.alive);if(alive.length<=1)c.complete(alive.map(p=>p.i),'얼음 바다에서 가장 오래 살아남았습니다.');}c.hint('이동 · A 점프. 물에 빠지면 A를 빠르게 눌러 다시 뛰어오르세요. 땅을 못 밟은 채 네 번 연속 빠지거나 화면 뒤로 밀리면 탈락! 펭귄은 밟으면 잠시 납작해집니다.');},render(){box(c,'sea',0,0,'#83adbd',22,25,-.8,.2);chunks.forEach(q=>{const at=position(q),z=5-(q.s-camera)*.7;if(Math.abs(z)>12)return;if(q.id===23)box(c,'ship',at.x,z,'#bfa888',7,3,.25,.8);else if(q.broken){for(const a of[-1,1])for(const b of[-1,1])box(c,`ice${q.id}-${a}-${b}`,at.x+a*q.w/4,z+b*q.h*.7/4,'#d8e4de',q.w/2-.12,q.h*.7/2-.12,-.15,.3);}else box(c,'ice'+q.id,at.x,z,'#d8e4de',q.w,q.h*.7,-.15,.3);});penguins.forEach(e=>{const q=chunks[e.id],at=position(q),z=5-(q.s-camera)*.7;if(Math.abs(z)<12)c.draw('penguin'+e.id,'sphere',{x:at.x,y:c.time<e.down?.12:.5,z,sx:.7,sy:c.time<e.down?.2:1,sz:.6,color:'#6b8c9e'});});},timeout(){c.complete([]);}};
};

games['Goomba Bowling']=(c,meta)=>{
 init(c,Infinity);c.view={size:24,eye:[0,21,25],target:[0,0,0]};const order=c.shuffle([0,1,2,3]);let turn=0,until=15,phase='aim',shell=null,pause=0;const pins=Array.from({length:20},(_,i)=>({id:i,s:3+i*.9,alive:true}));c.players.forEach(p=>{p.lx=0;p.angle=0;p.mode=0;p.aimed=false;p.throws=0;});
 const pinX=(q,time)=>Math.sin(time*.7+q.id*.12)*2.2;
 function next(){turn++;if(turn===4){highest(c,'한 번 던져 쓰러뜨린 스무 핀의 수');return;}pins.forEach(p=>p.alive=true);phase='aim';until=c.time+15;shell=null;}
 return{update(dt){const p=c.players[order[turn]];if(!p)return;for(const q of c.players){const bot=q===p?{x:clamp((pinX(pins[0],c.time+1)-q.lx)*2,-1,1),[meta.titleId==='top-100'?'a':'b']:c.time>until-12.5}:{};const u=c.input(q,bot);if(q!==p||phase!=='aim')continue;if(meta.titleId==='top-100'){q.lx=clamp(q.lx+u.x*dt*3,-4,4);q.angle=clamp(q.angle+u.z*dt*.5,-.45,.45);}else{if(u.ap)q.mode=1-q.mode;if(q.mode)q.angle=clamp(q.angle+u.x*dt*.5,-.45,.45);else q.lx=clamp(q.lx+u.x*dt*3,-4,4);}if((meta.titleId==='top-100'?u.ap:u.bp)||c.time>=until){shell={x:q.lx,s:0,vx:Math.sin(q.angle)*11,vs:Math.cos(q.angle)*11};phase='roll';q.throws++;}}if(phase==='roll'){shell.x+=shell.vx*dt;shell.s+=shell.vs*dt;for(const q of pins)if(q.alive&&Math.hypot(shell.x-pinX(q,c.time),shell.s-q.s)<.6){q.alive=false;c.points(p,1);}if(shell.s>22||Math.abs(shell.x)>6){phase='pause';pause=c.time+.6;}}else if(phase==='pause'&&c.time>=pause)next();c.players.forEach(q=>{q.x=q===p?q.lx:8;q.z=q===p?8:4+q.i;q.y=0;});c.hint(`${turn+1}/4 투구 · ${p.i+1}P 차례 · ${Math.max(0,Math.ceil(until-c.time))}초. ${meta.titleId==='top-100'?'←/→ 위치 · ↑/↓ 각도 · A 투구':'A 위치/각도 전환 · ←/→ 조정 · B 투구'}. 움직이는 핀 20개를 단 한 번의 껍질로 맞히세요.`);},render(){box(c,'lane',0,0,'#c2b897',11,20,-.2,.4);pins.forEach(q=>{if(q.alive){const x=pinX(q,c.time),z=7-q.s*.65;ball(c,'pin'+q.id,x,z,'#b7a38b',.65,.35);for(const side of[-1,1])ball(c,'eye'+q.id+side,x+side*.13,z+.2,'#e5dcc7',.1,.6);}});const p=c.players[order[turn]];if(p&&phase==='aim')line(c,'aim',{x:p.lx,z:7},{x:p.lx+Math.sin(p.angle)*5,z:7-Math.cos(p.angle)*5},'#cf9eac',.07,.05);if(shell)ball(c,'shell',shell.x,7-shell.s*.65,'#d09faf',.7,.35);},timeout(){c.complete([]);}};
};

games['Tumble Temple']=c=>{
 init(c,60);const shots=[],pegs=Array.from({length:12},(_,i)=>({x:(i%4-1.5)*3.4,z:-7+Math.floor(i/4)*2.5,phase:i%2}));let next=0,serial=0;
 return{update(dt){if(c.time>=next){shots.push({id:serial++,x:c.rand(-7,7),z:-10,vx:c.rand(-1,1),vz:2.5+c.time*.035,r:c.rand()<.25?1.1:.55,active:true});next=c.time+Math.max(.28,.95-c.time*.011);}const eliminated=[];for(const p of c.players){const danger=shots.filter(s=>s.active&&s.z> -4),u=c.input(p,{...avoid(p,danger,7,4),a:danger.some(s=>dist(p,s)<1.7&&s.r<1)&&tap(c,p,.4)});c.move(p,u,4.3,false);p.x=clamp(p.x,-7.4,7.4);p.z=clamp(p.z,-1.5,5);c.jump(p,u,7);}for(const s of shots){if(!s.active)continue;s.x+=s.vx*dt;s.z+=s.vz*dt;if(Math.abs(s.x)>7.5){s.x=clamp(s.x,-7.5,7.5);s.vx*=-1;}for(const [i,o]of pegs.entries()){const active=Math.floor(c.time/2.5)%2===o.phase;if(active&&dist(s,o)<s.r+.3&&c.time>=(s.hit||0)){s.vx=Math.sign(s.x-o.x||c.rand(-1,1))*(2+s.r);s.vz=Math.max(1,s.vz*.75);s.hit=c.time+.2;}}if(c.time>30)for(const side of[-1,1])if(Math.hypot(s.x-side*4,s.z+2)<1.3){s.vx+=side*dt*6;s.vz+=dt*5;}for(const p of c.players)if(p.alive&&dist(p,s)<s.r+.4&&p.y<s.r*1.8)eliminated.push(p);if(s.z>8)s.active=false;}eliminated.forEach(p=>c.eliminate(p));c.lastStanding();c.hint('이동 · A 점프. 작은·큰 가시공은 켜졌다 꺼지는 핀에 부딪혀 굴러옵니다. 30초 뒤 회전 기둥이 공을 가속합니다. 용암 가장자리로 걸어 떨어지지는 않습니다.');},render(){c.arena({depth:22,color:'#b3aea0'});pegs.forEach((o,i)=>{if(Math.floor(c.time/2.5)%2===o.phase)box(c,'peg'+i,o.x,o.z,'#8c9fa7',.6,.6,.45,.9);});for(const side of[-1,1])c.draw('pillar'+side,'box',{x:side*4,y:.5,z:-2,sx:2.6,sy:1,sz:.45,ry:c.time>30?c.time*3:0,color:'#9ba5a4'});shots.forEach(s=>{if(s.active){ball(c,'ball'+s.id,s.x,s.z,'#728692',s.r*2,s.r);for(let i=0;i<6;i++){const a=i*TAU/6+c.time;c.draw(`tip${s.id}-${i}`,'cone',{x:s.x+Math.cos(a)*s.r,y:s.r,z:s.z+Math.sin(a)*s.r,sx:.25,sy:.45,sz:.25,rz:Math.PI/2,ry:-a,color:'#d1c4a8'});}}});},timeout(){c.survivors('60초 동안 신전의 가시공을 피했습니다.');}};
};

games['Twist Ending']=c=>{
 init(c,Infinity);c.view={size:24,eye:[0,9,27],target:[0,3,0]};c.players.forEach(p=>{p.stage=0;p.dial=0;p.goal=c.int(2,6)/8*TAU;p.turn=c.pick([-1,1]);p.align=0;});
 return{update(dt){const done=[];for(const p of c.players){const remaining=(p.turn*(p.goal-p.dial)%TAU+TAU)%TAU,amount=remaining<.07?0:Math.min(1,remaining/(dt*(1.9+p.stage*1.4))*.4),u=c.input(p,{x:p.turn*amount}),speed=Math.max(0,u.x*p.turn)*(u.a?.2:1)*(1.9+p.stage*1.4),previous=p.dial;p.dial=(p.dial+p.turn*speed*dt+TAU)%TAU;const error=Math.abs(Math.atan2(Math.sin(p.dial-p.goal),Math.cos(p.dial-p.goal)));if(error<.085&&speed<.35)p.align+=dt;else p.align=0;if(p.align>=.25){p.stage++;p.score=p.stage;p.align=0;if(p.stage===3)done.push(p.i);else{p.dial=0;const marks=[8,12,16][p.stage];p.goal=c.int(2,marks-2)/marks*TAU;p.turn=c.pick([-1,1]);}}p.x=(p.i-1.5)*5.7;p.z=3;p.y=0;}finish(c,done,'동·은·금 세 겹 보물상자를 먼저 열었습니다.');c.hint('표시된 ←/→ 방향으로 다이얼을 돌리고 목표 눈금에서 손을 놓으세요. 반대 방향으로 되돌릴 수 없습니다. A를 누른 채 조향하면 천천히 돌립니다. 동 8·은 12·금 16눈금이며 뒤 상자일수록 빠릅니다.');},render(){c.players.forEach(p=>{const x=(p.i-1.5)*5.7,y=2.8,color=['#bca081','#b7c4c4','#ddc98b'][Math.min(2,p.stage)],n=[8,12,16][Math.min(2,p.stage)];box(c,'chest'+p.i,x,0,color,4-p.stage*.5,2.5,1.5,3);c.draw('dial'+p.i,'cylinder',{x,y,z:1.4,sx:2.7,sy:.2,sz:2.7,rx:Math.PI/2,color:'#dedbc9'});for(let k=0;k<n;k++){const a=k*TAU/n;c.draw(`mark${p.i}-${k}`,'box',{x:x+Math.sin(a)*1.08,y:y+Math.cos(a)*1.08,z:1.56,sx:.06,sy:.22,sz:.06,rz:-a,color:'#637e8c'});}c.draw('hand'+p.i,'box',{x:x+Math.sin(p.dial)*.55,y:y+Math.cos(p.dial)*.55,z:1.62,sx:.08,sy:1.1,sz:.08,rz:-p.dial,color:'#cc8ca4'});ball(c,'goal'+p.i,x+Math.sin(p.goal)*1.5,1.58,'#dcac93',.25,y+Math.cos(p.goal)*1.5);txt(c,'arrow'+p.i,p.turn>0?'→':'←',x,0,5,3);});},timeout(){c.complete([]);}};
};

games['Player Conveyor']=c=>{
 init(c,120);c.view={size:23,eye:[0,24,22],target:[0,0,0]};const nodes=Array.from({length:25},(_,i)=>({id:i,x:(i%5-2)*3,z:(Math.floor(i/5)-2)*3})),edges=[],pipes=new Map([[4,20],[20,4]]),bad=new Set([9,15]),starts=[0,4,24,20];let serial=0;
 function add(a,b){if(!edges.some(e=>e.a===a&&e.b===b))edges.push({id:serial++,a,b});}
 function rotate(id){return(id%5)*5+4-Math.floor(id/5);}
 const route=[0,1,6,5,10,11,12];for(let r=0;r<4;r++){let path=[...route];for(let k=0;k<r;k++)path=path.map(rotate);for(let i=0;i<path.length-1;i++)add(path[i],path[i+1]);}[[1,2],[2,3],[3,4],[6,7],[7,8],[8,9],[5,15],[10,20],[11,16],[16,17],[17,18],[18,19],[19,24],[23,22],[22,21],[21,20],[14,13],[13,12]].forEach(([a,b])=>add(a,b));
 function pathFrom(start){const queue=[[start]],seen=new Set();while(queue.length){const path=queue.shift(),n=path.at(-1);if(n===12)return path;if(seen.has(n))continue;seen.add(n);for(const e of edges.filter(e=>e.a===n))queue.push([...path,e.b]);}return[start];}
 c.players.forEach((p,i)=>{p.node=starts[i];p.travel=null;p.holdUntil=0;p.x=nodes[p.node].x;p.z=nodes[p.node].z;});
 return{update(dt){const done=[];for(const p of c.players){const route=pathFrom(p.node),goal=nodes[route[1]??p.node],u=c.input(p,p.travel?{}:toward(p,goal.x,goal.z));if(p.travel){const t=p.travel,a=nodes[t.a],b=nodes[t.b];t.f=Math.min(1,t.f+dt*4/dist(a,b));p.x=a.x+(b.x-a.x)*t.f;p.z=a.z+(b.z-a.z)*t.f;if(t.f===1){p.node=t.b;p.travel=null;if(p.node===12)done.push(p.i);else if(bad.has(p.node)){p.node=starts[p.i];Object.assign(p,{x:nodes[p.node].x,z:nodes[p.node].z});p.holdUntil=c.time+.6;}else if(pipes.has(p.node)&&p.node!==starts[p.i]){p.node=pipes.get(p.node);Object.assign(p,{x:nodes[p.node].x,z:nodes[p.node].z});p.holdUntil=c.time+.4;}}}else if(c.time>=p.holdUntil&&Math.hypot(u.x,u.z)>.3){const options=edges.filter(e=>e.a===p.node).map(e=>{const b=nodes[e.b],v=toward(p,b.x,b.z);return{e,dot:v.x*u.x+v.z*u.z};}).sort((a,b)=>b.dot-a.dot);if(options[0]?.dot>.5)p.travel={...options[0].e,f:0};}p.score=p.node===12?1:0;}finish(c,done,'컨베이어 미로의 중앙에 먼저 도착했습니다.');c.hint('방향키로 벨트를 고르세요. 벨트 위에서는 끝까지 내려올 수 없습니다. 파이프는 반대편으로, !는 바깥 출발점으로 보냅니다.'+(c.time>=60?' 1분 경과: 중앙 경로가 밝아졌습니다.':''));},render(){c.arena({width:17,depth:17,color:'#aeb9b0'});const lit=new Set();if(c.time>=60)c.players.forEach(p=>{const path=pathFrom(p.node);for(let i=0;i<path.length-1;i++)lit.add(path[i]+'-'+path[i+1]);});edges.forEach(e=>{const a=nodes[e.a],b=nodes[e.b],length=dist(a,b),color=lit.has(e.a+'-'+e.b)?'#ead690':length>3?'#d6a5b4':'#8eafbc';line(c,'belt'+e.id,a,b,color,.75,.06,.12);for(let k=1;k<4;k++){const dx=(b.x-a.x)/length,dz=(b.z-a.z)/length,m={x:a.x+(b.x-a.x)*k/4,z:a.z+(b.z-a.z)*k/4},tip={x:m.x+dx*.25,z:m.z+dz*.25};for(const sign of[-1,1])line(c,`arrow${e.id}-${k}-${sign}`,tip,{x:m.x-dx*.2-dz*.2*sign,z:m.z-dz*.2+dx*.2*sign},'#577583',.055,.18);}});nodes.forEach(n=>{box(c,'node'+n.id,n.x,n.z,n.id===12?'#ead690':'#cbd0bc',1.3,1.3,.05,.1);if(bad.has(n.id))txt(c,'bad'+n.id,'!',n.x,n.z,.4,2);if(pipes.has(n.id))ring(c,'pipe'+n.id,n.x,n.z,'#83a697',1.25,.2);});},timeout(){c.complete([],'2분 동안 중앙에 도착하지 못했습니다.');}};
};

games['Ballistic Beach']=c=>{
 init(c,Infinity);c.view={size:29,eye:[0,25,26],target:[0,0,0]};c.players.forEach(p=>{p.angle=0;p.range=10;p.shot=null;p.targets=[{x:-1.7,s:11+c.rand(-1,1),hit:false},{x:2,s:18+c.rand(-1,1),hit:false}];});
 return{update(dt){const done=[];for(const p of c.players){const target=p.targets.find(t=>!t.hit),angle=target?Math.atan2(target.x,target.s):0,range=target?Math.hypot(target.x,target.s):0,u=c.input(p,{x:clamp((angle-p.angle)*8,-1,1),z:clamp((p.range-range)*2,-1,1),a:target&&Math.abs(angle-p.angle)<.025&&Math.abs(range-p.range)<.15&&!p.shot&&tap(c,p,.4)});p.angle=clamp(p.angle+u.x*dt*.7,-.45,.45);p.range=clamp(p.range-u.z*dt*7,5,23);if(u.ap&&!p.shot){const flight=1.4;p.shot={x:0,s:0,y:.4,vx:Math.sin(p.angle)*p.range/flight,vs:Math.cos(p.angle)*p.range/flight,vy:7.1,age:0};}if(p.shot){const b=p.shot;b.age+=dt;b.x+=b.vx*dt;b.s+=b.vs*dt;b.vy-=10*dt;b.y+=b.vy*dt;for(const t of p.targets)if(!t.hit&&Math.hypot(b.x-t.x,b.s-t.s)<.8&&Math.abs(b.y-.7)<1){t.hit=true;p.score++;p.shot=null;break;}if(p.shot&&(b.y<0||b.age>3))p.shot=null;}p.x=(p.i-1.5)*6.8;p.z=8;p.y=0;if(p.targets.every(t=>t.hit))done.push(p.i);}finish(c,done,'먼 섬의 두 풍선을 먼저 맞혔습니다.');c.hint('←/→ 대포 방향 · ↑/↓ 사거리 · A 발사. 한 번에 포탄 하나만 날릴 수 있습니다. 두 섬의 풍선 모두를 맞히세요.');},render(){box(c,'ocean',0,0,'#8fb7c0',29,24,-.6,.2);c.players.forEach(p=>{const x=(p.i-1.5)*6.8;box(c,'beach'+p.i,x,8,'#d6c7a4',6,3,-.2,.4);p.targets.forEach((t,i)=>{const z=8-t.s*.7;box(c,`island${p.i}-${i}`,x+t.x,z,'#c5c8a1',2,2,-.2,.4);if(!t.hit)ball(c,`target${p.i}-${i}`,x+t.x,z,'#dba4b7',1,.7);});line(c,'barrel'+p.i,{x,z:8},{x:x+Math.sin(p.angle)*1.8,z:8-Math.cos(p.angle)*1.8},'#8195a0',.55,.75);const landing={x:x+Math.sin(p.angle)*p.range,z:8-Math.cos(p.angle)*p.range*.7};ring(c,'aim'+p.i,landing.x,landing.z,p.color,.6,.05);if(p.shot)ball(c,'shot'+p.i,x+p.shot.x,8-p.shot.s*.7,'#758996',.4,p.shot.y);});},timeout(){c.complete([]);}};
};

games['Magma Mayhem']=c=>{
 init(c,60);let tiltX=0,tiltZ=0;c.players.forEach((p,i)=>{p.x=i<2?-2:2;p.z=i%2?-2:2;});
 return{update(dt){const alive=c.players.filter(p=>p.alive),sum=alive.reduce((v,p)=>({x:v.x+p.x,z:v.z+p.z}),{x:0,z:0});tiltX+=(clamp(sum.x/20,-.35,.35)-tiltX)*dt*3;tiltZ+=(clamp(sum.z/20,-.35,.35)-tiltZ)*dt*3;c.players.forEach(p=>p.y=p.h||0);combat(c,dt,p=>{const q=near(p,c.players.filter(q=>q!==p&&q.alive)),edge=Math.hypot(p.x,p.z)>4,goal=edge?{x:0,z:0}:q||p;return{...toward(p,goal.x,goal.z),b:q&&dist(p,q)<1.2&&tap(c,p,.35),a:q&&dist(p,q)<1.5&&tap(c,p,.6)};});for(const p of c.players){if(!p.alive)continue;if(p.y<.15){p.vx+=tiltX*dt*14;p.vz+=tiltZ*dt*14;}if(Math.hypot(p.x,p.z)>5.5)c.eliminate(p);p.h=p.y;p.y=p.h-tiltX*p.x-tiltZ*p.z;}c.lastStanding();c.hint('이동 · A 점프 · B 펀치/공중 발차기. 선수들이 몰린 쪽으로 발판이 기울어 미끄러집니다. 상대를 용암으로 밀어내고 60초 동안 버티세요.');},render(){box(c,'lava',0,0,'#bf8e82',22,16,-1,.4);c.draw('platform','cylinder',{x:0,y:-.25,z:0,sx:11,sy:.5,sz:11,rx:tiltZ,rz:-tiltX,color:'#afb3a2'});},timeout(){c.survivors('60초 동안 기울어지는 발판에 남았습니다.');}};
};

games['Whomp Stomp']=c=>{
 init(c,Infinity);let hp=36,phase='choose',until=10,round=1,rotation=0,extra=0,victim=-1,attackUntil=0;const maxHp=hp;c.players.forEach(p=>{p.choice=0;p.gp=false;p.h=0;});
 function setup(){round++;phase='choose';until=c.time+10;extra=hp<=maxHp/2?c.int(1,2):0;c.players.forEach(p=>{p.choice=0;p.gp=false;p.h=0;p.vy=0;});}
 return{update(dt){const pounds=[];for(const p of c.players){let raw={};if(phase==='choose')raw={x:p.phase>.5?1:-1};else if(phase==='attack'&&p.i!==victim)raw={a:tap(c,p,.24)};const u=c.input(p,raw);if(phase==='choose'){if(u.x<-.3)p.choice=0;if(u.x>.3)p.choice=1;}else if(phase==='attack'&&p.i!==victim){if(u.ap){if(p.h===0){p.h=.01;p.vy=7;}else if(p.h>.25){p.gp=true;p.vy=-12;}}if(p.h>0){p.vy-=18*dt;p.h+=p.vy*dt;if(p.h<=0){p.h=0;if(p.gp)pounds.push(p);p.gp=false;}}}const a=(p.i+rotation)*TAU/4;p.x=phase==='attack'&&p.i!==victim?(p.i-1.5)*2:Math.cos(a)*5;p.z=phase==='attack'&&p.i!==victim?0:Math.sin(a)*5;p.y=p.h+(phase==='attack'&&p.i!==victim?.6:0);}if(phase==='choose'&&c.time>=until){rotation=(rotation+c.players.reduce((s,p)=>s+p.choice,0)+extra)%4;victim=c.players.find(p=>(p.i+rotation)%4===3).i;c.players[victim].score=Math.max(0,c.players[victim].score-1);phase='slam';until=c.time+1;}else if(phase==='slam'&&c.time>=until){phase='attack';attackUntil=c.time+4;}else if(phase==='attack'){for(const p of c.shuffle(pounds)){if(hp<=0)break;hp--;c.points(p,3);if(hp===0)c.points(p,3);}if(hp===0)highest(c,'돌벽 보스에게 준 공격 점수와 마지막 타격 보너스');else if(c.time>=attackUntil)setup();}c.hint(phase==='choose'?`${round}라운드 · ${Math.max(0,Math.ceil(until-c.time))}초 · 보스 추가 회전 ${extra}. ← 0회 / → 1회 선택, 네 선택을 합쳐 돌립니다.`:phase==='attack'?'눌리지 않은 세 선수: A 점프→공중 A 찍기! 한 번 3점, 마지막 공격은 추가 3점. 눌린 선수는 1점을 잃습니다.':'발판이 회전합니다. 보스 앞 선수는 공격할 수 없습니다!');},render(){c.arena({width:16,depth:16,shape:'cylinder',color:'#a7b0a3'});for(let i=0;i<4;i++){const a=(i+rotation)*TAU/4;box(c,'panel'+i,Math.cos(a)*5,Math.sin(a)*5,c.players[i].color,3.2,3.2,.02,.04);if(phase==='choose')txt(c,'choice'+i,c.players[i].choice,Math.cos(a)*5,Math.sin(a)*5,2.2,2);}const down=phase==='attack';box(c,'boss',0,down?0:-6,'#8c9fa8',7,down?4:1.4,down?.3:2.5,down?.6:5);for(const side of[-1,1])ball(c,'eye'+side,side*1.2,down?1:-5.2,hp<=18?'#dd9ba6':'#d8d2b8',.5,down?.75:3);txt(c,'health',`보스 ${hp}/${maxHp}`,0,-8,4,7);txt(c,'total','회전 '+(c.players.reduce((s,p)=>s+p.choice,0)+extra),0,4,1.2,4);},timeout(){c.complete([]);}};
};

export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['mp9']]));
for(const name of ['Speeding Bullets','Jigsaw Jumble','Goomba Bowling','Magma Mayhem'])supportedTitles[name].push('top-100');
export const notes={
 'Buddy Bounce':'자동 구름 점프·상대 머리 밟기 부스트·풍선 1/3/10점·재등장 5~7초·30초입니다. 가장 높은 풍선은 기본 점프로 닿지 않습니다. 점프 물리와 풍선 배치는 새로 제작했습니다.',
 'Pinball Fall':'5개 중 구슬 독점 선택 10초 후 자동 하강, 범퍼 반사·움직이는 블록·구멍 탈출 연타·경주 5분 제한입니다. 조향으로 구슬 경로를 직접 바꿀 수 없습니다. 핀볼 지도와 탈출 입력 횟수는 자체 조정했습니다.',
 'Speeding Bullets':'대시 구역마다 한 단계 가속, 충돌 시 1단계, 속도에 비례한 조향을 적용했습니다. Top100은 지면 파이프를 제거하는 버전 분기입니다. 코스와 속도 수치는 자체 제작, 강제 종료시간은 미확인으로 넣지 않았습니다.',
 'Pianta Pool':'분홍 3점 두 개·금색 5점 한 개를 모두 주운 뒤 다음 묶음을 던집니다. 고리를 들어 물고기가 통과하는 동안 잠깐 멈추며, 60초 직전 잡은 링도 보상합니다. 수영 관성과 연출은 자체 제작했습니다.',
 'Chain Event':'기울기 좌우를 방향키에 대응했습니다. 사슬 옆을 바꿔 가시공을 피하면 가속, 피격 시 기절·감속하며 먼저 바닥 도착이 승리인 일반 모드입니다. 코스는 새로 제작, 미확인 시간 상한은 넣지 않았습니다.',
 'Skyjinks':'일반 모드의 자동 스크롤, 회전 원판/십자·T자 발판/탄성 구름, 하트 3개 소모 후 추가 추락 탈락, 앞 발판 무작위 복귀를 구현했습니다. 먼저 결승에 닿거나 마지막 생존이면 승리입니다. 코스와 스크롤 속도는 자체 제작했습니다.',
 'Mecha Choice':'3초 동안 A/B/C 문 선택을 바꿀 수 있으며 막다른 길 하나와 미선택은 탈락합니다. 5라운드 또는 마지막 생존, 모두 탈락할 때 문을 고른 생존자들의 순위가 미선택보다 앞섭니다. 새로운 복도를 제작했습니다.',
 'Jigsaw Jumble':'누른 채 조각을 집어 빈칸으로 끌고 놓는 5개 퍼즐이며, 후보가 4개부터 8개로 늘어납니다. 오답은 튕겨 돌아가며 5분에 무승부입니다. 새 색무늬 퍼즐을 사용하고 MP9 포인터/Top100 터치 조작을 브라우저 포인터와 커서로 대응했습니다.',
 'Upward Mobility':'체크무늬 점프 블록은 착지 부스트, 일반 블록은 직접 A 점프이며 앞부분 쌍 발판·후반 단일 발판을 건너 꼭대기 착지로 승리합니다. 높이·점프 물리·코스는 새로 제작, 강제 시간 상한은 미확인입니다.',
 'Ring Leader':'낮은 빨강 링 1점, 잠수 후 높이 뛰어야 하는 금 링 3점, 코스 총 40점입니다. 위로 흔들기=A, 잠수 유지=B에 대응했으며 한 번의 점프로 연속 링 통과가 가능한 실제 포물선입니다. 자체 코스 속도를 사용합니다.',
 'Smash Compactor':'매 라운드 생존자보다 하나 적은 구멍, 마감 때 땅에 발을 붙인 위치 경쟁과 펀치/발차기·점프를 구현했습니다. 원작 라운드 길이는 미확인이라 5초를 브라우저판 템포로 사용하며 최후 생존까지 반복합니다.',
 'Toad and Go Seek':'4초 사전 장면에서 친구가 들어가는 집을 보여주고, 2분 동안 이동·문 두드리기로 찾습니다. 1분 후 정답 위치 표시, 오답 집의 다른 손님을 구현했습니다. 소개 길이와 마을은 새로 제작했습니다.',
 'Polar Extreme':'자동 스크롤·떠밀리는 얼음·큰 얼음 분열·물에서 연타로 재점프·연속 네 번 물에 빠지기와 뒤처짐 탈락을 구현했습니다. 펭귄 접촉 기절/밟으면 1초 납작, 배 도착 또는 마지막 생존입니다. 지형·구조 물리는 새로 제작했습니다.',
 'Goomba Bowling':'일반 1투구 모드, 무작위 순서·15초 조준·움직이는 일렬 핀 20개·최다 타격입니다. MP9 A 위치/각도 전환·B 투구, Top100 별도 위치/각도·A 투구로 분기합니다. 5프레임 Extra Mode는 포함하지 않습니다.',
 'Tumble Temple':'60초 동안 작은/큰 가시공을 피하며 핀은 주기적으로 켜지고 꺼집니다. 30초 뒤 회전 기둥은 실제 가속하고 가장자리 추락은 막았습니다. 일반 생존 모드이며 역전 모드는 포함하지 않습니다. 핀 배치·발사 패턴은 새로 제작했습니다.',
 'Twist Ending':'동·은·금 상자의 8·12·16눈금과 점점 빠른 다이얼입니다. 화살표 방향으로만 돌릴 수 있어 지나치면 한 바퀴를 돌아야 합니다. 정확한 정지 판정·회전 속도 수치는 브라우저판 조정이며 전체 시간 상한은 미확인입니다.',
 'Player Conveyor':'벨트는 진입 후 끝까지 강제 이동, 방향 선택은 끝의 고정 칸에서 합니다. 파이프 반대편 이동·!칸 출발점 복귀·1분 경로 강조·2분 제한입니다. 연결 미로는 새로 제작했습니다.',
 'Ballistic Beach':'좌우 각도·상하 사거리·한 번에 포탄 하나의 실제 포물선으로 먼 섬 풍선 두 개를 먼저 맞힙니다. Time Attack의 다섯 표적 대신 일반 모드입니다. 탄도와 섬은 새로 제작, 강제 시간 상한은 미확인입니다.',
 'Magma Mayhem':'60초 기울기 격투판, 선수 위치로 기울기를 만들고 실제 미끄럼·펀치/발차기 밀침·추락을 계산합니다. 마지막 생존 또는 시간 종료 생존자 모두 승리이며 MP9/Top100 기본 규칙입니다. 기울기 물리는 새로 제작했습니다.',
 'Whomp Stomp':'각자 0/1 회전 선택 10초, 합산 회전 후 앞 선수 1점 감점, 나머지 세 명의 점프→찍기 3점, 체력 절반부터 보스 +1/+2 회전, 마지막 공격 +3점입니다. 원작 정확 체력/공격창은 미확인으로 브라우저판 36타·4초 공격창을 명시합니다.'
};
