import { clamp, dist, toward } from '../core.js';
const TAU=Math.PI*2, KEYS=['a','b','c','d'];
const scored=(c,reason)=>Math.max(...c.players.map(p=>p.score))>0?c.highest(reason):c.complete([],'무득점 무승부');
const unequal=(c,reason)=>c.players.every(p=>p.score===c.players[0].score)?c.complete([],'전원 동점 무승부'):c.highest(reason);
const label=(c,id,text,x=0,z=-6,y=2,sx=8,color='#233d47')=>c.draw(id,'text',{text,x,y,z,sx,sy:.9,color});
const ball=(c,id,x,z,color,size=.5,y=.3)=>c.draw(id,'sphere',{x,y,z,sx:size,sy:size,sz:size,color});
const box=(c,id,x,z,color,sx=1,sz=1,y=0,sy=.2)=>c.draw(id,'box',{x,y,z,sx,sy,sz,color});
const pulse=(c,p,period=.3)=>((c.time+p.i*.043)%period)<period*.42;
const steer=(p,x,z)=>toward(p,x,z);
function positions(c){c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=3.5;p.y=0;});}
function nearest(p,items){return items.reduce((best,item)=>!best||dist(p,item)<dist(p,best)?item:best,null);}
function combat(c,p,u,others){
 if((p.stun||0)>c.time)return;
 c.move(p,u,4.8,false);c.jump(p,u);
 if(u.bp&&(p.attackAt||0)<c.time){p.attackAt=c.time+.38;p.pose='attack';for(const q of others){if(q!==p&&q.alive&&dist(p,q)<1.45){const v=toward(p,q.x,q.z);q.x+=v.x*(p.y>.4?1.5:1);q.z+=v.z*(p.y>.4?1.5:1);q.stun=c.time+.3;}}}
}
export const games={};

games['Smashdance']=(c)=>{
 c.limit=30;c.bounds={x:6.7,z:4.4};positions(c);const tiles=Array.from({length:35},(_,i)=>({x:(i%7-3)*2,z:(Math.floor(i/7)-2)*2,lit:c.rand()<.35,until:c.rand(.4,3)}));
 return {update(dt){for(const t of tiles)if(c.time>t.until){t.lit=!t.lit;t.until=c.time+c.rand(.6,2.5);}for(const p of c.players){const t=nearest(p,tiles.filter(t=>t.lit));const bot=t?{...steer(p,t.x,t.z),a:p.y>.25?!p.wasA:dist(p,t)<.6&&!p.wasA}:{};const u=c.input(p,bot);p.wasA=u.a;if(c.time<(p.stun||0))continue;c.move(p,u,4.8);if(u.ap&&p.y>.15){p.pound=true;p.vy=-12;}const was=p.y;c.jump(p,u);if(was>0&&p.y===0&&p.pound){p.pound=false;const tile=nearest(p,tiles);if(tile?.lit&&dist(p,tile)<.8){tile.lit=false;tile.until=c.time+.5;c.points(p);}for(const q of c.players)if(q!==p&&dist(p,q)<.7)q.stun=c.time+.8;}}c.hint('A: 점프 → 공중에서 다시 A: 쿵! 빛나는 발판을 찍으세요.');},render(){c.arena({color:'#3e6980'});tiles.forEach((t,i)=>box(c,'tile'+i,t.x,t.z,t.lit?'#fff294':'#426a7c',1.85,1.85,.03));},timeout(){c.highest('빛나는 발판을 가장 많이 찍었습니다.');}};
};

games['Odd Card Out']=(c)=>{
 c.limit=70;positions(c);let round=0,phase='start',until=0,odd=0,variant=0,answered=false;
 function next(){round++;phase='play';until=c.time+5;odd=c.int(0,2);variant=c.int(0,2);answered=false;c.players.forEach(p=>{p.reaction=c.time+c.rand(.45,1.5);p.guess=c.rand()<.86?odd:c.int(0,2);});}
 return {update(){if(phase==='start'||phase==='pause'&&c.time>=until)next();const inputs=c.players.map(p=>c.input(p,{[KEYS[p.guess||0]]:phase==='play'&&c.time>=p.reaction&&p.skip!==round}));if(phase==='play'){const picks=c.players.filter(p=>p.skip!==round).map(p=>({p,idx:KEYS.slice(0,3).findIndex(k=>inputs[p.i][k+'p'])})).filter(v=>v.idx>=0);if(picks.length&&!answered){answered=true;for(const {p,idx} of picks){if(idx===odd)c.points(p);else p.skip=round+1;}const winners=picks.filter(v=>v.idx===odd&&v.p.score>=2).map(v=>v.p.i);if(winners.length)c.complete(winners,'다른 카드 2장을 먼저 찾았습니다.');phase='pause';until=c.time+.8;}if(c.time>=until&&phase==='play'){phase='pause';until=c.time+.4;}if(round>=10&&phase==='pause')c.complete([],'10라운드 안에 2점 달성자가 없습니다.');}c.hint(`다른 카드 한 장: 왼쪽 A · 가운데 B · 오른쪽 C / ${round}라운드. 오답이면 다음 문제를 쉽니다.`);},render(){c.arena({color:'#d1b78d'});for(let i=0;i<3;i++){box(c,'card'+i,(i-1)*4,0,'#fff6e6',3.2,3.5,.15);ball(c,'face'+i,(i-1)*4,0,i===odd&&variant===0?'#65bba2':'#ef9d81',1.6,.7);for(let e=0;e<2;e++)ball(c,`eye${i}${e}`,(i-1)*4+(e?-.3:.3),-.25,'#213d47',i===odd&&variant===1?.1:.24,1.25);if(variant===2)box(c,'mark'+i,(i-1)*4,.55,i===odd?'#518cc7':'#ffd15b',.6,.3,1);label(c,'key'+i,KEYS[i].toUpperCase(),(i-1)*4,2,1,2);}label(c,'round',`${round} / 10`,0,-4);},timeout(){c.complete([],'2점 선취자가 없습니다.');}};
};

games['Freeze Frame']=(c)=>{
 c.limit=10;c.bounds={x:7,z:4};positions(c);const critters=Array.from({length:20},(_,i)=>({x:c.rand(-7,7),z:c.rand(-4,2),vx:c.rand(-1,1),vz:c.rand(-.7,.7),gold:i<2}));const curs=c.players.map(p=>({x:p.x,z:0,shot:false,score:0}));
 return {update(dt){for(const q of critters){q.x+=q.vx*dt;q.z+=q.vz*dt;if(Math.abs(q.x)>7)q.vx*=-1;if(q.z>2||q.z< -4)q.vz*=-1;}for(const p of c.players){const r=curs[p.i];let aim=critters.reduce((best,q)=>{const n=critters.filter(o=>Math.abs(q.x-o.x)<2&&Math.abs(q.z-o.z)<1.5).reduce((s,o)=>s+(o.gold?3:1),0);return n>best.n?{...q,n}:best;},{x:0,z:0,n:-1});const u=c.input(p,{...steer(r,aim.x,aim.z),a:c.time>6+p.i*.7&&dist(r,aim)<.8});if(!r.shot){r.x=clamp(r.x+u.x*dt*4,-7,7);r.z=clamp(r.z+u.z*dt*4,-4,3);if(u.ap){r.shot=true;r.score=critters.filter(q=>Math.abs(q.x-r.x)<2&&Math.abs(q.z-r.z)<1.5).reduce((s,q)=>s+(q.gold?3:1),0);c.points(p,r.score);}}}if(curs.every(r=>r.shot))c.highest('한 장의 사진에 담긴 점수');c.hint('방향키: 사진틀 이동 · A: 단 한 번 촬영. 분홍 새우 1점, 금색 3점.');},render(){c.arena({color:'#bfd3aa'});critters.forEach((q,i)=>{ball(c,'critter'+i,q.x,q.z,q.gold?'#efbd45':'#f79ba9',.55,.4);});curs.forEach((r,i)=>{const co=c.players[i].color;for(let side=0;side<4;side++)box(c,`frame${i}${side}`,r.x+(side<2?(side?2:-2):0),r.z+(side>1?(side===2?-1.5:1.5):0),co,side<2?.05:4,side<2?3:.05,.55,.05);label(c,'taken'+i,r.shot?`${i+1}P ${r.score}점`:`${i+1}P`,r.x,r.z,1.4,2,co);});},timeout(){curs.some(r=>r.shot)?c.highest('촬영한 사진의 점수'):c.complete([],'아무도 촬영하지 않았습니다.');}};
};

games['Catch You Letter']=(c)=>{
 c.limit=30;positions(c);const courier={x:0,z:0};const letters=Array.from({length:26},(_,i)=>({x:c.rand(-7,7),z:c.rand(-4,4),y:c.rand(0,7),value:i<2?3:1,available:true}));
 return {update(dt){courier.x=Math.sin(c.time*.67)*5;courier.z=Math.cos(c.time*.89)*3;for(const l of letters)if(l.available)l.y=Math.max(.06,l.y-dt*1.6);for(const p of c.players){const target=p.letter?courier:nearest(p,letters.filter(l=>l.available&&l.y<.2));const u=c.input(p,target?steer(p,target.x,target.z):{});c.move(p,u,5.2);if(p.letter){if(dist(p,courier)<.8){const delivered=p.letter;c.points(p,delivered.value);p.letter=null;if(delivered.value===1){Object.assign(delivered,{available:true,x:c.rand(-7,7),z:c.rand(-4,4),y:c.rand(3,6)});}}}else{const l=letters.find(l=>l.available&&l.y<.2&&dist(p,l)<.5);if(l){l.available=false;p.letter=l;}}}c.hint('이동만으로 줍고 배달! 한 번에 편지 한 장. 움직이는 금색 우체부에게 가져가세요.');},render(){c.arena({color:'#aad0b7'});ball(c,'courier',courier.x,courier.z,'#f2c854',1.1,.8);label(c,'mail','우체부',courier.x,courier.z,2.1,2.5);letters.forEach((l,i)=>{if(l.available)box(c,'letter'+i,l.x,l.z,l.value===3?'#ee6797':'#fffcdf',.5,.32,l.y,.07);});c.players.forEach(p=>{if(p.letter)box(c,'held'+p.i,p.x,p.z-.4,p.letter.value===3?'#ee6797':'#fffddd',.5,.3,1.25,.08);});}};
};

games['Snow Whirled']=(c,meta={})=>{
 c.limit=45;positions(c);const cap=meta.titleId==='superstars'?9990:9720;let turn=0,start=0,phase='slide';const seq=['a','b','c','d'];c.players.forEach(p=>{p.seq=0;p.nextSpin=0;p.spinInterval=c.rand(.13,.21);});
 return {update(){const p=c.players[turn],t=c.time-start;if(phase==='slide'&&t>1.5)phase='air';for(const q of c.players){let raw={};if(q===p&&phase==='air'&&c.time>=q.nextSpin){raw[seq[q.seq%4]]=true;q.nextSpin=c.time+q.spinInterval;}const u=c.input(q,raw);if(q===p&&phase==='air'){const key=seq[q.seq%4];if(u[key+'p']){q.seq++;c.points(q,Math.min(90,cap-q.score));q.rotation+=Math.PI/2;}q.y=Math.max(0,Math.sin((t-1.5)/5*Math.PI)*3);q.pose='jump';}}if(t>=6.5){p.y=0;turn++;start=c.time;phase='slide';if(turn>=4)unequal(c,'착지 전 회전 각도가 가장 큽니다.');}c.hint(`${Math.min(turn+1,4)}P 차례 · 공중에서 A → B → C → D를 순서대로 반복! 원작 A/B/Y/X를 재배치했습니다.`);},render(){c.arena({color:'#edf5fb'});box(c,'ramp',0,-1,'#c9dfed',15,3,.15,.6);c.players.forEach(p=>{box(c,'board'+p.i,p.x,p.z,p.color,1.8,.4,p.y+.02,.08);label(c,'spin'+p.i,`${p.score}°`,p.x,p.z,3.8,3);});},timeout(){unequal(c);}};
};

games['Trap Ease Artist']=(c)=>{
 c.limit=10;const cages=[{x:-4,z:-2},{x:4,z:-2},{x:-4,z:2},{x:4,z:2}];positions(c);const bugs=Array.from({length:35},(_,i)=>({x:c.rand(-8,8),z:c.rand(-4.5,4.5),vx:c.rand(-1.5,1.5),vz:c.rand(-1.1,1.1),gold:i<5}));
 function drop(p){if(p.dropped)return;p.dropped=true;const r=cages[p.i];const caught=bugs.filter(b=>b.captured===undefined&&Math.abs(b.x-r.x)<1.8&&Math.abs(b.z-r.z)<1.5);caught.forEach(b=>b.captured=p.i);c.points(p,caught.reduce((s,b)=>s+(b.gold?3:1),0));}
 return {update(dt){bugs.forEach(b=>{if(b.captured!==undefined)return;b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>8)b.vx*=-1;if(Math.abs(b.z)>4.5)b.vz*=-1;});c.players.forEach(p=>{const r=cages[p.i],n=bugs.filter(b=>Math.abs(b.x-r.x)<1.8&&Math.abs(b.z-r.z)<1.5).length;const u=c.input(p,{a:c.time>2+p.i*.4&&(n>=4||c.time>8)});if(u.ap)drop(p);});if(c.time>=10){c.players.forEach(drop);scored(c,'우리 안에 잡은 점수');}else if(c.players.every(p=>p.dropped))scored(c,'우리 안에 잡은 점수');c.hint('A: 내 우리를 한 번 내리기. 분홍 새우 1점, 금색 3점. 10초 끝에는 자동 낙하!');},render(){c.arena({color:'#b5c998'});bugs.forEach((b,i)=>ball(c,'bug'+i,b.x,b.z,b.gold?'#eabd44':'#ee9fac',.42));cages.forEach((r,i)=>{const y=c.players[i].dropped?.65:3;for(let k=0;k<4;k++)box(c,`cage${i}${k}`,r.x+(k<2?(k?1.8:-1.8):0),r.z+(k>=2?(k===2?-1.5:1.5):0),c.players[i].color,k<2?.08:3.6,k<2?3:.08,y,1.3);label(c,'cagelabel'+i,`${i+1}P`,r.x,r.z,y+1,2);});},timeout(){c.players.forEach(drop);scored(c);}};
};

games['Mowtown']=(c)=>{
 c.limit=30;positions(c);const grass=Array.from({length:300},(_,i)=>({x:(i%25-12)*.6,z:(Math.floor(i/25)-5.5)*.7,cut:false}));c.players.forEach(p=>{p.heading=-Math.PI/2;p.turnGain=c.rand(1.4,2.6);});
 return {update(dt){for(const p of c.players){const target=nearest(p,grass.filter(g=>!g.cut));let turn=0;if(target){const angle=Math.atan2(target.z-p.z,target.x-p.x);turn=Math.atan2(Math.sin(angle-p.heading),Math.cos(angle-p.heading));}const u=c.input(p,{x:clamp(turn*p.turnGain,-1,1),a:Math.abs(turn)<1.25});p.heading+=(u.x||0)*dt*2.5;const drive=(u.a?1:0)-(u.b?1:0);c.move(p,{x:Math.cos(p.heading)*drive,z:Math.sin(p.heading)*drive},3.5);if(u.a)for(const g of grass)if(!g.cut&&dist(p,g)<.52){g.cut=true;c.points(p);}p.rotation=-p.heading;}c.hint('←/→: 방향 전환 · A 누르기: 전진하며 깎기 · B: 후진. 남은 풀을 찾아 가세요.');},render(){c.arena({color:'#8cbb82'});grass.forEach((g,i)=>{if(!g.cut)box(c,'grass'+i,g.x,g.z,'#4c9963',.13,.14,.28,.55);});c.players.forEach(p=>box(c,'mower'+p.i,p.x+Math.cos(p.heading)*.5,p.z+Math.sin(p.heading)*.5,p.color,.8,.75,.2,.4));},timeout(){unequal(c,'깎은 풀의 넓이');}};
};

games['Note to Self']=(c)=>{
 c.limit=30;positions(c);const notes=Array.from({length:3},(_,i)=>({x:(i-1)*4,z:0,y:1.6,vx:c.rand(-3,3),vz:c.rand(-2,2),last:-1}));
 return {update(dt){notes.forEach(n=>{n.x+=n.vx*dt;n.z+=n.vz*dt;if(Math.abs(n.x)>7)n.vx*=-1;if(Math.abs(n.z)>4)n.vz*=-1;});for(const p of c.players){const t=nearest(p,notes),u=c.input(p,{...steer(p,t.x,t.z),a:dist(p,t)<1.4&&pulse(c,p,.6)});c.move(p,u,5);c.jump(p,u);for(const n of notes)if(dist(p,n)<.75&&Math.abs(p.y+.8-n.y)<.7&&c.time>n.last+.23){n.last=c.time;c.points(p);n.vx=c.rand(-3,3);n.vz=c.rand(-2,2);}if(p.y>.5&&p.vy<0)for(const q of c.players)if(q!==p&&q.y<.2&&dist(p,q)<.55){p.vy=8;q.stun=c.time+.5;}}c.hint('이동 · A: 점프. 떠다니는 세 음표를 건드려 점수를 얻으세요.');},render(){c.arena({color:'#aed5cf'});notes.forEach((n,i)=>{ball(c,'notebubble'+i,n.x,n.z,['#f8c659','#ef93b4','#6eafe0'][i],.9,n.y);label(c,'noteglyph'+i,'♪',n.x,n.z,n.y+.1,1,'#fff');});}};
};

games['Same Is Lame']=(c)=>{
 c.limit=65;positions(c);let round=1,until=5,phase='choose';c.players.forEach(p=>{p.choice=-1;p.botChoice=c.int(0,3);});
 return {update(){for(const p of c.players){const u=c.input(p,{[KEYS[p.botChoice]]:phase==='choose'&&c.time>until-2});for(let i=0;i<4;i++)if(u[KEYS[i]+'p']&&phase==='choose')p.choice=i;}if(c.time>=until){if(phase==='choose'){for(const p of c.players)if(p.choice>=0&&c.players.filter(q=>q.choice===p.choice).length===1)c.points(p);const winners=c.players.filter(p=>p.score>=3);if(winners.length)c.complete(winners.map(p=>p.i),'다른 버튼 3회 성공!');phase='reveal';until=c.time+1.3;}else{round++;if(round>10)c.complete([],'10라운드 안에 3점 선취자가 없습니다.');phase='choose';until=c.time+5;c.players.forEach(p=>{p.choice=-1;p.botChoice=c.int(0,3);});}}c.hint(`A/B/C/D 중 하나를 비밀 선택 · ${round}/10라운드. 다른 사람과 겹치지 않아야 상승합니다.`);},render(){c.arena({color:'#9bacc0'});c.players.forEach(p=>{p.y=p.score*.7;box(c,'podium'+p.i,p.x,p.z,p.color,2,2,p.score*.35-.1,p.score*.7+.2);label(c,'choice'+p.i,phase==='reveal'?(p.choice<0?'미선택':KEYS[p.choice].toUpperCase()):'?',p.x,p.z,p.y+2,2);});},timeout(){c.complete([],'무승부');}};
};

games["Monty's Revenge"]=(c)=>{
 c.limit=30;const holes=Array.from({length:11},(_,i)=>i===10?{x:0,z:0}:{x:Math.cos(i/10*TAU)*5.5,z:Math.sin(i/10*TAU)*3.8});positions(c);c.players.forEach((p,i)=>{p.hole=i*2;p.nav=0;p.peek=false;});const moles=Array.from({length:3},(_,i)=>({x:(i-1)*4,z:-3,target:0,strike:0,state:'seek'}));
 return {update(dt){for(const m of moles){if(m.state==='seek'){const peek=c.players.filter(p=>p.peek&&c.time>(p.stun||0));const target=peek.length?nearest(m,peek):null;m.target=target?target.hole:c.int(0,10);m.state='walk';}const h=holes[m.target];if(m.state==='walk'){const v=toward(m,h.x,h.z);m.x+=v.x*dt*3;m.z+=v.z*dt*3;if(dist(m,h)<.2){m.state='raise';m.strike=c.time+.75;}}else if(m.state==='raise'&&c.time>=m.strike){for(const p of c.players)if(p.hole===m.target&&p.peek){p.stun=c.time+2;p.peek=false;}m.state='rest';m.strike=c.time+.5;}else if(m.state==='rest'&&c.time>=m.strike)m.state='seek';}for(const p of c.players){const h=holes[p.hole],danger=moles.some(m=>dist(m,h)<2&&m.state!=='rest');const safe=holes.map((h,i)=>({i,s:Math.min(...moles.map(m=>dist(m,h)))})).sort((a,b)=>b.s-a.s)[0];const bh=holes[safe.i];const u=c.input(p,{x:danger?Math.sign(bh.x-h.x):0,z:danger?Math.sign(bh.z-h.z):0,a:!danger});if(c.time>p.nav&&(Math.abs(u.x)+Math.abs(u.z)>.2)){const candidates=holes.map((h,i)=>({...h,i})).filter(q=>q.i!==p.hole&&((q.x-h.x)*u.x+(q.z-h.z)*u.z)>.2).sort((a,b)=>dist(a,h)-dist(b,h));if(candidates.length)p.hole=candidates[0].i;p.nav=c.time+.22;}p.x=holes[p.hole].x;p.z=holes[p.hole].z;p.peek=!!u.a&&c.time>(p.stun||0);p.y=p.peek?-.3:-1.7;p.score+=p.peek?dt:0;}c.hint('방향키: 구멍 선택 · A를 누르고 있으면 얼굴 내밀기. 망치가 들리면 숨으세요!');},render(){c.arena({color:'#ccb488'});holes.forEach((h,i)=>{c.draw('hole'+i,'cylinder',{x:h.x,y:.02,z:h.z,sx:1.2,sy:.08,sz:1.2,color:'#424e53'});});moles.forEach((m,i)=>{ball(c,'mole'+i,m.x,m.z,'#ac8666',.85,.7);box(c,'hammer'+i,m.x,m.z-.25,'#876348',.8,.45,m.state==='raise'?2:.8,.45);});},timeout(){c.highest('얼굴을 내민 총 시간');}};
};

games['The Final Countdown']=(c)=>{
 c.limit=30;positions(c);c.players.forEach((p,i)=>{p.x=i%2?2:-2;p.z=i<2?-2:2;});const tiles=Array.from({length:9},(_,i)=>({x:(i%3-1)*3,z:(Math.floor(i/3)-1)*3,n:c.int(2,9),next:c.rand(.7,1.4)}));
 return {update(){for(const t of tiles)if(c.time>=t.next){t.n--;if(t.n<0)t.n=c.int(2,9);t.next=c.time+(t.n===0?.9:Math.max(.35,1-c.time*.016));}for(const p of c.players){const safe=tiles.filter(t=>t.n>=3).sort((a,b)=>dist(p,a)-dist(p,b))[0]||tiles[0],foe=nearest(p,c.players.filter(q=>q!==p&&q.alive));const u=c.input(p,{...steer(p,safe.x,safe.z),a:nearest(p,tiles).n<=1&&pulse(c,p,.5),b:foe&&dist(p,foe)<1.35&&pulse(c,p,.6)});if(!p.alive)continue;combat(c,p,u,c.players);const tile=nearest(p,tiles);if((Math.abs(p.x)>4.5||Math.abs(p.z)>4.5||tile.n===0)&&p.y<.25)c.eliminate(p);}c.lastStanding();c.hint('A: 점프 · B: 밀기/공중 발차기. 숫자가 0이 되면 바닥이 열립니다.');},render(){tiles.forEach((t,i)=>{if(t.n>0){box(c,'tile'+i,t.x,t.z,t.n<3?'#ee907e':'#7dafb1',2.92,2.92,-.2,.4);label(c,'number'+i,t.n,t.x,t.z,.18,1.7);}});},timeout(){c.survivors('카운트다운 바닥에서 살아남았습니다.');}};
};

games['Take Me Ohm']=(c)=>{
 c.limit=30;c.bounds={x:6,z:4.2};positions(c);const waves=[];let next=.7,serial=0;
 return {update(dt){if(c.time>next){const a=c.int(0,4)*TAU/5;waves.push({id:serial++%35,a,pos:-7,age:0});next=c.time+c.rand(.75,1.5)*(1-c.time/90);}for(const w of waves){w.age+=dt;if(w.age>1)w.pos+=dt*5;}while(waves.length&&waves[0].pos>9)waves.shift();for(const p of c.players){const near=waves.find(w=>w.age>1&&Math.abs(p.x*Math.cos(w.a)+p.z*Math.sin(w.a)-w.pos)<1.5);const u=c.input(p,{x:Math.sin(c.time+p.i)*.35,z:Math.cos(c.time+p.i)*.35,a:!!near&&pulse(c,p,.4)});c.move(p,u,4.5);c.jump(p,u);for(const w of waves)if(w.age>1&&Math.abs(p.x*Math.cos(w.a)+p.z*Math.sin(w.a)-w.pos)<.3&&p.y<.75)c.eliminate(p);}c.lastStanding();c.hint('A: 점프. 밝게 예고한 방향에서 전기 선이 훑고 지나갑니다!');},render(){c.arena({width:14,depth:11,color:'#536c91'});for(let i=0;i<5;i++){const a=i*TAU/5;box(c,'switch'+i,Math.cos(a)*7,Math.sin(a)*5,'#e4be4f',1,1,.2,.5);}waves.forEach(w=>c.draw('wave'+w.id,'box',{x:Math.cos(w.a)*w.pos,y:.4,z:Math.sin(w.a)*w.pos,sx:.14,sy:.22,sz:18,ry:-w.a,color:w.age<1?'#ddae54':'#edfc99',glow:w.age>1}));},timeout(){c.survivors();}};
};

games['Cointagious']=(c)=>{
 c.limit=20;positions(c);c.players.forEach(p=>{p.die=c.int(0,3);p.tick=0;p.hit=false;});
 return {update(){for(const p of c.players){if(c.time>p.tick){p.die=(p.die+1)%4;p.tick=c.time+.12;}const u=c.input(p,{a:p.y===0&&pulse(c,p,.35)});const y=p.y;c.jump(p,u,7);if(y<.7&&p.y>=.7&&!p.hit){c.points(p,p.die);p.hit=true;}if(p.y===0)p.hit=false;}c.hint('A: 점프해서 0~3 코인 주사위를 치세요. 각자 얻은 코인을 그대로 받습니다.');},render(){c.arena({color:'#d9c394'});c.players.forEach(p=>{box(c,'die'+p.i,p.x,p.z,'#f7d46b',1.2,1.2,2.2,1.2);label(c,'dieface'+p.i,p.die,p.x,p.z+.68,2.2,1);});},timeout(){c.complete(c.players.filter(p=>p.score>0).map(p=>p.i),'각자가 모은 코인을 받습니다.');}};
};

function flower(c,id,frame,x,z,size=1){
 const growth=(frame+1)/16;box(c,id+'paper',x,z,'#fff6dc',2.5*size,2.8*size,.12,.12);box(c,id+'stem',x,z,'#5ca374',.12*size,.9*growth*size,.23,.12);for(let i=0;i<8;i++){const a=i*TAU/8,r=(.16+growth*.54)*size;ball(c,id+'petal'+i,x+Math.cos(a)*r,z+Math.sin(a)*r,'#f29cac',(.14+growth*.2)*size,.3);}ball(c,id+'center',x,z,'#eeb64b',.28*size,.35);box(c,id+'marker',x-.95*size,z+(.9-frame/12)*size,'#6c94b4',.12*size,.12*size,.27,.08);
}
games['Picture This']=(c)=>{
 c.limit=125;positions(c);let target=c.int(0,15),until=20,round=1;c.players.forEach(p=>{p.page=0;p.flipAt=0;});
 return {update(){let winners=[];for(const p of c.players){const diff=target-p.page;const u=c.input(p,{a:diff>0&&pulse(c,p,.23),b:diff<0&&pulse(c,p,.23),c:diff===0&&pulse(c,p,.7)});if(u.ap)p.page=Math.min(15,p.page+1);if(u.bp)p.page=Math.max(0,p.page-1);if(u.cp&&p.page===target)winners.push(p);}if(winners.length){winners.forEach(p=>c.points(p));const done=winners.filter(p=>p.score>=3);if(done.length)c.complete(done.map(p=>p.i),'그림책 3장을 먼저 맞혔습니다.');target=c.int(0,15);until=c.time+20;round++;}if(c.time>=until){target=c.int(0,15);until=c.time+20;round++;}c.hint('A: 다음 장 · B: 이전 장 · C: 책갈피. 위의 꽃 성장 장면과 정확히 같은 장을 찾으세요. 3점 선취!');},render(){c.arena({color:'#baa585'});flower(c,'target',target,0,-3.7,1.25);label(c,'match','이 장면을 찾으세요',0,-6,2,7);c.players.forEach(p=>flower(c,'book'+p.i,p.page,(p.i-1.5)*4,1.2,.95));},timeout(){scored(c,'그림책 맞히기 종료');}};
};

games['Target Tag']=(c)=>{
 c.limit=28;c.view={size:22,eye:[0,18,19],target:[0,0,-1]};const flight=c.players.map(()=>({x:0,y:2}));const rings=Array.from({length:17},(_,i)=>({x:c.rand(-1.4,1.4),y:c.rand(1,3.4),at:2+i*1.35,value:c.pick([5,10,30,50,-1]),hit:[false,false,false,false]}));
 return {update(dt){for(const p of c.players){const f=flight[p.i],target=rings.find(r=>r.at>c.time&&!r.hit[p.i]&&r.value>0);const u=c.input(p,target?{x:clamp((target.x-f.x)*2,-1,1),z:clamp((f.y-target.y)*2,-1,1)}:{});f.x=clamp(f.x+u.x*dt*2.7,-1.75,1.75);f.y=clamp(f.y-u.z*dt*2.7,.5,4);p.x=(p.i-1.5)*4.5+f.x;p.y=f.y;p.z=2;p.pose='jump';for(const r of rings)if(!r.hit[p.i]&&Math.abs(r.at-c.time)<dt*1.2&&Math.hypot(r.x-f.x,r.y-f.y)<(r.value===-1?.9:r.value>=30?.42:.65)){r.hit[p.i]=true;if(r.value===-1)p.score=0;else c.points(p,r.value);}}c.hint('방향키: 공중 조종. 숫자 과녁을 통과하세요. 검은 X 과녁은 점수를 0으로 만듭니다.');},render(){c.arena({color:'#cbe1e1'});rings.forEach((r,i)=>{const z=2+(c.time-r.at)*5;if(z< -14||z>7)return;for(let p=0;p<4;p++)if(!r.hit[p]){const x=(p-1.5)*4.5+r.x,s=r.value===-1?1.8:r.value>=30?.84:1.3;c.draw(`target${i}-${p}`,'ring',{x,y:r.y+.7,z,sx:s,sy:s,sz:s,color:r.value===-1?'#354356':'#efc259'});label(c,`value${i}-${p}`,r.value===-1?'X':r.value,x,z,r.y+.7,.9,r.value===-1?'#263e50':'#9d6640');}});},timeout(){c.highest('착지 전 과녁 점수');}};
};

games['Mario Matrix']=(c)=>{
 c.limit=20;positions(c);const panels=Array.from({length:35},(_,i)=>({x:(i%7-3)*1.6,z:(Math.floor(i/7)-2)*1.4,on:c.rand()<.3,until:c.rand(.2,1.8)}));const curs=c.players.map(p=>({x:p.x,z:0}));
 return {update(dt){for(const t of panels)if(c.time>t.until){t.on=!t.on;t.until=c.time+c.rand(.3,1.4);}for(const p of c.players){const r=curs[p.i],target=nearest(r,panels.filter(t=>t.on)),u=c.input(p,target?{...steer(r,target.x,target.z),a:dist(r,target)<.45&&pulse(c,p,.18)}:{});r.x=clamp(r.x+u.x*dt*6,-5.7,5.7);r.z=clamp(r.z+u.z*dt*6,-3.5,3.5);if(u.ap||u.bp){const t=nearest(r,panels);if(t?.on&&dist(r,t)<.6){t.on=false;t.until=c.time+c.rand(.6,1.7);c.points(p);}}}c.hint('방향키: 색 원 커서 이동 · A/B: 빛나는 칸 활성화. 같은 칸은 먼저 누른 사람의 점수!');},render(){c.arena({color:'#315473'});panels.forEach((t,i)=>c.draw('hex'+i,'cylinder',{x:t.x,y:.1,z:t.z,sx:1.2,sy:.22,sz:1.2,color:t.on?'#a9f3e7':'#4c7894',glow:t.on}));curs.forEach((r,i)=>c.draw('cursor'+i,'ring',{x:r.x,y:.55,z:r.z,sx:1,sy:1,sz:1,rx:Math.PI/2,color:c.players[i].color}));},timeout(){scored(c);}};
};

games['Shake It Up']=(c)=>{
 c.limit=5;positions(c);c.players.forEach(p=>p.shakeCadence=c.rand(.12,.2));return {update(){for(const p of c.players){const u=c.input(p,{a:pulse(c,p,p.shakeCadence)});if(u.ap){c.points(p);p.rotation=Math.sin(c.time*40)*.3;}}c.hint('A를 빠르게 눌렀다 떼세요! 5초 동안 흔든 횟수가 탄산 분수 높이를 결정합니다.');},render(){c.arena({color:'#bcd4b2'});c.players.forEach(p=>{c.draw('can'+p.i,'cylinder',{x:p.x,y:.6,z:p.z-.65,sx:.55,sy:1.15,sz:.55,color:p.color});c.draw('foam'+p.i,'cylinder',{x:p.x,y:.8+p.score*.045,z:p.z-.65,sx:.23,sy:p.score*.09,sz:.23,color:'#faf4d7'});});},timeout(){scored(c,'가장 높은 탄산 분수!');}};
};

games['Sugar Rush']=(c)=>{
 c.limit=60;c.bounds={x:8,z:5};positions(c);const palette=['#e36b82','#5bafe0','#e7bc42','#6eba85','#ab8bc3'];const teams=[0,1].map(t=>({t,center:t?4.4:-4.4,cake:0,slots:[],items:[]}));const curs=c.players.map(p=>({x:(p.i<2?-4.4:4.4)+(p.i%2?.8:-.8),z:3,held:null}));
 function setup(t){const count=t.cake?5:4;t.slots=Array.from({length:count},(_,i)=>({x:t.center+Math.cos(i/count*TAU)*1.1,z:Math.sin(i/count*TAU)*1.1,type:t.cake?c.int(0,4):i,filled:false}));t.items=t.slots.map((s,i)=>({x:t.center+(i-(count-1)/2)*.67,z:3,type:s.type,placed:false,holder:null}));}
 teams.forEach(setup);
 return {update(dt){for(const p of c.players){const t=teams[p.i<2?0:1],r=curs[p.i];let target;if(r.held)target=t.slots.find(s=>!s.filled&&s.type===r.held.type);else target=nearest(r,t.items.filter(q=>!q.placed&&q.holder===null));const u=c.input(p,target?{...steer(r,target.x,target.z),a:dist(r,target)<.3&&pulse(c,p,.4)}:{});r.x=clamp(r.x+u.x*dt*4,t.center-2,t.center+2);r.z=clamp(r.z+u.z*dt*4,-1.8,3.5);if(r.held){r.held.x=r.x;r.held.z=r.z;}if(u.ap){if(r.held){const s=nearest(r,t.slots.filter(q=>!q.filled));if(s&&s.type===r.held.type&&dist(r,s)<.48){r.held.placed=true;s.filled=true;}else{r.held.x=t.center;r.held.z=3;}r.held.holder=null;r.held=null;}else{const q=nearest(r,t.items.filter(q=>!q.placed&&q.holder===null));if(q&&dist(r,q)<.45){r.held=q;q.holder=p.i;}}}}for(const t of teams){const ids=t.t?[2,3]:[0,1],n=t.slots.filter(s=>s.filled).length;ids.forEach(i=>c.players[i].score=t.cake*10+n);if(t.slots.every(s=>s.filled)){t.cake++;if(t.cake<2){ids.forEach(i=>curs[i].held=null);setup(t);}}}const finished=teams.filter(t=>t.cake>=2);if(finished.length)c.complete(finished.length===2?[]:finished.flatMap(t=>t.t?[2,3]:[0,1]),'케이크 2개를 먼저 장식했습니다.');c.hint('방향키: 손 커서 이동 · A: 토핑 집기/놓기. 위 샘플과 같은 색·위치로 케이크 2개를 완성하세요. 1·2P / 3·4P 팀');},render(){c.arena({color:'#d5bc9e'});teams.forEach(t=>{c.draw('cake'+t.t,'cylinder',{x:t.center,y:.2,z:0,sx:3.7,sy:.45,sz:3.7,color:'#fff1d7'});c.draw('sample'+t.t,'cylinder',{x:t.center,y:.2,z:-3.6,sx:2.3,sy:.35,sz:2.3,color:'#fff1d7'});t.slots.forEach((s,i)=>{ball(c,`sampletop${t.t}${i}`,t.center+(s.x-t.center)*.58,-3.6+s.z*.58,palette[s.type],.3,.5);if(s.filled)ball(c,`filled${t.t}${i}`,s.x,s.z,palette[s.type],.5,.7);else c.draw(`slot${t.t}${i}`,'ring',{x:s.x,y:.46,z:s.z,rx:Math.PI/2,sx:.55,sy:.55,sz:.55,color:'#c2ac9b'});});t.items.forEach((q,i)=>{if(!q.placed)ball(c,`top${t.t}${i}`,q.x,q.z,palette[q.type],.5,q.holder===null?.6:1.1);});label(c,'cakecount'+t.t,`${t.cake}/2`,t.center,-5,1.5,3);});curs.forEach((r,i)=>c.draw('hand'+i,'ring',{x:r.x,y:1.05,z:r.z,rx:Math.PI/2,sx:.7,sy:.7,sz:.7,color:c.players[i].color}));},timeout(){c.complete([],'제한 시간 안에 두 케이크를 완성하지 못했습니다.');}};
};

games['Goomba Spotting']=(c)=>{
 c.limit=29;positions(c);const groups=Array.from({length:18},(_,i)=>({at:1+i*1.05,count:c.int(1,4),extra:c.rand()<.5,seen:false}));const critters=[];let actual=0;c.players.forEach(p=>{p.pending=0;});
 return {update(dt){groups.forEach((g,gi)=>{if(!g.seen&&c.time>=g.at){g.seen=true;actual+=g.count;for(let k=0;k<g.count+(g.extra?1:0);k++)critters.push({id:gi*5+k,x:-9,z:Math.floor(k/3)*.85-1,y:(k%3)*.5+.3,target:k<g.count});c.players.forEach(p=>{p.pending+=g.count;if(c.rand()<.05)p.pending+=c.pick([-1,1]);});}});critters.forEach(q=>q.x+=dt*4);for(const p of c.players){const u=c.input(p,{a:p.pending>0&&pulse(c,p,.19)});if(u.ap){c.points(p);if(p.i>=c.humans)p.pending--;}}if(c.time>26){const error=Math.min(...c.players.map(p=>Math.abs(p.score-actual)));c.complete(c.players.filter(p=>Math.abs(p.score-actual)===error).map(p=>p.i),`실제 분홍 새우는 ${actual}마리입니다.`);}c.hint('A: 분홍 새우 한 마리씩 +1. 파란 생물은 세지 마세요! 숫자는 되돌릴 수 없습니다.');},render(){c.arena({color:'#b9d3b4'});box(c,'path',0,-1,'#e5c899',19,2,-.05,.1);critters.forEach(q=>{if(q.x<10){ball(c,'critter'+q.id,q.x,q.z,q.target?'#ee8fa3':'#5b91bb',.65,q.y);ball(c,'eye'+q.id,q.x+.2,q.z+.24,'#233b48',.08,q.y+.15);}});c.players.forEach(p=>label(c,'count'+p.i,p.score,p.x,p.z,2.2,2));},timeout(){const error=Math.min(...c.players.map(p=>Math.abs(p.score-actual)));c.complete(c.players.filter(p=>Math.abs(p.score-actual)===error).map(p=>p.i),`정답 ${actual}마리`);}};
};

games['Shy Guy Shuffle']=(c)=>{
 c.limit=65;positions(c);let round=0,phase='reveal',end=0,swapEnd=0,swaps=0,activeSwap=null,servers=[];const curs=c.players.map((p,i)=>({index:i,choice:null,nav:0}));
 function next(){round++;phase='reveal';end=c.time+2.5;swaps=0;activeSwap=null;servers=c.shuffle([1,2,3,4,5]).map((value,i)=>({id:i,value,slot:i,x:(i-2)*2.7,from:0,to:0}));c.players.forEach(p=>{p.memory=c.rand()<.86?servers.reduce((a,b)=>a.value>b.value?a:b).id:c.int(0,4);});curs.forEach(r=>r.choice=null);}
 next();return {update(){if(phase==='reveal'&&c.time>=end){phase='shuffle';end=c.time+5.4;swapEnd=c.time;}if(phase==='shuffle'){if(c.time>=swapEnd){if(activeSwap){activeSwap.forEach(s=>s.x=(s.slot-2)*2.7);activeSwap=null;}if(c.time>=end){phase='choose';end=c.time+10;}else{let a=c.pick(servers),b=c.pick(servers.filter(s=>s!==a));const tmp=a.slot;a.slot=b.slot;b.slot=tmp;[a,b].forEach(s=>{s.from=s.x;s.to=(s.slot-2)*2.7;});activeSwap=[a,b];swapEnd=c.time+.6;swaps++;}}if(activeSwap){const t=clamp(1-(swapEnd-c.time)/.6,0,1);activeSwap.forEach(s=>s.x=s.from+(s.to-s.from)*(t*t*(3-2*t)));}}for(const p of c.players){const r=curs[p.i],target=servers.find(s=>s.id===p.memory);const u=c.input(p,{x:phase==='choose'?Math.sign(target.slot-r.index):0,a:phase==='choose'&&r.index===target.slot&&c.time>end-8.5-p.i*.2});if(phase==='choose'&&r.choice===null){if(Math.abs(u.x)>.2&&c.time>r.nav){r.index=clamp(r.index+Math.sign(u.x),0,4);r.nav=c.time+.2;}if(u.ap)r.choice=servers.find(s=>s.slot===r.index).id;}}if(phase==='choose'&&(curs.every(r=>r.choice!==null)||c.time>=end)){c.players.forEach(p=>{const choice=servers.find(s=>s.id===curs[p.i].choice);if(choice)c.points(p,choice.value);});phase='result';end=c.time+1.3;}if(phase==='result'&&c.time>=end){if(round>=3)c.highest('세 번 고른 도넛의 합계');else next();}c.hint(`${round}/3라운드 · 도넛을 기억하세요! 섞기가 끝나면 ←/→ 선택, A 확정. ${phase==='shuffle'?'섞는 중':phase==='reveal'?'공개 중':phase==='choose'?'선택하세요':'확인'}`);},render(){c.arena({color:'#c9baa0'});servers.forEach(s=>{ball(c,'server'+s.id,s.x,-.8,'#b5c4bd',.9,.6);c.draw('hat'+s.id,'cone',{x:s.x,y:1.4,z:-.8,sx:1,sy:.7,sz:1,color:'#eef1da'});box(c,'tray'+s.id,s.x,.1,'#8a6d53',1.4,.9,.8,.1);if(phase==='reveal'||phase==='result'){for(let k=0;k<s.value;k++)c.draw(`donut${s.id}-${k}`,'ring',{x:s.x+(k%3-1)*.35,y:.92,z:.1+Math.floor(k/3)*.3,rx:Math.PI/2,sx:.32,sy:.32,sz:.32,color:'#e3a566'});}else box(c,'lid'+s.id,s.x,.1,'#a5b7b8',1.3,.8,1,.22);});if(phase==='choose')curs.forEach((r,i)=>label(c,'select'+i,r.choice!==null?'✓':`${i+1}P`,(r.index-2)*2.7,1.1+i*.4,.3,1.2,c.players[i].color));},timeout(){c.highest();}};
};

games['Bob-omb Combo']=(c)=>{
 c.limit=110;positions(c);let turn=0,phase='aim',start=0,bombs=[],bursts=[],cursor={x:0,z:0},landing=null,chainAt=0,serial=0;
 function reset(){bombs=Array.from({length:80},(_,i)=>({i,x:c.rand(-7.8,7.8),z:c.rand(-4.5,4.5),vx:c.rand(-.8,.8),vz:c.rand(-.6,.6),dead:false}));bursts=[];cursor={x:0,z:0};landing=null;phase='aim';start=c.time;}
 function explode(x,z){bursts.push({id:serial++%150,x,z,start:c.time});chainAt=c.time;}
 reset();return {update(dt){for(const b of bombs)if(!b.dead){b.x+=b.vx*dt;b.z+=b.vz*dt;if(Math.abs(b.x)>7.8)b.vx*=-1;if(Math.abs(b.z)>4.5)b.vz*=-1;}let target={x:0,z:0,n:-1};for(const b of bombs){const n=bombs.filter(q=>!q.dead&&dist(b,q)<2).length;if(n>target.n)target={...b,n};}for(const p of c.players){const u=c.input(p,p.i===turn?{...steer(cursor,target.x,target.z),a:phase==='aim'&&c.time-start>2&&dist(cursor,target)<.4}:{});if(p.i!==turn)continue;if(phase==='aim'){cursor.x=clamp(cursor.x+u.x*dt*5,-8,8);cursor.z=clamp(cursor.z+u.z*dt*5,-4.5,4.5);if(u.ap||c.time-start>=10){landing={...cursor,at:c.time};phase='flight';}}}if(phase==='flight'&&c.time-landing.at>.6){phase='chain';explode(landing.x,landing.z);}if(phase==='chain'){const active=bursts.filter(b=>c.time-b.start<.7);for(const b of bombs)if(!b.dead&&active.some(e=>dist(b,e)<1.6*Math.min(1,(c.time-e.start)*5))){b.dead=true;c.points(c.players[turn]);explode(b.x,b.z);}if(c.time-chainAt>1){phase='result';start=c.time;}}if(phase==='result'&&c.time-start>1){turn++;if(turn>=4)c.highest('한 번의 투척으로 만든 연쇄 폭발');else reset();}c.hint(`${Math.min(turn+1,4)}P 차례 · 방향키 조준, A 한 번 투척. 가까이 모인 폭탄에 연쇄 반응을 만드세요!`);},render(){c.arena({color:'#5e7280'});bombs.forEach(b=>{if(!b.dead){ball(c,'bomb'+b.i,b.x,b.z,'#424c5c',.44,.34);box(c,'fuse'+b.i,b.x,b.z,'#f0c161',.06,.06,.62,.18);}});bursts.forEach(b=>{const age=c.time-b.start;if(age<.7)c.draw('blast'+b.id,'sphere',{x:b.x,y:.45,z:b.z,sx:3.2*Math.min(1,age*5),sy:.8,sz:3.2*Math.min(1,age*5),color:'#f6bb67',opacity:Math.max(0,1-age/.7)});});if(phase==='aim')c.draw('aim','ring',{x:cursor.x,y:.3,z:cursor.z,rx:Math.PI/2,sx:1.5,sy:1.5,sz:1.5,color:c.players[turn]?.color||'#fff'});if(phase==='flight')ball(c,'throw',landing.x,landing.z,'#e8879d',.65,4*Math.sin((c.time-landing.at)/.6*Math.PI)+.3);},timeout(){c.highest();}};
};

games['Flash Forward']=(c)=>{
 c.limit=10;c.bounds={x:7,z:4.5};positions(c);c.players.forEach(p=>{p.fightCadence=c.rand(.4,.7);p.jumpCadence=c.rand(.65,1.15);});
 return {update(){for(const p of c.players){const foe=nearest(p,c.players.filter(q=>q!==p));const u=c.input(p,{...steer(p,0,0),a:dist(p,{x:0,z:0})<2&&pulse(c,p,p.jumpCadence),b:dist(p,foe)<1.4&&pulse(c,p,p.fightCadence)});if(u.ap&&p.y>.25){p.pound=true;p.vy=-12;}const before=p.y;combat(c,p,u,c.players);p.x=clamp(p.x,-7,7);p.z=clamp(p.z,-4.5,4.5);if(before>0&&p.y===0&&p.pound){p.pound=false;for(const q of c.players)if(q!==p&&dist(p,q)<1.2)q.stun=c.time+1;}const r=Math.hypot(p.x,p.z);p.score=r<2.05?Math.max(1,Math.round(10-r*4)):0;}c.hint('10초 뒤 찰칵! 중앙 원판을 차지하세요. A 점프·공중 A 찍기, B 밀기.');},render(){c.arena({color:'#b1cabd'});c.draw('photo-stage','cylinder',{x:0,y:-.04,z:0,sx:4.1,sy:.2,sz:4.1,color:'#f6dd9b'});c.draw('center-mark','ring',{x:0,y:.07,z:0,rx:Math.PI/2,sx:1,sy:1,sz:1,color:'#ee9bae'});box(c,'camera',0,-5,'#485a69',1.8,.8,1.6,1);ball(c,'lens',0,-4.5,'#203d52',.7,1.6);label(c,'shutter',`${Math.max(0,10-c.time).toFixed(1)}  찰칵!`,0,-5,3,5);},timeout(){scored(c,'사진 중앙 자리를 차지했습니다.');}};
};

export const notes={
 'Freeze Frame':'3D 장면 위의 사진틀을 방향 입력으로 조절합니다. 일반 1점·금색 3점과 단 한 장 촬영 규칙을 유지했습니다.',
 'Snow Whirled':'원작 A/B/Y/X를 A/B/C/D로 재배치했습니다. 순서를 맞힐 때마다 90도 회전하며 한 명씩 도전합니다. 활공 길이는 브라우저판에 맞게 조정했습니다. MP6 9,720도/슈퍼스타즈 9,990도 상한이며 톱100의 원작 상한은 확인되지 않아 9,720도로 정했습니다.',
 'Trap Ease Artist':'10초 한 번 포획, 일반 1점·금색 3점입니다. 동물 이동과 우리 배치는 새로 제작했습니다.',
 'Picture This':'넘기는 그림책의 꽃 성장 장면을 새로 그렸습니다. 같은 장면을 찾아 3점 선취하는 규칙을 유지했습니다.',
 'Target Tag':'방향 입력을 공중 조향으로 사용합니다. 점수 과녁과 0점 초기화 과녁을 유지했으며 비행 코스는 새로 제작했습니다.',
 'Shake It Up':'Wii 흔들기를 동작 A의 빠른 눌렀다 떼기로 바꾸었습니다. 흔들기 제한시간은 5초입니다.',
 'Sugar Rush':'포인터로 토핑을 집는 동작을 방향 입력과 A의 집기/놓기로 바꾸었습니다. 샘플 케이크 2개를 재현하는 협동 경기입니다.',
 'Goomba Spotting':'새우가 굼바를, 파란 생물이 방해 대상을 대신합니다. 더하기만 가능한 집계와 가장 가까운 답 판정을 유지했습니다.',
 'Shy Guy Shuffle':'도넛 개수 확인→덮개→위치 섞기→선택을 3회 진행합니다. 이동 패턴과 배치는 새로 제작했습니다.',
 'Bob-omb Combo':'80개의 움직이는 폭탄에 단 한 번 투척하는 연쇄 반응 경기입니다. 역전 모드 대신 일반 최다 폭발 규칙을 사용합니다.',
 'Flash Forward':'10초 촬영, 중앙 발판의 위치 점수, 밀기와 찍기를 구현했습니다. 촬영 배경과 발판 모양은 새로 제작했습니다.'
};

export const supportedTitles={
 'Smashdance':['mp6'],'Odd Card Out':['mp6'],'Freeze Frame':['mp6'],
 'Catch You Letter':['mp6','top-100','superstars'],'Snow Whirled':['mp6','top-100','superstars'],
 'Trap Ease Artist':['mp6','top-100','superstars'],'Mowtown':['mp6'],'Note to Self':['mp6'],'Same Is Lame':['mp6'],
 "Monty's Revenge":['mp7','top-100','superstars'],'The Final Countdown':['mp7','top-100','superstars'],
 'Take Me Ohm':['mp7'],'Cointagious':['mp7'],'Picture This':['mp7'],'Target Tag':['mp7'],
 'Mario Matrix':['mp8'],'Shake It Up':['mp8'],'Sugar Rush':['mp8'],
 'Goomba Spotting':['mp9','superstars'],'Shy Guy Shuffle':['mp10'],'Bob-omb Combo':['mp10'],
 'Flash Forward':['mp10','top-100','superstars']
};
