import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2, TEAM=[[0,1],[2,3]], SIDE=[[0],[1,2,3]], PAL=['#f493af','#6faed4','#eac259','#76bd9d'];
const text=(c,id,t,x=0,z=-5,y=2,sx=8,color='#24434d')=>c.draw(id,'text',{text:String(t),x,y,z,sx,sy:.7,color});
const box=(c,id,x,z,color,sx=1,sz=1,y=.1,sy=.2)=>c.draw(id,'box',{x,y,z,sx,sy,sz,color});
const ball=(c,id,x,z,color,s=.5,y=.4)=>c.draw(id,'sphere',{x,y,z,sx:s,sy:s,sz:s,color});
const ring=(c,id,x,z,color,s=1,y=.1)=>c.draw(id,'ring',{x,y,z,sx:s,sy:s,sz:s,rx:Math.PI/2,color});
const near=(p,items)=>items.reduce((a,b)=>!a||dist(p,b)<dist(p,a)?b:a,null);
const tap=(c,p,rate=.35)=>((c.time+(p.phase||0))%rate)<rate*.4;
function init(c,limit=60){c.limit=limit;c.players.forEach((p,i)=>{p.x=(i-1.5)*3;p.z=3;p.phase=c.rand(0,1);p.cadence=c.rand(.23,.4);});}
function scores(c,values,sides=TEAM){sides.forEach((ids,t)=>ids.forEach(i=>c.players[i].score=values[t]));}
function finish(c,values,reason,sides=TEAM){values=values.map(v=>Math.round(v*100)/100);scores(c,values,sides);c.complete(values[0]===values[1]?[]:sides[values[0]>values[1]?0:1],reason);}
function separate(players,r=.72){for(let i=0;i<players.length;i++)for(let j=i+1;j<players.length;j++){const a=players[i],b=players[j],d=dist(a,b);if(d<r){const dx=d?(b.x-a.x)/d:1,dz=d?(b.z-a.z)/d:0,k=(r-d)/2;a.x-=dx*k;a.z-=dz*k;b.x+=dx*k;b.z+=dz*k;}}}
function cursor(c,id,p,color=p.color){ring(c,id,p.x,p.z,color,.9,.2);}
function segment(c,id,a,b,color='#f8ecd4',width=.08,y=.35){const d=dist(a,b);c.draw(id,'box',{x:(a.x+b.x)/2,y,z:(a.z+b.z)/2,sx:d,sy:width,sz:width,ry:-Math.atan2(b.z-a.z,b.x-a.x),color});}
export const games={};

games['Candy Shakedown']=(c)=>{
 init(c,Infinity);const states=c.players.map(p=>({open:false,tilt:0,candy:Array.from({length:18},(_,i)=>({x:(i%3-1)*.36,y:.7+Math.floor(i/3)*.26,vx:0,vy:0,out:false}))}));
 return {update(dt){for(const p of c.players){const s=states[p.i],u=c.input(p,{x:Math.sin(c.time*5+p.phase)*.7,a:(c.time+p.phase)%1.7<.65&&tap(c,p,p.cadence)});s.tilt=clamp(s.tilt+u.x*dt*2,-.8,.8);s.tilt*=Math.exp(-dt*.6);if(u.ap){if(!s.open)s.open=true;else for(const q of s.candy)if(!q.out){q.vy+=c.rand(2.1,3.2);q.vx+=c.rand(-1.4,1.4);}}for(const q of s.candy){if(q.out)continue;q.vx+=(Math.sin(s.tilt)*8-q.vx*.6)*dt;q.vy-=7*dt;q.x+=q.vx*dt;q.y+=q.vy*dt;if(Math.abs(q.x)>.61){q.x=clamp(q.x,-.61,.61);q.vx*=-.45;}if(q.y>2.45){q.y=2.45;q.vy=-Math.abs(q.vy)*.3;}if(q.y<.12){if(s.open&&Math.abs(q.x)<.24){q.out=true;c.points(p);}else{q.y=.12;q.vy=Math.abs(q.vy)*.2;q.vx-=q.x*dt*6;}}}const left=s.candy.filter(q=>!q.out);for(let i=0;i<left.length;i++)for(let j=i+1;j<left.length;j++){const a=left[i],b=left[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>0&&d<.22){const k=(.22-d)/2;a.x-=dx/d*k;a.y-=dy/d*k;b.x+=dx/d*k;b.y+=dy/d*k;}}}const done=c.players.filter(p=>p.score===18);if(done.length)c.complete(done.map(p=>p.i),'병 안의 사탕을 모두 쏟았습니다.');c.hint('A: 뚜껑 열기, 이후 A 반복: 흔들기 · ←/→: 병 기울이기. 작은 입구로 사탕을 모두 빼세요.');},render(){c.arena({color:'#d8c6ac'});states.forEach((s,i)=>{const x=c.players[i].x;for(const side of [-1,1])box(c,`jar${i}${side}`,x+side*.76,0,'#accbd1',.12,.65,1.4,2.8);box(c,'top'+i,x,0,'#accbd1',1.6,.65,2.8,.12);for(const side of [-1,1])box(c,`neck${i}${side}`,x+side*.52,0,'#accbd1',.53,.65,.1,.14);if(!s.open)box(c,'lid'+i,x,0,PAL[i],.6,.65,0,.15);s.candy.forEach((q,j)=>{if(!q.out)ball(c,`sweet${i}-${j}`,x+q.x,0,PAL[j%4],.22,.2+q.y);});text(c,'count'+i,`${18-c.players[i].score}개`,x,-1,3.4,2);});},timeout(){c.complete([],'아직 병에 사탕이 남았습니다.');}};
};

games["Croozin' for a Broozin'"]=(c)=>{
 init(c,Infinity);c.view={size:22,eye:[0,19,18],target:[0,0,-2]};const forks=Array.from({length:70},(_,i)=>({at:12+i*13,blocked:c.pick([-1,1]),pipe:c.rand()<.6}));let camera=0,back=-7;c.players.forEach(p=>{p.progress=0;p.x=c.pick([-1,1])*2;p.branch=Math.sign(p.x);p.throttle=c.rand(.93,1);});
 return {update(dt){back+=dt*(3.9+c.time*.035);for(const p of c.players){const f=forks.find(f=>f.at+8>p.progress),ahead=f&&f.at+6-p.progress,visible=ahead<5,blocked=f&&p.branch===f.blocked&&visible;let target=p.branch*2;if(blocked){p.branch=-f.blocked;if(p.progress>f.at-.5)p.detour=true;}if(p.detour&&p.progress<f.at-.55)p.detour=false;if(f&&p.progress>f.at+8)p.branch=c.pick([-1,1]);target=p.branch*2;const u=c.input(p,{x:clamp((target-p.x)*2,-1,1),z:p.detour?1:-p.throttle});if(!p.alive)continue;p.x=clamp(p.x+u.x*dt*4,-4.2,4.2);let speed=-u.z*5.3;if(f&&p.progress>=f.at&&p.progress<=f.at+7&&Math.abs(p.x)<.4)p.x=p.x<0?-.4:.4;if(f&&Math.sign(p.x)===f.blocked&&Math.abs(p.progress-(f.at+6))<.5&&speed>0){speed=0;if(p.i>=c.humans)p.branch=-f.blocked;}if(f&&p.progress>f.at+5&&p.progress<f.at+7&&Math.abs(p.x)<.8&&Math.sign(p.x)!==f.blocked)speed=5.3;p.progress+=speed*dt;if(f&&f.pipe&&p.progress>f.at+2&&p.progress<f.at+5&&Math.sign(p.x)===f.blocked&&c.time%2<.5&&Math.abs(p.x)>3.45)c.eliminate(p);if(p.progress<back+.7)c.eliminate(p);p.score=Math.max(0,Math.floor(p.progress));p.pose='run';}camera=Math.max(camera,Math.max(...c.players.filter(p=>p.alive).map(p=>p.progress),camera));c.players.forEach(p=>p.z=3-(p.progress-camera));c.lastStanding();c.hint('↑로 달리기 · ←/→ 갈림길 선택. 앞이 보이면 막힌 길을 피하고 배관의 추격자를 조심하세요!');},render(){c.arena({width:10,depth:28,color:'#827e8d'});for(const side of [-1,1])box(c,'wall'+side,side*5,-3,'#596775',.6,28,1.2,2.4);forks.forEach((f,i)=>{const z=3-(f.at-camera);if(z>16||z< -18)return;box(c,'divider'+i,0,z-3.5,'#656c78',.5,7,.7,1.4);if(f.at+6-camera<5)box(c,'block'+i,f.blocked*2.7,z-6,'#a58c71',3.7,.8,.8,1.6);else{box(c,'fog'+i,0,z-6,'#a7adb3',8.6,2.5,1.8,.7);text(c,'hidden'+i,'?',0,z-6,2.7,2);}if(f.pipe&&f.at+3.5-camera<4)c.draw('pipe'+i,'cylinder',{x:f.blocked*4.1,y:.8,z:z-3.5,sx:1.2,sy:1.6,sz:1.2,color:'#78997b'});});for(let i=0;i<5;i++)box(c,'chaser'+i,(i-2)*1.7,3-(back-camera),'#c999a7',1.1,1,1,2);},timeout(){c.survivors('추격을 피해 살아남았습니다.');}};
};

games['Smash and Crab']=(c)=>{
 init(c,30);const crab={x:0,z:-2},hammers=[{at:-10,x:0},{at:-10,x:0}];c.players[0].x=0;c.players[0].z=2;
 return {update(dt){const solo=c.players[0],danger=hammers.filter(h=>c.time-h.at<.7);const safe=Array.from({length:27},(_,i)=>i*.5-6.5).map(x=>({x,value:danger.length?Math.min(...danger.map(h=>Math.abs(h.x-x)))-Math.abs(x-solo.x)*.2:Math.abs(x-crab.x)-Math.abs(x-solo.x)*.6})).sort((a,b)=>b.value-a.value)[0];const us=c.input(solo,{x:Math.sign(safe.x-solo.x)});solo.x=clamp(solo.x+us.x*dt*4.5,-6.5,6.5);const driver=c.players[2],ud=c.input(driver,{x:clamp((solo.x-crab.x)*1.2,-1,1)});crab.x=clamp(crab.x+ud.x*dt*3.6,-5.2,5.2);for(const [j,i] of [1,3].entries()){const p=c.players[i],h=hammers[j],hx=crab.x+(j?1.5:-1.5),u=c.input(p,{a:c.time>1+p.phase&&Math.abs(hx-solo.x)<1.3&&c.time-h.at>1.25});if(u.ap&&c.time-h.at>1.2){h.at=c.time;h.x=hx;}const age=c.time-h.at;if(age>=.55&&age<.55+dt&&Math.abs(h.x-solo.x)<1.12)c.complete([1,2,3],'협동 망치로 피하는 선수를 맞혔습니다.');}c.players.slice(1).forEach((p,j)=>{p.x=crab.x+(j-1)*1.3;p.z=-2;p.y=.9;});c.hint('1P ←/→ 회피 · 2P A 왼쪽 망치 · 3P ←/→ 게 이동 · 4P A 오른쪽 망치. 30초 생존!');},render(){c.arena({width:15,depth:9,color:'#cbbfa2'});box(c,'pier',0,2,'#ad916f',15,2.6,.1,.2);c.draw('crab','sphere',{x:crab.x,y:.65,z:crab.z,sx:4,sy:1.2,sz:2.8,color:'#eb8a91'});for(const side of [-1,1])for(let k=0;k<3;k++)segment(c,`leg${side}-${k}`,{x:crab.x+side*1.3,z:crab.z+(k-1)*.6},{x:crab.x+side*2.8,z:crab.z+(k-1)*1.2},'#cf7686',.3,.4);c.players.slice(1).forEach(p=>text(c,'role'+p.i,p.i===1?'왼쪽 망치':p.i===2?'이동':'오른쪽 망치',p.x,p.z,3,2.2,p.color));hammers.forEach((h,j)=>{const age=c.time-h.at,x=age<.9?h.x:crab.x+(j?1.5:-1.5);box(c,'arm'+j,x,.1,'#866950',.2,3,1.2,.25);box(c,'hammer'+j,x,2,'#bf6877',1.7,1.5,age>.55&&age<.85?.5:2.7,1);if(age<.55)ring(c,'warning'+j,x,2,'#efbd64',2.2,.25);});},timeout(){c.complete([0],'두 망치를 30초 동안 피했습니다.');}};
};

games['Off the Chain']=(c)=>{
 init(c,30);c.bounds={x:7,z:4.5};const chomp={x:0,z:0,angle:0,state:'aim',until:1.3};c.players[0].y=1.5;c.players.slice(1).forEach((p,i)=>{p.x=(i-1)*5;p.z=3;});
 return {update(dt){const solo=c.players[0],target=near(chomp,c.players.slice(1).filter(p=>p.alive)),u=c.input(solo,target?toward(chomp,target.x,target.z):{});if(Math.hypot(u.x,u.z)>.1){const a=Math.atan2(u.z,u.x),d=Math.atan2(Math.sin(a-chomp.angle),Math.cos(a-chomp.angle));chomp.angle+=clamp(d,-dt*(chomp.state==='aim'?6:.28),dt*(chomp.state==='aim'?6:.28));}if(chomp.state==='aim'&&c.time>=chomp.until){chomp.state='charge';chomp.until=c.time+1.1;}else if(chomp.state==='charge'){chomp.x+=Math.cos(chomp.angle)*dt*9;chomp.z+=Math.sin(chomp.angle)*dt*9;if(Math.abs(chomp.x)>7||Math.abs(chomp.z)>4.5||c.time>=chomp.until){chomp.x=clamp(chomp.x,-7,7);chomp.z=clamp(chomp.z,-4.5,4.5);chomp.state='aim';chomp.until=c.time+1.15;}}for(const p of c.players.slice(1)){let dx=p.x-chomp.x,dz=p.z-chomp.z;if(chomp.state==='aim'){const nx=-Math.sin(chomp.angle),nz=Math.cos(chomp.angle),sgn=dx*nx+dz*nz>0?1:-1;dx=nx*sgn;dz=nz*sgn;}const v=c.input(p,{x:dx+Math.sin(c.time+p.phase)*.25,z:dz+Math.cos(c.time+p.phase)*.25});c.move(p,v,4.4);if(p.alive&&dist(p,chomp)<1.1)c.eliminate(p);}solo.x=chomp.x;solo.z=chomp.z;solo.rotation=-chomp.angle;if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'돌진으로 세 선수를 모두 잡았습니다.');c.hint('1P 방향키: 대기 중 조준, 돌진 중 작은 보정 · 2~4P 이동 회피. 한 명만 남아도 팀 승리!');},render(){c.arena({width:17,depth:12,color:'#b7ba99'});ball(c,'chomp',chomp.x,chomp.z,'#455d70',2.1,1);const a={x:chomp.x,z:chomp.z},b={x:a.x+Math.cos(chomp.angle)*3,z:a.z+Math.sin(chomp.angle)*3};if(chomp.state==='aim')segment(c,'aim',a,b,'#edbe58',.12,.12);},timeout(){c.complete([1,2,3],'팀원 중 한 명 이상이 돌진을 피했습니다.');}};
};

games['Dust Buddies']=(c)=>{
 init(c,30);c.bounds={x:7.8,z:4.8};const dust=Array.from({length:240},(_,i)=>({x:(i%24-11.5)*.64+c.rand(-.15,.15),z:(Math.floor(i/24)-4.5)*.85+c.rand(-.15,.15),gone:false}));const hub={x:3,z:0},sum=[0,0];c.players[0].x=-5;c.players[0].z=0;c.players.slice(1).forEach((p,i)=>{p.x=3+Math.cos(i*TAU/3)*1.3;p.z=Math.sin(i*TAU/3)*1.3;});
 return {update(dt){const inputs=c.players.map(p=>{let candidates=dust.filter(d=>!d.gone);if(p.i>0)candidates=candidates.filter(d=>dist(hub,d)<3.5);const target=near(p,candidates)||near(p,dust.filter(d=>!d.gone));return c.input(p,target?toward(p,target.x,target.z):{});});c.players.forEach(p=>c.move(p,inputs[p.i],p.i===0?4:4.5));const avg={x:c.players.slice(1).reduce((s,p)=>s+p.x,0)/3,z:c.players.slice(1).reduce((s,p)=>s+p.z,0)/3};hub.x+=(avg.x-hub.x)*Math.min(1,dt*3);hub.z+=(avg.z-hub.z)*Math.min(1,dt*3);for(const p of c.players.slice(1)){const d=dist(p,hub);if(d>2.4){p.x=hub.x+(p.x-hub.x)/d*2.4;p.z=hub.z+(p.z-hub.z)/d*2.4;}}for(const d of dust)if(!d.gone){const claim=c.players.filter(p=>dist(p,d)<(p.i===0?.87:.4));if(claim.length){const p=c.pick(claim);d.gone=true;sum[p.i===0?0:1]++;}}scores(c,sum,SIDE);if(dust.every(d=>d.gone))finish(c,sum,'모아들인 먼지의 양',SIDE);c.hint('이동하면 자동 청소. 1P는 큰 흡입구, 2~4P는 짧은 호스로 연결되어 함께 이동해야 합니다.');},render(){c.arena({color:'#c8b394'});dust.forEach((d,i)=>{if(!d.gone)ball(c,'dust'+i,d.x,d.z,'#877d74',.21,.12);});ball(c,'vacuum',hub.x,hub.z,'#6a99a4',1,.6);c.players.forEach(p=>{box(c,'nozzle'+p.i,p.x,p.z-.35,p.color,p.i===0?1.75:.75,.4,.12,.22);if(p.i>0)segment(c,'hose'+p.i,p,hub,'#5c6970',.12,.35);});text(c,'dustscores',`${sum[0]}   :   ${sum[1]}`,0,-6,2,5);},timeout(){finish(c,sum,'모아들인 먼지의 양',SIDE);}};
};

games['Sign, Steal, Deliver']=(c)=>{
 init(c,60);c.bounds={x:8,z:4};const packs=[],sum=[0,0],trucks=[{x:-7.4,z:3},{x:7.4,z:3}];const floor=z=>z< -1.5?2:z<1.5?1:0;let next=0,serial=0;c.players[0].x=-4;c.players[0].y=3;c.players.forEach(p=>p.cargo=[]);
 return {update(dt){if(c.time>=next){for(let j=0;j<2;j++)packs.push({id:serial++,x:c.rand(-4.8,4.8),z:c.pick([-3,0,3]),holder:null,delivered:false});next=c.time+.9;}for(const p of c.shuffle(c.players)){let target;if(p.cargo.length>=(p.i===0?1:2))target=trucks[p.i===0?0:1];else if(p.i===0){const loose=near(p,packs.filter(q=>!q.delivered&&q.holder!==0));target=loose?(loose.holder!==null?c.players[loose.holder]:loose):trucks[0];}else target=near(p,packs.filter(q=>!q.delivered&&q.holder===null))||trucks[1];let waypoint=target;if(p.i>0&&target&&floor(target.z)!==floor(p.z)){const stair=p.x>0?5.9:-5.9;waypoint=Math.abs(p.x-stair)>.3?{x:stair,z:p.z}:{x:stair,z:target.z};}const u=c.input(p,{...(waypoint?toward(p,waypoint.x,waypoint.z):{}),a:target&&dist(p,target)<.75&&tap(c,p,.4)});const oldZ=p.z;c.move(p,u,p.i===0?6.5:4.8);if(p.i>0&&Math.abs(p.x)<5.3&&floor(oldZ)!==floor(p.z))p.z=oldZ;if(p.i>0)p.y=Math.abs(p.x)>5.3?clamp((3-p.z)/3,0,2):floor(p.z);if(p.i===0){p.y=3;if(u.ap){if(dist(p,trucks[0])<1.2&&p.cargo.length){sum[0]+=p.cargo.length;p.cargo.forEach(q=>q.delivered=true);p.cargo=[];}else if(p.cargo.length<1){const q=near(p,packs.filter(q=>!q.delivered&&q.holder!==0));if(q&&dist(p,q.holder===null?q:c.players[q.holder])<1){if(q.holder!==null)c.players[q.holder].cargo=c.players[q.holder].cargo.filter(a=>a!==q);q.holder=0;p.cargo.push(q);}}}}else{if(dist(p,trucks[1])<1&&p.cargo.length){sum[1]+=p.cargo.length;p.cargo.forEach(q=>q.delivered=true);p.cargo=[];}for(const q of packs)if(p.cargo.length<2&&!q.delivered&&q.holder===null&&floor(q.z)===floor(p.z)&&dist(p,q)<.55){q.holder=p.i;p.cargo.push(q);}}p.cargo.forEach(q=>{q.x=p.x;q.z=p.z;});}separate(c.players.slice(1));scores(c,sum,SIDE);c.hint('1P 드론: 이동, A로 집기·빼앗기·왼쪽 트럭 배달 · 2~4P: 걸어서 최대 2개 자동 수거, 계단을 이용해 오른쪽 트럭 배달.');},render(){c.arena({color:'#bfc5ba'});for(let level=1;level<=2;level++)box(c,'floor'+level,0,3-level*3,'#b5beb5',11,2.9,level-.1,.2);for(const side of [-1,1])for(let k=0;k<12;k++)box(c,`stair${side}-${k}`,side*5.9,3-k*.5,'#c6c8b7',1.2,.52,k/6-.1,.2);for(let i=0;i<6;i++)box(c,'door'+i,(i-2.5)*2,-4.7,'#6e8e96',1.4,.3,1.3,2.6);trucks.forEach((t,i)=>{box(c,'truck'+i,t.x,t.z,i?'#6ab398':'#eb99af',2.2,2.3,.5,1);text(c,'delivery'+i,sum[i],t.x,t.z,2.2,2);});packs.forEach(q=>{if(!q.delivered)box(c,'pack'+q.id,q.x,q.z,'#c89862',.48,.48,q.holder===null?floor(q.z)+.25:1+c.players[q.holder].y+c.players[q.holder].cargo.indexOf(q)*.4,.45);});const p=c.players[0];box(c,'drone',p.x,p.z,'#edb861',1.5,.7,3.2,.25);},timeout(){finish(c,sum,'트럭으로 배달한 상자 수',SIDE);}};
};

games['Dart Gallery']=(c)=>{
 init(c,30);c.bounds={x:5.7,z:3.7};const solo=c.players[0];solo.x=0;solo.z=0;solo.hp=3;const aims=c.players.slice(1).map((p,j)=>({x:(j-1)*3,z:0,left:5,next:c.rand(.8,1.8)})),darts=[];let serial=0;
 return {update(dt){const incoming=darts.filter(d=>!d.landed&&d.at-c.time<.8),target=incoming.length?incoming[0]:null;const safe=target?Array.from({length:35},(_,i)=>({x:(i%7-3)*1.65,z:(Math.floor(i/7)-2)*1.6})).map(q=>({...q,s:Math.min(...incoming.map(d=>dist(q,d)))-dist(q,solo)*.4})).sort((a,b)=>b.s-a.s)[0]:null;const raw=safe?toward(solo,safe.x,safe.z):{x:Math.cos(c.time*1.7),z:Math.sin(c.time*1.2)};const u=c.input(solo,raw),old={x:solo.x,z:solo.z};c.move(solo,u,4.5);for(const d of darts)if(d.landed&&dist(solo,d)<.55){const v=toward(d,solo.x,solo.z);solo.x=d.x+v.x*.55;solo.z=d.z+v.z*.55;if(!v.x&&!v.z){solo.x=old.x;solo.z=old.z;}}c.players.slice(1).forEach((p,j)=>{const a=aims[j],v=c.input(p,{...toward(a,solo.x,solo.z),a:c.time>a.next&&dist(a,solo)<.6});a.x=clamp(a.x+v.x*dt*5,-5.7,5.7);a.z=clamp(a.z+v.z*dt*5,-3.7,3.7);if(v.ap&&a.left>0){a.left--;a.next=c.time+c.rand(1.6,3);darts.push({id:serial++,x:a.x,z:a.z,at:c.time+.65,landed:false,done:false});}p.x=(j-1)*3;p.z=5.2;});for(const d of darts)if(!d.done&&c.time>=d.at){d.done=true;if(dist(solo,d)<.8){solo.hp--;solo.score=3-solo.hp;if(solo.hp<=0)c.complete([1,2,3],'캡슐을 다트로 세 번 맞혔습니다.');}else d.landed=!darts.some(o=>o!==d&&o.landed&&dist(d,o)<.5);}solo.score=3-solo.hp;if(aims.every(a=>a.left===0)&&darts.every(d=>d.done)&&!c.ended)c.complete([0],'15개의 다트를 모두 피했습니다.');c.hint(`1P 이동 회피 (${solo.hp}/3) · 2~4P 방향키 조준, A 발사. 각 5발! 빗나간 다트는 장애물이 됩니다.`);},render(){c.arena({width:13,depth:9,color:'#a2b7bc'});ring(c,'capsule',solo.x,solo.z,'#e8f0e0',1.5,.2);aims.forEach((a,j)=>{cursor(c,'aim'+j,a,c.players[j+1].color);text(c,'ammo'+j,`${a.left}발`,(j-1)*4,5.5,2,2);});darts.forEach(d=>{if(d.landed)c.draw('dart'+d.id,'cone',{x:d.x,y:.65,z:d.z,sx:.35,sy:1.3,sz:.35,color:'#edbd65'});else if(!d.done){ring(c,'target'+d.id,d.x,d.z,'#e28782',1.2,.25);ball(c,'flying'+d.id,d.x,d.z,'#e4b959',.3,Math.max(.5,(d.at-c.time)*9));}});},timeout(){c.complete([0],'캡슐을 30초 동안 지켰습니다.');}};
};

games['Block and Load']=(c)=>{
 init(c,Infinity);c.view={size:24,eye:[0,15,21],target:[0,2,0]};const towers=[-5,5].map((x,t)=>Array.from({length:30},(_,i)=>({x:x+(i%5-2)*.85,y:.45+Math.floor(i/5)*.8,z:0,hp:1,down:false,t,i})));const curs=c.players.map(p=>({x:p.i===0?-5:5,z:0,y:2,ready:0})),shots=[];let serial=0;
 return {update(dt){for(const p of c.players){const t=p.i===0?0:1,blocks=towers[t].filter(b=>!b.down),a=curs[p.i],target=blocks.sort((b,d)=>(b.y-Math.abs(b.x-(t?5:-5))*.1)-(d.y-Math.abs(d.x-(t?5:-5))*.1))[0];const u=c.input(p,target?{x:Math.sign(target.x-a.x),z:Math.sign(a.y-target.y),a:Math.hypot(target.x-a.x,target.y-a.y)<.7&&c.time>=a.ready&&tap(c,p,p.cadence)}:{});a.x=clamp(a.x+u.x*dt*4,t?2.4:-7.6,t?7.6:-2.4);a.y=clamp(a.y-u.z*dt*3,.3,5.3);if(u.ap&&c.time>=a.ready){a.ready=c.time+(t===0?1.7:.3);shots.push({id:serial++,x:a.x,y:a.y,z:5,t,at:c.time+.45,big:t===0});}p.x=p.i===0?-5:3+(p.i-1)*2;p.z=6;}for(const s of shots)if(!s.done){s.z=5*Math.max(0,(s.at-c.time)/.45);if(c.time>=s.at){s.done=true;const radius=s.big?1.3:.45;for(const b of towers[s.t])if(!b.down&&Math.hypot(b.x-s.x,b.y-s.y)<radius)b.down=true;for(let col=0;col<5;col++){let support=true;for(let row=0;row<6;row++){const b=towers[s.t][row*5+col];if(b.down)support=false;else if(!support)b.down=true;}}}}const count=towers.map(bs=>bs.filter(b=>b.down).length);scores(c,count,SIDE);const done=count.map((n,i)=>n===30?i:-1).filter(i=>i>=0);if(done.length)c.complete(done.length===2?[]:SIDE[done[0]],'상대보다 먼저 블록 탑을 전부 무너뜨렸습니다.');c.hint('방향키 조준 · A 포격. 1P 큰 포탄·긴 냉각 / 2~4P 작은 포탄·빠른 연사. 아래 지지 블록을 노리세요!');},render(){c.arena({width:19,depth:15,color:'#c3b89b'});towers.flat().forEach(b=>{if(!b.down)box(c,`block${b.t}-${b.i}`,b.x,0,PAL[(b.i+1)%4],.8,.9,b.y,.75);});curs.forEach((a,i)=>{c.draw('aim'+i,'ring',{x:a.x,y:a.y,z:.55,sx:.65,sy:.65,sz:.65,color:c.players[i].color});box(c,'cannon'+i,c.players[i].x,4.6,i?'#648a9b':'#ad7592',i?.65:1.4,2,.8,i?.65:1.2);text(c,'cool'+i,c.time<a.ready?'냉각':'준비',c.players[i].x,6,2,2);});shots.forEach(s=>{if(!s.done)ball(c,'shot'+s.id,s.x,s.z,'#455365',s.big?1:.3,s.y);});},timeout(){c.complete([],'블록 탑이 아직 남았습니다.');}};
};

games['Drop Shot']=(c)=>{
 init(c,30);c.bounds={x:6,z:3.4};const aim={x:0,z:0},bombs=[];let serve=.8,serial=0,ready=false;const solo=c.players[0];solo.x=0;solo.z=5.8;c.players.slice(1).forEach((p,j)=>{p.x=(j-1)*3;p.z=0;});
 return {update(dt){if(c.time>=serve&&!ready){ready=true;serve=c.time+1.5;}const target=near(aim,c.players.slice(1).filter(p=>p.alive)),u=c.input(solo,target?{...toward(aim,target.x,target.z),a:ready&&dist(aim,target)<.7}:{});aim.x=clamp(aim.x+u.x*dt*5,-6,6);aim.z=clamp(aim.z+u.z*dt*5,-3.4,3.4);if(u.ap&&ready){bombs.push({id:serial++,x:aim.x,z:aim.z,at:c.time+.75,done:false});ready=false;solo.pose='attack';}for(const p of c.players.slice(1)){const threat=near(p,bombs.filter(b=>!b.done));const v=c.input(p,threat?{x:p.x-threat.x,z:p.z-threat.z}:{x:Math.sin(c.time+p.phase)*.5,z:Math.cos(c.time+p.phase)*.5});c.move(p,v,4.3);}for(const b of bombs)if(!b.done&&c.time>=b.at){b.done=true;b.burst=c.time;for(const p of c.players.slice(1))if(p.alive&&dist(p,b)<1.25)c.eliminate(p);}if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'라켓으로 세 선수를 모두 맞혔습니다.');c.hint('1P 방향키: 조준 · A: 공급된 폭탄 스매시. 2~4P 방향키: 울타리 회피. 한 명 생존이면 팀 승리!');},render(){c.arena({width:14,depth:9,color:'#9fb6b4'});for(let i=-6;i<=6;i++)box(c,'fencex'+i,i,0,'#8c9ca0',.04,8,.02,.04);for(let i=-4;i<=4;i++)box(c,'fencez'+i,0,i,'#8c9ca0',13,.04,.02,.04);cursor(c,'aim',aim,'#edac62');if(ready)ball(c,'served',solo.x,solo.z-.6,'#454e61',.6,2.2);bombs.forEach(b=>{if(!b.done){ball(c,'bomb'+b.id,b.x,b.z,'#495063',.55,Math.max(.4,(b.at-c.time)*7));ring(c,'warning'+b.id,b.x,b.z,'#eeac5e',2.5,.2);}else if(c.time-b.burst<.3)ball(c,'blast'+b.id,b.x,b.z,'#eeb869',2.5,.5);});},timeout(){c.complete([1,2,3],'폭탄 스매시를 견뎠습니다.');}};
};

games['Bopping Spree']=(c)=>{
 init(c,Infinity);const centers=[-4.4,4.4],sum=[0,0],targets=centers.map((x,t)=>Array.from({length:8},(_,i)=>({x:x+Math.cos(i*TAU/8)*2.1,z:Math.sin(i*TAU/8)*2.1,lit:false,until:0,i,t})));let next=0;c.players[0].x=-4.4;c.players[0].z=0;c.players.slice(1).forEach((p,j)=>{const a=j*TAU/3;p.x=4.4+Math.cos(a)*3.1;p.z=Math.sin(a)*3.1;p.angle=a;});
 return {update(dt){if(c.time>=next){for(const group of targets){const t=c.pick(group);t.lit=true;t.until=c.time+2.2;}next=c.time+c.rand(.45,.85);}targets.flat().forEach(t=>{if(c.time>t.until)t.lit=false;});for(const p of c.shuffle(c.players)){const team=p.i===0?0:1,t=near(p,targets[team].filter(t=>t.lit)),goal=t?{x:centers[team]+(t.x-centers[team])*(team?1.4:.62),z:t.z*(team?1.4:.62)}:null,u=c.input(p,goal?{...toward(p,goal.x,goal.z),a:dist(p,t)<1.05&&tap(c,p,p.cadence)}:{});if(!team){c.move(p,u,4.8,false);const d=Math.hypot(p.x-centers[0],p.z);if(d>1.5){p.x=centers[0]+(p.x-centers[0])/d*1.5;p.z=p.z/d*1.5;}}else{const tangent={x:-Math.sin(p.angle),z:Math.cos(p.angle)},speed=u.x*tangent.x+u.z*tangent.z;p.angle+=speed*dt*2;p.x=centers[1]+Math.cos(p.angle)*3;p.z=Math.sin(p.angle)*3;}if(u.ap){const hit=near(p,targets[team].filter(t=>t.lit));if(hit&&dist(p,hit)<1.1){sum[team]++;hit.lit=false;hit.until=c.time;p.pose='attack';}}}scores(c,sum,SIDE);const done=sum.map((v,i)=>v>=20?i:-1).filter(i=>i>=0);if(done.length)c.complete(done.length===2?[]:SIDE[done[0]],'빛나는 표적 20개를 먼저 쳤습니다.');c.hint('방향키 이동 · A 펀치. 1P 안쪽 / 2~4P 바깥쪽에서 빛나는 8방향 공을 때리세요. 팀 합계 20점 선취!');},render(){c.arena({width:19,depth:10,color:'#adabb5'});centers.forEach((x,t)=>{ring(c,'rail'+t,x,0,'#816984',4.2,.3);text(c,'meter'+t,`${sum[t]}/20`,x,-4,2,3);});targets.flat().forEach(t=>ball(c,`target${t.t}-${t.i}`,t.x,t.z,t.lit?'#fff188':'#8b93a0',.65,.8));},timeout(){c.complete([],'20점에 도달한 팀이 없습니다.');}};
};

games['Drop Quiz']=(c)=>{
 init(c,110);let round=0,phase='movie',start=0,until=0,actors=[],questions=[],selected=0,options=[];const fruits=['딸기','바나나','사과'];const pads=[{x:-4,z:1},{x:0,z:1},{x:4,z:1}];
 function next(){round++;phase='movie';start=c.time;until=c.time+7;selected=0;actors=Array.from({length:7+round*3},(_,i)=>({at:i*.35,fruit:c.int(0,2),kind:c.int(0,1),x:0,z:0}));const f=c.int(0,2),k=c.int(0,1);questions=[{text:`${fruits[f]}를 든 동물은 몇 마리?`,answer:actors.filter(a=>a.fruit===f).length},{text:`${k?'날개새':'모자새'}는 몇 마리?`,answer:actors.filter(a=>a.kind===k).length},{text:`${fruits[f]}를 든 ${k?'날개새':'모자새'}는 몇 마리?`,answer:actors.filter(a=>a.fruit===f&&a.kind===k).length}];c.players.slice(1).forEach(p=>{p.memory=questions.map(q=>Math.max(0,q.answer+(c.rand()<.78?0:c.pick([-1,1]))));p.choice=-1;p.x=(p.i-2)*3;p.z=3;});}next();
 function ask(){phase='answer';start=c.time;until=c.time+10;const a=questions[selected].answer;options=c.shuffle([a,a+1,Math.max(0,a-1)===a?a+2:Math.max(0,a-1)]);c.players.slice(1).forEach(p=>p.answerTarget=options.indexOf(p.memory[selected])>=0?options.indexOf(p.memory[selected]):c.int(0,2));}
 return {update(dt){const solo=c.players[0],u=c.input(solo,{x:phase==='select'?Math.sign(2-selected):0,a:phase==='select'&&c.time-start>2});if(phase==='select'){if(Math.abs(u.x)>.5&&c.time>(solo.nav||0)){selected=clamp(selected+Math.sign(u.x),0,2);solo.nav=c.time+.25;}if(u.ap||c.time>=until)ask();}for(const p of c.players.slice(1)){const target=pads[p.answerTarget??0],v=c.input(p,phase==='answer'&&p.alive?toward(p,target.x,target.z):{});if(phase==='answer')c.move(p,v,4);if(phase==='answer'&&p.alive)p.choice=pads.findIndex(a=>dist(p,a)<1.25);}if(phase==='movie'&&c.time>=until){phase='select';start=c.time;until=c.time+10;}if(phase==='answer'&&c.time>=until){for(const p of c.players.slice(1))if(p.alive&&(p.choice<0||options[p.choice]!==questions[selected].answer))c.eliminate(p);phase='result';until=c.time+1.2;if(c.players.slice(1).every(p=>!p.alive))c.complete([0],'세 명 모두 퀴즈 함정에 빠졌습니다.');}if(phase==='result'&&c.time>=until){if(round===3)c.complete([1,2,3],'팀원 한 명 이상이 세 문제를 통과했습니다.');else next();}c.hint(`${round}/3 · ${phase==='movie'?'지나가는 동물과 과일을 기억하세요.':phase==='select'?'1P ←/→ 문제 선택, A 확정.':phase==='answer'?'2~4P 이동해서 정답 발판 위에 서세요.':'정답 확인'}`);},render(){c.arena({color:'#859cac'});box(c,'screen',0,-3,'#d1ddc4',14,3,.1,.2);if(phase==='movie')actors.forEach((a,i)=>{const age=c.time-start-a.at;if(age>=0&&age<3.7){const x=-7+age*4,z=-3+(a.kind?-.55:.55);ball(c,'actor'+i,x,z,a.kind?'#9fc9dd':'#edb09f',.65,.55);if(a.kind)box(c,'wing'+i,x,z,'#eeeace',1.2,.2,.8,.12);else c.draw('hat'+i,'cone',{x,y:1,z,sx:.85,sy:.45,sz:.85,color:'#e8d79c'});ball(c,'fruit'+i,x+.45,z,PAL[a.fruit],.33,.6);}});if(phase==='select')questions.forEach((q,i)=>text(c,'q'+i,`${i===selected?'▶ ':''}${q.text}`,0,-4+i,1.3,12,i===selected?'#ad5b78':'#3c5a62'));if(phase==='answer'||phase==='result'){text(c,'question',questions[selected].text,0,-3,2,12);pads.forEach((p,i)=>{box(c,'pad'+i,p.x,p.z,'#d8c79f',2.6,2.6,.05,.15);text(c,'option'+i,options[i],p.x,p.z,.35,1.8);});}c.players[0].x=-7;c.players[0].z=-4;},timeout(){c.complete(c.players.slice(1).some(p=>p.alive)?[1,2,3]:[0],'퀴즈 종료');}};
};

games['What a Racket']=(c)=>{
 init(c,30);c.bounds={x:7,z:4};const bombs=[],sum=[0,0];let next=.3,serial=0;c.players[0].x=-4;c.players[0].z=0;c.players.slice(1).forEach((p,j)=>{p.x=4;p.z=(j-1)*2.5;});
 return {update(dt){if(c.time>=next){const count=c.int(2,4);for(let i=0;i<count;i++)bombs.push({id:serial++,x:c.pick([-1,1])*c.rand(1.5,6.3),z:c.rand(-3.3,3.3),y:c.rand(3.5,5),vx:0,state:'fall',dead:false});next=c.time+c.rand(.8,1.3);}for(const b of bombs)if(!b.dead){if(b.state==='fly'){b.x+=b.vx*dt;b.y=1.3+Math.sin(clamp((c.time-b.launch)/.8,0,1)*Math.PI)*2;if(c.time-b.launch>=.8){b.state='fall';b.vx=0;b.y=1.2;}}else b.y-=dt*1.55;if(b.y<=.12){sum[b.x<0?1:0]++;b.dead=true;}}for(const p of c.shuffle(c.players)){const side=p.i===0?-1:1,candidates=bombs.filter(b=>!b.dead&&b.state==='fall'&&Math.sign(b.x)===side&&b.y<2),target=near(p,candidates),u=c.input(p,target?{...toward(p,target.x,target.z),a:dist(p,target)<(p.i===0?2.1:1)&&tap(c,p,p.cadence)}:{});c.move(p,u,p.i===0?4.4:4.7);p.x=clamp(p.x,side<0?-7:.7,side<0?-.7:7);if(u.ap&&c.time>(p.swing||0)){p.swing=c.time+.28;p.pose='attack';const hit=candidates.filter(b=>dist(p,b)<(p.i===0?2.3:1.05)).sort((a,b)=>a.y-b.y).slice(0,p.i===0?4:1);for(const b of hit){b.state='fly';b.launch=c.time;b.vx=-side*9;b.y=1.3;}}}separate(c.players.slice(1));scores(c,sum,SIDE);c.hint('이동 · A: 라켓. 1P 큰 라켓은 최대 4개, 2~4P 작은 라켓은 한 번에 1개! 상대 코트 바닥에 떨어뜨리면 득점.');},render(){c.arena({width:17,depth:11,color:'#b5c7aa'});box(c,'net',0,0,'#dae4d2',.12,9,.6,1.2);bombs.forEach(b=>{if(!b.dead){ball(c,'bomb'+b.id,b.x,b.z,'#48566a',.45,b.y);if(b.state==='fall'){c.draw('chute'+b.id,'cone',{x:b.x,y:b.y+.75,z:b.z,sx:.9,sy:.3,sz:.9,color:'#ead49c'});segment(c,'cord'+b.id,{x:b.x-.2,z:b.z},{x:b.x+.2,z:b.z},'#f6eddb',.03,b.y+.35);}}});c.players.forEach(p=>ring(c,'racket'+p.i,p.x,p.z,p.color,p.i===0?3.6:1.3,1));text(c,'score',`${sum[0]} : ${sum[1]}`,0,-5.5,2,6);},timeout(){finish(c,sum,'상대 코트에 떨어뜨린 폭탄 수',SIDE);}};
};

games['Tall Order']=(c)=>{
 init(c,30);const sum=[0,0],bowls=[{x:-4.5,z:1},{x:4.5,z:1}],flakes=[];let serial=0;c.players.forEach((p,i)=>{p.x=(i<2?-4.5:4.5)+(i%2?1.5:-1.5);p.z=-1;p.ice=10;p.angle=null;p.shave=0;p.rate=c.rand(4.5,7.5);p.catchError=c.rand(-.15,.15);});
 return {update(dt){bowls.forEach((b,t)=>b.x=(t?4.5:-4.5)+Math.sin(c.time*1.4)*2.1);for(const p of c.players){const t=p.i<2?0:1,catchSoon=Math.abs(bowls[t].x-p.x+p.catchError)<1.1,a=c.time*p.rate+p.phase,u=c.input(p,catchSoon&&p.ice>0?{x:Math.cos(a),z:Math.sin(a)}:{});if(Math.hypot(u.x,u.z)>.4){const angle=Math.atan2(u.z,u.x);if(p.angle!==null){const delta=Math.abs(Math.atan2(Math.sin(angle-p.angle),Math.cos(angle-p.angle)));if(delta<2){const shaved=Math.min(p.ice,delta*.15);p.ice-=shaved;p.shave+=shaved;if(p.shave>.08){flakes.push({id:serial++,x:p.x,z:1,y:3.8,amount:p.shave,t});p.shave=0;}}}p.angle=angle;}else p.angle=null;}for(const f of flakes)if(!f.done){f.y-=dt*4;if(f.y<.5){f.done=true;if(Math.abs(f.x-bowls[f.t].x)<.85)sum[f.t]+=f.amount;}}scores(c,sum.map(v=>Math.round(v*100)/100));if(c.players.every(p=>p.ice<=0)&&flakes.every(f=>f.done))finish(c,sum,'받아낸 빙수 조각의 총 높이');c.hint('방향 입력을 원으로 회전해 얼음을 가세요. 각자 얼음은 한정되어 있습니다. 그릇이 아래로 올 때만 갈아 담으세요!');},render(){c.arena({color:'#d9e5df'});c.players.forEach(p=>{box(c,'ice'+p.i,p.x,-1,'#a6d3df',1.2,1.1,2.6,Math.max(.08,p.ice*.15));box(c,'shaver'+p.i,p.x,0,'#7e929e',1.6,.8,1.7,.7);});bowls.forEach((b,t)=>{c.draw('bowl'+t,'cylinder',{x:b.x,y:.3,z:b.z,sx:1.9,sy:.6,sz:1.5,color:PAL[t*2]});c.draw('snow'+t,'cone',{x:b.x,y:.6+sum[t]*.08,z:b.z,sx:1.3,sy:Math.max(.05,sum[t]*.16),sz:1.3,color:'#f6f3df'});text(c,'height'+t,`${sum[t].toFixed(2)} m`,t?4.5:-4.5,-4,3.4,4);});flakes.forEach(f=>{if(!f.done)ball(c,'flake'+f.id,f.x,f.z,'#f9f5df',.15,f.y);});},timeout(){finish(c,sum,'받아낸 빙수 조각의 총 높이');}};
};

games['Making Faces']=(c)=>{
 init(c,32);const centers=[-4.6,4.6],target=[{x:-.65,z:-.55},{x:.65,z:-.55},{x:0,z:.55}],states=[0,1].map(t=>({x:c.rand(-1.6,1.6),z:c.rand(-1.6,1.6),placed:[],error:0}));let feature=0,start=0;c.players.forEach(p=>p.aimError=c.rand(-.2,.2));
 return {update(dt){const inputs=c.players.map(p=>{const s=states[p.i<2?0:1],g=target[feature]||target[2];return c.input(p,p.i%2?{z:clamp((g.z+p.aimError-s.z)*4,-1,1)}:{x:clamp((g.x+p.aimError-s.x)*4,-1,1)});});states.forEach((s,t)=>{s.x=clamp(s.x+inputs[t*2].x*dt*1.8,-1.8,1.8);s.z=clamp(s.z+inputs[t*2+1].z*dt*1.8,-1.8,1.8);});c.players.forEach((p,i)=>{const t=i<2?0:1;p.x=centers[t]+(i%2?3:inputs[i].x*1.2);p.z=i%2?inputs[i].z*1.2:3;});if(c.time-start>=10){states.forEach(s=>{s.placed.push({x:s.x,z:s.z});s.error+=Math.hypot(s.x-target[feature].x,s.z-target[feature].z);s.x=c.rand(-1.6,1.6);s.z=c.rand(-1.6,1.6);});feature++;start=c.time;if(feature>=3)finish(c,states.map(s=>Math.round(clamp(100-s.error/3*32,0,100))),'얼굴 조각 세 개의 배치 정확도');}c.hint(`${Math.min(feature+1,3)}/3 조각 · 1·3P ←/→ 가로 이동 / 2·4P ↑/↓ 세로 이동. 10초 뒤 자동으로 떨어집니다!`);},render(){c.arena({width:21,depth:11,color:'#c0b7bb'});centers.forEach((x,t)=>{c.draw('face'+t,'cylinder',{x,y:.12,z:0,sx:4.6,sy:.24,sz:4.6,color:'#f3b5bd'});target.forEach((g,j)=>{ring(c,`guide${t}-${j}`,x+g.x,g.z,'#b69a80',j<2?.65:1.1,.35);});states[t].placed.forEach((g,j)=>{if(j<2)ball(c,`eye${t}-${j}`,x+g.x,g.z,'#4d5964',.55,.4);else box(c,'mouth'+t,x+g.x,g.z,'#b5687a',1.1,.35,.4,.1);});if(feature<3){const s=states[t];ring(c,'shadow'+t,x+s.x,s.z,'#80767a',feature<2?.65:1.1,.32);if(feature<2)ball(c,'falling'+t,x+s.x,s.z,'#4d5964',.55,2);else box(c,'falling'+t,x+s.x,s.z,'#b5687a',1.1,.35,2,.1);}box(c,'horizontal'+t,x,3,'#90b8a8',3.6,.8,.05,.1);box(c,'vertical'+t,x+3,0,'#9dadcb',.8,3.6,.05,.1);});},timeout(){finish(c,states.map(s=>Math.round(clamp(100-s.error/3*32,0,100))),'얼굴 조각의 배치 정확도');}};
};

games['Dash and Dine']=(c)=>{
 init(c,60);c.bounds={x:7,z:4};const sum=[0,0],supplies=[{x:-5,z:-3,type:0},{x:0,z:-3,type:1},{x:5,z:-3,type:2}],chefs=[{x:-6,z:3},{x:6,z:3}],orders=[[],[]],waiters=[{x:0,z:0},{x:0,z:1}],food=['베이컨','양상추','토마토'];
 function order(t){orders[t]=Array.from({length:c.int(2,3)},()=>c.int(0,2));}order(0);order(1);c.players.forEach(p=>p.food=null);
 return {update(dt){waiters.forEach((w,i)=>{w.x=Math.sin(c.time*(i?.9:.6)+i)*6;w.z=i?Math.cos(c.time*.65)*2:0;});for(const p of c.shuffle(c.players)){const t=p.i<2?0:1,mate=c.players[t*2+(p.i%2?0:1)];let wanted=orders[t].find(type=>type!==mate.food)??orders[t][0];const target=p.food===null?supplies[wanted]:orders[t].includes(p.food)?chefs[t]:supplies[p.food],u=c.input(p,{...toward(p,target.x,target.z),a:dist(p,target)<.85&&tap(c,p,.35)}),old={x:p.x,z:p.z};c.move(p,u,4.8);if(waiters.some(w=>dist(p,w)<.85)){p.x=old.x;p.z=old.z;if(p.i>=c.humans)p.z=clamp(p.z+(p.i%2?1:-1)*dt*3,-4,4);}if(u.ap){if(p.food===null){const s=near(p,supplies);if(dist(p,s)<1)p.food=s.type;}else if(dist(p,chefs[t])<1&&orders[t].includes(p.food)){orders[t].splice(orders[t].indexOf(p.food),1);p.food=null;if(!orders[t].length){sum[t]++;order(t);}}else if(dist(p,supplies[p.food])<1)p.food=null;}}separate(c.players);scores(c,sum);c.hint('이동 · A: 재료 집기/돌려놓기/전달. 1·2P 왼쪽, 3·4P 오른쪽 주문을 완성하세요. 접시를 나르는 직원을 피하세요!');},render(){c.arena({color:'#cdbda1'});supplies.forEach(s=>{box(c,'table'+s.type,s.x,s.z,'#a98b66',2.5,1.4,.4,.8);ball(c,'ingredient'+s.type,s.x,s.z,PAL[s.type],.7,1);text(c,'food'+s.type,food[s.type],s.x,s.z,2,3);});chefs.forEach((q,t)=>{box(c,'counter'+t,q.x,q.z,'#d4a283',2.4,1.4,.4,.8);text(c,'order'+t,orders[t].map(i=>food[i]).join(' + '),q.x,q.z,2.3,6);});waiters.forEach((w,i)=>{ball(c,'waiter'+i,w.x,w.z,'#d4d8b7',.8,.6);box(c,'plates'+i,w.x,w.z,'#f1ecdc',1.3,.5,1.2,.15);});c.players.forEach(p=>{if(p.food!==null)ball(c,'held'+p.i,p.x,p.z-.35,PAL[p.food],.5,1.3);});},timeout(){finish(c,sum,'완성한 주문 수');}};
};

games['Fruit Forecast']=(c)=>{
 init(c,30);const fruits=[],sum=[0,0];let next=0,serial=0;const levels=[3.8,1,3.8,1],lane=[-4.3,-4.3,4.3,4.3];c.players.forEach((p,i)=>{p.x=lane[i];p.z=0;p.y=levels[i];p.catchError=c.rand(-.3,.3);p.react=c.rand(.25,.7);});
 return {update(dt){if(c.time>=next){const x=c.rand(-2.4,2.4),spike=c.rand()<.2,value=c.pick([1,1,2,3]);for(let t=0;t<2;t++)fruits.push({id:serial++,x:(t?4.3:-4.3)+x,z:0,y:7,spike,value,t,top:false,done:false});next=c.time+c.rand(.3,.55);}for(const p of c.players){const t=p.i<2?0:1,up=p.i%2===0,target=near(p,fruits.filter(f=>!f.done&&!f.spike&&f.t===t&&f.y>levels[p.i]&&(!up||!f.top)&&f.y-levels[p.i]>p.react));const danger=fruits.find(f=>!f.done&&f.spike&&f.t===t&&Math.abs(f.y-levels[p.i])<1.2&&Math.abs(f.x-p.x)<1);const u=c.input(p,{x:danger?Math.sign(p.x-danger.x)||1:target?clamp((target.x+p.catchError-p.x)*3,-1,1):0});if(c.time>(p.stun||0))p.x=clamp(p.x+u.x*dt*4.7,lane[p.i]-2.7,lane[p.i]+2.7);p.y=levels[p.i];p.z=up?-.2:.25;}for(const f of fruits)if(!f.done){const old=f.y;f.y-=dt*3.1;for(const i of TEAM[f.t]){const p=c.players[i],height=levels[i]+.5;if(old>=height&&f.y<height){if(i%2===0)f.top=true;if(Math.abs(f.x-p.x)<.8&&c.time>(p.stun||0)){if(f.spike)p.stun=c.time+1.8;else sum[f.t]+=f.value;f.done=true;break;}}}if(f.y<.1)f.done=true;}scores(c,sum);c.hint('←/→ 바구니 이동. 1·3P 위층, 2·4P 아래층에서 위가 놓친 과일 받기! 가시공은 잠시 움직이지 못하게 합니다.');},render(){c.arena({color:'#b6c9a4'});for(let t=0;t<2;t++)for(const [j,y] of [1,3.8].entries())box(c,`branch${t}-${j}`,t?4.3:-4.3,0,'#99794f',6.5,.65,y-.15,.3);fruits.forEach(f=>{if(!f.done){ball(c,'fruit'+f.id,f.x,0,f.spike?'#4b5e69':PAL[(f.value-1)%4],f.spike?.65:.48,f.y);if(f.spike)c.draw('spike'+f.id,'cone',{x:f.x,y:f.y+.4,z:0,sx:.3,sy:.6,sz:.3,color:'#75818a'});}});c.players.forEach(p=>{box(c,'basket'+p.i,p.x,p.z+.3,p.color,1.3,.6,p.y+.5,.35);if(c.time<(p.stun||0))text(c,'stun'+p.i,'빙글',p.x,p.z,p.y+2,2);});},timeout(){finish(c,sum,'위아래 바구니로 받은 과일 점수');}};
};

games['Nut Cases']=(c)=>{
 init(c,60);c.bounds={x:7.4,z:4.5};const crates=Array.from({length:28},(_,i)=>({id:i,x:(i%7-3)*1.7,z:(Math.floor(i/7)-1.5)*1.6,homeX:(i%7-3)*1.7,homeZ:(Math.floor(i/7)-1.5)*1.6,n:c.int(1,5),holder:null,stored:false}));const bases=[{x:-7,z:0},{x:7,z:0}],collections=[[],[]];c.players.forEach(p=>{p.box=null;p.checked=new Set();p.testAt=0;});
 function totals(){return collections.map(a=>a.reduce((s,b)=>s+b.n,0));}
 return {update(dt){for(const p of c.shuffle(c.players)){const t=p.i<2?0:1;let target;if(p.box){target=p.box.n>=4||c.time>43?bases[t]:{x:p.box.homeX,z:p.box.homeZ};}else target=near(p,crates.filter(q=>!q.stored&&q.holder===null&&!p.checked.has(q.id)))||near(p,crates.filter(q=>!q.stored&&q.holder===null));const u=c.input(p,collections[t].length<5&&target?{...toward(p,target.x,target.z),a:dist(p,target)<.65&&tap(c,p,.45)&&c.time>p.testAt}:{});c.move(p,u,4.2);if(u.ap&&collections[t].length<5){if(p.box){const q=p.box;if(dist(p,bases[t])<1.2){q.stored=true;collections[t].push(q);}else{q.x=p.x;q.z=p.z;}q.holder=null;p.box=null;}else{const q=near(p,crates.filter(q=>!q.stored&&q.holder===null));if(q&&dist(p,q)<.7){q.holder=p.i;p.box=q;p.checked.add(q.id);p.testAt=c.time+.8;}}}if(p.box){p.box.x=p.x;p.box.z=p.z;}}separate(c.players);scores(c,totals());if(collections.every(a=>a.length===5))finish(c,totals(),'다섯 상자 안의 도토리 합계');c.hint('이동 · A 상자 들기/놓기. 든 상자의 떨림 막대가 클수록 도토리가 많아요. 각 팀 창고에 최대 5상자만!');},render(){c.arena({color:'#c2b691'});crates.forEach(q=>{if(!q.stored)box(c,'crate'+q.id,q.x,q.z,'#b58c61',.7,.7,q.holder===null?.4:1.1,.7);});bases.forEach((b,t)=>{box(c,'storage'+t,b.x,b.z,PAL[t*2],1.5,6,.1,.2);text(c,'stored'+t,`${collections[t].length}/5`,b.x,-4,2,2);if(c.ended)text(c,'acorns'+t,totals()[t],b.x,3,2,2);});c.players.forEach(p=>{if(p.box){const q=p.box,n=q.n,wiggle=Math.sin(c.time*35)*n*.03;box(c,'rumble'+p.i,p.x+wiggle,p.z+.8,'#eaca63',n*.24,.2,2,.17);text(c,'feel'+p.i,'떨림',p.x,p.z+.8,2.5,2);}});},timeout(){finish(c,totals(),'창고에 넣은 상자의 도토리 합계');}};
};

// A taut rope records contacts as moving endpoints sweep a segment around a pin.
// Reversing the turn around that pin releases the contact, so mistakes can be unwound.
function ropeStep(rope,ends,pins){
 const cross=(a,b,d)=>(b.x-a.x)*(d.z-b.z)-(b.z-a.z)*(d.x-b.x);
 for(let k=rope.length-1;k>=0;k--){const h=rope[k],a=k?pins[rope[k-1].i]:ends[0],b=pins[h.i],d=k+1<rope.length?pins[rope[k+1].i]:ends[1];if(cross(a,b,d)*h.turn<-.04)rope.splice(k,1);}
 for(let pass=0;pass<3;pass++){
  let inserted=false;const path=[ends[0],...rope.map(h=>pins[h.i]),ends[1]];
  for(let j=0;j<path.length-1&&!inserted;j++){const a=path[j],b=path[j+1],vx=b.x-a.x,vz=b.z-a.z,len=vx*vx+vz*vz;if(len<.05)continue;for(const pin of pins){if(rope.some(h=>h.i===pin.i))continue;const q=((pin.x-a.x)*vx+(pin.z-a.z)*vz)/len;if(q<.04||q>.96)continue;const dd=Math.hypot(pin.x-(a.x+q*vx),pin.z-(a.z+q*vz));if(dd<.21){const turn=Math.sign(cross(a,pin,b))||1;rope.splice(j,0,{i:pin.i,turn});inserted=true;break;}}}if(!inserted)break;
 }
}
games['Tow the Line']=(c)=>{
 init(c,165);c.view={size:24,eye:[0,23,16],target:[0,0,-1]};const pins=Array.from({length:9},(_,i)=>({x:(i%3-1)*1.8,z:(Math.floor(i/3)-1)*1.8,i})),centers=[-5,5],sum=[0,0];let round=0,until=0,pause=0,targetRope=[],targetEnds=[],paths=[],ropes=[[],[]],progress=[];
 const patterns=[[[[-2.8,-2.8]],[[2.8,-2.8]]],[[[-2.8,2.8]],[[2.8,-2.8],[-2.8,-2.8]]],[[[-2.8,-2.8],[2.8,-2.8]],[[2.8,2.8]]],[[[-2.8,-2.8],[.8,-2.8]],[[2.8,-2.8],[2.8,.5]]],[[[-2.8,.1]],[[2.8,-2.8],[-.6,-2.8]]]];
 function next(){round++;until=c.time+30;pause=0;ropes=[[],[]];progress=[0,0,0,0];paths=c.pick(patterns).map(route=>route.map(([x,z])=>({x,z})));const ends=[{x:-2.8,z:2.8},{x:2.8,z:2.8}],indices=[0,0],sample=[];
  for(let step=0;step<1200;step++){for(let i=0;i<2;i++){const goal=paths[i][indices[i]];if(goal){const d=dist(ends[i],goal);if(d<.06){ends[i]={...goal};indices[i]++;}else{const u=toward(ends[i],goal.x,goal.z);ends[i].x+=u.x*.055;ends[i].z+=u.z*.055;}}}ropeStep(sample,ends,pins);if(indices.every((v,i)=>v>=paths[i].length))break;}
  targetRope=sample.map(h=>({...h}));targetEnds=ends.map(p=>({...p}));c.players.forEach((p,i)=>{p.x=centers[i<2?0:1]+(i%2?2.8:-2.8);p.z=2.8;p.botSpeed=c.rand(3,3.8);});
 }next();
 const local=p=>({x:p.x-centers[p.i<2?0:1],z:p.z});
 function shapeMatches(t){const current=ropes[t].map(h=>h.i),wanted=targetRope.map(h=>h.i);return current.join(',')===wanted.join(',')&&TEAM[t].every((i,j)=>dist(local(c.players[i]),targetEnds[j])<.4);}
 return {update(dt){for(const p of c.players){const t=p.i<2?0:1,j=p.i%2,point=local(p),goal=paths[j][progress[p.i]]||targetEnds[j];if(dist(point,goal)<.12&&progress[p.i]<paths[j].length)progress[p.i]++;const u=c.input(p,pause?{}:toward(point,goal.x,goal.z));if(!pause){p.x=clamp(p.x+u.x*dt*(p.i>=c.humans?p.botSpeed:3.5),centers[t]-3.3,centers[t]+3.3);p.z=clamp(p.z+u.z*dt*(p.i>=c.humans?p.botSpeed:3.5),-3.3,3.3);for(const pin of pins){const q={x:pin.x+centers[t],z:pin.z},d=dist(p,q);if(d<.35){const v=toward(q,p.x,p.z);p.x=q.x+v.x*.35;p.z=q.z+v.z*.35;}}}}if(!pause){for(let t=0;t<2;t++)ropeStep(ropes[t],TEAM[t].map(i=>local(c.players[i])),pins);const won=[0,1].filter(shapeMatches);if(won.length){if(won.length===1)sum[won[0]]++;scores(c,sum);pause=c.time+1.2;}else if(c.time>=until)pause=c.time+1.2;}else if(c.time>=pause){if(Math.max(...sum)>=3||round>=5)finish(c,sum,'로프 모양 맞추기 점수');else next();}c.hint(`${round}/5 · 방향키로 로프 양 끝을 함께 움직이세요. 핀을 돌아 샘플 모양을 재현! 반대로 돌아가면 풀립니다. 3점 선취·라운드당 30초.`);},render(){c.arena({width:20,depth:12,color:'#c3b0ac'});for(let t=0;t<2;t++){box(c,'cushion'+t,centers[t],0,t?'#b7cbc5':'#d5bac4',7.5,7.5,.05,.2);pins.forEach(p=>{c.draw(`pin${t}-${p.i}`,'cylinder',{x:centers[t]+p.x,y:.4,z:p.z,sx:.16,sy:.8,sz:.16,color:'#bfbfae'});ball(c,`head${t}-${p.i}`,centers[t]+p.x,p.z,'#eddb99',.32,.85);});const route=[local(c.players[t*2]),...ropes[t].map(h=>pins[h.i]),local(c.players[t*2+1])].map(q=>({x:q.x+centers[t],z:q.z}));for(let i=0;i<route.length-1;i++)segment(c,`rope${t}-${i}`,route[i],route[i+1],'#fff4cf',.12,.35);text(c,'points'+t,`${sum[t]}점`,centers[t],4.7,2,3);}
 const sc=.55,off={x:0,z:-6.1},sample=[targetEnds[0],...targetRope.map(h=>pins[h.i]),targetEnds[1]].map(q=>({x:q.x*sc,z:q.z*sc+off.z}));pins.forEach(p=>ball(c,'samplepin'+p.i,p.x*sc,p.z*sc+off.z,'#927b78',.14,.22));for(let i=0;i<sample.length-1;i++)segment(c,'sampleline'+i,sample[i],sample[i+1],'#fff7ce',.1,.35);sample.filter((q,i)=>i===0||i===sample.length-1).forEach((q,i)=>ring(c,'sampleend'+i,q.x,q.z,PAL[i],.4,.35));text(c,'samplelabel','이 모양을 만드세요',0,-8.4,1,7);},timeout(){finish(c,sum,'다섯 라운드 로프 점수');}};
};

export const supportedTitles=Object.fromEntries(Object.keys(games).map(name=>[name,['super-mario-party']]));
export const notes={
 'Candy Shakedown':'병 열기와 사탕 전부 쏟기 경주입니다. Joy-Con 기울이기는 방향 입력, 흔들기는 A 반복으로 바꾸었으며 병과 사탕 물리는 새로 제작했습니다.',
 "Croozin' for a Broozin'":'갈림길·막힌 길·배관 추격자와 최후 생존 규칙입니다. 복도 배치와 추격 속도는 새로 제작했습니다.',
 'Smash and Crab':'1P 회피, 2P 왼쪽 망치, 3P 로봇 이동, 4P 오른쪽 망치로 세 역할을 분리했습니다. 망치 한 번 적중 또는 30초 생존 판정입니다.',
 'Off the Chain':'대기 조준 후 자동 직선 돌진과 작은 방향 보정, 30초 안에 세 명 모두 잡기 규칙을 구현했습니다.',
 'Dust Buddies':'혼자 큰 흡입구를 사용하며 세 명은 한 청소기의 짧은 호스를 공유합니다. 먼지량 합계로 승패를 판정합니다.',
 'Sign, Steal, Deliver':'드론의 수동 집기·빼앗기와 도보 자동 수거를 구분했습니다. 드론 1상자, 보행 2상자와 서로 반대편 트럭 배달을 적용했습니다. 건물 배치는 새로 제작했습니다.',
 'Dart Gallery':'각 공격수 5발, 수비수 3회 피격, 빗나간 다트 장애물과 다트 소진 생존 승리를 구현했습니다.',
 'Block and Load':'큰 포탄·긴 냉각과 세 개의 작은 연사 대포를 구분합니다. 블록 지지대 붕괴를 포함한 탑 철거 경주이며 탑 구조는 새로 제작했습니다.',
 'Drop Shot':'공급된 폭탄만 칠 수 있는 공격수와 울타리의 세 회피자로 나뉩니다. 30초 안에 세 명 모두 맞혀야 공격수가 이깁니다.',
 'Bopping Spree':'8방향 공을 안쪽의 한 명과 바깥쪽의 세 명이 각각 때립니다. 빛나는 공만 득점하며 20점 선취입니다.',
 'Drop Quiz':'실제로 재생된 동물·과일 장면에서 세 질문을 만듭니다. 출제자가 고르고 세 답변자는 발판으로 답하는 3라운드 생존 퀴즈입니다.',
 'What a Racket':'혼자 큰 라켓으로 최대 4개, 팀원은 작은 라켓으로 1개씩 폭탄을 넘깁니다. 30초 동안 상대 코트에 떨어뜨린 폭탄을 셉니다.',
 'Tall Order':'각자의 한정된 얼음을 방향 입력의 원운동으로 깎고, 왕복하는 그릇 안에 떨어진 조각만 높이에 더합니다.',
 'Making Faces':'한 명은 가로, 한 명은 세로를 조절하며 조각마다 10초 뒤 자동 낙하합니다. 새로 제작한 플라밍고 얼굴 세 부분의 정확도를 비교합니다.',
 'Dash and Dine':'팀별 복수 재료 주문, 틀린 재료 반환, 직원·플레이어 충돌을 구현했습니다. 주문 하나를 완성해야 1점입니다.',
 'Fruit Forecast':'같은 팀이 위층과 아래층에서 과일을 받으며 위에서 놓친 과일을 아래가 받습니다. 가시공은 일정 시간 이동을 막습니다.',
 'Nut Cases':'Joy-Con 진동 강도를 상자를 들었을 때의 떨림 막대로 표시합니다. 팀마다 5상자만 보관할 수 있고 안의 도토리 합계로 판정합니다.',
 'Tow the Line':'두 끝을 움직이면 로프가 3×3 핀에 걸리고, 반대로 돌아가면 풀립니다. 샘플 모양 먼저 맞추기·라운드당 30초·최대 5라운드·3점 선취이며 핀 접촉 물리는 새로 제작했습니다.'
};
