import {clamp,dist,toward} from '../core.js';
const bright=['#e87896','#62b8d4','#eac251','#7cb28c'];
function heading(q,p){if(Math.hypot(q.x,q.z)>.1){p.dx=q.x;p.dz=q.z;}}
function knock(p,x,z,strength,dt){p.x+=x*strength*dt;p.z+=z*strength*dt;}
function label(c,id,text,x,y,z,color='#25454c',sx=2.3){c.draw(id,'text',{text,x,y,z,sx,sy:sx/4,color});}
function station(c,p,width=18,depth=12){c.bounds={x:width/2-.6,z:depth/2-.6};c.arena({width,depth,color:'#d4c798'});}
function rain(c,kind='popcorn'){
 c.limit=30;let spawn=0,items=[];c.players.forEach(p=>{p.stun=0;p.tier=p.i%2;});
 return {update(dt){spawn-=dt;if(spawn<=0){spawn=.16;items.push({id:c.int(0,1e8),x:c.rand(-7.5,7.5),z:c.rand(-4.5,4.5),y:c.rand(7,10),rock:c.rng()<.22,speed:c.rand(3,4.5)});}for(const p of c.players){p.stun=Math.max(0,p.stun-dt);const targets=items.filter(i=>!i.rock).sort((a,b)=>dist(p,a)-dist(p,b));const target=targets[0]||{x:0,z:0};const danger=items.find(i=>i.rock&&i.y<3&&dist(i,p)<1.5);let bot=toward(p,danger?p.x+(p.x-danger.x)*4:target.x,danger?p.z+(p.z-danger.z)*4:target.z);c.move(p,c.input(p,bot),p.stun?0:5.8);}
  for(const item of items){item.y-=item.speed*dt;if(item.y<.8){const eligible=c.players.filter(p=>dist(p,item)<.95).sort((a,b)=>dist(a,item)-dist(b,item));if(eligible[0]){const p=eligible[0];if(item.rock){p.score=Math.floor(p.score/2);p.stun=1;}else c.points(p,1);}item.remove=true;}}items=items.filter(i=>!i.remove);if(c.time>=30)c.highest('모은 팝콘 수');c.hint('그림자를 보고 팝콘을 받으세요 · 돌에 맞으면 절반을 잃습니다');},render(){c.arena({width:18,depth:12,color:'#e3cbbb'});for(const i of items){c.draw('shadow'+i.id,'cylinder',{x:i.x,y:.01,z:i.z,sx:1,sy:.025,sz:1,color:i.rock?'#7f7772':'#e9b941',opacity:.65});c.draw('rain'+i.id,i.rock?'box':'sphere',{x:i.x,y:i.y,z:i.z,sx:i.rock?.8:.55,sy:i.rock?.8:.7,sz:i.rock?.8:.6,rx:i.y,color:i.rock?'#726f74':'#fff1c1'});}for(const p of c.players)c.draw('bucket'+p.i,'cylinder',{x:p.x,y:1.2,z:p.z+.45,sx:1,sy:.4,sz:1,color:p.color});},timeout(){c.highest();}};
}
function magnets(c){c.limit=30;let serial=12,spawn=.3;const balls=Array.from({length:12},(_,i)=>({i,x:c.rand(-7,7),z:c.rand(-3.5,4.5),y:c.rand(3,8),gold:i%8===0}));c.players.forEach(p=>{p.cargo=[];p.x=(p.i-1.5)*4;p.z=-5;});return{update(dt){spawn-=dt;if(spawn<=0){spawn=.35;balls.push({i:serial++,x:c.rand(-7,7),z:c.rand(-3.5,4.5),y:8,gold:c.rng()<.15});}for(const b of balls)if(b.owner===undefined)b.y=Math.max(.3,b.y-dt*4);for(const p of c.players){let target=p.cargo.length>=3?{x:(p.i-1.5)*4,z:-5}:balls.filter(b=>b.owner===undefined).sort((a,b)=>dist(p,a)-dist(p,b))[0]||{x:(p.i-1.5)*4,z:-5};const q=c.input(p,()=>({...toward(p,target.x,target.z),a:true}));c.move(p,q,6/(1+p.cargo.length*.18));for(const b of balls)if(b.owner===undefined&&dist(p,b)<.9&&((b.y>.4&&b.y<1.8)||q.a&&b.y<=.4)){b.owner=p.i;p.cargo.push(b);}if(p.z<-4.2&&Math.abs(p.x-(p.i-1.5)*4)<1.25){for(const b of p.cargo){c.points(p,b.gold?3:1);b.owner=-1;}p.cargo=[];}
 for(const o of c.players)if(o.i>p.i&&dist(p,o)<1&&p.cargo.length&&o.cargo.length){for(const v of [p,o]){const b=v.cargo.pop();b.owner=undefined;b.y=.3;b.x=clamp(v.x+c.rand(-1.5,1.5),-7,7);b.z=clamp(v.z+c.rand(-1.5,1.5),-3.5,4.5);}p.x-=.25;o.x+=.25;}}
 if(c.time>=30)c.highest('보관함에 넣은 금속 구슬 점수');c.hint('A를 누르며 자석으로 수집 · 자기 색 보관함에 배달 · 금색 3점');},render(){c.arena({width:19,depth:13,color:'#9bc1bf'});for(const p of c.players){c.draw('bin'+p.i,'box',{x:(p.i-1.5)*4,y:.2,z:-5,sx:3,sy:.5,sz:1.8,color:p.color});c.draw('ufo'+p.i,'cylinder',{x:p.x,y:1.2,z:p.z,sx:1.7,sy:.22,sz:1.7,color:p.color});p.y=1;for(let j=0;j<p.cargo.length;j++)c.draw('cargo'+p.i+'_'+j,'sphere',{x:p.x+(j%3-1)*.4,y:.4+Math.floor(j/3)*.3,z:p.z,sx:.36,sy:.36,sz:.36,color:p.cargo[j].gold?'#edc254':'#bbc9d0'});}for(const b of balls)if(b.owner===undefined)c.draw('ball'+b.i,'sphere',{x:b.x,y:b.y,z:b.z,sx:.6,sy:.6,sz:.6,color:b.gold?'#f2c956':'#c6d5d8',metalness:.6});},timeout(){c.highest();}};}
function census(c){c.limit=20;const count=c.int(16,28),people=Array.from({length:count+7},(_,i)=>({x:c.rand(-7,7),z:c.rand(-3,3),decoy:i>=count,phase:c.rand(0,7)}));c.players.forEach(p=>{p.score=0;p.x=(p.i-1.5)*4;p.z=4;});return{update(){for(const p of c.players){const botTarget=count+((p.i+Math.round(c.seed))%3-1),q=c.input(p,()=>({a:p.score<botTarget&&Math.sin(c.time*10+p.i)>0,b:p.score>botTarget&&Math.sin(c.time*10+p.i)>0}));c.move(p,q,4);if(q.ap)p.score=Math.min(99,p.score+1);if(q.bp)p.score=Math.max(0,p.score-1);}c.hint('방향으로 열차 안 이동 · 작은 새를 세세요 · A +1 / B −1');if(c.time>=20){const difference=Math.min(...c.players.map(p=>Math.abs(p.score-count)));c.complete(c.players.filter(p=>Math.abs(p.score-count)===difference).map(p=>p.i),`실제 승객 ${count}명 · 가장 가까운 답`);}},render(){c.arena({width:18,depth:12,color:'#cbb68f'});for(let i=0;i<people.length;i++){const p=people[i],x=p.x+Math.sin(c.time*.8+p.phase)*.5,z=p.z+Math.cos(c.time*.9+p.phase)*.4;c.draw('person'+i,p.decoy?'box':'cone',{x,y:p.decoy?.4:.6,z,sx:.5,sy:p.decoy?.8:1.1,sz:.5,color:p.decoy?'#dbbe83':bright[i%4]});if(!p.decoy)c.draw('head'+i,'sphere',{x,y:1.1,z,sx:.45,sy:.45,sz:.45,color:'#ef97b1'});}for(const p of c.players)label(c,'count'+p.i,String(p.score),p.x,3,p.z,p.color);},timeout(){const diff=Math.min(...c.players.map(p=>Math.abs(p.score-count)));c.complete(c.players.filter(p=>Math.abs(p.score-count)===diff).map(p=>p.i),`실제 ${count}명`);}};}
function pancakes(c){c.limit=Infinity;const cakes=Array.from({length:24},(_,i)=>({i,x:c.rand(-5,5),z:c.rand(-3,3),layer:Math.floor(i/8),star:i%7===0,active:true}));c.players.forEach(p=>{p.x=(p.i-1.5)*4;p.z=4;p.cool=0;p.cursor={x:p.x,z:0};});const exposed=b=>!cakes.some(o=>o.active&&o.layer>b.layer&&dist(b,o)<1.25);return{update(dt){for(const p of c.players){p.cool=Math.max(0,p.cool-dt);const targets=cakes.filter(b=>b.active&&exposed(b)).sort((a,b)=>dist(p.cursor,a)-dist(p.cursor,b)),t=targets[0]||p,q=c.input(p,()=>({...toward(p.cursor,t.x,t.z),a:c.time>.5&&p.cool===0&&dist(p.cursor,t)<1}));p.cursor.x=clamp(p.cursor.x+q.x*6*dt,-6.5,6.5);p.cursor.z=clamp(p.cursor.z+q.z*6*dt,-4,4);if(q.ap&&p.cool===0){p.cool=.6;const b=targets.find(b=>dist(p.cursor,b)<1.05);if(b){b.active=false;c.points(p,b.star?3:1);}}}c.hint('가려지지 않은 팬케이크만 A로 집기 · 별 팬케이크 3점');if(!cakes.some(b=>b.active))c.highest('빈 접시! 팬케이크 점수 합계');},render(){c.arena({width:17,depth:12,color:'#dcc9ae'});c.draw('plate','cylinder',{y:.04,sx:14,sy:.12,sz:9,color:'#fff3d9'});for(const b of cakes)if(b.active){c.draw('cake'+b.i,'cylinder',{x:b.x,y:.2+b.layer*.25,z:b.z,sx:1.7,sy:.2,sz:1.7,color:exposed(b)?'#e9bd76':'#c79765'});if(b.star)label(c,'star'+b.i,'★',b.x,.6+b.layer*.25,b.z,'#fff2c4',.9);}for(const p of c.players){c.draw('cursor'+p.i,'ring',{x:p.cursor.x,y:1.1,z:p.cursor.z,sx:1,sy:1,sz:.3,rx:-Math.PI/2,color:p.color});label(c,'cursorLabel'+p.i,`${p.i+1}P`,p.cursor.x,1.5,p.cursor.z,p.color,.8);}},timeout(){c.highest();}};}
function gridiron(c){c.limit=30;let enemies=[],spawn=0;c.bounds={x:7,z:4.5};c.players.forEach(p=>{p.hits=0;p.score=3;p.grace=0;});return{update(dt){spawn-=dt;if(spawn<0){spawn=Math.max(.3,1-c.time*.018);const horizontal=c.rng()<.5,dir=c.rng()<.5?-1:1;enemies.push({id:c.int(0,1e7),x:horizontal?dir*11:c.pick([-6,-3,0,3,6]),z:horizontal?c.pick([-4,-2,0,2,4]):dir*9,vx:horizontal?-dir*7:0,vz:horizontal?0:-dir*7});}for(const p of c.players){p.grace=Math.max(0,p.grace-dt);const threat=enemies.filter(e=>(e.vx&&Math.abs(e.z-p.z)<1&&Math.abs(e.x-p.x)<4)||(e.vz&&Math.abs(e.x-p.x)<1&&Math.abs(e.z-p.z)<4))[0];const q=c.input(p,()=>threat?{x:threat.vz?(p.x>threat.x?1:-1):0,z:threat.vx?(p.z>threat.z?1:-1):0}:{x:0,z:0});c.move(p,q,6);for(const e of enemies)if(p.alive&&p.grace===0&&dist(p,e)<1){p.hits++;p.grace=1.1;p.score=3-p.hits;if(p.hits>=3)c.eliminate(p);}}for(const e of enemies){e.x+=e.vx*dt;e.z+=e.vz*dt;}enemies=enemies.filter(e=>Math.abs(e.x)<13&&Math.abs(e.z)<11);c.hint('달려오는 수비수를 피하세요 · 세 번 부딪히면 탈락');c.lastStanding();if(c.time>=30)c.survivors();},render(){c.arena({width:18,depth:12,color:'#71a590'});for(let i=-2;i<=2;i++)c.draw('line'+i,'box',{x:i*3,y:.02,z:0,sx:.05,sy:.05,sz:11,color:'#e6e8c9'});for(const e of enemies){c.draw('tackle'+e.id,'box',{x:e.x,y:.7,z:e.z,sx:1,sy:1.4,sz:1,color:'#e9c665'});c.draw('helmet'+e.id,'sphere',{x:e.x,y:1.6,z:e.z,sx:1,sy:.7,sz:1,color:'#315a67'});}},timeout(){c.survivors();}};}
function love(c){c.limit=80;let round=0,phase=0,target=0,answered=new Set();function next(){round++;phase=0;target=c.int(0,3);answered=new Set();}next();const spots=[[0,-3],[3,0],[0,3],[-3,0]];c.players.forEach(p=>{p.x=(p.i-1.5)*3.5;p.z=5;});return{update(dt){phase+=dt;for(const p of c.players){const delay=.4+p.i*.09,q=c.input(p,()=>phase>delay&&!answered.has(p.i)?{x:spots[target][0]/3,z:spots[target][1]/3}:{x:0,z:0});const answer=q.z<-.5?0:q.x>.5?1:q.z>.5?2:q.x<-.5?3:-1;if(answer>=0&&!answered.has(p.i)){answered.add(p.i);if(answer===target)c.points(p,[5,3,2,1][[...answered].filter(i=>c.players[i].correct===round).length]||0);p.correct=answer===target?round:0;p.pose=answer===target?'jump':'hit';}}c.hint(`${round}/10 · 색에 속지 말고 하트를 향해 방향 입력`);if(phase>2.7){if(round>=10)c.highest('정답 속도 순위의 합');else next();}},render(){c.arena({width:18,depth:13,color:'#ddc4d5'});const icons=['♣','♦','♠'];spots.forEach(([x,z],i)=>{c.draw('card'+i,'box',{x,y:.15,z,sx:2.2,sy:.15,sz:2.2,color:bright[(i+round)%4]});label(c,'symbol'+i,i===target?'♥':icons[(i+round)%3],x,1.1,z,'#fcf1df',2);});label(c,'round','LOOK FOR LOVE',0,4,-4,'#6e596b',6);},timeout(){c.highest();}};}
function navigator(c){c.limit=Infinity;c.bounds={x:8,z:5};const peels=Array.from({length:55},(_,i)=>({i,x:c.rand(-7,7),z:c.rand(-4.3,4.3)})).filter(b=>Math.hypot(b.x,b.z)>1.2);c.players.forEach((p,i)=>{const a=i*Math.PI/2;p.x=Math.cos(a)*7;p.z=Math.sin(a)*4.8;p.stun=0;p.grace=0;});return{update(dt){for(const p of c.players){p.stun=Math.max(0,p.stun-dt);p.grace=Math.max(0,p.grace-dt);let t={x:0,z:0};const nearest=peels.filter(b=>dist(b,p)<1.5).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(nearest){t={x:-p.x*.2+(p.z-nearest.z)*3,z:-p.z*.2-(p.x-nearest.x)*3};}const q=c.input(p,()=>toward(p,t.x,t.z));c.move(p,q,p.stun?0:3.8);if(p.grace===0&&peels.some(b=>dist(b,p)<.55)){p.stun=1;p.grace=1.8;p.pose='hit';}if(Math.hypot(p.x,p.z)<.8)c.complete([p.i],'중앙 깃발에 먼저 도착');}c.hint('바나나 껍질 사이를 지나 중앙으로 · 미끄러지면 1초 정지');},render(){c.arena({width:18,depth:12,color:'#aec19a'});for(const b of peels)c.draw('peel'+b.i,'cone',{x:b.x,y:.2,z:b.z,sx:.7,sy:.4,sz:.7,color:'#f2ca57',rz:.35});c.draw('goal','cylinder',{y:.04,sx:1.8,sy:.1,sz:1.8,color:'#e87f8f'});c.draw('flagpole','cylinder',{y:1.7,sx:.08,sy:3.4,sz:.08,color:'#fff0d4'});c.draw('flag','box',{x:.5,y:2.9,sx:1,sy:.6,sz:.05,color:'#e7758f'});},timeout(){c.complete([],'시간 안에 도착한 플레이어가 없습니다');}};}
function sled(c){c.limit=25;c.view={size:19,eye:[3,18,22],target:[0,0,0]};c.players.forEach(p=>{p.x=(p.i-1.5)*4;p.z=5;p.speed=0;p.released=false;p.done=false;p.target=c.rand(-4.5,-3.3);});return{update(dt){for(const p of c.players){const stopping=p.z-p.speed*p.speed/8,q=c.input(p,()=>({a:stopping<p.target}));if(q.ap)p.released=true;if(!p.released)p.speed=Math.min(10,p.speed+3*dt);else p.speed=Math.max(0,p.speed-4*dt);p.z-=p.speed*dt;if(p.z<-5){p.alive=false;p.done=true;p.speed=0;}else if(p.released&&p.speed===0){p.done=true;p.score=10-(p.z+5);}}c.hint('A로 줄 놓기 · 관성을 계산해 절벽 가까이 멈추세요');if(c.players.every(p=>p.done)){const valid=c.players.filter(p=>p.alive);if(!valid.length)c.complete([],'모두 절벽 아래로 떨어졌습니다');else{const best=Math.min(...valid.map(p=>p.z));c.complete(valid.filter(p=>Math.abs(p.z-best)<.03).map(p=>p.i),'절벽 가장 가까이에 정지');}}},render(){c.arena({width:19,depth:12,color:'#cbe5e7'});c.draw('edge','box',{y:.025,z:-5,sx:19,sy:.06,sz:.1,color:'#e87983'});for(const p of c.players){c.draw('sled'+p.i,'box',{x:p.x,y:.12,z:p.z,sx:1.5,sy:.24,sz:2,color:p.color});if(!p.released)c.draw('rope'+p.i,'box',{x:p.x,y:.4,z:p.z-1.5,sx:.06,sy:.05,sz:2,color:'#9c8d63'});label(c,'dist'+p.i,p.released?'RELEASED':'A →',p.x,3,p.z,p.color,2);}},timeout(){const valid=c.players.filter(p=>p.alive);if(!valid.length)c.complete([]);else {const z=Math.min(...valid.map(p=>p.z));c.complete(valid.filter(p=>p.z===z).map(p=>p.i),'가장 가까운 썰매');}}};}
function hammer(c){c.limit=180;const nails=[1.2,2.1,.8,1.7,2.6,1.1,2.3,1.5];c.players.forEach(p=>{p.x=(p.i-1.5)*4;p.z=1;p.nail=0;p.depth=nails[0];p.charge=0;p.cool=0;});return{update(dt){for(const p of c.players){p.cool=Math.max(0,p.cool-dt);p.charge=Math.min(1,p.charge+dt*.85);const q=c.input(p,()=>({a:p.cool===0&&p.charge>Math.min(.9,p.depth/2.9)}));if(q.ap&&p.cool===0){p.depth-=.15+p.charge*2.7;p.charge=0;p.cool=.22;p.pose='hit';if(p.depth<=0){p.nail++;p.score=p.nail;p.depth=nails[p.nail]||0;}}}const done=c.players.filter(p=>p.nail>=nails.length);if(done.length)c.complete(done.map(p=>p.i),'모든 못을 먼저 박았습니다');c.hint('힘을 모았다가 A로 내려치기 · 높은 못은 강한 타격이 필요합니다');},render(){c.arena({width:19,depth:10,color:'#d2b88d'});for(const p of c.players){c.draw('wood'+p.i,'box',{x:p.x,y:.4,z:-1,sx:2.7,sy:.8,sz:3,color:'#b78963'});c.draw('nail'+p.i,'cylinder',{x:p.x,y:1+Math.max(.05,p.depth)/2,z:-1,sx:.25,sy:Math.max(.1,p.depth),sz:.25,color:'#b6c8cb'});c.draw('head'+p.i,'cylinder',{x:p.x,y:1+Math.max(0,p.depth),z:-1,sx:.6,sy:.12,sz:.6,color:'#c9d8da'});c.draw('charge'+p.i,'box',{x:p.x-1.2+p.charge*1.2,y:.1,z:3,sx:Math.max(.01,p.charge*2.4),sy:.15,sz:.45,color:p.color});label(c,'nails'+p.i,`${p.nail}/8`,p.x,4,-1,p.color);}},timeout(){c.complete([],'3분 안에 끝내지 못해 무승부');}};}
function wrestling(c){c.limit=10;let balance=0;c.players.forEach(p=>{p.x=p.i<2?-4:4;p.z=p.i%2?2:-2;});return{update(dt){for(const p of c.players){const q=c.input(p,()=>({a:Math.sin(c.time*(15+p.i*.7)+p.i)>0}));if(q.ap){balance+=(p.i<2?-1:1)*.045;p.score++;}}balance=clamp(balance,-1,1);c.hint('A 연타 · 1P+2P 대 3P+4P · 기계 팔을 자기 쪽 버튼으로');if(Math.abs(balance)>=1)c.complete(balance<0?[0,1]:[2,3],'팔이 바닥 스위치를 눌렀습니다');else if(c.time>=10)c.complete(Math.abs(balance)<.001?[]:balance<0?[0,1]:[2,3],'10초 후 자기 쪽으로 더 기울인 팀');},render(){c.arena({width:16,depth:10,color:'#adc1ba'});c.draw('table','box',{y:.7,sx:5,sy:1.4,sz:4,color:'#6d9898'});c.draw('arm','box',{x:Math.sin(balance)*1.5,y:2.4,z:0,sx:.6,sy:3,sz:.6,rz:-balance*Math.PI/2,color:'#e4be67'});for(const p of c.players)c.draw('button'+p.i,'cylinder',{x:p.x,y:.2,z:p.z-.5,sx:1,sy:.4,sz:1,color:p.color});},timeout(){c.complete(Math.abs(balance)<.001?[]:balance<0?[0,1]:[2,3],'팀 연타 결과');}};}
export const games={'Snack Attack':rain,'Sphere Mongers':magnets,'Senseless Census':census,'Can Take Pancake':pancakes,'Gridiron Gauntlet':gridiron,'Looking for Love':love,'Trip Navigator':navigator,'Sled to the Edge':sled,'Hammer It Home':hammer,'Robo Arm Wrestle':wrestling};
export const notes={
 'Snack Attack':'방향 이동으로 받습니다. 돌은 절반 손실과 기절, 팝콘은 1점입니다. 낙하 배치는 새로 제작했습니다.',
 'Sphere Mongers':'방향 이동, A 자석. 자기 색 상자로 배달합니다. 적재량에 따른 감속과 충돌 시 낙하를 구현했습니다.',
 'Senseless Census':'방향 이동, A로 +1, B로 −1. 승객은 작은 분홍 새, 제외 대상은 상자로 바꿨습니다.',
 'Can Take Pancake':'방향으로 커서 이동, A 집기. 위에 겹친 팬케이크가 있으면 집을 수 없습니다. 별 팬케이크는 3점입니다.',
 'Gridiron Gauntlet':'방향 이동. 세 번 피격 시 탈락하며, 30초 후 생존자 모두 승리합니다.',
 'Looking for Love':'하트 방향으로 입력합니다. 색상은 정답과 무관합니다. 10라운드의 응답 순위로 채점합니다.',
 'Trip Navigator':'방향 이동만 사용합니다. 껍질 배치는 새로 생성되며 미끄러지면 1초간 멈춥니다.',
 'Sled to the Edge':'A 버튼으로 견인줄을 놓습니다. 썰매의 속도·마찰 값은 브라우저판에 맞게 조정했습니다.',
 'Hammer It Home':'A로 망치를 내립니다. 충전 막대가 힘을 보여 줍니다. 원작의 모션 타격을 버튼으로 바꿨습니다.',
 'Robo Arm Wrestle':'A 연타. 1·2P와 3·4P가 팀이며, 두 사람의 입력이 같은 팔에 합산됩니다.'
};
