import {clamp,dist,toward} from '../core.js';
const TAU=Math.PI*2,cream='#f2dfb8',pulse=(t,f=4,o=0)=>(t*f+o)%1<.4;
const label=(c,id,text,x=0,y=4,z=0,sx=7)=>c.draw(id,'text',{x,y,z,sx,sy:.8,text});
function active(c,duel=false){c.activePlayers=duel?[0,1]:[0];c.players.forEach((p,i)=>{if(i>=(duel?2:1)){p.visible=false;p.alive=false;}p.phase=c.rand(0,1);});}
function balloon(c){
 active(c,true);c.limit=120;c.players[0].x=-4;c.players[1].x=4;let turn=0,air=0,held=0,pumping=false,pause=.5,decision=1.5;const burst=c.rand(11,15);c.players.forEach(p=>p.z=1);
 function next(){turn=1-turn;held=0;pumping=false;pause=.5;decision=air<8?c.rand(1.2,2.6):c.rand(.1,1.5);}
 return{update(dt){c.hint(`${turn+1}P 차례 · A 누르고 있어 바람 넣기, 놓으면 교대 · 한 번에 최대3초 · 터뜨리면 패배`);const qs=c.players.slice(0,2).map(p=>c.input(p,()=>({a:p.i===turn&&!pause&&held<decision})));if(pause){pause=Math.max(0,pause-dt);return;}const q=qs[turn];if(q.ap)pumping=true;if(pumping&&q.a){air+=dt;held+=dt;c.players[turn].score=Math.round(held*100)/100;if(air>=burst)c.complete([1-turn],'상대가 풍선을 터뜨렸습니다');else if(held>=3)next();}else if(pumping&&!q.a)next();},render(){c.arena({width:18,depth:12,color:'#b4c7b2'});const scale=1.5+air*.3;c.draw('balloon','sphere',{x:0,y:2.2+scale*.25,z:-2,sx:scale,sy:scale*1.1,sz:scale,color:air>9?'#e1a1a4':'#c4a4c1'});for(let i=0;i<2;i++){c.draw('pump'+i,'cylinder',{x:i?4:-4,y:.5,z:0,sx:1,sy:1,sz:1,color:c.players[i].color});c.draw('handle'+i,'box',{x:i?4:-4,y:1.25+(turn===i&&pumping?Math.sin(c.time*15)*.15:0),z:0,sx:1.5,sy:.12,sz:.25,color:cream});}label(c,'turn',`${turn+1}P ${held.toFixed(1)} / 3초`,0,6,0,6);},timeout(){c.complete([],'풍선이 터지기 전 안전 제한에 도달했습니다');}};
}
function boo(c){
 active(c,true);c.limit=125;c.view={size:24,eye:[0,6,28],target:[0,2,0]};let turn=0,age=0,gap=.6,ghost=-7;const length=60,results=[];c.players.slice(0,2).forEach(p=>{p.d=0;p.speed=0;p.tapAgo=9;p.rate=c.rand(4.5,6);p.visible=p.i===0;p.x=-7;p.z=0;});
 function end(reached){results[turn]={d:c.players[turn].d,time:reached?age:null};if(turn===1){const a=results[0],b=results[1],score=r=>r.time!=null?1000-r.time:r.d;c.complete(Math.abs(score(a)-score(b))<1e-7?[]:score(a)>score(b)?[0]:[1],'탈출 시간, 미탈출 시 문까지 간 거리 비교');}else{c.players[0].visible=false;turn=1;c.players[1].visible=true;age=0;ghost=-7;gap=.7;}}
 return{update(dt){const p=c.players[turn];c.hint(`${turn+1}P 차례 · A 또는 B 반복으로 달리기 / 버튼을 멈추면 뒤를 돌아 유령을 물립니다`);const q=c.players.slice(0,2).map(o=>c.input(o,()=>{const run=o.i===turn&&ghost<p.d-3;return{a:run&&pulse(c.time,o.rate,o.phase),b:false};}))[turn];if(gap){gap=Math.max(0,gap-dt);return;}age+=dt;p.tapAgo+=dt;if(q.ap||q.bp){p.tapAgo=0;p.speed=Math.min(6.5,p.speed+2.6);}const running=p.tapAgo<.24;if(running){p.speed=Math.max(1.5,p.speed-.5*dt);p.d+=p.speed*dt;ghost+=8.1*dt;}else{p.speed=0;ghost=Math.max(p.d-9,ghost-6*dt);}p.x=-7+p.d/length*14;p.score=Math.round(p.d*100)/100;p.rotation=running?0:Math.PI;if(ghost>=p.d-.6)end(false);else if(p.d>=length)end(true);else if(age>=60)end(false);},render(){c.arena({width:22,depth:9,color:'#a1a5b1'});c.draw('door','box',{x:7.7,y:1.7,z:0,sx:.35,sy:3.4,sz:2,color:'#a9baa3'});const x=-7+ghost/length*14;c.draw('ghost','sphere',{x,y:1.5,z:0,sx:2.5,sy:2.7,sz:2.3,color:'#d5d8d6',opacity:.8});label(c,'time',age.toFixed(1)+'초',0,5,0,5);},timeout(){if(!c.ended){if(turn===0){end(false);end(false);}else end(false);}}};
}
function cast(c){
 active(c);c.limit=60;c.view={size:23,eye:[0,7,28],target:[0,0,0]};const wanted=c.int(0,3),colors=['#d899a9','#93afd1','#92bb9a','#d6ac84'],fish=Array.from({length:8},(_,i)=>({i,kind:i%4,x:c.rand(-8,8),y:-1.4-(i%4)*.95,speed:(i%2?1:-1)*c.rand(1.7,2.7)}));let hand={y:1,phase:'ready'};c.players[0].x=0;c.players[0].y=1;c.players[0].z=0;
 return{update(dt){c.hint('A로 집게 내리기 / 주문한 종류 한 마리를 잡으면 성공 · 다른 종류를 건드리면 실패');for(const f of fish){f.x+=f.speed*dt;if(Math.abs(f.x)>9)f.x=-Math.sign(f.x)*9;}const target=fish.filter(f=>f.kind===wanted).sort((a,b)=>Math.abs(a.x)-Math.abs(b.x))[0],travel=(1-target.y)/5,q=c.input(c.players[0],()=>({a:hand.phase==='ready'&&Math.abs(target.x+target.speed*travel)<.6&&!fish.some(f=>f.kind!==wanted&&f.y>target.y&&Math.abs(f.x+f.speed*(1-f.y)/5)<.8)}));if(q.ap&&hand.phase==='ready')hand.phase='down';if(hand.phase==='down'){hand.y-=5*dt;const hit=fish.filter(f=>Math.abs(f.x)<.7&&Math.abs(f.y-hand.y)<.5).sort((a,b)=>Math.abs(a.y-hand.y)-Math.abs(b.y-hand.y))[0];if(hit)c.complete(hit.kind===wanted?[0]:[],hit.kind===wanted?'주문한 물고기를 잡았습니다':'다른 물고기를 잡았습니다');else if(hand.y<-5.5)hand.phase='up';}else if(hand.phase==='up'){hand.y=Math.min(1,hand.y+5*dt);if(hand.y===1)hand.phase='ready';}},render(){c.draw('pond','box',{x:0,y:-2.7,z:-1,sx:21,sy:6.5,sz:.3,color:'#8ebdcd'});fish.forEach(f=>{c.draw('fish'+f.i,f.kind===3?'box':'sphere',{x:f.x,y:f.y,z:0,sx:1.1,sy:.6,sz:.5,color:colors[f.kind]});if(f.kind!==3)c.draw('tail'+f.i,'cone',{x:f.x-Math.sign(f.speed)*.65,y:f.y,z:0,sx:.55,sy:.6,sz:.3,rz:Math.PI/2,color:colors[f.kind]});});c.draw('line','cylinder',{x:0,y:(hand.y+1)/2,z:0,sx:.06,sy:Math.max(.01,1-hand.y),sz:.06,color:cream});c.draw('claw','box',{x:0,y:hand.y,z:0,sx:.8,sy:.3,sz:.5,color:cream});label(c,'order','주문',-6,2,0,3);c.draw('wanted','sphere',{x:-3.5,y:2,z:0,sx:1.2,sy:.7,sz:.6,color:colors[wanted]});},timeout(){c.complete([],'주문한 물고기를 잡지 못했습니다');}};
}
function rodeo(c){
 active(c);c.limit=10;let need=c.int(0,2),age=0,answered=false,miss=0,flash=0;c.players[0].x=c.players[0].z=0;const p=c.players[0];p.lag=c.rand(.2,.38);p.error=.08;
 function answer(ok){answered=true;flash=.25;if(ok){miss=0;c.points(p);}else{miss++;if(miss>=2)c.complete([],'두 번 연속으로 균형 입력을 놓쳤습니다');}}
 return{update(dt){age+=dt;flash=Math.max(0,flash-dt);c.hint('표시된 C(L)·D(R)·B를 누르기 / 연속 두 번 실수하면 실패 / 10초 버티기');const q=c.input(p,()=>age>p.lag&&!answered?{[['c','d','b'][need]]:true}:{}),pressed=['cp','dp','bp'].flatMap((k,i)=>q[k]?[i]:[]);if(!answered&&pressed.length)answer(pressed.length===1&&pressed[0]===need);if(!answered&&age>.78)answer(false);if(age>=1){age=0;answered=false;need=c.int(0,2);p.lag=c.rand(.18,.42);}p.x=Math.sin(c.time*8)*.2;p.y=1.1+Math.abs(Math.sin(c.time*5))*.25;p.rotation=Math.sin(c.time*4)*.2;},render(){c.arena({width:15,depth:10,color:'#b9c4a2'});c.draw('bull','sphere',{x:0,y:.7,z:0,sx:3,sy:1.3,sz:1.5,color:'#9fb8b0',rz:Math.sin(c.time*5)*.15});label(c,'button',['C','D','B'][need],0,4,0,3);label(c,'miss',`연속 실수 ${miss}/2`,0,5.5,0,6);},timeout(){c.complete([0],'10초 동안 안장 위에서 버텼습니다');}};
}
function feed(c){
 active(c);c.limit=60;c.view={size:21,eye:[0,24,18],target:[0,0,0]};const slots=c.shuffle([1,1,1,2,0,0,0,0]);let angle=0,tries=0,tongue=null,cool=0;c.players[0].x=-7;c.players[0].z=0;
 return{update(dt){angle+=1.5*dt;cool=Math.max(0,cool-dt);const p=c.players[0],index=((Math.round((Math.PI-angle-1.5*.2)/TAU*8)%8)+8)%8,q=c.input(p,()=>({a:!cool&&!tongue&&slots[index]>0}));c.hint(`A 혀 내밀기 / 3번 안에 동전 2개 · 두 배 동전 있음 / 시도 ${tries}/3`);if(q.ap&&!cool&&!tongue){tongue={age:0,hit:false};tries++;}if(tongue){tongue.age+=dt;if(tongue.age>=.2&&!tongue.hit){tongue.hit=true;const hit=((Math.round((Math.PI-angle)/TAU*8)%8)+8)%8;c.points(p,slots[hit]);}if(tongue.age>.5){tongue=null;cool=.2;if(p.score>=2)c.complete([0],'세 번 안에 동전 두 개를 얻었습니다');else if(tries>=3)c.complete([],'세 번의 혀 내밀기에서 동전이 부족했습니다');}}},render(){c.arena({width:19,depth:13,color:'#a9c2a2'});c.draw('spinner','cylinder',{x:1,y:.05,z:0,sx:9,sy:.1,sz:9,color:'#c2bea1'});slots.forEach((value,i)=>{const a=angle+i*TAU/8,x=1+Math.cos(a)*3.8,z=Math.sin(a)*3.8;c.draw('slot'+i,value?'cylinder':'sphere',{x,y:.3,z,sx:.8,sy:value?.15:.7,sz:.8,color:value?'#e0c472':'#9b95b4'});if(value===2)label(c,'double','2',x,.9,z,1);});if(tongue)c.draw('tongue','box',{x:-5+tongue.age*3,y:.5,z:0,sx:Math.min(4,tongue.age*20),sy:.12,sz:.3,color:'#d697b3'});},timeout(){c.complete([],'동전 두 개를 얻지 못했습니다');}};
}
function mallet(c){
 active(c);c.limit=60;let phase='choose',target=2,done=0,age=0,enemy=null,cool=0,next=.6,flash=0;c.players[0].x=-2;c.players[0].z=0;const p=c.players[0];p.lag=c.rand(.17,.35);
 return{update(dt){age+=dt;cool=Math.max(0,cool-dt);flash=Math.max(0,flash-dt);c.hint(phase==='choose'?'숫자가 바뀔 때 A로 잡을 적 수 결정':'A 망치질 / 적만 때리고 초록 친구는 피하기 / 적을 오래 두면 실패');if(phase==='choose')target=2+Math.floor(c.time*8)%5;const q=c.input(p,()=>({a:phase==='choose'?age>.4:enemy?.kind==='enemy'&&enemy.age>p.lag&&!cool}));if(phase==='choose'){if(q.ap){phase='play';age=0;}return;}next-=dt;if(!enemy&&next<=0){enemy={kind:c.rand()<.23?'friend':'enemy',age:0};p.lag=c.rand(.14,.33);}if(enemy)enemy.age+=dt;if(q.ap&&!cool){cool=.3;flash=.2;if(enemy?.kind==='friend'){c.complete([],'친구를 망치로 때렸습니다');return;}if(enemy?.kind==='enemy'){done++;c.points(p);enemy=null;next=c.rand(.35,.65);if(done>=target)c.complete([0],'목표 수만큼 적을 막았습니다');}}if(enemy&&enemy.age>.9){if(enemy.kind==='enemy')c.complete([],'적을 제때 막지 못했습니다');else{enemy=null;next=.35;}}},render(){c.arena({width:16,depth:10,color:'#b7c2a2'});c.draw('pipe','cylinder',{x:1,y:.4,z:0,sx:2,sy:.8,sz:2,color:'#91b5a3'});if(enemy)c.draw('head','sphere',{x:1,y:1.1,z:0,sx:1.3,sy:1.3,sz:1.3,color:enemy.kind==='friend'?'#8cb69b':'#b89b81'});c.draw('hammer','box',{x:flash?0:-1,y:flash?1.4:2,z:0,sx:1.4,sy:.65,sz:.8,rz:flash?-.7:0,color:'#bca391'});label(c,'target',phase==='choose'?String(target):`${done} / ${target}`,0,4,0,4);},timeout(){c.complete([],'목표 수의 적을 막지 못했습니다');}};
}
const luckEffects=['버린 더미에서 아이템 1장 가져오기','버린 더미에서 아이템 2장 가져오기','버린 더미에서 아이템 3장 가져오기','버린 더미에서 동전 최대3장 가져오기','버린 더미에서 동전 최대5장 가져오기','내 사용 중 아이템 1장 버리기'];
const bowserEffects=['모두의 사용 중 동전 전부 버리기','모든 손패를 왼쪽 선수에게 전달','모든 손패를 오른쪽 선수에게 전달','모든 사용 중 카드를 왼쪽으로 전달','모든 사용 중 카드를 오른쪽으로 전달','다른 선수의 사용 중 아이템을 모두 가져오기'];
function roulette(c,evil=false){active(c);c.limit=45;let angle=c.rand(0,TAU),speed=c.rand(9,11),started=false;const effects=evil?bowserEffects:luckEffects;function result(){const index=((Math.floor((TAU-angle%TAU)/TAU*6)%6)+6)%6;c.complete([],'카드 효과: '+effects[index]);c.result.outcome='effect';c.result.effect=effects[index];}return{update(dt){c.hint('A를 반복해 회전판을 멈추기 / 독립 승패 없이 멈춘 칸의 카드 효과를 표시합니다');const q=c.input(c.players[0],()=>({a:c.time>1&&pulse(c.time,3.5)}));if(q.ap){started=true;speed=Math.max(0,speed-1.3);}if(started)speed=Math.max(0,speed-.4*dt);angle+=speed*dt;if(started&&speed===0)result();},render(){c.arena({width:18,depth:13,color:evil?'#b7a3b4':'#abc2af'});c.draw('wheel','cylinder',{x:0,y:.1,z:0,sx:9,sy:.2,sz:9,color:'#d6c299'});for(let i=0;i<6;i++){const a=angle+(i+.5)*TAU/6,x=Math.cos(a)*3.2,z=Math.sin(a)*3.2;c.draw('sector'+i,'sphere',{x,y:.4,z,sx:1.4,sy:.3,sz:1.4,color:['#b99aae','#99b7ca','#a2bc98','#d3b887','#b7afce','#bdbfaf'][i]});label(c,'number'+i,String(i+1),x,1,z,1);}c.draw('pointer','cone',{x:5,y:.4,z:0,sx:.7,sy:1.2,sz:.7,rz:Math.PI/2,color:cream});const index=((Math.floor((TAU-angle%TAU)/TAU*6)%6)+6)%6;label(c,'effect',effects[index],0,5,-4,14);},timeout:result};}
function timeBomb(c){
 active(c,true);c.limit=300;c.view={size:23,eye:[0,25,15],target:[0,0,0]};const board=c.shuffle(Array.from({length:16},(_,i)=>i+1));let turn=0,next=1,elapsed=0,left=0,pause=.5;c.players.slice(0,2).forEach(p=>{p.cell=0;p.repeat=0;p.x=-8;p.z=p.i?2:-2;});
 function finish(){if(turn===0){left=Math.max(.1,elapsed);turn=1;next=1;pause=.8;}else c.complete([1],'설정에 걸린 시간 안에 폭탄을 해체했습니다');}
 return{update(dt){const p=c.players[turn],index=board.indexOf(next),tx=index%4,tz=Math.floor(index/4);c.hint(`${turn+1}P · 방향키로 칸 선택, A 스위치 · 1부터16까지 순서대로 / 잘못 누르면 2초 손해`);const qs=c.players.slice(0,2).map(o=>c.input(o,()=>o.i===turn?{x:Math.sign(tx-o.cell%4),z:Math.sign(tz-Math.floor(o.cell/4)),a:o.cell===index&&pulse(c.time,4,o.phase)}:{}));if(pause){pause=Math.max(0,pause-dt);return;}if(turn===0)elapsed+=dt;else{left-=dt;if(left<=0){c.complete([0],'해체 전에 폭탄의 시간이 끝났습니다');return;}}p.repeat-=dt;const q=qs[turn];if(p.repeat<=0&&(Math.abs(q.x)>.4||Math.abs(q.z)>.4)){const x=p.cell%4,z=Math.floor(p.cell/4);p.cell=clamp(z+(Math.abs(q.z)>=Math.abs(q.x)?Math.sign(q.z):0),0,3)*4+clamp(x+(Math.abs(q.x)>Math.abs(q.z)?Math.sign(q.x):0),0,3);p.repeat=.15;}if(q.ap){if(board[p.cell]===next){p.score=next;next++;if(next===17)finish();}else if(turn===0)elapsed+=2;else left-=2;}},render(){c.arena({width:19,depth:15,color:'#adb8b7'});board.forEach((n,i)=>{const x=(i%4-1.5)*2,z=(Math.floor(i/4)-1.5)*2;c.draw('button'+i,'box',{x,y:.2,z,sx:1.8,sy:.4,sz:1.8,color:n<next?'#8db59e':'#cfb398'});label(c,'n'+i,String(n),x,.7,z,1.1);});const cell=c.players[turn].cell;c.draw('cursor','ring',{x:(cell%4-1.5)*2,y:.7,z:(Math.floor(cell/4)-1.5)*2,sx:2,sy:.12,sz:2,color:c.players[turn].color});label(c,'next',`다음 ${Math.min(16,next)} / ${turn===0?'설정 '+elapsed.toFixed(1):'남은 '+Math.max(0,left).toFixed(1)}초`,0,4,-5,11);},timeout(){c.complete(turn===1?[0]:[],'폭탄 경기 제한 시간 종료');}};
}
function reign(c){
 active(c,true);c.limit=65;let turn=0,age=0,pause=.5,objects=[];const schedule=Array.from({length:90},(_,i)=>({at:.5+i*.32,x:c.rand(-7,7),kind:i%6===0?'hammer':i%5===0?'red':'coin',speed:c.rand(5,8)}));let next=0;c.players.slice(0,2).forEach(p=>{p.x=0;p.z=0;p.visible=p.i===0;p.goal=0;p.skill=c.rand(.85,1.1);p.nextThink=0;p.steer=0;});c.view={size:23,eye:[0,5,25],target:[0,2,0]};
 function end(){if(turn===0){turn=1;age=0;pause=.6;objects=[];next=0;c.players[0].visible=false;c.players[1].visible=true;}else{const a=c.players[0].score,b=c.players[1].score;c.complete(a===b?[]:a>b?[0]:[1],'노란 동전 1점·빨간 동전 5점 합계 비교');}}
 return{update(dt){const p=c.players[turn];c.hint(`${turn+1}P 차례 · 좌우 이동으로 동전 받기 / 망치에 맞으면 차례 끝 / 빨간 동전 5점`);if(pause){c.players.slice(0,2).forEach(o=>c.input(o,{}));pause=Math.max(0,pause-dt);return;}age+=dt;while(next<schedule.length&&schedule[next].at<=age)objects.push({...schedule[next],id:next++,y:9});const hazard=objects.filter(o=>o.kind==='hammer'&&o.y<3&&Math.abs(o.x-p.x)<1.4).sort((a,b)=>a.y-b.y)[0],target=objects.filter(o=>o.kind!=='hammer'&&o.y>0).sort((a,b)=>(Math.abs(a.x-p.x)+a.y*.5-(a.kind==='red'?2:0))-(Math.abs(b.x-p.x)+b.y*.5-(b.kind==='red'?2:0)))[0];if(age>=p.nextThink){p.nextThink=age+c.rand(.08,.24)/p.skill;p.steer=hazard?Math.sign(p.x-hazard.x||1):Math.sign((target?.x??0)-p.x)*Math.min(1,Math.abs((target?.x??0)-p.x));}const q=c.players.slice(0,2).map(o=>c.input(o,()=>o.i===turn?{x:p.steer}:{}))[turn];p.x=clamp(p.x+q.x*7*dt,-7.8,7.8);let hit=false;for(const o of objects){const y=o.y;o.y-=o.speed*dt;if(y>=1&&o.y<1&&Math.abs(p.x-o.x)<.8){if(o.kind==='hammer')hit=true;else c.points(p,o.kind==='red'?5:1);o.gone=true;}}objects=objects.filter(o=>!o.gone&&o.y>-.5);if(hit||age>=30)end();},render(){c.arena({width:19,depth:8,color:'#bac2ad'});objects.forEach(o=>c.draw('drop'+o.id,o.kind==='hammer'?'box':'cylinder',{x:o.x,y:o.y,z:0,sx:o.kind==='hammer'?1.1:.65,sy:o.kind==='hammer'?.6:.15,sz:.65,color:o.kind==='hammer'?'#8792a4':o.kind==='red'?'#d67f88':'#e0c26d'}));label(c,'clock',`${turn+1}P ${Math.max(0,30-age).toFixed(1)}초`,0,10,0,6);},timeout(){if(turn===0)end();if(!c.ended)end();}};
}
function bluff(c){
 active(c,true);c.limit=125;c.view={size:25,eye:[0,6,30],target:[0,1,0]};let turn=0,age=0,pause=.5;const results=[];c.players.slice(0,2).forEach(p=>{p.d=0;p.speed=0;p.started=false;p.visible=p.i===0;p.goal=c.rand(47,49);p.x=-8;p.z=0;});
 function end(fell){results[turn]={fell,d:c.players[turn].d};if(turn===0){turn=1;age=0;pause=.8;c.players[0].visible=false;c.players[1].visible=true;}else{const a=results[0],b=results[1];c.complete(a.fell&&b.fell?[]:a.fell?[1]:b.fell?[0]:Math.abs(a.d-b.d)<.005?[]:a.d>b.d?[0]:[1],'절벽에서 떨어지지 않고 가장 가까이 멈추기');}}
 return{update(dt){const p=c.players[turn];c.hint(`${turn+1}P 차례 · A 가속 / B 제동 / 절벽을 넘으면 실패`);const q=c.players.slice(0,2).map(o=>c.input(o,()=>{const brake=o.d+o.speed*o.speed/12>=o.goal;return o.i===turn?{a:!brake,b:brake}:{};}))[turn];if(pause){pause=Math.max(0,pause-dt);return;}age+=dt;if(q.a){p.started=true;p.speed=Math.min(15,p.speed+5*dt);}if(q.b)p.speed=Math.max(0,p.speed-6*dt);else if(!q.a)p.speed=Math.max(0,p.speed-.3*dt);p.d+=p.speed*dt;p.x=-8+p.d/50*16;p.score=Math.max(0,Math.round(p.d*100)/100);if(p.d>=50){p.score=0;end(true);}else if(p.started&&p.speed<=.001&&age>.5)end(false);else if(age>=60)end(false);},render(){c.draw('cliff','box',{x:-2,y:-1,z:0,sx:20,sy:2,sz:8,color:'#b4bca7'});c.draw('edge','box',{x:8,y:.03,z:0,sx:.1,sy:.08,sz:8,color:'#e7bc82'});const p=c.players[turn];c.draw('kart','box',{x:p.x,y:.15,z:0,sx:1.3,sy:.3,sz:1,color:p.color});label(c,'distance',`남은 거리 ${(50-p.d).toFixed(1)}`,0,4,0,8);},timeout(){if(turn===0)end(false);if(!c.ended)end(false);}};
}
export const games={'Balloon Burst!':balloon,'Bolt from Boo':boo,'Cast Away Mario!':cast,"Daisy's Rodeo!":rodeo,'Fast Feed Yoshi!':feed,"Lakitu's Luck":c=>roulette(c),"Mario's Mallet":mallet,'Spinister Bowser':c=>roulette(c,true),'Time Bomb Ticks!':timeBomb,"Waluigi's Reign":reign,"Wario's Bluff":bluff};
export const supportedTitles=Object.fromEntries(Object.keys(games).map(n=>[n,['party-e']]));
export const aliases={};
const adapted='원작의 버튼 규칙을 키보드로 옮겼으며 3D 지형·장식·물리·컴퓨터 반응은 브라우저판에서 새로 만들었습니다. ';
export const notes={
 'Balloon Burst!':adapted+'두 선수가 교대로 A를 최대3초씩 눌러 공동 풍선을 키우고 터뜨린 쪽이 집니다. 공기량 폭발 임계값과120초 안전 제한은 브라우저판 수치입니다.',
 'Bolt from Boo':adapted+'설명서처럼 A 또는 B 반복으로 달리고 멈춰 유령을 물립니다. 순차 도전하며 탈출 시간이 빠른 쪽, 둘 다 못 나가면 더 멀리 간 쪽이 이깁니다. 코스 길이·속도·차례당60초는 브라우저판 값입니다.',
 'Cast Away Mario!':adapted+'A로 집게를 내려 주문한 종류를 잡습니다. 다른 종류를 건드리면 실패합니다. 물고기 종류는 자체 색·모양으로 표시하며 배치와60초 안전 제한을 새로 정했습니다.',
 "Daisy's Rodeo!":adapted+'원작 L/R/B를 C/D/B로 입력합니다. 10초를 버티면 성공, 연속 두 번 틀리거나 놓치면 실패합니다. 표시 간격과 입력 판정 창은 브라우저판 값입니다.',
 'Fast Feed Yoshi!':adapted+'A로 혀를 내밀어 세 번 안에 동전2개를 모읍니다. 두 배 동전도 있습니다. 회전 속도와 배치,60초 안전 제한은 브라우저판 수치입니다.',
 "Lakitu's Luck":adapted+'A로 룰렛을 감속합니다. 원작 여섯 카드 효과를 표시하는 기능이며 독립적인 승패나 카드 보유량은 만들지 않았습니다. 회전·감속 수치는 브라우저판 값입니다.',
 "Mario's Mallet":adapted+'깜박이는 숫자를 A로 선택한 뒤 그 수만큼 적을 때립니다. 친구를 때리거나 적을 오래 놓치면 실패합니다. 표시 숫자2~6, 반응 시간,60초 안전 제한은 브라우저판 수치입니다.',
 'Spinister Bowser':adapted+'A로 룰렛을 감속합니다. 원작 여섯 카드 효과를 표시하고 독립 승패나 카드 보유량은 만들지 않았습니다. 회전·감속 수치는 브라우저판 값입니다.',
 'Time Bomb Ticks!':adapted+'첫 선수의 1~16 스위치 설정 시간이 둘째 선수의 해체 제한 시간입니다. 방향키로 칸 선택 후 A. 두 선수에게 동일한 새 숫자 배치를 쓰며 오입력2초 벌점과300초 안전 제한은 브라우저판 수치입니다.',
 "Waluigi's Reign":adapted+'각자 차례에 노란 동전1점·빨간 동전5점을 받습니다. 망치에 맞거나 시간이 끝나면 교대하고 합계가 높은 쪽이 승리합니다. 양쪽에 같은 낙하 배치를 쓰며 차례당30초와 낙하 물리는 새로 정했습니다.',
 "Wario's Bluff":adapted+'A 가속·B 제동으로 절벽에 가깝게 멈춥니다. 추락하면 기록이 없고 유효 거리로 승부합니다. 가속·제동·코스 길이 및 차례당60초 안전 제한은 브라우저판 수치입니다.'
};
