import {games,categories} from './registry.js';
import {Session,neutral,medalFor,AudioBus} from './core.js';
import {W,H,C,rect,circle,line,text,bird} from './draw.js';
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const canvas=$('game-canvas'),ctx=canvas.getContext('2d'),audio=new AudioBus(),storageKey='flamingo-pocket.records.v1';
let records={},category='all',session=null,current=null,running=false,paused=false,handled=false,last=0,hudAt=0,previewGeneration=0,previousFocus=null;
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');for(const g of games){const r=saved?.[g.id];if(r&&Number.isFinite(r.best)&&Number.isFinite(r.plays))records[g.id]={best:r.best,plays:r.plays};}}catch{}
const keys=new Set(),touch=new Map(),edges={ap:false,ar:false,bp:false,br:false};let pointer={x:W/2,y:H/2,down:false,valid:false,pressed:false,released:false},pointerId=null;
const actions={left:['ArrowLeft','KeyA'],right:['ArrowRight','KeyD'],up:['ArrowUp','KeyW'],down:['ArrowDown','KeyS'],a:['Space','KeyQ','Enter'],b:['KeyE','ShiftLeft','ShiftRight']};
const pressed=action=>actions[action].some(k=>keys.has(k))||(touch.get(action)?.size||0)>0;
const stats=()=>{const played=games.filter(g=>records[g.id]).length,medals=games.filter(g=>medalFor(g,records[g.id]?.best)).length;$('collection-stats').innerHTML='<strong>'+games.length+'개의 작은 도전</strong><br>'+played+'개 플레이 · '+medals+'개 메달 획득';};
function filtered(){const q=$('search').value.trim().toLowerCase();return games.filter(g=>(category==='all'||g.category===category)&&[g.name,g.description,g.controls,g.inspiration,g.kicker].join(' ').toLowerCase().includes(q));}
function gallery(){stats();const list=filtered(),generation=++previewGeneration;$('empty').hidden=!!list.length;$('category-description').textContent=categories[category]?.description||'짧은 쉬는 시간에도, 한참 놀고 싶은 날에도. 마음에 드는 게임을 골라보세요.';$('cards').innerHTML=list.map(g=>{const medal=medalFor(g,records[g.id]?.best);return '<button class="game-card" data-game="'+escape(g.id)+'" aria-label="'+escape(g.name)+' 시작"><div class="card-preview" style="--card-color:'+escape(g.color||categories[g.category].color)+'"><canvas data-preview="'+escape(g.id)+'" width="450" height="300" aria-hidden="true"></canvas><span class="card-index">'+String(games.indexOf(g)+1).padStart(2,'0')+' / '+categories[g.category].en+'</span>'+(medal?'<span class="card-medal '+medal+'" aria-label="'+({gold:'금',silver:'은',bronze:'동'}[medal])+'메달">✳</span>':'')+'</div><div class="card-info"><span class="eyebrow">'+escape(g.kicker||categories[g.category].en)+'</span><h3>'+escape(g.name)+'</h3><p>'+escape(g.description)+'</p><div class="card-bottom"><span>'+(records[g.id]?'최고 기록 '+records[g.id].best:'새로운 한 판')+'</span><b aria-hidden="true">↗</b></div></div></button>';}).join('');let i=0;function batch(){if(generation!==previewGeneration)return;for(let n=0;n<4&&i<list.length;n++,i++){const g=list[i],c=document.querySelector('[data-preview="'+g.id+'"]');if(!c)continue;try{const preview=new Session(g,{seed:93});preview.step(0);const p=c.getContext('2d');p.save();p.scale(.5,.5);preview.game.draw(p);p.restore();}catch(e){console.error('Preview failed',g.id,e);}}if(i<list.length)requestAnimationFrame(batch);}requestAnimationFrame(batch);}
function clearInput(){if(session)session.previous=neutral();keys.clear();touch.clear();for(const k in edges)edges[k]=false;pointer={...pointer,down:false,valid:false,pressed:false,released:false};if(pointerId!==null){try{canvas.releasePointerCapture(pointerId);}catch{}}pointerId=null;document.querySelectorAll('[data-touch]').forEach(b=>b.classList.remove('pressed'));}
function input(){const r={x:Number(pressed('right'))-Number(pressed('left')),y:Number(pressed('down'))-Number(pressed('up')),a:pressed('a'),b:pressed('b'),...edges,pointer:{...pointer}};const pad=Array.from(navigator.getGamepads?.()||[]).find(Boolean);if(pad){if(Math.abs(pad.axes[0]||0)>.18)r.x=pad.axes[0];if(Math.abs(pad.axes[1]||0)>.18)r.y=pad.axes[1];r.a||=!!pad.buttons[0]?.pressed;r.b||=!!pad.buttons[1]?.pressed;}for(const k in edges)edges[k]=false;pointer.pressed=pointer.released=false;return r;}
function resize(){const r=canvas.getBoundingClientRect(),scale=Math.min(devicePixelRatio||1,2);const w=Math.max(1,Math.round(r.width*scale)),h=Math.max(1,Math.round(r.height*scale));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}draw();}
function draw(){if(!session)return;try{ctx.save();ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);ctx.clearRect(0,0,W,H);session.game.draw(ctx);ctx.restore();}catch(e){ctx.restore();fail(e);}}
function fail(e){running=false;console.error(e);$('game-error').hidden=false;}
function start(){if(!session||session.result)return;audio.start();clearInput();$('start-screen').hidden=true;running=true;paused=false;$('pause-screen').hidden=true;last=performance.now();canvas.focus({preventScroll:true});}
function setup(){running=false;paused=false;handled=false;clearInput();for(const id of ['result-screen','pause-screen','game-error'])$(id).hidden=true;$('start-screen').hidden=false;session=new Session(current,{seed:Date.now(),sound:kind=>audio.play(kind)});session.step(0,neutral());$('start-title').textContent=current.name;$('start-rules').textContent=current.description;$('start-controls').textContent=current.controls+'\nA = Space / Q · B = E · 방향 = WASD / 화살표';resize();hud();}
function openGame(id){const game=games.find(g=>g.id===id);if(!game)return;current=game;previousFocus=document.activeElement;$('game-title').textContent=game.name;$('game-category').textContent=categories[game.category].en+' / '+String(games.indexOf(game)+1).padStart(2,'0');$('full-controls').textContent='조작: '+game.controls;$('objective').textContent='목표: '+game.objective;$('adaptation').textContent=game.adaptation;$('source-link').textContent='참고: '+game.inspiration+' ↗';$('source-link').href=game.sourceUrl;if(!$('play').open)$('play').showModal();document.querySelector('.game-notes').open=false;try{setup();}catch(e){fail(e);}history.replaceState(null,'','?game='+encodeURIComponent(game.id));}
function closeGame(){running=false;paused=false;clearInput();$('play').close();history.replaceState(null,'',location.pathname);gallery();if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});}
function pause(value){if(!session||session.result||!$('start-screen').hidden)return;paused=value;$('pause-screen').hidden=!value;$('pause').setAttribute('aria-label',value?'계속하기':'일시정지');clearInput();last=performance.now();}
function showResult(){if(handled||!session?.result)return;handled=true;running=false;clearInput();const r=session.result,old=records[current.id],best=Math.max(old?.best??-Infinity,r.score),isBest=!old||r.score>old.best;records[current.id]={best,plays:(old?.plays||0)+1};try{localStorage.setItem(storageKey,JSON.stringify(records));}catch{}const medal=medalFor(current,r.score);$('result-medal').className='result-medal '+(medal||'');$('result-medal').textContent=medal?'✳':r.outcome==='clear'?'✓':'↻';$('result-kicker').textContent=medal?{gold:'GOLDEN FLAMINGO',silver:'SILVER FEATHER',bronze:'BRONZE BEAK'}[medal]:'ONE MORE ROUND?';$('result-title').textContent=r.outcome==='clear'?'도전 성공!':r.outcome==='fail'?'다음엔 할 수 있어요':'이번 한 판의 기록';$('result-score').textContent=r.score.toLocaleString('ko-KR');$('result-message').textContent=r.message;$('result-best').textContent=(isBest?'새로운 최고 기록! · ':'내 최고 기록 ')+best;$('result-screen').hidden=false;audio.play(r.outcome==='fail'?'bad':'win');stats();}
function hud(){if(!session)return;const h=session.hud();$('score').textContent=(Math.round(h.score*100)/100).toLocaleString('ko-KR');$('metric-label').textContent=h.label;$('metric-value').textContent=h.value;$('hint').textContent=h.hint;$('progress-track').hidden=h.progress===null;if(h.progress!==null)$('progress').style.width=h.progress*100+'%';if(session.result)showResult();}
function randomGame(){const list=filtered();const pool=list.length?list:games;const others=pool.filter(g=>g.id!==current?.id);openGame((others.length?others:pool)[Math.floor(Math.random()*(others.length||pool.length))].id);}
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000||0,1/30);last=now;if(!document.hidden&&$('play').open&&session){try{if(running&&!paused&&!session.result)session.step(dt,input());if(running&&!paused||!handled)draw();if(now-hudAt>80||session.result&&!handled){hudAt=now;hud();}}catch(e){fail(e);}}}
$('cards').addEventListener('click',e=>{const b=e.target.closest('[data-game]');if(b)openGame(b.dataset.game);});$('categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;for(const item of $('categories').children){item.classList.toggle('selected',item===b);item.setAttribute('aria-pressed',String(item===b));}gallery();});$('search').addEventListener('input',gallery);$('random-play').addEventListener('click',randomGame);$('start').addEventListener('click',start);$('exit').addEventListener('click',closeGame);$('pause').addEventListener('click',()=>pause(!paused));$('resume').addEventListener('click',()=>pause(false));$('replay').addEventListener('click',()=>{setup();start();});$('next').addEventListener('click',randomGame);$('mute').addEventListener('click',()=>{audio.muted=!audio.muted;$('mute').textContent=audio.muted?'×♪':'♪';$('mute').setAttribute('aria-label',audio.muted?'소리 켜기':'소리 끄기');if(!audio.muted)audio.start();});$('play').addEventListener('cancel',e=>{e.preventDefault();closeGame();});
window.addEventListener('keydown',e=>{if(!$('play').open)return;if(e.code==='KeyP'&&!e.repeat){e.preventDefault();pause(!paused);return;}const action=Object.keys(actions).find(k=>actions[k].includes(e.code));if(!action||!running||paused)return;const control=e.target.closest?.('button,a,input,select,textarea');if((e.code==='Space'||e.code==='Enter')&&control&&!control.matches('[data-touch]'))return;e.preventDefault();if(!pointer.down)pointer.valid=false;const was=pressed(action);keys.add(e.code);if((action==='a'||action==='b')&&!was&&!e.repeat)edges[action+'p']=true;});window.addEventListener('keyup',e=>{const action=Object.keys(actions).find(k=>actions[k].includes(e.code)),was=action&&pressed(action);keys.delete(e.code);if((action==='a'||action==='b')&&was&&!pressed(action))edges[action+'r']=true;});window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});
function pointerPosition(e){const r=canvas.getBoundingClientRect();pointer.x=Math.max(0,Math.min(W,(e.clientX-r.left)/r.width*W));pointer.y=Math.max(0,Math.min(H,(e.clientY-r.top)/r.height*H));pointer.valid=true;}
canvas.addEventListener('pointerdown',e=>{if(!running||paused||pointerId!==null||e.button>0)return;e.preventDefault();pointerId=e.pointerId;canvas.setPointerCapture(e.pointerId);pointerPosition(e);pointer.down=true;pointer.pressed=true;});canvas.addEventListener('pointermove',e=>{if(pointerId===null||pointerId===e.pointerId)pointerPosition(e);});canvas.addEventListener('pointerleave',()=>{if(!pointer.down&&!pointer.pressed&&!pointer.released)pointer.valid=false;});canvas.addEventListener('pointerup',e=>{if(pointerId!==e.pointerId)return;pointerPosition(e);pointer.down=false;pointer.released=true;pointerId=null;});for(const name of ['pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>{if(pointerId!==e.pointerId)return;pointerId=null;pause(true);});
for(const b of document.querySelectorAll('[data-touch]')){const action=b.dataset.touch;b.addEventListener('pointerdown',e=>{if(!running||paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);const was=pressed(action);if(!touch.has(action))touch.set(action,new Set());touch.get(action).add(e.pointerId);if((action==='a'||action==='b')&&!was)edges[action+'p']=true;if(!pointer.down)pointer.valid=false;b.classList.add('pressed');});b.addEventListener('pointerup',e=>{const was=pressed(action);touch.get(action)?.delete(e.pointerId);if((action==='a'||action==='b')&&was&&!pressed(action))edges[action+'r']=true;if(!touch.get(action)?.size)b.classList.remove('pressed');});for(const type of ['pointercancel','lostpointercapture'])b.addEventListener(type,e=>{if(touch.get(action)?.has(e.pointerId))pause(true);});}
function hero(){const c=$('hero-canvas'),g=c.getContext('2d');g.clearRect(0,0,630,570);g.save();g.translate(315,284);g.rotate(-.095);g.fillStyle='#233c3717';g.beginPath();g.ellipse(0,232,210,25,0,0,Math.PI*2);g.fill();rect(g,-208,-213,425,462,C.ink,44);rect(g,-218,-226,425,462,'#e9afaf',44,C.ink);rect(g,-187,-194,364,270,C.ink,22);rect(g,-171,-177,331,234,'#dce4c6',12);circle(g,112,-139,19,C.gold);for(let i=0;i<3;i++){g.fillStyle='#ffffff77';g.beginPath();g.ellipse(-92+i*83,-140+(i%2)*25,30,8,0,0,Math.PI*2);g.fill();}rect(g,-171,-17,331,74,C.mint,0);for(let i=0;i<4;i++)line(g,-171,6+i*12,160,6+i*12,'#fff7df70',1);bird(g,-41,28,115,{pose:'jump'});circle(g,77,14,19,C.gold,C.ink);text(g,'1',77,16,20,C.ink);text(g,'POCKET CLUB',-7,105,14,C.ink,'center',900);rect(g,-154,157,86,28,C.ink,7);rect(g,-125,128,28,86,C.ink,7);circle(g,75,167,27,C.ink);circle(g,112,132,27,C.ink);circle(g,73,162,24,C.gold,C.ink);circle(g,110,127,24,C.rose,C.ink);text(g,'A',73,163,17,C.ink);text(g,'B',110,128,17,C.cream);rect(g,-33,187,33,7,'#ab747e',4);rect(g,12,187,33,7,'#ab747e',4);g.restore();g.save();g.translate(78,90);g.rotate(-.18);rect(g,-30,-15,112,36,C.cream,5,C.ink);text(g,'INSERT FUN',26,4,10,C.ink);g.restore();circle(g,550,420,26,C.mint,C.ink);text(g,'✳',550,422,38,C.ink);}
new ResizeObserver(resize).observe(canvas);window.__pocket={games:games.map(({create,...g})=>g),get session(){return session;},get current(){return current;},get paused(){return paused;},open:openGame,advance(seconds,bot=false){if(!session)return;for(let i=0;i<seconds*60&&!session.result;i++)session.step(1/60,bot?session.game.bot():input());draw();hud();return session.result;}};
try{gallery();hero();$('sources').innerHTML=games.map(g=>'<div class="source-row"><b>'+escape(g.name)+'</b> · <a href="'+escape(g.sourceUrl)+'" target="_blank" rel="noopener">'+escape(g.inspiration)+' ↗</a><small>'+escape(g.adaptation)+'</small></div>').join('');const id=new URLSearchParams(location.search).get('game');if(id)openGame(id);requestAnimationFrame(animate);}catch(e){$('load-error').hidden=false;console.error(e);}
