export const W=900,H=600;
export const C={ink:'#233c37',pink:'#f27ca0',rose:'#c94f78',cream:'#fff7df',mint:'#a7c6ad',teal:'#4e857b',blue:'#8cbbce',gold:'#e7b650',red:'#d26b59',white:'#fffdf4'};
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const lerp=(a,b,t)=>a+(b-a)*t;
export const distance=(x1,y1,x2,y2)=>Math.hypot(x2-x1,y2-y1);
export const hit=(p,x,y,w,h)=>!!p?.valid&&p.x>=x&&p.x<=x+w&&p.y>=y&&p.y<=y+h;
export function circle(g,x,y,r,fill,stroke,lineWidth=2){g.beginPath();g.arc(x,y,Math.max(0,r),0,Math.PI*2);if(fill){g.fillStyle=fill;g.fill();}if(stroke){g.strokeStyle=stroke;g.lineWidth=lineWidth;g.stroke();}}
export function rect(g,x,y,w,h,fill,radius=0,stroke){g.beginPath();if(radius&&g.roundRect)g.roundRect(x,y,w,h,Math.min(Math.abs(w)/2,Math.abs(h)/2,radius));else g.rect(x,y,w,h);if(fill){g.fillStyle=fill;g.fill();}if(stroke){g.strokeStyle=stroke;g.lineWidth=2;g.stroke();}}
export function line(g,x1,y1,x2,y2,color,width=3){g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.strokeStyle=color;g.lineWidth=width;g.lineCap='round';g.stroke();}
export function text(g,label,x,y,size=24,color=C.ink,align='center',weight=800){g.fillStyle=color;g.font=weight+' '+size+'px system-ui, sans-serif';g.textAlign=align;g.textBaseline='middle';g.fillText(String(label),x,y);}
export function bird(g,x,y,size=50,{color=C.pink,flip=false,pose='idle',rotation=0}={}){g.save();g.translate(x,y);g.rotate(rotation);g.scale((flip?-1:1)*size/100,size/100);const hop=pose==='jump'||pose==='fly';line(g,-9,-36,-10,hop?-8:0,C.rose,4);line(g,3,-35,hop?17:10,hop?-10:-4,C.rose,4);line(g,-10,hop?-8:0,3,hop?-8:0,C.rose,4);line(g,10,-4,23,-4,C.rose,4);g.fillStyle=color;g.beginPath();g.ellipse(-8,-48,27,17,-.08,0,Math.PI*2);g.fill();g.strokeStyle=color;g.lineWidth=12;g.lineCap='round';g.beginPath();g.moveTo(11,-47);g.bezierCurveTo(33,-66,1,-71,14,-86);g.bezierCurveTo(20,-98,38,-95,40,-88);g.stroke();circle(g,35,-88,10,color);g.fillStyle=C.cream;g.beginPath();g.moveTo(40,-88);g.lineTo(57,-82);g.lineTo(51,-73);g.lineTo(41,-79);g.closePath();g.fill();g.fillStyle=C.ink;g.beginPath();g.moveTo(52,-84);g.lineTo(60,-81);g.lineTo(52,-72);g.lineTo(49,-76);g.closePath();g.fill();circle(g,37,-91,2.3,C.ink);g.fillStyle=C.rose;g.globalAlpha=.5;g.beginPath();g.ellipse(-9,pose==='fly'?-59:-48,17,8,pose==='fly'?-.8:.1,0,Math.PI*2);g.fill();g.globalAlpha=1;g.restore();}
export function bg(g,{sky=C.cream,ground=C.mint,groundY=430}={}){g.fillStyle=sky;g.fillRect(0,0,W,H);if(groundY<H){g.fillStyle=ground;g.fillRect(0,groundY,W,H-groundY);}g.save();g.globalAlpha=.22;circle(g,760,92,44,C.gold);g.restore();}
export function button(g,label,x,y,w,h,{active=false,color=C.teal}={}){rect(g,x,y+4,w,h,C.ink,12);rect(g,x,y,w,h,active?C.gold:color,12,C.ink);text(g,label,x+w/2,y+h/2,Math.min(24,h*.43),active?C.ink:C.white);}
