import {Session,COLORS} from './core.js';
import {View} from './view.js';
import {PartyAudio} from './audio.js';
const audio=new PartyAudio();let resultSounded=false;
import {games,getGame,getNotes} from './registry.js';
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>String(s).toLowerCase().replace(/[^a-z0-9]/g,'');

let catalog,all=[],selectedTitle='all',status='ready',current,session,view,hero,heroSession,running=false,paused=false,last=0,lastHud=0;
const keys=new Set(),touch=new Set();
const mappings=[{up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD',a:'KeyQ',b:'KeyE',c:'KeyR',d:'KeyF'},{up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',a:'Enter',b:'ShiftRight',c:'Slash',d:'Period'},{up:'KeyI',down:'KeyK',left:'KeyJ',right:'KeyL',a:'KeyU',b:'KeyO',c:'KeyP',d:'Semicolon'},{up:'Numpad8',down:'Numpad2',left:'Numpad4',right:'Numpad6',a:'Numpad0',b:'Numpad1',c:'Numpad3',d:'Numpad5'}];
const keyLabels=['W A S D · Q / E / R / F','↑ ← ↓ → · Enter / 오른쪽 Shift / / / .','I J K L · U / O / P / ;','숫자패드 8 4 2 6 · 0 / 1 / 3 / 5'];
const patterns=['◆','III','↗','◉','≋','✳','01','✦','◎','★'];
const themes=['#c1d7b9','#edc7b9','#bfd9de','#e5d7ad','#d8c6d7','#bcd5c8'];
function factory(g){return getGame(g);}
function available(g){return !!factory(g);}
function shortTitle(t){if(t.id==='jamboree-tv')return 'Jamboree TV (확장)';return t.name.replace('Mario Party: ','MP: ').replace('Mario Party ','MP ').replace('Super Mario Party','Super MP');}
function render(){
 const ready=all.filter(available).length,unique=new Set(all.filter(available).map(g=>normalize(g.originalName))).size;
 $('totals').innerHTML=`<strong>${catalog.titles.length} 컬렉션 · ${all.length}개 선정</strong><br>${ready}개 수록 항목 플레이 가능 · 고유 규칙 ${unique}종`;
 $('series').innerHTML=[{id:'all',name:'전체 작품',selected:all},...catalog.titles].map(t=>`<button data-title="${escape(t.id)}" class="${selectedTitle===t.id?'selected':''}"><span>${escape(t.id==='all'?t.name:shortTitle(t))}</span><small>${t.selected.filter(available).length} / ${t.selected.length}</small></button>`).join('');
 const title=catalog.titles.find(t=>t.id===selectedTitle),term=$('search').value.trim().toLowerCase();
 const filtered=all.filter(g=>(selectedTitle==='all'||g.titleId===selectedTitle)&&(status==='all'||available(g))&&[g.originalName,g.parodyNameKo,g.mechanic,g.titleName].join(' ').toLowerCase().includes(term));
 $('series-description').textContent=title?`${title.name} · ${title.year} · ${title.platform} — ${title.selected.length}개 선정. 조작의 재미, 전략, 역할과 규칙의 다양성을 기준으로 골랐습니다.`:status==='ready'?'지금 바로 한 판. 같은 원작 게임이 여러 작품에 재수록된 경우 수록 항목과 고유 게임 수를 구분합니다.':'작품별 선정표입니다. 규칙 조사만 끝난 항목은 제작 대기 상태이며 아직 실행할 수 없습니다.';
 $('cards').innerHTML=filtered.map((g,i)=>`<button class="card" data-game="${escape(g.id)}" aria-label="${escape(g.parodyNameKo)} ${available(g)?'플레이':'규칙 보기'}"><div class="card-art" style="--card-bg:${themes[(g.titleIndex+i)%themes.length]}"><span class="card-number">${String(g.index+1).padStart(2,'0')}</span><span class="card-format">${escape(g.format.toUpperCase())}</span><span class="card-symbol" aria-hidden="true">${patterns[(g.index+g.titleIndex)%patterns.length]}</span><span class="card-lines"></span></div><div class="card-content"><div class="card-origin">${escape(g.titleName.toUpperCase())}</div><h3>${escape(g.parodyNameKo)}</h3><p>${escape(g.mechanic)}</p><div class="card-bottom"><span class="${available(g)?'ready-label':'pending-label'}">${available(g)?'● 3D PLAY':'○ 제작 대기'}</span><span>${available(g)?'플레이':'규칙 보기'} ↗</span></div></div></button>`).join('');$('empty').hidden=filtered.length>0;
}
function showDetails(g){const note=getNotes(g);$('detail-content').innerHTML=`<span class="eyebrow">${escape(g.titleName)} / ${String(g.index+1).padStart(2,'0')}</span><h2>${escape(g.parodyNameKo)}</h2><p>${escape(g.originalName)}</p><h4>규칙</h4><p>${escape(g.mechanic)}</p><h4>승리 조건</h4><p>${escape(g.winCondition)}</p><h4>원작 조작</h4><p>${escape(g.controls)}</p><p class="note">${available(g)?escape(note||'경기장·배치·캐릭터는 새로 제작했습니다. 방향과 동작 버튼으로 조작합니다.'):'규칙 조사를 마쳤습니다. 3D 게임 제작과 검증이 끝나면 플레이할 수 있습니다.'}</p><a class="source" href="${escape(g.sourceUrl)}" target="_blank" rel="noopener">원작 규칙 출처 ↗</a>${available(g)?'<button class="primary" id="detail-play">게임 시작 ↗</button>':''}`;$('details').showModal();$('detail-play')?.addEventListener('click',()=>{$('details').close();openGame(g);});}
function clearInput(){keys.clear();touch.clear();}
function getInputs(){const pads=Array.from(navigator.getGamepads?.()||[]).filter(Boolean);return mappings.map((m,i)=>{const pressed=k=>keys.has(m[k])||(i===0&&touch.has(k));const v={x:Number(pressed('right'))-Number(pressed('left')),z:Number(pressed('down'))-Number(pressed('up')),a:pressed('a'),b:pressed('b'),c:pressed('c'),d:pressed('d')};const pad=pads[i];if(pad){v.x=Math.abs(pad.axes[0]||0)>.15?pad.axes[0]:v.x;v.z=Math.abs(pad.axes[1]||0)>.15?pad.axes[1]:v.z;for(const [j,k]of['a','b','c','d'].entries())v[k]||=pad.buttons[j]?.pressed;}return v;});}
function configure(){clearInput();resultSounded=false;audio.lastScore=-1;running=false;paused=false;$('result-screen').hidden=true;$('pause-screen').hidden=true;$('start-screen').hidden=false;view.clear();const seed=Date.now();session=new Session(factory(current),current,{humans:Math.min(current.format==='solo'?1:current.format==='duel'?2:4,Number($('humans').value)),seed,draw:view.draw});if(!session.activePlayers&&current.format==='solo'&&session.players.slice(1).every(p=>p.visible===false))session.activePlayers=[0];if(!session.activePlayers&&current.format==='duel'&&session.players.slice(2).every(p=>p.visible===false))session.activePlayers=[0,1];view.begin();session.step(0,Array.from({length:4},()=>({})));view.render(session);$('start-title').textContent=current.parodyNameKo;$('start-rules').textContent=current.mechanic;$('start-controls').textContent=`${current.winCondition} · 1P: WASD 이동, Q/E/R/F = A/B/C/D`;hud();window.__party={session,current,games:all.filter(available).map(g=>g.id),open:id=>{const g=all.find(g=>g.id===id);if(g&&available(g))openGame(g);},advance:seconds=>{for(let i=0;i<seconds*60&&!session.ended;i++){view.begin();session.step(1/60,getInputs());}view.render(session);hud();return session.result;}};}
function openGame(g){if(!available(g))return showDetails(g);current=g;$('game-title').textContent=g.parodyNameKo;$('game-origin').textContent=`${g.titleName} / ${g.originalName}`;$('rules').textContent=g.mechanic;$('win').textContent=g.winCondition;$('adaptation').textContent=getNotes(g)||'원작의 방향·동작을 키보드/게임패드로 입력합니다. 경기장과 배치는 새로 제작했습니다.';$('source-link').href=g.sourceUrl;$('key-guide').innerHTML=keyLabels.slice(0,Math.min(g.format==='solo'?1:g.format==='duel'?2:4,Number($('humans').value))).map((v,i)=>`<span class="keys"><b style="color:${COLORS[i]}">${i+1}P</b> ${escape(v)}</span>`).join('')+'<span class="keys">동작 버튼 순서: A / B / C / D</span><span class="keys">게임패드: 왼쪽 스틱 + 아래/오른쪽/왼쪽/위 버튼</span>';
 if(!$('play').open)$('play').showModal();try{if(!view)view=new View($('game-canvas'));configure();$('webgl-error').hidden=true;}catch(error){console.error(error);$('webgl-error').hidden=false;}$('game-canvas').focus();history.replaceState(null,'',`?game=${encodeURIComponent(g.id)}`);}
function hud(){if(!session)return;$('timer').textContent=Number.isFinite(session.limit)?`${Math.max(0,Math.ceil(session.limit-session.time))} s`:'∞';$('hint').textContent=session.message;$('scoreboard').innerHTML=session.players.filter(p=>!session.activePlayers||session.activePlayers.includes(p.i)).map(p=>`<span class="score ${p.alive?'':'out'}" style="--player:${p.color}">${p.i+1}P ${p.i>=session.humans?'CPU ':''}· ${Math.round(p.score*100)/100}</span>`).join('');if(session.ended){running=false;if(!resultSounded){audio.finish(session.result.winners.length>0);resultSounded=true;}const winners=session.result.winners;$('result-title').textContent=session.activePlayers?.length===1?(winners.length?'도전 성공!':'다시 도전!'):winners.length===0?'무승부':winners.length===4?'모두 성공!':winners.map(i=>`${i+1}P`).join(' & ')+' 승리!';$('result-reason').textContent=session.result.reason;$('result-screen').hidden=false;}}
function closeGame(){$('play').close();running=false;clearInput();history.replaceState(null,'',location.pathname);}
function quick(){const pool=all.filter(g=>available(g)&&(selectedTitle==='all'||g.titleId===selectedTitle));if(pool.length)openGame(pool[Math.floor(Math.random()*pool.length)]);else{status='all';document.querySelectorAll('[data-status]').forEach(b=>b.classList.toggle('selected',b.dataset.status===status));render();$('collection').scrollIntoView({behavior:'smooth'});}}
function pause(value){if(!session||session.ended||!$('start-screen').hidden)return;paused=value;$('pause-screen').hidden=!value;clearInput();}
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.033,(now-last)/1000||0);last=now;if(document.hidden)return;if(hero&&heroSession&&!$('play').open){hero.begin();heroSession.step(dt);hero.render(heroSession);}if(view&&session&&$('play').open){if(running&&!paused&&!session.ended){view.begin();session.step(dt,getInputs());audio.consume(session.events);}view.render(session);if(now-lastHud>100){hud();lastHud=now;}}}
function initHero(){try{hero=new View($('hero-canvas'));heroSession=new Session(c=>{c.limit=1e9;c.view={size:12,eye:[10,11,15],target:[0,.5,0]};return{update(){c.arena({shape:'cylinder',width:11,depth:11,height:1,color:'#7bac87'});c.draw('rim','ring',{y:.04,sx:11,sy:11,sz:1,rx:-Math.PI/2,color:'#e3cb91'});c.draw('podium','cylinder',{x:0,y:.3,z:0,sx:3,sy:.6,sz:3,color:'#e69d88'});c.players.forEach((p,i)=>{const angle=i*Math.PI/2+c.time*.15;p.x=Math.cos(angle)*3.3;p.z=Math.sin(angle)*3.3;p.rotation=-angle-Math.PI/2;p.pose='run';p.scale=1.1;p.y=Math.max(0,Math.sin(c.time*2+i)*.35);});for(let i=0;i<7;i++)c.draw('confetti'+i,'box',{x:Math.sin(i*3.1)*4.3,y:3.5+Math.sin(c.time+i)*.3,z:Math.cos(i*2.7)*4.3,sx:.15,sy:.3,sz:.07,rz:c.time+i,color:COLORS[i%4]});}};},{},{humans:0,draw:hero.draw});}catch(error){console.warn('Hero WebGL unavailable',error);$('hero-canvas').style.background='#c1d7b9';}}
$('cards').addEventListener('click',e=>{const b=e.target.closest('[data-game]');if(b){const g=all.find(g=>g.id===b.dataset.game);available(g)?openGame(g):showDetails(g);}});$('series').addEventListener('click',e=>{const b=e.target.closest('[data-title]');if(b){selectedTitle=b.dataset.title;render();}});$('status-filter').addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(b){status=b.dataset.status;for(const v of $('status-filter').children)v.classList.toggle('selected',v===b);render();}});$('search').addEventListener('input',render);$('quick-play').addEventListener('click',quick);$('next-game').addEventListener('click',quick);$('exit-game').addEventListener('click',closeGame);$('mute-game').addEventListener('click',()=>{audio.muted=!audio.muted;$('mute-game').textContent=audio.muted?'소리 꺼짐':'소리 켜짐';$('mute-game').setAttribute('aria-label',audio.muted?'소리 켜기':'소리 끄기');if(!audio.muted)audio.start();});$('start-game').addEventListener('click',()=>{audio.start();$('start-screen').hidden=true;running=true;clearInput();$('game-canvas').focus();});$('replay').addEventListener('click',configure);$('pause-game').addEventListener('click',()=>pause(!paused));$('resume').addEventListener('click',()=>pause(false));$('play').addEventListener('cancel',e=>{e.preventDefault();closeGame();});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
window.addEventListener('keydown',e=>{if(!$('play').open)return;if(e.code==='Escape')return;if(mappings.some(m=>Object.values(m).includes(e.code))||e.code==='Space')e.preventDefault();if(e.code==='Space'&&!e.repeat){if(!$('start-screen').hidden)$('start-game').click();else pause(!paused);}keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});
for(const b of document.querySelectorAll('[data-touch]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch.add(b.dataset.touch);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>{e.preventDefault();touch.delete(b.dataset.touch);});}
try{catalog=await fetch('./catalog.json').then(r=>{if(!r.ok)throw new Error('Catalog unavailable');return r.json();});catalog.titles.forEach((t,ti)=>t.selected.forEach((g,i)=>{Object.assign(g,{titleId:t.id,titleName:t.name,titleIndex:ti,index:i,id:`${t.id}-${normalize(g.originalName)}`});all.push(g);}));render();$('scope-notes').innerHTML=`<p>${escape(catalog.selectionMethod)}</p>`+(catalog.exceptions||[]).map(e=>`<article><h4>${escape(e.title)}</h4><p>${escape(e.reason)}</p>${(e.sources||[]).map((u,i)=>`<a href="${escape(u)}" target="_blank" rel="noopener">출처 ${i+1} ↗</a>`).join(' · ')}</article>`).join('');initHero();const id=new URLSearchParams(location.search).get('game');if(id){const g=all.find(g=>g.id===id);if(g)openGame(g);}requestAnimationFrame(animate);}catch(e){$('cards').textContent='컬렉션을 불러오지 못했습니다. 새로고침해 주세요.';console.error(e);}
